### ISSUE TITLE
Query error when using variables of type ID!

### ISSUE THREAD

**Issue by Flamage82** [ChilliCream/hotchocolate#1001]
**Describe the bug**
Query error in 10.0.0-rc.2 when passing a variable of type `ID!` with an int value:
`Variable "id" got invalid value.`

**To Reproduce**
My query:

```
query GetBankDepositQuery($id: ID!) {
  bankDeposit(id: $id) {
    id
  }
}
```
and the variables:
```
{
  "id": 1
}
```

**Expected behavior**
The query should succeed.

**Additional context**
I've traced the problem through the source and it appears to have been caused by commit https://github.com/ChilliCream/hotchocolate/commit/2854912fa35bde3edf82d45aee70a21d32b4a94e.  Previously, the method `EnsureClrTypeIsCorrect` in `VariableValueBuilder.cs` would convert the int variable to a string (which is the ClrType of IdType).  That logic has been removed and `CheckForInvalidValueType` is getting upset that an int isn't a valid value for type `NonNullType<IdType>`

**Comment by michaelstaib** [comment]
We fixed a behavior that would wrongly convert scalar values. 

In this case it is a bug since the input coercion rules allow id to be a string and an int. I will fix that with the next build.

**Comment by michaelstaib** [comment]
I we will wait for other bugs and make rc.3 sometime tonight.
