### ISSUE TITLE
Error when using an unregistered DataLoader is unintuitive

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#1006]
**Is your feature request related to a problem? Please describe.**
My scenario:
- wired-up a DataLoader using a marker interface, but only registered the concrete type with `AddDataLoader<T>()`
- Tried to inject the interface as a `[DataLoader]` in a resolver method
- Got an error about not having a single public constructor (https://github.com/ChilliCream/hotchocolate/blob/3e8348399f653b130f4830870eed20430dabe7b4/src/Core/Utilities/ActivatorHelper.cs#L72)

**Describe the solution you'd like**
I would expect an error message about the given type not being registered as a dataloader.

**Comment by michaelstaib** [comment]
I will refine that hand we will throw a better exception that explains better that the DataLoader cannot be bound. 

For 10.0.1 we have added a better exception to the activator.

**Comment by PascalSenn** [comment]
Closed as dataloader do not longer have to be registered
