### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1011]
# Client API

We have experimented quite a lot with a GraphQL client API. We looked at things like the GitHub OctoKit implementation and where highly inspired by it. In the end we decided to not pursue this idea any more since with it we are trying to emulate GraphQL with .Net which leads to awkward syntax constructions. With such an API the user would not only have to learn GraphQL but also our LINQ syntax and then try to figure out which LINQ construct would lead to a desired GraphQL syntax.

We also had a look at how JavaScript and in particular [Relay](https://relay.dev) does things. With Relay the fragment is front and center and describes the data that you want to consume as an object for your component.

The nice thing about JavaScript is that you have template literals. This is something we do not have in C#. It would be actually awesome to have something like this, since we could reinvent how you consume data in frameworks like Xamarin or Blazor.

So, the main thing here is that we have come to the following conclusions about the client API:

- We want to use GraphQL to write GraphQL.
- We want that everything compiles (including the GraphQL).
- We want strong types that generate from the queries.

## Using GraphQL to write GraphQL

The basic idea would be to use GraphQL files ending on the extension `.graphql`, instead of magic strings. Lets say we have the following project structure.

```
root
|-- Programm.cs
|-- Demo.csproj
```

We would create a new folder that shall contain our GraphQL client, in this folder we will add a small configuration like the following:

```json
{
    "servers": [
        { "MyCustomSchemaName": "http://localhost:5000" }
    ]
}
```

The config will hold all the GraphQL servers that we are dealing with, if there are more than one, the client will auto-stitch them together.

Next we will add the Hot Chocolate client package to our project.

The client will bring in local tooling as well as the core APIs. The local tooling will let me update the schema and on build we will compile the query files against the schema. Syntax errors would result in build errors.

We would initialize the schemas by doing something like:

```bash
dotnet graphql init
```

By then our folder structure would look like the following:

```
root
|-- Programm.cs
|-- Demo.csproj
|-- OurClient
     |-- config.json
     |-- MyCustomSchemaName.graphql
```

The next thing to do would be to add query document which is another GraphQL file. We will use fragments to control the type name structure.

```graphql
query GetUser($userId: ID!) {
    user(id:$userId) {
        ... User
    }
}

fragment User on User {
    name
}
```

When we compile the msbuild integration of our package will turn all the GraphQL query documents into C# code.

This can also be done by triggering our .Net tool manually:

```bash
dotnet graphql compile
```

```
root
|-- Programm.cs
|-- Demo.csproj
|-- OurClient
     |-- config.json
     |-- MyCustomSchemaName.graphql
     |-- Generated
          |-- User.cs
          |-- IClient.cs
          |-- ...
```

In order to not be completely confined by fragments we will add a couple of directives that can help you to name things.

```graphql
query GetUser($userId: ID!) {
    user(id:$userId) @type(name: "User") {
        name
    }
}

fragment User on User {
    name
}
```

The above would yield the same client like before.

## Everything Compiles

The compiler integration will ensure that not only the GraphQL will yield a generated client but also that the GraphQL is correct and validated against the schema. Syntax errors will occur in IDEs in the error list and can be clicked on to get to the exact position in the GraphQL document that caused the error.

## Generate from Query Documents

We will generate the clients from the query documents and not from the schema. We will still use the schema to generate but we will not generate all types for the schema. The query document define what types will be generated and how these types will be generated.

## Transport

We will abstract the transport into a separate package that will bring in support for subscriptions and batching and other transport features like `@defer`, `@stream` and paging or even persisted queries.

## Persisted Queries

We have to ensure that the compiled queries contain the hashes so that we can use persisted query features.

## Stitching

The client will handle auto-stitching of schemas this will allow users to write query documents that will fetch from multiple sources in one go with one client.

## Local Resolvers

We will allow users to add schema extension files that extend on the server schemas.

```graphql
extend type User {
    someExtraData: String! @localField
    someStitchedData_ @delegate(schema: "Someschema" path: "...")
}
```

Also with the extensions we will support the stitching directives.

We still have to explore how to define the local resolvers.

**Comment by michaelstaib** [comment]
@nigel-sampson would also be great to get feedback on this from you guys.

**Comment by michaelstaib** [comment]
Regarding the actual client generation. Query documents have a clear structure where a document can have multiple operations. Each operation has multiple parameters that can be passed in. So we would end up with something like:

```CSharp
public interface IMyCustomClient 
{
    Task<QueryResult<User>> GetUserAsync(string userId);
}
```

The question here could be if we want one such client per document or one client or one client per operation.

We could also look at this more abstract and allow for better control about execution where we have like an executor facade and pass in in something like a compiled operation:

```CSharp
public interface IQueryExecutor 
{
    Task<QueryResult<T>> ExecuteAsync(IOperation<T> operation);
}

public interface IBatchExecutor 
{
    Task<IQueryResult> ExecuteAsync(params Operation[] operations);
}
```

This could be used like the following:

```CSharp
var result = await executor.ExecuteAsync(new GetUserOperation("userId"));
var name = result.User.Name
```

**Comment by michaelstaib** [comment]
Regarding the abstract API, I think we should always have this for underneath:

```csharp
var result = await executor.ExecuteAsync(new GetUserOperation("userId"));
var name = result.User.Name
```

even if we have some kind of an aggregated interface like the following on top:

```csharp
public interface IMyCustomClient 
{
    Task<QueryResult<User>> GetUserAsync(string userId);
}
```

**Comment by michaelstaib** [comment]
# Extendability

## Middleware

We will have to client versions depending on how many features you want to have. If you pull in our `HotChocolate` package as well we will use a real schema on the client side.

This will have a size impact but will allow people to add client side middleware.

We will generate in this case a hooks allowing to intercept the schema builder.

```
public partial class SchemaSetup
{
    public void OnConfigure(ISchemaBuilder builder)
    {
        builder.Use(next => context => ...)
    }
}
```

The important thing here, if size matters leaving away the core package will change the client generation and reduce the overall size. This is important for things like blazor.

## Custom Scalars

We will have out of the box support for our scalars. These scalars can be replaced or extended with custom scalars.

If the client is using our core, then we will need to implement full scalars. If the client is not using the core that one can implement a reduced scalar interface that mainly handles the .net type serialization and deserialization.

Since the scalars might be implemented in the library for which we are generating the client we will use roslyn to parse the code for scalars and integrate those into the generation.

**Comment by michaelstaib** [comment]
# Custom Scalars

In order to define which scalar maps to which serializer we will add a directive `@type` that can be applied like follows:

```graphql
extend scalar CustomScalar @type(typeName: "Namespace.TypeName")
```

**Comment by OneCyrus** [comment]
sounds great to me! like we discussed this is probably the most transparent way for developers. there are just very small things i would like to add here:

## Schema Source

your proposal with the schema source like this is a good starting point. But we should already consider some more advanced things here. I know that for our projects this won't be enough to get started.

```
{
    "servers": [
        { "MyCustomSchemaName": "http://localhost:5000" }
    ]
}
```

### Authentication
The major problem for us would be that we can't access our schema without authentication. any idea how we could add custom code for authentication (e.g. OAuth2)? maybe the client would have some extensibility to add plugins for authentication.

### Local Schema
An alternative for authenticated schemas could be to have just local schemas as .graphql/.json file and do the fetching outside of the tooling. So an option to specify a schema as a local file would be great too.

## Client API
While the following API is already very helpful

```
var result = await executor.ExecuteAsync(new GetUserOperation("userId"));
var name = result.User.Name
```

how about an even more simplified API? Inspired by react hooks and the apollo client/graphql code gen.

Each graphql-query/mutation should be named uniquely. Then we could use those names for predefined methods on the generated client.

```
query GetUser($userId: ID!) {
    user(id:$userId) {
        name
    }
}
```

```
var result = await myGqlClient.GetUser("userId");
var name = result.User.Name
```

**Comment by michaelstaib** [comment]
@OneCyrus 

This is the underlying API that will allow you to take advantage of more advance features:

```csharp
var result = await executor.ExecuteAsync(new GetUserOperation("userId"));
var name = result.User.Name
```

This is the API on top for the every day use....

```csharp
public interface IMyCustomClient 
{
    Task<QueryResult<User>> GetUserAsync(string userId);
}
```

**Comment by michaelstaib** [comment]
@OneCyrus I agree with you about the config we have to add more cases like local schema files. First version will not have auth but will fallback to local file. But I can see that we could do something in that direction once we have something that we can build on.

**Comment by tunurgitr** [comment]
One question I had here was whether it makes sense to build the client separately or whether to _always_ treat the client as a wrapper around a stitching server.

@michaelstaib you had mentioned that you're moving towards merging the stitching server and regular server to use the same pipeline structures. Although the client might be slightly larger, it might simplify things to always have a client be essentially a stitching server. That way, instead of being bound to a specific way of initializing the schema (e.g. the proposed settings file), you can set it up in any of the ways you'd normally merge a client schema.

It seems like it might be more straightforward and easier to troubleshoot issues by making the client a wrapper combined with some special stitching middleware.  I can think of a number of advantages:

- We've already run into situations where we wished we had the stitching pipeline in the "regular" server, this would give you all the same pipeline benefits at the client too.
- Since it's all the same execution path/logic, and updates to the server would benefit the client and wouldn't have to be ported over.
- Middleware/directives could potentially be used by both/either the server or the client.
- The `@client` directive would essentially just be field middleware
- If we wanted to do something like [`@rest`](https://github.com/graphql-community/graphql-directive-rest) middleware, that could work out of the box on either the client or the server.
- Scalar definitions could potentially work the same way they do on the server, just using TypeConverters

And from a developer perspective, this makes things easier:
- I have one set of abstractions I need to know about
- If I know how the server middleware and stitching works, I already know almost everything about the client schema and execution.
- Troubleshooting is likely to be much easier...either it's in the shared layers or it's in the thin client-wrapper layer.

Maybe I'm oversimplifying things here, but it seems like it could be a huge win to not have the mental overhead of a whole separate set of abstractions.

**Comment by michaelstaib** [comment]
@tunurgitr 

We will have to have two versions for the client since I want to be able to target things like Blazor where size matters.

But if you opt for the full features then we will have the full GraphQL inside with all the features and the same stitching capabilities.

**Comment by michaelstaib** [comment]
OK, I have done some implementation... everything is still experimental. I am playing with something I call _pull-up_.

Lets say we have a query like the following:

```graphql
query getHero {
  hero @remove {
    ...Hero
  }
}

fragment Hero on Hero {
  name
  friends {
    ...Friend
  }
}

fragment Friend on CharacterConnection {
  nodes @remove {
    name
  }
}
```

Then we will get the following models:

```csharp
public interface IStarWarsClient
{
    Task<IQueryResult<IHero>> GetHeroAsync();
}

public interface IHero
{
    string Name { get; }
    IReadOnlyList<IFriend> Friends { get; }
}

public interface IFriend
{
    string Name { get; }
}

public class Hero
    : IHero
{
    public string Name { get; set; }
    public List<IFriend> Friends { get; } = new List<IFriend>();
    IReadOnlyList<IFriend> IHero.Friends => Friends;
}

public class Friend
    : IFriend
{
    public string Name { get; set; }
}
```

What we are doing with the generator and what is messing up my head :) is we pull up types when we have for instance just one fragment.

```graphql
hero {
    ...Hero
  }
```

In the above case hero does not specify anything, so the return type will be inferred from the fragment definition `Hero`.

The second thing is that we are introducing a directive `@remove` which will let you remove insignificant parts like paging structures. With `@remove` you can basically shift your fields one level up.
 
This lets us write our queries in a way that the generated client feels more natural in .net.

What do you guys think?

**Comment by tunurgitr** [comment]
1. The `@remove` directive seems perfect....even for other clients. I've seen other attempts to do this, but they all have serious issues (imho):
- https://github.com/chasingmaxwell/graphql-leveler
- https://github.com/APIs-guru/graphql-lodash 
- https://github.com/graphql/graphql-js/issues/297

It's a common request from frontend devs who don't love working with a ton of levels of destructuring. They'd use this all the time.

At first I was thinking that `@hoist` might be a better name than `@remove`, but now I'm wondering if it might make more sense to call it `@spread` since it sorta works like spreading an object onto another object in javascript. Maybe it's just me, but thinking about it that way makes the most sense to me if you're thinking in the context of the field you're putting the directive on ("you're 'spreading' this field onto its parent").  But `@hoist` makes the most sense if you're thinking about the inner fields ("inner fields are being hoisted up a level").

My main concern with `@remove` is that it sounds like it might do something more along the lines of `@skip`.

2. Your thoughts on the fragments make sense. Spreading a fragment onto a type with no additional selections shouldn't result in a new type.

**Comment by rstaib** [comment]
`@spread` sounds to me good as well. And maybe something like renaming a field in this context would also make sense. The the following example.

```graphql
query {
    hero @spread {
        id @rename(name: "heroId")
    }
}
```

Results in:

```json
{
    data: {
        heroId: "..."
    }
}
```

However what would be the expected outcome of the following example then.

```graphql
query {
    hero @spread {
        id @rename(name: "heroId")
        friends @spread {
            id
        }
    }
}
```

**Comment by rstaib** [comment]
Spreading an array or list would only work if there is no other field on the new level, right?

**Comment by michaelstaib** [comment]
@rstaib `@remove` will only work if there is only one field at the moment. If we would change that you are right.

**Comment by michaelstaib** [comment]
@rstaib 

you do not need rename since you have aliases in GraphQL.

```
query {
    hero @spread {
        heroId: id
    }
}
```

**Comment by michaelstaib** [comment]
Everybody in agreement for the new name `@spread`? I will amend the generator to use the new name today.

**Comment by tunurgitr** [comment]
> @rstaib `@spread` will only work if there is only one field at the moment. If we would change that you are right.

So, to be clear, you're saying you **can't** do:
```
query {
  hero @spread {
    ...Hero
  }
  greeting {
    hello
  }
}
```

I can see how that limitation would make implementation simpler and avoid some odd edge cases, but it feels like there could be a case to support `@spread` with multiple fields. Obviously you'd have to handle collisions (I think you'd want to throw rather than the normal JS behavior where things are overridden in a specific order, but I haven't completely thought through that).

I was trying to think through possible legitimate use cases, but so far every scenario I'm envisioning feels like it would be a bad way to build a query.  I guess if something comes up this could be considered as something that support could be added for.

**Comment by michaelstaib** [comment]
@tunurgitr We can remove this limitation later in the implementation. I put this in to have a faster path forward. I think we will go the full way once we have the base.

**Comment by rstaib** [comment]
I think @tunurgitr has a good point here. Throwing an error if a spread results in collisions is a good behavior in this particular case.

**Comment by frostshoxx** [comment]
Looks good so far! I'm excited to try it once it's ready :)

Question: would supporting for union-type deserialization be part of the MVP early on?

For example:

```
const typeDefs = gql`
  union Result = Book | Author

  type Book {
    title: String
  }

  type Author {
    name: String
  }

  type Query {
    search: [Result]
  }
`;
```
So here I have a union type result, which return either `Book` or `Author` .

```
{
  search(contains: "") {
    ... on Book {
      title
    }
    ... on Author {
      name
    }
  }
}
```

It would be nice if we could just the result to be either Book or Author in the same collection (e.g., something like  IReadOnyList<ResultUnionType>) when deserialize the raw return back to C# object.

**Comment by tunurgitr** [comment]
@frostshoxx @michaelstaib I think in that case I'd expect classes like this generated:
```
public interface IResult { }

public interface ISearchClient
{
    Task<IReadOnlyList<IResult>> SearchAsync(string contains);
}

public class Book : IResult {
  public string Title { get; set; }
}

public class Author : IResult {
  public string Name { get; set; }
}
```

**Comment by michaelstaib** [comment]
@frostshoxx 

Yes, I think we will have a prototype ready by the end of this week for the model generation. Meaning you will be able to throw any query at it and it should generate something.

@tunurgitr 

I was exactly going this direction :)

We are already starting to add test cases ...

https://github.com/ChilliCream/hotchocolate/blob/client_api/src/Client/Generators.Tests/DocumentVisitorTests.cs

This is the snapshot of a clean query with spreads:
https://github.com/ChilliCream/hotchocolate/blob/client_api/src/Client/Generators.Tests/__snapshots__/DocumentVisitorTests.Generate_Models_Spread_Query.graphql.snap

Where as this query is a simple query without fragments but with type collisions:
https://github.com/ChilliCream/hotchocolate/blob/client_api/src/Client/Generators.Tests/__snapshots__/DocumentVisitorTests.Generate_Models_Simple_Query.graphql.snap

I am currently getting multiple fragments to work ... The type mapping is more mocked at the moment. I will put in the client core tomorrow with IScalar serializers and enum support.

I hope that we have a finished model generator by end of next week ... then we will start on the deserialization part which will be tricky. We might write a very optimized json parser for it that is based on the UTF8 GraphQL Reader.

I might also get the compiler running by next week that will provide syntax and validation errors to the visual studio error window.

**Comment by michaelstaib** [comment]
Just as a little goody ... the code that we generate is perfectly formatted :) I hate those generators that just generate code that is unreadable. We are really looking that the indentations are correct so that the code feels handwritten.

**Comment by michaelstaib** [comment]
@tunurgitr  @rstaib 

I did a bit more implementation yesterday night and I think we can also spread lists.

Let me put out some things that will lead to errors first.

1. If the list is a scalar list and we put `@spread` on it, we will throw an exception.
   ```graphql
   {
     foo {
        # will lead to a compile error 
        scalarList @spread
     }
   }
   ```

2. If the field is a scalar it cannot be spread and will throw an exception
   ```graphql
   {
     foo {
        # will lead to a compile error 
        bar @spread
     }
   }
   ```

3. If we have collisions we will throw an error
   ```graphql
   {
     # will lead to a compile error 
     foo @spread {
        bar 
     }
     bar {
        foo
     }
   }
   ```

OK, now the cases that will work:

1. A simple object can be spread when.
   ```graphql
   {
     foo @spread {
        bar
        baz
     }
     qux {
       quux
     }
   }
   ```

2. If the field that is spread is a list of object then it can be spread and the spread fields become lists. This can be very useful if you for instance fetch all the usernames but really do not want a user object with just a name but rather really a list of usernames.
   ```graphql
   {
     users  @spread {
        username
     }
   }
   ```
   would become in c#
   
   ```CSharp
   public IReadOnlyList<string> Username { get; }
   ```
   
   In order to get a nice property name `Usernames` you can use an alias in the query.

**Comment by tunurgitr** [comment]
fwiw, for collision errors, I'd hope for something like:
`Unable to spread "Foo" selections onto "Query". Field "bar" is selected on both types. Alias one of those fields to continue.`

```gql
{
  # will lead to a compile error 
  foo @spread {
     bar 
  }
  bar {
     foo
  }
}
```

**Comment by michaelstaib** [comment]
I have started on the result parser. This is basically the part the reads from the response stream and creates from it the graph.

I am taking here a view clues from relay. In relay they do a lot at build time in order to speed things up at run time.

So, I will generate the JSON serializers based on Microsofts new System.Json.Text. This can end up being a lot of code but will be super fast with almost no allocations. 

Still, we will also to swap out the result parsers. So the transport and serialization is completely pluggable.

The parser functions within the generated parse look like the following:

```csharp
private static object ParseRoot(
    JsonElement parent,
    ReadOnlySpan<byte> field)
{
    if (parent.TryGetProperty(field, out JsonElement obj))
    {
        return new GetHero
        {
            Hero = DeserializeHero(obj, _hero)
        };
    }

    return null;
}
```

Even the field names are kept as bytes so that we do not need to create expensive UTF-16 strings.

The parser methods get more complex in the case of a union or in case of an interface.

**Comment by michaelstaib** [comment]
Once we have this in place I will put in transport abstractions and then we could have a go playing with it. We have not all the tooling in place so we can generate but there is no compilation at the moment and when there is an error we will just explode.

But I think with that we could checkout if we like how the clients work.

**Comment by michaelstaib** [comment]
Also the first preview will hoist single fragments but will not spread yet.

**Comment by michaelstaib** [comment]
@tunurgitr  @rstaib 

I have found an issue in the deserializer that I am not sure ho we we should handle it. First here is one of the result parser functions that one of the operation result parsers consist of:

```CSharp
private string ParseRootHero(
    JsonElement parent,
    ReadOnlySpan<byte> field)
{
    if (!parent.TryGetProperty(field, out JsonElement obj))
    {
        return null;
    }

    string type = obj.GetProperty(_typename).GetString();

    if (string.Equals(TypeName, "Droid", StringComparison.Ordinal)
    {
        var droid = new Droid();
        droid.Name = (string)DeserializeStringValue(obj, "name");
        droid.Friends = ParseRootHeroFriends(obj, "friends");
        return droid.
    }

    if (string.Equals(TypeName, "Human", StringComparison.Ordinal)
    {
        var human = new Human();
        human.Name = (string)DeserializeStringValue(obj, "name");
        human.Friends = ParseRootHeroFriends(obj, "friends");
        return human.
    }

    throw new NotSupportedException("Handle not exhausted objects");
}
```

First lets assume we have a field that has an interface return type and at the time when we generate the client it has two implementations to this interface `Droid` and `Human`. 

Now, the schema is updated and has now a new implementation `Starship`. The query would still be valid in GraphQL and return either just the interface fields or in the case of the union an empty object.

But how should we handle this case in CSharp? we do not have this type yet. The solutions that I come up with so far are:

1. throw a NotSupportedException
   This really would be bad, since we render a perfectly working client useless with one schema update.

2. Generate a default implementation like `UnknownCharacterType`
   This would result in unknown types whenever we are dealing with abstract types. These types would let the client still work and in C# one could choose to throw or ignore these objects. In the case of the interface the instances of this type would carry all fields that are selected.

Any of you has a better idea or prefers one of the two that I suggested. At the moment I think the latter one is the better solution since it gives the user of the client the ability to write defensive code for such cases.

The could would look like:

```CSharp
private string ParseRootHero(
    JsonElement parent,
    ReadOnlySpan<byte> field)
{
    if (!parent.TryGetProperty(field, out JsonElement obj))
    {
        return null;
    }

    string type = obj.GetProperty(_typename).GetString();

    if (string.Equals(TypeName, "Droid", StringComparison.Ordinal)
    {
        var droid = new Droid();
        droid.Name = (string)DeserializeStringValue(obj, "name");
        droid.Friends = ParseRootHeroFriends(obj, "friends");
        return droid.
    }

    if (string.Equals(TypeName, "Human", StringComparison.Ordinal)
    {
        var human = new Human();
        human.Name = (string)DeserializeStringValue(obj, "name");
        human.Friends = ParseRootHeroFriends(obj, "friends");
        return human.
    }

    var unknown = new UnknownCharacterType();
    unknown = (string)DeserializeStringValue(obj, "name");
    return unknown.
}
```

**Comment by tunurgitr** [comment]
@michaelstaib 
I think we could have a very similar situation with new enum values, and more generally, with other schema changes you end up with complex situations:
- removing a non-null field removed from a type
- a field changing from non-null to null
- a field changing to a different type

Hopefully most of those are encountered during development :-)

It seems there should be a general way to handle these kinds of errors. My first thought would be to do something similar to the way that server-errors are handled -- return as much of the graph as possible, and use a separate "errors" object to report why fields aren't returned.

Depending on their situation, I'm guessing that callers would probably handle these issues similarly to server errors.

Another idea you may have already thought of...could we capture a snapshot of the schema at the time the model was generated and then have a way to potentially check for changes as a build-option? 

If we have a method to refetch a schema, I could think of wanting to refetch the schema and ensure that a regenerated client wouldn't be different than my current client as part of a CI/CD process.

**Comment by michaelstaib** [comment]
@tunurgitr 

So, I have reflected in the issue and have the following thoughts.

First, we should only as a last resort break and give the developer the option to work with the data that we can handle. I will elaborate on this later.

Second, there are things that will break.

Third, we will try to fail on build.

Ok, let me elaborate on these three points. There are schema changes that will inevitably lead to breaking clients. This is why people actually should you deprecate and not remove parts or for instance changes a non-null output field to nullable. Those changes are not amendable and will lead to errors.

But adding a implementation should not break a client. The client should be able to skip over those things.

I think something like `IUnknown` could help. Where we can now write a handler for this that either fails if there occurs an instance of `IUnknown` or work with the data that we understand of it.

```csharp
public interface IUnknown 
{
    // The GraphQL type name.
    string TypeName { get; }
}
```

so, if we had something like

```graphql
{
    foo {
       bar
       ... on Baz {
          baz
       }
    }
}
```

we would have a default class:

```csharp
private class UnknownFoo
    : Foo
    , IUnknown 
{
    // The GraphQL type name.
    string TypeName { get; set; }

    string Bar { get; set; }
}
```

I think this is a better solution that just failing if you have for instance mobile apps. We still can give the client ab option to fail if something is unknown and then we will fail fast.

**Comment by tunurgitr** [comment]
@michaelstaib that makes sense....I was thinking about the idea of "dangerous" changes (https://github.com/xuorig/graphql-schema_comparator/issues/11), since the case you're handling here is one of those (`TYPE_ADDED_TO_UNION`, `INTERFACE_ADDED_TO_OBJECT`). I was just thinking through how other situations would impact a dotnet client, and the only other one I can think of that would have an impact would be:

`VALUE_ADDED_TO_ENUM`

I'm not sure there's a way to "fail open" consistently in the case of a new enum value in an enum that's being returned. If the enum field was nullable, then you could return null if an unknown value is detected....but since it's a scalar, you don't have the same options you do with the union/interface situation.

**Comment by michaelstaib** [comment]
@tunurgitr I also reflected on the weekend a bit more on this. The thing that we can amend are new types added. 

The enum added becomes an issue since it is an input type and this would lead into situations where you are able to consume an enum value as unknown but you could not use the date to send something back.

So, this change would lead to the client API to fail. I think we we have to write a lot of documentation on these cases in order to help users along. 

This all has to do with good schema design recommendations.

**Comment by michaelstaib** [comment]
@OneCyrus @tunurgitr @rstaib 

# Executor

So, although we will have simple generated facades that most of the users will be just fine with, underneath those facades we will have executors. I have refined the API for the client usage. So names and structure differ from the server.

We will have three different executor types:

```csharp
public interface IOperationExecutor
{
    Task<IOperationResult> ExecuteAsync(IOperation operation);

    Task<IOperationResult<T>> ExecuteAsync<T>(IOperation<T> operation);
}

public interface IOperationBatchExecutor
{
    Task<IResponseStream> ExecuteAsync(IEnumerable<IOperation> batch);
}

public interface IOperationStreamExecutor
{
    Task<IResponseStream<T>> ExecuteAsync<T>(IOperation<T> operation);
}
```

The `IOperationExecutor` executes queries or mutations and is the default executor. 

The `IOperationBatchExecutor` allows to take advantage of batching. we will have auto-batching available where we collect like Apollo within a certain amount of time all requests and send them as batch. We will take advantage of of the stream nature of some batch implementations and make results available as they appear on the stream.

The `IOperationStreamExecutor` will handle things stream results like subscriptions or queries that use `@defer` or `@stream`.

Initially we will provide an implementation for `Http` for all of these.

These executor allow for more advanced scenarios. 

We also will create facades that will look like the following:

```
public interface IStarWarsServiceClient 
{
    Task<IOperationResult<IHero>> GetHeroAsync(Episode episode);

    Task<IOperationResult<IHero>> GetHeroAsync(Episode episode, CancellationToken cancellationToken);

    Task<IResponseStream<Review>> OnReviewAsync(Episode episode);

    Task<IResponseStream<Review>> OnReviewAsync(Episode episode, CancellationToken cancellationToken);
}
``` 

A response stream is basically an `IAsyncEnumerable`.


All clients can be generated with different options that enable things like persisted queries. We are hashing all queries and provide all those things with `IDocument`.

Although we are implementing most of the flows so that everything comes out of the box, the transport abstractions allow you to swap some parts out and replace them with custom implementations.

```CSharp
public interface IDocument
{
    ReadOnlySpan<byte> HashName { get; }

    ReadOnlySpan<byte> Hash { get; }

    ReadOnlySpan<byte> Content { get; }
}

public interface IOperation
{
    string Name { get; }

    IDocument Document { get; }

    IReadOnlyDictionary<string, object> GetVariables(
        IEnumerable<IValueSerializer> serializers);
}

public interface IOperation<out T>
    : IOperation
{
}
```

**Comment by michaelstaib** [comment]
# Custom Scalars

In order to register a custom scalar all we have to do is to implement `IValueSerializer` and register it with the dependency injection.

The generated result parser will get all value serializer from the dependency injection and use those when a result is parsed.

Here is an example of a generated result parser:

```CSharp
public class GetHeroResultParser
    : GeneratedResultParserBase<IGetHero>
{
    private readonly IValueSerializer_stringSerializer;

    public GetHeroResultParser(IEnumerable<IValueSerializer> serializers)
    {
        IReadOnlyDictionary<string, IValueSerializer> map = SerializersToDictionary(serializers);

        if (!_valueSerializers.TryGetValue(leafType.Name, out string typeName)){
            throw new ArgumentException(
                $"There is no serializer specified for `{leafType.Name}`.",
                nameof(serializers));
        }
        _stringSerializer = map["String"];
    }

    private IGetHero ParseRoot(
        JsonElement parent,
        ReadOnlySpan<byte> field)
    {
        if (!parent.TryGetProperty(field, out JsonElement obj))
        {
            return null;
        }

        string type = obj.GetProperty(_typename).GetString();

        var getHero = new GetHero();
        getHero.Hero = ParseRootHero(obj, "hero");
        return getHero;
    }

    private IHero ParseRootHero(
        JsonElement parent,
        ReadOnlySpan<byte> field)
    {
        if (!parent.TryGetProperty(field, out JsonElement obj))
        {
            return null;
        }

        string type = obj.GetProperty(_typename).GetString();

        if (string.Equals(TypeName, "Droid", StringComparison.Ordinal))
        {
            var droid = new Droid();
            droid.Name = (string)DeserializeStringValue(obj, "name");
            droid.Friends = ParseRootHeroFriends(obj, "friends");
            return droid;
        }

        if (string.Equals(TypeName, "Human", StringComparison.Ordinal))
        {
            var human = new Human();
            human.Name = (string)DeserializeStringValue(obj, "name");
            human.Friends = ParseRootHeroFriends(obj, "friends");
            return human;
        }

        throw new NotSupported("Handle not exhausted objects");
    }

    private IFriend ParseRootHeroFriends(
        JsonElement parent,
        ReadOnlySpan<byte> field)
    {
        if (!parent.TryGetProperty(field, out JsonElement obj))
        {
            return null;
        }

        string type = obj.GetProperty(_typename).GetString();

        var friend = new Friend();
        friend.Nodes = ParseRootHeroFriendsNodes(obj, "nodes");
        return friend;
    }

    private System.Collections.Generic.IReadOnlyList<IHasName> ParseRootHeroFriendsNodes(
        JsonElement parent,
        ReadOnlySpan<byte> field)
    {
        if (!parent.TryGetProperty(field, out JsonElement obj))
        {
            return null;
        }

        string type = obj.GetProperty(_typename).GetString();

        if (string.Equals(TypeName, "Droid", StringComparison.Ordinal))
        {
            int objLength = obj.GetArrayLength();
            var list = new IHasName[objLength];

            for (int objIndex = 0; objIndex < arrayLength; objIndex++)
            {
                JsonElement element = obj[objIndex];
                var entity = new Droid();
                entity.Name = (string)DeserializeStringValue(element, "name");
                list[objIndex] = entity;
            }

            return list;
        }

        if (string.Equals(TypeName, "Human", StringComparison.Ordinal))
        {
            int objLength = obj.GetArrayLength();
            var list = new IHasName[objLength];

            for (int objIndex = 0; objIndex < arrayLength; objIndex++)
            {
                JsonElement element = obj[objIndex];
                var entity = new Human();
                entity.Name = (string)DeserializeStringValue(element, "name");
                list[objIndex] = entity;
            }

            return list;
        }

        throw new NotSupported("Handle not exhausted objects");
    }

}
```

**Comment by michaelstaib** [comment]
**So, where are we with this issue?**

At the moment we can generate the result models and the result parser. 

I have started work on generating the operation types that basically represent one request that you can send to the server.

Things to do:

- [ ] `@spread`
- [ ] Facade Generator
- [ ] File Generator
- [ ] Operation Generator 
- [ ] HTTP Operation Executor
- [ ] HTTP Operation Batch Executor
- [ ] HTTP Operation Stream Executor
- [ ] Persisted Query Support
- [ ] Diagnostic Sources
- [ ] dotnet tools
- [ ] Query Compiler

**So, what do we need to try this stuff out?**

In order to play with our client and try first requests we have to finish our work on the operation generation. Apart from that we need the http executor and a simple dotnet tool version without any fancy things, just the ability to generate.

I currently think we will hit this goal end of this week beginning of next week. After that there its still plenty to do.

**Comment by michaelstaib** [comment]
# dependency injection

Ah one last thing ... the generated client will also have a generated dependency injection method.

Adding it to the services will look like this.

```csharp
services.AddGraphQLHttpClient();
services.AddStarWarsClient();
```

**Comment by michaelstaib** [comment]
@tunurgitr 

There are a couple of reasons for this. First `IValueSerializer` is different and also handles serialization of enums. 

With the current implementation we do not have any code of the server in. I want to support also building for watchOS and Blazor so we need to get the client really small.

If I would put the server in we have to hit netstandard2.0 but with the current client implementation we do not need netstandard2.0 and can instead focus on smaller size.

Second, the client is really different form the usage standpoint. You will have a strong typed API that is generated from your query documents.

We will still support local resolvers and and front-end schema stitching. But as I mentioned before this will be an opt-in.

I am looking at integrating the `IValueSerializer` with the server API. The server API could implement this interface for its input types so that you could use the server code if you are opting into there larger bundle size.

I also think I will rename the interface. It is more an input value serializer .... or something like that. We actually have a very similar interface in the backend. I might unify those. The issue is still I will not reference the core by default.

**Comment by michaelstaib** [comment]
This is the server interface:

https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types/Types/Contracts/ISerializableType.cs

**Comment by michaelstaib** [comment]
The problem with that interface is that it implements quite a lot:

```
public interface ITypeSystemObject
        : IHasName
        , IHasDescription
        , IHasContextData
        , ITypeSystemMember
    {
    }
```

**Comment by michaelstaib** [comment]
Sorry not true looked at the wrong object ... It actually just implements `IType` which implements `ITypeSystemMember`. 

So, we could reuse this interface with `IHasClrType` and `IHasName` together.

**Comment by michaelstaib** [comment]
So, just checked the size...

Full GraphQL Core: ca 1.2 MB
Slim Client Core: 17 KB

In both cases we have to add to that amount the generated code.

**Comment by michaelstaib** [comment]
I did more work.... :)

We are also opening up the generator API and since we are having builder APIs everywhere it will be again a builder API.

The API looks like this and is already in ...

```csharp
await ClientGenerator.New()
                .AddSchemaDocumentFromString(
                    "StarWars",
                    FileResource.Open("StarWars.graphql"))
                .AddQueryDocumentFromString(
                    GetFileNameWithoutExtension(queryFile),
                    FileResource.Open(queryFile))
                .SetOutput("./generated")
                .CreateAsync();
```

So, If someone wants to build ontop or extend the client generator it is possible to add, replace code generators or even to rewrite the schema. 

In fact beneath this API sits the `SchemaMerger` API from schema stitching that lets us merge and rewrite schemas.

Our tooling will use this API to generate clients and if someone wants for instance to build a website that automatically generate GraphQL clients this API might be useful....

**Comment by michaelstaib** [comment]
PS. The output does not have to be a directory but also can be a 

```csharp
    public interface IFileHandler
    {
        void WriteTo(string fileName, Func<CodeWriter, Task> write);

        Task WriteAllAsync();
    }
```

**Comment by michaelstaib** [comment]
We have hit our first internal milestone for the client this weekend and it is kind of usable now. We still have a ton to do. I think we can close this issue now and create smaller more specific ones as we go along on this project.
