### ISSUE TITLE
Date Filters not returning any result for Equals Filter

### ISSUE THREAD

**Issue by gmiserez** [ChilliCream/hotchocolate#1035]
Hello, 

We're using the HotChocolate PRISMA-like filters on top of a Mongo IQueryable. 
We're currently experiencing an issue when filtering on the exact date. 

**To Reproduce**
A sample repository is available here: 
https://github.com/gmiserez/HotChocolate_DateFilterWithMongoIssue

This query returns all the concerts: 
```
{
  blackSabbath2019Tour(where: { concertDate_gte: "2019-01-01" }) {
    concertDate
    name
  }
}
```
the returned concerts:
```
{
  "data": {
    "blackSabbath2019Tour": [
      {
        "concertDate": "2019-06-01",
        "cityName": "Amsterdam"
      },
      {
        "concertDate": "2019-07-10",
        "cityName": "Berlin"
      },
      {
        "concertDate": "2019-06-18",
        "cityName": "Paris"
      },
      {
        "concertDate": "2019-03-15",
        "cityName": "Zürich"
      }
    ]
  }
```

But this query doesn't return the concert that's taking place on that particular day:
```
{
  blackSabbath2019Tour(where: {concertDate: "2019-06-01"}){
    concertDate
    cityName: name
  }
}
```

**Expected behavior**
The following item should be returned for the second query:
{
        "concertDate": "2019-06-01",
        "cityName": "Amsterdam"
}

**Packages:**
 - HotChocolate.* 11.0.0-preview.4
 - MongoDB.Driver 2.8.1

**Additional context**
Could this be an issue with UTC vs Local dates comparisons? I'm living in the CET zone.

**Comment by michaelstaib** [comment]
This one works now in V11 and V10

**Comment by michaelstaib** [comment]
#1170
