### ISSUE TITLE
404 for Playground's resources with an existing AspNet Classic webapp

### ISSUE THREAD

**Issue by frbar** [ChilliCream/hotchocolate#1053]
**Summary**
`https://localhost/graphql/playground` fires 404 errors for resources (styles.css, settings.js, middleware.js) when HotChocolate is integrated to an existing AspNet Classic web application. Endpoint seems OK as I can see the Playground logo while loading is performed.

This is probably not related to HotChocolate but I'm struggling finding the cause.

**Details**
Integration is done in an existing AspNet Classic web application (4.6.1, webapi 2) using the following NuGet packages:

- HotChocolate.AspNetClassic 10.0.1
- HotChocolate.AspNetClassic.GraphiQL 10.0.1
- HotChocolate.AspNetClassic.Playground 10.0.1
- HotChocolate.AspNetClassic.Voyager 10.0.1

Configuration is:

```
        private void ConfigureGraphQL(IAppBuilder app)
        {
            var services = new ServiceCollection();

            // Add GraphQL Services
            services.AddGraphQL(sp => SchemaBuilder.New()
                    .AddServices(sp)
                    .AddQueryType<Query>()
                    .Create(),
                new QueryExecutionOptions
                {
                    TracingPreference = TracingPreference.Always
                });

            app
                .UseGraphQL(services.BuildServiceProvider(), new PathString("/graphql"))
                .UseGraphiQL(new PathString("/graphql"))
                .UsePlayground(new PathString("/graphql"))
                .UseVoyager(new PathString("/graphql"));
            ;
        }
```

Called from `StartUp`:

```
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {        
            var container = AutofacConfig.ConfigureAutofac();
            app.UseAutofacMiddleware(container);
            ConfigureAuth(app);
            ConfigureGraphQL(app);
        }
    }
```

`ASPNETCLASSIC` defined as Constant in a last ditch effort.

Same in Debug and Release, same with Voyager and GraphiQL.

**Comment by michaelstaib** [comment]
Hi, I will look at this on Monday.

**Comment by frbar** [comment]
@michaelstaib thanks. Looks ok with this workaround (https://github.com/aspnet/StaticFiles/issues/65):

```
<system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
  </system.webServer>
```

**Comment by twilly86** [comment]
Also getting the same issue.  Have the added module and the same setup as posted in above.

Is there an example project running against aspnetclassic that has this working that I can check?

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/tree/version_10_0_0_master/examples/AspNetClassic.StarWars

**Comment by penleychan** [comment]
For those who are having issue with aspnet classic running on OWIN this fixes the 404 issues.
Add to `system.webServer`

```
<system.webServer>
    <handlers>
      ...
      <add name="Owin" verb="" path="*" type="Microsoft.Owin.Host.SystemWeb.OwinHttpHandler, Microsoft.Owin.Host.SystemWeb" />
    </handlers>
</system.webServer>
```
Hope that helps

**Comment by Messan** [comment]
Hello,
Can somebody help me find the original sample https://github.com/ChilliCream/hotchocolate/tree/version_10_0_0_master/examples/AspNetClassic.StarWars.
I am unable to run a simplyest  test with OWIN, I still get 404 when I try to access the playground despite the advices above.

Regards

**Comment by michaelstaib** [comment]
I am closing this one since we are dropping aspnet Classic with version 11. The graphologist core will still be classic compliant but we no longer will provide middleware for .net framework.
