### ISSUE TITLE
How to retrieve the InputType as a Dictionary<string,object>

### ISSUE THREAD

**Issue by Stonepaw** [ChilliCream/hotchocolate#1056]
I would like to retrieve the argument in a mutation as both the InputType as the Dictionary<string, object>. My use case is to support partial updates where an explicit null means to clear the field and a missing property on the InputType means to leave it unchanged. The difference between undefined and null in json for example.

I investigated using the Argument on the context but was unable to retrieve the original Dictionary<string, object> except mapped as the InputType object.

Is this possible with the current library?

**Comment by michaelstaib** [comment]
So, while you cannot get it as a  Dictionary<string, object> out of the box with V10 you cab get it as a object literal. Which gives you the same capabilities as the dictionary. We have used this for the filter implementation.

`var x =  context.Argument<ObjectValueNode>()`

**Comment by Stonepaw** [comment]
Perfect. I can make use of `ObjectValueNode` for my use case.

Thanks!
