### ISSUE TITLE
Mutations example in the docs

### ISSUE THREAD

**Issue by louisjacksonrees** [ChilliCream/hotchocolate#1057]
Would it be possible to add some examples of mutations to the docs? Kind of struggling to figure out how to write them?

**Comment by Arsync** [comment]
Any link please? As this issue closed silently, but page well-indexed by googling "HotChocolate mutations example"

**Comment by michaelstaib** [comment]
Hi @Arsync, have a look at our workshop:
https://github.com/ChilliCream/graphql-workshop
