### ISSUE TITLE
Distinguish between HTTP and remote schema errors

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#1062]
Currently when there is a failed request to a remote schema `HttpQueryClient.`FetchInternalAsync` will throw an exception via `EnsureSuccessStatusCode`. 

This exception is being caught in the `ExceptionMIddleware` in the query delegation pipeline configured in `StitchingQueryExecutionBuilderExtensions.UseQueryDelegationPipeline` and turned a regular unexpected error.

At this point the remote error is difficult to distinguish from any regular errors returned from the remote schema.

We'd like to be able to make this distinction to aid in our service error handling strategies
.

**Comment by michaelstaib** [comment]
I have merged the changes now also to V11. So we have it now in both versions. I am closing this issue.
