### ISSUE TITLE
Feature-Request: Add Diagnostic Events for the Start and End of the Stitching process + trigger Stitching on startup

### ISSUE THREAD

**Issue by gmiserez** [ChilliCream/hotchocolate#1075]
Hi, 

We currently use HotChocolate remote schema Stitching (builder.AddSchemaFromHttp(...)).
While we're very satisfied by its ease of use, we encounter some suboptimal behaviors with it. 

The stitching is currently not done on Startup but only once the first query is received. Sometimes we encounter delays on some queries which we believe are due to kubernetes having restarted a pod, which means that on this first query we have an additional 10 seconds to re-stitch the schema. 
Problem is we can't efficiently track when and how a stitching operation has been performed (multiple monitoring tools: kube dashboard, company logging portal etc). 

We could trigger the stitching via automated healthchecks, for instance by throwing an introspection query at the server, and also detect stitching issues in that same way.

However, a useful feature for us would be to have new DiagnosticEvents which are invoked when the stitching starts and ends so that we can plug-in our own code to monitor it. 

Additionally, if it is somehow possible to trigger the stitching process on startup instead of the first query this would be a really great enhancement but I reckon this would be rather difficult to implement.

**Comment by gmiserez** [comment]
Thank you @nigel-sampson this is a really nice solution!

**Comment by michaelstaib** [comment]
This is implemented with 12

**Comment by gmiserez** [comment]
Thanks @michaelstaib 
I guess it's the following extension method

```
Assembly HotChocolate.AspNetCore, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null
namespace Microsoft.Extensions.DependencyInjection
{
    //
    // Summary:
    //     Provides DI extension methods to configure a GraphQL server.
    public static class HotChocolateAspNetCoreServiceCollectionExtensions
    {
        //
        // Summary:
        //     Adds the current GraphQL configuration to the warmup background service.
        public static IRequestExecutorBuilder InitializeOnStartup(this IRequestExecutorBuilder builder)
```
