### ISSUE TITLE
Introduce non-generic type descriptor method `descriptor.Type(System.Type).`

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1079]
#1058

For dynamic schema creating it would be useful to have a new `Type` description method that can be used to dynamically set types.

We need to write some validation logic that ensures the type context is always correct (input vs output).

Places where we have a type context:

- Object Fields
- Object Field Arguments
- Interface Fields
- Interface Field Arguments
- Input Fields
- Directive Arguments

**Comment by promontis** [comment]
@michaelstaib I've created a PR for this enhancement. Is it ok like this?

**Comment by michaelstaib** [comment]
I will have a look at it later or in the morning.

**Comment by promontis** [comment]
@michaelstaib did you already manage to have a look? :)

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/10.2.0-preview.4
