### ISSUE TITLE
Allow custom variable names for filtering / sorting

### ISSUE THREAD

**Issue by Flamage82** [ChilliCream/hotchocolate#1087]
**Is your feature request related to a problem? Please describe.**
The variable names for filters / sorting are hard-coded to `where` and `order_by` respectively.  Our code style enforces camelCase variables and it would be preferable if we didn't need to convert names in our codebase.

**Describe the solution you'd like**
We'd like to be able to customise these variable names, as `order_by` doesn't fit our code style of camelCase.

**Describe alternatives you've considered**
We could rewrite the variable name in our stitching layer, but allowing users to customise the name is preferable.

**Additional context**
We're using Typescript, ESLint, and we generate strongly-typed query types with the relay compiler and `relay-compiler-language-typescript`.  In the few places where we need to generate or manipulate variable objects in our code, we are prevented from naming our properties to match the query when they aren't camelCase.

**Comment by michaelstaib** [comment]
@PascalSenn is this fixed in v10 or v11?

**Comment by PascalSenn** [comment]
@michaelstaib  it is targeted for 11
We need the conventions for this

**Comment by michaelstaib** [comment]
no problem .... I am just wrapping up 10.2 and then we move this one to 11.

**Comment by michaelstaib** [comment]
we should write a little blog post for filtering showing what is possible with 10.2 and what we want to do in version 11.

**Comment by michaelstaib** [comment]
#1165

**Comment by PascalSenn** [comment]
Added Conventions in 11
