### ISSUE TITLE
Querying a type with multiple variables ( variables based on Fields )

### ISSUE THREAD

**Issue by AALGate** [ChilliCream/hotchocolate#1088]
Good morning,

it is my first time to try GraphQL and i came to this repo, which i can find it's great !

I have a project that i am working on, and i need to query an Entity based on multiple parameters which are their properties.

for example, i have an Entity called  ( Booking ) , this Entity has multiple properties like  

Booking
{
  Id : int
  ContactEmail : string
  RoomsBookingDetails : (type RoomsBookingDetails )
                                        {
                                          number : int
                                         .....
                                        }

List<Person> Persons : (type Person)
                                     {
                                       id : int
                                       name : string
                                       }
}
     

i want to be able to query this object ( Booking ) / maybe also some sub objects, with multiple parameters

for example : 

my query will be something like this 

{
query {
              booking(id:5, email: "" )
}
}
  

Sometimes, i want to query with only one parameters

This means that i want to pass dynamic parameters ( based on the Entity Fields )  to my query type, 
and i want to resolve this in a single generic Resolver

this could be possible to do ?

i mean with a single resolver, i want to pass multiple params (those params are the Fields of the Entity )

i'm using Code-First approach with .NET Core

i have tried graphql.net,  but it seems like i should handle all the passed arguments with multiple resolvers

**Comment by AALGate** [comment]
Note: i am using Elastic Search as a Data Source

**Comment by michaelstaib** [comment]
So, you want to query an elastic search server? 

What you can do if elastic search does not support `IQueryable` is to implement a query rewriter. The Filter API can be extended by implementing a query visitor.

Here is an example how we did it for queryable.
https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types.Filters/QueryableFilterVisitor.cs

**Comment by michaelstaib** [comment]
If you need help to implement it for nest head over to our slack channel.

**Comment by AALGate** [comment]
That's fantastic, i really appreciate your great help.
Thank you very very much

Please let me know the Slack channel as the Invitation is no longer active

`https://hotchocolategraphql.slack.com/join/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg`
> This invite link is no longer active.

**Comment by michaelstaib** [comment]
OK, fixed the invite link.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by michaelstaib** [comment]
@AALGate  Can I close this issue?

**Comment by AALGate** [comment]
Yes, thanks a lot @michaelstaib

**Comment by RomanVashchegin** [comment]
Hello everyone, I also looking for a way to convert Queries to ElasticSearch Nest client.
