### ISSUE TITLE
Relay example

### ISSUE THREAD

**Issue by tanekim77** [ChilliCream/hotchocolate#1091]
I was trying to following documentation regading to relay, but getting errors.

I think it would be very helpful if there is a minimul working example that implements relay. Thanks!

**Comment by michaelstaib** [comment]
Hi @tanekim77,

I will upgrade the documentation with an example and explain how we are (on the server-side) implementing the three relay specs.

It is really easy but I agree that we should have an example for this.

We are planing the next release for the 15th of October and I will include the example with the release.

**Comment by tanekim77** [comment]
Thanks, Today is 15th, and may I please know where I can get that example? Thanks!

**Comment by michaelstaib** [comment]
Hi @tanekim77 we are still working on the release... we hope to get it done this week. I will keep you posted.

**Comment by tanekim77** [comment]
Thanks Michael, please get me posted. Thanks!

**Comment by tanekim77** [comment]
Is there any update on this? Thanks for your hard work!
