### ISSUE TITLE
Star Wars example doesn't run

### ISSUE THREAD

**Issue by Daniel15** [ChilliCream/hotchocolate#1092]
Trying to follow the instructions at https://hotchocolate.io/docs/example-star-wars-code-first.html to test out the "Star Wars" example. It starts on a different port to what's documented (1293, not 5000), and hitting `/playground` just gives me a 404 error.

**To Reproduce**
```
dotnet new -i HotChocolate.Templates.StarWars
mkdir starwars
cd starwars
dotnet new starwars
dotnet run --project StarWars/StarWars.csproj -c release
```

Try to load http://localhost:1293/playground

**Expected behavior**
Should work

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Build 18362.10022

**Comment by michaelstaib** [comment]
I think your uri is wrong. .../graphql/playground

**Comment by michaelstaib** [comment]
Ah sorry you are using the template... let me check

**Comment by Daniel15** [comment]
I was trying the URL that was provided on the site. Perhaps the site is
wrong.

**Comment by michaelstaib** [comment]
Hi @Daniel15,

the site is invalid... http://localhost:5000/graphql/playground/ works ...

Do you want to do a docu pull request?

Really appreciate your help on this project 👍

**Comment by Daniel15** [comment]
Thanks for confirming~ /graphql/playground works for me. Submitted a PR to fix the docs: https://github.com/ChilliCream/hotchocolate-docs/pull/49
