### ISSUE TITLE
WebSocketSession Lifetime event - OnDisconnect

### ISSUE THREAD

**Issue by clayu** [ChilliCream/hotchocolate#1113]
I would like to add a listener to the disconnect event for a subscription. 

Ideally it would trigger when a session has ended, either by the client explicitly calling the stop event or when the token is canceled (due to browser closing/crashing).

**Comment by michaelstaib** [comment]
This actually should now be possible with the new async streams.

The async enumerator is disposed once the connection closes or the connection breaks. 

I will add a test for this and add some documentation on this.

**Comment by michaelstaib** [comment]
This one is Implemented
