### ISSUE TITLE
[question] How do I extend a base graph type

### ISSUE THREAD

**Issue by pingvinen** [ChilliCream/hotchocolate#1120]
Hi

I have a situation where I would like to expose a clean graph for consumers (at `/graphql`) of my service and a bigger graph for my back-office system (at `/private_graphql`).

I am using the **HotChocolate 10.1.0** package.

### This is what I am trying to achieve

A **shared** base type for a `User`

```
User
  id
  name
```

A **public** version of `User`

```
User
  id (from base)
  name (from base)
  relationToMe (public only)
```

A **private** version of `User`

```
User
  id (from base)
  name (from base)
  forAdminEyesOnly (private only)
```

### How do I do this? Is it even possible?

I have tried a bunch of different ways to achieve this, but have so far failed :(

I have tried using the `.Extend()` stuff, but I never seem to actually have anyting in the descriptor to work with.

I looked into using a `Directive`, but I failed to identify how to remove a field in the `InvokeAsync` implementation.

I am considering using stitching within my service, where I build a **shared schema**, a **public schema** and a **private** schema, and then serve a stiched schema with the shared and the public or private schema.

### Also of note

I am using [ServiceStack](https://servicestack.net) instead of AspNetCore MVC and building the schema using the following code:

```csharp
var builder = SchemaBuilder
    .New()
    .AddServices(_container)
    .AddQueryType<TQuery>();
```

I am aware that this concept is being discussed in lots of different forums all over the internet and has been for years. I have already built other graphs where fields are simply nulled if the user does not have the proper permissions etc.

Please do not turn this question into a discussion of 1 vs _n_ graphs. Thank you :)

**Comment by michaelstaib** [comment]
Hi,

it is possible with extensions. You basically have to `SchemaBuilder` instances and add the extension types that are specific to a schema to the corresponding type.


```csharp
var privateSchema = SchemaBuilder
    .New()
    .AddServices(_container)
    .AddQueryType<SharedQueryType>()
    .AddType<PrivateQueryTypeExtension>()
    .Build()
``` 

```csharp
var publicSchema = SchemaBuilder
    .New()
    .AddServices(_container)
    .AddQueryType<SharedQueryType>()
    .AddType<PublicQueryTypeExtension>()
    .Build()
``` 

https://hotchocolate.io/docs/schema-object-type#extension

In the shared schema you can also use classes to import resolvers like the following:

```csharp
public class PersonTypeExtension
    : ObjectTypeExtension
{
    protected override Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Name("Person");
        descriptor.Field<FooClass>(t => t.Bar)
            .Type<NonNullType<StringType>>();
    }
}
```

It is important to know that the type is matched by its name. So, the type extension and its type has to have the same name.

This is also working with sdl-first approach, in the sdl-first approach you would do:

```graphql
extend type Foo {
    custom: String
} 
```

> Please do not turn this question into a discussion of 1 vs n graphs. Thank you :)

We are not opinionated.

Does this help you?

**Comment by pingvinen** [comment]
I made a minimal-ish solution to show the full scope of everything: https://github.com/pingvinen/hotchocolate-issue-1120

> Does this help you?

Yes. It pointed me in the right direction, but I think the documentation could use some examples like this. The current documentation on "extending types" does not contain any examples and pointed me in the direction of the `descriptor.Name(..).Extend().On*` methods. I used the debugger to look at the things available to me and everything was just empty.

I ended with something like this.

```csharp
public class PrivateUserGraphTypeExtension : ObjectTypeExtension
{
  protected override void Configure(IObjectTypeDescriptor descriptor)
  {
    descriptor.Name(UserGraphType.GraphName);
    descriptor.Field<UserGqlOut>(t => t.ForAdminEyesOnly);
  }
}
```
...and...

```csharp
schemaBuilder.AddType<PrivateUserGraphTypeExtension>();
```

Thank you very much for your extremely fast response @michaelstaib

**Comment by michaelstaib** [comment]
Just as a side note:

https://github.com/pingvinen/hotchocolate-issue-1120/blob/e1f91d15a40cd3e9703bdd07cc7327b638f4e8a5/GraphStuff/Endpoint/GraphQlService.cs#L26

Building the schema is expensive ... so make sure that you store the schema somewhere and do not build it on every request.

**Comment by michaelstaib** [comment]
> descriptor.Name(..).Extend().On*

`Extend()` is meant for extensions like providing a entity framework extension or a paging extension etc. 

I will add some more documentation.

**Comment by pingvinen** [comment]
> Building the schema is expensive ... so make sure that you store the schema somewhere and do not build it on every request.

Thank you. This actual codebase is 2 days old at the moment, so it is still early days :)
