### ISSUE TITLE
Set name for InputFilterType and SortInputType

### ISSUE THREAD

**Issue by Chrislock1** [ChilliCream/hotchocolate#1149]
**Desired solution**
When writing `.UseFiltering<T>()` and `.UseSorting<T>()` I would like to add a name for the input types in the schema.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/10.2.0-preview.10

**Comment by michaelstaib** [comment]
The fix is in with preview 10... can we close this issue?
