### ISSUE TITLE
Disable FragmentsMustBeUsed

### ISSUE THREAD

**Issue by quazzie** [ChilliCream/hotchocolate#1156]
**Is your feature request related to a problem? Please describe.**
Need a way to disable FragmentsMustBeUsed validation.
I have a union type where i query it like 
```
query {
  items {
    ...fragmentForType1
    ...fragmentForType2
  }
}
fragment fragmentForType1 on Type1 { .... }
fragment fragmentForType2 on Type2 { .... }
```

if it return only Type1 items i get an error that fragmentForType2 is not used.

**Describe the solution you'd like**
Not receiving a "The specified fragment `xxx` is not used within the current document".

**Comment by michaelstaib** [comment]
That is not what the rule is about. 

FragmentsMustBeUsed just analyzes the query document and ensures that the fragment is referenced within the query document.

**Comment by michaelstaib** [comment]
The above document is valid by the way and should not trigger that rule.

**Comment by michaelstaib** [comment]
Can you maybe create a little repro?

**Comment by quazzie** [comment]
Hmm i'll have to check when i get back to work on Monday.

**Comment by michaelstaib** [comment]
Great, there is a way to disable it ... but you should not need to, so I want to find out if it is a bug.

**Comment by quazzie** [comment]
My mistake, deep in the errors i discovered i used the wrong name on a type. Because i tried use "fragment on <Misspelled type>" it caused a cascade of errors with the unused fragment error.

**Comment by michaelstaib** [comment]
Thanks for your feedback.
