### ISSUE TITLE
Subscription is not working with Variables

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#1157]
**Describe the bug**
Subscriptions will not work when using variables, because when creating subscriptions stream keys, the variables names are used to create the keys, instead of the actual value of the variable.

This results is, that subscriptions that use variables will never receive any messages, because their stream key is never matched. 

![image](https://user-images.githubusercontent.com/9481836/67617302-28c24280-f7e2-11e9-8196-9be844542305.png)

**To Reproduce**
Check out this repo (It's a fresh dotnet core 3 project with hc 0.10):
https://github.com/Narmor/hc-subscription-bug

Start the project, open Playground on http://localhost:5000/playground, create 4 editor-tabs and put the following snippets in one tab each:

**first editor-tab**
```
subscription {
  onReview(moviewName: "DieHard")
}
```

**second editor-tab**
```
subscription onReviewSub($movieName: String) {
  onReview(moviewName: $movieName)
}
```
with Variables:
```
{
  "movieName": "DieHard"
}
```

**third editor-tab**
```
mutation {
  fireSubscriptionEvent(moviewName: "DieHard")
}
```

**fourth editor-tab**
```
mutation fireEvent($movieName: String){
  fireSubscriptionEvent(moviewName: $movieName)
}
```
with Variables:
```
{
  "movieName": "DieHard"
}
```

Start both Subscriptions in the first two editor editor-tabs.
Then fire both mutations in the other two editor-tabs.

**Expected behavior**
Both open subscriptions will receive exactly the same two values.

**Comment by michaelstaib** [comment]
Thanks for filing this issue. I will look into it once I am back from Kiev.

**Comment by michaelstaib** [comment]
I can proof now that this is a bug. We will issue a fix for this today.

**Comment by michaelstaib** [comment]
This issue seems to be back in the 11 branch. I reopened this so we have a trigger to revalidate this.
