### ISSUE TITLE
Document DataLoaderOptions in either HC or GD API docs 

### ISSUE THREAD

**Issue by tohagan** [ChilliCream/hotchocolate#1162]
**Is your feature request related to a problem? Please describe.**

The [Green Donut Docs](https://greendonut.io/docs/introduction.html) describe the [DataLoader interface](https://greendonut.io/docs/dataloader-interface) but omits the [DataLoadOptions API](https://github.com/ChilliCream/hotchocolate/blob/master/src/DataLoader/Core/DataLoaderOptions.cs).    Same applies for [HC docs on DataLoaders](https://hotchocolate.io/docs/dataloaders)

**Describe the solution you'd like**
- Please add to either [Green Donuts](https://greendonut.io/docs/dataloader-interface) or [HC docs](https://hotchocolate.io/docs/dataloaders).

**Comment by rstaib** [comment]
Okay, I'm on it.

**Comment by tohagan** [comment]
Thank you very much!
