### ISSUE TITLE
Utf8GraphQLReader returns 500 Internal Server Error when request body is empty or []

### ISSUE THREAD

**Issue by Darskus3** [ChilliCream/hotchocolate#1167]
Issue: 
The response is `500 Internal Server Error`, but not a proper error message when `Utf8GraphQLReader` couldn't parse a request body value.

Steps to reproduce: 
Send a request with an empty body or `[ ]` in the body

Expected behavior: 
It should return a proper error message like it is done when request body has `{ }` or `[ { } ]`. It has error message `Either the query "property" or the "namedQuery" property have to have a value`.

![image](https://user-images.githubusercontent.com/13716272/67680556-23a4f500-f994-11e9-93e3-f73c47e8e5bd.png)

**Comment by michaelstaib** [comment]
is this a duplicate of #1168?

**Comment by Darskus3** [comment]
Yes, it is duplicate. Sorry, for that.
