### ISSUE TITLE
Utf8GraphQLReader returns 500 Internal Server Error when request body is empty or []

### ISSUE THREAD

**Issue by Darskus3** [ChilliCream/hotchocolate#1168]
**Describe the bug**
The response is `500 Internal Server Error`, but not a proper error message when `Utf8GraphQLReader` couldn't parse a request body value.

**To Reproduce**
1. Send a request with an empty body or `[ ]` in the body

**Expected behavior**
It should return a proper error message like it is done when request body has `{ }` or `[ { } ]`. It has error message `Either the query "property" or the "namedQuery" property have to have a value`.

**Desktop (please complete the following information):**
 - OS: Any
 - Version Any

**Additional context**
![image](https://user-images.githubusercontent.com/13716272/67680556-23a4f500-f994-11e9-93e3-f73c47e8e5bd.png)

**Comment by michaelstaib** [comment]
I think we will squeeze this one into 10.2 which we hopefully get out this week :)

**Comment by michaelstaib** [comment]
Thank you for reporting this one!

**Comment by michaelstaib** [comment]
this one is now fixed with #1309
