### ISSUE TITLE
request.Scheme in SettingsMiddleware is not supporting x-forwarded-proto and x-forwarded-host headers

### ISSUE THREAD

**Issue by Darskus3** [ChilliCream/hotchocolate#1169]
**Describe the bug**
`request.Scheme` in `SettingsMiddleware` is not supporting `x-forwarded-proto` and `x-forwarded-host` headers to get the correct protocol.

**To Reproduce**
1. Send a request with headers:

Host: example.app.d1.host.zone
User-Agent: curl/7.54.0
X-Request-Id: 78c6ae029992cbd3dc0d7fcbc288901b
X-Forwarded-Host: example.app.d1.host.zone
X-Forwarded-Port: 443
X-Scheme: https
X-Real-Ip: IP
X-Forwarded-For: IP
X-Forwarded-Proto: https

2. It still uses `http`, but not `https`

**Expected behavior**
It should use `https` over `http`.

**Desktop (please complete the following information):**
 - OS: Any
 - Version Any

**Comment by michaelstaib** [comment]
Hi @Darskus3, do you want to do a PR?

**Comment by Darskus3** [comment]
Hi @michaelstaib, sorry, but we do not have capacity for that at the moment.

**Comment by michaelstaib** [comment]
I have put it to the backlog for 10.3.0.
