### ISSUE TITLE
Add ability to configure DataLoaderOptions globally

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#1171]
I encountered a scenario where I need to alter the way the dataloader works globally by setting the MaxBatchSize

but the delegate dataloaders dont provider a way to pass DataLoaderOptions

as it stands i have a big graph with 100s of dataloaders and would have to refactor all of them just to change how the dataloaders work.

What would be nice would be one or all of the following
1. Add an option during StartUp Configuration
2. Allow us to override by registering DefaultDataLoaderOptions during service registration
3. Add overloads to pass in DataLoaderOptions when creating the dataloader

**Comment by michaelstaib** [comment]
We will allow to pass in the options but move it into the v12 release since it is an interface change.

**Comment by michaelstaib** [comment]
this one is done

**Comment by DeltekDavid** [comment]
How does one configure the dataloaders globally? I'm trying to remove (or raise) the `MaxBatchSize` from the default of `1024` for all our data loders.
