### ISSUE TITLE
Standalone stitched schema (Not hosted in asp.net core server)

### ISSUE THREAD

**Issue by cethia** [ChilliCream/hotchocolate#1172]
Dear all,
first of all thank you for your amazing tool. Respect for the design that allow extensibility (@ directives etc...).

My question:
Is it possible to create an executable stitched schema NOT HOSTED in an ASP.NET Webhost?
The Idea is to create a component that can:
1. return the stitched shema from one to many remote hosts
2. execute a query 

```csharp
    public interface IMyComponent
    {
        /// <summary>
        /// Return the stitched schema as string
        /// </summary>
        /// <returns></returns>
        Task<string> GetStitechedSchema();
        /// <summary>
        /// The result of the execution as string
        /// </summary>
        /// <param name="query"></param>
        /// <returns></returns>
        Task<String> ExecuteQuery(string query);
    }

    public class MyComponentImplementation : IMyComponent
    {
        private ISchema schema;
        private ServiceProvider serviceProvider;

        public async Task<string> ExecuteQuery(string query)
        {
            var executor = schema.MakeExecutable();
            ReadOnlyQueryRequest request =
            QueryRequestBuilder.New()
                .SetQuery(query)
                .SetServices(serviceProvider)
                .AddProperty("Key", "value")
                .Create();
            IExecutionResult result = await executor.ExecuteAsync(request);
            var res = result.ToJson();
            return res;
        }

        public async Task<string> GetStitechedSchema()
        {
            IServiceCollection services = new ServiceCollection();
            services.AddStitchedSchema(builder =>
            {
                builder.AddSchemaFromHttp("remote1");
                builder.AddSchemaFromHttp("remote2");
            });
            ISchema schema = null;
            this.schema = schema;
            this.provider = services.BuildServiceProvider();
            ///somehow build the schema
            return schema.ToString();
        }
    }
```
The idea is to have another way for deploying lighweigth graphql servers, for example as dotnet orleans grains (see https://github.com/dotnet/orleans)
If it is not possible, then may be you can estimate the complexity for doing something like that by a new contributor (my person)?
Alternatively, may be it is possible to do that by creating a generic host (asp.net core 2.2 ) for that?
Thank you in advance
Emeric

**Comment by michaelstaib** [comment]
Hi,

thank you for reaching out. We are planing to expand beyond ASP.NET Core with Azure Functions support. We have introduced some basic abstractions to help along.

The important thing is that you follow the GraphQL HTTP Spec. We have a parser for that and would only need the raw utf8 buffer to parse a valid GraphQL request.

I would not limit it to stitching but provide a way to host a schema. Schema stitching is nothing else then a schema with some extensions to fetch data from somewhere else. So, the component should actually provide a way to execute a GraphQL request.

My knowledge of Orleans in this way is limited. We did some experiments but I have no deep knowledge of how to best add a GraphQL server here supporting multiple protocols.

However, if you would like to contribute that we will help you building it.

**Comment by nigel-sampson** [comment]
This is definitely possible, we're doing this where a schema (that uses stitching) is shared between a web host (for a SPA to send queries) and a background service which uses the same schema for pulling data to create file exports.

The implementation is much the same, register the schema in the services collection and then when you want to use it take a dependency on `IQueryExecutor`. 

This lets us issue GraphQL queries for file exports without needing it hosted via ASP.NET.
