### ISSUE TITLE
Support injecting services which capture the IResolverContext and other resolver scoped objects

### ISSUE THREAD

**Issue by GoodmanEScott** [ChilliCream/hotchocolate#1181]
**Is your feature request related to a problem? Please describe.**
Currently there is not an easy and succinct way to write a service which takes a resolver scoped object (e.g. the IResolverContext) as a dependency.

**Describe the solution you'd like**
Here's an example of a service I would like to implement:
```

    public interface IMyResolverScopedService    {    }

    public class MyResolverScopedService : IMyResolverScopedService
    {
        private readonly HotChocolate.Resolvers.IResolverContext _context;

        public MyResolverScopedService(HotChocolate.Resolvers.IResolverContext context)
        {
            _context = context;
        }

       // do fancy stuff with the IResolverContext here
    }
```

And here's how I would inject that service into my resolvers:

```
        public async Task<string> MyResolverMethod([HotChocolate.Service] IMyResolverScopedService service)
        {
            service.DoFancyStuff();
        }
```

**Describe alternatives you've considered**
1) Creating my service as an extension method on IResolverContext. E.g.
```
    public static class ResolverContextExtension
    {
        public static void DoFancyStuff(this IResolverContext context)
        {
            // ...
        }
    }
```

2) Using [field middleware](https://hotchocolate.io/docs/middleware#field-middleware) to manually instantiate my service and storing it as [custom context data ](https://hotchocolate.io/docs/custom-context) in the HotChocolate pipeline.  Then using the CustomContextAttribute and/or StateAttribute to inject the service into my resolvers.

**Additional context**
See the Slack thread here
https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1572531929163100

**Comment by michaelstaib** [comment]
@GoodmanEScott thanks for posting this here so we can explore how we can enable this in a nice way and also sort out the performance aspects here.

**Comment by michaelstaib** [comment]
The resolver context is pooled in 12 and this is not a good object to inject. I would rather create extension methods.
