### ISSUE TITLE
Question:  Can I config a reversed-dependent resolver just like IObjectTypeDescriptor.

### ISSUE THREAD

**Issue by snys98** [ChilliCream/hotchocolate#1185]
Many thanks for your effort! 😄 

I'm trying to use filter with my resolver, but for now, my resolver is `reversed` like this:
```
    [GraphQLResolverOf(typeof(User))]
    [GraphQLResolverOf(typeof(Query))]
    public class UserResolver
    {
        public IQueryable<User> Users([Parent]Query query)
        {
            return new EnumerableQuery<User>(new List<User>());
        }
    }
```
I've noticed that it can be achieved by
```
    public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor.Field("users").UseFiltering();;
            base.Configure(descriptor);
        }
    }
```
will `reversed` resolver be able to achieve it?

**Comment by michaelstaib** [comment]
Hi @snys98,

actually you can use type extensions for that. It is a little different but will still let you use a single resolver.

```
public class QueryTypeExtension : ObjectTypeExtension
{
    protected override void Configure(IObjectTypeDescriptor descriptor) 
    {
        descriptor.Field<UserResolver>(t => t.Users(default)).UseFiltering();
    }
}
```


With type extensions you can decouple parts of your types.

The issue with providing filtering on an attributes base is that with the next version there are so many options with types that are not easily expressible through attributes.

Filtering is a middleware that also manipulates the type itself through the descriptor.

We sill are thinking about things like that...

```
    [GraphQLResolverOf(typeof(User))]
    [GraphQLResolverOf(typeof(Query))]
    public class UserResolver
    {
        [UsePaging]
        [UseFiltering]
        [UseSorting]
        public IQueryable<User> Users([Parent]Query query)
        {
            return new EnumerableQuery<User>(new List<User>());
        }
    }
```

The second concern that I have here is that order is important to middleware. Would people understand that a paging attribute has to come at the top and that an invalid order here could lead to invalid data processing?

**Comment by michaelstaib** [comment]
But it would be cool to have a middleware attribute :) 

@PascalSenn what do you think.

**Comment by snys98** [comment]
Yeah, that's what I want, good for `ObjectTypeExtensions`. Additionally, maybe kind of off topic, actually I'm trying to encapsulate my graphql types and resolvers into different modules(WIP).
![image](https://user-images.githubusercontent.com/11873100/68069109-d4e1cb80-fd96-11e9-9581-b20475209387.png)

And connect them through DI like this:
`startup.cs`
![image](https://user-images.githubusercontent.com/11873100/68069033-1e7de680-fd96-11e9-8e8e-8cbc19db7079.png)

`AppModule.cs`
![image](https://user-images.githubusercontent.com/11873100/68069117-e5924180-fd96-11e9-9ce7-991c97745006.png)


Do you have some plan of making a module system? 😄

**Comment by PascalSenn** [comment]
I'm up for attributes. 
We could do this. 

We might as well consider a way of controlling the execution order of middlewares. 
So that the middlewares could just be attached and control the

**Comment by PascalSenn** [comment]
> Do you have some plan of making a module system? 😄


Not that I would now. We do something similar in one of our projects at work. We basically have builder that composes the repository and the types. 
This will be even easier when there are non generic methods for `UseFiltering`,`UseSorting`, and `UsePageing` #1178

**Comment by michaelstaib** [comment]
@snys98 

> Do you have some plan of making a module system? 😄

So, I do not know AutoFac well enough, but if you are willing to attribute we could introduce autofac packages that basically contain the module system.

**Comment by michaelstaib** [comment]
@snys98 what do you actually mean with module system? you want to collect the types from the di and putt them together?

**Comment by snys98** [comment]
@michaelstaib sorry, I've been outside for days.

> you want to collect the types from the di and putt them together?

yeah, that's it. I want to separate my type&resolver definition to different modules, collect them to di "module by module", and merge them when build the schema.

**Comment by PascalSenn** [comment]
Closing as these attributes are in place 

>This will be even easier when there are non generic methods for UseFiltering,UseSorting, and UsePageing #1178

@snys98  if you are still interestes into `collect them to di "module by module", and merge them when build the schema.` you may open a new issue specific to this :)
