### ISSUE TITLE
More debugging info needed in general - "unable to infer or resolve a schema type from the type reference"

### ISSUE THREAD

**Issue by sellingsolutions** [ChilliCream/hotchocolate#1188]
Hi!

I switched from graphql.net due to hotchocolate having more features and seemingly better documentation.

But one big difference is that I'm getting a lot better debugging info in graphql.net, I find myself getting stuck over and over in HotChocolate.

**I'm able to register some classes just fine and others just fail without any error message beyond:**
```
HotChocolate.SchemaException: Multiple schema errors occured:
Unable to infer or resolve a schema type from the type reference `Input: ...IoProcess
Unable to infer or resolve a schema type from the type reference `Input: ...IoProcessRole
Unable to infer or resolve a schema type from the type reference `Input: ...IoProcess
```

**The types that can't be inferred have been defined below**
```
services.AddGraphQL(sp => Schema.Create(c =>
            {
                c.RegisterServiceProvider(sp);
                c.RegisterQueryType<RootQueryType>();
                c.RegisterMutationType<MutationType>();
                c.RegisterType<Process>();
                c.RegisterType<ProcessType>();
                c.RegisterType<Project>();
                c.RegisterType<ProcessRole>();
                c.RegisterAuthorizeDirectiveType();
            }));
```

**Here's my bare bone process graphql type:**
```
public class Process : ObjectType<IoProcess>
    {
        protected override void Configure(IObjectTypeDescriptor<IoProcess> descriptor)
        {
            descriptor.Name("Process");
            
            descriptor.Field(o => o.Id).Type<LongType>();
            //descriptor.Field(o => o.Name).Type<StringType>();
            //descriptor.Field(o => o.StartsAt).Type<DateTimeType>();
            //descriptor.Field(o => o.EndsAt).Type<DateTimeType>();
            //descriptor.Field(o => o.Type).Type<ProcessType>();
            //descriptor.Field(o => o.Parent).Type<Process>();
            //descriptor.Field(o => o.Roles).Type<ListType<ProcessRole>>();
            //descriptor.Field(o => o.Children).Type<ListType<Process>>();
            
        }
}
```

Any help would be greatly appreciated!

**Comment by sellingsolutions** [comment]
**Having removed my graphql types one by one, I've stumbled upon this:**
```
Application startup exception
System.ArgumentException: Method System.Collections.Generic.IEnumerable`1[....IoActor] GetActorsByDirectRole[TRole]() is a generic method definition (Parameter 'method')
```

I have no idea why HotChocolate is trying to make sense out of methods on classes, is there a way to ignore them?

**This makes no difference**
```
            descriptor.Field(o => o.GetActorsByDirectRole<IoProcessRole>()).Ignore();
```

**Comment by PascalSenn** [comment]
Hi @sellingsolutions 

You can either opt-in or opt-out

By default the fields are infered from the model. (opt-out)
If you would like to ignore a specific field or method just use `descirptor.Ignore(x => x.field)`

You can also opt in 
For this behavior you first need to call  `descriptor.BindFieldsExplicitly()`. This way by default the type is empty.

**Comment by michaelstaib** [comment]
Also the exception that is thrown has more information about which type is affected and why.

If you catch the exception in your debugger then you will be able to the the source schema type that is causing it and other objects.

**Comment by michaelstaib** [comment]
Having that said, we have this on our list for V11 to provide better help text messages.

**Comment by zaneclaes** [comment]
@michaelstaib was this ever improved in any way? I've lost 10+ hours randomly commenting out schema in the past two days, and I still have no idea why it's trying to create an Input object for something which should not even be an input (on version 11.0.9).

**Comment by reinux** [comment]
I'm also trying to put together a barebones program to try to repro another issue I've come across. 

```
  class Message
  {
    public string Text { get; set; }
  }

  class QuitMessage : Message
  {
    public string Reason { get; set; }
  }

  class Robot : User
  {
    public string Bleep { get; set; }
  }

  class User
  {
    public string Name { get; set; }
    public IEnumerable<Message> GetMessages()
    {
      throw new NotImplementedException();
    }
  }

  class QueryType
  {
    public IEnumerable<Message> GetMessages()
    {
      throw new NotImplementedException();
    }
  }

builder.Services.AddGraphQLServer()
  .AddQueryType<QueryType>();
```

Same error:

> 1. Unable to infer or resolve a schema type from the type reference `Output: QueryType`.

As an aside, the problem I'm getting, using EntityFramework, is that doing `User.GetMessages` with `UseProjection` doesn't return any inherited messages (e.g. `QuitMessage`). But then when I try to override it using `[BindMember(nameof(User.GetMessages))]` in an extension, I would get an error like this instead:

>       1. The field `messages` must be implement by object type `Robot`. (HotChocolate.Types.ObjectType<HotChocolateTest.Robot>)

Until I can figure out why the barebones implementation is failing, I can't repro the actual problem I'm having in my project.

**Comment by michaelstaib** [comment]
We are constantly making this better... with 12 we added even more context to errors. I am closing this since we consider it an ongoing effort.

**Comment by ermaugustinas** [comment]
@LeotrimThor Did you manage to resolve it?

**Comment by LeotrimThor** [comment]
Idk what to say, maybe half of it. 
I didn't knew that the order really matters when I added the graphql components when I created my schema. Now the server came back and I can run all the queries I have but when I put [Authorize] on any method in my graphql resolver, it says "The current user is not authorized to access this resource." even if I try with logged in user with or without permissions or even without logging in...

Should I paste my Program.cs here so maybe you can help me figure out what am I missing or post it in a github repo?

**Comment by ermaugustinas** [comment]
@LeotrimThor github repo would the best, I'm encountering the same problem, maybe I can workout what's the common issue

**Comment by cli00004** [comment]
same issue here
