### ISSUE TITLE
Compiled Filters

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1198]
Currently we recreate filters every time a request is executed. This is not very efficient. We should instead compile these filters to get a parametrised expression where each variable is converted to a expression parameter. These expressions should be cached and reused. 

**We first have to do execution plans in order to see how this fits in**

**Comment by PascalSenn** [comment]
Hm.. 
Is there an example of this? 
A paramterised expression could be a few things :D
