### ISSUE TITLE
Filter Attributes

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1200]
it should be possible to add filters and sorting to a resolver without having to override the 
```csharp
    [GraphQLResolverOf(typeof(User))]
    [GraphQLResolverOf(typeof(Query))]
    public class UserResolver
    {
        [UsePaging]
        [UseFiltering]
        [UseSorting]
        public IQueryable<User> Users([Parent]Query query)
        {
            return new EnumerableQuery<User>(new List<User>());
        }
    }
```

- [ ] Add test case for #1119

**Comment by drowhunter** [comment]
I like this and yea it should be possible HOWEVER
 this handles a use case.

But what if I have a shared resolver that returns an Iqueryable

but I want to control the filtering/sorting on the Type level.

eg.  When used from Type A Use Sorting
when used from type b use Filtering.

you get what im saying this use case could apply to any middleware where I dont necessarilty want to define what behavior the resolver should have globally.

**Comment by PascalSenn** [comment]
@drowhunter  
In this case the filters have to be registered on the resolver level on the parent type.

**Comment by PascalSenn** [comment]
Note to myself: Add a test case for  
#1119
``` 
public class FooType : ObjectType<Foo>
{
    protected override void Configure(IObjectTypeDescriptor<Foo> descriptor)
    {
        descriptor.Include<SharedResolver>();
         //this is allowed
        descriptor.Field(f => f.Bar()).UseFiltering();
        
        //this is not
        descriptor.Field<SharedResolver>(f => f.Bar()).UseFiltering();
    }
}```

**Comment by michaelstaib** [comment]
@drowhunter I have added the following issue which should fix this https://github.com/ChilliCream/hotchocolate/issues/1207. I will have a look at the impact tomorrow. If we can do it on V10 then we will issue another patch release for you.

**Comment by drowhunter** [comment]
Awesome.
