### ISSUE TITLE
DiagnosticObserver breaks Subscriptions

### ISSUE THREAD

**Issue by barrettg** [ChilliCream/hotchocolate#1204]
**Describe the bug**
I added a DiagnosticObserver to my project to help debug some queries and I found that my subscriptions stopped firing when I did so.  I followed the example code for the ASP.NET ILogger example:
https://github.com/ChilliCream/hotchocolate-examples/blob/master/Instrumentation/DiagnosticObserver.cs

**To Reproduce**
1. Clone StarWars example project
2. Add DiagnosticObserver.cs from link above
3. Add `services.AddDiagnosticObserver<DiagnosticObserver>();` to `ConfigureServices()` in `Startup.cs`
4. The `onReview` subscription event will not fire (in Playground)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .Net Core 3.0
- HotChocolate 10.2.0

**Comment by michaelstaib** [comment]
Hi @barrettg,

did it stop firing by just adding it? 
Or did it stop while debugging it with breakpoints?

**Comment by barrettg** [comment]
I am not debugging the application, running it detached.  It seems that both Kestrel and IIS are effected.  I dove into the code a bit more this morning and it seems to specifically be this function that is blocking the events:
```
        [DiagnosticName("HotChocolate.Execution.Query.Stop")]
        public void EndQueryExecute(IQueryContext context)
        {
            using (var stream = new MemoryStream())
            {
                var resultSerializer = new JsonQueryResultSerializer();
                resultSerializer.SerializeAsync(
                    (IReadOnlyQueryResult)context.Result,
                    stream).Wait();
                _logger.LogInformation(
                    Encoding.UTF8.GetString(stream.ToArray()));
            }
        }
```
If I comment this block out but leave the rest of the observer code, the events will fire.  Unfortunately, I am new the library and do not know enough about what is happening the diagnose any further.

**Comment by michaelstaib** [comment]
ah, are you using .net core 3.0?

**Comment by michaelstaib** [comment]
because you cant do the wait there ...

**Comment by michaelstaib** [comment]
So you basically want the json representation of the result. Let me check something.

**Comment by barrettg** [comment]
> ah, are you using .net core 3.0?

Yes.



> So you basically want the json representation of the result. Let me check something.

I was just following the example @ https://github.com/ChilliCream/hotchocolate-examples/tree/master/Instrumentation

Maybe that just needs to be updated for Core 3?

**Comment by michaelstaib** [comment]
@barrettg I will have a look at the example.

**Comment by psobanski** [comment]
I have similar issue.
We want to log all errors so we added diagnostic observer as @barrettg: 
`services.AddDiagnosticObserver<DiagnosticObserver>();` and it was working.
Now we want add metadata to returned errors from query and mutation, so we changed GraphQl registration (check attached file with working and broken code)

// Before - Diagnostic was working

```
services.AddGraphQL(
                sp =>
                    SchemaBuilder.New()
                        .AddServices(sp)
                        .AddQueryType<QueryType>()
                        .RegisterMutations()
                        .Create(),
                new QueryExecutionOptions
                {
                    ExecutionTimeout = TimeSpan.FromMinutes(3),
                    TracingPreference = TracingPreference.OnDemand
                });
services.AddDiagnosticObserver<ExceptionDiagnostic>();

```
//After - Diagnostic does not work

```
services.AddGraphQL(
	sp =>
	SchemaBuilder.New()
			.AddServices(sp)
			.AddQueryType<QueryType>()
			.RegisterMutations()
			.Create(),
	build =>
	{
		var options = new QueryExecutionOptions
		{
			ExecutionTimeout = TimeSpan.FromMinutes(3),
			TracingPreference = TracingPreference.OnDemand
		};

		build
			.AddOptions(options)
			.AddErrorFilter(error =>
			{
				if (error.Exception is NotImplementedException)
				{
					return ErrorBuilder.FromError(error)
						.SetCode("404")
						.Build();
				}

				return error;
			})
			.UseDefaultPipeline()
			// I tried to register Diagnostic in here with no luck
			//.AddDiagnosticObserver<ExceptionDiagnostic>()
			;
	}
);

services.AddDiagnosticObserver<ExceptionDiagnostic>();
```

Did I something wrong?

**Comment by michaelstaib** [comment]
We completely reworked the instrumentation API for HotChocolate. I will close this issue now since it no longer exists.
