### ISSUE TITLE
Review DataLoader v2.0

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1208]
Lee just tweeted that there will be a new DataLoader spec version tomorrow. We will have to review that and decide how it fits in with execution plans.

**Comment by PascalSenn** [comment]
The blog post: https://medium.com/@leeb/dataloader-v2-0-925b4dccf8d6

The release note : https://github.com/graphql/dataloader/releases/tag/v2.0.0

**Comment by michaelstaib** [comment]
This one is done.
