### ISSUE TITLE
GraphQL Playground cannot be hosted on the root `/`

### ISSUE THREAD

**Issue by leebenson** [ChilliCream/hotchocolate#1209]
**Describe the bug**

The GraphQL Playground cannot be mounted to the `/` root route.

An exception is thrown:

> An exception of type 'System.ArgumentException' occurred in Microsoft.AspNetCore.StaticFiles.dll but was not handled in user code: 'Request path must not end in a slash'

**To Reproduce**

```csharp
using HotChocolate.AspNetCore.Playground;

app.UsePlayground(new PlaygroundOptions
{
  QueryPath = "/graphql",
  Path = "/"
});
```

**Expected behavior**

For the Playground to be mounted to the root, and no exception to be thrown.

**Desktop (please complete the following information):**
 - HotChocolate.AspNetCore.Playground 10.2.0

**Comment by krishnakumarb** [comment]
I have this workaround to redirect `/` to `/playground`

```cs
app.UseRewriter(
  new RewriteOptions()
    .AddRedirect("(?i)^graphiql/*$", "playground")
    .AddRedirect("^$", "playground"));
```

**Comment by michaelstaib** [comment]
We are removing playground and are replacing it with banana cake pop in the next few preview builds for 11.
