### ISSUE TITLE
StrawberryShake / new Generator Flag[s]: Visibility

### ISSUE THREAD

**Issue by mbauerdev** [ChilliCream/hotchocolate#1214]
When writiting my first StrawberryShake client I faced the issue to be backward-compatible for the current clients. I thought it would be a nice feature, if I could toggle the visibility of the generated classes between "public" and "internal" (as gRPC does it, for example).

Maybe "berry.json" could be used to configure the behaviour. Certainly, "public" should be the default visibility.

**Comment by michaelstaib** [comment]
This flag needs to go in the new GraphQL config.
