### ISSUE TITLE
Upgrading from 10.1.1 to 10.2.0 input type error EXEC_INVALID_TYPE

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#1216]
**Describe the bug**
Upgraded to 10.2.0 and suddenly my mutations give me the following error

**To Reproduce**
```
{
	"errors": [{
		"message": "Variable `$input` got invalid value.",
		"locations": [{
			"line": 1,
			"column": 16
		}],
		"extensions": {
			"code": "EXEC_INVALID_TYPE",
			"remote": {
				"Exception": null,
				"message": "Variable `$input` got invalid value.",
				"locations": [{
					"line": 1,
					"column": 16
				}],
				"extensions": {
					"code": "EXEC_INVALID_TYPE"
				}
			}
		}
	}],
	"data": {
		"addUserBloodSugarTrackerDataPoint": null
	}
}
```

**Additional context**
Rolling back to 10.1.1 fixes the issue

**Comment by michaelstaib** [comment]
Can you provide more information mouth here. With 10.2 we fixed a validation bug, that mean variables now have to be of the correct type. Before that we were allowing eg ints for strings.

**Comment by drowhunter** [comment]
I have an object called input which is a custom poco class
```
public class AddWeightTrackerGoalInput
    {
        public double BodyWeight { get; set; }
        public int WeightUnit { get; set; }
    }
```
which has the following Type defined and registered
```
public class AddWeightTrackerGoalInputType : InputObjectType<AddWeightTrackerGoalInput>
    {
        protected override void Configure(IInputObjectTypeDescriptor<AddWeightTrackerGoalInput> descriptor)
        {

        }
    }
```
the query looks like this
```
"mutation ($input: AddWeightTrackerGoalInput) {
  addWeightTrackerGoal(input: $input) {
    ... fragment
  }
}
"
```
The Input is defined as 
![image](https://user-images.githubusercontent.com/2817488/69241587-192de380-0b6d-11ea-9920-0cea125be34d.png)

and the input variable passed is like
```
{
"input":{"bodyWeight": 80, "weightUnit": 2, dateOfEntry: "2019-11-20T13:02:58.939Z"}
}
``

**Comment by michaelstaib** [comment]
Can you trace out the query that is send between the gateway and the domain service?

**Comment by drowhunter** [comment]
im actually not using the gateway.  I went directly to the api itself to run the query
the example i passed earlier wasnt that great I was on my phone.  Here is a better example of what isn't working

![image](https://user-images.githubusercontent.com/2817488/69257893-cadb0d80-0b89-11ea-9e7b-7e26197f7206.png)

**Comment by drowhunter** [comment]
Actually looks like we are passing decimals to a parameter that is expecting Int.  I assume that in the previous version you were not actually validating these fields

**Comment by michaelstaib** [comment]
@drowhunter yeah that's it. The spec defines that you can put an int into a float but not the reverse way. We now enforce these rules.

**Comment by michaelstaib** [comment]
I will close this issue since this is now working as expected.
