### ISSUE TITLE
GraphQLNonNullType leads to SchemaException in combination with UseFiltering 

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1222]
**@pmbanugo reported this:**

>I have a ` [GraphQLNonNullType]` attribute on a property of string type. I’m applying UseFiltering and I get an error
Unhandled exception. HotChocolate.SchemaException: Unable to resolve type reference `Input: HotChocolate.Types.ListType<HotChocolate.Types.NonNullType<HotChocolate.Types.NativeType<System.String>>>`

>I don’t know why that breaks. If I remove the attribute I don’t get that error. and it’s because I applied UseFiltering

>Once I apply UseFiltering I get the error I posted. Without UseFiltering it works
>something with that attribute

**Workaround** 

>What I did to fix that was to switch to
[GraphQLType(typeof(NonNullType<StringType>))] attribute

>so I think it’s a bug. Because if I read it the other way, it uses the string clr type and throws an error, but changing to the other way solved it for me
I could file an issue if that’s a bug with the attribute

**Repo Repo:** 
https://github.com/PascalSenn/graphql-intro-aspnet-core

**Comment by michaelstaib** [comment]
We should retest this with preview 11

**Comment by michaelstaib** [comment]
This one works with 10.3.0-preview.14 and is under test with 11.0.0
