### ISSUE TITLE
Refactor the resolver to use ValueTask instead of Task.

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1223]
Many of the resolvers are actually resolving there data synchronously, so, we should enable the middleware and resolver to use ValueTask<T> over Task<T>.

**Comment by PascalSenn** [comment]
If anyone reads this issue and wonders what value tasks are, there's a great resource for this: 
https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/
