### ISSUE TITLE
Sorting does not work with BindingBehavior.Explicit

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1242]
From Alessandro Balasco

>Hi and first of all thanks for the incredible work! I have a problem with Sorting. I installed the HotChocolate.Types.Sorting package, and then enabled sorting on a query, by simply calling UseSorting(). The same query has already filtering and pagination and it works flawlessly. When I start the application I get HotChocolate.SchemaException: The enum type SortOperationKind has no values. - Type: SortOperationKind . I tried to disable Pagination and filtering without luck. I also tried to extend SortInputType and to use it as type parameter for UseSorting, but again i got the same error. What am I doing wrong? Thanks!

this is the relevant snippet in my Startup
```csharp
services.AddGraphQL(sp => SchemaBuilder.New()
                .AddServices(sp)
                .AddQueryType<ApiQueryType>()
                .AddMutationType<ApiMutationType>()
                .ModifyOptions(t => t.DefaultBindingBehavior = BindingBehavior.Explicit)
                .Create());
```
and this is what happens in my ApiQueryType:

```csharp
            descriptor.Field("sites")
                .Type<ListType<NonNullType<SiteType>>>()
                .Resolver(ctx => ctx.Service<SiteRepository>().GetQuery())
                .UsePaging<SiteType>()
                .UseFiltering<SiteFilterType>()
                .UseSorting();

```

**Comment by michaelstaib** [comment]
This one is fixed
