### ISSUE TITLE
Queryable Projection Middleware

### ISSUE THREAD

**Issue by TheJayMann** [ChilliCream/hotchocolate#1254]
I've seen a few issues here and there aiming to take the submitted query and convert it to an expression which can be used with the Queryable.Select method, as a way to only pull from the datasource the properties requested, though, from what I can see, the attempts are either abandoned, or were not made publicly available.  I have made an attempt myself, which, while not complete, appears to work for what I will need to do with it, located at [TheJayMann/HotChocolate](https://github.com/TheJayMann/HotChocolate).  My testing of this exclusively uses Entity Framework Core, and uses an initial projection from entity types to query types such that the Include method is not needed, the select expression is simpler to generate, and the graphql schema is kept separate from the data source schema.

I've submitted the work I've done to GitHub in case it is helpful for others, in case anybody knows a simpler way to do some of the things I've done, as I mostly built this by studying debugger state, decompilation, and GitHub source, and if there is any desire to eventually pull this in as an official assembly/package.

**Comment by michaelstaib** [comment]
I will look into it tomorrow. Thank you for posting this

**Comment by PascalSenn** [comment]
@TheJayMann  can this be closed? 🤘🤘

**Comment by TheJayMann** [comment]
Yes
