### ISSUE TITLE
GraphQLResolverOf not working as expected with code-first

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#1255]
**Describe the bug**
I expect to be able to use `GraphQLResolverOf` as described in the docs here: https://hotchocolate.io/docs/resolvers#resolver-types

1. If you have two attributes `GraphQLResolverOf ` on a file, it throws here https://github.com/ChilliCream/hotchocolate/blob/d5595996a6baf1dcd948174cacc6d078af48fa60/src/Core/Types/Configuration/TypeInitializer.cs#L288-L289

2. This snapshot seems wrong as the query clearly doesn't contain the logic from the new resolver: https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types.Tests/__snapshots__/SchemaBuilderTests.AddType_TypeIsResolverTypeByType_QueryContainsBazField.snap

3. The operation in a simple case (shown below) doesn't work:

```CSharp
public class QueryRoot
{
  // ...
}

[GraphQLResolverOf(typeof(QueryRoot))]
public class QueryRootResolvers
{
  public string GetTestString => "foobar";
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
                // ...
		services.AddGraphQL(
                    schemaFactory: sp => SchemaBuilder.New()
			// ...
			.AddQueryType<QueryRoot>()
                        .AddType<QueryRootResolvers>()
               // ...
    }
}

```

**Expected behavior**
Expected `QueryRoot` to have a new field `TestString`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.3.0-preview5

**Comment by michaelstaib** [comment]
I have checked this one now and it works like the following:

```csharp
[GraphQLResolverOf(typeof(QueryType))]
public class QueryResolverOnType
{
    public string GetFoo([Parent]object o) => "QueryResolverOnType";
}
```

```csharp
[GraphQLResolverOf("Query")]
public class QueryResolverOnName
{
    public string Baz { get; }
}
```

So, the type has to be a schema type. 

The question is if this is still a useful feature? This feature dates back to the pre SchemaBuilder versions of HC.

My gut feeling is that we should deprecate it and move to introduce type extension descriptor attributes.

```csharp
[ExtendObjectType("Query")]
public class QueryResolverOnType
{
    public string GetFoo([Parent]object o) => "QueryResolverOnType";
}
```

The attribute would mark this type an extension of a specific type.

what do you guys think? @tunurgitr @PascalSenn

**Comment by michaelstaib** [comment]
Also just as a side note to this. With version 11 there is already now support for the extensions like in 10 and then there are type interceptors which lets you intercept the type initialization on a broader scale. With that you can do things like ... for all types that have an `Id` field make the field of type `Uuid` and things like that.

https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types/Configuration/TypeInitializationInterceptor.cs

**Comment by tunurgitr** [comment]
My vote is for deprecating this in favor of the other ways of extending types...personally I think it's better to be more opinionated here unless there's some compelling reason to stick with this other behavior.

**Comment by michaelstaib** [comment]
I agree with you. The `GraphQLResolverOfAttribute` is I think fully replaced by our new ways to extend things.

OK, I will move this issue to 11 and we will deprecate it there.

We can then start removing it with version 12.

**Comment by michaelstaib** [comment]
So, I have marked this as a bug and will close it and create a follow up issue that will deprecate it.

**Comment by michaelstaib** [comment]
#1298
