### ISSUE TITLE
Schema-First: Default Value in input object

### ISSUE THREAD

**Issue by husseinraoouf** [ChilliCream/hotchocolate#1278]
**Is your feature request related to a problem? Please describe.**
I often need to set default value to on field in a large input object, currently there is no way to do that

I am not sure but i think the spec allow to do it like this 
```graphql
input ExampleInput {
  value: Int = 0
  another: String
}
```

**Describe the solution you'd like**
i would like to define default value like the example above

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelstaib** [comment]
This should already work. 

I will have a look and write some tests for this.

**Comment by jacobjmarks** [comment]
Any updates on this one?

**Comment by kamoclav** [comment]
Any update on this? I have a similar problem with  public System.Guid Id { get; set; } = System.Guid.NewGuid();

**Comment by michaelstaib** [comment]
This works. But `System.Guid.NewGuid()` is not a valid GraphQL default value. GraphQL default values are constants. You can still handle such logic in your resolver.

**Comment by michaelstaib** [comment]
For something like Guid.NewGuid() handle it in the resolver:

```csharp
public class Query
{
    public Guid GetBook(BookInput input) => input.Id ?? Guid.NewGuid();
}

public class BookInput
{
    public DynamicDefaultValueInput(Guid? id)
    {
        Id = id;
    }

    public Guid? Id { get; }
}
```

You could also create a custom directive if you want that to be automatically done by a middleware and reflected in the schema.

```graphql
input BookInput {
  id: UUID @newGuidIfNotSet
}
```

If you want to go down the latter give me a ping and I post how this can be done.

**Comment by michaelstaib** [comment]
Closed since the original issue was fixed with the initial work of version 12.
