### ISSUE TITLE
Variables parsing: Variables parsed within comments

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#1282]
**Describe the bug**
Comments in queries that reference variables are being parsed when delegating to remote schemas, maybe other situations.

**To Reproduce**
1. Have a query with a variable in the comments
```gql
productByNumber(productNumber: $crossSellProductNumber)
      	@include(if: true) { #TODO: use this  $getCrossSellProduct
        summary {
          ...
```

2. Execute the query
3. Get an error response about `getCrossSellProduct` not being defined

**Expected behavior**
Variables in comments should be ignored

**Comment by michaelstaib** [comment]
Interesting :)
