### ISSUE TITLE
Issue with variables not being set if property of object in array.

### ISSUE THREAD

**Issue by dlebee** [ChilliCream/hotchocolate#1287]
# Issue
When using query variables that are part of an array it does not set the variables.

# Source code of the issue
https://github.com/dlebee/HotChocolateIssue/

# Example of a query

```graphql
query blah($message1:String, $message2: String)
{
  contact(criteria: {
    messages: [
      { 
          message:$message1
      },
      {
          message: $message2
      }
    ]
  })
}
```

> the variables

```json
{
    "message1": "hello",
    "message2": "world"
}
```

Received Value

```json
{
  "data": {
    "contact": [
      null,
      null
    ]
  }
}
```

Expected value

```json
{
  "data": {
    "contact": [
      "hello",
      "world"
    ]
  }
}
```

# Versions 

It happens in both 10.2.0 and 11.0.0 preview latest.

**Comment by michaelstaib** [comment]
@PascalSenn can you write a test for this so we can check out what is wrong?

**Comment by michaelstaib** [comment]
@dlebee  Awesome just saw the linked repo :D thanks for this repro! We will work on this one tonight.

@PascalSenn this one has nothing todo with filters... my fault ;)

**Comment by dlebee** [comment]
@michaelstaib only normal :)

**Comment by michaelstaib** [comment]
This one is now fixed

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/commit/1b0efcbf081cb9dcaea35289d9d0ab62d96ce53d

**Comment by dlebee** [comment]
@michaelstaib thank you :)
