### ISSUE TITLE
ContextData resets between local Schema and root query

### ISSUE THREAD

**Issue by JekPoint** [ChilliCream/hotchocolate#1290]
**Describe the bug**
Stiching drop ContextData in to local schema

**To Reproduce**
Create stiching and local schema
AddAuthorizeDirectiveType
add .Authorize() to ObjectType<Query>
Authorize not working

**Expected behavior**
Authorize work

**Desktop (please complete the following information):**
 - current

**Additional context**
ContextData resets in localSchema
Example to fix in startup.cs -> ConfigureServices(IServiceCollection services)

 IDictionary<string, object> tempContextData = new Dictionary<string, object>();

            services.AddStitchedSchema(builder => builder
                .AddSchemaFromHttp("pim")
                .AddSchema("local", SchemaBuilder.New()
                    .AddType<Query>()
                    .AddQueryType<QueryType>()
                    .AddType<SearchItemType>()
                    .AddType<SearchRequestInputType>()
                    .AddType<SearchResponseType>()
                    .AddType<AutocompleteType>()
                    .AddType<AutocompleteItemType>()
                    .AddAuthorizeDirectiveType()
                    .Use(next => context =>
                    {
                        foreach (var (key, value) in tempContextData)
                        {
                            if (!context.ContextData.ContainsKey(key))
                            {
                                context.ContextData.Add(key, value);
                            }
                        }
                        return next.Invoke(context);
                    })
                    .Create())
                
                .AddSchemaConfiguration(c =>
                {
                    c.RegisterExtendedScalarTypes();
                })
                .AddExecutionConfiguration(b =>
                {
                    b.Use(next => async context =>
                    {
                        tempContextData = context.ContextData;
                        await next.Invoke(context); 
                    });
                    b.AddErrorFilter(error =>
                    {
                        if(error.Exception is HttpRequestException httpRequestException && httpRequestException.Message.Contains("Unauthorized"))
                        {
                            return error.WithCode("401");
                        }
                        return error.AddExtension("STITCH", "pim");
                    });
                })
            );

**Comment by michaelstaib** [comment]
This solution cannot work since there are multiple different scopes at work here. The solution for this is that we allow the context to be passed to the remote executor. We have this already on our list for 10.3.0
