### ISSUE TITLE
Endpoints authorization for queries/mutations splitted to files

### ISSUE THREAD

**Issue by micnyk** [ChilliCream/hotchocolate#1292]
Hi,
I'm using `GraphQLResolverOf` and `GraphQLResolver` attributes to organize queries/mutations into separate files.

```
  // FooQuery.cs
  [GraphQLResolverOf(typeof(Query))]
  public class FooQuery
  {
      public Task<string> Bar() { }
  }
  
  // Query.cs
  [GraphQLResolver(typeof(FooQuery))]
  [GraphQLResolver(typeof(OtherQuery))]
  public class Query
  {
  }

```
How could I configure the `Query` fields to authorize users? When the query is not splitted, I use `ObjectType<Query>` class and in override of `Configure` method I can easily use `IObjectFieldDescriptor.Authorize` method to do it. But how to do that in case of splitted query?

**Comment by michaelstaib** [comment]
You could use our type extensions:
https://hotchocolate.io/docs/schema-object-type#extension

**Comment by michaelstaib** [comment]
Version 10.3 will also bring auth attributes

**Comment by micnyk** [comment]
@michaelstaib could you please provide me some working example? Because as I understood
```
public class PersonTypeExtension
    : ObjectTypeExtension
{
    protected override Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Name("Person");
        descriptor.Field("address")
            .Type<NonNullType<StringType>>()
            .Resolver(/"Resolver Logic"/);
    }
}
```
requires to provide `Resolver Logic` in `Resolver` method. My Resolver Logic is quite complex class with a few injected services. And my goal is to have those many complex classes separated in files by domain.
It works fine using `GraphQLResolverOf`, `GraphQLResolver` attributes except I have no idea how to configure authorization in this way.
Is it even possible? Or should I use schema stitching?

**Comment by michaelstaib** [comment]
If you use the newest preview you now have generic extensions:

```csharp
public class QueryTypeExtension
    : ObjectTypeExtension<FooQuery>
{
    protected override Configure(IObjectTypeDescriptor<FooQuery> descriptor)
    {
        descriptor.Name("Query");
        descriptor.Field(t => t.Bar).Authorize("Policy");
    }
}
```

**Comment by michaelstaib** [comment]
The auth attributes are not yet in the preview but it will look like the following:

```csharp
 [ExtendObjectType("Query")]
 public class FooQuery
  {
      [Authorize("Policy")]
      public Task<string> Bar() { }
  }
```
