### ISSUE TITLE
"The specified argument value does not match the argument type" in star wars example human query

### ISSUE THREAD

**Issue by christianMurschall** [ChilliCream/hotchocolate#1294]
**Describe the bug**
The `id` argument in the docs state an `integer` while it is in fact a `string`. 

**To Reproduce**
Go to `http://localhost:port/graphql/playground/` and insert the following query according to the  [docs](https://hotchocolate.io/docs/example-star-wars-code-first). 
```
{
  human(id: 1000) {
    name
    appearsIn
    friends {
      name
      appearsIn
    }
  }
}
```

**Expected behavior**

I would expect to see a human object, but I get:
```
{
  "errors": [
    {
      "message": "The field `name` does not exist on the type `CharacterConnection`.",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ]
    },
    {
      "message": "The field `appearsIn` does not exist on the type `CharacterConnection`.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ]
    },
    {
      "message": "The specified argument value does not match the argument type.\nArgument: `id`\nValue: `1000`",
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ]
    }
  ]
}
```
The correct query must be:
```
{
  human(id: "1000") {
    name
    appearsIn
   	friends {
        nodes {
          name
          appearsIn
      }
    }
  }
}
```
notice the **nodes** property in the `friends` field.

**Desktop (please complete the following information):**
 - OS: [Windoes ]
 - Version [10]

**Comment by fpaul787** [comment]
Hello, would someone be able to point to the solution of this issue?

**Comment by sourcecode71** [comment]
In HotChocolate v12, DependecyInjection included in the ResolverWith method assumes all parameters as an Argument.
Can check this document 
https://chillicream.com/docs/hotchocolate/fetching-data/resolvers#arguments
