### ISSUE TITLE
Deprecate GraphQLResolver / GraphQLResolverOf attributes

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1298]
- [ ] Mark as deprecated
- [ ] Remove Documentation
- [ ] Introduce new documentation that shows the new ways of doing this.

**Comment by michaelstaib** [comment]
#1255

**Comment by benmccallum** [comment]
It doesn't look like `[ExtendObjectType]` has an equivalent for `[GraphQLResolverOf(types/typeNames)]` (at least on 10.5) as the attribute is restricted to only one usage on a class.

I'd really love support for `[ExtendObjectType(typeof(IAuditable))]`, e.g. extend all types that implement `IAuditable`. As then you can do crazy cross-cutting things like:
```c#
public interface IReturnsBooking { int BookingId { get; } }
public class CreateBookingOutput : IReturnsBooking { ... }
public class EditBookingOutput : IReturnsBooking { ... }

//[ExtendObjectType(Name = nameof(CreateBookingOutput))]
//[ExtendObjectType(Name = nameof(EditBookingOutput))] // second one doesn't work
[ExtendObjectType(typeof(IReturnsBooking))]
public class ReturnsBookingResolvers
{
    public Task<Booking> GetBooking([Parent] IReturnsBooking output) 
        => bookingDataLoader.LoadAsync(output.BookingId);
}
```

**Comment by benmccallum** [comment]
So to add onto your list:

- [ ] Support `AllowMultiple` with `[ExtendObjectType]`
- [ ] Support `[ExtendObjectType(typeof(ISomeBase))]`

**Comment by michaelstaib** [comment]
> I'd really love support for [ExtendObjectType(typeof(IAuditable))], e.g. extend all types that implement IAuditable. As then you can do crazy cross-cutting things like:

That`s a cool idea and it is easy to implement. Can you add that to a separate issue and I will fast track it to 11.

**Comment by tobias-tengler** [comment]
They have been deprecated for v12 and their replacement `ExtendObjectType` has been covered by the documentation.
