### ISSUE TITLE
Prevent fields from underlying type being exposed to schema

### ISSUE THREAD

**Issue by grounzero** [ChilliCream/hotchocolate#1314]
If I create a type from an underying entity type that is mapped to a db and only wish expose a limited number of property resolvers how do I go about this?  

I have declared a type like so and only wish to expose the fields provided to the type descriptor but it seems every property on the underlying type is added to the schema and I can't find out how to prevent this behaviour.

```
 public class ScheduleInputType
        : InputObjectType<Schedule>
    {
        protected override void Configure(IInputObjectTypeDescriptor<Schedule> descriptor)
        {
            base.Configure(descriptor);

            descriptor.Field(t => t.SequenceNo).Type<NonNullType<IntType>>();
            descriptor.Field(t => t.SessionType).Type<NonNullType<StringType>>();
            descriptor.Field(t => t.SessionTitle).Type<StringType>();
            descriptor.Field(t => t.StartDateTime).Type<NonNullType<DateTimeType>>();
        }
    }
```

**Comment by michaelstaib** [comment]
You can either set the type to declare fields explicitly or you can set the whole schema to explicit.

descriptor.BindFieldsExplicitly().

Or

SchemaBuilder.New()
    .ModifyOptions(o => o.DefaultBindinigBehav...

**Comment by grounzero** [comment]
Thanks, seems so obvious now

**Comment by michaelstaib** [comment]
you can also ignore things ... descriptor.Ignore(t => t.FieldToIgnore)
