### ISSUE TITLE
[UseFiltering] type or namespace not found in most recent 10.3 packages 

### ISSUE THREAD

**Issue by clmcgrath** [ChilliCream/hotchocolate#1315]
**Describe the bug**
The recently added feature [UseFiltering] attribute is not resolving with latest rc.0 packages on nuget see [documentation](https://hotchocolate.io/docs/descriptor-attributes)

**To Reproduce**
install Hotchocolate 10.3-rc.0 
add [UseFiltering] to property or type 
build 

**Expected behavior**
Type should be found in rc quality release

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 10.3-rc.0]

**Additional context**
Not sure if documentation was released early and package isn't up yet , or the package is broken 
according to release notes this should be in 10.3.0-preview.3 and later

**Comment by michaelstaib** [comment]
Hi,

yes we found that issue and it will be fixed in the rc.1 build.
