### ISSUE TITLE
Subscription authorization

### ISSUE THREAD

**Issue by Alan5142** [ChilliCream/hotchocolate#1319]
I have a question, how can I use authorization in subscriptions?
Below is my app configuration 
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseStaticFiles();
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseSpaStaticFiles();
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }


    app.UseAuthentication();
    app.UseAuthorization();

    app.UseRouting();
    app.UseWebSockets()
        .UseGraphQL("/api/graphql/")
        .UsePlayground("/api/graphql/")
        .UseGraphQLSubscriptions(new SubscriptionMiddlewareOptions
        {
            Path = "/api/graphql/"
        });
    app.UseHangfireDashboard();

    app.UseEndpoints(endpoints =>
    {
        // Mapping of endpoints goes here:
        endpoints.MapControllers();
    });

    app.UseSpa(spa =>
    {
        spa.Options.SourcePath = "web-app";
        if (env.IsDevelopment())
        {
            spa.UseAngularCliServer(npmScript: "start");
        }
    });
}
```

Authorization works in Query and Mutation but in Subscription ```ClaimsPrincipal``` doesn't exist, so I think the token is not being sent to the server.

#### Subscription user is not authorized
![imagen](https://user-images.githubusercontent.com/13205973/71605594-a599d180-2b2f-11ea-9a41-d237b2240633.png)

#### Mutation authorization
![imagen](https://user-images.githubusercontent.com/13205973/71605658-48eae680-2b30-11ea-8663-851f04eed5a4.png)

**Comment by michaelstaib** [comment]
Authentication over web sockets works differently, read the following issue on ASP.NET Core for more infos:

https://github.com/aspnet/AspNetCore/issues/2881

**Comment by AlonsoHernandez99** [comment]
@Alan5142 did you solved authentication implementation in Subscription?

**Comment by Alan5142** [comment]
@AlonsoHernandez99 IIRC I sent the authorization code in the query string but ain't secure. You can send the token in a header, keep in mind that you need to handle this in a custom ```JwtBearerEvents```
