### ISSUE TITLE
Add a way to enable authorization on all properties

### ISSUE THREAD

**Issue by husseinraoouf** [ChilliCream/hotchocolate#1321]
**Is your feature request related to a problem? Please describe.**
I am building an api with hotchocolate and one of the feature i use is the `@authorize` directive
currently most of the queries and mutations require a user so i have to repeat @authorize in front of most of the queries and mutations

**Describe the solution you'd like**
it would be better if i can make authorization enabled by default on all queries and mutations and introduce a new directive that remove the authorization on specific query or mutation

**Comment by michaelstaib** [comment]
We are at the moment thinking about authorize on the schema

**Comment by tobias-tengler** [comment]
In v11 we can do the following to require authorization for all operations.

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL().RequireAuthorization();
});
```
