### ISSUE TITLE
InputType Argument: wrong double number

### ISSUE THREAD

**Issue by giangcoi48k** [ChilliCream/hotchocolate#1323]
My query has a paramter of InputType
![image](https://user-images.githubusercontent.com/12107588/71675110-ab054f00-2daf-11ea-9c40-87570085c095.png)
When I passed my paramter: `from: 2666666666`, I got value `2666667000M`, mean the number which longer than 7 digit was rounded. This caused my query to get wrong results. Is there any way to solve this problem? Sorry for my bad English!

**Comment by michaelstaib** [comment]
If you use the decimal type. System.Decimal in combination with DecimalType

**Comment by giangcoi48k** [comment]
@michaelstaib but when I passed value 2666666666, I got value 2666667000. The value received is not equal to the input value. The 8th digit will be rounded

**Comment by giangcoi48k** [comment]
@michaelstaib hi, any solution to solve this problem?

**Comment by michaelstaib** [comment]
This is actually a bug in the way we coerce variables. I just wrote a test to check it out. We will fix this with the upcoming version 11. I will give you a ping once the fix is available as preview.

**Comment by michaelstaib** [comment]
we might issue a hot fix since we found another issue with 10.3 ... we are discussing it at the moment.... I will keep you in the loop.

**Comment by giangcoi48k** [comment]
Hi. Any fix on this bug? My project is in dire need of a fix for this bug...

**Comment by michaelstaib** [comment]
have you tried 10.3.5?

**Comment by giangcoi48k** [comment]
oh, this bug has already fixed on 10.3.5. I will close issue. Thank you very much!!!

**Comment by michaelstaib** [comment]
I forgot to close the issue
