### ISSUE TITLE
Cannot add resolvers

### ISSUE THREAD

**Issue by hotgen** [ChilliCream/hotchocolate#1325]
Version: 11.0.0-preview.74

This code works:

```
// ConfigureServices
services
    .AddGraphQL(SchemaBuilder.New()
        .AddQueryType<Query>()                    
        .AddType<BlogType>()
    );

public class SomeResolvers
{
    public IEnumerable<Post> GetPosts([Parent]Blog blog, [Service]Database db)
    {
        return db.Posts.Where(p => p.BlogId == blog.Id);
    }
}

public class BlogType : ObjectType<Blog>
{
    protected override void Configure(IObjectTypeDescriptor<Blog> descriptor)
    {
        descriptor.Include<SomeResolvers>();
    }
}
```

And this doesn't:

```
// ConfigureServices
services
    .AddGraphQL(SchemaBuilder.New()
        .AddQueryType<Query>()  
        .BindResolver<SomeResolvers>()
    );

[GraphQLResolverOf(typeof(Blog))]
public class SomeResolvers
{
    public IEnumerable<Post> GetPosts([Parent]Blog blog, [Service]Database db)
    {
        return db.Posts.Where(p => p.BlogId == blog.Id);
    }
}
```

Any ideas? Thanks.

**Comment by michaelstaib** [comment]
BindResolvers if for SDL-First and works differently ... 

If you want to add some fields to your blog type then this would work:

```csharp
[ExtendObjectType(Name = "Blog")]
public class SomeResolvers
{
    public IEnumerable<Post> GetPosts([Parent]Blog blog, [Service]Database db)
    {
        return db.Posts.Where(p => p.BlogId == blog.Id);
    }
}

services.AddGraphQL(
    SchemaBuilder.New()
        .AddQueryType<Query>()  
        .AddType<SomeResolvers>());
```

Bind resolvers works like the following:

```csharp
var schema = SchemaBuilder.New()
    .AddDocumentFromString(
        @"
        type Query {
            hello: String
        }")
    .BindComplexType<Query>(c => c.Field(t => t.GetGreetings()))
    .BindResolver<QueryResolvers>(c => c.To<Query>())
    .Create();
```

**Comment by michaelstaib** [comment]
Can we close this issue?

**Comment by hotgen** [comment]
> BindResolvers if for SDL-First and works differently ...
> 
> If you want to add some fields to your blog type then this would work:
> 
> ```cs
> [ExtendObjectType(Name = "Blog")]
> public class SomeResolvers
> {
>     public IEnumerable<Post> GetPosts([Parent]Blog blog, [Service]Database db)
>     {
>         return db.Posts.Where(p => p.BlogId == blog.Id);
>     }
> }
> 
> services.AddGraphQL(
>     SchemaBuilder.New()
>         .AddQueryType<Query>()  
>         .AddType<SomeResolvers>());
> ```
> 
> Bind resolvers works like the following:
> 
> ```cs
> var schema = SchemaBuilder.New()
>     .AddDocumentFromString(
>         @"
>         type Query {
>             hello: String
>         }")
>     .BindComplexType<Query>(c => c.Field(t => t.GetGreetings()))
>     .BindResolver<QueryResolvers>(c => c.To<Query>())
>     .Create();
> ```
> 
> Documentation: https://hotchocolate.io/docs/schema-first

Thanks for clarification! Important thing to note is that `ExtendObjectType` works if I want to **add** some fields. If a field already there (in my case `Posts`) I still need to use descriptor aproach.
