### ISSUE TITLE
[Question] Same resolver for different properties?

### ISSUE THREAD

**Issue by feliperugai** [ChilliCream/hotchocolate#1327]
I'm new at GraphQL and I would like to say that this library is just awesome, thank you for  this, really.

As I'm learning GraphQL and HotChocolate's implementation of it, I'm having some trouble to understand why this particular issue is happening. I really don't know if it's a bug or I'm doing something wrong, and after strugling for some days I decided to post it here.

So the thing is, I have an ```InitiativeType``` which has some fields like:

- long Id
- string Name
- **User** CreatedBy
- **User** Guardian

Which I configure like so:

```
 protected override void Configure(IObjectTypeDescriptor<Initiative> descriptor)
{
       descriptor.Field<UserResolvers>(r => r.GetUser(default, default, default))
           .Name("guardian")

       descriptor.Field<UserResolvers>(r => r.GetUser(default, default, default))
           .Name("createdBy");
}
```

In my query I'm getting my Initiative like this:

```
public async Task<Initiative> GetInitiative(long id, [Service]InitiativeRepository repository)
{
     return await repository.Get(id);
}
```

My ```UserResolver``` is using ```CacheDataLoader``` to get users:

```
public async Task<User> GetUser([Parent]Initiative initiative, [Service]UserRepository repository, IResolverContext context)
     {
           //getting the right prop of Initiative (Guardian or CreatedBy) with Reflection
            var fieldName = char.ToUpper(context.ResponseName.Value[0]) + context.ResponseName.Value.Substring(1);
            var user = (User)initiative.GetType()?.GetProperty(fieldName)?.GetValue(initiative);

            if (user == null) return null;

            var  domain = await context.CacheDataLoader<long, User>
                 ("UserById", key => repository.Get(key))
                 .LoadAsync(user.Id, CancellationToken.None);

            return domain;
        }
```

When I query something this (knowing that CreatedBy and Guardian are the same user):

```
{
  initiative(id:2){
    name,
    description,
    createdBy{
      id,
      name,
    },
    guardian{
      id,
      name
    }
  }
}
```
I get this:

```
{
  "data": {
    "initiative": {
      "name": "My Initiative",
      "description": "Description of my initiative",
      "createdBy": {
        "id": 1,
        "name": "John" // this has value
      },
      "guardian": {
        "id": 1,
        "name": null //this is null
      }
    }
  }
}
```

While debugging it, I realized that `UsersResolvers.GetUser()` gets hit only one time.

If I remove the `CreatedBy ` property from my `InitiativeType`, my `Guardian` comes with its name right (it seems that its ignoring properties with the same type?) 

I'm trying really hard to understand why such thing is happening but I can't find out any reasons. Could someone check if that's a bug or what am I doing wrong here?

Thank you in advance!

**Comment by michaelstaib** [comment]
the field descriptor is not really the resolver. with `descriptor.Field` you specified from which member we should infer the field. You can only use a member as field once on a specific type.

You can however use the resolver method multiple times in resolvers or middleware.

`descriptor.Field("foo").Resolver(....)`

**Comment by felrugai** [comment]
Thanks for the reply!
Actually I was following the StarWars example, which uses a SharedResolvers.

From DroidType.cs we have

```
 descriptor.Field<SharedResolvers>(r => r.GetCharacter(default, default))
                .UsePaging<CharacterType>()
                .Name("friends");
```

My UserResolvers would be the SharedResolvers, which I would use in other types so I don't have to duplicate code.
I did it just like the following docs [https://hotchocolate.io/docs/code-first-resolvers#resolver-types](https://hotchocolate.io/docs/code-first-resolvers#resolver-types).

Is there any other way I could share the same resolver for multiple fields on the same type?

**Comment by felrugai** [comment]
I ended up changing my ```UserResolvers.GetUser()``` to receive only ```IResolverContext``` so I could use it like this:

```
descriptor.Field("guardian").Resolver(ctx => ctx.Resolver<UserResolvers>().GetUser(ctx));
```
That's working. But would this be a correct way of doing it?

**Comment by michaelstaib** [comment]
> But actually I was following the StarWars example, which uses a SharedResolvers.

In the example the shared resolver is shared between two different types not two times in the same type. Hence you can just import the member.

**Comment by michaelstaib** [comment]
> That's working. But would this be a correct way of doing it?

yes you can do that.
