### ISSUE TITLE
Data loader for many to many relationship

### ISSUE THREAD

**Issue by strahinja16** [ChilliCream/hotchocolate#1328]
Hi,
I was following the guide from the docs about  implementing data loaders in my resolvers and I've run into an issue with many to many relationship.

I have **Recipe** class with the many to many relationship to **Tag**.  I want to make an query 

```
query {
  recipes {
    tags {
      name
    }
  }
}
```
where I would fetch the Tags with Recipes. I've tried with the _GroupDataLoader_ but it I cannot make it work that way.

How can I implement this use case ?

Thanks in advance !

**Comment by michaelstaib** [comment]
Can you provide some code to point to the issue at hand?

**Comment by strahinja16** [comment]
Yes. Well,  I have **Users**, **Recipes**, and **Tags**. There is 1:N relationship between users and recipes and N:M between Recipes and Tags, standard EF Core mapping. So for the recipes field of UserType I had this implementation

```
 descriptor
                .Field("recipes")
                .Type<NonNullType<ListType<RecipeType>>>()
                .Resolver(ctx =>
                {
                    var repository = ctx.Service<IRecipeRepository>();

                    IDataLoader<Guid, Recipe[]> recipeDataLoader =
                        ctx.GroupDataLoader<Guid, Recipe>(
                            "recipesByUserId",
                            repository.GetRecipesByUserId);

                    return recipeDataLoader.LoadAsync(ctx.Parent<User>().Id);
                });
```
with the repository.GetRecipesByUserId having this implementation

```
 public async Task<ILookup<Guid, Recipe>> GetRecipesByUserId(IReadOnlyList<Guid> guids)
        {
            List<Recipe> recipes = await _dbContext.Recipes
                .Where(r => guids.Contains(r.UserId))
                .ToListAsync();

            return recipes.ToLookup(r => r.UserId);
        }
```

I wanted to use the similar approach for the tags field in the RecipeType but I cannot do it that way. This is because, as I understood, data loader needs all the data fetched implementing **ILookup** interface. It was easy for the recipes i would fetch for user, they have the **UserId** foreign key as lookup key. But in the many to many relationship one Tag can appear in the list of tags for more than one recipe, and does not have the lookup key as it is in the Many to many class. I could implement _dirty solution_ and return list of custom objects having the recipe id and list of it's tags, for each recipe but then I'd have to use different schema for the tags property instead of  _<ListType< TagType>>_ which i want to avoid. I hope I explained it thoroughly.

**Comment by strahinja16** [comment]
@michaelstaib any ideas ?

**Comment by michaelstaib** [comment]
I will look tomorrow at this ... sorry for the wait.

**Comment by strahinja16** [comment]
ok, thanks, much appreciated

**Comment by strahinja16** [comment]
No news @michaelstaib ?

**Comment by strahinja16** [comment]
will this issue be closed  or there will be feedback ? @michaelstaib

**Comment by michaelstaib** [comment]
Hi,

sorry for the wait on this one... 

for questions like this its is sometimes better to get into our slack channel since there more people apart from the contributors who could help on this.

We will do some work on the data loader soon and will look how we can solve n:n easier. 

I will add this to the 11 backlog so that we will take that up when we work on dataloader. 

Be sure to get on the slack channel and ask there again.... there

@rstaib fyi

**Comment by strahinja16** [comment]
Ok, thank you for your response, I'll come to the slack channel and ask then

**Comment by leonardochaia** [comment]
Hi @strahinja16 did you get to any conclusion? 

Is there any output of the slack conversation that perhaps we could link here for future reference?

**Comment by thunguyen2015** [comment]
I faced similar issue in my project, for case product-tag which is n:n relationship, please advise if we have a way to use dataloader to fetch tags base on product id or an alternative way to handle this
Ef core entity define like below
```
public class Product
{
     public int Id { get; set; }
     public List<Tag> Tags { get; set};
}

public class Tag
{
    public int Id { get; set; }
    public string Value { get; set; }
    public List<Product> Products { get; set;}
}
```
