### ISSUE TITLE
Algolia search broken on docs (https://hotchocolate.io/)

### ISSUE THREAD

**Issue by barticus** [ChilliCream/hotchocolate#1336]
**Describe the bug**
It appears that using the search box on the docs currently returns no results from algolia, meaning there is no feedback whether there is a result, and no assistance jumping to different parts of the documentation (apart from the TOC).
This seems to only have stopped working in the last few days. Apologies if this is not the correct place to report this.

**To Reproduce**
1. Go to https://hotchocolate.io/
2. Click on the search box
3. Type something there should be results for, e.g. 'resolv'
4. No results are shown

**Expected behavior**
Search results should be shown as per usual.

**Additional context**
I can see the following network traffic happening on type in the search box:
https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.21.0%3Bdocsearch.js%201.5.0&x-algolia-application-id=BH4D9OD16A&x-algolia-api-key=47d61652587888cd5144dcdd6fb9117b
Regardless of the search, the response is always like:

```json
{
    "results": [{
        "hits": [],
        "nbHits": 0,
        "page": 0,
        "nbPages": 0,
        "hitsPerPage": 5,
        "exhaustiveNbHits": true,
        "query": "resolv",
        "params": "query=resolv&hitsPerPage=5&facetFilters=%5B%22language%3Aen%22%2C%22version%3A10.3.2%22%5D",
        "index": "hotchocolate",
        "processingTimeMS": 1
    }]
}
```

Speculation is that docs for 10.3.2 were not indexed by algolia?

**Comment by michaelstaib** [comment]
Hi @barticus,

thank you for reporting this one. We will look into it.

**Comment by barticus** [comment]
this looks to be fixed now, thanks :)
