### ISSUE TITLE
[Banana Cake Pop] Tracing Timeline for Results

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#1343]

**Comment by sjwilczynski** [comment]
Hey folks, is this issue about implementing trace visualization, similar as in GraphQLPlayground:
![image](https://user-images.githubusercontent.com/19153565/153245299-6d3b9463-39c1-4c31-b90b-d489d3427c12.png)
If so, could you give some ETA on when this feature might arrive in BCP? Looking forward to it!

**Comment by michaelstaib** [comment]
Yes, this is about tracing. We have a couple more things to do before we will implement this.
