### ISSUE TITLE
[Banana Cake Pop] Shortcuts

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#1345]

**Comment by fredericbirke** [comment]
BCP should come with:
 - Meaningful, OS-Scoped predefined keybinding sets (e.g. VsCode, Intellij)
 - A configuration possibility to change the keybindings any way the user prefers it

Different Contexts:
 - Global
 - DocumentSidebar
 - DocumentEditor

Possible actions could be:
 - Open Settings (global context)
 - Refetch Schema (global context)
 - Fire request (document context)
 - Save item (document context / or in #41 context in some future)
 - Focus DocumentSidebar (global context)
 - Navigate in DocumentSidebar (DocumentSidebar context)
 - Trigger autocomplete (document context)
 - ...

**Comment by tobias-tengler** [comment]
Closing this, since shortcuts are part of the newer BCP versions.
