### ISSUE TITLE
[Banana Cake Pop] Download SDL

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#1350]

**Comment by tobias-tengler** [comment]
Closing this, since the download button for the SDL has been in the "Schema Definition" view for some time.

![image](https://user-images.githubusercontent.com/45513122/151701905-a6706ab7-ade9-474a-95e0-f464e4369976.png)

**Comment by saber13812002** [comment]
how can i download this schema in ci cd and use it there. how can i guess this download link?
