### ISSUE TITLE
Filtering by dates should not filter when date is null

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#1357]
**Describe the bug**
I have a set of filters applied using the UseFiltering functionality. The filters include dates and other types. When I exclude the date filters from the set of filters I apply, I expect the date filters to be skipped entirely. Instead the result set returns no data.

**To Reproduce**
```c#
 [Fact]
        public void Execute_Filter_without_DateTimeFilter_SHOULD_ignore_dates()
        {

            // arrange
            var foos = new Foo[]
            {
                new Foo { Bar = "aa", Baz = 1, Qux = 1, SomethingHappenedToFoo = new DateTime(1980,1,1)},
                new Foo { Bar = "ba", Baz = 1, SomethingHappenedToFoo = new DateTime(1980,1,2) },
                new Foo { Bar = "ca", Baz = 2, SomethingHappenedToFoo = new DateTime(1980,1,2) },
                new Foo { Bar = "ab", Baz = 2, SomethingHappenedToFoo = new DateTime(1980,1,2) },
                new Foo { Bar = "ac", Baz = 2, SomethingHappenedToFoo = new DateTime(1980,1,3) },
                new Foo { Bar = "ad", Baz = 2, SomethingHappenedToFoo = new DateTime(1980,1,3) },
                new Foo { Bar = null, Baz = 0, SomethingHappenedToFoo = new DateTime(1980,1,4) }
            };
            ISchema schema = SchemaBuilder.New()
                .AddQueryType<Query>(d => d
                    .Field("FoosConnection")
                    .UsePaging<FooType>()
                    .UseFiltering<FooFilterType>()
                    .UseSorting<FooSortType>()
                    .Resolver(x => foos))
                .Create();

            IQueryExecutor executor = schema.MakeExecutable();


            IReadOnlyQueryRequest request = QueryRequestBuilder.New()
                .SetQuery(
                    @"query GetFooList($filter: FooFilter!) {
                        FoosConnection(where: $filter) {
                            totalCount
                        }
                    }")
                .AddVariableValue("filter", new Dictionary<string, object>
                {
                    { "somethingHappenedToFoo_gt", null}
                })
                .Create(); 

            // act
            var result = (ReadOnlyQueryResult)executor.Execute(request);

            // assert
            var foosConnection = (OrderedDictionary)result.Data.Values.First();
            var actualCount = (int)foosConnection.Values.First();
            var expectedCount = foos.Length;
            Assert.Equal(expectedCount, actualCount);
        }
```

**Expected behavior**
In this case I would expect the result set to include ALL values as I don't want to filter by date. Instead it returns 0. Otherwise there is no way to opt not to apply the date filter as it will always cause an empty result set when it is excluded.

**Comment by michaelstaib** [comment]
can you post your query?

**Comment by michaelstaib** [comment]
Sorry ... it is in the code.

But that is correct actually. If you pass `null` then you are passing an actual value... so your intention here is to filter `somethingHappenedToFoo_gt` to be greater null. Now it is up to the query interpreter to report an error or execute on it.

**Comment by michaelstaib** [comment]
Just to make this more clear... `somethingHappenedToFoo: null` could be a perfectly valid case. 

We are using optionals in this case. If you explicitly provide a value than this states your intention.

**Comment by freever** [comment]
The same thing happens if I omit the filter property entirely. 

In my specific case I have a set of filters like so:
{
  "where_modifiedAtTicks_gt": 100000,
  "where_totalCheckins_gt": 1,
  "where_totalCheckins_lt": 10,
  "where_lastCheckin_gt": "2019/11/1",
  "where_lastCheckin_lt": "2020/1/1"
}

If I omit where_lastCheckin_gt and where_lastCheckin_lt altogether, I get no results. 

This means I have to create an entirely separate query for when I don't want to filter by check in times because if I omit those query properties it gets to the database as "WHERE LastCheckin > NULL"

**Comment by freever** [comment]
I wasn't sure how to make a valid unit test where some query parameters were omitted, which is why I made the null explicit. I agree with what you are saying about null being a valid value for a filter (well, maybe not for gt or lt but for equals yes) ... what I need is a way of omitting some filters.

**Comment by freever** [comment]
Now that I can pass in a filter object instead of individual fields (#1342 ) I can omit fields without causing this behaviour
