### ISSUE TITLE
[Banana Cake Pop] hide deprecated fields

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#1358]
deprecated fields should be hidden/grouped away. so the user can focus on the things that is still relevant.

![image](https://user-images.githubusercontent.com/7747800/72059613-a28ea600-32d2-11ea-9f1d-7dd4e618cfa5.png)

for e.g. in graphiql it's like this:

![image](https://user-images.githubusercontent.com/7747800/72059578-90ad0300-32d2-11ea-914c-7aa6576fc93b.png)

and with the press of the button

![image](https://user-images.githubusercontent.com/7747800/72059792-fb5e3e80-32d2-11ea-8360-670eeb0c0b55.png)

**Comment by michaelstaib** [comment]
maybe this should be an option so that you can group it and even predefine your preference.

**Comment by rstaib** [comment]
Sounds like a good feature and not to hard to implement ;-)
