### ISSUE TITLE
[Banana Cake Pop] present json result data as hierachical datagrid view

### ISSUE THREAD

**Issue by grounzero** [ChilliCream/hotchocolate#1360]
What would be a really great enhancement that I think a lot of GraphQL IDE's are missing is the ability to return result data into a hierarchical tree / datagrid view where the columns are generated dynamically from the result data.

A bit like https://www.prisma.io/admin/

**Comment by rstaib** [comment]
Definitely worth thinking about it. Thank you for your feedback.
