### ISSUE TITLE
Implement MVC5 middleware to support ASP.net classic

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#137]
We need a middleware for ASP.net classic which basically works similar to the .net core middleware. Maybe both can share a lot of code. So, if anybody likes to contribute this we would be happy.

**Comment by rstaib** [comment]
I have recently published the first version 0.6.2 of the ASP.Net classic OWIN middleware released. Although there is currently no subscription support. I suppose we will bring it in the next minor version 0.7.0.

**Comment by rstaib** [comment]
Issue #348 brings support for subscriptions to ASP.Net classic.
