### ISSUE TITLE
No compatible constructor found for input type xxx

### ISSUE THREAD

**Issue by grounzero** [ChilliCream/hotchocolate#1371]
Since updating from 10.2.0 during startup when adding my types I get an exception `No compatible constructor found for input type: MyUnderlyingType`  There is no constructor on the type as it just a POCO.  I tried commenting out parts to try and locate something more specific but I haven't managed to track it down other than reverting back to 10.2.0 makes it go away.

**Comment by grounzero** [comment]
Ok It seems to occur because I have a List<T> property on my POCO with no set accessor.  If I add a set accessor to the property or tell the descriptor to ignore when configuring the InputObject the then it works.

i.e if I change 

```public List<Sector> Sectors { get; } = new List<Sector>();```

to

 ```public List<Sector> Sectors { get; set; } = new List<Sector>();```

Ideally I just want to change the list by using the `Add()`  and `Remove()` methods.  Is there a way I can do this without ignoring the property or adding a set accessor?

**Comment by michaelstaib** [comment]
But what would we do when the list is set to null?

BTW, you also can let us pass your read-only props into a constructor.

```csharp
public class Foo 
{
    public Foo(Bar bar) 
    {
        Bar = bar;
    }

    public Bar Bar { get; }
}
```

**Comment by michaelstaib** [comment]
I will close this issue. We will revisit the deserialization again in march after we have the new execution engine in.

**Comment by dillanmann** [comment]
Is there a way to work around this? E.g. if the type I have as an input type type is in a library I am unable to change, can I specify a way to construct each element, or ignore the property that I know has the wrong accessors?

For the library I am working with there is a class with one property which has a protected setter, I want to be able to ignore this as I cannot change the types library.

**Comment by michaelstaib** [comment]
If you ignore the property it will not be taken into account. You can either ignore the property with the fluent API or with the GraphQLIgnore Attribute.

In your case I know only the fluent API will work since it is from an external lib.

The question here is why bind a field for input serialization if it cannot be accessed by the serializer?

```csharp
public class FooInputType : InputType<Foo> 
{
    protected override void Configure(IInputObjectTypeDescriptor<Foo> descriptor) 
    {
        descriptor.Ignore(t => t.Prop);
    }
}
```

**Comment by PascalSenn** [comment]
@michaelstaib  we already discussed this on slack. @dillanmann  did try to ignore it with Ignore but apparently it did not work.

**Comment by michaelstaib** [comment]
Strange, we will have to write a test for this and verify that this is true and then look what is causing the issue. Anybody wants to do a pr?

Test would go here:
https://github.com/ChilliCream/hotchocolate/blob/master/src/HotChocolate/Core/test/Types.Tests/Types/InputObjectTypeTests.cs

**Comment by arif-hanif** [comment]
@michaelstaib / @PascalSenn  i am running into a similar issue with an external library

**Comment by michaelstaib** [comment]
Can you pinpoint what your issue is?

**Comment by dillanmann** [comment]
FYI I believe I managed to get this working, but the way that I had to ignore it was different than what you specified. I can't remember the exact details, I'll check tomorrow to see what I did for you.

**Comment by benjamincburns** [comment]
> FYI I believe I managed to get this working, but the way that I had to ignore it was different than what you specified. I can't remember the exact details, I'll check tomorrow to see what I did for you.

![image](https://github.com/ChilliCream/graphql-platform/assets/803016/8ba8f75c-3f69-4d18-9a7d-517a0a6563a9)

**Comment by dillanmann** [comment]
> > FYI I believe I managed to get this working, but the way that I had to ignore it was different than what you specified. I can't remember the exact details, I'll check tomorrow to see what I did for you.
> 
> ![image](https://private-user-images.githubusercontent.com/803016/306800451-8ba8f75c-3f69-4d18-9a7d-517a0a6563a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTM3NTYsIm5iZiI6MTcwODU5MzQ1NiwicGF0aCI6Ii84MDMwMTYvMzA2ODAwNDUxLThiYThmNzVjLTNmNjktNGQxOC05YTdkLTUxN2EwYTY1NjNhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwOTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTc5MTA5MjA3NTVhM2ZkZDUwMzJmZjhlNjBjN2Y2M2Q4ZjA3NGRjY2YxZGMwODBjYjJiOWYwN2Y5MzE1NjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gt3LtpCotyvOGDur0UzLXA1pD2DNXJ2ksu_EdSGTnW0)

Terribly sorry, I'm no longer at the company I worked at when I wrote that response so I've no hope in working out what the solution was. Hope you find what you're looking for though.
