### ISSUE TITLE
Batch operations is not working

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1373]
**Describe the bug**
A request of two batched operations (queries) only return the result of the first one with no errors.

**To Reproduce**
1. Download `https://github.com/geekox86/OeMis`
2. Using VS Code with REST Client extension, run the HTTP requests in the test.http at root path
3. Results only show for the first query (Organizations) but not for (Test)
4. No errors!

**Expected behavior**
Both queries return in the results with no errors or otherwise an error is produced.

**Desktop (please complete the following information):**
MacBook Pro (Retina, 13-inch, Late 2013)

**Additional context**
I am using Microsoft SQL Server with test data, but you can easily replace the database call with static data. Also, the Test resolver method is not even called.

**Comment by geekox86** [comment]
I can confirm that batching is working and both query resolvers are invoked only when I remove the `@export(as: "names")` directive and use a direct variables instead. So, my guess is that I am doing something wrong with the export directive. Any clue?

**Comment by geekox86** [comment]
Currently, I am getting this error: `Variable "names" got invalid value`

**Comment by michaelstaib** [comment]
Did you register the export directive?

**Comment by geekox86** [comment]
@michaelstaib Yes, I did here:
```
.AddGraphQL(
                    SchemaBuilder
                        .New()
                        .AddAuthorizeDirectiveType()
                        .AddExportDirectiveType()
                        .AddQueryType((options) =>
                            options
                                .Name("Query")
                                .Include<OrganizationQueriesResolver>()
                        )
                        .AddObjectType((options) =>
                            options
                                .Name("Mutation")
                                .Include<OrganizationMutationsResolver>()
                        )
                        .AddObjectType<Organization>((options) =>
                            options.Include<OrganizationFieldsResolver>()
                        )
                        .Create(),
                    new QueryExecutionOptions() {
                        TracingPreference = _environment.IsDevelopment() ?
                            TracingPreference.Always :
                            TracingPreference.OnDemand
                    }
                )
```

**Comment by michaelstaib** [comment]
This detail is missing in the docu

**Comment by geekox86** [comment]
BTW, the batching is working but I get an error saying `Variable "names" got invalid value (Code: EXEC_INVALID_TYPE)`

**Comment by michaelstaib** [comment]
builder.AddDirectiveType<ExportDirectiveType>()

**Comment by geekox86** [comment]
You mean `AddExportDirectiveType` right? Which I already did.

**Comment by michaelstaib** [comment]
sorry misread the thread on my phone :)

**Comment by michaelstaib** [comment]
can you post your batch query?

**Comment by geekox86** [comment]
Greetings,

```
POST https://localhost:5001/graphql?batchOperations=[A,B] HTTP/1.1
Content-Type: application/graphql

query A {
    organizarions {
        name @export(as: "names")
    }
}
query B ($names: [String!]!) {
    test(names: $names) {
        name
    }
}
```

**Comment by michaelstaib** [comment]
this should work .... hmmm let me check our tests

**Comment by michaelstaib** [comment]
is name an non-null property?

**Comment by geekox86** [comment]
Name is a nullable property.
C# nullable references is enabled.

**Comment by geekox86** [comment]
This is the API endpoint:

```
public async Task<IEnumerable<Organization>> Test(IEnumerable<String> names, [Service] OeMisDbContext context)
{
        return await context.Organizations
                .Where((organization) => names.Contains(organization.Name) == true)
                .AsNoTracking()
                .ToListAsync();
}
```

**Comment by michaelstaib** [comment]
ah but then the error is correct since from a nullable string you cannot create a non-null string list with non-null elements.

**Comment by michaelstaib** [comment]
Since if `name` is `String` it will be coerced to `[String]!` but you defined `$names` to be `[String!]!`. 

Also the execution engine can infer the variables...

```GraphQL
query A {
    organizarions {
        name @export(as: "names")
    }
}
query B  {
    test(names: $names) {
        name
    }
}
```

but the names input has still to align with the nullability of the exported type.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/tree/master/src/Core/Core.Tests/Execution/Batching

**Comment by michaelstaib** [comment]
The other way around would work by the way, you can have non-null source properties that are then injected into nullable arguments.

**Comment by geekox86** [comment]
@michaelstaib It is working like a charm now, thank you!
