### ISSUE TITLE
UseFiteringAttribute, UseSortingAttribute missing  

### ISSUE THREAD

**Issue by clmcgrath** [ChilliCream/hotchocolate#1376]
**Describe the bug**
the attributes UseFiteringAttribute, UseSortingAttribute described in 2.3.* [documentation ](https://hotchocolate.io/docs/descriptor-attributes#built-in-attributes) can not be found when used in code and result in broken builds 

**To Reproduce**
Reference [UseFiltering] or [UseSorting] in code 

**Expected behavior**
to be recognized as valid operations 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 2.3.* (tested in 2.3.5, 2.3.2 ) 

![image](https://user-images.githubusercontent.com/452012/72379489-867b7200-36e1-11ea-9ac5-96d8bfce1105.png)

**Comment by PascalSenn** [comment]
Hi @clmcgrath  

I see some inconsistency in the docs there.
Did you add these two packages?
https://hotchocolate.io/docs/filters
HotChocolate.Types.Filters
HotChocolate.Types.Sorting

**Comment by michaelstaib** [comment]
@clmcgrath did this fix you issue? can we close?

**Comment by clmcgrath** [comment]
ah ya i don't have these installed ,  thanks should probably update the docs  where it says it is built-in as well since it is a package

**Comment by michaelstaib** [comment]
Docs are already update... we have to republish them. I am closing this issue.
