### ISSUE TITLE
Translate exception into multiple errors

### ISSUE THREAD

**Issue by bram209** [ChilliCream/hotchocolate#1387]
I'm using fluent validations in my application layer. 

If I call some business logic from my queries / mutations, it might result in a ValidationException, which contains (possibly) multiple errors.

Currently an error filter can be used to do a 1-to-1 mapping from exceptions to graphql errrors, but in my case I need to map 1 exception into a list of errors. Is this possible?

**Comment by michaelstaib** [comment]
```csharp
public class ValidationMiddleware
{
    private readonly FieldDelegate _next;
    public ValidationMiddleware(FieldDelegate next) => _next = next;
    public async Task InvokeAsync(IMiddlewareContext context)
    {
        try
        {
            await _next.Invoke(context);
        }
        catch (ValidationException e)
        {
            context.Result = e.Errors.Select(validationError => ErrorBuilder.New()
                    .SetMessage(validationError.ErrorCode)
                    .SetExtension(validationError.PropertyName, validationError.ErrorMessage)
                    .SetPath(context.Path)
                    .Build())
                .ToList();
        }
    }
}
```

Apply it to all fields

```csharp
SchemaBuilder.New()
    .Use<ValidationMiddleware>()
   ....
```

Apply it to one specific field

```csharp
descriptor.Field(...).Use<ValidationMiddleware>()...
```

**Comment by huysentruitw** [comment]
I have the same needs as @bram209 and would like to discuss this issue as the proposed solution feels like a hack: it is not type-safe and can fail at runtime. 

Can we have a more sustainable solution to this?

**Comment by PascalSenn** [comment]
@huysentruitw  Hm. How is this not typesafe?

**Comment by huysentruitw** [comment]
`ValidationMiddleware` doesn't implement any interface, nor it inherits from an abstract class, which means the code expects a method `InvokeAsync` that takes one argument of type `IMiddlewareContext ` but this is not in any contract, same for the constructor of that class.

Second, `context.Result` is an `object`, so you can pass anything you want, it will not be enforced by the compiler.
