### ISSUE TITLE
not_in generates bad SQL when using EntityFrameworkCore Queryable

### ISSUE THREAD

**Issue by stevehansen** [ChilliCream/hotchocolate#1393]
**Describe the bug**
When using the filtering to do a not_in on a String the generated expression causes EntityFrameworkCore to generate bad SQL.

https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types.Filters/Expressions/FilterExpressionBuilder.cs#L56
The Not expression is being handled as ```expression == false``` instead of the expected ```!expression``` if ```Expression.Not(expression)``` would be used.

For information, using ```!expression``` will generate a clean ```column not in ('option', 'option')``` where as the ```expression == false``` will cause a complex (and badly optimizable) sql ```cast(case when column in ('option', 'option') then 1 else 0 end as bit) = cast(0 as bit)``` to be generated.

I don't think there would be any reason to do the manual equals(expression, constant(false)) instead of the built-in not(expression).

**Comment by michaelstaib** [comment]
I have merged your pr an close this issue now... Thanks again for contributing :)
