### ISSUE TITLE
Better error message on The value of X has a wrong structure error

### ISSUE THREAD

**Issue by nkovacic** [ChilliCream/hotchocolate#1397]
**Is your feature request related to a problem? Please describe.**
When writing client queries or mutations potential mistakes can be made, but there is no way to debug the issues, because the HotChocolate server always returns `The value of $input has a wrong structure.`.

**Describe the solution you'd like**
It would be great if an exception would be raised with additional information 
(located in [DictionaryToObjectValueConverter#80](https://github.com/ChilliCream/hotchocolate/blob/cf600304845e716fb9dfacdce491bc59c31bf1b8/src/Core/Core/Execution/Utilities/DictionaryToObjectValueConverter.cs#L80)). The exception or message should atleast containt `field.Key` or the whole `ConverterContext`

**Comment by PascalSenn** [comment]
The input paser has been completly rewritten for this in v12.
This is now reslolved
