### ISSUE TITLE
Apollo Tracing Doesn't Add Tracing Result to Extensions Map

### ISSUE THREAD

**Issue by robertervin** [ChilliCream/hotchocolate#1398]
**Describe the bug**
Even with `TracingPreference = TracingPreference.Always`, Apollo tracing doesn't return a tracing result, even in the example.

**To Reproduce**
Run an example query in the [DataLoader](https://github.com/ChilliCream/hotchocolate-examples/tree/master/DataLoader)

**Expected behavior**
It is expected to return an "extensions" map in the result which has the "tracing" map included with all of the details. Today it is just an empty "extensions" map.

**Comment by robertervin** [comment]
Looking into this today. It looks like the problem is related to the specific string: `tracing` . If I change the key at https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Core/Execution/Instrumentation/ApolloTracingDiagnosticObserver.cs#L61 to "tracing2", it works as expected. Will update with what I find

**Comment by robertervin** [comment]
It looks like it's adding it to the Extensions properly, but them later down the line is stripped out. Still baffled, but think I'm getting closer.

**Comment by robertervin** [comment]
Okay so it looks like HC works just fine. Attached is a screenshot showing the raw result from HC vs what's loaded in GraphiQL. As you can see there is a tracing in the raw result but not the Web UI. BananaCakePop has the same issue it as well.

![tracing-debugging](https://user-images.githubusercontent.com/6490808/73125152-97de3d00-3f71-11ea-9fa2-b47cb7cf1186.PNG)

**Comment by robertervin** [comment]
Okay so in GraphiQL it looks like there is a `tracing.hideTracingResponse` flag in the settings that handles this. When I changed it to `false`, tracing showed up :). Also clicking the `Tracing` link in bottom right will show the trace result.

Closing this issue since it's resolved and not an issue with HC 😄

**Comment by PascalSenn** [comment]
@robertervin  just updated the docs :+1: 
thanks for investigating !
