### ISSUE TITLE
GUID to IdType resulting in strings being ID fields

### ISSUE THREAD

**Issue by barticus** [ChilliCream/hotchocolate#1400]
**Describe the bug**
When using `.BindClrType<Guid, IdType>()` (with the intention that all Guids should be mapped to the Id type), strings also then get mapped to the ID type.

**To Reproduce**
1. Have a model like
```
public class Model {
        public Guid Id { get; set; }
        public string Name { get; set; } = default!;
    }
```
and a type like 
```
public class ModelType : ObjectType<Model> {}
```
2. Add GraphQL like
```
            .AddGraphQL(SchemaBuilder.New()
                .AddQueryType<Query>()
                .BindClrType<Guid, IdType>()
                .AddAuthorizeDirectiveType()
                .AddType<ModelType>()
                .Create()
            )
```
3. Run locally
4. Inspect the schema, both Id and Name will be of type `ID` 

*note* I have guessed at the above steps and so it does not match my code exactly, but it is fairly close in complexity.

**Expected behavior**
Id should be of type ID, but Name should be of type string

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 10.3.5

**Additional context**
Manual specifying of type still works correctly, will do this as a workaround for now.

**Comment by michaelstaib** [comment]
This is fixed on version 11.
For version 10 add a second binding for string to StringType in this case.

**Comment by michaelstaib** [comment]
I am closing this, since it is already fixed on the 11 preview

**Comment by barticus** [comment]
Ah, thanks @michaelstaib , I searched issues first but only open ones.
