### ISSUE TITLE
-t parameter broken

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#1401]
I have just updated to v11.0.0-preview.79 of the Strawberry Shake tools. 

This command used to work with preview .73:

dotnet graphql init https://{myurl}/api/graphql -n {MyNamespace} -t {MyToken} -s {MyScheme}

Now it throws the following:

> Unhandled Exception: McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '-t'
>    at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argValue)
>    at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
>    at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
>    at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
>    at StrawberryShake.Tools.Program.<Main>(String[] args)

Running dotnet graphql --help suggest the format is correct:
 dotnet graphql init {url} [-p|--Path] [-n|--SchemaName] [-t|--token] [-s|--scheme]

**Comment by michaelstaib** [comment]
The documentation is wrong there. We changed the parameters a bit since we introduce oauth support.

You can pass the token now via `--token`

With the next build we will add the new help.

**Comment by freever** [comment]
Thanks, I can confirm that --token and --scheme work for me.

**Comment by michaelstaib** [comment]
We are very close now to releasing the new visual studio tooling ... would be great if you would beta test it :)

**Comment by freever** [comment]
Would be happy to!
