### ISSUE TITLE
Strange build problems on Mac

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#1402]
I am building a Xamarin app using Strawberry Shake as the GraphQL client. I do most of my dev on Windows (and generate the client on Windows) but to build for iOS I need to run the code on a Mac. Which is where strange things happen. 

I generate the client on Windows using a custom namespace which is MySolutionName.MyProjectName.Generated because that maps to the folder structure of /Generated that the code ends up in. So I generate the client, run everything on Windows and all is well. 

When I clone the code onto a mac and attempt to build the client, however, a process runs somewhere in the Machine before my code is built. This process re-generates the client code, which I do not want to happen. Also when it regenerates the client it uses a different namespace, basically the project root namespace MySolutionName.MyProjectName... so all the code referencing the client breaks. 

The net result is that when I try and build the solution on a Mac it breaks itself. 

I'm not sure what exactly is happening here or how to fix it... any ideas?

I am using the latest Strawberry Shake prerelease (79).

**Comment by michaelstaib** [comment]
The regeneration happens because off the different line breaks... Win `\r\n` and Mac `\n`.

I only work on the Mac, so all the code base is written on the Mac :)

Are you using Visual Studio for Mac? We have not yet optimized for it but will soon. 

have you tried the newest preview? 79

**Comment by freever** [comment]
Sorry I meant to say I am on preview 79, not 70. I have updated the original comment. 

I am using Visual Studio for Mac, yes. 

Would it make sense to store the preferred namespace as part of berry.json so that generation of code is always consistent?

**Comment by freever** [comment]
My workaround for now is to use the root namespace when I generate manually.

**Comment by michaelstaib** [comment]
I think your issue here will be fixed with the next update :)

**Comment by michaelstaib** [comment]
This one is now fixed with the move to source generators.
