### ISSUE TITLE
How can I approach to solve this "challenge"?

### ISSUE THREAD

**Issue by wdamaral** [ChilliCream/hotchocolate#1429]
Hi,

I'm pretty new to GraphQL + .NET Core, which eventually makes me to have some questions about development. I have to develop a prototype using GraphQL + .Net Core 3. The company uses SQL Server 2016. One of the suggestions is to use JSON columns in some tables to make it easier to insert any data.

I just need a light to help me on the approach.

 

Imagine the following DB - Just an abstract example

`CARS`

```

carID int PRIMARY,

carType VARCHAR,

```

`COMPONENTS`

```

carID FOREIGN KEY,

componentID PRIMARY KEY,

componentType VARCHAR,

componentDetails JSON COLUMN

```

Cars can have multiple components;

Depending on the componentType, the JSON changes.

 

Let's say I have a componentType `SEATBELT`, which would have a json like this

```

{

"color" : "black",

  "material" : "nylon"

}

```

 

But I can also have a componentType `BATTERY`, which would have a json like this

```

{

  "brand" : "DieHard",

  "voltage" : 12.6

}

```

 

How can I approach to solve this problem using HotChocolate? Is there any example I can take a look which uses JSON column from SQL Server?

**Comment by michaelstaib** [comment]
Hi, 

we have a very active slack channel where you might find some more help on more General questions. 

To hc it does not matter where your data comes from.
