### ISSUE TITLE
[StrawberryShake] Should it target LTS dotnet sdk versions?

### ISSUE THREAD

**Issue by hanabi1224** [ChilliCream/hotchocolate#1430]
I notice that instead of targeting [LTS dotnet sdk](https://dotnet.microsoft.com/download/dotnet-core) 2.1 and 3.1, it targets 2.2 and 3.0. Just curious what is the design goal of that?

**Comment by michaelstaib** [comment]
Hi

**Comment by michaelstaib** [comment]
Hi, we are at the moment restructuring the repo. With the next big push the versions will change.

It will probably take one more week.

Work can be tracked here:

https://github.com/ChilliCream/hotchocolate/pull/1229

**Comment by michaelstaib** [comment]
In the current master we have updated the target frameworks to 3.1, 2.1 and standard 2.1 and 2.0.
