### ISSUE TITLE
Is it possible to serve two separate schemes on two separate routes?

### ISSUE THREAD

**Issue by raphaabreu** [ChilliCream/hotchocolate#1432]
Hello, I am coming to HotChocolate from the Graphql.net packages and one thing that I have not yet found a way to implement is to have the same process serving two separate schemes on two routes.

In my current project I have a publicly facing scheme that the mobile apps use and I have an internal scheme that is used by backend operations. I don't want to expose any more functionality than needed to the internet so the internal scheme is served on a route that is protected from outside access on the infrastructure level. At the same time, the internal scheme does not require authentication since it is only being accessed from my own servers.

Is it possible to do something like this?

            app.UseGraphQL<InternalSchema>("/internal/graphql");
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
            {
                GraphQLEndPoint = "/internal/graphql",
                Path = "/internal/graphql-playground"
            });

            app.UseGraphQL<SecureSchema>("/secure/graphql");
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
            {
                GraphQLEndPoint = "/secure/graphql",
                Path = "/secure/graphql-playground"
            });

**Comment by michaelstaib** [comment]
Not yet, this is coming with V11.

**Comment by cadusantosm** [comment]
Hi @michaelstaib Can I use this in a preview version?

**Comment by michaelstaib** [comment]
@cadusantosm we are doing a lot of changes on the previews at the moment so at this very moment I cannot recommend the 11 preview. The 10.4 previews are stable
