### ISSUE TITLE
[Banana Cake Pop] Subscription complete is not recognized.

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1433]
When doing subscriptions with Banana Cake Pop the subscription completion is not recognized meaning even though the server said that the subscription is completed bcp stays connected and shows the donut.

We should actually in the case of a data complete message close the connection.

**Comment by rstaib** [comment]
Agree. I will investigate a bit.

**Comment by michaelstaib** [comment]
There are some other issues around this ... like when I have a message stream that sends a sequence on messages and the unsubscribes bcp will show non of the messages. The messages instead are just logged to the results pain where I have to actively click on it.
