### ISSUE TITLE
Client Query as Expression<Selector>

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#1435]
Hello!!!
Client side query can be improved.
instead of saving queries in **Queries.graphql** File  and then calling them as 
`await client.GetHeroAsync(Episode.Empire);`

let _strawberry-shake_ generate a client like this.

```
var hero = await client.GetHero(Episode.Empire).Select(hero=> {
name = hero.Name,
}).FirstOrDefualtAsync();

```

Now client is responsible for creating Query on run time. 
Selection will be in C# not in graphql so It's more powerful.
Don't need to build and generate code multiple time just once.
Don't need to even touch graphql File so no maintenance,

**Comment by michaelstaib** [comment]
We are going the way of relay. Runtime query generation is inefficient for both the server and the client. Strawberry shake allows for persisted query flows and more. 

We experimented a lot with expressions and queryable and had already a prototype running but decided against it since you would need to learn a second language to express GraphQL, this severely would limit what you could do with GraphQL.

Client Side directives for instance are a concern and things like low dash would not be possible.

**Comment by aammfe** [comment]
I agree run time query generation is slow. but it can be cached.
 

> since you would need to learn a second language to express GraphQL

sorry what second language ?

**Comment by michaelstaib** [comment]
> sorry what second language ?

you are using expressions to express GraphQL and you cannot do everything with expressions that you can do with GraphQL...

some examples:
- fragments
- inline fragments
- @defer
- @stream
- @skip / @include
- dynamic directives 
- lodash

where we however see expressions and where we will build in expressions is for filters.

so, with version 12 if you use Prisma, or Hasura or Hot Chocolate we will use expressions to define the filters inputs. But this is in early discussions.

Apart from that we have built quite a view prototypes before we decided to use GraphQL...

And once the big pr for strawberry shake merges next week GraphQL will be fully integrated with visual studio. Meaning it compiles you have syntax errors integrated with the csharp compiler and so on using GraphQL will feel super nice.

**Comment by aammfe** [comment]
Yes u are right.
so in V12 we will be able to use Expressions for dynamic ones and use Query file for constant and complex queries ?
Thanks

**Comment by michaelstaib** [comment]
What I mean with that is that whenever you use `UseFiltering` and you are passing a filter graph to the outside you will be able to express this with queryable.

**Comment by aammfe** [comment]
Thanks!

**Comment by zmhh** [comment]
Just want to add a data point that this is exactly what I was looking for when initially trying to use StrawberryShake. It does seem like the slowness of client query generation can be mitigated by caching queries.
