### ISSUE TITLE
Overriding argument values from FieldMiddleware

### ISSUE THREAD

**Issue by tocsoft** [ChilliCream/hotchocolate#1437]
I want to be able set an arguments value that is used to during the invoke of a field. This argument value must be adjustable per request (and have access to contextual data) and not just a static default value.

I propose that `IResolverContext.OverrideArgument<T>("name", value)` is added. And `IResolverContext.Argument<T>("name")` is updated so that it first tries to look up the argument value from the collection of overridden values then falls back to the current argument lookup logic.

**Comment by michaelstaib** [comment]
So,

you want to be able to dynamically override the field values in the middleware .... interesting :)

I assume this specific override is only available in this pipeline and is not accessible from other resolvers.

**Comment by tocsoft** [comment]
yeah that's what I was envisioning.

**Comment by husseinraoouf** [comment]
is there is any way to do this even with a workaround until it get implemented

currently i am trying to put a default value from an argument based on data in the HttpContext
i think being able to override arguments is the easiest way to do that but if there is any other way i would like to know who

**Comment by michaelstaib** [comment]
Why do you not use default values?

**Comment by husseinraoouf** [comment]
because the i want to get the default value from the query parameters which change in each request

**Comment by michaelstaib** [comment]
We are adding for version 11 the ability to write serialization middleware for the input values this essentially gives you the ability to do such a thing. But I cannot commit to any date.

**Comment by michaelstaib** [comment]
With version 12.4 we introduce ReplaceArguments on the `IMiddlewareContext` this allows middleware to rewrite argument values as well as the argument structure at runtime.
