### ISSUE TITLE
Expose data set via ISchemaBuilder.SetContextData() during desciptor configuration.

### ISSUE THREAD

**Issue by tocsoft** [ChilliCream/hotchocolate#1438]
I want to be able to pass custom settings while configuring schemabuild that cen be used to reconfigure the generated schema from the `Configure()` method of `ObjectType<T>`.

This combined with multiple schemas/shema switch allows for creating filtered apis based on the requested users claims i.e. enables excluding all the admin apis when signed in from a general user account... enables lighting up preview apis to accounts that have that feature enabled.

**Comment by michaelstaib** [comment]
This is possible now.

**Comment by michaelstaib** [comment]
IDescriptorContext.ContextData represent the schema building context data.
