### ISSUE TITLE
Enable filtered APIs per user/request

### ISSUE THREAD

**Issue by tocsoft** [ChilliCream/hotchocolate#1439]
I have a use case where i want a single API endpoint backed by a single set of clr api objects but be able to filter out the usage of particular types/arguments from the exposed API based on user.

## Concreate example
We have a multi branded system, we need our staff to be able to interact with the API in a cross brand manor using our back office tooling.

We want to expose the API for clients to access but they need to not be able to see/know that the other brands exist.

All brand choice related variables need to be ignored/hidden from the entire API surface when someone access the API based on some custom logic driven off information in the HttpContext or equivalent (i.e.an account claim or host header switch etc)

All brand variables input values need to have their values populated as if a value was passed in from the query to the API but needs to be a dynamic value per request. (to simplify/normalize internal implementation of apis.)

Also we would need to be able to ignore whole fieldsets/fields (not just) arguments need to be hidden from the API surface for certain users (hiding Admin APIs etc).

## Proposed solution.

My proposed solutions is 3 fold;

1. Add the ability to register multiple named schemas into DI (#643) with the ability to have a callback when registering the options to allow switching the name of the schema to use per request. i.e. add a `Func<HttpContext, string>` to `QueryMiddlewareOptions` (plus a simple string overload for simplicity) to allow custom switching of a schema per request.

2. Update the type configuration pipeline to expose the `ContextData` during configuration this allow adding custom logic to add remove arguments/fields from the final schema per registration thus allowing a single core set of models to be tuned per named schema based on any logic developers require. (#1438)

3. Update `IMiddleware` context to allow a piece of middleware to inject additional custom arguments before final field resolver is invoked. (#1437)

These 3 together would allow a configuration like this;

1. Register Admin/internal version of schema with everything enabled with the name `adminSchema`

2. Register external api version, with `CustomData["isExternal"] == true` by calling `ISchemaBuilder.SetContextData("isExternal", true)`  with the name `externalScheme`

3. during descriptor configuration if `CustomData["isExternal"] == true` : inside `MutationType` (or equivilent) add an `.Extend().OnBeforeCompletion(()=>{})` which removes the argument that should not be exposed. (allows for hiding the arguments/fields)

4. during descriptor configuration if `CustomData["isExternal"] == true` : inside `MutationType` (or equivilent) add an `.Use(n=>c=>{})` which calls `c.OverrideArgument("name", targetValue)` this then allows us to set the value of the argument per request. (allows for providing custom values per request)

5. call `app.UseGraphQL()` with the option of `SchemaNameProvider = (c)=> c.User.HasClaim("InternalStaff") ? "adminSchema" : "externalScheme"` with the strings being those that we registere with above

This issue is less a feature request more of a use case that requires the other 3 features to be implemented 

I have a prototype/hack that can get this full end to end working (currently missing stuff around subscriptions but the rest of the APIs seem to work fine, also not looks as AspNetClass stuff as i cant even figure out compile/debug that build varient) my hack can been seen here https://github.com/tocsoft/hotchocolate/tree/dbd1990635c02782132be58d8cb96124cddcce61 I'll start raising PRs once i've made sure things seem to be stable and i've added any required coverage for any of this stuff. Allow allowing time for feedback on any of the details above where some of these things may already be possible and I am just unaware of how to do them all. (don't worry i'll make individual smaller PRs for parts instead of a big bang here's everything.)

**Comment by michaelstaib** [comment]
> Update the type configuration pipeline to expose the ContextData during configuration this allow adding custom logic to add remove arguments/fields from the final schema per registration thus allowing a single core set of models to be tuned per named schema based on any logic developers require. (#1438)

This can already be done. We have something called a type interceptor that lets you intercept each type at each initialization state.

https://github.com/ChilliCream/hotchocolate/blob/d5595996a6baf1dcd948174cacc6d078af48fa60/src/Core/Types/Configuration/Contracts/ITypeInitilizationInterceptor.cs

The interceptor gives you access to the contextData ....

```csharp
void OnBeforeRegisterDependencies(
            IInitializationContext context,
            DefinitionBase definition,
            IDictionary<string, object> contextData);
```

**Comment by michaelstaib** [comment]
> Add the ability to register multiple named schemas into DI (#643) with the ability to have a callback when registering the options to allow switching the name of the schema to use per request. i.e. add a Func<HttpContext, string> to QueryMiddlewareOptions (plus a simple string overload for simplicity) to allow custom switching of a schema per request.

This is planned for version 11.

**Comment by michaelstaib** [comment]
> Update IMiddleware context to allow a piece of middleware to inject additional custom arguments before final field resolver is invoked. 

you can do that already in multitude of ways. You could transport custom data through context data or scoped context data or directives.

Or how do you mean that?

**Comment by michaelstaib** [comment]
We are internally using this already to tell the types that relay is enabled, the one thing missing for you is actually to be able to host multiple schemas.

**Comment by tocsoft** [comment]
> > Update IMiddleware context to allow a piece of middleware to inject additional custom arguments before final field resolver is invoked.
> 
> you can do that already in multitude of ways. You could transport custom data through context data or scoped context data or directives.
> 
> Or how do you mean that?

Maybe an example will make this clear;
basically I have a list field `public Task<Order[]> Orders(string brandFilter) { }`
where brandFilter is a required field.

I want to expose this field to admin users as `order($brandFilter){ ... }` but for a brand specific user i want to expose it as  `order(){...}` where brand filter is not present in the exposed schema and not valid to set at all. however i want the users brand to populate automatically without without the API developer having to special case the type of user.

**Comment by PascalSenn** [comment]
This can be done by adding multiple schemas. 
Also all requested features are meanwhile possible
I am going to close this issue
