### ISSUE TITLE
Default Scalar support for BCL types DateTimeOffset and TimeSpan

### ISSUE THREAD

**Issue by raphaabreu** [ChilliCream/hotchocolate#1441]
Hello,

I have several models that currently use basic data types from BCL and I find myself having to implement support for them by extending ScalarType.

The two main culprits are DateTimeOffset and TimeSpan.

Is it possible to include them alongside with the other BCL type mappings on the standard release?

I have implemented them like this:

    public class DateTimeOffsetType : ScalarType
    {
        public DateTimeOffsetType() : base("DateTimeOffset")
        {
        }

        public override bool IsInstanceOfType(IValueNode literal)
        {
            if (literal == null)
            {
                throw new ArgumentNullException(nameof(literal));
            }

            return literal is StringValueNode || literal is NullValueNode;
        }

        public override object ParseLiteral(IValueNode literal)
        {
            if (literal == null)
            {
                throw new ArgumentNullException(nameof(literal));
            }

            if (literal is NullValueNode)
            {
                return null;
            }

            if (literal is StringValueNode stringLiteral)
            {
                return DateTimeOffset.Parse(stringLiteral.Value, CultureInfo.InvariantCulture);
            }

            throw new ArgumentException(
                "The DateTimeOffsetType can only parse string literals.",
                nameof(literal));
        }

        public override IValueNode ParseValue(object value)
        {
            if (value == null)
            {
                return new NullValueNode(null);
            }

            if (value is DateTimeOffset t)
            {
                return new StringValueNode(null, t.ToString("O", CultureInfo.InvariantCulture), false);
            }

            throw new ArgumentException(
                "The specified value has to be a DateTimeOffset in order to be parsed by the DateTimeOffsetType.");
        }

        public override object Serialize(object value)
        {
            if (value == null)
            {
                return null;
            }

            if (value is DateTimeOffset t)
            {
                return t.ToString("O", CultureInfo.InvariantCulture);
            }

            throw new ArgumentException(
                "The specified value cannot be serialized by the DateTimeOffsetType.");
        }

        public override bool TryDeserialize(object serialized, out object value)
        {
            if (serialized is null)
            {
                value = null;
                return true;
            }

            if (serialized is string s)
            {
                var result = DateTimeOffset.TryParse(s, out var ts);
                value = ts;
                return result;
            }

            value = null;
            return false;
        }

        public override Type ClrType => typeof(DateTimeOffset);
    }

And 

    public class TimeSpanType : ScalarType
    {
        public TimeSpanType() : base("TimeSpan")
        {
        }

        public override bool IsInstanceOfType(IValueNode literal)
        {
            if (literal == null)
            {
                throw new ArgumentNullException(nameof(literal));
            }

            return literal is StringValueNode || literal is NullValueNode;
        }

        public override object ParseLiteral(IValueNode literal)
        {
            if (literal == null)
            {
                throw new ArgumentNullException(nameof(literal));
            }

            if (literal is NullValueNode)
            {
                return null;
            }

            if (literal is StringValueNode stringLiteral)
            {
                return TimeSpan.Parse(stringLiteral.Value, CultureInfo.InvariantCulture);
            }

            throw new ArgumentException(
                "The TimeSpanType can only parse string literals.",
                nameof(literal));
        }

        public override IValueNode ParseValue(object value)
        {
            if (value == null)
            {
                return new NullValueNode(null);
            }

            if (value is TimeSpan t)
            {
                return new StringValueNode(null, t.ToString("c", CultureInfo.InvariantCulture), false);
            }

            throw new ArgumentException(
                "The specified value has to be a TimeSpan in order to be parsed by the TimeSpanType.");
        }

        public override object Serialize(object value)
        {
            if (value == null)
            {
                return null;
            }

            if (value is TimeSpan t)
            {
                return t.ToString("c", CultureInfo.InvariantCulture);
            }

            throw new ArgumentException(
                "The specified value cannot be serialized by the TimeSpanType.");
        }

        public override bool TryDeserialize(object serialized, out object value)
        {
            if (serialized is null)
            {
                value = null;
                return true;
            }

            if (serialized is string s)
            {
                var result = TimeSpan.TryParse(s, out var ts);
                value = ts;
                return result;
            }

            value = null;
            return false;
        }

        public override Type ClrType => typeof(TimeSpan);
    }

**Comment by michaelstaib** [comment]
Actually, our DateTime type use DateTimeOffset underneath. In the GraphQL proposal came a DateTime type up that is called DateTime and is a DateTimeOffset underneath. So we are following this draft spec.

Moreover, we also accept DateTime for the same type.

I am not sure about  `TimeSpan`. so far I have resisted introducing this type since we would need to do it in a more general way. I will look what other GraphQL servers did regarding a span of time.

**Comment by CNHume** [comment]
Thank you Raphael Abreu, for providing your implementation of TimeSpanType.

I use the SQL time(2) Data Type to specify "TimeOfDay", which was causing HotChocolate 10.4.3 to throw:

```
HotChocolate.SchemaException: Unable to infer or resolve a schema type from the type reference `Output: System.TimeSpan`.
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   etc.
```
your class, along with the requisite call to `.BindClrType<TimeSpan, TimeSpanType>()` fixed this.

Hopefully, a fix will make it into the next General Release.

**Comment by michaelstaib** [comment]
@CNHume it actually is in the version 11 branch now, so it will be part of version 11.
https://github.com/ChilliCream/hotchocolate/blob/master/src/HotChocolate/Core/src/Types/Types/Scalars/TimeSpanType.cs
