### ISSUE TITLE
Simpler extension of basic scalar types

### ISSUE THREAD

**Issue by raphaabreu** [ChilliCream/hotchocolate#1442]
Hello,

I have an API that uses custom scalars to add meaning to the values being retrieved on the fields. For instance, on some places I have a field that stores how many seconds an operation can take and I have a custom Seconds scalar to make it clear to the consumer that this particular field stores time information on that particular unit.

Other cases include Degrees (decimal number from 0 to 360) for angles, Meters (decimal) for distances, MetersPerSecond for speeds, etc. If this information is not provided on the scalar itself, the fields would have to be named to denote what physical unit they are on or I would have to rely solely on the argumentation to clarify this. Having custom scalars make the API much more elegant and easier to understand.

At this moment, the only way I found to do this is to create a whole new custom scalar for each variation, even when the only thing changing is just the name of the type.

Is there a simpler way to map a custom scalar named "MetersPerSecond" to the Clr`s decimal type?

Thanks and keep up the AWESOME work!

**Comment by michaelstaib** [comment]
Version 11 allows that already.

It can already be used in the previews

**Comment by michaelstaib** [comment]
Here is an example https://github.com/ChilliCream/hotchocolate/blob/50f9e649201f9202ee08fdac585a0361933ad927/src/HotChocolate/Core/src/Types/Types/Scalars/IntType.cs#L28

**Comment by michaelstaib** [comment]
Since we already support this I will close this issue.

**Comment by raphaabreu** [comment]
Awesome! Thanks!!
