### ISSUE TITLE
SchemaException: Unable to create instance of type `` 

### ISSUE THREAD

**Issue by sfmskywalker** [ChilliCream/hotchocolate#1447]
**Describe the bug**
Types containing methods with a generic type argument yield the following exception:

```
HotChocolate.SchemaException: Multiple schema errors occured:
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.
Unable to create instance of type ``.

// ...(goes on for a total of 999 errors)
```

**To Reproduce**
1. Create a new C# class containing one property and one method that has a generic type. For example:

```csharp
public class Foo
{
   public string Bar { get; set; }
   public string FooBar<T>() => Bar;
}
```

2. Create a class called `FooType : ObjectType<Foo>`.
3. Register the `FooType` with the schemabuilder and notice the exception I mentioned will occur.

Removing the `<T>` generic type argument works around the issue.
Admittedly, the example here doesn't make much sense, but I have a type in my application that uses the generic type to cast an object to T.

**Expected behavior**
No error should occur.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by michaelstaib** [comment]
Hi, 

we will remove generic methods from the auto-detection since they do not make sense.

We will integrate the fix in version 10.4.0

**Comment by sfmskywalker** [comment]
Makes sense. Thanks!

**Comment by michaelstaib** [comment]
After some testing also Methods returning Task without any value seem to cause issues in some scenarios.
