### ISSUE TITLE
Memory Consumption of Hot Chocolate

### ISSUE THREAD

**Issue by traitmmm** [ChilliCream/hotchocolate#1448]
hello.
Today we did a small performance testing for HotChocolate in our simple project. 
We generated around ~12mb of data. 

My question: do you have any guesses how to improve current situation? because we have gap between Rest-like API and GraphQL Engine. 

results: 
DotTrace snapshot: https://www.dropbox.com/s/ojp9n8y2wb0dwyh/LineByLine.dtp?dl=0

![photo_2020-02-05_13-14-59](https://user-images.githubusercontent.com/59527661/73863972-edf48f80-4851-11ea-969d-5c1a98935994.jpg)

p.s. do not worry about 42 sec, such results because we ran project under profiling.

**Comment by michaelstaib** [comment]
We are working in this at the moment. The issue is how we build up the result. In our current experiments the memory consumptions is reduced by 90%.

**Comment by michaelstaib** [comment]
You should retest end of the week with 10.4.0 rc.1

**Comment by traitmmm** [comment]
Hello,

Thanks we will try to do it on the next week, and I will provide feedback.

**Comment by traitmmm** [comment]
Hello @michaelstaib 
Did you release 10.4.0-rc1 ?

**Comment by michaelstaib** [comment]
No, 

this is the pr to watch. 

We also have decided to only fix this in version 11 since it has quite an impact.

https://github.com/ChilliCream/hotchocolate/pull/1451

**Comment by michaelstaib** [comment]
P.S. PR #1451 also switches the result serialization from JSON.NET to System.Text.JSON.

**Comment by traitmmm** [comment]
Perfect, thanks for fast update!

**Comment by michaelstaib** [comment]
I put this on the 11 backlog ... we will soon merge the pr after we have finished of version 10.4 so have a couple days more patience. This is high on our list.
