### ISSUE TITLE
Database First approach

### ISSUE THREAD

**Issue by pmonty** [ChilliCream/hotchocolate#1449]
Little new to this and I have an existing database that I want to try and create a graphql api for. I guess I'll need to use EF to produce entities then plugin hot chocolate and go from there? Is this an ok approach to use EF with graphql?

Regards,
Paul

**Comment by michaelstaib** [comment]
Yes, you could do that.

**Comment by michaelstaib** [comment]
https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i
