### ISSUE TITLE
Modify IQueryable projection based on required fields

### ISSUE THREAD

**Issue by rankdalibor** [ChilliCream/hotchocolate#1455]
**Is your feature request related to a problem? Please describe.**
I'm using HotChocolate for couple of days already, and it really has some great features. One thing i thought it would be worth implementing (if not already and i'm unaware of it) is final IQueryable projection based on fields required by the GraphQL query.

If we have the following GraphQL query:
````graphql
query {
  posts(
    first: 5
  ) {
    edges {
      node {
        id
        title
      }
    }
  }
}
````
Following SQL query is created, based on LINQ expression.
````sql
SELECT TOP(@__p_0) [p].[Id], [p].[Title]
FROM [Posts] AS [p]
````
And that's perfectly fine, but if we toss out `title` field on example and perform following query:
````graphql
query {
  posts(
    first: 5
  ) {
    edges {
      node {
        id
      }
    }
  }
}
````
Same SQL query is created again, instead of the following query:
````sql
SELECT TOP(@__p_0) [p].[Id]
FROM [Posts] AS [p]
````

**Describe the solution you'd like**
I would love to be able to project only fields that user required, since it reduces cost of communicating with external DB, with sending smaller amount of bytes (shorter SQL) and receiving smaller amount of bytes back (result sets).

I know this doesn't necessary has to do anything with DB, but this really can be used in any LINQ scenario, where data is represented through IQueryable. This is especially useful for me when i'm projecting some entity to other DTO using AutoMapper library.

**Describe alternatives you've considered**
I've done something 'hacky' for me currently, so i suppose something similar, and probably better, can be implemented in this library itself.

````csharp
public static IQueryable<T> GetRequiredFieldsQuery<T>(this IQueryable<T> query, IResolverContext context)
        {
            var fields = context.FieldSelection.SelectionSet.Selections.Cast<FieldNode>().Select(f => f.Name.Value);
            return query.Select<T>($"new({string.Join(',', fields)})");
        }
````
This example only covers top-level fields of course. There is also a way to do the same thing when we have paging. Only difference is that we would need to 'dig' a bit though graph to get field names from `nodes` and `edges.node` fields.

**Potential problem**
One of the things i see as an issue here is that this feature would require from us to specify required backup fields for the query (like ID on example), or some fields that we need whether or not user required them for final projection.

**Additional context**
I'm using EntityFrameworkCore 3.1 and 11.0.0-preview.84 version of HotChocolate (and it's sub-packages like Filters, Sorting etc.)

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/pulls

**Comment by michaelstaib** [comment]
This feature is already on its way for 10.4

https://github.com/ChilliCream/hotchocolate/pull/1446

**Comment by rankdalibor** [comment]
Thanks @michaelstaib! I was not aware of this feature being in progress. I'm closing this issue now.
