### ISSUE TITLE
Subscriptions with Guids lead to different streams if different ways of setting the variables are used

### ISSUE THREAD

**Issue by Narmor** [ChilliCream/hotchocolate#1460]
**Describe the bug**
These two subscriptions should both get the same messages, but they dont:
First:
![grafik](https://user-images.githubusercontent.com/9481836/74165184-046d6300-4c25-11ea-9033-8feaa90308f7.png)
Second:
![grafik](https://user-images.githubusercontent.com/9481836/74166086-4d71e700-4c26-11ea-8036-1d2ff250bd0b.png)

This is what it looks like while debugging:
![grafik](https://user-images.githubusercontent.com/9481836/74165424-5dd59200-4c25-11ea-97a7-858cb2f5613d.png)

**To Reproduce**
Same as to #1157 

**Expected behavior**
Both get the same messages, but they don't. Only one receives the messages. Its the Second one by default. 
If you change the definition of the Eventdescription to stringify the Guids without hyphons it's the other way around:
![grafik](https://user-images.githubusercontent.com/9481836/74165921-1a2f5800-4c26-11ea-9b28-a0700ca1de55.png)

**Desktop (please complete the following information):**

**Additional context**
Using 10.3.5

**Comment by Narmor** [comment]
@michaelstaib Do you need an Repo to reproduce? I'm afraid i deleted the reproduction repo from #1157.

**Comment by michaelstaib** [comment]
No worries, we are working on an easier approach regarding subscriptions at the moment which will come with 10.4

**Comment by michaelstaib** [comment]
This one is now fixed with the new subscription API in 10.4.0-preview.8
