### ISSUE TITLE
DRAFT - Auto-discover missing types like interface implementations and extensions

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1466]
**DRAFT**

In general the SchemaBuilder discovers all types that are connected with the root type. The exception here are interface implementations and type extensions.

In a discussion on the slack channel we came to the conclusion that we should add an option to auto-discover theses things.

So, in order to help newcomers we should by default scan for interface implementations (if interfaces are registered with the schema) and type extensions on the assembly of the root types.

```csharp
SchemaBuilder.New()
    .AddQueryType<Query>()
    .Create();
```

This behaviour could be disabled if not desired.

Also we should have a way to explicitly point to assemblies from which we want import missing types:

```csharp
SchemaBuilder.New()
    .AddQueryType<Query>()
    .AddTypesFrom<Query>()
    .AddTypesFrom(assembly)
    .Create();
```

Disable auto discovery:

```csharp
SchemaBuilder.New()
    .AddQueryType<Query>()
    .DisableAutoDiscovery()
    .Create();
```

**Comment by tunurgitr** [comment]
I think `.AddTypesFrom(...)` is sufficient for performing type discovery and that incorporating that into `.AddQueryType<>()` might be unintuitive.

Especially since there was some talk of offering an option where a default Query type would be automatically created if a schema only defined type extensions for the query type.

I'm envisioning a way you could just do:

```csharp
SchemaBuilder.New()
    .AddTypesFrom(...)
```

And that could be the only thing you need to do, QueryRoot and MutationRoot would get built if any types try to extend them

**Comment by michaelstaib** [comment]
I am thinking multiple use-cases.

I think the default use-case is that users are defining their root types and registering them. Being in control over those is a good thing. 

I think from a usability standpoint being able to just say:

```csharp
SchemaBuilder.New()
    .AddQueryType<Query>()
    .Create();
```

Is quite nice since I define my root type and tell the engine exactly what root type it is. This is important since I could name query `QueryRoot` and still have a `Query` type in my schema.

But I like also that we could just say:

```csharp
SchemaBuilder.New().AddTypesFrom(...).Create();
```

And everything is inferred. Or maybe we should also have:

```csharp
Schema.FromAssembly();
```

In order to allow automatically creating root types we need for the root types a special attribute.

`ExtendQueryTypeAttribute`
`ExtendMutationTypeAttribute`
`ExtendSubscriptionTypeAttribute`

When registering a root type we actually do not need these but when we infer all types from an assembly these are necessary since `Query` might not be the root type query.

**Comment by hartmannr76** [comment]
This is actually what I stood up locally. One of the biggest things I'm personally looking for is "schema-first". We have client apps in other languages and being able to drive/test all development off a `.graphql` file is a huge win for my org. This lib provides pretty intuitive/powerful support for that, which is why I've spent a lot of time the past few weeks experimenting with it, so thank you for writing this amazing lib!

In the schema-first approach, not sure if there are existing ways of doing this, I started adding a handful of things to work with this schema

```
type NestedDroid {
    name: String!
}

type Droid {
    id: String!
    name: String!
    nDroid: [NestedDroid]!
}

type Query {
    hero: Droid!
}
```

Resulting in doing 
```
SchemaBuilder.New()
.AddDocumentFromFile(System.IO.Path.Join(Directory.GetCurrentDirectory(), "Schema.graphql"))
.BindTypesFromAttributes()
```

I added a few simple attributes to get the ball rolling
```
    [AttributeUsage(AttributeTargets.Class)]
    public class ResolverAttribute : Attribute
    {
        public Type Of { get; private set; }
        public ResolverAttribute(Type of)
        {
            Of = of;
        }
    }
    
    [AttributeUsage(AttributeTargets.Class)]
    public class ComplexTypeAttribute : Attribute { }
```

Allowing me to simply attach to the types I wanted
```
    [ComplexType]
    public class Query
    {
        public string Hello() => "world";
        public Droid Hero(IResolverContext context)
        {
            context.ContextData["Foo"] = "bar";
            return new Droid();
        }
    }
    
    [ComplexType]
    public class Droid
    {
        public string id => "123";
    }
    
    [ComplexType]
    public class NestedDroid
    {
        public async Task<string> Name([Parent] NestedDroid droid, IResolverContext context)
        {
            await Task.Delay(10);
            return $"{droid}: {context.ContextData["Foo"]}";
        }
    }
    
    [Resolver(typeof(Droid))]
    public class DroidResolver
    {
        public string Name(Droid d, IResolverContext context, [Service] Service svc)
        {
            var a = context.ContextData["Foo"];
            
            return svc.NameGetter();
        }
        
        public List<NestedDroid> nDroid() => new [] { new NestedDroid(), new NestedDroid() }.ToList();
    }
```

It's super basic, but my binder func was just 
```
public static ISchemaBuilder BindTypesFromAttributes(this ISchemaBuilder builder)
{
    void AddBindings<T>(Func<Type, IBindingBuilder> builderFunc) where T : Attribute
    {
        var types = Assembly.GetCallingAssembly()
            .GetTypes()
            .Where(t => t.GetCustomAttribute<T>() != null)
            .Select(builderFunc);
        foreach (var type in types)
        {
            builder.AddBinding(type.Create());
        }
    }            
    
    AddBindings<ResolverAttribute>(t =>
    {
        var attribute = t.GetCustomAttribute<ResolverAttribute>();
        return ResolverTypeBindingBuilder.New()
            .SetFieldBinding(BindingBehavior.Implicit)
            .SetResolverType(t)
            .SetType(attribute.Of);
    });
    
    AddBindings<ComplexTypeAttribute>(t => 
        ComplexTypeBindingBuilder.New()
        .SetFieldBinding(BindingBehavior.Implicit)
        .SetType(t));

    return builder;
}
```

Would love to hear your thoughts or discuss more about this, but I went with the simpler names because theres nothing really to "extend" off of these since they are the original types

**Comment by PejmanNik** [comment]
@michaelstaib  What do you think about the `Scrutor` approach?

```csharp
FromAssemblies(params Assembly[] assemblies)
FromCallingAssembly();
FromAssemblyOf<T>();
```

**Comment by dhaligas** [comment]
@michaelstaib any update on this?  I would love to have auto register queries and mutations by convention

**Comment by tobias-tengler** [comment]
This is now implemented using the `HotChocolate.Types.Analyzer` source generator. Simply add the package to your .csproj file:

```xml
 <PackageReference Include="HotChocolate.Types.Analyzers" Version="12.7.0-preview.1">
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
       <PrivateAssets>all</PrivateAssets>
     </PackageReference>
```

Now you should get access to an extensions method on the `IRequestExecutorBuilder` named after your assembly: `Add{assemblyName}Types()`.
Examples:
- Assembly name: MyApp, method name: AddMyAppTypes()
- Assembly name: MyApp.Demo, method name: AddDemoTypes()

The name can also be customized using the `ModuleAttribute`: 
```csharp
[assembly: Module("CustomName")]
```
the method would be noe called `AddCustomNameTypes`.

Inside of this extension method, the source generator registers everything that inherits from a Type, e.g. `ObjectType<T>` or `ImterfaceType<T>`, and everything that is annotated using type attributes, e.g. `[ObjectType]` or `[InterfaceType]`. DataLoaders are also registered.
