### ISSUE TITLE
Schema stitching refresh

### ISSUE THREAD

**Issue by stubbz** [ChilliCream/hotchocolate#1469]
Hey, my team is using schema stitching and really love it!

I did have one question about it to which I could've find an answer for in the docs.

If you've got graph's A and B with A pointing to B (A -> B), if B's schema changes/is added to, it does not appear to propagate to A automatically without a server reboot or some other type of intervention. Is there a setting to do this?

**Comment by michaelstaib** [comment]
We are working on this at the moment. If you head over to our slack channel you can find the roadmap.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by stubbz** [comment]
Awesome, really great to hear as we very much have enjoyed schema stitching thus far!
