### ISSUE TITLE
Unseal Authorize Attribute

### ISSUE THREAD

**Issue by Dispersia** [ChilliCream/hotchocolate#1472]
Problem:
Asp.net Cores Authorize attribute is not sealed. This allows overriding for custom behavior, such as having policys be an enum, then resolve it and set in the constructor. Hot chocolates is Sealed, not allowing for customization.

Solution:
Unseal Authorize attribute, to mimic Microsofts API

Alternatives:
Simply hard coding the strings, or making a const file that everything can call from, however that would only slightly solve this one scenario.

**Comment by marcin-janiak** [comment]
The same thing goes for StateAttribute.

**Comment by michaelstaib** [comment]
@Dispersia do you want to do a pr?

**Comment by michaelstaib** [comment]
This is now merged.
