### ISSUE TITLE
[Berry] List of enums generated invalid code.

### ISSUE THREAD

**Issue by Alxandr** [ChilliCream/hotchocolate#1473]
**Describe the bug**
Trying to generate a client for a graph that has a list of enums generates invalid code. The generated code does not compile.

**To Reproduce**
1. Use a schema with a list of enums (see example below).
2. Use a query that fetches said list (example below).
3. Build (or run dotnet-graphql manually).

Schema:

```graphql
schema {
  query: Query
}

type Query {
  visibilities: [Visibility!]!
}

enum Visibility {
  INTERNAL
  PUBLIC
}

```

Query:

```graphql
query getVisibilities {
  visibilities
}
```

Generated code:

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json;
using StrawberryShake;
using StrawberryShake.Configuration;
using StrawberryShake.Http;
using StrawberryShake.Http.Subscriptions;
using StrawberryShake.Transport;

namespace BerryClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public class GetVisibilitiesResultParser
        : JsonResultParserBase<IGetVisibilities>
    {

        public GetVisibilitiesResultParser(IValueSerializerCollection serializerResolver)
        {
            if (serializerResolver is null)
            {
                throw new ArgumentNullException(nameof(serializerResolver));
            }
        }

        protected override IGetVisibilities ParserData(JsonElement data)
        {
            return new GetVisibilities
            (
                DeserializeListOfVisibility(data, "visibilities")
            );

        }

        private IReadOnlyList<Visibility> DeserializeListOfVisibility(JsonElement obj, string fieldName)
        {
            JsonElement list = obj.GetProperty(fieldName);
            int listLength = list.GetArrayLength();
            var listList = new Visibility[listLength];

            for (int i = 0; i < listLength; i++)
            {
                JsonElement element = list[i];
                listList[i] = (Visibility)_visibilitySerializer.Deserialize(element.GetString())!;
            }
            return listList;
        }
    }
}
```

The issue here is in the `DeserializeListOfVisibility` method, because it trieds to call `_visibilitySerializer.Deserialize`, however `_visibilitySerializer` does not exist.

**Expected behavior**
Berry should generate working code. In this case; that probably just means adding a `private readonly IValueSerializer _visibilitySerializer;` that get's initialized in the constructor.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by michaelstaib** [comment]
I think I have fixed this with the new generator ... will double check.

**Comment by michaelstaib** [comment]
As soon as I have the new generator in you can help contribute if you want. The new code is now super clean and easy to understand :)

**Comment by Alxandr** [comment]
Yeah, I will probably take a look at that. I have some things I consider looking at, like being able to set the enum values.

**Comment by michaelstaib** [comment]
This should be fixed.
