### ISSUE TITLE
Accessing and Modifying State in Resolvers and Middleware

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1476]
Currently accessing state in compiled resolver methods can be done with the `StateAttribute`.

We can get a global state like the following:

```csharp
public async Task<Foo> GetFooAsync([State("key")]string argument)
{

}
```

Also we can access scoped state like the following:

```csharp
public async Task<Foo> GetFooAsync([State("key", IsScoped = true)]string argument)
{

}
```

While this does not really look sexy it works for now.

Where it becomes not so nice is with changing the state. 
In order to do that we need to inject the full resolver context which will make 
optimizing this resolver impossible  since the execution engine now cannot analyze 
what the resolver really uses since it could be anything.

```csharp
public async Task<Foo> GetFooAsync(IResolverContext context)
{
    context.ContextData["key"] = "foo";
}
```

Another thing here is that with version 11 we introduced a local state which only exists within
a specific resolver pipeline.

## Accessing States

With version 11 we now want to allow people to access and modify state in a better way.

We will introduce three new  attributes:

- GlobalStateAttribute
- ScopedStateAttribute
- LocalStateAttribute

```csharp
public async Task<Foo> GetFooAsync([GlobalState]string key)
{

}
```

The above example will inject a state called `key` from the global state.

The key/name for the state is inferred from the argument name.

We still can provide the key if we want to.

```csharp
public async Task<Foo> GetFooAsync([GlobalState("MyKey")]string argument)
{

}
```

If the specified context data does not exist a runtime exception is thrown.

## Accessing States with TryGet

Sometimes we want to access a state if it is there or get a default if it is not there.

Basically we would like to do something like:

```csharp
if(!context.ContextData.TryGet("key", out string s)) 
{
    s = "myDefault";
}
```

For this scenario the resolver context will infer this from the following parameter declaration:

```csharp
public async Task<Foo> GetFooAsync([GlobalState]string key = "myDefault")
{

}
```

The above resolver will get the default injected if there is now context data found for `key`.

## Modifying States

The last scenario that we will now support is changing the state on the context:

```csharp
public async Task<Foo> GetFooAsync([GlobalState]SetState setKey)
{
    setKey("myNewValue");
}
```

Again we can infer the name of argument if it is either the key itself or `set{KeyName}`.

As mentioned before it is still possible to explicitly specify the key in the attribute.

**Comment by tunurgitr** [comment]
Maybe we can tackle two things here....I've been wanting to have a separate "dependency registration" for resolver methods, where you could define a factory object/method for retrieving the object from the query context.....

Say I have a PCF resolver

```
public int UserId(MyUser user) => user.Id;
```

**Comment by tunurgitr** [comment]
Maybe we can tackle two things here....I've been wanting to have a separate "dependency registration" for resolver methods, where you could define a factory object/method for retrieving the object from the query context.....

Say I have a PCF resolver

```
public int UserId(MyUser user) => user.Id;
```

I want to do something on my schema builder:
```
  SchemaBuilder.New()
    .AddResolverInjectedService<MyUser>(ctx => ctx.ContextData["User"] as MyUser)
```

**Comment by michaelstaib** [comment]
You would still need the attribute since otherwise we cannot know from which context we shall get something.
