### ISSUE TITLE
Nullable fields are not sortable

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#1481]
Per https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1581887583149800

In version 10.3.5 with `.UseSorting()`, nullable fields such as `DateTime?` are not sortable by default. 

Attempts to sort by such fields will throw the error "The specified input object field `xxx` does not exist."

Was able to work around it by creating a custom SortInputType, and explicitly marking the nullable field as sortable (`descriptor.Sortable(i => i.MyNullableField);`).

**Comment by michaelstaib** [comment]
Hi @hognevevle there is a fix already merged into 10.4.0. So, if you grab one of the 10.4.0 previews it should already work.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/commit/012c4719bfb67889eb75c7037bb00ab4b0c598e4

**Comment by michaelstaib** [comment]
I am closing this issue since @PascalSenn already fixed it :)
