### ISSUE TITLE
ObjectType with an Interface in it throws error "unable to resolve"

### ISSUE THREAD

**Issue by lTimeless** [ChilliCream/hotchocolate#1483]
Hello,

I have a problem with an interface that is inside of another class.
my Class looks like 
  ```
public class Plugin
    {
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string? Description { get; set; }
        public string? PluginType { get; set; }
        public string SystemPath { get; set; }
        public double Version { get; set; } 
        public bool Active { get; set; } 

        public IPlugin Plugin { get; set; }

        public PluginDto()
        {
            Version = 1.0d;
        }
```
    
And I want to return that type in a query it will throw, on the server startup, an exception that the schema can't resolve IPlugin. 

` HotChocolate.SchemaException: Unable to infer or resolve a schema type from the type reference `Input: NewHaven.PluginBase.IPlugin`.`

I tried creating an Interfacetype for IPlugin and in the Objecttype<Plugin> i wrote
"descriptor.Field(x => x.Plugin).Type<PluginInterfaceType>();"
that did't work
I wrote "descriptor.Ignore(x=>x.Plugin);"
that did't work aswell.

So my question is, what I can do to return an interface inside of another class?
Am I doing something wrong ?

Best Regards

**Comment by michaelstaib** [comment]
What do you expect IPlugin to be?

should it be an interface in GraphQL?

If so have you registered the instances of that interface with the schema builder?

**Comment by lTimeless** [comment]
IPlugin can be a class from another assembly that inherits from this interface.
And yes it should be an interface.
What exactly do you mean with registered?

**Comment by lTimeless** [comment]
Can be closed. 
I solved it
