### ISSUE TITLE
Different schemas for different endpoints

### ISSUE THREAD

**Issue by lTimeless** [ChilliCream/hotchocolate#1484]
Hello,

my question is if it is possible to have multiple endpoints with different schemas matched to it?
So I can attach asp.net core authorization/authentication to the endpoints.
Like adding Jwt to one endpoint and not to the other

for example:

endpoint: "/identity" has only queries/mutations : login and registration 
and everyone can connect to that endpoint

endpoint: "/graphql" has all the other queries/mutations/... 
that only users with a jwt token can access

---
```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapPost("/graphql", context => Task.CompletedTask)
                    .RequireAuthorization(new AuthorizeAttribute()
                    { AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme }) ;
}
```
If I add this code in the startup, all queries/etc. will only be callable if the user has a Jwt token.
If I add a second endpoint without Jwt security , I have two endpoints but from both i can call everything.

Or is the approach differnt and I'm mixing something up?

**Comment by michaelstaib** [comment]
This is on the list for version 11.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/projects/16

**Comment by michaelstaib** [comment]
I will close this since we are already tracking this in the project

**Comment by Jan080906** [comment]
Hello @michaelstaib , is there any work around for this?

**Comment by michaelstaib** [comment]
Hi @Jan080906, unfortunately no. We have started work on this an I expect a preview beginning of April.
