### ISSUE TITLE
Improved union types for PCF

### ISSUE THREAD

**Issue by shoooe** [ChilliCream/hotchocolate#1490]
**Is your feature request related to a problem? Please describe.**

Currently there are 2 ways to make union types:
    1. type descriptors
    2. marker interfaces

The first is not compatible with pure-code-first schema because you can't use the GraphQL type as return value.

The second option works for pure-code-first, but has the problem that you don't define the union as a set of types but you define the types as part of different unions. Therefore, for example, if you have an `AppError` type that is part of 20+ unions you'll have `AppError` implementing 20+ interfaces. Even though the number of interfaces a type is [practically limitless](https://stackoverflow.com/a/4286853/493122), this is suboptimal because in order to figure out what's the set of types for a union you have to scan all other types (both while reading and probably at the HC implementation level).

**Describe the solution you'd like**

I propose a custom library type (similarly to `Optional`) named `Union` that has overloads up to 16 types (12 would also be acceptable I guess but I wouldn't go lower than 12). 

So, for example you might have `Union<A>`, `Union<A, B>`, `Union<A, B, C>`, ...

This would just be a "marker" abstract class that defines implicit and explicit conversions from the types defined as type arguments.

The implementation would be similar to https://github.com/mcintyre321/OneOf and https://github.com/DiscU/DiscU but could be even simpler (just define explicit and implicit conversions and nothing else).

You'd then define a union type via something like:

```
public class CreateUserResult : Union<User, ValidationError, AuthorizationError> {}
```

and then, thanks to the implicit/explicit conversions, you would be able to use it as a return type and return `User`, `ValidationError` or `AuthorizationError`.

**Comment by michaelstaib** [comment]
I think your proposal would be good to discuss in our community standup. I will put it on the agenda.

**Comment by shoooe** [comment]
@michaelstaib Thanks.

**Comment by shoe-diamente** [comment]
@michaelstaib Hi Michael, was this discussed by any chance? I've seen it's on the 11.x.x milestone. Does that mean that you decided in favour?

**Comment by michaelstaib** [comment]
No, the milestone means we are looking into it after 11.0.0. We are at the moment laser focused on the execution engine and strawberry shake

**Comment by michaelstaib** [comment]
Also, Microsoft is working on unions for c# so we might even wait a little to see if they are coming in c# 9 or 10

**Comment by michaelstaib** [comment]
https://github.com/dotnet/csharplang/blob/master/proposals/discriminated-unions.md

**Comment by shoe-diamente** [comment]
@michaelstaib TBH I wouldn't hold my breath for discriminated unions entering C# any time soon. Other features such as "records" have been in the pipeline for much longer and were promised since C# 6 but at C# 8 they are nowhere to be found.

If discriminated unions were ever to make it into C# we could support them as well.
But even then GraphQL unions are not discriminated unions. They are more like a union of possible types, but they are not "tagged" in the same way a discriminated union (like in F#) does.

I think unions are one of the fundamental types in GraphQL that should be easy to use. For example representing errors in the scema require unions to represent them correctly.

If I were to work on a PR for it would there be a chance for it entering v11?

**Comment by michaelstaib** [comment]
> If discriminated unions were ever to make it into C# we could support them as well.

I do have other information on that.

But we can still explore this type. Do you want to do a PR?

**Comment by shoe-diamente** [comment]
> I do have other information on that.
You do?

> But we can still explore this type. Do you want to do a PR?
Sure, I can give it a try.

**Comment by michaelstaib** [comment]
Lets discuss details on slack ... we also can do a zoom call if you are stuck.

**Comment by shoooe** [comment]
By the way, with reference to your previous comments: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

Maybe records will make it into C# 9 this time (I'm [still](https://stackoverflow.com/questions/25400825/what-is-a-proposed-record-class-in-c-sharp-6) [very](https://www.kenneth-truyers.net/2016/01/20/new-features-in-c-sharp-7/) [skeptical](https://www.devsanon.com/c/c-8-is-introducing-records/)), but discriminated unions are nowhere to be seen.

**Comment by michaelstaib** [comment]
discriminated are coming ... they are on the roadmap to version 10. I was under NDA previous to build so I did not want to speak more about it. If you watch mats talk again you will see him mentioning them although just with one sentence. They are planned for c# 6 which puts them into fall next year.

**Comment by dzmitry-lahoda** [comment]
@michaelstaib any more info of how these will be done?  

If these will be record base, could we have next kind of records to union? I mean out of hack above or like this https://github.com/dadhi/ImTools/blob/410dcbbd99e8bb2483dc1d682773824a22283c77/src/ImTools/ImTools.cs#L232 or current marker interface, sealed classes; it seems records are best and immediately useful. It seems so easy to implement so - just scan assembly for patter.

https://github.com/dotnet/csharplang/blob/master/proposals/discriminated-unions.md#simple-class-members

https://github.com/dotnet/csharplang/issues/4174

```
public abstract record SomeDiscriminatedUnion(string Name)
{
    public sealed record FirstKind(string Name, int A) : SomeDiscriminatedUnion(Name);
    public sealed record SecondKind(string Name, int B) : SomeDiscriminatedUnion(Name);
    public sealed record ThirdKind(string Name, bool C) : SomeDiscriminatedUnion(Name);
    public sealed record FourthKind(string Name) : SomeDiscriminatedUnion(Name);
}
````

**Comment by dzmitry-lahoda** [comment]
Dzmitry Lahoda  13 minutes ago
[UnionType(nameof(Foo))]
[UnionRuntimeTypes(typeof(A), typeof(B), typeof(C))]
public abstract class Foo {
  private Foo(){};
  public sealed class A: Foo {};
  public sealed class B: Foo {};
  public sealed class C: Foo {};
}
thanks, yes - it will work. But better allow to .RegisterAbstractClassesWithPrivateCtrosAndChildSealedClassesAsUnionFromAssembly()
white_check_mark
eyes
raised_hands




Dzmitry Lahoda  12 minutes ago
or same for record with child records.

Dzmitry Lahoda  10 minutes ago
records can be abstract, can inherit, and can be sealed, so not sure if ctors can be private

Dzmitry Lahoda  1 minute ago
    public abstract record Foo
    {
        private Foo(){}
        public sealed record A: Foo{}
        public sealed record B: Foo{}
        public sealed record C: Foo{}
    }
compiles

Dzmitry Lahoda  < 1 minute ago
RegisterAbstractRecordsWithPrivateCtorsAndChildSealedRecordsAsUnionFromAssembly
