### ISSUE TITLE
Custom Scalar example in the docs uses the wrong exception type

### ISSUE THREAD

**Issue by chris-findlay** [ChilliCream/hotchocolate#1492]
**Describe the bug**
The docComments for the abstract members of `ScalarType` mention explicitly what exceptions each might throw, but the example code throws `ArgumentException` instead of `ScalarSerializationException` like the code docs indicate.

**To Reproduce**
1. Go to [the Custom Scalars page in the docs.](https://hotchocolate.io/docs/custom-scalar-types#custom-scalars)
2. See error

**Expected behavior**
I would expect reference implementations to be as correct as possible relative to the documentation of the code involved.

**Desktop (please complete the following information):**
 - N/A

**Additional context**
I found https://github.com/ChilliCream/hotchocolate/issues/1485 and wanted to add a comment, but can't currently.  I was going to say that I remember seeing some dotNet docs way back that would describe the what once, then have a tabbed box for code examples for each language.

Perhaps something similar might work for your docs - describe the what once, and have a tabbed box with code examples and/or specific descriptions about each flavour.

**Comment by chris-findlay** [comment]
Also, the docComments for `ScalarType:TryDeserialize(serialized, out value)` read like they were written for the Deserialize method not the TryDeserialize method.

**Comment by michaelstaib** [comment]
The docs on that are dated. We have started to rethink the documentation and will add a complete new documentation with version 11

**Comment by michaelstaib** [comment]
Thanks for reporting this
