### ISSUE TITLE
HotChocolate.Templates.Server does not compile

### ISSUE THREAD

**Issue by danjagnow** [ChilliCream/hotchocolate#1493]
**Describe the bug**
The **HotChocolate.Templates.Server** template produces a project that does not compile because **Startup.cs** is missing a `using` statement.

**To Reproduce**
1. Make sure you have installed the latest template via `dotnet new -i HotChocolate.Templates.Server`, uninstalling first if necessary.
2. Follow the steps described at https://hotchocolate.io/docs/dotnet-cli to create a new project.  An example follows:

```cmd
C:\Dev>mkdir graphql-demo

C:\Dev>cd graphql-demo

C:\Dev\graphql-demo>dotnet new graphql
The template "HotChocolate GraphQL Server" was created successfully.

C:\Dev\graphql-demo>dotnet restore
  Restore completed in 527.57 ms for C:\Dev\graphql-demo\graphql-demo.csproj.

C:\Dev\graphql-demo>dotnet run
Startup.cs(22,22): error CS1061: 'IServiceCollection' does not contain a definition for 'AddDataLoaderRegistry' and no accessible extension method 'AddDataLoaderRegistry' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [C:\Dev\graphql-demo\graphql-demo.csproj]
Startup.cs(25,33): error CS0103: The name 'SchemaBuilder' does not exist in the current context [C:\Dev\graphql-demo\graphql-demo.csproj]
Startup.cs(25,22): error CS1061: 'IServiceCollection' does not contain a definition for 'AddGraphQL' and no accessible extension method 'AddGraphQL' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [C:\Dev\graphql-demo\graphql-demo.csproj]

The build failed. Fix the build errors and run again.

C:\Dev\graphql-demo>
```

**Expected behavior**
The `dotnet run` command compiles without errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 Professional

**Additional context**
Adding a `using HotChocolate;` statement to **Startup.cs** fixes the compilation issue.  It would also be helpful if the docs at https://hotchocolate.io/docs/dotnet-cli told you to visit https://localhost:5001/playground/.  I had to search around for a while before I figured that out.

**Comment by michaelstaib** [comment]
Thanks for reporting this.

**Comment by sporeservant** [comment]
I can confirm same problem on Mac OSX, the merged PR does fix it. Thanks!

**Comment by michaelstaib** [comment]
This one is fixed on 11 but not on 10. @sporeservant do you still want to fix that? The branch for version 10 is `version_10_0_0_master`. We want to close version 10.5 next week.

**Comment by michaelstaib** [comment]
This one is fixed ....
