### ISSUE TITLE
Subscription not working on the Star Wars example

### ISSUE THREAD

**Issue by Oxyrus** [ChilliCream/hotchocolate#1499]
**Describe the bug**

The subscription can't be established in the Star Wars example. After following the instructions [here](https://hotchocolate.io/docs/example-star-wars-code-first) and starting the project, the following subscription will return an error:

```gql
subscription {
  onReview(episode: EMPIRE) {
    id
  }
}
```

```json
{
  "error": "Could not connect to websocket endpoint wss://localhost:44347/graphql/playground/... Please check if the endpoint url is correct."
}
```

![image](https://user-images.githubusercontent.com/11398826/75162562-bf006980-56eb-11ea-8869-ba4a745dbdcf.png)

The websocket is configured in the `Startup.cs` file:

![image](https://user-images.githubusercontent.com/11398826/75162933-582f8000-56ec-11ea-9e72-dc0aaa2e35ca.png)

**To Reproduce**
1. Create a new project based on the Star Wars template as explained [here](https://hotchocolate.io/docs/example-star-wars-code-first)
2. Run the subscription shown above in the playground: https://localhost:44347/graphql/playground/
3. See error

**Expected behavior**

The subscription should be set, I'm not entirely sure if it's the endpoint that is wrong here, or something server-side.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 
 - Version 18363.657

**Additional context**

N/A

**Comment by michaelstaib** [comment]
The issue is with the playground middleware. If you use banana cakepop it works https://hotchocolate.io/docs/banana-cakepop

We will fix playground soon.
