### ISSUE TITLE
Mutation Issue while using derived class objects as a InputType

### ISSUE THREAD

**Issue by engopi** [ChilliCream/hotchocolate#1501]
**Describe the bug**
Hi Team,

I am using HotChocolate into my project. I need to create a mutation for derived class objects.
i did create an input object type for derived class ,mutation and mutation type as well as.
I did register qraphql with querytype and mutation type in startup project. The solution successfully compiled and ran.
When I send a request to my grapql server, I am facing an error. The error message was
**"'No compatible constructor found for input type type `Model"**

When I ignore the properties of the base class, then its working fine.
But i need to send the base class properties.

Please help me out.
 

*Expected behavior**
i need to send the base class properties in the derived class.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

**Additional context**
Framework: DotNet Core 3.1
HotChocolate : 10.3.5

**Comment by michaelstaib** [comment]
The issue here is that we cannot compile a factory for you input type since there are readonly props that we cannot set.

```
public class Foo 
{
    public string Bar { get; }
}
```

The above example has a property `Bar` which cannot be set since it is readonly.

If you give us a public constructor like so

```
public class Foo 
{
    public Foo(string bar) 
    {
         Bar = bar;
    }
    public string Bar { get; }
}
```

we can again compile a factory for your input.

**Comment by PascalSenn** [comment]
Closed as appears to be stale
