### ISSUE TITLE
Error with nested Generic types

### ISSUE THREAD

**Issue by hexenjag** [ChilliCream/hotchocolate#1506]
**Describe the bug**
When declaring a method that retrieve a custom paged list of users I used a custom class named PagedList<T>.  When executing I get schemas errors.  If I "embed" this class in another one then it works.

This return type doesn't work : 
`public async Task<PagedList<UserDTO>> GetAllUsers([Service] IUserService userService, int currentPage, int pageSize)`

This return type works : 
`public async Task<PagedUserDTO> GetAllUsers([Service] IUserService userService, int currentPage, int pageSize)`

Just a test class I created and that class works fine with the schema : 
`
public class PagedUserDTO
    {
        private PagedList < UserDTO > pagedList;

        public PagedUserDTO(PagedList<UserDTO> pagedList)
        {
            this.pagedList = pagedList;
        }

        public List<UserDTO> Data
        {
            get
            {
                return pagedList.Donnees;
            }
        }

        public int TotalCount
        {
            get
            {
                return pagedList.TotalCount;
            }
        }
        public int RowsPerPage
        {
            get
            {
                return pagedList.RowsPerPage;
            }
        }
        public int CurrentPage
        {
            get
            {
                return pagedList.CurrentPage;
            }
        }
    }
`

Here's the stack error trace I have : 
```
Exception levée : 'HotChocolate.SchemaException' dans HotChocolate.Types.dll
Une exception de type 'HotChocolate.SchemaException' s'est produite dans HotChocolate.Types.dll mais n'a pas été gérée dans le code utilisateur
Multiple schema errors occured:
Unable to create instance of type ``.    => This line repeats like 100 times...
Unable to create instance of type ``.
```
...

Packages references (csproj) : 
```
    <PackageReference Include="automapper" Version="9.0.0" />
    <PackageReference Include="automapper.extensions.microsoft.dependencyinjection" Version="7.0.0" />
    <PackageReference Include="GraphQL" Version="2.4.0" />
    <PackageReference Include="HotChocolate" Version="10.3.5" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="10.3.5" />
    <PackageReference Include="HotChocolate.AspNetCore.Playground" Version="10.3.5" />
    <PackageReference Include="HotChocolate.AspNetCore.Voyager" Version="10.3.5" />
    <PackageReference Include="HotChocolate.Types" Version="10.3.5" />
    <PackageReference Include="HotChocolate.Types.Filters" Version="10.3.5" />
    <PackageReference Include="HotChocolate.Types.Sorting" Version="10.3.5" />
    <PackageReference Include="Konscious.Security.cryptography.Argon2" Version="1.2.1" />
    <PackageReference Include="Library" Version="0.0.35-audit" />
    <PackageReference Include="microsoft.entityframeworkcore.proxies" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.2" />
    <PackageReference Include="microsoft.entityframeworkcore.tools" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="microsoft.openapi" Version="1.1.4" />
    <PackageReference Include="swashbuckle.aspnetcore" Version="5.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.20" />
```

**Expected behavior**
The first method call should work

**Desktop (please complete the following information):**
 - OS: Windows 10
Visual Studio 2019 Community version

**Comment by michaelstaib** [comment]
Can you provide a repo?

**Comment by hexenjag** [comment]
I will try to reproduce it in StarWars and create a repo with it for you.

**Comment by hexenjag** [comment]
Oh well...  I can't reproduce it in StarWars so I tought it was because of
EF Core so I created a dummy memory based EF Core database in another
project and even there it works...

So...  I will try to find the true cause, meanwhile you can close the issue
I guess...

**Comment by hexenjag** [comment]
Problem is I can't send you the repo i'm working on since it can contains confidential data so if you have some hints to be able to debug the schema loader that would be welcome!

**Comment by michaelstaib** [comment]
can you get onto slack and post me there the code of PagedList<UserDTO>.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by michaelstaib** [comment]
@hexenjag what is the status on this one? can we close it?

**Comment by hexenjag** [comment]
Yes since it was the generic sub method of my class that gave the error.
It was not meant to be returned and used by the schema.

Le mer. 4 mars 2020 06 h 51, Michael Staib <notifications@github.com> a
écrit :
