### ISSUE TITLE
TypeConverter not working

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1525]
Greetings all,

Thank you so much for this wonderful library. It is really helpful.

I am using a class called HashId for all ID's in my entity classes.
However, the JS client interfacing with my GraphQL API need to deal with these ID's as strings.

I am trying to convert these HashId fields to strings in my GraphQL schema with no luck.
Although, I have defined the converters from/to HashId and registered these converters, I still get HashId in my GraphQL schema for ID fields instead of strings.

Any clue? what am I doing wrong?

**Comment by PascalSenn** [comment]
Hi @geekox86  
Do you have a little code example? 

You have to add  a type convertet like the following
```csharp
services.AddTypeConverter<string, HashId>(from => HashId.Parse(from));
services.AddTypeConverter<HashId, string>(from => from.ToString());
```
And you have to register it on the schema builder : 
```csharp 
 .BindClrType<HashId, StringType>()
```

**Comment by geekox86** [comment]
@PascalSenn Wonderful! I was missing the last line for binding. Thank you :)
