### ISSUE TITLE
HotChocolate.Execution.Resolver.Error not triggered when Context.ReportError is called

### ISSUE THREAD

**Issue by hundreder** [ChilliCream/hotchocolate#1526]
**Describe the issue**
When you call ResolverContext.ReportError, HotChocolate.Execution.Resolver.Error diagnostic is not being executed. It's only executed when terminating error (exception) happens. This brings inconsistency of what error means, and did it happen or not. 

**To Reproduce**
1. Create diagnostic observer with HotChocolate.Execution.Resolver.Error method attribute with simple implementation, like logger.Error("Resolver error ocured")
2. Create simple resolver and call ResolverContext.ReportError inside of it 
3. Check for logs and you'l see they are empty

**Expected behavior**
HotChocolate.Execution.Resolver.Error being called and error being logged

**Desktop (please complete the following information):**
 - OS: Windows 10
 - HotChocolate 10.3.5

**Comment by PascalSenn** [comment]
This works in 11
```csharp
    public class TestObserver : DiagnosticEventListener
    {
        public override void ResolverError(IMiddlewareContext context, IError error)
        {
            Console.WriteLine(error.ToString());
        }
    }
    public class Query
    {
        public int  Test(IResolverContext context)
        {
            context.ReportError(ErrorBuilder.New().SetMessage("fooBar").Build());
            return 0;
        }
    }
    public class Startup
    {

        public void ConfigureServices(IServiceCollection services)
        { 
            services
                .AddRouting()
                .AddGraphQLServer()
                .AddQueryType<Query>() 
                .AddDiagnosticEventListener<TestObserver>();
  
      }  
     //....
    }

```
