### ISSUE TITLE
Enable Selection middleware for single item results

### ISSUE THREAD

**Issue by TheJayMann** [ChilliCream/hotchocolate#1536]
So far, the selection middleware is working well for most of my needs.  One exception is where a query is designed to return a single item, but still wanting to use the selection middleware to limit the data retrieved, which is especially useful when the item contains multiple list properties.

I can use the following inline middleware immediately before the UseSelection middleware to make this work with any IQueryable as well as query providers supporting IAsyncEnumerable without taking a dependency on EntityFrameworkCore.  This is based on the idea of SingleOrDefault, but a FirstOrDefault version can easily be derived.
```csharp
                .Use(next => async ctx => {
                    await next(ctx);
                    if (ctx.Result is IQueryable<Profile> profilesQuery) {
                        if (profilesQuery.Take(2) is IAsyncEnumerable<Profile> profiles) {
                            var foundProfile = false;
                            Profile? currentProfile = default;
                            await foreach (var profile in profiles) {
                                if (foundProfile) throw new InvalidOperationException("Sequence contains more than one element");
                                foundProfile = true;
                                currentProfile = profile;
                            }
                            ctx.Result = currentProfile;
                        }
                        else {
                            ctx.Result = profilesQuery.SingleOrDefault();
                        }
                    }
                })
```
The above code can be simplified if willing to take a dependency on System.Linq.Async.  I'd be hesitant in a generic sense of taking a dependency on EntityFrameworkCore, as I believe this should be designed to work with any IQueryable.

**Comment by PascalSenn** [comment]
@TheJayMann  Please check with https://github.com/ChilliCream/hotchocolate/tree/10.4.0-rc.1 👍  

```

**Comment by TheJayMann** [comment]
Everything appears to be working with regards to this new feature.
