### ISSUE TITLE
[Strawberry Shake] Support using websocket for queries and mutations

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#1538]
**Is your feature request related to a problem? Please describe.**
I've encountered this requirement when working with a specific [third party API](https://develop.zendesk.com/hc/en-us/articles/360001331787-Getting-started-with-the-Chat-Conversations-API), where HTTP is only used initially to create an authenticated session (which provides you with an authenticated websocket URI. As soon as you are authenticated, all subsequent requests (incl. queries and mutations) should be done over this assigned websocket. 

**Describe the solution you'd like**
An option like that provided by graphql-dotnet's client: https://github.com/graphql-dotnet/graphql-client/blob/develop/src/GraphQL.Client/GraphQLHttpClient.cs#L67

**Comment by michaelstaib** [comment]
@PascalSenn can we do that already with the new implementation?

**Comment by michaelstaib** [comment]
I think for this to work we have to take into account the protocols definition from the configuration file while generating.

**Comment by PascalSenn** [comment]
Just need to generate them if no HTTP was specified

**Comment by michaelstaib** [comment]
This one is now implemented.
