### ISSUE TITLE
Get Argument Value after Applying Converters

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1543]
Greetings all,

I have a bi-directional converters defined as follows:
```
...
.AddGraphQL(
  ...
  .BindClrType<HashId, StringType>()
)
.AddTypeConverter<StringToHashIdConverter>()
.AddTypeConverter<HashIdToStringConverter>()
```

Somewhere in my field middleware, I want to get the value of an argument of type HashId (i.e. shown in the schema as StringType). I am using `middlewareContext.Argument<IValueNode>(...)` but I get the StringType value instead of the HashId after applying the converters.

I do not want to manually figure out the argument type and call `Argument` with the correct type. Is there a way to request HotChocolate to figure out the correct type after applying the converters (i.e. get the HashId argument value)?

Thank you.

**Comment by michaelstaib** [comment]
Why do you not ask for `middlewareContext.Argument<HashId>(...)`?

**Comment by geekox86** [comment]
Because, I will have other converters and custom types. I want my code to be generic and not tie it to the types. It would be really nice if we can get the argument value in the correct type just like inside the resolvers.

**Comment by michaelstaib** [comment]
I see. What would be your proposal. 

The issue here is that for the type system if you do `middlewareContext.Argument<object>(...)` you will get a string since you told the type system that this argument is a string.

We are at the moment discussing to apply the resolver compiler to middleware and thus allowing the same kind of injection that you can do with resolver methods.

**Comment by geekox86** [comment]
If I can get the argument's converted ClrType somehow then I can call `middlewareContext.Argument(name, convertedClrType)` but no such thing exist currently.

**Comment by geekox86** [comment]
Sorry, I did not get your proposal; if you can explain a little. How do you apply the resolver compiler to the middleware? and what does injection have to do with arguments and converters?

**Comment by michaelstaib** [comment]
Ah so you just want a non generic argument method?

**Comment by michaelstaib** [comment]
I have put it to our 11 backlog

**Comment by geekox86** [comment]
A non-generic `Argument` method that accepts the argument's name and type.

However, we also need a way to get the argument's final/converted CLR type (i.e. as the one received in the resolvers). I am not sure if this is possible today from the `middlewareContext` ?

**Comment by michaelstaib** [comment]
This is possible with an InputValueFormatter.
