### ISSUE TITLE
UseSelection: Nested collection paging is not generating SQL limit

### ISSUE THREAD

**Issue by ghost** [ChilliCream/hotchocolate#1546]
Nested collection paging is not working properly with EF Core, based on my tests. It is projecting data properly for me, and displaying only limited number of objects i requested with first, last, after etc. But it isn't incorporating those parameters inside LINQ expression, later translated to SQL expression. Let me show you a quick dummy example.

Having following classes:
````csharp
public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }

    [UsePaging]
    [UseSorting]
    [UseFiltering]
    public ICollection<Post2> NestedPosts { get; set; }
}

public class Post2
{
    public int Id { get; set; }
    public string Content { get; set; }
}

public class PostDbContext : DbContext
{
    public PostDbContext(DbContextOptions<PostDbContext> options) : base(options) { }
    public virtual DbSet<Post> Posts { get; set; }
}

public class Query
{
    [UsePaging]
    [UseSelection]
    [UseSorting]
    [UseFiltering]
    public IQueryable<Post> GetPosts([Service] PostDbContext db) => db.Posts;
}
````
When i perform a GraphQL query:
````graphql
query	{
  posts(first: 11 order_by: {id: DESC}){
    nodes{
      id
      nestedPosts (first: 22 order_by: {id: DESC}) {
        nodes {
          id
        }
        totalCount
      }
    }
    totalCount
  }
}
````
is generating following SQL through EF Core:
[Parameters=[@__p_0='11']
````sql
SELECT COUNT(*)
FROM [Posts] AS [p]

SELECT [t].[Id], [p0].[Id]
FROM (
    SELECT TOP(@__p_0) [p].[Id]
    FROM [Posts] AS [p]
    ORDER BY [p].[Id] DESC
) AS [t]
LEFT JOIN [Post2] AS [p0] ON [t].[Id] = [p0].[PostId]
ORDER BY [t].[Id] DESC, [p0].[Id] DESC
````

As you can see, only main collection paging parameters are applied and nested ones are being ignored.
Nested sorting and filtering are working fine for me currently.

**Comment by michaelstaib** [comment]
we are moving this one to the next release (version 11)

**Comment by rankdalibor** [comment]
Thanks @michaelstaib 👍

**Comment by michaelstaib** [comment]
We might get this one into 10.4.0-rc.1

**Comment by rankdalibor** [comment]
@michaelstaib Any confirmation about this being part of next 10.4 RC? Or we should wait 11?

**Comment by michaelstaib** [comment]
@PascalSenn is working on it as we speak

**Comment by PascalSenn** [comment]
This is delay because we have to rework argument coercion in V11

**Comment by TDDinAction** [comment]
I cannot find [UseSelection] attribute in v11. So this attribute is obsoleted?

**Comment by tobiasr** [comment]
Just wanted to chime in and say that I'd like this feature. 👍

**Comment by PascalSenn** [comment]
@TDDinAction  it's now called UseProjection
@tobiasr  I think it would be doable for OffsetPaging but without SkipWhile it's not possible for CursorPagingation

**Comment by TDDinAction** [comment]
> CursorPagingation

Yes, I am trying to implement Relay-style cursor pagination.  If now it is UseProjection, it will not work after I defining ObjectType,
so now I uderstand what I don't need this attribute. But I get error "The field `text` does not exist on the type `DetailConnection`", but I set UsePaging<DetailType> and in this class I defined connection type: descriptor.Field(p => p.Text).Type<StringType>():
    
        public class MasterType : ObjectType<Master>
    {
            descriptor.Field(p => p.Detail).ResolveWith<Resolvers>(p => p.Get.Details(default!, default!)).UsePaging<DetailType>();
        }

        private class Resolvers
        {
            public IQueryable<.Detail> Get.Details (Master master, [ScopedService] Context context)
            {
                return context..Details.Where(p => p.MasterId == master.Id);
            }
        }
    }
    
        public class DetailType : ObjectType<Detail>
    {
        protected override void Configure(IObjectTypeDescriptor<Detail> descriptor)
        {
            descriptor.Field(p => p.Text).Type<StringType>();
        }

    }
    
It looks like some additional DetailConnection class is needed, but nowhere in the documentation, I don't find such an example.

**Comment by PascalSenn** [comment]
@TDDinAction How does you query look like?

**Comment by TDDinAction** [comment]
> How does you query look like?

        [UseDbContext(typeof(Context))]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Master> GetContact([ScopedService] Context context)
        {
            return context.Masters;
        }

        [UseDbContext(typeof(Context))]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Detail> GetCV([ScopedService] Context context)
        {
            return context.Details;
        }
