### ISSUE TITLE
your documentation is outdated Execute() no longer exist only ExecuteAsync

### ISSUE THREAD

**Issue by softchris** [ChilliCream/hotchocolate#1553]
your docs are outdated. This looks like a great lib but people can't even go through hello world on version 10.3.6 . Do you want everyone to downgrade to a lower version or what?

```
executor.Execute() // no longer exist
```

Now you are supposed to use

```
executor.ExecuteAsync(IReadOnlyQueryRequest, token)
```

but you leave no clue how to create an `IReadOnlyQueryRequest`?

**Comment by michaelstaib** [comment]
Execute is an extension method.

**Comment by michaelstaib** [comment]
So there are multiple extension methods on the executor.

Also the `IReadOnlyQueryRequest` can be created with the `QueryRequestBuilder`.

```csharp
QueryRequestBuilder.New()
   .SetQuery("query a($b: String) { c(b:$b) }")
   .AddVariable("b", "foo")
   .Create();
```

We are currently working on our new documentation site:
https://chillicream.github.io/hotchocolate/

Our current documentation is here:
https://hotchocolate.io

Also we have a very active community channel which is open do anybody:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

Also we have a new demo for pure code-first here:
https://github.com/ChilliCream/graphql-workshop/tree/master/src/Server/PureCodeFirst

We soon have a tutorial around that. Entity Framework Demos are going up after the weekend with the release of 10.4

Hope that helps in getting started.

**Comment by michaelstaib** [comment]
Last thing, for the extension methods to show up add the following using:

`using HotChocolate.Execution;`

**Comment by michaelstaib** [comment]
I am closing this issue since we answered your question.
