### ISSUE TITLE
Detect if a selection field has a custom resolver from middleware context?

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1557]
Greetings gentlemen,

Is there a way to detect if a selection field has a custom resolver (that I have defined and attached to the parent type in the schema) from middleware context?

Thank you.

**Comment by michaelstaib** [comment]
With version 11 we are introducing resolver metadata. This gives insights into what is uses.

**Comment by geekox86** [comment]
Thank you. Can I use CollectFields directly from middeware context in latest preview v11 ? or I still need v10?

**Comment by michaelstaib** [comment]
CollectFields is there but the metadata are not
