### ISSUE TITLE
Event Hook when subscription request

### ISSUE THREAD

**Issue by gioxoay** [ChilliCream/hotchocolate#1561]
Can someone help me how to execute a Task (trigger a code block) when have any subscription request?

Many thanks!

**Comment by gioxoay** [comment]
I found it
```
descriptor.Field(t => t.OnReview(default, default))
    .Type<NonNullType<AirportType>>()
    .Subscribe(DefaultSubscribeResolverAsync);```

**Comment by michaelstaib** [comment]
Also, here is an example for 10.4 with pure code-first:
https://github.com/ChilliCream/graphql-workshop/tree/master/src/Server

One example is with mongo the other one with entity framework.
