### ISSUE TITLE
Directive Location Documentation 

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1566]
We just need a piece of documentation because there is literally no documentation about directive locations except from the spec. The spec is not easy to read. Something like this would make sense
```graphql
directive @field_definition on FIELD_DEFINITION
directive @argument_definition on ARGUMENT_DEFINITION
directive @object on OBJECT
directive @interface on INTERFACE

interface Foo @interface  {
    bar: String
}

type SomeType implements Foo  @object   {
    bar: String
    field(arg: Int @argument_definition ): String @field_definition
}

directive @field on FIELD

fragment SomeFragment on SomeType {
  field @field 
}

```

**Comment by tobias-tengler** [comment]
I think this is covered sufficiently by the current documentation. It shows that there's an enum `DirectiveLocation` and how to use it.
