### ISSUE TITLE
Global DataLoader throws exception

### ISSUE THREAD

**Issue by ahnseunghae** [ChilliCream/hotchocolate#1571]
As mentioned below document, I trie to use Global DataLoader for caching between requests.
https://hotchocolate.io/docs/dataloaders

At fist request, It works as expected. But from second request, It throws exception like below.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at HotChocolate.DataLoader.DataLoaderBatchOperation.RequestBuffered(IDataLoader sender, EventArgs eventArgs)
   at GreenDonut.DataLoaderBase`2.RaiseRequestBuffered()
   at GreenDonut.DataLoaderBase`2.LoadAsync(TKey key, CancellationToken cancellationToken)
```

Here is the source code that can reproduce the problem.
https://github.com/ahnseunghae/GlobalDataLoaderTest

**Comment by michaelstaib** [comment]
There is a slight issue with your setup. But after fixing that I still get an issue from the DataLoader. It is kind of random. I will look into that with @rstaib. We also need to change the documentation to show how to setup GlobalDataLoaders.

```csharp
services.AddSingleton<IDataLoaderRegistry>(sp => 
            {
                var registry = new DataLoaderRegistry(sp);
                registry.Register<UserDataLoader>();
                return registry;
            });
``

**Comment by michaelstaib** [comment]
With version 11 we have now a very simple solution to support this. We will soon release the first previews of this and state how it works in a blog post. I am closing this issue now.
