### ISSUE TITLE
Explore Source Generator Support for Hot Chocolate and Strawberry Shake

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1572]
https://github.com/dotnet/roslyn/blob/master/docs/features/generators.md

**Comment by michaelstaib** [comment]
this is now implemented

**Comment by fleed** [comment]
@michaelstaib is it using the standard `System.Text.JSON` source generators or something custom?
Will we benefit from the [.net 8 improvements](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/)?
