### ISSUE TITLE
Filtering & Sorting on Schema Type

### ISSUE THREAD

**Issue by Sacrilege** [ChilliCream/hotchocolate#1573]
I'm looking for guidance on the best way (if possible) to filter based on a schema type.

The scenario is I've overridden some field info at the schema level and I want that reflected in my filtering and sorting arguments.

Here is some psuedo real world code to illustrate what I'm doing currently.

```
public class Entity
{
    public int EntityId { get; set; }
}

public class EntitySchema : ObjectType<Entity>
{
    protected override void Configure(IObjectTypeDescriptor<Entity> descriptor)
    {
        descriptor.Field(entity => entity.EntityId)
            .Name("id");
    }
}

public class Query
{
    public IQueryable<Entity> GetEntities([Service]IDbRepository db)
    {
        return db.GetEntitites();
    }
}

public class QueryType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor.Field(q => q.GetEntities(default))
            .UseSorting()
            .UseFiltering();
    }
}
```

This results in being able to filter and sort based on all my entity fields which is desirable. However, since the schema type in this case changed a field name the arguments don't match up correctly.

I tried using the overloads which accept a generic type and passed in the schema type but that just resulted arguments that matched a couple of properties on the ObjectType base class. I also tried explicitly adding a UseFiltering call within the configure method of the schema class but that had no affect either.

I see there is another overload that takes a configure method that seems promising, however, I can't find much documentation on any of this.

I don't know if this is a limitation if this is a limitation I'm running into or if there's something better/different I should be doing to make this work but any guidance would be helpful.

**Comment by Sacrilege** [comment]
I've now tried to implement this using the UseFiltering and UseSorting overloads with configure actions passed in but I see no way to change the base name on the filters. Looks like I'd have to override each argument individually on IComparableFilterFieldDescriptor.

**Comment by PascalSenn** [comment]
Hi @Sacrilege  
We just discussed this internally and think this could be a cool feature. It think something like this was already requested once. 
This would obviously only work for properties that have a property type as member 
We need to create a feature request to define the behaviour.
I will do this tomorrow or the day after :+1: 
Thank you for opening this issue :+1:

**Comment by PascalSenn** [comment]
related #1322
