### ISSUE TITLE
ApplicationInsights Integration

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1596]
We should add another provider for our instrumentation so that we have a native integration with application insights.

**Comment by mdressel** [comment]
@michaelstaib Do you have any suggestion on how you would do this without having this functionality built into Hot Chocolate?

I have implemented a solution that I think gets "close" to what I want. I am using the `IDiagnosticObserver` to instrument most things. Including:
- `HotChocolate.Execution.Query.Start`
- `HotChocolate.Execution.Query.Stop`
- `HotChocolate.Execution.Query.Error`
- `HotChocolate.Execution.Validation.Error`
- `HotChocolate.Execution.Resolver.Error`

Which is almost everything I would want. I get a Dependency entry for every query and appropriate errors.

However, I don't get an "overall" entry for each request (which would include other things like authentication/authorization work). I was looking at using a `AddQueryRequestInterceptor` to add this, but then realized I would need a "begin" and "end". At this point I am not sure where to go or if I can/should do more.

Just to clarify, my ideal would be a structure similar to the following.
- GraphQL Request: [Operation Name]
  - Other Work
  - GraphQL Query: [Operation Name]
    - SQL
  - Other Work

Other work being any other dependencies that might happen as part of a request.

**Comment by michaelstaib** [comment]
we will add more events to this. We currently work on the new execution engine and have more events on the list.

**Comment by olitee** [comment]
@mdressel I've managed to get request logging working with AI. The trick is to create and start the request operation in the `HotChocolate.Execution.Query.Start` method, then STORE the operation in a dictionary so that you can fetch it later during the `HotChocolate.Execution.Query.Stop` phase.

The HttpContext has a handy `TraceIdentifier` property, which makes for a great key for the dictionary.

So you can imagine something like this:

```c#
private Dictionary<string, IOperationHolder<RequestTelemetry>> _inFlightOperations = new Dictionary<string, IOperationHolder<RequestTelemetry>>();

[DiagnosticName("HotChocolate.Execution.Query.Start")]
public void BeginQueryExecute(IQueryContext context)
{
    var httpContext = GetHttpContextFrom(context);

    if (httpContext == null) return;

    // Create a new request
    var requestTelemetry = new RequestTelemetry()
    {
        Name = $"{httpContext.Request.Method} {httpContext.Request.GetUri().GetLeftPart(UriPartial.Path)}",
        Url = new Uri(httpContext.Request.GetUri().AbsoluteUri)
    };

    requestTelemetry.Context.Operation.Id = GetOperationIdFrom(httpContext);
    requestTelemetry.Context.Operation.ParentId = GetOperationIdFrom(httpContext);
    requestTelemetry.Properties.Add("GraphQL Query", context.Request.Query.ToString());

    // Start the operation, and store it in the dictionary
    var operation = _telemetryClient.StartOperation(requestTelemetry);
    _inFlightOperations.Add(GetOperationIdFrom(httpContext), operation);
}

[DiagnosticName("HotChocolate.Execution.Query.Stop")]
public void EndQueryExecute(IQueryContext context, IExecutionResult result)
{
    var httpContext = GetHttpContextFrom(context);
    if (httpContext == null) return;

    if (_inFlightOperations.ContainsKey(GetOperationIdFrom(httpContext)))
    {
        var operation = _inFlightOperations[GetOperationIdFrom(httpContext)];
        _inFlightOperations.Remove(GetOperationIdFrom(httpContext));

        // handle any final request logging here (GraphQL query errors, success, etc)

        // Then stop the operation. This completes the request.
        _telemetryClient.StopOperation(operation);
    }

}

```

The two helper methods in that code simply fetch the httpcontext from the IQueryContext, and return the trace identifier:

```c#
private HttpContext GetHttpContextFrom(IQueryContext context)
{
    // This method is used to enable start/stop events for query.
    if (!context.ContextData.ContainsKey("HttpContext"))
        return null;

    return context.ContextData["HttpContext"] as HttpContext;
}

private string GetOperationIdFrom(HttpContext context)
{
    return context.TraceIdentifier;
}
```

I've included the query in the request metadata (custom properties), but you can extend it to include whatever you like. In my implementation I've appended the request URI to include the IQueryContext's QueryHash, which allows AI to separate the requests by query, rather than everything just being logged into the /graph endpoint.

**Comment by michaelstaib** [comment]
We also simplified the whole story around this with the current 11 preview versions. For this, I will close this issue.

**Comment by olitee** [comment]
Excellent - I look forward to upgrading ;)

**Comment by rsantosdev** [comment]
@michaelstaib can you clarify what was simplified and how?

**Comment by JohannSig** [comment]
An update to the documentation for v11 sure would be nice!

**Comment by woeterman94** [comment]
Any update for v11?

**Comment by rsantosdev** [comment]
@JohannSig @woeterman94 

Here's the code I use. It basically logs into Serilog and from Serilog I decide where I want the logs to go, in my case I send to Seq when locally and to Application Insights on production.

```
public class GrowFlowDiagnosticEventListener : DiagnosticEventListener
    {
        public override IActivityScope ExecuteRequest(IRequestContext context)
        {
            Log.Information("{QueryName} starting \n {QueryContent}",
                context.Request.Query.GetQueryName(),
                context.Request.Query.ToString());

            return base.ExecuteRequest(context);
        }

        public override void ResolverError(IMiddlewareContext context, IError error)
        {
            LogHotChocolateError(error);
        }

        public override void RequestError(IRequestContext context, Exception exception)
        {
            base.RequestError(context, exception);
        }

        private void LogHotChocolateError(IError error)
        {
            string path = error.Path?.ToString() ?? "";

            if (error.Exception == null)
            {
                Log.Error("  {0}\r\n{1}", path, error.Message);
            }
            else
            {
                Log.Error(error.Exception,
                    "   {0}\r\n{1}", path, error.Message);
            }
        }
    }
```

To register the class:
```
services.AddGraphQLServer(schemaName: SchemaName)
                .ConfigureSchemaServices(s =>
                {
                    s.AddSingleton<IDiagnosticEventListener, GrowFlowDiagnosticEventListener>();
                });
```

**Comment by Ricky-G** [comment]
Excellent solution @olitee , I am using schema first, so had to modify it slightly when generating the hash, the operation name will always be null unless the client passes in a query name and also when using Graphql play ground its creating too much noise in dev so blocked that out, apart from that more or less the same code.  The only change was in the ExecuteRequest

`public override IDisposable ExecuteRequest(IRequestContext context)
        {
            var httpContext = GetHttpContextFrom(context);
            if (httpContext == null)
                return EmptyScope;

            //During debugging every playground action will come here so we want this while debugging
            #if DEBUG
            if (context.Request.OperationName == "IntrospectionQuery")
                return EmptyScope;
            #endif

            //Create a new telemetry request
            var operationPath = $"{context.Request.OperationName ?? "UnknownOperation"} - {context.Request.QueryHash}";
            var requestTelemetry = new RequestTelemetry()
            {
                Name = $"/graphql{operationPath}",
                Url = new Uri(httpContext.Request.GetUri().AbsoluteUri + operationPath),
            };

            requestTelemetry.Context.Operation.Name = $"POST /graphql/{operationPath}";
            requestTelemetry.Context.Operation.Id = GetOperationIdFrom(httpContext);
            requestTelemetry.Context.Operation.ParentId = GetOperationIdFrom(httpContext);
            requestTelemetry.Context.User.AuthenticatedUserId = httpContext.User.Identity?.Name ?? "Not authenticated";

            if (context.Request.Query != null)
                requestTelemetry.Properties.Add("GraphQL Query", context.Request.Query.ToString());

            var operation = _telemetryClient.StartOperation(requestTelemetry);
            return new ScopeWithEndAction(() => OnEndRequest(context, operation));
        }`

**Comment by olitee** [comment]
Thanks @Ricky-G, that's great. I'd come to the same conclusion in production about noise. Thanks for posting your modifications - I might borrow those :)

**Comment by olitee** [comment]
@onionhammer The solution I posted does capture the Query as a custom property, so it's visible in App Insights. The parameter values are also logged as properties. If that was a concern for your solution - you could just omit those.

Or as you asking that is someone writes an unparameterised query, containing sensitive data, that you want to somehow redact those values?

**Comment by onionhammer** [comment]
@olitee Right now I don't have a UI, so I'm just using banana cake pop to test out queries, so perhaps its a non-issue once in production and variables are parameterized.
