### ISSUE TITLE
HotChocolate response doesn't specify charset

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#1597]
**Describe the bug**
responses from the HC graphql endpoint return the content-type header as `application/json`. according to RFC 7230 content must be in ISO-8859-1/US-ASCII (single octet) when no other encoding is specified.

**To Reproduce**
1. make a request to a HC endpoint
2. check the reponse header content-type. it's "application/json"

**Expected behavior**
1. make a request to a HC endpoint
2. check the reponse header content-type. it's "application/json; charset=utf-8"

**Additional context**
We are seeing encoding issues when querying HotChocolate endpoints with PowerShell which doesn't happen with other .Net GraphQL implementations.
ASP.Net core returns json content with charset=utf-8 by default when using their MVC controllers.

**Comment by michaelstaib** [comment]
This one is now fixed and we will ship it with 10.5.0-preview.8
