### ISSUE TITLE
Infer Schema from Types Part 2

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#160]
With this issue we want to enable support for inferring the complete schema from a single dotnet type.
The idea is to just provide a single query registration and the schema inspects the type and all associated types and infers from the types the GraphQL schema.

So, lets say we have the following three classes:

```csharp
public class MyQuery
{
   public Foo GetFoo() => new Foo();
}

public class Foo
{
    public Bar GetBar() => new Bar();
}

public class Bar
{
    public string Abc { get; set; } = "CDE";
}
```

Now if we register our query type like the following:

```csharp
Schema.Create(c =>
{
    c.RegisterQueryType<MyQuery>();
});
```

The expepected schema would be something like this:

```graphql
type MyQuery {
  foo: Foo
}

type Foo {
  bar: Bar
}

type Bar {
  abc: String
}
```

Since .net does not have nullable reference types yet we cannot infer non-nullability without a hint.

**Comment by ronnyek** [comment]
I assume this is regarding being able to build schema from an object marked up by specific attributes vs actually using a fluent builder or something?

**Comment by michaelstaib** [comment]
```csharp
public interface ITypeDiscoveryRule
{
    bool CanHandle(Type clrType);
    void RegisterType(ITypeRegistry typeRegistry, Type clrType);
}
```

**Comment by michaelstaib** [comment]
I will close this issue and create a more explicit follow up that defines how the type discovery rules shall work.
