### ISSUE TITLE
Using Connection Types In An Interface Throws Error The name `IConnection` was already registered by another type.

### ISSUE THREAD

**Issue by dannyheardairelogic** [ChilliCream/hotchocolate#1603]
**Describe the bug**
Version 10.4.0

I have an interface that contains a graphql relay field.

```csharp
using HotChocolate.Types;
using HotChocolate.Types.Relay;

    public class SubjectInterface : InterfaceType<ISubject>
    {
        protected override void Configure(IInterfaceTypeDescriptor<ISubject> descriptor)
        {
            descriptor.Name("SubjectInterface");
            // This introduces some conflict into the schema
            descriptor.Field("records").AddPagingArguments().Type<ConnectionType<SubjectItemInterface>>();

        }
    }
```

And then two objects that implement that interface in exactly the same way, This is currently a base case before I add more fields to the different implementations

```csharp
public class SubjectType : ObjectType<Subject>
    {
        protected override void Configure(IObjectTypeDescriptor<Subject> descriptor)
        {
            descriptor.Field<SubjectResolver>(t => t.GetRecords(default, default));
        }
    }
```

And the resolver for the object: 
```csharp
public class SubjectResolver
    {
        [UsePaging]
        public async Task<IEnumerable<ISubjectItem>> GetRecords(
            [Service] ISubjectItemService subjectItemService,
            [Service] IResolverContext context)
        {
            return await subjectItemService.GetSubjectRecords(context.Parent<ISubject>());
        }
    }
```

The error this then throws is:
`HotChocolate.SchemaException: The name `ISubjectItemConnection` was already registered by another type. - Type: ISubjectItemConnection`

I can also reproduce this if I have only one implementation of the ISubject interface.

As well as if I change the definiton of the records field to `descriptor.Field("records").UsePaging<SubjectItemInterface>();`

**Comment by michaelstaib** [comment]
Could you post `ISubject` as well?

**Comment by michaelstaib** [comment]
I already see the issue I think ... no need for `Subject`

**Comment by dannyheardairelogic** [comment]
`public interface ISubject
    {
        const string TypeName = "subject";
        Guid Id { get; set; }
        DateTime CreatedAt { get; set; }
        bool Active { get; set; }

    }`

In which location do  I remove ISubject? Removing ISubject from the interface causes the same issue.

**Comment by michaelstaib** [comment]
Can you build a small reoro of your issue? that would be a great help.

**Comment by michaelstaib** [comment]
@PascalSenn looks like in this case we are creating two connection types... how are we handling filters on interfaces?

**Comment by PascalSenn** [comment]
@michaelstaib  only of the interface properties

**Comment by dannyheardairelogic** [comment]
This is a repo that reproduces the issue: https://github.com/dannyheardairelogic/hotchocolate-connection-issue

**Comment by michaelstaib** [comment]
Great thanks.... we will start looking into it.

**Comment by michaelstaib** [comment]
I have now looked at your project. Sorry for the long delay ... I always have a large backlog.

You have actually multiple issues here.

For instance you are using relay types and implementing the node interface which demands the id field to be of ID type but right after declaring it correctly you are overwriting it with UUID.

Regarding the paging attribute... since you declare a specific schema type in your interface you need to use that also in the attribute. 

```
[UsePaging(SchemaType = typeof(SubjectItemInterface))]
        public IQueryable<ISubjectItem> GetItems(
            [Service] ISubjectItemService subjectItemService,
            [Service] IResolverContext context)
        {
            return subjectItemService.GetSubjectItems(context.Parent<ISubject>());
        }
```

While mixing and matching works, when starting with hot chocolate it is good to stick to one approach which will lead to a better understanding of it and to better code. When you have mastered it it can be quite useful to mix and match between code-first variants.

**Comment by dannyheardairelogic** [comment]
Thank you.

I did not realise that specifying the id field in the node would result in it casting it to a Uuid type instead of keeping it as an id field as i thought that was the specification
