### ISSUE TITLE
UseSelection and extending a object thows DbException

### ISSUE THREAD

**Issue by Eebo78** [ChilliCream/hotchocolate#1605]
If I extend an entity with following property `public bool SomeProp => true` will try to resolve this property from the database.

Workaround `public bool SomeProp() => true`

**Comment by TheJayMann** [comment]
From how I understand the selection middleware works, if a query were to include the SomeProp property, an expression will be created equivalent to `data.Records.Select(r => new Record() { SomeProp = r.SomeProp })`.  Given this, I am assuming the exception occurs because an expression is attempting to be used which is trying to set a read only property.  If you were to change `public bool SomeProp => true` to `public bool SomeProp {get;set;} => true`, does the exception still occur?  If it does not still occur, then perhaps the fix is to filter out read only properties in the selection middleware.

This does bring up another potential issue of where a read only property references other database mapped properties.  In code, if you wanted to use the aggregate property, you would simply include the other properties in the query so they can be aggregated into the other property.  Not sure how this could be done by HotChocoloate itself, except possibly by adding some configuration, either in code or in attributes, to state that specific properties depend on other properties being present.

**Comment by PascalSenn** [comment]
@TheJayMann  you are absolutely right. The problem in this specific case is that the property is on a type-extension. And UseSelection does not compare the declaring type yet. It just checks for `is PropertyInfo`

**Comment by PascalSenn** [comment]
>This does bring up another potential issue of where a read only property references other database mapped properties.  

This is also a limitation of the current implementation 
Include would be EF specific unfortunately. Also.. Nested includes and selections are again difficult in that case

**Comment by TheJayMann** [comment]
My way of having solved this is to have a set of data classes which are used by the query provider and mapped to the underlying data source, a set of DTO classes which mapped to the graphql query schema, and a linq query which maps from the data classes to the DTO classes.  This also eliminates the need for `Include()` method calls and the issue of selecting a property which is the aggregate of other properties.  I've noticed that EF Core (the only query provider I have tested) does a very good job of interpreting two levels of projections, even when one of the layers is of a type which is not mapped to the database.  Other query providers may or may not be able to handle the complicated queries generated by this method, but I did see a project which might help for query providers which don't work well: https://thorium.github.io/Linq.Expression.Optimizer/index.html.  It should simplify more complex queries, and might be able to help with other providers, though I haven't yet tested this.

**Comment by PascalSenn** [comment]
@TheJayMann  
Do you have an example for this? 
>My way of having solved this is to have a set of data classes which are used by the query provider and mapped to the underlying data source, a set of DTO classes which mapped to the graphql query schema, and a linq query which maps from the data classes to the DTO classes.

**Comment by TheJayMann** [comment]
A very quick sample:

```csharp
// Entity Framework Core data model class, represents a People table in the database
[Table("People")]
public class Person {
    [Key]
    public int PersonId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```
```csharp
// GraphQL model, representing data returned from the profiles query
public class Profile {
    public int ProfileId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string FullName { get; set; }
}
```
```csharp
// GraphQL model representing the root query type
public class Query {
    public IQueryable<Profile> GetProfiles([Service] ProfileContext profileContext) =>
        profileContext.People.Select(p => new Profile() {
            ProfileId = p.PersonId,
            FirstName = p.FirstName,
            LastName = p.LastName,
            FullName = $"{p.FirstName} {p.LastName}",
        })
    ;
}
```

If you query this while only selecting the `fullName` field, the query will still select both the `FirstName` and `LastName` columns of the `People` table, as the `FullName` property is set in the initializer by referencing the `FirstName` and `LastName` properties of the `Person` class.  Also, the `PersonId ` column is not selected, as the second select query made by the selection middleware is not selecting any properties which were initialized by it.

This also works when using navigation properties to perform joins.  Only one extra class is needed to be added to the profile class to create add a list of addresses, but the database has at least four different tables, each of which need to have its own separate Entity Framework class representing it.  Using this mapping process eliminates significant needless complications on the GraphQL surface.  In this case, the joins only get performed if you are actually query the `addresses` collection field.

**Comment by PascalSenn** [comment]
@TheJayMann  Very cool! Thank you for the example!
EF must really have a good provider then :D 
I can imagine MongoDB blowing up

**Comment by TheJayMann** [comment]
EF Core has a really good provider.  EF6 does not.  I have a feeling this will not work at all in EF6.  One of the reasons I had switched from EF6 to EF Core is that you could not create a new object in a select expression if the class being instantiated was not a registered entity type.

**Comment by PascalSenn** [comment]
This issue is resolved with HotChocolate.Data

You can also ignore members from the projection with
[IsProjected(false)]
