### ISSUE TITLE
Using Node descriptor only works with Id Type

### ISSUE THREAD

**Issue by dannyheardairelogic** [ChilliCream/hotchocolate#1613]
I am not sure whether this is a bug or an intended feature. However I have an object that has a Guid Id type which gets translated into the graphql schema as Uuid.

Whenever i try to use node descriptor on this object as such: (Where Id is the Guid field)
```
            descriptor
                 .AsNode()
                 .IdField(t => t.Id)
                 .NodeResolver((ctx, id) =>
                     ctx.Service<IRepository>().Get(id)
                 );
```
The schema will then generate this object as an Id field. Then when i query this object as an edge node, the id returned is not the Guid but some encoded value which causes issues further down in my application as i use this id for further queries.

If the node field is only supported with the id type and at least one node definition is required when using relay support, what is the solution for an application where all ids are of Guid type which are automatically converted into UUuid type?

**Comment by michaelstaib** [comment]
This is intended since the relay specification defines it like that.

https://graphql.org/learn/global-object-identification/

```graphql
# An object with a Globally Unique ID
interface Node {
  # The ID of the object.
  id: ID!
}
```
With a User conforming via:
```graphql
type User implements Node {
  id: ID!
  # Full name
  name: String!
}
```

**Comment by michaelstaib** [comment]
Here are all the relay server spec:
https://relay.dev/docs/en/graphql-server-specification

**Comment by dannyheardairelogic** [comment]
In that case, how can i disable the automatic registration of the UUID type for Guids in the pure code first approach?
Then instead I can use an ID type with a custom type conversion

**Comment by dannyheardairelogic** [comment]
Or Even simpler than that, in the pure code first approach, can i set the graphql type of a parameter. I.e. set a string parameter to be an id type, so then I can manually decode the encoded Id
