### ISSUE TITLE
UseSelection on Subscription Resolver throws exception

### ISSUE THREAD

**Issue by Eebo78** [ChilliCream/hotchocolate#1614]
UseSelection on a subscription throws following error:

"extensions": {
        //     "message": "Value cannot be null. (Parameter 'source')",
        //     "stackTrace": "   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)\r\n   at HotChocolate.Types.Selections.SelectionMiddleware`1.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler)"
        //   }

**To Reproduce**
See repo: https://github.com/Eebo78/HC_SubscriptionBug.git

**Expected behavior**
subscription f {
  onNewStudent {
    firstMidName
    lastName
    enrollments{
      course {
        title
      }
    }
  }
} should not throw error and enrollments should have data

**Desktop (please complete the following information):**

**Additional context**

See the https://github.com/Eebo78/HC_SubscriptionBug.git repo for reproducing this

**Comment by michaelstaib** [comment]
That is actually not a bug but the usage is wrong. 

In order to use selections you have to return IQueryable to let us write the query on top of EF.

```csharp
[UseFirstOrDefault]
[UseSelection]
public async IQueryable<Student> OnNewStudent([EventMessage]int studentId,
    [Service]Context context)
{
    return await context.Students.Where(t => t.ID == studentId);
}
```

To ensure that you just get a single result you can use our `UseFirstOrDefault` middleware.
