### ISSUE TITLE
Playground: query path is wrong

### ISSUE THREAD

**Issue by maximillianfx** [ChilliCream/hotchocolate#1630]
**Context**
My Startup.cs contains the following code to start Graphql, Playground and Voyager:

```c#
app.UseGraphQL("/graphql");
app.UsePlayground(new PlaygroundOptions { Path="/playground", QueryPath="/graphql" });
app.UseVoyager(new VoyagerOptions { Path="/voyager", QueryPath="/graphql" });
```

**Actual behavior**
The GraphQL server and Voyager starts normally, but when I go to Playground using the url (https://localhost:5001/playground) the query path shows the following url:

https://localhost:5001/playground/../graphql

**Expected Behavior**

I wanna access https://localhost:5001/playground and see the query path with https://localhost:5001/graphql

**Desktop (please complete the following information):**
 - OS: Windows 10
- .Net Core 3.1

**Additional context**
Hotchocolate version (Graphql, Playground and Voyager): 10.3.6

Any idea/help?

Thanks!

**Comment by michaelstaib** [comment]
Hi @maximillianfx,

this is an open issue that we want to address with version 11.

**Comment by michaelstaib** [comment]
Playground has now been replaced with bcp.
