### ISSUE TITLE
Apollo Federation Support

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1631]
We will introduce a new package HotChocolate.Types.ApolloFederation which will contain middleware and types to support the federation spec.

https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

TODOs:

- [x] Apollo Federation Types
- [ ] Apollo Federation schema printer for service type.
- [ ] Runtime

**Comment by dillanmann** [comment]
For reference after discussion on slack, a potential implementation:

```
public static class KeyExtensions
   {
      public static IObjectTypeDescriptor AddKeyDirective(this IObjectTypeDescriptor descriptor, string fields)
      {
         descriptor
             .Directive("key", new ArgumentNode("fields", fields))
             .Extend()
             .OnBeforeNaming((c, d) =>
             {
                if (!c.ContextData.TryGetValue("Entities", out object o) ||
                     !(o is List<ObjectType> entities))
                {
                   entities = new List<ObjectType>();
                   c.ContextData["Entities"] = entities;
                }
                entities.Add((ObjectType)c.Type);
             });
         return descriptor;
      }

      public static IObjectTypeDescriptor<T> AddKeyDirective<T>(this IObjectTypeDescriptor<T> descriptor, string fields)
      {
         descriptor
             .Directive("key", new ArgumentNode("fields", fields))
             .Extend()
             .OnBeforeNaming((c, d) =>
             {
                if (!c.ContextData.TryGetValue("Entities", out object o) ||
                     !(o is List<ObjectType> entities))
                {
                   entities = new List<ObjectType>();
                   c.ContextData["Entities"] = entities;
                }
                entities.Add((ObjectType)c.Type);
             });
         return descriptor;
      }

      /*public class KeyAttribute : ObjectTypeDescriptorAttribute
      {
         public override void OnConfigure(IDescriptorContext context, IObjectTypeDescriptor descriptor, Type type)
         {
            descriptor.AddKeyDirective();
         }
      }*/
   }
```

**Comment by scanerdogan** [comment]
Hi,
is there any estimations on when would this feature would be merged into sub-version? 
Also, is this change planned on v11 ?
Thanks,

**Comment by michaelstaib** [comment]
Version 11 is planned for end of October.

**Comment by michaelstaib** [comment]
We will start work on this particular item next week.

**Comment by fredericbirke** [comment]
- [ ] Throw proper exception if no entity types were declared
- [ ] Create Attribute `ExtendServiceType` for Apollo Federation Type extensions of other services
- [ ] Schema printer
- [ ] Create Query type if non is provided by the implemented Service

**Comment by PeterJKing** [comment]
If this has been moved to the backlog, when could we possibly expect HC to support Apollo Federation?

In the meantime, is there anything you could suggest we do (we need to integrate into Apollo Server with Federation)?

**Comment by fredericbirke** [comment]
This is planned for HC 11.1, which is planned for end of november (If I am not mistaken). This feature may be available earlier in a preview build.

The implementation is already done and is just waiting for review and merge.
(See the PRs 
   - https://github.com/ChilliCream/hotchocolate/pull/2472
   - https://github.com/ChilliCream/hotchocolate/pull/2389
)

**Comment by twilly86** [comment]
Is this still targeting 11.1? Would love to be a tester for this once it's in a preview.

**Comment by michaelstaib** [comment]
@twilly86 we have moved it to march with the other stitching and federation related features.

**Comment by michaelstaib** [comment]
We are abandoning the implementation of Apollo Federation in favor of our own solution.

**Comment by dillanmann** [comment]
> 
> 
> We are abandoning the implementation of Apollo Federation in favor of our own solution.

Is this at least compatible with Apollo Federation?

**Comment by rob3c** [comment]
> We are abandoning the implementation of Apollo Federation in favor of our own solution.

@michaelstaib Has the team documented the reasoning behind this surprising decision anywhere?

**Comment by michaelstaib** [comment]
Yes, essentially, we have for years now a competing solution. We want to invest our time rather in our own solution than spending it on someone else's thing.

**Comment by michaelstaib** [comment]
If you want a more in depth explanation join us on slack.

**Comment by galpin** [comment]
I’ve also put together a package to support Apollo Federation and I’m planning on working towards making the package available on NuGet in the next few weeks. See [the feature/initial branch](https://github.com/galpin/hotchocolate.extensions.apollofederation/tree/feature/initial) in my repo.

I’ve also added an implementation to [the Apollo subgraph compatibility repo](https://github.com/galpin/apollo-federation-subgraph-compatibility/blob/hotchocolate/implementations/hotchocolate/Program.cs) and I’ll submit a PR when the package is available (currently it has full support other than the tracing extension).

I started with the implementation in the hotchocolate repo so I’ve left the original license - @michaelstaib can you confirm you’re happy with the attribution (happy to do more) and for the package prefix if I was to publish to NuGet (also happy to rename if you’d prefer)?

**Comment by michaelstaib** [comment]
The source code is not under the MIT we moved it to our private repro and are selling licenses to it. That is the reason why we have not released it in the public repro. We also communicated this and are not granting a license to use our work since we are financing the whole project with our commercial components like the one you are referring to.

**Comment by galpin** [comment]
@michaelstaib That is a very disappointing response indeed.

The code is substantially based on [the tree at this commit](https://github.com/ChilliCream/hotchocolate/tree/77b9438b9005f3a1e79a1671558bc26be11033c2/src/HotChocolate/ApolloFederation) and the repo is under [the MIT License](https://github.com/ChilliCream/hotchocolate/blob/main/LICENSE) at this point (I don't see anything to indicate that the ApolloFederation project is licensed differently to the rest of the source code - forgive me if it does and I have missed it). 

Given that there is no scope for retrospectively revoking the terms of the MIT License _for this specific revision_ - and AFAIK, I am compliant with the terms of the license - please can you elaborate on why my package is not a legitimate derivative work?

I do not have any interest, nor have I ever seen, code after is was subsequently moved into another repo and the license changed (which is of course your right to do so).

**Comment by michaelstaib** [comment]
We have never released it under the MIT license; it was only a draft on our repository. 

We announced publicly that we would not merge it into the release and removed it. The same goes for BCP which has minified sources on this repository. Only things becoming part of a release are subject to MIT and we honor that, so we do not change licenses. ApolloFederation has moved along but never became part of a release.

Since this is at the moment represents our main income source I implore you to remove it from GitHub. We are investing so much into OSS and giving a lot of our time to this project and you are attacking.

If you want to buy a license we are open to it and we have the component with samples and docs.

**Comment by galpin** [comment]
@michaelstaib I am of the opinion that pushing code (indeed merging PRs) into a public GitHub repo clearly advertised as MIT constitutes as release; code that I cloned, built and used at the time. Furthermore, this is consistent with [the GitHub Terms of Service](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users) (e.g. I can fork and create copies of the repo).

Again, if there is any specific documenation in the repo _at that revision_ which indiciates that this portion of the tree is licensed differently - let me know.

As the maintainer of a popular open source framework, I implore you to support community contributions even if they occasionally conflict with your own business interests. This is not an _attack_ - I consider it a good-faith contribution that will drive the adoption of your product (and business).

I am happy to work towards rewriting portions of code that originated in your repo over time - which is less than 50% of the overall codebase (guesstimate).

**Comment by michaelstaib** [comment]
How does it grow adoption and my business if I cannot pay my bills anymore?

**Comment by galpin** [comment]
I am not sure I see relevance to the MIT licensed source code.

I am happy to engage further on this matter if required (and to proceed as per my proposal above).
