### ISSUE TITLE
GraphQL Playground opened by HTTP URI can't reach GraphQL server in ASP .NET Core 3.1

### ISSUE THREAD

**Issue by NFroeh** [ChilliCream/hotchocolate#1634]
**Summary**
By following the [Getting Started Tutorial](https://hotchocolate.io/docs/tutorial-01-gettingstarted) a GraphQL Server project in ASP .NET Core 3.1 is created. The playground by HTTPs on "https://localhost:5001/playground" is accessible and working. Playground by HTTP on "http://localhost:5000/playground" can be accessed, but GraphQL server request fails with 404 (Server cannot be reached).

Same behaviour on Star Wars example in the GitHub repository.

**To Reproduce**
1. Set up basic GraphQL Server by following the Getting Started Tutorial.
2. Start the GraphQL Server.
3. Access "http://localhost:5000/playground".
4. See error: "Server cannot be reached". Console contains 404 errors.

**Expected behavior**
When accessing the Playground by HTTP, it should work properly and reach the GraphQL Server (see Playground by HTTPs). 

**Basic configuration in Startup**

        public void ConfigureServices(IServiceCollection services)
        {
            var schemaBuilder = SchemaBuilder.New();
            schemaBuilder.AddQueryType<Query>();
            services.AddGraphQL(schemaBuilder);
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app
                .UseGraphQL()
                .UsePlayground();
        }

with packages HotChocolate.AspNetCore and HotChocolate.AspNetCore.Playground Version 10.4.0.

**Desktop (please complete the following information):**
 - OS: Windows
 - Net Core 3.1

**Question**
Should it be possible to access the playground by HTTP?
If yes, is this a known bug or is there a workaround to access the working playground by HTTP.
At least the documentation needs to be updated, because of the non-working example with the referenced URI.

**Comment by michaelstaib** [comment]
It should actually. I tried to test it on my machine and it seems to work. I am on macOS though. I will ask @PascalSenn to check it on windows again.

BTW we have a better example project here:
https://github.com/ChilliCream/hotchocolate-examples/tree/master/workshop/src/Server

PureCodeFirst uses mongo
PureCodeFirst+EF uses EntityFramework

Also I can recommend using our slack channel where we respond much quicker than on issues.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by michaelstaib** [comment]
Also we are in the progress of creating a new documentation that has better tutorials.

**Comment by NFroeh** [comment]
Well, thank you for the quick answer.

I just tried the tutorial on another machine with .net core 3.1 and windows and there it worked. So it should only be a problem for my other machine. @PascalSenn doesn't need to check it on his windows system.

The machine where the playground on http is not working has Windows at Version 10.0.17134 (In contrary to the working example on machine with Windows 10.0.18363). They both use the same .net sdk version (3.1.101). 

Already checked port with netstat and port 5000 is not occupied. After that i tried to work on another port (7000) and there it worked. 

So there is there is a problem with the port 5000 on that specific machine. I will have to investigate why there is a problem on that port. Right now i have no idea why it does not work on port 5000, because that port is free to use and works on other applications and i can open the playground on first request.

**Errors*
![image](https://user-images.githubusercontent.com/23337292/78334097-6db98480-758b-11ea-9403-c30852f6ce1b.png)

![image](https://user-images.githubusercontent.com/23337292/78334191-9e99b980-758b-11ea-9e64-c06415d50c8f.png)

**Comment by michaelstaib** [comment]
@NFroeh great to hear. So I am closing this issue since it is related to your system. Please state back once you have figured out what the issue was since it might help others.

**Comment by ahmad2smile** [comment]
I had this same issue, after doing alot of debuggin and trying to figure out why, It just worked at 

```
app.UseGraphQL()
   .UsePlayground();
```

The only thing after getting Playground up and running I could find is that you need to point the GraphQL Request URL at right endpoint.

By default it would go at `playground/..` (mind the `..`) but if you have `app.UseGraphQL("/graphql"` you need to change it to `/graphql`
