### ISSUE TITLE
How to centralize the definition of a native type wrapper

### ISSUE THREAD

**Issue by matteobaglini** [ChilliCream/hotchocolate#1640]
Hi,
in our application we have several custom types that wraps a native `Guid` and this own types are exposed by multiple queries. For example:
```csharp
      public class GuidWrapper
      {
          public readonly Guid Value;
          public GuidWrapper(Guid value) =>  
              this.Value = value;
      }

      public class Query
      {
          public GuidWrapper Foo() => new GuidWrapper(Guid.NewGuid());
          public GuidWrapper Bar() => new GuidWrapper(Guid.NewGuid());
      }
```
In this way HotChocolate tries to serialize the wrapper so we use `ObjectType` and `TypeConversion` to specify that the type is actually a `UuidType` and how to (de)serialize it.
```csharp
      TypeConversion.Default.Register<Guid, GuidWrapper>(from => new GuidWrapper(from));
      TypeConversion.Default.Register<GuidWrapper, Guid>(from => from.Value);

      public class QueryType : ObjectType<Query>
      {
          protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
          {
              descriptor.Field(t => t.Foo()).Type<NonNullType<UuidType>>();
              descriptor.Field(t => t.Bar()).Type<NonNullType<UuidType>>();
          }
      }
```
With this approach every time a `WrapperGuid` is used in a query we have to remember to specify the `UuidType`. Is there any way to centralize this definition?

Thanks in advance

**Comment by michaelstaib** [comment]
Hi @matteobaglini, 

there is. You can tell the schema builder that this type also binds automatically to `UuidType`.

```csharp
SchemaBuilder.New()
    ...
    .BindClrType< GuidWrapper, UuidType>()
    .Create();
```

We also have a very active slack channel for help. So I can recommend joining us there.

**Comment by michaelstaib** [comment]
Please close the issue if this was what you were looking for :)

**Comment by matteobaglini** [comment]
Yes, it is. :-) Thanks @michaelstaib.
