### ISSUE TITLE
How to add more information in the response's extensions field from a middleware?

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1648]
Greetings gentlemen,

I am trying to add extra information under the response's `extensions` field (i.e. next to the `tracing` field of Apollo) from a middleware.

How can this be done?

Thank you.

**Comment by michaelstaib** [comment]
you can do that with a query middleware. 
https://hotchocolate.io/docs/middleware#query-middleware

**Comment by geekox86** [comment]
@michaelstaib thanks man.

Last question and we can close this if you don't mind. I'm using some attributes on my query/mutation resolver classes. I am trying to get references of these classes when they get included into my GraphQL schema by the query/mutation types. Where is the best place in your framework for me to hook and get them?

**Comment by michaelstaib** [comment]
This really depends. Are you using descriptor attributes? With descriptor attributes this is really super simple.

https://chillicream.github.io/hotchocolate/blog/2019/12/26/hot-chocolate-10.3.0#descriptor-attributes

**Comment by geekox86** [comment]
Also please note that I don't want to register the classes again outside of our framework.

**Comment by geekox86** [comment]
Yes, attributes. Fantastic! Thank you :)
