### ISSUE TITLE
Strayberry Shake not deserializing lists of enumerations correctly

### ISSUE THREAD

**Issue by raphaabreu** [ChilliCream/hotchocolate#1695]
**Describe the bug**
When a query as a property that is a list of an enumeration type, the code generated does not compile because no variable is created to hold the serializer.

**To Reproduce**
1. Using the following schema:

````
    schema {
      query: InternalQuery
      mutation: InternalMutation
    }

    directive @cost(
      complexity: Int! = 1
      multipliers: [MultiplierPath!]
    ) on FIELD_DEFINITION
    enum DayOfWeek {
      SUNDAY
      MONDAY
      TUESDAY
      WEDNESDAY
      THURSDAY
      FRIDAY
      SATURDAY
    }

    type InternalMutation {
      setDaysOfWeek(days: [DayOfWeek]!): Boolean!
    }

    type InternalQuery {
      daysOfWeek: [DayOfWeek]!
    }

    scalar MultiplierPath
````

2. With the following query:

````
    query SimpleQuery{
      daysOfWeek
    }
````

3. And the version ``11.0.0-preview.123``
4. The generated class ``SimpleQueryResultParser`` has a compilation error:

![image](https://user-images.githubusercontent.com/3214715/79071111-37c58000-7cb0-11ea-882b-788ddc038c78.png)

**Expected behavior**
Lists of enumerables should be handled without issue.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10.0.18363 Build 18363

**Additional context**
I have uploaded the following repository with a sample of failing code for review.
https://github.com/raphaabreu/ListOfEnumerationTest

**Comment by michaelstaib** [comment]
This is now fixed with the new preview 11.1.0-preview.58

Documentation and blog will follow over the weekend.
