### ISSUE TITLE
[Question] Exception on empty where object

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1705]
**Describe the bug**
Is exception on empty where clause is valid?

```gql
{
  entities(where: { }) {
    field
  }
}
```

It is a valid gql and valid "code logic" implementation (with "invalid" query), but exception thrown.
I think it is about "robust" queries and can fix some filter generation bugs, but it is not intuitive =/

**To Reproduce**
1. Query something with UseFiltering setup with empty `where` input

**Expected behavior**
When where is empty input, just not filter at all??

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
StackTrace:
```
Queue empty.

at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
at System.Collections.Generic.Queue`1.Peek()
at HotChocolate.Types.Filters.QueryableClosure.CreateLambda[T]()
at HotChocolate.Types.Filters.QueryableFilterVisitorContextExtensions.CreateFilter[TSource](IQueryableFilterVisitorContext context)
at HotChocolate.Types.Filters.QueryableFilterMiddleware`1.InvokeAsync(IMiddlewareContext context)
at HotChocolate.Types.Relay.QueryableConnectionMiddleware`1.InvokeAsync(IMiddlewareContext context)
at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler)
```

**Comment by PascalSenn** [comment]
where: {} will return all elements in 11

**Comment by AmbroiseCouissin** [comment]
It seems this issue is still there.

The queries works if where any other value than { } or is no there.
But if `where: { }`, the following happens:

request:

``` gql
{
  listEntities(
    where: { }
    ) {
      totalCount
      pageInfo {
        hasNextPage
      }
      items {
        id
        name
        type {
          id
        }
        createdBy {
          id
          name
        }
      }
  }
}
```

response

``` json
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listEntities"
      ],
      "extensions": {
        "message": "Operation is not valid due to the current state of the object.",
        "stackTrace": "   at HotChocolate.Data.Filters.Expressions.QueryableCombinator.TryCombineOperations(QueryableFilterContext context, Queue`1 operations, FilterCombinator combinator, Expression& combined) in HotChocolate.Data.dll:token 0x6000644+0xe\r\n   at HotChocolate.Data.Filters.FilterVisitor`2.TryCombineOperations(TContext context, Queue`1 operations, FilterCombinator combinator, T& combined) in HotChocolate.Data.dll:token 0x600058f+0x0\r\n   at HotChocolate.Data.Filters.FilterVisitorBase`2.Leave(ObjectValueNode node, TContext context) in HotChocolate.Data.dll:token 0x6000597+0xc\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context) in HotChocolate.Language.Visitors.dll:token 0x6000032+0xa2\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit(ISyntaxNode node, TContext context) in HotChocolate.Language.Visitors.dll:token 0x6000031+0x0\r\n   at HotChocolate.Data.Filters.Expressions.QueryableFilterProvider.<>c__DisplayClass10_0.<ConfigureField>g__VisitFilterArgumentExecutor|0(IValueNode valueNode, IFilterInputType filterInput, Boolean inMemory) in HotChocolate.Data.dll:token 0x600074c+0x8\r\n   at HotChocolate.Data.Filters.Expressions.QueryableFilterProvider.<>c__DisplayClass9_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext() in HotChocolate.Data.dll:token 0x6000750+0x1c5\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context) in HotChocolate.Types.dll:token 0x6000856+0x95\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task) in HotChocolate.Utilities.dll:token 0x600009c+0x64\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken) in HotChocolate.Execution.dll:token 0x60004bb+0xad\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken) in HotChocolate.Execution.dll:token 0x60004ba+0x16c"
      }
    }
  ],
  "data": {
    "listEntities": null
  }
}
```

Any idea?

**Comment by sudosandwich3** [comment]
I see this was moved to the backlog, but is there any plans to take this issue on?  What makes this issue difficult to work with is it is valid GraphQL so tools do not throw errors when this occurs.  This error is only detectable at when the query is sent.

**Comment by mtinnes** [comment]
We are getting the same error trying to utilize the 'some' filter.

```
query q {
  schedule(where: { devices: { some: { }} }) {
    totalCount
  }
}

```

`Queue empty.
System.Collections.Generic.Queue`1.ThrowForEmptyQueue()\r\n at System.Collections.Generic.Queue`1.Dequeue()\r\n at HotChocolate.Data.Filters.Expressions.QueryableDefaultFieldHandler.TryHandleLeave(QueryableFilterContext context, IFilterField field, ObjectFieldNode node, ISyntaxVisitorAction& action)\r\n at HotChocolate.Data.Filters.FilterVisitor`2.OnFieldLeave(TContext context, IFilterField field, ObjectFieldNode node)\r\n at HotChocolate.Data.Filters.FilterVisitorBase`2.Leave(ObjectFieldNode node, TContext context)\r\n at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[TNode,TParent](TNode node, TParent parent, TContext context)\r\n at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ObjectValueNode node, TContext context)\r\n at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[TNode,TParent](TNode node, TParent parent, TContext context)\r\n at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit(ISyntaxNode node, TContext context)\r\n at HotChocolate.Data.Filters.Expressions.QueryableFilterProvider.<ConfigureField>g__VisitFilterArgumentExecutor|12_0(IValueNode valueNode, IFilterInputType filterInput, Boolean inMemory)\r\n at HotChocolate.Data.Filters.Expressions.QueryableFilterProvider.AsPredicate[TEntityType](IResolverContext context, String argumentName, Boolean isInMemory)`
