### ISSUE TITLE
Readable exceptions when passing null to filters

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1706]
**Describe the bug**
Filters: `starts_with`, `ends_with`, `contains`, `in` is non nullish by design, but should be null in gql type system. If i pass null as value for this fields i get different strange exceptions

**To Reproduce**
1. Add null to filters above

```gql
{
  a(where: { b_contains: null }) {
    c
  }
}
```

**Expected behavior**
I think that is should be validation rule for them (if it is possible to differ null as value and not set)?
More readable exceptions?

**Additional context**
- **Contains**: "Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Boolean Contains(System.String)' (Parameter 'arg0')"
- **In**: "No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. "
- **StartsWith**: "Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Boolean StartsWith(System.String)' (Parameter 'arg0')"
- **EndsWith**: "Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Boolean EndsWith(System.String)' (Parameter 'arg0')"

**Comment by PascalSenn** [comment]
New errors messages:
```json
{
  "Data": {
    "foos": []
  },
  "Errors": [
    {
      "Message": "The provided value for filter `comparable` of type FooFilter is invalid. Null values are not supported.",
      "Code": null,
      "Path": [
        "foos"
      ],
      "Locations": [
        {
          "Line": 3,
          "Column": 42
        }
      ],
      "Exception": null,
      "Extensions": {
        "expectedType": "Int!",
        "filterKind": "Comparable",
        "operationKind": "Equals",
        "filterType": "FooFilter"
      }
    }
  ],
  "Extensions": null,
  "ContextData": null
}
```

**Comment by sergeyshaykhullin** [comment]
@PascalSenn Can this fix backported to 10 version? It is not critical, but if it is cheap it would be nice

**Comment by PascalSenn** [comment]
@sergeyshaykhullin  I was thinking about this, but there has changed a lot since 10.4 :S 
we try to iterate a bit faster so this will not be backported. it's not security critical, it's "just" nice to have
