### ISSUE TITLE
UseSelectionAttribute for complex and list type Field ,   

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#1707]

**Comment by michaelstaib** [comment]
Can you please describe your issue in more detail?

**Comment by aammfe** [comment]
For Example I have this social media domain.

```
 public class User
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public List<Post> Posts { get; set; }

        /*
         * and lot of other fields as well
         */
    }

    public class Post
    {
        public DateTimeOffset CreatedDate { get; set; }
        public long ApprovedById { get; set; }
        public User ApprovedBy { get; set; }


        public long Id { get; set; }
        public long UserId { get; set; }
        public User User { get; set; }

        public string Introduction { get; set; }

        public string Content { get; set; }
        public List<Comment> Comments { get; set; }

        /*
        * and lot of other fields as well
        */
    }

    public class Comment
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public User User { get; set; }

        public long PostId { get; set; }
        public Post Post { get; set; }

        public string Content { get; set; }

        /*
        * and lot of other fields as well
        */
    }
}
```


Each user page will have his 10 latest posts , post will just have
Post.Introduction,
Post.CreatedDate,
Post.ApprovedBy.Id,
Post.ApprovedBy.UserName

A possible query could be like.
```
query { 
    user(whereId = SomeId) {
        // other userInfo
        posts(take= 10, sortBy=CreatedDate) {
            introduction,
            createdDate,
            approvedBy { 
                id,
                userName
            }
        } 
    }
}
```

Question is when coming from user>posts>comments path
do we have possibility to [automatically ](https://hotchocolate.io/docs/descriptor-attributes#usefilteringattribute)
sort/filter/select on list type like posts, comments
select on complex type like approvedBy(user)

**Comment by PascalSenn** [comment]
@aammfe  yes this is possible with the useSelection middleware. It does not yet work with paging though

**Comment by PascalSenn** [comment]
Checkout https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

**Comment by aammfe** [comment]
> Checkout https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

Yes thats what I was talking about (y)


> @aammfe yes this is possible with the useSelection middleware. It does not yet work with paging though

it don't have paging /sorting support(what I get from article)... hope u have plans for it ?

**Comment by PascalSenn** [comment]
i does have filtering and sorting support. it is just paging that is not yet supported. This will be supported in a later version

**Comment by PascalSenn** [comment]
I'm gonna close this as we have already #1546 to track the progress on nested paging. 

To conclude. Use Selection optimises Database calls of:

Filtering, Sorting, Paging on the first level.
Filtering, Sorting on the deeply nested fields

For futher discussion check #1546
