### ISSUE TITLE
"Buisness entities" validation support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1708]
**Is your feature request related to a problem? Please describe.**
You have an official support for AspNetCore - biggest web framework for .NET
Dotnet-graphql [has](https://github.com/SimonCropp/GraphQL.Validation) FluentValidation (biggest validation library for .NET, i guess) integration and some of contributors helps to maintain that project
Have you any plans to support kind of thing?

My problem with Hotchocolate that i should write my own validation middleware to integrate input arguments validation and no built-in(or ... "out") support for that

**Describe the solution you'd like**
Now i should use custom hand-written (solution below) integration with FluentValidation, because Hotchocolate has nothing no validate input arguments (but has middlewares, it's great!)
And i don't like it, because it is my custom code =/

**Describe alternatives you've considered**
Go deeper and support data annotations, but they not as comfortable and powerful as FluentValidation (Just my thoughts)

**Additional context**
Extension
```cs
public static class ValidationExtensions
{
	public static IObjectFieldDescriptor Argument<TArgument, TValidator>(
		this IObjectFieldDescriptor descriptor,
		NameString argumentName,
		Action<IArgumentDescriptor> argumentDescriptor)
		where TValidator : AbstractValidator<TArgument>
	{
		return descriptor
			.Argument(argumentName, argumentDescriptor)
			.Use((_, next) =>
				new ValidationMiddleware<TArgument, TValidator>(
					next,
					argumentName));
	}
}
```

Middleware
```cs
public class ValidationMiddleware<TArgument, TValidator>
	where TValidator : AbstractValidator<TArgument>
{
	private readonly FieldDelegate next;
	private readonly NameString argumentName;

	public ValidationMiddleware(FieldDelegate next, NameString argumentName)
	{
		this.next = next;
		this.argumentName = argumentName;
	}

	public async Task InvokeAsync(IMiddlewareContext context)
	{
		var argument = context.Argument<TArgument>(argumentName);

		if (argument != null)
		{
			var validator = context.Service<TValidator>();

			var result = await validator.ValidateAsync<TArgument>(argument);

			if (!result.IsValid)
			{
				var errors = result.Errors
					.Select(error =>
						ErrorBuilder.New()
							.SetCode(error.ErrorCode)
							.SetPath(context.Path)
							.SetMessage(error.ErrorMessage)
							.SetExtension(error.PropertyName, error.ErrorMessage)
							.Build())
					.ToArray();

				context.Result = errors;

				return;
			}
		}

		await next(context).ConfigureAwait(false);
	}
}
```

Usage
```cs
...
.Argument<CustomerInput, CustomerInputTypeValidator>(
	"input",
	options => options.Type<CustomerInputType>())
...
```

**Comment by michaelstaib** [comment]
We are discussing validation at the moment. But we have not settled for a specific solution yet. We think the most important aspect is a better hook into argument coercion before doing something around it.

**Comment by michaelstaib** [comment]
we are tracking validation on this item #841.

**Comment by michaelstaib** [comment]
Just to make it clear. If you want you can help us shape the direction in this.
