### ISSUE TITLE
Directive Middleware

### ISSUE THREAD

**Issue by Dolfik1** [ChilliCream/hotchocolate#171]
I need to validate fields before process query/mutation. For example, I need to check is email have correct format, and is password strong enough.
Seems that is not possible for now, I can't find any examples in documentation and source code.

I suggest to create generic method `Validate` in `ArgumentDescriptor` that accepts validation function. This function must return validation result. Validation result contains flag, that indicates validation success, and optionally contains error message, if validation was failed.

Here is an example of `Validate` function usage:
```csharp
descriptor
    .Field(t => t.RegisterUser(default, default))
    .Type<NonNullType<UserType>>()
    .Argument("email", a => a
        .Type<NonNullType<StringType>>())
        .Validate<string>(x => ValidationUtility.IsValidEmail(x))
    .Argument("password", a => a
        .Type<NonNullType<StringType>>())
        .Validate<string>(x => ValidationUtility.IsPasswordStrong(x));
```

Also, I think this method can have more wide application, we can create it in `FieldDescriptor` and use for check user permissions on mutation or query.

**Comment by michaelstaib** [comment]
@Dolfik1: This looks promising. The resolver function would than have to call those validators and throw a FieldError which than would manifest in the result error collection.

With the current version you are able to throw a `QueryException`:

```csharp

if(!ValidationUtility.IsValidEmail(x))
{
    throw new QueryException(new FieldError("The message is not valid",  context.FieldSelection));
}

```

**Comment by Dolfik1** [comment]
Is it possible to allow developers create custom extension methods for Argument/Field Descriptor? This feature will make HotChocolate very flexible library. It is something like attributes in classic web api.

I can create extension methods right now, but seems that it is not possible to influence the processing of the request.

```csharp
    public static class Extensions
    {
        public static IObjectFieldDescriptor AllowUnauthorized(
            this IObjectFieldDescriptor descriptor)
        {
            return descriptor;
        }
    }
```

**Comment by michaelstaib** [comment]
The spec allows for directives which can be use for this. We are currently only supporting the built-in directives. We do have custom directives on our roadmap. I want first to finish work on subscriptions before doing this.

With directives you basically can annotate schema and query elements and use it to change the default execution behaviour.

```graphql
{
    person {
        firstname @skip(if: true)
        lastname
    }
}

**Comment by michaelstaib** [comment]
Once we have implemented these for custom use you could use the descriptors in code-first and annotate this:

```
public static class Extensions
    {
        public static IObjectFieldDescriptor AllowUnauthorized(
            this IObjectFieldDescriptor descriptor)
        {
            descriptor.Directive(new AuthDirective());
            return descriptor;
        }
    }
```

**Comment by michaelstaib** [comment]
I think we could do custom schema directives very quickly. I am currently solving some issues with the query directives so that it is easy to manipulate the execution behaviour and feels nice to use.

**Comment by Dolfik1** [comment]
> Once we have implemented these for custom use you could use the descriptors in code-first and annotate this:

Seems you have a typo in your code. Extension method should have name `Authorized`. 
In my example, I would like add AuthDerective to all queries/mutations, and remove it by using `AllowUnauthorized` method.
It is like `AuthorizedFilter` in Web API, that makes all methods required authorization by default, and `AllowUnauthorized` attribute, that allows to execute method without authentication.

**Comment by Dolfik1** [comment]
> I think we could do custom schema directives very quickly. I am currently solving some issues with the query directives so that it is easy to manipulate the execution behaviour and feels nice to use.

Thank you! This is a great news!

**Comment by michaelstaib** [comment]
This issue is related to #57.

**Comment by michaelstaib** [comment]
@Dolfik1: Could you have a look at #57 if that would be sufficient for your use cases?

**Comment by Dolfik1** [comment]
@michaelstaib yes, this is seems what I need to. But I have some questions:
How can I use dependency injection in `OnBeforeInvoke` and `OnAfterInvoke` methods?
What is `resolverResult` in `OnAfterInvoke` method?
What should return `OnAfterInvoke` method?

**Comment by michaelstaib** [comment]
`OnAfterInvoke` is called after the field resolver is called. The resolver result is the .net object that was returned by the field resolver. It is not yet completed, means that it was not yet serialized.
The `OnAfterInvoke` method returns the result that shall be passed into the value completion. 

This opens up some nice scenarios where you could implement a sort directive which gets the resolver result, lets say a list of strings which is than sorted. The sorted list is that returned and will be used instead of the original one. I mean sort is not the best example since you would sort in-place and return the same list that was passed in.  But it might give you an idea what it is for. 

I am thinking about breaking that interface into two interfaces, so that one has not to implement both when you do not need to implement both. In the case off a validation you might just want to implement `OnBeforeInvoke`.

Regarding your question about dependency injection I am still not quite sure what to do. You can always access all services via the resolver context. This is a service-locator-pattern way which I personally do not favour to much. Constructor injection feels better for me. So, the directive might not directly implement the interface but register its implementation.

What I mean with that is something like the following:

```csharp

public class MyValidationDirective
    : Directive
{
    protected override void Configure(IDirectiveDescriptor descriptor)
    {
        descriptor.Middleware<ValidatorMiddleware>();
    }
}

public class MyValidatorMiddleware
    : IResolverMiddleware
{
    public MyValidatorMiddleware(MyDependency foo) 
    {

    }

}

```

With that we could also allow to just use a delegate as middleware:

```csharp

public class MyValidationDirective
    : Directive
{
    protected override void Configure(IDirectiveDescriptor descriptor)
    {
        descriptor.OnBeforeInvoke(c => { /* code */ }) 
    }
}

```

**Comment by michaelstaib** [comment]
#268

**Comment by michaelstaib** [comment]
@Dolfik1 With preview 3 you should be able to implement the validation scenario.

**Comment by michaelstaib** [comment]
@Dolfik1: I have started the preview 3 build. Could you have a look at the following integration test that shows how a validation could be implemented with executable directives. I am still adding more functionality to this feature like directives on schema etc. But you can now implement your use case. Please give me some feedback.

**Comment by michaelstaib** [comment]
Hi @Dolfik1,

what du you think? Can I close this issue or do you have change requests?

**Comment by Dolfik1** [comment]
Hi. Can you wait few days? I check it during the weekend.

**Comment by michaelstaib** [comment]
Sure, I will wait for your feedback.

**Comment by Dolfik1** [comment]
I have some questions:
1. Can I add directive to all queries/mutations by default, and remove it via `IObjectFieldDescriptor` extension method for specified queries and mutations? I want make authorize directive required by default for all queries and mutations.
2. Can I use bitwise operations for `DirectiveLocation` to specify `Location`? 
For example:
```csharp
descriptor.Location(DirectiveLocation.Mutation | DirectiveLocation.Query);
```

ReSharper shows warning: `Bitwise operation on enum which is not marked by [Flags] attribute`

**Comment by michaelstaib** [comment]
> Can I add directive to all queries/mutations by default, and remove it via IObjectFieldDescriptor extension method for specified queries and mutations? I want make authorize directive required by default for all queries and mutations.

Not by default exactly, but if you put the directive on the query type than all query fields will inherit it if it is an executable directive.

> Can I use bitwise operations for DirectiveLocation to specify Location?

You can call location multiple times and add multiple locations. But we could also mark DirectiveLocation to be flags. The descriptor would have to be reworked though.

Moreover, I have been thinking this weekend to seperate directives and middleware and go a way that is more in line how asp.net works. So, we could change the implementation that you would have to register a middleware, almost the same like in asp.net. Each middleware then can use directives in order to change the execution behaviour. 

There are some drawbacks here. The current implementation supports pipelining where the resolver value can be transformed during the execution.

Lets say we just have a GraphQL SDL like the following:

```GraphQL
type Query {
  person: Person
}

type Person {
 ...
}
```

we could now add our executable directives and make this schema executable without writing any code.

```GraphQL
type Query {
  person: Person @httpGet(url: http://someUrl) @json(path: "persons.person")
}

type Person {
 ...
}
```

Since with the current implementation the resolvers are chained the resolver result flows to each resolver. So, httpGet fetches some web content and json takes the content and gets some part of the json and throws it back into the execution pipeline.

Since middlewares are currently bound to directives this world quite well. 

I am currently in Germany and on my way back to Zurich. I will elaborate on this a bit more once I am back tomorrow.

**Comment by michaelstaib** [comment]
| Location               | OnBeforeInvoke | OnInvoke | OnAfterInvoke |
| ---------------------- | -------------- | -------- | ------------- |
| QUERY                  |                |          |               |
| MUTATION               |                |          |               |
| SUBSCRIPTION           |                |          |               |
| FIELD                  | X              | X        | X             |
| FRAGMENT_DEFINITION    |                |          |               |
| FRAGMENT_SPREAD        |                |          |               |
| INLINE_FRAGMENT        |                |          |               |
| SCHEMA                 | X              | X        | X             |
| SCALAR                 |                |          |               |
| OBJECT                 | X              | X        | X             |
| FIELD_DEFINITION       | X              | X        | X             |
| ARGUMENT_DEFINITION    |               |          |               |
| INTERFACE              | X              | X        | X             |
| UNION                  |                |          |               |
| ENUM                   |                |          |               |
| ENUM_VALUE             |                |          |               |
| INPUT_OBJECT           |                |          |               |
| INPUT_FIELD_DEFINITION |                |          |               |

**Comment by michaelstaib** [comment]
The table above shows on which directive locations you can put a middleware. Moreover, executable directives are inherited. So, executable directives on a type flow onto all the fields by default. The directives on a field flow onto the field selection in a query.

Directives on interfaces flow onto objects and so on....

**Comment by Dolfik1** [comment]
> Not by default exactly, but if you put the directive on the query type than all query fields will inherit it if it is an executable directive.

OK, thanks. I am little bit figured out, and have an idea how to implement what I want.

> You can call location multiple times and add multiple locations. But we could also mark DirectiveLocation to be flags. The descriptor would have to be reworked though.

That's would be great. Bitwise operations is most obviously for me to specify multiple locations.

> Moreover, I have been thinking this weekend to seperate directives and middleware and go a way that is more in line how asp.net works. So, we could change the implementation that you would have to register a middleware, almost the same like in asp.net. Each middleware then can use directives in order to change the execution behaviour.

Sounds good, but I do not totally understand how it will be implemented.

**Comment by michaelstaib** [comment]
> Is it correct behaviour? I can try to fix it and make PR, if this behaviour wrong.

Is the directive associated with the type? Can you post your directive code?

**Comment by Dolfik1** [comment]
> 
> 
> > Is it correct behaviour? I can try to fix it and make PR, if this behaviour wrong.
> 
> Is the directive associated with the type? Can you post your directive code?

I have not access to code right now, but you can try to change [this](https://github.com/ChilliCream/hotchocolate/blob/master/src/Core.Tests/Integration/ArgumentValidation/QueryType.cs) code to generic way, and integration test must be failed. I used the same code to reproduce the behavior.

**Comment by michaelstaib** [comment]
Ah, now I understand. No, in this case the behaviour is correct. So, let me explain this example in more detail.

I have two directives, one acting just as a middleware. This directive has no arguments and is not associated with a .net type.

```csharp
public class ExecuteArgumentValidationDirectiveType
        : DirectiveType
    {
        protected override void Configure(IDirectiveTypeDescriptor descriptor)
        {
            descriptor.Name("executeValidation");
            descriptor.Location(Types.DirectiveLocation.Object);
            descriptor.OnBeforeInvokeResolver<ExecuteArgumentValidationMiddleware>(
                t => t.Validate(default));
        }
    }
```

The type `ExecuteArgumentValidationMiddleware` just contains the middleware logic. So in our case it has the validation logic.

Since this type has no .net representation you can only use the name or the ast node to associate the directive with your type.

The second directive type...

```csharp
public class ArgumentValidationDirectiveType
        : DirectiveType<ArgumentValidationDirective>
    {
        protected override void Configure(
            IDirectiveTypeDescriptor<ArgumentValidationDirective> descriptor)
        {
            descriptor.Name("validate");
            descriptor.Location(Types.DirectiveLocation.ArgumentDefinition);
            descriptor.BindArguments(BindingBehavior.Explicit);
        }
    }
```

... has a .net type representation `ArgumentValidationDirective`.

**Comment by Dolfik1** [comment]
> But if you want you can add the flags functionality so that location can be defined bitwise. The descriptor will still have to have a list of directive location underneath. Do you want to create a PR for that?

Yes, sure. Please check my PR.

**Comment by michaelstaib** [comment]
> I think we need throw exception on startup if wrong directive name setted.

Yes, there should be a schema exception on Schema.Create.

So, I think we should report this error during schema creation. In the directive type class is a method called `OnRegisterDependencies`. The type of the graphql schema has 3 initialisation phases.

1. Creation -> This is when the descriptors are executed and the actual type object is created.
2. RegisterDependencies -> This is called by the type initialization flow and allows the type object to report their dependencies on other types in the schema.
3. CompleteType -> The type can now request all its dependencies from the schema and finalize itself. After all types are completed the schema and its types become immutable.

An error can be reported during phase 2 and 3 via the initialisation context. 

Just as a little background for you how the types work.

Regarding the non-generic `DirectiveType`:

The untyped (non-generic) variant of `Directive` is useful when we build a schema from the graphql sdl (Schema First). So, basically you can soon provide Hot Chocolate with a schema and add some directives and the schema automatically maps a database without any code needed.

**Comment by michaelstaib** [comment]
So, what we need to do next to get this feature finally out:

- [ ] Report Type Validation Issues (Name is missing or invalid). -> context.ReportError()
- [ ] Write some more integration tests that show a view directive use-cases
- [ ] Write tests that show the execution engine error behaviour is correct (I am currently working on this one)
- Documentation

Do you have anything else that you think has to be done to get this feature finished?

**Comment by michaelstaib** [comment]
#278

**Comment by Dolfik1** [comment]
> Do you have anything else that you think has to be done to get this feature finished?

I have some ideas about `InvokeResolver`. We can make interface IInvokeResolver:

```
interface IInvokeResolver
{
    void Invoke(IResolverContext context);
}
```
And inherit it in our resolver:

```
class ExecuteArgumentValidationMiddleware : IInvokeResolver
{
    void Invoke(IResolverContext context)
    {
        ...
    }
}
```
and then use it in directive configuration:
```
descriptor.OnBeforeInvokeResolver<ExecuteArgumentValidationMiddleware();
```

This is classic OOP way, this way is more explicit and obvious to people previously working with other frameworks. Dependencies can be injected in `ExecuteArgumentValidationMiddleware ` constructor.

What do you think about this?


Few days ago you said about splitting directives and middleware, did you have any progress in this?

**Comment by michaelstaib** [comment]
> Few days ago you said about splitting directives and middleware, did you have any progress in this?

No, the current solution still feels better at the moment. 

> void Invoke(IResolverContext context)

I originally started with an interface but have abandoned the idea because of the following issues:

1. The delegate has less overhead.
2. Member bindings allow strongly typed middleware methods:

```csharp
public Task<string> MyResolverFunc(Person previousResolverResult [DataLoader]SomeDataLoader loader)
```

With the interface one would be stuck fetching everything from the context. Feels like using some kind of service locator pattern.

We still could introduce an interface to provide another way to specify a middleware.

I just have looked up how AspNetCore Is implementing that. So, they provide an extension methods that lets you use interfaces.

see here:
https://github.com/aspnet/HttpAbstractions/blob/07d115400e4f8c7a66ba239f230805f03a14ee3d/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UseMiddlewareExtensions.cs

We could introduce it this way. The delegates and member bindings would execute faster but you could use an interface to specify a middleware.

What are your thoughts on that?

**Comment by michaelstaib** [comment]
But maybe we should get rid of OnBeforeInvoke and OnAfterInvoke and just have the OnInvoke.... This would make the execution pipeline cleaner.

**Comment by Dolfik1** [comment]
> The delegate has less overhead.

It depends. How you do method invoke?
We can try to use `struct` in middleware, and instantiate it on stack. That should be very fast, and with zero allocation. We can allocate memory for struct manually, but I have no idea how to inject dependencies fast enough.

> But maybe we should get rid of OnBeforeInvoke and OnAfterInvoke and just have the OnInvoke.... This would make the execution pipeline cleaner.

Is there any case, when `Before`/`After` might be useful?

**Comment by michaelstaib** [comment]
Regarding the interfaces lets implement the interface support like Microsoft did it with their extension method. This way one can use it however one prefers it.

Moreover, I have reviewed how they do their middleware and I think I will redesign our base delegate to work similar. Let me do some foundational work and then if you like we could split the work.

**Comment by Dolfik1** [comment]
> Let me do some foundational work and then if you like we could split the work.

OK, let me know when you finish your work.

**Comment by Dolfik1** [comment]
@michaelstaib I wrote small benchmark to measure method call:
```
                          Method |     Mean |    Error |    StdDev | Allocated |
-------------------------------- |---------:|---------:|----------:|----------:|
 ExpressionWayDirectMethodInvoke | 134.7 ms | 4.119 ms | 11.883 ms |       0 B |
             ExpressionWayStruct | 136.3 ms | 3.625 ms | 10.458 ms |       0 B |
        NativeDirectMethodInvoke | 128.6 ms | 2.604 ms |  7.128 ms |       0 B |
                    NativeStruct | 134.9 ms | 4.197 ms | 12.308 ms |       0 B |
```
here is code: https://gist.github.com/Dolfik1/d94b75ceb555c662c5da057d2813761d

each test method call OnInvoke method 100000 times, but:
ExpressionWayDirectMethodInvoke - makes method call via generated expression for exist object.
ExpressionWayStruct  - makes method call via generated expression, but new struct instance created per call.
NativeDirectMethodInvoke - same as 1, but without generate expression.
NativeStruct  - same as 2, but without generate expression.

As you see, overhead with new object per call very small. I used `struct` to make all memory allocations on stack, so GC also does not make any overhead.

**Comment by michaelstaib** [comment]
I will upload the benchmarks tomorrow there were some issues with your implementation since you used var x = new Class() which than optimises quite differently. Moreover, when the invocations return real data instead of calling console.writeline the result changes again. 
Last but not least when results are generated it is important to return those to the benchmark engine so that the jit does not optimise those away.

**Comment by michaelstaib** [comment]
But what I also checked by studying the asp.net core implementation is that they have a convention based middleware. Meaning, that event without interface you can do something like the following:

```csharp
app.Use<MyMiddlewareClass>();
```

So, no need to mark the actual method that shall be used.

**Comment by michaelstaib** [comment]
I think I will get the middlewares refactored by tomorrow. You could then start integrating the interface support if you like.

**Comment by michaelstaib** [comment]
@Dolfik1: I was a little bit lazy on the weekend so I have only now finished my work on the middleware.

It feels now a lot more like asp.net.

Regarding the interface. The interface would look something like the following now:

```csharp
public class IFieldMiddleware
{
    Task InvokeAsync(IDirectiveContext context);
}
```

The delegate works almost the same like in asp.net core:
```csharp
desc.Middleware(next => context => 
{
   context.Result = "Foo";
   next.Invoke();
});
```

The nice thing about this delegate is that basically you provide a factory that returns a delegate that represents the real invocation. This way you can short-circuit the pipeline.

With the interface short-circuiting the pipeline can be done by injecting the next pipeline into the constructor.

With the convention based approach in cases you do not want to bother about the next delegate the generator will take care of that. In cases where you inject the next delegate you as a developer are responsible for calling it.

I will write some more tonight on how to use the middleware.

**Comment by michaelstaib** [comment]
@Dolfik1: I have started work on the documentation but will not manage to write everything today.

We should create a slack channel to have another way to communicate.

**Comment by michaelstaib** [comment]
The documentation is here.... but I am still working on it:
https://github.com/ChilliCream/hotchocolate-docs/blob/master/docs/directive-middleware.md

**Comment by Dolfik1** [comment]
I check middleware implementation later.


> 
> 
> @Dolfik1: I have started work on the documentation but will not manage to write everything today.
> 
> We should create a slack channel to have another way to communicate.

It would be a good idea.


I am possibly found a bug. GraphiQL does not show directives, that declared in fields.

**Comment by michaelstaib** [comment]
I have opened a slack channel https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNDUyMjIxOTc1MTU3LWNlN2ViMGM5YTVhMWI3MzcwNDdjOTVkYWQ5ODZkMjJiODIwZjY5MzYzODc1Zjg5NDE5ZDQ4Zjk0MGExZWMzZGY

**Comment by michaelstaib** [comment]
I will close this issue and create follow up issues for interface support and so on....
