### ISSUE TITLE
BindFieldsImplicitly can not ignore indexers.

### ISSUE THREAD

**Issue by chyyran** [ChilliCream/hotchocolate#1711]
**Describe the bug**
When using implicit bindings for a type with an indexer property, HotChocolate attempts to create a GraphQL field. This fails as indexer properties are allowed to take arguments, resulting in the following exception.

```
System.ArgumentException: 'Incorrect number of arguments supplied for call to method 'MyClass get_Item(MyArgumentType)' (Parameter 'property')'
```

I tried to explicitly ignore the property like so

```csharp
descriptor.Ignore(c => c[default]);
```

But this causes the following exception
```
System.ArgumentException: 'The member expression must specify a property or method that is public and that belongs to the type MyClass (Parameter 'expression')'
```

**To Reproduce**
* Create a backing class or interface with an indexer property accepting one or more arguments
* Create an `ObjectType<T>` code-first definition for the backing class, with implicitly bound fields.
* Ignore the indexer in `Configure` with `descriptor.Ignore(c => c[default]);`.

**Expected behavior**
The indexer is ignored.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 11.0.0-preview.123

**Additional context**
This is outside of the scope of this bug report, but in the future it may be interesting to explore binding indexer properties to fields that take arguments.

Discussed in [Slack](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1586905899354100)

**Comment by michaelstaib** [comment]
Indexers are now detected and ignored. The question is if we want to allow indexers explicitly like so ... 

```
descriptor.FIeld(t => t[default])
```

For 11.1 we will just stick with ignoring them but we will have another look at it with version 12.
