### ISSUE TITLE
Subscriptions path have to end with /?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1712]
**Describe the bug**
I had a problem with subscriptions using GraphiQL with custom paths:
```cs
app.UseWebSockets()
	.UseGraphQL("/graphql")
	.UseGraphiQL("/graphql")
```
Subscriptions isn't working, BUT if i setup UseGraphQL(options) manually and add to SubscriptionPath `/` to the end all start working:
```cs
app.UseWebSockets()
	.UseGraphQL(new QueryMiddlewareOptions
	{
		Path = "/graphql",
		SubscriptionPath = "/graphql/"
	})
	.UseGraphiQL("/graphql")
```

The problem is that `SubscriptionMiddleware.IsValidPath` is checking for `equality` of string and `context.Request.Path` ends with `/`

**To Reproduce**
1. Create project, add subscriptions
2. Configure custom path for graphql api
3. Raise subscription

**Expected behavior**
```.UseGraphQL("/graphql")``` is working with subscriptions

**Desktop (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/46970457/79389076-eb5f9600-7f76-11ea-955d-e7b636a48517.png)

**Comment by michaelstaib** [comment]
We have this on our list already. We will deprecate GraphiQL in favor of Playground. But playground at the moment has the same problem. We are already tracking this on our 11 backlog so I am closing this one.

**Comment by michaelstaib** [comment]
#1630
