### ISSUE TITLE
Support other DI frameworks / IoC containers?

### ISSUE THREAD

**Issue by Confusingboat** [ChilliCream/hotchocolate#1714]
**Is your feature request related to a problem? Please describe.**
I am using Simple Injector in an ASP.NET Core project where all my custom services are registered, and only have third party services that absolutely depend on IServiceCollection registered with the default DI framework, like Hot Chocolate. I cannot resolve my own application services (like my repositories) without creating a registration with the Microsoft DI that calls back to my Simple Injector container. Simple Injector supports cross-wiring, but it's only one-way that falls back to Microsoft DI from the Simple Injector container, not the other way around.

**Describe the solution you'd like**
I propose adding the ability to specify _any_ IServiceProvider to resolve services from to allow free use of whatever DI framework one would want. I'm not sure if that is what `AddServices(IServiceProvider)` is intended to do on the SchemaBuilder, but I have passed my Simple Injector container to this method and it did not work, and I am unable to find any meaningful documentation about this method.

**Describe alternatives you've considered**
I briefly attempted to create an external integration with Simple Injector for Hot Chocolate that essentially just replaces IServiceCollection with a Simple Injector container, but it appears that Hot Chocolate is deeply dependent on the IServiceCollection, beyond simply integrating with ASP.NET Core, to the point where many internal classes and methods would have needed to be modified or replaced, causing a ton of duplicated code. Perhaps I'm just not understanding where the proper place is to create the integration with an external IServiceProvider. Should I instead create a custom ISchemaBuilder?

**Comment by PascalSenn** [comment]
hot chocolate does not have a dependency on a specific dependency injection framework. 
It only need a DI framework that correctly implements IServiceProvider. 
I think one way to use Simple Injector is the following guide:
https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html

**Comment by Confusingboat** [comment]
Yeah I know how to use Simple Injector, and I've used it in several projects, but I'm saying that, when using the ASP.NET Core integration, I cannot get Hot Chocolate to resolve dependencies unless they are registered with IServiceCollection.

When using Simple Injector, the cross-wiring works by first attempting to resolve from the Simple Injector container, and if that fails, then by anything registered with IServiceCollection. It is not supported or implemented to register a service with the Simple Injector container and then resolve it from something registered with IServiceCollection.

Basically, all I'm looking for is a way to use the default Hot Chocolate ASP.NET Core integration (which lets it register all its stuff with IServiceCollection) but tell Hot Chocolate to try resolving from the Simple Injector container (which implements IServiceProvider) instead of the one provided by the default DI framework, or some guidance on how to wire up my own integration with Simple Injector without having to reverse engineer the prebuilt ASP.NET Core integration. I haven't been able to locate any documentation on what Hot Chocolate types to register with other DI frameworks, only the default integration guides that tell you to use the extension methods.

**Comment by TheJayMann** [comment]
The `AddGraphQL` extension method has one overload which takes a `Func<IServiceProvider,ISchema>`.  With this method, instead of using `services.AddGraphQL(SchemaBuilder.New().AddQueryType<QueryType>());`, you would use `services.AddGraphQL(sp => SchemaBuilder.New().AddQueryType<QueryType>().AddServices(sp).Create()`.  In your case, you could create your own `IServiceProvider`, which has a reference to SimpleInjector `IServiceProvider` and the service provider provided as the lambda parameter, which attempts to first get a service from SimpleInjector, and, failing that, attempts to get a service from the provided service provider.  And, assuming you already have something which does that, simply provide that to the `AddServices` method in the builder.

**Comment by michaelstaib** [comment]
@TheJayMann there might be more issues in the detail since we get a scoped service provider from asp.net into the request. So all services that are used during the request are solved using that. So you would also need to wire that up. 

@Confusingboat how are scopes handled in simple injector? I mean how are they created in asp.net core? You would need to handle that. You basically can add a request interceptor which can configure the graphql request that is passed to the execution engine. you can add the scoped services there.

We so far had not a lot demand for other DIs but are open to make this experience better. Internally we only need `IServiceProvider` so it should be easy to integrate it.

I am also opent to create a package for it but the input would need to come from you on that.

**Comment by Confusingboat** [comment]
@TheJayMann if I'm understanding you correctly, all I should have to do is pass the Simple Injector container to `AddServices` (it what implements `IServiceProvider`); this was actually the very first thing I tried, however in doing this I get an error stating my service cannot be resolved. The only way I can get Hot Chocolate to resolve my services is by using `IServiceCollection`, as illustrated by the following three examples.

Does not work:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddServices(Container)
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());
```
`("No service for type 'CarmmunityApiCore.Dal.Users.IUserRepository' has been registered.")`

Works:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddServices(Container)
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());

services.AddTransient(sp => Container.GetInstance<IUserRepository>());
```

Also works:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());

services.AddTransient(sp => Container.GetInstance<IUserRepository>());
```

I'm going to dig into the Hot Chocolate code to see how the `IServiceProvider` is consumed after it is added via `AddServices` to see what's going on, since clearly my providing one is not working as expected.

@michaelstaib scopes are handled as expected with the default integration pattern of Simple Injector, in that it sets the default scope lifecycle to a request (though other scopes may be defined manually) as indicated here: https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html
I would expect this behavior to extend into using it with Hot Chocolate.

**Comment by Confusingboat** [comment]
@TheJayMann if I'm understanding you correctly, all I should have to do is pass the Simple Injector container to `AddServices` (it what implements `IServiceProvider`); this was actually the very first thing I tried, however in doing this I get an error stating my service cannot be resolved. The only way I can get Hot Chocolate to resolve my services is by using `IServiceCollection`, as illustrated by the following three examples.

Does not work:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddServices(Container)
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());
```
`("No service for type '...IUserRepository' has been registered.")`

Works:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddServices(Container)
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());

services.AddTransient(sp => Container.GetInstance<IUserRepository>());
```

Also works:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());

services.AddTransient(sp => Container.GetInstance<IUserRepository>());
```

I'm going to dig into the Hot Chocolate code to see how the `IServiceProvider` is consumed after it is added via `AddServices` to see what's going on, since clearly my providing one is not working as expected.

@michaelstaib scopes are handled as expected with the default integration pattern of Simple Injector, in that it sets the default scope lifecycle to a request (though other scopes may be defined manually) as indicated here: https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html
I would expect this behavior to extend into using it with Hot Chocolate.

**Comment by TheJayMann** [comment]
At this point, having looked more into how service providers are used in HotChocolate, I'm more confused than anything else, thus I don't believe I can contribute anything further to the discussion.

**Comment by michaelstaib** [comment]
Just as a small waring around this... we are currently working on the new execution engine so the code around this will completely change.

so the way it works is that we have two layers of dependency injection. 

```
SchemaBuilder.New()
   .AddServices(foo)
```

will add the service provider that is used by the type system to get service during creation or even to bring in place some global services.

Then we have the runtime services. Which you can modify by doing:

services.AddRequestInterceptor((httpContext, requestBuilder, ct) => 
{
    // internally we do:
    requestBuilder.SetServices(httpContext.RequestServices);
    // this gives the correctly scoped services for that particular service.
    return Task.CompletedTask;
});

both of these apis will still be there with 11. But internally with version 9 we had some kind of an internal service provider that we used for infrastructure which messed a lot up. We removed this for 10 but still have a lot of the code around which makes it difficult to understand. 

So with 11 we are at the moment reworking all the dependency injection code. It is the right time to make it work more easily with other DIs.

**Comment by Confusingboat** [comment]
Thanks for the interceptor guidance @michaelstaib, that worked. I do feel it seems like a rather hacky, nuclear approach though, just forcing an `IServiceProvider` in there on every request, and that a simple upfront configuration like `AddServices` would be a more user-friendly approach for adding global services.

Also, after brushing up on how Simple Injector handles scoped services, I am a little less sure of its effectiveness outside of their own controller activator since I don't know how it will mesh with Hot Chocolate due to my unfamiliarity with the inner-workings of Hot Chocolate's request execution. By default, async scoped is used by Simple Injector, which is described here: https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#asyncscoped
Any insight you have on this would be greatly appreciated.

For future persons encountering an issue like this, here is an example of the working code as of Hot Chocolate v10.4, but I would put an asterisk next to doing it this way without first knowing how Simple Injector's (or another DI framework's) scoping works in conjunction with Hot Chocolate:
```
private SimpleInjector.Container Container { get; } = new Container();

...

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddQueryType<QueryType>()
    .AddType<UserType>()
    .AddType<UserQueries>()
    .Create());

services.AddQueryRequestInterceptor((httpContext, requestBuilder, ct) =>
{
    requestBuilder.SetServices(Container);
    return Task.CompletedTask;
});
```

**Comment by tobias-tengler** [comment]
I think most people are using the "default" Microsoft DI, so there is no need for a "top-level" API to switch the service provider in my opinion. In the case that someone needs to switch out the service provider, we provide [documentation for this](https://chillicream.com/docs/hotchocolate/server/dependency-injection/#switching-the-service-provider).
I'm closing the issue, since it has been stale for a while now and not many people seem to require a more integrated solution on the regular.
