### ISSUE TITLE
Relay-style paging improvements suggestions

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#1716]
**Is your feature request related to a problem? Please describe.**
I'm using a relay-style paging in my project which exposes the data out of very big database (tens of millions of records). How for obvious reasons I don't want my customers to be able to get all of the data in one call and I want to enforce paging on them (say. max 1000 records with one query). 

**Describe the solution you'd like**
In the current implementation paging is completely optional, and it'd be great to be able to make it mandatory by some kind of overload on `.UsePaging` or parameter. Ideally what I'd like is those things:
* be able to define mandatory paging for specific query
* be able to define max value of `first` and `last` paging parameters (currently it's `int.MaxValue`)
* be able to provide a default value for `first` and `last` paging parameters

**Describe alternatives you've considered**
I've actually implemented all of the above in my project but I had to rewrite some of the extension methods in order to achieve this.

```
// this is the same as UsePaging<T> but it calls AddCustomPagingArguments instead of 
// AddPagingArguments
public static IObjectFieldDescriptor UseCustomPaging<T>(
  this IObjectFieldDescriptor descriptor)
  where T : class, IOutputType
{
  static FieldDelegate Placeholder(FieldDelegate next) => context => Task.CompletedTask;
  var middlewareDefinition = typeof(QueryableConnectionMiddleware<>);

  descriptor
    .AddCustomPagingArguments()
    .Type<ConnectionWithCountType<T>>()
    .Use(Placeholder)
    .Extend()
    .OnBeforeCompletion((context, definition) =>
    {
      var reference = new ClrTypeReference(typeof(T), TypeContext.Output);
      var type = context.GetType<IOutputType>(reference);
      if (!(type.NamedType() is IHasClrType hasClrType))
      {
        return;
      }

      var middlewareType = middlewareDefinition.MakeGenericType(hasClrType.ClrType);
      var middleware = FieldClassMiddlewareFactory.Create(middlewareType);
      var index = definition.MiddlewareComponents.IndexOf(Placeholder);
      definition.MiddlewareComponents[index] = middleware;
    })
    .DependsOn<T>();

  return descriptor;
}

// default value provided to first and last parameters
// replaced PaginationAmountType with LimitedPaginationAmountType
private static IObjectFieldDescriptor AddCustomPagingArguments(
  this IObjectFieldDescriptor descriptor) =>
  descriptor
    .Argument(ARG_FIRST, a => a.Type<LimitedPaginationAmountType>()
      .DefaultValue(MAX_PAGE_SIZE))
    .Argument(ARG_AFTER, a => a.Type<StringType>())
    .Argument(ARG_LAST, a => a.Type<LimitedPaginationAmountType>()
      .DefaultValue(MAX_PAGE_SIZE))
    .Argument(ARG_BEFORE, a => a.Type<StringType>());

// limit max page size to something less that int.MaxValue
public sealed class LimitedPaginationAmountType
  : IntTypeBase
{
  public const int MAX_PAGE_SIZE = 1000;

  public LimitedPaginationAmountType()
    : base("LimitedPaginationAmount", 0, MAX_PAGE_SIZE)
  {
  }
}
```

**Additional context**
I believe all of that could be achieved by adding an optional parameter to `UsePaging<T>` where configuration can be specified. Perhaps something like:
```
.UsePaging<MyType>(new PagingOptions 
{ 
  DefaultPageSize = 1000, 
  MaxPageSize = 2000, 
  Mandatory = true 
});

**Comment by michaelstaib** [comment]
Hi,  this is on our list.

**Comment by RaYell** [comment]
I saw that all this is possible in V11. I think this issue can be closed now.
