### ISSUE TITLE
Add namespaced subscriptions support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1718]
**Is your feature request related to a problem? Please describe.**
I can do nested mutations:

```cs
descriptor.Field("entities")
	.Type<EntityMutationsType>()
	.Resolver(new object());
```

```gql
mutation {
  entities {
    create(input: {field: "field"}) {
      field
    }
  }
}
```

but using subscriptions like this not works and return error message `Register a event registry as service in order to use subsciptions.` - because i do not subscribe to anything on namespaced-type

**Describe the solution you'd like**
Add something to support namespaced subscriptions

**Describe alternatives you've considered**
Explain me/add to docs workarounds or why it shouldn't be used

**Additional context**

**Comment by PascalSenn** [comment]
@sergeyshaykhullin  Nested Mutations and especially nested subscriptions are not supported by the graphql spec. 

[normal and serial execution:](https://spec.graphql.org/June2018/#sec-Normal-and-Serial-Execution)

>Because the resolution of fields other than top‐level mutation fields must always be side effect‐free and idempotent, the execution order must not affect the result, and hence the server has the freedom to execute the field entries in whatever order it deems optimal.

**Comment by michaelstaib** [comment]
I will close this issue since the mentioned request violates the GraphQL spec.
