### ISSUE TITLE
Add EventMessage<T> method to context resolver

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1719]
**Is your feature request related to a problem? Please describe.**
Now i don't get how to extract event message from code-first approach in 10.4.1 not using string keys and direct casts in resolver:
```cs
descriptor.Field("onEntity")
  .Type<NonNullType<EntityType>>()
  .Subscribe(async context => await context
    .Service<ITopicEventReceiver>()
    .SubscribeAsync<string, OnEntityEventMessage>(nameof(OnEntityEventMessage)))
  .Resolver(context =>
  {
    // This part
    var message = (OnEntityEventMessage) context.ContextData["HotChocolate.Execution.EventMessage"];

    // ...
  })
```

**Describe the solution you'd like**
Add method like Service\<T>, Resolver\<T>, Parent\<T> named EventMessage\<T>

**Comment by michaelstaib** [comment]
Usually you would have a method backing your resolver in which case we compile a native resolver for your function with method level dependency injection.

```
public async Task<Foo> MyResolver([EventMessage]MyMessage message) 
{

}
```

**Comment by michaelstaib** [comment]
Both the subscribe and the resolve method can be represented as methods rather than delegates.

**Comment by michaelstaib** [comment]
You basically could simplyfiy your code to:


```csharp
public class Subscription 
{
    [Subscribe(nameof(OnEntity))]
    public async ValueTask<IAsyncEnumerable<OnCustomerEventMessage>> SubscribeToOnEntity([Service]ITopicEventReceiver eventReceiver) => 
        eventReceiver.SubscribeAsync<string, OnEntityEventMessage>(nameof(OnEntityEventMessage)));
 

    public async Task<Entity> OnEntity([EventMessage] OnCustomerEventMessage message) 
    {
     
    }
}
```

you can now either use the type to bind these or just register this type like is:

```csharp
SchemaBuilder.New()
    .AddSubscriptionType<Subscription>()
    ....
    .Create()
```

However, I think it would still be nice to have a helper around this for the case when you really want to do it as a delegate. Will add one for 10.4.2.

**Comment by DrJuriko** [comment]
Thank you for your support, also I found these resources - 

https://chillicream.com/blog/2019/12/26/hotchocolate-10.3.0#subscriptions
https://github.com/ChilliCream/hotchocolate-examples/tree/master/blog/2020/2020-03-24-subscriptions

But for "2020-03-24-subscriptions" it could be great to have examples of implementation for ITopicEventReceiver/ITopicEventSender

**Comment by sergeyshaykhullin** [comment]
@michaelstaib Is this feature released in 10.4.2?

**Comment by michaelstaib** [comment]
No, we just did bug fixes in 10.4.2.

**Comment by michaelstaib** [comment]
I am a bit hesitant for this one since we are working on a big feature update for 11 and I think we should do that on 11 instead on 10.

**Comment by michaelstaib** [comment]
Lets track this on this issue #1744
