### ISSUE TITLE
How to get HTTP headers in query/mutation?

### ISSUE THREAD

**Issue by Dolfik1** [ChilliCream/hotchocolate#172]
Can I get HTTP headers or `HttpContext` inside query/mutation method? It is necessary for authorization.

**Comment by michaelstaib** [comment]
The HTTPContext is now available through dependency injection or via the `IResolverContext`. This behaviour will be available with once #177 is merged.

**Comment by michaelstaib** [comment]
Change is integrated in [0.4.0-preview-2](https://github.com/ChilliCream/hotchocolate/releases/tag/0.4.0-preview-2).
