### ISSUE TITLE
[Question] descriptor.Field([fieldname]).ignore() is failing

### ISSUE THREAD

**Issue by MartinScha** [ChilliCream/hotchocolate#1721]
I want to ignore fields of different ObjectTypes with a list of field names.
During testing I noticed that the Ignore () function does not work when using the field name.

The descriptor.Field ("Deleted") .Ignore () or descriptor.Field ("deleted") .Ignore () statements 
have no effect.

If i use the statement descriptor.Field(t => t.Deleted).Ignore() everything works.

How can I solve the problem? 

Thank you!

**Comment by michaelstaib** [comment]
can you retest this with the current 10.5 preview?

**Comment by MartinScha** [comment]
Hi Michael!

Sorry, but I was only able to run the tests now.

Unfortunately, it still doesn't work.

The field to be ignored is still displayed.

I tested different spellings with the version 10.5.0-rc.0.

Model ContactItem:
public string OrgGroupId {get; set; }

ObjectType ContactItem:
Test 1: descriptor.Field("OrgGroupId").Ignore();
Test 2: descriptor.Field("ORGGROUPID").Ignore();
Test 3: descriptor.Field("orgGroupId").Ignore();

I then carried out the three tests again with the CamelCase naming convention switched on.
These tests also did not lead to the desired result.

I solved the problem by using the [GraphQlIgnore] attribute in the model.

Greetings from Hamburg to Zurich!

 

Gesendet: Dienstag, 07. Juli 2020 um 23:44 Uhr
Von: "Michael Staib" <notifications@github.com>
An: "ChilliCream/hotchocolate" <hotchocolate@noreply.github.com>
Cc: "MartinScha" <martin@schababerle.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ChilliCream/hotchocolate] [Question] descriptor.Field([fieldname]).ignore() is failing (#1721)


 

can you retest this with the current 10.5 preview?

**Comment by michaelstaib** [comment]
This one is now fixed.
