### ISSUE TITLE
Add UseSelection<TSource, TResult>()/UseProjection<TSource, TResult>

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1727]
**Is your feature request related to a problem? Please describe.**
I am trying to construct something like:
```
var models = db.Entities.Select(e => new Model{ Property = e.Property }).ToArray()
```
using HC and stuck in the problem that `UseSelection` can select from T to T only and i can't construct a valid expression using `IQueryable<TEntity>` and project to `IQueryable<TModel>`

**Also here**
If `IQueryable<T>`, `but UseSelection<U>` HC just thorwing `ANE`, because no `if (result is ...)` passed in `SelectionMiddleware` and trying use `null.Select(visitor.Project)`. I think that need more readable exception

**Describe the solution you'd like**
- Add `UseSelection<TSource, TResult>()/UseProjection<TSource, TResult>`
- Add `SelectionMiddleware<TSource, TResult>`, for `UseSelection<T>` used `SelectionMiddleware<T, T>`
- Add `SelectionVisitor.Project<TSource, TResult>()`

**Describe alternatives you've considered**
Put this in backlog or show a workaround and just fix an exception to more readable

**Additional context**
```
descriptor.Field(x => x.GetEntities(default!))
	.Name("entities")
	.Type<NonNullType<ListType<NonNullType<EntityModelType>>>>()
	.UsePaging<EntityModelType>()
        // HERE IS PROBLEM
	.UseSelection<EntityModel>()
        // Entity, because here is IQeryable<Entity>
	.UseFiltering<Entity>(options =>
	{
		options.Filter(x => x.Property).BindFiltersImplicitly();
	})
	.UseSorting();
```

**Comment by PascalSenn** [comment]
Do you now Automapper? https://automapper.org/

**Comment by sergeyshaykhullin** [comment]
Yes, but i should write my own Middleware, Extensions, Profiles and then support all of that =(

**Comment by sergeyshaykhullin** [comment]
May be it is a point to create some IProjectionProvider/whetever and then configure how to create projections, then i can comfortably use AutoMapper (or not).

@PascalSenn What you think about that? Am i understand you correct? Better approach?

**Comment by TheJayMann** [comment]
I already do what you mention above, where I have an entity type describing the database, but I'd rather expose a different model type to graphql.  In that case, I have my own code which does a select to project from the entity type to the model type, which converts the `IQueryable<TEntity>` to `IQueryable<TModel>`, then I return the `IQueryable<TModel>` to the query execution engine.  The selection middleware will then be converting the `IQueryable<TModel>` to `IQueryable<TModel>` with only the selected properties populated, all other properties as default value. I briefly mention this concept [here](https://github.com/ChilliCream/hotchocolate/issues/1605#issuecomment-604105191).

Two things to note here.  First, this specifically was designed with Entity Framework Core/SQL Server in mind.  The queries generated by this may or may not work correctly with other Entity Framework Core providers or other query providers.  Second, Automapper, making use of its `IQueryable` support, will end up generating the same code which I manually provided, provided the correct mappings are either inferred or specified.  Thus, Automapper should work without having to write much beyond the typical Automapper configurations.

**Comment by sergeyshaykhullin** [comment]
@PascalSenn I read a thread about UseSelection and not intuitive exception in it.
I stuck in same problem earlier, one of points of this issue is to add more readable exceptions, can you add to backlog? https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1588180161236300

...

Not `Value cannot be null`, but `Return type should be IQueryable/IEnumerable, lalala, use UseFirstOfDefault/UseSingleOrDefault to return single value, lalala`
