### ISSUE TITLE
Problem with Queries.graphql file for StrawberryShake

### ISSUE THREAD

**Issue by flacidsnake** [ChilliCream/hotchocolate#1728]
Hi,

I have the following queries at my Queries.graphql file:

```graphql
query auth($token: String) {
	auth_externallogin(logintoken: $token) {
		result
		errors {
			errorKey
			message
			stackTrace
			detailDescription
		}
	}
}

query status($token: String!) {
	stat_currentversion(token: $token) {
		result
		errors {
			errorKey
			message
			stackTrace
		}
	}
}

query simple_assets($token: String!) {
	assets_search(token: $token) {
		result {
			id
		}
		errors {
			message
			errorKey
			stackTrace
		}
	}
}
```

Just the the queries for the first type referred work.

The rest of queries generate all the code correctly but return null when executing the queries.

Is it possible to have all the queries for all the types available at the API in the same file? Do I need to create a separate file for each type I want to query?

OS: Windows
Version: 11-Preview.124

Thanks in advance. This tool looks promising!!!!

**Comment by michaelstaib** [comment]
Ideally you have them all in one file. since then you can share types via fragments.

**Comment by flacidsnake** [comment]
I updated to 11--Preview.127 with the same result. Just the queries for the first type referenced work (doesn't matter if there are many or just one, all the queries for that type will work)

**Comment by michaelstaib** [comment]
Can you put up a repro?

**Comment by ic3guy** [comment]
Same thing is happening to me. I think it's because of 

public IDocument Document => Queries.Default;

Defaults to sending the entire query each time.

**Comment by michaelstaib** [comment]
The spec defines that if there are more than one operation the name must be used to choose the operation.

**Comment by michaelstaib** [comment]
http://spec.graphql.org/June2018/#GetOperation()

**Comment by michaelstaib** [comment]
Otherwise the server is not spec compliant

**Comment by michaelstaib** [comment]
What GraphQL server implementations are you guys using?
