### ISSUE TITLE
Add ArgumentAttribute?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1733]
**Is your feature request related to a problem? Please describe.**
Only way how i can get input argument is using context?
```cs
var input = context.Argument<EntityInput>("input");
```
Is there any limitation on adding an attribute?
```cs
[Argument("input")] EntityInput input
```

**Describe the solution you'd like**
Add `ArgumentAttribute(name)` or may be i missed thing how i can do it?

**Comment by PascalSenn** [comment]
Where would you like to apply this argument?

**Comment by sergeyshaykhullin** [comment]
@PascalSenn
```cs
descriptor.Field<EntityResolvers>(x => x.CreateEntity(default!, default!))
  ...

// EntityResolvers
public async Task<EntityModel> CreateEntity(
	IResolverContext context,
        [Argument("input")] EntityInput input)
{
	// var input = context.Argument<EntityInput>("input");
	...
}
```

**Comment by PascalSenn** [comment]
you do not need this attribute:
```
descriptor.Field<EntityResolvers>(x => x.CreateEntity(default!))
  ...

// EntityResolvers
public async Task<EntityModel> CreateEntity(EntityInput input)
{
        input
	...
}
```

**Comment by sergeyshaykhullin** [comment]
How does this resolves `arguments(input1: EntityInput, input2: EntityInput)`? will i get same-typed arguments in they order?

**Comment by TheJayMann** [comment]
If I'm not mistaken, it will use the name of the method argument when generating the name for the argument in the schema.  In other words, so long as you declare your method as `public async Task<EntityModel> CreateEntity(EntityInput input1, EntityInput input2)`, then it will create arguments with the names of `input1` and `input2`.  If you declare your method as `public async Task<EntityModel>CreateEntity(EntityInput baseInput, EntityInput diffInput)`, then it will create arguments with the names of `baseInput` and `diffInput`.

**Comment by sergeyshaykhullin** [comment]
I am declaring schema in code first, @TheJayMann is this about pure-code first?

**Comment by TheJayMann** [comment]
I'm not really using pure code first, I'm using code first via fluent API rather than via attributes.  However, I'm nearly certain this is an area where both fluent API and attribute style work the same way, i.e. common to both.

**Comment by sergeyshaykhullin** [comment]
@PascalSenn How does this works? Fluent api is prioritised? How HC is resolving which to use?

**Comment by PascalSenn** [comment]
@sergeyshaykhullin  It takes the code first configuration of the arguments and then adds arguments for all parameters

When you have a parameter called XYZ and you configure fluently an XYZ argument nothing will be applied
If you have a parameter XYZ and you configure fluently a ZYX argument you will have two arguments

**Comment by PascalSenn** [comment]
Gonna close this for now. Let us know if you have any more questions
