### ISSUE TITLE
Subscriptions with UseFiltering is not filtering

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1734]
**Describe the bug**
I have subscription:
```cs
descriptor.Field<EntityResolvers>(c => c.OnEntity(default!, default!))
	.Name("onEntity")
	.Type<NonNullType<EntityType>>()
	.Subscribe(async context =>
	    await context.Service<ITopicEventReceiver>()
	        .SubscribeAsync<string, OnEntityEventMessage>(nameof(OnEntityEventMessage)))
	.UseFiltering<Entity>(filtering =>
	{
		filtering.Name("OnEntityFilter");

		filtering.Filter(x => x.Property).BindFiltersImplicitly();
	})
	.UseFirstOrDefault();
```
and resolver:
```cs
public IQueryable<Entity> OnEntity(
	[Service] DatabaseContext databaseContext,
	[EventMessage] OnEntityEventMessage message)
{
	return databaseContext.Entities.Where(entity => entity.Id == message.Id);
}
```
Subscription send messages even if it is not suites for fiter:
```gql
subscription {
  onEntity(where: { property: "filtered" }) {
    property
  }
}
```
```gql
{
  "data": {
    "onEntity": {
      "property": "random"
    }
  }
}
```

**To Reproduce**
1. Create project, add mutation and subscriptions
2. Create subscription, add filter to it
3. Send mutation is not suited for filter on subscription

**Expected behavior**
HC shouldn't send subscription messages to client, if it is not suites filter

**Desktop (please complete the following information):**
- HC: 10.4.1

**Additional context**
Also, i tested without IQueryable, just using Entity as return value, i think that case should be aslo covered (If returnned Entity was filtered, do not send message event)

**Comment by vsylvestre** [comment]
Hey, I was wondering if you had eventually found a way to use filtering on subscriptions in HC? I'm having a hard time finding information on that one feature. Did you have any examples or documentation to help you set that up?

For context, the way I set up my subscription seems to be different from what you did - I think I used the pure code-first approach:

```
namespace Schema
{
    public class Subscription
    {
        [SubscribeAndResolve]
        public async ValueTask<IAsyncEnumerable<string>> EventRaised(
            [Service]ITopicEventReceiver eventReceiver,
            string input,
            CancellationToken cancellationToken) =>
            await eventReceiver.SubscribeAsync<string, string>("EventName", cancellationToken);
    }
}
```
