### ISSUE TITLE
Subscriptions - RESULT_TYPE_NOT_SUPPORTED

### ISSUE THREAD

**Issue by DrJuriko** [ChilliCream/hotchocolate#1735]
When I tried to implement Subscriptions HelloWorld based on available documentation and AspNetCore.StarWars example I got this error:
```js
{
  "errors": [
    {
      "message": "Result type not supported.",
      "extensions": {
        "code": "RESULT_TYPE_NOT_SUPPORTED"
      }
    }
  ]
}
```
**To Reproduce**
The same error I got when I used in AspNetCore.StarWars example (from master) latest 10.4.1 as follows:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>7.2</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="10.4.1" />
    <PackageReference Include="HotChocolate.AspNetCore.Subscriptions" Version="10.4.1" />
    <PackageReference Include="HotChocolate.AspNetCore.Voyager" Version="10.4.1" />
    <PackageReference Include="HotChocolate.Subscriptions.InMemory" Version="10.4.1" />
  </ItemGroup>

</Project>

```
UsePlayground I commented.

**Expected behavior**
Example should work, documentation could be more precise, especially, regarding to obsolete types… :)

**Desktop (please complete the following information):**
 - OS: Windows 10

I am not very professional with C# and .net core, therefore I try to rely to documentation and available examples.

**Comment by awonglk** [comment]
Specifically interested in Subscriptions portion of the StarWars example.. and looks like "EventMessage" used is already obsolete in 10.4.1.

_warning CS0618: 'IEventMessage' is obsolete: 'Use HotChocolate.Subscriptions.IEventStream<TMessage>.'_

Would appreciate updating the example to work with v10.4.1

**Comment by PascalSenn** [comment]
So the docs & example are indeed not up to date.
We are working on this.
In the mean time, maybe this helps?
https://github.com/ChilliCream/hotchocolate/issues/1719#issuecomment-614854264

**Comment by DrJuriko** [comment]
Thank you for your support, also I found these resources -
[blog text](https://chillicream.com/blog/2019/12/26/hotchocolate-10.3.0#subscriptions)
[blog samples](https://github.com/ChilliCream/hotchocolate-examples/tree/master/blog/2020/2020-03-24-subscriptions)

But for "2020-03-24-subscriptions" it could be great to have examples of implementation for ITopicEventReceiver/ITopicEventSender

**Comment by RehanSaeed** [comment]
Are there any examples using the Code First Fluent approach?

**Comment by michaelstaib** [comment]
I have a blog post coming up. Should be next week. The blog is going into subscriptions.

**Comment by DrJuriko** [comment]
Thank you, it would be great!

**Comment by RehanSaeed** [comment]
Is there an example I can look at for v11?
