### ISSUE TITLE
Fine grained Authorization while using EF with Querying 

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#1737]
**Domain**

 ```
public class User
    {
        public long Id { get; set; }
        public List<Post> Posts { get; set; }
    }
    public class Post
    {
        public bool IsPrivate { get; set; }
    }
```
how to assure OtherUsers can not access ones private posts ?
not just private post but any other data which is saved in database and its accessibility status will be calculated after querying from db.

**Comment by PascalSenn** [comment]
If the accessibility status will be calculated after querying the database you have to use a middleware to filter out the data. 
**IMPORTANT:** Orders matters in case of middlewares!
```csharp
public class FooType
    : ObjectType<Foo>
{
    protected override void Configure(IObjectTypeDescriptor<Foo> descriptor)
    {
        descriptor.Field(t => t.Bar)
            .UsePaging()
            .UseSelection()
            .Use(next => async context =>
            {
                await _next(context);

                if(context.Result is IQueryable<Bar> query)
                {
                    context.Result = query.DoYourMagic()
                }
            })
            .UseFiltering()
            .UseSorting();
    }
}
```
**[More info](
https://hotchocolate.io/docs/middleware#__docusaurus )**

If you are using pure code first you may also want to look into **[Descriptor Attributes](https://hotchocolate.io/docs/descriptor-attributes#__docusaurus)**. They enable you to do this
```csharp
public class Query
{
    [UsePaging]
    [UseSelection]
    [UseYourCustomerMiddlewaer]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Foo> GetFoos()
    {
        ...
    }
}

```


If you want to implement security you can use **[authorization policies](https://hotchocolate.io/docs/authorization)**

Authorization policies can also be applied AFTER the resolver is executed. This might be helpful :)
