### ISSUE TITLE
Entity Framework queries with parameters

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#1738]
**Is your feature request related to a problem? Please describe.**
**I could not determine its feature request or bug**

1-Without sql parameter our servers are just waiting to be [hacked](https://stackoverflow.com/questions/7505808/why-do-we-always-prefer-using-parameters-in-sql-statements)
2-using parameter is more [performant ](https://www.sqlshack.com/query-optimization-techniques-in-sql-server-parameter-sniffing/)

**Describe the solution you'd like**
[Building a parameterized EntityFramework Core Expression](https://stackoverflow.com/questions/54075758/building-a-parameterized-entityframework-core-expression)

**Comment by PascalSenn** [comment]
hi @aammfe   

1- Entity Framework Core will prevent SQL Injection over IQueryable
2- This could potentially be an improvement to some providers. with #1688 you can override the behaviour. 
But.. Did you actually measure it? Have you seen any noticeable performance improvements by just using parameters? Creation of an execution plan is rarely a bottleneck. What performance problems do you have? Do you have any?

**Comment by PascalSenn** [comment]
I played around a little you can check the comment in #1740

**Comment by aammfe** [comment]
> But.. Did you actually measure it? Have you seen any noticeable performance improvements by just using parameters? Creation of an execution plan is rarely a bottleneck. What performance problems do you have? Do you have any?

specifically no.
it's hard to reproduce it since like making execution plan cache full but u can simply see without using parameters execution plan is recalculated each time.

**Comment by PascalSenn** [comment]
Implemented in v11 filtering
