### ISSUE TITLE
While using Querying with EF, Where "OR" is still producing sql AND query 

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#1739]
**Describe the bug**
I'm following [this blog](https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i) 

```
(
    where:{ 
      id:2
      OR: {
      id:3
  	}})
```
is still producting AND sql query 

**To Reproduce**
1- full query

```
query {
  students (
    where:{ 
      id:2
      OR: {
      id:3
  	}})
  {
    id
  }
}
```
  
sql output 

```
SELECT "s"."Id"
      FROM "Students" AS "s"
      WHERE ("s"."Id" = 2) AND ("s"."Id" = 3)
```

**Expected behavior**

sql output 

```
SELECT "s"."Id"
      FROM "Students" AS "s"
      WHERE ("s"."Id" = 2) OR ("s"."Id" = 3)
```

**Additional context**
Hotchocolate: 10.41

**Comment by PascalSenn** [comment]
@aammfe  
Yep this is the intended behaviour 

All filters are by default concatenated with and. So when you have a filter like the one above, the criteria is bar AND baz_gt. You do not have to write the AND in this case.

for both, AND and OR you do have to provide an array value though.
You have to use it like this:

query ExampleQuery($where: FooFilter) {
   foo(where: { OR: [{bar: "asd"},{ baz_gt: 4}]}) {
      bar
      baz
   }  
}
{
    "where": { "OR": [{"bar": "asd"},{ "baz_gt": 4}]}
}
You should not write

query ExampleQuery {
   foo(where: { bar: "asd",  OR: {baz_gt: 4}) {
      bar
      baz
   }  
}
as variables

{
    "where": { "bar": "asd",  "OR": {"baz_gt": 4}}
}
