### ISSUE TITLE
stitching misses used variables in complex input types

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#1742]
**Describe the bug**
stitching of filters doesn't work with HotChocolate 10.4.1 when using variables.

**To Reproduce**
when requesting something like this from a stitched graphql schema
![image](https://user-images.githubusercontent.com/7747800/79785075-925f7b80-8343-11ea-8266-e4602842bba4.png)

the backend receives an incorrect query
![image](https://user-images.githubusercontent.com/7747800/79785199-bd49cf80-8343-11ea-8885-4bd52e2daa54.png)

**Expected behavior**
the $uid variable should be used in this query as well.

**Additional context**
the issue is in the ExtractFieldQuerySyntaxRewriter where the ExtractField only detects the $cust variable but not the $uid.

![image](https://user-images.githubusercontent.com/7747800/79785318-f7b36c80-8343-11ea-96e4-aa98a7b882dd.png)

**Comment by michaelstaib** [comment]
this was already fixed.
