### ISSUE TITLE
Single line break does not work

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1775]
Sometimes you may not want to end a paragraph but only add a linebreak.

**Current Behaviour**

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 

Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 

Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 

**Expected Behaviour**

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 

Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc. 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 

Nam rutrum ante at turpis sagittis suscipit. Mauris nec tellus condimentum, gravida ipsum ut, volutpat nunc.

**Comment by rstaib** [comment]
In my opinion we shouldn't handle line break and only think in paragraphs.

**Comment by PascalSenn** [comment]
I agree
