### ISSUE TITLE
DataLoader Documentation

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#178]
The data loader configuration has to be expanded. We especially need more documentation about error handling, null values when working with lists.

We also should create an end-to-end example that uses mongo as a database.

**Comment by drowhunter** [comment]
https://hotchocolate.io/docs/dataloaders

very end of dataloader documentation is truncated.

**Comment by michaelstaib** [comment]
@drowhunter that's unfortunate :) I will look into that
