### ISSUE TITLE
Integer Type == PaginationAmount?

### ISSUE THREAD

**Issue by MartinScha** [ChilliCream/hotchocolate#1802]
All integer properties of a class are converted into the scalar type PaginationAmount.

**I have a class:**
`public class WorkAction`
`{`
`  public string WorkActionId { get; set; }`
`  public int ImageIndex { get; set; }`
`}`

**In my Schema, i created a ObjectType:**
`public class WorkActionType`
`{`
`  protected override void Configure(IObjectTypeDescriptor<WorkAction> descriptor)`
`  {`
`    descriptor.Field t => t.WorkActionId.Type<NonNullType<IdType>>();`
`  }`
`}`

**Result:**
WorkActionId: ID!
ImageIndex: PaginationAmount

**ImageIndex should be an IntType**

Greetings to Switzerland :-)

**Comment by PascalSenn** [comment]
HI @MartinScha  
Thanks for reporting this
I think we have fixed this already in V11

If I remember correctly the problem was that the PagingType was bound earlier as the Int type.. 
Can you try to add `BindClrType` to the very top of your schema builder?

```csharp
     .AddGraphQL(
                 SchemaBuilder.New()
                .BindClrType<int, IntType>() 
                .AddQueryType<Query>()
            )
```

**Comment by michaelstaib** [comment]
This is fixed in 11. Will close the issue.
