### ISSUE TITLE
Subscriptions will not work if query sent to route ending in "/" and server is not configured on "/" ending route

### ISSUE THREAD

**Issue by hundreder** [ChilliCream/hotchocolate#1806]
**Describe the bug**
Subscription performance depends on graphql url definition. If configured url is not ending in / executing subscription from playground query will return an error.

**To Reproduce**
1. Run  StarWarz example
2. Run simple subscription query in Playground
`subscription{
  onReview(episode:EMPIRE){
    commentary
    stars
  }
}`
3. You will get and error:
`{
  "error": "Could not connect to websocket endpoint ws://localhost:5000/graphql/playground/... Please check if the endpoint url is correct."
}`

**Expected behavior**
Playground should say Listening..

**Desktop (please complete the following information):**
 - OS: WIN 10, Chrome Version 81.0.4044.122 (Official Build) (64-bit)
 - Git commit 2d724adcf2f8b45fe268ca0598bd5798b320291f

**Additional context**
Problem seems to be in combination of how url Playground in using to execute queries and how path comparation is implemented in SubscriptionMiddleware.IsValidPath method. Playground will always add **/** at the end of url. If server is configured with .UseGraphQL("/graphql"), SubscriptionMiddleware.IsValidPath will return false as "/graphql" and "/graphql/" are not equal. Interesting is that with same configuration of server url queries will executing if you send the both to /graphql and /graphql/ routes.

**Comment by sergeyshaykhullin** [comment]
I got same issue: https://github.com/ChilliCream/hotchocolate/issues/1712
Track this one: https://github.com/ChilliCream/hotchocolate/issues/1630

**Comment by michaelstaib** [comment]
Since as @sergeyshaykhullin pointed out this is a duplicate we are gonna close this one and mark it as duplicate.

**Comment by michaelstaib** [comment]
#1630
