### ISSUE TITLE
DeveloperMode option does not exist

### ISSUE THREAD

**Issue by netpoetica** [ChilliCream/hotchocolate#1813]
**Describe the bug**
In the documentation, there is a "DeveloperMode" option listened on Schema.Create. If I attempt to do this in Hot Chocolate, it does not exist in any namespace I can find: https://hotchocolate.io/docs/general-schema-options#__docusaurus

```
var schema = Schema.Create(c =>
{
    c.Options.ExecutionTimeout = TimeSpan.FromSeconds(30);
    c.Options.DeveloperMode = true;
});
```

**To Reproduce**
Paste above code in ConfigureServices method of Startup script in ASP.NET Core.

**Expected behavior**
Should be able to follow documentation as well as enable DeveloperMode.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by michaelstaib** [comment]
Hi, that is correct.

we split the options with version 9

Schema Options:
https://hotchocolate.io/docs/options

Execution Options:
https://hotchocolate.io/docs/execution-options

**Comment by michaelstaib** [comment]
Also we the Schema.Create method will be deprecated with version 11. 

In order to create a schema better use:

```csharp
SchemaBuilder.New()
    .AddQueryType....
    .ModifyOptions(o => o.....)
    .Create()
 ```
