### ISSUE TITLE
Create a Contributing.md guide for the project.

### ISSUE THREAD

**Issue by joslat** [ChilliCream/hotchocolate#1823]
Illustrate the basic points for contributing and guide a potential collaborator on an example implementation.

**Comment by joslat** [comment]
Added a Pull Request for this:
https://github.com/ChilliCream/hotchocolate/pull/1838

Can somebody check it, link it to the issue and hopefully approve-merge it? :)

**Comment by tobias-tengler** [comment]
I recently added a [contributing guide](https://github.com/ChilliCream/hotchocolate/blob/main/CONTRIBUTING.md) as part of another PR. I didn't check your closed PR prior, but now I see it contained a lot of similarities and good content.

I'm closing this issue for now, but would love to hear your feedback on the piece! :)
