### ISSUE TITLE
[Strawberry Shake]  Generated ValueSerializer for enums set values in upper case

### ISSUE THREAD

**Issue by maanwo** [ChilliCream/hotchocolate#1847]
**Describe the bug**
CodeGenerator generates the EnumValuerSerilizers in upper case while enum values in schema are not.

**To Reproduce**

Having a schema including an enum like:

enum SalutationOutput {
  Mr
  Mrs
}

Using the CodeGenerator to generate the client with a query including a SalutationOutput
is generating a SalutationOutput.cs and SalutationOutputValueSerializer.cs.
SalutationOutput is correctly generated like:

    public enum SalutationOutput
    {
        Mr,
        Mrs
    }

Both methods Serialize and Deserialize of SalutationOutputValueSerializer are generated incorrectly

        public object? Serialize(object? value)
        {
            if (value is null)
            {
                return null;
            }

            var enumValue = (SalutationOutput)value;

            switch(enumValue)
            {
                case SalutationOutput.Mr:
                    return "MR";
                case SalutationOutput.Mrs:
                    return "MRS";
                default:
                    throw new NotSupportedException();
            }
        }

        public object? Deserialize(object? serialized)
        {
            if (serialized is null)
            {
                return null;
            }

            var stringValue = (string)serialized;

            switch(stringValue)
            {
                case "MR":
                    return SalutationOutput.Mr;
                case "MRS":
                    return SalutationOutput.Mrs;
                default:
                    throw new NotSupportedException();
            }
        }

The enum values are upper case although they are not in the schema and in the SalutationOutput. 
This leads to a NotSupportedException when using the generated client.

**Expected behavior**
Both methods Serialize and Deserialize of SalutationOutputValueSerializer are generated correctly like:

        public object? Serialize(object? value)
        {
            if (value is null)
            {
                return null;
            }

            var enumValue = (SalutationOutput)value;

            switch(enumValue)
            {
                case SalutationOutput.Mr:
                    return "Mr";
                case SalutationOutput.Mrs:
                    return "Mrs";
                default:
                    throw new NotSupportedException();
            }
        }

        public object? Deserialize(object? serialized)
        {
            if (serialized is null)
            {
                return null;
            }

            var stringValue = (string)serialized;

            switch(stringValue)
            {
                case "Mr":
                    return SalutationOutput.Mr;
                case "Mrs":
                    return SalutationOutput.Mrs;
                default:
                    throw new NotSupportedException();
            }
        }

**Additional context**
Assuming the bug is in the DefaultNamingConvention in Method GetEnumValueName. It is returning value.ToString().ToUpperInvariant(). 
Maybe its either possible to remove ToUpperInvariant here or to pass an own implementation of INamingConvention  when using the ClientGenerator.

**Comment by michaelstaib** [comment]
Could you post the schema sdl?

**Comment by maanwo** [comment]
[Schema.zip](https://github.com/ChilliCream/hotchocolate/files/4597542/Schema.zip)

**Comment by maanwo** [comment]
It is a slimmed down version of the original:


[SchemaExample.txt](https://github.com/ChilliCream/hotchocolate/files/4597692/SchemaExample.txt)

**Comment by michaelstaib** [comment]
We have now completely reworked how serializes work.
