### ISSUE TITLE
[Feature request] Add ability to configure query execution strategy for pagination

### ISSUE THREAD

**Issue by AMalininHere** [ChilliCream/hotchocolate#1851]
**Is your feature request related to a problem? Please describe.**
`QueryableConnectionResolver` uses synchronous extensions of `IQueryable<T>` (e.g. `ToList()`, `Count()`) but there are a lot of cases when would be better to use asynchronous version.

**Describe the solution you'd like**
I think it would be possible to add a query execution strategy as a parameter of `QueryableConnectionResolver`. Implementation of an idea may look as follows:
```csharp
interface IQueryableExecutionStrategy
{
    Task<int> CountAsync<T>(IQueryable<T> src);
    Task<List<T>> ToListAsync<T>(IQueryable<T> src);
    // ...
}

class DefaultQueryableExecutionStrategy : IQueryableExecutionStrategy
{
    Task<int> CountAsync<T>(IQueryable<T> src) => Task.FromResult(src.Count());
    Task<List<T>> ToListAsync<T>(IQueryable<T> src) => Task.FromResult(src.ToList());
    //  ...
}

class QueryableConnectionResolver<T> : IConnectionResolver
{
    public QueryableConnectionResolver(
            IQueryable<T> source,
            PagingDetails pagingDetails,
            IQueryableExecutionStrategy executionStrategy
    )
    {
        // ...
    }

    // ...
}
```

**Comment by AMalininHere** [comment]
@PascalSenn if there is no problem with this issue, I would be happy to solve it

**Comment by PascalSenn** [comment]
Hi @AMalininHere  
Cool 👍  
I htink some interceptor, convention thing could work in this case.
We need to think how to integrate it though. we itnroduce a ton of new configuration apis and we need to investigate where to put this best so it does not feel out of place
lets see what @michaelstaib  thinks: Interceptor on schema builder or convention?

**Comment by michaelstaib** [comment]
I am at the moment working on this interface for a different reason. I will factor these things in.

**Comment by michaelstaib** [comment]
We can move on this probably end of the coming week. I will let you know ... if anybody wants to help I am happy to get you guys involved.

**Comment by michaelstaib** [comment]
This one is now implemented with the new `IPagingProvider` interface ... documentation is in the works!

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.CursorPagination/CursorPagingProvider.cs
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.CursorPagination/CursorPagingHandler.cs

**Comment by michaelstaib** [comment]
BTW ... it is also possible with 11 to reverse responsibility and let the resolver do everything.
