### ISSUE TITLE
[Spec] Spatial Data Types

### ISSUE THREAD

**Issue by John0x** [ChilliCream/hotchocolate#1878]
# Spatial Data Types
## Introduction
We should have a basic set of spatial data types built in. They can then be extended by other developers to add something like "asGeoJson" for example.

## References
- slack-channel: https://hotchocolategraphql.slack.com/archives/C0122EMLVU6
- spatial filters: https://github.com/ChilliCream/hotchocolate/issues/1747
- previous discussion: #1650 
- current progress(PR): #1870 
- geojson types: https://medium.com/@sumit.arora/what-is-geojson-geojson-basics-visualize-geojson-open-geojson-using-qgis-open-geojson-3432039e336d
- geojson spec: https://tools.ietf.org/html/rfc7946

## Proposal
All proposed types are open for discussion.
```graphql
input CoordinateInput {
    x: Int!
    y: Int!
}

type Coordinate {
    x: Int!
    y: Int!
}
"----------------------------------------------------------------"
input PointInput {
  srid: Int
  coordinate: CoordinateInput!
}

type Point {
  srid: Int!
  coordinate: Coordinate!
}
"----------------------------------------------------------------"
input LineStringInput {
  srid: Int
  coordinates: [CoordinateInput!]!
}

type LineString {
  srid: Int!
  coordinates: [Coordinate!]!
}
"----------------------------------------------------------------"
input PolygonInput {
  srid: Int
  coordinates: [[CoordinateInput!]]!
}

type Polygon {
  srid: Int!
  coordinates: [[Coordinate!]]!
}
"----------------------------------------------------------------"
input MultiPointInput {
  srid: Int
  coordinates: [CoordinateInput!]!
}

type MultiPoint {
  srid: Int!
  coordinates: [Coordinate!]!
}
"----------------------------------------------------------------"
input MultiLineStringInput {
  srid: Int
  coordinates: [[CoordinateInput!]]!
}

type MultiLineString {
  srid: Int!
  coordinates: [[Coordinate!]]!
}
"----------------------------------------------------------------"
input MultiPolygonInput {
  srid: Int
  coordinates: [[[CoordinateInput!]]]!
}

type MultiPolygon {
  srid: Int!
  coordinates: [[[Coordinate!]]]!
}

```

This would almost be like GeoJson:
https://medium.com/@sumit.arora/what-is-geojson-geojson-basics-visualize-geojson-open-geojson-using-qgis-open-geojson-3432039e336d

**Comment by steveoh** [comment]
Should this have been closed with #1870
