### ISSUE TITLE
Authorize directive on InputObjectTypes

### ISSUE THREAD

**Issue by bogdancice** [ChilliCream/hotchocolate#1879]
**The problem**
Hi,
We are currently using [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) on our project and we are thinking of migrating to HotChocolate. 

I'm having a hard time figuring out how to add authorization on Input Models. From what I see the AuthorizeDirective is not supported on IInputObjectTypeDescriptor. This authorization is useful when I want to use the same mutation for users with different permissions or roles.

For example if I have the following Input Model, in which a normal user (without any special permission) can update the name of an account and also a user that is SuperAdmin can update SensitiveData regarding the account.

```    
public class AccountInputType : InputObjectType<Account>
    {
        protected override void Configure(IInputObjectTypeDescriptor<Account> descriptor)
        {
            descriptor.Name("account input");
            descriptor.Description("create or update account");
            descriptor.BindFieldsExplicitly();
            descriptor.Field(a => a.Name);
            descriptor.Field(a => a.SensitiveData).Directive(new AuthorizeDirective("SUPER_ADMIN"));
        }
    }
```

but at runtime the following error appears
```
System.InvalidCastException: Unable to cast object of type 'HotChocolate.Types.ObjectType`1[HotChocolate.AspNetCore.Authorization.AuthorizeDirective]' to type 'HotChocolate.Types.DirectiveType'.
   at HotChocolate.Configuration.CompletionContext.GetDirectiveType(IDirectiveReference reference)
   at HotChocolate.Types.DirectiveCollection.TryCompleteDirective(ICompletionContext context, DirectiveDefinition definition, ISet`1 processed, Directive& directive)
   at HotChocolate.Types.DirectiveCollection.CompleteCollection(ICompletionContext context)
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.InputField.OnCompleteField(ICompletionContext context, InputFieldDefinition definition)...
```

I checked also the Authorize extension in AuthorizeObjectFieldDescriptorExtensions.cs and it's pretty clear that it is not implemented for InputObjectType. I'm missing something here or this is currently not supported?

**The solution I would like**
I would like to be able to use Authorization on any field defined on an  InputObjectType. Maybe this is possible but I was unable to find the solution for this, if someone knows how to do it a simple example would be greatly appreciated

**Alternatives I've considered**
An alternative to my issue would be to have multiple mutations, one mutation for each authorization check that I want to do based on user permissions. But in our project this will imply to have a lot of multiplied mutations that are doing the same thing, saving a new object in the database. We don't see this as a scalable solution because it will imply a lot of duplicated code for some entities in our project, we have entities that have fields authorized by 4 different permissions (each field with his own permission)

**Additional context**
This is currently possible in [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet)
Example: 
```
  public class CustomerCreateViewModel : InputObjectGraphType<Customer>
    {
        public CustomerCreateViewModel()
        {
            Field(x => x.CustomerName, false).Description("Name of the customer. Max 255 characters");
            Field(x => x.DefaultRevShare, true)
                .AuthorizeWith(Permission.RevenueManagement.ToString())
                .Description("Default revenue share for newly created players. Integer Min: 0, Max: 100")
            Field(x => x.ServingFee, true)
                .AuthorizeWith(Permission.RevenueManagement.ToString())
                .Description(
                    "Serving fee to be applied if the amount of Creatives served from Connatix in all sessions " +
                    "is lower than the Threshold. Decimal (5,2)")
                .DeprecationReason("Use Revenues.ServingFee instead");
            Field(x => x.AdsTxtIdent, true).Description("Ads.txt unique identifier")
                .AuthorizeWith(Permission.EditAdsTxt.ToString());
            Field(x => x.PublisherAdsTxtIdent, true).Description("Publisher's ads.txt unique identifier")
                .AuthorizeWith(Permission.EditAdsTxt.ToString());
        }
    } 
```

My question would be if this is on the road map or if you have any other alternatives on how can we implement this? Thanks for you're time

**Comment by michaelstaib** [comment]
In GraphQL inputs represent raw data and are not meant to cary functionality. Who would you prevent and input. You can however authorize fields since on fields you can apply logic.

The way this works in Hot Chocolate is that we use Microsofts authorization policies. You can create policies that would authorize the field and apply depending the input access or not.

As far as I know graphql-dotnet has a fundamentally different approach and the authorization in their case is based on validations. In out case it is base on directive middleware.

So if you want to apply this on the inputs still you could use directives or context data and write up a policy that applies these.

https://hotchocolate.io/docs/authorization

Within the policy you have fill access to the inputs of the resolver. So it would be quite simple to check for context data on the input argument through the resolver context.

```csharp
public class SalesDepartmentAuthorizationHandler
    :  AuthorizationHandler<SalesDepartmentRequirement, Document>
{
    protected override Task HandleRequirementAsync(
        AuthorizationHandlerContext context,
        SalesDepartmentRequirement requirement,
        IResolverContext resource)
    {
        if (context.User.HasClaim(...))
        {
            context.Succeed(requirement);
        }

        return Task.CompletedTask;
    }
}
```

> An alternative to my issue would be to have multiple mutations, one mutation for each authorization check that I want to do based on user permissions

Just as a side note. The GraphQL schema design guidlines from facebook, github or shopify would suggest that you should have very specific mutations on which you apply these rules. There is a very good talk on this by marc-andre from github.

https://www.youtube.com/watch?v=pJamhW2xPYw

Regarding roadmap, we have a lot planned for authorization. Although your question was asked before I am still not convinced that it is worth to standardize it since validation logic should either reside in the business logic or in policies on fields where you could implement such a behavior. This also adds too testability since you know can test the policy separate from the actual service layer and also can you swap in testing policies to the field.

I hope the pointer to the policies helps. Also I have tagged this issues as discussion since I am interested on thoughts of the community on this.

@PascalSenn, @rstaib any thoughts?

**Comment by michaelstaib** [comment]
Interesting, just saw that graphql-dotnet also has a authorization policy approach nowadays:
https://github.com/graphql-dotnet/authorization

@PascalSenn did you work with that when you worked with graphql-dotnet?

**Comment by bogdancice** [comment]
@michaelstaib thanks a lot for the quick response. We will check out the authorization handler

**Comment by PascalSenn** [comment]
@michaelstaib  no we did not use this

**Comment by willwolfram18** [comment]
Just mentioning that this issue has a duplicate #744

**Comment by benmccallum** [comment]
> Interesting, just saw that graphql-dotnet also has a authorization policy approach nowadays:
> https://github.com/graphql-dotnet/authorization

FYI, the one I was using was actually in the server project, which is an asp.net core only implementation that doesn't need to deal with legacy. https://github.com/graphql-dotnet/server/tree/develop/src/Authorization.AspNetCore

**Comment by gerneio** [comment]
Confused on why this was marked as completed when it looks like `InputObject`/`InputFieldDefinition` are still not supported with the `@authorize` directive (at least on latest HC 13).

```
The specified directive `@authorize` is not allowed on the current location `InputObject`
The specified directive `@authorize` is not allowed on the current location `InputFieldDefinition`
```

If that was the ultimate conclusion (not supported), that's fine, but seeing this marked as completed with no other linked discussions or commit references makes it confusing to understand whether this should actually be working or not. In my case, I want to take the built-in input types for filtering & sorting and perform additional authorization checks. Atm the workaround seems to be to add the auth directive to the field (i.e. `Query.customers`) that is exposing the input and do my checks under that layer (can get metadata via `GetFilterContext()` & `GetSortingContext()` in my case), but also means there are some holes if I forget to add that implementation under other fields that use the same input type and should therefore be doing the same auth checks.

Ultimately just looking for clarification on the state of support of auth directives w/ `InputObject`, that's all.
