### ISSUE TITLE
Unable to convert type from `List`1` to `List`1`

### ISSUE THREAD

**Issue by stanipintjuk** [ChilliCream/hotchocolate#1884]
Hello I am new to this framework so I might be missing something obvious.

I have a simple object `User` with a list of tracked groups `List<Group>`
This is what they look like

User.cs
```
public class User {
      public string UserName { get; set; }

      public List<Group> TrackedGroups { get; set; }
}
```

Group.cs
```
 public class Group {
      public string Name { get; set; }
      public List<string> Sites { get; set; }
}
```

And here are their input types, respectivly
```
   public class CreateUserInputType: InputObjectType<CreateUserInput>
   {
      protected override void Configure(IInputObjectTypeDescriptor<CreateUserInput> descriptor)
      {
         base.Configure(descriptor);
         descriptor.Field(a => a.UserName)
            .Type<NonNullType<StringType>>();
         descriptor.Field(a => a.TrackedGroups)
            .Type<ListType<CreateGroupInputType>>();
      }
   }
```

```
   public class CreateGroupInputType: InputObjectType<CreateGroupInput>
   {
      protected override void Configure(IInputObjectTypeDescriptor<CreateGroupInput> descriptor)
      {
         base.Configure(descriptor);

         descriptor.Field(a => a.Name)
            .Type<NonNullType<StringType>>();
         descriptor.Field(a => a.Sites)
            .Type<ListType<StringType>>();
      }
   }
```

so when I run the following mutation in graphiql:
```
mutation {
  updateUser(userId: "5eb2a55641d8fe3edaeff54e",
    user: {
      userName: "Test",
      trackedGroups: [
        {
          name: "test.com",
        }
      ]
    }
  )
}
```

I get the following runtime exception:
```
Unable to convert type from `List`1` to `List`1`
```

Thank you in advance

**Comment by michaelstaib** [comment]
Which version are you on?

**Comment by stanipintjuk** [comment]
HotChocolate.AspNetCore Version 10.4.2

**Comment by TheJayMann** [comment]
Briefly looking at the code you provided, you have the `TrackedGroups` property as a List<Group>, while you configure the property to be of `CreateGroupInput`.  I'm not sure the relationship between `CreateGroupInput`, but, even if `CreateGroupInput` derives from Group, classes are not able to be made covariant.  If a `List<CreateGroupInput>` is being created, then attempted to be assigned to a property of type `List<Group>`, this cannot work, as you cannot cast from one type to the other.  I'd imagine the error list should actually be saying something along the lines of ``Unable to convert type from `List`1[CreateGroupInput]` to `List`1[Group]`​``. 

If my assumptions are correct, a way to fix this would be to use a covariant interface.  Typing the property as `IEnumerable<Group>` would work in this case, as it is covariant, but `ICollection<Group>` and `IList<Group>` would not.

**Comment by michaelstaib** [comment]
@TheJayMann that is right. In this case you have to provide a converter. But the converter should actually have a better message with the full type name in a readable manner. I will look into making the error message better. As always @TheJayMann is eagle eyed :)

**Comment by stanipintjuk** [comment]
Hello, and sorry for my delayed response. Didn't get the opportunity to test this during the weekend.

I changed the type of `TrackedGroups` to `IEnumerable<Group>` but get an almost identical error: ``Unable to convert type from `List`1` to `IEnumerable`1` ``
based on what @TheJayMann said I assume that the exception means `` Unable to convert type from `List`1[CreateGroupInput]` to `IEnumerable`1[Group]` `` but HotChocolate still can't automatically convert the types.

Maybe I need to write a custom type converter for this anyway?

**Comment by stanipintjuk** [comment]
I'm not sure about that.

I tried adding these lines to my Startup

```
services.AddTypeConverter<List<Group>, IEnumerable<Group>>(from => from);
services.AddTypeConverter<IEnumerable<Group>, List<Group>>(from => from.ToList());

services.AddTypeConverter<List<CreateGroupInputType>, IEnumerable<CreateGroupInputType>>(from => from);
services.AddTypeConverter<IEnumerable<CreateGroupInputType>, List<CreateGroupInputType>>(from => from.ToList());
```

But the issue remains.

**Comment by TheJayMann** [comment]
Does `CreateGroupInput` derive from `Group`? I.e., do you have the code as follows.
```csharp
class CreateGroupInput : Group {
}
```
This is required in order to convert `List<CreateGroupInput>` to `IEnumerable<Group>`.  If it is the case that `CreateGroupInput` does derive from group, and this error still occurs, I'm at a loss as to why.

In the case the above doesn't work, or in the case that `CreateGroupInput` does not derive from `Group`, that would be the need for specifying a converter.  However, I believe the conversion necessary is between `CreateGroupInput` and `Group`.  You would probably need code similar to `services.AddTypeConverter<CreateGroupInput, Group>(gInput => new Group(){ /* initialize properties from gInput */ }`.  I think this is what is needed, but I cannot be certain as I have not used this feature myself.

**Comment by stanipintjuk** [comment]
Thanks for the input,

however yes `CreateGroupInput` is derived from `Group` and is implemented in the exact same way as it is in your comment.

And for some reason the type converter didn't do it in this case either.

Though I played around some more and noticed that changing the inheritence of `CreateGroupInputType: InputObjectType<CreateGroupInput>` to `CreateGroupInputType: InputObjectType<Group>` did it.

After the change the api works as expected.

Thanks for all the help! :)
