### ISSUE TITLE
Strawberry shake creates multiple interfaces for same interface

### ISSUE THREAD

**Issue by mhomde** [ChilliCream/hotchocolate#1919]
Strawberry shake generates one interface per class that implements it, so you end up with IMyClass, IMyClass1 etc.

Seems it should be able to collapse identical files/interfaces into one, otherwise you can't use it  across classes

**Comment by michaelstaib** [comment]
This depends on how you structure your queries. Strawberry Shake is built around the concept of fragments, meaning that by using fragments your are defining the structure of your c# types.


```graphql
{
   person(id:1) {
        ... personInfo
   }
}

# will result in the type IPersonInfo
fragment PersonInfo on Person { 
    name
}
```

**Comment by mhomde** [comment]
Hmm, yeah, but wouldn't you want to merge identical interfaces anyhow? or even have have the option of using one interface even if not every query contains all fields? 

Or maybe I'm not understanding something :)

**Comment by michaelstaib** [comment]
Not really, since the contract would no longer be clear. If you even think further with nullable ref types which we already support for strawberry shake you would need to generate all props that are not always fetched nullable, forcing you to write null checks for non-nullable fields.

Also if take into account things like `@defer` where you defer parts of data on the fragment this would not work with single interfaces.

```graphql
{
   feed(id:1) {
        news
        ... Comments
   }
}

fragment Comments on story @defer(label: "Comments") { 
    comment
}
```

Also types often do not line up like in the query, with the next update we will allow to flatten objects.

```graphql
{
   person(id:1) {
        ... personInfo
   }
}

fragment PersonInfo on Person { 
    ... PersonName
    nodes @spread {
        friends {
            ... PersonName
        }
    }
}

fragment PersonName on Person {
   name
}
```

Leads to:

```csharp
public interface IPerson : IPersonName
{
     IReadOnlyList<IPersonName> Friends { get; }
}

public interface IPersonName
{
     string Name { get; }
}
```

**Comment by mhomde** [comment]
Hmm, I understand tricky. Lots of edge cases.  Though I still not quite understand why interfaces that are identical couldn't be merged.

I mean it must be a quite common scenario where you have bunch of queries against the same interface (on the the server side), query the same fields, but vary other things like where clauses and want to be able to treat them as that server-side interface. 

If merging is not good for some reason maybe some other syntax to mark them as same interface.

I'm not completely sold on not being able to have a "larger interface", so even if the query just returns two out of five fields it can still fulfill the interface as long the others are not non-nullable.  I 

I mean, null-checks is how we normally handle things :)

Hard to reconcile with all other features perhaps but would be great to be able to support it somehow. Otherwise you'd have to refactor your generated code on each update. 

Perhaps you could even in the query syntax indicate that the resulting objects should implement an additional interface by name, without type-checking it , and it's up to the developer to shape that interface

**Comment by michaelstaib** [comment]
But you have syntax for that .... fragments. Strawberry Shake is a fragment base client like relay and others. It is very powerful to shape your classes with that.

Maybe you could give a more detailed use-case for your scenario. Can you post a query document and show how that translates and how you would like it to translate?

**Comment by mhomde** [comment]
You might be right :) I'm going to make sure I understand all of this thoroughly and make some tests with my scenario. Get back to you!
