### ISSUE TITLE
Filter inference bug

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#1927]
HotChocolate 10.4.3

The below code breaks filtering, as it cannot correctly infer the FilterType and uses an empty ObjectFilter instead.

```{"errors":[{"message":"The variable `filter` type is not compatible with the type of the argument `where`.\r\nExpected type: `ObjectFilter`.","locations":[{"line":2,"column":65},{"line":1,"column":56}]}]}```

```
descriptor.Field("conversations")
                .Type<ListType<ConversationType>>()
                .Argument("brandIds", i => { i.Type<ListType<IdType>>(); })
                .Resolver(async ctx =>
                {   
                    var dbContext = ctx.Service<DbContext>();
                    var queryable = dbContext.Conversations.AsNoTracking();
                    _(simplified)_
                    return queryable;
                })
                .UsePaging<ConversationType>()
                .UseFiltering()
                .UseSorting<ConversationSortType>();

```

Current workarounds that resolves the error:
- Using a non-async resolver method
or
- Creating a custom FilterType (which does nothing else than `descriptor.BindFieldsImplicitly();`)

**Comment by hognevevle** [comment]
It seems to also break sorting inference, however I didn't experience this because I already had a custom sorting type. Disabling that and doing just `.UseSorting() throws the following exception when starting the application:

```Unhandled exception. HotChocolate.SchemaException: InputObject `ObjectSort` has no fields declared. - Type: ObjectSort
   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
```

**Comment by michaelstaib** [comment]
I think you are missing a using ... since most of the resolver methods are extension methods.

**Comment by hognevevle** [comment]
Hmm. Which "using" could that be? 

Also want to mention that I was originally on 10.3.5 when I first encountered this. (I've since upgraded to 10.4.3.)

I'll try to piece together a repro.

**Comment by PascalSenn** [comment]
that would be *using HotChocolate.Types;*

**Comment by hognevevle** [comment]
I see, unfortunately I already have that one.

```
using HotChocolate;
using HotChocolate.Execution;
using HotChocolate.Types;
using HotChocolate.Types.Relay;
(plus some other non-HC ones)
```

**Comment by michaelstaib** [comment]
This could actually be.... It might be that we only look at `IQueryable` if it is not async since usually an `IQueryable` would not be returned by an async resolver. I will have a look.

**Comment by PascalSenn** [comment]
I added a test for this in #3375 
I could not reproduce this behaviour in v11 and HotChocolate.Data.
