### ISSUE TITLE
Options not applied using persisted queries

### ISSUE THREAD

**Issue by albertofojo** [ChilliCream/hotchocolate#1935]
**Describe the bug**
I am not able to apply 

`IQueryExecutionOptionsAccessor`

 using         

`public static IServiceCollection AddGraphQL(this IServiceCollection services, Func<IServiceProvider, ISchema> schemaFactory, Action<IQueryExecutionBuilder> build);`

**To Reproduce**
1. Configure the services:

```
 public static IServiceCollection AddGatewayGraphQLWithPersistedQueries(this IServiceCollection services, IQueryExecutionOptionsAccessor options)
        {
            services.AddGraphQL(
                    schemaFactory: GetSchema,
                    queryExecutionBuilder =>
                        queryExecutionBuilder
                            .UsePersistedQueryPipeline()
                            .AddSha256DocumentHashProvider(HashFormat.Hex)
                            // WARNING: this options will be not applied, bug?
                            .AddOptions(options)
                         );

            return services.AddFileSystemQueryStorage("./queries");
        }
```

2. Try any query.

**Expected behavior**
Options is not applied

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 19.04

**Additional context**
Using Visual Studio Code with docker

**Comment by michaelstaib** [comment]
The api here is not ideal we have that on our list.... so instead of doing AddOptions do UsePersistedQueryPipeline(options)

**Comment by albertofojo** [comment]
I's working fine doing that way. 
Thank you!
