### ISSUE TITLE
Strawberry Shake ignoring schema extension for a custom scalar

### ISSUE THREAD

**Issue by El-Gor-do** [ChilliCream/hotchocolate#1942]
**Describe the bug**
I am trying to follow https://chillicream.com/blog/2019/11/25/strawberry-shake_2 to create a .Net Standard GraphQL client to share with my applications. My query returns a custom type that contains a Guid property. StrawberryShake generates this property as a string type instead of Guid type.

**To Reproduce**
I am using HotChocolate 10.4.3, HotChocolate.AspNetCore 10.4.3 and StrawberryShake 11.0.0-preview.130.

In my CustomScalarsWebApi project I have the following types
```
using System;

namespace CustomScalarsWebApi.Models
{
    public class MyClass
    {
        public Guid Id { get; set; }
    }
}
```
```
using CustomScalarsWebApi.Models;
using HotChocolate.Types;

namespace CustomScalarsWebApi.GraphQLTypes
{
    public class MyClassType : ObjectType<MyClass>
    {
        protected override void Configure(IObjectTypeDescriptor<MyClass> descriptor)
        {
            descriptor.Field(f => f.Id).Type<NonNullType<IdType>>();
        }
    }
}
```
```
using HotChocolate.Types;

namespace CustomScalarsWebApi.GraphQLTypes
{
    public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor
                .Name("myClass")
                .Field(q => q.GetMyClass())
                .Type<NonNullType<MyClassType>>();
        }
    }
}
```
```
using System;
using CustomScalarsWebApi.Models;

namespace CustomScalarsWebApi.GraphQLTypes
{
    public class Query
    {
        public MyClass GetMyClass()
        {
            return new MyClass()
            {
                Id = Guid.NewGuid(),
            };
        }
    }
}
```
```
using System;
using HotChocolate;

namespace CustomScalarsWebApi.GraphQLTypes
{
    public static class RootSchema
    {
        public static ISchema Create(IServiceProvider provider)
        {
            ISchemaBuilder builder = SchemaBuilder.New()
                                        .AddServices(provider)
                                        .AddQueryType<QueryType>()
                                        ;

            ISchema schema = builder.Create();
            return schema;
        }
    }
}
```

The downloaded schema is
```
schema {
  query: myClass
}

type myClass {
  myClass: MyClass!
}

"The multiplier path scalar represents a valid GraphQL multiplier path string."
scalar MultiplierPath

type MyClass {
  id: ID!
}

"The cost directives is used to express the complexity of a field."
directive @cost("Defines the complexity of the field." complexity: Int! = 1 "Defines field arguments that act as complexity multipliers." multipliers: [MultiplierPath!]) on FIELD_DEFINITION
```

In my CustomScalarsClient project I have created SchemaExtensions.graphql
```
extend scalar ID
    @runtimeType(name: "System.Guid")
    @serializationType(name: "System.String")
```
and Queries.graphql
```
query getMyClass
{
    myClass
    {
        id
    }
}
```
In my CustomScalarsClient .Net Standard project I have also created IdValueSerializer but it's not clear what I'm supposed to do with this serializer - there's no service provider to register it.
```
using System;
using StrawberryShake;
using StrawberryShake.Serializers;

namespace CustomScalarsClient.ValueSerializers
{
    public class IdValueSerializer : ValueSerializerBase<Guid, string>
    {
        public override string Name => "ID";
        public override ValueKind Kind => ValueKind.String;

        public override object Deserialize(object serialized)
        {
            if (serialized is null)
                return null;

            if (serialized is string s)
                return new Guid(s);

            throw new ArgumentException($"The specified value is of an invalid type. {SerializationType.FullName} was expeceted.");
        }

        public override object Serialize(object value)
        {
            if (value is null)
                return null;

            if (value is Guid g)
                return g.ToString();

            throw new ArgumentException(
                $"The specified value is of an invalid type. {ClrType.FullName} was expeceted.");
        }
    }
}
```

When I build my client project, the autogenerated IMyClass.cs is
```
namespace CustomScalarsClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public partial interface IMyClass
    {
        string Id { get; }
    }
}
```

**Expected behavior**
I expected IMyClass.Id to be a Guid type rather than a string type.
```
namespace CustomScalarsClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public partial interface IMyClass
    {
        System.Guid Id { get; }
    }
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.18363.836

**Additional context**
I suspect I am just not using StrawberryShake correctly but I also can't tell if this is a bug or not.

**Comment by michaelstaib** [comment]
The ID Scalar is as spec scalar and cannot be overridden since the behavior, serialization and runtime manifestation is specified in the spec. With the spec definition of ID it cannot be guaranteed that ID is always a GUID.

**Comment by El-Gor-do** [comment]
The problem I am encountering is not just with ID type. In my real project I am using NodaTime.Duration and NodaTime.Instant . In my examples above, if you change MyClass.Id's type to NodaTime.Duration or NodaTime.Instant, the downloaded schema becomes
```
type MyClass {
  id: Duration!
}
```
and change SchemaExtensions.graphql to
```
extend scalar Duration
    @runtimeType(name: "NodaTime.Duration")
    @serializationType(name: "System.String")
```
the generated IMyClass interface still has the property type as string instead of NodaTime.Duration.

My question isn't specifically about Guid and NodaTime types but rather, in general, how do I tell the code generator which runtime type to use for a custom scalar property?

**Comment by El-Gor-do** [comment]
I'm only just starting out with GraphQL so I'm not familiar with its peculiarities but in what way does the spec definition of ID not guarantee that it will be a Guid? MyClass.Id is defined as a Guid type so I can't see how it's possible for Id to not be a valid Guid.

**Comment by michaelstaib** [comment]
> With the spec definition of ID it **CANNOT** be guaranteed that ID is always a GUID.

**Comment by michaelstaib** [comment]
Can you create a repro of your issue with the `Duration`?

**Comment by El-Gor-do** [comment]
[StrawberryShakeCustomScalars.zip](https://github.com/ChilliCream/hotchocolate/files/4643947/StrawberryShakeCustomScalars.zip)

Attached is a repro solution with Id, NodaTime.Duration and NodaTime.Instant.

- CustomScalarsWebApi\MyClass.cs defines Guid, Duration and Instant properties.
- CustomScalarsWebApi\GraphQLTypes\MyClassType.cs defines the mapping to a GraphQL type.
- CustomScalarsWebApi\GraphQLTypes\Query.cs function GetMyClass() is the resolver returning a MyClass object.
- CustomScalarsClient\Queries.graphql defines the query that I want to run.
- CustomScalarsClient\SchemaExtensions.graphql defines the serialization for ID, Duration and Instant.
- CustomScalarsClient\Generated\IMyClass.cs has my 3 properties all as string type instead of Guid, NodaTime.Duration and NodaTime.Instant.

What I am trying to make the generator output for IMyClass.cs is
```
using System;
using System.Collections;
using System.Collections.Generic;
using StrawberryShake;

namespace CustomScalarsClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public partial interface IMyClass
    {
        System.Guid Id { get; }

        NodaTime.Duration DurationValue { get; }

        NodaTime.Instant InstantValue { get; }
    }
}
```


> > With the spec definition of ID it **CANNOT** be guaranteed that ID is always a GUID.

I don't understand this. How can ID not be guaranteed to be a Guid when MyClass.cs has defined ```public Guid Id { get; set; }``` ? I understand that Id will be serialised as a string in the GraphQL output but I want the client to deserialise Id as a Guid because the value can only ever be a Guid-formatted string, not any randomly formatted string.

**Comment by Alxandr** [comment]
> I want the client to deserialise Id as a Guid because the value can only ever be a Guid-formatted string, not any randomly formatted string.

**Comment by El-Gor-do** [comment]
> Then make a Guid scalar. 

This is what I am trying to demonstrate with my attached repro. I want Strawberry Shake to generate IMyClass.Id/DurationValue/InstantValue properties as the types defined in my SchemaExtensions.graphql file but the generator always generates these properties as string. How do I configure Strawberry Shake to use the schema extensions? I have not been able to find any working samples demonstrating this.

>  The GQL builtin ID is defined as allowing any string/number. Your client would not be conformant if it threw on it not being a Guid. Though it's mostly pedantic IMHO.

GraphQL's ID type is defined as allowing any string/number but surely it can only return what I specify in MyClass, which is a Guid. The whole point of making IMyClass.Id a Guid is to enforce that the client can never pass an Id string that is not a valid Guid rather than allowing a user to pass an Id "abc" then throwing because it's not a valid Guid.

**Comment by Alxandr** [comment]
If you're talking about inputs, you will have to handle that, because your server is (by contract) saying that it accepts any ID. For outputs though, yes, you control the ID. Basically, you can never control clients.

**Comment by El-Gor-do** [comment]
Alxandr have you tried my attached repro? As I mentioned above, I have been trying to make Strawberry Shake generate IMyClass.cs as

```
using System;
using System.Collections;
using System.Collections.Generic;
using StrawberryShake;

namespace CustomScalarsClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public partial interface IMyClass
    {
        System.Guid Id { get; }

        NodaTime.Duration DurationValue { get; }

        NodaTime.Instant InstantValue { get; }
    }
}
```

but what is actually generated is

```
using System;
using System.Collections;
using System.Collections.Generic;
using StrawberryShake;

namespace CustomScalarsClient
{
    [System.CodeDom.Compiler.GeneratedCode("StrawberryShake", "11.0.0")]
    public partial interface IMyClass
    {
        string Id { get; }

        string DurationValue { get; }

        string InstantValue { get; }
    }
}
```

Based on the discussion so far, you can ignore the Id property, but the NodaTime.Duration and NodaTime.Instant properties are still incorrectly generated as string types. Your suggestion to make Guid a custom scalar is exactly what I have been trying to do with Duration and Instant but there is no documentation on how to achieve this. So what I have been asking all along is whether this behaviour is by design or if the blog post documentation is obsolete.

**Comment by Alxandr** [comment]
@El-Gor-do as far as I know, you can't currently achieve that. Only some of the builtin types (`System.Int32` and friends) work. At least that was the case a few months ago. They're working on a new generator that will unblock this though.

**Comment by El-Gor-do** [comment]
https://chillicream.com/blog/2019/11/25/strawberry-shake_2#custom-scalars says to use a schema extensions graphql file and a custom value serializer to specify custom scalars should be deserialised. This is what my repro tries and fails to do with Duration/Instant. If I can't get this working with Duration/Instant then I don't see how it would be possible to create a custom Guid scalar either.

@michaelstaib it would be helpful to know if this behaviour is by design, a bug or work in progress. As it stands, the current implementation of Strawberry Shake does not meet its stated goal of providing a strongly-typed API and I'm finding it completely unusable compared to writing my own wrapper on top of GraphQL.Client, which is a shame for Strawberry Shake.

**Comment by Alxandr** [comment]
@El-Gor-do because Guid is part of the core framework. Instant/Duration is a custom type you brought along (that strawberry shake doesn't know about).

**Comment by El-Gor-do** [comment]
> Instant/Duration is a custom type you brought along (that strawberry shake doesn't know about).

How does Strawberry Shake not know about these custom types when I've defined them in the schema extensions and provided custom value serializers?

**Comment by Alxandr** [comment]
Cause it has no idea what DLLs to load. At least that was my understanding of the issue. It's a component running compile time, and apparently it does some type checking or something? I'm not sure. @michaelstaib told me about it on slack a good while ago. And that it was going to be fixed with the new code generator they're working on.

**Comment by zmhh** [comment]
+1

**Comment by michaelstaib** [comment]
We will soon shift attention back to strawberry shake once hot chocolate 11 is out.

**Comment by michaelstaib** [comment]
We have now introduced the new code generation and I will close this issue .... we will follow up with blogs and docs over the weekend.

**Comment by mazaycheck** [comment]
Hi, im using 12.15 version, and here is a minimal repro:

schema.graphql: 

`schema {
  query: Query
  mutation: Mutation
}

type Query {
  users: [User!]!
  user(id: ID!): User!
}

type User {
  id: ID!
  name: String!
  email: String!
  age: Int
  gender: gender
}

enum gender {
  Male
  Female
}

type Mutation {
  createUser(id: ID! name: String! email: String! age: Int gender: gender!): User!
  updateUser(id: ID! name: String email: String age: Int): User!
  deleteUser(id: ID!): User!
}

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

"The `Upload` scalar type represents a file upload."
scalar Upload

directive @cacheControl(maxAge: Int scope: CacheControlScope) on FIELD_DEFINITION | OBJECT | INTERFACE`


mutation.graphql

`mutation CreateUser($id: ID! $name: String! $age: Int $email: String!  $gender: gender!) {
  createUser(id: $id, name: $name, age: $age, email: $email, gender: $gender){
    id,
    name,
    age,
    gender
  }
}`

Generating a client will fail with : Sequence contains no matching element error
