### ISSUE TITLE
Using enums directly in parameter lists

### ISSUE THREAD

**Issue by gregsdennis** [ChilliCream/hotchocolate#1960]
**Describe the bug**
Enum values cannot be used in a parameter list directly.  They must be incorporated into a variable.

**To Reproduce**
This doesn't work
```
query {
  numbersBelow100 (filter: "ODD") {  # "filter" param is of type "NumberFilter" which is an enum
    ...
  }
}
```
This returns an error about the value being a `String` and not a `NumberFilter`.

You have to pass it in through a variable.
```
query ($filter: NumberFilter) {
  numbersBelow100 (filter: $filter) {
    ...
  }
}

# variables
{
  "filter": "ODD"
}
```

**Expected behavior**
I would expect the first case to work so long as the value is a valid member of the enum.

**Desktop (please complete the following information):**
 - Version: 10.4.1

**Comment by PascalSenn** [comment]
@gregsdennis 

You get this error message because the value is a string and not a NumberFilter. 
Try this:
```csharp
query {
  numbersBelow100 (filter: ODD) {  # "filter" param is of type "NumberFilter" which is an enum
    ...
  }
}
```

**Comment by gregsdennis** [comment]
Thank you.  I expected enums to be represented as strings in GQL.  This feels... odd. ;)
