### ISSUE TITLE
Using [GraphQLNonNullType] Attribute on Non-String Scalars Breaks Filtering

### ISSUE THREAD

**Issue by albanfellows** [ChilliCream/hotchocolate#1961]
Given the following GraphQL Query and backing type
```
public class QueryType 
{
    [UseFiltering]
    public IEnumerable<TestObject> TestGet()
    {
        yield return new TestObject { Id = 1, Name = "Test 1" };
        yield return new TestObject { Id = 2, Name = "Test 2" };
        yield return new TestObject { Id = 3, Name = "Test 3" };
        yield return new TestObject { Id = 4, Name = "Fourth Test" };
        yield return new TestObject { Id = 5, Name = "Fifth Test" };
        yield return new TestObject { Id = 6, Name = "Sixth Test" };
        yield return new TestObject { Id = 7, Name = "More Tests" };
    }
}

public class TestObject
{
    [GraphQLNonNullType] public int? Id { get; set; }
    [GraphQLNonNullType] public string Name { get; set; }
}
```

Attempting to run the following query
```
query {
  testGet(where: {name_starts_with:"Tes"})
  {
    id,name
  }
}
````
Gives an field required error for **every** integer filter parameter:
```
{
  "errors": [
    {
      "message": "`id` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_gt` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_gte` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_lt` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_lte` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_not` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_not_gt` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_not_gte` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_not_lt` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    },
    {
      "message": "`id_not_lte` is a required field and cannot be null.",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ]
    }
  ]
}
```
The error is not produced if only the string fields are marked with the `[GraphQLNonNullType]` attribute.

It appears that the `[GraphQLNonNullType]` attibute is being erroneously copied from the base type into the Filter type.

Reproduced in HC 10.4.3 and 11.0.0-preview.127

**Comment by PascalSenn** [comment]
Hi @albanfellows  

These cases are under test. Can you add create a minimal repro of the bug?
https://github.com/ChilliCream/hotchocolate/blob/master/src/HotChocolate/Filters/test/Types.Filters.Tests/FilterInputTypeTest.cs#L221-L238

**Comment by PascalSenn** [comment]
https://github.com/ChilliCream/hotchocolate/issues/1222

**Comment by albanfellows** [comment]
Using the workaround described in #1222 does work. 
i.e.
```
public class TestObject
{
    [GraphQLType(typeof(NonNullType<IntType>))]
    public int? Id { get; set; }
    [GraphQLNonNullType] public string Name { get; set; }
}
```
I will have a go at creating a test case.

**Comment by albanfellows** [comment]
Reproduction project at [https://github.com/albanfellows/HC_Issue_1961](https://github.com/albanfellows/HC_Issue_1961)

**Comment by albanfellows** [comment]
> 
> 
> Hi @albanfellows
> 
> These cases are under test. Can you add create a minimal repro of the bug?
> https://github.com/ChilliCream/hotchocolate/blob/master/src/HotChocolate/Filters/test/Types.Filters.Tests/FilterInputTypeTest.cs#L221-L238

If the `[GraphQLNonNullType]` attribute is added to either `Pages` or `Chapters` properties of the `Book` class the `FilterAttribute_NonNullType` test will fail on the members of the `BookFilter` input type having the wrong type (`Int!` instead of `Int`)

**Comment by PascalSenn** [comment]
@albanfellows  is this still a thing in V11 filtering?

**Comment by albanfellows** [comment]
> @albanfellows is this still a thing in V11 filtering?

@PascalSenn I can confirm that the original bug (from 10.4.3) no longer exists in 11.0.7.
The new filtering in 11.0.7 also works correctly.

I have updated the Sample project to HC11.0.7.

**Comment by PascalSenn** [comment]
Very nice! Thanks for the feedback, i will close this issue in this case
