### ISSUE TITLE
Unable to infer or resolve a schema type from the type reference `Input: System.TimeSpan`.

### ISSUE THREAD

**Issue by RomanVashchegin** [ChilliCream/hotchocolate#1969]
**Describe the bug**
After migration from 10.4.1 to 11.0.0.-review.130 I get the schema initialization error:
Unable to infer or resolve a schema type from the type reference `Input: System.TimeSpan`.
My classes doesn't have TimeSpan properties. 
ObjectTypes described with option descriptor.BindFields(BindingBehavior.Explicit); and then listed all needed properties from my class. 

**To Reproduce**
Failed on ISchema.Create() method

**Expected behavior**
In 10.4.0 Schema created and GraphQL started successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 11.0.0-Preview.130

**Comment by RomanVashchegin** [comment]
Issue is reproduced only with .UseFiltering()

**Comment by michaelstaib** [comment]
In general we do not recommend to use the preview versions, at the moment they are unreliable and we are introducing a lot of breaking changes over the coming weeks. 

The next version that is coming out is version 10.5.0 which is in preview also.

**Comment by ShaikhShakeebAhmed** [comment]
change your TimeSpan variable to Object and later cast it to DateTime and extract TimeofDay from it
