### ISSUE TITLE
How to debug EXEC_INVALID_TYPE?

### ISSUE THREAD

**Issue by gallivantor** [ChilliCream/hotchocolate#1973]
I have a large project which I have just upgraded from 10.1 to 10.4

Having done that, I've started to get this error with one of the mutations:

{"errors":[{"message":"Variable \u0060$input\u0060 got invalid value.","locations":[{"line":1,"column":16}],"extensions":{"code":"EXEC_INVALID_TYPE"}}]}

I read in [this issue](https://github.com/ChilliCream/hotchocolate/issues/1216) that there were validation changes, however the error message gives no clue about which field is causing the problem. My $input object has more than 30 fields on it, how am I supposed to know which one is causing this?

Is there a way to get the field name returned in the error message?

**Comment by gallivantor** [comment]
Just noticed #1397 which is similar for the "wrong structure" message.

This is really vital, it's very hard to work with this when you're digging through loads of properties trying to guess which one is the wrong one

**Comment by PascalSenn** [comment]
@gallivantor  I see your points. We may can make this error message better. do you use a client? it makes things easier to spot. checkout banacake pop 
https://hotchocolate.io/docs/banana-cakepop

**Comment by michaelstaib** [comment]
Version 11 will provide a path to the prop.

**Comment by gallivantor** [comment]
@michaelstaib  thanks, that's good to know.
@PascalSenn  thanks for that link, I tried out Banana Cakepop and it looks like a useful tool but it just seems to show me the same "Variable got invalid value" error message, how can I use it to find the faulty field?

As follow-up, through trial and error I think I found the problem, there is a __typename field that is being passed in to the update which is causing the error. BUT, this field is returned automatically by the query to get the data and the UI is simply reflecting it back in the update.

It seems that the JS Apollo library is automatically adding this field to the query that goes in, and HotChocolate is returning it back as part of the query results.
So why is this then causing an error when the JS tries to pass it back in with the update? Is that because it's a read-only field and it should be stripped from the update call?

**Comment by gallivantor** [comment]
Also -- this extra validation is a massive breaking change, and I'm surprised that it was introduced with a minor version update from 10.1 to 10.4 ... presumably there's no option to turn it off?

**Comment by PascalSenn** [comment]
@gallivantor  
if this was working in 10.1 then it was a bug in validation. We are following the spec validation rules strictly. 
You will have to remove it from the query in the frontend 
You can also skip validation if you want to. you can create a custom pipeline if you like. Just keep in mind that validation is the first layer of security :)

**Comment by gallivantor** [comment]
Thanks for your replies.
Sounds like the upcoming 11.0 release will resolve this which is great!

**Comment by michaelstaib** [comment]
Related to #3111

**Comment by michaelstaib** [comment]
We will fix this one with #3111. I am closing this one.
