### ISSUE TITLE
GraphQL with DDD approach domain architecture problem

### ISSUE THREAD

**Issue by XardasLord** [ChilliCream/hotchocolate#1975]
My domain entity aggregate root looks like this:
```csharp
    public class Book : Entity<long>
    {
        private BookInformation _bookInformation;
        private bool _inStock;

        public BookInformation BookInformation => _bookInformation;
        public bool InStock => _inStock;

        public Book() { }

        private Book(BookInformation bookInformation)
        {
            _bookInformation = bookInformation;
            _inStock = true;
        }

        public static Book Create(string title, string author, string subject, string isbn)
        {
            var bookInformation = new BookInformation(title, author, subject, isbn);
            var book = new Book(bookInformation);

            return book;
        }
    // and other methods (...)
    }
```

And my `Entity` class has a list of events (of type `INotification`):
```csharp
 private List<INotification> _domainEvents;
 public IReadOnlyCollection<INotification> DomainEvents => _domainEvents?.AsReadOnly();
```

`INotification` is a markup interface from the `MediatR` library. My problem is the following - when I add GraphQL with the following setup:
```csharp
services.AddGraphQL(
                    SchemaBuilder.New()
                        .AddQueryType<QueryType>()
                        .Create(),
                    new QueryExecutionOptions
                    {
                        ForceSerialExecution = true
                    });
(...)
app.UseGraphQL().UsePlayground();
```
and the Query:
```csharp
    public class Query
    {
        [UseSelection]
        public IQueryable<Book> GetBooks([Service] LibraryDbContext context)
            => context.Books;
    }
```

I get the following error on project startup
 >    An unhandled exception of type 'HotChocolate.SchemaException' occurred in 
 >    HotChocolate.Types.dll: 'Interface `INotification` has no fields declared. - Type: INotification'
 >   Stack trace:
 >   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
 >   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
 >   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
 >   at HotChocolate.SchemaBuilder.Create()
 >   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()

I tried to introduce QueryType like this:
```csharp
    public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            // How to ignore these DomainEvents property here from the Query?
        }
    }
```
but I don't know how can I ignore the DomainEvents property from the model. How can I achieve this? Or am I doing this from the wrong side?

**Comment by PascalSenn** [comment]
You can add 
```csharp 
[GraphQLIgnore]
 public IReadOnlyCollection<INotification> DomainEvents => _domainEvents?.AsReadOnly();
```
or create an object type for book:
```
    public class QueryType : ObjectType<Book>
    {
        protected override void Configure(IObjectTypeDescriptor<Book> descriptor)
        {
           descriptor.Ignore(x => x.DomainEvents);
        }
    }
```

if there are actually different type of events you can also add Interfaces Or Union Types based on the interface

**Comment by XardasLord** [comment]
Indeed, adding `[GraphQLIgnore]` attribute works well. But as far as I understand if I create this QueryType for Book I have to use it when register graphql in my IServiceCollection by `.AddQueryType<QueryType>()` am I right? 

But then my graphql playground shows me this:
![image](https://user-images.githubusercontent.com/29070326/82732012-c6dfa200-9d0a-11ea-871e-af0780374753.png)

there is no Books array, why?

And this: 
![image](https://user-images.githubusercontent.com/29070326/82732021-e1198000-9d0a-11ea-94a2-5f3c63ea18f8.png)
is not returning any correct value

**Comment by PascalSenn** [comment]
ah i just copied the class from your example. 
so:
```csharp
public class BookType : ObjectType<Book>
    {
        protected override void Configure(IObjectTypeDescriptor<Book> descriptor)
        {
           descriptor.Ignore(x => x.DomainEvents);
        }
    }
`
```
But you still need the root type 
```csharp
public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        { 
        }
    }
`
``` 

you can also make this pure code first with this on the Books class
```csharp
[GraphQLIgnore]
 public IReadOnlyCollection<INotification> DomainEvents => _domainEvents?.AsReadOnly();
```
adn this on the schema builder:
```
.AddQueryType<Query>()
```

**Comment by XardasLord** [comment]
@PascalSenn thanks for the answer :)
If I have only `.AddQueryType<Query>()` registered it still says that `Interface INotification has no fields declared`. But if I add `.AddQueryType<BookType>()` the error is following:

> System.ArgumentException: 'An item with the same key has already been added. Key: Query'

Here is my registration: 
```csharp
    services
                .AddGraphQL(
                    SchemaBuilder.New()
                        .AddQueryType<Query>()
                        .AddQueryType<BookType>()
                        .Create(),
                    new QueryExecutionOptions
                    {
                        ForceSerialExecution = true
                    });
```

and here are my query types:

```
public class BookType : ObjectType<Book>
    {
        protected override void Configure(IObjectTypeDescriptor<Book> descriptor)
        {
            descriptor.Ignore(x => x.DomainEvents);
        }
    }

    public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
        }
    }

    public class Query
    {
        [UseSelection]
        public IQueryable<Book> GetBooks([Service] LibraryDbContext context)
            => context.Books;
    }
```

**Comment by PascalSenn** [comment]
Yes you only need to add one query type
```csharp
  SchemaBuilder.New()
            .AddQueryType<Query>()
            .AddType<BookType>()
            .Create(),
```

**Comment by PascalSenn** [comment]
you also do not need `QueryType` in this case 👍

**Comment by XardasLord** [comment]
@PascalSenn Great, it works! :) 
I have another question. Do I need a public ctor in my Book entity? I had private parameterless ctor because EFCore needs it, but I see that GraphQL need a public one. Is there any way to keep my entity encapsulated like before (private ctor). The same question about missing 'set accesor on my properties:

> The property 'System.String Author' has no 'set' accessor (Parameter 'member')"

Can I somehow workaround this?

**Comment by PascalSenn** [comment]
Unless you use it as an input type you do not need any ctor

in case of an input type we map all public {get,set,} properties into the schema. 
you can also have readonly {get;} properties that are set over a pulbic ctor 
```
public class FooInput {
    public string Bar {get;set;}
}
public class FooInput {
     public FooInput(string bar) 
     {
        Bar = bar;
     }
     public string Bar {get;}
}
```

**Comment by XardasLord** [comment]
So with backend field it is not able to work with? Like in my case:

```csharp
public class Book : Entity<long>
{
    private bool _inStock;
    public bool InStock => _inStock;

    private Book(BookInformation bookInformation)
    {
        _bookInformation = bookInformation;
        _inStock = true;
    }

    public static Book Create(string title, string author, string subject, string isbn)
    {
        var bookInformation = new BookInformation(title, author, subject, isbn);
        var book = new Book(bookInformation);

        return book;
    }
}
(...)
```

**Comment by PascalSenn** [comment]
This should work

**Comment by XardasLord** [comment]
> This should work

But I have this error:
![image](https://user-images.githubusercontent.com/29070326/82754316-5b5e0900-9dcc-11ea-8131-e0322b76a774.png)

**Comment by PascalSenn** [comment]
Ah, yes with UseSelection it does not work.  sorry for the inconvenience. You can not write this as a type safe select statement:
```
bboks,Select(x => new Book(){InStock = x.InStock}); 
```

**Comment by XardasLord** [comment]
Indeed, without UseSelection works but of course the generated SQL query is very inefficient :(

**Comment by PascalSenn** [comment]
Ok i am gonna close this issue as the original question is answered 👍
