### ISSUE TITLE
c# TimeSpan not recognized in dotnet core 

### ISSUE THREAD

**Issue by acx70** [ChilliCream/hotchocolate#1977]
**Description of the bug**
I implemented Hotchocolat in a dotnet core API REST project (c#). I wrote a class that represent my database model "TestTimelines". In this class, I defined a timestamp field.  Ones I create the schema I get the following message:

**_Unable to infer or resolve a schema type from the type reference `Output: System.TimeSpan`._**

(If I mark the field with "[GraphQLIgnore]" attribute I don't get errors anymore. but I can't query the filed "TLTime")

**To Reproduce** 

Create the model class TestTimelines

     public class TestTimeSpan
      {
          //[GraphQLIgnore]
          public TimeSpan TLTime { get; set; }
          public string TLString { get; set; }
      }

Create the query class:

    public class Queries
    {
        public List<TestTimeSpan> TestTimelines()
        {
            List<TestTimeSpan> l = new List<TestTimeSpan>();
            TestTimeSpan el = new TestTimeSpan();
            el.TLTime = new TimeSpan(0, 0, 0);
            el.TLString = "aaa";
            l.Add(el);
            return l;
        }
   }

Create the type class

    public class QueryTypes : ObjectType<Queries>
    {
        protected override void Configure(IObjectTypeDescriptor<Queries> descriptor)
        {
            base.Configure(descriptor);

                        descriptor
                .Field(f => f.TestTimelines());
        }
    }

Add the schema in the StartUp class 

        public void ConfigureServices(IServiceCollection services)
        {
           // ......
            var schema = Schema.Create(c =>
            {
                //c.RegisterExtendedScalarTypes();
                c.RegisterQueryType<QueryTypes>();
            });
           // ......
        }

( I tried using "RegisterExtendedScalarTypes" without success)

Run the project and you should see the error: 

**_Unable to infer or resolve a schema type from the type reference `Output: System.TimeSpan`._**

**Expected behavior**
I was expetting I didn't get any error.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version	10.0.17763 Build 17763
 - Visual Studio 2019
 - dotnet core 3.0
 - HotChocolate.AspNetCore v.11.0.0-preview.130
- HotChocolate.AspNetCore.Playground v.11.0.0-preview.130

**Comment by PascalSenn** [comment]
`TimeSpan` is not a scalar that is supported out of the box. Check custom scalars out

https://hotchocolate.io/docs/custom-scalar-types

**Comment by acx70** [comment]
> `TimeSpan` is not a scalar that is supported out of the box. Check custom scalars out
> 
> https://hotchocolate.io/docs/custom-scalar-types

I implemented my "CustomTimespanType" and it works perfectly!!

**Comment by PascalSenn** [comment]
@acx70  very cool, i am gonna close this issue :)
