### ISSUE TITLE
IdType description isn't accurate

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2003]
**Describe the bug**
https://github.com/ChilliCream/hotchocolate/blob/9dc88dcaadec1f14400cec8ab15c51fc69c1fd0b/src/HotChocolate/Core/src/Types/Properties/TypeResources.resx#L281

It ends with "When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.", same as what GitHub say about their IDs, but I don't think that's the case in HC, right?

**To Reproduce**
Look at the schema description for `ID`.

**Expected behavior**
Prob shouldn't say that at the end.

**Desktop (please complete the following information):**
 - HC v10 and v11

**Comment by benmccallum** [comment]
> Technically if you do not opt in to relay support this is correct. since you can pass either string or int.

Ah, interesting! @maraisr asked that we don't support this polymorphic behaviour when we get onto HC (we were on the relay stuff I did for graphql-dotnet), so I was worried they'd see the type description and wonder what's up when it says it still behaves that way.

Definitely not a high priority. Could look to toggle desc depending on Relay support or just update the description with a bit saying that only applies when not using Relay support. Cheers

**Comment by michaelstaib** [comment]
It is speced like that
http://spec.graphql.org/June2018/#sec-ID

**Comment by benmccallum** [comment]
Hmm, well I guess we should probably support this as we were @maraisr. Will close this and we can talk internally.
