### ISSUE TITLE
[Berry] fragments of subtypes are ignored

### ISSUE THREAD

**Issue by Alxandr** [ChilliCream/hotchocolate#2004]
**Describe the bug**
Returning an interface, and trying to get fields from one of the implementations, the field is not included in the generated code.

**To Reproduce**
Fairly simple reproduction can be seen here: https://gist.github.com/Alxandr/e125dd9a8d11a159e73153ed727e8406

In summary:

```gql
#schema
schema {
  query: Query
}

scalar CustomerNumber

type Query {
  customer(id: CustomerNumber!): Customer
}

interface Customer {
  # All customers have IDs
  id: CustomerNumber!
}

# Some customers are people
type Person implements Customer {
  id: CustomerNumber!
  ssn: String!
}
```

```gql
#query
query getCustomerById($id: CustomerNumber!) {
  customer(id: $id) {
    id
    ... on Person {
      ssn
    }
  }
}
```

The SSN here is not available from the generated client (in any way that I can find).

**Expected behavior**
I should be able to do something like `if (customer is Person p) { p.Ssn }`.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I've tried this in both preview.97 and preview.130. Both produce the same code.

**Comment by michaelstaib** [comment]
This case is now handled.
