### ISSUE TITLE
Proper way for nested mutation resolvers

### ISSUE THREAD

**Issue by vtrihos** [ChilliCream/hotchocolate#2007]
Hello,

I'm trying to get my head around nested mutations. 
I have successfully created nested input types holding the data. However, I can't implement a proper way to insert them.

**What I hope for**
What I ultimately want is to process the nested input data in a graph, before I actually end up inserting the whole graph in database in one go (currently using EF Core)

**What I can live with**
What I can live with is inserting one by one the objects in database (respecting the hierarchy). 

Is there something I'm missing? I've spent a good few days looking for a decent solution :(

Thank you in advance

**Comment by PascalSenn** [comment]
Hi @vtrihos  

GraphQL does by spec not support nested mutations 
so this would be invalid:
```graphql
mutation  {
   user{
       add(input: {userName:"Foo"}) {
           userName
       }
   }
}
```

where as this would be valid
```graphql
mutation  {
   addUser(input: {userName:"Foo"}) {
           userName
       } 
}
```

 
Only the top level is executed serially, everything below is a 'query'

**Comment by PascalSenn** [comment]
can you show use some graphql/code to provide some more context?

**Comment by vtrihos** [comment]
Hey @PascalSenn ,

Thank you for your quick reply. That made things way clearer.

I was looking at the whole matter from the wrong perspective. 
I was expecting there to be mutation resolvers which I would chain (like I do with the query resolvers).

The right approach was to have nested ObjectInputTypes instead, and handle the mutation chaining myself, in one go, in the resolver of the root mutation. Now, I'm chaining the creation of the objects and linking them together, as the nested input instruct.

I think I'm on the right track now.

Thanks again,
Bill
