### ISSUE TITLE
Allow further data processing prior to returning it through API

### ISSUE THREAD

**Issue by JTinkers** [ChilliCream/hotchocolate#2018]
**Is your feature request related to a problem? Please describe.**
You have models: Post and Tag with many-to-many relationship.
Because of the relationship type, you had to also add a model PostTag with fields post_id, tag_id.

If you tried to use HC to return multiple posts with related tags, you'd have to return PostTag and then dig deeper to get the actual tags - which in effect would return json as such:

```csharp
...
{
	[
		{
			"id": 1,
			"tags":
			[
				{
					"tag":
					{
						"name": "test tag"
					}
				},
				{
					"tag":
					{
						"name": "another testtag"
					}
				}
			]
		}
	]
}
...
```

Clearly, the solution is subpar as there's an extra object wrapping tags because it has to go through PostTag model.

**Describe the solution you'd like**
An ability to dig deeper before returning data would suffice, perhaps:

`
descriptor.Field(x => x.PostTags).GetValue(x => x.Select(y => y.Tag))
`

.. or, considering the fact it'd have to also load related fields

`
descriptor.Field(x => x.PostTags).UseSelection(x => x.Select(y => y.Tag))
`

**Describe alternatives you've considered**
I've considered implementing virtual properties and methods on the EF Core DTO's that'd dig deeper, but putting `this.PostTags.Select(x => x.Include(y => y.Tag).Tag)` into a property/method sounded like a terrible idea.

**Comment by michaelstaib** [comment]
This can be done with a request middleware.

```
.AddGraphQLServer().UseRequest(...
```
