### ISSUE TITLE
Support Ignore Attribute for Inherited Types

### ISSUE THREAD

**Issue by daminee80** [ChilliCream/hotchocolate#2019]
I am using an ORM that requires every entity to inherit the parent type `Resource`. This causes HotChocolate to fail during the type auto-discovery process as the parent contains generics. 

`HotChocolate.SchemaException: Unable to create instance of type ''.`

[Issue](https://github.com/ChilliCream/hotchocolate/issues/1447)

The only way for me to get things working is to force explicit binding:

` .ModifyOptions(o => o.DefaultBindingBehavior = BindingBehavior.Explicit)`

I would like for this to work

```
public class Person : [GraphQLIgnore] Resource 
{
    public string Name { get; set; }
    public int Age { get; set; }
}
```

**Comment by michaelstaib** [comment]
Have you tried to put the ignore attribute on then props and methods of the base class?

At the moment it is not possible to ignore the whole base class. We could, however, look at implementing such behavior. 

Also, the type-discovery is abstracted through our type discoverer. You could override the field discovery and implement a custom ignore pattern.

**Comment by michaelstaib** [comment]
In order to customize the field discovery, inherit from DefaultTypeInspector and override the following method: 
https://github.com/ChilliCream/hotchocolate/blob/c26221c93b17c0a2afcc5806d1380d5251007f6e/src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DefaultTypeInspector.cs#L28

In your case, you could get the discovered members from the base method and remove the once that are on the resource type.

**Comment by michaelstaib** [comment]
In order for the type discoverer to work add it to your dependency injection as singleton:

`service.AddSingleton<ITypeInspector, MyTypeInspector>()`

Also, make sure that you add the service provider to the schema builder:

`service.AddGraphQL(sp => SchemaBuilder.New().AddServices(sp) ....`

**Comment by michaelstaib** [comment]
If you need more help head over to our slack channel.

**Comment by daminee80** [comment]
Thank you.

**Comment by Zero3** [comment]
Thanks for the useful guide @michaelstaib.

I made this this quick and dirty hack to exclude all superclass members from the discovery results:

````
public class MyTypeInspector : DefaultTypeInspector
{
	public override IEnumerable<MemberInfo> GetMembers(Type type)
	{
		return base.GetMembers(type)
			.Where(memberInfo => memberInfo.DeclaringType == type);
	}
}
````

**Comment by ahmad2smile** [comment]
Just tried on v12 and it works but with following overload

```csharp
IEnumerable<MemberInfo> GetMembers(Type type, bool includeIgnored)
```

one without `includeIgnored` wouldn't have any effect for me.


Also only had to register the Singleton service nothing related to `.AddServices(sp)`

**Comment by gerneio** [comment]
@ahmad2smile spent way too long trying to figure out how to get this to work. Read all the comments above your comment multiple times... should have just read yours since it's accurate for v12.
