### ISSUE TITLE
Stitching - Requests sent to remote schema with invalid json for variables

### ISSUE THREAD

**Issue by chris-redhead** [ChilliCream/hotchocolate#2024]
**Description**
When using schema stitching to send requests to a remote resource number variables are not given a trailing comma, therefore producing invalid json.

I've experimented with this and it seems if the remote schema is hotchocolate it will happily parse this invalid json, but other gql implementations won't.

**To Reproduce**
1. Set up schema stitching to consume a remote schema.
2. make a query of the remote schema using one or more number variables (issue exists for ints and floats).
3. Inspect the body of the http request made - note that number variables are not followed by commas, as they should per json spec.

**Expected behavior**
valid Json produced.

**Additional context**
I've put together a fix for this and a test describing the problem. I'll submit a PR

**Comment by erwan-joly** [comment]
@michaelstaib i think this can now be closed
