### ISSUE TITLE
DataLoaderBase.StartAsyncBackgroundDispatching blocks thread

### ISSUE THREAD

**Issue by thibault-reigner** [ChilliCream/hotchocolate#2028]
**Description**
In DataLoaderBase, StartAsyncBackgroundDispatching relies on AutoResetEvent to perform a recurrent "wait then process batch". 
However, this design, by using `WaitOne` blocks the thread executing this task, which defeats the benefit of the async method in which it is called.
https://github.com/ChilliCream/hotchocolate/blob/15f09f6efcf22319eff536c4afe737f378dce4d4/src/GreenDonut/src/Core/DataLoaderBase.cs#L602

I am wondering if it would not be possible to switch to a fully asynchronous version.

**Comment by PascalSenn** [comment]
hi @thibault-reigner  we are completely rewriting the execution engine and data loaders in V11. This is not longer needed with the new execution i think 
Lets check with the others

**Comment by rstaib** [comment]
Hi @thibault-reigner,
@PascalSenn is right with the new DataLoader and ExecutionEngine this isn't the case anymore. With the next version of GreenDonut a IBatchScheduler is passed through and the implementation for that may differs for various scenarios.

**Comment by max4t** [comment]
I believe this is the new version: https://github.com/ChilliCream/hotchocolate/pull/1966

**Comment by rstaib** [comment]
Correct

**Comment by michaelstaib** [comment]
I am closing this issue since this issue is already solved in the execution engine branch.
