### ISSUE TITLE
HotChocolate.Server.Template causes a compiler warning

### ISSUE THREAD

**Issue by DaanAcohen** [ChilliCream/hotchocolate#2031]
**Describe the bug**
HotChocolate.Server.Template causes a compiler warning: 

> Startup.cs(5,7): warning CS0105: The using directive for 'HotChocolate' appeared previously in this namespace [C:\Users\daan1982\source\githubRepos\hotchocolate\templates\Server\content\HotChocolate.Server.Template.csproj]

**To Reproduce**
1. Go to the root folder of hot chocolate
2. Type `cd templates/Server/content`
3. Type` dotnet build`
4. See warning

**Expected behavior**
Zero warnings.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 (build 1909)

**Additional context**
The warning could have been avoided by a cleanup of the namespaces.

**Comment by DaanAcohen** [comment]
@michaelstaib Why is this labelled as a duplicate? What is the other item this item duplicates?

**Comment by michaelstaib** [comment]
Sorry overlooked it and thought this was the original error where the using HotChocolate was missing. Approved your PR and we will merge it.
