### ISSUE TITLE
can't generate client code with PaginationAmount

### ISSUE THREAD

**Issue by 9b9** [ChilliCream/hotchocolate#2046]
**Describe the bug**
If schema has any **PaginationAmount**, ClientGenerator.BuildAsync() will throw an exception.

**To Reproduce**
```csharp
using System.Threading.Tasks;
using Snapshooter.Xunit;
using Xunit;

namespace StrawberryShake.Generators
{
    public class ClientGeneratorTests
        : ModelGeneratorTestBase
    {
        [Fact]
        public async Task Known_PaginationAmount_Scalar_Types()
        {
            // arrange
            var outputHandler = new TestOutputHandler();

            string schema = @"
                type Query {
                    foo: Foo
                }

                type Foo {
                    first: PaginationAmount
                }
                ";

            string query =
               @"
                query getFirst {
                    foo {
                        first
                    }
                }
                ";

            // act
            await ClientGenerator.New()
                .AddQueryDocumentFromString("Queries", query)
                .AddSchemaDocumentFromString("Schema", schema)
                // .SetScalarType(new LeafTypeInfo("PaginationAmount", typeof(int)))
                .SetOutput(outputHandler)
                .BuildAsync();

            // assert
            outputHandler.Content.MatchSnapshot();
        }
    }
}
```

**Actual behavior**
```
[xUnit.net 00:00:01.04]     StrawberryShake.Generators.ClientGeneratorTests.Known_PaginationAmount_Scalar_Types [FAIL]

  X StrawberryShake.Generators.ClientGeneratorTests.Known_PaginationAmount_Scalar_Types [406ms]
  Exception Text:
   System.NotSupportedException : Leaf type `PaginationAmount` is not supported.
  Stack Trace:
     at StrawberryShake.Generators.CSharp.TypeLookup.CreateLeafClrTypeName(IType type, Boolean nullable) in E:\hotchocolate\src\StrawberryShake\CodeGeon\src\Generators\CSharp\TypeLookup.cs:line 306
   at StrawberryShake.Generators.CSharp.TypeLookup.GetLeafClrTypeName(IType type) in E:\hotchocolate\src\StrawberryShake\CodeGeneration\src\Generatorsp\TypeLookup.cs:line 273
   at StrawberryShake.Generators.CSharp.TypeLookup.GetTypeName(IType fieldType, FieldNode field, Boolean readOnly) in E:\hotchocolate\src\StrawberryShdeGeneration\src\Generators\CSharp\TypeLookup.cs:line 83
   at StrawberryShake.Generators.CSharp.ClassGenerator.WriteConstructorAsync(CodeWriter writer, IClassDescriptor descriptor, ITypeLookup typeLookup) in E:\hotchocolate\src\StrawberryShake\CodeGeneration\src\Generators\CSharp\_m\ClassGenerator.cs:line 108
   at StrawberryShake.Generators.CSharp.ClassGenerator.WriteAsync(CodeWriter writer, IClassDescriptor descriptor, ITypeLookup typeLookup) in E:\hotchocolate\src\StrawberryShake\CodeGeneration\src\Generators\CSharp\_m\ClassGenerator.cs:line 55
   at StrawberryShake.Generators.CSharp.NamespaceGenerator.WriteAsync(CodeWriter writer, ICodeDescriptor descriptor, ITypeLookup typeLookup) in E:\hotchocolate\hotchocolate\src\StrawberryShake\CodeGeneration\test\Generators.Tests\ModelGeneratorTestBase.cs:line 111
   at StrawberryShake.Generators.ClientGenerator.BuildAsync() in E:\hotchocolate\src\StrawberryShake\CodeGeneration\src\Generators\ClientGenerator.cs:line 362
   at StrawberryShake.Generators.ClientGeneratorTests.Known_PaginationAmount_Scalar_Types() in E:\hotchocolate\src\StrawberryShake\CodeGeneration\test\Generators.Tests\ClientGeneratorTests.cs:line 522
--- End of stack trace from previous location where exception was thrown ---
```

**Expected behavior**
without exception 

**Desktop (please complete the following information):**
 - Version 11.0.0-preview.134

**Comment by SbiCA** [comment]
@michaelstaib I think it would be cool to an example on pagination in the "StarWars" demo or a dedicated one but as a beginner, it seems quite hard to know how to write you "queries" to get a properly generated client.

**Comment by ademchenko** [comment]
@michaelstaib, actually this is a very important issue because lacking of PaginationAmount support makes StrawberryShake practically unusable in real-world projects because any such project has lists and paging. So, I implemented support of PaginationAmount and kindly ask you to review, merge and push to Nuget.

**Comment by michaelstaib** [comment]
@ademchenko we have dropped the pagination amount with 11. We now use `Int`. We did a lot of work around paging when we added your PR around offset pagination.

**Comment by michaelstaib** [comment]
@ademchenko Just saw your PR around this ... at this moment we cannot merge anything into strawberry shake. We are finishing of 11 at the end of October and then focus on strawberryshake. We hope to release it at the end of December. We will set up a meeting around this. If you want to join you are very welcome to do so. Are you on slack? If so dm me so I can tag you for the meeting.

**Comment by ademchenko** [comment]
@michaelstaib,  unfortunately, I'm not on slack since it's kind of shareware (like there are restrictions on messages history and so on), so, to be honest with you I'm not sure this is the right messaging tool for open source initiatives.

But, @michaelstaib, this is a real big issue with StrawberryShake. Once you decided not to merge before the end of December it definitely means that StrawberryShake will be left unusable for 2 months. So, if I could ask, is there a chance to make a small exception in your merge politics?

**Comment by michaelstaib** [comment]
@ademchenko, sorry for the late reply.

At the moment, slack is granting us standard account rights. Also, we use slack as a place where the community comes together. I really can recommend joining.

Regarding Strawberry Shake, at the moment, it does not build, so we really cannot create another preview. But that does not mean we have to wait two months for another build. We are planning to create new previews in about two weeks again. At the moment, everyone is focused on getting the server released. We hope to wind down work on the server in about two weeks and then focus on Strawberry Shake. The December release will focus almost purely on Strawberry Shake, and a lot is coming.

Are you OK with waiting another two weeks?

**Comment by PascalSenn** [comment]
@michaelstaib  would registering PaginationAmount as a custom scalar on starberryshake solve this problem?

**Comment by michaelstaib** [comment]
I mean, we are removing pagination amount with 11. But when we restart strawberry shake, we will have a look at how we can make it super easy to register scalars. We first need to talk through the direction of this.

**Comment by michaelstaib** [comment]
@ademchenko @PascalSenn is actually right you should be able to add a custom scalar to your project. Did you already try that?

**Comment by michaelstaib** [comment]
This one is now fixed.
