### ISSUE TITLE
Add documentation for AddType and AddQueryType

### ISSUE THREAD

**Issue by nbon12** [ChilliCream/hotchocolate#2048]
Hi, 

As a developer who wants to use Hot Chocolate, I want to know what is the difference between .AddType and .AddQueryType. I could not find documentation on either method.

Here are the places I looked:

Search results:
![image](https://user-images.githubusercontent.com/17408265/84269138-cad73680-aaf6-11ea-8d1e-f2f3544a3b26.png)

Docstring comment:
![image](https://user-images.githubusercontent.com/17408265/84269232-f0644000-aaf6-11ea-9866-f56ad8207d9f.png)

**Comment by desley-roelofsen** [comment]
I use the AddType for the schema definition, like:

![image](https://user-images.githubusercontent.com/10446870/84367432-83bf7300-abd4-11ea-9d82-1522f6ab090c.png)

And the AppQueryType for the definition to describe the possible queries, like:

![image](https://user-images.githubusercontent.com/10446870/84367555-b10c2100-abd4-11ea-94d8-a44968e3964e.png)

And in the above example you can see the includes of the resolvers, and one of the resolvers looks like the next example:

**Comment by desley-roelofsen** [comment]
Hi! To explain it better, I made an example to show you the difference. I hope you understand the difference now, and the possibilities.

I use the AddType for the schema definition, like:

![image](https://user-images.githubusercontent.com/10446870/84367432-83bf7300-abd4-11ea-9d82-1522f6ab090c.png)

And the AppQueryType for the definition to describe the possible queries, like:

![image](https://user-images.githubusercontent.com/10446870/84367555-b10c2100-abd4-11ea-94d8-a44968e3964e.png)

And in the above example you can see the includes of the resolvers, and one of the resolvers looks like the next example:

![image](https://user-images.githubusercontent.com/10446870/84367683-df89fc00-abd4-11ea-9ef7-1cc46294685c.png)

And types and the QueryType i define like the next example:

![image](https://user-images.githubusercontent.com/10446870/84368024-56bf9000-abd5-11ea-9345-f8f77073470b.png)

And the result in the GraphQL schema looks like:

![Example Schema](https://user-images.githubusercontent.com/10446870/84368780-4c51c600-abd6-11ea-9d34-8433ddd091d1.gif)

**Comment by michaelstaib** [comment]
This is solved with the new docs.

**Comment by toreaurstadboss** [comment]
Hello. Just wondered if HotChocolate got any marker interfaces so we could add all query types that implement an interface. I.e AddQueryTypes<ISomeQueryMarkerInterFace>(Assembly someAssembly = null)
If assembly is null then current executing assembly is scanned. 
Same goes for the AddType. The benefit of adding specifically is being explicit. But then HotChocolate requires you to do lengthy registrations as the backend application increases in complexity.

**Comment by tobias-tengler** [comment]
@toreaurstadboss we built a source generator to do the registrations and it's been available since 12.7. Check out https://www.youtube.com/watch?v=QPelWd9L9ck

I'm also going to document it hopefully soon.
