### ISSUE TITLE
Deprecations not appearing in stitched schema

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2050]
**Describe the bug**
Deprecation not coming through in schema.

**To Reproduce**
Stitched schema with downstream schema using `.Deprecate("...")` on a field

**Expected behavior**
Field to be deprecated when stitched with msg given.

**Desktop (please complete the following information):**
 - Linux container, netcore3.1, HC 10.5.0-preview.3 or preview.6

**Comment by michaelstaib** [comment]
This one is now fixed with:
https://github.com/ChilliCream/hotchocolate/releases/tag/10.5.0-preview.10
