### ISSUE TITLE
listen disconnect subscription

### ISSUE THREAD

**Issue by huudatk53** [ChilliCream/hotchocolate#2053]
Hi, I use the subsciption when I know when users are online and offline
How to listen user disconnect subcription "onlines"

**Comment by michaelstaib** [comment]
Subscriptions internally are represented as a stream `IAsyncEnumerable`. So, when a user gets offline the context.RequestAborted is raised and the IAsyncEnumerator is disposed of.

**Comment by lovemiss** [comment]
@michaelstaib I have a same problem. You can give me sample about that, 
`var result = await eventReceiver.SubscribeAsync<string, Hero>(
                "topichero", cancellationToken);`
In there, I don't know how to handle when IAsyncEnumerable (result) disposed.

**Comment by michaelstaib** [comment]
@lovemiss  are you using 10.4.3? if so we fixed an issue on this with 10.5.0-preview.6

**Comment by lovemiss** [comment]
@michaelstaib Yes, I am using version 10.4.3. so with version 10.5.0-preview.6,
Is it using ITopicEventSender.CompleteAsync.

**Comment by PascalSenn** [comment]
closed in favour of #2892
