### ISSUE TITLE
authorize doesn't work with identity server local api

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#2054]
**Describe the bug**
we have a very strange behaviour with HotChocolate authorization. The authorize attribute from AspNetCore works very well on controllers. But when we try to leverage the authorization in GraphQL with the authorize attribute from the HotChocolate namespace. It always evaluates to not authorized.

this works:
```
[Authorize(LocalApi.PolicyName)]
        public IActionResult Index()
        {
```
https://github.com/OneCyrus/HotChocolateAuthorizeBug/blob/d3488e5639547758fe8df8085fc6c82eab7aa19b/HotChocolate.Authorize/Quickstart/Home/HomeController.cs#L31

this fails:
```
protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor.Field(t => t.Secured).Authorize(LocalApi.PolicyName);
```
https://github.com/OneCyrus/HotChocolateAuthorizeBug/blob/d3488e5639547758fe8df8085fc6c82eab7aa19b/HotChocolate.Authorize/GraphQL/Query.cs#L20

**To Reproduce**
there's a repro here: https://github.com/OneCyrus/HotChocolateAuthorizeBug
it has four unit tests which should pass but currently it looks like this:
![image](https://user-images.githubusercontent.com/7747800/84401176-40302d80-ac03-11ea-8026-b8ae2063e508.png)

**Expected behavior**
all four unit tests should pass

**Comment by michaelstaib** [comment]
Which version?

**Comment by michaelstaib** [comment]
ah ... is the `UseGraphQL` before or after UseAuthentication?

**Comment by OneCyrus** [comment]
it's like this and happens with with latest 10.4.x and 10.3.x (didn't test versions before that again)

```
app.UseRouting();
app.UseIdentityServer();
app.UseAuthorization();

app.UseGraphQL(new PathString("/graphql"));

app.UseEndpoints(endpoints =>
{
  endpoints.MapDefaultControllerRoute();
});
```

**Comment by sascha-andres** [comment]
Same here. We have not yet found a workaround. @OneCyrus did you found one?

**Comment by fbogensperger** [comment]
Found a workaround via AddQueryRequestInterceptor.

```csharp
services.AddQueryRequestInterceptor( async ( ctx, builder, ct ) => {
                                             var authenticateResult =
                                               await ctx.AuthenticateAsync( IdentityServerConstants.LocalApi.AuthenticationScheme );
                                             if ( authenticateResult.Succeeded )
                                               ctx.User = authenticateResult.Principal;
                                           } );
```

**Comment by michaelstaib** [comment]
We are using Identity Server in our project and it works just fine. We run it with Identity Server integrated into the server as well as with a separate entity server.

The `AddQueryRequestInterceptor` is the extension point to enrich the ClaimsPrincipal. This allows intercepting the request and adding context information.

**Comment by michaelstaib** [comment]
@OneCyrus will look at your repro tomorrow.

**Comment by OneCyrus** [comment]
> Found a workaround via AddQueryRequestInterceptor.
> 
> ```cs
> services.AddQueryRequestInterceptor( async ( ctx, builder, ct ) => {
>                                              var authenticateResult =
>                                                await ctx.AuthenticateAsync( IdentityServerConstants.LocalApi.AuthenticationScheme );
>                                              if ( authenticateResult.Succeeded )
>                                                ctx.User = authenticateResult.Principal;
>                                            } );
> ```

that looks simpler. we made one with a complicated virtual scheme.

**Comment by avisra** [comment]
@michaelstaib  I see this was closed - but was there ever a fix or resolution? I am running into this same problem. Is the AddQueryRequestInterceptor the recommended workaround?

**Comment by nikolasbeckel** [comment]
@avisra I don't know if it helps you, but after adding

```
mvcBuilder.Services
    .AddIdentity<IdentityUser, IdentityRole>()
    .AddEntityFrameworkStores<RhenaniaDbContext>()
    .AddDefaultTokenProviders();

mvcBuilder.Services
    .AddTransient(x => x.GetRequiredService<IDbContextFactory<RhenaniaDbContext>>().CreateDbContext());
```

to my services, the Authorization of HotChocolate doesn't work anymore. In my case the solution was to switch the order of `.AddAuthorization` and `.AddGraphQLServer`.

Correct order:
```
mvcBuilder.Services
    .AddAuthorization()
    .AddGraphQLServer()
```

Maybe it can help you or someone.

**Comment by kfrajtak** [comment]
Where does the `AddQueryRequestInterceptor` come from?
