### ISSUE TITLE
IQueryable<> query methods in local schema returns null values if used together with schema stitching

### ISSUE THREAD

**Issue by marian-margeta** [ChilliCream/hotchocolate#2055]
**Describe the bug**
I found a problem in version `11.0.0-preview.135`. I am exposing local schema with query that have a method with `IQueryable<>` return type:
```csharp
public class Obj
{
    public string? MyProperty { get; set; }
}

public class Query
{
    public IQueryable<Obj> GetValues() => new Obj[] {
        new Obj() { MyProperty = "1" },
        new Obj() { MyProperty = "2" }
    }.AsQueryable();
}
```
When I register only the local schema, everything works as expected
```csharp
services.AddGraphQL(SchemaBuilder.New()
    .AddAuthorizeDirectiveType()
    .AddQueryType<QueryType>()
    .ModifyOptions(o => o.RemoveUnreachableTypes = true)
    .Create());
```

But when I want to register this schema together with remote schema using schema stitching then all values returned from `Query.GetValues()` are null.
```csharp
services.AddGraphQLSubscriptions();
services.AddStitchedSchema(builder => builder
    .AddSchemaFromHttp("remoteSchema")
    .AddSchema("local", SchemaBuilder.New()
        .AddAuthorizeDirectiveType()
        .AddQueryType<QueryType>()
        .Create())
    .AddSchemaConfiguration(c =>
    {
        c.RegisterExtendedScalarTypes();
    }));
```
Request:
```graphql
{
  values {
    myProperty
  }
}
```
Response:
```json
{
  "data": {
    "values": [
      {
        "myProperty": null
      },
      {
        "myProperty": null
      }
    ]
  }
}
```

Note that this scenario works properly in version `10.4.3`.

**Desktop:**
 - OS: Windows 10
 - Version: 11.0.0-preview.135

**Comment by michaelstaib** [comment]
you can either add `services.AddGraphQL` or `services.AddStitchedSchema` in the same project.

**Comment by marian-margeta** [comment]
@michaelstaib I actually do so. My description may be unclear but I gave 2 separate examples how I register GraphQL - in the first case I use `services.AddGraphQL` to register "local" schema and this works fine. But in my application I want to register both - "local" and "remote" schema and expose it to my client together. I find out that it is possible by using `services.AddStitchedSchema`:

```csharp
services.AddStitchedSchema(builder => builder
    .AddSchemaFromHttp("remoteSchema") // Remote schema
    .AddSchema("local", SchemaBuilder.New() // Local schema
        .AddAuthorizeDirectiveType()
        .AddQueryType<QueryType>()
        .Create())
    .AddSchemaConfiguration(c =>
    {
        c.RegisterExtendedScalarTypes();
    }));
```

As I mentioned this works great with version `10.4.*`. But now I am forced to use preview version `11.0.0` as I use Strawberry client which is only available in version 11 and it has a common reference `HotChocolate.Language`.

**Comment by michaelstaib** [comment]
We are at the moment completely reworking schema stitching in 11 so we cannot help you with this at the moment. In the current preview build, schema stitching is at the moment completely gone. We hope to have it back by the end of next week.
