### ISSUE TITLE
Bad enum constant name generated

### ISSUE THREAD

**Issue by babyfish-ct** [ChilliCream/hotchocolate#2056]
If the C# enum constant name is 'FooBar', the enum constaint name of GraphQL generated automatically is 'FOOBAR', not the exepected value 'FOO_BAR'.

In order to generate the expected name, the C# constant name must be 'Foo_Bar', that brokes the naming rule of C# language.

**Comment by michaelstaib** [comment]
Hi, 

this is on our list and we are going to fix this.

**Comment by PejmanNik** [comment]
Hi, @michaelstaib Do you accept PR on this? I like to help

**Comment by fnolla** [comment]
Any update on this?

**Comment by fnolla** [comment]
Or at least a pure code workaround?

**Comment by jonrose-dev** [comment]
Also interested in any updates

**Comment by michaelstaib** [comment]
This one is fixed with the newest hc 11 preview build.

**Comment by michaelstaib** [comment]
I am closing this since it is fixed.
