### ISSUE TITLE
Directive is not applied to schema

### ISSUE THREAD

**Issue by ogliznutsa** [ChilliCream/hotchocolate#2057]
Hi,
I added custom directive `MyDirective` (with `DirectiveLocation.FieldDefinition`) and registered it (`.AddDirectiveType<MyDirective>()`).
Then I applied it to the object type field in `.Configure()`: `descriptor.Field(x => x.Department).Directive<MyDirective>();`.
The problem is that it is not shown in resulting schema for this field (e.g. in Playground).

I experimented with `DeprecatedDirective` as well - `@deprecated` appears in schema only if I apply it with `descriptor.Field(x => x.Department).Deprecated();` but not when I do `descriptor.Field(x => x.Department).Directive<DeprecatedDirective>();`

Sample code: https://github.com/ogliznutsa/GraphqlDirectives

\* HotChocolate v.10.4.3

**Comment by michaelstaib** [comment]
The introspection in GraphQL is not capable to show Schema directives.

**Comment by michaelstaib** [comment]
Or more correctly their annotations. There are discussions on the spec repro to allow for this

**Comment by ogliznutsa** [comment]
Thanks for clarification. I'm implementing validation for input objects and I though that it would be nice to expose validation requirements for the clients.
