### ISSUE TITLE
Exception on page info creation

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#2059]
**Describe the bug**
I am using 10.5.0-preview6

```gql
mutation {
  createUser(input: {name: "1234"}) {
    id
    name
    notes {
      nodes {
        id
        title
        content
        user {
          id
          name
        }
      }
    }
  }
}
```

Exception details:

"message": "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')",
"stackTrace": "   at System.Collections.Generic.List`1.get_Item(Int32 index)\r\n   at HotChocolate.Types.Relay.QueryableConnectionResolver`1.ResolveAsync(IMiddlewareContext context, IQueryable`1 source, ConnectionArguments arguments, Boolean withTotalCount, CancellationToken cancellationToken)\r\n   at HotChocolate.Types.Relay.ConnectionMiddleware`2.InvokeAsync(IMiddlewareContext context, IConnectionResolver`1 connectionResolver)\r\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler)"

**Additional context**

I tried to debug `GetSelectedEdgesAsync->...` tree, but not found more details. I guess there would be FirstOrDefault/bound checks like in previous versions

Preview version
![image](https://user-images.githubusercontent.com/46970457/84586869-87950480-ae23-11ea-8ff1-8d07ff74ca04.png)

Master version
![image](https://user-images.githubusercontent.com/46970457/84587199-dc397f00-ae25-11ea-9da6-04f93f6e8fb7.png)

**Comment by michaelstaib** [comment]
Great catch :) and good that you found this one :)

**Comment by michaelstaib** [comment]
This one is now fixed with:
https://github.com/ChilliCream/hotchocolate/releases/tag/10.5.0-preview.7
