### ISSUE TITLE
generate document playground not working

### ISSUE THREAD

**Issue by huudatk53** [ChilliCream/hotchocolate#2072]
i create class MyConfigNamingConventions : DefaultNamingConventions to change json result, but /playground document not working. How does Docs work again? tks.
![testing](https://user-images.githubusercontent.com/13384935/84888129-03f84380-b0c1-11ea-9c6d-897402ce1186.jpg)

**Comment by michaelstaib** [comment]
can you post your `MyConfigNamingConventions` code?

**Comment by huudatk53** [comment]
`public class MyConfigNamingConventions : DefaultNamingConventions
    {
        public MyConfigNamingConventions() : base()
        {

        }
        public MyConfigNamingConventions(IDocumentationProvider documentation) : base(documentation)
        {

        }
        // public override NameString GetArgumentName(ParameterInfo parameter){
        //     if (parameter == null)
        //         {
        //             throw new ArgumentNullException(nameof(parameter));
        //         }
        //     return parameter.Name;

        // }

        public override NameString GetMemberName(MemberInfo member, MemberKind kind)
        {

            if (member == null)
            {
                throw new ArgumentNullException(nameof(member));
            }

            if (member is PropertyInfo p)
            {
                return p.Name;
            }

            return base.GetMemberName(member, kind);
        }

    }`

**Comment by michaelstaib** [comment]
I will have a look tomorrow..

**Comment by michaelstaib** [comment]
We have now replaced playground with bcp.
