### ISSUE TITLE
Create and add Types on runtime

### ISSUE THREAD

**Issue by vtrihos** [ChilliCream/hotchocolate#2073]
So I was playing around the idea of generating types on runtime. Meaning, a user could create for example a "class" (more like a data structure being able to hold data) in a form with fields specified by the user.

Let's say for our example that those data would be held in-memory. 
Then, one could query for the metadata of the schema again and get the information for the new class.

Is there an elegant way at the moment to add a runtime type for that created class?

**Comment by michaelstaib** [comment]
This is supported by the new execution engine. While the schema is still immutable you can replace the schema with a new schema. We will have more on this once we have merged it. This is the PR to follow:
https://github.com/ChilliCream/hotchocolate/pull/1966
