### ISSUE TITLE
Slow first query after start up

### ISSUE THREAD

**Issue by mlstubblefield** [ChilliCream/hotchocolate#2077]
I'm having some troubles setting up a healthcheck to know when my graphql service is ready to have traffic from the old version shifted to the new one during a deployment.

What I'm noticing is that the first query to the service after a deployment takes a pretty significant amount of time.

I'm using code first and schema stitching, and locally it takes somewhere around 3 seconds before I get results. Then after that, everything is very snappy.

I'm assuming that it has to do with building some metadata/interpreting the query/response. Can I tell code first to cache these things before it serves traffic somehow?

**Comment by michaelstaib** [comment]
If you are using schema stitching then the first request will trigger the stitching by default. Basically the server fetches from the downstream services the schema and stitches them together. You can configure this to be done at startup or even at build time.

**Comment by mlstubblefield** [comment]
That's awesome! Can you give details on how to do that at startup. I'd love to configure that and don't see it in the docs here.
https://hotchocolate.io/docs/stitching

Also, I noticed that even when not including stitched fields in the response it's still slow. I assume that it's as you said and simply by extending the schema, it pays this price and it is what it is. Figured it's worth mentioning though.

On a side note, is it possible to tell hot chocolate to periodically check for schema changes on the stitched server? I suppose this has a downside of less deterministic schema changes, but we've run into some minor issues being caused by schema changes not propagating quickly and requiring a reboot of the server with the extended schema.

**Comment by mlstubblefield** [comment]
It's worth mentioning that I tried this and verified that the schema was cached on the client.
![image](https://user-images.githubusercontent.com/7562533/85163312-a7b43180-b230-11ea-9c81-5aa441a858ee.png)
But still experienced the slow time. I think it has something to do with the "execution plan" of the query.

**Comment by damikun** [comment]
@mlstubblefield  Are you sure that this is not the EF core behavior? Because i have first slow query because of EF core Inits... Can be seen without HC too..

**Comment by mlstubblefield** [comment]
I played around with a simple "hello world" type of example and saw it. I am seeing it in HC as well.

**Comment by michaelstaib** [comment]
Closing this issue ... we will have some new documentation around startup tuning with the release of version 11 at the end of October.

**Comment by mlstubblefield** [comment]
Exciting to hear! I look forward to version 11.

**Comment by hobjois** [comment]
> Closing this issue ... we will have some new documentation around startup tuning with the release of version 11 at the end of October.

Do you have any links to the new documentation? I couldn't find anything about startup tuning.

**Comment by tobias-tengler** [comment]
> Do you have any links to the new documentation? I couldn't find anything about startup tuning.

@hobjois Sadly there is non yet. It's on my radar though, just like 20 other topics :D
The first thing that comes to mind would probably be:
```csharp
services
    .AddGraphQLServer()
    .InitializeOnStartup()
```
This will "warmup" the GraphQL server when launching so the first query should be a lot faster. 
If other people in this thread or other members have more suggestions, please post them here. It'll also help me when doing the documentation, as I haven't looked at startup tuning yet...
