### ISSUE TITLE
Type Descriptor Context

### ISSUE THREAD

**Issue by codecantrell** [ChilliCream/hotchocolate#2082]
I am building a graph dynamically using reflection.  I need to pass data from a parent type descriptor to a child type descriptor during type resolution to set field names based on reflected data.  I want to iterate through the "reflected type fields" in the ChildGraphType Configure method and create graph fields accordingly.  Can I pass data as part of some descriptor context?  

    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
      ...
      var types = assembly.GetTypes();
      foreach(var type in types)
      {
        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Static);
        descriptor.Field(type.Name)
          .Resolver(ctx => fields)
          .Type<ChildGraphType>();
      }
    }

**Comment by michaelstaib** [comment]
All descriptors have an extension point called `descriptor.Extend()` this allows you to modify the underlying definition at specific points during the type initialization.

`descriptor.Extend().OnBeforeCreate(d => /*here you have raw access to the underlying definition*/);`

**Comment by michaelstaib** [comment]
Please close this issue if this answered your question.

**Comment by codecantrell** [comment]
What I need is to pass some context data from parent to child during type resolution, similar to the IResolverContext capability via scoped data at runtime.  I tried the "extend" as you suggest but have been unable to determine an approach.  

Basically, I want access descriptor.ContextData["dataFromParent"] in the child configure method. Then loop through that data to generate corresponding fields.  Below is my child descriptor definition.  My prior post is the parent descriptor code.  This will open up several possibilities for generating a graph using reflection.  

protected override void Configure(IObjectTypeDescriptor descriptor)
{
  ...
  var fields descriptor.ContextData["fieldsFromParent"] 
  foreach(var field in fields)
  {
    descriptor.Field(field.Name)
      .Resolver(ctx => field.Value)
      .Type<StringType>();
  }
}

Absolutely love your product!

**Comment by michaelstaib** [comment]
What do you mean by parent. The types have no parent. This is not a resolver. The type system initialization works completely different.

**Comment by michaelstaib** [comment]
Also there is a way to control field inference. Basically this is done through the type inspector. Can you maybe describe more what your aim is, it might be that it is simpler than what you are trying.

**Comment by codecantrell** [comment]
By parent, I simply mean parent node in the graph.  Right, it's not a resolver, otherwise I would have access to the ctx.Parent.  

We have an assembly, that is outside my team's control, with 500+ types defined where each has 50+ constants.  These types are presented in various dropdowns throughout our system.  Just trying to avoid coding each type manually.  I want the resulting graph to look like this.

The LookupContantsGraphType configure method is where I use reflection to enumerate the types in the assembly.  I need to pass the fields down to the child configure method, but need access to the type name during type initialization.

LookupConstants {
   ProductType: {
      productType1: field1Value;
      productType2: field2Value;
   },
   ProductCategory: {
      productCategory1: field1Value;
      productCategory2: field2Value;
  }
}

I have been able to successfully produce something like this, which is fine in this case.  I can think of a few more use cases where having access to the parent during type initialization would be nice.

LookupConstants {
   ProductTypes: [
      {
          key: 'productType1',
          value: 'field1value',
      },
      {
          key: 'productType2',
          value: 'field2value',
      }
   ]
   ...
}

**Comment by michaelstaib** [comment]
I think you just need to add the types and we will do that automatically for you. Basically, by default, we can infer those type structures.

**Comment by michaelstaib** [comment]
You even could just leave the types away and just add the .net types.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate-examples/tree/master/workshop/src/Server/PureCodeFirst

**Comment by codecantrell** [comment]
I can create a small code generator to create the schema types.  Like you mention, the type system will infer the fields for me, so it should be straight forward.  Thank you so much for your help!
