### ISSUE TITLE
ErrorPath override

### ISSUE THREAD

**Issue by m-khademloo** [ChilliCream/hotchocolate#2085]
**Describe the bug**
When we set a path on an error over an IMiddlewareContext, the path overridden by its parent

**To Reproduce**
Consider the following schema:
```
type User {
    id: ID! 
    username: String!
}
```
When the username is null, the error should be something like:
```
{
  "message": "Cannot return null for non-nullable field.",
  "locations": [
	{
	  "line": 4,
	  "column": 5
	}
  ],
  "path": [
	"user",
	"username"
  ],
  "extensions": {
	"code": "EXEC_NON_NULL_VIOLATION"
  }
}
```
but it currently response like this:
```
{
  "message": "Cannot return null for non-nullable field.",
  "locations": [
	{
	  "line": 2,
	  "column": 3
	}
  ],
  "path": [
	"user"
  ],
  "extensions": {
	"code": "EXEC_NON_NULL_VIOLATION"
  }
}
```
Or even when we call ReportError like this:
```
var builder = ErrorBuilder
    .New()
    .SetCode("test")
    .SetMessage("test")
    .SetPath(context.Path) //path is "/user/username"
    .SetException(new Exception("test"));

context.ReportError(builder.Build());
```
we got `Path="/user"` when we catch the error in `ErrorFilter`

**Expected behavior**
The `Path` should not be overridden 

**Desktop (please complete the following information):**
 - Version `10.4.3`

**Comment by benmccallum** [comment]
That could probably explain why when I was setting path on an error today with the result of `context.Path.Add(index)` it was never outputting the index :P 

Thanks for reporting!

**Comment by michaelstaib** [comment]
This is already fixed with the version 11 execution branch.

https://github.com/ChilliCream/hotchocolate/blob/611d9abdf17416bff4a083bf74b2b62b26ea77fb/src/HotChocolate/Core/src/Execution/MiddlewareContext.Global.cs#L133

With 11 when you pass in the error we will associate it internally with the field but not touch your error.

**Comment by michaelstaib** [comment]
I am closing this since it is fixed.
