### ISSUE TITLE
Correct way of using string enumerations

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2090]
I'm not sure I'm following the correct way of using string enumerations since I get some weird results with that. So, could you help me with the way?

I have a database object "Payment" which has a property "Type" with the only values "deposit" and "withdrawal". Since the only predefined values are possible I decided to expose that property in graphQL API as a string enum:
`
public class PaymentKindEnumType : EnumType<string>
    {
        protected override void Configure(IEnumTypeDescriptor<string> descriptor)
        {
            descriptor.Name("PaymentKind");
            descriptor.Value("deposit").Name("deposit");
            descriptor.Value("withdrawa'").Name("withdrawal");
        }
    }

public class PaymentType : ObjectType<Payment>
    {
        protected override void Configure(IObjectTypeDescriptor<Payment> descriptor)
        {
            descriptor.Field(t => t.Type).Type\<PaymentKindEnumType\>();
        }
    }
`

But the result which I can see in voyager is that **all string properties** have become of PaymentKind type and of course it causes multiple parse exceptions.
How can I assign PaymentKind to only "Type" property of the class "Payment"?

**Comment by michaelstaib** [comment]
Do you still have this issue?

**Comment by tobias-tengler** [comment]
Closing, as this is now covered by the documentation:
```csharp
public class UserRoleType : EnumType<string>
{
    protected override void Configure(IEnumTypeDescriptor<string> descriptor)
    {
        // we need to specify a name or otherwise we will get a conflict
        // with the built-in StringType
        descriptor.Name("UserRole");

        descriptor
            .Value("Default")
            .Name("Standard");
    }
}

public class QueryType : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Name(OperationTypeNames.Query);

        descriptor
            .Field("users")
            .Argument("role", a => a.Type<UserRoleType>())
            .Resolve(context =>
            {
                var role = context.ArgumentValue<string>("role");

                // Omitted code for brevity
            });
    }
}
```

[Link to documentation](https://chillicream.com/docs/hotchocolate/defining-a-schema/enums)
