### ISSUE TITLE
UseFiltering() implicit binding doesn't work as intended and ignores type name.

### ISSUE THREAD

**Issue by JTinkers** [ChilliCream/hotchocolate#2092]
**Describe the bug**
Using `IObjectFieldDescriptor.UseFiltering<Type>(x => x.BindFieldsImplicitly())` seems to have no effect on the generated schema.

The generated filter object is empty and only has 'AND' and 'OR' fields.

In addition, it seems to ignore names set on types it's meant to filter, ex: ArticleType with name set to 'Article' will generate 'ArticleTypeFilter' as opposed to desired 'ArticleFilter'.

**To Reproduce**
1. Set 'DefaultBindingBehavior' to 'BindingBehavior.Implicit' as seen in the code below:
`services.AddGraphQL(SchemaBuilder.New()
	[...]
	.ModifyOptions(x => x.DefaultBindingBehavior = BindingBehavior.Implicit);`
2. Open your QueryType and add the code below to anything that is filterable (returns a list):
`.UseFiltering<Type>(x => x.BindFieldsImplicitly());`
3. Open playground to see the schema, in result you should have a wrongly named, almost empty filter.

**Expected behavior**
If I set the default behavior to Explicit, but then tell filtering to use implicit binding for a specific type - it should map all fields of the provided type implicitly as requested.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context:**
If the explanation is unclear, here's my thread on slack: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1593335816138400

**Comment by PascalSenn** [comment]
@JTinkers  The new filtering does not have this issue, but i fixed it in the legacy filtering in #2431

**Comment by michaelstaib** [comment]
Can we close this one?
