### ISSUE TITLE
Offset (skip-take) Paging. Out of the box support

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2094]
**Is your feature request related to a problem? Please describe.**
Despite the fact that the cursor style of pagination and navigation between edges is a powerful model there are plenty of cases when not only the sequential navigation but also random page access is needed. Actually, lots of less loaded than Facebook applications do need displaying the page numbers of lists as well as random navigation between them.
For that reason, I believe it would be worthwhile to have such functionality out of the box, i.e. similar to relay-style cursors support of extensions allowing to declaratively add that functionality to lists.

I have implemented an initial version of that functionality and created a pull request which I would like the maintainers to review.

**Describe the solution you'd like**
The solution is technically similar to relay-style paging. It can apply paging to IQueryable<T> and IEnumerable<T>.
Can be used as:
1. attribute like this:
`
        [UseOffsetPaging]
        public IQueryable<Payment> Payments { get; set; }
`
2. extension of IObjectFieldDescriptor or IInterfaceFieldDescriptor. 
`
public static class OffsetPagingObjectFieldDescriptorExtensions
{
public static IObjectFieldDescriptor UseOffsetPaging<TType>(this IObjectFieldDescriptor descriptor)
{
...
}
}
`

TType can be either CLR Type or Schema Type which makes using that extension pretty convenient. Once you have schema type defined you could use it like this:
`
descriptor.Field(t => t.Payments).UseOffsetPaging<PaymentType>()
`
But if you don't have schema type you can still use that extension with direct reference to CLR type:
`
descriptor.Field(t => t.Payments).UseOffsetPaging<Payment>()
`

In order the paging is correctly defined on a list it is translated into "CollectionSlice" object which accepts two parameters "skip" and "take" and consists of two fields Nodes  and totalCount (both fields have the same meaning as in relay-style), i.e. requesting something like:
`  payments(take: 2, skip: 3)
    {
      totalCount,
      nodes
      {
        id,
        provider
      }    
    }`

has to return something like: 

` "payments": {
          "totalCount": 184,
          "nodes": [
            {
              "id": 5,
              "provider": "awesome provider"
            },
            {
              "id": 6,
              "provider": "not very awesome provider"
            }
          ]
        }`

"take", "skip" or both can, of course, be omitted. Also, the implementation is compatible with sorting and filtering, so, defining payments like 
 ` descriptor.Field(t => t.Payments).UseOffsetPaging<PaymentType>().UseFiltering().UseSorting()`
it becomes possible to make requests like:
`payments(take: 2, skip: 3, order_by: {id: ASC}, where: {provider: "awesome provider"})...`

[PR](https://github.com/ChilliCream/hotchocolate/pull/2096) with the implementation is attached to that issue. You can see that no one line of the existing code has been changed (only additions have been made) so the feature shouldn't cause any regression of the existing functionality.
Thanks in advance.

**Comment by michaelstaib** [comment]
This fearure is now merged.

**Comment by jeffason1997** [comment]
Is this feature also available in v11?

**Comment by PascalSenn** [comment]
@jeffason1997  yes, `[UseOffsetPaging]` or `.UseOffsetPaging`
