### ISSUE TITLE
How to use the upcoming federation support?

### ISSUE THREAD

**Issue by Tall-Paul** [ChilliCream/hotchocolate#2098]
Hi, 

After some digging I see that federation support is on the roadmap for HC11.0 via this branch: https://github.com/ChilliCream/hotchocolate/tree/feat-apollo-federation-support

However, I need it now..... I've pulled that branch down, built it and added the resulting packages into my project.  If I'm using schema first, can I just define a schema with the external / key etc directives and HC will know what to do with them?  Is there support for resolving references yet?

**Comment by michaelstaib** [comment]
It is not fully implemented and will not work.

**Comment by michaelstaib** [comment]
@dillanmann is leading the effort here and might have some more to say on it. Furthermore, it is not clear if this feature will make the cut for 11.0, it might be moved to a later version. However, we always need helping hands on our efforts, so if you want to help to implement this you can join our slack channel and I can set you up with @dillanmann who did the initial parts of it.
