### ISSUE TITLE
Hot Chocolate docs and schema not loading

### ISSUE THREAD

**Issue by gurdeepsira** [ChilliCream/hotchocolate#2100]
**Describe the bug**

I am using Hot Chocolate 10.43. However, when clicking the schema or docs section nothing loads. In Firefox dev tools, an "unexpected error" error comes up, but no more details.

**To Reproduce**

I have the following startup:

           services.AddDataLoaderRegistry();

            // Add GraphQL Services
            services.AddGraphQL(s => SchemaBuilder.New()
                .AddServices(s)
                // enable for authorization support
                // .AddAuthorizeDirectiveType()
                .AddType<BookingType>()
                .AddType<CourtesyCarType>()
                .AddType<CourtesyCarBookingsType>()
                .AddType<DeliveryOptionsType>()
                .AddQueryType<BookingQuery>()
                .Create()).AddErrorFilter(error => {
                    Console.WriteLine(error.Exception);
                    return error;
                });

And:

            app
                .UseRouting()
                .UseGraphQL("/api")
                .UsePlayground();

**Expected behavior**

The docs and schema section works and loads, the spinner goes away.

What am I missing?

Thanks!

**Comment by michaelstaib** [comment]
Do you have a schema exception when the schema is built on the first request?

**Comment by gurdeepsira** [comment]
I don't see any exceptions from the server side? Is there a way I should be catching that?

Sorry new to Hot Chocolate!

**Comment by PascalSenn** [comment]
Closes this as it appears to be stale
@gurdeepsira  in case you still have issues, reach out to us on slack or open a new issue :)
