### ISSUE TITLE
Need away to set value of request.credentials for GraphQL Playground

### ISSUE THREAD

**Issue by AgrawalAshishS** [ChilliCream/hotchocolate#2101]
I am using Playground with graph queries that are required to be authorized. In my project, I have Cookie-based authentication. What I found is Playground doesn't work well with such a scenario. During debugging I found it is not sending any cookies to the server with require. From what I see possible reason is a default setting request.credentials in set to "omit". We need to have a way to set it to "same-origin" or "include"

**Comment by michaelstaib** [comment]
You can always just use the npm package of playground and then integrate it yourself. With that, you are more flexible.
