### ISSUE TITLE
Possible bug filtering nested entities

### ISSUE THREAD

**Issue by arminneman** [ChilliCream/hotchocolate#2102]
```
query {
  customerById (id: 1123864) {
    debiteurNr
    bank (where: {standaard: 1}) {
      iBAN,
      bIC,
      standaard
    }
    bankAuthorization (where: {standaard: 1}) {
      code
      status,
      standaard
    }
  }
}
```
If I leave the standaard attribute out of the select, I get null back for bank and bankAuthorization

```
query {
  customerById (id: 1123864) {
    debiteurNr
    bank (where: {standaard: 1}) {
      iBAN,
      bIC
    }
    bankAuthorization (where: {standaard: 1}) {
      code
      status
    }
  }
}
```

Expected out come:
(even if the attribute is left out of the select)
```
{
  "data": {
    "customerById": {
      "debiteurNr": 783022,
      "bank ": [
        {
          "iBAN": "NL02INGB0000005125",
          "bIC": null,
        }
      ],
      "bankAuthorization ": [
        {
          "code": "20171113EH5000034367",
          "status": "A",
        }
      ]
    }
  }
}
```
using:
hotchocolate.aspnetcore version 10.4.3
hotchocolate.types.selections version10.4.3
BananaCakePop-1.0.0-preview.3
microsoft.entityframeworkcore version 3.1.5

```
   [ExtendObjectType(Name = "Query")]
    public class CustomerQueries
    {
        [UseFirstOrDefault]
        [UseSelection]
        [UseFiltering]
        public IQueryable<DbKlant> GetKlantenById([Service] KlantCentraalContext context, int id) =>
            context.Klanten.Where(o => o.Id == id);
    }
```

```
 [Table("tblKlant")]
    public class DbKlant
    {

        [Key]
        public int Id { get; set; }
        public int DebiteurNr { get; set; }

        [UseFiltering]
        public virtual IEnumerable<DbKlantBank> bank  { get; set; }

        [UseFiltering]
        public virtual IEnumerable<DbKlantBankMachtiging> bankAuthorization  { get; set; }
    }
```

The SQL query that gets executed on the sqldatabase seems to be correct. It looks like graphql filtering is done based on the selected fields. So if a field is not selected it might be considered null in the filtering process?

**Comment by TheJayMann** [comment]
Most likely you have Filtering and Select in the wrong order.  I can't remember the correct order off the top of my head, but, if Select runs before Filter, then any item not selected will have a value of `default` assigned, and, when filtered afterwards, will not match any filter except `default`.  Try moving your Filter declaration to be on the other side of your Select declaration and see if it works.

**Comment by PascalSenn** [comment]
@arminneman  can you share some code?

**Comment by arminneman** [comment]
> @arminneman can you share some code?

I added some code, mostly 

> @arminneman can you share some code?

Added some code, if you're interested in something specific, let me know.

**Comment by PascalSenn** [comment]
@arminneman  looks good, do you have a repro?

**Comment by michaelstaib** [comment]
I think I can even reproduce this with our blog example @PascalSenn.

**Comment by TheJayMann** [comment]
I haven't pieced together the full process, but I see that the Selection middleware uses IListHandler in order to handle things such as filtering and sorting when applied to nested list properties.  What should be happening is that the ListHandler should complete its handling of the list property before the selection middleware completes its handling of the list property.  The generated expression for the `bank` property should be:
```csharp
bank =
    k.bank
    .Where(b => b.standaard == 1)
    .Select( b => new bank() {
        iBAN = b.iBAN,
        bIC = b.bIC
    })
,
```
It sounds like what is actually being produced is:
```csharp
bank =
    k.bank
    .Select( b => new bank() {
        iBAN = b.iBAN,
        bIC = b.bIC
    })
    .Where(b => b.standaard == 1)
,
```

**Comment by PascalSenn** [comment]
This should be resolved in v12
