### ISSUE TITLE
F# discriminated union support 

### ISSUE THREAD

**Issue by aammfe** [ChilliCream/hotchocolate#2103]

**Comment by michaelstaib** [comment]
Can you elaborate on your request?

**Comment by TheJayMann** [comment]
I would assume the request is to allow this as a GraphQL union type.

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwBcBPABxgAIBlACwENyKBeAWACh8KBhASyjAyUI2CgCU6AEx4BXXDgwQ6hdpyoBHaXVgVhFADIwAdgHNCNeYuUcxMMITonBOkQZNmLSigCoKAdR4S7tgKSkA=

Getting it to work without taking a dependency on FSharp.Core might be difficult, but should be possible.

**Comment by aammfe** [comment]
> I would assume the request is to allow this as a GraphQL union type.
> 
> https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwBcBPABxgAIBlACwENyKBeAWACh8KBhASyjAyUI2CgCU6AEx4BXXDgwQ6hdpyoBHaXVgVhFADIwAdgHNCNeYuUcxMMITonBOkQZNmLSigCoKAdR4S7tgKSkA=

yep




> Getting it to work without taking a dependency on FSharp.Core might be difficult, but should be possible.

THANX :)

**Comment by adelarsq** [comment]
Also interested on this. Any update?

**Comment by michaelstaib** [comment]
Can anybody set a test project up for us? 

Create a PR that adds and F# test project that creates a schema with the expected union structure. We can then add the support for that.

**Comment by timotheegloerfeld** [comment]
Hi there, I'm also very much interested in this. Are there any updates? Is this the test project used: https://github.com/adelarsq/hotchocolate_fsharp_sample ? If so, is there anything I can do to contribute?

**Comment by michaelstaib** [comment]
@timotheegloerfeld you are welcome to help on this. I have already looked at how we can implement this. What we really need  is a new unit-test project for F#. If you are interested to help set this up give me a ping. Bets join us on slack ... 

https://bit.ly/joinchilli

**Comment by michaelstaib** [comment]
We have started work  on this one.

**Comment by AlexeyRaga** [comment]
Any update on the matter? ;)

**Comment by michaelstaib** [comment]
Help would be appreciated. Are you on slack? 

slack: https://bit.ly/joinchilli 

we can have a chat on this there.

**Comment by AlexeyRaga** [comment]
@michaelstaib I think that I can register, but I am in an opposite time zone (Australia) so synchronous chat could be not that easy :)
If there can be a list of tasks with short description about what and where needs to be done, it'd be very helpful.

**Comment by adelarsq** [comment]
@michaelstaib Any update on this?
Because I have interested on this but I am a little off by health issues. I will try to help when possible.

**Comment by AlexeyRaga** [comment]
@michaelstaib Any chance for having the branch updated anytime soon?

**Comment by adelarsq** [comment]
@michaelstaib Any update regardless of this?
