### ISSUE TITLE
Exposing query params in IResolverContext

### ISSUE THREAD

**Issue by raorob** [ChilliCream/hotchocolate#2104]
Problem:
When one wishes access of query params inside a Resolver, it is not really comfortable to get the params from IResolverContext

Solution:
IResolverContext has a method like "T GetQueryParam\<T\>(string name)"
The method has some special treatments for enums.

As I needed this method in our project I have already coded the solution and I integrated the code already in hotchocolate. If you are interested, we can push my branch.

**Comment by michaelstaib** [comment]
Hi @raorob,

what do you mean with query param exactly?

Http Query Parameters?

**Comment by raorob** [comment]
Hi Michael,

In the GraphQL spec they call them “arguments”.

{
  picture(height: 100, width: 200)
}

“height” and “width” are query params or “arguments” 😊



Von: Michael Staib <notifications@github.com>
Gesendet: Freitag, 3. Juli 2020 17:01
An: ChilliCream/hotchocolate <hotchocolate@noreply.github.com>
Cc: raorob <rao@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ChilliCream/hotchocolate] Exposing query params in IResolverContext (#2104)


Hi @raorob<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fraorob&data=02%7C01%7C%7Cdb5c34ec3dc94515c94608d81f61d887%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637293852384378846&sdata=BYyAlXqmPMrCxbQfrQYDD0OzOplAR0c%2FQl9yOh2%2BF9o%3D&reserved=0>,

what do you mean with query param exactly?

Http Query Parameters?

**Comment by michaelstaib** [comment]
Then we don’t you use context.Argument<T>(name)?

**Comment by raorob** [comment]
Indeed! 😊
Thx anyway

Von: Michael Staib <notifications@github.com>
Gesendet: Samstag, 4. Juli 2020 10:08
An: ChilliCream/hotchocolate <hotchocolate@noreply.github.com>
Cc: raorob <rao@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ChilliCream/hotchocolate] Exposing query params in IResolverContext (#2104)


Then we don’t you use context.Argument(name)?

**Comment by raorob** [comment]
Ok. I used the Argument method. It works fine. Thx

Please use always verbs in method names (see also here https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods)

It makes it easier for developers to find what they are looking for (GetArgument would catch immediately developer‘s eye).

Cheers
Roberto

Am 04.07.2020 um 10:08 schrieb Michael Staib <notifications@github.com>:

﻿

Then we don’t you use context.Argument(name)?
