### ISSUE TITLE
Support X-Apollo-Tracing header

### ISSUE THREAD

**Issue by vbornand** [ChilliCream/hotchocolate#2106]
**Is your feature request related to a problem? Please describe.**
If the tracing is enabled with the mode `TracingPreference.OnDemand`, the tracing result is not displayed in the playground by default.

**Describe the solution you'd like**
The playground sends a header `X-Apollo-Tracing = 1` when the tracing pane is open. It is not possible to define another header in the playground settings because this value is hardcoded (https://github.com/prisma-labs/graphql-playground/blob/master/packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts#L128).

I would like hotchocolate returns the tracing data if the header `X-Apollo-Tracing = 1` is set.

There are 2 solutions:
- Replace the current header `GraphQL-Tracing` by `X-Apollo-Tracing`
- Add the support for `X-Apollo-Tracing`, and keeping the support for `GraphQL-Tracing` for backward compatibility.

**Describe alternatives you've considered**
Add `"X-Apollo-Tracing": "1"` in the HTTP headers in the playground, but the value is sent even if the tracing pane is closed.

**Comment by michaelstaib** [comment]
This one is now implemented with version 11.0.0-dev.2 and will be soon merged into the 11.0.0-preview.140

**Comment by michaelstaib** [comment]
We opted for: Add the support for X-Apollo-Tracing, and keeping the support for GraphQL-Tracing for backward compatibility.
