### ISSUE TITLE
Rust relay-compiler new persisted query support

### ISSUE THREAD

**Issue by maraisr** [ChilliCream/hotchocolate#2107]
Relay's new rust compiler, the next generation for relay now instead of persisting queries to disk as json. It now POST's the query text to a server, and asks it to give back an id.

The idea as confirmed by @kassens is to store this query text, and ID indefinitely in some database or whatever. The compiler, if it has an id _wont_ tell this to the server again. But I feel there will be a _force_ resend of the queries, and maybe a future fallback to json files on disk.

Never the less the implementation is:

- At compile-time (`relay-compiler`), every query for a project that is marked to persist. Will POST to a config driven endpoint.
- The POST will contain form-data, of `text={query}`.
- Also through config, you can specify extra params to be send, which I dare say is for meta or anything. So I guess HC will just ignore extra fields—or make use of it.
- The endpoint must then respond with `application/json`, and `{ "id": "<some-id>" }` - or an object for errors `{ "error": "..." }`
- Relay will then _relay_ this id, in a similar fashion to what it was before—the `doc_id` param.

Further readings:
- https://github.com/facebook/relay/blob/master/compiler/crates/persist-query/src/lib.rs#L39-L73
- https://github.com/facebook/relay/blob/master/compiler/crates/relay-compiler/src/config.rs#L396-L402

**Comment by michaelstaib** [comment]
@artola fyi
