### ISSUE TITLE
Using UseSelection with subscription

### ISSUE THREAD

**Issue by MysticFragilist** [ChilliCream/hotchocolate#2108]
Hi,

I want to start with a big thank you for your library, it's really time saving and really great to use! I've been using HotChocolate 10.4.3 and EntityFrameworkCore 3.1.5 for my newly project and I had an issue regarding the attribute [UseSelection] on a custom subscription (using IEventMessage). I've followed [this article](https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i) to setup my environment which was really helpful.

I've tested it on queries and it's all going great. The thing is that I need to access entity nested inside another entity when getting response from a subscription. Code example:
```cs
// Mutation
public async Task<UpdateDevicePayload> UpdateDevice(
       UpdateDeviceInput input,
       [Service]IRepository<Device> repository,
       [Service]IEventSender eventSender)
{
       Device updatedDevice = await repository.Update(input.Id, input);
       await eventSender.SendAsync(new OnDeviceMessage(updatedDevice ));
       return new UpdateDevicePayload(realDevice);
}

// Subscription
[UseSelection]
public Device OnDevice(
        int deviceId,
        IEventMessage message)
{
    return message.Payload;
}
```
When I launch my subscription, it's listening which means it is fine, but once I launch the updateDevice mutation, the subscription receive this error:
```json
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "onDevice"
      ],
      "extensions": {
        "message": "Value cannot be null. (Parameter 'source')",
        "stackTrace": "   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)\r\n   at HotChocolate.Types.Selections.SelectionMiddleware`1.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Types.Relay.QueryableConnectionMiddleware`1.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler)"
      }
    }
  ],
  "data": {
    "onDevice": null
  }
}
```
My question is just to know if UseSelection is supported on subscription and what am I missing. if it is not, I'll adapt my workflow accordingly (fetch 1 time once the result has arrived).
 
Thanks!
Samuel

**Comment by michaelstaib** [comment]
The thing here is that `UseSelection` works on `IQueryable` not just on anything. So, if the subscription message, for instance, would be an Id and you would then use the DBContext in your case to fetch data with that id it would work.

**Comment by michaelstaib** [comment]
can we close this issue?

**Comment by MysticFragilist** [comment]
I still can't manage to make it work, but I found a workaround so you can close it.

Just to make it clearer, my schema behind is 1 "Device" connect to multiple "Pattern" (ICollection) and 1 "Pattern" connect to multiple "PatternArgument" (ICollection). When I do so when I subscribe without UseSelection I can access the Pattern collection fine but all the patternArgumentsCollection is null each time.

As I said, it was not that big of a deal, on my frontend I launch a second query following the subscription reception.

Thanks for the quick reply!
