### ISSUE TITLE
schema first from multiple files

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2109]
I tried to split graqhql language code in multiple files like this:

a.graphql:
type Query{
   hello: String!
}

b.graphql:
type Query{
   hi: String!
}

and  typed code like this in gateway, but  i get an error  
" HotChocolate.SchemaException:“The name `Query` was already registered by another type. - Type: Query":

services.AddGraphQL(sp => SchemaBuilder.New()
    .AddDocumentFromFile("a.graphql")
    .AddDocumentFromFile("b.graphql")
    .BindComplexType<Query>()
    .Create());

**Comment by zivfuture** [comment]
anyone can help ?

**Comment by vbornand** [comment]
If you define the same type in multiple file, you have to add "extend" before the type definition in the b file.

More details here: https://www.apollographql.com/blog/modularizing-your-graphql-schema-code-d7f71d5ed5f2

**Comment by zivfuture** [comment]
> If you define the same type in multiple files, you have to add `extend` before the type definition in the _b.graphql_ file.
> 
> _a.graphql_:
> 
> ```graphql
> type Query{
>   hello: String!
> }
> ```
> 
> _b.graphql_:
> 
> ```graphql
> extend type Query{
>   hi: String!
> }
> ```
> 
> More details about this : https://www.apollographql.com/blog/modularizing-your-graphql-schema-code-d7f71d5ed5f2

Thanks for reply.
I do as you said and get a new error:
{
    "errors": [
        {
            "message": "The field `hi` does not exist on the type `Query`.",
            "locations": [
                {
                    "line": 7,
                    "column": 5
                }
            ]
        }
    ]
}

**Comment by vbornand** [comment]
I think you have another issue.

This following code works:
```cs
class Program
    {
        static void Main(string[] args)
        {
            var sb = SchemaBuilder.New().AddDocumentFromFile("a.graphql")
            .AddDocumentFromFile("b.graphql")
            .AddResolver("Query", "hi", "Earth")
            .AddResolver("Query", "hello", "World")
            .Create();

            var r = sb.MakeExecutable().Execute("{ hi\nhello\n }");
            Console.WriteLine(r.ToJson());
        }
    }
```

Result:
```js
{
  "data": {
    "hi": "Earth",
    "hello": "World"
  }
}
```

Can you please share more code or create a github repo with your code?

**Comment by michaelstaib** [comment]
We haven’t support for extend on sdl first yet. There is however a big update coming to sdl first. We will soon start discussing sdl first in v11

**Comment by michaelstaib** [comment]
Join our slack channel

**Comment by michaelstaib** [comment]
Closing this issue since splitting types in sdl first is not supported in 10

**Comment by oising** [comment]
Is it support for v11?
