### ISSUE TITLE
Support for namespace per client in Client API

### ISSUE THREAD

**Issue by keerthivasanm** [ChilliCream/hotchocolate#2110]
**Is your feature request related to a problem? Please describe.**
I have 3 clients in a single project. Code generation results in conflicts and I had to use Resharper's adjust namespaces in folder suggestion to get rid of conflicts.

**Describe the solution you'd like**
An option in `berry.json` for namespace would be nice. It can extend the root namespace by default w/o any configuration. Say ClientA would take `$RootNameSpace.ClientA.Generated` and can be overridden in `berry.json` for that client.

**Describe alternatives you've considered**
Using ReSharper to adjust namespaces after code generation is the present mitigation.

**Comment by michaelstaib** [comment]
This is on our list internally but it is good to have your issue now. The CLI too actually already has this capability but we have to bring it into the project system.
