### ISSUE TITLE
Allow automatic schema generation for 'bundle' types like tuples, anonymous objects etc.

### ISSUE THREAD

**Issue by JTinkers** [ChilliCream/hotchocolate#2113]
**Is your feature request related to a problem? Please describe.**
It's not much as much of a problem as it would be an improvement to the overall workflow.
The feature would reduce code and simplify abstraction greatly.

**Describe the solution you'd like**
I would like to be able to return tuples and anonymous objects through my queries, subscriptions, and mutations.
Being able to have a mutation called `BanUser(int userId, string reason, long length)` and be able for it to return `UserType` and `BanType` without having to create `UserBanType` would greatly reduce the amount of code that has to be written

**Describe alternatives you've considered**
Creating ObjectTypes for every return type.

**Comment by PascalSenn** [comment]
@JTinkers  Can you elaborate on this one. You usually do not need to create ObjectTypes  unless you have Implicit Binding activated.

**Comment by JTinkers** [comment]
> @JTinkers Can you elaborate on this one. You usually do not need to create ObjectTypes unless you have Implicit Binding activated.

I think you mean Explicit Binding, but in fact - in both cases, I can't use tuples because it would pop an error about being unable to define the type for `ValueTuple<User, string>`
