### ISSUE TITLE
Pagination and PaginationAmount seems to be broken

### ISSUE THREAD

**Issue by JTinkers** [ChilliCream/hotchocolate#2115]
**Describe the bug**
I've set global pagination to 64, but I can only fetch 32 entries.
Setting it to 66 allows me to fetch 33 entries.

**To Reproduce**
1. Set global pagination to 64
2. Try fetching 32 of any resource
3. Try fetching 33 of any resource

**Additional context**

Here's the query:
```
query {
  tags(first: 33) {
    nodes {
      id
      name
    }
  }
}
```

**Comment by ademchenko** [comment]
Hi, @JTinkers . What is global pagination? I can't find a way to set global pagination in HotChocolate. Could youm please, provide an example of that?

**Comment by PascalSenn** [comment]
@ademchenko  
you can specify a global max for paging:
```csharp
.Type(new PaginationAmount(30)); 
```

**Comment by ademchenko** [comment]
@PascalSenn , I assume you mean:
`.AddType(new PaginationAmountType(2))`
But it doesn't seem to be usable since adding that global type causes all integer fields across the schema to become of that type.

**Comment by JTinkers** [comment]
> @PascalSenn , I assume you mean:
> `.AddType(new PaginationAmountType(2))`
> But it doesn't seem to be usable since adding that global type causes all integer fields across the schema to become of that type.

You have to bind int ClrType via `.BindClrType<int>()`.

I know it's not ideal and adding pagination shouldn't do such things, but it works.

**Comment by ademchenko** [comment]
Okay, this way
```
.AddType(new PaginationAmountType(4))
                    .BindClrType<int, IntType>()
```
it doesn't work as well. The collection with no arguments is just not being filtered. So, I think, @JTinkers  the feature is completely not working.

**Comment by JTinkers** [comment]
> Okay, this way
> 
> ```
> .AddType(new PaginationAmountType(4))
>                     .BindClrType<int, IntType>()
> ```
> 
> it doesn't work as well. The collection with no arguments is just not being filtered. So, I think, @JTinkers the feature is completely not working.

I've mentioned it to @PascalSenn before, the workaround worked for me thought.

Have you tried different order? (move Pagination below BindClrType).

I don't know if that would make difference, and since order of UsePagination, UseSorting, and UseFiltering does.

**Comment by ademchenko** [comment]
@JTinkers, yes, I tried both orders.

**Comment by michaelstaib** [comment]
> I know it's not ideal and adding pagination shouldn't do such things, but it works
It actually should not. Consider custom scalars here. We could with that override a binding from a user. BindClrType<int, CustomInt>().

However, PaginationAmount should not bind as an int, which is already fixed on the master.

**Comment by michaelstaib** [comment]
> Have you tried different order? (move Pagination below BindClrType).

The order does not matter in this case.
