### ISSUE TITLE
Is the document for Subscription obsoleted?

### ISSUE THREAD

**Issue by rex-pj** [ChilliCream/hotchocolate#2116]
I am working on version 10.4.3
And I am following this document [https://hotchocolate.io/docs/code-first-subscription](https://hotchocolate.io/docs/code-first-subscription) for **Subscriptions**, but might it out of date because IEventMessage, IEventSender are obsoleted, do you have any new instruction for Subscriptions?

![image](https://user-images.githubusercontent.com/16367896/86990779-8effc180-c1c7-11ea-8b61-e977da5f16d7.png)

**Comment by vsylvestre** [comment]
I've been playing with subscriptions for the past few days and managed to get something working. The documentation is not up to date. Hopefully this can help you as well:

I added the line `services.AddInMemorySubscriptions();` inside of my ConfigureServices method in my Startup.cs, and `app.UseWebSockets();` in Configure. (The first one caused me a lot of headaches: note that it is **not the same** as the one found in the documentation on subscriptions.)

I have a Subscription.cs file written as such:

```
using HotChocolate;
using HotChocolate.Subscriptions;
using HotChocolate.Types;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Schema
{
    public class Subscription
    {
        [SubscribeAndResolve]
        public async ValueTask<IAsyncEnumerable<string>> EventRaised(
            [Service]ITopicEventReceiver eventReceiver,
            CancellationToken cancellationToken) =>
            await eventReceiver.SubscribeAsync<string, string>("EventName", cancellationToken);
    }
}
```

And, from my mutation, I publish an event like so:

```
using System.Threading.Tasks;
using HotChocolate;
using HotChocolate.Subscriptions;

namespace Schema
{
    public class Mutation
    {
        public async Task<bool> Update([Service]ITopicEventSender eventSender)
        {
            await eventSender.SendAsync("EventName, "test");

            return true;
        }
    }
}
```

Also make sure that you import the `HotChocolate.Subscriptions.InMemory` package.

Hope this helps.

**Comment by ddieppa** [comment]
@delta-it Same is happening to me, in Visual Studio and Rider, using HC 10.4.3
@vsylvestre do you have a repo where to check how you got everything working?
Also ask the same in the [slack](hotchocolategraphql.slack.com) channel: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1594419457333400

**Comment by delta-it** [comment]
Hi @ddieppa and @vsylvestre 
**This is my subscription:**
![image](https://user-images.githubusercontent.com/16367896/87249465-7a525080-c489-11ea-8a66-627ecbd1d700.png)


**This is my Subscription Type:**
![image](https://user-images.githubusercontent.com/16367896/87249455-61499f80-c489-11ea-8fb9-bc195afe3aa6.png)


**I already config on Startup.cs**
![image](https://user-images.githubusercontent.com/16367896/87249441-4e36cf80-c489-11ea-9d55-2982632b0458.png)
and
![image](https://user-images.githubusercontent.com/16367896/87249478-876f3f80-c489-11ea-86db-4440a2ff7d73.png)

But after I try to run the Playground, I got this message:
![image](https://user-images.githubusercontent.com/16367896/87249529-c7362700-c489-11ea-9ad7-b8cec10f6096.png)

**Comment by ddieppa** [comment]
Try this:
```c#
add.UseGraphQL("/graphql");
add.UsePlayground("/graphql", "/playground");
```
I think as you defined the _"/graphql"_ path as the endpoint you have to tell **playground** where to query

**Comment by delta-it** [comment]
@ddieppa yeah, it's working now, thank you!

**Comment by ademchenko** [comment]
@delta-it , Playground have [the issue](https://github.com/ChilliCream/hotchocolate/issues/1806) with path when using subscriptions, so, if you want to use playground on "/graphql/playground" you have to add a trailing slash:
`add.UsePlayground("/graphql/");`

**Comment by vsylvestre** [comment]
> @delta-it Same is happening to me, in Visual Studio and Rider, using HC 10.4.3
> @vsylvestre do you have a repo where to check how you got everything working?
> Also ask the same in the [slack](hotchocolategraphql.slack.com) channel: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1594419457333400

Are you still having issues? I haven't had the time yet but I'd be happy to make a repo with my setup, if that can help.

**Comment by ddieppa** [comment]
@vsylvestre that will be great, cuz I was trying to get it work and it was kind of working, nothing related with HC(no compilation or build errors), but in the way I understood and created the subscription wasnt working, didnt get to follow the entire process during debugging. 
So yeah, a repo will be awesome

**Comment by delta-it** [comment]
Hi @ademchenko,
I have tried "app.UsePlayground("/graphql/")" but it was not working, but follow the way from @ddieppa "app.UsePlayground("/graphql", "/playground")" was fine.

Hi @vsylvestre,
This issue from me is solved, I use "app.UsePlayground("/graphql", "/playground")" and it's working fine.

**Comment by vsylvestre** [comment]
> @vsylvestre that will be great, cuz I was trying to get it work and it was kind of working, nothing related with HC(no compilation or build errors), but in the way I understood and created the subscription wasnt working, didnt get to follow the entire process during debugging.
> So yeah, a repo will be awesome

There you go: https://github.com/vsylvestre/graphql-playground-csharp. It has the most minimal config I was able to come up with to get the subscriptions working. After running the program you should be able to open two separate playgrounds at `http://localhost:5000/playground`, have one listen for the `valueUpdated` subscription, and another one send the `updateValue` mutation.

**Comment by michaelstaib** [comment]
Have a look at our workshop https://github.com/michaelstaib/graphql-workshop/blob/master/docs/6-subscriptions.md.

I will still update the documentation and write a blog on this, but the workshop walks you through the new subscription API.

Also, you can find the final workshop code here:
https://github.com/michaelstaib/graphql-workshop/tree/master/code

I am closing this issue.
