### ISSUE TITLE
Publishing a subscription event not within a mutation

### ISSUE THREAD

**Issue by vsylvestre** [ChilliCream/hotchocolate#2118]
Hi,

I'm trying to see how we can publish a subscription event outside the context of a mutation, and outside our schema altogether. In the [susbcriptions documentation](https://hotchocolate.io/docs/code-first-subscription#getting-started), it says about the InMemory implementation that:

> This one is good enough if we have a single server and all events are triggered through our mutations.

So, I assume that the one to choose in my case is Redis. But I'm having trouble understanding how it works just from what's available in the documentation, as there is only information on how to _set up_ the Redis subscription provider.

How would I go about publishing an event that can be read by a subscription, but from outside the context of my GraphQL schema?

Thanks!

**Comment by ademchenko** [comment]
Hi, @vsylvestre. Regardless of what exactly you use - either InMemory or Redis subscription provider - the interface for sending messages remains the same. For current production version - 10.4 it is IEventSender. In the case of ASP.NET Core it's registered as as singleton while you're configuring your subscription method doing  "app.AddRedisSubscriptionProvider", or "app.AddInMemorySubscriptionProvider". So, you could use it in any place retrieving with DI and send the messages you need.
To how it works you could, for instance, use the ASP.NET Core WeatherForecastController which is created on ASP.NET Core API project scaffolding:
`        private readonly IEventSender _eventSender;
        public WeatherForecastController(IEventSender eventSender)
        {
            _eventSender = eventSender;
        }

        [Microsoft.AspNetCore.Mvc.HttpGet]
        public async Task<IEnumerable<WeatherForecast>> Get()
        {
            await _eventSender.SendAsync(new OnUserChangeMessage(new UserChangePayload
            {
                User = new User(id:1)
                {
                    Balance = 1200,
                    RegistrationTime = DateTimeOffset.UtcNow,
                }
            }));
...Other code
`
So you could see that the message has been send outside the context of the mutation.

**Comment by vsylvestre** [comment]
@ademchenko Thanks a lot for your help. I'm also still relatively new to C#, so I can see now that I just didn't understand how to properly leverage DI to get access to this class anywhere in my app.

I have another question regarding subscriptions, I don't know if you could help with this as well (and maybe I should put this in a separate issue). I'm trying to replicate the behaviour of `withFilter` in apollo-server (JS), described [here](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#subscription-filters). In short, I'm trying to apply a filter that compares the payload (or message) from the event sender with the arguments passed along with the subscription on the client side, in order for the server to "filter out" subscribers that don't need to get a certain update. I haven't seen any documentation on subscriptions filters for Hot Chocolate. Do you know how I should go about doing this?

**Comment by michaelstaib** [comment]
@vsylvestre if you use the newer event system with `ITopicEventSender`, you can create a subscription-based on topics and with thus do not need to filter.

**Comment by michaelstaib** [comment]
I will close the issue now.

**Comment by michaelstaib** [comment]
Signup with us on slack if you need more help.
