### ISSUE TITLE
List of enum types (and maybe other value types) is inferred incorrectly

### ISSUE THREAD

**Issue by mvestergaard** [ChilliCream/hotchocolate#2119]
`IEnumerable<SomeEnum>` is infered as `[SomeEnum]!` and not `[SomeEnum!]!`

**Comment by PascalSenn** [comment]
Thanks for reporting!! 
I think @michaelstaib  just fixed a bunch of them in a feature branch

**Comment by mvestergaard** [comment]
Appears to be fixed in 10.5
