### ISSUE TITLE
IResolverContext.Argument<string>()` returns Null

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2127]
**Describe the bug**
`IResolverContext.Argument<string>("userId")` returns Null, It should not be `Null`

The C# code  like this:
```
public class User
{
    public string ID { get; set; }
    public string Name { get; set; }
}

public class UserType: ObjectType<User>
{
    protected override void Configure(IObjectTypeDescriptor<User> descriptor)
    {
        descriptor.Field(p => p.ID).Name("id");
        descriptor.Field(p => p.Name).Name("name");
        descriptor.Field("friends")     //---------------add a new field
            .Resolver(p =>p.Service<IFriendRepository>().FindUser(p.Argument<string>("userId"))); //p.Argument<string>("userId")  returns null.
    }
}

ISchema schema = SchemaBuilder.New()
                .AddType<UserType>()
                .AddQueryType<Query>()
                .Create();

//query
query
{
    users(userId:"ziv")     //here is the argument
    {
            id
            name
            friends
            {
                id
                name
            }
    }
}
```

**Desktop (please complete the following information):**
 - 10.4.3

**Comment by PascalSenn** [comment]
@zivfuture  you try to retrieve the argument for the field friends but the arguement is defiend on the field users a layer above.
You may want to look at scoped context data in this case

**Comment by ademchenko** [comment]
Hi, @zivfuture , I assume that somewhere in your query you, firstly, retrive user:
`[ExtendObjectType(Name = "Query")]
    public class UserQuery
    {
        public async Task<IEnumerable<User>> GetUser(int[] ids, [Service] IUserService userService)
        {
            var nativeUsers = userService.GetUsers(ids, dc);
            return nativeUsers.Select(Converter.ConvertUser);
        }
`
If that's the case then on a "friends" level you already have a particular user resolved, so could use the field Id directly (without addressing .Argument):
`descriptor.Field("friends").Resolver((ctx, t) =>
            {
                var userId = ctx.Parent<User>().Id;
                return ...;
            })

**Comment by michaelstaib** [comment]
Arguments are not automatically pushed down since the lower level fields have their own arguments and this would lead to chaos :)

@pascal is right, if you want to push information down from a node above look at scoped context data. 

I will close this issue.
