### ISSUE TITLE
Is Banana Cake similar to Github's GQL Explorer or GraphiQL?

### ISSUE THREAD

**Issue by BenHayat** [ChilliCream/hotchocolate#2128]
I was looking at your website to find something like GQL API Explorer.
Do you offer your live explorer or do we use the one from Github?
Or something like GraphiQL?

Thanks!
..Ben

**Comment by ademchenko** [comment]
Hi, @BenHayat .
To explore the API you could use [Playground explorer](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/) which is based on GraphiQL or HotChocolate [Banana Cake Pop](https://hotchocolate.io/docs/banana-cakepop). The latter is an app and can be installed on windows/macOS/linux. The former is provided in a separate NuGet package - HotChocolate.AspNetCore.Playground if you use ASP.NET Core. Once you have installed that package - just turn it on in Startup configure:
`  app
                .UseGraphQL("/graphql")
                .UsePlayground("/graphql")
 `
You could also use [GraphQL Voyager](https://github.com/APIs-guru/graphql-voyager) - an awesome tool describing your API as a graph.
If you decide to use Playground take into account [that issue](https://github.com/ChilliCream/hotchocolate/issues/1806) with subscriptions which is still reproducible for Playground.

**Comment by BenHayat** [comment]
Hi, @ademchenko;

Thank you for detail reply. Looking forward to be using your HotChocolate product. From a video I saw last night, I like Banana Cake Pop. Sticking with one vendor.
Thanks again.
..Ben
