### ISSUE TITLE
ExtendObjectType attribute should take an argument that makes the extension to propagate to all derived classes

### ISSUE THREAD

**Issue by MaximS** [ChilliCream/hotchocolate#2136]
When I have a class hierarchy I have to add the same extension to each derived class separately.

ExtendObjectType attribute should take an argument that makes the extension to propagate to all derived classes of this class. So I have to add an extension to one base class only.

Ex:
As is:
```
   public class SomeBaseClass...

   public DerivedClass: SomeBaseClass...

    [ExtendObjectType(Name = "SomeBaseClass")]
    public class SomeBaseClassExtension

    [ExtendObjectType(Name = "DerivedClass")]
    public class DerivedClassExtension
```

To be:
```
   public class SomeBaseClass...

   public DerivedClass: SomeBaseClass...

    [ExtendObjectType(Name = "SomeBaseClass", PropagateToSublasses: true)]
    public class SomeBaseClassExtension
```

**Comment by michaelstaib** [comment]
We have reworked the type extensions. Have a look at the docs:
https://chillicream.com/docs/hotchocolate/defining-a-schema/extending-types/
