### ISSUE TITLE
dotnet graphql update doesn't write to Path

### ISSUE THREAD

**Issue by jorrit** [ChilliCream/hotchocolate#2141]
**Describe the bug**

When a schema is updated using `dotnet graphql update --Path somepath` the scheme is written to the working directory instead of somepath.

I think this is because the `path` parameter of `UpdateCommandHandler.DownloadSchemaAsync()` is not used.

**To Reproduce**

1. Initialize the StrawberryShake client with:
   > dotnet graphql init http://localhost:8000/graphql/ --Path ApiClients\Product --SchemaName ProductApi
   This writes ProductApi.graphql to ApiClients\Product.

2. Update this schema using:
   > dotnet graphql update --Path ApiClients\Product

**Expected behavior**

ApiClients\Product\ProductApi.graphql should be updated.

**Actual behavior**

ProductApi.graphql is created, ApiClients\Product\ProductApi.graphql is not updated.

**Desktop (please complete the following information):**
 - OS: Win10Pro
 - Version: 11.0.0-preview.138

**Comment by michaelstaib** [comment]
Do you want to do a fix?

**Comment by jorrit** [comment]
This bug is outdated. It works fine with v12 and IIRC v11 as well.
