### ISSUE TITLE
Authorization filter?

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2150]
Is that possible to implement  mvc authorization filter ?

**Comment by michaelstaib** [comment]
Have you read https://hotchocolate.io/docs/authorization?

**Comment by zivfuture** [comment]
@michaelstaib    
yes.   I have read it. Thanks for reminding.

I mean  i need  authorization in gateway with schema stiching.  

In gateway . 
I need to know who you are(token already include this) and witch query method or mutation method that you call.  beacuse there is a DB table  that records who has permission to call this method(query or mutation).  if you have no permission .  you will be refused and get an 401 error code. not send to remote microservice.

I spent  lot of  time for that.  can you help me? thanks!

**Comment by gmiserez** [comment]
Hello @zivfuture 

This looks more like a question about ASP.Net Authorization in general than specifically HotChocolate. 

In your particular case you can solve this with claims in your stitching layer:
- Define an authorization policy for each combination of claims that is needed by a field 
For instance: you have two fields who need claim A, one field who needs claim B, and one field who needs claims A & B, that gives you 3 policies: "hasClaimA", "hasClaimB" and "hasClaimAB"
- When the user connects for the first time, you can add him claims 
- In your Stitching layer, add the @authorize directive on your fields/types that you want to protect
-

**Comment by zivfuture** [comment]
@gmiserez  thanks!

**Comment by zivfuture** [comment]
@gmiserez   sorry i opened it again.    i can't find any example like yours,   can you give me some url about it. thanks very much!
```
myField : String! @authorize(apply: BEFORE_RESOLVER, policy: "hasClaimA")
```

**Comment by gmiserez** [comment]
You can use the examples from here: 
https://hotchocolate.io/docs/authorization#policies
In these examples, the authentication is implemented in an API without stitching, and not in a stitching layer. 


I don't think that there are any examples available online for field-level authorization on the Stitching layer. 
In the stitching layer, you have two possiblities: 
- extend the entire Type in your stitching layer and add the authorize directive to it. 
` extend type Foo @authorize(...)`
- declare the field as a delegate and add the authorize directive there
`foos @delegate(path: "..." schema: "...") @authorize(...)`

But I'd recommend declaring the authorization directly on your stitched Apis, and not in your stitching layer. 
Pros: 
- your stitched Apis are protected even if someone bypasses the Stitching layer
- you can use the existing documentation from https://hotchocolate.io/docs/authorization#policies
- you can do it in code-first
