### ISSUE TITLE
Query Middleware exception

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2151]
**Describe the bug**
Query Middleware exception:
"errors": [
        {
            "message": "Unexpected Execution Error",
            "extensions": {
                "message": "The query key can only be set once. (Parameter 'value')",
                "stackTrace": "   at HotChocolate.Execution.QueryContext.set_QueryKey(String value) in D:\\hotchocolate-master\\src\\HotChocolate\\Core\\src\\Core\\Execution\\QueryContext.cs:line 78\r\n   at HotChocolate.Execution.ParseQueryMiddleware.InvokeAsync(IQueryContext context) in D:\\hotchocolate-master\\src\\HotChocolate\\Core\\src\\Core\\Execution\\Middleware\\ParseQueryMiddleware.cs:line 76\r\n   at HotChocolate.Execution.ExceptionMiddleware.InvokeAsync(IQueryContext context) in D:\\hotchocolate-master\\src\\HotChocolate\\Core\\src\\Core\\Execution\\Middleware\\ExceptionMiddleware.cs:line 27"
            }
        }
]

**To Reproduce**

```
services.AddStitchedSchema(builder => 
      builder .AddSchemaFromHttp("orders")
              .AddSchemaFromHttp("users")

              .AddExecutionConfiguration(x =>{
                   x.UseDefaultPipeline();             //use default pipeline first,   remove this line works fine.
                   x.Use(next =>async context =>{        //my custom query Middleware 
                        //do something other.
                        await next(context); 
             });
}));
```

**Expected behavior**
Did I make any mistakes?   

By the way,  I really need a interceptor  bebore the request query get excuted by remote. But I haven't found it yet. the "ITypeInitializationInterceptor" i don't know how to use in stiching sechma. any explames for that?

**Desktop (please complete the following information):**
 - OS:win10
 - 10.4.3

**Comment by michaelstaib** [comment]
You cannot use the default pipeline with schema stitching. It is more complex to extend the stitching pipeline. We actually reworked this part for version 11 and it will become easier. I can post later an example of how to do it.

**Comment by zivfuture** [comment]
@michaelstaib     Thanks very much.  i'll close this issue immediately.     looking forward to your exampe.
