### ISSUE TITLE
Filtering by DateTime property ignores the time

### ISSUE THREAD

**Issue by moredatapls** [ChilliCream/hotchocolate#2152]
**Describe the bug**

Our use case:
- we use EF Core and one of our entities has a `DateTime` property: `public DateTime Timestamp { get; set; }`
- we expose the property via HC like so: `descriptor.Field(e => e.Timestamp).Type<NonNullType<DateTimeType>>();`
- we want to filter a list of these entities based on the `Timestamp` property:

```cs
descriptor.Filter(e => e.Timestamp)
    .AllowEquals().And()
    .AllowIn().And()
    .AllowGreaterThanOrEquals().And()
    .AllowLowerThanOrEquals().And()
    .BindFiltersExplicitly();
```

When we filter in the query (`where: { timestamp_gte: "2020-09-26T13:00:00Z" }`, the time is ignored and only the date component is used for filtering. I think that this is because in HC `DateTime` is the CLR type of `DateType`? And `DateType` ignores the time component of the string?

**To Reproduce**

Steps to reproduce the behavior: see example above

**Expected behavior**

I find this behaviour inconsistent. I'd expect one of two things:
1. The filter automatically uses the `DateTimeType`, as this is what we specified in the `ObjectType` for our entity
2. The `IFilterInputTypeDescriptor` should offer a method to specify the type, just like it's possible with the `IObjectTypeDescriptor`

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - HC version: 10.4.3

**Additional context**

I think one workaround could be to change the type of our `Timestamp` property to `DateTimeOffset`. However, I don't like this solution so much because we would need to introduce a translation between the types in EF Core.

**Edit**: a workaround to convert between the types in EF core, the API now works as expected

```cs
builder.Property(e => e.Timestamp)
    .IsRequired()
    .HasConversion(t => t.UtcDateTime,
        t => new DateTimeOffset(t, TimeSpan.Zero));
```

**Comment by PascalSenn** [comment]
Creating custom filter types with custom scalar is possible in v11 filtering
