### ISSUE TITLE
Paging in reverse way (before:"cursor" last:1) on position: 3 is not applied and returns 2 elements..

### ISSUE THREAD

**Issue by damikun** [ChilliCream/hotchocolate#2154]
**Describe the bug**

Paging returns 2 elements and is not applied in SQL command... in case you go back (before:"cursor" last:1) in potion 3 from start

Important: only on element position = 3 in reverse way! (paging include "before")

**To Reproduce**

_Edited_: Reproduce project: https://github.com/damikun/HCPaginationBug

Reproduce steps:
I have some entities in DB and for example cursors are:

ID1: "MA=="
ID2: "MQ=="
ID3: "Mg=="
ID4: "Mw=="

If i write query with this pagination variables (going reverse)

`{
  "first": null,
  "last": 1 ,
  "before": "Mg==", // This is cursor with position == 3 
  "after": null
}`

response return 2 elements from cursor "Mg==" and paging in SQL command is not apply-ed 

All other works +3 elements  if i do:

`{
  "first": null,
  "last": 1 ,
  "before": "Mw==",  // This is +3 cursor
  "after": null
}`

i get correct response and SQL command is OK

It looks like start +1 offset problem....
 
**Expected behavior**

response return 1 element from cursor "Mw==" and SQL contains LIMIT -1 OFFSET @__p_1

**Versions :**
HC:  10.5.0-rc.1
.Net Core :   .net 5
DB: SQLite

EfCore Log Wrong state
![Errror111](https://user-images.githubusercontent.com/54806834/88082525-2bd83c80-cb82-11ea-969a-28a28a1fd844.PNG)
EfCore Log OK State
![OK111](https://user-images.githubusercontent.com/54806834/88082565-34c90e00-cb82-11ea-90fc-80567259c968.PNG)

**Comment by damikun** [comment]
I created the Test project to reproduce under: https://github.com/damikun/HCPaginationBug

**Comment by emrahyigit** [comment]
Also selecting nested properties with **last**, produces following error:
`Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlFunctionExpression' to type 'System.Linq.Expressions.ConstantExpression`

**Comment by damikun** [comment]
> Also selecting nested properties with **last**, produces following error:
> `Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlFunctionExpression' to type 'System.Linq.Expressions.ConstantExpression`

@emrahyigit  I`m not sure... your error looks more like EFcore error from message.... Can you provide some info: query, code and version of Net and Efcore you use..

**Comment by emrahyigit** [comment]
Thank you for your reply. You are right. It is more related to EFcore:
`
EF Core version: 3.1.6
Oracle EF Core:  3.19.0 beta2
`

**Comment by damikun** [comment]
> Thank you for your reply. You are right. It is more related to EFcore and It is totally fine with EFcore2:
> 
> My environment:
> EF Core version: 3.1.6
> Oracle EF Core: 3.19.0 beta2

Yes there are known bugs in this in .net core 3.1 so i can recommend to migrate to .net5 .

**Comment by MariaCobretti** [comment]
there is a bug with the "last" parameter in "QueryableCursorPagingHandler" line 147 where it says 

            if (skip > 1)
            {
                temp = temp.Skip(skip);
                offset += count;
                offset -= temp.Count();
            }

so if there are 2 items in the db and I query last: 1... I have to skip 1 item.
the if clause has to be if (skip > 0) otherwise the filter is not applied and both items are returned

**Comment by MariaCobretti** [comment]
also, there are 2 calls against the db that are not necessary to get the count of all and remaining items
here is my implementation of GetLastEdges

protected virtual IQueryable<TEntity> GetLastEdges(
            IQueryable<TEntity> edges,
            int last,
            int count,
            ref int offset)
        {
            if (last < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(last));
            }
            IQueryable<TEntity> temp = edges;

            var skip = count - last;

            if (skip > 0)
            {
                temp = temp.Skip(skip);
                offset = skip;
            }

            return temp;
        }

**Comment by Vict0r1** [comment]
For me, upgrading **ef core** to **5.0.0** fixed this problem, even if I still using **.net 3.1**
