### ISSUE TITLE
JSON Serializer Options Override

### ISSUE THREAD

**Issue by foundationerich** [ChilliCream/hotchocolate#2156]
Would it be possible to make the Newtonsoft JSON options an optional parameter on the Redis Subscription package that we can pass in? We are having issues currently due to circular references in a couple of our models that would be fixed if we could specify the settings to use since we could set the ReferenceLoopHandling property to Ignore.  We're currently using the workaround of first serializing and deserializing the data using that option before passing it into the subscription however that seems like a waste of processing.

**Comment by RehanSaeed** [comment]
Is this a duplicate or related to https://github.com/ChilliCream/hotchocolate/issues/4072?
