### ISSUE TITLE
ResolverResult not setting Value

### ISSUE THREAD

**Issue by seblescure** [ChilliCream/hotchocolate#216]
**Describe the bug**
The constructor of the ResolverResult class does not initialize Value member correctly.

**To Reproduce**
1. var rr = new ResolverResult<int>(1);
2. rr.Value is null

Constructor currently initializes Value to "default" of the type.

**Comment by michaelstaib** [comment]
@seblescure I fixed the bug and wrote some tests. I will create a new patch release tonight.

**Comment by michaelstaib** [comment]
@seblescure fix is included in version 4.2

**Comment by seblescure** [comment]
Thanks for the quick fix :)
