### ISSUE TITLE
ExecutionTimeout not working

### ISSUE THREAD

**Issue by pmahit05** [ChilliCream/hotchocolate#2168]
ExecutionTimeout not working in 10.4.3

service.AddGraphQL(sp => SchemaBuilder.New()
.AddService(sp)
.AddAuthorizeDirectiveType()
.AddQueryType<QueryType>()
.AddMutationType<MutationType>()
.Create
//.MakeExecutable(
//builder =>
//builder.AddOptions(
//new QueryExecutionOptions()
//{
//ExecutionTimeout = TimeSpan.FromSeconds(1)
//}
//)
//.Schema
,new QueryExecutionOptions()
{
ExecutionTimeout = TimeSpan.FromSeconds(1)
}

**Expected behavior**
I was expecting "The Transaction has aborted" after 1 sec but I'm getting that error after 1 min.
In my testing api I have kept wait of 61 sec. 
I'm getting that error after 1 min even if I dont set ExecutionTimeout
If I keep wait of 59 sec I get response properly.

I'm testing my .net core api using playground.

Also not sure what is meaning of this error because though I'm getting error in playground but my api is performing all task. It just not returning me response.
Like it is doing all insert and update, it's logging everything even after 1 min but I'm not getting success response which I'm passing after all execution is completed

**Comment by michaelstaib** [comment]
Try the following:

```csharp
service.AddGraphQL(
    sp => SchemaBuilder.New()
    .AddService(sp)
    .AddAuthorizeDirectiveType()
    .AddQueryType()
    .AddMutationType()
    .Create(),
    (IQueryExecutionBuilder builder) => 
        builder.UseDefaultPipeline(new QueryExecutionOptions { ExecutionTimeout = TimeSpan.FromSeconds(1) });
```

For version 11, we made this API much more user-friendly and less error-prone.

**Comment by pmahit05** [comment]
Still no luck.
Upgraded to 10.5.2
Set timeout 2 min but still getting Transaction has aborted error after 1 min

(IQueryExecutionBuilder builder) => 
        builder.UseDefaultPipeline(new QueryExecutionOptions { ExecutionTimeout = TimeSpan.FromSeconds(120) })

**Comment by pmahit05** [comment]
Hi Michael,

Thanks a lot for your reply.
I upgraded to 10.5.2 and implemented my code as you said.
But still it is not working as expected.
Getting the same Transaction has aborted error.

Is that something hotchocolate is throwing or I need to look into my code?


*Thanks & Regards,Prasad Mahit*
*609-775-7639*

**Comment by michaelstaib** [comment]
Did you set the ASP.NET execution timeout as well?
