### ISSUE TITLE
Case Insensitive Filtering

### ISSUE THREAD

**Issue by JuStTheDev** [ChilliCream/hotchocolate#2169]
Hello,
I would like to be able to do graphql-queries that are case-insensitive.

## **Is my feature request related to a problem?**
Yes it is. We want to do a case-insensitive search using filtering. Posting a constraint using the where syntax always results in case-sensitive results.
```
query {
  Entities(where: {myField_contains: "abraCadabra"}){
    myField
    anotherField
    andMoreFields
  }
}
```
This query does not result in entities containing the strings as `AbraCadabra` or `abracadabra` but only the one matching the case.

## **The solution I'd like**
In addition to `myField_contains` I would like to have something like `myField_icontains` where results are filtered ignoring case.
Ther query would then be:
```
query {
  Entities(where: {myField_iContains: "abraCadabra"}){
    myField
    anotherField
    andMoreFields
  }
}
```

## **Alternatives I've considered**
An even more elaborated idea would be to be able to apply regular expressions as filter constraints. Hasura has something like that https://hasura.io/docs/1.0/graphql/manual/queries/query-filters.html#text-search-or-pattern-matching-operators-like-similar-etc. In a RegExp, one could that way put case-sensitivity flags as needed by the given use-case.
A possible query would then be:
```
query {
  Entities(where: {myField_iLike: "^[abcdr]+$"}){
    myField
    anotherField
    andMoreFields
  }
}
```
And result in all entities matching the regular expression `^[abcdr]+$`.

**Comment by StevenGranados** [comment]
When working with EF Core case sensitive queries are a pain if the collation is case insensitive. I think LINQ containing `Equals("foo", StringComparison.IgnoreCase")` would produce an exception and `EF.Functions.Collate` should be used instead. I'm assuming here that Hot Chocolate translates to LINQ and EF Core does the rest.

**Comment by PascalSenn** [comment]
Hi @JuStTheDev 

Thanks for opening this issue. We are currently redesign filtering completely in 11. With the new implementation it will be easy to just add the things you need

**Comment by michaelstaib** [comment]
Closing this issue since it is solved with the new hotchocolate.data api.

**Comment by kolpav** [comment]
@michaelstaib Can you please explain what new api you mean?

**Comment by michaelstaib** [comment]
New API ... aka HotChocolate.Data

**Comment by ciprian-aw** [comment]
Leaving this here maybe it will help others. I've added my solution to the discussion below

https://github.com/ChilliCream/graphql-platform/discussions/3915#discussioncomment-6517235
