### ISSUE TITLE
`ID` attribute support and IIdSerializer issues

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2170]
**Describe the bug**

- [x] **Issue 1**
DI'ing your own `IIdSerializer` with `includeSchemaName: true` isn't picked up when injected later, causing schema names to never be written into serialized ids. (Or at least the value provided isn't set on the instance you get later).

- [ ] **Issue 2**
Deserialization of string of or actual CLR type version doesn't work. 

For example, these should all deserialize as int automagically for us:
```
# Argument-level
query byStringOfIntDbId {
  supplier(id: "12") { ... }
}
query byIntDbId {
    supplier(id: 12) { ... } 
}
query byGlobalId {
    supplier(id: "U3VwcGxpZXIKaTEy") { ... } # note: that ID doesn't currently include schema name as per issue 1
}

# InputObject-level
mutation byStringOfIntDbId {
  deleteSupplier(input: { id: "12" }) { ... }
}
mutation byIntDbId {
    deleteSupplier(input: { id: 12 }) { ... } 
}
mutation byGlobalId {
    deleteSupplier(input: { id: "U3VwcGxpZXIKaTEy" }) { ... } # note: that ID doesn't currently include schema name as per issue 1
}
```

Where the relevant SDL is:
```
supplier(id: ID!): Supplier

deleteSupplier(input: DeleteSupplierInput!): DeleteSupplierOutput

type DeleteSupplierInput {
  id: ID!
}
```

And the C# side is:
```c#
public class Query
{
    public Supplier GetSupplierAsync(
        //...,
        [ID]int id)
    { 
        //... 
    }
}

// ... have left out the mutation for brevity

public class DeleteSupplierInput 
{
    [ID("Supplier")]
    public int Id { get; set; }
}
```

Have confirmed issue 2 exists at both InputObject and argument levels.

I haven't added any examples of array args/input props, but I imagine that'll be fixed by same fix too. e.g. so we can do the following in as a resolver arg:
```c# 
[ID]string[]? ids
```

**To Reproduce**
Set up scenario above.

**Expected behavior**
As described above. 

**Desktop (please complete the following information):**
 - OS: Win 10 latest
 - Version: 10.5.0

**Additional context**
N/A.

**Comment by benmccallum** [comment]
Issue 1 could be as simple as this spot here only doing a `TrySingleton<IIdSerializer, IdSerializer>()` instead of:
https://github.com/ChilliCream/hotchocolate/blob/e69aac769fd3490a98016570b50412a512ebbd37/src/Server/AspNetCore/Extensions/ServiceCollectionExtensions.cs#L427

I always thought doing AddSingleton twice would blow up, but maybe I'm missing something.

**Comment by benmccallum** [comment]
I assigned this to a 10.5.1 milestone, but perhaps you just group them all as 10.5.0? Feel free to change it @michaelstaib

**Comment by michaelstaib** [comment]
> supplier(id: "12") { ... }

so by design, we only allow global IDs when you put on the attribute. Since we validate the format and the wrapped type.

**Comment by michaelstaib** [comment]
I will add some helpers to set up the id serializer with the schema serialization.

**Comment by michaelstaib** [comment]
```
query byStringOfIntDbId {
  supplier(id: "12") { ... }
}
query byIntDbId {
    supplier(id: 12) { ... } 
}
query byGlobalId {
    supplier(id: "U3VwcGxpZXIKaTEy") { ... } # note: that ID doesn't currently include schema name as per issue 1
}
```

At the moment we only accept `U3VwcGxpZXIKaTEy` when `ID` global IDs are activated. We could probe the argument/input value if it is something else but it's kind of like going fishing here. Isn`t it better to be stricter, meaning if you said you want global IDs of a specific kind you expect them to be of that ID?

**Comment by benmccallum** [comment]
> so by design, we only allow global IDs when you put on the attribute

I think I'm doing that, no? See `GetSupplierAsync` in description.

**Comment by benmccallum** [comment]
It makes it a hell of a lot easier to debug things quickly when you've got the db id, and it's something that GitHub supports, so I think it's a great thing to have.

This also comes back to the description on the `ID` type, which says all three should/are supported.
> The ID scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as "4") or integer (such as 4) input value will be accepted as an ID.

Key part being that last sentence.

**Comment by benmccallum** [comment]
Strict is usually the way to go, and Marais was leaning that way to begin with too a while back, but in the end he came around :P 

More specifically to our case, our worry is that we've prob got a few uses of the string or real type being passed, so we'd need to crawl through and make sure we weren't anymore.

**Comment by benmccallum** [comment]
A fix for issue 1 is to do the following after calling AddGraphQL:

```c#
services.RemoveAll<IIdSerializer>(); 
services.AddSingleton<IIdSerializer>(new IdSerializer(includeSchemaName: true); 
```

**Comment by michaelstaib** [comment]
Regarding issue 2, I think that is a custom ID serializer since we would need to try first deserializing if that does not work than we would need to try and convert the value depending on the field's type. 

I think to have a generic solution it sounds quite error prone since we could end up passing a broken base64 string as ID to a string ID.
