### ISSUE TITLE
Rewrite Filtering

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#2172]
Open Tasks:
 - [x] Consider renaming QueryableFilter* to ExpressionsFilter*
 - [x] Consider renaming everything that is currently named operation*
 - [x] How do we deal with nested arrays
 - [x] QueryableFilterContext.ClrTypes may be obsolete
 - [x] We have to rework the bindings for types. Type to Type is good, but there is the need for more. It is currently not possible to replace ListFilterTypes, EnumTypes, and the basic FilterInputType

**Comment by PascalSenn** [comment]
@michaelstaib  what about the renames?

**Comment by michaelstaib** [comment]
> Consider renaming everything that is currently named operation

to what?
