### ISSUE TITLE
resolve dynamically generated input object types in mutation arguments

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2178]
I am trying to generate a graphql schema on startup based on schema information in a db
-> the client gets the convenience of concrete types while the graphql server maps the properties to generic types 

for every dynamic type in the db  I create a .Net type with the System.Reflection.Emit namespace during startup and pass it to a descriptor.Field() 

there I have to specify the return type with 
`descriptor.Field(dynamicType.Name).Type(concreteOutputType)` //concreteOutputType: System.Type

as well as the argument type with 
`descriptor.Field(dynamicType.Name).Argument("item", ad => ad.Type(concreteInputType))`

now when I specify the resolver I have to specify a compile time type for the argument. therefor I use object or rather AnyType
`descriptor.Field(dynamicType.Name).Resolver(x => UpdateConcreteTypeItem(x.Argument<AnyType>("item")))`

In this last line I am getting a HotChocolate.Execution.QueryException
Could not convert argument `item` from `ConcreteType1Input` to `HotChocolate.Types.AnyType`.

I would expect this to work or what is the reason we can't convert to object here?
Alternatively I would need a method overload on Argument that takes a System.Type in the Resolver just like descriptor.Field().Type():
x.Argument(concreteInputType)

**Comment by MariaCobretti** [comment]
it works with x.Argument<object> instead of x.Argument<AnyTpye>

**Comment by benmccallum** [comment]
I believe the `.Type(Type type)` method here only expects a graphql type (ObjectType for instance). 

At least that's been my experience and if so it should probably throw if the given type isn't of one of the base HC graph types, so it's not used incorrectly.

I've definitely found myself in need, when doing pure-code-first types, of a way to type another field to that, so I'd love personally a `.Field(x => x.Foo).ClrType(clrType)` kinda method that allows that, but knows that this is the backing/clr type and to find the actual graph type to feed into `.Type(graphType)`.

**Comment by MariaCobretti** [comment]
@benmccallum the `.Field(x => x.Foo).Type(Type type)` already accepts ClrTypes

**Comment by benmccallum** [comment]
Hmm, now that I think about it, potentially my experience was trying to do that as nullable which I couldn't figure out. Cheers.
