### ISSUE TITLE
Required annotated string property is mapped to `[String]!` type in 10.5.2

### ISSUE THREAD

**Issue by barticus** [ChilliCream/hotchocolate#2179]
**Describe the bug**
For a non-nullable string, that is also marked up with the required attribute, the schema infers the type incorrectly as `[String!]` instead of `String!` 

**To Reproduce**
1. have a model class that has a following structure:
```
[Required]
public string Content { get; set; } = default!;
```
2. Add this type to your schema

Project demonstrating this behaviour is here: https://github.com/barticus/hotchocolate-string-bug
In particular, you can see the result of the test (`cd Sample.Test && dotnet test`) here: `https://github.com/barticus/hotchocolate-string-bug/blob/master/Sample.Tests/GraphQL/ApprovalTests/SchemaTest.GetSchema.approved.txt`

**Expected behavior**
Correctly map this property to `String!`

**Desktop (please complete the following information):**
 - Version 10.5.2

**Comment by PascalSenn** [comment]
Looks like this works in v11.1:
```csharp
 public class RequiredQuery
 {
     [Required]
     public string Content { get; set; } = default!;
 }

```

produces
```graphql
schema {
  query: RequiredQuery
}

type RequiredQuery {
  content: String!
}
```
