### ISSUE TITLE
Resource based Authorization

### ISSUE THREAD

**Issue by StevenGranados** [ChilliCream/hotchocolate#2197]
Adding resource based authorisation in a pure code first way would be a nice feature.

The ability to add attributes to a field to enable policy and role based is really useful, but sometimes authorisation needs to occur on a field in a class.

Maybe a ResourceAuthorizeAttribute could be put on a data class. A method would be called once the field is resolved and have its value passed in along with the user. The method could then assess the fields value and stop the whole class from being resolved.
This is a naive guess of what I want mostly stripped from the docs, but the attribute would need to be told only to load the Author field to authorise and not everything.
```C#
[ResourceAuthorize]
public class Document
{
    public string SensitiveData { get; set; }
    public Author Author { get; set; }
}

public class DocumentAuthorizationHandler : 
    AuthorizationHandler<SameAuthorRequirement, Document>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                                                   SameAuthorRequirement requirement,
                                                   Document resource)
    {
        if (context.User.Identity?.Name == resource.Author.Name)
        {
            context.Succeed(requirement);
        }

        return Task.CompletedTask;
    }
}

public class SameAuthorRequirement : IAuthorizationRequirement { }
```
Maybe move the attribute to the field something more like:
```C#
public class Document
{
    public string SensitiveData { get; set; }
    [ResourceAuthorize]
    public Author Author { get; set; }
}

public class AuthorAuthorizationHandler : 
    AuthorizationHandler<SameAuthorRequirement, Author>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                                                   SameAuthorRequirement requirement,
                                                   Author resource)
    {
        if (context.User.Identity?.Name == Author.Name)
        {
            context.Succeed(requirement);
        }

        return Task.CompletedTask;
    }
}

public class SameAuthorRequirement : IAuthorizationRequirement { }
```
Is this possible?

**Comment by tobias-tengler** [comment]
This can be done using the `[Authorize]` attribute and specifying the name of an ASP.NET Core policy as argument.

**Comment by chungonion** [comment]
Hi there, I would like to ask whether such resource based authorization is currently available in v11 and v12? It seems in the documentation I could not locate the section on the detail implementation of such feature. Thanks!

**Comment by tobias-tengler** [comment]
@chungonion what exactly is missing in the documentation for you? It shows how to add authorization on a field / type and some common examples. How you implement your policy is up to you and there is plenty of documentation by Microsoft.

**Comment by chungonion** [comment]
> @chungonion what exactly is missing in the documentation for you? It shows how to add authorization on a field / type and some common examples. How you implement your policy is up to you and there is plenty of documentation by Microsoft

I might not have clearly explained what my question was in my previous reply, my apology for that. 

Yes, I have some knowledge on how to use the  Authorization attribute to implement policy-based authorization, however, I am not so certain (and could not really google that) on how to use the `AuthorizationHandler` to control what fields to be resolved. For example : only allow the user to access its personal information, but not by other users.
