### ISSUE TITLE
OpenID support for Playground

### ISSUE THREAD

**Issue by promontis** [ChilliCream/hotchocolate#2199]
I've implemented this feature in the following repository: https://github.com/promontis/HotChocolate.AspNetCore.Playground.OpenId

Would like to get some code reviews and people testing it, if possible.
If all is cool, I would like to do a pull request to this repo. Is that ok?

**Comment by bram209** [comment]
Nice idea, 

Not sure if this should be a Graphql Server feature tho, this basically is a React app with OpenID authentication.
Could I ask what usecases you have in mind? If it is for development purposes, I found that the following is sufficient for me:

A prerequest script using the Altair client:
https://altair.sirmuel.design/docs/features/prerequest-scripts.html
![image](https://user-images.githubusercontent.com/9047770/90253602-b179a000-de41-11ea-8f94-90d105753a2d.png)

**Comment by promontis** [comment]
@bram209 the use case is indeed just for development purposes. I like your approach as well! 
The implementation is indeed just a react app app with openid, although it is a little bit tricky to actually get it compiled to a single file (webpack instead of CRA) and you'll need to add the correct routes to asp.net core, so it also has the correct UsePlayground implementation.

**Comment by TylerSiegrist** [comment]
@michaelstaib is there any chance of something like this being included in Banana Cake Pop? We use OpenID Connect and it makes it a hassle each time we want to work in playground.

**Comment by michaelstaib** [comment]
Yes, we are working at the moment to get banana cake pop on the web. Will be included I think at the end of September into the Hotchocolate server.

**Comment by michaelstaib** [comment]
That is why we already dropped playground in the preview builds.

**Comment by michaelstaib** [comment]
We have now replaced playground with bcp and are closing this issue.
