### ISSUE TITLE
 10.5.2 is not backward compatible with 10.4.3

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2201]
**Describe the bug**
Updating from 10.4.3 to 10.5.2 causes the system fail to work in some cases. The following test will cause an error on 10.5.2 but pass on 10.4.3 which means that 10.5.2 is not backward compatible with 10.4.3.
```
        public class BackwardCompatibilityOf10_5_2_Test
        {
            public class Account
            {
                public int? OwnerId { get; set; }
                public Account Owner { get; set; }
            }

            public class AccountType : ObjectType<Account>
            {
                protected override void Configure(IObjectTypeDescriptor<Account> descriptor)
                {
                    descriptor.Field(h => h.Owner).Resolver((ctx, t) =>
                    {
                        int? ownerId = ctx.Parent<Account>().OwnerId;
                        if (ownerId == null)
                            return null;

                        return ctx.BatchDataLoader<int, Account>("accountsById", async ids => new Dictionary<int, Account> { { 1, new Account() } }).LoadAsync(ownerId, t);
                    });
                }
            }
            
            [Test]
            public void BackwardCompatibility_Should_TakePlace() => SchemaBuilder.New().AddQueryType(t => t.Name("Query")).AddType<AccountType>().Create();
        }
```

**Additional context**
The issue here is that the compiler selects LoadAsync(**object**...) overload instead of LoadAsync(**int**...) because ownerId is _int?_ but not _int_. As a result, the resolver function returns 'object' (not 'Account') type. It looks like it was possible in 10.4.3 but no more in 10.5.2. In that particular case the fix is pretty easy - just call LoadAsync(**ownerId.Value**...) and the compiler will resolve the overload 'better'.

I don't know if that issue could lead to some more serious issues or it's just a broken backward compatibility and nothing more.
But, anyway, it was really hard to understand what had happened. I spent quite a bit of time solving the issue and wouldn't want the other community members to do the same. So, if you don't plan to fix could you at least add a line to 10.5.2 release note about the problem?

**Comment by michaelstaib** [comment]
We are closing this one. We are now trying to take more care about things like that so that semver rules are better applied.
