### ISSUE TITLE
Queries that use interfaces don't use the explicit interface implementation on the class

### ISSUE THREAD

**Issue by MattA48** [ChilliCream/hotchocolate#2203]
**Describe the bug**
When you have a GQL query returning an interface structure IObject, the schema builder gets confused when the implementing Object has an explicit interface implementation of a property

**To Reproduce**
Steps to reproduce the behaviour:

    [InterfaceType(Name="Object")]
    public interface IObject
    {
        public string Src { get; }
        
        public IReadOnlyList<string> List { get; }
    }

    public class Object : IObject
    {
        public string Src { get; set; }
        
        public List<string> List

       IReadOnlyList<string> IObject.List
        {
            get
               {
                    return List.AsReadOnly();
               }
         }
    }

    [ExtendObjectType(Name = "Query")]
    public class ObjectQueries
    {
        public IObject GetObject()
        {
            return new Object()
        }
    }

**Expected behavior**
Code picks up IObject.List implementation instead of the public List implementation returning the List<string>

**Actual behaviour**
Error on schema build: Object type Object does not implement the field List from interface IObject

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Version [e.g. 22] 10.15.6

**Additional context**
This was attempting a pure code-first implementation

**Comment by michaelstaib** [comment]
Can you post the code of your schema builder?

**Comment by MattA48** [comment]
I've re-created a slightly modified example here: https://github.com/MattA48/HotChocolateIssue2203 - I committed it with the interface added to the schemabuilder, but it needs to know the implementation (my other issue), so needs the QueryImpl line in Startup uncommenting.
