### ISSUE TITLE
HotChocolate should infer [GraphQLIgnore] from interfaces if that is the only way a class is exposed

### ISSUE THREAD

**Issue by MattA48** [ChilliCream/hotchocolate#2204]
**Is your feature request related to a problem? Please describe.**
This is mainly a problem incurred from an assumption on how HotChocolate uses interfaces in a pure-code-first environment which turned out to be incorrect. I had assumed that I could use interfaces to effectively dictate what parts of my implementing classes were exposed externally via GQL, therefore I had thought that the framework would ignore the parts of my classes that weren't covered by interfaces.

When I got to run my project, HotChocolate started complaining about being 'Unable to infer or resolve a schema type from the type reference XXX', where XXX tended to be Framework constructs like IAsyncResult, Type, RuntimeFieldHandle etc.

I now understand that it just looked at my implementing classes to build a schema and ignored that half of the methods weren't actually exposed outside. 

**Describe the solution you'd like**
I'd like HotChocolate to recognise when properties aren't exposed by any queries and automatically ignore them

**Describe alternatives you've considered**
The alternatives I can see are a liberal application of [GraphQLIgnore] or moving from pure code-first to code-first, which is a shame, as just exposing the queryable surface via interfaces seemed a much cleaner way of doing things.

**Comment by michaelstaib** [comment]
That would work if you never expose the class itself.

**Comment by MattA48** [comment]
That's what I originally attempted to do, but I could only see the following ways of doing it:

In SchemaBuilder:
Only adding the query => There is no object type implementing interface 'XXX'
Adding the query and interface => There is no object type implementing interface 'XXX'
Adding the query, interface and class => needs GraphQLIgnore on problematic properties on the class
Adding the query and class => needs GraphQLIgnore on problematic properties on the class

The only other way of doing it that I can see is if, rather than just relying on the SchemaBuilder, I need to explicitly state somewhere either in the interface or implementing classes what their relationship is, in addition to the pure c# `public class ClassName : InterfaceName`.
