### ISSUE TITLE
Exception while processing: No service for type 'Microsoft.Extensions.DependencyInjection.IServiceScopeFactory' has been registered.

### ISSUE THREAD

**Issue by bramtassyns** [ChilliCream/hotchocolate#2207]
When calling GET /graphql/api?query=hello in the sample below the following response is shown:

[InvalidOperationException: No service for type 'Microsoft.Extensions.DependencyInjection.IServiceScopeFactory' has been registered.]
   Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) +195
   Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider) +60
   HotChocolate.AspNetClassic.<HandleRequestAsync>d__14.MoveNext() in d:\a\1\s\src\Server\AspNetCore.Abstractions\QueryMiddlewareBase.cs:191
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   HotChocolate.AspNetClassic.<Invoke>d__12.MoveNext() in d:\a\1\s\src\Server\AspNetCore.Abstractions\QueryMiddlewareBase.cs:130
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__7.MoveNext() +179
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__12.MoveNext() +180
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +483
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

I'm trying to add AspNetClassic to an existing WebApi project (HttpApplication with Controllers based).
I use Microsoft.Owin.Host.SystemWeb 4.1.0 to get the GraphQL endpoint in the existing service project with HotChocolate.AspNetClassic 10.5.2
voyager/playground load but when retrieving the data from the endpoint they get the same error.
The schema SDL endpoint works as expected.
Not that calling serviceProvider.GetRequired<IServiceScopeFactory>() works when done in the Configuration method.
Calling serviceProvider.CreateScope() in the same place also works as intended.

full code sample:

using HotChocolate;
using HotChocolate.AspNetClassic;
using HotChocolate.AspNetClassic.Playground;
using HotChocolate.AspNetClassic.Voyager;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Owin;
using Owin;

[assembly: Microsoft.Owin.OwinStartup(typeof(Enfocus.Subscription.OwinStartup))]

namespace Enfocus.Subscription
{
    public class Query
    {
        public string Hello => "World";
    }

    public class OwinStartup
    {
        public void Configuration(IAppBuilder app)
        {
            var services = new ServiceCollection();

            var schema = SchemaBuilder.New()
                .AddType<Query>()
                .Create();
            services.AddGraphQL(schema);

            var serviceProvider = services.BuildServiceProvider();

            app.UseGraphQLHttpGet(serviceProvider, new HttpGetMiddlewareOptions
            {
                Path = new PathString("/graphql/api")
            });
            app.UseGraphQLHttpPost(serviceProvider, new HttpPostMiddlewareOptions
            {
                Path = new PathString("/graphql/api")
            });
            app.UseGraphQLHttpGetSchema(serviceProvider, new HttpGetSchemaMiddlewareOptions
            {
                Path = new PathString("/graphql/schema")
            });
            app.UseVoyager(new VoyagerOptions
            {
                Path = new PathString("/graphql/voyager"),
                QueryPath = new PathString("/graphql/api")
            });
            app.UsePlayground(new PlaygroundOptions
            {
                Path = new PathString("/graphql/playground"),
                QueryPath = new PathString("/graphql/api")
            });
        }
    }
}

**Comment by promontis** [comment]
@bramtassyns I think you are missing a service registration, namely 
```
services.AddMvc();
```

Try creating a new project for the same stack (classic stuff) and see which services it all registers.

**Comment by promontis** [comment]
You'll need to add it on top btw, before HC.

**Comment by bramtassyns** [comment]
I cannot find support for the injection classes in the version of the AspNet framework we're using (nuget packages Microsoft.Aspnet.... with version 5.2.7).
In those packages I can do UseWebApi etc on IAppBuilder which also takes a HttpConfiguration input but that does not appear to register the required services....

If I try to add the AspNetCore mvc packages which do seem to provide the AddMvc method it compiles, but I cannot run it because of clashes elsewhere (in a brand new setup with AspNetCore it does work, but I would like to run it as part of our existing service if possible - .net 4.7.2 btw)

**Comment by promontis** [comment]
@bramtassyns I think I gave you the wrong advice. Sorry bout that. This code should help you out (it works for me)...
```
public class Startup
    {
        public IServiceProvider ConfigureServices()
        {
            var services = new ServiceCollection();

            services.AddSingleton<Query>();
            services.AddSingleton<Mutation>();

            var schema = Schema.Create(c =>
            {
                c.RegisterServiceProvider(services.BuildServiceProvider());
               
                c.RegisterQueryType<QueryType>();
                c.RegisterMutationType<MutationType>();
            }).MakeExecutable(new QueryExecutionOptions { IncludeExceptionDetails = true });
            services.AddGraphQL(schema);
            return services.BuildServiceProvider();
        }
        public void Configuration(IAppBuilder app)
        {
            // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=316888
            IServiceProvider services = ConfigureServices();
            app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);
            app.UseGraphQL(services, new PathString("/graphql"))
               .UsePlayground(new PathString("/graphql"), new PathString("/graphql"));
        }
    }
```

**Comment by bramtassyns** [comment]
Setting the serviceProvider on the schema during creation fixed my problem.
(I called AddServices instead but I assume that is just the newer variant of the same call)
Thank you for your help.

**Comment by promontis** [comment]
Awesome 👍
