### ISSUE TITLE
schema and doc  tab is not working in playground

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2208]
**Describe the bug**
schema and doc  tab is not working in playground,   it awalys loading,  sometime  it works fine.   I'm troubled :
![image](https://user-images.githubusercontent.com/49356505/89362897-91d7ce80-d701-11ea-8f0e-749d2504d7e2.png)

**To Reproduce**
Code list this,  yes , i comment it all, but useless.
```
services.AddGraphQL(sp => SchemaBuilder.New()
                .AddQueryType(x => x.Name("Query"))
                //.AddType<DicQuery>()
                //.AddType<ConfigQuery>()
                .AddMutationType(x => x.Name("Mutation"))
                //.AddType<DicMutation>()
                //.AddType<ConfigMutation>()
                .Create()
                //, new QueryExecutionOptions() {  IncludeExceptionDetails=false }
                );


 app.UseRouting();
 app.UseGraphQL();
 app.UsePlayground();
 app.UseAuthorization();
``` 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: windows10
 - Version  10.5.2

**Comment by promontis** [comment]
@zivfuture I've noticed that this is mostly because of that the Playground is unable to fetch your schema because of an error in it (you misconfigured HC). If you open up developer tools, you probably get to see some errors in the console window and hopefully know what's going on.

**Comment by zivfuture** [comment]
@promontis   thanks!  as you said, i found some error in developer tools,     
well , It's hard to find this information if without someone's reminder.

**Comment by promontis** [comment]
@zivfuture yeah, Playground should just do some toaster notification or something. Now, it's a bit hidden. When developing, I now and then just check the schema tab to see if it still loads. If it doesn't I open up the developer tools to get an indication what was wrong.
