### ISSUE TITLE
Unauthorized in playground

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2209]
i get the unauthorized error in playground as follow:
```
middleware.js:1 Uncaught Error: {
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "__schema"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    }
  ]
}
```
Where to set value of baerer token?    i try to set the access token to the header area,  but not working.  how should i do?
![image](https://user-images.githubusercontent.com/49356505/89431954-24648600-d773-11ea-9849-97142a3988e3.png)

**Comment by promontis** [comment]
```
{
  "Authorization": "Bearer TOKEN"
}
```

If it works, please hit close

**Comment by zivfuture** [comment]
@promontis     it not working,  did i make any mistake?
![image](https://user-images.githubusercontent.com/49356505/89480293-8b138f00-d7c7-11ea-85b5-a5b9d7563aa2.png)

**Comment by vbornand** [comment]
Check here 
https://github.com/prisma-labs/graphql-playground/issues/140
