### ISSUE TITLE
About scaffolding features.

### ISSUE THREAD

**Issue by tanekim77** [ChilliCream/hotchocolate#2210]
It would be great if there are ways to scaffold/generate codes for CRUD methods for a class model. I believe JS libraries like Prisma IO has such feature. 

For example, if I create a user model, it would be great to have an option like 

[IncludeBasicCRUD]
public class User {

}
,
or by right clicking on a project item and clicking new Scaffolding item and clicking Generate CRUD on a model

that will generate/provide queries and mutations like GetUser (with key as param), GetUsers, RemoveUser, RemoveUsers,
UpdateUser, UpdateUsers, AddUser, AddUsers, SubscribeToAddUser, SubscribeToUpdateUser etc.

And one of the generated GetUsers query method would look like

```
    public class UserQueries
    {
        [UsePaging]
        [UseSelection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<ApplicationUser> GetUsers([Service] ApplicationDbContext dbContext)
        {
            return dbContext.Users;
        }

        ...
    }
```
And for mutation for Add/Update users, it will have class like below and also generate input and payload types for each method.
```
    public class UserMutations
    {
        ...
    }
```

And same for Subscriptions.

In case of the first way (i.e. [IncludeBaseCRUID]), it would be better if there is an API that allows customizing the generated methods. But I still prefer 2nd way.

 Is there a feature like this? Or is it being planned in the future? It would help to reduce development time when there are tons of classes to create.

**Comment by erisman20** [comment]
Any plans for this?
