### ISSUE TITLE
[v10.5.x] GraphQLNonNullType causes exception at startup (regression?)

### ISSUE THREAD

**Issue by aloker** [ChilliCream/hotchocolate#2212]
**Description**
Adding a GraphQLNonNullType-attribute to a resolvable property causes the application to crash on startup.

This might be a regression related to https://github.com/ChilliCream/hotchocolate/issues/1222

**Reproduction**
Consider this minimal GraphQL code model:
```
public class Something
{
    public Guid Id { get; set; } = Guid.NewGuid();
}

public class Query
{
    [GraphQLNonNullType] public List<Something> Somethings => new[] {new Something()}.ToList();
}
```

In v10.4.3, this works fine and produces the expected Schema:

```
type Query {
  somethings: [Something!]!
}
```

However, in v10.5.0 and later, the GraphQLNonNullType attribute causes an exception on launch:
```
HotChocolate.SchemaException: Unable to resolve type reference `Output: HotChocolate.Types.NonNullType<HotChocolate.Types.NativeType<System.Collections.Generic.List<HotChocolate.Types.NonNullType<HotChocolate.Types.NativeType<HotChocolate.Types.NativeType<System.Collections.Generic.List<Something>>>>>>>`. - Type: Query
```
Removing the GraphQLNonNullType causes the exception to disappear, but as expected, the schema is different:
```
type Query {
  somethings: [Something]!
}
```
(Something vs Something!)

**Expected behavior**
No crashes, same behavior as 10.4.3

**System**
- Windows 10 Pro 1909
- HotChocolate v10.5.2
- ASP.NET Core 3.1, latest SDK
- nullable checks on (which should not make a difference)

**Comment by PascalSenn** [comment]
You can achieve this by adding the `nullable` argument in v11
For each component there has to be a boolean value provided that handles the nullability:
```csharp
    public class Query
    {
         //                                  | List | Member
        [GraphQLNonNullType(nullable: new[] { false, false })] 
        public List<Something> Somethings => new[] { new Something() }.ToList();
    }
```
```graphql
schema {
  query: Query
}

type Query {
  somethings: [Something!]!
}

type Something {
  id: Uuid!
}
 
```
