### ISSUE TITLE
Unable to switch off default lower-casing of first letter

### ISSUE THREAD

**Issue by whitecobalt** [ChilliCream/hotchocolate#2218]
When using HotChocolate it's default configuration, there doesn't appear to be anyway to turn off the making the first character of each property lowercase. 

I appreciate this is good practice in GraphQL, but it is causing issues for us.

**Comment by PascalSenn** [comment]
naming conventions is what you are looking for
https://hotchocolate.io/docs/conventions

**Comment by whitecobalt** [comment]
Thank you!

I thought there must be something but I couldn't find it.
