### ISSUE TITLE
Optional Method Parameters

### ISSUE THREAD

**Issue by dochoss** [ChilliCream/hotchocolate#2220]
Hi HC guys,

First, fantastic tool you guys are writing.  I like it MUCH better than GraphQL .Net so far.  I've really just started getting into GraphQL in general, but it's simple enough that I think I have a decent understanding of how it works.  I am looking to add GQL to an existing project, and I'd like to have GET methods with optional parameters, so the GQL query would look like this:

```
query { 
  matters { 
    matterName matterId status 
  } 
}
```

However, I'd like the `matters` query to have two optional parameters, `includeDeleted` and `includeHolds`.  I'd like to be able to execute the query with or without these parameters, so that any of these queries would be valid...

```
query { matters(includeHolds:true) { ... } } 
query { matters(includeDeleted:true) { ... } }
query { matters(includeHolds:true, includeDeleted:true) { ... } }
query { matters { ... } }
```

My C# code looks like this: 
```
public List<ExtMatter> GetMatters(bool includeHolds = false, bool includeDeleted = false)
        {
            var matters = _context.Matters
                    .AsNoTracking()
                    .Where(m => includeDeleted
                        ? m != null
                        : m.Status != 999)
                    .Select(m => new ExtMatter().FromMatter(m))
                    .ToList();

            if (includeHolds)
            {
                // ... logic ...
            }

            return matters;
        }
```

But with this code the Playground still requires both parameters.  How can I make these optional?

EDIT: I found I can do this by making the param values `bool?` then doing the necessary checks in the code.  If there's an easier way to do this, please let me know.  Otherwise, you can close this issue.

**Comment by PascalSenn** [comment]
hot chocolate inferes the arguments like defined
the default value of these arguments are false and false
the problem is that they are not nullable. 
default values do not protect you from nullablility issues :) 
if you defined the values as bool? it will be possible to leave them away.

**Comment by dochoss** [comment]
Got it.  Thanks, @PascalSenn!  Closing as solved.
