### ISSUE TITLE
Support for Serilog Request Logging

### ISSUE THREAD

**Issue by RehanSaeed** [ChilliCream/hotchocolate#2221]
**Is your feature request related to a problem? Please describe.**
I use Serilog's [Request Logging](https://github.com/serilog/serilog-aspnetcore#request-logging) feature which allows you to log an entire request and response in a single log message. This reduces the number of log messages and removes the need for correlation of messages when diagnosing an issue.

```cs
application.UseSerilogRequestLogging(
    options =>
    {
        options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
        {
            var request = httpContext.Request;
            var response = httpContext.Response;
            var endpoint = httpContext.GetEndpoint();

            diagnosticContext.Set("Host", request.Host);
            diagnosticContext.Set("Protocol", request.Protocol);
            diagnosticContext.Set("Scheme", request.Scheme);

            if (request.QueryString.HasValue)
            {
                diagnosticContext.Set("QueryString", request.QueryString.Value);
            }

            var clientName = request.Headers["apollographql-client-name"];
            if (clientName.Any())
            {
                diagnosticContext.Set("ClientName", clientName);
            }

            var clientVersion = request.Headers["apollographql-client-version"];
            if (clientVersion.Any())
            {
                diagnosticContext.Set("ClientVersion", clientVersion);
            }

            if (endpoint is object)
            {
                diagnosticContext.Set("EndpointName", endpoint.DisplayName);
            }

            diagnosticContext.Set("ContentType", response.ContentType);
        };
    });
```

**Describe the solution you'd like**
Currently, the only way to add logging of high level Hot Chocolate constructs is via the [IDiagnosticObserver](https://chillicream.github.io/hotchocolate/blog/2019/03/19/logging-with-hotchocolate#diagnostic-observer). However, I understand from @michaelstaib that changes are coming soon in version 11.

I'd like to be able to resolve some kind of service from IoC above and then add query, response and error information from Hot Chocolate to Serilog.

**Comment by michaelstaib** [comment]
@RehanSaeed if you help me on this one we can put a serilog adapter package in. I have no clue on serilog itself but can provide the hc knowledge.

**Comment by RehanSaeed** [comment]
That's great because I own two fairly popular Serilog packages and can supply that knowledge!

The ideal scenario would be something I can get from IoC that can give me metadata about the current GraphQL request. All the magic has to happen in the `EnrichDiagnosticContext` delegate. In the above example, I'm pulling information from the `HttpContext` and pushing that into a single log message for the entire request which makes analysing logs a lot simpler.

**Comment by RehanSaeed** [comment]
@michaelstaib Sure!

**Comment by SbiCA** [comment]
@RehanSaeed @michaelstaib  not sure if you already had time to look into that one? I guess in general there is a need to know what's going on similar to what peter describes in the blog post https://chillicream.com/blog/2021/01/10/hot-chocolate-logging 

I think adding serilog integration will help a lot since @RehanSaeed  already sketched it in the sample with the enrichment of `agent`, `client-version`. I was wondering if there is a nice way to actually enrich the logs with the hotchocolate request context e.g. to see `Query`, `Mutation` and fields `requested` and the `Errors`

Cheers and thx for the great work!

**Comment by jackdh** [comment]
Sorry to slightly grave dig. I can see this was marked as done but I don't see where it was added / the documentation on using it?
