### ISSUE TITLE
Question: queries and mutations in different classes

### ISSUE THREAD

**Issue by fenomeno83** [ChilliCream/hotchocolate#2222]
Hi.
In a real project I need to use "controller-like" approach, to define methods for each group.
For example, in .net I have "WheaterController", "CountryController", each with own methods.

In case of graphql, I have for example "Query" class with inside several methods.
I need to split Query class into QueryWheater and QueryCountry classes for example.
But I can register only 1 Query class with AddQueryType.

How can I have different classes and group them under "Query" class (the one that I register with AddQueryType)?

**Comment by tientq** [comment]
Hope this same code meet your case.

```csharp
/// <summary>
/// The query root of GraphQL interface.
/// </summary>
public class Query
{
}
```

```csharp
[ExtendObjectType(Name = nameof(Query))]
public class DepartmentQuery
{
    // Some queries
```

```csharp
[ExtendObjectType(Name = nameof(Query))]
public class EmployeeQuery
{
    // Other queries
}
```

```csharp
SchemaBuilder.New()
    .AddQueryType<Query>()
    .AddType<DepartmentQuery>()
    .AddType<EmployeeQuery>()
```

**Comment by fenomeno83** [comment]
Thanks! Is what I need!

**Comment by tientq** [comment]
You are welcome.
You should close the issue.

**Comment by fenomeno83** [comment]
> You are welcome.
> You should close the issue.

Sorry. I reopen this question.
But what about I have the same method in different extended object type.

For example I have:
EmployeeQuery with method "Update" and DepartmentQuery with the same method "Update" it will be in conflict?

Maybe need something as extra level that identify group, like
    query{
                 departmentQuery
                 {
                    update
     .....,..................
                  }
             }

**Comment by tientq** [comment]
It's should be: 
UpdateEmployeePayLoad updateEmployee(UpdateEmployeeInput input) 
UpdateDepartmentPayload updateDepartment(UpdateDepartmentInput input)

**Reference to Github GraphQL API v4** https://docs.github.com/en/graphql/reference/mutations#updateissue

**Comment by fenomeno83** [comment]
So, but in that case I have 2 different methods name(updateemployee and updaredeparmente).
I'd like have something like controller style, so have another level that indicated groups (like controller name) and under group I can have the method (update in this case).

For example

       mutation{
             departmentMutation
             {
                update
 .....,..................
              }
             employeeMutation
            {
              update
 ............................
            }
         }

As you can see, we don't have update method directly and "mutation", but we have another level (departmentMutation and employeeMutation) that represents class name(like controller name)

**Comment by tientq** [comment]
You are free to use your naming convention.

**Comment by michaelstaib** [comment]
@fenomeno83 just one important thing with mutations. Only top-level fields on the mutation are mutations, all beneath fields are considered queries on the changed state of the server.

http://spec.graphql.org/draft/#sec-Mutation

**Comment by kfrajtak** [comment]
This extension mechanism works for me, but how can I configure the query type (i.e. the one extending the base one) to support paging as described here https://hotchocolate.io/docs/pagination?

**Comment by kfrajtak** [comment]
I just figured it out ... using the `[UsePaging]` attribute.
