### ISSUE TITLE
Graphql Playground SSL Termination

### ISSUE THREAD

**Issue by cliedeman** [ChilliCream/hotchocolate#2223]
**Describe the bug**
The graphql-playgroud does not work behind an ssl terminating proxy

**To Reproduce**
Enable graphql-playground

```
            app
                .UsePlayground("/graphql");
```

1. Open link https://someurl/graphql/playground
2. See error in console

![image](https://user-images.githubusercontent.com/3578740/90242626-ab79c400-de2d-11ea-8b94-1fe28bd96bdc.png)

**Expected behavior**
The playground should work

I want to submit a pr for this. Adding a force https option to the playground settings but got tripped up by the unit tests

**Comment by benmccallum** [comment]
Are you on asp.net core? 

The best way to fix this is to use the http header forwarding middleware that asp.net core has out-of-the-box. I did this just last week and it worked a treat.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

**Comment by cliedeman** [comment]
@benmccallum Perfect thanks, that is exactly the solution,

Anyone else who stubles on this make sure you don't ignore this [section](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#other-proxy-server-and-load-balancer-scenarios) if you are not behind IIS.
