### ISSUE TITLE
Remove automatic "required" when use pure code first

### ISSUE THREAD

**Issue by fenomeno83** [ChilliCream/hotchocolate#2224]
Hi.
I use code first approach to write graphql types.

I want to make validatation using data annotation on dto.
For dto validation I use this middleware explain in this guide
https://compiledexperience.com/blog/posts/graphql-validate-arguments (see ValidateInputMiddleware)

Here my example dto used as input in a query method

    public class TestRequest
    {
        [Required(ErrorMessage = "required_field")]
        public string Fake { get; set; }

        [RequiredIf(nameof(Fake), "CheckOther", ErrorMessage = "required_field")] 
        public string FakeOther { get; set; }
    }

RequiredIf says: if prop "Fake" has value "CheckOther", so prop "FakeOther" is required

Hot chocolate translate this model in:

    input TestRequestInput {
       fake: String!
       fakeOther: String!
    }

So I need to give value to fakeOther prop ALWAYS

But I want this automatic translation without required

    input TestRequestInput {
       fake: String
       fakeOther: String
    }

Then data validation are made by middleware, where RequiredIf custom annotation will work.

How can I solve?

**Comment by fenomeno83** [comment]
I've temporary solved modifying RequiredIf custom data annotation. 
I've changed from
    
     RequiredIfAttribute : RequiredAttribute
to
    RequiredIfAttribute : ValidationAttribute

and inside made required validation by code
    value==null || string.IsNullOrWhiteSpace(value.ToString())

In this manner graphql type don't take required, but is it validated by ValidateInputMiddleware.

I've build also a custom validation to replace original RequiredAttribute

    public class RequiredAttribute : ValidationAttribute
    {

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {

            if (value == null || string.IsNullOrWhiteSpace(value.ToString()))
            {
                
                string errorMessage = ""This field {0} is required.";
               
                ValidationResult result = new ValidationResult(string.Format(errorMessage, validationContext.DisplayName));
                return result;
            }


            return ValidationResult.Success;
        }

    }

so, also for required attribute , mandatory type is bypassed, but it is validated by ValidateInputMiddleware on dto.

But, can I make this on graphql directly on code first approach?

**Comment by michaelstaib** [comment]
Version 11 now allows ignoring the required attribute.

```csharp
        [Fact]
        public void Ignore_RequiredAttribute()
        {
            // arrange
            var inspector = new DefaultTypeInspector(requiredAttributeAsNonNull: false);
            var services = new DictionaryServiceProvider(typeof(ITypeInspector), inspector);

            // act & assert
            SchemaBuilder.New()
                .AddQueryType<Foo>()
                .AddServices(services)
                .Create()
                .Print()
                .MatchSnapshot();
        }
```

**Comment by michaelstaib** [comment]
This feature will be included in 11.0.0-dev.8

**Comment by fenomeno83** [comment]
@michaelstaib can you add it also in 10 stable version?
Thanks

**Comment by michaelstaib** [comment]
@fenomeno83 we are doing no more fixes or additions for 10.x. We will release 11 at the end of October and are now purely focusing on 11.
