### ISSUE TITLE
How to change DateTime response from Local Time to UTC?

### ISSUE THREAD

**Issue by nikonthethird** [ChilliCream/hotchocolate#2230]
I cannot find a way to set custom `System.Text.Json.JsonSerializerOptions` to change the returned `DateTime` values from Local Time to UTC.

What (if any) is the proper way to do this? I could not find anything in the documentation.

**Comment by michaelstaib** [comment]
Can you describe your problem a little more? Do you have a custom scalar or are you using our internal scalar?

**Comment by RehanSaeed** [comment]
I think this is related: https://github.com/ChilliCream/hotchocolate/issues/4072

**Comment by PascalSenn** [comment]
Closed as this seems stale
