### ISSUE TITLE
Filter based on role or policy

### ISSUE THREAD

**Issue by sascha-andres** [ChilliCream/hotchocolate#2231]
I would like to return filtered data based on the role or policy a user has. That is: in addition to a client provided filter I want to add additional filterings.

Is a custom data loader the way to go?

**Comment by damikun** [comment]
Hello @sascha-andres  i do this in data-loaders....  i take user ID/Name from Httpcontext inside loader and return only data that user is allowed to see by selecting them from DB...  There is also this approach in Facebook to have this in business layer logic and data-loaders are kind of business layer or they have repository connection to it..
