### ISSUE TITLE
Azure Function with EF Core Code First approach not working

### ISSUE THREAD

**Issue by gmavritsakis** [ChilliCream/hotchocolate#2243]
**Describe the bug**
Merging the **Azure Function** example from https://github.com/OneCyrus/GraphQL-AzureFunctions-Ho**tChocolate and the **EF Core** example from https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i gives error 

_Unable to create instance of type `HotChocolate.Types.ObjectType`1_

**Expected behavior**
Should create the types properly

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

**Additional context**

**Comment by PascalSenn** [comment]
How does the constructor of this object type look like?

**Comment by tobias-tengler** [comment]
Closing this for now. If you still have issues with this, please raise a new issue and include a reproduction of the issue.
