### ISSUE TITLE
Assign/Return Query ResultType as Json 

### ISSUE THREAD

**Issue by ganesh-p** [ChilliCream/hotchocolate#2245]
I am trying with Schema First approach where SDL is defined in graphql.schema file.  In Resolver implementation, able to access the input param values from IResolverContext, as business logic, am making an API call, which returns the Result Json.  This has to be returned back as  Query result. How to implement this without define/create Query result type[as class] ? Is there a support for assigning the Json directly to the Result ?

Thank You.

**Comment by PascalSenn** [comment]
I think you should be able to use Dictionary<string, object> for the result.

**Comment by ganesh-p** [comment]
Thank you @PascalSenn for the solution.  Hope, HotChocolate supports complete resolver implementation with Json Manipulation and without defining  types[object/input/result] in C#. Let me try and get back for issues.
Pls. share, any sample application If already available.

**Comment by michaelstaib** [comment]
#2385
