### ISSUE TITLE
Can't create a scope and resolve services in local schema field middleware

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2246]
**Describe the bug**
I use middleware to resolve a service (`IMediator`) in its own scope so that all downstream things have their own scope, specifically DbContext to support parallel exec and DbContext pooling.

This has worked perfectly in remote schemas but fails in local schemas. The service can't be found.

```c#
[AttributeUsage(AttributeTargets.Method)]
public class UseResolverScopedMediatorAttribute : ObjectFieldDescriptorAttribute
{
	private static readonly string _injectedArgumentName = "mediator";
	public override void OnConfigure(
		IDescriptorContext descriptorContext,
		IObjectFieldDescriptor descriptor,
		MemberInfo member)
	{
		descriptor.Use(next => async context =>
		{
			using var scope = context.Service<IServiceProvider>().CreateScope();
			var mediator = scope.ServiceProvider.GetRequiredService<IMediator>();
			context.ModifyScopedContext(c => c.SetItem(_injectedArgumentName, mediator));
			await next(context);
		});
	}
}

// Example resolver method
[UseResolverScopedMediator]
public async Task<string> GetXyzAsync(
    [ScopedState] IMediator mediator) => await mediator.Send(...);
```

If I chuck a breakpoint in the middleware delegate, I can successfully do these:
`context.Service<IServiceProvider>().GetService<IMediator>();`
`context.Service<IMediator>();`

But the actual code, trying to resolve a service from the created scope fails:
`No service for type 'MediatR.IMediator' has been registered.`

**To Reproduce**
See above.

**Expected behavior**
Should be able to create my own scope and get a service resolved from it.

**Desktop (please complete the following information):**
 - OS: Win 10 latest
 - Version: 10.5.2

**Workarounds**
Extremely nasty but does the job in case anyone runs into this before it's fixed:
`context.Service<IHttpContextAccessor>().HttpContext.RequestServices.CreateScope().ServiceProvider.GetRequiredService<IMediator>()`

**Comment by benmccallum** [comment]
From Michael on slack:

> ok found the issue

> We are passing on the application service provider instead of the request service provider
https://github.com/ChilliCream/hotchocolate/blob/04ccc1081b40e079914c94156b201c4666eb2341/src/Stitching/Stitching/Client/RemoteRequestDispatcher.cs#L80

> The buffered request should also store the service provider of the requests:
https://github.com/ChilliCream/hotchocolate/blob/04ccc1081b40e079914c94156b201c4666eb2341/src/Stitching/Stitching/Client/BufferedRequest.cs#L8

> and then we need to pass this on

**Comment by michaelstaib** [comment]
This is solved with 11.
