### ISSUE TITLE
Unable to build dynamic schema

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#2248]
I've been experimenting with building a dynamic schema based on external data / configuration and running into some things that look like bugs. A majority of it appears to work but there's some issues around input types and non null types. 

This is all in `10.5.2`.

Removing as much as possible gives me a sample that looks like
``` csharp
services.AddGraphQL(sp => Schema.Create(c =>
{
    var inputType = new InputObjectType(d =>
    {
        d.Name("TestInput");
        d.Field("name").Type<NonNullType<StringType>>();
    });

    c.RegisterType(inputType);

    c.RegisterMutationType(new ObjectType(d =>
    {
        d.Name("Mutation");

        d.Field("test")
            .Type<StringType>()
            .Argument("input", a => a.Type(new NonNullType(inputType)))
            .Resolver("test");
    }));

    c.RegisterQueryType(new ObjectType(d => d.Name("Query")));
}));
```
The line that we're failing on is setting the argument to the mutation field.  With the same above we get the error
> HotChocolate.SchemaException: Unable to cast object of type 'HotChocolate.Types.NonNullType' to type 'HotChocolate.Types.TypeSystemObjectBase'

Updating that line to 
``` csharp
 .Argument("input", a => a.Type(inputType))
```
gives the following error
> HotChocolate.SchemaException: Unable to resolve dependencies Input: HotChocolate.Types.InputObjectType for type `Mutation`. - Type: Mutation

**Comment by michaelstaib** [comment]
Just noticed that you use `Schema.Create`, have you tried the `SchemaBuilder`? It offers in general more flexibility.
