### ISSUE TITLE
Version 11 target date?

### ISSUE THREAD

**Issue by aTable** [ChilliCream/hotchocolate#2249]
Hi, thanks for all your hard work with Hot Chocolate. I delved into the issues, roadmap, blog and docs page to self service an answer but cant find a hint to when version 11 may be released. I think this is a project in your spare time but was wondering if you could indicate a date?

Asking because [some of the docs](https://hotchocolate.io/docs/security) are difficult to follow which may just be my inexperience with GraphQL in general as I'm not sure how to apply execution timeouts, query depth limiting or query complexity weighting in a pure code first proejct. Perhaps v11 is reworking that code, is coming with more documentation updates or maybe you'd like a contribution to assist :-)

**Comment by michaelstaib** [comment]
We are currently working on the new documentation and the server. We plan for a mid or end of October release.

https://chillicream.github.io/hotchocolate/blog/2020/07/16/version-11

**Comment by michaelstaib** [comment]
P.S.: the link already points to the new site but it is really work in progress ...
