### ISSUE TITLE
Strawberry Shake subquery

### ISSUE THREAD

**Issue by stephannagy** [ChilliCream/hotchocolate#2252]
I'm trying to figure out how to model the graphql file for strawberry shake for doing a filter on a subresource.  We have a type modeled similarly to:

type Thing{
  name: Balance
  id: DateTime
  something(
    limit: Limit
    ids: [ID!]
  ): Something!
}

How would we go about constructing the queries file to model the filter on the type?

**Comment by PascalSenn** [comment]
can you elaborate a bit more? I am not sure if I understand :)
