### ISSUE TITLE
Batch query with export directive and combination of mutation and query does not work

### ISSUE THREAD

**Issue by mortzi** [ChilliCream/hotchocolate#2266]
**Describe the bug**
I want to send a batch request as the following:

```
mutation CreateOwnershipToken{
  createOwnershipToken(input: {
    requestToken: "34f92b7f-2422-434e-aaa9-0842a3c74094"
    verificationToken: "00000"
  }){
        ownershipToken @export(as: "token")
    }
}


query LookUpUser ($token: String!){
    lookUpUser(input:{
    userIdentity:{
      ownershipToken: $token ,
      value:"09371111111"
    }
  }){
    lookupToken
  }
}
```

When running this query, I get an error saying "Variable `token` is not defined". 

HotChocolate v10.4.3

**Comment by PascalSenn** [comment]
this is a validation issue that should be fixed in 11.

**Comment by michaelstaib** [comment]
Are you sure @PascalSenn. My first guess is that the http request might noght be right.

**Comment by michaelstaib** [comment]
@mortzi can you post the HTTP request?

**Comment by michaelstaib** [comment]
@PascalSenn regarding why, the batch request is send to a different middleware that understands that `@export` will create the missing variable.

**Comment by mortzi** [comment]
@michaelstaib This is the HTTP request for this query:

`{
  "Url": "http://localhost:5000/?batchOperations=[CreateOwnershipToken,%20LookUpUser]",

  "Headers": "{}",

  "Body": "{\n  \u0022query\u0022: \u0022mutation CreateOwnershipToken{\\n  createOwnershipToken(input: {\\n    requestToken: \\u002234f92b7f-2422-434e-aaa9-0842a3c74094\\u0022\\n    verificationToken: \\u002200000\\u0022\\n  }){\\n        ownershipToken @export(as: \\u0022token\\u0022)\\n    }\\n}\\n\\n\\nquery LookUpUser ($token: String!){\\n    lookUpUser(input:{\\n    userIdentity:{\\n      ownershipToken: $token ,\\n      value:\\u002209371111111\\u0022\\n    }\\n  }){\\n    lookupToken\\n  }\\n}\\n\u0022,\n  \u0022operationName\u0022: null,\n  \u0022variables\u0022: {}\n}",

  "Method": "POST"
}
`

**Comment by mortzi** [comment]
@michaelstaib Should we expect this request to work? or there is something wrong with it?

**Comment by geekox86** [comment]
Greetings. Is this still an issue in the latest HotChocolate preview version?
