### ISSUE TITLE
Schema stitching locally from multiple files in one project

### ISSUE THREAD

**Issue by kfrajtak** [ChilliCream/hotchocolate#2267]
I'd like to keep things organized and separated. That's why I'd like to define root query fields in separate files, i.e `users`, `products`, etc.

What worked to me was 
```
ISchema schema = HotChocolate.Schema.Create(c =>
{
    c.RegisterQueryType<Query>();
    c.RegisterType<UsersQuery>();
});
```
where `Query` is empty and `UsersQuery` adds `users` field resulting in `query { users { ... } }`. 

Both classes are POCO classes and I can extend the functionality with the attributes
```
[ExtendObjectType(Name = nameof(Query))]
public class UsersQuery 
{
   [UsePaging]
   [UseSorting(SortType = typeof(UserSortType))]
   public IQueryable<User> GetUsers() { ... } 
}
```

But I am loosing here the ability to a more granular configuration and more importantly context:
```
public class UsersQuery : ObjectType<Query>
{
   protected override void Configure(IObjectTypeDescriptor<Query> descriptor) { ... }
}
```

When `UsersQuery` is defined like this and I won't change anything else, it won't appear in the schema.

Can you provide an example on how to achieve this?

**Comment by PascalSenn** [comment]
you have to use ObjectTypeExtension<T> and not ObjectType<T> in this case

**Comment by kfrajtak** [comment]
Thanks, it works.

**Comment by PascalSenn** [comment]
Cool, I will close this issue in this case 👍

**Comment by kfrajtak** [comment]
Ok. Please mention this approach in documentation. Thank you.
