### ISSUE TITLE
Support Route Parameters

### ISSUE THREAD

**Issue by zmhh** [ChilliCream/hotchocolate#2275]
**Is your feature request related to a problem? Please describe.**
In a multi-tenant app it is common to have route parameters like:

`/api/{tenant}/...`

aspnetcore supports this for Controllers, like:

```
[Route("/api/{tenant}/resource")]
[HttpPost]
public async Task<IActionResult> CreateResource(string tenant) {
    ...
}
```

Any post request matching the pattern will resolve to this controller. For example, a request to `/api/hotchocolate/resource` will call this Controller method with `string tenant = "hotchocolate"`. This is needed because the user should authenticate against that tenant, and the data retrieved or modified should only be for that tenant.

`app.UseGraphQL()` method does not support route parameters. It is currently necessary to specify the exact route for the method to work.

**Describe the solution you'd like**
In my opinion the best solution would be for `app.UseGraphQL()` to support route parameters, and for those parameters to be supported as optional parameters in the relevant data fetching methods. In this way the behavior of UseGraphQL would align closely with the behavior of aspnetcore.

**Describe alternatives you've considered**
I am open to alternative solutions for matching on url patterns and multi-tenancy, but have not come up with any.

**Comment by michaelstaib** [comment]
This is already implemented with the current version 11 preview bits. Read hear for further information:
https://chillicream.github.io/hotchocolate/blog/2020/07/16/version-11

**Comment by zmhh** [comment]
Thanks Michael.

**Comment by paulirwin** [comment]
Does anyone have an example of this working? My schema/query/etc works fine without the route parameter, but I attempted to add one (currently unused by the code) and no matter what I put in that parameter (i.e. `/api/projects/123/graphql`) I get a 404:

```C#
app.UseRouting();

app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL("/api/projects/{id}/graphql");
});
```

Using HC 12.13.2. Any help is appreciated. Also, would be interesting to know if I can have dynamic schemas (via type modules?) per route parameter value. (My use case is that each "project" will have its own data-driven schema.) Thanks!

**Comment by paulirwin** [comment]
Upon further debugging, it appears that converting the string argument to `MapGraphQL` to a `PathString` is what is causing this issue. The conversion to `PathString` is escaping the curly braces in the route. Therefore, I do not believe this is currently working and this issue should be re-opened. 

Notice the %7B/%7D URL escaping in the path segments:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/1874103/190006744-34a2aad5-5669-4cb2-965f-2c986a920e32.png">

**Comment by fairok** [comment]
> 

Hey, @paulirwin Does there any solution for the tenant resource?

**Comment by jay-zahiri** [comment]
+1

**Comment by florianbader** [comment]
If someone comes across this: 
Based on #4210 you need to use `MapGraphQLHttp` so you can pass the pattern as string which gets converted to a `RoutePattern`. This for some reason still didn't work for me so I was using `app.MapGraphQLHttp(RoutePatternFactory.Parse("/{tenant}/graphql"))` to manually pass the RoutePattern.
