### ISSUE TITLE
Using HotChocolate and StrawberryShake in the same project

### ISSUE THREAD

**Issue by charles-pp** [ChilliCream/hotchocolate#2276]
Hi All,
I'm working on building an api application which needs to both host and consume GraphQL endpoints.
Currently we are using HotChocolate version 10.1.0 from HotChocolate.AspNetCore. With the introduction of
StrawberryShake version 11.0.0-preview-137, the following runtime error occurs

`Could not load type 'HotChocolate.Language.ObjectTypeDefinitionNode' from assembly 'HotChocolate.Language, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'.`

It was mentioned that with version 11 preview it is possible to use both HotChocolate and StrawberryShake in the same project
https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1596808155028700?thread_ts=1596805271.024700&cid=CD9TNKT8T

Is there a roadmap/timeline of when this might be possible?

**Comment by michaelstaib** [comment]
This is not possible at this moment but we are working on separating the two libs so that they are no longer version dependant.
