### ISSUE TITLE
Batch request with one Operation and multiple queries

### ISSUE THREAD

**Issue by mortzi** [ChilliCream/hotchocolate#2278]
As mentioned in Batching document, I understand that Hot Chocolate supports sending multiple Operations in a single HTTP Post request.

But does Hot Chocolate support executing multiple queries in a single Operation? like:

```
query {
  queryA {
    fieldA @export(as: "foo")
  }
  queryB (input: $foo) {
    fieldB
  }
}
```

However, I executed this query and I get an error saying: "Variable foo is not declared".
I am not sure if it's not supported or a bug.

Thanks guys

**Comment by michaelstaib** [comment]
No, that is not allowed and would violate the spec. When doing it over HTTP we are preprocessing the queries to make them valid, but this query is getting straight to the GraphQL processor which marks them as invalid.

**Comment by michaelstaib** [comment]
Operation batching is the closest to what you ask here.

**Comment by mortzi** [comment]
@michaelstaib Thanks. That's the answer I was looking for.
My problem was that my client supports multiple queries in one operation and not operation batching.
https://github.com/graphql/graphql-spec/issues/375 related to what you mentioned.

**Comment by michaelstaib** [comment]
The problem here is the export directive. Just having multiple root fields in one operation is possible, but each of them is independent from each other.

**Comment by michaelstaib** [comment]
Closing this issue.
