### ISSUE TITLE
Question: Partition Resolution

### ISSUE THREAD

**Issue by zmhh** [ChilliCream/hotchocolate#2281]
Hello,

I am new to GraphQL, so apologies if this question is missing the mark or if I am misusing any terms.

I have objects which are partitioned by a hash of the object ID. There is a service for each partition. There is a gateway service which is responsible for routing our current REST requests to the correct partitions and aggregating results.

I would like to add a GraphQL endpoint hosted on the Gateway. I would like to also host a GraphQL endpoint on each partition, and have the gateway service delegate portions of the overall GraphQL query to the correct partition, then merge the results. I am not sure if this is possible, or how to do this?

For example, if the gateway gets the query:

```
{
  objects(ids: [1, 2, 3, 4]) {
    name
    child_object {
      name
    }
  }
}
```

I would like the gateway to call the GraphQL route for each partition and combine the results:

```
Query to partition 1:
{
  objects(ids: [1, 2]) {
    name
    child_object {
      name
    }
  }
}

Query to partition 2:
{
  objects(ids: [3, 4]) {
    name
    child_object {
      name
    }
  }
}

```

I have seen documentation regarding stitching together schemas of different types, so it seems that it is possible to delegate portions of the GraphQL query to different services. However this seems to be done on the type level, but in this case the partitions have the same types.

I have also seen how I could use Resolvers and DataLoaders to batch and request the items from each partition using our existing REST calls. However this again seems to be on the type level, and I have not seen whether it is possible to "forward" the GraphQL child-query in a resolver, or merge results.

Thank you!

**Comment by zmhh** [comment]
I do see a lot of injectable information in the [resolver docs](https://hotchocolate.io/docs/resolvers), but am not yet sure the best approach to use them, or if doing this on the resolver level is a good idea.

**Comment by zmhh** [comment]
Or perhaps this is a use case for the [Query Rewriter](https://hotchocolate.io/docs/stitching#query-rewriter)?

**Comment by zmhh** [comment]
I guess there is not a good way to do this? The reason I would prefer to forward the graphql sub-query, as opposed to calling partition services via REST inside the gateway data loader, is the similar to the reasons to do schema stitching when types are different - fewer network calls, no need to maintain REST routes, and transmitting only the needed data.

**Comment by michaelstaib** [comment]
You could write a simple middleware for this like we did with schema stitching. The middleware would have the split logic and merge the results back together.

**Comment by zmhh** [comment]
Thanks Michael, that is good to know. I am not as familiar with the internals of the library as you are, would the middleware to look at for inspiration be `DelegateToRemoteSchemaMiddleware` ? Any other types to be aware of?

**Comment by zmhh** [comment]
And would it be correct that this would be a [query middleware](https://hotchocolate.io/docs/middleware#docsNav)?

**Comment by michaelstaib** [comment]
Have you done our graphql-workshop already? It goes into many aspects. 

https://github.com/ChilliCream/graphql-workshop

**Comment by zmhh** [comment]
Thanks Michael, I had not done the workshop. When I have some time I will look through the workshop. Feel free to close this if you want to since it seems to have come to a short term resolution: if someone wants to do this they should create custom middleware, and the workshop can provide inspiration on how to do so.
