### ISSUE TITLE
Suggested to replace Optional<> with [GraphQLOptional]

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#2284]
"Optional<>" brings many problems.

1. Up to now , Optional<int?> is not supported yet.
2. It changed the type of field. So we can not use "AutoMapper" ,"MediatR"

Can you replace "Optional<>" with "[GraphQLOptional]"? we already have "[GraphQLNonNullType]" ,"[GraphQLIgnore]", Why not add another one? it simple and clear.
It won't change any thing.

Please consider this proposal.

**Comment by michaelstaib** [comment]
This would not work, since Optional<T> is keeping the state. Also, Optional<int?> works. we have nullable value types under test. The attribute would have no functionality.

**Comment by zivfuture** [comment]
@michaelstaib   oh.  it terrible news.  It changes the field type.(Nullable<int> ==>  IOption<Nullable<int>>) .
This means I have to give up the other components(Automapper, etc.).  but i really like hotchocolate.

Well.  can you offer us a way to change it by myself?
```
public class InputField
        : FieldBase<IInputType, InputFieldDefinition>
        , IInputField
        , IHasClrType
{
    public InputField(InputFieldDefinition definition) : base(definition)
    {
        ......
        if (propertyType is { }
            && propertyType.IsGenericType
            && propertyType.GetGenericTypeDefinition() == typeof(Optional<>))
        {
            IsOptional = true;
        }
     ......
     // can you change internal to public  and add a setter?
     internal protected bool IsOptional { get; }
}
```
or  add a interface to services container to control it ?   
thanks

**Comment by zivfuture** [comment]
@michaelstaib   Up to now .  I added a ITypeInitializationInterceptor . and try to change the field's IsOptional . I failed. it read only.

**Comment by michaelstaib** [comment]
What are you trying to achieve?

**Comment by michaelstaib** [comment]
If you are able to explain more what your issue at hand is and what you are trying to achieve we might be able to help. 

Regarding `IsOptional`, the type system is immutable and cannot be mutated.

Which version are you using?

**Comment by zivfuture** [comment]
@michaelstaib   version 10.5.2

Field type of database entity is "int?",  "bool?", DTO is IOptional<int?>, IOptional<bool?>.  So, The other github repository "Automapper" can not map DTO to database entity.   I had to write more extra code to map these entities.  this is why i spent lot of time here.

**Comment by PascalSenn** [comment]
Do you really need optional in this case? 
I mean, the only reason to use optional is to know if a value was provided (even when the value is null). If you use automapper anyway, then you probably do not need optional?

**Comment by shidcordero** [comment]
Not a suggestion but is there a way we can make Optional worked on Automapper? Based from the test I have Optional<T?> where T are the different types does not work with Automapper and keeps on throwing this error
```
System.ArgumentException: 'Expression of type 'System.Int32' cannot be used for parameter of type 'System.Nullable`1[System.Int32]' of method 'HotChocolate.Optional`1[System.Nullable`1[System.Int32]] op_Implicit(System.Nullable`1[System.Int32])' (Parameter 'arg0')'
```

Where the model and mapper config that I have was this
```
public class EmployerDuplicateInput
{
    public Optional<int?> Id { get; set; }
    public Optional<int?> EmployerId { get; set; }
    public Optional<int?> DuplicateEmployerId { get; set; }
    public Optional<bool?> IsProcessed { get; set; }
}

public class EmployerDuplicateInputProfile : Profile
{
    public EmployerDuplicateInputProfile()
    {
        CreateMap<EmployerDuplicateInput, EmployerDuplicate>()
            .ForMember(dest => dest.Id, opt => opt.Condition(src => src.Id.HasValue))
            .ForMember(dest => dest.EmployerId, opt => opt.Condition(src => src.EmployerId.HasValue))
            .ForMember(dest => dest.DuplicateEmployerId, opt => opt.Condition(src => src.DuplicateEmployerId.HasValue))
            .ForMember(dest => dest.IsProcessed, opt => opt.Condition(src => src.IsProcessed.HasValue))
            .EqualityComparison((d, s) => d.Id == s.Id)
            .ReverseMap();
    }
}
```

I also tried Precondition and MapFrom like
```
CreateMap<EmployerDuplicateInput, EmployerDuplicate>()
    .ForMember(dest => dest.Id, opt =>
    {
        opt.PreCondition((src) => src.Id.HasValue);
        opt.MapFrom((src) => src.Id.Value);
    })
```

and both of this does not work.

The reason why I do this is because we're implementing Upsert mutations and we want only to map those values that the user pass a value and I know Optional works that way.

**Comment by michaelstaib** [comment]
I am closing this issue since I do not see a way forward for this. It's not worth keeping this issue open since we do not intend to change the behavior here. What you can do is implement a middleware ... you can check against the resolver context if something is provided or not and by thus removing optional from your models.
