### ISSUE TITLE
Schema-First approach example does not work on Introduction page

### ISSUE THREAD

**Issue by jacknugent** [ChilliCream/hotchocolate#2288]
**Describe the bug**
The example code under [2. Schema-First Approach](https://hotchocolate.io/docs/introduction.html) gives me an error.

**To Reproduce**
1. Go to [2. Schema-First approach](https://hotchocolate.io/docs/introduction.html) on the Introduction page.
2. Paste the example code into your `Program.cs`:
```
public class QueryResolver
{
   public string Hello() => "World!";
}

var schema = SchemaBuilder.New()
    .AddDocumentFromString("type Query { hello: String! }")
    .BindResolver<QueryResolver>()
    .Create();

var executor = schema.MakeExecutable();

Console.WriteLine(executor.Execute("{ hello }").ToJson());
```

3. `dotnet run`
4. Get this error: `Unhandled exception. HotChocolate.SchemaException: The field Query.hello has no resolver. - Type: Query`

**Expected behavior**
`{"data":{"hello":"World!"}}`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.6

**Additional context**
This example _does_ work if I rename the `QueryResolver` class to `Query`. I am happy to make that PR if that is in fact the problem.

**Comment by damikun** [comment]
Hello this looks like bug in docs you need to specify how to resolve using Query resolver...

```
    public class QueryResolver
    {
        public string Hello() => "World!";
    }

    class Program
    {
        static void Main(string[] args)
        {

            var schema = SchemaBuilder.New()
                .AddDocumentFromString("type Query { hello: String! }")
                .BindResolver<QueryResolver>(c => c
                    .To("Query")
                    .Resolve("Hello")
                    .With(r => r.Hello()))
                .Create();

            var executor = schema.MakeExecutable();

            Console.WriteLine(executor.Execute("{ hello }").ToJson());
        }
    }
```

**Comment by damikun** [comment]
Corrected under: https://github.com/ChilliCream/hotchocolate-docs/compare/master...damikun:patch-2

**Comment by damikun** [comment]
@jacknugent  All is merged so in next docs build it will be updated...

**Comment by jacknugent** [comment]
Thank you!
