### ISSUE TITLE
missing types in FilterConventionDescriptorExtensions

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2297]
descriptor.BindRuntimeType<Guid, ComparableOperationInput<Guid>>();
descriptor.BindRuntimeType<DateTime, ComparableOperationInput<DateTime>>();
descriptor.BindRuntimeType<DateTimeOffset, ComparableOperationInput<DateTimeOffset>>();
descriptor.BindRuntimeType<TimeSpan, ComparableOperationInput<TimeSpan>>();

those already exist and their nullable counterparts should probably be added in the BindDefaultTypes method

for Guids a custom filter would make sense to me that includes 
Equals, NotEquals, In, NotIn

**Comment by michaelstaib** [comment]
This one os now fixed and merged .... #2310
