### ISSUE TITLE
Possibility to manually apply incoming filter expressions to an IQueryable

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2298]
I have some fixed predicates that go into the my query and I want to pull the expression that the user entered from a query/resolver/filter context and apply it manually to my IQueryably that I'm getting from my db

I also would like to execute that query asynchronously so I can't just return the IQueryable in the resolver

**Comment by TheJayMann** [comment]
Based on my memory, if the IQueryable also happens to implement IAsyncEnumerable, when using the selection middleware, it does execute the query asynchronously.  Unless you have some other requirement regarding executing the IQueryable asynchronously.

**Comment by MariaCobretti** [comment]
well.. the queryable provider in the .net cosmos v3 sdk that I'm using does not implement IAsyncEnumerable

I also don't think the selection middleware is going to apply the filters?
anyhow.. I thinks its very useful to be able to grab the graphql filter expression and manipulate it in various ways

**Comment by TheJayMann** [comment]
My memory was was not correct earlier, as now I remember the async execution was in the first result and single result middleware components.

However, one thing that you could do is implement a middleware component, make sure it comes before the filter middleware but after any middleware which would resolve an IQueryable, then the Result value in the context parameter after having called the next middlware will be the IQueryable that you returned from your field resolver but with the filters already applied to it.  This will work well if you need to do the same or similar enough process to all of your IQueryable collections after the filters have been applied, not so much if each collection needs to be processed differently.  In the latter case, you might have to implement your own filtering process somehow, but, in that case, I believe there is an extension method that modifies the schema to include all of the filtering options but does not add the filtering middleware, allowing you to process it yourself.

**Comment by MariaCobretti** [comment]
sorry for the late response..

@TheJayMann I have tried your idea with a middleware and was able to solve the filtering for the more static parts of my schema.
For that I can apply something to the IQueryable and execute it async in the middleware. the only issue then is when I add paging, as I it can't really execute the IQueryable async.. I have not yet dove into the inner workings of the paging middleware to see how it works and why it different from the filtering one.

another even more important problem I have is that a part of the schema is generated dynamically. That means that the user filters on fields that dont exist in the database.. there the field names are replaced with guids to access them.

so i have to swap the field names with those keys somewhere down the pipeline

e.g. 
where { myFieldName:  { eq: "inputstring" } } 
becomes to
where { properties["_f860074e4bec4d4a9a6e3d4805c90432"]:  { eq: "inputstring" } }    <-- this does not exist in schema

or looking from the database side:

queryable.Where(x => x.MyFieldName == "inputstring");     <-- this does not exist in the db
vs
queryable.Where(x => x.Properties["_f860074e4bec4d4a9a6e3d4805c90432"] == "inputstring");

@PascalSenn in the other issue #2299 you mentioned an idea for exposing visitors.
descriptorContext.TryCreateFiltering(out Expression<Func<TEntityType, bool>> where);

or whats your take on this?

**Comment by PascalSenn** [comment]
@MariaCobretti 
yes something like this. Just didnt find the time to do it. :)

**Comment by MariaCobretti** [comment]
ok, good to hear that you got the idea to how make this work. do you mind reopening this issue for when you got the time to come around this one again?

**Comment by MariaCobretti** [comment]
hey @PascalSenn 
I finally managed to get this to work and wanted to share it with you, also because it required some small changes to HC

Essentially, I needed to change the behavior of the QueryableDefaultFieldHandler to build the expression whenever it encounters a field that is part of one of my dynamic objects.
 In order to build the expression correctly I need some additional context data in the QueryableFilterContext

this brings me to the following classes

```
public class CustomQueryableDefaultFieldHandler : FilterFieldHandler<CustomQueryableFilterContext, Expression>
public class CustomQueryableFilterProvider : FilterProvider<CustomQueryableFilterContext>
public class CustomQueryableFilterContext : QueryableFilterContext
```
important to note here is that CustomQueryableFilterContext implements QueryableFilterContext which make it easy to extend with a small change in HC which is

```
public class QueryableCombinator<TContext>
        : FilterOperationCombinator<TContext, Expression> where TContext : QueryableFilterContext
```

my Startup.cs

```
.AddFiltering(x =>
{
   x.AddDefaultOperations().BindDefaultTypes();
   x.Provider(new CustomQueryableFilterProvider(c => c
      .AddFieldHandler<CustomQueryableDefaultFieldHandler>()
      .AddDefaultFieldHandlers()
   ));
})
```

one other important thing is that the schemaType on which the filter is build differs from the entityType returned by the db.
So to inject the propper types into the filter provider, another .UseFiltering extension is needed, similar to the paging api

```
public static IObjectFieldDescriptor UseFiltering(
            this IObjectFieldDescriptor descriptor,
            Type schemaType,
            Type? entityType,
            string? scope = null)
```

lastly I changed the QueryableScope constructor to take a System.Type parameter instead of an IExtendedType, which I was unable to produce for my entityType

also I'd like the ErrorHelper to be public since it is used in the CustomQueryableDefaultFieldHandler 

I can drop you a pull request if you want

Greetings

**Comment by PascalSenn** [comment]
hi @MariaCobretti 
cool that you got i working! i like the idea of the entity type. i think in case of dtos this could be helpful too
in a future release we want to support this natively so no need for automapper and such
for projections we also meed a slight change to the filtering api, we need to add the filter context to the context data of the field. 
this would also enable you to pull it by yourself from the context data and apply it manually
we do not want the base visitor classes to depend on system.type because this should also work with schema first at some point
in case of queryable a runtime type is obviously something that is needed
i think a PR to discuss the api changes would be nice, if it is not too much work :)

**Comment by MariaCobretti** [comment]
sure thing, let me know what I need to do.. I'm getting a 403 when trying to push my branch as expected

**Comment by PascalSenn** [comment]
you can either 
1. fork the repo
2. copy the git link
3. git remote add fork <<link>>
4. git push --set-upstream fork branchname 
5. go to github and create a pr 👍 

or wait till @michaelstaib  granted you permissions to push to the github repository :)

**Comment by MariaCobretti** [comment]
done 👍 
happy to discuss the changes and contribute further
