### ISSUE TITLE
missing System.Type argument in the .UseFiltering() extension

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2299]
I have a dynamic schema that I create by generating .net types with reflection.emit and pass them to the HC schema builder with code first and the .Type(System.Type) extension.. now I would like the same for .UseFiltering() .. 

the UseFilteringAttribute class already supports this

the UseFiltering() method would look something like this

`
public static IObjectFieldDescriptor UseFiltering(
            this IObjectFieldDescriptor descriptor,
            string? scope = null,
            Type? filterType = null)
        {
            if (descriptor is null)
            {
                throw new ArgumentNullException(nameof(descriptor));
            }

            if(filterType != null)
            {
                filterType =
                typeof(IFilterInputType).IsAssignableFrom(filterType)
                    ? filterType
                    : typeof(FilterInputType<>).MakeGenericType(filterType);
            }

            return UseFiltering(descriptor, filterType, null, scope);
        }
`

**Comment by MariaCobretti** [comment]
the same goes for the .UsePaging() extension

**Comment by PascalSenn** [comment]
@michaelstaib  should we add a parameter to UseFiltering that allows to skip the middleware and then create a helper for visitation and such? 

Like: 
```csharp
fieldDescriptor.UseFiltering(skipMiddlware: true);
```
```csharp
descriptorContext.TryCreateFiltering(out Expression<Func<TEntityType, bool>> where);

```

**Comment by PascalSenn** [comment]
Filteringextensions are in the current preview available.

**Comment by PascalSenn** [comment]
could you open a new issue for paging?

**Comment by michaelstaib** [comment]
Paging btw now has also a type argument.
