### ISSUE TITLE
Schema first, nested array field causes exception when creating schema

### ISSUE THREAD

**Issue by trenttobler** [ChilliCream/hotchocolate#2319]
**Describe the bug**
It appears "schema-first" for a graphql schema containing a field specified as a nested list fails with Hot Chocolate parser / schema factory.

**To Reproduce**
1. Create a console .NET core app: `dotnet new console` in an empty folder (bug)
2. edit bug.csproj and add the nuget package for Hot Chocolate:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate" Version="10.5.2" />
  </ItemGroup>

</Project>
```
3. edit Program.cs, and try to load a schema with a nested array:
```
using HotChocolate;

namespace bug
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema = SchemaBuilder.New()
                .AddDocumentFromString( @"
                type Query {
                    fixme: [[String!]!]!
                }
            " )
            .Create();
        }
    }
}
```

3. Run the code: 'dotnet run'

4. Observe exception:
```
Unhandled exception. HotChocolate.SchemaException: Specified method is not supported.
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
   at bug.Program.Main(String[] args) in /workspaces/CsPlay/bug/Program.cs:line 10
```

Drilling into the Errors field leads me to believe exceptions is thrown at this line of code -- https://github.com/ChilliCream/hotchocolate/blob/a7b1f39c686d2d572f0ef61ff9d8c0ceea90b795/src/HotChocolate/Language/src/Language.SyntaxTree/Extensions/TypeNodeExtensions.cs#L49)

**Expected behavior**
Errors indicating missing bindings to the field.  If you remove one level of bracket from the fixme type, you can see a binding exception, but this would be expected for this specific code snippet since bindings have not been set yet... E.G
```
Unhandled exception. HotChocolate.SchemaException: The field `Query.fixme` has no resolver. - Type: Query
   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
   at bug.Program.Main(String[] args) in /workspaces/CsPlay/bug/Program.cs:line 10
```

**Desktop (please complete the following information):**
 - OS: windows 10 (linux docker container)
 - .Net core 3.1

**Additional context**
See https://spec.graphql.org/June2018/#ListType - I could not find any restrictions on the nesting of types within the list or NonNullType spec here.

**Comment by michaelstaib** [comment]
This is already fixed with version 11 which can be used as preview 11.0.0-dev.11 and will be released at the end of October.
