### ISSUE TITLE
Unable to use "app.UseGraphQL" inside Configure(IApplicationBuilder app, IWebHostEnvironment env) HC DEV REL 10

### ISSUE THREAD

**Issue by ganesh-p** [ChilliCream/hotchocolate#2327]
After upgrading to the dev version of Hotchocolate & HotChocolate.aspnetcore to DEV Release 11.0.0-dev.11, unable to use "UseGraphQL" method on ApplicationBuilder object inside "Configure" method of "Startup" Class. Is there any other way to add the middleware to the server. Is the latest release supports splitting large schema into multiple files.

Thankyou.

**Comment by michaelstaib** [comment]
The configuration API has changed:

https://github.com/ChilliCream/graphql-workshop/blob/version-11/code/GraphQL/Startup.cs
