### ISSUE TITLE
Unable to resolve service for type 'HotChocolate.AspNetCore.Utilities.IHttpResultSerializer

### ISSUE THREAD

**Issue by chielos24** [ChilliCream/hotchocolate#2332]
**Describe the bug**
System.InvalidOperationException: 'Unable to resolve service for type 'HotChocolate.AspNetCore.Utilities.IHttpResultSerializer' while attempting to activate 'HotChocolate.AspNetCore.HttpGetMiddleware'.'

Having this code setup
```
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGraphQL();
            });
```

Using 11.0.0-dev.xx

Am i missing packages?
Current list:
```
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="3.1.1" />
    <PackageReference Include="HotChocolate.Abstractions" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.AspNetCore.Abstractions" Version="10.5.2" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.AspNetCore.HttpGet" Version="10.5.2" />
    <PackageReference Include="HotChocolate.AspNetCore.HttpGetSchema" Version="10.5.2" />
    <PackageReference Include="HotChocolate.AspNetCore.Playground" Version="10.5.2" />
    <PackageReference Include="HotChocolate.Execution" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.Types" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.Types.Filters" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.Types.Selections" Version="11.0.0-preview.133" />
    <PackageReference Include="HotChocolate.Types.Sorting" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.Utilities" Version="11.0.0-dev.10" />
    <PackageReference Include="HotChocolate.Validation" Version="11.0.0-dev.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.6">

```

**Comment by PascalSenn** [comment]
you should really not mix versions in package references :) 
What features are you using?

**Comment by chielos24** [comment]
I Actually like to do this:
https://github.com/ChilliCream/hotchocolate/issues/1459#issuecomment-600213767
So i updated my references to 11. But came into this problem.

**Comment by PascalSenn** [comment]
ahh ok. 
so we did a rewrite of filtering. You can still use the old one with 11 but the new one is descirbed here: 
https://github.com/ChilliCream/hotchocolate/blob/pse/filtering-blogpost/website/src/blog/2020-09-16-new-filtering-api/2020-09-16-new-filtering-api.md
This blog is still under construction :)

**Comment by michaelstaib** [comment]
Also, remove all the packages apart from 

```
<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.0-dev.13" />
```

If you want the new filtering add:
```
<PackageReference Include="HotChocolate.Data" Version="11.0.0-dev.13" />
```

If you want the old filtering add:
```
<PackageReference Include="HotChocolate.Types.Filters" Version="11.0.0-dev.13" />
<PackageReference Include="HotChocolate.Types.Sorting" Version="11.0.0-dev.13" />
```

You cannot mix versions. Selections are at the moment not supported. Also, the playground middleware is not supported.

**Comment by michaelstaib** [comment]
We have an example in the works:
https://github.com/ChilliCream/graphql-workshop

**Comment by chielos24** [comment]
thanks. works for me!

Only i was setting filters explicity before (BindFiltersExplicitly) but not sure how this will work.
Also sorting not sure how.

But hey, i have to be patient, you are probably implementing this on v11.

**Comment by astrandr** [comment]
adding: builder.Services.AddGraphQLServer(); solved the problem for me. My program.cs file:
using GraphQLTest;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer();
builder.Services.AddGraphQL().AddQueryType<Query>();

var app = builder.Build();

app.MapGraphQL();

app.Run();
