### ISSUE TITLE
Strawberry Shake: Optional<T> HasValue Should Be False for Null or Have Constructor with HasValue

### ISSUE THREAD

**Issue by zmhh** [ChilliCream/hotchocolate#2343]
**Is your feature request related to a problem? Please describe.**
I was getting the error "EXEC_INVALID_TYPE". It turns out that this is because I was setting one of the generated Optional<T> parameters to null, which resulted in an Optional<T> with Value = null and HasValue = True.

**Describe the solution you'd like**
I would prefer if setting the property to null did not implicitly result in an Optional<T> with HasValue = True. Instead it should be the same as if the property were not set.

**Describe alternatives you've considered**
As an alternative I would like a constructor for Optional<T> that accepts HasValue as a constructor, so I can use null coalescing to set null properties to an Optional<T> with HasValue = false.

**Additional context**
In my case I was initializing the object like:

```
new ObjectInput() {
  FirstProp = internalModel.FirstProp?.ToInput()
}
```

I do this because I did not want to use duplicated types per query (IObject, IObject1, etc.) which could change when re-generated depending on the number and order of queries in Queries.graphql. Instead I have an internal model that I then have .ToInput() and .ToModel() calls to convert to and from the generated GraphQL types, and a wrapper client that does the conversion.

**Comment by michaelstaib** [comment]
> I was getting the error "EXEC_INVALID_TYPE". It turns out that this is because I was setting one of the generated Optional parameters to null, which resulted in an Optional with Value = null and HasValue = True.

This is actually the expected behavior... The optional is there to express intend. If you pass on null than you have explicitly set it to the value null .... if you want to have it unset, set it to default.

**Comment by zmhh** [comment]
Thanks Michael. I did not realize that "default" would have the behavior I was desiring, but I can see now that that would work when doing property initialization like my case.
