### ISSUE TITLE
Strawberry Shake: No Type Duplication

### ISSUE THREAD

**Issue by zmhh** [ChilliCream/hotchocolate#2344]
**Is your feature request related to a problem? Please describe.**
The generated client in Strawberry Shake cannot be used directly because a type is produced per query, which makes it difficult to use the code since one would have to write conversion code for each type. Additionally if the Queries.graphql file is modified then the types may change and break calling code.

**Describe the solution you'd like**
I would prefer if I was able to use a single type per GraphQL type when interacting with Strawberry Shake.

**Describe alternatives you've considered**
Alternatively, an option to have a single type per GraphQL type.
Alternatively, a type per query / mutation based on the query / mutation name, rather than the order in the Queries.graphql file. This way at least we can add or remove queries without breaking existing code.

**Comment by PascalSenn** [comment]
this is the intended behavior. The idea is to generate dotnet types for the queries and not for the graphql types. This way you know what fields are requested and where they are used. It happens so often that you miss field in a request and then expect it to be there in the result value. 

If you want to use the types directly fragments can be a help. We also generate types for fragments and they should be stable.

**Comment by zmhh** [comment]
That makes sense Pascal.

That is an interesting idea for fragments. That would improve stability at least, so changes to Queries.graphql does not break the existing code. Thanks!
