### ISSUE TITLE
Add OpenTelemetry Instrumentation

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#2351]
**Is your feature request related to a problem? Please describe.**
Add instrumentation to trace queries/mutations and (maybe) subscriptions

**Describe the solution you'd like**
Example for Quartz.NET
Instrumentation tracing each fired job, marks execution on error

Good to have same thing, but for HC
https://github.com/quartznet/quartznet/tree/master/src/Quartz.OpenTelemetry.Instrumentation

**Comment by michaelstaib** [comment]
We have added to 11 a new abstraction that can be used to implement such a thing. We will update our docu soon on this. However, we will not implement any specific way to report telemetry and leave this up to the community.

**Comment by sergeyshaykhullin** [comment]
@michaelstaib It is not *specific* way, it is **standard** way for OpenTelemetry

1. [HTTP](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http/0.6.0-beta.1)
2. [AspNetCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore/0.6.0-beta.1)
3. [SqlClient](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.SqlClient/0.6.0-beta.1)
4. [StackExchangeRedis](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.StackExchangeRedis/0.6.0-beta.1)
5. [Grpc](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.GrpcNetClient/0.6.0-beta.1)
6. [Quartz](https://www.nuget.org/packages/Quartz.OpenTelemetry.Instrumentation/)
7. [MassTransit](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/master/src/OpenTelemetry.Contrib.Instrumentation.MassTransit)
8. [Elasticsearch](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/master/src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch)
9. [EntityFrameworkCore](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/master/src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore)

Do you mean that OpenTelemetry is not only way to collect and report telemetry and that's why will not implement?

**Comment by michaelstaib** [comment]
Yes, and I think there are many ways how to implement it. We no provide a simple way to implement these things but I do not see this a something we need in the core. My thoughts might change on this, but for the next two releases we will not work on this.

However, if you want to do this we are happy to help you. But in this case outline in an issue how you want to implement it, and what events you want to provide when.
