### ISSUE TITLE
Support `[UnionType, InterfaceType]` on one C# type

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2367]
**Is your feature request related to a problem? Please describe.**
Simpler declaration in pure-code first of a base type that can act as a union and an interface.

**Describe the solution you'd like**
Support both attributes, creating a schema type for each. One would obviously need to specify an explicit name to be unique from the default derived from the annotated class/interface.

```c#
[UnionType, InterfaceType(Name = "Animalable")]
public interface IAnimal { }

// Startup
.AddType<IAnimal>()
.AddType<Dog>()
.AddType<Cat>()
```

Order would matter, in a similar way to below when hooked up via startup. e.g. pure code first uses of `IAnimal` would be typed in the schema (by default) as the type of the first attribute.

**Describe alternatives you've considered**
Below is the way to do it now (order matters).
```c#
public interface IAnimal { }

// Startup
.AddUnionType<IAnimal>()
.AddInterfaceType<IAnimal>(d => d.Name("Animalable"))
.AddType<Dog>()
.AddType<Cat>()
```

(doesn't work though, on v10.5 anyway, see comment below)

**Additional context**
Really just a nice-to-have, not a priority at all.

**Comment by benmccallum** [comment]
It actually seems like (at least on v10) the alternative workaround above doesn't ever add the types into the interface, so that's a bummer.

**Comment by michaelstaib** [comment]
@benmccallum we have reviewed this and will not implement this. We think it is to much work for such a small use-case. We however will cover your use-case in a better way with the new mutation error type generation that use stage 6a of the errors guide.

**Comment by benmccallum** [comment]
No worries @michaelstaib , I think the workaround works on v11 anyway as I did that the other day, so it's fine. It was more an issue when that didn't on V10.
