### ISSUE TITLE
UseSelection and could not load type 'HotChocolate.Utilities.TypeInfo'

### ISSUE THREAD

**Issue by toralux** [ChilliCream/hotchocolate#2369]
I'm trying the example here, just with Npgsql.EntityFrameworkCore.PostgreSQL instead of Microsoft.EntityFrameworkCore.Sqlite:
https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

This works fine:
```
public class Query
{
    public IQueryable<Student> GetStudents([Service] FleetFlowDbContext fleetFlowDbContext) =>
        fleetFlowDbContext.Students;
}    
```

However if I add [UseSelection] annotation on top of GetStudents() i get this error when opening Playground:

>An unhandled exception has occurred while executing the request.
HotChocolate.SchemaException: For more details look at the `Errors` property.
Could not load type 'HotChocolate.Utilities.TypeInfo' from assembly 'HotChocolate.Types, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'. (ExampleProject.Query)

HotChocolate.* version: "11.0.0-preview.141
HotChocolate.Playground version: 10.5.2

**Comment by PascalSenn** [comment]
Use selection is not yet supported in 11. 
Also, you should not mix dependency verisons :)

**Comment by michaelstaib** [comment]
I am closing this issue since the question has been answered.
