### ISSUE TITLE
Support for IQueryable in DataLoaders

### ISSUE THREAD

**Issue by ng923** [ChilliCream/hotchocolate#2374]
Hello! I'm working on graphql endpoint over sql database. And I'd like to consolidate queries as much as possible. Right now I use BatchDataLoaders to enrich some classes with properties which don't have relations in db schema. In this way I can only explicitly use Includes inside DataLoader.  So my question is: Is there any ability for dataloaders behave like IQueryable in the QueryObject to avoid explicit Includes and selecting all properties of included objects?

Looks like the same problem was discussed here: https://github.com/ChilliCream/hotchocolate/issues/553

**Comment by Jonatthu** [comment]
@michaelstaib Any response to this issue?

**Comment by Jonatthu** [comment]
@rstaib any response to this old issue? I am trying to accomplish the same.

```
	[ExtendObjectType(typeof(User))]
	public class UserExtensions
	{
		[BindMember(nameof(User.Posts))]
		[UseTemplateDbContext]
		[UsePaging(IncludeTotalCount = true)]
		[UseProjection]
		[UseFiltering]
		[UseSorting]
		public Task<IQueryable<Post>> GetPostsAsync(
			[Parent] User user,
			IResolverContext context,
			[ScopedService] TemplateDbContext dbContext,
			CancellationToken cancellationToken
		)
		{
			return context.GroupDataLoader<int, Post>(
				async (keys, ct) =>
				{
					List<Post> result = await dbContext.Posts
						.Where(x => keys.Contains(x.UserId))
						.ToListAsync(ct);
					return result.ToLookup(x => x.UserId);
				}).LoadAsync(user.Id, cancellationToken);
		}
	}
```

**Comment by arctouch-sergeymetlov** [comment]
Any chance to reopen?

**Comment by michaelstaib** [comment]
Not really as this does not really make sense as outlined here.

We are thinking about projectable DataLoader for database-first scenarios. But we are still in the concept phase on this one.

**Comment by Arrivegrsmith** [comment]
@michaelstaib I'm working on a project with entity framework, noticed that [UseProjection] didn't apply to the generated queries! I would definitely appreciate the DataLoader/GroupDataLoader to benefit from Projection.
