### ISSUE TITLE
Order_by in Hotchocolate v11

### ISSUE THREAD

**Issue by jeffason1997** [ChilliCream/hotchocolate#2376]
I know you guys are busy working on the v11 of hot chocolate but I was wondering if it is possible to use the order_by somehow?

I Use the following packages

`<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.0-dev.17" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="11.0.0-dev.17" />
    <PackageReference Include="HotChocolate.AspNetCore.Playground" Version="10.5.2" />
    <PackageReference Include="HotChocolate.Data" Version="11.0.0-dev.17" />`

my current Query is:
`query {
  payments(
    logicalAccountID: "some Account"
    skip:10
    take:10
    where: {currency: {contains: "GBP"}}
  ) {
    items {
      iD
      order {
        iD
        customerAccount {
          merchant {
            name
          }
        }
      }
    }
  }
}
`

And in v10 we used this Query
`query {
  payments(
    logicalAccountID: "some account"
    order_by: { createdAt: DESC }
    first: 50
  ) {
    nodes {
      iD
      order {
        iD
        customerAccount {
          merchant {
            name
          }
        }
      }
    }
  }
}
`

**Comment by PascalSenn** [comment]
yes UseSorting is supported in the latest previews

there are a couple bugfixes comming, PR are already open

you need to use order instead of order_by

**Comment by jeffason1997** [comment]
@PascalSenn any idea when to expect those bugfixes
