### ISSUE TITLE
Subscriptions don't appear to work on local IIS

### ISSUE THREAD

**Issue by TAGC** [ChilliCream/hotchocolate#2382]
**Describe the bug**

I'm developing an ASP.NET Core 3.1 application that supports a couple of subscription operations. Both of these operations work fine when running my application in Visual Studio, either by launching as a console app or via IIS Express. However, after publishing this application to local IIS, the subscriptions don't appear to work.

The way that my application works is that it launches a background service that connects to an instance of [EventStore](https://eventstore.com/) and connects to a couple of event projections. When events are detected on those projections, it queries a SQL server database for updated data and publishes an event using the GraphQL `ITopicEventSender`:

```cs
// ...
using var scope = _serviceScopeFactory.CreateScope();
var repository = scope.ServiceProvider.GetRequiredService<SalesOfficeRepository>();
var eventSender = scope.ServiceProvider.GetRequiredService<ITopicEventSender>();
var order = await repository.GetOrderById(orderId);

if (order is null)
{
    _logger.LogWarning(
        "Event detected for order {OrderId} but this order was not found in the database",
        orderId);

    return;
}

await eventSender.SendAsync(stream, order);
```

I'm testing this out by creating a subscription request through GraphiQL and then manually raising events on EventStore by hitting the "Add" button in the image below:

![image](https://user-images.githubusercontent.com/1588951/94349868-b173df00-0040-11eb-9e12-03f699f4126e.png)

As a console app and when running in IIS Express, I immediately see the expected data appear in the output window. However, after being deployed to local IIS, every time I fire an event the spinner keeps on spinning as if it's still waiting for an event to occur. I can see from the IIS logs that the application is still connecting to EventStore fine and picking up these events:

```
trce: MyCompany.Sales.AntiCorruption.EventStore.EventStoreMonitor[0]

      Event detected on event stream SO_Order-8058432
```

My application also supports standard queries and these work fine across all environments, including the deployed IIS version.

Is there something that could explain this behaviour, or something I can add to my `DiagnosticLogger` to help me debug this issue (currently it only logs GraphQL queries and their responses)?

**Expected behavior**

I expect that all types of GraphQL requests work the same across all environments:
 - Console app
 - IIS Express
 - Local IIS

**Desktop:**
 - OS: Windows 10 
 - Version 1909

**Additional context**

The relevant parts of my `Startup` class are included below:

```cs
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddLogging();
        services.AddDiagnosticObserver<DiagnosticObserver>();
        
       // ...

        services.AddGraphQL(sp => SchemaBuilder.New()
            .AddServices(sp)
            .AddQueryType<Query>()
            .AddSubscriptionType<Subscription>()
            .AddType<BranchType>()
            .AddType<ProductConsultantType>()
            .Create());

        services.AddInMemorySubscriptions();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseRouting();
        app.UseWebSockets();

        app.UseGraphQL(new QueryMiddlewareOptions
        {
            Path = "/graphql",
            SubscriptionPath = "/graphql/"
        });

        app.UseGraphiQL("/graphql");

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGet("/", context =>
            {
                context.Response.Redirect("/graphql/graphiql", true);
                return Task.CompletedTask;
            });
        });
    }
}
```

I model my subscriptions like this:

```cs
public class Subscription
{
    /// <summary>
    /// Subscribes to any potential changes to the specified product consultant.
    /// </summary>
    /// <param name="id">The product consultant ID</param>
    /// <param name="eventReceiver"></param>
    /// <param name="cancellationToken"></param>
    [SubscribeAndResolve]
    public async ValueTask<IAsyncEnumerable<ProductConsultant>> OnProductConsultantUpdated(
        int id,
        [Service] ITopicEventReceiver eventReceiver,
        CancellationToken cancellationToken)
    {
        var eventName = EventStoreMonitor.GetEventNameForProductConsultant(id);
        return await eventReceiver.SubscribeAsync<string, ProductConsultant>(eventName, cancellationToken);
    }

    /// <summary>
    /// Subscribes to any potential changes to the specified order.
    /// </summary>
    /// <param name="id">The order ID</param>
    /// <param name="eventReceiver"></param>
    /// <param name="cancellationToken"></param>
    [SubscribeAndResolve]
    public async ValueTask<IAsyncEnumerable<Order>> OnOrderUpdated(
        int id,
        [Service] ITopicEventReceiver eventReceiver,
        CancellationToken cancellationToken)
    {
        var eventName = EventStoreMonitor.GetEventNameForOrder(id);
        return await eventReceiver.SubscribeAsync<string, Order>(eventName, cancellationToken);
    }
}
```

**Comment by michaelstaib** [comment]
Have you enabled WebSockets support for IIS?

**Comment by TAGC** [comment]
Thanks, that was exactly it. I didn't realise websocket support needed to be explicitly enabled for IIS.

This is a great library by the way. It's my first time working with GraphQL and it was a toss-up between HotChocolate and GraphQL.NET. I went with this and it seems to have been the right choice, because I've got pretty much everything I need set up on the server side of things for the time being. On to the client.

**Comment by PascalSenn** [comment]
@TAGC  What kind of client? Dotnet or JS?

**Comment by TAGC** [comment]
Dotnet

**Comment by PascalSenn** [comment]
have you seen strawberry shake? 
It is still in preview and there is not many documentation around it yet. but essentially it generates a c# client based on the queries you specify :) 
There will be a major update to docs and code in the future after we released v11. 
https://chillicream.com/blog/2019/11/25/strawberry-shake_2

**Comment by TAGC** [comment]
I've seen it yeah, and I read that article, but I think I'm going to go with the GraphQL.NET client for the time being just because it's more established and there's more documentation around it. My schema is simple enough that I'd prefer to write the code for it on the client-side by hand.

I might take another look after the v11 release.
