### ISSUE TITLE
Nodes in pure code first

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#2386]
As of now, there is no way really to specify a node in pure code first. 
This proposal will line out how we could solve this. 

In order to mark an entity as a node, we will introduce a new attribute called `NodeAttribute`.

```csharp
[Node]
public class Foo 
{
    [ID] public string Id { get; set; }
}
```

We already have the ID attribute to mark a global ID. Still, if the `id` field is not represented by a property called `Id` or `ID` or by a method called `GetId`, `GetID`, `GetIdAsync`, `GetIDAsync` one needs to specify the member that represents the id on the node attribute:

```csharp
[Node(IdField = nameof(SomeId))]
public class Foo 
{
    [ID] public string SomeId { get; set; }
}
```

Next, we also need to specify a node resolver that we can use in the `node` field to effectively load the node by its id.

This node resolver shall have the same argument injection as other resolvers. By default we will look on the entity type for a static method called `Get{EntityName}Async(...)` or `GetAsync(...)` or `GetByIdAsync(...)` or `Get{EntityName}ByIdAsync(...)`.

```csharp
[Node(IdField = nameof(SomeId))]
public class Foo 
{
    [ID] public string SomeId { get; set; }

    public static async Task<Foo> GetAsync([ID]string id, [Service]IFooRepository) 
    {
        // some code ....
    }
}
```

Again one can specify the name on the node attribute:

```csharp
[Node(
    IdField = nameof(SomeId),
    NodeResolver = nameof(GetAsync))]
public class Foo 
{
    [ID] public string SomeId { get; set; }

    public static async Task<Foo?> GetAsync([ID]string id, [Service]IFooRepository) 
    {
        // some code ....
    }
}
```

The node resolver can also be put on a different type.

```csharp
[Node(
    IdField = nameof(SomeId),
    NodeResolverType = typeof(FooResolver))]
public class Foo 
{
    [ID] public string SomeId { get; set; }

    public static async Task<Foo?> GetAsync([ID]string id, [Service]IFooRepository) 
    {
        // some code ....
    }
}

public class FooResolver 
{
    public static async Task<Foo?> GetAsync([ID]string id, [Service]IFooRepository) 
    {
        // some code ....
    }
}
```

The separate resolver type can be a static class or a standard class. If the resolver is not static it must be registered with the DI.

You can also put multiple node resolver methods into a single class, the name of the resolver method must be specified.

**Comment by michaelstaib** [comment]
The attribute shall also work in that way on type extensions:

```csharp
[Node(IdField = nameof(SomeId)]
[ExtendObjectType(typeof(Foo))]
public class FooExtension
{
    [ID] public string SomeId { get; set; }
}
```

**Comment by benmccallum** [comment]
Big thumbs up from me; all looks sound. Was thinking about this just yesterday as I was needing/wanting this to avoid an unnecessary `ObjectType` wrapper.

**Comment by michaelstaib** [comment]
Code-First variant:

```csharp
descriptor
    .ImplementNode()
    .WithId(t => t.Id)
    .ResolveWith<AttendeeResolver>(t => t.LoadNodeAsync(default));
```

**Comment by michaelstaib** [comment]
This one is now implemented. We need a couple more tests and this can go into 151
