### ISSUE TITLE
Examples in Docs are deprecated

### ISSUE THREAD

**Issue by noleu** [ChilliCream/hotchocolate#2404]
Hello Everyone,
I hope I am using the right kind of Issue right now.
I noticed some outdated and unclear parts in the docs. While trying to apply your examples on our project, visual studio stated that IEventMessage is deprecated and one should rather use IEventStream<TMessage>. My Problem is that I don't really see a way to use IEventStream instead of the IEventMessage.
The parts that are unclear to me, is why to use an Input on a subscription Method, maybe you could put a explaining sentence in the docs. 
One Last request would be a reference to the blog/2020-03-24 example, where a subscription without any input is used. For me it would be enough to have a sentence like: "An example without any Input in the subscriptions can be found in the blog/2020-03-24 code or in the corresponding Blog Post". 

The version that is used by us, is:
.net core 3.1 & hot chocolate 10.5.2

Thanks for the nice framework, it is nice to use as beginner in GraphQL.

Best Regards 
Niels

**Comment by michaelstaib** [comment]
We are at the moment rehabbing the documentation and will publish a new one with version 11.

The best way at the moment to learn about subscriptions is with our workshop:
https://github.com/ChilliCream/graphql-workshop
