### ISSUE TITLE
Return 400 http status if errors

### ISSUE THREAD

**Issue by fenomeno83** [ChilliCream/hotchocolate#2411]
Hi.
I'd like that when we have errors, the returned status code is 400, and not always 200.
How can I solve?
Thanks

**Comment by fenomeno83** [comment]
In this moment I have solved by a custom management using response body
    
    public class ErrorDto
    {
        public ExtensionsError Extensions { get; set; }
    }

    public class ErrorsDto
    {
        public List<ErrorDto> Errors { get; set; }
    }

    public class ExtensionsError
    {
        public string Code { get; set; }
        public string StackTrace { get; set; }
    }

    public class ResponseMiddleware
    {
        private readonly RequestDelegate next;

        public ResponseMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task Invoke(HttpContext context)
        {

            Stream originalBody = context.Response.Body;

            try
            {
                using (var memStream = new MemoryStream())
                {
                    context.Response.Body = memStream;

                    await next(context);

                    memStream.Position = 0;
                    string responseBody = new StreamReader(memStream).ReadToEnd();

                    if (!string.IsNullOrWhiteSpace(responseBody))
                    {
                        ErrorsDto errors = JsonConvert.DeserializeObject<ErrorsDto>(responseBody);

                        if (errors?.Errors != null && errors.Errors.Count > 0)
                        {
                            if (errors.Errors.FirstOrDefault(x => !string.IsNullOrWhiteSpace(x?.Extensions?.StackTrace)) != null)
                                context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                            else if (errors.Errors.FirstOrDefault(x => x?.Extensions?.Code == "AUTH_NOT_AUTHORIZED") != null)
                                context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                            else
                                context.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                        }
                    }

                    memStream.Position = 0;
                    await memStream.CopyToAsync(originalBody);
                }

            }
            finally
            {
                context.Response.Body = originalBody;
            }

        }
    }

    // Extension method used to add the middleware to the HTTP request pipeline.
    public static class ResponseMiddlewareExtensions
    {
        public static IApplicationBuilder UseResponseMiddleware(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<ResponseMiddleware>();
        }
    }

And in starttup configure method

                app.UseResponseMiddleware();

But is there another integrated method to change default 200 status code?

**Comment by michaelstaib** [comment]
With version 11 we are now following the GraphQL Http Spec Draft:
https://github.com/graphql/graphql-over-http

The spec now lines out when which error code has to be sent.

**Comment by michaelstaib** [comment]
The new HTTP middleware is already implemented... so if you use our new middleware in 11 you will get the spec behavior.
