### ISSUE TITLE
MaxExecutionDepth should allow the level of depth it is set to

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#2414]
In Hot Chocolate's docs, on the [execution options](https://chillicream.com/docs/hotchocolate/v10/execution-engine/execution-options) page, the description for the `MaxExecutionDepth` option is as follows:
> The maximum allowed query depth of a query.

Reading this, you would intuitively assume that if you set this to 5, for example, that means any query that is more than 5 levels deep (6 or higher) would be disallowed.

However, instead, it disallows 5 itself too, which is not in accordance with the usual meaning of the word "maximum" and phrases like "maximum allowed is N", which is "allow N and lower, but not higher" or "at most this, but not higher" AND what you would intuitively understand from the description in the docs itself.
"Maximum allowed value" means "this is the highest value _that is allowed_, any number higher than this is disallowed".

See [dictionary.com/browse/maximum](https://www.dictionary.com/browse/maximum)
> The greatest quantity or amount possible, assignable, allowable, etc.

This works the way I explained in other libraries and frameworks too, for example, in [graphql-depth-limit](https://github.com/stems/graphql-depth-limit#usage), setting the depth limit to 10 (`depthLimit(10)`) would mean that any query with a depth of 11 or more would be disallowed. As the documentation itself explicitly mentions:
> ...This will throw a validation error for queries (or mutations) with a **depth of 11 or more**.

Another example would be AutoMapper where it has a `MaxDepth` for mapping, and it works the same way.

PS: There is also a `MaxOperationComplexity` option in Hot Chocolate, which I haven't worked with but I suppose it currently works the same way as `MaxExecutionDepth`, which if you decide to fix, should be fixed too.

**Comment by michaelstaib** [comment]
Hi @AradAral,

you are absolutely right :) we will fix it with version 11.

**Comment by AradAral** [comment]
@michaelstaib Thanks you so much! ;)

**Comment by PascalSenn** [comment]
Just validated that the current behaviour in 11 is correct. I will close this issue
