### ISSUE TITLE
List of ID's not mapped correctly with fluentapi

### ISSUE THREAD

**Issue by csteeg** [ChilliCream/hotchocolate#2422]
**Describe the bug**
When using the fluent api to add an argument that should hold a list of id's, the original type is not remembered because of the rewrite happening in RelayIdFieldExtensions.RewriteInputFieldType

The AddSerializerToInputField does check for parametertype in 
`Type resultType = definition.Parameter?.ParameterType ?? ((ClrTypeReference)definition.Type).Type;`
But parameter is not set when using fluent api. If I set a dummy parameterinfo myself, it works as expected

**To Reproduce**
Add a parameter using fluentapi:
```
mytype.Field("getStuffById")
                    .Type<ListType<Stuff>>()
                    .Argument("ids", d => {
                        d.Type(typeof(int[])).ID("Stuff");
                    })
                    .ResolveWith<StuffResolver<T>>(resolver=> resolver.GetByIdsAsync(default!, default!, default));
```
**Expected behavior**
To be able to call getStuffById with a list of ID's -> when I do this an exception is thrown that int cannot be added to a list of strings, this is because FieldValueSerializer is initialized with IdType instead of int[]

**Additional context**
Workaround:
```
public class DummyParameterInfo: ParameterInfo
    {
        private Type type;

        public DummyParameterInfo(Type type)
        {
            this.type = type;
        }

        public override Type ParameterType => type;
    }

....
mytype.Field("getStuffById")
                    .Type<ListType<Stuff>>()
                    .Argument("ids", d => {
                        d.Extend().OnBeforeCreate(def => def.Parameter = new DummyParameterInfo(typeof(int[])));
                        d.Type(typeof(int[])).ID("Stuff");
                    })
                    .ResolveWith<StuffResolver<T>>(resolver=> resolver.GetByIdsAsync(default!, default!, default));
```

**Comment by michaelstaib** [comment]
why do you specify the type as `d.Type(typeof(int[]))`

better would be here to leave that out or specify the schema type.

**Comment by michaelstaib** [comment]
Which version are you using?

**Comment by csteeg** [comment]
> why do you specify the type as `d.Type(typeof(int[]))`
> 
> better would be here to leave that out or specify the schema type.

Leaving it out crashes in RelayIdFieldExtensions.RewriteInputFieldType because it has nothing to rewrite there, it can't detect the type from anything since with fluent you always have to specify it (or so I thought?)

I also tried d.Type<ListType<IntType>>().ID("Stuff") instead of the clrtype, but it has the same issue. 
I'm using v10.5.3, but if I look at the current develop branch,
https://github.com/ChilliCream/hotchocolate/blob/develop/src/HotChocolate/Core/src/Types/Types/Relay/Extensions/RelayIdFieldExtensions.cs still redirects the definition.Type  to idType, loosing the given type with d.Type()
So `else if (definition.Type is ExtendedTypeReference typeReference)` at https://github.com/ChilliCream/hotchocolate/blob/8299a944864a07bc0881ef06ce68818d801533d2/src/HotChocolate/Core/src/Types/Types/Relay/Extensions/RelayIdFieldExtensions.cs#L173 will always get IdType for definition.Type
