### ISSUE TITLE
Introspection fields should not be affected by MaxExecutionDepth

### ISSUE THREAD

**Issue by AradAlvand** [ChilliCream/hotchocolate#2423]
Currently in Hot Chocolate, by setting the `MaxExecutionDepth` option, introspection fields are affected by the specified depth limit as well, which shouldn't really be the case, at least by default.

The [graphql-depth-limit](https://github.com/stems/graphql-depth-limit#usage) library, for example, ignores introspection fields by default. On its `README.md` it says:
> ...The second argument is an options object, where you can do things like specify ignored fields. **Introspection fields are ignored by default.**

Even if this doesn't happen by default, there should at least be a configuration option to allow the developer to decide on it. (e.g. `IgnoreMaxDepthForIntrospectionFields = true`)

**Comment by AradAral** [comment]
For example, if you set MaxExecutionDepth to 5, and then send the following introspection query:
```
{
  __schema {
    types {
      name
      fields {
        name
        type {
          name
          kind
          ofType {
            name
            kind
          }
        }
      }
    }
  }
}
```
You would get an error saying you have exceeded the maximum depth of a query.

**Comment by michaelstaib** [comment]
The problem here is that you could still kill the server with that. Since you could build large introspection queries that consume large amounts of memory.

But we could still add an option that the user can decide on this.

**Comment by AradAral** [comment]
@michaelstaib You're right.
So I think it would be reasonable to at least have an option like `IntrospectionMaxExecutionDepth` which would allow the user to decide separately on the depth of the introspection fields. But I would say having the same max depth for both normal fields and introspection fields is a bit too inflexible, and in many cases undesirable, and I think you'd agree.
Thank you, again, for all the valuable work.
