### ISSUE TITLE
Unable to disable unauthorized use of introspection query

### ISSUE THREAD

**Issue by BlacKCaT27** [ChilliCream/hotchocolate#2436]
Hello,
Perhaps someone can help me out. Try as I might, I'm not able to find any information on how to either

a) disable the introspection query

or

b) require a caller to be authorized to reach the query

Our policies are requiring that we lock down or disable the introspection query and as far as I can tell HotChocolate doesn't appear to have a mechanism to do so. Can someone please offer any insight?

**Comment by michaelstaib** [comment]
There are actually multiple ways to do that. You could write a validation rule, an authorization policy, a field middleware, or a directive that either prohibits it always or allow it only for certain users.

Moreover, there are better ways to lock your service down ... join our slack channel.
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by BlacKCaT27** [comment]
Closing this out but for anyone who finds it later, I ended up using a modified version of this:

https://gist.github.com/benmccallum/9329bcc70711f1bc14e74dc82693c607
