### ISSUE TITLE
Relay ID doesn't contain the ID if the ID property is declared on a parent class

### ISSUE THREAD

**Issue by vbornand** [ChilliCream/hotchocolate#2438]
**Describe the bug**
The ID is not included the relay id if the ID property is defined in a parent class in HC11.0.0-preview.154 

**To Reproduce**
```csharp
public class Query
{
    public Child Child { get; set; } = new Child { Id = 999 };
}

public class Parent
{
    public int Id { get; set; }
}

public class Child: Parent
{
    public string Foo { get; set; }
}

public class ChildResolver
{
    public Child GetChildAsync(int id) => new Child { Id = id };
}

public async Task IDMissing()
{
    ISchema schema = SchemaBuilder.New()
        .EnableRelaySupport()
        .AddQueryType<Query>()
        .AddObjectType<Child>(d => d
            .ImplementsNode()
            .IdField(t => t.Id)
            .ResolveNodeWith<ChildResolver>(t => t.GetChildAsync(default)))
        .Create();

    IRequestExecutor executor = schema.MakeExecutable();

    IExecutionResult result = await executor.ExecuteAsync(
        "{ child { id } }");

    var json = result.ToJson();
}
```
The result is:
```json
{
  "data": {
    "child": {
      "id": "Q2hpbGQKaTA="
    }
  }
}
```

BASE64_Decode("Q2hpbGQKaTA=") => 
Child
i0

**Expected behavior**
The decoded id should be:
Child
i999

**Fix proposal**
Replacing this line:
https://github.com/ChilliCream/hotchocolate/blob/6a78a9b2bdaf2ac97c6f693bc74f072edd905157/src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectTypeDescriptor.cs#L281

with 
`propertyOrMethod.ReflectedType ?? Definition.RuntimeType);`

or with 
`Definition.RuntimeType);`

The 2 alternatives changes fix this issue and don't break any existing tests but I don't know enough about HC to know the impacts.

**Comment by michaelstaib** [comment]
this one is fixed.
