### ISSUE TITLE
Customisable syntax for offset based pagination 

### ISSUE THREAD

**Issue by PaulGarnerUk** [ChilliCream/hotchocolate#2465]
HotChocolate 11+ has added 'Offset based pagination', which works wonderfully with queries like

```
{
   products (skip:30 take:15)
   {
      items
      {
         ...
      }
   }
}

```

However the syntax - `skip`, `take` in the query and `items` in the result - is still not standardised.  Some clients (Vue Apollo for example) expect the syntax to be `offset` and `limit` instead of `skip` and `take`.

It would be nice if these syntax keywords could be customised until standards are established.

**Comment by PascalSenn** [comment]
Note: 
- We need to make sure projections is aware of renames. At the moment "items" is hardcoded as we do not yet have a convention

@michaelstaib

**Comment by taipignas** [comment]
was this implemented?
