### ISSUE TITLE
Reporting exception using ITopicEventSender

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/hotchocolate#2469]
Hi, perhaps it's already here but I didnt find anything on docu nor usable methods.

How do I raise websocket error event using ITopicEventSender?

If its no possible it would be great to add this feature in order to be able to signal errors

**Comment by michaelstaib** [comment]
You can only raise GraphQL errors. The transport is abstracted. Moreover, the subscription protocol has specified responses. 

If you want to raise an error create a GraphQL error in the root subscription resolver.

**Comment by Deathrage** [comment]
Do you have an example how to properly signal the Exception via ITopicEventSender and then catch it in the IAsyncEnumerator around ITopicEventReciever (or do I send the IError right through ITopicEventSender?) and transform it to IError? 

I was succesful to send it through when I used object as type of message `.SendMessage<string, object>("key", /* real payload or exception */)` but I do not feel like this is proper way to do it as I have to make both `SendMessage` and `Subscribe` use object instead of the proper type.

**Comment by michaelstaib** [comment]
So essentially the topic event sender is just a pub-sub abstraction... you can send anything you want over it. On the root resolver for subscription, you can then interpret it and create an error.

**Comment by Deathrage** [comment]
Yes but if I `.SendAsync<string, Exception>("key", ex)` and watch using `.Subscribe<string, Foo>("key)` I do not recieve the message, that forces me to use `object` (in `.SendAsync("key", (object)ex`)` and `.Subscribe<string, object>`) instead of the proper type. It also means that the resolve has to return `IAsyncEnumerable<object>` whereas when I use queries and mutations I can `throw Exception` properly and then work with it in `ErrorFilter` thus I can have strongly typed resolver.

Or am I missing something?

**Comment by michaelstaib** [comment]
Really is a design issue. First I would not send down the exception object. Also, you could have a proper message object that can have an error. Like the GraphQL result, itself transports errors and data.
