### ISSUE TITLE
Add error manually

### ISSUE THREAD

**Issue by fenomeno83** [ChilliCream/hotchocolate#2470]
Hi.
My graqhpl pure code first methods call some rest api methods using httpclient.
In response I can have an error object with error code and message.
So I'd like map this error in graphql error filter adding manually
How can I do?

Can I add error on diagnostic observer stop method?

        [DiagnosticName("HotChocolate.Execution.Query.Stop")]
        public void EndQueryExecute(IQueryContext context)

???

thanks

**Comment by PascalSenn** [comment]
Something like this could work
```csharp
    var error = ErrorBuilder
        .New()
        .SetMessage("Entity not found")
        .SetPath(
            Path.New("cfp")
                .Append(nameof(UpdateCfpInput.Id))
        )
        .Build();
    throw new QueryException(error);
````

**Comment by michaelstaib** [comment]
For 11 we have introduced `GraphQLException`... QueryException will be marked obsolete in version 12 and removed in 13.

**Comment by michaelstaib** [comment]
Btw, `IErrorFilter` is what you are looking for...

https://chillicream.com/docs/hotchocolate/v10/execution-engine/error-filter/
