### ISSUE TITLE
HotChocolate.Templates.StarWars has a typo in a folder name

### ISSUE THREAD

**Issue by StefH** [ChilliCream/hotchocolate#2482]
**Describe the bug**
HotChocolate.Templates.StarWars has a typo in a folder

**To Reproduce**
```
dotnet new -i HotChocolate.Templates.StarWars
dotnet new starwars
```

Folder with name `Charachters` is created, this should be `Characters`

**Comment by michaelstaib** [comment]
Thanks for reporting, do you want to do a pr?

**Comment by StefH** [comment]
Hello @michaelstaib,

I think this is already corrected in https://github.com/ChilliCream/hotchocolate/tree/develop/templates/StarWars/content/StarWars/Characters

Maybe release/publish a new version?

**Comment by michaelstaib** [comment]
It is released as a preview. We are working towards the next release. I am closing this issue.
