### ISSUE TITLE
UseSelection, illegal Type

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/hotchocolate#2484]
**Describe the bug**
If IQueryable contains a class that is used in InterfaceType (as it is a base for two child classes) it's reported as illegal even though EF returns proper type.

**To Reproduce**
1. Create a base class Foo
2. Create it's child FooBar
3. Create it's child FooBaz
4. Configure Foo in EF to use discriminator for FooBar and FooBaz
5. Create an InerfaceType around Foo
6. Create one ObjectType for FooBar and another one for FooBaz, make them implement FooType
7. Create resolver that returns IQueryable<Foo> and uses UseSelection
8. Try a query

`
```
// classes
class Foo {}
class FooBar: Foo {}
class FooBaz: Foo {}
// DBContext
ITypeConfigurationBuilder<Foo>

builder.HasDiscriminator() /* omitted /*

// GQL Types
class FooType: InterfaceType<Foo> {}
class FooBarType: ObjectType<FooBar>{
    Configure(d) {
          d.Implements<FooType>();
    }
}
class FooBazType: ObjectType<FooBaz>{
    Configure(d) {
          d.Implements<FooType>();
    }
}
class QueryType {
    Configure(d) {
          d.Field<Resolvers>(r => r.GetFoos(default)).UseSelection().Type<ListType<FooType>>();
     }
}
// Resolvers
class Resolvers {
    
public IQueryable<Foo> GetFoos([Service]DbContext dbContext) 
            => dbContext.Foos;
}
```

**Expected behavior**
HotChocolate is properly able to resolve the underlying types in IQueryable<Foo> and asserts their proper ObjectTypes. 

**Additional**
I am not sure whether it's achievable in other way and that this is acutally bad behaviour. It seems to me to be as I do not know other way how to implement something similar to discriminators in HC.

**Comment by PascalSenn** [comment]
@Deathrage  yes this is currenlty still a limitation. We did not yet had the time to implement polymorphism into projections. 
We compile expression trees internally. So a query like

```graphql
# This query is written in V11 syntax
{
     foos(where: { bar: {eq:400}}, order: [{bar: DESC}, {baz: ASC}]) {
        bar
        baz
    } 
}
```
is compiled to 
```csharp
foos.Where(x => x.Bar == 400) // UseFiltering
    .OrderByDescending(x => x.Bar) // UseSorting
    .ThenBy(x => x.Baz)  
    .Select(x => new Foo {Bar = x.Bar, Baz =x.Baz}) // UseSelection
``` 

As you see we currently create an instance of the requested object. EF traverses this expression tree and then executes the SQL Query and creates the response object. The projection onto the object has a few drawbacks we are aware off. 

There are a couple of cases to consider:
- Unions => we need to project completely different types. 
- Interfaces => we may need to project onto an abstract type
- Properties without setter => we cannot set these properties in a `new` expression
- Field Aliases => especially on nested collections this can lead to issues 
- Commputed fields => it is currently not supported to project computed fields like 
    `Field(x => x.Name + " " + x.Surname).Name("fullName")`

These are things we want to support, but it is not yet on the board. We are currently working on the next release and just migrated projections over from V10. We want to be feature complete before we invest into big new features like the things mentioned above
