### ISSUE TITLE
"Object reference not set to an instance of an object." when using AutoMapper ProjectTo IQueryable<T>

### ISSUE THREAD

**Issue by StefH** [ChilliCream/hotchocolate#2485]
**Describe the bug**
I'm not sure it's a bug, or just invalid setup.

**To Reproduce**
This code works when I do a `ToList` and return `IEnumerable<T>`:
``` c#
[UseFirstOrDefault]
[UseSelection]
public IEnumerable<StudentModel> GetStudentById(int studentId)
{
    return _mapper.ProjectTo<StudentModel>(_schoolContext.Students.Where(t => t.Id == studentId)).ToList();
}
```

However when using this code:
``` c#
[UseFirstOrDefault]
[UseSelection]
public IQueryable<StudentModel> GetStudentByIdError(int studentId)
{
    return _mapper.ProjectTo<StudentModel>(_schoolContext.Students.Where(t => t.Id == studentId));
}
```

It fails with exception:

> "Object reference not set to an instance of an object."
> "   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.AddCollectionProjection(ShapedQueryExpression subquery, INavigation navigation, Type elementType)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)\r\n   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)\r\n   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)\r\n   at HotChocolate.Types.Selections.FirstOrDefaultMiddleware`1.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler)"

**Desktop (please complete the following information):**
 - OS: Windows with .NET Core App 3.1
 - Version 10.5.3

**Additional context**
Maybe related to https://github.com/ChilliCream/hotchocolate/issues/2002 ?

Example project:
https://github.com/StefH/HotChocolateExample/tree/main/ContosoUni

**Comment by PascalSenn** [comment]
Can you try once #4563 is merged if it works with the new extension method?
1. This will only work when you use HotChocolate.Data
2. `dotnet add package HotChocolate.Data.AutoMapper`
3.  Rewrite the mapping to:
```csharp
        [UseProjection]
        public IQueryable<PostDto> GetPosts(BloggingContext dbContext, IResolverContext context)
            => dbContext.Posts.ProjectTo<Post, PostDto>(context);
```
