### ISSUE TITLE
[Idea] Add default query, mutation and subscription types

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#2487]
**Is your feature request related to a problem? Please describe.**
HC providing types dependency inversion using extensions.
For now to use extensions ` .AddMutationType(x => x.Name("Mutation"))` and `descriptor.Name("Mutation")` or creating my own classes and types

**Describe the solution you'd like**
1. Add new library, like EFCore integration, but with default root types. So we will have strongly typed conventions instead string based

```cs
public class Query
{
}
public class QueryType : ObjectType<Query>
{
}
// ...
```

2. Add `ObjectTypeExtension<TExtendedType, TTypeExtension> : ObjectTypeExtension<TTypeExtension>` so `ObjectTypeExtension<Mutation, UserMutations>` can be used. This type will name extension using `TExtendedType` but have a `TTypeExtension` contract

3. Usage
```cs
// ...
.AddQueryType<QueryType>()
.AddMutationType<MutationType>()
// .AddSubscriptionType<SubscriptionType>()
.AddTypeExtension<HotChocolateQueryExtension>() // class HotChocolateQueryExtension : ObjectTypeExtension<Query, HotChocolateQueries>
.AddTypeExtension<HotChocolateMutationExtension>() // class HotChocolateMutationExtension : ObjectTypeExtension<Mutation, HotChocolateMutations>
```

**Describe alternatives you've considered**
For now i am doing this by my own, but this strongly typed approach can be a part of HotChocolate

**Comment by michaelstaib** [comment]
The issue with this is that you closely couple your queries which removes one of the biggest features...

@benmccallum provided a different proposal on this which we are going to implement. It is more in the direction that type extension can bind using a delegate. If the delegate matches certain criteria then the extension will bind... this, in turn, allows an extension to bind to multiple types.

**Comment by sergeyshaykhullin** [comment]
@michaelstaib But with descriptor.Name("Query") you closely couple too, right?

**Comment by michaelstaib** [comment]
Not really, it's a string ... there has to be no type relation. 

But the idea to make this nicer is to have a delegate that can couple depending on properties of types. This means that you can define a predicate that analyzes whatever and add something to all the types that match.
