### ISSUE TITLE
Add compatibility API: AddQueryRequestInterceptor

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#2501]

**Comment by michaelstaib** [comment]
We should just document this one

**Comment by sandorfr** [comment]
All I could find in the docs is // TODO : services.AddQueryRequestInterceptor((context, builder, ct)

**Comment by michaelstaib** [comment]
https://chillicream.com/docs/hotchocolate/api-reference/aspnetcore/#graphql-request-customization

**Comment by michaelstaib** [comment]
We are still working on the documentation.... will probably take 2 more weeks.
