### ISSUE TITLE
Unauthorized on root type HTTP Status Code

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#2513]
With the new HTTP Spec implementation we return a 500 error when data is null.

Should we return a 403 when the errorcode is `AUTH_NOT_AUTHENTICATED` ?

```
{
  "name": "ServerError",
  "statusCode": 500,
  "statusText": "Internal Server Error",
  "bodyText": "{\"errors\":[{\"message\":\"The current user is not authorized to access this resource.\",\"locations\":[{\"line\":10,\"column\":3}],\"path\":[\"foo\"],\"extensions\":{\"code\":\"AUTH_NOT_AUTHENTICATED\"}}]}"
}
````

**Comment by michaelmccord** [comment]
I think I just ran into this and it took me quite awhile to track down where there issue was. As it stands this is at the very least a confusing way to handle this and not at all indicative of what's actually going on. As a user I would prefer this was simply handled with a 200 and a graphql error response like any other error unless that goes against the graphql HTTP spec.

**Comment by michaelmccord** [comment]
@michaelstaib -- is this a bug ....or?

**Comment by Alxandr** [comment]
This is reasonably easy to fix:

```csharp
    internal class AuthorizationAwareHttpResultSerializer : DefaultHttpResultSerializer
    {
        /// <inheritdoc/>
        public override HttpStatusCode GetStatusCode(IExecutionResult result)
        {
            return result switch
            {
                QueryResult queryResult => GetStatusCode(queryResult),
                DeferredQueryResult => HttpStatusCode.OK,
                BatchQueryResult => HttpStatusCode.OK,
                _ => HttpStatusCode.InternalServerError,
            };
        }

        private HttpStatusCode GetStatusCode(IQueryResult result)
        {
            if (result.Data is not null)
            {
                return HttpStatusCode.OK;
            }

            if (result.ContextData is not null)
            {
                if (result.ContextData.ContainsKey(WellKnownContextData.ValidationErrors))
                {
                    return HttpStatusCode.BadRequest;
                }

                if (result.ContextData.ContainsKey(WellKnownContextData.OperationNotAllowed))
                {
                    return HttpStatusCode.MethodNotAllowed;
                }
            }

            // handle authorize errors
            if (result.Errors is { Count: 1 } &&
                result.Errors[0] is { Code: ErrorCodes.Authentication.NotAuthorized })
            {
                return HttpStatusCode.Forbidden;
            }

            if (result.Errors is { Count: 1 } &&
                result.Errors[0] is { Code: ErrorCodes.Authentication.NotAuthenticated })
            {
                return HttpStatusCode.Unauthorized;
            }

            // if a persisted query is not found when using the active persisted query pipeline
            // is used we will return a success status code.
            if (result.Errors is { Count: 1 } &&
                result.Errors[0] is { Code: ErrorCodes.Execution.PersistedQueryNotFound })
            {
                return HttpStatusCode.OK;
            }

            return HttpStatusCode.InternalServerError;
        }
    }
```

The `GetStatusCode` here is copied directly from `DefaultHttpResultSerializer`. I have 2 suggestions here (and can provide a PR with them if wanted).

1. Add the 2 new `if` statements to the `DefaultHttpResultSerializer`.
2. Make the `GetStatusCode(IQueryResult)` protected virtual, so that it's not required to override the outer `GetStatusCode(IExecutionResult)` which deals with things I don't (in this case) care about.

**Comment by ignj** [comment]
hey @michaelstaib, do you think that we could get this one for V12?

**Comment by michaelstaib** [comment]
This is not spec behavior. That is why we have not picked it up.

Here is the GraphQL over HTTP draft:
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes

But you are free to override the spec behavior as you see fit.

**Comment by Alxandr** [comment]
> In case of errors that completely prevent the successful execution of the request, the server SHOULD respond with the appropriate status code depending on the concrete error condition.

This is from that spec - so if `data` is `null` (or not present), "appropriate status code" should be returned. Though, not for partial responses.

**Comment by michaelstaib** [comment]
The main issue I see here is that the spec is quite firm on the `2xx`

`If the response has Content-Type GraphQL and contains a non-null data entry, then it MUST have status code 2xx, and it SHOULD have status code 200 (Okay).`

This is a `MUST` so if we do not want to violate we should follow this.

So we could have authentication errors when `data` is `null`. But what if you have auth issues and you do have partial results ... isn't that a bit inconsistent?

The question might also go into a more general question on how we do authorization.

What are the thoughts on this one?

**Comment by michaelstaib** [comment]
I have put the issue on the backlog for discussion btw ... so while I am pushing back on some things here its to engage in a discussion not to kill this issue.

**Comment by Alxandr** [comment]
The code I posted explicitly returns 200 if `result.Data is not null` - which as far as I can see is spec compliant. But our entire graph required authorization, so you will never get partial responses with unauthorized.

**Comment by ignj** [comment]
In my humble interpretation of the spec, if I perform a query and
- All authorization conditions succeed:
  - I get a `2xx` response with non null `data` in HC
  - Satisfies `If the response has Content-Type GraphQL and contains a non-null data entry, then it MUST have status code 2xx, and it SHOULD have status code 200 (Okay).` from the spec
- Some authorization conditions succeed, some others not:
  - I get a `2xx` response with non null `data` having the partial results plus the `errors` in HC
  - Satisfies `If the response has Content-Type GraphQL and contains a non-null data entry, then it MUST have status code 2xx, and it SHOULD have status code 200 (Okay).` from the spec
- I can't access the schema at all
  - I get a `4xx` response with null data in HC
  - Satisfies `In case the client can not access the schema at all, the server SHOULD respond with the appropriate 4xx status code.` from the spec
- I can access the schema, but the authorization conditions fail for the entire query
  - I get a `5xx` response with null `data` and `errors` in HC
  - May be arguable if the statement `In case of errors that completely prevent the successful execution of the request, the server SHOULD respond with the appropriate status code depending on the concrete error condition.` from the spec is satisfied

**Comment by Alxandr** [comment]
My only gripe is on the last point. In the case of "authorization conditions fail for the entire query" I would say that "appropriate status code" is Unauthorized - not 500. I generally only want 500 for unexpected errors (I have a bug in my server code).

**Comment by smfeest** [comment]
For what it's worth I've noticed that the Authorization documentation for v12 [explicitly states](https://github.com/ChilliCream/hotchocolate/blob/d6cdeeeb82a4650c4cc17ce68c61f76ed3e423ab/website/src/docs/hotchocolate/security/authorization.md?plain=1#L120) that unauthorized requests get an HTTP 200 response which, combined with the other points above, suggests that the HTTP 500 response we currently get is not intended or expected.

**Comment by smfeest** [comment]
I've also just realized that the status code is only 500 if the affected field is not nullable.

+ If the affected field is nullable, then the data entry is present, includes the affected field with a null value and the HTTP response code is 200
+ If the affected field is not nullable, then the data entry is omitted and the HTTP response code is 500

**Comment by michaelstaib** [comment]
Version 12 will return 200 for success or partial success of a request and 500 if data is null or does not exist.

**Comment by ignj** [comment]
hey @michaelstaib is this still being considered for V13?
