### ISSUE TITLE
Client (StrawberryShake) is unable to serialize query to json if there are array parameters

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2518]
**Describe the bug**
The issue is reproduced in test JsonOperationFormatterTests.Serialize_To_Json_With_Array_Variable (look into the associated pool request).

Any operation with array variable(s) is unable to be serialized into JSON before sending to graphql server. For instance the operation (I skipped Document definition since it's not important here, it can be literally any):

`private class OperationWithArrayVariable
            : IOperation
        {
            public string Name => "abc";

            public IDocument Document { get; } = new Document();

            public OperationKind Kind { get; } = OperationKind.Subscription;

            public Type ResultType => typeof(OnReview);

            public IReadOnlyList<VariableValue> GetVariableValues() =>
                new[] { new VariableValue("Foo", "[String!]!", new[] { "123", "456" }) };
        }`
gives an error:
`System.InvalidOperationException
'}' is invalid following a property name.`

while trying to serialize it with JsonOperationFormatter.

**Expected behaviour**
The given operation is supposed to be successfully serialized into something like the following (depending on Document):
`{"id":"Hash","query":"subscription abc { onReview(episode: NEWHOPE) { stars } }","operationName":"abc","variables":{"Foo":["123","456"]}}
`

**Additional context**
Using array variables is so basic functionality that, in my opinion, that issue (along with issue #2046 ) makes StrawberryShake almost impossible to use in real projects.

**Comment by michaelstaib** [comment]
@ademchenko thanks for doing all the work regarding strawberry shake. Work on 11 server is winding down and we will start working on strawberry shake today... I will go through with @fredericbirke and start sorting out the way forward. We will look at merging your fixes next week once we got the core compiling again.

**Comment by ademchenko** [comment]
@michaelstaib , will there be a movement on that issue?

**Comment by michaelstaib** [comment]
Yes, we have started work on Strawberryshake. You can join in if you like to.
