### ISSUE TITLE
OnBeforeCompleteType does not generate schema

### ISSUE THREAD

**Issue by guillaumebailleul** [ChilliCream/hotchocolate#2542]
Hello, 

I need to generate a multisite CMS, I try to generate a schema at runtime with the new API **11.0.0-preview.180**.

```
           services
                .AddGraphQLServer()
                .AddQueryType(d =>
                {
                    d
                        .Name("Query")
                        .Field("hello")
                        .Resolver("world");
                })
                .OnBeforeCompleteType<ObjectTypeDefinition>(
                    (context, def, contextData) =>
                    {
                        if(def is { } && def.Name.Equals("Query"))
                        {
                            ObjectTypeDescriptor.From(context.DescriptorContext, def)
                                .Field("foo")
                                .Type<StringType>()
                                .Resolver(resolverContext => "say hello");
                        }
                    });
```

At runtime the code inside ```if(def is { } && def.Name.Equals("Query"))``` but the schema is not generated.

**Expected behavior**

```
query { foo } 
```

would return this response

```
{
    "data": {
        "foo": "say hello"
    }
}
```

but got

```
{
    "errors": [
        {
            "message": "The field `foo` does not exist on the type `Query`.",
            "locations": [
                {
                    "line": 1,
                    "column": 9
                }
            ],
            "extensions": {
                "type": "Query",
                "field": "foo",
                "responseName": "foo",
                "specifiedBy": "http://spec.graphql.org/June2018/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"
            }
        }
    ]
}
```

**Desktop**
 - OS: [macOS bigSur]
 - Version [11.0.1]

best regards

**Comment by laibulle** [comment]
Hi @michaelstaib. I am trying to run the star wars project to have better understanding of the internals of hotcholocate. But the project doesn't run. What branch and what project am I supposed to launch ?

I run dotnet 5.0-100 on macOS and windows.

Best regards

**Comment by michaelstaib** [comment]
so .... when you clone main run the following command first:

```bash
./build.sh compile
```

This will create the build solution, restore packages and compile everything.


I am my self also on macos and use personally vscode. 

If you use vscode head over to ... src/HotChocolate/AspNetCore and open this folder.

It should run and let you debug the sample.

If you use rider open src/All.sln

**Comment by PascalSenn** [comment]
Hi @laibulle  

I think you register the changes to late. 
`OnBeforeCompleteType` is very close to the initialization cycle. 
Try to register it `OnBeforeRegisterDependencies` then everything should work

**Comment by laibulle** [comment]
Hi @PascalSenn 

I tried this 
```
 services
                .AddGraphQLServer()
                .AddQueryType<Query>()
                .AddMutationType<Mutation>()
                .OnBeforeRegisterDependencies<ObjectTypeDefinition>(
                    (context, def, contextData) =>
                    {
                        if (def is { } && def.Name.Equals("Query"))
                        {
                            ObjectTypeDescriptor.From(context.DescriptorContext, def)
                                .Field("foo")
                                .Type<StringType>()
                                .Resolver(resolverContext => "say hello");
                        }
                    })
                .AddApolloTracing();
```

but it did not solved the issue

Best regards

**Comment by guillaumebailleul** [comment]
@PascalSenn @guillaumebailleul do you have more info to help me ? My goal is to create something similar to contentfull. https://www.contentful.com/blog/2018/12/21/dynamic-schema-generation-changing-data-models/ 

I am able to do it with Elixir and Go, I suppose F# type providers should do the job but my team only work with C#. So for now I am quite stucked. 

Best regard
