### ISSUE TITLE
Runtime schema modification

### ISSUE THREAD

**Issue by IKolosynskyi** [ChilliCream/hotchocolate#2544]
Hi all. I working on GraphQl Gateway. 

Microservices can be upgraded, the schema can be changed so my Gateway has to be able to refresh it`s stitched schema.
No matter how it will be implemented, either gateway will ask micro for a new schema, or micro will send new schema to the gateway, I am fine with both ways. 

The question is: can I manage schema in runtime? Is it possible with hotchoclate? Or I have to restart gateway each time when service got updated?

Thanks in advance.

**Comment by PascalSenn** [comment]
@IKolosynskyi  Yes this is possible with V11. 
Are you on slack? There is a cool videos that shows this feature off

**Comment by IKolosynskyi** [comment]
Oow, this sounds great! No, I`m not there, could you please share the link or invite me? Thanks a lot!

**Comment by PascalSenn** [comment]
You can join here:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q
Ping me and i will send you the link

**Comment by IKolosynskyi** [comment]
Thanks. Found it. I will play around with the new version, thanks again. Are you strictly suggest using Redis or I can substitute it with my own DB provider?
