### ISSUE TITLE
HotChocolate.Types.Selection RC0 not available in nuget

### ISSUE THREAD

**Issue by tanekim77** [ChilliCream/hotchocolate#2550]
HotChocolate.Types.Selection v11.0.0-rc0 is not available in nuget.

Nuget only has v10.5.3 version,  and [UseSelection] attribute from the package in that version conflicts with other HotChocolate v11.0.0 RC0 packages.

In other words,
The [UseSelection] used in the following instruction no longer works.
https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

**Comment by michaelstaib** [comment]
We have migrated selections to Hotchocolate.Data
