### ISSUE TITLE
Issues with Identity Server

### ISSUE THREAD

**Issue by tanekim77** [ChilliCream/hotchocolate#2551]
I am following the instructions at 
https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

```
    public class Student: IdentityUserClaim<int>
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
```
However, if the student class inherits from the base class of IdentityUserClaim<int> from Microsoft.AspNetCore.Identity package, like above, then compilation throws a following error:
![image](https://user-images.githubusercontent.com/20119808/98392630-3bdb3580-2026-11eb-9bb9-6e3bcea6bc9f.png)

Is there a way to make it work with the inheritance from the class of Identity Server package?

**Comment by PascalSenn** [comment]
@tanekim77  The problem you are facing is that HotChocolate tries to create fields for the parent object 
What you can to do avoid this issue is to register a ObjectType<Student> 
you can then either Ignore the fields that you do not want to map or you can exclude all and specify waht you want to Include

```csharp
public class StudentType : ObjectType<Student> 
{
    protected override void Configure(IObjectTypeDescriptor<Student> desc) {
        desc.Ignore(x => x.FieldToExclude);
    }
}
// OR
public class StudentType : ObjectType<Student> 
{
    protected override void Configure(IObjectTypeDescriptor<Student> desc) {
        desc.BindFieldsExplicitly();
        desc.Field(x => x.FieldToInclude);
    }
}
```
You can then register this type on the schemabuilder `.Type<StudentType>()`

**Comment by tanekim77** [comment]
@PascalSenn 
Thanks for the update. I am getting same error in the following case as well. Is it possible to ignore field that is nested, like in the following case?
```
   public class Student
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }

        public virtual ICollection<StudentClaim> StudentClaims {get; set;}
    }

public class StudentClaim: IdentityUserClaim<int> {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
}
```

**Comment by PascalSenn** [comment]
@tanekim77  sure just create another object type for StudentClaim and register it on the schema :)

**Comment by tanekim77** [comment]
@PascalSenn 

I tried BindFieldsExplicitly() method, and it worked. But I want to use .Ignore() method, and it's not working. I tried to ignore all the base class(IdentityUserClaim)'s properties, but it still threw the same error messages. It seems like it's a bug.
