### ISSUE TITLE
Use StrawberryShake without code generation

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#2552]
Greetings all,

How can I use StrawberryShake client directly without using the code generation tools?

We already have our own code generation platform that we would like to leverage here.

Thank you.

**Comment by geekox86** [comment]
Hi. No answer?

**Comment by benmccallum** [comment]
The team is pretty busy trying to wrap up the v11 release.

TBH, I don't really see what you're trying to achieve. The StrawberryShake client AFAIK is heavily coupled to the code it generates. If you already have a code generation platform, wouldn't you just want to use `HttpClient` direct and just build a light wrapper that can call a gql server and deserialize the response into the types your other generator has created for you?

**Comment by michaelstaib** [comment]
Sorry for not answering but @benmccallum is exactly right on both points... We are really at the moment pushing 11 which we want to deliver on the 20th. We already have started with meetings on Strawberry Shake and are at the moment in a prototyping phase in a private repository.

But as to the point here, I do not see any value in a client that does not generate a model. If you want that, I really would just create a wrapper around the HTTP client. But you will lose handling of things like unions which a standard JSON serializer has now clue about.

**Comment by geekox86** [comment]
Thank you guys @benmccallum and @michaelstaib . I really really appreciate what you are doing and waiting for v11.
It make sense for StrawberryShake to generate code. The thing is we already have a platform that generates the models and other stuff for us. It just does not provide a GraphQL client and I would like to use the StrawberryShake's GraphQL client without having to use its code generation capabilities. I thought of peeking into the generated code and see how it is using its GraphQL client so that I can do so also from my code. But I am not sure what is the class responsible for this in StrawberryShake. Also, I think in the future StrawberryShake will introduce some client-side caching strategies which I would like to leverage later on.

So, which class is responsible for StrawberryShake's GraphQL client?

**Comment by michaelstaib** [comment]
@geekox86 I would wait before you build something around StrawberryShake we will start work on it soon and with this, a lot of changes will come... At the moment try it like it is but do not invest time to build on its lower-level parts, since we are swapping them out. In January, we think to have a stable version. I am closing this issue.

**Comment by michaelstaib** [comment]
@geekox86 make sure to join us on slack.

**Comment by benmccallum** [comment]
Check out this, which night better suit your needs, https://github.com/graphql-dotnet/graphql-client
