### ISSUE TITLE
Allow GraphQLNameAttribute on enum values.

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#256]
```csharp
public enum Foo 
{
    [GraphQLName("B")]
    A 
}
```

**Comment by OneCyrus** [comment]
also on the enum itself it's not possible right now

```
[GraphQLName("MyEnum")]
public enum Foo 
{
    A 
}
```

![image](https://user-images.githubusercontent.com/7747800/92903026-0a792b80-f422-11ea-8cab-a2d6848a2145.png)

**Comment by PascalSenn** [comment]
@OneCyrus  nice catch, thanks. 
As a workaround you can use DescriptorAttributes at the moment

**Comment by michaelstaib** [comment]
We can get that into the next previews... I put it on our board.
