### ISSUE TITLE
Inconsistent behavior for array nullability creates invalid schema when using collection resolvers

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/hotchocolate#2565]
**Describe the bug**
HotChocolate (appears) to treat `ICollection<T>` differently for models and for resolvers.

**To Reproduce**
Using EFCore5, create a `ParentModel` and `ChildModel` with a `N:M` (many-to-many) relationship:

```
class ParentModel {
  public ICollection<ChildModel> children { get; set; } = new List<ChildModel>();
}
```

(and vice versa).

Note that the schema is of type `[ChildModel!]!`. This is correct, in that neither the array nor the child models may be null, per the lack of nullability in the source code.

However, now try to add a resolver to the parent model. E.g.,

```
descriptor.Field(p => p.children).ResolveWith(r => new List<ChildModel>());
```

In this case, the generated schema is `[ChildModel]`. This subsequently causes downstream errors with clients which depend on correct schema, such as graphql-codegen, requiring a ton of nullability boilerplate to fix.

**Expected behavior**
Both code paths should respect nullability in the same fashion.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version: 11.0.0-rc.1

**Comment by zaneclaes** [comment]
I tried to fix this by adding `.Type<NonNullType<ListType<NonNullType<ChildModelObj>>>()`. It did fix the schema, but it created other problems — the resolver suddenly stopped working. Also note that the response from the server is not a valid GraphQL response:
<img width="1246" alt="Screen Shot 2020-11-11 at 6 40 59 AM" src="https://user-images.githubusercontent.com/2084821/98818587-00a38280-23e9-11eb-9ccb-4e32c465fe1b.png">

**Comment by gojanpaolo** [comment]
Note that we also need to explicitly handle `null` in the resolver function, at least when using `DataLoader`. A `Cannot return null for non-nullable field` error will be thrown if `null` is not handled explicitly,

e.g.
```c#
descriptor
    .Field(p => p.Children)
    .ResolveWith<MyResolver>(r => r.GetChildrenAsync(default!, default!, default))
    .Type<NonNullType<ListType<NonNullType<ChildModelObj>>>>();

// MyResolver
public async Task<IEnumerable<ChildModel>> GetChildrenAsync(
    Parent parent,
    ChildByParentIdDataLoader childByParentId,
    CancellationToken cancellationToken) =>
    await childByParentId.LoadAsync(parent.Id, cancellationToken)
    ?? Enumerable.Empty<ChildModel>(); // notice explicit null handling
```

**Comment by gojanpaolo** [comment]
Note that we also need to explicitly handle `null` in the resolver function, at least when using `DataLoader`. A `Cannot return null for non-nullable field` error will be thrown if `null` is not handled explicitly,

e.g.
```c#
descriptor
    .Field(p => p.Children)
    .ResolveWith<MyResolver>(r => r.GetChildrenAsync(default!, default!, default))
    .Type<NonNullType<ListType<NonNullType<ChildModelObj>>>>();

// MyResolver
public async Task<IEnumerable<ChildModel>> GetChildrenAsync(
    Parent parent,
    ChildByParentIdDataLoader childByParentId,
    CancellationToken cancellationToken) =>
    await childByParentId.LoadAsync(parent.Id, cancellationToken)
    ?? Enumerable.Empty<ChildModel>(); // notice explicit null handling
```

## EDIT

It looks like it was needed on my `DataLoader` because it inherits `BatchDataLoader<int, IGrouping<int, ChildModel>>`.. Changing it to `BatchDataLoader<int, IEnumerable<ChildModel>>` deemed the explicit `null` handling unnecessary.

**Comment by michaelstaib** [comment]
Completely overlooked this one.

**Comment by michaelstaib** [comment]
So this are different issues.... the first issue 

ResolveWith(r => new List) is actually not meant be used with an expression .... ResolveWith is meant to refer to member expressions.

-> .ResolveWith<MyResolver>(r => r.GetChildrenAsync(default!, default!, default))

the above is correct.

`Resolve` is for delegates.

**Comment by michaelstaib** [comment]
@gojanpaolo also this is correct. If you return null this is per spec invalid. That you want an empty list in this case is implementation detail to your specific case.

**Comment by gojanpaolo** [comment]
@michaelstaib I think the issue on my example is that the `DataLoader.LoadAsync` returns `Task<TValue>` where `TValue` is not marked as `nullable`.

**Comment by Odonno** [comment]
Facing the same problem here. Adding the `.Type()` was my only idea, like @zaneclaes you did.

It's really annoying that it does not infer the NonNull or Null type from the `Field()` function...
