### ISSUE TITLE
Thinking to build a code generator tool using HotChocolate

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#2573]
Greetings,

I am thinking to build a code generator tool using HotChocolate.
The tool will basically take as input all `*.gql` files and outputs multiple other formats such as `*.sql`, `*.cs`, `*.ts`, `*.vue`, etc  by leveraging a plugin system plus some compile-time GraphQL directives to enrich the `*.gql` inputs.
There will also be some configuration file to control the pipeline.

My questions are:
Can I rely on HotChocolate for parsing, walking, and rewriting the `*.gql` inputs and then transforming them to outputs?
Do I need the full HotChocolate library or can I just import HotChocolate.Language for this?
Any other dependencies form HotChocolate are needed for my objective?
Where do I need to starting reading other than the official docs?
Any anticipated issues with HotChocolate?

Thank you in advance.

**Comment by geekox86** [comment]
Also, do you think I should use `DocumentNode` or `ISchema` as input for my code generator?

**Comment by geekox86** [comment]
I tried to use `SchemaBuilder` by calling `AddDocumentFromFile` on multiple `*.gql` files.
Now after calling `Create`, I need to know the source file of each type. How can I achieve this?

**Comment by michaelstaib** [comment]
It all depends ... but you could just use the Language lib which gives you the parser and syntax walker and rewriter.

The schema will give you semantic for a schema. But depending on what you do it might not be what you want :)

**Comment by geekox86** [comment]
@michaelstaib Hi Michael. I think I will need to validate the semantics of the `*.gql` so I think I will go with the `SchemaBuilder` but I do not need the resolvers and I still need to know each type/directive/operation... etc. came from which original source file before merging them all into one single schema using `AddDocumentFromFile`.

How do I create the schema without resolvers?
How do I figure out the original source file used with `AddDocumentFromFile` for each type/directive/operation... etc.?

**Comment by geekox86** [comment]
I was reading on schema stitching and it seems very helpful in what I am trying to accomplish if I can figure out which type/directive/operation/field... etc. comes from which source schema. All of my source schemas are local `*.gql` files.

How do I access the stitched schema after creating it using `AddRemoteSchemaFromFile`?
How can I figure out the source schema for each type/directive/operation/field... etc.?

**Comment by geekox86** [comment]
I gave schema stitching more thought and it seems what I really need is to be able to `AddLocalSchemaFromFile` (i.e. not remote schema) that will be treated differently by the `@delegate` directive such that it will simply trigger the right local query resolver instead of triggering a remote query request. This approach in essence would remove the need for field resolvers and allow the schema to be dissected into multiple schema files. Then, the only thing left is somehow reference the required schemas inside other schemas so that tooling can figure out auto-complete and validation errors.

Is this somehow possible to implement in HotChocolate using middleware components?
Do you know of any tools that support such external references (not imports)?

**Comment by michaelstaib** [comment]
> How do I create the schema without resolvers?

you can feed in a middleware that will intercept all resolvers:

```csharp
schemaBuilder.Use(next => context => throw new NotSupportedException();)
```

this essentially will make you bypass the resolver validation.

**Comment by geekox86** [comment]
Hi @michaelstaib again.

Is it possible to create a stitched schema from a console application (i.e. a dotnet tool)?
If all my remote schemas are from files or strings, why do I still need to register an HTTP client via `AddHttpClient`?
