### ISSUE TITLE
[Spread] object argument into separate arguments

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2577]
# Desired behaviour
Possibility to be able to annotate a resolver method argument to be "spread". Happy to discuss alternate names, just thought it kinda works like a JS spread operator on an object.

```c#
// Resolver method
public Uri GetQuoteUrl(
    [Spread] QuoteUrlParameters input)
    =>  _mediator.Send(input);

// Input class
public class QuoteUrlParameters
{
    /// <summary>A vehicle's make, e.g. Ford</summary>
    public string VehicleMake { get; }

    /// <summary>A vehicle's model, e.g. Fiesta</summary>
    public string? VehicleModel { get; }

    [GraphQLIgnore] public string Ignored { get; set; }
    // ctor
}
```

```graphql
type Query {
    quoteUrl(
        "A vehicle's make, e.g. Ford"
        vehicleMake: String!, 

        "A vehicle's model, e.g. Fiesta"
        vehicleModel: String
    ): Uri!
}
```

# Why?

1. Allows FEDs to see the api surface with args at the top-level, like GitHub's API for instance, but allows us on BE to get an object constructed for us that we can:
    1. Validate with [FairyBread](https://github.com/benmccallum/fairybread)
    2. Fire as a MediatR `IRequest`
2. Further to that, XML documentation can be picked up and exposed out of the schema.

# Design

## Annotating an argument

1. `SpreadAttribute`
    1. Supported directly on argument in resolver method.
    2. Supported on object class itself (`QuoteUrlParameters`) in scenario above (to be applied in all uses).
2. Extension method for fluent-style setup

All above would use a descriptor extension to then set a flag that can be picked up by the type interceptor.

## Rewriting arg and building arg object for resolver

The recent mutation conventions type interceptor and middleware would be a good source of inspiration.

Would replace the annotated arg with the arg's type's properties/fields.

Would hook up a middleware that takes the arguments and instantiates the full object arg.

# Relates to
* A request from @RohrerF (issue #773) Michael mentioned which essentially wants the opposite. 

# Edge cases

1. Multiple uses of `[Spread]` in one field on multiple arguments. This could cause arg names conflicts when expanded. 
Current thinking is to just throw a schema build-time exception.
2.

**Comment by benmccallum** [comment]
Feel free to chuck some thinking on here @michaelstaib / @PascalSenn . 

I think the annotating part would be easy enough, I just need more details/design on how the rewriting arg and instantiating it on use would work. Given those concepts already exist in HC, it'd be great to be able to re-use existing functionality that knows how to build args list for a type T and similarly the functionality that knows how to pluck args and use T's ctor.

**Comment by benmccallum** [comment]
@maraisr this will interest you and allow us to not use the `input: SomeInput` convention in queries too for the convenience it provides. Best of both worlds :)

**Comment by RohrerF** [comment]
@benmccallum The issue I created a while ago would be #773

**Comment by PascalSenn** [comment]
This can be done with MutationConventions

**Comment by PHILLIPS71** [comment]
@PascalSenn I understand this issue is closed, but it would be nice to have more flexibility in defining mutation inputs. Currently, it would wrap the message contract input within the mutation convention input, which requires defining all input parameters separately and then creating a new `UserRegister.Command` inside the mutation call. 

It would be nice to pass the contract directly and have a way to annotate it so it's spread it into the mutation conventions input.

For example, with the current code:
```C#
[MutationType]
internal sealed class UserRegisterMutation
{
    [Error<DomainException>]
    [Error<ValidationException>]
    [UseSingleOrDefault]
    [UseProjection]
    public async Task<IQueryable<Membership>> UserRegister(
        [Service] ApplicationDbContext database,
        [Service] IRequestClient<UserRegister.Command> request,
        UserRegister.Command input,
        CancellationToken cancellation = default)
    {
        Response response = await request.GetResponse<UserRegister.Result, DomainFault, ValidationFault>(input, cancellation);
        return response switch
        {
            (_, UserRegister.Result result) => database.Memberships.AsNoTracking().Where(x => x.TenantId == result.TenantId && x.UserId == result.UserId),
            (_, DomainFault fault) => throw new DomainException(fault),
            (_, ValidationFault fault) => throw new ValidationException(fault),
            _ => throw new InvalidOperationException()
        };
    }
}
```


```graphql
type Mutation {
  user_register(input: User_registerInput!): User_registerPayload!
}

input User_registerInput {
  input: CommandInput!
}

input CommandInput {
  email: String!
  given_name: String!
  family_name: String!
  password: String!
}
```

**Comment by PascalSenn** [comment]
@PHILLIPS71  lets try something, can you annotate the command with [GraphQLName("User_registerInput")]?

Its more of a test than a final solution, so dont worry adding a dependency to your application layer

**Comment by PHILLIPS71** [comment]
@PascalSenn annotating the message contract does seem to work 😆 

```C#
public sealed class UserRegister
{
    [GraphQLName("User_registerInput")] 
    public sealed record Command : Message
    {
        public required string Token { get; init; }

        public required string GivenName { get; init; }

        public required string FamilyName { get; init; }

        public required string Password { get; init; }
    }
    
    ...
}
```

```graphql
type Mutation {
  user_register(input: User_registerInput!): User_registerPayload!
}

input User_registerInput {
  token: String!
  given_name: String!
  family_name: String!
  password: String!
}
```

**Comment by PascalSenn** [comment]
@PHILLIPS71 you can use a naming convention to overwrite the naming centrally.  create a class that extends from `DefaultNamingConvention`, overwrite the method which creates the type name and register it with `AddConvention<INamingConvention, YourNamingConvention>()`

**Comment by michaelstaib** [comment]
You do not need to throw btw.

```
[MutationType]
internal sealed class UserRegisterMutation
{
    [UseSingleOrDefault]
    [UseProjection]
    public async Task<MutationResult<IQueryable<Membership>, DomainFault, ValidationFault>> UserRegister(
        [Service] ApplicationDbContext database,
        [Service] IRequestClient<UserRegister.Command> request,
        UserRegister.Command input,
        CancellationToken cancellation = default)
    {
        Response response = await request.GetResponse<UserRegister.Result, DomainFault, ValidationFault>(input, cancellation);
        return response switch
        {
            (_, UserRegister.Result result) => database.Memberships.AsNoTracking().Where(x => x.TenantId == result.TenantId && x.UserId == result.UserId),
            (_, DomainFault fault) => fault,
            (_, ValidationFault fault) => fault,
            _ => throw new InvalidOperationException()
        };
    }
}
```
