### ISSUE TITLE
Setting MaxexecutionDepthRule sets MaxComplexityRule instead

### ISSUE THREAD

**Issue by JTinkers** [ChilliCream/hotchocolate#2579]
**Describe the bug**
Using the following line: `.AddMaxExecutionDepthRule(16)` will set `MaxComplexityRule` instead of what it should.

**To Reproduce**
1. Create a fresh project, add a query type with single field
2. After `.AddGraphQLServer()` add the following line: `.AddMaxExecutionDepthRule(4)`
3. Upon fetching the schema, you'll receive an error about received document being too complex with the following error: `The GraphQL document has an operation complexity of 53 which exceeds the max allowed operation complexity of 4.`

**Expected behavior**
Setting MaxExecutionDepth as opposed to MaxComplexity

**Comment by michaelstaib** [comment]
I now have looked at the code, and only the message is wrong. So it is the correct rule but a wrong message. We will fix that with the next rc.
