### ISSUE TITLE
Broken links on site

### ISSUE THREAD

**Issue by CD1010** [ChilliCream/hotchocolate#2582]
![image](https://user-images.githubusercontent.com/7614498/99191275-ccf29080-2739-11eb-8675-40f738a2b053.png)

**Comment by michaelstaib** [comment]
There should be a js redirect.

**Comment by rstaib** [comment]
@michaelstaib There is no redirect for this specific link. Did we changed that link?

**Comment by PascalSenn** [comment]
Closed as stale
