### ISSUE TITLE
StrawberryShake.Tooling Token is Discarded if Not Null

### ISSUE THREAD

**Issue by matt-goldman** [ChilliCream/hotchocolate#2584]
cc: @william-liebenberg

**Describe the bug**
When using `dotnet graphql init`, passing in a token with `-t` or `--token` doesn't work - the API returns a 401

**To Reproduce**
1. Install the StrawberryShake tooling with `dotnet tool install`
2. Run `dotnet graphql init [url] -n MyName -p MyPath -t [token]`

**Expected behavior**
An authenticated call to the GraphQL API should be made

**Actual behavior**
The API returns a 401

**Additional context**
I think this is caused by this line: 

https://github.com/ChilliCream/hotchocolate/blob/121cbad2c35adf9478850504cd0bce259a4391b9/src/StrawberryShake/Tooling/src/dotnet-graphql/DefaultHttpClientFactory.cs#L20

Should be 
```csharp
if(!(token is { }))
```

or

```csharp
if (!string.IsNullOrWhitespace(token))
```

**Comment by matt-goldman** [comment]
FYI, I have been trying to update this locally so I can submit a PR, but I can't get this to build locally. I receive multiple package errors. Plus project references don't appear to be working correctly, adding these manually to see if it helps.

**Comment by matt-goldman** [comment]
@Jmercha I hope you don't mind - I submitted a PR into your branch to fix this

**Comment by fernand0aguilar** [comment]
Hi @michaelstaib and @matt-goldman 

I've been trying to use the cli tool to create a new schema and pass an authentication token with the `--token` flag.
The thing is that every string I pass throws the error from below

` $ dotnet graphql update --token 1234`
```
Download schema started.
error INTROSPECTION_ERROR: 1 validation error detected: Value at 'accessToken' failed to satisfy constraint: Member must satisfy regular expression pattern: [A-Za-z0-9-_=.]+
```

I`m somewhat a newb in this. Could it be that I'm doing something wrong?

**Comment by matt-goldman** [comment]
@fernand0aguilar this doesn't look like a related issue. I'm curious what branch you're running from? I don't think the code change I submitted has been released yet.

In any case - your token of '1234' matches the regex pattern in the error response. But that error looks like its come from your GraphQL server, not from this tooling (that regex isn't in the tooling as far as I can tell: https://github.com/ChilliCream/hotchocolate/tree/main/src/StrawberryShake/Tooling/src/dotnet-graphql/OAuth - but I can't be 100% sure, it's not my library :) ). What's the GraphQL server you're hitting?

**Comment by matt-goldman** [comment]
In fact a quick search of the repo shows that the only reference to that regex is in this issue, so I'd say its a safe bet that its coming from the server you're trying to query.

**Comment by fernand0aguilar** [comment]
Hey @matt-goldman thank you for answering so quick. 

I'm running the StrawBerry.Tools from CLI, version `11.0.0-preview.138` And It's true what you've said.  I've also searched for the regex and couldn't find anything so it must be in the server side. The server url is [here](https://3m2vlpfe3h.execute-api.us-east-1.amazonaws.com/development/auth/sign-in)

I was wondering if there's a possibility that the token data sent forwards in being manipulated in some way that causes the error.  

The steps im taking are: I have sent a curl request to their servers auth endpoint with the clientId, username and password as header. Then got a bearer token as response. Now I'm following the [tutorial](https://chillicream.com/blog/2019/11/25/strawberry-shake_2) and trying to send this token via CLI to be able to query their graphql api.

Anyways... Thank you again for all the great work.

**Comment by matt-goldman** [comment]
@fernand0aguilar is it your GraphQL server? Have you tried querying it using the token you obtained but with other tooling? For example there's the Banana Cake Pop GraphlQL client that's part of this stack, or you can use Postman.

**Comment by fernand0aguilar** [comment]
@matt-goldman not mine. I have to consume and write some automated tests for an interview. I've tried using https://hoppscotch.io/ works out fine.

thank you for your attention tho.
