### ISSUE TITLE
Namespace for HotChocolateAspNetCoreServiceCollectionExtensions is Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by unwork-ag** [ChilliCream/hotchocolate#2590]
The namespace declaration in this file: src/HotChocolate/AspNetCore/src/AspNetCore/Extensions/HotChocolateAspNetCoreServiceCollectionExtensions.Http.cs
is presumably wrong. Currently it is:

namespace Microsoft.Extensions.DependencyInjection

I think it should be HotChocolate.AspNetCore.

This applies to all ServiceCollectionExtensions in this folder.

**Comment by unwork-ag** [comment]
Looks like this is intentional (same pattern also for other ServiceCollection extensions.

**Comment by michaelstaib** [comment]
> Place extension methods in the Microsoft.Extensions.DependencyInjection namespace to encapsulate groups of service registrations. Including the namespace portion Microsoft.Extensions.DependencyInjection for DI extension methods also:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2
