### ISSUE TITLE
PublishToRedis should have string configurationName

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#2595]
For now configurationName is NameString which validates values as valid graphql type

I want to use `MyStitchingRedisPrefix.MyStitchingService` with `.` separator for redis key and it is impossible for now

![image](https://user-images.githubusercontent.com/46970457/99377216-fdbbfc80-28d6-11eb-9efd-800423b8c98a.png)
![image](https://user-images.githubusercontent.com/46970457/99377285-14625380-28d7-11eb-88cd-08e891971986.png)

**Comment by michaelstaib** [comment]
For now, you can use an underscore instead of a `.`. I will evaluate a change when we work on 11.1.

**Comment by sergeyshaykhullin** [comment]
I am using `.` for all my services for better redis gui experience

For now i am using `stitching` configurationName

I will wait for 11.1, thanks)

**Comment by sergeyshaykhullin** [comment]
Is this a duplicate of something? Should i close issue?

**Comment by michaelstaib** [comment]
No, leave it open.

**Comment by michaelstaib** [comment]
I thought you did report this already, but it might be you told me this on slack.
