### ISSUE TITLE
String max length not in schema

### ISSUE THREAD

**Issue by 206mph** [ChilliCream/hotchocolate#2611]
I added Added [StringLength(200)] to a record property for a mutation input and am not seeing it noted in the schema using Banana Cake Pop or other tools.

I expected that when I add the annotation in, the schema would pick that up so users can see the max length of a string field. However, I am new to GraphQL and Hot Chocolate so my expectation could be off. My expectation was somewhat set by REST API coding with Swagger.

I'm using Hot Chocolate 11.0.0-rc.5, on net5 using Pure Code First.

If this is not the intended functionality, how can I notate a max length in the schema?

BTW, that's for all the work! It's greatly appreciated.

**Comment by michaelstaib** [comment]
We do not handle these attributes ... if you want validation then there is the following project:
https://github.com/benmccallum/fairybread

I do not know if its already on 11.

**Comment by michaelstaib** [comment]
@benmccallum is there already a version for 11?

**Comment by benmccallum** [comment]
I haven't updated FairyBread to v11 yet, will likely attempt this weekend. 

I believe what @206mph is asking though is a directive in the schema saying what the max length allowed is. I don't have that on the radar for FairyBread yet, but it's something that could be done I guess. Marais and I were going to think about how we could expose rules to the FE one day to inform client-side UI frameworks for instance.

If you wanna create an issue on FairyBread @206mph detailing why you need it we can have a think about it. Being quite strict on the feature set atm for obv reasons :)

**Comment by 206mph** [comment]
I created an issue for FairyBread. Sorry for the lack of better terminology. I'm still new to GraphQL but after more research, it does look like custom directives based on the FluentValidation and/or data annotations is exactly what I'm looking for, That seems to be the cleanest implementation from what I can tell.

**Comment by benmccallum** [comment]
I think we can probably close this so I will, but feel free to re-open if I got it wrong.

Can't say when I'd ever get to something like the max length annotations in FairyBread-land, but if you want to learn more about HC and GraphQL it could be an interesting PR you could contribute over there. We can continue the discussion over there. CHeers.
