### ISSUE TITLE
Fix ID Input Coercion

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#264]
When expected as an input type, any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

**Comment by algjohnston** [comment]
Is it really fixed?

https://stackoverflow.com/questions/79182547/how-do-you-get-strawberryshake-to-treat-id-as-a-number
