### ISSUE TITLE
XML documentation missing on derived fields

### ISSUE THREAD

**Issue by mvestergaard** [ChilliCream/hotchocolate#2643]
This bug was introduced between rc6 and rc7, I suspect this commit c8faf5efe447da880327c23ae729c39526bb334e

```cs
public class A
{
  /// <summary>Bla bla</summary>
  public string Foo { get; set; }
}

public class B : A
{
}
```

The documentation for `foo` will not be output on `B`

**Comment by michaelstaib** [comment]
found it:
https://github.com/ChilliCream/hotchocolate/commit/c8faf5efe447da880327c23ae729c39526bb334e#diff-dd209d2b6cd474e7b7a36cf53c371fe841c7d8f6076f86b4a3f1acf106fa5042

**Comment by michaelstaib** [comment]
OK, fixed it.
