### ISSUE TITLE
Any resources on Strawberry Shake?

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#2647]
Hey there. This is more of a question than a bug report or feature request.

I wanted to get into Strawberry Shake, but I noticed that the documentation is actually non-existent (https://chillicream.com/docs/strawberryshake/)

We're working on a project where we use Hot Chocolate on the back-end, and we're gonna use Blazor on the front-end, so we obviously need a robust GraphQL client framework. But there is almost no competition there in .NET! Strawberry shake is the only promising choice.

So, I have 2 questions:
1. When are you planning to write the docs for Strawberry Shake?
2. In the meantime, put simply, where should one go to learn it?! What other resources are there that you recommend? Any articles? Videos? I'd appreciate some links.

I'm also curious to know what has been the go-to resource for people who are _already_ using Strawberry Shake? Because I noticed there are quite a few issues on it in this repo, so that means people must be using it, but since there are no docs, they must have learned about it through some other resource(s).

I appreciate any guidance as to how and where to get started when it comes to Strawberry Shake. Thanks in advance.

**Comment by michaelstaib** [comment]
Hi there, we will start diverting dev resources to strawberry shake starting next week... The release is planned for the end of January. At this moment we are working to get the server documentation updated.

**Comment by michaelstaib** [comment]
https://chillicream.com/blog/2019/11/25/strawberry-shake_2

**Comment by AradAral** [comment]
>The release is planned for the end of January
Just to make sure, by "release" you mean the release of docs or the next version?

> https://chillicream.com/blog/2019/11/25/strawberry-shake_2
Thanks for the link. Other than the two blog posts (this one and the other one) and the YouTube videos where you're giving a presentation, are there any other resources that I'm not aware of?
