### ISSUE TITLE
GraphQL multipart request specification

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#265]
https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by thangchung** [comment]
Hi @michaelstaib, could you let me know that when do we have this one? Or any way to work-around when using HotChocolate lib?

**Comment by michaelstaib** [comment]
We are planing this for 11.1. I cannot commit to a timeline on this.

**Comment by GuptaParitosh** [comment]
Hi @michaelstaib , we are trying to implement multi-part request in our hot chocolate application. just wanted to know the updates on this issue. Is there any other workaround for file upload functionality through hot chocolate.

**Comment by michaelstaib** [comment]
Not yet.

**Comment by pablor21** [comment]
I'm very interested in this feature too! I'm using v. 11 and I have not had luck trying to implement by myself.
@michaelstaib Is there any news on this? (even in beta/alpha)

**Comment by findli** [comment]
> Hi @michaelstaib , we are trying to implement multi-part request in our hot chocolate application. just wanted to know the updates on this issue. Is there any other workaround for file upload functionality through hot chocolate.

Hi

https://stackoverflow.com/a/63818353/2910338

and this gist is helpfull: [https://gist.github.com/PascalSenn/9b623a439426fa361552632d8bd7972a](https://gist.github.com/PascalSenn/9b623a439426fa361552632d8bd7972a)

**Comment by tobias-tengler** [comment]
I needed this in a personal project, so I threw together a [quick implementation](https://github.com/tobias-tengler/hotchocolate/pull/1).

This is a pretty hacky solution, but it works for me at the moment and offers a really simple API:
```csharp
descriptor.Field("uploadFiles")
    .Type<UploadedFilesType>() // irrelevant
    .Argument("files", i => i.Type<ListType<FileType>>())
    .Argument("file", i => i.Type<FileType>())
    .Resolve(context =>
    {
        var files = context.ArgumentValue<List<IFormFile>>("files");
        var file = context.ArgumentValue<IFormFile>("file");

        return null;
    });
```

Looking forward to the final implementation of this feature by the lovely folks of this repository! :)
If I can help advance this feature in any form, let me know.

**Comment by michaelstaib** [comment]
Hi @tobias-tengler,

thank you for your work on this. I went through your implementation and it looks promising. 

Can you create a pull-request to our repo and then we can start refining it together?
