### ISSUE TITLE
Query not shown when using the integrated Banana Cake Pop

### ISSUE THREAD

**Issue by cryo75** [ChilliCream/hotchocolate#2657]
I created an ASP.NET Core app with an SQLite DB, and set up GraphQL. So my `Startup` looks like this:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>();

            services.AddGraphQLServer()
                .AddType<CategoryType>()
                .AddQueryType<Query>();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints => {
                endpoints.MapGraphQL();
            });
        }
    }

I added a `Query` class which is simply this:

    public class Query
    {
        [UseSelection]
        public IQueryable<Category> GetCategories([Service] AppDbContext context) => context.Categories;
    }

I start the app and using the integrated Banana Cake Pop. But I cannot see the query. 

Am I missing something during configuration?

**Comment by PascalSenn** [comment]
By default there is no query defined in Banana Cake Pop.

You have to write queries by youself:
```
{
    categories {  someprop}
}
```

Also, UseSelection was deprecated with V11.  You should use UseProjections from the `HotChocolate.Data` package

**Comment by cryo75** [comment]
I did that but it didn`t solve the problem. When I test with Playground, the error "Server could not be reached" is shown

**Comment by PascalSenn** [comment]
what does the console tab say? 
![image](https://user-images.githubusercontent.com/14233220/100143391-8d444b00-2e95-11eb-952a-99e1f316e2a4.png)

**Comment by cryo75** [comment]
Nothing. It`s empty. Like every other pane. And Playground shows this:

![image](https://user-images.githubusercontent.com/3060986/100192829-f1492c80-2ef2-11eb-86d0-9c8cfbffaf62.png)

**Comment by abdusco** [comment]
`[UseSelection]` is not yet supported in v11. From what I understand, you kinda have to `.Include()` relations yourself until it becomes available.
