### ISSUE TITLE
Enum values in response splitting with underscore!

### ISSUE THREAD

**Issue by yasharvc** [ChilliCream/hotchocolate#2658]
**Enum name that has 2 or more parts underscoring**
When enum name has 2(or more parts) (say `HelloWorld` ) is going to be `Hello_World` and even worse is `GUID` is going to be `G_U_I_D`!!!
![Capture](https://user-images.githubusercontent.com/15121807/100078353-ada1e480-2e58-11eb-808a-b9271cf31ea2.PNG)

**Comment by PascalSenn** [comment]
Hi @yasharvc  
We follow the GraphQL spec recommendation in naming enums,

If you want the old behaviour back you can use a naming convention:
https://chillicream.com/docs/hotchocolate/api-reference/migrate-from-10-to-11/#enum-type

**Comment by michaelstaib** [comment]
The G_U_I_D could be an issue however ... we can have a look at that. But `NEGATIVE_INTEGER` is correct. You can however change it to the old behaviour.

**Comment by yasharvc** [comment]
@michaelstaib please share the way of using the old behavior.

**Comment by huysentruitw** [comment]
@michaelstaib I have a PR proposal ready to fix cases like this, but I wonder how hard it is for people to just change their enum names from `StringGUID` to `StringGuid` f.e.

**Comment by michaelstaib** [comment]
@huysentruitw where is the PR?

**Comment by michaelstaib** [comment]
And yes would be great if we correctly handle cases like `StringGUID`

**Comment by huysentruitw** [comment]
PR is linked

**Comment by michaelstaib** [comment]
I have merged the PR and we have released it as https://github.com/ChilliCream/hotchocolate/releases/tag/11.1.0-preview.2
