### ISSUE TITLE
AUTH_NOT_AUTHORIZED code returned instead of AUTH_NOT_AUTHENTICATED when jwt is invalid

### ISSUE THREAD

**Issue by hundreder** [ChilliCream/hotchocolate#2665]
**Describe the bug**
Looks like after change in this commit in version 10.4.2 Authorize directive is changed so that error code returned are inconsistent.
https://github.com/ChilliCream/hotchocolate/commit/2e8b7b282bc95c4f01605cdaf1c9e9b0959f5194
Prior to this version when **Authorize()** directive is used on field definition, and invalid jwt is passed, error code returned was AUTH_NOT_AUTHENTICATED. 
After 10.4.2. code returned in this case is AUTH_NOT_AUTHORIZED. Inconsistency lies in a fact that when directive is set on field with role as **.Authorize(new[] {"HasCountry"})** with same invalid jwt, different (and good) code is returned AUTH_NOT_AUTHENTICATED. Code returned should not be dependent on that.

**To Reproduce**
1. Open StarWars example from 10.4.2 + version 
2. Goto QueryTupe calls and change Ln 28 with 
 `.Authorize(new[] {"HasCountry"});`
3. Execute query
`{
  search(text:"R2-D2"){
    ... on Droid{
      id
      name
    }
  }
}`
Response returned is 
`{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "search"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    }
  ],
  "data": {
    "search": null
  }
}`
4. Now go to class QueryType and change Ln 28 to
`.Authorize();`
5. Execute same query again an response is
`{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "search"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    }
  ],
  "data": {
    "search": null
  }
}`

**Expected behavior**
No matter if field is protedted by role or not, same error code **AUTH_NOT_AUTHENTICATED** should be returned as user is not authenticated.

**Desktop (please complete the following information):**
 - OS: WIN 10 
 - HotChocolate 10.4.2
 - .net core 3.1

**Comment by michaelstaib** [comment]
This was a deliberate change where we give policy control over the authentication check. This, in turn, means we only are authorized or not authorized ... which actually is correct. 

If you want an auth check you can require authentication now on the route.

**Comment by hundreder** [comment]
Let me get it right.
It is ok to return AUTH_NOT_AUTHENTICATED on field with Authorize(new []{"fooRole"])
and to return AUTH_NOT_AUTHORIZED on field with Authorize()

In both cases token not provided.

**Comment by michaelstaib** [comment]
No, it should be always `AUTH_NOT_AUTHORIZED`. We need to clean up the implementation. We were so split in working on two versions at the same time that both implementations were developed further on their own :)

I will have to reevaluate this. I put this issue on the backlog.

**Comment by michaelstaib** [comment]
The general idea is to not deal with authentication state but refer if somebody is authorized to the auth policies.

**Comment by hundreder** [comment]
So it sounds like AUTH_NOT_AUTHENTICATED is going to disappear. 
If this is true I am not sure if client would be able to distinct when user token has simply expired and perform some refresh of the token compared to that he is not allowed to access the field. Because in both scenarios AUTH_NOT_AUTHORIZED  will be returned. 
Lets say we have schema something like this
`type Query {
  foo: String @authorize
  bar: String`

and query

`query{
foo
bar`

if user is not authenticated foo field should return error, and bar should return data. If only AUTH_NOT_AUTHORIZED is returned how should client distinguish from "I need to refresh token" to "Its ok, I just cant access this"?

**Comment by michaelstaib** [comment]
This should be handled earlier before GraphQL execution is started which is much mir efficient.

**Comment by michaelstaib** [comment]
I will write something up.

**Comment by hundreder** [comment]
I'll write down one more example, and than I'll stop (I hope :D)

Schema
```
type Query {
  foo: String @authorize( roles: [ "fooRole" ]) 
  bar: String @authorize( roles: [ "barRole" ]) 
  baz: String
```

And we have query
```
query{
  foo
  bar
  baz
}
```

Anonimous user executes a query and get response
```
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "path": [
        "foo"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    },
    {
      "message": "The current user is not authorized to access this resource.",
      "path": [
        "bar"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    }
  ],
  "data": {
    "foo": null
    "bar": null
    "baz": "baz"
  }
}
```

Authorized user with fooRole will get
```
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "path": [
        "bar"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    }
  ],
  "data": {
    "foo": "foo"
    "bar": null
    "baz": "baz"
  }
}
```

Like there is a difference in REST how clients perceive 401 and 403, I have a feeling that similar thing should be done here. With 403, client is like, ok I cant access this. With 401, client enters some flow, like refresh the token, or go to login page. With examples above client is not able to distinguish that.
I am not saying I am right, you are wrong, but just trying to understand how would client be able to know they are not authenticated. Especially when you say that should be done earlier, seems like mixed queries with public fields would not be possible.

**Comment by michaelstaib** [comment]
If you are not authenticated it should only be checked once and then faulted before any execution is done. Otherwise, you waste processing on something that you cannot use. Authorization is different since it can be totally valid to grab the data that you are allowed while telling the consumer what data is not allowed. Still, the authentication check could produce a GraphQL error content with a corresponding status code. I have not yet had the time to specify this. But its on the backlog and we will fix that I think with the first 11 patch release.

**Comment by hundreder** [comment]
> If you are not authenticated it should only be checked once and then faulted before any execution is done.

To me, it sounds like that anonymous user will not be able to fetch public field, or I'm missing something.

**Comment by ntziolis** [comment]
@michaelstaib I have come across this thread in the search for a way to customize auth error responses (similar to what aspnet core allows via `IAuthorizationMiddlewareResultHandler`). There doe not seem to be one today or am I mistaken, if you are reworking this area could you take this into consideration as well? Happy to to open an issue for this separately to track it.
