### ISSUE TITLE
How to get execution result data?

### ISSUE THREAD

**Issue by Dolfik1** [ChilliCream/hotchocolate#267]
Schema.Execute returns `IExecutionResult` that contains only `Errors` field. I need to get `Data` field in `QueryResult`, but `QueryResult` is `internal`, so I can not use type casting.

**Comment by michaelstaib** [comment]
You can cast it to https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Execution/IQueryExecutionResult.cs

**Comment by michaelstaib** [comment]
With the addition of subscriptions it also can be a subscription execution result.

**Comment by Dolfik1** [comment]
> 
> 
> You can cast it to https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Execution/IQueryExecutionResult.cs

Thanks!

**Comment by itmuckel** [comment]
I have the same problem. `Execute()` returns an `IExecutionResult` and `Console.WriteLine()` prints out `HotChocolate.Execution.ReadOnlyQueryResult`. I followed the instructions in the paragraph `Using Hot Chocolate`.

**Comment by michaelstaib** [comment]
@itmuckel we have changed the way it works ... I am working an updated example.

At the moment we have the IQuerResultSerializer / JsonQueryResultSerializer that is able to serialize the result .... 

With the ASP.net server this is much better and we can now exchange the serialization format and implementation.

However, for demo purposes we will add an extension method ToJson() ... but this is coming in the next view commits....

for now JsonQueryResultSerializer is the solution.... sorry for the outdated documentation....

**Comment by michaelstaib** [comment]
I have opened an issue for that .... 
https://github.com/ChilliCream/hotchocolate/issues/905

**Comment by asad-sangla** [comment]
according to "Update Readme Example #905 " `ToJsonString()` or `ToJson()` works and produces result
