### ISSUE TITLE
Strawberry Shake guidance on .netframework

### ISSUE THREAD

**Issue by celoke** [ChilliCream/hotchocolate#2673]
Is there an implementation guide for Strawberry Shake client using .net framework?

I have successfully implemented using .net core following this article https://chillicream.com/blog/2019/11/25/strawberry-shake_2

**Comment by celoke** [comment]
At the moment, I am using dotnet standard to bridge the implementation as a ,net core library with .net framework project. I am not sure if this is the best practice.

**Comment by michaelstaib** [comment]
StrawberryShake is a new project and will not be targeting .NET Framework.

**Comment by michaelstaib** [comment]
We target with the newest version .netstandard 2.0
