### ISSUE TITLE
Api Reference Docs: not clear where AddSocketSessionInterceptor extension located

### ISSUE THREAD

**Issue by Arsync** [ChilliCream/hotchocolate#2681]
I've tried to implement `MyCustomSocketSessionInterceptor` as described in [arcticle](https://chillicream.com/docs/hotchocolate/api-reference/aspnetcore) of HotChocolate 11, but stuck with
```cs
services.AddSocketSessionInterceptor<MyCustomSocketSessionInterceptor>();
```
as this service collection extension doesn't contains in any referenced assembly (or just ReSharper can't find it quickly).

Found [here](https://github.com/ChilliCream/hotchocolate/commit/13ebe83b82a841f1bbf0b13955506720effc62a5#diff-ef9c932921a08bd59ba05acb5d638cab4b9b4236fface000a7103d117f2724ba), but can't imagine where it located.

Also, previously I've used `IQueryExecutionBuilder`, but seems it changed in v11:
```cs
services.AddGraphQL(
    sp =>
    {
        return SchemaBuilder.New()
            .AddServices(sp)
            ...
            .Create();
    },
    // This one:
    (IQueryExecutionBuilder builder) => builder
        // For websocket authentication purpose:
        .Use(next => async context =>
        {
            var hca = context.Services.GetRequiredService<IHttpContextAccessor>();            
            context.ContextData["ClaimsPrincipal"] = hca.HttpContext.User;            
            await next(context);
        })
        .UseDefaultPipeline()
);
```
And there is no `Authorization` section yet...
Please, guide me how to migrate it?

**Comment by michaelstaib** [comment]
We are still working on the new documentation. We hope to get it done over the next two weeks.

We now have a unified configuration API where you can just chain in configurations.

```csharp
services
    .AddSocketSessionInterceptor<MyCustomSocketSessionInterceptor>();
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .UseRequest(next => async context =>
        {
            var hca = context.Services.GetRequiredService<IHttpContextAccessor>();            
            context.ContextData["ClaimsPrincipal"] = hca.HttpContext.User;            
            await next(context);
        })
        .UseDefaultPipeline()
       .AddAuthorization()
```
