### ISSUE TITLE
Case-insensitive String Filters

### ISSUE THREAD

**Issue by afouadr** [ChilliCream/hotchocolate#2687]
I am using your wonderful 'graphql' server for exposing a big event-sourced in-memory object graph/domain model for performance reasons. All is going well except the current implementation of filters have no support for specifying case-insensitive string comparisons for 'in-memory data'.

I would like to have an option to enable all/specific fields to have case-insensitive filters. Or just a confiquration switch while configuring schema, e.g.:
.
.
.
schema.AddFilters(options => options.IgnoreCase = true);

For now I've substituted my own filter input type instead of using the auto-generated filter input class. But its too much effort to create a substitute filter input type for each of my entities.

Please help!

**Comment by PascalSenn** [comment]
@afouadr  are you working with filters in version 11?

**Comment by afouadr** [comment]
> @afouadr are you working with filters in version 11?

Yes I am using v 11.0.0

**Comment by PascalSenn** [comment]
@afouadr this repo contains a example how you can override the handlers for string operations:
https://github.com/PascalSenn/Filtering.Demo
it just adds a handler for the equals operation, but you can also add handlers for all other operations

**Comment by afouadr** [comment]
> @afouadr this repo contains a example how you can override the handlers for string operations:
> https://github.com/PascalSenn/Filtering.Demo
> it just adds a handler for the equals operation, but you can also add handlers for all other operations

Thank you for the sample :-) I'll follow the code and let you know the outcome.

**Comment by afouadr** [comment]
@PascalSenn I've followed the sample code and its a 100% success, thank you very much for you help 👍

**Comment by PascalSenn** [comment]
@afouadr  cool, i am gonna close the issue in this case :)
