### ISSUE TITLE
TypeLoadException when having Strawberry Shake on frontend and Hot Chocolate on the backend

### ISSUE THREAD

**Issue by araxemy** [ChilliCream/hotchocolate#2689]
Hey. I'm facing a strange exception, and I believe it to be due to some sort of a bug. I'm using the Blazor WebAssembly ASP.NET Core hosted project template, which consists of 2 projects, "client" and "server", "client" being a Blazor WebAssembly project, and "server" being a regular ASP.NET Core project, you're definitely familiar with this template.
I have installed Hot Chocolate on the server project, and I have nothing but a "Query" class which contains nothing but one method that returns a literal string.
On the client project, I have installed Strawberry Shake and I haven't done anything other than that there.

**The mere presence of the Strawberry Shake package on the client project causes the following exception to be thrown when sending a request to the server** I know this is because of Strawberry Shake because as soon as I uninstall it or remove the reference to the client project from the server project, the error is gone.
```
TypeLoadException: Could not load type 'HotChocolate.Language.DirectiveDefinitionNode' from assembly 'HotChocolate.Language, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
On another project with the same stack I get this exception (similar, but not identical, on this project I've installed `HotChocolate.Types.Selection` too, I don't know if that has anything to do with it or not):
```
TypeLoadException: Could not load type 'HotChocolate.Language.OperationType' from assembly 'HotChocolate.Language, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Here is the GitHub repo, just clone it real quick and see it for yourself. It's the simplest of projects you could possibly imagine. Nothing complicated, as I said all I did was add one query class and install HC and SS packages, that's it. https://github.com/araxemy/StrawberryShakeProblem

### Version details:
Hot Chocolate 10.5.5
Strawberry Shake 11.0.0-preview.137
.NET 5

**Comment by araxemy** [comment]
**Update:** I found out that this doesn't happen with Hot Chocolate v11.0.0.
That being said, due to the fact that documentation for v11 is non-existent, we can't migrate conveniently.
Is there any way this can be solved?

**Comment by PascalSenn** [comment]
Hi @araxemy 
So you can not mix the version 10 with strawberry shake in the same project. 

Documentation on version 11 is trickling in at the moment 
Have you seen the migration guide? 
https://chillicream.com/docs/hotchocolate/api-reference/migrate-from-10-to-11/

Yes there is a selection middleware, it is now called `UseProjections` and lifes in `HotChocolate.Data`

**Comment by araxemy** [comment]
@PascalSenn Hi!
Okay then, I guess it's time to migrate!
Thanks for the link! I didn't know such a guide existed. Great to see some progress on the docs!
Thanks. Keep up the great work.

**Comment by PascalSenn** [comment]
cool! 
lets us know if you bump into any issue while migrating 👍 if so, gou can also ping us on slack
