### ISSUE TITLE
AnyType not supported in stitched schemas 

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2691]
when the downstream service is using AnyType in its schema as input or output, the gateway fails to resolve its type reference

1. Unable to resolve type reference `Output: Any`. (HotChocolate.Types.ObjectType)

v11

**Comment by PascalSenn** [comment]
@MariaCobretti  Did you register the AnyType on the gateway schema?

**Comment by MariaCobretti** [comment]
yes I did

**Comment by michaelstaib** [comment]
Any is not supported with schema stitching at the moment.

**Comment by michaelstaib** [comment]
It is not supported with V10 or V11. There are some details to it that make it difficult. Also, we will focus on other things that we think are more important with schema stitching like subscription stitching and the execution engine integration. So, it might be a while until we support Any for stitching.

**Comment by michaelstaib** [comment]
I will have another look at this ....

**Comment by PascalSenn** [comment]
@michaelstaib  is this one done?
