### ISSUE TITLE
BCP: shortcut to add all properties to query

### ISSUE THREAD

**Issue by francisrath** [ChilliCream/hotchocolate#2692]
**Is your feature request related to a problem? Please describe.**
It would be useful when testing the API under development to quickly add all possible properties to a query.

**Describe the solution you'd like**
When you have added a query and can start adding properties to the request, I propose another option at the top of the dropdown list: "&lt;add all properties&gt;" that adds all the available properties to the query.

**Comment by rstaib** [comment]
What do you mean by all properties? If you mean all fields, this could lead to an infinite tree or at least to a very deep tree in case we put an algorithm in place that recognises and stops infinite recursion respectively. Do you have already a concept you would like to share?

**Comment by francisrath** [comment]
Yes, I meant all fields. But to keep things relatively simple and avoid said infinite trees, how about just including the current level, and maybe an empty {} for object fields, for example this from the Star Wars sample:

```
query {
  characters {
    nodes {
      <dropdown and select "all fields" here>
    }
  }
}
``` 
would result in this:
```
query {
  characters {
    nodes {
      appearsIn
      friends {}
      height
      id
      name
    }
  }
}
``` 
As you can see, we limit the problem by not selecting fields of `friends`, but making it easy to repeat the same inside `friends`, or simply deleting the line if we don't care about it.

Maybe not the top priority feature, but it would make exploring and testing a bit quicker when you have many fields.

**Comment by rstaib** [comment]
Okay now I see what you are up to 👍 looks interesting! Let me think about this. I will come back to you.

**Comment by julianadormon** [comment]
I would like to see this as well. Adding the fields is tedious. It would be faster to remove the fields we don't want in some cases. Thanks for considering this.

**Comment by o4zloiroman** [comment]
Yeah, I'd appreciate having this functionality.

**Comment by glen-84** [comment]
See https://github.com/ChilliCream/graphql-platform/issues/6213.
