### ISSUE TITLE
Stitching remote and a local schema results in error

### ISSUE THREAD

**Issue by bromix** [ChilliCream/hotchocolate#2714]
**Describe the bug**
We try to stitch/merge two remote schemas and one local schema at the gateway. In NodeJS with graph-tools and expressjs this works. Now we want to do the same in dotnet, because we are thinking about switching to HotChocolate.

```The name `Query` was already registered by another type. (HotChocolate.Types.ObjectType<hotchocolate_stitching.Query>)```

**To Reproduce**
1. Clone [https://github.com/bromix/hotchocolate-stitching](https://github.com/bromix/hotchocolate-stitching)
2. Run Service
3. Try to get documentation or execute query

**Expected behavior**
We expect that the remote schema and the locale are merged in a way that the query "sayHello" is also included.

**Desktop (please complete the following information):**
 - Windows 10
 - HotChocolate v11.0
- Net5.0

**Log File**
[error.log](https://github.com/ChilliCream/hotchocolate/files/5628546/error.log)

**Comment by bromix** [comment]
Additional Information - I followed the example of:
https://chillicream.com/blog/2020/11/23/hot-chocolate-11#schema-stitching

```
services
    .AddGraphQLServer()
    // adds a local query type
    .AddQueryType<Query>()
    // and merges that with the incoming schemas
    .AddRemoteSchema(Accounts)
    .AddRemoteSchema(Inventory)
    .AddRemoteSchema(Products)
    .AddRemoteSchema(Reviews);
```
But it results in the same error:
```The name `Query` was already registered by another type. (HotChocolate.Types.ObjectType<hotchocolate_stitching.Query>)```

I tried HotChocolate.AspNetCore v11.0.1, HotChocolate.Stitching v11.0.1 and v11.1.0-preview.4

**Comment by michaelstaib** [comment]
Which would be correct.... since you already have a query type ....

in your case:

```
.AddRemoteSchema(Inventory, ignoreRootTypes: true)
```

and then create a type extension which defines which parts from the downstream services you want to merge with the local Query type.

or the other way around.

```
[ExtendObjectType(""Query)]
public class Query
{

}

services
    .AddGraphQLServer()
    // adds a local query type
    .AddTypeExtension<Query>()
    // and merges that with the incoming schemas
    .AddRemoteSchema(Accounts)
    .AddRemoteSchema(Inventory)
    .AddRemoteSchema(Products)
    .AddRemoteSchema(Reviews);
```

**Comment by bromix** [comment]
Nice! Didn't know about ```[ExtendObjectType("Query")]```

```ignoreRootTypes: true``` on the remote Schemas won't work for us, because we lose the Queries and Mutations of the remote schema, only the local Query survived.

But with ```ExtendObjectType``` it`s exactly what we're are looking for. I presume this will also work for any other types like Mutations and Subscriptions?

Thanks for the help!

**Comment by sgebhardt** [comment]
> Which would be correct.... since you already have a query type ....
> 
> in your case:
> 
> ```
> .AddRemoteSchema(Inventory, ignoreRootTypes: true)
> ```
> 
> and then create a type extension which defines which parts from the downstream services you want to merge with the local Query type.
> 
> or the other way around.
> 
> ```
> [ExtendObjectType(""Query)]
> public class Query
> {
> 
> }
> 
> services
>     .AddGraphQLServer()
>     // adds a local query type
>     .AddTypeExtension<Query>()
>     // and merges that with the incoming schemas
>     .AddRemoteSchema(Accounts)
>     .AddRemoteSchema(Inventory)
>     .AddRemoteSchema(Products)
>     .AddRemoteSchema(Reviews);
> ```

Thanks @michaelstaib 
This solves exactly my question from https://github.com/ChilliCream/hotchocolate/issues/2683#issuecomment-737119772_ .

**Comment by sgebhardt** [comment]
> `ignoreRootTypes: true` on the remote Schemas won't work for us, because we lose the Queries and Mutations of the remote schema, only the local Query survived.

You can re-add the root queries by extending the Query type. 
An example is in the "hotchocolate-examples": https://github.com/ChilliCream/hotchocolate-examples/blob/master/misc/Stitching/centralized/gateway/Stitching.graphql

```
extend type Query {
  me: User! @delegate(schema: "accounts", path: "user(id: 1)")
  topProducts(first: Int = 5): [Product] @delegate(schema: "products")
}
```

This uses the graphql file. But i dont know how you can do it with `[ExtendObjectType("Query")]`

**Comment by bromix** [comment]
> This uses the graphql file. But i dont know how you can do it with ```[ExtendObjectType("Query")]```

```[ExtendObjectType("Query")]``` is exactly doing that. We now have a merged Query of local and remote schema. But thanks for the hint with delegates - maybe this will come in handy.
