### ISSUE TITLE
Splitting a single error into multiple errors using IErrorFilter

### ISSUE THREAD

**Issue by drewbj21** [ChilliCream/hotchocolate#2716]
Hello,

I am new to GraphQL/HotChocolate and am trying to set up error handling with fluent validation. I am using Fairy Bread to integrate Fluent Validation with HotChocolate.

I have created an error filter that gets the IError and ValidationException objects when there is a validation error and currently have the errors within the ValidationException being passed back in as a JSON string in a custom extension in the IError. This is working as expected, but I would prefer to remove the original IError from the error collection and add an IError to the collection for each validation error.

Is this possible with a IErrorFilter? Is there a better approach I should be using? Thanks in advance!

**Comment by michaelstaib** [comment]
No, this is not possible with filters.

What you could do is catching the exception in the middleware pipeline and creating from that a `GraphQLException` which can have multiple errors.

**Comment by drewbj21** [comment]
Thanks for the response. I will try to get that to work.

I also have another question surrounding error handling... I am running into an issue where I throw an exception within my mutation and instead of returning a 200 response with the error collection and data, I am getting a 500 response with only the error collection. I have nothing in the pipeline after HotChocolate so there shouldn't by anything interfering with what HotChocolate is returning from what I understand. I am running v11.0.0.

Do you know what could be causing this?

Let me know what other information you might need from me. Thanks!

**Comment by drewbj21** [comment]
So I've been trying to catch the ValidationExcpetion in exception middleware before my error filter without much luck...

I have been trying use an exception handler added to the pipeline in startup.cs like this:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
   app.UseMiddleware<ExceptionHandlerMiddleware>();
   ...
}
```

Within my ExceptionHandlerMiddleware class I have the following:

```
private async Task InvokeAsync(HttpContext context)
{
   try
   {
      await _request(context);
   }
   catch (Exception exception)
   {
       //Throw GraphQLException here
   }
}
```


My error filter is getting hit before the code above so by the time the code above is hit, the response has already been written to. Because of this, I am unable to create multiple hot chocolate errors from the ValidationException and I am unable to change the response.

Is there something I am missing? Are you aware of a way to implement middleware that is hit before my error filter? Where should that be put?

Thanks again for your help!
