### ISSUE TITLE
Ability to load multiple items in one call/request

### ISSUE THREAD

**Issue by Wkalmar** [ChilliCream/hotchocolate#2731]
**Is your feature request related to a problem? Please describe.**
The feature request title suggests that it's a case for batch data loader described in docs. However, it's not the thing I need and I'll describe why below.
The problem I have is that I get the collection of instances by their IDs and each property of the instance is obtained from a different service. Here's what it looks like.
```
public class Result 
{
	public Guid Id {get; set;}
	public int Prop1 {get; set;}
	public int Prop2 {get set;}	
}

public async Task<List<Result>> GetItems(
            [Service] Service1 service1,
            [Service] Service2 service2,
            Guid[] entityIds)
{
	var uniqueEntityIds = entityIds.ToHashSet();
	Dictionart<Guid, int> props1 = await service1.Get(uniqueEntityIds);
	Dictionart<Guid, int> props2 = await service2.Get(uniqueEntityIds);
	return MergeResults(uniqueEntityIds, props1, props2); //produce list of Result instances
}
```
And then I configure it via `builder.AddQueryType`
**Here are key things to understand at this point**:
- I need to pass multiple ids to a service in order to get data in one hop instead of opening multiple connections/requests
- These are some time-consuming services so if `prop1` is not provided in a request I'd love not to call `service1`

**Describe the solution you'd like**
So as a starting point I've found [this class](https://github.com/ChilliCream/hotchocolate/blob/main/src/MarshmallowPie/src/GraphQL/BatchDataLoader.cs) and I've crafted a resolver for each field which uses a child loader. Something like this.
```
public class ResultType : ObjectType<Result>
{
	protected override void Configure(IObjectTypeDescriptor<NodeRelationCount> descriptor)
	{
		descriptor.Field(p => p.Prop1)
			.Resolver(ctx => {
				var loader = ctx.Service<Prop1DataLoader>();
				return loader.LoadAsync(id, CancellationToken.None); //need smh to infer id here
			});
		//etc etc
	}
}

public class Prop1DataLoader: BatchDataLoader<Guid, int>
{
	//ommited for brievity

	protected override Task<IReadOnlyDictionary<Guid, int>> 
		FetchBatchAsync(IReadOnlyList<Guid> keys, CancellationToken cancellationToken)
	{
		return _service1.Get(new HashSet<Guid>(keys));
	}
}
```
However, now I'm not sure how to register a query that will return a collection of these `ResultType`s. 

**Describe alternatives you've considered**
Another alternative might be just to inject `IResolverContext` directly into the original query method and somehow infer from one of its properties that `prop1` is not on a request. 

Thank you and have a good day,
Bohdan.

**Comment by michaelstaib** [comment]
Where is the `id` coming from? is it an argument or is it the ID from the parent?

**Comment by Wkalmar** [comment]
Sorry for the late response. 
`id` is coming from the parent
