### ISSUE TITLE
Unable to resolve diagnostics listener with dependencies

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#2733]
In Hot Chocolate 11 I've been unable to add any diagnostics listeners that have a constructor dependency.  Ones with the default constructor work correctly, but the others fail with a message

> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Notifications.Api.GraphQL.TestDiagnosticEventListener'.

I've verified that the dependency is registered and other services can correctly resolve it.

I've reproduced the bug as a unit test on the following [branch](https://github.com/ChilliCream/hotchocolate/compare/ns/event-listener-bug).

**Comment by jmezach** [comment]
We just ran into this issue as well. It is almost as if Hot Chocolate has its own dependency injection container.

**Comment by PascalSenn** [comment]
@jmezach  It kind of has, but unless you work with error handler or diagnostice listeners you do not have to worry about it :) 

If you have one schema there are three service providers. 
1. The application SP that you configure in ConfigureServices
2. The schema service provider that is used for schema related things (specific to each schema)
3. The execution service provider, a scoped of a service provider that combines the two above

During development this is opaque to you, unless you do create DiagnosticListeners or ErrorFilters (SP 2.) with dependencies on application services (SP 1.). 

You have to register it like this:
given @nigel-sampson  sample you would have to register the diagnostic listener like this:

```csharp
private class DependentListener : DiagnosticEventListener
{
    private readonly IDependency dependency;

    public DependentListener(IDependency dependency)
    {
        this.dependency = dependency;
    }
}

private interface IDependency
{
}

private class Dependency : IDependency
{ 
}
```

```csharp
services.AddGraphQLServer()
      .AddDiagnosticListener(x => new DiagnosticListener(x.GetApplicationService<DependentListener>));
```

cc @michaelstaib  if i got the above right, i will add it to the docs

**Comment by jmezach** [comment]
After posting here I figured this out on my own ;). I solved it by adding my DiagnosticEventListener as a singleton to my application container using `AddSingleton<>` and then using `AddDiagnosticEventListener(sp => sp.GetApplicationService<InsightsDiagnosticEventListener>())`. That at least solves the startup issue.

Interestingly my event listener doesn't seem to be invoked though. I've overriden `RequestError` from the `DiagnosticEventListener` but that method isn't called, even though an error occurs during my request (I've taken the database offline).

**Comment by michaelstaib** [comment]
@jmezach do you have a simple repro?

**Comment by michaelstaib** [comment]
Can we close this issue?

**Comment by nigel-sampson** [comment]
I think so. Understanding the different service provides is key here.  Definitely a candidate for inclusion in the docs.
