### ISSUE TITLE
Replacing one type in master schema with type from other schema

### ISSUE THREAD

**Issue by petstrani** [ChilliCream/hotchocolate#2744]
I have two databases. Each of them has a customer table with the same key values for customers but different field names with similar contents. I would like to use HotChocolate graphql with code first approach and entity framework for my queries. My question is, if it is possible to stick these two database schemas together and in master schema replace customer type with the customer type from the second schema (it means making relation from the master database to  table in the other database and take customer data from the other database  ). How can I achieve that?

**Comment by michaelstaib** [comment]
Have you done our workshop already?

https://github.com/ChilliCream/graphql-workshop
