### ISSUE TITLE
Can not access Cookies inside IHttpContextAccessor

### ISSUE THREAD

**Issue by yasharvc** [ChilliCream/hotchocolate#2753]
Consider following code inside Resolve function:
```
var httpctx = ctx.Service<IHttpContextAccessor>().HttpContext;
var value = httpctx.Request.Cookies["somekey"];
httpctx.Response.Cookies.Append("newCookie", "value");

```
the `value` will be null despite it is set and `newCookie` won't set.

Sample source code:

```
descriptor.Field("version")
	.Type<StringType>()
	.Resolve(ctx =>
	{
		var httpctx = ctx.Service<IHttpContextAccessor>().HttpContext;

		var value = httpctx.Request.Cookies["test"];
		httpctx.Response.Cookies.Append("test", "value");
		return "1.0";
	});
```

**Comment by PascalSenn** [comment]
Hi @yasharvc 

We just hand the response back to the client. 
So this works:
![image](https://user-images.githubusercontent.com/14233220/103011867-f07bd880-453a-11eb-8df4-5e6f91714815.png)

Are you using banana cake pop? Because BCP does not support cookies. 
cc @rstaib

**Comment by yasharvc** [comment]
Front-end sending data with Appolo-Client. But I couldn't get the cookies inside the resolver. Actually, the Type of the cookie is HTTP-Only.

**Comment by reinux** [comment]
Is there a reason cookies aren't supported by BCP? It'd be nice to have, since I want to use it to test authentication.

**Comment by rex-pj** [comment]
Hi, I have the same problem, do you have any solution?

**Comment by PascalSenn** [comment]
@reinux  Do you have set the HTTP Settings to Include?

**Comment by reinux** [comment]
@PascalSenn Yeah, I ended up discovering that later 😁
