### ISSUE TITLE
ToListMiddleware/ExecutableMiddleware is not applied on Task<IQueryable<T>> type

### ISSUE THREAD

**Issue by JakeSmokie** [ChilliCream/hotchocolate#2754]
**Describe the bug**
When `UseDbContext<>()` applied on resolver that returns `Task<IQueryable<T>/Task<IExecutable<T>>` execution fails with this exception: 
`System.ObjectDisposedException: Cannot access a disposed context instance`

The reason is that `UseDbContext<>()` does not treat return types that are wrapped in `Task<T>`

**To Reproduce**
```
[UseDbContext(typeof(MyContext))]
public Task<IQueryable<Item>> GetItems([ScopedService] MyContext context) =>
    Task.FromResult(context.Items.AsNoTracking());
```

**Expected behavior**
Query executes successfully and middleware checks for `Task<IQueryable/IExecutable>` types

**Comment by michaelstaib** [comment]
Hi @JakeSmokie,

what is the use-case here? Is there a case where this would be async? I can imagine that there could be a case where you want to aggregate data before building the query. But what did you have in mind?

**Comment by JakeSmokie** [comment]
I have a case when I receive EmploymentId asynchronously first and then I filter out items using that EmploymentId
