### ISSUE TITLE
Code-First Generation of Split .graphql (Extensions) for Graphql Modules (?)

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/hotchocolate#2756]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I have a code-first schema in my project. I would like to generate multiple different `.graphql` files (to be consumed by `graphql-codegen` on the frontend). I want the type files separated by package because I also want to use [`graphql-modules`](https://graphql-modules.com/).

It seems like `ExtendObjectType` should provide this (and if it already does, I apologize). What I'm looking for specifically is a way to make it so that this class:

```
[ExtendObjectType(Name = "Query")]
  public class PortsQuery {
    public function List<Port> ListPorts();
```

Ends up generating a `.graphql` file that uses the `extended` syntax, **located specifically** at `./src/ports/PortQuery.graphql`:

```
extend type Query {
  listPorts {
[...]
```

**Describe alternatives you've considered**
It seems like the piece I'm missing is how to go from an introspection query to a split graphql schema. I use [an IDE plugin](https://blog.jetbrains.com/webstorm/2019/04/featured-plugin-js-graphql/) to pull the `.graphql` file from my HotChocolate backend.

**Additional context**
I've looked at using an `ISchemaInterceptor`, and have access to the HttpContext sent from the IDE. I have considered simply creating a white/blacklist of type names based upon client parameters. However, I have struggled to figure out how to mutate `ISchema`s types directly.

If it's any help, here's what I was considering:
```
namespace Makerverse.Api {
  public class SchemaSplitterInterceptor : ISchemaInterceptor {
    private static readonly Dictionary<string, string> ClassNameToModuleMap = new Dictionary<string, string>() {
      [nameof(ControlledMachine)] = "",
    };
    
    public void OnBeforeCreate(IDescriptorContext context, ISchemaBuilder schemaBuilder) { }

    public void OnAfterCreate(IDescriptorContext context, ISchema schema) {
      IHttpContextAccessor? httpAccessor = context.Services.GetService<IHttpContextAccessor>();
      IHeaderDictionary? headers = httpAccessor?.HttpContext?.Request.Headers;
      string? schemaContext = headers?["User-Agent"];
      string? module = headers?["Module"];

      // TODO! Use the "module" to return only a subset of the schema

      Log.Debug("[SCHEMA] created {schemaContext}#{module} with types: {@types}",
        schemaContext, module, schema.Types.Select(t => t.Name.Value));
    }

    public void OnError(IDescriptorContext context, Exception exception) {
      Log.Error(exception, "[SCHEMA] split failed");
    }
  }
}
```

**Comment by zaneclaes** [comment]
One more thought —

The `ExtendObjectTypeAttribute` itself would, ideally, hook into this somehow. I think a really elegant solution would be to have this:

```
[ExtendObjectType(Name = "Query", Module = "System")]
```

And then, the sketched out `SchemaSplitter` from above would automatically pick up the `Module` and filter appropriately.

The idea of type extensions are still pretty new to me, so I'm not sure if this is 100% the best route. But having the codegen isolated into modules is a big win for me :)

**Comment by michaelstaib** [comment]
I am thinking on a modules concept ... but rather than have it on types I am thinking on packaging them when you register things.

```csharp
services
    .AddGraphQL()
    .AddModule<FooModule>()
    ....
```

The module contains all the things you want to package by a certain topic. We are still in discussion around this.

**Comment by michaelstaib** [comment]
Preserving the type extensions after build schema is another thing.

**Comment by zaneclaes** [comment]
@michaelstaib great, that'd work well too. If there's any way I can prototype this or test it by editing my code, lmk. Happy to try this out with patches before it makes it to mainline. I already use a static extension method to register each of my modules. This module concept is an opportunity perhaps to formalize this pattern.

**Comment by michaelstaib** [comment]
We have now a module concept which fixes a different use case more meant to solve dynamic schemas. I think I will go with your original idea. Instead of module I will call it tags. 

`[ExtendObjectType(Name = "Query", Tags = "A, B, C")]`

These tags can be picked up in the type interceptor. The type interceptor will allow to discard of type extensions. 

I am still thinking on how to efficiently store the type extensions for serialization. I hope to have this in next week.

**Comment by michaelstaib** [comment]
Schema first variant:

Tags on documents:

```csharp
.AddDocumentFromString("type Foo { ... }", tags: "A, B, C")
```

Tags on types:

```GraphQL
extend type Foo @tags(names: ["A", "B", "C"]) {
   foo: String
}
```

Tags on resolvers: 

```csharp
.AddResolver("Foo.bar", () => ...., tags: ...)
```

There might be other areas where we want to have tags and use them to switch behavior or ignore things.

cc @PascalSenn
