### ISSUE TITLE
Filtering on the extended attributes defined in the stitched schema

### ISSUE THREAD

**Issue by antonlx1** [ChilliCream/hotchocolate#2760]
**Is your feature request related to a problem? Please describe.**
Would like to use filtering on the extended attributes defined in the stitched schema

**Describe the solution you'd like**
Would like to use filtering on the extended attributes defined in the stitched schema

**Describe alternatives you've considered**
Tried Adding .AddFiltering(); in Startup.cs. in the schema stitching project
But not getting filter support on the new attributes defined in Extensions.graphql

**Additional context**

**Comment by PascalSenn** [comment]
Hi @antonix1 

Thank you for your feature request! :) 

There are a couple of things that make this difficult. Stitching makes use of the execution engine to resolve the fields that are requested. Filtering works on the resolver and the middleware pipeline of a field. These two things do not yet know from each other. 

Even though we would like to have support for said feature, this is at the moment not possible. We will keep this in mind though, when we design further steps

**Comment by gojanpaolo** [comment]
@PascalSenn Does that limitation also apply to fields that uses `ResolveWith`?

e.g. we cannot use the `LastActivityTimestamp` field as filter input when configured like so:

```
descriptor
    .Field(_ => _.LastActivityTimestamp)
    .ResolveWith<MyResolver>(_ => _.LastActivityTimestampAsync(default!, default!, default))
    .UseDbContext<MyDbContext>();

// MyResolver
public async Task<DateTime?> GetLastActivityTimestampAsync(
    MyModel model,
    [ScopedService] MyDbContext ctx,
    CancellationToken cancellationToken)
{
    var time = 
         await ctx.Time
        .Where(_ => _.ModelId == model.Id)
        .OrderByDescending(_ => _.OutTimestamp ?? _.InTimestamp)
        .FirstOrDefaultAsync(cancellationToken);
    
    return t?.OutTimestamp ?? t?.InTimestamp;
}
```

Is there a workaround or different approach to solve the said issue?

Thank you!

**Comment by elmanav** [comment]
Do you have plans (backlog) to solve this problem in version 13, where the target is stitched?
Thank you!

**Comment by PascalSenn** [comment]
@elmanav Not this feature in particular. We might be able to do this at some point. but distributed filtering is a complex topic.

**Comment by elmanav** [comment]
> @elmanav Not this feature in particular. We might be able to do this at some point. but distributed filtering is a complex topic.

Thanks.

**Comment by vickytr44** [comment]
Is there any workaround to solve this problem. I need to apply sort/filter on parent node based on child attributes where the child node is extended from stitched schema.
