### ISSUE TITLE
Please bring back ForceSerialExecution in v11

### ISSUE THREAD

**Issue by ayoung-cforp** [ChilliCream/hotchocolate#2761]
Our application is separated into three layers: data, domain, and application.  Our architecture is based on the three-layer approach of DDD.

We use EF Core for our data layer; our domain layer uses projections to translate EF entities into domain objects and expose them to the application layer; then, finally, our GraphQL API is implemented in the application layer.  This means the GraphQL API (ideally) has no knowledge of EF Core or DbContexts or entities or anything.  All that it knows is that the domain services it interacts with are not thread-safe.  There isn't any way for the application layer to communicate to the data layer that it should use some particular DbContext.

In v10 we used ForceSerialExecution, and everything just worked.  Unfortunately it looks like this option has been replaced with DbContext pooling in v11, but that is not an alternative for us.  It seems to me that EF Core was not the only use case for ForceSerialExecution&#8212;it's generally useful when your services are not thread-safe and it's difficult to scope them outside of the context of a request.

If it's too difficult to bring back ForceSerialExecution, I'm open to other suggestions. I'm also willing to contribute if there is some way I can help to make this happen.

**Comment by tsykes-2020** [comment]
(Just wrote this in the slack channel but this seems a better place to discuss it)

We are running into a similar issue with migrating to v11, in our case the resolvers don't directly access the `DbContext`, but instead querying is delegated to other services that in turn use DI to access a `DbContext`.

It seems that the problem stems from HotChocolate breaking the assumptions behind the DI abstraction - that one DI scope is handling one concurrent request.

I think a simple solution to this (unless there's something I've missed) would be to create a DI scope per thread. This way nothing special even needs to be done with `DbContext`, as far as each service is concerned it is serving sequential requests. The `DbContext` can still be obtained from a pool by setting up with `AddDbContextPool`.

**Comment by tsykes-2020** [comment]
Alternatively, it is possible to construct a new `IServiceScope` on a per-field basis. This _could_ be done as part of the field middleware, but it is a bit of a headache to replace the `Services` object for an existing instance of `IMiddlewareContext`
I also have no idea what impact this might have on performance

**Comment by tsykes-2020** [comment]
Another option, which is extremely cumbersome, is to make your services aware that they are part of the HotChocolate pipeline, and allow them to grab and release pooled DbContexts when necessary.
For example:
```
public abstract class DbContextClient<TDbContext> : IDisposable where TDbContext : DbContext
    {
        private readonly IDbContextFactory<TDbContext> dbContextFactory;
        private TDbContext dbContext;

        public DbContextClient(IDbContextFactory<TDbContext> dbContextFactory)
        {
            this.dbContextFactory = dbContextFactory;
        }

        public void Dispose()
        {
            if(dbContext != null)
            {
                dbContext.Dispose();
                dbContext = null;
            }
        }

        protected TDbContext DbContext
        {
            get
            {
                if(dbContext == null)
                {
                    dbContext = dbContextFactory.CreateDbContext();
                }
                return dbContext;
            }
        }
    }


    public class UseScopedServiceAttribute : ObjectFieldDescriptorAttribute
    {
        private static readonly MethodInfo _useScopedService =
            typeof(ScopedServiceObjectFieldDescriptorExtensions)
                .GetMethod(
                    nameof(ScopedServiceObjectFieldDescriptorExtensions.UseScopedService),
                    BindingFlags.Public | BindingFlags.Static)!;

        private static readonly MethodInfo _getService =
            typeof(ServiceProviderServiceExtensions)
                .GetMethod(
                    nameof(ServiceProviderServiceExtensions.GetService),
                    BindingFlags.Public | BindingFlags.Static)!;

        private static readonly MethodInfo _dispose =
            typeof(UseScopedServiceAttribute)
                .GetMethod(
                    nameof(UseScopedServiceAttribute.Dispose),
                    BindingFlags.NonPublic | BindingFlags.Static)!;

        private readonly Type _service;

        public UseScopedServiceAttribute(Type service)
        {
            _service = service;
        }

        public override void OnConfigure(
            IDescriptorContext context,
            IObjectFieldDescriptor descriptor,
            MemberInfo member)
        {
            var createType = System.Linq.Expressions.Expression.GetFuncType(typeof(IServiceProvider), _service);
            var create = _getService.MakeGenericMethod(_service).CreateDelegate(createType);

            var disposeType = System.Linq.Expressions.Expression.GetActionType(typeof(IServiceProvider), _service);
            var dispose = _dispose.MakeGenericMethod(_service).CreateDelegate(disposeType);

            _useScopedService.MakeGenericMethod(_service).Invoke(null, new object?[] { descriptor, create, dispose, null });
        }

        private static void Dispose<TService>(IServiceProvider serviceProvider, TService service)
        {
            if(service is IDisposable)
            {
                ((IDisposable)service).Dispose();
            }
        }
    }
```

With the above, you can inherit your services from `DbContextClient` and use `[UseScopedService(typeof(MyService))]` on your resolver method.

I do not think this is a good solution as it is very invasive to existing services. It would make far more sense to have HotChocolate provide a scope per thread (or per field if that wouldn't impact performance), but can serve as a temporary workaround

**Comment by tsykes-2020** [comment]
relevant: #2735

**Comment by michaelstaib** [comment]
> Alternatively, it is possible to construct a new IServiceScope on a per-field basis. This could be done as part of the field middleware, but it is a bit of a headache to replace the Services object for an existing instance of IMiddlewareContext
I also have no idea what impact this might have on performance

This could be a good solution. 

I will have a look at this.

**Comment by michaelstaib** [comment]
We would actually not need to have this on every field but on those accessing certain services ...

**Comment by michaelstaib** [comment]
So... I now have a branch with this capability, but it introduces new issues with the DataLoader and other APIs that would now reset on those fields. It also introduces other issues with scoped services that are specifically scoped to the request ...

**Comment by tsykes-2020** [comment]
> 
> 
> So... I now have a branch with this capability, but it introduces new issues with the DataLoader and other APIs that would now reset on those fields. It also introduces other issues with scoped services that are specifically scoped to the request ...

Do you think these issues are solvable or is it a fundamental problem with the approach?

If it's not possible to have a separate context per field, then maybe a better approach might be to allow fields to opt in to serial execution. Fields that do this go into a queue to guarantee serial execution. I think this kind of thing might be necessary, because if a context per field is not possible, then fields and services themselves cannot be insulated from being aware that they are executed concurrently. In that situation, the only options are a) the field/service is aware of concurrent execution and is able to cooperate in carrying it out, or b) the field cannot cooperate for one reason or another so concurrent execution should not be attempted with that field

**Comment by michaelstaib** [comment]
> think this kind of thing might be necessary, because if a context per field is not possible, then fields and services themselves cannot be insulated from being aware that they are executed concurrently.

Actually depending on your approach you can already use scoped-services for a field. 

> Do you think these issues are solvable or is it a fundamental problem with the approach?

We are looking at various approaches to this problem. We have not found one that we at this moment like. The idea with the queue was one of them. The fundamental issue here is that not all features work with this. I fundamentally believe that we should not introduce something that introduces issues to other aspects of Hot Chocolate like batching.

We will have a look at solving the problem probably for version 11.2.

**Comment by michaelstaib** [comment]
Serial execution behavior is now handled by the query plans. This means that everything that cannot be executed in parallel is executed serially. However, Microsofts recommendation is to use parallel execution with pooled dbcontexts for performance. 
https://youtu.be/4k3WzW2ZdXs
