### ISSUE TITLE
HC no longer compatible with Simple Injector in v11? Cyclical dependency with the default IBatchDispatcher

### ISSUE THREAD

**Issue by Confusingboat** [ChilliCream/hotchocolate#2764]
**Describe the bug**
I haven't been able to comb through the new batch dispatcher system yet, but from what I'm able to deduce thus far, it would appear as though the [default `IBatchDispatcher`](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Fetching/BatchScheduler.cs) has an indirect dependency on itself somehow (at least in this configuration), and that is causing Simple Injector to reject the configuration.

**To Reproduce**
1. Use HC v11 with default batch scheduler/dispatcher
2. Add your Simple Injector container
3. Watch it blow up when you run a query:
```
{
    "errors": [
        {
            "message": "Unexpected Execution Error",
            "extensions": {
                "message": "The registered delegate for type IBatchDispatcher threw an exception. The configuration is invalid. The type IBatchDispatcher is directly or indirectly depending on itself. The cyclic graph contains the following types: IBatchDispatcher.",
                "stackTrace": "   at SimpleInjector.InstanceProducer.GetInstance()\n   at SimpleInjector.Container.System.IServiceProvider.GetService(Type serviceType)\n   at lambda_method(Closure , IRequestContext , OperationExecutionMiddleware )\n   at HotChocolate.Execution.Pipeline.RequestClassMiddlewareFactory.<>c__DisplayClass7_0`1.<Create>b__3(IRequestContext c)\n   at HotChocolate.Execution.Pipeline.OperationVariableCoercionMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)"
            }
        }
    ]
}
```

**Expected behavior**
No cyclical dependencies and a happy DI framework.

**Additional context**
HC packages are on `11.1.0-preview.6`

I'm working on a repro repo, will update here later.

**Comment by Confusingboat** [comment]
Repro repository: https://github.com/Confusingboat/hot-chocolate-v11-simple-injector

**Comment by michaelstaib** [comment]
We need some services from the request services. You need to do this a little different. Will have a look at this later.

**Comment by hmvs** [comment]
@michaelstaib Have you had a chance to look at it?
