### ISSUE TITLE
[UsePaging] attribute seems to be missing in HotChocolate.Types 11.1.0-preview.6

### ISSUE THREAD

**Issue by sangelastro** [ChilliCream/hotchocolate#2766]
**Bug description**
[UsePaging] attribute seems to be missing in HotChocolate.Types 11.1.0-preview.6.

**To Reproduce**
1. Install HotChocolate.Types (11.1.0-preview.6)
2. Using HotChocolate.Types.Relay;
3. Try to add a [UsePaging] attribute upon your query 
4. See error "The type or namespace "UsePagingAttribute"/"UsePaging" could not be found (are you missing a using directive or an assembly reference?)

**Expected behavior**
[UsePaging] is expected to be found.

**Desktop:**
 - OS: Windows 10

**Comment by PascalSenn** [comment]
This should be enough
`using HotChocolate.Types;`

**Comment by sangelastro** [comment]
`using HotChocolate.Types;` is not enough though.

**Comment by PascalSenn** [comment]
Do you have a package reference to the package `HotChocolate` ?

**Comment by michaelstaib** [comment]
can we close this issue?
