### ISSUE TITLE
When adding an IErrorFilter with dependencies, that is created using the provided ServiceFactory of .AddErrorFilter, the ErrorFilter is never instantiated, nor executed.

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#2768]
**Describe the bug**
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGraphQLServer()
                .AddErrorFilter(factory => new MyErrorFilter(factory.GetApplicationService<ILogger<MyErrorFilter>>()))
                .AddQueryType<Query>();
        }
```

```
public class MyErrorFilter: IErrorFilter
    {
        private readonly ILogger<MyErrorFilter> _myErrorFilter;
        public MyErrorFilter(ILogger<MyErrorFilter> myErrorFilter)
        {
            _myErrorFilter = myErrorFilter;
        }
        public IError OnError(IError error)
        {
            Console.WriteLine("An Error occured!");
            return error;
        }
    }
```

**To Reproduce**
Checkout https://github.com/fredericbirke/HcErrorFilterBug, start it and fire the ping query using BCP.
If you set the breakpoints, you will see, that the ErrorFilter is never instantiated or used.

**Expected behavior**
The ErrorFilter should work exactly the same way as the ErrorFilter, that has no dependencies to other services from the DI-Container.

**Comment by shgreig-mtm** [comment]
Does anyone have any way of working around this issue.
I'm trying to get an ILogger into my Error filter so I can log all errors that come from the api but obviously can't inject the ILogger at the moment as the API breaks when I add this in

**Comment by PascalSenn** [comment]
@shgreig-mtm this should be fixed with #2774. Do you still see this issue? What version are you on?

**Comment by shgreig-mtm** [comment]
@PascalSenn 12.4.1 
So if I do just this
```
public class ErrorFilter : IErrorFilter
{
	private readonly ILogger<ErrorFilter> _logger;
	private readonly IHttpContextAccessor _contextAccessor;

	public ErrorFilter()
	{
	
	}
	public IError OnError(IError error)
	{
            return error.WithMessage(error.Exception.Message);
	}
}
```
Its working

But when I try and inject into the constructor I all of my queries will just 500 error

`public class ErrorFilter : IErrorFilter
{
	private readonly ILogger<ErrorFilter> _logger;
	private readonly IHttpContextAccessor _contextAccessor;

	public ErrorFilter(ILogger<ErrorFilter> logger, HttpContextAccessor httpContextAccessor)
	{
		_contextAccessor = httpContextAccessor;
		_logger = logger;
	}
	public IError OnError(IError error)
	{
		return error.WithMessage(error.Exception.Message);
	}
}`

**Comment by PascalSenn** [comment]
@shgreig-mtm  You have to register it with the delegate overload:
```csharp
 .AddErrorFilter(factory => new ErrorFilter(factory.GetApplicationService<ILogger< ErrorFilter>>(),....))
               
```

**Comment by shgreig-mtm** [comment]
Ah okay thank you, that is now working

**Comment by PascalSenn** [comment]
Cool :)

**Comment by ThisNoName** [comment]
> 

Hope you are still tracking this.  I tried this with IHttpContextAccessor, it works the first time when I launch the application, but if I make another call, the injected context seems disposed.  Any clue what I missed?  Thanks.

```
    services.AddHttpContextAccessor();

    services.AddGraphQLServer()
        .AddErrorFilter(factory => new MyLErrorFilter(
            factory.GetApplicationService<IHttpContextAccessor>()))

    public class MyErrorFilter : IErrorFilter
    {
        public MyErrorFilter (IHttpContextAccessor context) { ... }

        public IError OnError(IError error) { ... }
```
