### ISSUE TITLE
[Banana Cake Pop] Disable schema caching of BCP Middleware

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#2771]
Check https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1608502041362000

**Comment by dzmitry-lahoda** [comment]
i cannot disable and cannot get to thread, could you please post here

**Comment by dzmitry-lahoda** [comment]
i feel miserable

**Comment by fredericbirke** [comment]
Currently if BCP is used as middleware, it uses caching by default. You must simply press the schema refresh button every time you change your schema in the server.

<img width="1790" alt="grafik" src="https://user-images.githubusercontent.com/9481836/106145691-23d30800-6176-11eb-8505-33ab87b4717b.png">
