### ISSUE TITLE
[Banana Cake Pop] Add Authenticationflows

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#2772]
The following authenticationflows types should be supported:
 - OAuth 1.0
 - OAuth 2.0
 - Basic Auth
 - Bearer Token
 - Cookie Based Auth

An arbitrary amount of authenticationflows should be defineable per project.
Each authenticationflow should be able to take a name and all necessary data needed to execute the authenticationflow.

When executing an operation, the user should be able to choose the authenticationflow on a per document basis.

![authflow](https://user-images.githubusercontent.com/9481836/102725191-1de73d00-4315-11eb-8266-2f854780a038.png)

**Comment by RiaanVR** [comment]
Hi Team.
Is there a technical challenge here or it just requires some people, we've got some consumers of our HotChocolate instance who have really come to love the ability to rapidly iterate the queries they then build into their systems, but without this their workflow is impaired by having to an OAuth flow outside, usually with a script or having to clear some cookies and re-entering the app and copying an access_token from a helper endpoint, it would be great if it natively supported some flows?

**Comment by RafaelMalgor** [comment]
Hi, 
Just wanted to say that BCP is a great tool when it comes to quickly building and trying queries, loving the product so far. The biggest gap I have encountered so far is the lack of authentication. So far I have been obtaining the Token from outside BCP (using Postman) and then manually copying it into the "Headers" section of BCP. It works, but it is cumbersome, so I wanted to leave my 2 cents, as I think this feature would be really helpful to a lot of people.

**Comment by tobias-tengler** [comment]
@RafaelMalgor the new preview with this feature is already on its way #4441 :)

**Comment by tobias-tengler** [comment]
Authentication Flows have now been part of BCP for some time, so I'm closing this issue. 

![image](https://user-images.githubusercontent.com/45513122/151701775-b6d80eb7-789f-4db7-bf4a-0fa3e90438a8.png)


If you encounter issues, please raise a new issue here on GitHub! :)
