### ISSUE TITLE
[StrawberryShake] GraphQL websocket client error with websocketclientfactory

### ISSUE THREAD

**Issue by rafsanulhasan** [ChilliCream/hotchocolate#2775]
**Describe the bug**

While implementing graphql with Hotchocolate in .net 5 and blazor, my server works well with subscription (graphiql and playground) but while I created graphql client with strawberryshake, it has thrown me an exception:

“WebSocket connection to 'wss://localhost:5001/graph' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: graphql-ws” 

“”

It happened when I tried to use websocketclient.connect got injected from Iwebsocketclientfactory from Transports.WebSocket package.

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10

**Additional context**

**Comment by tobias-tengler** [comment]
Does this still happen with version 11.2?
I'm closing this for now, feel free to re-open if this is still an issue.
