### ISSUE TITLE
delegate directive: $fields doesn't work on local schema

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#2785]
**Describe the bug**
when using $fields in a delegate directive, the values are always null when the type to extend is local and not remote.

**To Reproduce**
https://github.com/OneCyrus/hc_repro-fields-delegate

**Expected behavior**
$fields should resolve on local types like on remote types.

**Desktop (please complete the following information):**
 - OS: Windows 10 2009
 - Version HC 11.x

**Comment by PascalSenn** [comment]
I guess this is fixed with #2835

**Comment by OneCyrus** [comment]
> I guess this is fixed with #2835

it's not fixed with 11.0.8. i guess it's not supposed to be fixed yet or @michaelstaib would have closed the issue by now?

**Comment by michaelstaib** [comment]
No, its not. This one is slated for 11.2 -> March

**Comment by michaelstaib** [comment]
The local schema fix is about allowing to stitch in local schemas.

**Comment by PascalSenn** [comment]
@michaelstaib  but if @OneCyrus  would use a local schema it would work right? or is there no serialization between localschema and gateway schema?

**Comment by michaelstaib** [comment]
ah ... oK yes it would I guess :) since it would be serialized :) good thinking @PascalSenn

**Comment by OneCyrus** [comment]
isn't the repro already using a local schema?

```
services
                .AddRouting()
                .AddGraphQLServer()                
                .AddQueryType<Query>()
                .AddRemoteSchemaFromFile("network", networkSdl, true)
                .AddTypeExtensionsFromFile(Path.Combine(HostingEnvironment.ContentRootPath, "NetworkSchemaExtension.graphql"));
```
