### ISSUE TITLE
Asp.Net Core multiple authentication schemes

### ISSUE THREAD

**Issue by castroal** [ChilliCream/hotchocolate#2786]
**Describe the bug**
Hello all, I have a question regarding the support for multiple authentication schemes in HotChocolate v11.0.6.

I am working on a multi-tenant application using Azure AD for users authentication and I configured the required services as described here: https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#using-multiple-authentication-schemes

```
//First tenant
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(Configuration, "AzureAd")
            .EnableTokenAcquisitionToCallDownstreamApi()
            .AddInMemoryTokenCaches();

//Second tenant
services.AddAuthentication()
            .AddMicrosoftIdentityWebApi(Configuration, "AzureAdB2C", "B2CScheme")
            .EnableTokenAcquisitionToCallDownstreamApi();

services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme, "B2CScheme")
                    .RequireAuthenticatedUser()
                    .Build();
            });

....

services.AddGraphQLServer()
            .AddAuthorization()
            .AddQueryType(d => d.Name("Query"))
            .AddTypeExtension<SomeQueries>();
```

Only the users from the first tenant are able to query graphql, for the users from the second tenant I get "The current user is not authorized to access this resource."

Is this scenario supported? If not, can you advise me on how to implement it?

Thanks in advance.

**Comment by otryshko** [comment]
I had to add a "DoubleSchemeAuthenticationHandler" and register it as its own schema. In HandleAuthenticateAsync there I call this.Context.AuthenticateAsync() passing first schema name and on failure, second schema name.

**Comment by castroal** [comment]
> 
> 
> I had to add a "DoubleSchemeAuthenticationHandler" and register it as its own schema. In HandleAuthenticateAsync there I call this.Context.AuthenticateAsync() passing first schema name and on failure, second schema name.

How it is related to graphql? I mean, the authentication pipeline seems to work correctly except for graphql; for example controllers decorated with the [Authorize] attribute allow the access to both users from both tenants.

**Comment by castroal** [comment]
Some more information.

I was able to debug the `AuthorizeMiddleware` in `HotChocolate.AspNetCore.Authorization` and it seems that the ClaimsPrincipal that it gets from `IDirectiveContext.ContextData` in the method `TryGetAuthenticatedPrincipal ` is empty when I perform a request using a token that belongs to an users from the second tenant.

**Comment by castroal** [comment]
So I found the culprit of the issue...

I was missing a call to RequireAuthorization() after MapGraphQL():


            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapGraphQL()
                         .RequireAuthorization();
            });
