### ISSUE TITLE
Option to name types based on fully qualified names of .Net Types 

### ISSUE THREAD

**Issue by jewpaltz** [ChilliCream/hotchocolate#2805]
B"H

I have one project where the existing DTOs are all of the same name as the EntityFramework classes, just in the DTO namespace.

i.e. we have `Customer` & `Transaction` classes as part of our EntityFramework model. However for obvious reasons both business & technical. Our existing REST service does not send those back to the client. So we have separate `Customer` & `Transaction` in a namespace called DTO. (we have a dozen more classes like that)

This works great in C# we just use the qualified names.

We also have functions and expressions right in the EF classes for returning the DTOs. So as _HotChocolate_ is scanning the model it ends up with two types named `Customer` tec. This causes an error to be thrown.

**Comment by michaelstaib** [comment]
You can override the default naming convention to build up very long names... They just have to conform to the GraphQL naming definition .... meaning no `.` and so on .... 

http://spec.graphql.org/June2018/#sec-Names

**Comment by jewpaltz** [comment]
You can override the default the default naming on a Type by Type basis. (that may very well be the workaround that we will opt for until this is implemented).
However, things would be much simpler and scalable. If we could just have a setting on the `AddType<>()` method that scans the model. That would name all types by their fully qualified name instead of their local name.
What you have basically answered is that "There is no way to do that in Pure code first. Therefore in this case you should switch over to (or augment) the fluent api approach"

**Comment by PascalSenn** [comment]
@jewpaltz  
Michael was talking about naming conventions. These work in all approaches.
We have not updated the docs to v11. But i think this should still work. 
https://chillicream.com/docs/hotchocolate/v10/schema/conventions/

**Comment by jewpaltz** [comment]
So you're saying that I can either start a brand new project from scratch. Or rename all of my existing DTOs to fit HT's naming convention. But adding a feature to use fully qualified names, so that we people can incrementally add it to an existing projects with this naming convention, is not an option.

I hear you. Priority and time need to be dedicated to what you think is will help the most amount of people, and not be squandered where there are workarounds.

**Comment by PascalSenn** [comment]
No you can add the naming convention anytime you like.
>DefaultNamingConventions handles how things are named (e.g. lower-camel-case) or where to fetch the description of member.

HotChocolate uses the INamingConvention to name the types. 

just create a new class that extend from DefaultNamingConvetions and then register it in the DI or on the schema builder with
```csharp
services.AddGraphQL()
    .AddConvention<INamingConvention, YourCustomNamingConvention>()
```

**Comment by jewpaltz** [comment]
Awesome. No, sorry. I hadn't seen that link. I will look into it.
