### ISSUE TITLE
GeoJson Point has inconsistent input and output types

### ISSUE THREAD

**Issue by bram209** [ChilliCream/hotchocolate#2826]
**Describe the bug**
The input type of a GeoJsonPoint is inconsistent with it's output type:

[GeoJson Point spec](https://tools.ietf.org/html/rfc7946#section-3.1.2)
```
3.1.2.  Point

   For type "Point", the "coordinates" member is a single position.
```
[Spatial/src/Types/GeoJsonPointType.cs#L17](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Spatial/src/Types/GeoJsonPointType.cs#L17)
```csharp
            descriptor
                .Field(x => x.Coordinates)
                .Description(GeoJson_Field_Coordinates_Description_Point);
```
[NetTopologySuite/Geometries/Point.cs#L77](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Geometries/Point.cs#L77)
```csharp
        public override Coordinate[] Coordinates => IsEmpty ? new Coordinate[] { } : new Coordinate[] { this.Coordinate };
```

**Comment by steveoh** [comment]
Input types are not meant to be geojson as json isn't really a graphql input but I am curious to see what Pascals opinion is

**Comment by steveoh** [comment]
Or is the issue the plurality of coordinates? You might explain yourself and why you posted those links so we don't have to infer and assume
