### ISSUE TITLE
Please add support for GraphQL Voyager

### ISSUE THREAD

**Issue by dhirschfeld** [ChilliCream/hotchocolate#2839]
There was a pervious integration with GraphQL voyager:
https://www.nuget.org/packages/HotChocolate.AspNetCore.Voyager/

...but apparently that has been deprecated in favour of adding the functionality to BCP:
![image](https://user-images.githubusercontent.com/881019/103986435-7011d480-51d6-11eb-8b5e-ba886eda57dd.png)

If it's not too much of a maintenance burden I'd like to request that GraphQL Voyager support be brought back, at least until such functionality is built-in to BCP.

As it is, BCP seems a good replacement for [GraphiQL](https://github.com/graphql/graphiql) but IIUC it doesn't have ***interactive graph visualization/exploration*** capabilities comparable to Voyager:

![image](https://user-images.githubusercontent.com/881019/103986541-a94a4480-51d6-11eb-83a8-3a15b973d7a1.png)

I think there's huge value in being able to ***visualize*** your schema and so I'd like support for Voyager to be kept until BCP has equivalent functionality

**Comment by michaelstaib** [comment]
We are working on building this into BCP at the moment. But Voyager is just a piece of JavaScript so you easily can add that to your project. We will not bring it back just to deprecate it again :)
