### ISSUE TITLE
Persisted Queries Not Working 

### ISSUE THREAD

**Issue by clausthalVK** [ChilliCream/hotchocolate#2841]
I have updated the server to version 11 and since then persisted queries are not working all the time ack  message is "The query request contains no document." event though documents exist

**Comment by PascalSenn** [comment]
could you provide some more context? 
Without repro it is difficult to see what went wrong

**Comment by michaelstaib** [comment]
This will be solved with 10.0.8 ... I will link the original issue.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/issues/2759

I will close this issue and we are tracking this on 2759

**Comment by michaelstaib** [comment]
This issue is now implemented. We also released with it the new docs for this feature.

https://chillicream.com/docs/hotchocolate/performance/
https://chillicream.com/docs/hotchocolate/performance/automatic-persisted-queries/

The current release is 11.0.8-rc.9
