### ISSUE TITLE
How to modify argument values in a middleware?

### ISSUE THREAD

**Issue by araxemy** [ChilliCream/hotchocolate#2843]
Hi there!
I have a couple of input object types that contain a number of properties, some of which are strings. These input object types are used as arguments for my mutation methods.

I want to be able to apply some transformations to some of these properties before they are passed to the mutation method.
For instance, say I want to Trim() all the string properties, ToLower() them, and all the boring stuff so that the mutation method won't have to worry about any of it.

I've created custom attributes like [Trim], [ToLower] which I'm decorating those properties with.

My initial idea was to have a middleware and in it, look for the arguments that are of an input object type, examine properties within them that are decorated with my custom attributes, and then apply the appropriate transformation on each individual property.

But I couldn't figure out how I can modify input arguments within a middleware? Is that possible in HC?

Thanks in advance.

**Comment by AradAral** [comment]
I'm not sure if changing argument values in middleware is supported in Hot Chocolate, but you can also use something like PostSharp for that purpose (Doing transformations on properties before them being set)

**Comment by PascalSenn** [comment]
A middleware cannot not change the value of a input argument. 
But i guess this could be  the thing you are looking for:
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/test/Types.Tests/Types/InputValueFormatterTests.cs#L103-L105

**Comment by araxemy** [comment]
@PascalSenn Hi, thanks for the response.
Yeah, that seems to be a good fit actually.
But what are these "formatters" exactly?! They aren't explained in the docs apparently, right?

**Comment by PascalSenn** [comment]
@araxemy yes they are new in v11 :) 
there are a few of these fancy things that do not have documentation yet

**Comment by araxemy** [comment]
@PascalSenn Yeah, they're pretty cool!
Thank you for introducing them, also looking forward to seeing them documented so we could learn more about them.
Thanks!
