### ISSUE TITLE
Validation messages localization

### ISSUE THREAD

**Issue by leonardoporro** [ChilliCream/hotchocolate#2844]
Hello!
I need to localize validation errors. Error contains the validated field, but not the validator name (and arguments?)

Is it possible to add the validation type to the error extensions?
e.g.:
 ...
      ],
      "extensions": {
        "field": "password",
        "validation": "required", // < add this?
        "specifiedBy": "http://spec.graphql.org/June2018/#sec-Input-Object-Required-Fields"
      }
    }

I tried to intercept the error and patch it, by looking for the "required" word in the message, or something, but error filter
does not work for validations.
Error helper and resources seem to be static, and internal.

Am I missing something?

**Comment by damikun** [comment]
You can allso check @benmccallum solution for input validation... https://github.com/benmccallum/fairybread

**Comment by leonardoporro** [comment]
Made a version of middleware for data annotations using this: [ValidateInputMiddleware](https://compiledexperience.com/blog/posts/graphql-validate-arguments).
It works for all validators except [Required] that happens before the middleware.

I think that maybe ErrorHelper can be made a singleton or injected, or at least, a validation type can be added as an extension:

`  public static IError FieldIsRequiredButNull(
            this IDocumentValidatorContext context,
            ISyntaxNode node,
            string fieldName)
        {
            return ErrorBuilder.New()
                .SetMessage(Resources.ErrorHelper_FieldIsRequiredButNull, fieldName)
                .AddLocation(node)
                .SetPath(context.CreateErrorPath())
                .SetExtension("field", fieldName)
                .SetExtension("validator", "required") // inform what validation is being performed, for localization purposes!
                .SpecifiedBy("sec-Input-Object-Required-Fields")
                 .Build();
        }`

**Comment by PascalSenn** [comment]
To localize these error messages we will add error codes but have to wait for this one to be official:
https://github.com/graphql/graphql-spec/issues/708

**Comment by michaelstaib** [comment]
@PascalSenn we already use error codes ... our error codes are located in the extensions section.

**Comment by michaelstaib** [comment]
The plan is to introduce more error hot chocolate error codes of the next few releases ....

**Comment by PascalSenn** [comment]
Closed as this is a ongoing improvement
