### ISSUE TITLE
StrawBerry Shake non-optional parameter checking does not occur at compile-time

### ISSUE THREAD

**Issue by sangelastro** [ChilliCream/hotchocolate#2852]
**Is your feature request related to a problem? Please describe.**
All generated proxy methods parameters by StrawBerry Shake, seem to be wrapped by an `Optional` type, even though I set a parameter with the `!` notation to make it non-optional. 
If I have the following query:
``` 
query myQuery(par: String!) {
    ... 
}
```
someone could call the generated method without `par` as well.
``` c#
client.myQueryAsync() 
```
I figured out that the parameter checking is meant to occur at run-time (server-side).
So, I'd like to avoid that.

**Describe the solution you'd like**
Wouldn't be better using the c# built-in argument specifics to check the parameters non-optionality?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
- Strawberry Shake: 11.0.0-preview.137

**Comment by michaelstaib** [comment]
This will be fixed with the next preview release end of this month ....

**Comment by sangelastro** [comment]
ok, thanks! :)

**Comment by michaelstaib** [comment]
This is now fixed.
