### ISSUE TITLE
Default paging behavior on v11 is problematic

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#2863]
**Is your feature request related to a problem? Please describe.**
After upgrading from v10 to v11, default pagination behavior has changed to enforce a default dataset size of 10 and a default max size of 50.

The issues are:
- This restriction is not communicated to clients in any way, changes to max/allowable sizes do not change the SDL.
- Error messages when max is exceeded do not indicate the max allowed value
- (debatable) If max is exceeded, no results are returned.

**Describe the solution you'd like**
1. I think the error message should be similar to GitHub where it clearly indicates the correct max value
2. (debatable) I think, if there are max enforced values, we should consider making clients specify them (e.g. either `first` or `last`  is required). This way clients aren't surprised by what's returned. Or at-least have an opt-in to this behavior.
3. (debatable) I think _some_ results should still be returned by default to avoid making changes to the max page size breaking for clients (either return default or return max size). Maybe make this a user-defined behavior.
4. (debatable) If max/default are supported by HotChocolate by default, I think it might be helpful to incorporate those into SDL comments. This allows for a diff of the SDL to at least show a change in comments when these values change.

**Describe alternatives you've considered**

**Additional context**
Based on [this thread](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1610387141388400) on slack

**Comment by tobias-tengler** [comment]
@michaelstaib I remember you did a change for v12 that includes the default paging arguments in the SDL. Did you also include the maximum number of elements in the error message, if the maximum is exceeded?
If so, this issue can be closed.

**Comment by michaelstaib** [comment]
- [ ] Allow Connection to be named
- [ ] Allow nodes field to be named
- [ ] Allow to require first or last
