### ISSUE TITLE
TotalCount Not Included

### ISSUE THREAD

**Issue by prashantjustp** [ChilliCream/hotchocolate#2866]
**Describe the bug**
I have migrated my project from Hotchocolate 10.5.2 to 11 and .Net core 3.1 to .Net 5 and I added the Include TotalCount options but it still doesnt appear in edges
I have done this in startup.cs
```csharp
 services
                .AddGraphQLServer()
                .AddQueryType<Query>()
                .AddType<JobQuery>()
                .AddMutationType<Mutation>()
                .AddType<JobsMutation>()
                .AddAuthorization()
                .BindRuntimeType<DateTime, DateTimeType>()
                .BindRuntimeType<int, IntType>()
                .BindRuntimeType<string, StringType>()
                .BindRuntimeType<bool, BooleanType>()
                .BindRuntimeType<long, LongType>()
                .AddProjections()
                .SetPagingOptions(
                new PagingOptions()
                {
                    MaxPageSize = 100,
                    DefaultPageSize = 30,
                    IncludeTotalCount = true
                }
                )
                .ModifyRequestOptions(x => x.TracingPreference = TracingPreference.OnDemand); ;
```
and my query is like
```csharp
        [Authorize]
        [UsePaging(IncludeTotalCount = true)]    
        [UseProjection]
        [HotChocolate.Types.UseFiltering]
        [HotChocolate.Types.UseSorting]
        public IQueryable<JobTable> GetJobs([Service] SomeDBContext _dbContext, [Service] IHttpContextAccessor httpContextAccessor,[Service] ICommonRepository repository)
````

**Comment by michaelstaib** [comment]
Can you please provide a small repro?

**Comment by ch1ffa** [comment]
@michaelstaib I have experienced something similar for the latest v12 RC. TotalCount appears only for the code-first approach and absents while using `[usePaging(IncludeTotalCount = true)]` annotation for a type extension.

**Comment by tobias-tengler** [comment]
> @michaelstaib I have experienced something similar for the latest v12 RC. TotalCount appears only for the code-first approach and absents while using `[UsePaging(IncludeTotalCount = true)]` annotation for a type extension.

Can you please share some code that reproduces the issue?

**Comment by ch1ffa** [comment]
> > @michaelstaib I have experienced something similar for the latest v12 RC. TotalCount appears only for the code-first approach and absents while using `[UsePaging(IncludeTotalCount = true)]` annotation for a type extension.
> 
> Can you please share some code that reproduces the issue?

Ah, it seems in my case I just forgot to change ConnectionName, so the field started using already initialised connection with the same name, which does not include totalCount. Maybe the original issue is somehow connected with my case.

**Comment by tobias-tengler** [comment]
There hasn't been any further clarification of the problem described by the original author so I'm closing this issue.
