### ISSUE TITLE
Output schema as text

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#2876]
I'm looking for something similar to graphql-dotnet's `SchemaPrinter`. Essentialy what it would do is convert the in-memory type system to a text-based schema, e.g.:
```graphql
# Enumeration type for a level of priority
enum Priority {
  LOW
  MEDIUM
  HIGH
}

# Our main todo type
type Todo {
  id: ID!
  name: String!
  description: String
  priority: Priority!
}

type Query {
  # Get one todo item
  todo(id: ID!): Todo
  # Get all todo items
  allTodos: [Todo!]!
}
```

I use HotChocolate in conjunction with React/Relay and would like to be able to print the schema in order to supply it to Relay.

**Comment by michaelstaib** [comment]
that's easy :)

`schema.ToString()`

**Comment by michaelstaib** [comment]
also we have a schema endpoint

Version 10:
http://localhost:5000/graphql/schema

Version 11:
http://localhost:5000/graphql?sdl

**Comment by michaelstaib** [comment]
Also, any syntax node has this capability as well. Kets say you have an `OperationDefinitionNode` and do a `ToString` on it, it will just bring this part of your query.

**Comment by michaelstaib** [comment]
BTW, we personally use relay as well and have set up a little build script that will pull the schema from the schema endpoint with `curl`.

**Comment by michaelstaib** [comment]
https://stackoverflow.com/questions/65717505/how-can-i-print-the-schema-in-hotchocolate-as-graphql-sdl/65717506#65717506
