### ISSUE TITLE
Strawberry Shake cancellation throws a GraphQLException

### ISSUE THREAD

**Issue by aahmadi458** [ChilliCream/hotchocolate#2880]
Hi there. Thanks for all your hard work.
When you pass a cancellation token to the methods of Strawberry Shake's generated client, and the operation is canceled, it throws an exception:
> The operation was canceled. StrawberryShake.GraphQLException: The operation was canceled.

But why? When a cancellation is requested you either do not throw any exceptions at all, or throw an `OperationCanceledException` or something (and not a `GraphQLException`), so that way the client could recognize it and choose to catch it specifically. The way it currently is you have no way of knowing whether the exception thrown by Strawberry Shake is due to task cancellation or something else. Please tell me if I'm missing something.

I'm using Blazor by the way, and I'm trying to [cancel background work](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#cancelable-background-work) when the component is disposed of. This exception causes the Blazor's error toast to pop up, and that's not good.

**Comment by aahmadi458** [comment]
Can you please address this. Thanks.

**Comment by aahmadi458** [comment]
@michaelstaib @PascalSenn Anybody home?!

**Comment by michaelstaib** [comment]
Hi there,

we are working on the next build ... it will take I think another two weeks before we restart preview builds. So, please a little more patience on this.

**Comment by aahmadi458** [comment]
@michaelstaib Okay, but I just want to know whether this particular issue will be addressed in the next build?
Thanks.

**Comment by michaelstaib** [comment]
This should be fixed with the newest preview.
