### ISSUE TITLE
Support for Notifying the GraphQL server about the disconnection of client from subscription.

### ISSUE THREAD

**Issue by Archuna** [ChilliCream/hotchocolate#2892]
Does Hotchocolate Subscriptions support any hook similar to onDisconnect of Apollo-Subscriptions to notify the server that the client is not anymore listening to the channel and has disconnected.

**Comment by Archuna** [comment]
Say there is a chat room where the users are subscribed to a channel. Is Hotchocolate subscription providing an event to indicate that any user is disconnected from the subscription ?

**Comment by PascalSenn** [comment]
What you are looking for is the `ISocketSessionInterceptor`

```csharp
services.AddSingleton<ISocketSessionIntercetpor, AuthenticationSocketInterceptor>();
```

```csharp
public interface ISocketSessionInterceptor
    {
        ValueTask<ConnectionStatus> OnConnectAsync(
            ISocketConnection connection,
            InitializeConnectionMessage message,
            CancellationToken cancellationToken);

        ValueTask OnRequestAsync(
            ISocketConnection connection,
            IQueryRequestBuilder requestBuilder,
            CancellationToken cancellationToken);

        ValueTask OnCloseAsync(
            ISocketConnection connection,
            CancellationToken cancellationToken);
    }
```

**Comment by Archuna** [comment]
Thank You @PascalSenn for the quick reply.
I tried adding  services.AddSingleton<ISocketSessionInterceptor, DefaultSocketSessionInterceptor>();
I also extended the DefaultSocketSessionInterceptor class and redefined the methods.
The methods OnConnectAsync,OnRequestAsync,OnCloseAsync are never called when I start listening to subscription or when I stop.
May I know when these methods will be called. Also tried adding services.AddSocketSessionInterceptor<MyCustomSocketSessionInterceptor>(); to add custom SessionInterceptor class. But the IServiceCollection does not contain any definition of AddSocketSessionInterceptor. May i know in which version does this work. 

Thanks in Advance

**Comment by michaelstaib** [comment]
ISocketSessionInterceptor is a version 11 feature and it is not on the service collection but on the request builder.

`services.AddGraphQLServer()` returns a `IRequestExecutorBuilder`.

`services.AddGraphQLServer().AddSocketSessionInterceptor`

The reason for this is that you can have multiple schemas hosted on on server and this configuration belongs to a specific schema.

`services.AddGraphQLServer().AddQueryType<Query>().AddGraphQLServer("second_schema").AddQueryType<Query2>()` 

For this reason many services are bound to a specific schema using the `IRequestExecutorBuilder`.

Please close this issue if it helped and solved your issue.

**Comment by Archuna** [comment]
Thanks @michaelstaib . 
services.AddGraphQLServer().AddSocketSessionInterceptor is working .
The method OnRequest() and OnConnectAsync() is getting called when listening to subscription. But could not find the call coming to OnCloseAsync() when trying to stop listening to the subscription. Could you help me in this regard.

Thanks in advance.

**Comment by michaelstaib** [comment]
OnCloseAsync will be send if the channel is disrupted or the client sends the close message specified in the protocol.

**Comment by michaelstaib** [comment]
With version 13 we have reworked this further and guarantee no the OnCloseAsync event in any cse.
