### ISSUE TITLE
Subscriptions delegation does not work in 11.0.8

### ISSUE THREAD

**Issue by vyacheslav-mikhaylov** [ChilliCream/hotchocolate#2894]
**Describe the bug**
Subscriptions delegated from a gateway to a service do not work.
On subscribe attempt it says "You must declare a subscribe resolver for subscription fields."

**To Reproduce**
1. Make a service with subscription
2. Make a gateway
3. AddRemoteSchema with ignoreRootTypes: false 
4. Run, try to subscribe.

**Expected behavior**
It should work )

 - Version [11.0.8]

**Comment by PascalSenn** [comment]
Hi there :) 

This feature is not yet supported. It is planned for 11.2 👍

**Comment by michaelstaib** [comment]
I am closing this issue in favor of:
https://github.com/ChilliCream/hotchocolate/issues/562
