### ISSUE TITLE
Merge Rules? / Type Merging

### ISSUE THREAD

**Issue by woeterman94** [ChilliCream/hotchocolate#2898]
https://chillicream.com/docs/hotchocolate/v10/stitching#merge-rules
The documentation here talks about merge rules. "In most cases the default merge rules should be enough. But with more domain knowledge about the source schemas one could write more aggressive merge rules."

Where can I find more info about merge rules? How to write one of my own? 

I'm trying to merge two objects of the same type into one. For example

```
Object A of type something
Prop 1
Prop 2
```

```
Object B of type something
Prop 3
Prop 4
```

Should be stitched / merged into
```
An object of type something with
Prop 1
Prop 2
Prop 3
Prop 4
```

How can I achieve this? 
Edit: an example of what I want to do: https://www.graphql-tools.com/docs/stitch-type-merging/

**Comment by bromix** [comment]
Looking for the same. We have an API with 5 Microservices + Gateway written in node and the help of Graphql-tools. Each microservice provides additional information for the same type and will be merged with a merge resolver in the exact same way as schown above.

**Comment by wullemsb** [comment]
This is something I would like as well. As an example I created 2 services each with their own message type(with the same id but different fields. The stitched API only showed the properties of one of the 2 services. I'm willing to help to create a solution, but I need some hints to get started.

**Comment by michaelstaib** [comment]
We will have more documentation on this with the coming V13 release.
