### ISSUE TITLE
RelayOptions - UseOpaqueCursors

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2899]
**Is your feature request related to a problem? Please describe.**
Just like global ids, cursors would ideally be opaque, as per docs [here](https://relay.dev/docs/en/graphql-server-specification.html#connections).

**Describe the solution you'd like**
* `bool UseOpaqueCursors` setting on `RelayOptions`.
* if true, would set up:
  * serialization of the `cursor` field on a `PageInfo` type, and 
  * deserialization of the `before` and `after` 

It'd also be nice if the `ICursorSerializer` could be swapped out by the developer so they could specify their own (to aid adoption allowing them to do a non-breaking change by keeping all ids the same).

**Describe alternatives you've considered**
It's possible to do this yourself with middleware, but it'd be nicer to be in the framework since it's a common need.

**Comment by michaelstaib** [comment]
how would the interface look like?

**Comment by benmccallum** [comment]
Taking inspiration from IIdSerializer, it could be this. The "Serialize/Deserialize" feels a bit weird though. Particularly given it's string <--> string and I imagine it still will be, unless you wanted to have the Edge have `object Cursor` and then there's always a registered ICursorSerializer, but there's an option to toggle `.ToString()` or `.ToString().ToBase64()`.

Almost could be `IIdEncoder` or `IIdMasker`, but probably doesn't matter too much either way. 

I'm mostly interested in this as I know our FE have a couple of global ids in their JS for icon maps or something, so with this abstraction I could swap in my exact base64 implementation (or fallback onto HC's built-in if it turns out to be the same) without having a breaking release. But it also lets people use whatever serialization/encoding they want, if they wanna make it opaque some other way, use some future faster encoding method.

Also OK with not even bothering as I can easily update the FE code AOT to handle both before/after ids and maybe we don't care about making this flexible - it's just on/off base64 encoding, end of story. Up to you :) 

```c#
#nullable enable

namespace HotChocolate.Types.Relay
{
    public interface ICursorSerializer
    {
        /// <summary>
        /// Creates an serialized cursor returned to clients.
        /// </summary>
        /// <param name="cursor">The cursor.</param>
        /// <returns>
        /// Returns a serialized cursor.
        /// </returns>
        /// <exception cref="CursorSerializationException">
        /// Unable to create a serialized cursor string.
        /// </exception>
        string Serialize(string cursor);

        /// <summary>
        /// Deserializes a serialized cursor.
        /// </summary>
        /// <param name="serializedCursor">
        /// The serialized cursor.
        /// </param>
        /// <returns>
        /// Returns the deserialized cursor string.
        /// </returns>
        /// <exception cref="CursorSerializationException">
        /// Unable to deserialize the serialized cursor string.
        /// </exception>
        string Deserialize(string serializedCursor);
    }
}

```
