### ISSUE TITLE
How to sort by parent list by child object?

### ISSUE THREAD

**Issue by afestbaum** [ChilliCream/hotchocolate#2900]
Can someone help me how to sort a parent list by one of its nested child objects. As an example take those two entities:

```
public class Group
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
}

public class Person
{
    public int Id { get; set; }
    [GraphQLIgnore]
    public int GroupId { get; set; }

    [UseSorting]
    public Group Group { get; set; }
    public string UserName { get; set; } = null!;
}
```

And the following Query:
```
query {
  persons {
    id
    userName
    group(order_by: { name: DESC }) {
      id
      name
    }
  }
}
```

As the sorting is only resolved on the lowest level (containing 1 element) and not for the List of Persons, it is useless. How would I be able to express this using Code First and Hot Chocolate 10.5.5?

Thank you in advance
Alex

**Comment by PascalSenn** [comment]
This is not possible on v10 sorting

You can use v11 sorting  for this https://chillicream.com/docs/hotchocolate/fetching-data/sorting/

```graphql
query {
  persons(order: {group: {name: DESC}}}{
    id
    userName
    group  {
      id
      name
    }
  }
}
```
