### ISSUE TITLE
[Banana Cake Pop] Requests are not shown in network tab

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#2903]
When firing a request using the BCP middleware, I cannot see the fired requests in the network tab of the browser.

**Comment by alexandercarls** [comment]
@rstaib What is the current branch where I can start working on? Maybe it makes sense to schedule a meeting for an on boarding session.

The reason we are not seeing the request is, that  the request is made from a SharedWorker.

The shared worker can be inspected from this URL `chrome://inspect/#workers` in a chrome browser - a new developer console starts up.

@fredericbirke 
![image](https://user-images.githubusercontent.com/4022053/105108494-a85cc100-5aba-11eb-9a5a-b005a6a527cd.png)

**Comment by rstaib** [comment]
@alexandercarls at the moment you cannot work on this, because there is a big refactoring ongoing. However we could start working together on the refactoring.
