### ISSUE TITLE
"Unable to create instance of type ``" when adding ObjectType

### ISSUE THREAD

**Issue by nevsnirG** [ChilliCream/hotchocolate#2907]
**Describe the bug**
A HotChocolate.SchemaException is thrown with the following error message whenever I register an object type in my configuration:
```
Unable to create instance of type ``
```

**To Reproduce**
Clone and run the test project:
https://github.com/nevsnirG/HotChocolateObjectTypeIssue

**Expected behavior**
The server starts correctly and the object type can be used for configuration.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: HC 11.0.8

**Comment by michaelstaib** [comment]
We need a better error message when users put an ObjectType in an ObjectType.

**Comment by bram209** [comment]
> We need a better error message when users put an ObjectType in an ObjectType.

Is there a reason why we cannot use generic type constraints to only take a subtype of ObjectType for example?
