### ISSUE TITLE
Features for BanaCakePop (Prettify, Hotkey(s), Voyager)

### ISSUE THREAD

**Issue by smaktacular** [ChilliCream/hotchocolate#2909]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to see BananaCakePop next to the playground and voyager! 😩 
Well, it's not that bad actually, but both tools were really nice and helpful. Voyager alone is awesome! 😍 

**Describe the solution you'd like**
Please bring back the "Prettify Button" and "Ctrl+ Enter to Execute" and Voyager to BananaCakePop

**Comment by michaelstaib** [comment]
Hi @smaktacular,

thank you for your feedback. We are busy busy busy on BCP and we are soon ready to push releases in a bi-weekly cadence. There is a ton of features coming that will make you forget the others :) 

I think four to five more weeks and we will start on our new release cadence on BCP.

**Comment by PascalSenn** [comment]
@smaktacular Sidenote, prettify is already there 🤩  it is hidden in a shortcut, just press F1 and search for Format Document

**Comment by michaelstaib** [comment]
I always forget to mention `F1` haha.

**Comment by smaktacular** [comment]
That sounds very promising! Thanks for the update.
The fact that F1 is essentially the CTRL+P (like VSCode) of BCP :open_mouth: should be pointed out somewhere in the UI, whith HUGE blinking letters 😄

**Comment by michaelstaib** [comment]
@fredericbirke I already talked with Rafi about having a first time BCP screen. Something that is open when you first open it and points to all the things you can do. Kind of like a tour with some arrows pointing to things. We should put something like this on the list.

**Comment by glen-84** [comment]
Could the hotkey for `Insert Line Below` be switched with the one for `Run`, so that we can use Ctrl+Enter to run queries?
