### ISSUE TITLE
`GreenDonut.DataLoaderBase#LoadAsync` should have `Task<TValue?>` as return type instead of `Task<TValue>`

### ISSUE THREAD

**Issue by simon-wacker** [ChilliCream/hotchocolate#2911]
**Describe the bug**
The method [`GreenDonut.DataLoaderBase#LoadAsync`](https://github.com/ChilliCream/hotchocolate/blob/b689f5bcf4d9fbe072c2882d768ad2994cd25b5e/src/GreenDonut/src/Core/DataLoaderBase.cs#L182) may return `null` although its return type suggests that it does not. Note that [the method's non-generic variant](https://github.com/ChilliCream/hotchocolate/blob/b689f5bcf4d9fbe072c2882d768ad2994cd25b5e/src/GreenDonut/src/Core/DataLoaderBase.cs#L76) has the correct `Task<object?>` as return type.

**To Reproduce**
Call the method for example on in instance of a batch data loader whose `LoadBatchAsync` method always returns an empty dictionary. The return value (after executing the task) is `null`.

**Comment by michaelstaib** [comment]
It may return null depending on your implementation. Meaning, if you implement a DataLoader that does not return null then it won't. So, we leave the definition of `TValue` up to the implementor.

**Comment by simon-wacker** [comment]
Then maybe it's an issue with the [`AttendeeByIdDataLoader`](https://github.com/ChilliCream/graphql-workshop/blob/master/code/complete/GraphQL/DataLoader/AttendeeByIdDataLoader.cs) from the [GraphQL workshop](https://github.com/ChilliCream/graphql-workshop/tree/master/code/complete)? When you call `LoadAsync` on an instance of it as in [`AttendeeQueries#GetAttendeeByIdAsync`](https://github.com/ChilliCream/graphql-workshop/blob/c07b36885d7e2a1822171c8a1c2bfad393cf946e/code/complete/GraphQL/Attendees/AttendeeQueries.cs#L22) with a valid but non-existent identifier, then `null` is being returned from `LoadAsync` and the query responds with an `InternalServerError` with the code `EXEC_NON_NULL_VIOLATION`, although all types check. Can't this issue be caught by the type system? Or is the real problem in the implementation of [`AttendeeByIdDataLoader#LoadBatchAsync`](https://github.com/ChilliCream/graphql-workshop/blob/c07b36885d7e2a1822171c8a1c2bfad393cf946e/code/complete/GraphQL/DataLoader/AttendeeByIdDataLoader.cs#L26) which should have one value, either an `Attendee` instance or `null`, in the dictionary for each given identifier (which would force the type `Attendee?`)? Thanks for your great work!

**Comment by michaelstaib** [comment]
Actually, this is then handled correctly by the execution engine. The execution engine is preventing an item to be null where the type system states that it is non nullable.
