### ISSUE TITLE
Can a subscription listen to multiple channels simultaneously?

### ISSUE THREAD

**Issue by Archuna** [ChilliCream/hotchocolate#2914]
Can I use -> await receiver.SubscribeAsync<string, string>(topic); in the same subscription resolver multiple times.
This means a user will be listening to a channel initially and he should also listen to other channels without stopping to listen to the earlier ones. The channel would be changed dynamically within the subscription resolver based on the input of mutation's post. 
Is this possible? I am using redis to store the channel information received from the mutation.

**Comment by michaelstaib** [comment]
Yes, you can use System.Reactive to achieve this.

**Comment by michaelstaib** [comment]
https://github.com/dotnet/reactive

**Comment by michaelstaib** [comment]
Essentially, IAsyncEnumerable can be used by System.Reactivea and you can combine two subscriptions into one message stream. The resulting observable can be used as a event source for Hot Chocolate.
