### ISSUE TITLE
Projected fields in fragments return empty objects.

### ISSUE THREAD

**Issue by Kcola** [ChilliCream/hotchocolate#2918]
**Describe the bug**
#2727 Is now fixed but when querying with fragments the issue persists. (11.0.9-preview.3)

**To Reproduce**
```graphql
{
  books{
    nodes{
      docid
      doc{
        ...Doc
      }
    }
  }
}
fragment Doc on Document{
  title
  publisher{
    pubname
  }
}
```

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.1

**Response**
```json
{
  "data": {
    "books": {
      "nodes": [
        {
          "docid": 1,
          "doc": {
            "title": "Harry Potter and the Half-Blood Prince (Harry Potter  #6)",
            "publisher": {}
          }
        },
      ]
    }
  }
}
```

**Comment by PascalSenn** [comment]
Hi @Kcola  

I try to reproduce this in #2920, but it did work in these test cases. Can you provide a failing test case?

**Comment by Kcola** [comment]
Just created a PR for your branch with the failing test. #2923

**Comment by PascalSenn** [comment]
@Kcola  finally fixed it, it's in review

**Comment by PascalSenn** [comment]
This is now merged and in master
