### ISSUE TITLE
How to apply custom complicated authorization rules on fields

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#2931]
Take a video course platform as an example, which simply sells video courses, in the GraphQL schema of such a system, you have you can find the following 2 types:
```graphql
type Course {
  id: Int!
  title: String!
  lectures: [Lecture]
  # etc.
}
```
```graphql
type Lecture {
  id: Int!
  title: String!
  videoUrl: String!
  course: Course!
  # etc.
}
```

Let's say you want to protect the `videoUrl` field of `Lecture` from users who haven't bought the course that the lecture is associated with.

In other words, only the users who have bought a certain course are authorized to access the `videoUrl` field on its lectures.

How would you suggest performing these kinds of authorizations, which are not uncommon at all, in Hot Chocolate? Assuming you already have a regular ASP.NET Core auth system in place, which uses `ClaimsPrincipal`, `ClaimsIdentity`, etc.

I initially thought I could achieve this by registering a custom field middleware on `videoUrl`, and in it, I query the database and find out whether the current user has bought the course that this lecture belongs to or not. However, within the middleware, although I'd obviously know which user is sending the query request, I couldn't know which lecture(s) is/are being queried and are going to be returned. So, half of the puzzle is missing.

I think it's a somewhat tricky problem. Any ideas? I'd appreciate it if you point me in the right direction here.
Thanks!

**Comment by sergeyshaykhullin** [comment]
### Using your domain
If you want to use database to check if user can get video url, i think you can:
- Do nothing with standard ASP.NET Core authorization flow with claims verification, it is not for that
- Use ASP.NET Core authorization to store all bought video ids to claims and then use field middleware to extract ids and return null url conditionally
- Or use field middleware with AuthorizeDirective. Extract userId from claims, check if it has a bought course using db query

### Subscription model
Also you can use `subscription model` for this service, you can use standard ASP.NET Core authorization with claims:

```cs
# Add policy
services.AddAuthorization(options =>
  options.AddPolicy("subscribers", builder => builder.RequireRole("subscriber")));
  
# Use policy
descriptor.Field(x => x.VideoUrl).Authorize("subscribers");
```

So you have to manage claims roles and give access to all videoUrls (or null with `AUTH_NOT_AUTHENTICATED` auth error)


### Use cleaner domain

The main problem i see it is not a descriptive domain. You can show that user can access videoUrl only if he has a purchased course using schema (Just example, do not use it as is. Some fields and `!` is omitted for readability):

```gql
type Query {
  me: User
  courses: [Course]
}

type User { 
  ...
  purchasedCourses: [PurchasedCourse]
}

type Course {
  ...
  previews: [LecturePreview]
}

type LecturePreview {
  ...
  title: String
  description: String
  #  BUT! Has no video url
}

type PurchasedCourse {
  course: Course
  lectures: [Lecture]
}

type Lecture {
  ...
  preview: LecturePreview
  videoUrl: String
  # stats, rating, video bookmarks, etc
}
```

Usage

```gql
# Query courses (filtering, pagination, etc is ommitted)

{
  courses {
    ...
    previews {
      ...
    }
  }
}

# Query your courses with video url

{
  me {
    purchasedCourses {
      course {
        ...
      }
      lectures {
        preview {
          ...
        }
        videoUrl
      }
    }
  }
}
```

If user is not purchased a course, he has no PurchasedCourse entity, so can't access videoUrl. Try to model your domain with your requirements and only required fields

**Comment by AradAral** [comment]
@sergeyshaykhullin Thank you for sharing your thoughts, Sergey.
> Use ASP.NET Core authorization to store all bought video ids to claims and then use field middleware to extract ids and return null url conditionally

I did give that a try, but I got stuck where I wanted to "use field middleware to extract ids and return null url conditionally", I'm not sure how I get the IDs of the queried `Lecture`s if the client hasn't mentioned the `id` field in the query that they originally sent. I couldn't find a way to "add" a new field to the query in a field middleware. I'd be happy if you can point me in the right direction there.

The second solution you proposed, I'm not quite sure I understand. I guess that way as soon as a user purchases only 1 course, they technically become a subscriber, and then they could access the video URLs of any course lectures. Am I missing something there?

I did think of the third approach you proposed as well (i.e. having both a `PurchasedLecture` and a `PreviewLecture` type), but my initial feeling at least was that it's kind of a clunky workaround, don't you think so? Wouldn't it be more ideal if there was 1 type for each of those entities and different fields just had different access rules? I'm open to it though. I guess that's what I would have to opt-in for if no other solution works.

**Comment by sergeyshaykhullin** [comment]
> I did give that a try
1. `client hasn't mentioned the id field in the query` you can use ...Field().IsProjected() to query field from db anyway to use it in 'auth' resolver
2. You can use field resolver with access checks (Attention! Preudo code)
```cs
despriptor.Field(x => x.VideoUrl).Resolve(context =>
{
  var userId = context.Service<...>().GetUserIdOrHttpContextOrWhateverToAccessAspNetCoreAuthClaims();
  var lecture = context.Parent<Lecture>();
  
  var canAccessVideoUrl = db.Courses(x => ...Check user id purchased this course using lecture...).Any();
  
  return canAccessVideoUrl ? lecture.VideoUrl : null;
  
});
```
3. You can use field middleware to check and modify lectures properties after executed resolver (Just an algorithm)
```
Start Query
Some HC magic
Resolver returns lectures
Middleware foreach context.Resuls and set null to VideoUrl for all non-purchased course lectures
```

> The second solution you proposed
The user purchases not a course, but a subscription. For a month, a year, etc., like Pluralsight. This is definitely a different business model and most likely it should not be decided by the developer

> I did think of the third approach
The third approach is to use something like a domain driven design/rich domain models. I think if there is no understanding and experience of using it, then it is better not to choose it

**Comment by sergeyshaykhullin** [comment]
This is middleware approach

```cs
public class LectureDbContext : DbContext
{
	public LectureDbContext(DbContextOptions<LectureDbContext> options)
		: base(options)
	{
	}

	public DbSet<Lecture> Lectures { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Lecture>()
			.HasData(new List<Lecture>
			{
				new()
				{
					Id = 1,
					VideoUrl = "https://video.url/1"
				},
				new()
				{
					Id = 2,
					VideoUrl = "https://video.url/2"
				},
				new()
				{
					Id = 3,
					VideoUrl = "https://video.url/3"
				},
				new()
				{
					Id = 4,
					VideoUrl = "https://video.url/4"
				}
			});
	}
}

public class Lecture
{
	public int Id { get; set; }
	public string VideoUrl { get; set; }
}

public class Query
{
	public IQueryable<Lecture> Lectures([ScopedService] LectureDbContext dbContext)
	{
		return dbContext.Lectures;
	}
}

public static class ObjectFieldDescriptorExtensions
{
	public static IObjectFieldDescriptor UseLectureVideoUrlRestrictions(this IObjectFieldDescriptor descriptor)
	{
		return descriptor.Use(next =>
		{
			return async context =>
			{
				await next(context);

				// TODO: Get user id from claims
				var userId = context.Service<IHttpContextAccessor>().HttpContext.Request.Query["userId"];
				var lectures = (IQueryable<Lecture>)context.Result;

				context.Result = lectures.Select(lecture => new Lecture
				{
					Id = lecture.Id,
					// TODO: Check user purchased a course
					VideoUrl = userId == "NoAccess" ? null : lecture.VideoUrl
				});
			};
		});
	}
}

public class QueryType : ObjectType<Query>
{
	protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
	{
		descriptor.Field(x => x.Lectures(default!))
			.UseDbContext<LectureDbContext>()
			.UseLectureVideoUrlRestrictions();
	}
}

public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddHttpContextAccessor();

		services.AddPooledDbContextFactory<LectureDbContext>(builder => builder.UseSqlite("Data Source=lectures.db"));

		services.AddGraphQLServer()
			.AddQueryType<QueryType>();
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		app.UseRouting();

		app.UseEndpoints(endpoints =>
		{
			endpoints.MapGraphQL();
		});
	}
}
```

Try to query `https://localhost:5001/graphql` and `https://localhost:5001/graphql?userId=NoAccess` endpoints

**Next steps**
You can generalize this approach, pass expressions to extension and [expand](https://github.com/scottksmith95/LINQKit#plugging-expressions-into-entitysets--entitycollections-the-solution) them

**Comment by sergeyshaykhullin** [comment]
This is resolver approach with N+1 problem:

```cs
public class LectureDbContext : DbContext
{
	public LectureDbContext(DbContextOptions<LectureDbContext> options)
		: base(options)
	{
	}

	public DbSet<Lecture> Lectures { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Lecture>()
			.HasData(new List<Lecture>
			{
				new()
				{
					Id = 1,
					VideoUrl = "https://video.url/1"
				},
				new()
				{
					Id = 2,
					VideoUrl = "https://video.url/2"
				},
				new()
				{
					Id = 3,
					VideoUrl = "https://video.url/3"
				},
				new()
				{
					Id = 4,
					VideoUrl = "https://video.url/4"
				}
			});
	}
}

public class Lecture
{
	public int Id { get; set; }
	public string VideoUrl { get; set; }
}

public class LectureType : ObjectType<Lecture>
{
	protected override void Configure(IObjectTypeDescriptor<Lecture> descriptor)
	{
		descriptor.Field(x => x.Id);
		descriptor.Field(x => x.VideoUrl)
			.Resolve(context =>
			{
				// TODO: Use dataloaders to solve N+1
				
				// TODO: Get user id from claims
				var userId = context.Service<IHttpContextAccessor>().HttpContext.Request.Query["userId"];
				var lecture = context.Parent<Lecture>();

				// TODO: Check user purchased a course
				return userId == "NoAccess" ? null : lecture.VideoUrl;
			});
	}
}

public class Query
{
	public IQueryable<Lecture> Lectures([ScopedService] LectureDbContext dbContext)
	{
		return dbContext.Lectures;
	}
}

public class QueryType : ObjectType<Query>
{
	protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
	{
		descriptor.Field(x => x.Lectures(default!))
			.UseDbContext<LectureDbContext>()
			.Type<ListType<LectureType>>();
	}
}

public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddHttpContextAccessor();

		services.AddPooledDbContextFactory<LectureDbContext>(builder => builder.UseSqlite("Data Source=lectures.db"));

		services.AddGraphQLServer()
			.ModifyRequestOptions(options => options.IncludeExceptionDetails = true)
			.AddQueryType<QueryType>();
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		app.UseRouting();

		app.UseEndpoints(endpoints =>
		{
			endpoints.MapGraphQL();
		});
	}
}
```

**Comment by AradAral** [comment]
@sergeyshaykhullin 

> you can use ...Field().IsProjected() to query field from db anyway to use it in 'auth' resolver

Oh! I didn't know about the `IsProjected()` method. Thanks a lot! It basically solves the problem I was stuck on.

Thanks for clarifying the second solution. Yes, that would be an entirely different business model.

Thank you so much for the code examples as well, it really helps, I truly appreciate it.

I'm now playing with all of this, I need a bit of time to wrap my head around all of it. I'll let you know.

Thanks, again!

**Comment by michaelstaib** [comment]
Can this be closed?

**Comment by VarunSaiTeja** [comment]
```
        public IQueryable<Device> GetDevices([Service] AppDbContext dbContext)
        {
            //How to retrive user claims here
            //Incase of controllers we use User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value
            var userid = 0;
            return dbContext.Devices.Where(x=>x.UserId == userid);
        }
```
How to retrieve claims in the above code?

**Comment by sergeyshaykhullin** [comment]
@VarunSaiTeja Controllers has ClaimsPrinciple User from ControllerContext, because MVC is http specific and it cares about HttpContext

GraphQL is transport agnostic and you have nothing about http to access User property

If you are using gql with http transport you just need to acces HttpContext inside resolver to access ClaimsPrinciple

In examples above i showed how you can access ClaimsPrinciple, please follow one of example

**Comment by AradAral** [comment]
@VarunSaiTeja
You could register `IHttpContextAccessor` in your DI container, like this:
```csharp
services.AddHttpContextAccessor();
```

You could receive it as a service in your resolver, like:
```csharp
public IQueryable<Device> GetDevices([Service] AppDbContext dbContext, [Service] IHttpContextAccessor accessor)
{
     // Now you could access the User property:
     accessor.HttpContext.User
}
```
