### ISSUE TITLE
PagingOptions.IncludeTotalCount=false still triggers SELECT COUNT(*) on the database

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#2934]
I've set up `PagingOptions.IncludeTotalCount=false` on my API, as I wanted to get rid of the `SELECT COUNT(*)` queries that in my cases sometimes takes longer than actually query to run. However in my log files I still see that they are being generated and called.

I wanted to ask if that's expected behavior? Seems to me like the only thing this flag does is to hide the `totalCount` field from being returned to the clients but the logic behind this field is still executed.

**Comment by michaelstaib** [comment]
I think the default implementation for queryable still does this. We could probably get rid if this by overfetching the result by one item.

**Comment by sergeyshaykhullin** [comment]
Yes, this should handle `IncludeTotalCount == null or false`

https://github.com/ChilliCream/hotchocolate/blob/0a65a1fb30a9e4c902680efd65b7a950ebe94915/src/HotChocolate/Core/src/Types.CursorPagination/QueryableCursorPagingHandler.cs#L37

**Comment by traciborski** [comment]
What is status of that issue?

**Comment by michaelstaib** [comment]
@traciborski I think it is fixed. But not sure if everything is merged yet. I pinged @PascalSenn who worked on this.

**Comment by PascalSenn** [comment]
@traciborski  this will be fixed with #3878 and go to 12 
The new helpers that are used in v12 are also in the latest 11 version, but not wired up as this would be a breaking change. 
you could wire them up in v11 manually or you wait for the change in 12
