### ISSUE TITLE
Filter shows also ignored fields

### ISSUE THREAD

**Issue by matnar** [ChilliCream/hotchocolate#2935]
**Describe the bug**
When HotChocolate generates the object filters for the domain object, it includes also the possibility to filter on fields marked as Ignored.

**To Reproduce**
1. Create a domain object with a field. 
2. Create the object type by extending the ObjectType<T> class
3. Configure the object type to ignore the field by overriding the Configure(IObjectTypeDescriptor<T> descriptor) method
3. Create a new query to return an enumeration of the class objects
4. Decorate the query returing the mapped object type with the [UseFiltering] attribute
5. Navigate the filter properties (eg. using GraphiQL)

**Expected behavior**
The filter should not include the ignored fields 

We are using the latest version of HotChocolate 11.1.0-preview.8

**Comment by PascalSenn** [comment]
With the Code First approach you need to create `FilterInputType<T>` to ignore properties

https://chillicream.com/docs/hotchocolate/fetching-data/filtering/#customization

**Comment by matnar** [comment]
Thanks for your reply @PascalSenn . 

I'm just trying to use a FilterInputType<T>, however if I apply it on all methods requiring filtering, I receive a `HotChocolate.SchemaException`:  `The name '...' was already registered by another type.`. 

I checked my code and I'm not deliberately registering filters multiple times. 
So, I guess HotChocolate does it behind the scene (which is fine). 
How can I investigate who is registering the filter multiple times? 
The error message does not provide information on that (as far as I understood)

**Comment by PascalSenn** [comment]
Can you share some code?

**Comment by PascalSenn** [comment]
As there was not much activity on this issue I am gonna close it.
In case you still see this problem feel free to open a issue with a reproduction :)
