### ISSUE TITLE
This docs page (found searching google) pops up and then promptly disappears

### ISSUE THREAD

**Issue by pkellner** [ChilliCream/hotchocolate#2944]
**Describe the bug**
Tried this on my macbook OSX 11.1 on chrome and safari.
https://chillicream.com/docs/hotchocolate/v10/data-fetching/pagination
Both places, page appears briefly, then screen clears.

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by PascalSenn** [comment]
Thanks for report @pkellner  :) 

Meanwhile you can find this under:
https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/v10/data-fetching/pagination.md

We track this bug in #2941
