### ISSUE TITLE
Nuget Package Description Missing

### ISSUE THREAD

**Issue by bradhoov** [ChilliCream/hotchocolate#2945]
**Describe the bug**
The Nuget package description for several projects is missing
![image](https://user-images.githubusercontent.com/4921635/105892087-5d253f80-5fdf-11eb-98a4-31a039c72fef.png)

**To Reproduce**
See included image

**Expected behavior**
Expected concise description of the package

**Comment by michaelstaib** [comment]
Thanks for reporting this.

**Comment by michaelstaib** [comment]
@PascalSenn can you add these to the data package?
