### ISSUE TITLE
IEnumerable is not supported for ErrorBuilder's extensions 

### ISSUE THREAD

**Issue by shoe-diamente** [ChilliCream/hotchocolate#2947]
**Describe the bug**
When using the `ErrorBuilder`, `SetExtension` doesn't seem to accept an `IEnumerable<string>` as value.
It used to support that in HC10. In HC11 instead it responds with:

```
{
  "errors":[
    {
      "message":"...",
      "path":[
        "...",
        "..."
      ],
      "extensions":{
        "code":"...",
        "list":"System.Linq.Enumerable\u002BAppendPrepend1Iterator\u00601[System.String]"
      }
    }
  ]
}
```

(see `errors.path.list`).

**To Reproduce**

Run this inside a resolver:

```
                IEnumerable<string> list = new string[]{ "Test1", "Test2" };
                context.ReportError(
                    ErrorBuilder.New()
                        .SetCode("X")
                        .SetMessage("Some message")
                        .SetExtension("list", list)
                        .SetPath(context.Path)
                        .Build());
```

**Expected behavior**

The extension value for `list` is a JSON array.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Version: HotChocolate 11.1.0-preview.8

**Comment by earthslasthope** [comment]
Can we re-open? This is still an issue in v13.
