### ISSUE TITLE
using variables as well as constant inputs in query arguments throws null exceptions

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#2948]
when using variables as well as constant inputs in query arguments the order seems to be important.

this works:
mutation CreateBasicInventory($stringInput: String) {
  createBasicInventory(input: {numberField: 1 stringField: $stringInput }) {
    ...
}

this throws an argument null exception trying to resolve to arguments
mutation CreateBasicInventory($stringInput: String) {
  createBasicInventory(input: {stringField: $stringInput numberField: 1  }) {
    ...
}

**Comment by PascalSenn** [comment]
What version are you on? this was fixed in https://github.com/ChilliCream/hotchocolate/pull/2751 I think
