### ISSUE TITLE
v11 is not working

### ISSUE THREAD

**Issue by thiagomoises** [ChilliCream/hotchocolate#2965]
I am trying to use v11 but it is not working. I thought I was setting it up wrong, until I tried to run the [graphql-workshop](https://github.com/ChilliCream/graphql-workshop) example, but it didn't work here either.

See the print:

![image](https://user-images.githubusercontent.com/34064662/106320680-f78cb980-6251-11eb-9938-96eb79fbec53.png)

Note that the BCP does not connect.

**Comment by PascalSenn** [comment]
what is not working? 
what do you expect to see?

**Comment by michaelstaib** [comment]
Looks OK to me. Have you clicked on the schema button? Book icon .... third icon on the left-hand side?

**Comment by thiagomoises** [comment]
Sorry.... It's work 0/

Tanks
