### ISSUE TITLE
SchemaBuilder.ContextData is not copied to Schema.ContextData

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#2967]
**Describe the bug**
Schema.ContextData is empty even if SetContextData is called

**To Reproduce**
- `services.AddGraphQLServer().SetContextData("a", "b");`
- schema.ContextData["a"]
- Or in middleware -> middlewareContext.ContextData["a"]

**Expected behavior**
`schemaBuilder.Create()` is copying `ContextData` to Schema

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win
 - Version [e.g. 22] 10

**Additional context**
![image](https://user-images.githubusercontent.com/46970457/106385883-81b85780-63e3-11eb-9cae-fe9197f63557.png)

**Comment by michaelstaib** [comment]
That is correct and intended this way.... The schema builder context data are the context data that are used during schema building.

If you want to define schema context data inherit from `Schema` and override `Configure` and then use the descriptor.

Or use a type interceptor / schema interceptor.
