### ISSUE TITLE
Cannot have query with argument of `Name` when using `StrawberryShake`

### ISSUE THREAD

**Issue by rsking** [ChilliCream/hotchocolate#2970]
**Describe the bug**
Compilation of generated code fails when there is an argument of `Name` in a query

**To Reproduce**
1. Create an application that has `StrawberryShake` version `11.0.0-preview.137`
2. Write a query that has an argument of `name`
```graphql
query getUserByName($name: String!) {
	userByName(name: $name) {
		id
	}
}
```
3. Build

**Expected behavior**
Build completes successfully

**Actual behavior**
Build fails as `Name` is defined twice in the generated `GetUserByNameOperation.cs`

**Desktop (please complete the following information):**
 - Windows
 - 10

**Comment by michaelstaib** [comment]
We will release a new build in the next few days that fixes most of the issues with the generator.

**Comment by michaelstaib** [comment]
This one is now fixed.
