### ISSUE TITLE
Enhancements for [ExtendObjectType]

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2991]
**Problem and proposed solution**
Currently `ExtendObjectType` is great for extending one type at a time, but we can make this way cooler for cross-cutting scenarios when you want to extend multiple types with single field resolver implementation. Originally raised on #1298 ages ago but I forgot to create a new issue!

It doesn't look like [ExtendObjectType] has an equivalent for [GraphQLResolverOf(types/typeNames)] (at least on 10.5) as the attribute is restricted to only one usage on a class. Would be cool if we could do this:

```csharp
// Interface enforcing the FK
public interface IHasBooking 
{ 
    [GraphQLIgnore]
    int BookingId { get; } 
}

// Mutations payloads that return a booking field
public class CreateBookingPayload : IHasBooking { ... }
public class EditBookingPayload : IHasBooking { ... }

// A normal type that has a relation to a booking
public class BookingOffer : IHasBooking { ... }

//[ExtendObjectType(Name = nameof(CreateBookingPayload))]
//[ExtendObjectType(Name = nameof(EditBookingPayload))] // second one doesn't work as not allowed by compiler
[ExtendObjectType(typeof(IHasBooking))]
public class HasBookingResolvers
{
    public Task<Booking> GetBooking([Parent] IHasBooking x) 
        => bookingDataLoader.LoadAsync(x.BookingId);
}
```

For the extending of the interface, perhaps more pure for those with C# lang version to support it, would be even to allow default method implementations on the interface to be interpreted as resolver methods, though this may need an opt-in flag as it could be breaking.

```c#
// Interface enforcing the FK and also providing the resolver method / field
[ExtendImplementingTypes] // opt-in all methods
public interface IHasBooking 
{ 
    [GraphQLIgnore]
    int BookingId { get; } 

    [GraphQLField] // opt-in just this method
    [GraphQLIgnore] // opt-out just this method (for when class has ExtendImplementingTypes)
    public Task<Booking> GetBooking([Parent] IHasBooking x) 
        => bookingDataLoader.LoadAsync(x.BookingId);
}
```

Another scenario as raised in #2136 is via a base class, which would also be good to support but base classing isn't always as easy.

So it'd be cool if we could support a few ways of doing this. My wishlist in order of most wanted first would be:
- [ ] Extension by C# interface only with attributes (with resolver implemented as default member)
- [ ] Extension by `[ExtendObjectType(typeof(IHasBooking))]` with interface type (supports cases when interface can't cross-cut)
- [ ] `[ExtendObjectType]` to allow multi usage (supports cases when interface/base can't cross-cut)
- [ ] Extension by `[ExtendObjectType]` with base class (dupes #2136)

In #2136, there's mention of a bool flag to turn on/off propagation, we should consider that further here too.

We may also need to think about the fluent code-first style, e.g. `InterfaceType`.

Finally:
- [ ] `[GraphQLIgnore]` on the interface field should ignore `bookingId` from becoming exposed in the schema on concrete types (currently it doesn't, which could be logged elsewhere).

**Describe alternatives you've considered**
The only alternative right now is to do a `HasBookingResolversBase` with the resolver method and a class per type you want to extend which is painful.

**Additional context**
n/a

**Comment by benmccallum** [comment]
One issue to consider too is when different authorization is required for different implementors.

**Comment by benmccallum** [comment]
Interesting interface default implementation playground... https://dotnetfiddle.net/7eLRMP
You can access the default, but if you call it from the overrided implementation it calls itself infinitely, makes sense.
So you need to abstract the implementation out to a static method.

[MS docs](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions#extend-the-default-implementation).

**Comment by benmccallum** [comment]
Perhaps putting a resolver method on an interface is mixing concerns a little too much. Mixing in HotChocolate/GraphQL stuff into potentially a domain interface. The `[ExtendObjectType]` is preferable most of the time because you can extend right at the last moment when you're in "graph land".

So I'll  think the extension by C# interface only is maybe less of a priority, but an interesting idea :P

**Comment by dzmitry-lahoda** [comment]
you can use recursive generics to depend on type directly instead of interface

**Comment by michaelstaib** [comment]
@dzmitry-lahoda can you open a separate issue for this?

**Comment by michaelstaib** [comment]
We have implemented this a bit differently. We will also add more features to this over time.

Here are some base examples.

Lets say we have the following:

```csharp
public class Session
{
    public int Id { get; set; }
    [Required]
    [StringLength(200)]
    public string? Title { get; set; }
    [StringLength(4000)]
    public string? Abstract { get; set; }
    public DateTimeOffset? StartTime { get; set; }
    public DateTimeOffset? EndTime { get; set; }
    // Bonus points to those who can figure out why this is written this way
    public TimeSpan Duration => 
        EndTime?.Subtract(StartTime ?? EndTime ?? DateTimeOffset.MinValue) ?? 
            TimeSpan.Zero;
    public int? TrackId { get; set; }
    public ICollection<SessionSpeaker> SessionSpeakers { get; set; } = 
        new List<SessionSpeaker>();
    public ICollection<SessionAttendee> SessionAttendees { get; set; } = 
        new List<SessionAttendee>();
    public Track? Track { get; set; }
}
```

Case 1: we want to replace the field TrackId with the actual Track:

```csharp
[ExtendObjectType(typeof(Session))]
public class SessionResolvers
{
    [BindProperty(nameof(Session.TrackId))]
    public async Task<Track?> GetTrackAsync([OriginalProperty] int? trackId) => ....
}
```

Case 2 a: we want to remove a property

```csharp
[ExtendObjectType(typeof(Session), IgnoreProperties = new[] { nameof(Session.TrackId) })]
public class SessionResolvers
{
}
```

Case 2 b: we want to remove a property

```csharp
[ExtendObjectType(typeof(Session))]
public class SessionResolvers
{
    [GraphQLIgnore]
    public Track? Track { get; set; }
}
```

case 3: we want to add a field to multiple types

```csharp
[ExtendObjectType(typeof(object))] <--- everything that inherits or implements this type is extended
public class SessionResolvers
{
    public string Info([Parent] object parent) => "hello";
}
```

case 4: we want to have an extension type that extends depending on the parent argument

```csharp
[ExtendObjectType(typeof(object))] <--- everything that inherits or implements this type is extended
public class SessionResolvers
{
    public string Info([Parent] Session parent) => "hello"; <---- this is added to all types that inherit, implement or are equal to the parent argument type
}
``
