### ISSUE TITLE
Slack invite URL only works for internal mails

### ISSUE THREAD

**Issue by KarlKl** [ChilliCream/hotchocolate#2993]
**Describe the bug**
There are Slack invite URL all over the chillicream Homepage, Docu and GitHub issues. But it doesn't let me in with my non '@chillicream.com' email. :(
I have some questions on how we can get started with Hot Chocolate, but the docu isn't completed yet and the invite links are all "dead".

**To Reproduce**
1. Go to [Docu](https://chillicream.com/docs/hotchocolate/fetching-data/fetching-from-rest/) or main homepage
2. Click on 'Slack Channel' link

**Expected behavior**
Should let me join slack with any mail, or invite links should be removed if this is no longer intended. Alternatively you could also post an email-address where we can get an invite.

**Comment by michaelstaib** [comment]
This link is open to everyone:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q


Which link did you try?

**Comment by KarlKl** [comment]
Hi @michaelstaib, thanks for the fast response.
What I get when I click the link is the following:
![image](https://user-images.githubusercontent.com/8360477/107007800-5216a000-6793-11eb-8a48-1c3853fcc685.png)

**Comment by michaelstaib** [comment]
Somehow slack has changed their rules to that. These links are now only valid for 30 days. 

https://join.slack.com/t/hotchocolategraphql/shared_invite/zt-lqkb8z7b-aFepT0Qrsgv5_yKy0yoyzw
