### ISSUE TITLE
Memory leak when using interface types

### ISSUE THREAD

**Issue by SebastianStehle** [ChilliCream/hotchocolate#3006]
**Describe the bug**
When you create dynamic schemas using the NamedTypeNode (which is afaik the only way to do it) the Interface Type is kept in memory.

**To Reproduce**
Just use my sample: https://github.com/SebastianStehle/dynamic-schemas/tree/main/WebApplication1/TestSchema

There is a dynamically created schema which causes the memory leak. I do not have any references between the objects myself, so I guess and hope I made everything correctly.

![image](https://user-images.githubusercontent.com/1236435/107149220-af5b4e80-6957-11eb-9efb-4ebf070741c9.png)

**Expected behavior**
Should not leak.

You can download the dotMemory workspace here as well:

https://www.dropbox.com/s/k9qt30eog6eftt4/WebApplication1.dmw?dl=0

**Comment by PascalSenn** [comment]
@SebastianStehle  We just merged #3071 the other day. It is likely that this leak was also fixed on the way. Could you do a test with the latest 11.1.0 preview?

**Comment by michaelstaib** [comment]
11.1.0-preview.84

**Comment by tobias-tengler** [comment]
Closing this for now. Feel free to reopen if this is still an issue for you :)
