### ISSUE TITLE
Change return type of query

### ISSUE THREAD

**Issue by rsantosdev** [ChilliCream/hotchocolate#3018]
Hey Guys,

I will try to describe this as best as possible. We have one screen that dynamically applies filters and all the filter options are based on the user selection. For sample when the user selects a type in the first dropdown we use this to filter all the other possible filters.
![image](https://user-images.githubusercontent.com/863056/107421849-3f84c980-6af9-11eb-88cb-c96a83c29477.png)

As of today, we are applying the filters and a node selection logic by hand.
![image](https://user-images.githubusercontent.com/863056/107422244-896daf80-6af9-11eb-9494-5d8bc1871d65.png)

The goal is to move the queries to stop using the class LineItemCustomFilterType and use Filtering 2.0. so our current question is how to apply the UseFiltering middleware in the Iqueryable but capture that to load the fields we need?
Should we use data loaders here? Should we use a custom type with resolvers for each field?

**Comment by twilly86** [comment]
we are looking for a suggestion on how to best implement aggregations prior to them officially being supported.  we'd like to re-use our UseFiltering input from our main query and apply that to the aggregates.  We'd need the query run prior to the "paging" being applied since aggregates would be run on "all" records in query, not just the first page.

**Comment by rsantosdev** [comment]
In summary, what we needed was to run a bunch of aggregations but using the default filtering support. After talking with @michaelstaib on the slack channel, here's our implementation. I hope it helps people that need to use aggregations for now.

1 - Create an ObjectTypeExtension for your query class, this will define the desired returning type and the middleware that will do all the magic. This class will be registered in your schema with ".AddType<LineItemDefaultFilterQueriesType>".
Add the filtering support after the middleware, order is important!
The returning type is different from the class used in the filtering middleware.

```
public class LineItemDefaultFilterQueriesType : ObjectTypeExtension<LineItemDefaultFilterQueries>
    {
        protected override void Configure(IObjectTypeDescriptor<LineItemDefaultFilterQueries> descriptor)
        {
            descriptor.Field("lineItemFilters")
                .Type<LineItemFiltersType>()
                .Use<LineItemDefaultFilterMiddleware>()
                .UseFiltering<LineItem>();
        }
    }
```

2 - Creates a middleware that will have all your logic. Here's a base sample:

```
 public class LineItemDefaultFilterMiddleware
    {
        private readonly FieldDelegate _next;

        public LineItemDefaultFilterMiddleware(FieldDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(IMiddlewareContext context)
        {
            var accountProvider = context.Services.GetRequiredService<IAccountProvider>();
            
            // Let's create a scoped DbContext
            await using var dbContext = context.Services
                        .GetRequiredService<IDbContextFactory<GrowFlowCoreContext>>()
                        .CreateDbContext();

            // Creates the IQueryable to be used for the Filter middleware
            context.Result = dbContext.LineItems.AccountFilter(accountProvider.AccountId.GetValueOrDefault());

            // Invokes the Filter middleware
            await _next(context);

            var filteredQuery = (IQueryable<LineItem>)context.Result;
            var result = new LineItemFilters();

            // Only calulates requested fields
            var fields = context.FieldSelection.SelectionSet.Selections;
            foreach (var selectionNode in fields)
            {
                var field = (FieldNode)selectionNode;
                switch (field.Name.Value)
                {
                    case "priceMax":
                        result.PriceMax = await filteredQuery.MaxAsync(x => (decimal?)x.Price) ?? 0;
                        break;

                    case "priceMin":
                        result.PriceMin = await filteredQuery.MinAsync(x => (decimal?)x.Price) ?? 0;
                        break;
                }
            }

            // Sets the final result back
            context.Result = result;
        }
    }
```

Now you can run your aggregation queries:
```
{
  lineItemFilters(where: {
    transferDate: {
      gt: "2021-01-01"
    }
  }) {
    priceMin
    priceMax
    strains {
      id
      name
    }
  }
}
```
