### ISSUE TITLE
Authorization always returns AUTH_NOT_AUTHENTICATED

### ISSUE THREAD

**Issue by Anton0123** [ChilliCream/hotchocolate#3029]
**Describe the bug**
If you add aspnetcore jwt authorization with the hotchocolate 11 Authorization attribute it will always return unauthorized even if you provide a valid bearer token.

**To Reproduce**
1. Check out the example repository https://github.com/Anton0123/HotchocolateAuthExample
2. Run the project
3. Copy the generated token printed in the console
4. When making a graphql request for "auth", add the http header `"Authorization": "Bearer <token from step 3>"`

**Expected behavior**
"Secret" should be returned.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Version	10.0.18363 Build 18363

**Comment by pasqualirb** [comment]
For now, I circumvented the problem by using **`AddHttpRequestInterceptor()`** extension method to explicitly decode the token and set property `User` of `HttpContext`.

    services
  
        .AddGraphQLServer()
  
        .AddAuthorization()
  
        .AddHttpRequestInterceptor((context, executor, builder, cancellationToken) => {
            try {
                // Decode token
                var authHeader = context.Request.Headers.Single(p => p.Key == "Authorization");
                var token = (new JwtSecurityTokenHandler()).ReadJwtToken(authHeader.Value);
                // Get username and roles
                var username = token.Claims.Single(p => p.Type.Equals("username")).Value;
                var roles = token.Claims.Where(p => p.Type.Equals("role")).Select(p => p.Value).ToArray();
                // Set User identity
                context.User = new GenericPrincipal(new GenericIdentity(username), roles);
            } catch(Exception ex) { }
            return ValueTask.CompletedTask;
        });

For coming up with this solution I had to debug `TryGetAuthenticatedPrincipal()` and `IsInAnyRole()` of [`AuthorizeMiddleware.cs`](https://github.com/ChilliCream/hotchocolate/blob/11.1.0-preview.59/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/AuthorizeMiddleware.cs).

Try/catch is used to prevent triggering an exception when, for example, there is no Authorization header.

**Comment by Anton0123** [comment]
> For now, I circumvented the problem by using **`AddHttpRequestInterceptor()`** extension method to explicitly decode the token and set property `User` of `HttpContext`.
> 
> ```
> services
> 
>     .AddGraphQLServer()
> 
>     .AddAuthorization()
> 
>     .AddHttpRequestInterceptor((context, executor, builder, cancellationToken) => {
>         try {
>             // Decode token
>             var authHeader = context.Request.Headers.Single(p => p.Key == "Authorization");
>             var token = (new JwtSecurityTokenHandler()).ReadJwtToken(authHeader.Value);
>             // Get username and roles
>             var username = token.Claims.Single(p => p.Type.Equals("username")).Value;
>             var roles = token.Claims.Where(p => p.Type.Equals("role")).Select(p => p.Value).ToArray();
>             // Set User identity
>             context.User = new GenericPrincipal(new GenericIdentity(username), roles);
>         } catch(Exception ex) { }
>         return ValueTask.CompletedTask;
>     });
> ```
> 
> For coming up with this solution I had to debug `TryGetAuthenticatedPrincipal()` and `IsInAnyRole()` of [`AuthorizeMiddleware.cs`](https://github.com/ChilliCream/hotchocolate/blob/11.1.0-preview.59/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/AuthorizeMiddleware.cs).
> 
> Try/catch is used to prevent triggering an exception when, for example, there is no Authorization header.

Thank you, it worked!

**Comment by Scott-Selke** [comment]
This is still broken -- stopped my companies migration from 10.5.5 to 11.x. Is there any word on this getting resolved?

**Comment by tobias-tengler** [comment]
I had no issues like this when writing/testing the authentication/authorization docs. Simple JWT Bearer authentication definitely worked for me. I'll whip up an example for you using the latest version of 11.

**Comment by tobias-tengler** [comment]
@Scott-Selke this works as expected when following the documentation. Here's an example: https://gist.github.com/tobias-tengler/4059f1ac929324daeae5f387cc713125
