### ISSUE TITLE
Need a way to inject service in resolver via nested scope

### ISSUE THREAD

**Issue by KerVitarLaeda** [ChilliCream/hotchocolate#3032]
I need some mix of [Service] & [ScopedService] attrubutes. I want to resolve DbContext but from nested IServiceScope.

I have to use [ScopedService] to resolve DbContext to avoid multithread operations with it. Like this:

```
[UseDbContext]
public IQueryable<Company> GetItemsIds(long[] ids, [ScopedService] DbContext db) {
	return db.Set<Company>().AsQueryable().Where(u => ids.Contains(u.Id));
}
```

where [UseDbContext] is

```
public class UseDbContextAttribute : ObjectFieldDescriptorAttribute {
		public override void OnConfigure(IDescriptorContext context, IObjectFieldDescriptor descriptor, MemberInfo member) {
			descriptor.UseDbContext();
		}
	}
```

and descriptor.UseDbContext() is

```
public static class IObjectTypeDescriptorExtensions {
	public static IObjectFieldDescriptor UseDbContext(this IObjectFieldDescriptor descriptor) {
		return descriptor.UseScopedService(serviceProvider => serviceProvider.GetRequiredService<DbFactory>().Create(),
										   (serviceProvider, db) => db.Dispose());
	}
}
```

And everything works nice but in mutation (or maybe another query resolver) I need to resolve another services with dependency on the DbContext.

```
public CompanySavePayload CompanySave(CompanySaveData data,
								  [Service] DbContext db,
								  [Service] CompanyService companyService) {
	Company company;
	using (var transaction = db.BeginTransaction()) {
		company = companyService.Save(data);
		transaction.Commit();
	}
	return new CompanySavePayload(company);
}
```

```
public class CompanyService(DbContext db) {
...
}
```

This code (above) is working but I need single DbContext instance per each resolver to inject it in all services (Is's working). And different instance in another resolver to avoid multithread issues (It's not working).
DbContext & CompanyService are registered as scoped services.

I can do:

```
public CompanySavePayload CompanySave(CompanySaveData data, IResolverContext ctx) {
	using (var serviceScope = ctx.Services.CreateScope()) {
		var serviceProvider = serviceScope.ServiceProvider;
		var db = serviceProvider.GetService<DbContext>();
		var CompanyService = serviceProvider.GetService<CompanyAppService>();
		var SubscriptionService = serviceProvider.GetService<SubscriptionAppService>();
		Company company;
		using (var transaction = db.BeginTransaction()) {
			company = CompanyService.Save(data);
			transaction.Commit();
		}
		return new CompanySavePayload(company);
	}
}
```
But I want to use resolver parameters and dependency injection instead of this ugly code.
I want something like:

```
public CompanySavePayload CompanySave(CompanySaveData data,
									  [ScopedServiceInjection] DbContext db,
									  [ScopedServiceInjection] CompanyService companyService) {
	...
}
```

ScopedServiceInjection attribute shuld:
* get ServiceScope from Scoped Context Data of IResolverContext and create new if there is no one
* resolve requested service
* pass it to parameter of resolver

Everything like [Service] but resolve from local IServiceScope
Right now I can't find a way to write such custom attribute or extend HC's dependency injection system.

PS: Thanks for great library! And sorry for bad english :)

**Comment by PascalSenn** [comment]
Hi there

We will tackle the synchronised access on DB contexts soon! Ones this is implemented you can just use the scoped service

PS: Don't be sorry! Your English is good :)

**Comment by adamhathcock** [comment]
I think I'm running into the same thing.

Our scoped services work fine in standard Http request/response and I expected the same code to behave the same way.  Each request doesn't seem to be scoped to a request container.  What can I do to enforce that?  

I'm willing to contribute and/or extend but I don't know where to look yet.

**Comment by adamhathcock** [comment]
I keep expecting to find some middleware that allows me to scope the `IResolverContext` like above so I don't have to go to each query/mutation to do it.

**Comment by michaelstaib** [comment]
With the current preview of V12 this issue is fixed. We also apart from handling synchronization now allow for scoping services in the pipeline.

**Comment by michaelstaib** [comment]
Resolver can be marked as serial like the following:

```
[Serial]
public async Task<Entity> Foo([Service] MyContext context) => context.Entities.FirstOrDefaultAsync();
```

But it also is possible to scope services now ....

```
.Use(next => async context => 
{
    IServiceProvider original = context.Services;
    using IServiceScope scope = original.CreateScope();
    context.Services = scope.ServiceProvider;
    await next(context);
    // this is important :)
    context.Services = original;
});
```
