### ISSUE TITLE
Private members in .Field property expressions are broken

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#3037]
**Describe the bug**
If property expression is using private methods for resolvers it is broking arguments binding.

If CreateUser is private - input is null, if public - all is working fine

**To Reproduce**
1. Field
```cs
descriptor.Field(x => x.CreateUser(default!))
  .Type<UserType>()
  .Argument("input", arg => arg.Type<CreateUserInputType>());
```

.2 Resolver
```cs
// HERE
private User CreateUser(CreateUserInput input)
{
  return null;
}
```

3. Gql
```gql
mutation {
  createUser(input: {name: "Test"}) {
    id
    name
  }
}
```

**Expected behavior**
Argument binding works with private resolvers

**Additional context**

**Comment by michaelstaib** [comment]
This is deliberatly not supported. We only allow public members.

**Comment by sergeyshaykhullin** [comment]
Should HC throw on private members? For now this unsupported behaviour is working, but skipping arguments

**Comment by michaelstaib** [comment]
It actually should ... I need ti gave a look at this.

**Comment by michaelstaib** [comment]
I am reopening this issue and we will have a look.
