### ISSUE TITLE
AUTH_NOT_AUTHENTICATED Cause 500 Status Code

### ISSUE THREAD

**Issue by rserj** [ChilliCream/hotchocolate#3044]
I'm trying to update GraphQL from version 10 to 11. 
When my Authorization logic fails in 
Microsoft.AspNetCore.Authentication.HandleAuthenticateAsync
GraphQL v10 use to return 200 Status Code with AUTH_NOT_AUTHENTICATED Error, V11 returns the same AUTH_NOT_AUTHENTICATED Error but with 500 Status Code.

I think it might be a bug in DefaultHttpResultSerializer.GetStatusCode(IExecutionResult result)
https://github.com/ChilliCream/hotchocolate/blob/4e4120d726fcc11dbf50b56065105addcde9ffe7/src/HotChocolate/AspNetCore/src/AspNetCore/Serialization/DefaultHttpResultSerializer.cs#L117

By default, it returns InternalServerError.

**Comment by gioxoay** [comment]
Hi, you can override this one as this guide
https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/api-reference/aspnetcore.md

Find keyword MyCustomHttpResultSerializer.

**Comment by itmuckel** [comment]
Sorry for digging this up, but this also broke our web app. A successful request can contain a GraphQL response with errors. A 500 internal server error should be reserved for when a server cannot serve a request.

**Comment by smfeest** [comment]
I've also noticed that the authorization documentation for Hot Chocolate v12 [explicitly states](https://github.com/ChilliCream/hotchocolate/blob/d6cdeeeb82a4650c4cc17ce68c61f76ed3e423ab/website/src/docs/hotchocolate/security/authorization.md?plain=1#L120) that unauthorized requests will receive an HTTP 200 status code response, which suggests that the observed HTTP 500 response code is an unintentional regression

**Comment by smfeest** [comment]
I believe this may be a duplicate of #2513
