### ISSUE TITLE
Need advice on creating query against Azure Search

### ISSUE THREAD

**Issue by ashishmundrajll** [ChilliCream/hotchocolate#3054]
When a client calls our API, we want to query Azure Search Index and return them the results. 

I like to know which is the best way to convert GraphQL queries to Azure Search API calls? i.e. how should we convert a Graph QL Projection and where clause to Azure Search index query? If you can point us to best and easy way to do this, its much appreciated!!

**Comment by PascalSenn** [comment]
How do you query azure serach outside the context of graphql?

**Comment by ashishmundrajll** [comment]
We use this SDK - https://docs.microsoft.com/en-us/azure/search/search-howto-dotnet-sdk to query Azure Search. The where clause required is in OData. The whereclause which we will get in GraphQL will be a different format though. 

So one option is to define a filter like where: filter eq 'ODATA string in azure search format'. The other option will be to navigate the GraphQL AST and convert graphql where clause (like name eq 'ashish' and age > 15) to ODATA format.

Are there other options, which option is best way to do this?
