### ISSUE TITLE
Why the structure of GeoJSONMultiPolygonInput is not equal to the standard structure for MultiPolygon in GeoJSON?

### ISSUE THREAD

**Issue by aleksandrkarpenko** [ChilliCream/hotchocolate#3055]
In HotChocolate structure for GeoJSONMultiPolygonInput for example is:
`
{
	"type": "MultiPolygon",
	"coordinates": [
		[
			[
				0.0,
				0.0
			]
		]
	]
}
`
but in GeoJson it will be
`
{
	"type": "MultiPolygon",
	"coordinates": [                               
		[                                               
			[                                       
				[                               
					0.0,
					0.0
				]
			]
		]
	]
}
`
As you can see GeoJson contains four levels of arrays (array of polygons -> array of exterior and interior (holes) coordinates for polygons -> array of coordinates -> coordinates

**Comment by PascalSenn** [comment]
@steveoh  is this a bug on our side?

**Comment by aleksandrkarpenko** [comment]
> @steveoh is this a bug on our side?

I think yes. We need full compatibility with standard GeoJSON structure to avoid any problems

**Comment by PascalSenn** [comment]
Looking at the spec I see that we may have a problem:

```graphql
 [ [ [ [ 0.0, 0.0 ] ] ] ] 
```

would be 
```graphql
[[[Position]]]
```

and this would not be a valid graphql syntax, it's bad that we didn't see this earlier... 
We obviously have to honour the GeoJson spec, but with the current implementation of the position scalar I  don't think this is possible. 
We probably need to introduce something like `Coordinate` which has an arbitrary depth.

**Comment by steveoh** [comment]
This was fixed and should be closed right?

**Comment by vyacheslav-mikhaylov** [comment]
Guys, if it is fixed what version it is going to?

**Comment by JayChase** [comment]
The same problem exists for **GeoJSONPolygonInput**. The coordinates are a [Position] but to match the GeoJSON spec it should be an array or linear ring arrays [[Position]]  https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6 (I ran into the issue trying to save polygons created with  Bing maps drawing tools).

**Comment by klasrpersson** [comment]
Any information on when this will be looked at?
