### ISSUE TITLE
GUIDs Displaying as a series of Zeros in Query Result

### ISSUE THREAD

**Issue by bluhatsoftware** [ChilliCream/hotchocolate#3056]
**Describe the bug**
The Id properties of my entities are of the .NET primitive Guid type. Now when they are returned from a database query, they're just fine. However, after the entities are bound to the HC ObjectTypes and queried, those Guid fields display as a series of zeros instead of the proper format for GUIDs. 
By the way, in the type definition, I have mapped the GUID field to HotChocolate.Types.UuidType. See code below:

`public class CityType  :  ObjectType<City>`

    {

        protected override void Configure(IObjectTypeDescriptor<City> descriptor)`
        {
            descriptor.Description("Represents the city of business operation under a province/state.");

           descriptor
                .Field(f => f.Id)
                .Type<NonNullType<UuidType>>();

            descriptor
                .Field(f => f.Name)
                .Type<StringType>();

            .....

        }

    }

**Expected behavior**
I expect my Id columns to be displayed in the proper GUID format.

Is this a bug or have I missed something?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Database: SQL Server 2016
HC Package: HotChocolate.AspNetCore 11.0.9

**Comment by bluhatsoftware** [comment]
After a series of tests, it turns out that decorating a query method that returns an IQueryable<T> with the `UseProjectionAttribute` was responsible for that behaviour. I don't know why but that's my observation from testing different scenarios.
I think this should be investigated further.

**Comment by PascalSenn** [comment]
I guess these are two different problems:
1.  The format of the Guid
The Guide are by default formatted as `Guid.ToString('N')`
If you want to have hyphens you have to specify them like this
```
services.AddGraphQLServer()
   ...
   .AddType(new UuidType('D'))
```

2. The value of the guid
The default value of a guid are all zeros. It could be that the projection middleware messes something up. Could you provide a minimal reproduction of the issue on a GitHub repo? or preferably create a PR with a failing unittest :) You could just add it here: https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Data/test/Data.Tests/IntegrationTests.cs

**Comment by ademchenko** [comment]
> After a series of tests, it turns out that decorating a query method that returns an IQueryable with the `UseProjectionAttribute` was responsible for that behaviour. I don't know why but that's my observation from testing different scenarios.
> I think this should be investigated further.

@bluhatsoftware is this the same issue as in  #3182 ?

**Comment by bluhatsoftware** [comment]
> > After a series of tests, it turns out that decorating a query method that returns an IQueryable with the `UseProjectionAttribute` was responsible for that behaviour. I don't know why but that's my observation from testing different scenarios.
> > I think this should be investigated further.
> 
> @bluhatsoftware is this the same issue as in #3182 ?

I think they are both the same issue.

**Comment by ademchenko** [comment]
@PascalSenn could you connect that two issues into a single one?

**Comment by PascalSenn** [comment]
@bluhatsoftware  
Do you also have private `Id` field?

**Comment by bluhatsoftware** [comment]
Indeed I do. In fact, the structure of the classes in the other issue
report is identical to mine where I have private setters for all the
properties and inherit from and Entity class that holds the Guid ID
property for every class that's classified as an entity.

**Comment by PascalSenn** [comment]
Closing this as explained in #3182
