### ISSUE TITLE
Git checkout failing on master branch on windows due to long file names

### ISSUE THREAD

**Issue by arif-hanif** [ChilliCream/hotchocolate#3058]
**Describe the bug**
Git checkout failing of master branch on windows due to long file names

**Desktop (please complete the following information):**
 - Windows 10
 - Master branch v11.1.0

![image](https://user-images.githubusercontent.com/8672758/107955385-b68fe700-6f6b-11eb-9955-910333b2697d.png)

**Comment by rserj** [comment]
I have the same issue, it happens because of Test's long snapshot names

**Comment by michaelstaib** [comment]
Thanks for reporting ... we will have a look at this.

**Comment by PascalSenn** [comment]
This should be fixed
