### ISSUE TITLE
AsSpan logic in IntValueNode may need updated

### ISSUE THREAD

**Issue by wonbyte** [ChilliCream/hotchocolate#3065]
**Describe the bug**
While looking to update the `IntValueNode` to be able to handle `BigInteger` I came across this `if` branch: https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Language/src/Language.SyntaxTree/IntValueNode.cs#L362

If is only operating on `short`, `int`, `long`, however, it's not touching any of the other types like `decimal` or `double` here: https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Language/src/Language.SyntaxTree/IntValueNode.cs#L22

Per the request of @PascalSenn, I am opening an issue.

**To Reproduce**
1. Go to https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Language/src/Language.SyntaxTree/IntValueNode.cs

**Expected behavior**
Confirm if the `if` statement logic is correct or should be updated.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 10.15.7

**Additional context**

**Comment by michaelstaib** [comment]
but only `if (_memory.IsEmpty)` meaning only if the value is in the first place a `Int16`, `Int32` or `Int64`. Since we are talking about integers here the decimal is only a conversion which is cached but not used to convert to span. So the logic looks as intended.

**Comment by wonbyte** [comment]
@michaelstaib makes perfect sense!

**Comment by wonbyte** [comment]
👍
