### ISSUE TITLE
i do not want set only props to be set by chocolate

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ChilliCream/hotchocolate#3069]
```
 Time = new EventTime{Start = x.StartDate, End = x.EndDate},
```

```
    public class EventTime 
    {
        public DateTimeOffset Start { get; init ; }
        public DateTimeOffset End { get; init; }

        public TimeSpan? StartsIn => DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;  
        public TimeSpan? EndsIn => DateTimeOffset.UtcNow > Start && DateTimeOffset.UtcNow < End ? End - DateTimeOffset.UtcNow : null;
    }
```

```
  "bodyText": "{\"StatusCode\":500,\"Detail\":null,\"BodyJson\":\"{\\\"Message\\\":\\\"System.InvalidOperationException: No compatible constructor found for input type type `EventTime`.\\\\r\\\\nEither you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties.There was no way to set the following properties: StartsIn, EndsIn.\\\\r\\\\n   at HotChocolate.Utilities.Serialization.InputObjectConstructorResolver.GetCompatibleConstructor(Type type, IReadOnlyDictionary`2 properties)\\\\r\\\\n   at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)\\\\r\\\\n   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)\\\\r\\\\n   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|32_0(RegisteredType registeredType)\\\\r\\\\n   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)\\\\r\\\\n   
```

**Comment by PascalSenn** [comment]
The problem are the StartsIn and EndsIn properties not the init properties

HotChocolate picks up all properties, these properties would also be in the type itself. If they have no setter we look for a constructor. If there is no constructor we throw. 
A options would be to ignore the properties without and constructor parameter completely

You can work around this issue in multiple ways:
```csharp
    public class EventTime 
    {
        public DateTimeOffset Start { get; init ; }
        public DateTimeOffset End { get; init; }

        public TimeSpan? StartsIn() => DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;  
        public TimeSpan? EndsIn() => DateTimeOffset.UtcNow > Start && DateTimeOffset.UtcNow < End ? End - DateTimeOffset.UtcNow : null;
    }
```
or

```csharp
  public class EventTime 
    {
        public DateTimeOffset Start { get; init ; }
        public DateTimeOffset End { get; init; }
        [GraphQLIgnore]
        public TimeSpan? StartsIn => DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;  
        [GraphQLIgnore]
        public TimeSpan? EndsIn => DateTimeOffset.UtcNow > Start && DateTimeOffset.UtcNow < End ? End - DateTimeOffset.UtcNow : null;
    }
```
or
```csharp
    public class EventTimeInput : InputObjectType< EventTime>
    {
       protected override void Configure(IInputObjectTypeDescriptor< EventTime>) 
       {
           descriptor.Ignore(x => x. StartsIn);
           descriptor.Ignore(x => x. EndsIn);
       } 
    }
```

**Comment by dzmitry-lahoda** [comment]
thanks for workarounds,

current behavior - `if developer will try to set the properties ever let throw exception, even if he will never will do that`. In C# `TimeSpan? get_StartsIn()` is internal impl of property, workaround suggested (on of) is `TimeSpan? StartsIn()`, so there is no difference in workaround and consider readonly props as readonly methods. But yes - if developer will try to `set` readonly method than throw. 

So workarounds will work for me, but I do not see why would graphql try to set readonly methods one case (readonly props) and not in other (read only methods). while dropping an opinion about dev intetion, could just follow formal rule consier read only props as readonly methods (which these actually are)

**Comment by PascalSenn** [comment]
@dzmitry-lahoda 

So the reason why we try to infer the readonly properties is because this is valid and will work:
```csharp
    public class EventTime 
    {
        public EventTime(DateTimeOffset start, DateTimeOffset end) {
            Start = start;
            End = end;
        }
        
        public DateTimeOffset Start { get; }
        public DateTimeOffset End { get; }
    }
```

>readonly methods one case (readonly props) and not in other (read only methods).

This code create properties and not methods: 
```csharp
public TimeSpan? StartsIn => DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;   
 
```
which will compile to
```csharp
public TimeSpan? StartsIn 
    { 
         get { 
               return DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;  
               }
    } 
 
```
where as 
```csharp
public TimeSpan? StartsIn() => DateTimeOffset.UtcNow < Start  ? Start - DateTimeOffset.UtcNow : null;  
     
```
is and stays a method

**Comment by dzmitry-lahoda** [comment]
so i can fix
```
   public class EventTime 
    {
        public EventTime(DateTimeOffset start, DateTimeOffset end) {
            Start = // do the calculation, ignore aregument
            End =  // do the calculation, ignore aregument
        }
        
        public DateTimeOffset Start { get; }
        public DateTimeOffset End { get; }
    }
```

i believe in MSIL
`DateTimeOffset Start { get; }` - is property with private setter
`DateTimeOffset Start =>` the property with no setter at all (only backing field)
but still could be same on of two options
eventually in MSIL, property is get_FooBar method, tagged with custom attribute may be, if I recall correctly, so it is method with get_ prefix.

option could be `if there are props with public setter, neither having constructor with args - than do nothing until i try set the property`. i think behaviour of json serializes could be event more relaxed - ignore issue and allow to debug on json data level.

my propblem is next - i do not want gql to set these, i set them manually, why would it throw?
