### ISSUE TITLE
Why not update playground schema? 

### ISSUE THREAD

**Issue by AAIING** [ChilliCream/hotchocolate#3081]
trying to adding new elements in schema and run the server, dont show the changes aplyied

why dont update schema in the playground?

i found a solution is it change in launchSettings.json

  "applicationUrl": "http://localhost:5002", to  "applicationUrl": "http://localhost:5003"  

increasing by one 

is a solution not trusted

any know this problem?

**Comment by PascalSenn** [comment]
Seems like the schema is cached in the browser.

In playground you can refresh the schema here:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/14233220/108609503-9b3f3480-73ce-11eb-8c24-1211d7921e54.png">

in banacak pop here:
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/14233220/108609521-b5791280-73ce-11eb-9eae-02dc815d1000.png">

**Comment by AAIING** [comment]
Using Insomnia Core to test Graphql server is more confortable, thanks
