### ISSUE TITLE
consider reading FromService attribute data (not attribute -> no dependency of assembly)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ChilliCream/hotchocolate#3083]
*Current:*
```csharp
public await Task<Foo> GetFoo([Service]MyRepo repo) {
  ..
}
```

*Expected:*

ASP.NET FromServiceAttribute also works (so 2 way):
```csharp
public await Task<Foo> GetFoo([FromService]MyRepo repo) {
  ..
}
```

*Why:*
Not sure why [Service] was invented overall, [FromService] tells more  (from) and is know to all ASP.NET devs. So considering attribute data (not attribute) of FromService to work, will make migration for GQL <-> EP back and forth easy.

**Comment by dzmitry-lahoda** [comment]
currently, my code has no revolvers, not attributes from gql, except [Service]. Data loader is fine - its unique concept. I know there are some GQL attributes like GqlDeprecated, not sure if usual Deprecated is supported? I mean keeping old attributes to work will make much value for me.

**Comment by michaelstaib** [comment]
I have added it ... will be in the next preview go 11.1
