### ISSUE TITLE
StraberryShake unlisted from nuget

### ISSUE THREAD

**Issue by VarunSaiTeja** [ChilliCream/hotchocolate#3087]
Seeing this warning  **The owner has unlisted this package. This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore.**

https://www.nuget.org/packages/StrawberryShake/

Which is a relevant tool to use now to generate client side classes?

**Comment by PascalSenn** [comment]
Hi @VarunSaiTeja  

We unlisted the preview because we now have rewritten strawberry shake and do not want new people to start working with this old preview.  You can still use it though.
 The blogpost about it will follow soon.

**Comment by VarunSaiTeja** [comment]
@PascalSenn, @michaelstaib   Please provide the steps to generate client-side classes with the new strawberry shake.
Due to the lack of documentation about the new strawberry shake. My development work is stopped.

**Comment by PascalSenn** [comment]
StrawBerry Shake is in preview, the documentstion will come soon

why is your development work stopped? you can still use 11.0.0-preview.137
