### ISSUE TITLE
Complete API reference

### ISSUE THREAD

**Issue by jkelin** [ChilliCream/hotchocolate#3094]
Hi, I'm new to HC and am currently in the state of amazement of what it can do (especially with automatic `IQueryable` operations). However it is very hard for me find different available attributes, classes and other APIs and what they do as they are scattered across existing documentation.

For example: I have found that the `GraphQLIgnoreAttribute` exists through disassembling, however it's not documented anywhere.

I would love to see (likely autogenerated) API reference with all available options.

I think this would be a boon for people new to the project just finding out what is available, as well as people who know what they are looking for but just can't remember the name of it.

**Comment by michaelstaib** [comment]
Have you tried our workshop project?

https://github.com/ChilliCream/graphql-workshop

also there is a good video tutorial:
https://www.youtube.com/watch?v=HuN94qNwQmM&amp;t=1s

**Comment by jkelin** [comment]
Hi, I did! While they are amazing (they are), they are not an API reference. Hunting through the video or an example project is a completely different experience than https://docs.microsoft.com/en-us/dotnet/api/?view=net-5.0.

This really is about providing API reference as well as the tutorials/guides that you already have. It is the same information, just structured differently and for different purposes.
