### ISSUE TITLE
Pass a Inherited Class as Input Type

### ISSUE THREAD

**Issue by ashishmundrajll** [ChilliCream/hotchocolate#3105]
I defined following class - 

```csharp
public class SearchFilter
{        
    public string FilterName { get; set; }
}
```

Then, I created various Filters inheriting from this - an example is below 

```csharp
[ExtendObjectType(Name = "SearchFilter")]
    public class RangeFilter : SearchFilter
    {
        public AllowedRangeField RangeFieldNameEnum { get; set; }

        public double From { get; set; }

        public double To { get; set; }
    }
```

Then, I defined a Input type which I will use in my Query as below. The idea is that client can pass any type of Filter and combine them with AND/OR clause. My API will then construct a where clause based on what client passes.

```csharp
public class FilterPhrase 
    {
        public List<SearchFilter> Filters { get; set; } = null!;
        public FilterComposerOperator FilterComposerOperatorEnum { get; set;}
    }
```

The Query looks like below - 

`public SearchResults GetAvailability(List<FilterPhrase> filterPhrases) =>`

In Startup.cs in ASP.Net Core project, I added types as below - 

```csharp
services
                .AddGraphQLServer()
                .AddQueryType<Query>()
                    .AddType<SearchFilter>()
                    .AddType<FilterPhrase>()
                    .AddType<RangeFilter>();
```

Question is - 
1. On Banana GraphQL UI, I do not see any 'Filter' Types in Schema.
2. How can I pass RangeFilter to the query? The UI is only taking Parent Class in intellisense and not Child Class RangeFilter?

Thanks,
Ashish

**Comment by michaelstaib** [comment]
`[ExtendObjectType(Name = "SearchFilter")]`

is for extending object types. It translates to:

```graphql
extend type SearchFilter {

}
```

We currently do not allow  splitting input types.

Moreover, the GraphQL spec does not allow for inheritance on inputs.

**Comment by michaelstaib** [comment]
There are patterns to get around this by using a tagged union which is an input that has for each type type case a specific field. There is also a spec effort ongoing to introduce a new input union but it is still far from finalization.
