### ISSUE TITLE
UsePaging on interface type gives an error

### ISSUE THREAD

**Issue by jacobvp** [ChilliCream/hotchocolate#3106]
**Describe the bug**
When I try to use the UsePagingAttribute on an interface (I have tried IList, IEnumerable and Collection I get an error. It does work when I use an implementation like List<T>

**To Reproduce**
1. Create a model with a list reference to a different model
2. Make sure the type is ICollection
3. Add UsePaging as attribute
4. Execute query trying to access the paging
5. See error

**Expected behavior**
The same behaviour as when I use List<T>

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.2.1)
 - HotChocolate Version 11.0.9

**Additional context**
[Slack message](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1613742337118400)

```"message": "Type 'System.Collections.Generic.ICollection`1[HCExampleServer.Data.Models.Session]' does not have a default constructor (Parameter 'type')",
        "stackTrace": "   at System.Linq.Expressions.Expression.New(Type type)\n   at HotChocolate.Data.Projections.Expressions.ProjectionExpressionBuilder.CreateMemberInit(Type type, IEnumerable`1 expressions)\n   at HotChocolate.Data.Projections.Expressions.Handlers.QueryableProjectionFieldHandler.TryHandleLeave(QueryableProjectionContext context, ISelection selection, ISelectionVisitorAction& action)\n   at HotChocolate.Data.Projections.ProjectionVisitor`1.Leave(ISelection selection, TContext context)\n   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(ISelection selection, TContext context)\n   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(ISelection selection, TContext context)\n   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitChildren(IOutputField field, TContext context)\n   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(IOutputField field, TContext context)\n   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(IOutputField field, TContext context)\n   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(TContext context)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<CreateExecutor>g__ExecuteAsync|2_1[TEntityType](FieldDelegate next, IMiddlewareContext context)\n   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context)\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\n--- End of stack trace from previous location ---\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\n--- End of stack trace from previous location ---\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"```

**Comment by PascalSenn** [comment]
Looks like a problem in the QueryableProjectionPagingHandler

**Comment by jacobvp** [comment]
Adding to it:
```[UsePaging(typeof(NonNullType<ObjectType<Session>>), IncludeTotalCount = true)]
public virtual List<Session> Sessions { get; set; } = new List<Session>();
```

Above code doesn't give an error, but it also doesn't show the session belonging to the object:
With paging it gives:
```{
  "data": {
    "tracks": {
      "edges": [
        {
          "node": {
            "id": "VHJhY2sKaTE=",
            "name": "testtrack",
            "sessions": {
              "totalCount": 0,
              "edges": []
            }
          }
        }
      ]
    }
  }
}```

while without paging I get this:
```{
  "data": {
    "tracks": {
      "edges": [
        {
          "node": {
            "id": "VHJhY2sKaTE=",
            "name": "testtrack",
            "sessions": [
              {
                "id": "U2Vzc2lvbgppMQ=="
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by jacobvp** [comment]
After some extra testing what seems to be the problem is that I can't use projection together with paging on a sub-model.
As soon as I remove [UseProjection] from the query **OR** remove paging from the sub-model it starts working again

**Comment by jacobvp** [comment]
Track.cs:
```
[Node(NodeResolverType = typeof(NodeResolvers))]
// ReSharper disable once ClassWithVirtualMembersNeverInherited.Global
public class Track
{
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string? Name { get; set; }
    
    [UsePaging(typeof(NonNullType<ObjectType<Session>>), IncludeTotalCount = true)]
    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}
```

Query with projection, **does not** work:
```
[UseApplicationDbContext]
[UsePaging]    
[UseProjection]
// ReSharper disable once UnusedMember.Global
public IQueryable<Track> GetTracks([ScopedService] ApplicationDbContext context) => 
   context.Tracks.OrderBy(t => t.Name).Include(x => x.Sessions);
```

Query without projection, **does** work:
```   
[UseApplicationDbContext]
[UsePaging]    
// ReSharper disable once UnusedMember.Global
public IQueryable<Track> GetTracks([ScopedService] ApplicationDbContext context) => 
   context.Tracks.OrderBy(t => t.Name).Include(x => x.Sessions);
```

**Comment by TDDinAction** [comment]
> NodeResolvers

Could you share your NodeResolvers class, because I get an error in both cases?

**Comment by jacobvp** [comment]
This is what the class looks like:

```c#
public static class NodeResolvers
{
    // ReSharper disable UnusedMember.Global
    public static async Task<Attendee> GetAttendee([Service] AttendeeByIdDataLoader dataLoader, IResolverContext ctx, int id) => await dataLoader.LoadAsync(id, ctx.RequestAborted);
    public static async Task<Session> GetSession([Service] SessionByIdDataLoader dataLoader, IResolverContext ctx, int id) => await dataLoader.LoadAsync(id, ctx.RequestAborted);
    public static async Task<Speaker> GetSpeaker([Service] SpeakerByIdDataLoader dataLoader, IResolverContext ctx, int id) => await dataLoader.LoadAsync(id, ctx.RequestAborted);
    public static async Task<Track> GetTrack([Service] TrackByIdDataLoader dataLoader, IResolverContext ctx, int id) => await dataLoader.LoadAsync(id, ctx.RequestAborted);
    // ReSharper restore UnusedMember.Global
}
```

**Comment by jacobvp** [comment]
For the database I am using an AWS Aurora Serverless instance (Mysql version: 5.6.10)

**Comment by TDDinAction** [comment]
> This is what the class looks like:

Thanks a lot))

**Comment by michaelstaib** [comment]
@PascalSenn is this an issue for 11.1?

**Comment by jacobvp** [comment]
This error occurs because what it tries to do in ProjectionExpressionBuilder is 
```c#
public static MemberInitExpression CreateMemberInit(Type type, IEnumerable<MemberBinding> expressions)
{
    NewExpression ctor = Expression.New(type);
    return Expression.MemberInit(ctor, expressions);
}```

But the type in this case is ICollection<T>, since this is just an interface it doesn't have any constructor implementation. That is why using a specific type in your model would work (like List<T>). 
I am not sure if this error could be resolved to make it work with interfaces unless the projection middleware is somehow aware of the actual implemented type (In case of EFCore with MySql it seems to be List<T>). After all, how else would it be aware of what implementations are available and which one to pick?

**Comment by Joni-Torrado** [comment]
Hi,

I have the same problem:

**Class:**
```
public class Catalog
{
    public string Name { get; set; }
    [UsePaging] 
    public ICollection<CatalogCategory> CatalogCategory { get; set; }
}

public class CatalogCategory
{
    public string Name { get; set; }
    public string Version { get; set; }
}
```
**Middleware:**
```
[UseDbContext(typeof(CatalogDbContext))]
[UseProjection]
[UseFiltering]
[UseSorting]
public IQueryable<Entities.Catalog> CatalogDB([ScopedService] CatalogDbContext catalogDbContext)
     => catalogDbContext.Catalog.AsNoTracking();
```
**Query:**
```
query GetCatalogWithAllRelated {
  catalogDB {
    id
    catalogCategory{
      nodes{
        catalog{id}
        }
      }
  }
}
```

**Error:**
```
{
  "errors": [
    {
      "message": "Type 'System.Collections.Generic.ICollection`1[ODOC.Catalog.Api.Entities.CatalogCategory]' does not have a default constructor (Parameter 'type')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "catalogDB"
      ]
    }
  ],
  "data": {
    "catalogDB": null
  }
}
```

**Comment by PascalSenn** [comment]
So to clearify this
Projections cannot project pagination. I added a better error message in #3651 .
It would technically be possible to project the relation, but then we could not process `after` and `before`. 
So for this reason we now throw a better error

**Comment by reinux** [comment]
I'm using projections with interfaces. Is this likewise impossible?

If it possible to use EF inheritance instead?
