### ISSUE TITLE
Mutation - Specified method is not supported

### ISSUE THREAD

**Issue by jrcuff** [ChilliCream/hotchocolate#3109]
**Describe the bug**
When calling a mutation that throws an exception, the following is returned: 
```json
[
  {
    "Locations": null,
    "Message": "Unexpected Execution Error",
    "Path": null,
    "Extensions": {
      "message": "Specified method is not supported.",
      "stackTrace": "   at HotChocolate.Execution.Processing.ResultHelper.BuildResult()\n   at HotChocolate.Execution.Processing.MutationExecutor.ExecuteSelectionsAsync(IOperationContext operationContext, IReadOnlyList`1 selections, ResultMap resultMap)\n   at HotChocolate.Execution.Pipeline.OperationExecutionMiddleware.ExecuteQueryOrMutationAsync(IRequestContext context, IBatchDispatcher batchDispatcher, IPreparedOperation operation, OperationContext operationContext)\n   at HotChocolate.Execution.Pipeline.OperationExecutionMiddleware.ExecuteOperationAsync(IRequestContext context, IBatchDispatcher batchDispatcher, IPreparedOperation operation)\n   at HotChocolate.Execution.Pipeline.OperationExecutionMiddleware.InvokeAsync(IRequestContext context, IBatchDispatcher batchDispatcher)\n   at HotChocolate.Execution.Pipeline.OperationVariableCoercionMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)"
    }
  }
]
```

**To Reproduce**
1. Have a mutation defined.
2. In your mutation, throw any exception (`throw new exception("This is an error");`)
3. Call your mutation.
4. See error above.

**Expected behavior**
Have an error that reflects the actual exception.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04.5 LTS

**Additional context**
We hit this issue upgrading from 10.4.3 to 11.0.9. It works fine with 10.4.3.

It's an intermittent problem that only seems to happen on boot. It works after a while (checked an hour or two after) or after multiple calls (7-8). I am actually not even able to replicate it on my dev setup (Ubuntu 20.04.1 LTS), we are hitting the issue in our testing environment which spawns the API then immediately starts sending it calls.

The packages we used:
`<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.9" />`

We also tried:
`<PackageReference Include="HotChocolate.AspNetCore" Version="11.1.0-preview.59" />`

**Comment by michaelstaib** [comment]
The issue is that you have multiple package versions of HotChocolate.

**Comment by michaelstaib** [comment]
Remove all HotChocolate packages apart of
<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.9" />

also any extension packages that might reference an older version.

**Comment by jrcuff** [comment]
The only packages we had were
`<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.9" />`
`<PackageReference Include="HotChocolate.Types.Filters" Version="11.0.9" />`

We then tried to upgrade those to packages to 11.1.0-preview.59 to see if it would get rid of the error. It did not.

We then tried to remove the HotChocolate.Types.Filters package; still have the issue.

So, to summarize, we only have `<PackageReference Include="HotChocolate.AspNetCore" Version="11.0.9" />` installed and the issue persists.

**Comment by michaelstaib** [comment]
Repro:

```csharp
   [ExtendObjectType(Name = "Mutation")]
    public class TestException
    {
        public Task<bool> Test()
        {
            throw new GraphQLException("test");
        }
    }
```

```csharp
    .AddMutationType(_=>_.Name("Mutation"))
    .AddTypeExtension<TestException>()
```
