### ISSUE TITLE
option "ExecutionTimeout" does not work? Queries time outing after 100 sec - does not matter what value is set for "ExecutionTimeout"

### ISSUE THREAD

**Issue by vdrasutis** [ChilliCream/hotchocolate#3110]
**Describe the bug**
Hello.
We having issue that our GraphQL queries is time outing after 100 seconds.
Looks like it ignores "ExecutionTimeout" option.
Previously we used v10, thought upgrade to v11 will help to fix this issue.

Does anyone faced any issue with "ExecutionTimeout" - or for other it is working fine?
Maybe it is some our middleware configuration/order issue?
From configuration maybe you will see what we doing wrong?

Thanks for any help.

**Current version:** <PackageReference Include="HotChocolate.AspNetCore" Version="11.0.9" />
**Project:** .NET Core 3.1 Console App

**Our startup.cs**:

```
public void ConfigureServices(IServiceCollection services)  
{
            services.AddApplication();
            services.AddInfrastructure(Configuration, _logger);            
            services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });

            var defaultTimeoutInMin = 15;
            var timeoutSetting = Configuration.GetSection("Api");
            if (timeoutSetting.Exists())
            {
                defaultTimeoutInMin = timeoutSetting.GetValue<int>("maxTimeoutInMin");
            }

            services.AddGraphQLServer()
                .AddQueryType<Graph.Schema.Types.GraphQl.DashboardQueryType>()
                .AddMutationType<Graph.Schema.Types.GraphQl.MutationType>()
                .AddAuthorization()
                .AddTypes(new[]
                {
                    typeof(Graph.Schema.Types.DataModel.Object1Type),
                    typeof(Graph.Schema.Types.DataModel.Object2Type)
                    //...
                })
                .UseDefaultPipeline()
                .ModifyRequestOptions(opt => opt.ExecutionTimeout = new TimeSpan(0, defaultTimeoutInMin, 0))
                .ModifyOptions(x => x.SortFieldsByName = true)
                .AddConvention<INamingConventions>(new CompatibilityNamingConvention());
                

            //CORS
            services.AddCors();

            services.Configure<RequestLocalizationOptions>(options => { options.SetDefaultCulture("en-US"); });

            // In production, the Angular files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = Path.Combine(AppLocation, "ClientApp", "workspace", "dist");
            });

            services
                .AddMvc()
                .AddNewtonsoftJson(action =>
                {
                    action.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        }
```

**To Reproduce**
Change "defaultTimeoutInMin" property to different value like 1 minute or 15 (as in example).
Then query should timeout after that specified time but it is always time outing after 100 seconds - which is http default time out duration.

**Expected behavior**
When I set "defaultTimeoutInMin" to 15 minutes then query is time outing after specified time.

**Desktop (please complete the following information):**
 - OS: Win 10 x64

**Comment by michaelstaib** [comment]
Are you honoring the cancellation tokens in your code? If not that is the issue. Essentially the timeout is implemented by creating a CancellationTokenSource all resolvers can inject CancellationToken. If these are not correctly passed on and honored the call cannot be aborted.

**Comment by michaelstaib** [comment]
also ... 

services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });

should not be used.

**Comment by vdrasutis** [comment]
Removed: "AllowSynchronousIO = true;" (As other Dev said it was left from v9 - there was some issues which was requiring this option..),
Honored cancelation tokens - **now it works**.

Thanks.

**Comment by vdrasutis** [comment]
Solved.

**Comment by hundreder** [comment]
@michaelstaib 
Can options.AllowSynchronousIO = true; cause some issues? There could be some libs other than gql that might need this option turned on to true.
