### ISSUE TITLE
More information in HC0016 "Variable xyz got an invalid value" errors for complex input types

### ISSUE THREAD

**Issue by petli** [ChilliCream/hotchocolate#3111]
Hot Chocolate v11 doesn't provide very good error feedback when an input variable with a complex input type (nested subobjects, lists etc) gets an invalid value in a query. Currently the error HC0016 only says "Variable `xyz` got an invalid value." without any hint as to where to start looking for the error.

It would be very useful if the error could also reference the errant field, and the path to it from the root of the value.

Currently the only option when facing this error is to test out the same query in GraphiQL (or some other query tool) and see what part of the input value is marked as invalid and figure it out from there, but this doesn't help if the issue is a schema-to-code mapping issue that stops the provided JSON from being mapped successfully.

I may be able to take a look at improving this and providing a PR, if you think it is a viable improvement to the code.

**Comment by michaelstaib** [comment]
Yes, this one is bad :) I am dragging my feet on this one for quite a while. 

I have put it to the backlog for the next release.

**Comment by steveoh** [comment]
yeah this would be a very nice improvement.
