### ISSUE TITLE
AnyType is not Working in Schema Stitching

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/hotchocolate#3113]
I have two projects running in my machine. One is base server another one is Federation server.My base server has the following the Graphql schema which is running in port 4000 and it has no problem at all,working fine as a separate server.

`type Query{
   me(userinfo:Any):Any
}`

Next,Federation server which is running in port 8000,where I am trying to stitch schema of base server using Hotchocolate.Stitching package. while stitching( i.e while loading the federated server schema in playground) I m getting the error saying "  Unable to resolve type reference `Output: Any`. (HotChocolate.Types.ObjectType) " eventhough AnyType is added in federataion server like AddType< AnyType >().

If my base server schema has StringType instead of AnyType like below.,Schema stitching is working without throwing any error,seems like AnyType is problem or Is anything I missed out?

`type Query{
   me(userinfo:String):String
}`

Here is my startup file of Federation Server:
[Startup.txt](https://github.com/ChilliCream/hotchocolate/files/6034600/Startup.txt)

**Comment by Archuna** [comment]
Facing a similar issue for Code First Approach also. Got error saying "Unable to resolve dependencies with Input type:Any". Replacing Any with String type worked fine.  Should we add anything in Startup file of Federation Server to make AnyType work in federation .

**Comment by michaelstaib** [comment]
Fix is coming with 11.1

**Comment by Sangeetha-Murugesan** [comment]
@michaelstaib  when can I expect this bug fix release?

**Comment by ganesh-p** [comment]
Hi,
Is the fix released in latest Preview[11] version. If not any tentative date is appreciated.

**Comment by Sangeetha-Murugesan** [comment]
Hi @PascalSenn  @michaelstaib 

   AnyType is working in latest fix(11.1.0-preview.82).But we are receiving the data as ValueNodes. Data has to be received as 

{
  "data": {
    "station_dtl": [
      {
        "STATION_TYPE": "IA"
      }
	]
   }
}

But the actual data we are receiving is 

{
  "data": {
    "station_dtl": [
    {
        "STATION_CODE": {
          "kind": "StringValue",
          "location": null,
          "value": "IA",
          "block": false
        }
	}
	]
}
