### ISSUE TITLE
The errors in response should have the lowerCamelCase format

### ISSUE THREAD

**Issue by namnm** [ChilliCream/hotchocolate#312]
**Describe the bug**
The errors in response should have the lowerCamelCase format

**To Reproduce**
Just have an error when execute the query, the fields inside errors are formatted as UpperCamelCase:
```json
{
  "errors": [
    {
      "FieldName": "hello",
      "Locations": [
        {
          "Line": 2,
          "Column": 3
        }
      ],
      "Message": "Unexpected execution error."
    }
  ],
  "data": {
    "hello": null
  }
}
```

**Expected behavior**
Should be formatted as lowerCamelCase

**Comment by michaelstaib** [comment]
Hi, I will fix that tonight. Thanks for reporting this one. 👍

**Comment by michaelstaib** [comment]
#313

**Comment by michaelstaib** [comment]
The bug is fixed with version 0.6.0-preview-4. We will release the final version end of next week I think.

**Comment by michaelstaib** [comment]
We also aligned the error implementation with the 2018 spec version. So, I added the path property and also moved non-spec properties under the extension property.

**Comment by michaelstaib** [comment]
[0.6.0-preview-4](https://github.com/ChilliCream/hotchocolate/releases/tag/0.6.0-preview-4)
