### ISSUE TITLE
add unsigned integer types (non negative integers) scalars

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ChilliCream/hotchocolate#3120]
ulong, ushort

Why? To model my domain better with specifying 0+ values

**Comment by dominik4545** [comment]
Hi @dzmitry-lahoda,

I asked the same :) (see: 3116)
It will be part of release 11.1 as @michaelstaib commented.

**Comment by michaelstaib** [comment]
closing this issue as it is already solved.
