### ISSUE TITLE
"Filename too long" on Windows when checking out develop branch

### ISSUE THREAD

**Issue by huysentruitw** [ChilliCream/hotchocolate#3122]
Opening this issue as some sort of note-to-self and for anyone bumping against the same problem when checking out the development branch of hotchocolate on Windows.

First, make sure you have long path support for Windows enabled, there are two ways to do that:

1. With regedit.exe (preferred on Windows 10 Home): go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` and create a REG_DWORD named `LongPathsEnabled` and set the value to 1.

2. With gpedit (preferred on Windows 10 Pro): go to `Computer Configuration > Administrative Templates > System > Filesystem` and enable the setting `Enable Win32 long paths`.

If the git instance you're running is based on msys, you might also have to configure git to allow paths with more than 260 characters, to do so, run: `git config --system core.longpaths true` from a console.

**Comment by michaelstaib** [comment]
This issue should be fixed.
