### ISSUE TITLE
Dependencies between resolvers

### ISSUE THREAD

**Issue by ronaldvdv** [ChilliCream/hotchocolate#3129]
Hi!

I'm getting stuck with the following when using Hot Chocolate v11 with Entity Framework Core. Say I have a `Department` containing multiple `Employee` instances. For some property `DepartmentFunction` of the `Employee`, I want to combine a property `Name` of its `Department` with a `Function` on the `Employee` itself.

First I was considering lazy loading. However, this does not work with pooled contexts since the context is already disposed by the time I call the property. Also, it would not give the best performance since it would not allow me to use a data loader.

Then I realized I could have a resolver type for `Employee` with one method to return its `Department` and another to calculate its `DepartmentFunction`. However, the second would then need to call the first and things get more complicated. For example, the second would also have a dependency on the data loader required to load the `Department` with the first method. In reality I'm looking at more complex calculations that depend on more than one other property/relation.

Am I missing something? Is there a nicer way to solve this problem?

Thanks & keep up the great work!
Ronald

**Comment by michaelstaib** [comment]
You can either use DataLoader or projections for this. DataLoader would batch all requests for the lazy loaded part into one DB call. Projections would dynamically get all the data you need in one call. I personally prefer DataLoader since they have a couple of other benefits, but this depends on how you feel.

**Comment by ronaldvdv** [comment]
So let's say I go the data loader approach. I'm getting something like the below. Note that GetDepartmentFunctionAsync needs to call GetDepartmentAsync and hence has the same arguments. It works, but if its result would be based on two or more different other fields, each of the corresponding resolvers needs to be called manually with all required arguments. Can it be done any nicer? E.g. call a resolver from another resolver in a simple way (e.g. in GetDepartmentFunctionAsync, just "ask" for Employee.Department via the execution engine)?

Earlier I was using Hot Chocolate v10, I would define these calculations on the entity types themselves.  Because with GraphQL we don't know what the query will look like, we don't know beforehand which related entities to be loaded (e.g. we can't know whether for an Employee we also need to load the Department, since it depends on whether we're interested in the Employee.DepartmentFunction property in the GraphQL query). Therefore I used lazy loading. However, this breaks in v11. We now need to use context pooling and we get an exception while lazy loading since the context is already disposed/returned by the time the Employee.Department relation is loaded.

```
class EmployeeType : ObjectType<Employee>
{
  protected override void Configure(IObjectTypeDescriptor<Employee> descriptor)
  { 
    base.Configure(descriptor);
    descriptor.Field(e => e.Department).ResolveWith<EmployeeResolver>(er => er.GetDepartmentAsync(default!, default!, default!));       
    descriptor.Field(e => e.DepartmentFunction).ResolveWith<EmployeeResolver>(er => er.GetDepartmentFunctionAsync(default!, default!, default!));
  } 
  private class EmployeeResolver
  {
      public async Task<string> GetDepartmentFunctionAsync(Employee employee, DepartmentByIdDataLoader loader, CancellationToken cancellationToken)
      {
        var department = await GetDepartmentAsync(department, loader, cancellationToken);
        return department.Name + ": " + employee.Function;
      }
            
      public Task<Department> GetDepartmentAsync(Employee employee, DepartmentByIdDataLoader loader, CancellationToken cancellationToken)
      {
        return loader.LoadAsync(employee.DepartmentId, cancellationToken);
      }
  }
}
```

**Comment by gojanpaolo** [comment]
We had a similar design issue where we needed a lot of service dependencies for our resolver. We basically extracted the logic to a service and we're able to inject as much dependency it needs.

```c#
public class DepartmentService
{
    private readonly DepartmentByIdDataLoader _departmentById;
    private readonly DivisionByIdDataLoader _divisionById;
    private readonly CompanyByIdDataLoader _companyById;
    private readonly IFooService _fooService;
    private readonly ILogger _logger;

    public DepartmentService(
        DepartmentByIdDataLoader departmentById,
        DivisionByIdDataLoader divisionById,
        CompanyByIdDataLoader companyById,
        IFooService fooService,
        ILogger logger)
    {
        _departmentById = departmentById;
        _divisionById = divisionById;
        _companyById = companyById;
        _fooService = fooService;
        _logger = logger;
    }

    public async Task<string> GetDepartmentFunctionAsync(Employee employee, CancellationToken cancellationToken)
    {
        var department = await GetDepartmentAsync(employee, cancellationToken);
        return department.Name + ": " + employee.Function;
    }
          
    public Task<Department> GetDepartmentAsync(Employee employee, CancellationToken cancellationToken)
    {
        return _departmentById.LoadAsync(employee.DepartmentId, cancellationToken);
    }
}
```

Our resolvers are then just wrappers for the service that we extracted.. Note that we only do this for complex logic that requires a lot of service dependencies. IOW, if we only need one `DataLoader`, we just define that directly in the resolver.

```c#
private class EmployeeResolver
{
    public Task<string> GetDepartmentFunctionAsync([Service] IDepartmentService departmentService, Employee employee, CancellationToken cancellationToken) => departmentService.GetDepartmentFunctionAsync(employee, cancellationToken);

    public Task<string> GetDepartmentAsync([Service] IDepartmentService departmentService, Employee employee, CancellationToken cancellationToken) => departmentService.GetDepartmentAsync(employee, cancellationToken);
}
```

**Comment by ronaldvdv** [comment]
Allright, good idea to move the resolver logic into a separate service. Not sure why lazy loading breaks in combination with context pooling, but for now this looks like a reasonable workaround!
