### ISSUE TITLE
Union documentation v11 - clarification/insights

### ISSUE THREAD

**Issue by Aeseir** [ChilliCream/hotchocolate#3139]
Trying to work through the documentation on Unions and Interfaces i am struggling to connect the dots.

Having followed the previous tutorials finally landed on unions and been keen to give it a go but I  keep hitting the wall.
The biggest question mark is the IAccessRepo that appears the in the how to documentation but no explanation as to what it is?

![image](https://user-images.githubusercontent.com/985321/109411361-aa893800-79f5-11eb-85f6-4e4382745738.png)

What is this supposed to represent, and how does this relate to entities stored in one of the many dbs?

For example how does this relate to the following (I used the example on that page to store Users and Groups in a PostgreSql DB):

```
[UseDbContext(typeof(AppDbContext ))]
[UseProjection]
[UseFiltering]
[UseSorting]
public IQueryable<User> GetUsers([ScopedService] AppDbContext context) => context.Users;
```

I've tried to figure it out but I just cannot connect the dots.
I am using NET 5 as target framework.

**Comment by gojanpaolo** [comment]
Assuming you're using Annotation-based configuration, a Union type will start with a C# `interface` that is marked with the `UnionType` attribute:

```c#
[UnionType("GroupMember")]
public interface IGroupMember { }
```

Then you'll have classes that inherit that interface:
```c#
public class Group : IGroupMember { }

public class User : IGroupMember { }
```

HotChocolate will then generate the following graphql Union type

```graphql
union GroupMember = User | Group
```

---

`IAccessRepo` is just a sample interface that basically represents your business logic to get an array of `IGroupMember`. HotChocolate does NOT use the `IAccessRepo` to generate the graphql schema.

**Comment by Aeseir** [comment]
Thanks mate, I ended up spending the evening digging through the older examples to figure out how v10 did it, and eventually figured out a way to make it work.

What you mentioned here just confirmed my approach.

Thanks for the assist this can be closed off, however i recommend just calling it out on the documentation the way you described it here, it is a lot more clearer.

**Comment by damikun** [comment]
I will just extend that if you don't want to use attributes `[UnionType("GroupMember")]` you can use type descriptor also... At the end attribute is converted to this..

**Example:**

```
    public class SetIssueStatusPayloadErrorUnion : UnionType<ISetIssueStatusError> {
        protected override void Configure(IUnionTypeDescriptor descriptor) {
            descriptor.Type<ValidationErrorType>();
            descriptor.Type<UnAuthorisedType>();
            descriptor.Type<IssueNotFoundType>();
            descriptor.Type<InternalServerErrorType>();
        }
    }
```

And add it to server by calling

` .AddType<SetIssueStatusPayloadErrorUnion >()`  where  `ISetIssueStatusError` is merge interface for all unions...
