### ISSUE TITLE
ByteArrayType not implicitly applying

### ISSUE THREAD

**Issue by OneLogicalMyth** [ChilliCream/hotchocolate#3145]
**Describe the bug**
When you add `ByteArrayType` to services within Startup.cs you would expect that all `byte[]` fields to implicitly have the type applied. However, this does not appear to be the case and explicitly applying the `ByteArrayType` on the object type resolves the issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a simple object that uses `byte[]` such as RowVersion for entity framework
2. Add the type to the GraphQL service using `.AddType<ByteArrayType>();`
3. Perform a query request and see the error stating `ByteArray cannot serialize the given value`

**Expected behavior**
To stop each byte being displayed in an array of integers application of the ByteArray should convert the property to a base64 encoded string. However, this causes the above error.

**Additional context**
Full discussion on the issue is here https://github.com/ChilliCream/hotchocolate/discussions/3132?sort=new

**Comment by gojanpaolo** [comment]
@michaelstaib Can I take a stab at this? I believe you mentioned that you already looked at the code. It would be a great help if you could point where to start looking at.

**Comment by michaelstaib** [comment]
I have moved this again.... we will change the type initialization for the august release so its better handled there. We have analyzed what the issues is and have a very old piece of code causing this in the type initialization.

**Comment by eduardogoncalves** [comment]
Any updates on this?
