### ISSUE TITLE
Urgent Help Needed

### ISSUE THREAD

**Issue by mcopur** [ChilliCream/hotchocolate#3165]
I am trying to access skip and take arguments in my service but I could not find any proper sample on the web.
I shared a sample template about my current service, this is a kind of template real implementation is long and different.
I just need to access these pagination parameters and pass them into my repository service. I don not want to create extra properties to keep those arguments because it is already is created by hotchocolate as I share below. How can I do that?

```
 public class Query
    {
        private readonly IRepository<MyData> repository;       
        private IList<MyData> searchResult;

        public Query(IRepository<MyData> repository)
        {
            this.repository = repository;
        }

        [UseOffsetPaging(DefaultPageSize = 2, IncludeTotalCount = true, MaxPageSize = 20)]
        public async Task<IQueryable<MyData>> GetMyData(MyDataParameter queryParam)
        {
            searchResult = (IList<MyData>)await repository.Search(queryParam);           
            return searchResult.AsQueryable();
        }

    }

    public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor.Field(d => d.GetObjects(default))
                .AddOffsetPagingArguments()
                .Type<ListType<NonNullType<MyDataType>>>()
                .UseFiltering();
        }
    }
```

![image](https://user-images.githubusercontent.com/10618618/109640248-7f672b80-7b50-11eb-833f-7b8e26b15068.png)

**Comment by michaelstaib** [comment]
```
 [UseOffsetPaging(DefaultPageSize = 2, IncludeTotalCount = true, MaxPageSize = 20)]
        public async Task<IQueryable<MyData>> GetMyData(MyDataParameter queryParam)
        {
            searchResult = (IList<MyData>)await repository.Search(queryParam);           
            return searchResult.AsQueryable();
        }
```

You do not need to return a queryable here... just return the list.

As for the paging parameters... just inject them.

```
 [UseOffsetPaging(DefaultPageSize = 2, IncludeTotalCount = true, MaxPageSize = 20)]
        public async Task<IQueryable<MyData>> GetMyData(
           MyDataParameter queryParam, int skip, int take)
        {
            searchResult = (IList<MyData>)await repository.Search(queryParam);           
            return searchResult.AsQueryable();
        }
```

**Comment by mcopur** [comment]
@michaelstaib Thank you so much for your quick response.
In that case, I am getting an error on configure method since the service parameter changed.

Error : There is no argument given that corresponds to the required formal parameter 'skip' of 'Query.GetMyData(ObjectDbObjectParameter, int, int)


```
 public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor.Field(d => d.GetMyData(default))
                .AddOffsetPagingArguments()
                .Type<ListType<NonNullType<MyDataType>>>()
                .UseFiltering();
        }
    }
```

**Comment by mcopur** [comment]
@michaelstaib  I have fixed it like below but previously, I was getting page information correctly but now, since I passed skip and take parameter into my repository service it returns incorrectly. Do I have to fill it myself by calling some database count operation or calculate?

```
public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {
            descriptor.Field(d => d.GetMyData(default,default,default))
                .AddOffsetPagingArguments()
                .Type<ListType<NonNullType<MyDataType>>>()
                .UseFiltering();
        }
    }
```


Before it was
```
  "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false
      },
      "totalCount": 1089
```

Since I used skip:0, take:10, Now it is

```
  "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false
      },
      "totalCount": 10
```

**Comment by michaelstaib** [comment]
OK ... I am just seeing that the code example of you is a bit muddled :)

So either use attributes or the fluent api.

Join us on slack .... it is easier there to talk .... 

http://bit.ly/joinchilli

**Comment by michaelstaib** [comment]
Closing this issue since its stale.
