### ISSUE TITLE
Field selections issue with re-used fragment

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#3166]
**Describe the bug**
There's a case I've found where fields in objects aren't returned when they should be.

**To Reproduce**
Run a query like this, passing `true` for `isPendingView`. Note that even though the `BookingsList_1fUkW6` fragment will be skipped, the `BookingOffersList_1gJW2v` fragment reaches all the way down to the `BookingListItem_booking` itself, so those fields should come back.

```graphql
query tabsBookingStatusTabQuery(
  $supplierIds: [ID!]!
  $isPendingView: Boolean!
  $bookingStatusForSupplier: BookingStatusForSupplier!
) {
  ...BookingOffersList_1gJW2v @include(if: $isPendingView)
  ...BookingsList_1fUkW6 @skip(if: $isPendingView)
}

fragment BookingOffersList_1gJW2v on Query {
  bookingOffers(
    first: 7
    last: 7
    supplierIds: $supplierIds
    status: PENDING
    orderBy: UNCLAIMED_FIRST_THEN_BY_SERVICE_DATE_ASC
  ) {
    edges {
      ...BookingOfferListItem_booking
    }
  }
}

fragment BookingOfferListItem_booking on BookingOfferEdge {
  node {
    booking {
      ...BookingListItem_booking
    }
  }
}

fragment BookingsList_1fUkW6 on Query {
  bookings(
    first: 7
    last: 7
    supplierIds: $supplierIds
    bookingStatusForSupplier: $bookingStatusForSupplier
    bookingTypes: [STANDARD]
    orderBy: SERVICE_DATE_DESC
  ) {
    edges {
      node {
        ...BookingListItem_booking
      }
    }
  }
}

fragment BookingListItem_booking on Booking {
  id
  dbId
  job
  serviceDate
  totalNetPrice {
    includingTax
  }
  customer {
    avatarUrl
    fullName
    id
  }
  vehicle {
    configuration {
      make
      model
      id
    }
    id
  }
}
```

**Expected behavior**
All fields on `BookingListItem_booking` are returned, including sub fields of object types like the customer and vehicle fields.

**Actual behaviour**
All fields on `BookingListItem_booking` are returned, but those that object types are returned as an empty object; even those that aren't resolved via stitching but just locally, like `totalNetPrice` for instance.
```
              "totalNetPrice": {},
              "customer": {},
              "vehicle": {},
```
(similar behaviour to this [bug](https://github.com/ChilliCream/hotchocolate/issues/2727))

**Desktop (please complete the following information):**
 - OS: Linux Alpine
 - HC Version: v11.0.9

**Additional context**
From Slack convo:

Michael:hot_pepper:  12:19 PM
so the type case matches
12:19
ah i see
12:20
I need to write some extra tests for this
12:23
I think when we compile this it merges the fragments
12:23
which would be a bug

**Comment by damikun** [comment]
I think i saw something similar in slack... So im posting to have more resouces :) 
https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1614299550318300
