### ISSUE TITLE
Resolvers should be registered from interfaces with implementations with recursive generics

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ChilliCream/hotchocolate#3170]
Given I have next entity in graphq:
```csharp
public interface ISome<T> where T:IHasBooking {
   Task<Booking> GetBooking([Parent] T x) => bookingDataLoader.LoadAsync(x.BookingId);
}

public class Fligth: ISome<Fligth>, IHasBooking 
{
    public int BookingId { get; set;} 
}
```

I want `booking` to be registered as `resolver` in `Flight`

As of now it is not registered.

Recursive generics work well for inheritance, so if `ISome` is class, than `booking` is resolved.

**Comment by MattA48** [comment]
Have also come across this issue - going to need to go back to using a base class for now, which is a pity as this is a nice case for composition from multiple interfaces
