### ISSUE TITLE
Projection for inherited field with private setter is ignored

### ISSUE THREAD

**Issue by rafaelldi** [ChilliCream/hotchocolate#3182]
**Describe the bug**
If you inherit a class from another with a field with a `private` setter, that field will not be considered in the SQL expression.

**To Reproduce**
I have two classes:
```csharp
public abstract class Entity
{
    public int Id { get; private set; }
}

public class Speaker: Entity
{
    public string Name { get; set; }

    public string Bio { get; set; }

    public string WebSite { get; set; }
}
```
And a straightforward query:
```csharp
public class Query
{
    public IQueryable<Speaker> GetSpeakers([Service] ApplicationDbContext context) =>
        context.Speakers;
}

public class QueryType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor
            .Field(p => p.GetSpeakers(default));
    }
}
```
I send a request:
```graphql
query GetSpeakerNames {
  speakers {
    id
    name
  }
}
```
In this case, the correct SQL query is generated.
```sql
SELECT "s"."Id", "s"."Bio", "s"."Name", "s"."WebSite"
FROM "Speakers" AS "s"
```
But if you add projections, the query will not consider the inherited field.
```csharp
public class QueryType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor
            .Field(p => p.GetSpeakers(default))
            .UseProjection();
    }
}
```
```sql
SELECT "s"."Name"
FROM "Speakers" AS "s"
```
With `public` setter, everything works fine:
```sql
SELECT "s"."Id", "s"."Name"
FROM "Speakers" AS "s"
```
**Expected behavior**
Is it a bug?

It seems to me that fields with a private setter should not be ignored.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 11.0.9

**Comment by PascalSenn** [comment]
Hi @rafaelldi  
So i know where you issue comes from, but for now we do not have a solution for it other than making the field public or projecting it into another DTO that has a public representation of it

What projection does internaly is basically the following:
```csharp
collection.Select(x => new Speaker { Name = x.Name})
```
As the `id` field is not settable, it can also not be set in a projection

**Comment by rafaelldi** [comment]
Thank you for answering

**Comment by AsgerPetersen** [comment]
For others with the same issue it seems like a possible work-around is making the setter `protected` instead of `private`. It is not perfect, but it is still a lot better than making it `public`. This is using HotCocolate v 12.8.1.

**Comment by kawazoe** [comment]
@AsgerPetersen I just spend 8 hours trying to figure out why this doesn't work, and learning about this workaround makes me even more confused...

You can have a private setter in the concrete type used by the query, so for the previous example any properties on Speaker could have a private setter, and it would still work. Setting a property to protected also makes it private from the perspective of the HotChocolate engine. @PascalSenn 's justification makes no sense given these two facts. My guess is that today, this bug should probably be reopened as it feels like there is some legacy code in the schema that checks for invariants that aren't true anymore.
