### ISSUE TITLE
configure file location of query files to avoid too many files in project root

### ISSUE THREAD

**Issue by FrederikNygart** [ChilliCream/hotchocolate#3191]
Hi,

First things first, thank you for all the hard work on this project. It is a really cool toolset!

I just started implementing hot chocolate and strawberry shake in my Blazor SPA and right of the bat, i really want to move all graphql files into a separate folder, so that they're not all in the root folder. However i get an error when i move them out of the root folder.

my config:
```json
{"Schemas":[{"Name":"Some","Type":"http","File":"Some.graphql","Url":"https://localhost:50001/graphql"}],"ClientName":"SomeClient"}
```

Is there any way to configure the berry.json so that documents in subfolders are included as query files? 

If not it would be nice with an option in the json config file to specify the location of all of your query files.

Best
Frederik

versions:
Hot Chocolate 11.0.9
Strawberry Shake 11.0.0-preview.130

**Comment by Sibusten** [comment]
This appears to be resolved in newer versions of Strawberry Shake with the `documents` property in `.graphqlrc.json`. The default value `**/*.graphql` finds files in subfolders.

https://chillicream.com/docs/strawberryshake/get-started#step-4-add-a-graphql-client-to-your-project-using-the-cli-tools

The config file in this step shows the property.

**Comment by PascalSenn** [comment]
@FrederikNygart  can you close the issue if it works in a newer version?
