### ISSUE TITLE
Queries with skip/take arguments fail to generate code in StrawberryShake

### ISSUE THREAD

**Issue by wmeints** [ChilliCream/hotchocolate#3196]
**Describe the bug**
Queries that use skip/take arguments can't be generated by the source generator. You'll receive an error: `Sequence contains no elements` from the source generation process.

**To Reproduce**

Create a schema with the following query definition in it:

```graphql
schema {
  query: Query
}

type Query {
  newsItems(skip: Int take: Int query: String!): NewsItemCollectionSegment
}

type NewsItem implements Node {
  id: ID!
  feedId: Uuid!
  feedUrl: String!
  html: String!
  image: String!
  keywords: [String!]!
  language: String!
  summary: String!
  text: String!
  title: String!
  updated: DateTime
  url: String!
}

type NewsItemCollectionSegment {
  items: [NewsItem]
  "Information to aid in pagination."
  pageInfo: CollectionSegmentInfo!
}

"Information about the offset pagination."
type CollectionSegmentInfo {
  "Indicates whether more items exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more items exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
}
```

Next, create another graphql file for the operation that you want to implement:

```graphql
query SearchNewsItems($query: String! $skip: Int $take: Int) {
  newsItems(skip: $skip take: $take query: $query) {
    items {
      id, title, summary
    }
  }
}
```

After that, compile the project. And you'll get the error message.

**Expected behavior**
A client is generated with a paged operation.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 11.1.0-preview.73

**Comment by michaelstaib** [comment]
Found the bug... thanks for reporting this.... fix will be included into preview.74

**Comment by wmeints** [comment]
I'm happy to help out provide a PR to fix the bug if needed. Love the product you're building and want to help out :-)
