### ISSUE TITLE
IError not catched with query engine on Request middleware

### ISSUE THREAD

**Issue by maris-jurgenbergs** [ChilliCream/hotchocolate#3199]
I created a request intercepting middleware, that checks if a header is present, if it is not then i am throwing a QueryException. (Using .NET Core)
```
public class HeaderMiddleware
{
    private readonly RequestDelegate _next;

    public HeaderMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(IHttpContextAccessor httpContextAccessor, IRequestContext context)
    {
        HttpContext httpContext = httpContextAccessor.HttpContext;
        var someHeader = httpContext.Request.Headers["SomeHeader"];
        if (string.IsNullOrEmpty(someHeader))
        {
            throw new QueryException(ErrorBuilder.New()
                .SetMessage("BadRequest")
                .SetCode("HEADER_MISSING")
                .Build());
        }

        await _next(context);
    }
}
```
And it is registered in this approach:
```
services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddType<SomeType>()
    .UseRequest<HeaderMiddleware>()
    .UseDefaultPipeline();
```

If there is no header present, then graphql returns an "**Unexpected Execution Error**" error type, but i wanted the query engine to catch and handle IError appropriately without the  "**Unexpected Execution Error**"  and with the additional code property "HEADER_MISSING".
```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "extensions": {
        "message": "BadRequest",
        "stackTrace": ".........."
      }
    }
  ]
}
```
I guess i am throwing the error too soon for the query engine to catch it? Is there any other middleware or pipeline place where i can inject this logic to achieve a proper IError handling situation?

**Comment by Mihail3843** [comment]
I have similar error, but the exception which has been throwned is the InvalidOperationException with message "Operation is not valid due to the current state of the object."
