### ISSUE TITLE
An option to not automatically format the data as lowerCamelCase

### ISSUE THREAD

**Issue by namnm** [ChilliCream/hotchocolate#320]
**Is your feature request related to a problem? Please describe.**
Right now we are formatting the data as lowerCamelCase automatically, but we want to let the data as it is.

**Describe the solution you'd like**
Add an option to not automatically format the data as lowerCamelCase. This option will not effect the `errors` or `data` field, only with the data inside the `data` field.

**Comment by michaelstaib** [comment]
This should not be the case. We have a test to validate that:
[QueryMiddlewareTests.cs](https://github.com/ChilliCream/hotchocolate/blob/master/src/AspNetCore.Tests/QueryMiddlewareTests.cs) -> HttpPost_Casing

**Comment by michaelstaib** [comment]
Or do you mean that we automatically make the schema types case compliant?

```csharp
public class Foo
{
   string Bar { get; set; }
}
```

becomes:

```graphql
type Foo {
   bar: String
}
```

**Comment by michaelstaib** [comment]
I will look into how we can do that. Maybe I will split this one and first allow this on a type basis and then introduce a global default.

**Comment by michaelstaib** [comment]
this one is possible since 10.0
