### ISSUE TITLE
Hot Reload causing mutation failure

### ISSUE THREAD

**Issue by karlskraken** [ChilliCream/hotchocolate#3216]
**Describe the bug**
Redis hot reloading of a stitched schema does not trigger a clearing of existing prepared operations. This causes an issue with mutations as the schema mutation type gets updated but the type associated with the cached operation does not. When running the same mutation after a reload occurs the types do not match and OperationType.Query is assigned for execution.

**To Reproduce**

1. Create a server project exposing a mutation and serving the schema to Redis.
2. Create a stitching project with remote schemas from Redis.
3. Execute the mutation through the stitched project
4. Restart server project
5. Execute the same mutation again

**Expected behavior**
Mutation to execute without failure

**Actual behavior**
request:
```
mutation {
  addTest(anything:"boom") {
    value
  }
}
```

response before restart:
```
{
  "data": {
    "addTest": {
      "value": "boom"
    }
  }
}
```

response after restart:
```
{
  "errors": [
    {
      "message": "Field `addTest` does not exist on type ``QueryType``.",
      "extensions": {
        "remote": {
          "message": "Field `addTest` does not exist on type `QueryType`."
        },
        "schemaName": "test"
      }
    }
  ],
  "data": {
    "addTest": null
  }
}
```

**Additional Context**
Adding an implementation for IPreparedOperationCache that resets cache on RequestExecutorEvicted solves this but doesn't seem like an ideal approach.

HC v11.0.9

**Comment by michaelstaib** [comment]
Thanks for reporting this.
