### ISSUE TITLE
Banana Pop Cake Editor not working in Chrome

### ISSUE THREAD

**Issue by noobinthisgame** [ChilliCream/hotchocolate#3221]
**Describe the bug**
It is not possible to write something inside of the query editor in Banana Pop Cake under Chrome. In Firefox everything works fine.

**To Reproduce**
1. Go to the Banana Pop Cake Playground
2. Click on inside of the query editor
3. Try to write something.
4. It does'nt work :(

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 89.0.4389.72 (Official Build) (64-bit)

**Comment by PascalSenn** [comment]
I cannot reproduce this behaviour. Can you clear the page data and try it again? (or try it in a in private window, this should also be clean)

**Comment by noobinthisgame** [comment]
Cache was badly messed up indeed... My bad!
