### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#323]
I am deciding whether to use this project or GrpahQL.net and its so close. Is there an equivalent way in this project to handle type level and field level security policies like this?

https://github.com/graphql-dotnet/authorization/blob/master/README.md

**Comment by michaelstaib** [comment]
Hi,

yes but I think different. We are also using the policies from asp.net. But we are included them into authorization directives that can be annotated to fields, objects, schema etc....
This way it is more spec compliant.

Since, this question was asked on our slack channel I will create an example project for that with a little tutorial next week.

**Comment by michaelstaib** [comment]
Directives can be annotated to basically anything from query elements to types or fields etc.

Lets say we have a type and for a certain field we want to limit the access that we could add to that field the authorization directive like the following:

```GraphQL
type Person {
  name: String!
  address: String! @authorize(policy: "Foo")
}
```

So, every time the address field is resolved the Foo policy validates if the current user is able to access the current field. You could also add the `authorize` directive to the type `Person` type itself and it would then be executed on any field.

```GraphQL
type Person @authorize(role: "bar") {
  name: String!
  address: String! @authorize(policy: "Foo")
}
```

So, in the above example the name resolver would only execute if the user has the role `bar` and the address resolver would only execute if the `Foo` policy validates to `true`.

We are currently also working on the "Limit directive uniqueness to explicitly marked directives" spec item that will be introduced with the next GraphQL spec version. This will further allow to pipe directives and make them even more powerful.

In Hot Choclolate directives can be associated with a field middleware that can change the execution behavior. We have implemented those very similar to the asp.net core middleware delegates.

[More about directives](https://hotchocolate.io/docs/directive-middleware)

So, you are able to implement your own authorization attributes our default set is not enough for you. Our own directives are built upon the [asp.net core policies](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1) so you can basically do anything that you can do with those.

So if you wanted to implement a directive like the authorize directive by your self it would look something like the following:

```csharp
public class Authorize
{
    public string Policy { get; set; }
}

public class CustomMiddleware
{
    public async Task Invoke(Authorize directive, [Service] IAuthorizationService authorizationService)
    {
        bool allowed = await _authorization.AuthorizeAsync(directive.Policy);
        // the authorization service the asp.net core authorization service .... so basically you would execute the policy and the put here your own logic....
    }
}

public class AuthorizeDirectiveType : DirectiveType<Authorize>
{
    protected overrode void Configure(IDirectiveTypeDescriptor<Authorize> desc) 
    {
        desc.Middleware< CustomMiddleware>(t => t.Invoke(default, default));
    }
}
```

For a rock solid solution we would add some more validation etc... but this should just show you how easily you can extend our solution or even completely replace it with your own.

If you need some more assistance you can also join our slack channel and we can discuss details more deeply.

With the upcoming version (0.6.0) there are many more enhancements in this area.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNDUyMjIxOTc1MTU3LWNlN2ViMGM5YTVhMWI3MzcwNDdjOTVkYWQ5ODZkMjJiODIwZjY5MzYzODc1Zjg5NDE5ZDQ4Zjk0MGExZWMzZGY

**Comment by michaelstaib** [comment]
I just looked at their example and they basically added this to their types from what it looks like. 

So, just to show you how it would look like in Schema First (GraphQL SDL):

```graphql
type Person @authorize(role: "bar") {
  name: String!
  address: String! @authorize(policy: "Foo")
}
```

Code First adding authorization works like the following:

```csharp
public class QueryType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Person> descriptor)
    {
        descriptor.Directive(new Authorize { Policy =  "Bar" });
        descriptor.Field(f => f.Address).Directive(new Authorize { Policy =  "Foo" });
    }
}
```

Forgive me all my typos ;)

**Comment by michaelstaib** [comment]
There is now an example server project demonstrating authorization:
https://github.com/ChilliCream/hotchocolate-aspnetcore/tree/master/examples/StarWars

Documentation of the new version will go live tomorrow. So, I will close this issue.

**Comment by michaelstaib** [comment]
https://hotchocolate.io/docs/next/authorization
