### ISSUE TITLE
Projections with data loaders

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#3235]
I have an upp using HC11 and EF Core and recently I've added projections to it. This works great on IQueryables that I expose on my API and it also allows me to skip redundant `SELECT COUNT(*)` calls which I also mentioned in [#2934](https://github.com/ChilliCream/hotchocolate/issues/2934). But there's one place where it doesn't work as expected and I'm wondering if anything can be done here.

I'm using a lot of data loaders (mostly group and batch) which I use to resolve the data linked to the stuff I expose on the higher level on API. The structure of my database makes this way more efficient than doing that on EF level and let it run the JOINs. Obviously projections do not work here and my data loaders are still fetching all of the columns.

Here's the example implementation of the fetch method used by `GroupDataLoader`

```csharp
public async Task<ILookup<string, InvoiceLine>> GetLinesAsync(
    IReadOnlyList<string> keys, CancellationToken cancellationToken = default)
{
    await using var context = _contextFactory.CreateDbContext();
    return await context.InvoiceLines.Where(x => keys.Contains(x.PrimaryKey))
        .ToLookupAsync(x => x.PrimaryKey.ToUpperInvariant(), cancellationToken);
}
```

I'm wondering is there a way to somehow inject projections into this kind of code? It'd definitely need to be called before IQueryable is enumerated and mapped to ILookup.

**Comment by MarkoH17** [comment]
Is there any update on this? I'm just starting to play around with the GraphQL-Workshop repository and the EF demo in the docs, so I'm pretty new to this still.

However, it seems like not projecting when using a data loader nullifies one of GraphQL's benefits where only selected fields are queried from the data provider. I believe this issue also affects resolvers, correct? In that case, aren't most queries affected by this issue when they don't return an IQueryable?

**Comment by Pjotrtje** [comment]
This would be super nice and would make my very nested aggregate with related aggregates so much more performant. Not sure if there are already idea's how the interface should look like. Something like this would be nice (pseudo code):

```csharp

public sealed record GroupedDataLoaderMap<TParent, TChild, TKey>(
	IQueryable<TChild> ChildQueryable,
	Func<TChild, TKey> ChildToKeySelector,
	Func<TParent, TKey> ParentToKeySelector);
	
public sealed record BatchedDataLoaderMap<TParent, TChild, TKey>(
	IQueryable<TChild> ChildQueryable, 
	Func<TChild, TKey> ChildToKeySelector,
	Func<TParent, TKey> ParentToKeySelector);

[ExtendObjectType(typeof(User))]
public class UserExtensions
{	
	//This already works rite?
	[UseProjection]
	[UseFiltering]
	[UseSorting]
	public IQueryable<Post> GetPosts(
		[Parent] User user,
		TemplateDbContext dbContext)
	{
		return dbContext
			.Posts
			.Where(p => p.UserId == user.Id);
	}
	
	//This is kinda simular, and from user of HotChocolate (like me :)) perspective easy. Not sure if easy to implement. Because we need all users/parents here
	[UseProjection]
	[UseFiltering]
	[UseSorting]
	public GroupedDataLoaderMap<User, Post, int> GetPosts(
		[Parents] IReadOnlyCollection<User> users,
		TemplateDbContext dbContext)
	{
		var userIds = user
			.Select(u => u.Id)
			.ToList();
			
		var postQuery = dbContext
			.Posts
			.Where(p => userIds.Contains(p.UserId));
			
		return new(
			postQuery, 
			p => p.UserId,
			u => u.Id);
	}
	
}

[ExtendObjectType(typeof(Post))]
public class PostExtensions
{		
	//This already works rite?
	[UseSingleOrDefault]
	[UseProjection]
	public IQueryable<User> GetUser(
		[Parent] Post post,
		TemplateDbContext dbContext)
	{		
		return dbContext
			.Users
			.Where(u => u.Id == post.Userid);
	}
	
	//This is kinda simular, and from user of HotChocolate (like me :)) perspective easy. Not sure if easy to implement. Because we need all posts/parents here
	[UseProjection]
	public BatchedDataLoaderMap<Post, User, int> GetUser(
		[Parents] IReadOnlyCollection<Posts> posts,
		TemplateDbContext dbContext)
	{
		var userIds = posts
			.Select(p => p.UserId)
			.Distinct()
			.ToList();
			
		var userQuery = dbContext
			.Users
			.Where(u => userIds.Contains(u.Id));
			
		return new(
			userQuery, 
			u => u.Id,
			p => p.UserId);
	}
}

```
In theory all data for the mapping is in return type. Feel free to completly ignore this :).

**Comment by DanielNinchev** [comment]
Is there any update on this?
