### ISSUE TITLE
StrawberryShake - ExecuteAsync hangs on particular input.

### ISSUE THREAD

**Issue by TeunKooijman** [ChilliCream/hotchocolate#3238]
**Describe the bug**
For the following query and schema, the call to `ExecuteAsync` hangs, and does not throw an exception of any kind.

```
CancellationTokenSource timeout = new CancellationTokenSource(5000);
IOperationResult<IGetFeatsPageResult> result = await PathfinderOfficialApi.GetFeatsPage
     .ExecuteAsync(10, 20, "Quick", new [] { new FeatSortInput { Name = SortEnumType.Asc }}, timeout.Token);
```

*Query:*
```
query GetFeatsPage($skip: Int!, $take: Int!, $searchTerm: String! = "", $order: [FeatSortInput!] = [{name: ASC}]) {
	feats(
		skip: $skip, 
		take: $take, 
		order: $order,
		where: {
			or: [
				{name: {contains: $searchTerm}}, 
				{traits: {some: {name: {contains: $searchTerm}}}}
			]
		}) 
	{
		totalCount,
		items {
			id,
			name,
			level
		}
	}
}
```

schema: 
https://pf2e.io/api/graphql?sdl

However, when passing in an empty `FeatSortInput` array, the call does work. I.e. the following does not hang:

```
CancellationTokenSource timeout = new CancellationTokenSource(5000);
IOperationResult<IGetFeatsPageResult> result = await PathfinderOfficialApi.GetFeatsPage
     .ExecuteAsync(10, 20, "Quick", Array.Empty<FeatSortInput>(), timeout.Token);
```

**To Reproduce**
If this is needed in more detail, please let me know.

**Expected behavior**
I expect the call to return, throw an exception, or potentially get cancelled after a particular amount of time if such a CancellationToken is passed in.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - StrawBerryShake: Preview 79
 - Visual Studio: 2019 16.8.2

**Additional context**
Let me know if you need additional information.

**Comment by PascalSenn** [comment]
@TeunKooijman  does this still occure in the official 11.1 release?

**Comment by TeunKooijman** [comment]
Sadly, by the looks of it, it does :(.
