### ISSUE TITLE
HotChocolate.AspNetCore pulls in references to the ASP.NET Core Shared Framework which is not supported by Blazor WebAssembly apps.

### ISSUE THREAD

**Issue by compgumby** [ChilliCream/hotchocolate#3239]
I have a Blazor WebAssembly app that interacts with a .NET core GraphQL (HC) server. I added validation to one of my classes and HC dutifully tried to figure out how to hydrate a ValidationContext. I have workarounds for this, but my first attempt was to use the [GraphQLIgnore] attribute. That works like a charm on my server testing via BCP, but my WebAssembly app complains about the involvement of the shared framework. 

I am using a code-first implementation so nothing is ObjectType<blah>. It's just POCOs. I would rather not go to some explicit binding approach. I'm really asking if there's some way the GraphQLIgnore attribute to be moved to a lighter assembly so I can use it on my WebAssembly side. For now, I can use different package versions between the two, but it's really meant to be a common package for both client and server so maintenance will get ugly.

**Comment by compgumby** [comment]
My post is so lonely.... :(

**Comment by michaelstaib** [comment]
For questions like this head over to our community on slack.

http://bit.ly/joinchilli 

Or try GitHub discussions.

**Comment by michaelstaib** [comment]
I am closing this issue since it is not referring to a bug or improvement of cc.
