### ISSUE TITLE
Use Signed version of Neo4.Driver

### ISSUE THREAD

**Issue by jschioedtz** [ChilliCream/hotchocolate#3243]
First of all thanks for the super exiting amount of work that is done to support Neo4j in HotChocolate!

Would it be possible to use Neo4J.Driver.Signed instead of Neo4J.Driver in the nuget references?

https://github.com/ChilliCream/hotchocolate/blob/513b5d2db9eb03807351f4c45aa6097ef53b2da2/src/HotChocolate/Neo4J/src/Data/HotChocolate.Data.Neo4J.csproj#L18

When using the Neo4jClient 4.1.6 in the same project it creates a conflict between the signed and not signed version of the driver.

**Comment by arif-hanif** [comment]
@jschioedtz will look into this, want to make sure it doesn't cause problems the other opposite direction as well.

**Comment by arif-hanif** [comment]
@jschioedtz I plan on adding alot of the capabilities in Neo4J client to this library, is there a specific reason you are using Neo4JClient?

**Comment by jschioedtz** [comment]
Hi @arif-hanif. We are currently using the client to create all content in Neo4j from integration events on the message queue. This has been the case for a while and now we plan to use HotChocolate to expose this directly on a GraphQL endpoint - not directly adding content with mutations. 

We will have no problem in changing this behavior over time, but right now we are really looking forward to the release of your cool implementation and thus we will face a conflict in using it as it is right now.

I did build a version of the code with the signed version of the driver and I see no issues in that direction, but I guess there can be potential conflicts in other directions, though I still think the signed version is a better package.

**Comment by arif-hanif** [comment]
We will need to change Squadron as well, if we decide to go this direction. Once the OGM and last bit of filtering is complete  will look into this.

**Comment by jschioedtz** [comment]
So cool - please let me know if there is anything I might be able to help with :-)

**Comment by jschioedtz** [comment]
Hi @arif-hanif - I noticed this has been removed from To do. Does that mean that you will not support the signed driver in the coming release?

**Comment by jschioedtz** [comment]
This is unfortunate, but I have resolved by building the project with my own small modification to get it to work together with the official Neo4J client

**Comment by michaelstaib** [comment]
Why don't you do a PR?

**Comment by jschioedtz** [comment]
@michaelstaib simply because @arif-hanif has found that it is not the right solution for the standard product and I have to use the driver together with HC in my product. It works for me, but will perhaps not work for all

**Comment by jschioedtz** [comment]
We may move to mutations at some point but we are currently feeding Neo4J with our own cypher and thus we have to use the driver directly
