### ISSUE TITLE
StrawberryShake - Code generation fails on valid schema and query.

### ISSUE THREAD

**Issue by TeunKooijman** [ChilliCream/hotchocolate#3244]
**Describe the bug**
For the following schema and query, code generation does not run successfully. However, if the sub-query to `details { text }` is removed, it does work like it is supposed to.

**To Reproduce**
query:
```
query GetFeatById($id: Uuid!) {
	feats(where: {id: {eq: $id}}) {
		items {
			id,
			name,
			level,
			details {
				text
			}
		}
	}
}
```
schema:
 https://pf1e.io/api/graphql?sdl

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
- Version: 10
- StrawBerryShake: Preview 79
- Visual Studio: 2019 16.8.2

**Comment by michaelstaib** [comment]
This works with our internal build.

**Comment by TeunKooijman** [comment]
That would be what's coming in preview 80, you mean? Or it works on 79 for you?

**Comment by TeunKooijman** [comment]
You're right, this seems to work on preview 80. You can close the issue :).
