### ISSUE TITLE
StrawberryShake - Error is thrown when SortEnumType is null

### ISSUE THREAD

**Issue by Megasware128** [ChilliCream/hotchocolate#3262]
**Describe the bug**
A GraphQLClientException error is thrown when any SortEnumType is null

**To Reproduce**
1. Create a (...)SortInput parameter in GraphQL
2. Generate code
3. Execute and give a (...)SortInput object with one Asc value

**Expected behavior**
You should be able to sort just one field (or more) without having to give other SortEnumType fields a value.

**Desktop (please complete the following information):**
 - OS: Windows and WASM
 - Version 11.1.0-preview.80

**Additional context**
![image](https://user-images.githubusercontent.com/3170510/110962242-0b4b3580-8351-11eb-9f06-d6d36af46a2f.png)

**Comment by PascalSenn** [comment]
@Megasware128  Can you provide a schema + a query to reporduce this behaviour?

**Comment by PascalSenn** [comment]
I think this is fixed with #3323

**Comment by Megasware128** [comment]
Thx for getting back to me. I'll try the pr tomorrow. If it fails I'll try to reproduce a simple schema and query. Otherwise I will let you know if the fix works.

**Comment by Megasware128** [comment]
@PascalSenn I've tried running the code against #3323. It got me a new error.
![image](https://user-images.githubusercontent.com/3170510/111974384-a5547000-8aff-11eb-85e4-b6831330f516.png)
These are the schema and query throwing the error: 
https://gist.github.com/Megasware128/9b20f857d0b8a27c3cc003848525b667
https://gist.github.com/Megasware128/8f97bd023544d14ad3d9b936789c4f4a

After that I'm calling the query by:
`var result = await Client.GetArticles.ExecuteAsync((page - 1) * 10, new ArticleSortInput { ArticlePrice = SortEnumType.Desc });`

**Comment by Megasware128** [comment]
Stack trace of Errors[0] is:
![image](https://user-images.githubusercontent.com/3170510/111975424-ded9ab00-8b00-11eb-86c2-1d0ac68d98bf.png)

**Comment by Megasware128** [comment]
@PascalSenn  It seems the issue is resolved on the StrawberryShake layer in at least version [11.1.0-rc.4](https://github.com/ChilliCream/hotchocolate/releases/tag/11.1.0-rc.4). Now HotChocolate on the server is still throwing errors for sort input values being null. Should I open a new issue for HotChocolate?

**Comment by Megasware128** [comment]
Issue seems to be fixed for me since at least 11.2.2
