### ISSUE TITLE
Querying relationship ID was not converted to relay string ID 

### ISSUE THREAD

**Issue by shidcordero** [ChilliCream/hotchocolate#3280]
**Describe the bug**
Querying ID of a relationship was not converted into a relay ID, but querying ID in the object itself is showing correctly. Is there a way to also convert those ID in relay?

**To Reproduce**
heres the query and code

![image](https://user-images.githubusercontent.com/26376208/111092366-d9b0b500-8570-11eb-8b30-d1302a78db78.png)

![image](https://user-images.githubusercontent.com/26376208/111092428-0664cc80-8571-11eb-9a01-0c741e63a107.png)

**Expected behavior**
should return it like this

`    "data": {
        "locations": {
          "nodes": [
            {
              "id": "TG9jYXRpb24KaTE0",
              "name": "Silay City",
              "locationTypeId": "TG9jYXRpb25UeXBlCmkx",
              "locationType": {
                "id": "TG9jYXRpb25UeXBlCmkx"
              }
            },`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Pro

**Comment by PascalSenn** [comment]
Yes, i think this should work
Code First:
```
descriptor.Field(x => x. LocationTypeId).ID();
```
annotation based:
```
[ID]
public int LocationTypeId { get; set; } 
```

**Comment by shidcordero** [comment]
![image](https://user-images.githubusercontent.com/26376208/111163604-35625900-85d8-11eb-8586-e94d672caf2b.png)

@PascalSenn tried it and it returns different values

**Comment by PascalSenn** [comment]
ID takes by default the type name the field is attached to
If this id denotes the LocationType you have to pass the typename to `ID`

**Comment by shidcordero** [comment]
@PascalSenn  works great. thank you so much. closing the ticket.
