### ISSUE TITLE
BatchDataLoader fetch called twice when it should be called once.

### ISSUE THREAD

**Issue by mcuzmenco** [ChilliCream/hotchocolate#3299]
**Describe the bug**
`BatchDataLoader`'s fetch function is called at least twice.

**To Reproduce**
I created a repo with the test, which reproduces behavior. https://github.com/mcuzmenco/BatchDataLoaderBug
Run the `UnitTest1`. 

**Expected behavior**
I expect that fetch function is called just once on `LoadAsync`, but **sometimes**(every second or third time) it's called twice.
It's a big issue, when you are trying to use `DbContext` underneath, as it's initiating a second parallel operation on `DbContext` which is leading to the exception.

**Desktop (please complete the following information):**
- Windows 10
- HotChocolate 11.0.9

**Comment by mcuzmenco** [comment]
Hey I wanted to add more details to this.
Narrowed done the problem a bit.

The issue is reproducible only if `await` some other task is called *before* the `await context.BatchDataLoader(..).LoadAsync()`;

I.e. 
```csharp
public async Task<IReadOnlyList<Book>> GetBooks(IResolverContext context)
{
	requestCount = 0;
	var ids = Enumerable.Range(0, 100).ToImmutableList()

    // if await is present the error is likely to happen
    // if it's omitted all good
	await Task.Delay(1);

	var books = await context.BatchDataLoader(
		async (IReadOnlyList<int> bookIds, CancellationToken t) => {
			Interlocked.Increment(ref requestCount);
			if (requestCount > 1)
			{
				throw new Exception("Nope!");
            }

            // ... get some result
			
			return result;
		}).LoadAsync(ids, context.RequestAborted)
	return books.ToList();
}
```

**Comment by mcuzmenco** [comment]
Still reproducible on HC `11.1`

**Comment by nigel-sampson** [comment]
Adding some extra data here, the delegate for the data loader is being called multiple times . However it's because the batch of 100 keys is being split into two batches which is the unexpected behavior, especially given there is effectively only a single field attaching a batch of values.
