### ISSUE TITLE
ExecutionTimeout has no effect

### ISSUE THREAD

**Issue by ewarwick** [ChilliCream/hotchocolate#3310]
**Describe the bug**
Execution timeout setting has no effect; the cancellation token injected into resolvers never reads as cancelled.

**To Reproduce**
configure the server and timeout
```
services.AddGraphQLServer().ModifyRequestOptions(o=>o.ExecutionTimeout = TimeSpan.FromSeconds(1))
                .AddQueryType<Query>().AddFiltering().UseDefaultPipeline();
```
make a resolver, w/ cancellation token
```
    public async Task<string> FetchThing(CancellationToken tok )
        {
            
            await Task.Delay(TimeSpan.FromSeconds(3),tok);
            tok.ThrowIfCancellationRequested();
            return "foo";
        }
```
upon querying the resolver, the code runs, waits, and completes without the token requesting cancel. The exception is not thrown, and I verified with the debugger that the cancellation requested boolean is never set to true.

**Expected behavior**
I would expect that the configured execution timeout be honored, and that the cancellation token should show cancellation requested after one second.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 11.0.9
 - .NET 5.0.201
 - Kestrel

**Additional context**
From what I have found in the docs/migration guide, the repro steps should be sufficient to have the token cancel. I have additionally tried:
* compiling in 'release' configuration
* changing my asp environment away from 'Development' to 'Production'
* adding `services.AddMvcCore();`
* adding the `[Service]` to the resolver parameter
* removing my configured timeout; even the built-in default of 30 seconds is not cancelling the query
* I am able to configure max query depth with no issues

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/issues/3110

**Comment by michaelstaib** [comment]
There is a min time we set

**Comment by michaelstaib** [comment]
It’s 100 milliseconds so your 1 second should work.

**Comment by ewarwick** [comment]
After reviewing that ticket you linked; I rearranged the configuration code to be as similar as possible to the other person:
```
     public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<KestrelServerOptions>(options => { options.AllowSynchronousIO = false; });
            services.AddGraphQLServer()
                .AddQueryType<Query>().UseDefaultPipeline()
                .ModifyRequestOptions(o => o.ExecutionTimeout = TimeSpan.FromSeconds(1))
                .ModifyOptions(x => x.SortFieldsByName = true)
                .AddConvention<INamingConventions>(new DefaultNamingConventions());
            services.AddCors();
            services.Configure<RequestLocalizationOptions>(options => { options.SetDefaultCulture("en-US"); });
            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        }
```
resolver is the same as in my original post, and I've explicitly DISABLED the Synchronous IO that seemed to be the issue in the other ticket just to be absolutely certain. 
No change; the token is never cancelled. Am I  misunderstanding what is meant by 'honoring the cancellation token' ? I think that it should be throwing that exception, or at minimum I should see in the debugger that cancellation was requested.

**Comment by ewarwick** [comment]
Until/unless this gets resolved; I am resorting to the workaround below so that our API is not vulnerable to unbounded queries. Thought I would share in case others have the same issue.

Note that the request middleware is before the default pipeline; this is important so that the token gets assigned a timeout before the resolvers actually start firing. This seems dirty, but I reckon it is better than unbounded queries as long as we don't turn up any problems during testing.
```
services.AddGraphQLServer().AddQueryType<Query>().UseRequest(next=> context =>
                {
                    CancellationTokenSource s = new CancellationTokenSource();
                    s.CancelAfter(QueryTimeoutMs);
                    context.RequestAborted = s.Token;
                    return next(context);

                }).UseDefaultPipeline()
```

**Comment by michaelstaib** [comment]
>   services.Configure<KestrelServerOptions>(options => { options.AllowSynchronousIO = false; });

this was not the issue in the other ticket. It was just a remark.

**Comment by michaelstaib** [comment]
```
services.AddGraphQLServer().AddQueryType<Query>().UseRequest(next=> context =>
                {
                    CancellationTokenSource s = new CancellationTokenSource();
                    s.CancelAfter(QueryTimeoutMs);
                    context.RequestAborted = s.Token;
                    return next(context);

                }).UseDefaultPipeline()
```

This code will create a few other issues for you since now ASP.NET core is unable to cancel work anymore. Meaning if HTTP calls are canceled this is ignored.

**Comment by michaelstaib** [comment]
also you should at leas dispose `s`

**Comment by michaelstaib** [comment]
But I confirm this is a Bug.

**Comment by michaelstaib** [comment]
mst/timeout
