### ISSUE TITLE
Move scalars from HotChocolate.Types.Scalars to HotChocolate.Types

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#3317]
The namespace HotChocolate.Types.Scalars collides with this class :https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types/Types/Scalars/Scalars.cs 

All scalars in the package HotChocolate.Types.Scalars should go into the namespace HotChocolate.Types

```csharp
namespace HotChocolate.Types.Scalars 
{
...
```

```csharp
namespace HotChocolate.Types
{
...
```

**Comment by wonbyte** [comment]
https://github.com/ChilliCream/hotchocolate/pull/3320
