### ISSUE TITLE
[StrawberryShake] Schema is not downloaded correctly

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3327]
**Describe the bug**
Downloading the schema via `dotnet graphql init` or `dotnet graphql update` produces an incomplete `schema.graphql` file.

[This](https://gist.githubusercontent.com/tobias-tengler/6785572f001a3ecc0f0e128970b79544/raw/8c7831b1b577f7eb74a4a69b21a6eb8b6815050d/schema.graphql) is what's being correctly returned running `curl <url>?sdl`. (HotChocolate 11.1.0-preview.86 is used for the Server-side)

[This](https://gist.githubusercontent.com/tobias-tengler/d96688f6781ba2b193c88bae5137610c/raw/894ae50554c62256a76a4f1df7e9d84b21c7236f/schema.graphql) is what's being incorrectly written to the `schema.graphql` file running any of the aforementioned commands.

**To Reproduce**
Since this has to do with downloading the schema from a server, I sadly can't provide a (public) way for you to reproduce this. :(
But you can check out the StrawberrryShake configuration I used [here](https://github.com/tobias-tengler/strawberrryshake-issue-repro).

**Expected behavior**
The schema should be the same as the one returned using curl.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 11.1.0-preview.86

**Comment by PascalSenn** [comment]
@tobias-tengler  Are you targeting dotnet 6? If so they have a bug in the stream writer

**Comment by tobias-tengler** [comment]
@PascalSenn I was indeed. Locked it to 5.0 and now it works like a charm! :)
