### ISSUE TITLE
How the delegate to a local schema at gateway to merge remote and local type

### ISSUE THREAD

**Issue by bromix** [ChilliCream/hotchocolate#3330]
Our gateway (graphql-tools with TypeScript) takes a remote schema and extends one type by some additional fields. I have to mention that our project (gateway) runs as a local service on a PC and gets data from a server but can only attach more information locally from the operating system (e.g. if a product is installed locally on the PC or currently running). We would love to switch to HotChocolate, but we don't know how to achive the same result.

In the examples it is explained how with _AddTypeExtensionsFromFile(...)_ and _Delegates_ this is solved among the services. But nothing seems to fit for our problem?

I have put together a small example project where a remote schema is loaded and the Query is extended by _Book_ and the _Author_.
[hotchocolate-type-merging](https://github.com/bromix/hotchocolate-type-merging)

Additionally I try to extend the type **Album** from the remote schema with **myCustomField**. My question now is how do I resolve myCustomField?

We know how to do this with graphql-tools with TypeScript (merge remote and local schema), but unfortunately we have no idea how we can solve this with HotChocolate.

**Comment by bromix** [comment]
Okay, I see there is a function AddLocalSchema(<NAME>). I have looked at the TestCases. I haven't quite figured out how to define a LocalSchema similar to the RemoteSchema. But after that I can then use the delegates to have the new field resolved?

**Comment by michaelstaib** [comment]
https://bit.ly/joinchilli

**Comment by bromix** [comment]
```
/*
Setup local schema. The local schema provides some root
queries of its own and also extends a remove type (Ablum).
*/
services
.AddGraphQLServer("myschema")
.AddType<Query>();

/*
Add local and remote (stitch) schema.
The extension file will provide information about the
delegation of the extended type (custom field).
*/
services
.AddGraphQLServer()
.AddRemoteSchema("almansi")
.AddLocalSchema("myschema")
.AddTypeExtensionsFromFile("./Extensions.graphql");
```

I think I got it now. Someone else asked the same question in Slack. After some trial and error I got it to work. Now I can extend a remote type with a custom field.

I also updated the sources of my example project.

Thanks for the help :)
