### ISSUE TITLE
Query until filter is find

### ISSUE THREAD

**Issue by shidcordero** [ChilliCream/hotchocolate#3332]
**Is your feature request related to a problem? Please describe.**
I need to find a specific item in my query but I also need to return the previous value.
For example, I have a list sorted by name:
i have the following data: [a, b, c, d, e]
in my query I need to get 'c' so the return should be [a, b, c]

Is there a way to do it in HotChocolate?

Use case of this is I have a lazy loaded dropdown, and I need to get all the items before the selected one.

**Describe the solution you'd like**
An annotation or something alike that can help with my issue

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelstaib** [comment]
Have you tried cursor pagination ... where a cursor represents the item?

**Comment by shidcordero** [comment]
@michaelstaib I'm not sure what you mean but here is exactly what my queries are.
`       [UseDbContext(typeof(PlatformContext))]
        [UsePaging]
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Country> Countries([ScopedService] PlatformContext context)
        {
            return context.Countries;
        }`

**Comment by PascalSenn** [comment]
This should not matter as you sort the results
if you query a second time with the cursors and the same sorting, you get the items in the same order back, but only after the current cursor

**Comment by TDDinAction** [comment]
> I tried the { before: "" }

If you already have implemented class CountryType :  : ObjectType<Country>, you need drop [UseProjection] attribute.
Also before you can use "before", you need to reed cursor of each element.

query {
  countries(first : 5) {
      edges {
        cursor
        node {
          id
        }
      }
  }
}

For example, cursor for "c" was "MQ==". So, your next request must be like this:

query {
  contacts(before : "MQ==", last : 3) {
      edges {
        cursor
        node {
          id
        }
      }
  }
}
