### ISSUE TITLE
Unable to Have Custom Name/Description for Query/Mutation

### ISSUE THREAD

**Issue by RehanSaeed** [ChilliCream/hotchocolate#3334]
**Describe the bug**
Unable to give Query, Mutation or Subscriptions a custom Name or Description.

**To Reproduce**

If I have the following Query class:

```cs
services
    .AddGraphQLServer()
    .AddQueryType<QueryObject>();

public class QueryObject : ObjectType<QueryResolvers>
{
    public QueryObject()
    {
        this.Name = "Query";
        this.Description = "The query type, represents all of the entry points into our object graph.";
    }

    protected override void Configure(IObjectTypeDescriptor<QueryResolvers> descriptor)
    {
        // ...
    }
}
```

The schema generated has a query type named `QueryResolvers` which is the name of the generic resolver type and the description is null.

**Expected behavior**

I want to be able to set a custom name `Query` and description. As a workaround, I suppose I could rename `QueryResolvers` to `Query` but I would still be missing the description. I believe this used to work in v10.

**Desktop (please complete the following information):**
 - OS: Windows
 - Hot Chocolate v 11

**Comment by michaelstaib** [comment]
:)
