### ISSUE TITLE
Enum description is ommited

### ISSUE THREAD

**Issue by rafaelldi** [ChilliCream/hotchocolate#3335]
Hello. 
I have an issue with `EnumType`. I want to add a description to each enum value:
```csharp
public enum Number
{
    One,
    Two,
    Three
}

public class NumberType : EnumType<Number>
{
    protected override void Configure(IEnumTypeDescriptor<Number> descriptor)
    {
        descriptor.Value(Number.One).Description("One");
        descriptor.Value(Number.Two).Description("Two");
        descriptor.Value(Number.Three).Description("Three");
    }
}

services
    .AddGraphQLServer()
    .AddEnumType<NumberType>();
```

But in this case, a `HotChocolate.SchemaException` is thrown. `1. The enum type NumberType has no values. (HotChocolate.Types.EnumType<GraphQL.NumberType>)`

Is it a bug, or I'm missing something? The version of `HotChocolate.AspNetCore` is 11.0.9.

Thanks.

**Comment by luizhennemann** [comment]
Hi, What is the outcome of this? I am having the same issue. Not able to add any EnumType 

.AddEnumType<EnumType>();

It always gives me an error.

Thanks.

**Comment by michaelstaib** [comment]
It’s wrongly used. But the error message is bad

**Comment by michaelstaib** [comment]
I will add more Info to this issue tomorrow

**Comment by michaelstaib** [comment]
So,

```csharp
.AddEnumType<NumberType>();
```

is the equivalent of

```csharp
.AddType<EnumType<NumberType>>();
```

Meaning now your type is doubly wrapped.

You can either do 

```csharp
.AddEnumType< Number>(d => 
{
        descriptor.Value(Number.One).Description("One");
        descriptor.Value(Number.Two).Description("Two");
        descriptor.Value(Number.Three).Description("Three");
});
```

or

```csharp
.AddType<NumberType>();
```

**Comment by michaelstaib** [comment]
I can recommend joining us on slack since you get a quicker answer to questions there. Issues have a longer cycle time.

You can join here: https://bit.ly/joinchilli

**Comment by luizhennemann** [comment]
Hi,

Thanks for your answer.
Sorry, my example was incorrect. What I meant, and is not working is like that:

I created an enumType similar to that:
public class NumberType : EnumType<Number> {}

And when I add that type like that:
.AddEnumType<NumberType>();

It raises and error on BananaCakePop. It doesn't even reach the app. It gives me a 500 Server Error. If I remove the AddEnumType it works properly again, but then I don't have the enum mapping.

**Comment by PascalSenn** [comment]
@luizhennemann

```.AddEnumType< Number >();```
is the equivalent of
```.AddType<EnumType<Number>>();```


if you do
```
.AddEnumType<NumberType>();
```

You end up doing
```
.AddType<EnumType<NumberType>>();
```

Which will be 
```
.AddType<EnumType< EnumType <Number>>>();
```

If you just do
```
.AddType<NumberType>()
```

you should be fine
