### ISSUE TITLE
StrawberryShake dotnet tool returns exitcode 1 when succesful

### ISSUE THREAD

**Issue by Megasware128** [ChilliCream/hotchocolate#3336]
**Describe the bug**
While there are no errors `dotnet-graphql update` returns exit code 1 indicating an error has happened after being succesful

**To Reproduce**
Execute `dotnet-graphql update` and read the exit code

**Expected behavior**
When executing `dotnet-graphql update` should return exit code 0

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11.1.0-preview.89

**Additional context**
Issue seems to be the call to UpdateSchemaAsync. It has a local variable named [hasErrors](https://github.com/ChilliCream/hotchocolate/blob/0924116ccf52306cc2437b4bc5ec6d709a39b413/src/StrawberryShake/Tooling/src/dotnet-graphql/UpdateCommandHandler.cs#L103) which will be returned by UpdateSchemaAsync. When no errors have happend hasErrors stays false so UpdateSchemaAsync will also return false which in turn makes the code execution reach return 1:
![image](https://user-images.githubusercontent.com/3170510/112152134-3c91f400-8be2-11eb-8f61-98990c11ff69.png)

**Comment by michaelstaib** [comment]
Do you want to do a PR?
