### ISSUE TITLE
Add a boolean property indicating whether to stop debugging in Debug mode if an GraphQLException is thrown.

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3345]
There is possibility to throw exaptation in the resolver of the ObjectType:

throw new GraphQLException(ErrorBuilder.New()
                .SetMessage("Some msg.")
                .SetCode("201")
                .Build());

This is very informative. But at the same time, there are cases when the request is almost successful and we just add a message explaining the result without stopping debugging. It needs add metadata message and code, but then prevent further generation of the error itself.

At first glance, this is a rather strange proposal, but we must return the result corresponding to the field type, but not a wrapper like IActionResult (judging by FieldCollection class that accepts only input parameter IEnumerable<T>, now this is not possible). Therefore, I believe such feature will be very useful at least as a temporary solution, since an alternative solution with a wrapper will be a very large change affecting backward compatibility issues.

**Comment by michaelstaib** [comment]
`context.ReportError` can issue non terminating errors.

**Comment by TDDinAction** [comment]
> `context.ReportError` can issue non terminating errors.

Thanks a lot, this is exactly what I need.
