### ISSUE TITLE
Strawberry Shake fails to generate node query with `__typename`

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/hotchocolate#3353]
# Strawberry Shake fails to generate node query with `__typename`

Strawberry Shake 11.1.0-rc.2

ref: [Slack thread](https://hotchocolategraphql.slack.com/archives/CMUJ40EHJ/p1616611890087800)

## Summary

Strawberry Shake fails to generate code for the node query:

```
query Nodes($id: ID!) {
  node(id: $id) {
    __typename
    id
  }
}
```

## Steps to reproduce

Please find attached the sample project.

Change to its directory and run

    dotnet build

## Actual result

The build fails:

```
CSC : error SS0006: An error occurred during generation: The given key '__typename' was not present in the dictionary. [C:\tmp\_210325_9p-HCSS\My.GraphQL.Test.csproj]
C:\tmp\_210325_9p-HCSS\BaseClientTest.cs(3,10): error CS0234: The type or namespace name 'Client' does not exist in the namespace 'My' (are you missing an assembly reference?) [C:\tmp\_210325_9p-HCSS\My.GraphQL.Test.csproj]
C:\tmp\_210325_9p-HCSS\BaseClientTest.cs(17,19): error CS0246: The type or namespace name 'MyClient' could not be found (are you missing a using directive or an assembly reference?) [C:\tmp\_210325_9p-HCSS\My.GraphQL.Test.csproj]
    0 Warning(s)
    3 Error(s)
```

## Expected result

The build succeeds and generates relevant code.

## Workaround (?)

Comment out `__typename` in `GraphQL\Resources\Nodes.graphql`.

***

[_210325_9p-HCSS.zip](https://github.com/ChilliCream/hotchocolate/files/6202675/_210325_9p-HCSS.zip)

**Comment by nightroman** [comment]
It does not fail anymore, great. But it does not generate anything for `__typename` in the result, is this expected?

**Comment by michaelstaib** [comment]
This one is now fixed.
