### ISSUE TITLE
Sorting and filtring metatata are not embedded for fields that use ResolveWith

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3356]
Sorting and filtring metatata are not embedded for fields that use ResolveWith. HotChocolate version 11.1.0-rc.2.

Code:

[UseDbContext(typeof(Context))]
    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Master> GetMasters([ScopedService] Context context)
    {
        return context.Masters;
    }
    
    public class MasterType : ObjectType<Master>
    {
        descriptor.Field(p => p.Name)..Description("Some field from Entity");
        descriptor.Field("calc").ResolveWith<Resolvers>(p => p.GetCalc(default!, default!)).UseDbContext<Context>();
    }

    private class Resolvers
    {
        public string GetCalc (Master master, [ScopedService] Context context)
        {
            return context.Calcs.Where(p => p.MasterId == master.Id);
        }
    }

Description:
Sorting and filtring works perfect if do this by field "name", but not by "calc". There is not "calc" in metadata for "order".  Field "Calc" not present in the table "Master", but it successfuly calulated by resolver and has string type as well as field "Name".

query {
  masters(order : {calc :  ASC}) {
      edges {
        cursor
        node {
          id
        }
      }
  }
}

Also trying to add to descriptor "calc" of extension methods .UseFiltering().UseSorting(), leads to error "Unexpected token H in JSON at position 0".

**Comment by damikun** [comment]
By Default There is not and that is correct...  because filters are generated from objects not from graphql schema type...

When you call UseFiltering, HC scans that underling objects for all public props that can be fields and if they fit some requirements than make them a filter...

**Comment by TDDinAction** [comment]
> There is not and that is correct... because filters are generated from objects not from graphql schema type...
> 
> By doing `descriptor.Field("calc")` you extends schema type not object itself... So Filtering part have no idea there is something like _"calc"_ This schema extension is just abstraction on top of objects.. **At the end filter must be translated to real object...** and if field does not exist in source object HC cannot translate it to Queriable or linq **by default**...
> 
> When you call UseFiltering, HC scans **by default** that underling objects for all public props that can be fields and if they fit some requirements than make them a filter...

Thank for the information, but UseFiltering and UseSorting set on GetMasters which has return type IQueryable. There are same type "String" for "name" and "calc" in the Schema. Also I tried to add .Type<StringType>() to descriptor "calc" and to change return type for method GetCalc to StringType, it does not affect the result. In my opinion, this difference is due to the order in which the middleware is applied, which adds metadata.

**Comment by TDDinAction** [comment]
> There is not and that is correct... because filters are generated from objects not from graphql schema type...
> 
> By doing `descriptor.Field("calc")` you extends schema type not object itself... So Filtering part have no idea there is something like _"calc"_ This schema extension is just abstraction on top of objects.. **At the end filter must be translated to real object...** and if field does not exist in source object HC cannot translate it to Queriable or linq **by default**...
> 
> When you call UseFiltering, HC scans **by default** that underling objects for all public props that can be fields and if they fit some requirements than make them a filter...

Thank for the information, but UseFiltering and UseSorting set on GetMasters which has return type IQueryable. There are same type "String" for "name" and "calc" in the Schema. Also I tried to add .Type() to descriptor "calc" and to change return type for method GetCalc to StringType, it does not affect the result. In my opinion, this difference is due to the order in which the middleware is applied, which adds metadata.

**Comment by TDDinAction** [comment]
> by default

Regarding the manual https://chillicream.com/docs/hotchocolate/v10/data-fetching/pagination there are only samples for version v10, but not for v.11.1. Could you provide some example how can I do that?

**Comment by TDDinAction** [comment]
> Docs are under writing for V11 you can for now looks on sources code which helps usually the most or look on official workshop

Ok, thanks a lot)
