### ISSUE TITLE
[Banana Cake Pop] Ignores "Cookie" HTTP header

### ISSUE THREAD

**Issue by wojciechrak** [ChilliCream/hotchocolate#3367]
**Describe the bug**
I know, that BCP does not support Cookies per se, but it even does not work, when setting an HTTP header manually.
Having set following HTTP headers:
```
{
  "Cookie": "somecookie=ok",
  "Other-Header": "loremipsum"
}
```
in the Results pane it even shows this header
![image](https://user-images.githubusercontent.com/3034230/112630903-883cdb80-8e36-11eb-87ce-569f15318ce8.png)
but it is not present in the actual HTTP request (checked with Fiddler proxy, as well as debugging web server)

**To Reproduce**
1. Open BCP, open additional query settings with HTTP headers tab
2. Add `Cookie` header with some value
3. Send request
4. Check actual http request with http debugging proxy or log it on webserver etc

**Expected behavior**
`Cookie` header should be passed in request to web server

**Desktop:**
Banana Cake Pop hosted on `/graphql` endpoint on ASPNetCore app (HotChocolate 11.0.9)

**Comment by rstaib** [comment]
I guess it's working as it's supposed to. Third-party cookies are blocked in chrome and probably other browsers too. The cookie need to be set by your server, which is HotChocolate. Then you need to set the Credentials to Same-Origin.

![image](https://user-images.githubusercontent.com/4325318/116472746-9a1aff80-a876-11eb-8bfb-0d3cec95b44f.png)

**Comment by sadogeri** [comment]
Banana Cake Pop App does not set cookies in version 14

**Comment by JUSTIVE** [comment]
same problem here.
