### ISSUE TITLE
Node field in dynamic types return the wrong id  

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#3371]
so I have an app where i read some type description (TSchema) from a db and for each type description i register it with the ConcreteItemType<TSchema> class
the last line adds custom fields for each type.. the ones above are shared fields..
```
public class ConcreteItemType<TSchema> : ObjectType<DynamicItem>
    where TSchema : ConcreteItem
{
    protected override void Configure(IObjectTypeDescriptor<DynamicItem> descriptor)
    {
        descriptor.BindFieldsExplicitly();
        descriptor.Name(typeof(TSchema).Name.FirstCharToUpper());
        descriptor
            .ImplementsNode()
            .IdField(f => f.Id)
            .ResolveNode(async (context, id) =>
            {
                   return GetItemById(id);
            });     
        descriptor.Field(f => f.ChangeDate)
            .Resolve(ctx => ctx.Parent<IItem>().ChangeDate)
            .Type<NonNullType<CustomDateTimeType>>();
        descriptor.Field(f => f.ChangeUser)
            .Resolve(ctx => ctx.Parent<IItem>().ChangeUser)
            .Type<NonNullType<StringType>>();
        descriptor.Extend()
            .OnBeforeCreate(ConcreteFieldsBuilder<TSchema>.AddConcreteFields<DynamicItem>);
    }
}
```
now, everything seems absolutely fine.. i even debugged thourgh the HC NodeFieldTypeInterceptor resolver and the type as well as the deserialized id is correct

however for some reason when i query the node field with a particular id .. i am getting the wrong type and id

I pushed a simplified working sample that showcases the issue here 
https://github.com/MariaCobretti/HotChocolateSample/tree/master/HotChocolateSample

with some queries

```
query Buildings {
  buildings {
    __typename
    id
    address
  }
}

query Flats {
  flats {
    __typename
    id
    owner
  }
}

query Node {
  node(id: "RmxhdApkMQ==") {
    __typename
    id
  }
}
```

the Node query returns a Flat object but the type thats returned is Building

**Comment by michaelstaib** [comment]
Intersting :)

I will have a look at it.

**Comment by MariaCobretti** [comment]
any insight on this? I thought I read something in slack about a ID field implementation redesign.. I can wait till then for this issue

**Comment by MariaCobretti** [comment]
I was just looking at this again today and got some additional insight..

the node field returns the correct id and __typename when I build the type as follows
public class ConcreteItemType<TSchema> : ObjectType<TSchema>

however, the object returned from my database is not TSchema but rather TEntity (or as in the example above DynamicItem).
So when doing ObjectType<TSchema> querying the id field gets an exception "parent cannot be cast to TSchema"
Both types (TSchema and TEntity) implement a common interface (IItem, just like the the github example thats linked)

with ConcreteItemType<TSchema> : ObjectType<IItem>
in v11.3.1-rc2 querying the id fields throws an exception instead of returning the wrong type, probably related to the changes in #3855
