### ISSUE TITLE
Query and Field Middleware

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#338]
We currently support field middleware via directives. We now also want to be able to modify the default field resolver middleware. Moreover, we should support a query middleware that basically is executed for the whole query. This can be used to modify or extend the query result itself.

**Comment by michaelstaib** [comment]
We should introduce two more middleware types to the currently available directive middleware. 

The directive middleware is already available and can replace the default field resolver middleware whenever a field is annotated with an executable directive. 

DirectiveMiddleware->FieldResolver

```csharp
 public delegate DirectiveDelegate DirectiveMiddleware(
        DirectiveDelegate next);
```

The field middleware can extend the global field resolver pipeline. This is useful for things that shall extend the field resolver pipeline of all fields.

With directive middleware:

FieldMiddleware->DirectiveMiddleware->FieldResolver

Without directive middleware;

FieldMiddleware->FieldResolver

```csharp
 public delegate FieldDelegate FieldMiddleware(
        FieldDelegate next);
```

The query middleware allows to extend the execution of a query request. This can be used to splice or merge query execution.

```csharp
 public delegate QueryDelegate QueryMiddleware(
        QueryDelegate next);
```

**Comment by michaelstaib** [comment]
Executable directives on operations will be enabled with this issue.

**Comment by akaSybe** [comment]
Probably it blocks Apollo Tracing support (#352)

**Comment by akaSybe** [comment]
@michaelstaib sure, I did some research and this part of Apollo Tracing specification made me doubt:

> Resolver timings should be collected in nanoseconds using a monotonic clock

Need to investigate if there is support of monotonic clock in .NET or we can use regular DateTime.

**Comment by michaelstaib** [comment]
Yeah, If you search for the java class than you will find some suggestions how to do that in .net.

**Comment by michaelstaib** [comment]
The DateTime was reworked so it has in .net core a much higher resolution. Microsoft is using that with its DiagnosticSources for that reason.

**Comment by michaelstaib** [comment]
The execution engine is now completely rewritten. The execution engine can now be customized and build with the `QueryExecutionBuilder`

We can now create our default executer like the following:

```csharp
IQueryExecuter executer = QueryExecutionBuilder.BuildDefault(schema)
```

This basically sets up the default execution engine for the given schema.

But I could also change the behavior of this by expanding this:

 ```csharp
IQueryExecuter executer = QueryExecutionBuilder.New()
   .AddQueryParser(customParser)
   .UseDefaultPipeline()
   .Build(_schema);
```

This basically uses the default pipeline with a custom query parser.

If I wanted to change the execution pipeline itself I could expand again:

 ```csharp
IQueryExecuter executer = builder.UseDiagnostics()
                .UseExceptionHandling()
                .UseQueryParser()
                .UseValidation()
                .Use(next => context => 
                {
                    // custom middleware code 
                })
                .UseOperationResolver()
                .UseOperationExecuter();
```
