### ISSUE TITLE
Can't find description of methods in HotChocolate.AspNetCore

### ISSUE THREAD

**Issue by Chameleon45** [ChilliCream/hotchocolate#3382]
I already wrote this question on StackOverflow, so I will duplicate it here for better tracking of the problem.

_"I installed HotChocolate.AspNetCore package (v. 11.0.9) for my project via NuGet in Visual Studio. While writing methods names or hovering on them I can't see what these methods actually do. I went to some classes to check if there were any summary tags but I didn't see anything. So my question is: does this graphql package have any description of methods at all and if so, how can I "install" it?"_

Actually, in this short term, I managed to use only a small part of these methods, and here are some of them: service extensions methods (AddGraphQLServer, AddQueryType, AddMutationType), endpoint extensions method MapGraphQL and methods of descriptor object (Field, Type, Description, Argument etc.). All of them work pretty fine but it would be easier to write code with description.
Maybe I'm doing something wrong :\ ?

**Comment by michaelstaib** [comment]
Thanks for reporting

**Comment by michaelstaib** [comment]
This is now updated in v12
