### ISSUE TITLE
Projections do not work correctly with field aliases

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#3390]
**Describe the bug**
When you have two field where one is an alias to the second one and projections enabled, you'll get execution error if you try to use the aliased name in request.

**To Reproduce**
I have this type
```csharp
public class ItemCatalogType : ObjectType<ItemCatalog>
{
    protected override void Configure(IObjectTypeDescriptor<ItemCatalog> descriptor)
    {
        descriptor.Field(x => x.OldDbId).Type<NonNullType<StringType>>()
            .Deprecated("Use databaseId instead").IsProjected();
        descriptor.Field("databaseId").Type<NonNullType<StringType>>()
            .Resolve(ctx => ctx.Parent<ItemCatalog>().OldDbId);
    }
}
```

As you can see `OldDbId` field is projected and `databaseId` is basically just an alias to that field. If I do the request like that all is working fine.
```
query getItemCatalogs($tenantId: Uuid!, $userId: Uuid!) {
  documents: itemCatalogs(tenantId: $tenantId, userId: $userId) {
    nodes {
      itemCatalogNo
      databaseId
      description
      externalComment
    }
  }
}
```

It also works fine if I use the obsolete property name
```
query getItemCatalogs($tenantId: Uuid!, $userId: Uuid!) {
  documents: itemCatalogs(tenantId: $tenantId, userId: $userId) {
    nodes {
      itemCatalogNo
      oldDbId
      description
      externalComment
    }
  }
}
```

However, if I assign `oldDbId` as an alias to `databaseId` in my request the field is ignored in the projection and my call fails as I marked it as non-nullable.

```
query getItemCatalogs($tenantId: Uuid!, $userId: Uuid!) {
  documents: itemCatalogs(tenantId: $tenantId, userId: $userId) {
    nodes {
      itemCatalogNo
      oldDbId: databaseId
      description
      externalComment
    }
  }
}
```

```json
{
      "message": "Cannot return null for non-nullable field.",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "documents",
        "nodes",
        0,
        "oldDbId"
      ],
      "extensions": {
        "code": "EXEC_NON_NULL_VIOLATION"
      }
    }
```

I've also checked in SQL (EF) and indeed in the last example OldDbId is not on SELECT list.
```sql
SELECT TOP(@__p_3) [i0].[ItemCatalogNo], [i0].[Description], [i0].[ExternalComment] FROM ...
```

**Expected behavior**
All previously mentioned queries should return correct data

**Desktop (please complete the following information):**
 - Version HC 11

**Comment by PascalSenn** [comment]
At the moment it is not possible to directly express this relation
But you can always include this field 
```
        descriptor.Field(x => x.OldDbId).Type<NonNullType<StringType>>()
            .Deprecated("Use databaseId instead").IsProjected(true);
```

**Comment by RaYell** [comment]
@PascalSenn the only difference I see in your code snippet is adding `true` parameter to `IsProjected` method, which is the default value for `IsProjected` anyways. As I described above, this does not work but only in one particular case when I try to assign the alias of  "oldDbId" to the new name in the query.

**Comment by PascalSenn** [comment]
ah, I see, will have a look
