### ISSUE TITLE
Breaking change with filtering when upgrading from 11.0.9 to 11.1

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#3391]
**Describe the bug**
I've upgraded from 11.0.9 to 11.1 which is supposed to be backwards compatible, then I've updated Filters and Sorters to use `HotChocolate.Data` as suggested by obsolete method warnings. However, this causes a breaking change for all the clients that are using my APIs as the syntax for filters (`where`) has changed.

In 11.0.* when `UseFiltering<>` was used it generated operators like this:

```
id: Int
id_gt: Int
id_gte: Int
id_lt: Int
id_lte: Int
...
```

In HC 11.1 the filters have different structure
```
id: {
  eq: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
  ...
}
```

**To Reproduce**
1. Upgrade HC to 11.1
2. Run the app
3. Try using any "old-style" filters i.e. `"id_gte": 0`
4. Execution error

**Expected behavior**
I'd expect minor releases to be fully backwards compatible and changes to the syntax of `where` filters should require a new major release.

**Desktop (please complete the following information):**
 - Version HC 11.1

**Comment by diegomaninetti** [comment]
AFAIK the new filtering API was introduced in 11.0

**Comment by RaYell** [comment]
Well, in 11.0.9 it used to work like I described above (operator was part of the field name), 11.1 makes HotChocolate.Types.Filters obsolete in favor of HotChocolate.Data.Filters and this is where the behavior changes.

**Comment by michaelstaib** [comment]
Exactly, we are deprecating in phases here. With 11 we discouraged usage of the old API and announced that no more updates will be made to it. With 11.1 we deprecate it. With 12 the package will be removed. You still can use it with 11.1 but it is on the way out. We are focussing on the `HotChocolate.Data`.

**Comment by michaelstaib** [comment]
Closing this issue since there is no breaking change yet.

**Comment by PascalSenn** [comment]
@RaYell if people wonder why we decided to go down another route, you can read the reasoning here: https://chillicream.com/blog/2020/11/18/new-filtering-api
