### ISSUE TITLE
Async/Await issue with lazy loaded EntityFramework Entity

### ISSUE THREAD

**Issue by kYann** [ChilliCream/hotchocolate#3411]
**Describe the bug**
When using async/await in resolve I can't access LazyLoaded entities of my MainEntity.
I'm having an exception :
`System.InvalidOperationException: A second operation was started on this context before a previous operation completed`

Also I opened a StackOverflow issue : [https://stackoverflow.com/questions/66875998/hotchocolate-resolve-and-async](https://stackoverflow.com/questions/66875998/hotchocolate-resolve-and-async)

**To Reproduce**

See this repository : [https://github.com/whyseco/ReproHotChocolateIssueAsyncEF](https://github.com/whyseco/ReproHotChocolateIssueAsyncEF)

**Expected behavior**
In async/await and synchronous scenario I should be able to access lazyloaded entities.
In that case the resolver should be launch in Synchronous mode (as you can't replace DbContext on a LazyLoader).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Only happens with async/await

**Comment by michaelstaib** [comment]
Lazy loading cannot work with resolver trees since you have no guarantee when one is called and parallelized. I would recommend rather getting the selection tree and applying this as a projection. This is better for performance and also gives more controll.
