### ISSUE TITLE
MongoDB example issues

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/hotchocolate#3416]
# MongoDB example issues

Ref:

- [Slack discussion](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1617292973471800)
- [MongoDB example source](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/MongoDB)
- HotChocolate v11.1.0

## Synopsis

The MongoDB example from hotchocolate-examples provides

- mutation `createPerson`
- query `persons`
- query `node`
- query `personById`

The mutation `createPerson` and the query `persons` work fine.
But the queries `node` and `personById` reveal some issues.

## Issue 1 (major) - invalid node id

After adding persons by `createPerson` and getting data either as its payload or by `persons` we get person ids like:

```
UGVyc29uCmRVR1Z5YzI5dUNtYzJNVGRqTldFMlpUQmhZbVkwWVRZNU9UYzJOR0V3WVRrelpqQTJNakV3Wmc9PQ==
```

These node ids are invalid, somewhat twice encoded original `Uuid` values.
E.g. using the primitive helper `Decode-Base64.ps1` we can get to the original value with two steps (instead of expected one):

```
0> Decode-Base64.ps1 UGVyc29uCmRVR1Z5YzI5dUNtYzJNVGRqTldFMlpUQmhZbVkwWVRZNU9UYzJOR0V3WVRrelpqQTJNakV3Wmc9PQ==
Person
dUGVyc29uCmc2MTdjNWE2ZTBhYmY0YTY5OTc2NGEwYTkzZjA2MjEwZg==

0> Decode-Base64.ps1 UGVyc29uCmc2MTdjNWE2ZTBhYmY0YTY5OTc2NGEwYTkzZjA2MjEwZg==
Person
g617c5a6e0abf4a699764a0a93f06210f
```

As a result, the query `node` with such ids fail with the following message:

```
"Unable to convert the value if the argument `id` to `System.Guid`. Check if the requested type is correct or register a custom type converter."
```

A workaround exists, see the next comment.

### Issue 2 (minor) - error message typo

In the above error message "Unable to convert the value **if** the argument..."
should be corrected to "Unable to convert the value **of** the argument..."

The message text with typo found in sources here:

```
hotchocolate\src\HotChocolate\Core\src\Execution\Properties\Resources.resx(204):
  <data name="ThrowHelper_ResolverContext_CannotConvertArgument_Message" xml:space="preserve">
    <value>Unable to convert the value if the argument `{0}` to `{1}`. Check if the requested type is correct or register a custom type converter.</value>
  </data>
```

### Issue 3 (minor) - not useful personById

The query `personById` is probably correct. But it is not clear how to use it in the context of the example project with its data model + API.

The query accepts `Uuid` as the parameter. But this sort of data is not exposed / returned anywhere.

This is all we can get:

```graphql
type Person implements Node {
  id: ID!
  name: String
  addresses: [Address]
  mainAddress: Address
}
```

where `id` is the encoded node id, not the original `Uuid` explicitly.

So either the query `personById` should be removed (to avoid "what's it for and how to use it?") or `Person` should expose the original `Uuid` (it's not that clear how, BTW).

**Comment by nightroman** [comment]
# Issue 1 workaround

Source file: *Person.cs*

Replace

```csharp
    [Node(
        NodeResolverType = typeof(PersonNodeResolver),
        NodeResolver = nameof(PersonNodeResolver.ResolveAsync))]
    public class Person
    {
        [ID]
        public Guid Id { get; init; }
```

with

```csharp
    [Node(
        IdField = nameof(Id),
        NodeResolverType = typeof(PersonNodeResolver),
        NodeResolver = nameof(PersonNodeResolver.ResolveAsync))]
    public class Person
    {
        public Guid Id { get; init; }
```

i.e. remove the filed attribute `[ID]` and add `IdField = nameof(Id)` instead.

As a result the example operations return correctly encoded node ids and the query `node` works with them.

**Comment by PascalSenn** [comment]
Thanks for reporting @nightroman  !!

**Comment by nightroman** [comment]
No problem, thank you for dealing with this.
For some reason the PR did not close the issue, I am closing.
