### ISSUE TITLE
When replacing a member in a resolver, provide the original member value to the resolver

### ISSUE THREAD

**Issue by Chris-Hogan-Logikos** [ChilliCream/hotchocolate#3421]
I would like to replace an entity framework foreign key member with a resolved value.  Currently, the original value of the member is not available in the resolver context because I am using projections.

For example:

```
    [ExtendObjectType(typeof(Alert))]
    public class AlertResolvers
    {
        [GraphQLIgnore] public virtual User User { get; set; } = default!;

        [BindMember(nameof(Alert.UserId))]
        [UseDbContext(typeof(OverviewDbContext))]
        public async Task<PasswordUser> GetPasswordUserAsync([Parent] Alert alert, [ScopedService] OverviewDbContext dc) =>
            await dc.PasswordUsers.SingleAsync(r => r.Id == alert.UserId);
    }
```

In the resolver context above, UserId is always 0.

I'd like to have the original value of UserId available in the resolver context when, in the above case, passwordUser {...} is in the selection set.

Discussion on Slack: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1617391666039200

**Comment by michaelstaib** [comment]
This one is fixed with the newest 11.2 preview
