### ISSUE TITLE
Add Latitude Scalar Type

### ISSUE THREAD

**Issue by wonbyte** [ChilliCream/hotchocolate#3424]
Add `LatitudeType` to `Hotchocolate.Types`

- https://github.com/ChilliCream/hotchocolate/pull/3493

Addresses: #2927

**Comment by steveoh** [comment]
Isn't this covered by the position scalar?

**Comment by PascalSenn** [comment]
@steveoh These lat an lon would also allow the following format
```
48° 27' 30.0672'' N
7° 47' 4.5924'' E
```

**Comment by steveoh** [comment]
oh so degrees minutes and seconds... Do you plan to allow this to work with the rest of the spatial types?
