### ISSUE TITLE
StrawberryShake: StyleCop Warnings

### ISSUE THREAD

**Issue by braidenstiller** [ChilliCream/hotchocolate#3436]
If StrawberryShake added `// <auto-generated/>` in the header of the generated source, this would prevent StyleCop warnings from occurring, namely:

- warning SA1403: File may only contain a single namespace
- warning SA1507: Code should not contain multiple blank lines in a row
- warning SA1518: Code should not contain blank lines at the end of the file

See: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1633.md
and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2108

**Comment by michaelstaib** [comment]
This one is fixed with 11.2.0-preview.7
