### ISSUE TITLE
Your documentation page has non compiling code

### ISSUE THREAD

**Issue by majorimi** [ChilliCream/hotchocolate#3442]
I was trying to implement case insensitive filtering and found this example on you [docs page](https://chillicream.com/docs/hotchocolate/api-reference/extending-filtering#extending-iqueryable). Bit it gives compile errors.
AddProvider() method does not exists. 

```
public class CustomFilteringConvention : FilterConvention
{
    protected override void Configure(IFilterConventionDescriptor descriptor)
    {
        descriptor.AddDefaults();
        descriptor.AddProvider(
            new QueryableFilterProvider(
                x => x
                    .AddDefaultHandlers()
                    .AddFieldHandler<QueryableStringInvariantEqualsHandler>()));
    }
}
```

According to [issue reports](https://github.com/ChilliCream/hotchocolate/issues/2687) there is another code snippet. So might this should be used:

```
  public class CustomFilteringConvention : FilterConvention
  {
      protected override void Configure(IFilterConventionDescriptor descriptor)
      {
          descriptor.AddDefaults();
          descriptor.Operation(DefaultFilterOperations.Equals).Name("equals");
          descriptor.AddProviderExtension(
              new QueryableFilterProviderExtension(
                  x => x.AddFieldHandler<QueryableStringInvariantEqualsHandler>()));
      }
    }
```

**Comment by majorimi** [comment]
@PascalSenn Thanks for fixing the docs. However I think there are a few more errors in that. `.AddDefaultHandlers()` does not exists. Might be `.AddDefaultFieldHandlers()` should be used?

Also in the next section methods are not chainable if there is `;` between them:
```
.AddFiltering<CustomFilteringConvention>();
.AddConvention<IFilterConvention>(
```

**Comment by PascalSenn** [comment]
Ah I see @majorimi  Do you want to create a PR?

**Comment by majorimi** [comment]
Sorry currently trying to balance between 2 projects, one of my Blazor repo here and life.... So far life is loosing :)

**Comment by tobias-tengler** [comment]
@PascalSenn I made a [PR](https://github.com/ChilliCream/hotchocolate/pull/3523) for this, but I still get an error: 
`There is no provider defined for the filter convention 'HotChocolate.Data.Filters.FilterConvention;.`

My understanding of custom filter conventions is not deep enough, so maybe you can tell me where the issue is!

**Comment by PascalSenn** [comment]
Very cool @tobias-tengler !

**Comment by tejasvih** [comment]
Finally, after struggling 2 days, I was able to create working functionality for custom filters successfully ;)

Implements operations **"like"** , **"ci_like"** and **"ci_equals"**. For case sensitive and insensitive ("ci_...") 

[GraphQL Hot Chocolate v13 Custom filter operation example](https://gist.github.com/tejasvih/0ab6066a51d1138e256db243b1c03f46)


Hope this helps...
