### ISSUE TITLE
StrawberryShake: Mutable/Immutable Configuration

### ISSUE THREAD

**Issue by braidenstiller** [ChilliCream/hotchocolate#3443]
This was briefly discussed in Slack but wanted to formalize the enhancement request here.

Having a configuration flag for SS to control the mutability of its generated classes would be useful in frontend applications like Blazor where two-way binding a field to a returned query class would save having to create an additional ViewModel (with mutability) to act as an intermediary.

I would also propose extending a similar setting for generated input classes. Currently their mutable, but it would be valuable to be able to control this and make them immutable (e.g. in front-end workloads where you may buffer mutations until a user selects save and you don't want them to be unintentionally mutated).

You could potentially achieve the above with three flags in the config:

"mutableQueries": Boolean,
"mutableInputs": Boolean,
"mutableEntities": Boolean - For the store.

**Comment by michaelstaib** [comment]
Hi @braidenstiller,

we are adding at the moment support for immutable records which give a better way to work with mutations by using the withers. Mutable object will not be possible due to side-effects with the store itself. Strawberry Shake is designed to be immutable.

However, we could allow mutable objects for inputs. since they would not affect the state.

**Comment by braidenstiller** [comment]
Is the store the only blocker with the mutable objects? Understandable, but I ask because I did see you mentioned recently an enhancement to generate without the store. In this case could we allow the mutable objects?

I suppose the broader issue here is what is the best pattern for making use of Blazor's DataForm and EditContext components, which require two-way binding, with Strawberry Shake's immutable types.

**Comment by braidenstiller** [comment]
Hi @michaelstaib,

After reading into this more and also looking at how Apollo do things, I'm generally in the same boat now and agree immutability is better here. I think in cases where two-way binding is required a ViewModel can be used here.

Blazor EditForm/EditContext  <------- ViewModel <----Casts---- Container (Page) <----Passes Immutable entity----- StrawberryShake
