### ISSUE TITLE
Update HotChocolate README

### ISSUE THREAD

**Issue by zmarty** [ChilliCream/hotchocolate#3450]
Following the basic ASP.NET example in the [README](https://github.com/ChilliCream/hotchocolate/blob/main/README.md) of this repo.

After adding the HotChocolate.AspNetCore 11.1.0 package in a .NET 5 ASP.NET website, I tried following the example which says:

<pre>
protected override void ConfigureServices(IServiceCollection services)
{
    services.AddGraphQL(sp => SchemaBuilder.New()
      .AddQueryType<<b>Query</b>>()
      .AddServices(sp)
      .Create());
}
</pre>

Visual Studio complains it cannot find Query.

Then later on in the configure snippet, Visual Studio complains that using app.UseGraphQL is obsolete and I should "use the new routing API".

<pre>
protected override void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    <b>app.UseGraphQL();</b>
}
</pre>

Even the basic README of the repo is wrong, this does not look good :|

**Comment by PascalSenn** [comment]
Thanks for reporting. 
These example get out of date from time to time 
You are best of looking into the docs:
https://chillicream.com/docs/hotchocolate/defining-a-schema/
Or into the workshop, which shows many of the concepts:
https://github.com/ChilliCream/graphql-workshop

**Comment by PascalSenn** [comment]
This particular example is a lot simpler with version 11 

```csharp
protected override void ConfigureServices(IServiceCollection services)
{
    services.AddGraphQLServer() .AddQueryType<Query>();
}

protected override void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    app.UseEndpoints(endpoints => endpoints.MapGraphQL());  
}
```

We also have a very active slack channel where you can get help quickly :) 
http://bit.ly/joinchilli

**Comment by tobias-tengler** [comment]
@PascalSenn I already made a PR for this without realising that there already was an issue. I hope that's fine :)
If you there is anything that's not covered by my PR feel free to include it or tell me and I'll do it!

**Comment by PascalSenn** [comment]
Awesome @tobias-tengler  !! thanks for the PR!
