### ISSUE TITLE
Filtering issue with suggested demo application

### ISSUE THREAD

**Issue by majorimi** [ChilliCream/hotchocolate#3451]
Here is a [demo application](https://github.com/PascalSenn/Filtering.Demo) what you suggested to implement case insensitive filtering. Downloaded the code it builds fine returns values for simple queries. But filtering does not work at all.

**Here I want to test case incendivity:**
```
{
  persons(where: { name: "FRed" }) {
    id, name
  }
}
```

**Response:**
```
{
  "errors": [
    {
      "message": "The specified value type of field `name` does not match the field type.",
      "locations": [
        {
          "line": 2,
          "column": 25
        }
      ],
      "path": [
        "persons"
      ],
      "extensions": {
        "fieldName": "name",
        "fieldType": "StringOperationFilterInput",
        "locationType": "StringOperationFilterInput",
        "specifiedBy": "http://spec.graphql.org/June2018/#sec-Values-of-Correct-Type"
      }
    }
  ]
}
```

How can I write a query which satisfies all types? However I think `Name` property should be a string and query should be fine...
Thanks.

**Comment by PascalSenn** [comment]
The query should be
```graphql
{
  persons(where: { name: {eq: "FRed" }}) {
    id, name
  }
}
```

**Comment by majorimi** [comment]
@PascalSenn Thanks for your reply. Yes meanwhile I have found the string query operators in you docs as well. And tried out the same query you suggested. But still getting error this time a different one. It seems `System.String` is threated like a complex object and filter operators as Properties. Or something like that...

**Your query's response in Postman:**
```
{
    "errors": [
        {
            "message": "The specified input object field `eq` does not exist.",
            "locations": [
                {
                    "line": 2,
                    "column": 27
                }
            ],
            "path": [
                "persons"
            ],
            "extensions": {
                "field": "eq",
                "specifiedBy": "http://spec.graphql.org/June2018/#sec-Input-Object-Field-Names"
            }
        }
    ]
}
```
Also when I try to use a very similar query in our application. Basically it is the same query on a different Entity type than your demo app, the `eq` operator matters. So **even in your Query designer tool is suggesting the same problem in the designer**. Despite of the shown error I still can send the query to the server. Which responds with the same error I got with Postman and your Demo app:

![image](https://user-images.githubusercontent.com/7632824/114154904-31003600-9921-11eb-8675-4a9040176e80.png)

**Any idea about this error? Thanks.**

**Comment by PascalSenn** [comment]
@majorimi  I see, in this particular demo application i also renamed the `eq` operations to `equals`
![image](https://user-images.githubusercontent.com/14233220/114304428-5765d300-9ad3-11eb-80ba-c885a82e7fc1.png)

Sidenote. in graphql you do not need the `,`

**Comment by PascalSenn** [comment]
If you want to give it a try:

```graphql
{
  persons(where: { name: { equals: "FRed" } }) {
    id
    name
  }
}
```

**Comment by majorimi** [comment]
@PascalSenn Thanks for your response. Yes it worked with "equals". So operation name was overwritten. Get it.
**However the problem is now every filtering stopped working except the "equals".**

**For example used to "contains" worked like this:**
```
{
  persons(where: { { name_contains: "ed" } }) {
    id
    name
  }
}
```
**Now we get error message**: `"message": "The specified input object field `firstName_contains` does not exist.",`

Also trying to query NON string values does not work. Before adding the equal filter we could query ENUM values like this (`type` is an `Enum`):
```
{
  tags(where: { type: "ACTIVITY" }) {
    id
    name
    type
  }
}
```
**Now Enum query returns error**: `"message": "The specified value type of field `type` does not match the field type.",`

Tried to use it with the same "equals" syntax:
`  tags(where: { type: {equals:  "ACTIVITY" }}) { ... }`

 **Still getting error:**`"message": "The specified value type of field `equals` does not match the field type.",`

It seems adding the `QueryableStringInvariantEqualsHandler` to the filter pipeline override all the existing filters. I was trying to add `descriptor.AddDefaults();` and `.AddDefaultFieldHandlers()` etc. Also was trying to change the handler to override all kinds of operations by using: `protected override int Operation => DefaultFilterOperations.All/.Any;`. Not much luck...

**So the question is the a way to use `QueryableStringInvariantEqualsHandler` and meanwhile have all the existing filter like "contains" and enum compare work as before?**
Thansk.

**Comment by PascalSenn** [comment]
This example uses the new filtering api:
https://chillicream.com/blog/2020/11/18/new-filtering-api
