### ISSUE TITLE
Non-availability support for sorting and filtering on relay id

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3458]
This issue was previously addressed, but has been perceived as new functionality: https://github.com/ChilliCream/hotchocolate/issues/2971

I would like to add that this is not simply a new functionality, it is a bug. For example:

{
  masters (
    where: { and: [
        { details: { some: { typeId: { eq: "someBase64characters" } }} }
    ] }
    order: [{ state: { name: ASC } }]
  ) {
    edges{
      node{
        masterName
      }
    }
  }
}

This request would work successfully with any other type other than relay ID, because filter input type descriptor of default filter operation **Equals** has no binding for this type **.Type<IdType>().ID<TEntityType, TIdType>().MakeNullable()** in the source code. At the same time, the possibility of such a request is necessary for the operation of drop-down lists, which match values exactly by ID. When this is possible, filtering and sorting will become a truly powerful and versatile tool to cover all cases.

Based on the source code, these changes were blocked because the unit tests were not passed: https://github.com/ChilliCream/hotchocolate/pull/2999 I wanted to clarify whether these changes will be included in the next version or if for some reason this cannot be done, it would be enough to make GlobalIdInputValueFormatter class public instead of internal (in this case, it would be possible to add types of your choice through extension methods).

**Comment by michaelstaib** [comment]
Hi there,

I blocked the change for 11.x releases since we will change how the ID serialization work for the June release. My thinking in this is that it would be bad to make something public and then take it away in the next major release. 

The functionality of this will be fixed. We simply moved it to the June release since we have planned changes for the ID handling in that release anyway.

**Comment by TDDinAction** [comment]
> I blocked the change for 11.x releases since we will change how the ID serialization work for the June release. My thinking in this is that it would be bad to make something public and then take it away in the next major release.

Ok, conceptually, this is, of course, correct, then I will wait for the next release. Thanks a lot)

**Comment by MariaCobretti** [comment]
I have a related issue that ties to the solution of #2999 over which I had a lenghy discussion with Pascal
in that the FilterInputType does not respect InputValueFormatters..
I want to extend the FilterInputType and bring my own formatters which currently are being ignored.
Will the conceptual change to the Id field implementation also address this?

**Comment by michaelstaib** [comment]
@MariaCobretti can you open a new issue for that?

**Comment by MariaCobretti** [comment]
ofc #3510

**Comment by TDDinAction** [comment]
I have chacked HotChocolate version 12.0.0-preview.18. Now it is possible to sort by relay ID, but so far there is no filtering option.

**Comment by PascalSenn** [comment]
This is possible in 12.7 with `IdOperationFilterInputType`
