### ISSUE TITLE
Nested filtering does not work with nested sorting

### ISSUE THREAD

**Issue by GhostlyRaven** [ChilliCream/hotchocolate#3463]
Our project has a query with nested filtering and sorting. The data is requested from the database, but we don't get exactly the result we expect. The reason for this is that if filtering and sorting are enabled at the same time, we get an empty array instead of nested data. If we disable sorting or add a field for which it is performed, then everything works as expected. Tell me what could be the reason for this behavior? Is this a bug or are we configuring our hot chocolate server incorrectly?

EF Core models:
```csharp
    public class Computer
    {
        [GraphQLIgnore]
        public long Id { get; set; }

        public DateTime CreationDate { get; set; }

        public string Name { get; set; }

        public string[] Names { get; set; }

        public IPAddress[] Addresses { get; set; }

        public string Description { get; set; }

        public bool LogSensors { get; set; }

        public TimeSpan LogDelay { get; set; }
        
        public Dictionary<string, string> DynamicSettings { get; set; }

        [GraphQLIgnore]
        public long? GroupId { get; set; }

        public virtual Group Group { get; set; }

        [UseFiltering]
        [UseSorting]
        public virtual ICollection<Sensor> Sensors { get; set; }
    }

    public class Sensor
    {
        [GraphQLIgnore]
        public long Id { get; set; }

        public DateTime CreationDate { get; set; }

        public string Name { get; set; }

        public double Value { get; set; }

        public SensorUnit Unit { get; set; }

        public SensorType SensorType { get; set; }

        public HardwareType HardwareType { get; set; }

        [GraphQLIgnore]
        public long ComputerId { get; set; }

        [GraphQLIgnore]
        public virtual Computer Computer { get; set; }
    }
```
Query №1 (Bad response):
```graphql
query{
  computers(order:{name:DESC},where:{name:{in:["WS0358","WS0359"]}}){
    name,
    sensors(order:{creationDate:ASC},where:{sensorType:{eq:TEMPERATURE}}){
      creationDate,
      value
    }
  }
}
```

Response №1 (Bad response):
```json
{
  "data": {
    "computers": [
      {
        "name": "WS0359",
        "sensors": []
      },
      {
        "name": "WS0358",
        "sensors": []
      }
    ]
  }
}
```

Query №2 (Good response):
```graphql
query{
  computers(order:{name:DESC},where:{name:{in:["WS0358","WS0359"]}}){
    name,
    sensors(order:{creationDate:ASC},where:{sensorType:{eq:TEMPERATURE}}){
      creationDate,
      value,
      sensorType
    }
  }
}
```

Response №2 (Good response):
```json
{
  "data": {
    "computers": [
      {
        "name": "WS0359",
        "sensors": [
          {
            "creationDate": "2020-02-14T20:23:53.281+05:00",
            "value": 122,
            "sensorType": "TEMPERATURE"
          },
          {
            "creationDate": "2020-02-14T20:23:53.281+05:00",
            "value": 33,
            "sensorType": "TEMPERATURE"
          }]
      },
      {
        "name": "WS0358",
"sensors": [
          {
            "creationDate": "2020-02-14T20:23:52.878+05:00",
            "value": 28,
            "sensorType": "TEMPERATURE"
          },
          {
            "creationDate": "2020-02-14T20:23:52.878+05:00",
            "value": 46,
            "sensorType": "TEMPERATURE"
          }]
      }
    ]
  }
}
```

P.S. If you need more details or code to understand our problem, please let us know.

**Comment by PascalSenn** [comment]
@GhostlyRaven  what version are you on?

**Comment by GhostlyRaven** [comment]
@PascalSenn The HotChocolate version was 11.0.9. We updated to 11.1.0, but that didn't fix the query bugs. Our project runs on the latest version of the NET 5 SDK.

**Comment by PascalSenn** [comment]
Hi @GhostlyRaven  
I tried to reproduce this bug in #3625 but did not see this behaviour in my tests. 
Could you try to reproduce it?

**Comment by GhostlyRaven** [comment]
Hi @PascalSenn 
Here is the archive with the project where the bug is reproduced. We used it to exclude the influence of third-party code on HotChocolate and find out what caused the bug. We hope this will help clarify the situation.

Project archive: [Monitoring.Service.zip](https://github.com/ChilliCream/hotchocolate/files/6404265/Monitoring.Service.zip)

**Comment by GhostlyRaven** [comment]
Hi @PascalSenn. After a lengthy process of debugging the HotChocolate.Data source code and the project reproducing the error, the following pattern was found:

1. The WrappedPipeline method of the QueryableSortProjectionOptimizer class successfully sets the SkipSortingKey (Field Sensors) to automatically and work correctly.
2. The WrappedPipeline method of the QueryableFilterProjectionOptimizer doesn't automatically set the SkipFilteringKey (Field Sensors) to successfully and doesn't work correctly. Since it is never called while the program is running.
3. If you set SkipSortingKey and SkipFilteringKey to successfully, then the bad query starts working correctly. A good query also continues to work correctly with such changes.

The reason for this behavior has not yet been found. Could you please comment on this strange behavior of the code?

**Comment by PascalSenn** [comment]
@GhostlyRaven  sorry i am a bit absorbed the next few weeks.
Looking at the code it could be that we actually override pipeline
https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/Data/src/Data/Projections/Expressions/Optimizers/QueryableFilterProjectionOptimizer.cs
and 
https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/Data/src/Data/Projections/Expressions/Optimizers/QueryableSortProjectionOptimizer.cs

In both cases we use 
```csharp
 FieldDelegate resolverPipeline = context.CompileResolverPipeline(selection.Field, selection.SyntaxNode);
```

I think what happens is that we compile the resolver pipeline first for filtering, wrap it with the `WrappedPipeline` and set it as the resolver.
Then we compile it for sorting, wrap it and set it as the resolver.
I guess as we compile the resolver pipeline twice and then individually wrap it and set it, we acutally only get the lastest result.
I could be wrong on this
@michaelstaib  what is the recommended way to apply multiple selection optimizer that change the resolver pipeline?

**Comment by GhostlyRaven** [comment]
Hi, @PascalSenn and @michaelstaib.
I ran the test and registered my optimizer to the pipeline after all in the [RegisterQueryableHandler](https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/Data/src/Data/Projections/Convention/Extensions/ProjectionProviderDescriptorExtensions.cs) method. As a result, the sorting and filtering optimizer never worked, but my optimizer ran successfully. Therefore, we can say that only the last optimizer is registered in the pipeline and @PascalSenn assumption was correct.
I could not find the reason for this behavior. **I believe this behavior is a critical error.** I would like to hear @michaelstaib  opinion on this issue.
