### ISSUE TITLE
Using uppercase variablenames as query variables dosen't allow execution of the query

### ISSUE THREAD

**Issue by Nivisan1234** [ChilliCream/hotchocolate#3468]
**Describe the bug**
When creating a query with the annotation-based apporach.
You can choose a variablename, that starts with uppercase for the a queryparameter.
But when trying to use the param for the query, the execution dosen't work.

**To Reproduce**
1. Create a annotation based HotChocolate.AspnetCore  project.  (ASP .NET Core Web API)
2. Create a query with the following method and add it into the startup.cs : 

_**Class: Query**_
```
	public class Query
	{
		public string HelloWorld(string HelloWorldTest) => HelloWorldTest;
	}

```

_**Class: Startup
Method: ConfigureServices**_
`
		services.AddControllers();
		services.AddCors(opt => opt.AddPolicy("OpenCorsPolicy", pl => pl.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()));
			services.AddGraphQLServer().InitializeOnStartup().AddQueryType<Query>();
`

_**Class: Startup
Method: Configure**_

```
	if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			

			app.UseHttpsRedirection();

			app.UseRouting();

			app.UseAuthorization();

			app.UseCors("OpenCorsPolicy");
			app.UseEndpoints(endpoints =>
			{
				endpoints.MapGraphQL();
			});
```

**Expected behavior**
Was expecting that it's possible to give parameters with uppercase variablenames.

**Desktop**
 - OS: Windows 10 Pro
 - Version 19042.870

**Additional context**
-

**Comment by PascalSenn** [comment]
@Nivisan1234 Hi Nivisan 👋 
We lower case this parameter name by default, if you want to override it to PascalCase you need to use a `[GraphQLName()]` attribute

```csharp
	public class Query
	{
		public string HelloWorld(
		    [GraphQLName("HelloWorldTest") string helloWorldTest) => helloWorldTest;
	}
```

**Comment by Nivisan1234** [comment]
Heii Pascal

I knew that this was possible like that, but thought that it was a bug.
But thank you anyway for providing an answer!
