### ISSUE TITLE
Labels are not automatically added for new bug & enhancement issues

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3478]

**Comment by tobias-tengler** [comment]
@michaelstaib I think it's an issue, that the tag used for bugs in this repo, does not include the actual emoji, but rather `:beetle:`.

![image](https://user-images.githubusercontent.com/45513122/114308567-b5e77d00-9ae4-11eb-8cb5-01983d2071e8.png)
vs. 
![image](https://user-images.githubusercontent.com/45513122/114308584-c4359900-9ae4-11eb-8006-cb5ab9f32cad.png)
I was wondering, since a bug report of mine was not correctly labeled, even after the attached PR had been merged. I validated the behavior before in a private repo, so I think this is the issue.
The fix would be that a maintainer edits the bug label to include the actual emoji: `🐞 bug`.
I could also submit another PR, but that would be too much noise around a thing that could be changed within the repo, without consequence.

**Comment by michaelstaib** [comment]
done

**Comment by tobias-tengler** [comment]
Thanks, but now it's `:bug:` instead of the actual emoji :D
![image](https://user-images.githubusercontent.com/45513122/114316653-b4c64800-9b04-11eb-932e-d3bb6427abb2.png)
From one of your presentations I know that you're using MacOS, so maybe it's a weird Safari/MacOS quirk. 
I'm on Linux + Firefox and I can paste the actual emoji from my comment above into a label in a private repository of mine...

**Comment by michaelstaib** [comment]
Ok... misunderstood you :) now it is the bug emoji and I used the proper utf8 character.

**Comment by michaelstaib** [comment]
is:open label:"🐛 bug"
