### ISSUE TITLE
Projection causes fields to be null

### ISSUE THREAD

**Issue by Vec7or** [ChilliCream/hotchocolate#3486]
**Describe the bug**
I have an object with two constructors:
```csharp
public Entity2(string id, Entity1 owner)
{
    this.Id = id;
    this.Owner = owner;
}
// Used by entity framework
protected Entity2()
{
    this.Id = default;
    this.Owner = default;
}
```
If I now run the following query which returns an `Entity2`:
```
query {
  getEntity2 {
    id,
    owner {
      name
    }
  }
}
```
I get the expected result:
```
{
  "data": {
    "getEntity2": [
      {
        "id": "HelloWorld",
        "owner": {
          "name": "Franz"
        }
      }
    ]
  }
}
```
But if I now activate `Projection` on the query the result looks like this:
```
{
  "data": {
    "getEntity2": [
      {
        "id": null,
        "owner": {
          "name": "Franz"
        }
      }
    ]
  }
}
```
It seems like `Projection` uses the second constructor to construct the element but does not fill in the `Id` afterwards. This might be because `Id` is not settable. Is this behavior intended?

**To Reproduce**
1. Extract the attached minimal example zip project 
[WebApplication.zip](https://github.com/ChilliCream/hotchocolate/files/6299107/WebApplication.zip)
2. Run the following query against the API:
```
query {
  getEntity2 {
    id,
    owner {
      name
    }
  }
}
```
4. Comment and un-comment the `Projection` Attribute within the `Query`-Class.
5. See the error.

**Expected behavior**
I would expect the query to return the same result with `Projection` enabled.

**Comment by Vec7or** [comment]
@PascalSenn informed me that Projections currently require a public setter. So this works as intended.

**Comment by steveoh** [comment]
Maybe add this as a doc improvement if not already stated as it got me also.

**Comment by Vec7or** [comment]
I created a pull request for improved documentation.
