### ISSUE TITLE
Support by projection of OrderBy operation.

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3488]
This feature was introduced in EF Core 5.0: https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include
(HotChocolate supports .NET 5 which supports EF Core 5.0).

I want to point out that the cases Select for filtring + ordering and SelectMany for filtring  are already working. Only SelectMany case does not work. For example: if we use projection for query and try to sort slave table "details",  we cannot see this field in the constructor of the playgraund (at the same time, a similar filtering request works):
```graphql
{
  masters (order: { details : { modifiedOn: DESC } }) { 
    edges {
      node {
        id
        details {
          modifiedOn
        }
      }
    }
  }
}
```
If we do not use the projection attribute, but use ScopedService with Include, we will get a result with a non-working sorting:

```csharp
[UseDbContext(typeof(Context))]
        [UsePaging(typeof(MasterType))]
        //[UseProjection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Master> GetMasters([ScopedService] Context context)
        {
            return context.Masters.Include(p => p.Details.OrderBy(p => p.ModifiedOn));
        }
```
The reason for this is that **HotChocolate.Data.EntityFramework** implementation on the level of using **Linq** of EntityFramework still skips **OrderBy** with **SelectMany**. Could you enable this support regarding **EF Core 5.0**.

**Comment by PascalSenn** [comment]
If I understand you correctly you would like to sort the details realtion
You can do this by doing 

```csharp
public class Master 
{
     [UseSorting]
     public ICollection<Detail> Details {get; set;}
}
```
```graphql
{
  masters { 
    edges {
      node {
        id
        details (order: { modifiedOn: DESC } )  {
          modifiedOn
        }
      }
    }
  }
}
```

**Comment by TDDinAction** [comment]
> If I understand you correctly you would like to sort the details realtion
> You can do this by doing
> 
> ```cs
> public class Master 
> {
>      [UseSorting]
>      public ICollection<Detail> Details {get; set;}
> }
> ```
> 
> ```graphql
> {
>   masters { 
>     edges {
>       node {
>         id
>         details (order: { modifiedOn: DESC } )  {
>           modifiedOn
>         }
>       }
>     }
>   }
> }
> ```

This case will sort the nested details array itself, but it will not sort the masters array by the specified parameter.

**Comment by PascalSenn** [comment]
Is `details` a list?
