### ISSUE TITLE
ResolveWith does not exist on InterfaceType

### ISSUE THREAD

**Issue by Odonno** [ChilliCream/hotchocolate#3498]
I would like to use resolvers on a field of an interface. Example:

```
interface Entity {
  id: Int!
  childs: [ChildEntity!]!
}

type A implements Entity {
  ...
}
type B implements Entity {
  ...
}
```

For the moment, I can't create a resolver to retrieve childs on my Entity interface.. :(
All I get is the following error: 

Error	CS1061	'IInterfaceFieldDescriptor' does not contain a definition for 'ResolveWith' and no accessible extension method 'ResolveWith' accepting a first argument of type 'IInterfaceFieldDescriptor' could be found (are you missing a using directive or an assembly reference?)

**Comment by PascalSenn** [comment]
How does you resolver look like?

**Comment by Odonno** [comment]
I am trying to do this: 

```cs
public class EntityType : InterfaceType<Entity>
{
    protected override void Configure(IInterfaceTypeDescriptor<Entity> descriptor)
    {
        descriptor.Field(b => b.Child)
            .ResolveWith<EntityResolvers>(r => r.GetChildOfEntityAsync(default!, default!))
            .UseRepository<ChildRepository>();
    }

    private class EntityResolvers
    {
        public Task<Child?> GetChildOfEntityAsync(
            Entity entity,
            [ScopedService] ChildRepository childRepository
        )
        {
            return childRepository.GetById(entity.ChildId);
        }
    }
}
```

**Comment by Odonno** [comment]
For information, I am using HotChocolate v11.1.

**Comment by Odonno** [comment]
@PascalSenn Any idea?

**Comment by Odonno** [comment]
Still searching for a solution. Can anyone help me?

**Comment by PascalSenn** [comment]
@Odonno  Resolve with does not exists on interfaces because it does not have a resolver
You can just define it like this
```

        descriptor.Field(b => b.Child)
            .Type<ObjectType<Child>>()
```

**Comment by Odonno** [comment]
Well, my goal is to have an abstract base class (that act like an interface in GraphQL language). So, if I do what you suggest, I should implement the resolver in every child classes. But then, when I look at the GraphQL SDL, it's completely messed up because the property is now both in the parent and the children... which is weird. And it's also not working because I got the "Child is not defined in the schema" error... And of course, it's not logical to copy/paste resolver in each child...

So, I don't see any other than having the `ResolveWith` method in the interface/base class.

I don't know how to explain it properly but I find it frustrating how to make inheritance work in HotChocolate.

**Comment by tobias-tengler** [comment]
I'm not sure if you mean interface and Implementation with Parent and Child, but properties of the interface are supposed to be present on the implementation in the schema definition. [Reference](https://graphql.org/learn/schema/#interfaces)
For the duplication of the resolver I remember that I wrote an extension method where I defined the interface resolvers and I would just call that from the interface and the implementation definition. I don't have it at hand right now, but I'll try to find it after I'm done with work and get back to you. 
Maybe that's not the way to go about it as well though. Would also love to know how it's done correctly!

**Comment by Odonno** [comment]
Nice. I managed to make it working thanks to your example @tobias-tengler 

But still, I find it weird. Maybe it's how GraphQL was created but it's really weird to query the graph like this: 

* you can query by fragment of each child classes/types, which is expected but you can also query by fragment the parent class which have clearly no sense (since it is an interface)
* you can query all properties of the parent class in the fragment of a child class (which you can already do with the base class/interface, right?) 

Now that I write this, I can see that the second point can be interesting where you only want to execute some resolvers/properties only for a kind of type. But the first point, I don't see it because you'll never output anything (base class/interface will never get instantiated).

Maybe there's a better way to have a proper schema I suppose. Until then, it's working and that's what I wanted, so thanks!
