### ISSUE TITLE
Strawberry Shake List Type Parameters Memory Leak

### ISSUE THREAD

**Issue by davidbrazel2** [ChilliCream/hotchocolate#3513]
**Describe the bug**
When invoking queries where one or more of the variable parameters is a list, this causes every repeat execution of the query to add another operation result to the operation store after every completed ExecuteAsync request. This is caused by the fact that the call to GetOrAddStoredOperation in OperationStore performs a GetOrAdd on the ConcurrentDictionary<OperationRequest, IStoredOperation> _result, the .Equals equality comparison within the OperationRequest object that acts as the key and thus invoked by GetOrAdd, when comparing the content of variables will always return false with a list variable because a new list instance is instantiated on every ExecuteAsync; only a a.Equals(b) is applied to the list, which is always a comparison of 2 different list objects. The result is that every invocation adds another item to _results which will keep growing indefinitely, triggering a memory leak as well as higher and higher cpu usage (every time more items in _results needs to be compared to).

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute ExecuteAsync on a query which has a list type variable parameter
2. After 2 or more completed executions of the above with identical parameters on that same query upon inspecting _operationExecutor -> _operationStore -> _results it will be observed that another result gets added after each time

**Expected behaviour**
If one of the variables is a list type, the contents of that list needs to iterated and compared so that the comparison when GetOrAdd is executed correctly recognises that is another call to the same query and therefore the existing result should updated, not another one added; i.e. Get is triggered not Add.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .net: 5.0

**Additional context**
Using 11.1 Strawberry Shake, but checking the code, latest remains affected by this bug.

**Comment by michaelstaib** [comment]
This is now fixed.
