### ISSUE TITLE
Starwberry-shake-generated client : A timeout when resolving each field individually?

### ISSUE THREAD

**Issue by jeancallisti** [ChilliCream/hotchocolate#3518]
Let's say this is my graphQL schema / query: 

```
query {
    someField1
    someField2
    someField3
}
```

...and then I call it through Postman or the GraphQL playgroung...
... Then if every field is resolved **quickly enough,** then it works as expected : 

```

//When calling with anything but Strawberry-shake-generated classes
{
  "data": {
    "someField1": "value"
    "someField2": "value"
    "someField3": "value"
  }
}
```

However if, let's say, **someField2 takes too long to be resolved,** I get something like this with Strawberry Shake: 

```
//When calling specifically through Strawberry-shake-generated classes
{
  "data": {
    "someField1": "value"
    "someField2": null  // <-- a timeout happened somewhere in the Strawberry-shake-generated client???
    "someField3": "value"
  },
  "errors": [
    {
      "extensions": {
        "data": {
          "1": "One of the identified items was in an invalid format."
        }
      }
    }
  ],
}
```

I can't find any concrete evidence of its existence but everything seems to point at some **timeout** specifically in Strawberry shake.

**Is this real? Is there a time out?**
I'm 99% sure that the issue comes from Strawberry shake because I never have it when I call the same GraphQL query through the GraphQL playground, only when it's my C# program that calls the query through Strawberry Shake's generated classes.

**How do I increase this timeout???**

**Comment by PascalSenn** [comment]
@jeancallisti  
I think the default timeout is 30 seconds. 

You can increase the timeout on the server like this
```csharp
services.AddGraphQLServer()
   ...
   .ModifyRequestOptions(x => x.ExecutionTimeout = TimeSpan.FromMinutes(30))
```

**Comment by jeancallisti** [comment]
I upgraded to Strawberry Shake 12 to see if it fixes this weird timeout issue.
The time out is 10 seconds by the way.
