### ISSUE TITLE
Apollo Tracing Support

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#352]
https://github.com/apollographql/apollo-tracing

**Comment by michaelstaib** [comment]
```csharp
private static long nanoTime() {
   long nano = 10000L * Stopwatch.GetTimestamp();
   nano /= TimeSpan.TicksPerMillisecond;
   nano *= 100L;
   return nano;
}
```

[source](https://stackoverflow.com/questions/1551742/what-is-the-equivalent-to-system-nanotime-in-net)

**Comment by rstaib** [comment]
The `nanoTime` implementation above is dangerous, because it does not consider `Stopwatch.Frequency` which may differ from hardware to hardware. The following implementation is technically correct.

```csharp
private static long GetTimestampInNanoseconds()
{
    const long nanosecondsPerSecond = 1000000000;

    return Stopwatch.GetTimestamp() *
        (nanosecondsPerSecond / Stopwatch.Frequency);
}
```

**Comment by rstaib** [comment]
#459
