### ISSUE TITLE
Support for Prisma Playground

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#353]
We should write another middleware delivering Prisma Playground.

This way people can choose between GraphiQL or Playground.

https://github.com/prisma/graphql-playground

**Comment by drowhunter** [comment]
I actually prefer playground to graphiql.  Also Voyager middle ware suppory could be cool. I use it   alot..

**Comment by michaelstaib** [comment]
Ok, can you add an issue for Voyager with a url to it?

**Comment by akaSybe** [comment]
Here is Voyager: https://apis.guru/graphql-voyager.

I'm also prefer Playground, @michaelstaib can I help you to implement middleware? As far as I understand it will be almost the same like GraphiQl.

**Comment by michaelstaib** [comment]
@akaSybe sure.... if you want to have a got at it this issue is all yours.

This is our GraphiQL Middleware:
https://github.com/ChilliCream/hotchocolate-aspnetcore/tree/master/src/AspNetCore.GraphiQL

All the files are located here and are integrated into the assembly as resources:
https://github.com/ChilliCream/hotchocolate-aspnetcore/tree/master/src/AspNetCore.GraphiQL/Resources

The settings are created via the settings middleware here:
https://github.com/ChilliCream/hotchocolate-aspnetcore/blob/master/src/AspNetCore.GraphiQL/SettingsMiddleware.cs

you can join our slack group here for further discussions:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNDkxMjA1MzkxNzMwLTFlMjUxMWQ2YWQ4ODRkYmI5MWJiMmNhNzI2MjQ4MzRmZjlhY2Y0Yjg0MzM1YTRhMDc4YWUwOTViMjNhNzY1ZGI

**Comment by michaelstaib** [comment]
This is now integrated and I will close this issue.
