### ISSUE TITLE
[StrawberryShake] Cannot access scope for HTTP client token configuration

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/hotchocolate#3533]
**Is your feature request related to a problem? Please describe.**
It appears I cannot access any scoped DI from within the `ConfigureHttpClient` method. My authentication tokens are stored in a scoped service (representing the current user, as many users may be proxied through the same StrawberryShake implementation). 

**Describe the solution you'd like**
Ideally, the callback which is responsible for setting the token is executed in a scoped context. 

e.g.,
```
      services.AddScoped<OpenControllerContext>();

      services.AddOpenWorkShopClient()
              .ConfigureHttpClient((serviceProvider, client) => {
                 OpenControllerContext context = serviceProvider.GetRequiredService<OpenControllerContext>();
                 client.BaseAddress = new Uri($"{context.OwsHost}/api/graphql");

                 string? token = context.CurrentUserToken;
                 Log.Debug("Token = {token}", token);
                 if (token != null) {
                   client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                 }
```

Which presently gives the error:
```System.InvalidOperationException: Cannot resolve scoped service 'OpenWorkEngine.OpenController.OpenControllerContext' from root provider.```

**Describe alternatives you've considered**
- The builder (second callback)
- Locking the client for thread safety and using a static value
- Creating multiple clients

**Comment by michaelstaib** [comment]
That is correct. We are using `Microsoft.Extensions.Http` for HttpClient creation. At the moment there is no way to access the scoped services. The client is thread-safe btw.

However, we have the following proposal to provide custom middleware in the June release:
https://github.com/ChilliCream/hotchocolate/issues/3467

**Comment by zaneclaes** [comment]
> The client is thread-safe btw.
Thanks. A lock will still be required on the static object to prevent concurrent requests clobbering the same global value. I think this is probably my easiest path to a workable solution at the moment.

Cool — middleware sounds like a good solution here.

**Comment by alexeyzimarev** [comment]
There's no need to lock because all that is required for manipulation is the `HttpRequestMessage`. If `ExecuteAsync` provides an optional argument of `Action<HttpRequestMessage>`, it will solve those issues for adding request-level headers like auth tokens.

I believe the assumption that the whole app operates with a single token is not correct. I am trying to build a multi-tenant app and the client needs to supply the auth token based on the call context, and it doesn't seem possible. Bummer...

**Comment by alexeyzimarev** [comment]
I checked the implementation of the client registration and I have to say it's not what is expected from the lifecycle side. The `IHttpConnection` implementation is registered in a separate service collection and is being resolved outside of the main application scope. As a result, if I add a delegating handler to the client configuration, and the handler is registered as scoped, it will be executed, but the scope is completely different.

Idiomatic DI resolution with request scope in ASP.NET Core is expected to have _one_ scope per request. But when I get the client instance from within a given scope, I can see that it has its own scope for the `HttpClient` call. So, if I register something as scoped, open a scope, get the client instance from the scoped provider, and try using a delegated handler (also scoped), I find that it's not the same scope although it should be.

**Comment by michaelstaib** [comment]
@alexeyzimarev can you open a feature request for:
> Instantiate the client within the correct scope, so people can use scoped delegating handlers

We are reworking the transport layer and will have something more aiming to relay where we give you full control over the transport.

**Comment by fleed** [comment]
> @alexeyzimarev can you open a feature request for:
> 
> > Instantiate the client within the correct scope, so people can use scoped delegating handlers
> 
> We are reworking the transport layer and will have something more aiming to relay where we give you full control over the transport.

@michaelstaib  any updates on this? I'd like to access the request message before sending the request

**Comment by vdekercd** [comment]
Are you still planning to fix this issue?

**Comment by saleem-hadad** [comment]
is this implemented?

**Comment by krobotics** [comment]
bump

**Comment by WoistdasNiveau** [comment]
I guess it is still not fixed?
