### ISSUE TITLE
Set Banana Cake Pop schema URL to the current URL per default

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3536]
If you start to build a new HotChocolate server with all the defaults and open the browser at `/graphql` you get Banana Cake Pop as expected. What's not intuitive for new users though, is that you have to input the same URL as the schema url as well.
In most cases the URL in the browser will also be the one, where the GraphQL server is listening.
So to make the common case simpler, we could initialize the schema URL of Banana Cake Pop to `window.location.href`.

I would've written a PR for this, but I can't find the Source Code in the repository. Where is it hosted/located?
If it's not part of this repository, the description of the repository is misleading about that.

**Comment by michaelstaib** [comment]
That is a bug and should be addressed soon.

**Comment by tobias-tengler** [comment]
This has been fixed.
