### ISSUE TITLE
Strawberry Shake query with scalar `AnyType` fails.

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/hotchocolate#3543]
# Strawberry Shake query with scalar `AnyType` fails.

- ref: [Slack](https://hotchocolategraphql.slack.com/archives/CMUJ40EHJ/p1618573989285400)
- Strawberry Shake: 11.2.0-preview.24
- Windows 10

The schema has the scalar `Map`.
One of object types has the field `counts: Map!`.
The GraphQL service sends some JSON object as `counts`.

We use this service in our gateway scenario and add the scalar `Map` as `AnyType`:

```
.AddType(new AnyType("Map"))
...
.ConfigureSchema(x => x.AddType(new AnyType("Map"))
...
```

The result gateway service with such a schema and data works fine with Banana Cake Pop.
BCP successfully gets and displays the result `counts` as an object with keys and values.

But in Strawberry Shake this scenario does not work.

(1) The generated type is `public global::System.String Counts { get; }`.
`String` does not look ideal for this kind data, a set of key / value pairs.
Perhaps it's work in progress and it's supposed to get results as JSON strings.
But this is not working in any case.

(2) On running a query with `counts` Strawberry Shake generated code fails with the error

> The requested operation requires an element of type 'String', but the target element has type 'Object'.

**Comment by jorrit** [comment]
I'm having this issue as well. I'll just mention JSONObject here, because that name is often used for this GraphQL type.

There needs to be a way for field serializers to either access the JSONElement or the raw JSON string.

Right now, the following is generated:

```c#
return _jSONObjectParser.Parse(obj.Value.GetString()!);
```

This needs to be either:

```c#
return _jSONObjectParser.Parse(obj.Value!);
```

```c#
return _jSONObjectParser.Parse(obj.Value.GetRawText()!);
```

I need this functionality ASAP so I am going to make an attempt at this in a PR.

**Comment by michaelstaib** [comment]
This one is now implemented.

**Comment by timeshift92** [comment]
i had same fail but i got next message:
```
The requested operation requires an element of type 'String', but the target element has type 'Number'.
```

**Comment by geometrikal** [comment]
@michaelstaib This is not fixed for me in StrawberryShake 12.11.1, was it merged into another version?

**Comment by timeshift92** [comment]
Good day, my mistake, I did not pay attention to the generated files, after deleting them everything became normal

**Comment by Villawhatever** [comment]
Looks like this is still an issue in 12.15.2? Failing to deserialize a JSON object with `"Exception = {"The requested operation requires an element of type 'String', but the target element has type 'Object'."}"`

**Comment by PascalSenn** [comment]
This is now fixed in the newest version 12 and preview 13
