### ISSUE TITLE
Strawberry Shake generates base interface type incorrectly

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#3544]
I built a service last year using the preview version of Strawberry Shake, and I am now finally getting around to trying out v11.1.0. I am currently unable to get it working, and I'm not sure if it's a bug or something I'm doing incorrectly - this worked on the preview, but doesn't work any more. 

Given the following schema:

```graphql
schema {
  query: QueryType
}

type QueryType { 
  UserRewardSync(): SyncResultOfUserReward 
}
 
type UserReward implements IClientEntity {
  Id: ID!
  ModifiedAt: DateTime!
  ModifiedAtTicks: Long!
  CreatedAt: DateTime!
  EntityState: EntityState! 
  RewardId: ID
  Reward: Reward
}

type Reward implements IClientEntity {
  Id: ID!
  ModifiedAt: DateTime!
  ModifiedAtTicks: Long!
  CreatedAt: DateTime!
  EntityState: EntityState!
  SubscriberId: ID!
  Name: String!
  ValidityDays: Float!
}

type SyncResultOfUserReward {
  EntityBatch: [UserReward]!
  TotalActiveEntityCount: Long!
  EntitiesToDownloadCount: Long!
}

interface IClientEntity {
  Id: ID!
  ModifiedAtTicks: Long!
  EntityState: EntityState!
}

enum EntityState {
  ACTIVE
  DRAFT
  ARCHIVED
  DELETED
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime

"The `Long` scalar type represents non-fractional signed whole 64-bit numeric values. Long can represent values between -(2^63) and 2^63 - 1."
scalar Long

enum SortOperationKind {
  ASC
  DESC
}   
```

And the following Query.graphql file:

```graphql
query UserRewardSyncQuery() {
  UserRewardSync() {
    TotalActiveEntityCount
    EntitiesToDownloadCount
    EntityBatch {
      ... UserRewardDto
    }
  }
}
 
fragment RewardDto on Reward {
  ...Entity
  Name
  SubscriberId 
}

fragment UserRewardDto on UserReward {
  ...Entity 
  RewardId
  Reward {
    ... RewardDto
  }
}

fragment Entity on IClientEntity{
  Id
  EntityState
  ModifiedAtTicks
}
```

Strawberry shake generates a class called UserRewardSyncQuery_UserRewardSync_EntityBatch_UserReward to represent the UserReward, and correctly (I think) gives it a property of type IUserRewardSyncQuery_UserRewardSync_EntityBatch_Reward to represent the Reward that is part of the UserReward. 

However there is another class called  UserRewardData which also has a Reward property, but this property is of type IIClientEntityData instead of IUserRewardSyncQuery_UserRewardSync_EntityBatch_Reward. This results in a compilation error in the following generated code:

![image](https://user-images.githubusercontent.com/2269624/115197015-d7ea8c00-a0f0-11eb-8a62-a7af0c3b74a2.png)

The error is:

"cannot convert from 'Reveye.Client.Graph.State.IIClientEntityData' to 'Reveye.Client.Graph.IUserRewardSyncQuery_UserRewardSync_EntityBatch_Reward?"

I can share a repro project if you ping me on slack.

**Comment by PascalSenn** [comment]
@freever  We already have a ton of bugfixes in the 11.2 previews. Can you quickly check if this behaviour is also there when you use a preview?

**Comment by freever** [comment]
@PascalSenn do you mean 12.0.0-preview.1? I tried updating to that version and still get the same error

**Comment by PascalSenn** [comment]
@freever  11.2.0-preview.27

**Comment by freever** [comment]
Aaaaaaah.... that seems to have sorted it out, thanks!
