### ISSUE TITLE
StrawberryShake: Mutation containing a union with nested data fails to generate code

### ISSUE THREAD

**Issue by ChrisMH** [ChilliCream/hotchocolate#3547]
[UserSetting.zip](https://github.com/ChilliCream/hotchocolate/files/6339128/UserSetting.zip)

preview.27

I have a mutation that returns a union where one part has a nested data structure:
```
mutation StoreUserSettingFor($userId: Int!, $customerId: Int!, $input: StoreUserSettingForInput!) {
    storeUserSettingFor(userId: $userId, customerId: $customerId, input: $input) {
        ... on UserSettingSuccess {id}
        ... on UserSettingError {errors {code message}}
    }
}
```

When building the above, code generation returns:
`CSC : error SS0006: The given key 'StrawberryShake.RuntimeType' was not present in the dictionary. [C:\Users\chogan\DevO\ovc-source\WebService\GraphTest\GraphTest.csproj]`

I have tried removing the other arm of the union with the same error message:
```
mutation StoreUserSettingFor($userId: Int!, $customerId: Int!, $input: StoreUserSettingForInput!) {
    storeUserSettingFor(userId: $userId, customerId: $customerId, input: $input) {
        ... on UserSettingError {errors {code message}}
    }
}
```

I don't know for sure that it's the nested data, but `UserSettingSuccess`, which is flat, works, and the other doesn't.

**Comment by PascalSenn** [comment]
@ChrisMH  can you share your schema too? I could not reproduce this issue

**Comment by ChrisMH** [comment]
@PascalSenn Attached
