### ISSUE TITLE
Strawberry Shake 12.0 compatible with .Net 2.1?

### ISSUE THREAD

**Issue by jeancallisti** [ChilliCream/hotchocolate#3553]
I've generated the Strawberry classes/Client in my .Net standard 2.1 project after upgrading to Strawberry Shake 12. I was previously using Strawberry Shake 11.

Everything builds properly, but when  start the app I get this : 
![image](https://user-images.githubusercontent.com/1881493/115362730-20be4580-a1c2-11eb-9c0c-d29f252ca943.png)

I believe it means that .Net 5 is expected.

Hence, my question : **Is this by design? Is there a workaround?**

PS: I don't know how to add or remove labels to a post. Sorry that it's displayed as a "Bug".

**Comment by michaelstaib** [comment]
I suggest that you use strawberry shake 11.2. 12.0 builds are very early experimental builds.

Strawberry Shake itself works with .NET Standard 2.0 and C# 8. So you can use it almost everywhere.
