### ISSUE TITLE
Uknown variable in where clause only sometimes returns error

### ISSUE THREAD

**Issue by samburville** [ChilliCream/hotchocolate#3555]
**Description**
Possibly not a bug, but at least slightly inconsistent behaviour.

When using filtering and graphQL variables, an unknown variable in the where clause sometimes causes and error, and sometimes doesn't.

This seems to depend on whether the rest of the where clause contains primitive types or not.

**To Reproduce:**
Take a graphQL instance with filtering
For example, I took https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/CodeFirst and added filtering to this method (and installed HotChocolate.Types.Filters)
![image](https://user-images.githubusercontent.com/7041731/115410902-f0d76800-a1ea-11eb-91ad-fb886ddb1330.png)

Query:
```
query (
  $characterIds : [String]
  $where : ICharacterFilterInput!
){
  character(
    characterIds: $characterIds   
    where: $where
    )
    {
      id
      name
    }
}
```

Parameters 1:
```
{
  "characterIds" : ["1000", "2000"],
  "where" : {
      "name" : { "in" : "C-3PO" },
      "xyz" : 20
    }
}
```

Parameters 2:
```
{
  "characterIds" : ["1000", "2000"],
  "where" : {
      "name" : { "in" : ["C-3PO"] },
      "xyz" : 20
    }
}
```
Parameters 3:
```
{
  "characterIds" : ["1000", "2000"],
  "where" : {
      "name" : { "eq" : "C-3PO" },
      "xyz" : 20
    }
}
```

Parameters 1 and Parameters 3 will return an error message "Variable `where` got an invalid value"
Parameters 2, however, will treat this as an acceptable query, and return data.

**Expected behavior**
All three queries have the same fault, so it would be expected that they all fail, or all succeed.
E.g. all return "Variable `where` got an invalid value error."
or all three should ignore "xyz" and return results.

**Comment by PascalSenn** [comment]
Interesting, thanks for reporting! 
They should actually all fail

**Comment by samburville** [comment]
I had a quick look and error appears to come from 
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/Processing/VariableCoercionHelper.cs

Although haven't spotted why the cases behave differently
