### ISSUE TITLE
SS IOperationResult<> may be incorrect when the server returns an error

### ISSUE THREAD

**Issue by ChrisMH** [ChilliCream/hotchocolate#3556]
SS and HC 12.2.1-rc.0

I have a mutation I'm calling that, in the case I'm testing, is supposed to return AUTH_NOT_AUTHORIZED.

I am not seeing the expected error code, message, locations, and path in the errors collection of the IOperationResult.

This is the response JSON directly from the HTTP Transport, and is what I expect to see in this case:

StatusCode: 500
Body: "{"errors":[{"message":"The current user is not authorized to access this resource.","locations":[{"line":1,"column":101}],"path":["storeUserSettingFor"],"extensions":{"code":"AUTH_NOT_AUTHORIZED"}}]}"

The actual response does not break out the error code, message, location, or path as I would expect (i.e., the values from the response body are in ClientError[0].Code, ClientError[0].Message, ClientError[0].Locations, and ClientError[0].Path).  Please see the attached image.

![image](https://user-images.githubusercontent.com/731999/115432791-c7abdd00-a1d4-11eb-9924-f79c783269b8.png)

The error from the message body does appear in ClientError[0].Extensions.

Perhaps my expectations are incorrect, please correct me if so.

Thanks

**Comment by PascalSenn** [comment]
This is fixed in 12.5 by https://github.com/ChilliCream/hotchocolate/pull/3928
