### ISSUE TITLE
Guid serialization in strawberry shake only accepts one format. 

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#3562]
StrawberryShake only seems to recognize uuid values in "D" form (aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee). Is there a way to get it to use "N" form (aaaaaaaabbbbccccddddeeeeeeeeeeee)?

**Comment by dmg-hamann** [comment]
Sadly dotnet does only support the "D" format [link](https://github.com/dotnet/runtime/issues/1567#issuecomment-520462956).

My suggesstion would be to add another JsonElementExtension method. Maybe something like "GetGuidUnkownFormat" and use it in GetParseMethod in the JsonUtils class.

Currently I am struggeling with setting up vscode to run the code. But if I can it to work I will try to provide a pr for the issue.

**Comment by dmg-hamann** [comment]
After further digging into the code I was not able to get it to work. I guess at some point the GetGuid call to JsonElement should be replaced by Guid.Parse. I am sorry that I was not able yet to find the right spot ;)

**Comment by matt-psaltis** [comment]
Hit this today as well. I'm continually surprised with the missing features of dotnet's serializer. Thanks to everyone working to make this library even more amazing!

**Comment by michaelstaib** [comment]
@dmg-hamann so there is a workaround for this.... you can set the serializer to use string serialization and the use Guid.Parse instead of the JsonDocument serialization. We will fix that with the next patch release.
