### ISSUE TITLE
Allow Strawberry Shake to remove __typename from queries

### ISSUE THREAD

**Issue by Jaredcl1994** [ChilliCream/hotchocolate#3565]
The strawberry shake client includes __typename in the selection nodes by default, and it causes problems in my custom queries. The Strawberry Shake client should be able to be configured to not include the __typename field.

**Comment by PascalSenn** [comment]
@Jaredcl1994 are you using it in a client application like Blazor or Xamarin?

**Comment by Jaredcl1994** [comment]
I am using it in an ASP.NET core web api. It sets up the client to query another server.

**Comment by PascalSenn** [comment]
Ok. well you need the __typename field to identify the returned object. If you have a interface or union you dont know what data is returned. 
What kind if problems does it cause?

**Comment by Jaredcl1994** [comment]
Our generated server-side code wasn't configured to handle __typename in the query and it throws a `NotImplementedException`. We can also make changes on the server to fix this issue, but I was hoping for a client side correction.

**Comment by michaelstaib** [comment]
`__typename` is required by the GraphQL specification. Strawberry Shake expects that servers honor the contract. What server implementation are you using? If you are using Hot Chocolate it should automatically handle all of this.

**Comment by Jaredcl1994** [comment]
Ah so Strawberry Shake requires `__typename`? That is good to know, thanks. We are making queries to a service called BigQuery which requires non-standard SQL, so we are using a custom backend alongside Hot Chocolate.
