### ISSUE TITLE
[HotChocolate] Emitting state to new subscribers causes a race condition

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/hotchocolate#3572]
**Describe the bug**
c.f., [Slack message](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1619111529006000).

Often, we want to fetch the initial state of an object while simultaneously subscribing to changes. Attempting to do this as two discrete queries leads to a race condition wherein the object may be mutated between the query and the subscription (it's also very clunky for the clients). However, it appears there is no way to respond to a new subscription by sending the initial state of the subscribed object (ideally, ONLY to the new client, not to previous subscribers).

**To Reproduce**
Consider a typical subscribe pattern:

```
  [ExtendObjectType(Name = OpenControllerSchema.Subscription)]
  public class PortsSubscription {
    [Subscribe(With = nameof(SubscribeToAllPortState))]
    [AuthorizeReadControllers]
    public SystemPort OnPortChange([EventMessage] SystemPort port) => port;

    public ValueTask<IObservable<SystemPort>> SubscribeToAllPortState(
      [Service] ControllerManager controllerManager,
      CancellationToken ct
    ) => controllerManager.Ports.SubscribeToAll(PortTopic.State, ct);
```

There is no hook (AFAIK) in between the two methods. The latter is called implicitly, but the subscription is not active until it returns. Therefore, any attempts to emit a change in the `controllerManager.Ports.SubscribeToAll` method is invalid. That is, the `IObservable` has no observers yet because `Subscribe` has not yet been called.

**Expected behavior**
I would like to emit the initial state of the object back to ONLY the client which is newly subscribed. I have no strong opinions how to achieve this.

**Comment by zaneclaes** [comment]
Hmm... it looks like implementing my own `IObservable` class can solve this. Specifically, I'm overriding `Subscribe` to emit the last message to any new subscriber...

```
public class SubscribableTopic<T> : IObservable<T> where T : ITopicMessage {
    private readonly List<TopicSubscription<T>> _subscriptions = new();

    private T? _lastMessage;

    public virtual IDisposable Subscribe(IObserver<T> observer) {
      TopicSubscription<T> sub = new TopicSubscription<T>(this, observer);
      if (_lastMessage != null) sub.observer.OnNext(_lastMessage);
      return sub;
    }

    public virtual void Emit(T obj) {
      lock (_subscriptions) {
        for (int i = 0; i < _subscriptions.Count; i++) {
          _subscriptions[i].observer.OnNext(obj);
        }
      }
      _lastMessage = obj;
    }
```

... but I'd be interested in any feedback or ideas how this could be improved.

**Comment by michaelstaib** [comment]
An Observable is a good solution. If you have an Idea for how to make this a simple thing I am all yours :)
