### ISSUE TITLE
Pass obtained field as variable to another nested query

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/hotchocolate#3575]
I'm querying for two objects which are both needed in the same component. One of the queries have to wait for the other and use its "authorid" field as an argument for the other.Any way to implement this.?

`query BookDetail($author:String!) {
  Author(authorname: $author)
  {
    authorid
  }
  Book(id: authorid)
  {
    listofbooks {
      name
    }
  }
`
 in the query above Book needs authorid as an argument which is returned by the Author query.

**Comment by tobias-tengler** [comment]
I personally would add a book field to the author type. And then query the book through the author:
```sdl
query {
  author(authotname: $authorname) {
    # ....
    book {
      # ...
    }
  }
}
```
This way you can access the id of the author inside thr book field resolver.

**Comment by Sangeetha-Murugesan** [comment]
@tobias-tengler Thanks for the response. But,I want to execute queries in the way I mentioned earlier.

Is there any possibility to achieve this?

**Comment by PascalSenn** [comment]
@Sangeetha-Murugesan  there is also this (v10 docs):
https://chillicream.com/docs/hotchocolate/v10/execution-engine/batching/

**Comment by michaelstaib** [comment]
Can we close this?
