### ISSUE TITLE
A concise way to persist a GraphQL Argument in Scoped State

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#3576]
**Is your feature request related to a problem? Please describe.**

Currently I'm able to set scoped state in a Resolver in two ways:

1) Using the ResolverContext `context.ScopedContextData.SetItem`

2) Using `SetState<T>`

If I want to persist a GraphQL Argument in scoped state, I need two resolver arguments, the GraphQL Argument, and the ResolverContext or SetState.

**Describe the solution you'd like**
It would be really cool to have just one Resolver Argument namely the GraphQL Argument preceding by an Attribute like `PersistToScopedState` or something like that.

**Comment by PascalSenn** [comment]
@rstaib  
One problem I see with this are the linters. IDE and Sonar would see it as a issue that a parameter is not used
```csharp
public class Query 
{
      public Foo GetFoo([PersistToScopedState]string bar) => new Foo();
}
```

**Comment by rstaib** [comment]
@PascalSenn it's for a specific use-case where you want to do both, use the argument but also store it in the scoped state.
