### ISSUE TITLE
Class based interface types not implemented (pure code-first)

### ISSUE THREAD

**Issue by mikaelkolkinn** [ChilliCream/hotchocolate#3577]
**Describe the bug**
When using pure code-first and decorating a class or record with the attribute `InterfaceType`, all classes deriving the type also become interface types in the GraphQL schema.
This in turn leads to none of the interfaces receiving any implementing types.

**To Reproduce**
Tiny reproduction repository here: https://github.com/mikaelkolkinn/hotchocolate-interface-issue-repro 

C# code:

```c#
public class Query
{
    public string Hello => "World!";
    
    // This doesn't work since Orange and Pineapple become interfaces
    // public IEnumerable<Fruit> GetFruits() => new Fruit[] {new Orange(), new Pineapple()};
}

[InterfaceType]
public class Fruit
{
    public string Taste { get; } = "Sweet";
}

public class Orange : Fruit
{
    public string Color { get; } = "Orange";
}

public class Pineapple : Fruit
{
    public string Shape { get; } = "Strange";
}
```

Resulting GraphQL schema:

```graphql
schema {
    query: Query
}

interface Fruit {
    taste: String
}

interface Orange {
    color: String
    taste: String
}

interface Pineapple {
    shape: String
    taste: String
}

type Query {
    hello: String
}
```

**Expected behavior**
Expected GraphQL schema:

```graphql
schema {
    query: Query
}

interface Fruit {
    taste: String
}

type Orange implements Fruit{
    color: String
    taste: String
}

type Pineapple implements Fruit {
    shape: String
    taste: String
}

type Query {
    hello: String
}
```

**Additional context**
Hot Chocolate version: 11.2.2

**Comment by akolpachev** [comment]
Perhaps it can be easily fixed by changing "true" to "false" in IsDefined call :
```
        private static bool IsInterfaceType(ExtendedTypeReference unresolvedType)
        {
            return (unresolvedType.Type.IsInterface
                || unresolvedType.Type.Type.IsDefined(typeof(InterfaceTypeAttribute), true))
                && (unresolvedType.Context == TypeContext.Output
                    || unresolvedType.Context == TypeContext.None);
        }
```

**Comment by OneCyrus** [comment]
@mikaelkolkinn we are facing the same issue. did you find a workaround?

**Comment by mikaelkolkinn** [comment]
@OneCyrus 
The workaround was to use C# interface instead of a class for the interface type. Then it just worked, but required all types to implement the interface instead of inheriting the implementation from the class.

One workaround for inheriting the implementation was to create a base class that contained the interface implementation, but didn't actually implement the interface it self, and use that as a base class for all the types that should implement the GraphQL interface.

**Comment by michaelstaib** [comment]
interesting

**Comment by michaelstaib** [comment]
Issue found :) and it is logical. The attribute is inherited. So we essentially allow to put attributes on base classes. This allows you to introduce fields in a base type and annotate them. In this case the interface attribute is inherited by `Orange` thus orange becomes an interface.

**Comment by michaelstaib** [comment]
This is now fixed. We are still debating if we move it to 12 or 11.3 since this change has an impact on the overall behavior.

**Comment by michaelstaib** [comment]
This is now merged and will be included into 11.3.0-rc.0

**Comment by tobias-tengler** [comment]
We are undoing this in #3870 again, since it's causing issues in other areas. We will reconsider it for the v12 release, where we can potentially break existing behavior.

**Comment by michaelstaib** [comment]
11.3.1 will now have the 11.2.x behavior again. We probably will allow control for the inheritance behavior of the attributes for 12.

**Comment by michaelstaib** [comment]
So, we leave the patch in 11.3 intact and are now refining it in 12.

In 12 you have now control over inheritance of these attributes. In order to inherit one of the type attributes you can do:

```csharp
[InterfaceType(Inherited = true)]
public class Fruit
{
    public string Taste { get; } = "Sweet";
}
```

**Comment by mikaelkolkinn** [comment]
Looks good!

**Comment by Odonno** [comment]
I am trying to fix this issue but I have a new one with the v12.  

Based on this code:

```cs
[InterfaceType(Inherited = true)]
public abstract class BaseClass
{
    public Guid Id { get; set; }

    // other props...
}

public class Child : BaseClass
{
}
```

When one of my resolver try to return a list of `BaseClass`, an error is thrown, like this one:

```
Could not resolve the actual object type from `Namespace.Models.Child` for the abstract type `children`.
```

I am correctly returning the implementation types from the resolver. Do I need another annotation to declare all implementations of the base class? If that's necessary, I would be happy to do something like this:

```cs
[ImplementationType]
public class Child : BaseClass
{
}
```

**Comment by michaelstaib** [comment]
This is merged.
