### ISSUE TITLE
[Banana Cake Pop] Schema not refreshing

### ISSUE THREAD

**Issue by mrodrigues95** [ChilliCream/hotchocolate#3588]
**Describe the bug**
Reloading the schema via "Reload Schema" located at the top right of Banana Cake Pop results in multiple attempts to reload but with no success.

![image](https://user-images.githubusercontent.com/38141653/115972199-ed115180-a51a-11eb-9681-2e7bb6c0f4a1.png)

**To Reproduce**
1. Go to `/graphql`
2. Click on 'Reload Schema'
3. Open console
4. See multiple attempts to fetch schema with no success

**Expected behavior**
Schema should update with changes that were made.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
I've been making changes to my schema and reloading it with no issues until now. I have no clue why it's not refreshing and I've also tried in Google Chrome, same result.

Services:
```
services
    .AddGraphQLServer()
    .AddQueryType()
        .AddTypeExtension<ClassroomQueries>()
    .AddMutationType()
        .AddTypeExtension<ClassroomMutations>()
    .AddType<ClassroomType>()
    .EnableRelaySupport()
    .AddDataLoader<ClassroomByIdDataLoader>()
    .AddAuthorization();
```
```
app
    .UseRouting()
    .UseAuthentication()
    .UseAuthorization()
    .UseEndpoints(endpoints => endpoints.MapGraphQL());
```

**Comment by mrodrigues95** [comment]
Turns out, removing `.AddAuthorization()` from the services fixes this. Is this intended? If not, what's the work around? It seems odd i need to remove that every time I need to refresh the schema.

**Comment by MariaCobretti** [comment]
there are already an issue surrounding auth for introspection
https://github.com/ChilliCream/hotchocolate/issues/2869
may I also suggest the slack channel where this was discussed.
with one of the newest versions you can add .AllowIntrospection() to your query builder but you also need an HttpInterceptor

**Comment by mrodrigues95** [comment]
Thanks. This issue can be closed since the same problem is already being looked at.
