### ISSUE TITLE
[Banana Cake Pop] Save as for collection

### ISSUE THREAD

**Issue by DrJuriko** [ChilliCream/hotchocolate#3599]
I wonder, is there a possibility to save a collection of graphQl requests to defined location? For local testing BCP is very fine, but how can I share my requests with someone else? 

Or I missed some important documentation?

**Comment by michaelstaib** [comment]
This is coming.

**Comment by rstaib** [comment]
We'll bring data export functionality with the upcoming version which will come in May. In the first version it will be a simple import/export everything solution. The second version will be a more sophisticated solution backed by a cloud service where someone can share portions of a collection with individuals or teams.

**Comment by DrJuriko** [comment]
It would be great, thank you!
