### ISSUE TITLE
StrawberryShake: Don't set isSet Flag if Value Equals Previous Value

### ISSUE THREAD

**Issue by braidenstiller** [ChilliCream/hotchocolate#3603]
**Is your feature request related to a problem? Please describe.**
Having the isSet equality compare the incoming and current value and not set the IsSet flag if they're equal would be a useful optimization for input objects.

**Comment by michaelstaib** [comment]
Not really since if you explicitly set null we need to send that null to the server.

**Comment by braidenstiller** [comment]
That makes sense!
