### ISSUE TITLE
Extension types will throw an error

### ISSUE THREAD

**Issue by munkhnasanHUB** [ChilliCream/hotchocolate#3604]
**Describe the bug**
I'm writing an API on a .net core using hot chocolate v11.1. The following example of Extending Types [https://chillicream.com/docs/hotchocolate/defining-a-schema/extending-types/](url) indicates an error.
```
[ExtendObjectType(typeof(Session))]
public class SessionResolvers
{    
      public async Task<IEnumerable<Speaker>> GetSpeakersAsync([Parent] Session session) => ...
}
```
Example,  I have two table. I did not create any relation to these two tables. I want to one student have many programs using add field. 
1st 
```
public partial class TbStudName
{
	public long Sid { get; set; }
	public string Fname { get; set; }
	public string Lname { get; set; }
} 

```
2nd
```
public partial class TbStudProgram
{
	public int Recnr { get; set; }
	public long Sid { get; set; }
	public long ProgramId { get; set; }
} 
```

And extension is:

```
[ExtendObjectType(typeof(TbStudName))]
public class StudentExtension
{
	[UseSisiDbContext]
	[UseProjection]
	[GraphQLName("programs")]
	public IQueryable<TbStudProgram> GetPrograms(
	   [Parent] TbStudName stud,
	   [ScopedService] SisiDBContext dbContext)
	{
		return dbContext.TbStudPrograms.Where(t => t.Sid == stud.Sid);
	}
}
```

UseSisiDbContext is:
```
public class UseSisiDbContextAttribute : ObjectFieldDescriptorAttribute
{
        public override void OnConfigure(
            IDescriptorContext context,
            IObjectFieldDescriptor descriptor,
            MemberInfo member)
        {
            descriptor.UseDbContext<SisiDBContext>();
        }
 }
```

![Untitled](https://user-images.githubusercontent.com/18617568/116224240-00bef100-a783-11eb-9111-b52ef4d079cb.png)

But this error **Method 'System.Linq.IQueryable`1[GraphQL.HC.Entities.Models.sisiDBContext.TbStudProgram] GetPrograms(GraphQL.HC.Entities.Models.sisiDBContext.TbStudName, GraphQL.HC.Entities.Models.sisiDBContext.SisiDBContext)' declared on type 'GraphQL.HC.API.Schema.ExtendObjectTypes.StudentExtension' cannot be called with instance of type 'GraphQL.HC.Entities.Models.sisiDBContext.TbStudName'**

return IEnumerable, IQueryable, List is same error.

**Comment by michaelstaib** [comment]
can you upgrade to 11.2.2 and try again ... we fixed a lot of issues with the extensions in the last patch release.

**Comment by munkhnasanHUB** [comment]
I upgrade to 11.2.2. It's fixed. Thank you
