### ISSUE TITLE
MongoDbFiltering problems

### ISSUE THREAD

**Issue by Chameleon45** [ChilliCream/hotchocolate#3607]
Recently, I started using `MongoDbFiltering` in my project for searching users and encountered some problems. I'm using сode-first approach and modified options of GraphqlServer like this to ignore not binded fields:
```C#
services.AddGraphQLServer("userSchema").ModifyOptions(c => c.DefaultBindingBehavior = BindingBehavior.Explicit)
```
Also I wrote simple search method in my query type and describe it by desriptor like that: 
```C#
    public class UserQuery
    {
        private readonly UserManager userManager;

        public UserQuery(UserManager userManager)
        {
            this.userManager = userManager;
        }

        public IExecutable<User> Search()
        {
            return userManager.GetCollection().AsExecutable();
        }
    }

    public class UserQueryType : ObjectType<UserQuery>
    {
        protected override void Configure(IObjectTypeDescriptor<UserQuery> descriptor)
        {
            descriptor
                .Field(uq => uq.Search())
                .Type<ListType<UserType>>()
                .Name("search")
                .Description("Search user")
                .UseFiltering();
        }
    }
```
And here is my first problem :( Filter input variable of search method contains only "and" and "or" fields:
![image](https://user-images.githubusercontent.com/50486434/116260849-bd16b800-a77f-11eb-9fc1-b8b84197a26a.png)
But if I remove modified options, `UserFilterInput` start to contain other fields for search:
![image](https://user-images.githubusercontent.com/50486434/116261915-c6eceb00-a780-11eb-86a7-f6b3955fd7f6.png)
I didn't know that `BindingBehavior` affects the arguments too. So I guess I need to add an `Argument` using descriptor but I can't figure out what to write here because I want to use default `UserFilterInput` without defining new one. 
Also I have troubles with searching users by birthday. This field can be nullable and when I'm trying to do something like that:
``` birthday: { lt: "20-02-1920", gt: "20-02-2000" }``` I'm receiving this error: 
```Unable to cast object of type 'System.DateTimeOffset' to type 'System.Nullable`1[System.DateTime]'.```
Besides, I don't know if I understood correctly how to use `MongoDbFiltering` with `IQueryable`. Is it correct to write something like this: 
``` C#
services
    .AddGraphQLServer("userSchema")
    .AddFiltering()
    .AddMongoDbFiltering("mongoScope")
```
and then write `UseFiltering()` for `IQueryable<TEntity>` seacrh and `UseFiltering("mongoScope")` for  `IExecutable<TEntity>` search ?
And sorry for this messy report because I don't really know where it's better to ask questions like that.

**Comment by tobias-tengler** [comment]
For questions regarding functionality, please [join our slack](https://bit.ly/joinchilli). 
Issues are for tracking bugs and feature requests. If your question turns out to be a bug then you can of course write an issue! :)

**Comment by PascalSenn** [comment]
Hi @Chameleon45  

1. You should be able to opt into the binding behaviour
```csharp
public class UserFilterInputType : FilterInputType<User>
{
    protected override void Configure(IFilterInputTypeDescriptor<User> descriptor) 
    {
        descriptor.BindFieldsImplicitly()
    }
}
```

2. `Unable to cast object...` I will have to look at this
3. Correct, `UseFiltering` when you have a IQueryable and UseFiltering("mongoscope") when you have a mongo IExecutable
Also, if you use mongodb with IQueryable expect many things to not work :)

**Comment by Chameleon45** [comment]
@PascalSenn thank you for your answer)

**Comment by PascalSenn** [comment]
No worries #3613 should fix the date time bug
