### ISSUE TITLE
Objects with ObjectId type ID return null in relay root node

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [ChilliCream/hotchocolate#3615]
**Describe the bug**
Objects with ```ObjectId``` type ID return null in relay root node.

**To Reproduce**
1. Create an object with MongoDB ```ObjectId``` ID
```cs
class Test {
  [BsonId]
  public ObjectId Id { get; set; }
}
```
2. Get its Base64 Globally Unique ID by
```graphql
query Query {
  testObjects(first: 5) {
    nodes {
      id
    }
  }
}
```
return
```json
{
  "data": {
    "testObjects": {
      "nodes": [
        {
          "id": "VGFnCmQ1ZDg5NWNmNTBiNDc0YzA4NGNiZTE1MTM="
        }
      ]
    }
  }
}
```
3. Query root node
```graphql
query Query {
  node(id: "VGFnCmQ1ZDg5NWNmNTBiNDc0YzA4NGNiZTE1MTM=") {
    id
  }
}
```
return
```json
{
  "data": {
    "node": null
  }
}
```
4. If you change the ID type to ```string``` or ```int```, then it works.

**Expected behavior**
Objects with ```ObjectId``` work like objects with ```string``` or ```int``` id

**Desktop (please complete the following information):**
 - OS: Windows 10 or Ubuntu 18.04.2
 - Version 11.2.2

**Additional context**

**Comment by michaelstaib** [comment]
Thanks for reporting, we will put it on the may backlog.
