### ISSUE TITLE
EFCore Projection to type with Dictionary<string,string> causes errors

### ISSUE THREAD

**Issue by ApocDev** [ChilliCream/hotchocolate#3619]
**Describe the bug**
When enabling projections on EFCore IQueryable<CustomType> when CustomType has a Dictionary property (e.g.; pgsql JSON, or mysql JSON), HotChocolate seems to be generating incorrect projection expressions.

**To Reproduce**
The following repo case(s):

```csharp
    public class Repro
    {
        public long Id { get; set; }
        public Dictionary<string, string> Dictionary { get; set; } = new();

        public Projected Projected { get; set; }
    }

    public class Projected
    {
        public long Id { get; set; }
        public string SomeField { get; set; }
    }
```

```csharp
        [UseDbContext(typeof(MyDbContext))]
        [UseProjection]
        public IQueryable<TaskVersion> GetReproById([ScopedService] MyDbContext db, long id)
            => db.Repros.Where(t => t.Id == id);
```

And finally, the query:

```graphql
query GetRepro($id: Long!) {
    reproById(id: $id) {
        id
        dictionary {
          key
          value        
        }
        projected {
          someField
        }
    }
}
```

**Expected behavior**
Expected IDictionary (and similar counterparts) to be projected as "fields" rather than "objects" when queried.

Interestingly enough, it seems like the projections somehow get projected onto the sub-object. (The errors are pretty misleading in general in this case)

**Comment by steveoh** [comment]
also related to https://github.com/ChilliCream/hotchocolate/issues/3617

**Comment by PascalSenn** [comment]
```csharp
    public static class DictionaryProjectionsSchemaBuilderExtensions
    {
        public static ISchemaBuilder AddDictionaryProjections(this ISchemaBuilder builder)
        {
            if (builder is null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            return builder.AddConvention<IProjectionConvention>(
                new ProjectionConventionExtension(
                    x => x.AddProviderExtension(
                        new DictionaryProviderExtension(y => x.RegisterFieldHandler<QueryableSpatialProjectionScalarHandler>()))));
        }
    }

    public class QueryableSpatialProjectionScalarHandler
        : QueryableProjectionScalarHandler
    {
        public override bool CanHandle(ISelection selection) =>
            selection.Field.Member is not null &&
            typeof(Dictionary<string,string>).IsAssignableFrom(selection.Field.Member.GetReturnType());
    }
```

I think this should do the job

**Comment by luvolondon** [comment]
> 
> 
> ```cs
>     public static class DictionaryProjectionsSchemaBuilderExtensions
>     {
>         public static IRequestExecutorBuilder AddDictionaryProjections(this IRequestExecutorBuilder builder)
>         {
>             if (builder is null)
>             {
>                 throw new ArgumentNullException(nameof(builder));
>             }
> 
>             return builder.AddConvention<IProjectionConvention>(
>                 new ProjectionConventionExtension(
>                     x => x.AddProviderExtension(
>                         new DictionaryProviderExtension(y => x.RegisterFieldHandler<QueryableSpatialProjectionScalarHandler>()))));
>         }
>     }
> 
>     public class QueryableSpatialProjectionScalarHandler
>         : QueryableProjectionScalarHandler
>     {
>         public override bool CanHandle(ISelection selection) =>
>             selection.Field.Member is not null &&
>             typeof(Dictionary<string,string>).IsAssignableFrom(selection.Field.Member.GetReturnType());
>     }
> ```
> 
> I think this should do the job
> 
> ```cs
> services.AddGaphqlServer()
>   ...
>   .AddProjections()
>   .AddDictionaryProjections();
> ```
Where do I find class "DictionaryProviderExtension"?

I´m trying this workaround to be able to use "UseProjection" together with Dictionary properties. I´m using latest v12 RC version.
I don´t find class DictionaryProviderExtension . Does this no longer work with v12?

If I remove "UseProjection" all Dictionary<string,string> properties are working (output as array of {key,value}). If I add UseProjection the output of the Dictionary properties is null.
I can set the Dictionary properties to AnyType. But this breaks mutations which then no longer work.

Thank you for any help to get my Dictionary properties working.

**Comment by fredrik-stock** [comment]
Did the following to get it working in version 12.3:

```cs
using HotChocolate.Data.Projections.Expressions.Handlers;
using HotChocolate.Data.Projections;
using HotChocolate.Execution.Configuration;
using HotChocolate.Execution.Processing;
using System.Collections.Generic;
using System;
using HotChocolate.Utilities;
using Microsoft.Extensions.DependencyInjection;

namespace XX.YY
{
    public static class DictionaryProjectionsSchemaBuilderExtensions
    {
        public static IRequestExecutorBuilder AddDictionaryProjections(this IRequestExecutorBuilder builder)
        {
            if (builder is null)
                throw new ArgumentNullException(nameof(builder));

            return builder.AddConvention<IProjectionConvention>(
                new ProjectionConventionExtension(
                    x => x.AddProviderExtension(
                        new ProjectionProviderExtension(y => y.RegisterFieldHandler<QueryableDictionaryProjectionScalarHandler>()))));
        }
    }

    public class QueryableDictionaryProjectionScalarHandler
        : QueryableProjectionScalarHandler
    {
        public override bool CanHandle(ISelection selection) =>
            selection.Field.Member is not null &&
            typeof(Dictionary<string, string>).IsAssignableFrom(selection.Field.Member.GetReturnType());
    }
}
```

My changes from @PascalSenn 's solution are basically replacing a few method names.

This combined with adding .UseDictionaryProjection() after .UseProjection() fixed it for me.

**Comment by ir-dev** [comment]
Any news on this? Seems to be still an issue with v13.9.4. Btw. @fredrik-stock's solution works for me but I feel like that should actually work out of the box.

**Comment by onionhammer** [comment]
This is still an issue, despite being marked complete
