### ISSUE TITLE
Build slim HotChocolate.AspNetCore package

### ISSUE THREAD

**Issue by petli** [ChilliCream/hotchocolate#3631]
We use HotChocolate.AspNetCore in an API that is deployed as an AWS Lambda, and in that environment it is important to reduce the deploy size as much as possible to have quicker cold starts and better user experience.

When investigating our deploy size the HotChocolate.AspNetCore package stood out, at 15 MB it is an order of magnitude bigger than the next biggest (EFCore). I've tracked this down to the contents of the Resources folder, which appears to be the Banana Cake Pop IDE.

Since we have no need for that tool in the production deployments, would it be possible to move the IDE into a separate nuget package, so we can have a HotChocolate.AspNetCore that is much smaller? 

This would break projects that depend on HotChocolate.AspNetCore and use the IDE, though, so I don't expect you to do that in a minor version. So within the version 11 would it be possible to make HotChocolate.AspNetCore into a meta package that pulls in HotChocolate.AspNetCore.Core (which contains everything but the tool) and HotChocolate.AspNetCore.BananaCakePop (which adds the IDE)?

I'm willing to have a go at the initial project and solution restructuring required for this in a PR, if that would help.

**Comment by jorrit** [comment]
This would be great to have.
