### ISSUE TITLE
Disable default 30 second request timeout when debugger is attached

### ISSUE THREAD

**Issue by mvestergaard** [ChilliCream/hotchocolate#3656]
**Is your feature request related to a problem? Please describe.**
The default 30 second timeout can make debugging quite confusing because the request is suddenly aborted. When the cancellation token is propagated down to database calls and alike, this will lead to an exception at some point.

**Describe the solution you'd like**
Allow null for `RequestExecutorOptions.ExecutionTimeout` and default it to null when `Debugger.IsAttached` is true, and in that case, don't add the request timeout middleware.

**Describe alternatives you've considered**
Assigned some arbitrary large value to `ExecutionTimeout` when debugger is attached in user code. This works fine, but I believe it'd be a good idea to have this be default behavior, as it'll likely lead to confusion for unsuspecting devs while trying to debug.

**Comment by michaelstaib** [comment]
Yes ... but we should not set it to null. I think we can put it to a high number like 30 min. 

Essentially we should introduce a constructor to `RequestExecutorOptions` and have a if check there. If the debugger is initialized we will set the execution timeout to 30 min. This allows people still to set their own values that are adhered to even if the debugger is attached.
