### ISSUE TITLE
Website  headings are rendered broken

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#3660]
The Website has issues with Headings
[See Here](https://chillicream.com/docs/hotchocolate/api-reference/extending-filtering/#provider-descriptor)
![image](https://user-images.githubusercontent.com/14233220/117140248-7c392780-adad-11eb-8776-ffd418c84349.png)

**Comment by tobias-tengler** [comment]
Is this being worked on? It's really annoying :sweat_smile: 
If not, I can take a look...
