### ISSUE TITLE
Integration tests respond with non-success when using WebApplicationFactory<T>

### ISSUE THREAD

**Issue by BaileyMillerSSI** [ChilliCream/hotchocolate#3663]
**Describe the bug**
When writing integration tests that use WebApplicationFactory<T> to simulate a server, the response for graphql requests is always:
`{"errors":[{"message":"Expected a \u0060String\u0060-token, but found a \u0060Name\u0060-token.","locations":[{"line":2,"column":3}],"extensions":{"code":"HC0011"}}]}`

**To Reproduce**
1. Follow the [Quick Start Guide](https://chillicream.com/docs/hotchocolate/get-started/)
2. Add a test class with the following:
```
public class SimpleTest
    {
        public HttpClient Client { get; set; }

        public WebApplicationFactory<Startup> Factory { get; set; }

        public SimpleTest()
        {
            Factory = new WebApplicationFactory<Startup>();

            Client = Factory.CreateClient();
        }

        [Fact]
        public async Task Test1()
        {
            var response = await SendAsync(@"{
  book {
    title
    author {
      name
    }
  }
}
");

            var text = await response.Content.ReadAsStringAsync();
        }

        public async Task<HttpResponseMessage> SendAsync(
            string query
        ) =>
            await Client.SendAsync(new HttpRequestMessage(HttpMethod.Post, "/graphql")
            {
                Content = new StringContent(query, Encoding.UTF8, "application/json")
            });
    }
```

**Expected behavior**
The response from graphql should be a 200 status code with the body:
```
{
  "data": {
    "book": {
      "title": "C# in depth.",
      "author": {
        "name": "Jon Skeet"
      }
    }
  }
}
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Version 10.0.18363 Build 18363

**Comment by michaelstaib** [comment]
The request you specified is invalid. Have a look at the graphql over http spec

**Comment by BaileyMillerSSI** [comment]
Did this change coming from v10 to v11? These tests were passing while using v10.

**Comment by michaelstaib** [comment]
V10 allowed non spec compliant requests. With version 11 we have moved to implement the GraphQL over HTTP spec which abandoned these kinds of request.

**Comment by KSrivatsan85** [comment]
Hi Michael, Can you please explain what exactly was wrong in the request . I am getting the same error but only while passing the request through jmeter. The same request works through Insomnia.

**Comment by treymack** [comment]
The GraphQL over HTTP Spec requires special formatting. This is working for me so far (HC 12).

```
        ...
        var response = await client.SendAsync(CreateGraphQLHttpRequest(query));
    }

    private static HttpRequestMessage CreateGraphQLHttpRequest(string query)
    {
        return new HttpRequestMessage(HttpMethod.Post, "/graphql")
        {
            Content = new StringContent(GetGraphOverHttpPostBody(query), Encoding.UTF8, "application/json"),
        };
    }

    private static string GetGraphOverHttpPostBody(string query)
    {
        return $@"{{
""query"": ""{query.Replace("\n", "").Replace("\r", "")}""
}}";
//""variables"": {{}} // todo: add variables support
    }
```
