### ISSUE TITLE
Generated code throws ArgumentNullException when using conditional @include directive.

### ISSUE THREAD

**Issue by RhodeHummel** [ChilliCream/hotchocolate#3668]
**Describe the bug**
Generated code throws ArgumentNullException when executing a query that uses conditional @include directive.

**To Reproduce**

Using the following query. `imageData` is defined as a required field in `schema.graphql`
```
fragment fields on ImagePreview
{
  id
  name
  imageData @include(if: $includeImageData)
}

query GetImagePreview($id: UUID!, $includeImageData: Boolean = false) {
  imagePreview(id: $id) {
      ...fields
  }
}
```

When running the query, `service.GetImagePreview.ExecuteAsync(id, false)`, the StrawberryShake generated code enforces imageData to be a required field regardless if the $includeImageData flag is true or false

**Expected behavior**
StrawberryShake should not enforce null checks when the @include directive is false.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by PascalSenn** [comment]
Hi @RhodeHummel  thanks for reporting this issue
Can you provide us with the schema too?

**Comment by RhodeHummel** [comment]
Sure, it would look something like this (shortened for brevity)

```
schema {
  query: Query
  mutation: Mutation
}

type Query {
  imagePreview(id: UUID!): ImagePreview
}

type ImagePreview {
  id: UUID!
  filename: String!
  imageData: String!
}
```

**Comment by eduardocp** [comment]
Hi guys, any news? This still happens on last version (13.9.9) of cli and strawberry shake
