### ISSUE TITLE
Duplicate word "Filter" while using ListFilterInputType

### ISSUE THREAD

**Issue by Chameleon45** [ChilliCream/hotchocolate#3676]
I have custom `UserLanguageFilter` class which I apply to the list:
```C#
descriptor
    .Field(auif => auif.LanguagesToLearn)
    .Type<ListFilterInputType<UserLanguageFilter>>()
    .Description("Languages that user want to learn");
```
It works fine but it generates filter type with duplicate word "Filter" in my schema:
![image](https://user-images.githubusercontent.com/50486434/117421371-26888a80-af27-11eb-9653-c2a0ecab65c1.png)
Applying  `UserLanguageFilter` to simple field (not list) generates `UserLanguageFilterInput` in schema as expected.
So I think it would be more correct if it generated `ListUserLanguageFilterInput` without second word "Filter" (like in default `ListStringOperationFilterInput` and other types)

**Comment by PascalSenn** [comment]
I think the convention is it has to end in input, then we rewrite it

so to solve this you can do two things
1. Rename the type to `UserLanguageFilterInput` 
2. Use the descriptor to rename the type `descriptor.Name("UserLanguageFilter")`

**Comment by Chameleon45** [comment]
I added "Input" to my custom filter class and it seems to work now. I didn't see word "Input" in customization examples in documentation and I didn't know that it was necessary so I thought that it is a bug. Anyway, sorry for reporting.
