### ISSUE TITLE
Simplify DataLoader API

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#368]
**Fetch Delegates**

```csharp
public delegate IReadOnlyDictionary<TKey, TValue> Fetch<TKey, TValue>(IEnumerable<TKey> keys);

public delegate ILookup<TKey, TValue> FetchGrouped<TKey, TValue>(IEnumerable<TKey> keys);

public delegate TValue FetchSingle<TKey, TValue>(TKey key);

public delegate TValue FetchSingle<TValue>();
```

**Comment by drowhunter** [comment]
I like the adhoc design, as this is more like how graphql-dotnet has it implemented. [Example](https://graphql-dotnet.github.io/docs/guides/dataloader#examples)

So with this approach you wouldn't have to pre-register your dataloader in schema configuration correct?

**Comment by drowhunter** [comment]
I had fooled around trying to implement this a couple of days ago but it didn't work because my dataloaders weren't really attached to anything so they didn't get dispatched. 

Anyway I assume that you already have it figured out how to integrate the adhoc approach as your technique seems to achieve the same goal.


**Interface**
```
public interface IDataLoaderFactory
    {
        IDataLoader<TKey, TValue> Create<TKey, TValue>(string name, FetchDataDelegate<TKey, TValue> fetch, DataLoaderOptions<TKey> options = null);
    }
```
**DataLoader Factory**
```
public class DataLoaderFactory : IDataLoaderFactory
    {
        private Dictionary<string, object> _loaderCache;

        public DataLoaderFactory()
        {
            _loaderCache = new Dictionary<string, object>();
        }

        public IDataLoader<TKey, TValue> Create<TKey, TValue>(string name,FetchDataDelegate<TKey, TValue> fetch, DataLoaderOptions<TKey> options = null)
        {
            if(_loaderCache.TryGetValue(name, out object loader))
            {
                return loader as IDataLoader<TKey, TValue>;
            }

            loader = new DataLoader<TKey, TValue>(options ?? new DataLoaderOptions<TKey> { AutoDispatching = false }, fetch);
            _loaderCache.Add(name, loader);

            return (IDataLoader<TKey, TValue>)loader;
        }
    }
```
**Startup**
```
public void ConfigureServices(IServiceCollection services)
{
      services.AddScoped<IDataLoaderFactory, DataLoaderFactory>();
}
```
**Resolver**
```
public Task<User> GetUser(int id, [Service] IDataLoaderFactory factory, [Service] IUserRepository userRepo) // UserByIdDataLoader loader)
{
           var dataloader = factory.Create<int, User>("someuniquestring", async keys =>
            {
                var data = await userRepo.FetchOneToOne(keys, "UserId", "Users", o => o.UserId);
                return data.Values.Select(Result<User>.Resolve).ToList();
            });
     return dataloader.LoadAsync(id);
}
```

**Comment by michaelstaib** [comment]
- [ ] Remove State Objects
- [ ] Refactor Execution Context 
- [ ] Remove Operation Request
- [ ] Split Execution Middleware
- [ ] Introduce interface IDataLoaderRegistry
- [ ] How do we handle global data loader? Remove them?
- [ ] How do we treat load once calls? Maybe this should not be a data loader?

**Comment by michaelstaib** [comment]
#366 shall also be addressed with this issue

**Comment by michaelstaib** [comment]
> How do we handle global data loader? Remove them?

The `ExecutionScope` is gone. If one wants to have global and request DataLoader then a registry can be declared twice. We should add some helper extensions for this scenario.

**Comment by michaelstaib** [comment]
> How do we treat load once calls? Maybe this should not be a data loader?

The are now treated like a `FetchSingle` with a fixed key.

**Comment by michaelstaib** [comment]
DataLoader can now be created and added went the schema is created or they can be created ad-hoc. 
We removed the DataLoader from the  resolver context and added some extension methods for the `IResolverContext`.


So, basically now we can do the following:

```csharp
context.DataLoader<string, string>("FooLoader", key => context.Service<Foo>().GetMyData());
```

Moreover, I still can access my preregistered or my class DataLoader like the following:

```csharp
context.DataLoader<FooLoader>();
```

**Comment by michaelstaib** [comment]
This one is now finished. The documentation task is #446
