### ISSUE TITLE
Incorrect total count in MongoDbOffsetPaging

### ISSUE THREAD

**Issue by Chameleon45** [ChilliCream/hotchocolate#3683]
I'm using `MongoDbOffsetPaging` (with `MongoDbFiltering`) in my search query. I need total count of elements for generating pagination component so I added this option via `SetPagingOptions`. `totalCount` field appeared in query result but it's value is incorrect and depends on values of `take` and `skip` fields. 
Fore example, filters should return 30 items:
```
"take": 12,
"skip": 0 //items for first page

//returns: "totalCount": 13
```
```
"take": 12,
"skip": 12 //items for second page

//returns: "totalCount": 13
```
```
"take": 12,
"skip": 24 //items for third page

//returns: "totalCount": 6
```
In all examples I receive correct number of items (12, 12 and 6) but `totalCount` has different values (expected "30" in all cases). `MongoDbPaging` (cursor based pagination) returns correct `totalCount` but I can't use it for generation of pagination component.

**Comment by michaelstaib** [comment]
This one is related to #3868.
