### ISSUE TITLE
StrawberryShake Runtime errror deserializing GeoJSONPointType

### ISSUE THREAD

**Issue by ChrisMH** [ChilliCream/hotchocolate#3685]
Runtime error while deserializing the the 'coordinates' field of a GeoJSONPointType
HC and SS 11.3.0-preview.7

I'm trying to desterilize the 'coordinates' field of a point
```
fragment currentStatusFields on CurrentStatus {
    position {crs coordinates}
}
```
I'm getting this error:
```
The requested operation requires an element of type 'String', but the target element has type 'Array'., code:
   Exception: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Array'
```

I assume that is because the actual JSON contains an array for the coordinates:
```
"position":{"__typename":"GeoJSONPointType","crs":4326,"coordinates":[-85.15869,41.12649,0]}
```

I've tried registering my own Serializer for the 'Position' scalar type (that's the type my schema reports for coordinates):
```
extend scalar Position
    @runtimeType(name: "global::NetTopologySuite.GeometriesGraph.Position")
    @serializationType(name: "global::System.Array")
```

However, in that case I get a build error:
```
Serialization format not supported
```

**Comment by RobTF** [comment]
@ChrisMH see #6261 for possible solution to this.
