### ISSUE TITLE
Mixing convention and explicit schema type code first design.

### ISSUE THREAD

**Issue by BernhardGlueck** [ChilliCream/hotchocolate#3688]
Currently, as far as i can see, one can design their schema either via conventions 
 (normal C# types, fields, types are inferred based on conventions, and/or attributes ) or 
by inheriting from the appropriate schema design type ( ObjectType<T>, InputType<T> etc ) and 
fluently configure those fields. 

In my use case i have a multi tenant plugin based web application where i want to augment certain graphql types via plugins.
So i use ObjectType<T> for my augmentable schema types,  that are later extended via plugins. 
So far so good, but ObjectType<T> does not offer a way to add a field and basically say -> For this field use this C# POCO type and use conventions to derive its schema.  ( basically best of both  worlds approach where some types are explicitly configured while others, especially input types are inferred ) 

Is there any solution to this ?

**Comment by PascalSenn** [comment]
That works out of the box?
you can mix an match all approaches, even schema first

**Comment by michaelstaib** [comment]
I am closing this as it was answered. Schema building approaches can be mixed out of the box.
