### ISSUE TITLE
nodes field in relay support

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#3695]
**Is your feature request related to a problem? Please describe.**
Often it's nice to be able to query multiple nodes by their ID in one client call. 

GitHub's api offers a `nodes` field for this purpose, as seen [here](https://docs.github.com/en/graphql/reference/queries#node).

I thought there was a definition of this field in the Relay [server spec](https://relay.dev/docs/guides/graphql-server-specification/) too, but can't find it anymore. Perhaps I'm getting confused with the connection spec.

**Describe the solution you'd like**

.AddRelaySupport() to automatically (or behind a boolean option) add a `nodes` field as below to root `Query` type.

```graphql
type Query {
  "Lookup nodes by a list of IDs."
  nodes(
    "The list of node IDs." ids: [ID!]!
  ): [Node]! 
}
```

Notice how the inner type of the array is nullable (as per GH's), presumably as `null` should be returned if the ID is not found and that the order matters (which is what I was trying to find in a spec somewhere...).

For consideration:
1. Is this just a wrapper around multiple `node` calls executed in parallel or is it more clever? 
  a. e.g. attempting to group by type, which would then possibly need `nodes` support for each type?
  b. in a stitching context, batching with dataloaders would alleviate this some what, but not everyone uses stitching.
2. Parallelization of calls
3. How would this work with stitching? We'd need a new custom middleware kind of like [this one does](https://gist.github.com/benmccallum/bc421a21f2c55755b8a7dce1a55047b5) for `node`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by benmccallum** [comment]
@michaelstaib / @tobias-tengler , this is in v12 now yea?

**Comment by tobias-tengler** [comment]
@benmccallum yes
