### ISSUE TITLE
Cannot create two descriptors for mutation inherited from ObjectType class

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3696]
Cannot create two descriptors for mutation inherited from ObjectType class. 
If add only first descriptor CreateMaster, it works. But when I try second one (UpdateMaster), I get "Unexpected token H in JSON at position 0":
```csharp
public partial class Mutation : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("CreateMaster")
        .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
        .Argument("input", _ => _.Type<CreateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("createMaster");

        descriptor.Field("UpdateMaster")
        .ResolveWith<Resolvers>(m => m.UpdateMaster(default!, default!)).UseDbContext<Context>()
        .Argument("input", _ => _.Type<UpdateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("updateMaster");
    }

    private class Resolvers
    {
        public async Task<MasterPayload> CreateMaster([ScopedService] IMasterService service, CreateMasterInput input)
        {
            var result = await service.CreateMasterAsync(input);
            return result;
        }

        public async Task<MasterPayload> UpdateMaster([ScopedService] IMasterService service, UpdateMasterInput input)
        {
            var result = await service.UpdateMasterAsync(input);
            return result;
        }
    }
}
```

I use input type:
```csharp
public class CreateMasterInput : InputObjectType<Master>
{
    protected override void Configure(IInputObjectTypeDescriptor<Master> descriptor)
    {
        base.Configure(descriptor);
    }
}
```
Also, if I do not inherit mutation from an ObjectType, but simply use a general class, then this method (which pas parameter InputObjectType) disappears from the schema.

**Comment by PascalSenn** [comment]
Can you provide a simple reproduction of this issue? 
This should work without a problem

**Comment by TDDinAction** [comment]
> Can you provide a simple reproduction of this issue?

For my case it reproduct for versions 11.1.0 and 11.2.2. This is code is works:

public partial class Mutation : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("CreateMaster")
        .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
        .Argument("input", _ => _.Type<CreateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("createMaster");

        descriptor.Field("UpdateMaster")
        .ResolveWith<Resolvers>(m => m.UpdateMaster(default!, default!)).UseDbContext<Context>()
        .Argument("input", _ => _.Type<UpdateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("updateMaster");
    }

    private class Resolvers
    {
        public async Task<MasterPayload> CreateMaster([ScopedService] IMasterService service, CreateMasterInput input)
        {
            var result = await service.CreateMasterAsync(input);
            return result;
        }

        public async Task<MasterPayload> UpdateMaster([ScopedService] IMasterService service, UpdateMasterInput input)
        {
            var result = await service.UpdateMasterAsync(input);
            return result;
        }
    }
}

But when I add additional descriptor, I got error "Unexpected token H in JSON at position 0"

        descriptor.Field("UpdateMaster")
        .ResolveWith<Resolvers>(m => m.UpdateMaster(default!, default!)).UseDbContext<Context>()
        .Argument("input", _ => _.Type<UpdateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("updateMaster");
        
An interesting detail is that not only the mutation itself ceases to work, but the schema as a whole is no longer available in the playdround. The same effect is obtained if you use extensions or try to move methods into separate classes, this does not affect the error.

**Comment by PascalSenn** [comment]
I guess you have a schema exception somewhere.
Where do you get `"Unexpected token H in JSON at position 0"`

**Comment by TDDinAction** [comment]
> I guess you have a schema exception somewhere.
> Where do you get `"Unexpected token H in JSON at position 0"`

For any request. For example:

mutation {
  createMaster(input: {
    firstName: "test",
    lastName: "test last name",
  }){
    
      firstName,
    lastName,
    }
  }
  
  This and all another requests start to work if I drop it:
  
          descriptor.Field("UpdateMaster")
        .ResolveWith<Resolvers>(m => m.UpdateMaster(default!, default!)).UseDbContext<Context>()
        .Argument("input", _ => _.Type<UpdateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Name("updateMaster");

**Comment by tobias-tengler** [comment]
That error is just a generic Javascript JSON parsing error. It should be caused by an Exception of Hot Chocolate. You should be seeing an Exception in your ASP.NET Core debug output that should be more indicative of what is wrong.

**Comment by TDDinAction** [comment]
> That error is just a generic Javascript JSON parsing error. It should be caused by an Exception of Hot Chocolate. You should be seeing an Exception in your ASP.NET Core debug output that should be more indicative of what is wrong.

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The name `MasterInput` was already registered by another type. (...UpdateMasterInput)
      
      But CreateMasterInput and UpdateMasterInput. But they inherited from InputObjectType<Master> both.

**Comment by tobias-tengler** [comment]
The name of the POCO in InputObjectType<POCO> is chosen as the schema name of thr input object type per default. Since both InputObjectTypes inherit from the same POCO you get a name collision.
Override the Configure method in one or both of the input types and use the descriptor to give a unique name, e.g.
```csharp
descriptor.Name("UpdateMasterInput");
```

**Comment by TDDinAction** [comment]
> ```cs
> descriptor.Name("UpdateMasterInput");
> ```

Thank a lot, that helped.

**Comment by TDDinAction** [comment]
> The name of the POCO in `InputObjectType<POCO>` is chosen as the schema name of the input object type per default. Since both InputObjectTypes inherit from the same POCO you get a name collision.
> Override the Configure method in one or both of the input types and use the descriptor to give a unique name, e.g.
> 
> ```cs
> descriptor.Name("UpdateMasterInput");
> ```

Thanks a lot. One more question if it possible. I am tiring validate my input and follow manual https://chillicream.com/docs/hotchocolate/v10/execution-engine for using middleware. For this class Mutation which inherited from ObjectType I set .Use<ValidateInputMiddleware>(), but debugger indicates that the execution of the code does not start the middleware.

        descriptor.Field("CreateMaster")
        .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
        .Argument("input", _ => _.Type<CreateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Use<ValidateInputMiddleware>()
        .Name("createMaster");
        
        I use this validation middleware:
        
using FluentValidation;
using HotChocolate;
using HotChocolate.Resolvers;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SomeProject.UI.Middleware
{
    public class ValidateInputMiddleware
    {
        private readonly FieldDelegate _next;

        public ValidateInputMiddleware(FieldDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(IMiddlewareContext context)
        {
            var serviceProvider = context.Service<IServiceProvider>();

            if (!context.FieldSelection.Arguments.Any())
            {
                await _next(context);
                return;
            }

            var failures = context.FieldSelection.Arguments
                    .Select(x => context.Argument<object>(x.Name.Value))
                    .SelectMany(argumentInstance => serviceProvider
                                    .GetServices(typeof(IValidator<>).MakeGenericType(argumentInstance.GetType()))
                                    .OfType<IValidator>(),
                            (instance, validator) => (Instance: instance, Validator: validator))
                    .SelectMany(x => x.Validator.Validate((IValidationContext)x.Instance).Errors)
                    .ToList();

            if (!failures.Any())
            {
                await _next(context);
                return;
            }

            foreach (var failure in failures)
            {
                context.ReportError(ErrorBuilder.New()
                        .SetCode("error.validation")
                        .SetMessage(failure.ErrorMessage)
                        .SetExtension("propertyName", failure.PropertyName)
                        .SetPath(context.Path)
                        .Build());
            }
        }
    }
}

**Comment by michaelstaib** [comment]
It would be great if you create one question per issue so that it can be better followed.

**Comment by TDDinAction** [comment]
> It would be great if you create one question per issue so that it can be better followed.

Okay.
