### ISSUE TITLE
Issue with sorting middleware when used with Cosmosdb

### ISSUE THREAD

**Issue by manoj-agasibagila** [ChilliCream/hotchocolate#3707]
We are seeing performance issue with sorting middleware when used with Cosmosdb with more than 1million records.

It works perfectly fine with Pagination and filtering middlewares. When we add UseSorting, the response time increases to 1minute from around 5seconds. We have tested the call to cosmos with same query from application to make sure there is no issue with database and it seems to returning results pretty fast. So we feel there is an issue with Hotchocloate library while applying sorting criteria to Iqueryable and fetching the results.

Query:
```csharp
[UsePaging(IncludeTotalCount = true)]
[UseFiltering]
[UseSorting]
        public IQueryable<User> GetReceipts([Service] IUserDao userDao)
        {
            return userDao.GetUsers();
        }
```
```csharp
Dao:
public IQueryable<User> GetUsers()
        {
            return _receiptScanProcessContainer
                .GetItemLinqQueryable<User>(true);             
        }
```
Startup.cs:
```csharp
services.AddGraphQLServer()
                .AddQueryType<Query>()
                .AddFiltering()
                .AddSorting()
                .SetRequestOptions(_ => 
                    new HotChocolate.Execution.Options.RequestExecutorOptions { 
                        ExecutionTimeout = TimeSpan.FromMinutes(1) 
                    });
```
OS: Win10
Version: Hotchocolate v11.2.2

**Comment by PascalSenn** [comment]
@manoj1022770  how did you tests? and what was the query? 
Because what we do is just `.OrderBy(x => x.Foo)`

**Comment by manoj1022770** [comment]
@PascalSenn We have recently pushed our application to production with Graphql endpoint built using hotchocolate and CosmosDb. With large data in production, we started seeing the issue when we query the data with pagination enabled, with single filter applied and default orderby set. It is taking minutes to respond. If we just remove orderby keeping pagination and filter, response is faster. Then we are able to reproduce it local.

Below is sample query where we facing issue with, 
{
  users(
    first:50,
    where: {campaignId: {eq: "1234" } },
    order: {creationTime: ASC}
  ){
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges{
      node{
        a
        b
        c        
      }
    }
  }  
}

**Comment by PascalSenn** [comment]
what's the difference in execution time between
```csharp
queryable.Where(x => x.ComapignId == "1234").OrderBy(x => x.CreateiionTime).Take(50)
```
vs
```csharp
queryable.Where(x => x.ComapignId == "1234").Take(50)
```

**Comment by manoj1022770** [comment]
Query without order clause taking 4-6secs, while the one with order clause is taking around 60secs. 
And if run the query directly against cosmosdb client without Hotchocolate, its giving results in 4-6secs.
var results = _userContainer
                .GetItemLinqQueryable<User>(true)
                .Where(x => x.ComapignId == "1234")
               .OrderBy(x => x.CreationTime)
               .Take(50)
               .ToList()

**Comment by PascalSenn** [comment]
Can you publish a project with a reproduction on github? 
We translate the incomming query into a expression tree. So in fact, we end up with the same query that you have written manually. 
It could be an issue of middleware ordering or something.
Need to check the source to see what's happening

**Comment by manoj1022770** [comment]
@PascalSenn I have created sample solution, please find the clone url https://github.com/manoj1022770/hotchoclolate-with-cosmosdb.git
Please replace connectionstring, databasename and containername in appsettings.json

**Comment by manoj-agasibagila** [comment]
@PascalSenn Any update on the above issue?

**Comment by onionhammer** [comment]
This seems like it should still be open

When '.Sort(context)' is applied to an 'CosmosLinqQuery', the query appears unmodified.

![cosmossorting](https://user-images.githubusercontent.com/969938/169856938-afdef1c3-537d-45ae-acce-f035b3b40939.jpg)



Expression tree is unchanged
