### ISSUE TITLE
Subscriptions are not cancelled when connection is closed  while waiting

### ISSUE THREAD

**Issue by tvildo** [ChilliCream/hotchocolate#3715]
CancellationToken in Subscriptions is not working.

Repo which show that bug exists: https://github.com/tvildo/hotbug
1. Clone repo.
2. Run project and execute subscription https://localhost:5001/graphql/:
```
subscription TestSub {
  onSessionEvent {
    name
  }
}
```
3. Refresh Entire page.
4. Subscription must be cancalled but it is not so console keeps logging:
![hotbugCapture](https://user-images.githubusercontent.com/8401382/118804997-40e13300-b85a-11eb-9810-94b3a7d41185.PNG)

I tried to investigate why this is happening and I found that, you are creating New CancellationToke by linking using `CreateLinkedTokenSource`:
https://github.com/ChilliCream/hotchocolate/blob/82bc367141144e095a7524f02820e2133504be75/src/HotChocolate/Core/src/Execution/Pipeline/TimeoutMiddleware.cs#L30

but CreateLinkedTokenSource gets disposed after handler does it's job and after CreateLinkedTokenSource is disposed  it's token can't be cancelled anymore

_Originally posted by @tvildo in https://github.com/ChilliCream/hotchocolate/issues/2740#issuecomment-844012575_

**Comment by tvildo** [comment]
I pulled 11.3.0-rc.0 in https://github.com/tvildo/hotbug
1. When I close connection (refresh page) subscription should close.  (works)
2. When I stop subscription it should close. (**not working**) 
![2021-06-09 05-51-02](https://user-images.githubusercontent.com/8401382/121281024-19471e80-c88c-11eb-8aa7-820b5b5591a9.gif)

**Comment by michaelstaib** [comment]
I will have a look at this

**Comment by michaelstaib** [comment]
I have replicated the error.

**Comment by michaelstaib** [comment]
This one is fixed.
