### ISSUE TITLE
Error the provided middleware type must contain an invoke method

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3717]
I use validation directive:

```
public class ValidateInputDirectiveType : DirectiveType<ValidateInputDirective>
    {
        protected override void Configure(IDirectiveTypeDescriptor<ValidateInputDirective> descriptor)
        {
            base.Configure(descriptor);

            descriptor
                .Name("validateInput")
                .Location(DirectiveLocation.FieldDefinition)
                .Use<ValidateInputMiddleware>();
        }
    }
```
    
It uses in the mutation:

```
public partial class Mutation : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("CreateMaster")
        .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
        .Argument("input", _ => _.Type<CreateMasterInput>())
        .Type<ObjectType<MasterPayload>>()
        .Use<ValidateInputDirectiveType>()
        .Name("createMaster");
    }

    private class Resolvers
    {
        public async Task<MasterPayload> CreateMaster([ScopedService] IMasterService service, CreateMasterInput input)
        {
            var result = await service.CreateMasterAsync(input);
            return result;
        }
    }
}
```

In testing aims I use simple middleware from manual https://chillicream.com/docs/hotchocolate/v10/execution-engine to be sure that everything is fine with the shell itself:

```
public class ValidateInputMiddleware
    {
        private readonly FieldDelegate _next;
        public ValidateInputMiddleware(FieldDelegate next)
        {
            _next = next;
        }
        public async Task InvokeAsync(IMiddlewareContext context)
        {
            await _next(context);
        }
    }
```

But it returns diagnostic error (it is only diagnostic error from ASP .NET Core: https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Diagnostics.EntityFrameworkCore/src/DatabaseDeveloperPageExceptionFilter.cs#L85-L89 and should not stop EntityFrameworkCore operations):

```
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseDeveloperPageExceptionFilter[7]
      An exception occurred while calculating the database error page content. Skipping display of the database error page.
```
      
      To avoid this error messeage, I swithed off app.UseDeveloperExceptionPage() and got real error:
      
```
       Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8Q97Q6MR3E", Request id "0HM8Q97Q6MR3E:00000017": An unhandled exception was thrown by the application.  System.NotSupportedException: The provided middleware type must contain an invoke method.
```
      
       It looks like HotChocolate middleware is using standard one and in this situation cannot correctly call this invoke method. For exapmle, ASP .NET Core middleware expect HttpContext and  cannot convert IMiddlewareContext to it. It turns out this is either a conversion error or the section of manual about middleware is outdated.

**Comment by PascalSenn** [comment]
the return type should be `ValueTask`

**Comment by TDDinAction** [comment]
> the return type should be `ValueTask`

Ok, I set it to class Resolvers, but nothing has changed.

**Comment by PascalSenn** [comment]
@TDDinAction  i meant the Middleware :)

**Comment by TDDinAction** [comment]
> i meant the Middleware :)

Ok, I set it also to Middleware, but nothing has changed. Signatura: async ValueTask Invoke(IMiddlewareContext context).

**Comment by TDDinAction** [comment]
> i meant the Middleware :)

I have checked it for signatures:

async ValueTask Invoke(IMiddlewareContext context)
async ValueTask InvokeAsync(IMiddlewareContext context)

But the error remained the same.

**Comment by PascalSenn** [comment]
ah 
i see, well the problem is that you apply the directive like it was a middleware:
```csharp
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("CreateMaster")
            .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
            .Argument("input", _ => _.Type<CreateMasterInput>())
            .Type<ObjectType<MasterPayload>>()
            .Use<ValidateInputDirectiveType>() // <---------
            .Name("createMaster");
    }
```

This is not correct. 
You need to add the directive there
```csharp
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("CreateMaster")
            .ResolveWith<Resolvers>(m => m.CreateMaster(default!, default!)).UseDbContext<CRMContext>()
            .Argument("input", _ => _.Type<CreateMasterInput>())
            .Type<ObjectType<MasterPayload>>()
            .Directive<ValidateInputDirective>() // <---------
            .Name("createMaster");
    }
```
and register the type of the directive on the schema
```csharp
service.AddGraphQLServer()
   ....
   .AddType<ValidateInputDirectiveType>();
```

**Comment by TDDinAction** [comment]
> i see, well the problem is that you apply the directive like it was a middleware:

I set your changes and got new error:

```
 Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8SB9T14EQB", Request id "0HM8SB9T14EQB:0000001F": An unhandled exception was thrown by the application.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The object type `ValidateInputDirective` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType<DataArt.CRM.UI.GraphQL.Directive.ValidateInputDirective>)
```
      
      Also I replaced .Directive<ValidateInputDirective>() by .Directive<ValidateInputDirectiveType>()
      
      In this case, the diagnostic errors disappear, but as with the case of direct connection of the middleware, the debugger shows that the middle does not run.

**Comment by PascalSenn** [comment]
@TDDinAction  
My bad
you have to use `.Directive<ValidateInputDirective>()`
But you have to register it with ` .AddDirectiveType<ValidateInputDirectiveType>();`

**Comment by TDDinAction** [comment]
> .AddDirectiveType<ValidateInputDirectiveType>();

I use HotChocolate v11.2.2 in this version .AddDirectiveType cannot be added to descriptor also resharper does not find for extantion method.

**Comment by PascalSenn** [comment]
I created a example here:
 https://github.com/PascalSenn/hotchocolate-directive-example

**Comment by TDDinAction** [comment]
> I created a example here:
> https://github.com/PascalSenn/hotchocolate-directive-example

Thanks a lot, I will use directives in this way.

**Comment by TDDinAction** [comment]
And I rewrote the code in accordance with the example. It doesn't work the right way for me. The directive is executed only once, and not with every request, since it is bound to the fields of entity GraphQL types, and not to the mutation descriptor field where it cannot be bound.

Nevertheless, this example made it possible to find the reason why the shell did not start for my case. Immediately after executing the directive, the shell does not start, it starts after 24 seconds and an error is returned:

```
warn: Microsoft.EntityFrameworkCore.Query[10102]
      The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.
warn: Microsoft.EntityFrameworkCore.Query[20504]
      Compiling a query which loads related collections for more than one collection navigation either via 'Include' or through projection but no 'QuerySplittingBehavior' has been configured. By default Entity Framework will use 'QuerySplittingBehavior.SingleQuery' which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'
```
      
      It looks like this case: https://stackoverflow.com/questions/65311789/entity-framework-core-5-0-warning-limiting-operator-skip-take-without-an It looks like this error occurs while applying the projection:
      
```
         [UseDbContext(typeof(Context))]
        [UsePaging(typeof(ContactType))]
        [UseFiltering]
        [UseSorting]
        public IQueryable<MasterViewModel> GetContacts([ScopedService] Context context)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Contact, ContactViewModel>()
            .ForMember(d => d.SomeField, opt => opt.MapFrom(c => c.ContactMeans.OrderByDescending(p => p.ModifiedOn).FirstOrDefault(p => p.SomeTypeId == 1).Value))
            );

            IQueryable<MasterViewModel> result = context.Masters.ProjectTo<MasterViewModel>(config);

            return result;
        }
```
        
        In this case, the database context itself successfully performs the mutation itself to add a record, that is, it is a diagnostic error that is ignored in any other case ( https://stackoverflow.com/questions/65311789/entity-framework-core-5-0-warning-limiting-operator-skip-take-without-an ). It looks like this error is created by using projection. The only thing I have not yet managed to localize the source HotChocolate or AutoMapper.

**Comment by PascalSenn** [comment]
@TDDinAction  is this resolved?
