### ISSUE TITLE
Schema Stitching without Gateway requests sends $fields:id values as null in HC11

### ISSUE THREAD

**Issue by mlstubblefield** [ChilliCream/hotchocolate#3718]
**Describe the bug**

**To Reproduce**
1. Create a simple local graphql schema in an HC 11.2.2 project as of writing this
2. Add a remote schema to that
3. Add an extension that bridges the two schemas
4. Use a network sniffing tool such as fiddler to inspect the outbound network traffic
5. You'll note that the variables __0_____fields_productId will contain a null value, which will produce cascading errors
6. Each stitched value will then be null and produce an EXEC_NON_NULL_VIOLATION error.

Below you can see a sample schema - I removed some internal terminology from this screenshot to make it easier to follow.
![image](https://user-images.githubusercontent.com/7562533/119030016-fc938700-b96e-11eb-89b4-7988cf43ab80.png)

Below you can see the network sniffing that I performed showing that the request was made with null values in the variables. What isn't included is the fact that I can see the values of $fields:productId coming back from the local schema.
Please note that skuBaseNumber is our equivalent to "productId" I removed some internal terminology in my other screenshot.
![image](https://user-images.githubusercontent.com/7562533/119029499-5051a080-b96e-11eb-81c3-d8813e5b1454.png)

**Expected behavior**
- The outbound network request variables should match the $fields:productId values that come back from the local schema response. They should not be made with all null values.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version HC 11.2.2

**Comment by PascalSenn** [comment]
@mlstubblefield  did you try it with `AddLocalSchema` too?

**Comment by xStorm111** [comment]
@PascalSenn i have the same issue and i tried the `AddLocalSchema` and it didn't change nothing

**Comment by PascalSenn** [comment]
Did you add it like this?

```csharp
service.AddGraphQL("localSchema")
      .AddQueryType<YourLocalQueryType>()

service.AddGraphQLServer()
    ...
   .AddRemoteSchema("Foo")
   .AddLocalSchema("localSchema")
```

**Comment by mlstubblefield** [comment]
That worked for me. Thanks so much!
