### ISSUE TITLE
StrawberryShake Fails to parse response when two different fragments on same type are present in the query

### ISSUE THREAD

**Issue by HonzaBejvl** [ChilliCream/hotchocolate#3728]
**Describe the bug**
Imagine a structure:

I have a `Listing`. `Listing` can be `ListingSimple` or `Project`. `ListingSimple` can be `Offer` or `Auction`. `Project` may have multiple `ListingSimple` items.

`ListingSimple` has a field `Estate`.

I have two fragments:

```
fragment Estate on Estate{
 fieldA : String
 fieldB : String!
}
```

```
fragment ProjectEstate on Estate{
 fieldA : String
}
```

`query listing : Listing!
` allows me to use both estate fragments in the same query. But when the Shake is parsing Listing-Project result, a null value exception is thrown because Shake is trying to deserialize not nullable fieldB in ProjectEstate even there is no fieldB.

**To Reproduce**
I created a min repro repo https://github.com/HonzaBejvl/throwaway-shake-repro-example/tree/full-schema
You can run the code from the full-schema branch. Schema is a little bit more complicated than described above, but the plot is the same. 

**Expected behavior**
Result without error.

**Desktop (please complete the following information):**
 - OS: mac
 - Version 12.0.0-preview.6

**Comment by kellyrbourg** [comment]
I'd love to see this get fixed as the bug is still very much in existence. There are no work arounds AFAIK; we have resulted into adding a different client library to work around the issue.

Best case, you'll get a runtime exception; worst case, the wrong data will be hydrated which could lead to some obscure runtime issues.
