### ISSUE TITLE
Smarter XML doc to schema doc translations

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#3730]
**Is your feature request related to a problem? Please describe.**
It's awesome to be able to use XML doc in HC, but there's a few limitations.

##### Opportunity 1
Using `see` to point to C# types should convert to the real name in the graphql schema, 
e.g. `<see cref="BookingDto" />` --> `Booking` if you had a naming convention that dropped the Dto. 
e.g. `<see cref="BookingType" />` --> `Booking` if `BookingType` was a `ObjectType<BookingDto>`

##### Opportunity 2
`/// <inheritdoc />` is great to document things in a cross-cutting way, but then the doc on the base type needs to be generic enough for all places where that flows to. 

An example would be GitHub's `createdAt` field, which is clearly done in a cross-cutting manner as it looks like:
```graphql
"Identifies the date and time when the object was created."
createdAt: DateTime!
```

You can see they've used the word "object" which isn't super great and I think we could do better if we supported token substitution, like $type, or $type$ or whatever we agree on.

**Describe the solution you'd like**
##### Opportunity 1
I think this'd need to be done in the existing XML crawling when the full context is known, before only the innerText of the XML node is taken.

##### Opportunity 2
Potentially we could leave all the XML documentation crawling stuff now as is, still having it set the description of a field as `"Identifies the date and time when the $type$ was created."` or the, and then just use a type interceptor to crawl all fields and their descriptions, looking for these and replacing them.

##### Etc?
I also wonder if there's any other tokens we could/should support:
* ...?

**Describe alternatives you've considered**
Do it in the XML crawling, which could be just as easy... not too familiar with how it works. 

**Additional context**
N/A.

**Comment by benmccallum** [comment]
This could also be done with #3180

**Comment by cjzzz** [comment]
Using `see` also seems to have some strange behaviour if it references a method (possibly a bug, or just an unhandled situation?).

If I have a mutation:

```gql
public async Task<TestMutationPayload> TestMutation(TestMutationInput input)
{
    ...
```

With the input object defined as:

```gql
/// <summary>
/// Input object for <see cref="TestMutations.TestMutation"/>.
/// </summary>
public class TestMutationInput
{
    ...
```

Then this appears in the SDL as:

```gql
"""
Input object for TestMutationInput).
"""
input TestMutationInput {
  ...
```

The comment always seems to reference the object type of the last parameter to the mutation, followed by an ending bracket.

Ideally this would instead be output as:

```gql
"""
Input object for TestMutation.
"""
input TestMutationInput {
  ...
```

**Comment by tobias-tengler** [comment]
@cjzzz This does appear to be a bug. If raised a new issue about it: #4070
