### ISSUE TITLE
Cannot use Mediator pattern with Mutations

### ISSUE THREAD

**Issue by jacknugent** [ChilliCream/hotchocolate#3732]
**Describe the bug**
If I try to call a mutation using `Mediator.send(payload)`, it works the first time, but after the first time, it throws this error:
```
Cannot access a disposed object.
Object name: 'IServiceProvider'.
```

**To Reproduce**
1. Download project at [HotChocolateMutationsBug.zip](https://github.com/ChilliCream/hotchocolate/files/6534967/HotChocolateMutationsBug.zip) (project based on hot chocolate's official [Server example](https://github.com/ChilliCream/hotchocolate/tree/develop/templates/Server/content))
2. Run project 
3. Go to [http://localhost:49570/graphql/](http://localhost:49570/graphql/)
4. Run this mutation twice:
```
mutation {
    echoMessage(
      payload: {
        message: "this is a test"
      }) 
  }
```
(Note: all this mutation does is return back the `message` parameter)

5. On the first run of this mutation, you will get `this is a test` back. But on the second run, `Mediator.Send(payload)` will throw an exception and return the error: `Cannot access a disposed object. Object name: 'IServiceProvider'.`

**Expected behavior**
The mutation call should return back the `message` parameter on each call.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Version 10.0.18362 Build 18362

**Additional context**
This looks like a Dependency Injection issue with Hot Chocolate. This code and the Mediatr code are correct and use Scoped/Transient, but somewhere in GraphQL there may be a singleton. Possibly, that singleton disposes the service provider after the first request, and never again gets a new one because it's a singleton.

**Comment by PascalSenn** [comment]
do you mind pushing the source onto github rather than in a zip? :) 
It makes it a lot easier for us to have a quick look

**Comment by jacknugent** [comment]
Sure, [here's the repo](https://github.com/jacknugent/hotchocolatebug).

**Comment by PascalSenn** [comment]
Either do
```csharp
      
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
        services.AddScoped<Mutation>();
            services
                .AddGraphQLServer()
                .AddQueryType<Query>()
                .AddMutationType<MutationType>();

            services.AddMediatR(typeof(EchoMessageType));
        }

```

or just use method injection:
```csharp

    public class Mutation
    {
        public async Task<string> EchoMessage(
             [Service] ISender mediator, 
             EchoMessageType payload)
        {
            try
            {
                return await mediator.Send(payload);
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
    }
```

Also if the `MutationType` is empty you do not need it. You can just register `.AddMutationType<Mutation>`

**Comment by jacknugent** [comment]
Thank you! I confirmed that both of those solutions work.

**Comment by thangchung** [comment]
@PascalSenn My project was also gotten this same issue. And we could fix it by using the way you describe above. I just concern about why don't fix it and put it into the HotChocolate libs (core-libs) so that other people don't have got when using it with MediatR in the future?

**Comment by PascalSenn** [comment]
@thangchung  I am not sure if i understand :) 
There is not really a bug in the core lib.
The object that is used by the types is by default singletons, so you do not allocate a new obejct on every request. If you want to make the obejct scoped, you register it as a scoped service.
Without flagging the dependency as scoped on the service provider, hot chocolate does know what scope the dependency should be
