### ISSUE TITLE
There is no object type implementing interface with abstract class

### ISSUE THREAD

**Issue by erwan-joly** [ChilliCream/hotchocolate#3741]
**Describe the bug**
When using an abstract class it doesn't seems like hotchocolate is able to infer interfaces opposite to the documentation https://chillicream.com/docs/hotchocolate/defining-a-schema/#interface-definition .

**To Reproduce**

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddRouting()
        .AddGraphQLServer()
        .AddQueryType<Query>()
        .AddType<TextMessage>()
}
 
[InterfaceType]
public abstract class Message
{
  public User SendBy { get; set; }
  public DateTime CreatedAt { get; set; }
}

public class TextMessage : Message
{
  public string Content { get; set; }
}

```
this currently return There is no object type implementing interface `Message`

if we use interfaces instead of abstract class it works fine. 

```csharp
 public void ConfigureServices(IServiceCollection services)
 {
    services
        .AddRouting()
        .AddGraphQLServer()
        .AddQueryType<Query>()
        .AddType<TextMessage>()
 }
 
[GraphQLName("Message")]
public interface IMessage
{
  User SendBy { get; set; }
  DateTime CreatedAt { get; set; }
}

public class TextMessage : IMessage
{
  public User SendBy { get; set; }
  public DateTime CreatedAt { get; set; }
  public string Content { get; set; }
}

```

**Expected behavior**
It should infer the interface type based on abstract class

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version  HotChocolate.AspNetCore 11.2.2

**Comment by tobias-tengler** [comment]
Relates to #3577.
