### ISSUE TITLE
InputObjectType with relay ID

### ISSUE THREAD

**Issue by TDDinAction** [ChilliCream/hotchocolate#3742]
I try to get relay ID from input.

```csharp
public class MasterDeactivationInputType : InputObjectType<MasterDeactivationInput>
{
    protected override void Configure(IInputObjectTypeDescriptor<MasterDeactivationInput> descriptor)
    {
        if (descriptor is null)
        {
            throw new ArgumentNullException(nameof(descriptor));
        }

        descriptor.Field(p => p.Id).ID(typeof(Master).Name);
    }
}
```

The returned error:

> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

But this id has generated by HotChocolate (implements node) and has successfully decoded by Convert.FromBase64String(encodedString) or by standard JavaScript function atob: "Master\ni1". Perhaps this is due to the fact that, unlike other types, relay ID is not supported by filting, for example. But then, the error message is incorrect for these cases.

**Comment by michaelstaib** [comment]
Can you provide a repro for this issue.

**Comment by TDDinAction** [comment]
> Can you provide a repro for this issue.

I use HotChocolate v11.1.0 and EntityFrameworkCore v5.0.2 (CodeFirst). MasterDeactivationInputType is based on:

```
public class MasterDeactivationInput
    {
        public string Id { get; set; } = string.Empty;
    }
```

This input is used in this way:

```
    public partial class Mutation
    {
        public async Task<MasterPayload> DeactivateMaster([Service] IMastersService service, MasterDeactivationInput input)
        {
            var result = await service.DeactivateMasterAsync(StringHelper.DecodeGraphQLNodeId(input.Id)).ConfigureAwait(false);
            return result;
        }
    }
```
    
    Also I have registred mutation in this way:
    
```
        public partial class MutationObjectType : ObjectType<Mutation>
    {
        protected override void Configure(IObjectTypeDescriptor<Mutation> descriptor)
        {
            descriptor.Field(_ => _.DeactivateMaster(default!, default!))
            .Name("deactivateMaster")
            .Argument("input", a => a.Type<MasterDeactivationInputType>());
        }
    }
```

And in the startup:

`.AddMutationType<MutationObjectType>()
`
It is schema with MasterDeactivationInputType works for StringType. It returns error only when I replace it to:

`descriptor.Field(p => p.Id).ID(typeof(Master).Name);`

My sugestion what in previous version replay ID key uses not "MasterPayload\ni1", but for example "MasterPayload::i1" and validator still expact "::" instead of "\n".

**Comment by TDDinAction** [comment]
For these purposes, you can use ID attribute on the entity in this scenario, there is no need to use InputObjectType.
