### ISSUE TITLE
How to resolve service registered in IServiceCollection?

### ISSUE THREAD

**Issue by featherbits** [ChilliCream/hotchocolate#375]
When using ASP.NET Core and registering services in `IServiceCollection` from `Startup.ConfigureServices` method, those services then are not available in `IResolverContext` when I use `T Service<T>()`.

Is this by design or a bug?

**Comment by michaelstaib** [comment]
Are you using our middleware?

**Comment by michaelstaib** [comment]
Here is our middleware example with dependency injection:
https://github.com/ChilliCream/hotchocolate-aspnetcore/blob/next/examples/StarWars/Startup.cs

**Comment by featherbits** [comment]
I'm trying to resolve service from context of `IMiddlewareContext`. My middleware is registered with `IMiddlewareConfiguration.Use(FieldMiddleware middleware)`. I have not registered any service provider on schema configuration. GraphQL is added from `GraphQLApplicationBuilderExtensions`.

**Comment by michaelstaib** [comment]
Can you give feedback once you figured it out so I can close this issue or we can investigate further.

**Comment by featherbits** [comment]
I made upgrade to 0.7.0-preview.3 and still getting the same issue. Can it be related to the fact that I'm using schema first approach? It looks like my setup is the same as in https://github.com/ChilliCream/hotchocolate-aspnetcore/blob/next/examples/StarWars/Startup.cs

**Comment by michaelstaib** [comment]
Should not make a difference.... can you share some code?

**Comment by michaelstaib** [comment]
We could create a small StarWars schema first project...

**Comment by michaelstaib** [comment]
Could you set up a small schema first project  that replicates and share that repo?

**Comment by featherbits** [comment]
> Could you set up a small schema first project that replicates and share that repo?
Working on it

**Comment by featherbits** [comment]
On fresh project it works as expected. I will add more code to it in order to replicate setup.

**Comment by featherbits** [comment]
Looks like false alarm. Cleared bin and obj directories and it seems that it resolved the issue. Sorry for that.

**Comment by michaelstaib** [comment]
No problem....

we have a slack group ... so if you like to join use the following link:

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNDkxMjA1MzkxNzMwLTFlMjUxMWQ2YWQ4ODRkYmI5MWJiMmNhNzI2MjQ4MzRmZjlhY2Y0Yjg0MzM1YTRhMDc4YWUwOTViMjNhNzY1ZGI
