### ISSUE TITLE
Add graphql-ws support for subscriptions

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#3758]
https://github.com/enisdenjo/graphql-ws

**Comment by dmirizzi** [comment]
Is this feature planned to implemented in the near future? We are hoping to switch from apollo to graphql-ws for the client, as apollo uses subscriptions-transport-ws, which is no longer maintained and the project instead recommends to use graphql-ws.

**Comment by ntziolis** [comment]
@enisdenjo Any chance you know c# ? :)

**Comment by enisdenjo** [comment]
I've done some Unity long time ago. I cannot say I know it well enough. 😄

**Comment by ntziolis** [comment]
@michaelstaib Has work started on this if not I might give it a try over the Christmas break. 

In regards to scope:
- the protocol covers more than just a replacement for handling subscriptions over ws
- it allows to use websockets as a transport layer for any graphql operation (query, mutation + subscriptions)

So my question is:
Is the current plant to offer the new protocol for subscriptions only (to replace the legacy protocol). Or is the plan to enable the full protocol and allow the user to choose different transport protocols for query / mutation as well? The second is obviously bigger in scope.

**Comment by michaelstaib** [comment]
Hi there,

Work already is underway, we hope it will go into 12.6 so beginning of January. We are implementing this for the client- and server-side. We also will integrate it into Banana Cake Pop so it is quite a connected effort do get it into every bit of the platform.

We know the scope of the protocol and we are enabling it for all scenarios. In this PR we will rework how we handle execution for socket protocols. We will still also support the old sub-protocol for subscription for compatibility.

But if you want you can join in and we break up parts of the work.

**Comment by michaelstaib** [comment]
This is now implemented.

**Comment by kimjuho-daim** [comment]
How can I change hot-chocolate graphql server subscription protocol that support graphql-ws?

I found [this page](https://chillicream.com/docs/hotchocolate/v11/api-reference/aspnetcore#subscription-transport), and this issue.

But I don't know yet.

**Comment by michaelstaib** [comment]
`graphql-ws` is supported with the Hot Chocolate Version 13 preview packages.
https://www.nuget.org/packages/HotChocolate/13.0.0-preview.28

Both protocols are now ... we still support the legacy apollo protocol as well.

In one of the next previews we also will add `graphql-sse` as a third alternative for subscriptions.

**Comment by michaelstaib** [comment]
BTW.... if you upgrade to preview 28 the protocol will work out of the box... so there is nothing that you must do to activate it ... just `app.MapGraphQL()` and it will be available.

**Comment by sanjaykulkarni04** [comment]
> `graphql-ws` is supported with the Hot Chocolate Version 13 preview packages. https://www.nuget.org/packages/HotChocolate/13.0.0-preview.28
> 
> Both protocols are now ... we still support the legacy apollo protocol as well.
> 
> In one of the next previews we also will add `graphql-sse` as a third alternative for subscriptions.

@michaelstaib Is this available in the **13.5.1** version? (https://github.com/ChilliCream/graphql-platform/releases/tag/13.5.1)
