### ISSUE TITLE
Bulk RegisterTypes

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#377]
[https://github.com/drowhunter/hotchocolate/tree/BulkRegisterTypes](https://github.com/drowhunter/hotchocolate/tree/BulkRegisterTypes)

I have a branch where i am trying to create a bulk register function
It works when run in my web application using 
`typeof(Startup).Assembly`

 but I am unable to test referencing the correct assembly

Not sure whether *GetCallingAssembly()* or *GetExecutingAssembly()* is correct

heres the code for brevity

```
public void RegisterTypes<TQuery>(){
                RegisterTypes(typeof(TQuery));
}
        public void RegisterTypes<TQuery, TMutation>(){
                RegisterTypes(typeof(TQuery),typeof(TMutation));
        }
        public void RegisterTypes<TQuery, TMutation, TSubscription>(){
                RegisterTypes(typeof(TQuery),typeof(TMutation),typeof(TSubscription));
        }

       public void RegisterTypes(Type queryType, Type mutationType = null, Type subscriptionType = null)
        {
            IEnumerable<Type> graphQlTypes = System.Reflection.Assembly.GetExecutingAssembly()
                .GetTypes()
                .Where(x => !x.IsAbstract &&
                            (typeof(INamedType).IsAssignableFrom(x)
                            ));


            foreach (Type type in graphQlTypes)
            {
                INamedType namedType = RegisterObjectType(type);

                if(type.FullName == queryType.FullName)
                    Options.QueryTypeName = namedType.Name;
                else if(type.FullName == mutationType?.FullName)
                    Options.MutationTypeName = namedType.Name;
                else if(type.FullName == subscriptionType?.FullName)
                    Options.SubscriptionTypeName = namedType.Name;
            }
            
        }
```

**Comment by michaelstaib** [comment]
They might be both wrong depending where your code is :)

**Comment by michaelstaib** [comment]
Have you looked at the way Microsoft does it for their controllers?

**Comment by drowhunter** [comment]
No I haven't.  I could also just add a parameter so that you pass the assembly in , but that seems ugly.

**Comment by michaelstaib** [comment]
I am just looking it up... give me a sec

**Comment by drowhunter** [comment]
somewhat related,  Hotchocolate has alote of dependent nuget projects. Such as HotChocolate.AspNetCore

so i referenced all of the Hotchoclate Core Projects in my solution, but then projects that are expecting a specific dll version of HotChocolate.Types  complain and give runtime errors

in the .net classic days you would put a runtime assembly binding in the web/app config.

Do you know of a way I can do this in .Net Core?

**Comment by drowhunter** [comment]
ok..
