### ISSUE TITLE
Generic CollectionSegment<T> not present in HotChocolate.Types.OffsetPagination.dll

### ISSUE THREAD

**Issue by PendingChanges** [ChilliCream/hotchocolate#3772]
**Describe the bug**
I was trying to use CollectionSegment<Whatever> in my application and it seems that the generic type is not present in the dll

**To Reproduce**
1. Install HotChocolate.Types.OffsetPagination package
2. In the namespace HotChocolate.Types.Pagination there is CollectionSegment but no CollectionSegment<>
3. Here a screenshot of assembly decompilation
![Assembly decompilation](https://user-images.githubusercontent.com/10407221/120299011-e076da80-c2ca-11eb-841a-591023d77eb8.png)

**Expected behavior**
Generic CollectionSegment<> included in the dll

**Desktop :**
 - OS: Windows 10
 - .net 5.0 (but same in 3.1), haven't checked in below versions

**Additional context**
Precisions : le file exists on the repository on the develop branch : https://github.com/ChilliCream/hotchocolate/blob/develop/src/HotChocolate/Core/src/Types.OffsetPagination/CollectionSegment~1.cs

**Comment by tobias-tengler** [comment]
The `CollectionSegment<T>` is part of HotChocolate 11.3, which has not yet been released. If you install the latest 11.3 preview package, you should have access to it.

**Comment by PendingChanges** [comment]
> The `CollectionSegment<T>` is part of HotChocolate 11.3, which has not yet been released. If you install the latest 11.3 preview package, you should have access to it.

Oh okay thanks for quick answer!
