### ISSUE TITLE
Ignoring fields with `ObjectTypeExtension<T>` does not work

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3776]
**Describe the bug**
Calling `Ignore` on the `descriptor` of a `ObjectTypeExtension<T>` does not work. The supposedly ignored field is still part of the generated schema.

**To Reproduce**
```csharp
public class Example
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
}

public class ExampleType : ObjectType<Example> { }

public class ExampleTypeExtensions : ObjectTypeExtension<Example>
{
    protected override void Configure(IObjectTypeDescriptor<Example> descriptor)
    {
        descriptor.Name(nameof(Example));

        // this is the problematic portion
        descriptor.Ignore(f => f.Property2);
    }
}

public class Query
{
    public Example? GetExample() => null;
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddGraphQLServer()
            .AddTypeExtension<ExampleTypeExtensions>()
            .AddQueryType<Query>();
    }
}
```

Leads to:

```graphql
type Example {
  property1: String!
  property2: String!
}
```

**Expected behavior**
`Property2` should not be part of the generated schema:

```graphql
type Example {
  property1: String!
}
```

**Desktop (please complete the following information):**
- Version: `11.3.0-preview.7`

**Comment by tobias-tengler** [comment]
cc @michaelstaib

**Comment by tobias-tengler** [comment]
This also happens when trying to replace fields.
```csharp
descriptor
    .Field(f => f.Property2)
    .Type<IntType>()
    .Name("property3")
    .Resolve(context =>
    {
        return null;
    });
```
I would expect the schema to look like this:
```graphql
type Example {
  property1: String!
  property3: Int
}
```
But it looks like this:
```graphql
type Example {
  property1: String!
  property2: String!
  property3: Int
}
```

**Comment by tobias-tengler** [comment]
Would it maybe also make sense for `Ignore` to exist on the non-generic `IObjectTypeDescriptor` and take a `NameString`? Same would be true for interface and enum types.

**Comment by esko22** [comment]
Ran into a similar issue using the `descriptor.Authorize(new [] {"admin"});` in an attempt to having different role level access for an `ObjectTypeExtension`

Seems like the configure overrides are getting merged some how. I made sure to not call `base.Configure(descriptor);` from the `ObjectTypeExtension` to be safe. 

When I apply the `descriptor.Authorize(new [] {"admin"});` on the  `ObjectTypeExtension`, it applies it to the `ObjectType`  

Not sure if this needs to be a separate concern as it might stem from the same underlying issue.

**Comment by tobias-tengler** [comment]
@esko22 This is in fact the expected result in this case. The issue I'm talking about is that ignored fields are not correctly merged with the base type.
However, I think it would be nice to be able to opt-out of merging the authorization rules. I'll create an issue for it.

**Comment by sturlath** [comment]
You might want to remove the remark that its not working in the documentation https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/extending-types#replacing-fields

**Comment by Prikalel** [comment]
the problem with replacing a field is still persist

**Comment by mnordland-newclassrooms** [comment]
This is still happening, at least with replacing fields. I've attached a repro project on HC 15.1.12.

[field-replace-broken-repro.zip](https://github.com/user-attachments/files/26310886/field-replace-broken-repro.zip)
