### ISSUE TITLE
Docstrings on Methods, Classes, etc..

### ISSUE THREAD

**Issue by DimitrisKostorrizos** [ChilliCream/hotchocolate#3781]
I would like to see C# docstrings on methods, classes, interfaces, properties

**Comment by PascalSenn** [comment]
We are improving XML docs on every release, do you have a concrete example where you would like to see it?

**Comment by DimitrisKostorrizos** [comment]
I could make a pull request using my defind types, to see how i ususually document my classes.
________________________________
Από: PascalSenn ***@***.***>
Στάλθηκε: Πέμπτη, 3 Ιουνίου 2021 9:25 πμ
Προς: ChilliCream/hotchocolate ***@***.***>
Κοιν.: Dimitris Kostorrizos ***@***.***>; Author ***@***.***>
Θέμα: Re: [ChilliCream/hotchocolate] Docstrings on Methods, Classes, etc.. (#3781)


We are improving XML docs on every release, do you have a concrete example where you would like to see it?

**Comment by michaelstaib** [comment]
you mean you want to help documenting? if so yeah ... you can help!

**Comment by DimitrisKostorrizos** [comment]
Since my schedule is quite full, with other tasks, I could help if it is something, let's say small scale. Otherwise i will make a simple pull request showcasing the XML documentation that i use in my .NET projects plus a bug fix. If you like my work, i could help with the project, in the future.
