### ISSUE TITLE
Implement OneOf spec proposal.

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#3784]
https://github.com/graphql/graphql-spec/pull/825

**Comment by nkvaronis** [comment]
Am I correct in understanding that "UnionType" cannot be used for inputs?
If so, "OneOf" is a highly anticipated feature!

**Comment by tobias-tengler** [comment]
> Am I correct in understanding that "UnionType" cannot be used for inputs?

Yes.
