### ISSUE TITLE
Infinite loop when mutation throws an exception

### ISSUE THREAD

**Issue by vbornand** [ChilliCream/hotchocolate#3793]
**Describe the bug**
The request stucks (Infinit loop?) when a mutation throws an exception with version 12.0.0-preview.12

**To Reproduce**
1. Get project https://github.com/vbornand/hc-mutation-exception
2. Execute the query
```graphql
mutation
{
  test
  {
    test
    {
      bar
      __typename
    }
    __typename
  }  
}
```

**Additional context**
It's only happened when the both `__typename` are requested

**Comment by michaelstaib** [comment]
@vbornand thank you for the code, it probably saved me hours of debugging. The bug is fixed with the next preview.
