### ISSUE TITLE
Any way to manually parse or serialized an id into a scalar type ID

### ISSUE THREAD

**Issue by shidcordero** [ChilliCream/hotchocolate#3794]
**Describe the bug**
My requirement was to add the id in the url link that needs to be on a scalar type rather than int type. Is there a way to do this manually? I have check the documentation and cant find anything.

To make it clear, I want it to do it like this

                var type = new IDScalarType();
                // 1st param is the id to be converted, second param is the typeName similar to what we pass in [ID(<here>)]
                bool success = type.TryConvert(1, nameof(User), out string value); 
                // value should have the scalar string

**Comment by tobias-tengler** [comment]
You can access the `IdSerializer` like any other service:

```csharp
var idSerializer = host.Services.GetRequiredService<IIdSerializer>();

var serializedId = idSerializer.Serialize(null, nameof(User), 1);
```

Feel free to reopen, if you further questions regarding this.
