### ISSUE TITLE
Default valued input  not found in resolver object

### ISSUE THREAD

**Issue by Archuna** [ChilliCream/hotchocolate#3804]
I am trying to give a default value for a certain input in the schema as follows.
 userid : String = "admin"
 
In the IResolverContext object, I am not able to find this entire input value if I do not mention this input in the query.
Is there any way to access this deault valued input variable

Thanks in Advance.

**Comment by PascalSenn** [comment]
In GraphQL this will not be inferred by the spec.
If you have a default value on a input object, you need to at least specify the input object.
Imagine the scenario of a recursive input

```graphql
type Query {
    do(input: FooInput): String
}
input FooInput {
   userId: String = "admin"
   nested: FooInput
}
```

**Comment by Archuna** [comment]
Thank you. But  i am specifying the input object. 
Assume my schema is 
`type Query {
    do(input: FooInput): String
}
input FooInput {
   userId: String = "admin"
   score: Int
   avg: Int
}`
and if i write the query as 
`query{
 do(input:{score:12,avg:10})
}`
 In this case the resolvercontext object should have userid as admin in addition to score and avg right?.
But I am not getting the default valued input field.

**Comment by PascalSenn** [comment]
@praseetht  

In graphql a default value and nullability are different things. Your problem is that your field is non nullable and therefor the validation will throw the exception you see.

You can fix this by either doing this:
```csharp
 public class Person
 {        
       [HotChocolate.Types.DefaultValue(true)]
       public bool? Test { get; set; }        

       public string? Name { get;set; }
 }
```
or this:
```csharp
 public class Person
 {        
       [GraphQLType(typeof(BooleanType))]
       [HotChocolate.Types.DefaultValue(true)]
       public bool? Test { get; set; }        

       public string? Name { get;set; }
 }
```

@michaelstaib  i tested this in #4130, this bug is resolved
