### ISSUE TITLE
Quic implementation

### ISSUE THREAD

**Issue by tanekim77** [ChilliCream/hotchocolate#3809]
Now that Quic specs are standardized, it would be great if Quic is implmented in Hot Chocolate.

**Comment by tobias-tengler** [comment]
I'm not that familiar with Quic, but from what I understand there wouldn't be any changes required in Hot Chocolate to support it. 
The Web Server technology you are using, for example Kestrel, needs to implement this specification, not Hot Chocolate itself. Here's the epic for [HTTP/3 support in ASP.NET Core (Kestrel)](https://github.com/dotnet/aspnetcore/issues/15271).

Are there specific parts of the specification that you think need attention from Hot Chocolate's side? Please elaborate on your enhancement request.

**Comment by michaelstaib** [comment]
Exactly, this is up to the ASP.NET Core team.
