### ISSUE TITLE
Headers are not copied to proxy request when using Schema Federation

### ISSUE THREAD

**Issue by PabloDeCortes** [ChilliCream/hotchocolate#3821]
**Describe the bug**

**To Reproduce**
1. Clone `https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/Stitching/federated-with-hot-reload`
2. Add in gateway any `CustomDelegatingHandler` to any http client registration
3. Get all headers from `request.headers` in `CustomDelegatingHandler`
4. Send a request to gateway with custom header
5. Headers are empty in `CustomDelegatingHandler`

**Expected behavior**
Headers should be filled from original request.

**Environment:**
 - OS: Windows 10
 - Dotnet Version: 5.0

**Additional context**
If you are using `HttpContextAccessor.HttpContext.Request.Headers` headers are not empty and filled. This behavior force you to write custom handlers that proxy headers from gateway to other graphql services

**Comment by michaelstaib** [comment]
This behavior is by design since in many cases you do not want to copy the headers. In order to implement this behavior user the HttpClientFactory and the `IHttpContextAccessor`.
