### ISSUE TITLE
Simplify access to the `ClaimsPrincipal`

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3824]
**Is your feature request related to a problem? Please describe.**
Currently the authenticated user has to be accessed through state, which is annoying to type out and doesn't feel as integrated:
```csharp
// Annotation-based
void Method([GlobalState(nameof(ClaimsPrincipal))] ClaimsPrincipal claims);

// Code-first
var claims = context.GetGlobalValue<ClaimsPrincipal>(nameof(ClaimsPrincipal))
```

You could also go through the `IHttpContextAccessor`, but then it is even more unnecessary code.

**Describe the solution you'd like**
**Annotation-based**: The Authorization package could introduce a new attribute that abstracts the state call, something like:
```csharp
void Method([Claims] ClaimsPrincipal claims);
```

**Code-first**: The Authorization package could introduce a new extension method that abstracts the state call, something like:
```csharp
context.Claims();
```

_We need to decide on a good name for these APIs. I also considered User, since that's how MVC makes the ClaimsPrincipal available on the `HttpContext`._

**Describe alternatives you've considered**
For the Annotation-based approach we could also just allow for a ClaimsPrinicipal to be injected without the use of an attribute.

```csharp
void Method(ClaimsPrincipal claims);
```

**Comment by ApocDev** [comment]
I would prefer the last option here, personally for annotation based code.

I don't think you'll realistically ever see someone passing around a `ClaimsPrincipal` to an actual query/mutation from the outside world.

To add to the above, I also think `CancellationToken` should be treated the same way as well.

```csharp
async Task SomeQuery([GlobalState(nameof(ClaimsPrincipal))] ClaimsPrincipal user, [GlobalState(nameof(CancellationToken))] CancellationToken cancellation)
```
vs (using custom attributes)
```csharp
async Task SomeQuery([ClaimsPrincipal] ClaimsPrincipal user, [CancellationToken] CancellationToken cancellation)
```
vs
```csharp
async Task SomeQuery(ClaimsPrincipal user, CancellationToken cancellation)
```

Considering how often you (should) use the CancellationToken, I feel like the API to use it from HC is overbearing, and quite honestly makes code hard to read.

**Comment by tobias-tengler** [comment]
@ApocDev Yes, I also like the last approach the most.

About the CancellationToken, it should already be injected as expected from you or atleast I remember doing it...

**Comment by ApocDev** [comment]
> @ApocDev Yes, I also like the last approach the most.
> 
> About the CancellationToken, it should already be injected as expected from you or atleast I remember doing it...

I'm honestly not sure if it is. The last time I was fighting with it, I had to go the attribute route, so now it's ingrained in my muscle memory. :)

**Comment by PascalSenn** [comment]
@ApocDev  CancellationToken should already work like this :)

**Comment by michaelstaib** [comment]
CancellationToken has always worked :)

In the same vain `ClaimsPrincipal` is now working. There is now attribute needed.

```csharp
public Task<string> MyResolver(ClaimsPrincipal foo)
```

When using nullable annotations the ClaimsPrincipal will be injected with null if not available; otherwise we will cause a resolver error.

This will allow to get null whenever there is no claims principal:
```csharp
public Task<string> MyResolver(ClaimsPrincipal? foo)
```

**Comment by michaelstaib** [comment]
For the fluent api we are now mimicking the `HttpContext` and have en extension method `GetUser`.

```csharp
services
    .AddGraphQL()
    .AddQueryType(d =>
    {
        d.Name("Query");
        d.Field("foo").Resolve(ctx => ctx.GetUser()?.Identity?.Name);
    })
```
