### ISSUE TITLE
Make public parameterless construstor required for the base ScalarType

### ISSUE THREAD

**Issue by DimitrisKostorrizos** [ChilliCream/hotchocolate#3825]
Since the GraphQL implementation uses the Activator.CreateInstance with the parameterless constructor, during the call of the method BindRuntimeType<>(), to initialize the user defined type converter, the parameterless constructor should be required, in order to avoid the runtime exceptions when the GraphQL endpoint is called.

**Comment by michaelstaib** [comment]
It is not required. You can register types in the DI and we will get them from there. Also you can use the factory registration to provide a lambda that creates them.

**Comment by DimitrisKostorrizos** [comment]
When i register a custom type converter using the BindRuntimeType, that doesn't have a parameterless constructor, the GraphQL endpoint throw an exception.
