### ISSUE TITLE
How to disable GraphQL BCP IDE?

### ISSUE THREAD

**Issue by CodeHawkz** [ChilliCream/hotchocolate#3829]
Is it possible to disable BCP IDE for certain environments (e.g. for Production)? If it's not possible, I think this would be a nice feature to have. BCP IDE is very useful to have while development and perhaps even in QA. However, I don't think that is suited for a Production environment. 

I would love to contribute to such a feature.

**Comment by arif-hanif** [comment]
@CodeHawkz 

endpoints.MapGraphQL()
 .WithOptions(new GraphQLServerOptions {
     EnableSchemaRequests = env.IsDevelopment(), // Disable / enable schema query
     Tool = { Enable = env.IsDevelopment() }, // disable / enable tooling
  });

https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/AspNetCore/src/AspNetCore/GraphQLServerOptions.cs

**Comment by CodeHawkz** [comment]
This hits the mark! Thank you very much.
