### ISSUE TITLE
BatchDataLoaders are not running in parallel

### ISSUE THREAD

**Issue by DeepakSTiwariAllscripts** [ChilliCream/hotchocolate#3838]
**Describe the bug**
We have a GraphQL endpoint which uses 2 BatchDataloaders to fetch data from 2 separate Rest APIs. As this BatchDataloaders executes sequentially, the runtime for our GraphQL Endpoint = Runtime for BatchDataloaders 1 + Runtime for BatchDataloaders 2. 

We want to run this 2 BatchDataloaders in Parallel so as to optimize the performance of our GraphQL Endpoint.

There was a similar issue reported previously
ref: https://github.com/ChilliCream/hotchocolate/pull/1741

I think following is the cause of the issue:
In BatchExecutionTask.ExecuteAsync method, **await** is inside a for loop. This causes all the tasks to run sequentially instead of parallelly.
https://github.com/ChilliCream/hotchocolate/blob/develop/src/HotChocolate/Core/src/Fetching/BatchScheduler.cs

private class BatchExecutionTask : ParallelExecutionTask
![image](https://user-images.githubusercontent.com/77429316/122191082-0944c580-ceb0-11eb-822e-0cc476476296.png)

**To Reproduce**
Here **await** is inside a for loop which causes all the tasks to run sequentially and not parallelly.
ref: https://github.com/ChilliCream/hotchocolate/pull/1741

**Expected behavior**
BatchDataloaders should run in Parallel.

**Additional context**
https://github.com/ChilliCream/hotchocolate/pull/1741

**Comment by michaelstaib** [comment]
We did this intentional to keep the pressure from the database when executing multiple DataLoader agains a single database. In hindsight this might in this case not be the desired behavior. I will think about this a bit.

**Comment by DeepakSTiwariAllscripts** [comment]
Thank you @michaelstaib and @tobias-tengler for your quick response. I appreciate that!

**Comment by michaelstaib** [comment]
This one is now fixed.

**Comment by michaelstaib** [comment]
We potentially could give more control over batching in general in a future release. For now the dispatcher will dispatch them in parallel.

**Comment by DeepakSTiwariAllscripts** [comment]
Thanks @michaelstaib.
