### ISSUE TITLE
Can't deny introspection after having allowed it once in a custom `IHttpRequestInterceptor`

### ISSUE THREAD

**Issue by rune-vikestad** [ChilliCream/hotchocolate#3841]
**Describe the bug**
The `WellKnownContextData.IntrospectionAllowed` flag seems to be persisted across multiple request, and as such there's no way to deny introspection after having allowed it.

**To Reproduce**

Consider a custom interceptor used to conditionally allow or deny introspection base on the value of the `X-API-KEY` HTTP header field.

An example would look something like this;

```csharp
public class ConditionalIntrospectionHttpRequestInterceptor : DefaultHttpRequestInterceptor
{
    public override async ValueTask OnCreateAsync(HttpContext context, IRequestExecutor requestExecutor, IQueryRequestBuilder requestBuilder, CancellationToken cancellationToken)
    {
        string apiKey = context.Request.Headers["X-API-KEY"];

        if (apiKey.Equals("Foo"))
            requestBuilder.AllowIntrospection();
        else
            requestBuilder.SetIntrospectionNotAllowedMessage($"The HTTP header field X-API-KEY does not contain a valid API key");

        await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
    }
}
```

This should work well, but has some hickups.

If your first request is sent without a valid `X-API-KEY` header, you'll see the following error

```json
{
    "errors": [
        {
            "message": "The HTTP header field \"X-LOOPFRONT-GRAPHQL-INTROSPECTION-API-KEY\" does not contain a valid API key",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "extensions": {
                "field": "__schema",
                "code": "HC0046"
            }
        }
    ]
}
```

If you then add a valid `X-API-KEY` header field you'll be allowed to perform the introspection query.

All is well so far.

However, if you now remove the `X-API-KEY` header field, and re-run the query, you'll notice that introspection is still allowed - even though we'd expect it to be denied since `requestBuilder.AllowIntrospection();` was never run.

**Expected behavior**

I would expect that every introspection request sent without the `X-API-KEY` header field would be denied, since we never explicitly added the `WellKnownContextData.IntrospectionAllowed` flag.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro 10.0.19043 Build 19043
 - Version: 11.3.0
 - IDE: JetBrains RIder 2021.1.3

**Additional context**

Not entierly sure what the exact bug is here, but for reference  I was hoping we could get a `.DenyIntrospection()` extension on the `IQueryRequestBuilder`, which would remove the setting flag from the data context, causing the introspection query to be denied.

**Comment by michaelstaib** [comment]
So, looked into it and we cache successful validations :) which then skips any further validation .... good catch.
Am writing a better integration test that also captures this case. We probably do a 11.3.1

**Comment by rune-vikestad** [comment]
> 
> 
> So, looked into it and we cache successful validations :) which then skips any further validation .... good catch.
> Am writing a better integration test that also captures this case. We probably do a 11.3.1

That's excellent, @michaelstaib :)

I'll keep watching this, as I'll easily be able to test this again when it's patched.

**Comment by michaelstaib** [comment]
This one is fixed with the next preview.
