### ISSUE TITLE
Neo4J filters does not filter on relations

### ISSUE THREAD

**Issue by jschioedtz** [ChilliCream/hotchocolate#3849]
**Describe the bug**
We have a schema where ProductOwners has a relation to a set Characteristics using the Neo4J implementation. We are able to filter on all properties in ProductOwners, but if we try to add filters from Characteristics those are not included in the Cypher sent to Neo4J.

**To Reproduce**
A query like this:
```
{
  productOwners (where: { 
    brandId: { eq: "ff0e04c8-c54d-4788-9304-61d552d35aed" }
    and: {
      charateristics: {
       all: {
          attributeId: {
            in: ["5ee649dc-e7d4-49a2-ab9d-51410f017e5e"],
          }, 
        }
      }
    }
  })
  {
    id
    productType
    displayName
    brandId
  }
}
```
only creates Cypher for ProductOwners and brandId and totally skips Characteristics relation.

**Expected behavior**
We would expect the relation to be part of the filter.

**Desktop (please complete the following information):**
HC 12-preview15.

**Additional context**
Perhaps we should add additional filters or concepts in the middleware, but currently we are just using plain 

```
/// <summary>
/// ProductOwners query.
/// </summary>
/// <param name="session">Session.</param>
/// <returns>Appropriate product owners.</returns>
[UseNeo4JDatabase("neo4j")]
[UseProjection]
[UseFiltering]
[UseSorting]
public Neo4JExecutable<ProductOwner> ProductOwners([ScopedService] IAsyncSession session) => new (session);

/// <summary>
/// Gets or sets charateristics.
/// </summary>
[Neo4JRelationship("HAS_CHARATERISTICS", RelationshipDirection.Outgoing)]
public IEnumerable<Charateristic>? Charateristics { get; set; }
```

**Comment by arif-hanif** [comment]
Similar to #4514
