### ISSUE TITLE
Support new host configuration api

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#3852]
**Is your feature request related to a problem? Please describe.**
https://github.com/dotnet/aspnetcore/issues/30354

**Describe the solution you'd like**
Need some fixes:
1. `.InitializeOnStartup()` will fail with `System.InvalidOperationException: Server has already started.`
2. Need to add manually `.AddTransactionScopeHandler<DefaultTransactionScopeHandler>()` or will fail on first request with `System.ArgumentNullException: Value cannot be null. (Parameter 'transactionScopeHandler')` **OperationExecutionMiddleware:45**
3. Need to add manually `.AddHttpRequestInterceptor<DefaultHttpRequestInterceptor>()` or will fail on first request with `System.InvalidOperationException: No service for
type 'HotChocolate.AspNetCore.IHttpRequestInterceptor' has been registered.`

**Describe alternatives you've considered**
Try to find why new builder api is breaking HC DI, seems like new API is copying service from one service collection to another and omitting all hosted services. Startup configuration is working fine

**Additional context**
```cs
services.AddGraphQLServer()
  // .InitializeOnStartup()
  .AddTransactionScopeHandler<DefaultTransactionScopeHandler>()
  .AddHttpRequestInterceptor<DefaultHttpRequestInterceptor>()
 // ...
```

HC 11.3.0
dotnet 6 preview 5

**Comment by michaelstaib** [comment]
Do you want to do a PR on this?

**Comment by davidfowl** [comment]
There should be no work required here to support the new hosting APIs.

**Comment by michaelstaib** [comment]
Yes, I think the confusion came up with .NET 6 preview 4 which had an issue where services instance were duplicated. This was gone with preview 5. I am closing this issue since this is no longer an issue.
