### ISSUE TITLE
Confusing behavior for inherited types

### ISSUE THREAD

**Issue by kenewbie** [ChilliCream/hotchocolate#3858]
I have a query endpoint which needs to return several different levels of types from a type hierarchy. When I register the base type with hot chocolate it seems to block the inherited classes from appearing. I'm not 100% sure if I am just being dense or if this is an issue (at least in documentation or schema-warning). I do not have a lot of experience with GraphQL.

Example: 

These are my models:

```
    public interface IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; }
    }

    public class Article : IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; } = "Lorem Ipsum";
    }

    public class AuthoredArticle : Article
    {
        public string Author { get; set; } = "Author McAuthorson";
    }

    public class NewsArticle : AuthoredArticle
    {
        public DateTime Published { get; set; } = DateTime.Now;
    }
```

The Query type:

```
    public class Query
    {
        private static int _roundRobin = -1;

        public IArticle GetArticle()
        {
            return (++_roundRobin % 3) switch
            {
                0 => new Article { Title = "Normal Article" },
                1 => new AuthoredArticle { Title = "Authored Article" },
                _ => new NewsArticle { Title = "News Article" },
            };
        }
    }
```

Startup:

```
            services.AddGraphQLServer()
            .AddQueryType<Query>()
            .AddType<Article>()
            .AddType<AuthoredArticle>()
            .AddType<NewsArticle>();
```

I want to execute the following query and grab properties depending on the returned type:

```
query {
  article {
    __typename
    title
    content

    ... on AuthoredArticle 
    {
      author
    }

    ... on NewsArticle 
    {
      author
      published
    }
  }
}
```

But the response is always of __typename: "Article". Example:

```
{
  "data": {
    "article": {
      "__typename": "Article",
      "title": "News Article",
      "content": "Lorem Ipsum"
    }
  }
}
```

When I look at the schema in BananaCakePop it says the article endpoint returns IArticle, which is implemented by the types Article, AuthoredArticle and NewsArticle.

So I don't get why the __typename is always "Article" or how I could get the behavior I want. I would look into restructuring the models but they are from a different domain and changing them is not really an option.

**Comment by michaelstaib** [comment]
GraphQL has no object inheritance. In order to use these kinds if inheritance structures you must resort to interfaces.

**Comment by michaelstaib** [comment]
in graphql object only implement interfaces. But interfaces can implement other interfaces.

https://spec.graphql.org/draft/#sec-Objects
and 
https://spec.graphql.org/draft/#sec-Interfaces

**Comment by kenewbie** [comment]
Sorry to keep harping on this but I'm having a hard time letting it go. I have discussed it on SO and Slack and it always boils down to "GraphQL has no object inheritance". But I don't see this as a GraphQL issue, but a problem with how HC evaluates the types internally when they are returned. 

Allow me to elaborate. This is the schema produced by the original example:

```
schema {
  query: Query
}

interface IArticle {
  title: String
  content: String
}

type Article implements IArticle {
  title: String
  content: String
}

type AuthoredArticle implements IArticle {
  title: String
  content: String
  author: String
}

type NewsArticle implements IArticle {
  title: String
  content: String
  author: String
  published: DateTime!
}

type Query {
  article: IArticle
}
```

The schema is fine and "Article", "AuthoredArticle" and "NewsArticle" are all valid responses from the "article"-query. It is HC that decides to always return an Article here, not a limitation in the schema. Now if I change the types to implement IArticle directly like this

```
    public interface IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; }
    }

    public class Article : IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; } = "Lorem Ipsum";
    }

    public class AuthoredArticle : IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; } = "Lorem Ipsum";
        public string Author { get; set; } = "Author McAuthorson";
    }

    public class NewsArticle : IArticle
    {
        public string Title { get; set; }
        public string Content { get; set; } = "Lorem Ipsum";
        public string Author { get; set; } = "Author McAuthorson";
        public DateTime Published { get; set; } = DateTime.Now;
    }
```

Now HC is able to return the correct types, but the schema is EXACTLY the same! So I think it is wrong to "blame" this on GraphQL not supporting inheritance. To me it looks like HC is not handling inherited types in an good way. 

A birds eye view solution would be something like returning the most specific type which is endpoint compliant. Of course I have no idea of the cost of implementing something like that or the implications for other parts of the framework.

Sorry for bringing this up again, and if you still tell me that I am way off base here and the issue is with my understanding of GraphQL, I will let it go and forever hold my peace.

**Comment by michaelstaib** [comment]
So your problem is not the resulting schema :)

Regarding runtime type detection. You can change this. Like the reference implementation we allow you to take over the type checks.

**Comment by michaelstaib** [comment]
OK, I see the issue of the default type inspection.

we do:

```
return RuntimeType.IsInstanceOfType(result);
```

Which boils down to:

```
runtimeType.IsAssignableFrom(result.GetType())
```

**Comment by michaelstaib** [comment]
I will change the default type resolution to:

```
private bool IsOfTypeWithRuntimeType(
            IResolverContext context,
            object? result) =>
            result is null || RuntimeType == result.GetType();
```

This however will affect people using interfaces for object types which I know a couple of people do. But since I think that is an edge case we will describe to them that they should actually override the type resolution. 

The type resolution can be overridden like the following:

```
builder
    .SetTypeResolver((objectType, obj) => objectType.RuntimeTime.IsInstanceOfType(obj))
```

The new behavior will be in 11.3.1-preview.6

**Comment by kenewbie** [comment]
Fantastic news! Thanks for reopening and reconsidering.

**Comment by michaelstaib** [comment]
Its now implemented ... the preview will be available probably in an hour. Have a great day.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/11.3.1-preview.6

**Comment by michaelstaib** [comment]
Tag me on slack if this release works for you.

**Comment by kenewbie** [comment]
Thanks, I'll test soon and get back to you there.
