### ISSUE TITLE
"Length" type inference from the UnitsNet library

### ISSUE THREAD

**Issue by JosefRousal** [ChilliCream/hotchocolate#3866]
Is there some way to expose a Length type property on a schema object? I'm using annotation based schema generation for the rest of my project but I don't think it works in this case.

For reference [this](https://github.com/angularsen/UnitsNet#serialization) is the UnitsNet documentation regarding the serialization of the Length type.

**Comment by PascalSenn** [comment]
Not sure if i understand the context. Length of what?
How would you access it with a resolver? :)

**Comment by JosefRousal** [comment]
So firstly, the whole point of using Length over (for example) a decimal for a field type in a POCO is as a ValueObject to better reflect the type of information being stored. 

A simple example of this would be:

``` c#
class SimpleSquare
{
    public decimal SideLength { get; set; }
}

class ValueSquare
{
    public Length SideLength { get; set; }
}
```

Usage comparison looks like this:

``` c#
var s1 = new SimpleSquare
{
    SideLength = 10m
};
var s2 = new ValueSquare
{
    SideLength = Length.FromMillimeters(10)
};
var s1l = s1.SideLength;
var s2l = s2.SideLength.Millimeters;
```

Next - possible graphql implementations:

Queries

``` graphql

simpleSquares {
    sideLength
}

valueSquares {
    sideLength(unit: MILLIMETERS)
}

```

Seems like this should be possible using [field arguments](https://graphql.org/learn/queries/#arguments).

Mutations

This might be more tricky. Need to provide a type of input type property which would convey all the required info to the backend.

Simple version that requires some manual intervention would be something like this:
``` c#
public class LengthInput
{
    public LengthUnit Units { get; set; }
    public double Value { get; set; }
}

public class ShapeInput
{
    public LengthInput SideLength { get; set; }
}

public class Mutation
{
    public bool AddShape([Service] ShapeService service, ShapeInput input)
    {
        // create Length from LengthInput, omitted for brevity
    }
}
```

Ideal version would not require a `LengthInput` POCO and instead automatically generate the LengthInput graphql type (by some rule defined in some place, this is the heart of my question)

``` c#
public class ShapeInput
{
    public Length SideLength { get; set; }
}
```

In either case the mutation would look something like this:

``` graphql
mutation {
    addShape(input: {
        sideLength: {
            units: MILLIMETERS,
            value: 10
        }
    }) {
        sideLength
    }
}
```

Hope that explains it :)

**Comment by michaelstaib** [comment]
There are multiple ways to do that. `ExtendObjectType` is one of them. But it could also be that you actually want a custom scalar.

- https://chillicream.com/docs/hotchocolate/defining-a-schema/extending-types/
- https://chillicream.com/docs/hotchocolate/defining-a-schema/scalars/#custom-scalars
