### ISSUE TITLE
totalCount seems to be wrong when using UseMongoDbPaging

### ISSUE THREAD

**Issue by jprubio** [ChilliCream/hotchocolate#3868]
**Describe the bug**
Hi everyone,

when i use UseMongoDbPaging with IncludeTotalCount=true , the totalCount field seems to be wrong when 'first' field is included in query.

**To Reproduce**
On MongoDB example (https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/MongoDB) ... When I write following query
```
{
  persons(where: { name: { contains: "Romeo" } }) {
    totalCount
    nodes {
      name
    }
  }
}
```
throws right number of items and totalCount (3):
```
{
  "data": {
    "persons": {
      "totalCount": 3,
      "nodes": [
        {
          "name": "Romeo McCloy"
        },
        {
          "name": "Romeo2 McCloy"
        },
        {
          "name": "Romeo3 McCloy"
        }
      ]
    }
  }
}
```
But when i include 'first' value, totalCount differs:

```
{
  persons(first:1, where: { name: { contains: "Romeo" } }) {
    totalCount
    nodes {
      name
    }
  }
}
```
```
{
  "data": {
    "persons": {
      "totalCount": 2,
      "nodes": [
        {
          "name": "Romeo McCloy"
        }
      ]
    }
  }
}

```

**Expected behavior**
totalCount should show always the total number of elements that matches the input filter, in above case, 3.

**Additional context**
Faced with HC 11.3 and also HC 12.0.0-preview.18

**Comment by PascalSenn** [comment]
did you try this with 11.3? we reworked paging completly

**Comment by jprubio** [comment]
> did you try this with 11.3? we reworked paging completly

Sure, 11.3 and also 12.0.0-preview.18

**Comment by tobias-tengler** [comment]
I think there's a general flaw in the MongoDB pagination logic, since #3683 talks about the same issue, but for `MongoDbOffsetPaging`.

**Comment by michaelstaib** [comment]
@PascalSenn I put both paging bugs on your deck for V12 since we need this to be working for our ccc project.
