### ISSUE TITLE
Better GraphQL client support

### ISSUE THREAD

**Issue by cyberhck** [ChilliCream/hotchocolate#3872]
Hi, first of all, ever since I saw that wriging a `.graphql` operation file and then being able to generate this I absolutely loved strawberryshake.

However there are times where this generated client simply isn't enough.

Where I've ran into problems is when I'm having to do different auth schemes based on what query I'm firing. (client credentials vs jwt for example)

We could do one of two things:
- Add http request header support per operation
- Use some sort of way so that the http client also has access to operation name using which we can modify auth behavior.

If I'm missing something, please let me know :slightly_smiling_face:

**Comment by cyberhck** [comment]
In my case, I'm trying to forward my incoming request's auth header onto another subgraph.

**Comment by michaelstaib** [comment]
This is coming with this issue:

https://github.com/ChilliCream/hotchocolate/issues/3467

You can add your thoughts there.
