### ISSUE TITLE
Unobserved task exception with subscriptions

### ISSUE THREAD

**Issue by randyridge** [ChilliCream/hotchocolate#3891]
I'm noticing random unobserved task exceptions down in the subscription execution code, at the moment I don't have a reliable way to repro.

Running 11.3.1, though I'm sure it was happening with previous versions as well.  Also, my subscription backend is custom and not in-memory or redis...

{
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived')",
  "RemoteStackIndex": 0,
  "RemoteStackTraceString": null,
  "ClassName": "System.AggregateException",
  "Source": null,
  "HelpURL": null,
  "StackTraceString": null,
  "Depth": 0,
  "HResult": -2146233088
},
{
  "Message": "The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'",
  "RemoteStackIndex": 0,
  "RemoteStackTraceString": null,
  "ClassName": "System.Net.WebSockets.WebSocketException",
  "Source": "System.Net.WebSockets",
  "HelpURL": null,
  "StackTraceString": "   at void System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, bool isDisposed, WebSocketState[] validStates)\r\n   at ValueTask System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory<byte> buffer, WebSocketMessageType messageType, bool endOfMessage, CancellationToken cancellationToken)\r\n   at async Task HotChocolate.AspNetCore.Subscriptions.DefaultMessagePipeline.ProcessAsync(ISocketConnection connection, ReadOnlySequence<byte> slice, CancellationToken cancellationToken)\r\n   at async Task HotChocolate.AspNetCore.Subscriptions.MessageProcessor.ProcessMessagesAsync(CancellationToken cancellationToken) x 2",
  "Depth": 1,
  "HResult": -2147467259
}

**Comment by michaelstaib** [comment]
It seems like the connection was aborted by the client.

**Comment by randyridge** [comment]
Should there be an additional catch in the MessageProcessor?
