### ISSUE TITLE
Improve IObjectTypeDescriptor interface

### ISSUE THREAD

**Issue by akaSybe** [ChilliCream/hotchocolate#390]
Move method `IObjectFieldDescriptor Field<Expression<Func<TResolver, object>> propertyOrMethod)` of `IObjectTypeDescriptor<T>` interface to`IObjectTypeDescriptor` interface, so  it'll be possible to use shared resolvers with objects that do not have any fixed clrType representation

**Comment by michaelstaib** [comment]
#389

**Comment by michaelstaib** [comment]
This one is now implemented so I close this issue. I will release the change as 0.6.11.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/0.6.11
