### ISSUE TITLE
Request Executor forgets ServiceCollection Configuration

### ISSUE THREAD

**Issue by matthiaslischka** [ChilliCream/hotchocolate#3900]
**Describe the bug**
I configure my `ServiceCollection` and at the end generate an `RequestExecutor`. When I then want to access the configured ServiceCollection via `executor.Services` it does not contain my registered services. I'm not sure if this is a bug or if I'm just expecting the wrong thing here.

**To Reproduce**
```csharp
var executor = await new ServiceCollection()
    .AddTransient<ISomething, Something>()
    .AddGraphQL()
    .AddQueryType<Query>()
    .BuildRequestExecutorAsync();

executor.Services.GetRequiredService<ISomething>(); // System.InvalidOperationException: No service for type 'HotChocolate.RequestExecutor.Tests.ISomething' has been registered.
```

**Expected behavior**
Is this to be expected? Do I have to do this this way? 

**My approach now**
```csharp
var serviceCollection = new ServiceCollection()
    .AddTransient<ISomething, Something>();

var executor = await serviceCollection
    .AddGraphQL()
    .AddQueryType<Query>()
    .BuildRequestExecutorAsync();

var services = serviceCollection.BuildServiceProvider();
services.GetRequiredService<ISomething>();
```
I was kinda thinking that the executor takes the existing `ServiceCollection`, adds some additional stuff and offers all under `executor.Services`. Maybe just my misunderstand of how this is meant to work.

BR, Matthias.

**Comment by michaelstaib** [comment]
This behavior is expected.

Hot Chocolate uses two separate DI system. One internal for schema bound services. Each GraphQL server essentially uses its own DI system. `IRequestExecutor.Services` are not application services but the internal services of the executor. Your server can have multiple executors that have different services in order to provide different behavior.

Doing this also allows us to hot reload schemas and their dependent objects in order to provide functionality that allows for dynamic schemas.

The code below is only for unit tests. The method `BuildRequestExecutorAsync ` is mainly a helper.

```
var executor = await new ServiceCollection()
    .AddTransient<ISomething, Something>()
    .AddGraphQL()
    .AddQueryType<Query>()
    .BuildRequestExecutorAsync();

executor.Services.GetRequiredService<ISomething>(); 
```

**Comment by matthiaslischka** [comment]
Ok, gotcha. Just a misunderstanding on  my party. Thx for clarifying.
But what did you want to show with your "code below"? This does not work,...🤔

**Comment by michaelstaib** [comment]
Yes ...if you wanted the application services you would need to do the following:

```
var services = await new ServiceCollection()
    .AddTransient<ISomething, Something>()
    .AddGraphQL()
    .AddQueryType<Query>()
    .BuildServiceProvider();
    
var executor = await service.GetRequestExecutorAsync();
services.GetRequiredService<ISomething>(); 
```

**Comment by matthiaslischka** [comment]
My point is that in your code `.BuildServiceProvider()` can't be called after `.AddGraphQL()` or `.AddQueryType<Query>()` because this returns an `IRequestExecutorBuilder`. But the code I wrote in my first post under "**My approach now**" works for me. So all good. 👍

**Comment by michaelstaib** [comment]
```
var services = await new ServiceCollection()
    .AddTransient<ISomething, Something>()
    .AddGraphQL()
    .AddQueryType<Query>()
    .Services
    .BuildServiceProvider();
```

**Comment by matthiaslischka** [comment]
Not sure what's going on now. This code doesn't compile because of the `await` und does not create an `executor`. 😅
Like I said, my current solution is in the first post anyway and works well enough for the few tests I need it in.

If you want to play aground further feel free to use [this dummy project](https://github.com/matthiaslischka/HotChocolate.RequestExecutor.Tests/blob/master/HotChocolate.RequestExecutor.Tests/ServiceRegistrationTests.cs).

Thanks and BR

**Comment by michaelstaib** [comment]
the wait needs to go .... I am just hinting at what you can do ... did not compile
