### ISSUE TITLE
EnableRelaySupport throws an exception when trying to stitch 2 separate schemas, that are using a relay

### ISSUE THREAD

**Issue by umnik03** [ChilliCream/hotchocolate#3913]
**Description**
Version 11.2.2. EnableRelaySupport throws an exception when trying to stitch 2 separate schemas, that are using a relay.

**Exception**: 

> HotChocolate.SchemaException: For more details look at the `Errors` property.
> 1. The name `Node` was already registered by another type. (HotChocolate.Types.Relay.NodeType)

**How to Reproduce**
1. Create a service A with EnableRelaySupport() and configure node as described in [docs](https://chillicream.com/docs/hotchocolate/v10/schema/relay)
2. Create a service B with EnableRelaySupport() and configure node as described in [docs](https://chillicream.com/docs/hotchocolate/v10/schema/relay)
3. Create a service with EnableRelaySupport() and schema stitching
4. Not sure if it is important, schema stitching is used via Redis as described [here](https://chillicream.com/docs/hotchocolate/distributed-schema/schema-federations/)

**Expected behavior**
There is no exception and node queries are routed to correct upstreams/schemas. As well node queries a combined into one.

**Additional context**
When EnableRelaySupport() is not used, graph types that implemented Node interface are grouped correctly, but the nodes for queries are adjusted with schema name in front.

**Comment by michaelstaib** [comment]
This is not supported yet. We are working on schema stitching improvements in the August release cycle. Closing this for now.

**Comment by umnik03** [comment]
Maybe at least update docs, that this is not supported?

**Comment by tobias-tengler** [comment]
@umnik03 I planned on starting to document Relay stuff for v11/12 this weekend - will make sure to include a note!

**Comment by umnik03** [comment]
thank you :)
