### ISSUE TITLE
Question : difference between sp.GetApplicationService<T> and sp.GetApplicationService<T>

### ISSUE THREAD

**Issue by StefH** [ChilliCream/hotchocolate#3923]
Is there documentation or a blog-post which described the way HotChocolate handles Dependency Injection and why you need to use 
``` c#
.AddDiagnosticEventListener(sp => new MyDiagnosticEventListener(sp.GetApplicationService<ILogger<MyDiagnosticEventListener>>()))
```

Instead of just
``` c#
.AddDiagnosticEventListener(sp => new MyDiagnosticEventListener(sp.GetService<ILogger<MyDiagnosticEventListener>>()))
```

Or even:

``` c#
.AddSingleton<MyDiagnosticEventListener>()

//

.AddDiagnosticEventListener<MyDiagnosticEventListener>()
```

**Comment by michaelstaib** [comment]
This changes in 12

**Comment by StefH** [comment]
OK.

But in 12, I still cannot use `.AddDiagnosticEventListener<MyDiagnosticEventListener>()` in case I have a dependency on Iogger for example?

**Comment by michaelstaib** [comment]
12 is not yet fully finished. This will work when we release.
