### ISSUE TITLE
Global BindingBehavior default

### ISSUE THREAD

**Issue by jbray1982** [ChilliCream/hotchocolate#393]
**Is your feature request related to a problem? Please describe.**
We do not want anyone changing the schema of our graphQl endpoint by accident, so we tell each graph type to explicitly bind all of the fields for that type. However, new developers might not know to set that explicit flag and accidentally expose fields they did not mean to include in the external schema. 

**Describe the solution you'd like**
Ideally we'd have a spot in the ISchemaConfiguration that calls BindFields(Explicit) on each object type as it is being constructed for the schema. 

**Describe alternatives you've considered**
My current implementation is to manually set Explicit for each of our object types

I'd be glad to work on this, but it doesn't seem like there's an obvious place for this to be handled, so I'd need a little guidance on where in the object type creation process we'd do such a check.

**Comment by michaelstaib** [comment]
Let me have a look at this. We are planning to open up the schema building process so that you can add your own discovery service, how the casing of fields should be etc.

**Comment by michaelstaib** [comment]
This is related to  #320

**Comment by michaelstaib** [comment]
Let me work a few more days on the schema builder design. I think once I got this we both could have a look how we break up the descriptor services. The thing here is that I do not want to add some static defaults that would impact all schemas in the same process. 

I would rather like to define it on a schema base. So, basically that you could say this specific schema behaves in a certain way and has certain defaults. 

What do you think?

**Comment by michaelstaib** [comment]
For the meantime you could create a base class like the following:


```csharp
public class ExplicitObjectType<T>
        : ObjectType<T>
    {
        protected override void Configure(IObjectTypeDescriptor<T> descriptor)
        {
            descriptor.BindFields(BindingBehavior.Explicit);
        }
    }
```

**Comment by jbray1982** [comment]
Yeah I would agree. If I understand the code base correctly, an ISchemaConfiguration is scoped to a single schema, which is why I would think we'd have a method on that that can set and provide the default BindingBehavior as the schema is being constructed. The Base class is a good idea, I may try that.

**Comment by jbray1982** [comment]
accidentally closed.

**Comment by michaelstaib** [comment]
I am moving this to version 0.8.0 since we will focus on enhancement in the type system.

**Comment by michaelstaib** [comment]
This is implemented with 10
