### ISSUE TITLE
Template doesnt show document

### ISSUE THREAD

**Issue by erizet** [ChilliCream/hotchocolate#3930]
**Describe the bug**
When running the template no doucment is shown in "Banana Cake Pop".

**To Reproduce**
1. install template: dotnet new -i HotChocolate.Templates.Server
2. dotnet new graphql
3. dotnet run
4. Browse: localhost:5000/graphql

**Expected behavior**
See person under doucument.

**Desktop (please complete the following information):**
 - OS: win10

**Comment by czmirek** [comment]
Have you found a workaround? I'm trying to learn the platform and make some minimal working project but not even the example project does not work. I'm not sure what to do or try next.

**Comment by tobias-tengler** [comment]
The templates do definitely work. I assume you are looking for the schema definition in the wrong place. How you can access it is shown [here](https://chillicream.com/docs/bananacakepop/schema-definition).
