### ISSUE TITLE
Getting "The root type Query has already been registered" when running hello world project in development mode

### ISSUE THREAD

**Issue by kolpav** [ChilliCream/hotchocolate#3931]
**Describe the bug**

I am getting this error
```
System.ArgumentException: The root type `Query` has already been registered. (Parameter 'operation')
         at HotChocolate.SchemaBuilder.AddRootType(Type type, OperationType operation) in HotChocolate.Types.dll:token 0x60000f2+0xb6
         at HotChocolate.SchemaBuilderExtensions.AddQueryType[TQuery](ISchemaBuilder builder) in HotChocolate.Types.dll:token 0x6000096+0xe
         at Microsoft.Extensions.DependencyInjection.SchemaRequestExecutorBuilderExtensions.<>c__77`1.<AddQueryType>b__77_0(ISchemaBuilder b) in HotChocolate.Execution.dll:token 0x600083f+0x0
```
When trying to run super simple app in `Development` environment but when I switch to `Production` the problem goes away for some strange reason?

**To Reproduce**

https://github.com/kolpav/HcBug

**Expected behavior**

Be able to run hello world app in Development environment

**Desktop (please complete the following information):**

I was able to reproduce same behavior in docker running ubuntu
```
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="12.0.0-preview.23" />
    <PackageReference Include="HotChocolate.Data" Version="12.0.0-preview.23" />
  </ItemGroup>

</Project>

```

**Additional context**

Please run the linked repo exactly as is described in README.

**Comment by tobias-tengler** [comment]
I remember another issue where another user had an issue with using `dotnet run` inside of Docker - I can't seem to find it though. I remember that I also could reproduce it.
#3930 might also be related since it's also using `dotnet run`.

**Comment by kolpav** [comment]
@tobias-tengler Might be related I previously had docker-compose in linked repo but I deleted it because people were thinking the problem lies somewhere in docker.

**Comment by kolpav** [comment]
That was me but I haven't received much help then so I thought I should create proper issue.

**Comment by kolpav** [comment]
`dotnet new graphql` and `ASPNETCORE_ENVIRONMENT="Development" dotnet run` produces same error no need to use my repo.

**Comment by PascalSenn** [comment]
Work without any issue on my machine:

![image](https://user-images.githubusercontent.com/14233220/124782176-4eef2e00-df44-11eb-801a-a1d35e2c9462.png)
![image](https://user-images.githubusercontent.com/14233220/124782248-5e6e7700-df44-11eb-87e6-1b233bc191e4.png)


Can you try to update the template?
```
 dotnet new -i HotChocolate.Templates.Server::11.3.1
```

**Comment by kolpav** [comment]
@PascalSenn I forgot to mention I made one change to template generated by `dotnet new graphql` I changed target framework to `net6.0`

```
<TargetFramework>net6.0</TargetFramework>
```

Can you try again please?

**Comment by tobias-tengler** [comment]
There have been multiple issues reporting problems with the latest ASP.NET Core 6 preview.

I don't think we will introduce changes to accommodate .NET 6, while it's not even in its RC phase yet. Let's wait for the next preview, maybe it resolves the issue. In the meantime stick to <= .NET 5.

**Comment by kolpav** [comment]
@tobias-tengler Understandable I'll try 5.0 and close this issue if the problem goes away, thank you.
