### ISSUE TITLE
Relay node resolver fails for `uint` ID type

### ISSUE THREAD

**Issue by ocecaco** [ChilliCream/hotchocolate#3932]
It appears that Relay node resolvers do not get called when the type of the ID used for `IdField` is `uint`. The following is a minimal reproduction:
```
    public class Foo
    {
        public uint Id => 0;
    }

    public class FooType : ObjectType<Foo>
    {
        protected override void Configure(IObjectTypeDescriptor<Foo> descriptor)
        {
            descriptor
                .ImplementsNode()
                .IdField(f => f.Id)
                .ResolveNode((ctx, id) =>
                {
                    // This never gets called
                    Console.WriteLine(id);
                    return Task.FromResult(new Foo());
                });
        }
    }

    // The query type
    public class Query
    {
        public Foo GetFoo()
        {
            return new Foo();
        }
    }
```
 
If one first does a query for `foo { id }`, then it returns the `Foo` node with its relay ID (base64 encoded). However, a subsequent query for `node(id: MYFOOID) { id }` returns `null`, and hence fails to find the `Foo` node again.

The reason for this is that `IdSerializer` does not have a special case for `uint` IDs, and uses its `default` branch, which converts the ID to a string. Then, upon deserialization, the ID gets read back as a string again, and does not get converted to `uint`. This causes the test in `NodeDescriptorBase.ResolveNode<TId>` to fail, because the ID stored in the context is a `string`, and my resolver function requires a `uint`. Hence, the resolver returns `null` and fails to find my `Foo`.

Not sure what the best fix for this would be. Adding a case for `uint` to `IdSerializer` would work, but that would also require adding cases for all the other primitive integer types. As a quick fix, I could also use a different integer type like `long` for the ID, but that would require back-and-forth casting throughout multiple cases in my code base, so that's not ideal.

**Comment by PascalSenn** [comment]
@ocecaco  This will be fixed with the next 12 preview :
https://github.com/ChilliCream/hotchocolate/pull/3917

**Comment by ocecaco** [comment]
Thanks for the reply, that's good to hear. I looked at the `main` branch to see if the issue was still present there (since I'm using v11), but I didn't think to check the pull requests / `develop` branch.
