### ISSUE TITLE
Projection does not work with abstract types (repro repo)

### ISSUE THREAD

**Issue by kolpav** [ChilliCream/hotchocolate#3935]
**Describe the bug**

I can't figure out how to use projections with abstract types even after reading through https://github.com/ChilliCream/hotchocolate/pull/3650 

**To Reproduce**

https://github.com/kolpav/HotChoco

**Expected behavior**

Be able to use `[UseProjection]` with abstract types

**Desktop:**
```
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```

**Additional context**

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/19467143/135176720-213a5212-e496-408d-b854-f27ec96bd72b.png">

Failing query:
```gql
{
  animals {
    items {
      ... on Dog {
        id
        wof
      }
      ... on Cat {
        id
        nya
      }
    }
  }
}
```
Error:
```
"error": {
    "errors": [
      {
        "message": "Unexpected Execution Error",
        "extensions": {
          "message": "Operation is not valid due to the current state of the object.",
          "stackTrace": "   at HotChocolate.Data.Projections.Handlers.QueryablePagingProjectionOptimizer.RewriteSelection(SelectionOptimizerContext context, Selection selection)\n   at HotChocolate.Data.Projections.ProjectionProvider.RewriteSelection(SelectionOptimizerContext context, Selection selection)\n   at HotChocolate.Data.Projections.ProjectionOptimizer.OptimizeSelectionSet(SelectionOptimizerContext context)\n   at HotChocolate.Execution.Processing.OperationCompiler.OptimizeSelectionSet(CompilerContext context)\n   at HotChocolate.Execution.Processing.OperationCompiler.Visit(Stack`1 backlog)\n   at HotChocolate.Execution.Processing.OperationCompiler.Compile(String operationId, DocumentNode document, OperationDefinitionNode operation, ISchema schema, ObjectType rootType, InputParser inputParser, IEnumerable`1 optimizers)\n   at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationComplexityMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.TimeoutMiddleware.InvokeAsync(IRequestContext context)\n   at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)"
        }
      }
    ]
```

```
Version="12.0.0" 
```

**Similar issues**
- https://github.com/ChilliCream/hotchocolate/issues/4318

**Comment by TruebloodOF** [comment]
I seem to be having a similar issue as well.  I noticed that #1658 was closed but I am encountering the exact same issue on 12.0.0-rc.1 and 11.3.4.  Is there some special configuration that should be documented that makes this possible?

**Comment by kolpav** [comment]
This problem is still present and I think its quite serious bug. At least for me its blocking me from many features I would like to tackle in my project. I don't expect immediate fix I just want to make sure hc team knows about this or just acknowledgment if this is indeed a bug would be great. I updated my repo to latest version of everything and switched from InMemory db to postgre so its closer representation of my project if there is anything you would like to see which would make debugging easier let me know.

**Comment by reinux** [comment]
Maybe we could at least get some more specific exceptions/messages if this is going to take a while to fix?

I'm getting this same error just trying to return an `IEnumerable<string>` from an extension, and I have no clue why nor what to even report.
