### ISSUE TITLE
Add schema endpoint to be able to download graphql schema

### ISSUE THREAD

**Issue by Temppus** [ChilliCream/hotchocolate#3937]
**Is your feature request related to a problem?
I am using latest preview of HotChocolate.AspNetCore (12.0.0-preview.19) and there seems to be no endpoint exposed for downloading of graphql schema. 

**Describe the solution you'd like**
Add default middleware that will build and and returns graphql schema.

**Additional context**
I have found some old documentation that states that this functionality existed, but I am unable to find this in current 11+ release.

**Comment by tobias-tengler** [comment]
You should be able to download the schema as described here: https://chillicream.com/docs/hotchocolate/api-reference/aspnetcore/#graphql-schema-request

I'm closing this issue for now. If what's described above doesn't work for you, feel free to re-open this issue. :)

**Comment by Temppus** [comment]
Thank you, it works :)
