### ISSUE TITLE
Error when generating schema with non-us letters

### ISSUE THREAD

**Issue by JesperAxelssonIca** [ChilliCream/hotchocolate#3938]
**Describe the bug**
I want use an enum with swedish letters in it but unfortunately I get an error when dowloading the schema.

**To Reproduce**
Try generate schema with the following class:
```
    public class Foo
    {
        public TestEnum Classification { get; set; }
    }

    public enum TestEnum
    {
        ÖVRIGT
    }
```

**Expected behavior**
A schema is generated with `ÖVRIGT` as an enum.

**Desktop (please complete the following information):**
 - Windows 10
 - Version 11.3.1

**Comment by michaelstaib** [comment]
This is not allowed by the GraphQL Spec.

https://spec.graphql.org/June2018/#sec-Enum-Value
