### ISSUE TITLE
Support for IQueryable in DataLoaders

### ISSUE THREAD

**Issue by Jonatthu** [ChilliCream/hotchocolate#3949]
I want to be able to filter user posts, the use case would be:

"Bring users and all it's posts that matches the title of 'hello'"

The problem is that I am not sure how to pass down in the dataloader what's the query to be generated.

```
[ExtendObjectType(typeof(User))]
public class UserExtensions
{
	[BindMember(nameof(User.Posts))]
	[UseTemplateDbContext]
	[UsePaging(IncludeTotalCount = true)]
	[UseProjection]
	[UseFiltering]
	[UseSorting]
	public Task<Post[]> GetPostsAsync(
		[Parent] User user,
		IResolverContext context,
		[ScopedService] TemplateDbContext dbContext,
		CancellationToken cancellationToken
	)
	{
		return context.GroupDataLoader<int, Post>(
			async (keys, ct) =>
			{
				List<Post> result = await dbContext.Posts
					.Where(x => keys.Contains(x.UserId))
					.ToListAsync(ct);
				return result.ToLookup(x => x.UserId);
			}).LoadAsync(user.Id, cancellationToken);
	}
}
```

**Comment by Jonatthu** [comment]
This will need to use Row number window function for mssql

**Comment by PendingChanges** [comment]
On my side i'm stitching a bunch of microservices all exposing data in a graphql schema and create delegates on the stitcher.
Until now, i was making requests througs Dataloaders calling my dataaccess with IEnumerable (not using projections, sorting and filtering).
I want to mix up using data loaders (to avoid n+1 issues) and IQueryable.

@Jonatthu Have you got any answers on how to mix up Dataloaders and projections using IQueryable? I will be interrested

**Comment by chrsadk** [comment]
This would be a great enhancements. If there is a workaround to achieve some level of support for this on a released version, I'm also interested!

**Comment by michaelstaib** [comment]
DataLoader is the wrong place for this. Hot Chocolate has a more abstract batching API that the stitching engine uses. @PascalSenn and I will sit together next week planing V13 where we will have projected batching.

**Comment by michaelstaib** [comment]
I am closing this issue and we will open a new spec issue describing the new batching feature.

**Comment by elmanav** [comment]
> I am closing this issue and we will open a new spec issue describing the new batching feature.

Great. Waiting for news.
