### ISSUE TITLE
How can use Aggregations(Avg, Sum, Count, Group by, ...) in Version 11?

### ISSUE THREAD

**Issue by Vadoudi** [ChilliCream/hotchocolate#3953]
**Describe the bug**
I'm not able to group by the result or use aggregations like Avg, Count, or Sum.

This is my `GraphQL` configuration:
![image](https://user-images.githubusercontent.com/47804206/125725454-ed9f99dd-a365-4b90-802f-6578b5539007.png)

These are libraries that I used in my project:
![image](https://user-images.githubusercontent.com/47804206/125725500-5932532f-8c2f-4ddb-8c2a-8b7121f0799b.png)

**Expected behavior**
Able to do **Group by**, **Avg**, **Count**, and **Sum** by sing **`GraphQL`**.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 11

**Comment by PascalSenn** [comment]
We already have a discussion about that:
https://github.com/ChilliCream/hotchocolate/discussions/2963
