### ISSUE TITLE
It was not possible to find any compatible framework version on .NET6.0-P6

### ISSUE THREAD

**Issue by PlastMan420** [ChilliCream/hotchocolate#3959]
**Describe the bug**
Hello. I was attempting to use strawberry shake on Blazor Wasm running on .NET6-preview6

**To Reproduce**
running ```dotnet graphql init https://localhost:5001/graphql -n <name> -p ./``` shows this error message

**Expected behavior**
It should download a json file from the server like it usually would.
the error message is straightforward. it says it could not find .NET5.0. I dont have it installed.
Is it possible to run on .NET6? or do i just install 5 and call it a day?

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: Hotchocolate 11.3.1 on asp core server. strawberry shake 11.3.1 on blazor wasm

**Additional context**
message:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      6.0.0-preview.6.21352.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by michaelstaib** [comment]
We will add support for .NET 6 this week.

**Comment by psalmeight** [comment]
Any update to StrawberryShake support for .NET 6 Preview 6?

**Comment by michaelstaib** [comment]
This moved a bit since we are still working on the server. Will still be in V12
