### ISSUE TITLE
Splitting up `EnableRelaySupport`

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3966]
`EnableRelaySupport` can do two things at the moment:
- Global Object Identification
- Adding a query field to mutation payloads

Both of these features represent schema design principles and only GOI is sort of required for Relay. Both are good to have for any kind of schema, so I think connecting them with Relay is unnecessary.

I propose to split these functionalities apart, to make them more explicit and remove the Relay association. Of course we would still reference the Relay Server Specification in the documentation and make notes where appropriate.

### Global Object Identification

```csharp
services
    .AddGraphQLServer()
    .AddGlobalObjectIdentification();
```

### AddQueryFieldToMutationPayloads

I would rename `RelayOptions` to something like `AddQueryFieldToMutationPayloadsOptions` (way too long...) and add it to the `ISchemaOptions`:

```csharp
public class AddQueryFieldToMutationPayloadsOptions
{
    public bool Enabled { get; set; }

    public NameString? QueryFieldName { get; set; }

    public Func<INamedType, bool> MutationPayloadPredicate { get; set; }
}

public interface ISchemaOptions
{
    AddQueryFieldToMutationPayloadsOptions AddQueryFieldToMutationPayloads { get; }

    // ...
}
```

Then you could enable it through the schema options:

```csharp
services
    .AddGraphQLServer()
    .ModifyOptions(options => 
    {
        options.AddQueryFieldToMutationPayloads.Enabled = true;
    });
```

We could also hoist up these options on the schema options directly or add another extension method like:

```csharp
services
    .AddGraphQLServer()
    .AddQueryFieldToMutationPayloads();
```

**Comment by tobias-tengler** [comment]
I also just noticed that you can't use the mutation payloads feature without using GOI as well, you'll  get an error:
> There is no object type implementing interface `Node`

**Comment by michaelstaib** [comment]
I agree, let us pull them apart. I anyway wanted to move the relay stuff into a separate package that still is referenced through the main HotChocolate package but gives the compiler to do tree shaking if it is not used.
