### ISSUE TITLE
UsePaging does not discover Interface Types correctly when interface is a abstract class

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#3992]
UsePaging does not discover Interface Types correctly when interface is a abstract class

**Comment by PascalSenn** [comment]
hm.. this could also be a different problem with `ExtendObjectType(typeof(Parent))]`

**Comment by reinux** [comment]
I'd been running around making and registering interfaces for all my EF entities because until I read this, I didn't even realize you could even make GraphQL interfaces out of .NET classes 😂

**Comment by michaelmccord** [comment]
I'm thinking whatever is going on here is related to @PascalSenn's issue.
