### ISSUE TITLE
AuthorizeAttribute when used in class level applies to the entire ExtendObjectType

### ISSUE THREAD

**Issue by Jonatthu** [ChilliCream/hotchocolate#3995]
When using authorize attribute this way, the entire "Query" schema will be under this rule instead of just the methods on "UserQueries".

```
    [Authorize]
	[ExtendObjectType("Query")]
	public class UserQueries
	{
		[UseAppDbContext]
		[UsePaging(IncludeTotalCount = true)]
		[UseProjection]
		[UseFiltering]
		[UseSorting]
		public IQueryable<User> GetUsers(
			[ScopedService] AccountDbContext dbContext
		) => dbContext.Users;
```

The same happens with "Mutation" and "Subscription"

**Comment by michaelstaib** [comment]
This is the correct behavior since `ExtendObjectType` class translates to:

```sdl
extend type Foo @authorize
```

which essentially merges with the `type Foo`.

However, we will redo authorization soon.

**Comment by KrzysztofPajak** [comment]
Just only for notes: 
If you have 
using Microsoft.AspNetCore.Authorization;
then authorization method does not work
when you change to:
using HotChocolate.AspNetCore.Authorization;
Then everything works well
