### ISSUE TITLE
Need a way to authenticate the /graphql?sdl endpoint

### ISSUE THREAD

**Issue by msawczyn** [ChilliCream/hotchocolate#3996]
Even with the Query, Mutation and Subscription classes tagged with [Authorize], the /graphql?sdl endpoint allows schema download without authentication. We need a means of requiring authentication for that functionality.

**Comment by PascalSenn** [comment]
this should help:
```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGraphQL().RequireAuthorization();
            })
```

**Comment by gallargit** [comment]
Here's a quick fix I just wrote, return 403 forbidden if the querystring contains the "sdl" word. While it does not fix the issue, works for me so far.

```//This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
{
  //check if the querystring contains the "sdl" keyword, if so, block the request
  app.Use(async (context, next) =>
  {
      var queryDictionary = new Dictionary<string, StringValues>(StringComparer.InvariantCultureIgnoreCase);
      foreach (var item in
          Microsoft.AspNetCore.WebUtilities.QueryHelpers.ParseQuery(context.Request.QueryString.Value))
      {
          queryDictionary.Add(item.Key, item.Value);
      }
      if (queryDictionary.ContainsKey("sdl"))
      {
          context.Response.StatusCode = (int)HttpStatusCode.Forbidden;
      }
      else
      {
          await next.Invoke().ConfigureAwait(false);
      }
  });
...
```

you may want to block it only whenever not debugging, i.e.:

```                if (queryDictionary.ContainsKey("sdl") && !Debugger.IsAttached)```

**Comment by PascalSenn** [comment]
@gallargit  you can also disable the request with GraphQLServerOptions 
```csharp
app.UseEndpoints(endpoints =>
{ 
    endpoints
        .MapGraphQL()
        .WithOptions(new GraphQLServerOptions() { EnableSchemaRequests = !Debugger.IsAttached });
}); 
```

**Comment by PascalSenn** [comment]
@msawczyn  @gallargit  
Does these solution work for you? can this issue be closed?

**Comment by msawczyn** [comment]
@PascalSenn 

Unfortunately, no. 

`endpoints.MapGraphQL().RequireAuthorization()` stops BCP from appearing at all without authorization data, but in a normal browser scenario, we add the authorization data in BCP. The goal is to stop `/graphql?sdl` from returning the schema file unless authorization data is sent, rather than stopping BCP from showing at all. That can easily be done using existing options, as you indicate above.

**Comment by gallargit** [comment]
@PascalSenn

> you can also disable the request with GraphQLServerOptions
> 
> ```cs
> app.UseEndpoints(endpoints =>
> { 
>     endpoints
>         .MapGraphQL()
>         .WithOptions(new GraphQLServerOptions() { EnableSchemaRequests = !Debugger.IsAttached });
> }); 
> ```

The solution proposed works as long as there is no authorization involved as msawczyn said, but probably the best option is:

`EnableSchemaRequests = Debugger.IsAttached`

so that requests are only enabled whenever debugging

**Comment by michaelstaib** [comment]
We have reworked the ASP.NET Core integration. We have added more Map* methods to allow putting authorization on the different aspects of the middleware. 

- MapGraphQLHttp
- MapGraphQLWebSocket
- MapGraphQLSchema
- MapBananaCakePop
