### ISSUE TITLE
12.0.0.preview-27 banana cake pop editor missing sidebar entry

### ISSUE THREAD

**Issue by sjefvanleeuwen** [ChilliCream/hotchocolate#4003]
No null reference exception anymore as related to: #3989, but now missing sidebar entry.

![image](https://user-images.githubusercontent.com/36629650/127231655-c0008977-9340-4311-9dce-a7f4ea43bf79.png)

/graphql?sdl is retrievable.

**Comment by michaelstaib** [comment]
Try clearing your browser cache.

**Comment by sjefvanleeuwen** [comment]
Thanks Michael that worked.
