### ISSUE TITLE
Very slow DataLoader performance while debugging

### ISSUE THREAD

**Issue by dylantf** [ChilliCream/hotchocolate#4044]
Hi, I am not sure if this is a bug or expected behavior as I am not that experienced with C#/.NET.

**Describe the bug**
I am experiencing a large performance difference when resolving fields via a data loader, based on whether the app was started with `dotnet run` or while started with the debugger.  In my minimal example, it loads 1000 records + resolves 5 related records in ~30ms. While the debugger is running, the same query is around 320ms. If I remove the relation, it is extremely fast, so I assume it has something to do with the dataloader.

**To Reproduce**
1. Clone my minimal example repo: https://github.com/dylantf/DataLoaderTest
Note this repo is not connected to a database or anything, it is just using a simple in-memory list of items
2. Start the server with `dotnet run` and navigate to http://localhost:5000/graphql in a graphql client
3. Run the example query below
4. Rerun the example query while running in debug mode in vscode or visual studio

Example query:
```gql
{
  authors {
    id
    name
    books {
      id
      name
    }
  }
}
```

**Expected behavior**
I would expect the query to not execute 10x slower :)

**Desktop (please complete the following information):**
 - Windows 10
 - .NET 5.0.302 (same performance on 3.x)
 - Hot Chocolate 11.3.3

**Additional context**
In our actual app connected to a real database, the performance difference is much larger (~1s queries).
I did some logging and it appears that the dataloader is _working_ properly, i.e. the requests are being properly batched.

![image](https://user-images.githubusercontent.com/3457993/128225184-a1f0b0fc-8db4-4a79-83df-c183b9b35fdb.png)

**Comment by PascalSenn** [comment]
@dylantf  what version are you on?

**Comment by dylantf** [comment]
Sorry forgot to add that but it's in the .csproj: `<PackageReference Include="HotChocolate.AspNetCore" Version="11.3.3" />`

**Comment by dylantf** [comment]
One other note is that I tested it in my real project with a separate class for the dataloader that extends BatchDataLoader, to see if there was something special about the delegate style (or maybe I was using it wrong). It seems to exhibit the same problem in both cases.
