### ISSUE TITLE
Support EntityFramework 2

### ISSUE THREAD

**Issue by kbrow20** [ChilliCream/hotchocolate#4048]
**Is your feature request related to a problem? Please describe.**
Due to the issue with some third party dlls not supporting .net core or .net 5 I was forced to push back my entity framework to entity framework 2.0 since they only support .net framework and .net standard 2.0. So I had to downgrade that until Photon Server will support .net 5. Since the database layer is used by multiple solutions I don't have a choice.

**Describe the solution you'd like**
I would like a nuget package that supports Entity Framework 2.0. The solution that uses GraphQL is a .net5 project. So I don't think that would need to change. 

**Describe alternatives you've considered**
I tried to download the source code and change the entity framework myself but there is 3 errors that would need to be addressed and I don't know enough about the framework to fix them.

**Comment by tobias-tengler** [comment]
[EntityFramework Core 2 is no longer supported by Microsoft](https://docs.microsoft.com/en-us/ef/core/what-is-new/). 2.1 will also be running out of support in a few weeks, therefore I don't think we will add support for it going forward.

@PascalSenn what's your opinion on this?

**Comment by PascalSenn** [comment]
We cannot provide support for a framework that is out of support by Microsoft. Maintaining a codebase that supports EF 2 would be too much work for us to handle

**Comment by kbrow20** [comment]
@PascalSenn I am not asking you to support a codebase. Just create a NugetPackage with the dlls. Right now I am unable to use HotChocolate due to this issue. There is a constant error with it because of Entity Framework.

**Comment by PascalSenn** [comment]
@kbrow20  
>I tried to download the source code and change the entity framework myself but there is 3 errors that would need to be addressed and I don't know enough about the framework to fix them.

What were these three issues?

**Comment by kbrow20** [comment]
![Screen2](https://user-images.githubusercontent.com/5554132/128376147-9bfde3b1-e79b-4e49-acfd-6c64678a45ee.PNG)
![Screen1](https://user-images.githubusercontent.com/5554132/128376154-7d998358-cc3c-40ab-8dab-f02de7243bdd.PNG)

These 2 locations

**Comment by kbrow20** [comment]
@PascalSenn @tobias-tengler Trust me I am not happy that Photon Server is so far behind with .net support. If it wasn't for the fact that are so critical in developing my video game section I would get rid of it. Until they support it I am stuck in this spot. I use the GraphQL API for my website to report bugs with the video game and create a user account. If I had it my way everything would be done in .net5.
