### ISSUE TITLE
IFilterConvention cannot be overridden with AddMongoDbFiltering

### ISSUE THREAD

**Issue by benzmarkus** [ChilliCream/hotchocolate#4069]
**Describe the bug**
Overriding IFilterConvention does not work as with normal AddFiltering().
Currently, case insensitive filtering is not supported. I want to add this for some filters and that's why I wanna override the eq filter.

Does not jump into the overridden methods.

`
.AddConvention<IFilterConvention>(
                    new FilterConventionExtension(
                        x => x.AddProviderExtension(
                            new QueryableFilterProviderExtension(
                                y =>
                                {

                                    y.AddFieldHandler<QueryableStringInvariantEqualsHandler>();
                                }))));
`

**To Reproduce**
- Create a API
- create QueryableStringInvariantEqualsHandler as in documentation
- set debugger in the overridden method
- debug point is never reached

**Comment by PascalSenn** [comment]
@benzmarkus  You add a Queryable handler. These handlers are specific to the database provider. 
If you use mongodb you have to use a MongoDb handler
This is a example of a mongodb handler:
https://github.com/ChilliCream/hotchocolate/blob/develop/src/HotChocolate/MongoDb/src/Data/Filters/Handlers/MongoDbEqualsOperationHandler.cs

**Comment by benzmarkus** [comment]
In which package can I find the InputParser. In HotChocolate.Types it I could not find it.

**Comment by PascalSenn** [comment]
@benzmarkus  Sorry, this is the upcomming API in v12 as we moved the serialization out of the input type. 
In version 11 have a look at https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/MongoDb/src/Data/Filters/Handlers/MongoDbEqualsOperationHandler.cs

**Comment by benzmarkus** [comment]
Thx awesome kudos for the quick response. Love your product!

**Comment by benzmarkus** [comment]
Mhh could not find class MongoDbFilterOperation?

**Comment by benzmarkus** [comment]
I think i need to wait for the next version ?
If I copy the code of MongoDbFilterOperation and create MyMongoDbFilterOperation then StringFieldDefinitionHelper is missing.

**Comment by PascalSenn** [comment]
@benzmarkus  are you using the MongoDb or the Queryable provider?

**Comment by benzmarkus** [comment]
Using HotChocolate.Data.MongoDb

**Comment by PascalSenn** [comment]
ah i see `MongoDbFilterOperation` is internal. that looks wrong to me, going to make a PR
@michaelstaib  do we plan to do another pathc release for v11?

**Comment by benzmarkus** [comment]
Currently, for me, the feature is not really important. The plan behind this was to make a case-insensitive MongoDB query for strings.

**Comment by nirendrashakya** [comment]
> Mhh could not find the class MongoDbFilterOperation?
> It is inaccessible due to my access level.

We had similar issue to allow case insensitive filtering and MongoDbFilterOperation accessibility was an issue. But got around it by using Reflection to create an instance. Seems to do the trick until accessibility issue is fixed.

**Comment by PascalSenn** [comment]
@benzmarkus @nirendrashakya  
The MongoDB API will be opened up with #4119
