### ISSUE TITLE
Add schema first approach to bind directives similarly like object types are bound

### ISSUE THREAD

**Issue by featherbits** [ChilliCream/hotchocolate#407]
Add schema first approach to bind directives similarly like object types are bound `BindType<T>()`.

Currently, if directive is declared with `DirectiveType<TDirective>` then declaration in schema has no effect and no error arrises when declarations are not equal. Directive declared in code takes precedence.

**Comment by michaelstaib** [comment]
We will rework how schema-first works and add lots of improvements on that with version 12
