### ISSUE TITLE
Provide a Way to Override JSON Serializer Options

### ISSUE THREAD

**Issue by RehanSaeed** [ChilliCream/hotchocolate#4072]
**Is your feature request related to a problem? Please describe.**
I would like to override the JSON serializer options which seem to be hard coded in [HttpResponseExtensions](https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/AspNetCore/src/AspNetCore/Extensions/HttpResponseExtensions.cs). It would be nice to indent the JSON in dev/test for easier debugging.

**Describe the solution you'd like**

ASP.NET Core provides a way to override the JSON options e.g. I use this in my Swagger API:

```cs
builder.AddJsonOptions(
    options =>
    {
        var jsonSerializerOptions = options.JsonSerializerOptions;
        if (webHostEnvironment.IsDevelopment() ||
            webHostEnvironment.IsEnvironment("Test"))
        {
            // Pretty print the JSON in development/test for easier debugging.
            jsonSerializerOptions.WriteIndented = true;
        }

        jsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
        jsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
        jsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    });
```

**Comment by yasserss** [comment]
do you have any workaround for this ?

**Comment by ikirkpat** [comment]
I see this was reopened. We really need this in place cause of issues with current serialization using System.Text.Json. We need to switch to Newtonsoft.Json but this limitation is preventing us from doing that. Is there an estimate on when this will be implemented?

**Comment by aaron-manning** [comment]
I need this feature.
The default JSON serializer seems to be stripping out microseconds from datetimes.

**Comment by michaelstaib** [comment]
This is not really possible as the scalars in GraphQL also define how they translate into JSON or other serialization formats. Also things like casing are very much specified by the GraphQL spec.

However, for version 13 we now allow to specify the indentation options and the JsonEncoder.

```csharp
services.AddHttpResponseFormatter(indented: true, encoder ....
```
