### ISSUE TITLE
There is no service implementing IResolverContext

### ISSUE THREAD

**Issue by eugenpaval** [ChilliCream/hotchocolate#4079]
**Using HC 12.0.0-preview.29**

A query which uses in its implementation IResolverContext fails with the message:
"message": "No service for type 'HotChocolate.Resolvers.IResolverContext' has been registered.",

The stack trace is as follows:
        "stackTrace": [
          "   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)",
          "   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)",
          "   at HotChocolate.Execution.Processing.MiddlewareContext.Service[T]()",
          "   at lambda_method637(Closure , IResolverContext )",
          "   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()",
          "--- End of stack trace from previous location ---",
          "   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)",
          "   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
        ]

To reproduce just inject IResolverContext to a field resolver or inject this interface into an object's constructor instantiated by DI.

**Comment by PascalSenn** [comment]
@eugenpaval  IResolverContext is not a service an therefore cannot be injected into a object constructor instantiated by the DI.
If you want to inject it into a resolver you can just do it like this
```csharp
public class Query
{
    public string GetFoo(IResolverContext resolverContext) => "";
}
```

**Comment by eugenpaval** [comment]
> @eugenpaval IResolverContext is not a service an therefore cannot be injected into a object constructor instantiated by the DI.
> If you want to inject it into a resolver you can just do it like this
> 
> ```cs
> public class Query
> {
>     public string GetFoo(IResolverContext resolverContext) => "";
> }
> ```

Still get the error but if I add [SchemaService] attribute to the parameter  it works!
```cs
public class Query
{
    public string GetFoo([SchemaService] IResolverContext resolverContext) => "";
}
```

**Comment by tobias-tengler** [comment]
The way Pascal has showcased should work, I've just tried it as well. I believe you are registering something weirdly.
Could you share the code of your ConfigureServices method in Startup.cs?

**Comment by michaelstaib** [comment]
I will check if that is a bug with the new resolver compiler. He is on preview 29.

**Comment by michaelstaib** [comment]
Just one remark... The IResolverContext is a rented object that can **NOT** be injected in constructors. The IResolverContext is not a service and is injected by the execution engine during processing of the field. It is also not possible to hold on to such an instance since as soon as a field is processed it will be reinitialized for the next field.

**Comment by michaelstaib** [comment]
I have checked and everything works as expected in the build. Closing this issue.
