### ISSUE TITLE
adding custom header for (StrawberryShake.Tools) dotnet graphql init http://localhost/graphql

### ISSUE THREAD

**Issue by timeshift92** [ChilliCream/hotchocolate#4080]
**Is your feature request related to a problem? Please describe.**
my server issues schema after authorization

**Describe the solution you'd like**
нужно добавить возможность получение заголовка

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelstaib** [comment]
what headers do you need?

**Comment by timeshift92** [comment]
Hello, for example, for hasura x-hasura-admin-secret, but even so after parsing the scheme, the system did not work, should I create a repository with an example?

**Comment by xsoheilalizadeh** [comment]
I also need this feature for Hasura schema, Hasura authentication works with a custom HTTP header so we should be able to set custom headers during `dotnet init` command.

For example:

`
dotnet graphql init http://localhost:31800/v1/graphql --h "X-Hasura-Admin-Secret: myadminsecret" -n HasuraClient
`

**Comment by nex-derek** [comment]
+1 for needing this feature

**Comment by johan-lindqvist** [comment]
This would also be great for us!
