### ISSUE TITLE
when parsing bigint column i haave error 

### ISSUE THREAD

**Issue by timeshift92** [ChilliCream/hotchocolate#4083]
**Describe the bug**
Hello  i'm Using Hasura,
and i create new table sections with id id: bigint
and relation table section_locale  with section_id : bigint

```The requested operation requires an element of type 'String', but the target element has type 'Number'.```.

**To Reproduce**

1. Create Demo  https://chillicream.com/docs/strawberryshake/get-started/console
2. get schema
3. build

**Expected behavior**
we need parse bigint as long 

**Desktop (please complete the following information):**
 - OS: windows 11

**Additional context**

**Comment by tobias-tengler** [comment]
Sounds like the BigInt is a custom scalar, which StrawberryShake tries to interpret as a string. 
I haven't worked with StrawberryShake much, but this seems to be covered by the documentation: https://chillicream.com/docs/strawberryshake/scalars#custom-scalars

**Comment by timeshift92** [comment]
ok, but could not found service container, how can i add "serviceCollection.AddSerializer" method

**Comment by tobias-tengler** [comment]
This is shown in the guide you've linked in your initial issue:
https://chillicream.com/docs/strawberryshake/get-started/console#step-4-add-a-graphql-client-to-your-project-using-the-cli-tools

**Comment by timeshift92** [comment]
![image](https://user-images.githubusercontent.com/13614530/129545967-ced9f544-e088-47cf-b9d2-bb25023e67e4.png)

after then i add "AddSerializer" method, i have error

**Comment by timeshift92** [comment]
```
serviceCollection.AddSingleton <global::StrawberryShake.Serialization.ISerializer, BigIntSerializer >();
```
i thnik it could can help somone
