### ISSUE TITLE
Scalar's DateTime and Long make SDL unvalid

### ISSUE THREAD

**Issue by JeroenDaniels** [ChilliCream/hotchocolate#4147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding a DateTime or Long property to an object, the SDL validation comes out unvalid.  (Validation site used: https://lucasconstantino.github.io/graphiql-online/)

This is because the comments above the scalar definition in the SDL file contain a new line:

```
# The "DateTime" scalar represents
 an ISO-8601 compliant date time type.
scalar DateTime

# The "Long" scalar type
 represents non-fractional signed whole 64-bit numeric
# values. Long can represent values between -(2^63) and 2^63 - 1.
scalar Long
```

I've followed the exact steps to create a new project with HotChocolate v11 and reproduced this issue in my minimum code solution: https://github.com/JeroenDaniels/GraphQLWrongSDL

### Steps to reproduce

https://github.com/JeroenDaniels/GraphQLWrongSDL

1. Add DateTime or Long property to an object
2. Go to the playground 
3. Schema
4. Download
5. SDL

### Relevant log output

```shell
# The "DateTime" scalar represents
 an ISO-8601 compliant date time type.
scalar DateTime

# The "Long" scalar type
 represents non-fractional signed whole 64-bit numeric
# values. Long can represent values between -(2^63) and 2^63 - 1.
scalar Long
```

### Product

Hot Chocolate

### Version

11

**Comment by JeroenDaniels** [comment]
Hi @PascalSenn. 
Thanks for the fast reply! I've updated to 11.3.5 but unfortunately the issue is still there.

**Comment by michaelstaib** [comment]
I used your project and downloaded the SDL from our server and it is totally fine.

```graphql
schema {
  query: Query
}

type Person {
  date: DateTime!
  number: Long!
}

type Query {
  person: Person!
}

"The `@defer` directive may be provided for fragment spreads and inline fragments to inform the executor to delay the execution of the current fragment to indicate deprioritization of the current fragment. A query with `@defer` directive will cause the request to potentially return multiple responses, where non-deferred data is delivered in the initial response and data deferred is delivered in a subsequent response. `@include` and `@skip` take precedence over `@defer`."
directive @defer("If this argument label has a value other than null, it will be passed on to the result of this defer directive. This label is intended to give client applications a way to identify to which fragment a deferred result belongs to." label: String "Deferred when true." if: Boolean) on FRAGMENT_SPREAD | INLINE_FRAGMENT

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `@stream` directive may be provided for a field of `List` type so that the backend can leverage technology such as asynchronous iterators to provide a partial list in the initial response, and additional list items in subsequent responses. `@include` and `@skip` take precedence over `@stream`."
directive @stream("If this argument label has a value other than null, it will be passed on to the result of this stream directive. This label is intended to give client applications a way to identify to which fragment a streamed result belongs to." label: String "The initial elements that shall be send down to the consumer." initialCount: Int! "Streamed when true." if: Boolean!) on FIELD

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")

"The `Long` scalar type represents non-fractional signed whole 64-bit numeric values. Long can represent values between -(2^63) and 2^63 - 1."
scalar Long
```

how do you download the SDL? Are you generating it from the introspection? If so your tool might be the issue.

Playground for instance has issues with downloading the SDL.

In order to download the SDL directly you can do `http://localhost:5000/graphql?SDL`

**Comment by JeroenDaniels** [comment]
Hi @michaelstaib,

I downloaded the SDL from the playground -> Schema -> Download -> SDL.
When i download the SDL directly from http://localhost:5000/graphql?SDL it does indeed work,

Thanks

**Comment by michaelstaib** [comment]
Also try out the new BCP app which also gives you the ability to download the schema file.

https://chillicream.com/docs/bananacakepop

**Comment by michaelstaib** [comment]
What playground does is do a introspection which gives you the json result and then converts it form there to the SDL. There are a couple of issue that they have.

**Comment by michaelstaib** [comment]
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/9714350/131307058-e7afa0e4-bb58-4c60-967b-0af08029ac8f.png">

**Comment by JeroenDaniels** [comment]
Thanks for the tip! 👍🏽
