### ISSUE TITLE
Allow to inject Edge<T> into type extensions of edge types

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4151]
### Is your feature request related to a problem?

I want to be able to add a new field to a specific Edge. I can add a field which doesn't need access to the parent type like the following:
```csharp
public class Query
{
    [UsePaging]
    public IQueryable<User> GetUsers()
    {
        // ...
    }
}

[ExtendObjectType("UsersEdge")]
public class UsersEdgeExtensions
{
    public string Test()
    {
        return "test";
    }
}
```
However most of the time I'll need access to the edge value though and as far as I'm aware this is currently not possible.

### The solution you'd like

I would like for one of the following to work, preferably the first one:
```csharp
[ExtendObjectType("UsersEdge")]
public class UsersEdgeExtensions
{
    public string Test([Parent] Edge<User> edge)
    {
        return "test";
    }
}

[ExtendObjectType("UsersEdge")]
public class UsersEdgeExtensions
{
    public string Test([Parent] User user)
    {
        return "test";
    }
}
```

If this is already possible today, please let me know how to do it via a comment and label the issue as a question.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
It actually works already but you need to match the parent type which in this case is `IndexEdge<User>`. There seems to be an issue when the parent needs a cast.
