### ISSUE TITLE
IdType overwritten with UuidType 

### ISSUE THREAD

**Issue by alecrespo** [ChilliCream/hotchocolate#4164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having the following class, where `Id` is `Guid`
```csharp
public class Customer
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}
```
Is desired to have its field representation in the schema as `ID`:
```csharp
public class CustomerType : ObjectType<Customer>
{
    protected override void Configure(IObjectTypeDescriptor<Customer> descriptor)
    {
        base.Configure(descriptor);

        descriptor.Name(nameof(Customer));

        descriptor.Field(t => t.Id)
            .Type<NonNullType<IdType>>().Description("Id of the Customer.");

        descriptor.Field(t => t.Name)
            .Type<NonNullType<StringType>>().Description("Customer Name.");

        descriptor.Field(t => t.Description)
            .Type<NonNullType<StringType>>().Description("Customer Description.");
    }
}
```
This works ok until an extension over this type is declared:
```csharp
public class CustomerTypeExtensions: ObjectTypeExtension<Customer>
{
    protected override void Configure(IObjectTypeDescriptor<Customer> descriptor)
    {
    }
}

public void ConfigureServices(IServiceCollection services)
{
      services
          .AddRouting()
          .AddGraphQLServer()
              .AddQueryType(p => p.Name(OperationTypeNames.Query))
              .AddType<CustomerType>()
          .AddTypeExtension<CustomerTypeQuery>()
}
```

When doing this it doesn't matter if the extension of the type is empty the `ID` field will be changed to `Uuid`

### Steps to reproduce

1. Attached is the minimum to reproduce. 
2. When the like ` .AddTypeExtension<CustomerTypeQuery>()` is uncommented this behaviour can be observed.
[content.zip](https://github.com/ChilliCream/hotchocolate/files/7086082/content.zip)

### Product

Hot Chocolate

### Version

11.3.2

**Comment by tobias-tengler** [comment]
Also confirmed this behavior in 12.0 0-rc.1
