### ISSUE TITLE
"Back" navigation and/or breadcrumb bar for BCP schema reference view

### ISSUE THREAD

**Issue by reinux** [ChilliCream/hotchocolate#4166]
### Is your feature request related to a problem?

There's currently no way to trace back your steps when navigating the schema with BCP.

### The solution you'd like

My first instinct is to hit the Back button, which takes you out of the app entirely. It'd be nice if it would just go back to the previous schema type that I was looking at, but I'd imagine that's a pretty big change, so a back button within the app would be fine too.

A breadcrumb bar would be _really_ nice.

![image](https://user-images.githubusercontent.com/5127297/131593757-4bb9b6a4-8557-4398-8f10-0d8741db7476.png)

### Product

Banana Cake Pop

**Comment by Tyrrx** [comment]
I would also recommend to add a forward button (including shortcuts) to allow users to navigate into both directions. So in my optinion the "or" breadcrumb bar is not a good option or at least an incomplete one.
