### ISSUE TITLE
Banana cake pop hangs / loses cookies

### ISSUE THREAD

**Issue by gallargit** [ChilliCream/hotchocolate#4169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes if you delete an existing request in Banana cake pop it will hang, it seems to be a cookie-related error: "TypeError: Cannot read property 'variables' of null". The only way to solve it is by clearing cookies on the site and then reloading.

### Steps to reproduce

Please watch [this video](https://github.com/gallargit/gapi/blob/main/cookies.mp4) to see the bug happening, it's probably easier to understand

1. open a site with introspection disabled, you can use [this demo project](https://github.com/gallargit/gapi/)
2. create a new request called "B"
3. create a new request called "A"
4. switch between them a few times
5. delete the "A" request, Banana cake pop will still show "A" at the browser's tab but the content of the page will be empty, if you go to the browser's developing tools, you will get the following javascript error: "TypeError: Cannot read property 'variables' of null"
6. you'll probably see the bug does not happen always, if you follow the video steps you'll get it soon enough

![banana](https://user-images.githubusercontent.com/36661178/131638407-00bd007a-04ee-40a4-b21d-6713a7517f73.png)

### Additional Context?

Introspection is disabled at the server but it also happens if not disabled, for example in the [BananaCakePop demo site](https://workshop.chillicream.com/graphql/) it [also happens](https://github.com/gallargit/gapi/blob/main/livesite.mp4)

### Product

Hot Chocolate

### Version

12.0.1

edited: still happens in 12.0.1

**Comment by Xenovore** [comment]
This exact problem is happening to me as well...

Any ideas? Cause? Resolution?

**Comment by hieudole** [comment]
I got the same error several times when switching tabs or closing a tab. I needed to delete the site data to make it work, but all my queries and mutation had gone.

**Comment by michaelstaib** [comment]
This is already fixed and will be released with BCP preview 15 which will be included in Hot Chocolate 12.3

**Comment by rstaib** [comment]
Exactly, it's already fixed in the current dev branch and will be published with BCP preview 15.
