### ISSUE TITLE
StrawberryShake ignoring subscription when data remains unchanged from previous event

### ISSUE THREAD

**Issue by jonbmul** [ChilliCream/hotchocolate#4171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The subscription handlers we have set up for StrawberryShake is not triggered as expected.
It triggers the handler correctly the first time the event occurs, but if the same event occurs again with exactly the same data returned the handler is not called

### Steps to reproduce

1. Set up a subscription handler using StrawberryShake, ie

```
subscription onStepChangedSubscription {
  onStepChanged {
    id
  }
}
```
with corresponding handler:
```
planClient.OnStepChanged.Watch().Subscribe(result =>
{
    Console.WriteLine("Handling OnStepChanged event...");
});
```
2. Make sure the subscription is triggered
3. The client should handle the subscription event (ie console output in the example above)
3. Trigger the subscription once more with exactly the same id
4. **The client is not handling the second subscription event**, whereas if you listen for the same subscription in Banana Cake pop it will list out both events
5. When triggering the subscription again with a different id it will be handled as expected by the strawberry shake client

### Product

Strawberry Shake

### Version

11.3.1

**Comment by jonbmul** [comment]
Also tried with Strawberry Shake 11.3.6, but still not working as expected

**Comment by michaelstaib** [comment]
That is actually a feature. :) we will only notify when data has changed not when event is thrown.

**Comment by jonbmul** [comment]
But this behaviour is different from other GraphQL clients, such as Apollo.  And it also seems to be in conflict with the idea that subscriptions can be used to communicate events from a server to a client. Now events will be missed in many cases.

Can we make this feature optional? If not, is there a workaround?

**Comment by thomastvedt** [comment]
So if I'm sending a message with TOPIC =  PRODUCT_UPDATED , and payload: 
```json
{
  productId: 2
}
```

Then I will only get the first update, not the second? I guess the message is received by strawberry shake client, but then filtered since it's not different?

A workaround would be to use the following payload?: 
```json
{
  productId: 2,
  uniqueSomething: ffee33
}
```

@michaelstaib I think this feature should be opt-in?
