### ISSUE TITLE
Server without UI

### ISSUE THREAD

**Issue by vanillajonathan** [ChilliCream/hotchocolate#4176]
### Is your feature request related to a problem?

In my `Startup.cs` file I added:
```cs
services.AddGraphQLServer().AddQueryType<Query>();
```

This also added the UI.

### The solution you'd like

I think the UI should be optional and separate from the rest of functionality so that it is optionally added using an extension method.

I also think you should be able to conditoinally add the UI depending on environment.
Example:
```cs
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseBananaCakePop();
    }
    // ...
}
```

### Product

Hot Chocolate

**Comment by eliottrobson** [comment]
This is already possible, I have used it myself.
[Tooling Documentation](https://chillicream.com/docs/hotchocolate/v11/api-reference/aspnetcore/#tooling)

```csharp
endpoints
    .MapGraphQL()
    .WithOptions(
        new GraphQLServerOptions
        {
            Tool = { Enable = env.IsDevelopment() }
        }));
```

**Comment by PascalSenn** [comment]
I am going to close this issue as this feature is already implemented

**Comment by vanillajonathan** [comment]
My bad, with my experience with ASP.NET Core being very barebones with features enabled as needed by adding middleware to the the request pipeline I was surprised to see the UI tool added and enabled by the `AddGraphQLServer` extension method. This went against my expectations.

I expected this to work like ASP.NET Identity where you add Identity by calling `services.AddIdentity<IdentityUser, IdentityRole>();` and add the UI by calling  `services.AddIdentityUI();`.

**Comment by tobias-tengler** [comment]
@vanillajonathan this has been improved in v12: #4157
You are now able to map only the components you need to specific paths. I'll also add documentation for this in the coming days.

**Comment by vanillajonathan** [comment]
@tobias-tengler That's great!
You might also want to consider providing a overload for the `MapGraphQL` method to take in the options instead of having the `WithOptions` chained method.
