### ISSUE TITLE
Unable to send topics using ITopicsEventSender from a worker class

### ISSUE THREAD

**Issue by digitaldias** [ChilliCream/hotchocolate#4187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a worker class that listens for Azure EventHub messages , and I want to use an ITopicEventSender to push that data to the frontend/UI over GraphQL Subscriptions. This worker class is not invoked by a mutation. 

I have verified that if I have a mutation message that takes in 
```csharp
public void SomeMethod([Service] ITopicEventSender sender, SomeValue someValue) {
 ...
}
```
And I use the sender, then whatever is subscribed will get that notification without problems. 

However, in my worker class, I am injecting the ITopicEventSender, and using it as in the mutation method, then nothing gets sent. 

Looking for differences during debug, I see that when the sender is inside the Mutation method, it has 1 outgoing connection. 
When I look at it in my worker class, it has 0. 

I think the bug is that connections in the DI container declared InMemoryPubSub never updates the subscriber count and thus, fails to send anything when asked. There are no exceptions or errors. Just silence. 

### Steps to reproduce

1. Have a POCO ready, in this example, Im' using a **class Consumable**
2. Create a Subscription class that declares the subscription type, i.e.
```csharp
	public class Subscription
	{
		[Topic, Subscribe]
		public Consumable ConsumableCreated([EventMessage] Consumable consumable)
		{
			return consumable;
		}
	}
```
2. In Startup.cs, add **services.AddSubscriptionType<Subscription>()** to your GraphQL intializers.  
3. I'm using InMemoryPubSub for the ITopicEventSender by calling **services..AddInMemorySubscriptions()**
3. Do the rest of the stitching to get Subscriptions up and running, app.UseWebSockets() etc
4. Create a worker class (not a Mutation class) wich takes a dependency on ITopicEventSender. For the sake of testing, this can be a background worker that sendes a "Consumable" every 30 seconds or so
5. Start the application, connect to the GraphQL endpoint, and set up a subscription to ConsumableCreated
6. None of the events appear
7. Create a method in the Mutation class that takes **[Service] ITopicEventSender sender**  as one of it's arguments
8. Call the mutation method from a different tab. Notce how the sender now sends the event and works as expected

### Product

Hot Chocolate

### Version

12.0.0-rc.2

**Comment by tobias-tengler** [comment]
Were you also able to verify this behavior with the latest v12 (12.0.0-rc.2)?

**Comment by digitaldias** [comment]
Not yet, sorry. I'm restricted to using release versions only, but I can branch out and try

**Comment by digitaldias** [comment]
Tested it using HotChocolate.AspNetCore 12.0.0-rc.2 and HotChocolate.Data 12.0.0-rc2. Same issue, the IEventSender while injected into my worker class, does not pick up the subscriptions I make from the playgroun.

**Comment by michaelstaib** [comment]
can you provide a small repro project?

**Comment by digitaldias** [comment]
I'll make one for you, give me 30 minutes:)

**Comment by digitaldias** [comment]
Closing down the issue. Turns out I wasn't warming up the service that needs to respond, and thus send the message over graphql. Once I did that, events started to flow as expected. This is NOT A bug. 

[The repro project can be seen here](https://github.com/digitaldias/MessySubscription)

**Comment by michaelstaib** [comment]
Thanks for reporting back.
