### ISSUE TITLE
MapGraphQLSchema is not intuitive

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having the new Map* methods is great, but the MapGraphQLSchema is not intuitive in my opinion.
I would expect the schema to be served from the URL I'm specifying. I would assume that `endpoints.MapGraphQLSchema(RoutePatternFactory.Parse("/schema"));` would allow me to download the schema from `/schema`, but this is not the case. I can only download it from `/schema?sdl`.

In case the MapGraphQLSchema is explicityly called like this, it should map to the specified path, without the need for a query string. With MapGraphQL it would be nice, if it could keep its default behavior, i.e. `/graphql?sdl`.

If this is intentional behavior please consider this an enhancement request.

### Steps to reproduce

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQLSchema(RoutePatternFactory.Parse("/schema"));
});
```

### Product

Hot Chocolate

### Version

12.0.0-rc.2

**Comment by michaelstaib** [comment]
That is a bug... your assumption is 100% correct :)
