### ISSUE TITLE
Can't get the httpOnly cookie on the resolver

### ISSUE THREAD

**Issue by rex-pj** [ChilliCream/hotchocolate#4201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't get the cookie that is flagged as HttpOnly in the resolver, although I have appended it on the response cookies in the previous request.

### Steps to reproduce

1. I set the cookie which is flagged HttpOnly in the previous request
` _httpContextAccessor.HttpContext.Response.Cookies.Append("Auth_RefreshToken", refreshToken, new CookieOptions
            {
                HttpOnly = true,
                Expires = DateTime.UtcNow.AddDays(10)
            });`
2. In another request I try to get this cookie
`var refreshToken = _httpContextAccessor.HttpContext.Request.Cookies["Auth_RefreshToken"];`

Expected: I can get the cookie
Actual: The cookie is return null

### Product

Hot Chocolate

### Version

11.3.7

**Comment by michaelstaib** [comment]
This actually has nothing to do with Hot Chocolate. The GraphQL layer is transport agnostic. Everything regarding HTTP transport is ASP.NET Core.

**Comment by rex-pj** [comment]
@michaelstaib, yes, that's my fault, I forgot to add { credentials: true } on the request on the client-side, the ticket can be closed.
Thanks!
