### ISSUE TITLE
Unable to add UsePaging attribute to navigation property

### ISSUE THREAD

**Issue by AcidNoX** [ChilliCream/hotchocolate#4214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two classes "Category" and "Entry" that I'm using with EFCore:
``` csharp
public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Slug { get; set; }
    public DateTime CreatedDate { get; set; } = DateTime.Now;

    // Navigation props
    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public virtual ICollection<Entry> Entries { get; set; }

    [UseFiltering]
    [UseSorting]
    public virtual ICollection<Vote> Votes { get; set; }
}
```

``` csharp
public class Entry
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string CreatedBy { get; set; }
    public string AudioUrl { get; set; }
    public string ImageUrl { get; set; }
    public int CategoryId { get; set; }
    public string Slug { get; set; }
    public DateTime CreatedDate { get; set; } = DateTime.Now;

    // Navigation props
    public virtual User User { get; set; }
    public virtual Category Category { get; set; }
}
```

I already have a paginated query for Entries:
``` csharp
[UsePaging(IncludeTotalCount = true)]
[UseFiltering]
[UseSorting]
[UseProjection]
[UseDbContext(typeof(DataContext))]
public IQueryable<Entry> GetEntries([ScopedService] DataContext context)
{
    return context.Entries;
}
```

The paging works fine for the query. but when I add [UsePaging] to the "Entries" navigation property in the Category class, I get the below error.

Is there a way that I can page the "Entries" property as well as the Entries query? 
(The UseFiltering and UseSorting attributes work fine.)

Thanks,

Lee

### Steps to reproduce

1. Add two EFCore DTOs with a one-to-many relationship between them.
2. Add a query to get all of class B.
3. Add a navigation property of ICollection<B> to class A.
4. Add the [UsePaging] attribute to the navigation property. 

### Relevant log output

```shell
1. The name `EntryConnection` was already registered by another type. (HotChocolate.Types.Pagination.ConnectionType<HotChocolate.Types.ObjectType<SportsIndustryBiz.Data.Models.Entry>>)

         at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.<>c__DisplayClass23_0.<CompleteNames>g__CompleteName|0(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames(Func`1 schemaResolver)
         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
         at HotChocolate.SchemaBuilder.Create()
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

11.3.5

**Comment by AcidNoX** [comment]
Never mind. 

It looks like the issue was that I was using "IncludeTotalCount" for one but not the other. As soon as I added it, it appears to be working.

Thanks,

Lee

**Comment by AcidNoX** [comment]
I spoke too soon.

When using UsePaging with an ICollection navigation property I get the error:
Type 'System.Collections.Generic.ICollection`1[Data.Models.Entry]' does not have a default constructor (Parameter 'type')

I can see that from #3106 that this is already an issue. I tried to use the advice given in that ticket, which is to change the enumerable type to a concrete (IE List<>) and that does resolve the error but now I get 0 results. If I removed the UsePaging I do get results returned.

Can someone please advise the correct way to use UsePaging with navigation properties please/

**Comment by KoshelevS** [comment]
I'm struggling with same issue. `UsePaging` does not return data although data is queried from the DB according to the SQL Server logs. Removing `UsePaging` from the navigation property fixes this, but I need to have an ability to take only the first item from this navigation property

**Comment by michaelstaib** [comment]
```
[UsePaging(IncludeTotalCount = true)]
[UseFiltering]
[UseSorting]
[UseProjection]
[UseDbContext(typeof(DataContext))]
```

Middleware order is important. A middleware is essentially a pipeline ... you have put the `[UseDbContext(typeof(DataContext))]` middleware at the bottom with will close the connection before paging can be applied. Version 12 finally validates these things.

This would be the correct order.

```
[UseDbContext(typeof(DataContext))]
[UsePaging(IncludeTotalCount = true)]
[UseProjection]
[UseFiltering]
[UseSorting]
```

Also with V12 you should no be able to name the connections which in turn allows to have different connection types.

```
[UseDbContext(typeof(DataContext), ConnectionName = "PeoplePersons")]
[UsePaging(IncludeTotalCount = true)]
[UseProjection]
[UseFiltering]
[UseSorting]
```

**Comment by michaelstaib** [comment]
Naming Connections:
https://chillicream.com/docs/hotchocolate/fetching-data/pagination/#naming

**Comment by michaelstaib** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/9714350/132763073-880edc89-6fe0-469b-a614-da647b0d1ac7.png">

**Comment by AcidNoX** [comment]
Hi Michael, 

Thank you so much for your reply.

I've changed the order of the middleware so that the UseDbContext is first, here's my query for categoryById: 

``` csharp
[UseDbContext(typeof(DataContext))]
[UseFirstOrDefault]
[UseProjection]
public IQueryable<Category> GetCategoryById([ScopedService] DataContext context, int id)
{
    return context.Categories.Where(x => x.Id == id);
}
```

(I've also tried changing the order of UseFirstOrDefault and UseProjection but neither way round seem to affect behavior)

And, again, my category DTO:

``` csharp
public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Slug { get; set; }
    public DateTime CreatedDate { get; set; } = DateTime.Now;

    // Navigation props
    [UsePaging(IncludeTotalCount = true)]
    [UseFiltering]
    [UseSorting]
    public virtual  List<Entry> Entries { get; set; }

    [UseFiltering]
    [UseSorting]
    public virtual ICollection<Vote> Votes { get; set; }
}
```

This is my request: 
``` gql
query {
  categoryById(id: 9) {
    id,
    entries {
      totalCount
      nodes {
        id
      }
      edges {
        cursor
        node {
          id
        }
      }
    }
  }
}
```

And response: 
``` json
{
  "data": {
    "categoryById": {
      "id": 9,
      "entries": {
        "totalCount": 0,
        "nodes": [],
        "edges": []
      }
    }
  }
}
```

And just to prove that category does in fact have some entries:
<img width="452" alt="Screenshot 2021-09-09 221808" src="https://user-images.githubusercontent.com/8410021/132764084-5f0c5f35-2be3-4af8-83d2-2997bf2aa5ed.png">

So it's still not working... am I missing something?

Since you mentioned it - I'm on v11 at the moment. I haven't opted to upgrade to v12 as it appears to be in release candidate. Would you recommend upgrading? Are there any obvious benefits of v12 vs v11?

Thanks again,

Lee

**Comment by AcidNoX** [comment]
Hi @michaelstaib 

I’ve just upgraded to v12 and I did get a couple of validation errors for other queries where the middleware’s were in the wrong order but I’ve corrected them and now no longer get any errors. I still have the same problem though. 

Also, after @KoshelevS mentioned it, i profiled the db and I can see EF is selecting the entries out of the DB, they’re just not returned in the response. 

Not sure if that helps? 

Thanks, 

Lee

**Comment by elmanav** [comment]
Please tell me what is the reason for closing the problem? It is still being reproduced on the last candidate (12-rc.5).
It is not yet possible to set the interface type (IReadOnlyCollection<>) instead of explicitly (List<>) on the navigation property.
We get this error
```csharp
Type 'System.Collections.Generic.IReadOnlyCollection`1[]' does not have a default constructor (Parameter 'type')
```

Any help.

**Comment by PascalSenn** [comment]
Paging does not work on navigation properties. You have to define a resolver if you use nested pagination. It is not possible to project cursor based pagination.

**Comment by AcidNoX** [comment]
Thanks for getting back to me @PascalSenn.

This isn't obvious in the documentation.
Could I recommend a "Nested paging" topic to be added to the docs? - I feel it's a pretty common usecase / question people may have and could do with a little spelling out.

Thanks again,

Lee

**Comment by nikosiim** [comment]
I was dealing with the same issue and found out that one reason why you not get Interest from resolver is that person.Id value is 0. This is the case if the client query does not ask for the id field. 

To avoid the issue, you should add:
descriptor.Field(f => f.Id).IsProjected(true);
