### ISSUE TITLE
 Don't continue/return errors on sequential mutations

### ISSUE THREAD

**Issue by Dispersia** [ChilliCream/hotchocolate#4216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 As an example:
 ```
 mutation foo {
    foo
    bar
 }
 ```
 if foo errors, is it intentional to execute bar, as mutations are meant to run sequentially and be able to rely on data before them. In the other graphql implementations I have tested, if foo fails then the mutations stop, but I see nothing in the graphql spec specifying how this should work.

If it is intentional, is there a way to short circuit a pure-code method? I am currently using IResolverContext to pass through if an error occurred in a previous step and attempt to short circuit, but I can't return null out of them, as that adds another error. I can mock a massive fake object on each of the mutations, but that makes it feel like even more of a hack.

I'm not sure to list this as a bug or feature request, so if it should be changed I can move it

### Steps to reproduce

```
public class Mutation
{
    public int Foo([Service] IResolverContext context, int number)
    {
        if (number == 0)
        {
            throw new QueryException(ErrorBuilder.New()
                .SetMessage("Can't be 0!")
                .SetCode("NOT_ZERO")
                .Build());
        }

        context.ContextData["error"] = true;

        return number;
    }

    public int Bar([Service] IResolverContext context)
    {
        if (context.ContextData.ContainsKey("error"))
        {
            // short circuit and no error
            return 5; // Some massive object that doesn't make sense to fake
        }

        return 10;
    }
}
```

### Product

Hot Chocolate

### Version

11.3.7

**Comment by michaelstaib** [comment]
I can confirm this is a bug in 12

**Comment by michaelstaib** [comment]
We put this on the October backlog.

**Comment by michaelstaib** [comment]
Note: we need to have conditionals in the query executions plan.

**Comment by michaelstaib** [comment]
This one is now fixed.
