### ISSUE TITLE
.UseDbContext<TDbContext>() does not support INodeDescriptor<TNode> from .ImplementsNode()

### ISSUE THREAD

**Issue by kondelik** [ChilliCream/hotchocolate#4219]
### Is your feature request related to a problem?

Looks like [`.UseDbContext<TDbContext>()`](https://github.com/ChilliCream/hotchocolate/blob/ee5813646fdfea81035c681989793514f33b5d94/src/HotChocolate/Data/src/EntityFramework/Extensions/EntityFrameworkObjectFieldDescriptorExtensions.cs#L18) from `HotChocolate.Data.EntityFramework` package (12.0.0-rc.6) does not support [`INodeDescriptor<TNode>`](https://github.com/ChilliCream/hotchocolate/blob/ee5813646fdfea81035c681989793514f33b5d94/src/HotChocolate/Core/src/Types/Types/Relay/Descriptors/INodeDescriptor~1.cs) from [`.ImplementsNode()`](https://github.com/ChilliCream/hotchocolate/blob/ee5813646fdfea81035c681989793514f33b5d94/src/HotChocolate/Core/src/Types/Types/Relay/Extensions/NodeObjectTypeExtensions.cs#L8)

```c#
services.AddPooledDbContextFactory<SomeDbContext>(...);

(...)

protected override void Configure(IObjectTypeDescriptor<SomeEntity> descriptor)
{
  descriptor
    .ImplementsNode()
    .IdField(p => p.Id)
    /**
     * "Cannot Resolve Symbol"
     * Because .UseDbContext<TDbContext>() is expecting IObjectFieldDescriptor 
     * but .IdField(p => p.Id) from .ImplementsNode(T) returns INodeDescriptor<T>
     */
    //.UseDbContext<SomeDbContext>()
    .ResolveNode(
      (ctx, id) =>
      {
        // does not work because SomeDbContext is pooled.
        return Task.FromResult(ctx.Service<SomeDbContext>().SomePoco.Find(id));

        /**
         * This might works but pooling is AFAIK crippled - I am Creating & Disposing DbContext
         * in EVERY call to this delegate.
         */
        // using var dbContext = ctx.Service<IDbContextFactory<SomeDbContext>>().CreateDbContext();
        // return Task.FromResult(dbContext.SomeEntity.Find(id));
      }
    );
 (...)
}
```

### The solution you'd like

Be able to use 
```c#
descriptor
  .ImplementsNode()
  .IdField(p => p.Id)
  .UseDbContext<SomeDbContext>()
  .ResolveNode(
    (ctx, id) => {
      var dbContext = ctx.Service<SomeDbContext>();
      // ...
    }
  );
```

to have single `SomeDbContext` from pool.

Same as in [Documentation](https://chillicream.com/docs/hotchocolate/integrations/entity-framework) for `IObjectFieldDescriptor` but for `INodeDescriptor<TNode>` 🙂 

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Field configuration can be chained in after the resolver since ResolveNode will return `IObjectFieldDescriptor`.

**Comment by kondelik** [comment]
```c#
descriptor
  .ImplementsNode()
  .IdField(p => p.Id)
  .ResolveNode(
    (ctx, id) => Task.FromResult(ctx.Service<SomeDbContext>().SomePoco.Find(id))
  )
  // now we have IObjectFieldDescriptor so we can configure it
  .UseDbContext<SomeDbContext>();
```

That is a little unintuitive because all of us was trained "order matters" (`UseDbContext().UsePaging().UseProjection().UseFiltering().UseSorting().Resolve()` from top of my head 😄 ) and `ResolveNode()` _feels_ like `Resolve()`. But I can see why - it cant be `IObjectFieldDescriptor` and `INodeDescriptor` at the same time.

Maybe word or two in [documentation?](https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/defining-a-schema/relay.md) (sorry, I cant help you with that because of my engrish)
