### ISSUE TITLE
Error SS0006 when custom scalar type begins with lowercase letter (and used as query argument)

### ISSUE THREAD

**Issue by jstorz** [ChilliCream/hotchocolate#4246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**UPDATE** Changing title to reflect that this is happening for any custom scalar that begins with a lowercase letter. Does not appear to have anything to do with Hasura or uuid.

I am attempting to use StrawberryShake with a Hasura endpoint. Fully appreciate that this is pretty bleeding edge, thank you for building an alternative to graphql-dotnet.

Hasura uses a custom scalar for uuid, and I'm running into problems when authoring queries that accept it as an argument. I've attached the schema file generated from a fresh Hasura instance with a single items table. This table only has two columns: id (uuid) and name (text). For testing I added two rows only: "foo" and "bar.

[schema.graphql.txt](https://github.com/ChilliCream/hotchocolate/files/7190775/schema.graphql.txt)

Attempting to build this query, with or without using it, results in a SS0006 error:

```graphql
query GetItemsById($item_id: uuid!) {
  items(where: {id: {_eq: $item_id}}) {
    id
    name
  }
}
```

I am able to use a nearly identical query to get items by name successfully:

```graphql
query GetItemsByName($item_name: String!) {
  items(where: {name: {_eq: $item_name}}) {
    id
    name
  }
}
```

Here is the test client I used:

```cs
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace ss_test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();

            serviceCollection
                .AddTestClient()
                .ConfigureHttpClient(client => client.BaseAddress = new Uri("http://localhost:8080/v1/graphql"));
            
            IServiceProvider services = serviceCollection.BuildServiceProvider();

            ITestClient client = services.GetRequiredService<ITestClient>();

            var result = await client.GetItems.ExecuteAsync();
            foreach (var item in result.Data.Items)
                Console.WriteLine(item.Name);
            
            var result2 = await client.GetItemsByName.ExecuteAsync("foo");
            foreach (var item in result2.Data.Items)
                Console.WriteLine(item.Name);

            // FIXME: simply including GetItemsById.graphql in build produces this error:
            //        CSC : error SS0006: Sequence contains no matching element
            //var result3 = await client.GetItemsById.ExecuteAsync("c52dbb49-f578-473d-91c4-dd1212753c46");
            //foreach (var item in result3.Data.Items)
            //    Console.WriteLine(item.Name);
        }
    }
}
```

### Steps to reproduce

1. Start clean Hasura dev instance using docker container
2. Add single table items with columns: id (uuid auto) and name (text)
3. Add two rows: foo, bar
4. Follow console StrawberryShake tutorial
5. Attempt to build query to get items by id (see bug description)

### Relevant log output

```shell
dotnet build
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error SS0006: Sequence contains no matching element [/home/josh/projects/ss-test/ss-test.csproj]

Build FAILED.

CSC : error SS0006: Sequence contains no matching element [/home/josh/projects/ss-test/ss-test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.82
```

### Product

Strawberry Shake

### Version

11.3.7

**Comment by jstorz** [comment]
Interestingly, if I find/replace uuid with Uuid in schema.graphql it builds fine. But of course this doesn't work since Hasura expects uuid.

My thinking is there is some difference between a built-in scalar type (Uuid) and a custom one that is causing codegen to barf. When I add a custom serializer class for uuid it works great for deserializing uuid responses back to System.Guid, but still has theerror when building a query with uuid as an argument.

**Comment by jstorz** [comment]
After a little playing around, this is happening for **any custom scalar that starts with a lowercase letter**. Hopefully this will give you a clue where to look. It doesn't appear to have anything to do with Hasura or uuid in particular, only scalar naming.

**Comment by jstorz** [comment]
Adding stack trace:

```
[xUnit.net 00:00:16.75]     StrawberryShake.CodeGeneration.CSharp.SchemaGeneratorTests.Query_With_Lowercase_Custom_Scalar [FAIL]
  Failed StrawberryShake.CodeGeneration.CSharp.SchemaGeneratorTests.Query_With_Lowercase_Custom_Scalar [6 ms]
  Error Message:
   System.InvalidOperationException : Sequence contains no matching element
  Stack Trace:
     at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at StrawberryShake.CodeGeneration.Mappers.OperationDescriptorMapper.<>c__DisplayClass0_0.<Map>b__0(ArgumentModel arg) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/src/CodeGeneration/Mappers/OperationDescriptorMapper.cs:line 24
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at StrawberryShake.CodeGeneration.Mappers.OperationDescriptorMapper.Map(ClientModel model, IMapperContext context) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/src/CodeGeneration/Mappers/OperationDescriptorMapper.cs:line 19
   at StrawberryShake.CodeGeneration.CSharp.CSharpGenerator.Generate(ClientModel clientModel, CSharpGeneratorSettings settings) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/src/CodeGeneration.CSharp/CSharpGenerator.cs:line 191
   at StrawberryShake.CodeGeneration.CSharp.GeneratorTestHelper.AssertResult(AssertSettings settings, Boolean skipWarnings, String[] sourceTexts) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/GeneratorTestHelper.cs:line 83
   at StrawberryShake.CodeGeneration.CSharp.GeneratorTestHelper.AssertResult(AssertSettings settings, String[] sourceTexts) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/GeneratorTestHelper.cs:line 52
   at StrawberryShake.CodeGeneration.CSharp.GeneratorTestHelper.AssertResult(Boolean strictValidation, String[] sourceTexts) in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/GeneratorTestHelper.cs:line 44
   at StrawberryShake.CodeGeneration.CSharp.SchemaGeneratorTests.Query_With_Lowercase_Custom_Scalar() in /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/SchemaGeneratorTests.cs:line 448

Failed!  - Failed:     1, Passed:   115, Skipped:     0, Total:   116, Duration: 18 s - /home/josh/projects/hotchocolate/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/bin/Debug/net5.0/StrawberryShake.CodeGeneration.CSharp.Tests.dll (net5.0)
```

**Comment by jstorz** [comment]
Obviously this is the wrong way to fix it, but doing a case insensitive argument lookup works for me. Without digging deeper into how the code generator works today I don't have an actual proposal to fix yet.

Case-insensitive hack + new test that fails before and passes after hack:
https://github.com/jstorz/hotchocolate/commit/c1d86d69b096709cab717b613e2fef3fb0298d11

**Comment by michaelstaib** [comment]
Can you post the schema?

**Comment by jstorz** [comment]
> Can you post the schema?

It's a file attached in the original post right before the example query. I re-used it in a test I added to find the place it was failing:

https://github.com/jstorz/hotchocolate/commit/c1d86d69b096709cab717b613e2fef3fb0298d11

**Comment by michaelstaib** [comment]
Awesome ... will have a look at your fix

**Comment by michaelstaib** [comment]
We will put it on the first 13 builds starting this week.

**Comment by jstorz** [comment]
> We will put it on the first 13 builds starting this week.

I don't think ignoring case (my "fix") is the right thing to do, but it may be no worse than what's already happening since it still uses Single to get the "only one".

Did not get a chance to dig much deeper, are you intending to support scalars that use different casing? Or, say, UUID and uuid as two distinct identifiers that can co-exist in the same schema? I noticed you do some camel or title casing when generating the client, which I imagine might cause collisions.

But I am happy to report that I'm able to use custom scalars for uuid (Guid), timestamptz (DateTimeOffset), and bytea (byte[]) perfectly when connecting to a Hasura endpoint. Really happy to be able to do this in C# for a Blazor wasm frontend, vs graphql-dotnet or hacking something together with JS interop. Looking forward to better control of cache invalidation & possibly custom resolvers / optimistic mutations / like urql graphcache. Being able to write a Blazor wasm PWA that can work fully offline will be killer.

**Comment by jstorz** [comment]
Also had to change input type lookup to case insensitive (see my branch). Again, not the right fix, but working for me for now since I don't have any types or inputs types with same name different casing.

**Comment by tomadj** [comment]
Hello ! 

I have the same problem. Even with version 12.5.0-preview.4. 

Like @jstorz, for deal with Hasura uuid, I added a custom scalar : 

In schema.extensions.graphql : 
 
```
extend scalar uuid
  @serializationType(name: "global::System.Guid")
  @runtimeType(name: "global::System.Guid")
```

In program.cs : 
`builder.Services.AddSerializer<UUidSerializer>();`


Since version 12.5 it works better but I'm running into problems when authoring queries that accept uuid as an argument. 
Error : Sequence contains no matching element

**Comment by tomadj** [comment]
Hello @michaelstaib ! Happy new year ! 

Even with version **12.5.0-preview.7**,  I have the same error : Sequence contains no matching element 

the error appears if I add this query : 

`query GetUserById($id: uuid!) {
  User_by_pk(id: $id) {
    id
    firstname
    lastname
  }
}`

**Comment by michaelstaib** [comment]
@PascalSenn was this fixed?

**Comment by PascalSenn** [comment]
@michaelstaib  There was no specific fix for scalars. I will add some more tests

**Comment by tomadj** [comment]
Thank's ! It's work fine now ! (12.5.0-preview.23)
