### ISSUE TITLE
SubscriptionManager: ObjectDisposedException

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#4258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
System.AggregateException
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Object name: 'SubscriptionManager'.)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SubscriptionManager'.
  ?, in void SubscriptionManager.Unregister(string subscriptionId)
  ?, in async Task SubscriptionSession.SendResultsAsync() x 2
```

### Steps to reproduce

Not sure

### Product

Hot Chocolate

### Version

11.3.4

**Comment by michaelstaib** [comment]
Have you looked at the newest version of 11?

**Comment by hognevevle** [comment]
I saw [these changes were made in 11.3.4](https://github.com/ChilliCream/hotchocolate/pull/4052), but I could not see any changes in later versions that seemed related. 

Therefore I'm still on 11.3.4, but I do have a pending deployment to upgrade to 11.3.7. If you think it will make a difference, feel free to close this and I'll come back if the issue still persists.

**Comment by michaelstaib** [comment]
I am not sure... we did some more fixes on subscriptions. You need to check if this still happens. For the next version we will re-work the whole subscription API to support the new graphql-ws spec.

**Comment by hognevevle** [comment]
Forgot to report back; this still persists after upgrading to 11.3.7.

**Comment by tobias-tengler** [comment]
How is it looking with v12?

**Comment by michaelstaib** [comment]
There should be no difference with 11.3.7 and 12 on this. We have started work on subscriptions which can be tracked here: https://github.com/ChilliCream/hotchocolate/pull/4371

This PR brings a new protocol but also reworkes subscriptions as a whole.

**Comment by michaelstaib** [comment]
I put this on 13 since we do not yet know which release it will hit... I expect that we will put one version of this into 12.3 / 12.4

**Comment by vkynchev** [comment]
@michaelstaib I confirm same issue is happening in 12.4.1. However it's throwing it from .Register method. Sending screenshots from our Sentry in production. If there's a way I can help just let me know 🙂 

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SubscriptionManager'.
  ?, in void SubscriptionManager.Register(ISubscriptionSession subscriptionSession)
  ?, in async Task DataStartMessageHandler.HandleAsync(ISocketConnection connection, DataStartMessage message, CancellationToken cancellationToken)
  ?, in async Task DefaultMessagePipeline.HandleMessageAsync(ISocketConnection connection, OperationMessage message, CancellationToken cancellationToken)
  ?, in async Task DefaultMessagePipeline.ProcessAsync(ISocketConnection connection, ReadOnlySequence<byte> slice, CancellationToken cancellationToken)
  ?, in async Task MessageProcessor.ProcessMessagesAsync(CancellationToken cancellationToken) x 2
```

<img width="1229" alt="Screenshot 2022-01-07 at 16 49 41" src="https://user-images.githubusercontent.com/10143016/148561288-bd0dfbb5-7810-41eb-be8c-ea744db3ea97.png">

<img width="939" alt="Screenshot 2022-01-07 at 16 49 56" src="https://user-images.githubusercontent.com/10143016/148561316-fed4f4a0-f8e4-42a0-bd5f-f4d8ff329d54.png">

<img width="706" alt="Screenshot 2022-01-07 at 16 49 27" src="https://user-images.githubusercontent.com/10143016/148561335-22aa5cae-5509-47ab-b2f6-080442ad416b.png">

**Comment by michaelstaib** [comment]
should no be fixed.
