### ISSUE TITLE
Query exposes sorting by ignored field

### ISSUE THREAD

**Issue by acid12** [ChilliCream/hotchocolate#4260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have found an issue (using code-first approach) that when we ignore a field from model on the appropriate Type class, it is properly hidden in the response and is not shown in the schema, but it is still possible to sort by that field using the ORDER keyword during query, and the field is suggested in popup when writing the order clause.

I'd expect the ordering to not work by that field or at least schema to not suggest that hidden field when writing the query with ordering.

Is there a workaound or a configuration toggle, as this very much could be a feature not a bug - as many things - but in my mind, it exposes the domain model, which we want to protect from API.

### Steps to reproduce

1. I've found it by looking the tutorial by Les jackson on https://youtu.be/HuN94qNwQmM?t=11161
2. full code can be found under his repository https://github.com/binarythistle/S04E01---.NET-5-GraphQL-API
3. PlatformType.cs
`descriptor
                .Field(p => p.LicenseKey).Ignore();`
4. Query is properly handled and licenseKey is suggested by schema in the editors (build-in and/or insomnia)
`query{
  platform(order: {licenseKey: DESC}){
    name
  }
}`

### Additional Context?

Adding a QueryType to change the output of a Query method from Platform to PlatformType, does not work, hidden field is still suggested

### Product

Hot Chocolate

### Version

11.3.7

**Comment by PascalSenn** [comment]
Hi @acid12  

Sorting is based on the model and not on the type.
There are two ways to ignore the field. 

Option 1:
You can ignore the field with the [GraphQLIgnore] property. This works a bit different than just `Ignore()` and will ignore it also from filtering and sorting

Options 2:
You can define custom SortInputTypes and ignore the field there. You have to register the type on the schema with `AddType<>`

```csharp
    public class PersonSortInputType : SortInputType<Person> 
    {
        protected override void Configure(ISortInputTypeDescriptor<Person> descriptor)
        {
            descriptor.Field(x => x.Name).Ignore();
        }
    }
```

**Comment by michaelstaib** [comment]
I am closing this issue since the question has been answered.
