### ISSUE TITLE
Make AddIntrospectionAllowedRule easier to use

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4262]
### Is your feature request related to a problem?

Just from the name I would assume that this allows introspection, while it has the opposite effect.
The lack of configuration options also make this option very verbose, since I now have to implement a request interceptor just to allow the introspection in a specific case. When in most cases users simply want to be able to toggle this behavior on and off.

### The solution you'd like

I would assume that something like an `AllowIntrospection(boolean)` method would be a lot easier and nicer to use for most people.
If you for example want to only enable introspection at development time, you could now do:

```csharp
services.AddGraphQLServer().AllowIntrospection(hostingEnv.IsDevelopment());
```

When passing false it would have the same effect as calling `AddIntrospectionAllowedRule` today and it could still be overriden using `IQueryRequestBuilder.AllowIntrospection()`.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
So essentially you are proposing another extension method that essentially would look like:

```csharp
public static IRequestExecutorBuilder AllowIntrospection(this IRequestExecutorBuilder builder, bool allow)
{
    if(!allow) 
    {    
        builder. AddIntrospectionAllowedRule();
    }
    return builder;
}
```

**Comment by tobias-tengler** [comment]
Yes

**Comment by michaelstaib** [comment]
Do you want to do a PR for the next RC?

**Comment by tobias-tengler** [comment]
Will submit one tonight.

**Comment by michaelstaib** [comment]
Awesome... will wait then for your PR before doing the next build.
