### ISSUE TITLE
Order does not work when used in query variable

### ISSUE THREAD

**Issue by kolpav** [ChilliCream/hotchocolate#4263]
### Describe the bug

If you hardcode order like `order: DESC` query works but if you use variable `order: $order` then it does not.

Might be related to https://github.com/ChilliCream/hotchocolate/issues/2475

### Steps to reproduce

https://github.com/kolpav/HotChoco/tree/order-bug

OK

https://user-images.githubusercontent.com/19467143/134618817-e269145c-ce70-4a8a-a883-32d43d6a46c8.mp4

NOK

https://user-images.githubusercontent.com/19467143/134618811-fb6ff4fb-31d1-4b48-8a30-fe976027706e.mp4

### Product

Hot Chocolate

### Version

12.0.0-rc.11

**Comment by damikun** [comment]
I'm not sure about your bug it is working in my environment well...

Only difference is I'm using .Net5 not Net6 packages for EF...

**Comment by kolpav** [comment]
@michaelstaib Hi, was this fixed as part of rc.12? I updated to latest version and I still have the same problem.


https://user-images.githubusercontent.com/19467143/134750494-f189c8ea-0995-42b5-bf50-83a81fee1325.mp4
