### ISSUE TITLE
`DispatchBatch` diagnostic event is never called

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `DispatchBatch` event on the `ExecutionDiagnosticEventListener` is never called.
If I was following correctly the scheduler has moved outside of the Hot Chocolate source code, so maybe the method should be removed from the `ExecutionDiagnosticEventListener`.

### Steps to reproduce

Search for references of the method in the codebase. Only the `AggregateExecutionDiagnosticEvents` is using it.

### Product

Hot Chocolate

### Version

12.0.0-rc.12

**Comment by michaelstaib** [comment]
This could be a regression of me refactoring the DataLoader ... will look at it.

**Comment by michaelstaib** [comment]
This one is fixed with 12.2.2-preview.1
