### ISSUE TITLE
BCP doesn't always report JSON syntax errors for Variables and HTTP Headers; fails silently

### ISSUE THREAD

**Issue by reinux** [ChilliCream/hotchocolate#4279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some (probably most) syntax errors will be underlined by a red squiggly if it isn't valid JSON syntax, but an extra comma won't. Instead, the Run button simply does nothing.

It's a trivial problem, but it can be hard to spot the cause, especially because some JSON parsers aren't as strict.

### Steps to reproduce

In either the Variables or HTTP Headers tab:

```
{
  "id": 129,
  "message": "test message / note",
}
```

### Relevant log output

```shell
None
```

### Additional Context?

Red squigglies to indicate syntax error:

![image](https://user-images.githubusercontent.com/5127297/134999282-09254c8e-a2b1-4c64-9878-ebc7b2725901.png)

No error message or squiggly on extraneous comma:

![image](https://user-images.githubusercontent.com/5127297/134999244-4c9b489f-2bd7-4a53-ac88-8552484e5ab2.png)

### Product

Banana Cake Pop

### Version

12.0.0-rc.12

**Comment by michaelstaib** [comment]
Thank you for reporting this.

**Comment by rstaib** [comment]
The next BCP preview will fix that.
