### ISSUE TITLE
ConnectionType<T> is missing in v12

### ISSUE THREAD

**Issue by tmitchel2** [ChilliCream/hotchocolate#4290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A class for ConnectionType<T> is not available and thus more control over the return connection type as described in the documentation is not possible.  Also, ConnectionType is internal so currently you are restricted to completely implementing IConnectionType again in order to do this.

### Steps to reproduce

Try to use 

descriptor.Type<ConnectionType<UserType>>()

as per the documentation

### Product

Hot Chocolate

### Version

12.0.0

**Comment by tmitchel2** [comment]
Along with ConnectionType, please consider making EdgeType public also.  In my case I need to fully reimplement that from interface for the ConnectionType reimplementation.

**Comment by tobias-tengler** [comment]
I'll have to update the documentation for this, as this type has indeed been removed. 

However you can still customize the pagination:

```csharp
descriptor.Field("test").UsePaging<IdType>().Resolve(ctx =>
{
    return new Connection<string>(new[] { new Edge<string>("hello", "abc"), new Edge<string>("world", "def") },
            new ConnectionPageInfo(false, false, "abc", "abc", 2), _ => ValueTask.FromResult(0));
});
```

This would produce the following schema: 

```graphql
type TestConnection {
  pageInfo: PageInfo!
  edges: [TestEdge!]
  nodes: [ID]
}

type TestEdge {
  cursor: String!
  node: ID
}
```

Let me know if this doesn't cover your use case.

**Comment by tmitchel2** [comment]
Hi Tobias,

Thanks for getting back.  I really want to make the Connection a non nullable type.  I don't that is possible currently?

```
type Query {
   test: TestConnection!
}
```

**Comment by michaelstaib** [comment]
Its best practice in GraphQL to not make connections non-null. The first GraphQL version actually had everything nullable. If you think about the execution algorithm and the schema update implications its logical to be careful with non-null types. That is why non-nullability is opt-in which is the reverse to C# where you express when something is nullable.

Consider that in case of an error a non-nullable field can cause your complete result to be erased through the non-null propagation. Further, making an output field nullable is a breaking change bit the reverse is not. So, everywhere, where something could go wrong the type should be nullable which in the case of fetching a paginated its is warranted.  

In general ... should composite types be nullable and leaf types where appropriate non-null.

**Comment by michaelstaib** [comment]
Maybe this is a good starting point to understand why nullability in GraphQL is better in the case of connection:
https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8

**Comment by tmitchel2** [comment]
Hi Michael,

I see you point and the articles of course, protobuf etc follow similar styles and are great for version evolution.

However, still it is (IMHO) common practise to have non nullable connections, even githubs graphql connections are all non nullable as per https://docs.github.com/en/graphql/reference/queries . I'm successfully using HotChocolate with non nullable connections in v11 and this will be a breaking change for me if i upgrade.  The choice should be mine even if there is some debate on the approach, but in this case the option to allow a nullable connection seems to be locked away.

Is there a way to modify the Type once it has been set or someother approach I can take?  All I want to do is upgrade to v12 asap without any schema changes.

Many thanks

**Comment by tmitchel2** [comment]
For in the unlikely event anyone else has a similar problem I devised this hack to:
1) make the connection non nullable
2) make the connection name same as in v11

(Be aware this only handles my limited use case, it's not generic code by any means)


```
public static IObjectFieldDescriptor UsePaging<TNodeType>(
            this IObjectFieldDescriptor descriptor) where TNodeType : class, IOutputType
        {
            descriptor
                .UsePaging<TNodeType>(null, null, GetConnectionName(typeof(TNodeType)))
                .Extend()
                .OnBeforeCreate((context, definition) =>
                {
                    if (definition.Type is SyntaxTypeReference typeReference)
                    {
                        definition.Type = typeReference.With(
                            new NonNullTypeNode((INullableTypeNode)typeReference.Type),
                            typeReference.Context,
                            typeReference.Scope,
                            typeReference.Factory);
                    }
                });

            return descriptor;
        }

        private static string GetConnectionName(Type value)
        {
            var nodeType = value;
            if (nodeType.GetGenericTypeDefinition() == typeof(NonNullType<>))
            {
                nodeType = nodeType.GetGenericArguments().First();
            }

            if (nodeType.BaseType?.GetGenericTypeDefinition() == typeof(ObjectType<>))
            {
                nodeType = nodeType.BaseType.GetGenericArguments().First();
            }

            return nodeType.Name;
        }
```
