### ISSUE TITLE
Nuget does not have symbols/snupkg for 12.x releases

### ISSUE THREAD

**Issue by JelteF** [ChilliCream/hotchocolate#4299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Nuget does not contain link to download symbols for 12.x packages:
![image](https://user-images.githubusercontent.com/1162278/135826794-b36c6830-2ccb-4b8a-aed8-f8e5d8d03efb.png)

### Steps to reproduce

1. Go to https://www.nuget.org/packages/HotChocolate/12.0.1
2. There is no link to download the symbols

11.3.8 does have the symbols as can be seen here: https://www.nuget.org/packages/HotChocolate/11.3.8
![image](https://user-images.githubusercontent.com/1162278/135827003-a34527ff-a397-46ee-bac3-1c8f53db8fc1.png)

### Product

Hot Chocolate

### Version

12.0.1

**Comment by michaelstaib** [comment]
The main package is now only a meta package. This means it has neither dll nor symbols ... if you have a look at the other packages like HotChocolate.Execution you will see that they still have symbols.
