### ISSUE TITLE
Unable to specify JsonWriteOptions.Encoder

### ISSUE THREAD

**Issue by MaxShoshin** [ChilliCream/hotchocolate#4300]
### Is your feature request related to a problem?

Our GraphQL result contains a lot of Cyrillic strings. 

When it serialized these strings written in the encoded way:
`"Summary": "\u0436\u0430\u0440\u043A\u043E"` instead `"Summary": "жарко"`

Encoded strings takes place. They are bit complicated to observe in chrome dev tools. Etc.

So, I would like to use non encoded cyrillic strings in GraphQL result.

### The solution you'd like

For more information about encoding: 
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding

The simplest way to resolve my issue:
In every place when we create `JsonWriteOptions` we can specify `Encoder`:
```
new JsonWriterOptions 
{
    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
}
```

Another way: we can specify options via 
```
services.AddHttpResultSerializer(options: new JsonWriterOptions() { ... });
```
Such approach is more configurable, but it is necessary to pass this options via necessary pipeline.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
I have added it to the 12.1 backlog.

**Comment by MaxShoshin** [comment]
I can try to create Pull Request for this.

Which way do you prefer? 

```
services.AddHttpResultSerializer(options: new JsonWriterOptions() { ... });
```

This?

**Comment by michaelstaib** [comment]
This should be coming in a preview next week.
