### ISSUE TITLE
Dead subscription socket is causing high cpu usage

### ISSUE THREAD

**Issue by horego** [ChilliCream/hotchocolate#4303]
### UPDATE:
I made a example of client / server to demonstrate the problem. Including an workaround to detect and repair broken subscriptions.
https://github.com/horego/hotchocolate-graphql-examples

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you terminate a GraphQL Server (terminating tcp sockets) the StrawberryShake Client causes high cpu usage.

### Steps to reproduce
When you build a system containing two parts:
* HotChocolate Server with subscriptions
* Client which consumes the subscription via ".Watch(StrawberryShake.ExecutionStrategy? strategy = null)"

then...
* Start the server (wait until the server is ready)
* Start the client (subscribe to any subscription)
* Closing the server (kills the tcp sockets)

you get a high CPU load caused by strawberry client

### What i figured out
StrawberryShake.Transport.WebSockets.WebSocketClient IsClosed State is never true and causing lots of exception an some kind of an endless loop. When you have a look at "ClientWebSocket _socket" variable _socket.State equals WebSocketState.Aborted.

### Solution?
I added the following code to get rid of the high cpu usage inside file [https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/Client/src/Transport.WebSockets/WebSocketClient.cs](url).
`
public bool IsClosed =>
	_disposed
	|| _socket.CloseStatus.HasValue || _socket.State == WebSocketState.Aborted;
`

maybe there is a better way to fix this. This was my first attempt.
This issue belongs to version 12 and 11 (maybe below but haven't tried this)

best regards

### Product

Strawberry Shake

### Version

12.0.1, 11.3.1

**Comment by michaelstaib** [comment]
do you want to try a pr?

**Comment by horego** [comment]
> do you want to try a pr?

i created a pr
https://github.com/ChilliCream/hotchocolate/pull/4304
