### ISSUE TITLE
BCP title configuration being ignored

### ISSUE THREAD

**Issue by msawczyn** [ChilliCream/hotchocolate#4307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to change the title of the built-in BCP web ui, the code
```
            app.UseEndpoints(
                endpoints =>
                {
                    endpoints.MapBananaCakePop()
                       .WithOptions(new GraphQLToolOptions
                       {
                           Title = "Custom title",
                       });
                });
```
doesn't change the title text in the BCP browser tab.

![image](https://user-images.githubusercontent.com/1778442/136542120-dbbd3fcc-c28f-4df7-b32f-74402259d2fd.png)

### Steps to reproduce

1. Configure the server using the code shown above.

### Product

Banana Cake Pop

### Version

12.0.1

**Comment by kkliebersbach** [comment]
The following works for me in v12.0.1 as a workaround:

```csharp
endpoints.MapGraphQL().RequireAuthorization().WithOptions(new GraphQLServerOptions
{
    Tool =
    {
        Title = "Custom title"
    }
});
```
