### ISSUE TITLE
[UseServiceScope] attribute hangs with DataLoader

### ISSUE THREAD

**Issue by braidenstiller** [ChilliCream/hotchocolate#4315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

When using the new [UseServiceScope] attribute on a resolver with a dataloader causes the resolver to hang when the dataloader's LoadAsync() method is called.

This breaks resolvers which require both dataloaders and scoped services.

### Steps to reproduce

1) Create DataLoader
2) Create Resolver with DataLoader and use the [UseServiceScope] attribute on the resolver.
3) Call LoadAsync() on the DataLoader.

### Relevant log output

```shell
No logs. Just hangs.
```

### Product

Hot Chocolate

### Version

V12

**Comment by jamiewinder** [comment]
This appears to still be an issue.

**Comment by PascalSenn** [comment]
@jamiewinder  what version are you on?
Can you provide a minimal reproduction?

**Comment by jamiewinder** [comment]
@PascalSenn - This is on the latest version - 12.12.1 (same on 12.12.0).

The following example shows this:

```c#
public class ExampleDataLoader : BatchDataLoader<int, string>
{
    public ExampleDataLoader(IBatchScheduler batchScheduler, DataLoaderOptions? options = null) 
        : base(batchScheduler, options)
    {
    }

    protected override Task<IReadOnlyDictionary<int, string>> LoadBatchAsync(
        IReadOnlyList<int> keys, 
        CancellationToken cancellationToken)
        => Task.FromResult<IReadOnlyDictionary<int, string>>(keys.ToDictionary(key => key, key => key.ToString()));
}

public class Query
{
    [UseServiceScope]
    public Task<string> Example1([DataLoader] ExampleDataLoader dataLoader, int value)
        => dataLoader.LoadAsync(value);

    [UseServiceScope]
    public Task<string> Example2(int value)
        => Task.FromResult(value.ToString());

    public Task<string> Example3([DataLoader] ExampleDataLoader dataLoader, int value)
        => dataLoader.LoadAsync(value);
}

public static class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        builder.Services
            .AddGraphQLServer()
            .AddQueryType<Query>();

        var app = builder.Build();
        app.MapGraphQL();
        app.Run();
    }
}
```
The following will hang (uses `UseServiceScope` and data loader):
```graphql
{
    example1(value: 1)
}
```
The following will work (uses `UseServiceScope`, but not a data loader):
```graphql
{
    example2(value: 1)
}
```
The following will work (does not use `UseServiceScope`, but does use a data loader):
```graphql
{
    example3(value: 1)
}
```

**Comment by jamiewinder** [comment]
A little more detail: the `LoadAsync` method (in the resolver) is being called, but the `LoadBatchAsync` method (of the data loader) is not.

**Comment by jamiewinder** [comment]
@sgabler I'm afraid not, I've just had to force the resolvers to run in serial.

**Comment by michaelstaib** [comment]
This is now fixed and will be shipped with version 13 preview 95
