### ISSUE TITLE
Filtering of child lists evaluated before resolver is called

### ISSUE THREAD

**Issue by robolize** [ChilliCream/hotchocolate#4317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a data model where I have a list of parents, and those parents have children.  The children are fetched using a resolver.
I want to be able to filter the parents by children.  Let's say, give me a list of all the parents who have a child named Bob.
When the filtering is applied, it appears to be evaluated before the children resolver executes.  So from the filtering perspective, it appears as though no parents have any children.

### Steps to reproduce

The query would look like this.

`query {
  parents(where: {
    children: {some: {childName: {eq: "Bob"}}}
  },
  ) {
      parentName
      children {
        childName
      }
    }
}`

### Relevant log output

```shell
n/a
```

### Additional Context?

I am not using IQueryable.  My types are configured to read from repository interfaces which return lists of data.

I have tried with and without paging enabled.

### Product

Hot Chocolate

### Version

12.0.1

**Comment by JK2Kgit** [comment]
Hi are there any plant to support this with newer versions?
