### ISSUE TITLE
IdType don't respect nullability and [GraphQLNonNullType] attribute

### ISSUE THREAD

**Issue by deadeyye** [ChilliCream/hotchocolate#4319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm working on moving from longs-type ids to ID. I have strict nullability enabled in the project, however, after the switch from long to ID, the field is exported as nullable.
This
```
public class Customer
{
    public long Id { get; set; }  
}
```
works correctly and the schema contains Id: long!
but this:
```
public class Customer
{
    [GraphQLType(typeof(IdType))] [GraphQLNonNullType]
    public long Id { get; set; }
   
}
```
generates schema:
Id: ID
which is nullable.

Expected solutions:
preferred - when strict nullability is enabled, this should generate a non-nullable field:
```
public class Customer

    [GraphQLType(typeof(IdType))] 
    public long Id { get; set; }

```

alternatively - at least [GraphQLNonNullType] should be respected, so: 
```
[GraphQLType(typeof(IdType))] [GraphQLNonNullType]
    public long Id { get; set; }
```

generates the non-nullable field.

### Steps to reproduce

1. Write any model or query with parameters as described above.

### Relevant log output

```shell
id: ID
```

### Product

Hot Chocolate

### Version

12.0.1

**Comment by PascalSenn** [comment]
This should work:
```
   [GraphQLType(typeof(NonNullType<IdType>))] 
```

**Comment by michaelstaib** [comment]
This one is fixed with preview 10
