### ISSUE TITLE
Don't overfetch when `hasNextPage` isn't requested + the `hasPreviousPage` field for offset paging is redundant

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#4321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there. I'm currently working with HC's offset pagination middleware, and I think there are 2 changes that should be made to it.

## 1. Don't overfetch when the `hasNextPage` field wasn't requested by the client:
Currently, when you send a query to a paginated field, with the `take` parameter set to "N", HC will fetch "N+1" to know whether there is a next item or not. However, if the client hasn't requested the `hasNextPage` field, that's entirely unnecessary and should not happen.
In my project, for instance, most of the time I only need the `totalCount`, and I almost never need the `hasNextPage` field, and so I don't want HC to unnecessarily fetch an extra row every time I send a request even though I didn't ask for `hasNextPage`. I hope that makes sense.

## 2. The `hasPreviousPage` field doesn't make sense for offset pagination:
I don't think this one needs much elaboration, the `hasPreviousPage` only makes sense for cursor pagination. In the case of offset pagination, if the `skip` parameter is greater than 0, then then you know there is a previous page. So, this field should not be included in the `CollectionSegmentInfo` type when you're using offset pagination.

### Product
Hot Chocolate

### Version
12.0.1

**Comment by AradAral** [comment]
@PascalSenn @michaelstaib I'm curious whether you guys agree with this. Could it perhaps be added to the HC-12.2.0 milstone?
Thanks.

**Comment by PascalSenn** [comment]
@AradAral  This would be a breaking change in the pagination API. 
Paging does not know about graphql. So you would have to pass on state to signal that it should not overfetch. 
My thoughts on 1) are, does it matter much if you overfetch by one? did you do performance benchmarks and saw that the query is slower? 
My thoughts on 2) are that at the moment both pagination implementations are implemented the same. The SDL structure is aligned to have the same shape. having a hasNextPage but no hasPreviousPage seems odd. You could still ignore the the field if you do not like to have it.

**Comment by AradAral** [comment]
@PascalSenn 

> This would be a breaking change in the pagination API.

Which one do you mean? 1 or 2? I'm not sure how 1 would be a breaking change. So you must be talking about 2 there.

> Paging does not know about graphql.

Well I'm surprised to hear that. Then how is it that it's looking at the selection set to see whether `totalCount` has been requested, to decide whether it should retrieve the total count or not?!

> are that at the moment both pagination implementations are implemented the same

Sure, but I'm suggesting that they should not be, since the two pagination approaches are fundamentally different.

> having a hasNextPage but no hasPreviousPage seems odd

Not in offset pagination. Since in offset pagination having a `skip` greater than `0` means there is a previous page, by definition. If you have a `skip` of `5`, then it means there are `5` items before the first item that is going to be returned.
So, a `hasPreviousPage` doesn't make sense here. It only makes sense in the case of cursor pagination where the only information the client has prior to sending a request to the API is the cursor, and he cannot infer whether there is an item "before" the cursor or not. But in the case of offset pagination, he does. So, `hasPreviousPage` is redundant.

**Comment by PascalSenn** [comment]
> Which one do you mean? 1 or 2? I'm not sure how 1 would be a breaking change. So you must be talking about 2 there.

Both actually. 1) breaks the HotChocolate API, 2) breaks the customer schema

> Well I'm surprised to hear that. Then how is it that it's looking at the selection set to see whether totalCount has been requested, to decide whether it should retrieve the total count or not?! Can't it do the same thing with hasNextPage?

https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.CursorPagination/CursorPaginationAlgorithm.cs

> Not in offset pagination. Since in offset pagination having a skip greater than 0 means there is a previous page, by definition. If you have a skip of 5, then it means there are 5 items before the first item that is going to be returned.
So, a hasPreviousPage doesn't make sense here. It only makes sense in the case of cursor pagination where the only information the client has prior to sending a request to the API is the cursor, and he cannot infer whether there is an item "before" the cursor or not. But in the case of offset pagination, he does. So, hasPreviousPage is redundant.

I understand how offset paging works. But it's about the shape of the graphql type. If there is a hasNextPage why shouldnt there be a hasPreviousPage. You can have a fragment  and create a component for it that handles the pagination information that does not need to know anything about the query or the parameters.

**Comment by AradAral** [comment]
@PascalSenn 
Ok, what about at least providing a way to make both `take` and `skip` optional? I mean such that when they're not specified by the client, no take or skip is applied to the IQueryable. Currently that's not possible and HC will always use `DefaultPageSize`. Personally, I have many query fields that I need that kind of mechanism for, but I'm paralyzed at the moment and the best I can do is create separate fields like `courseReviewsPaginated` and `courseReviews`, which is ugly and tedious.

I know this is unrelated but I just wanted to ask this here quickly to avoid creating a separate issue if you think this isn't feasible either.

Thanks.

**Comment by michaelstaib** [comment]
> Not in offset pagination though. Since in offset pagination having a skip greater than 0 means there is a previous page, 

Also this is not true ... you can skip 50 on a set that has 0 items then you do not have a previous page.

But anyway we favor no structural change since you can just not fetch the fields that you do not like. Changing the structure will fundamentally break all schemas that we have.

Further, I do not thing that the issues outlined are big pain points at this moment. 

> Ok, what about at least providing a way to make both take and skip optional? I mean such that when they're not specified by the client, no take or skip is applied to the IQueryable. Currently that's not possible and HC will always use DefaultPageSize. Personally, I have many query fields that I need that kind of mechanism for, but I'm paralyzed at the moment and the best I can do is create separate fields like courseReviewsPaginated and courseReviews, which is ugly and tedious.

This would be really bad In my opinion. If you want that behavior just specify DefaultPageSize to `int.Max`.

**Comment by PascalSenn** [comment]
@AradAral  
Also, you can really easily build this. 
You can return a CollectionSegement from the resolver that you use offset paging with, and you can also inject the parameters into that resolver. 
Doing a `if is null` is and apply skip and take conditionally is pretty straight forward. just create a connection based on the result and you are done.

**Comment by michaelstaib** [comment]
I am closing this issue since we also discussed it internally and the core team is not in favor of this.

**Comment by AradAral** [comment]
You can return a CollectionSegement from the resolver that you use offset paging with, and you can also inject the parameters into that resolver.

@PascalSenn I did actually try that but I need projection as well and `CollectionSegment`'s constructor expects an `IReadOnlyCollection` and you can't pass an `IQueryable` to it. Unless I'm missing something, it isn't possible to use `CollectionSegment` AND projection at the same time. Am I right?

**Comment by AradAral** [comment]
> Also this is not true ... you can skip 50 on a set that has 0 items then you do not have a previous page.

@michaelstaib Note that you actually haven't taken that into account yourself by the way. Look:
https://github.com/ChilliCream/hotchocolate/blob/7ec5071ce2080b3eb2c02c5a9fc9ee417fd448ce/src/HotChocolate/Core/src/Types.OffsetPagination/OffsetPaginationAlgorithm.cs#L68

It's just checking for whether skip is greater than 0, which as you said would wrongly evaluate to `true` on a set that has 0 items.

**Comment by michaelstaib** [comment]
Sure, but from the structure, I could... just saying you are oversimplifying things. The main thing for me not to change the schema structure is a) not to break people's schema and b) I do not see the issues. I think the change is not worth it.
