### ISSUE TITLE
Add new Scalar Types for System.DateOnly & System.TimeOnly

### ISSUE THREAD

**Issue by RehanSaeed** [ChilliCream/hotchocolate#4328]
### Is your feature request related to a problem?

.NET 6 added the new System.DateOnly & System.TimeOnly types. These should be mapped to the `LocalDate` and `LocalTime` types specifically.

### The solution you'd like

Two new scalar type mappings added by default.

### Product

Hot Chocolate

**Comment by AradAral** [comment]
> These should be mapped to the LocalDate and LocalTime types specifically.

Why wouldn't `DateOnly` be mapped to the already-existing `Date` type?!

**Comment by AradAral** [comment]
@michaelstaib  Does https://github.com/ChilliCream/hotchocolate/pull/4483 resolve this?

**Comment by tobias-tengler** [comment]
This should be resolved. `DateOnly` is now inferred as the `DateType` and `TimeOnly` is inferred as the `TimeSpanType`.
