### ISSUE TITLE
Open telemetry instrumentation

### ISSUE THREAD

**Issue by SbiCA** [ChilliCream/hotchocolate#4336]
### Is your feature request related to a problem?

As of HC 12 

I see two interesting operational challenges that could be solved by open telemetry (https://github.com/open-telemetry/opentelemetry-dotnet)  integration/instrumentation

Logging a "request" (I know it's not as straight forward with stream, defer) context
- https://github.com/ChilliCream/hotchocolate/issues/4092
Allowing to get more context for all requests that happen e.g. I'd like to know which `user`, `user-agent`/device executed something
- https://github.com/ChilliCream/hotchocolate/issues/2221

### The solution you'd like

Having an instrumentation for opentelemetry tracing + potentially logs (https://github.com/ChilliCream/hotchocolate/issues/2221 can be split out?) will allow end to end picture on what query/mutation did cause a lot of db headaches or I/O round trips.

I guess hc can already leverage existing instrumentation approaches such as 
 https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We have discussed open-telemetry support internally and will add this feature with 12.5 or 12.6.

**Comment by atrauzzi** [comment]
Awesome!  npgsql just rolled out their OpenTelemetry support.  Would love to be able to add HotChocolate to the mix!
