### ISSUE TITLE
Check MimeType while uploading file

### ISSUE THREAD

**Issue by muhammed-ozer** [ChilliCream/hotchocolate#4342]
### Is your feature request related to a problem?

We want to check MimeType while uploading file. Bu we couldn't. 

It would be great if we could also get the file name.

I'm not sure if this is the HC feature.

This issue was opened based on the conversation here (https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1635029998100800.)

### The solution you'd like

.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
I have added the content-type as nullable prop to the interface for 13. 

```csharp
public interface IFile
{
    /// <summary>
    /// Gets the file name.
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Gets the file length in bytes.
    /// </summary>
    long? Length { get; }

    /// <summary>
    /// Gets the content type of the file if it is available.
    /// </summary>
    string? ContentType { get; }

    /// <summary>
    /// Asynchronously copies the contents of the uploaded file to the target stream.
    /// </summary>
    /// <param name="target">
    /// The stream to copy the file contents to.
    /// </param>
    /// <param name="cancellationToken">
    /// The cancellation token.
    /// </param>
    Task CopyToAsync(Stream target, CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens the request stream for reading the uploaded file.
    /// </summary>
    Stream OpenReadStream();
}
```

I found this nicer and more discoverable. Will merge this in the next couple of minutes.

**Comment by cliedeman** [comment]
Thanks for the fast turnaround

**Comment by michaelstaib** [comment]
This one is now implemented.
