### ISSUE TITLE
Optional<> is requiring the field on the input.

### ISSUE THREAD

**Issue by Jonatthu** [ChilliCream/hotchocolate#4353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If using Optional interface in one of the properties, the only way to make sure graphql thinks that is actually optional, is to mark it as nullable. 

See for example  `Optional<DateTime?> CreatedAt ` vs  `Optional<AccountType> AccountType`

One introspected one will be rendered as AccountType! vs the other one just as DateTime.

```
	public class UpdateExternalAccountInput
	{
		public int Id { get; set; }
		public Optional<DateTime?> CreatedAt { get; set; }
		public Optional<AccountType> AccountType { get; set; }
        }
```

### Steps to reproduce

1. 
![image](https://user-images.githubusercontent.com/3742176/139359895-e85a59c3-6f3a-4eba-8e8b-136f88fd2c2e.png)

### Product

Hot Chocolate

### Version

12.0.1

**Comment by Jonatthu** [comment]
What's the use case @PascalSenn ?

**Comment by PascalSenn** [comment]
@Jonatthu  It does sound like it. We also had many discussions around the name of it. But we and the community did not come up with a better name.
Optional is really only there to check if a user value is provided or not. If a argument for example has a default value, the user does not have to provide it. In this case the argument does not have to be nullable.

**Comment by Jonatthu** [comment]
The problem of this is that values like String are nullable by default, I would rather assume that an string will render as String! Instead of String and when Optional is applied, the default value is null and if the user does not even call it (undefined) on the server I know that the user did not tried to modify to null or to empty string. Optional helps to do this possible because HasValue is true even if the user defines null but if the user did not tried to set the string to null HasValue is false and also makes it easier to know if I have to update an entity on the backend. There is ways to workaround this. Of course. But to be honest the Optional naming does not makes sense and makes scenarios like 

Optional<DateTime?> to acquire the value like:

DateTime myTime = myDate.Value.Value

**Comment by Jonatthu** [comment]
The optional value as designed only makes sense on string types but not on the other regular types since truly requires you to define the value on the graphql mutation. Unless using string null strict I would have to do string?

I think this topic should be re-open or re analyzed, maybe rename the Optional with the current behavior but recreate another one that helps to accomplish this.

**Comment by PascalSenn** [comment]
@Jonatthu  
See for more context: https://github.com/ChilliCream/hotchocolate/issues/1808
