### ISSUE TITLE
Projections with Cursor Paging on Oracle db return empty nodes

### ISSUE THREAD

**Issue by MarkitoAgnito** [ChilliCream/hotchocolate#4365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using projections with cursor based againg on Oracle DB I expect the requested values to return. Instead empty nodes are returned {}. 

### Steps to reproduce

1. Running the following against Oracle db: 
`{
  organisations{
   edges{    
      node{
        organisation{
          id
          description
          name       
        }
      }
   }      
    pageInfo{ 
      endCursor
      endCursor   
      hasPreviousPage
      hasNextPage
    }
  }
}`

returns:
`{
  "data": {
    "organisations": {
      "edges": [
        {
          "node": {
            "organisation": {}
          }
        },
        {
          "node": {
            "organisation": {}
          }
        }
      ],
      "pageInfo": {
        "endCursor": "MQ==",
        "hasPreviousPage": false,
        "hasNextPage": false
      }
    }
  }
}`

2. If a single property is requested in the nodes the data is returned back:
`{
  organisations{
   nodes{
     organisation{
       id
     }
   }
   edges{ 
        organisation{
          id
          description
          name
        }
      }
   }           
    pageInfo{ 
      endCursor
      endCursor     
      hasPreviousPage
      hasNextPage
    }
  }
}`

But the data requested in edges is duplicated for Nodes and Edges in full effectively doubling the payload.

**3. This issue does not occur when using offset paging**

### Product

Hot Chocolate

### Version

11.0.7

**Comment by tobias-tengler** [comment]
Can you please confirm that this also happens with the latest version (v12) as well as create and share a GitHub repository that reproduces the issue on a small scale?

**Comment by MarkitoAgnito** [comment]
Upgrading to 12.0.1 and the issue now appears to be resolved. Happy to close this defect.
