### ISSUE TITLE
Summary descriptions missing

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#4388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For the longest time, one of the most important things I wished HC had was summary descriptions for interfaces, classes, methods and so on, I always assumed you never wrote them. But after looking at the source code, I noticed that they are actually there. It's just that when the NuGet packages are installed, they are missing.

As @michaelstaib mentioned [here](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1636133290143200?thread_ts=1636133167.143100&cid=CD9TNKT8T), there must be something wrong with the XML files or something.

This would be a huge pro, and would drastically improve the developer experience. The summary descriptions are currently essentially wasted now. Would love to have them soon.

### Additional Context?

Side note: I published a NuGet package a long time ago and I dimly remember I had the same problem in the beginning, namely that even though I had written summary descriptions, they weren't shown when the package was installed. As far as I remember it had a straightforward fix. So, this shouldn't be too big of a problem.

### Product

Hot Chocolate

### Version

12.0.0

**Comment by michaelstaib** [comment]
This is fixed.
