### ISSUE TITLE
UseFirstOrDefault and UseSingleOrDefault cause type errors #2

### ISSUE THREAD

**Issue by lucas-garrido** [ChilliCream/hotchocolate#4397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
I think this issue is not resolved : https://github.com/ChilliCream/hotchocolate/issues/2917#issue-791321558

Sometimes adding association breaks everything, i had everything working fine( with multiples classes and multiples associations) until i added
![image](https://user-images.githubusercontent.com/48165310/140898622-ca012f7b-85a5-411d-ae15-579ab89be3a5.png)
to one of my classes.
I think this is related to UseFirstOrDefault because removing all annotations avoid the problem.

### Steps to reproduce

1. 

### Relevant log output

```shell
Unable to resolve type reference `None: Customer`. (HotChocolate.Types.ObjectType<api.Graphql.Query>)
```

### Product

Hot Chocolate

### Version

12.1.0

**Comment by tobias-tengler** [comment]
@PascalSenn [your PR](https://github.com/ChilliCream/hotchocolate/pull/2921) addressing the original issue was never merged. 
Is there anything that's blocking it? If not I'd say we resolve merge conflicts and make it part of the next preview.

**Comment by lucas-garrido** [comment]
sounds great, do you have a workaround meanwhile ?

**Comment by tobias-tengler** [comment]
@lucas-garrido I sadly do not, but Pascal might have :)
