### ISSUE TITLE
ActionFilterAttribute

### ISSUE THREAD

**Issue by shidcordero** [ChilliCream/hotchocolate#4398]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Anyone tried adding ActionFilterAttribute. I want to add a DNS look-up on my code to check the RemoteAddress based on the request HttpContext.Connection. The user could be unauthenticated so I was not able to use a custom policy handler for it being used in an Authorize attribute. Any way I could implement it in ActionFilterAttribute?

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12.0.1

**Comment by tobias-tengler** [comment]
Could you please elaborate on what you are trying to achieve? I'm unable to understand your use case based on the example given. Try to explain it without relying on MVC references.

It sounds to me like you want to run code either before a request is executed or a field resolver is executed!?
You might want to look into [request interceptors](https://chillicream.com/docs/hotchocolate/server/interceptors) or field middleware, i.e. `descriptor.Use(next => context => ...)`

**Comment by shidcordero** [comment]
@tobias-tengler sorry for the bad explanation. Yes, you are right, I want a code to run before a request is executed and deny any request that does not belong to the specified DNS host name that I listed.

```
  public class GoogleBotHandler : AuthorizationHandler<GoogleBotRequirement>
    {
        private readonly IHttpContextAccessor _http;

        public GoogleBotHandler(IHttpContextAccessor http)
        {
            _http = http;
        }

        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, GoogleBotRequirement requirement)
        {
            var host = Dns.GetHostEntry(_http.HttpContext.Connection.RemoteIpAddress);

            // ..check dns and success if it is equal to it
            context.Succeed(requirement);

            return Task.CompletedTask;
        }
    }
```

This is what its looks like If I implement it using custom policy handler. But this requires me that the client is authenticated. I also have take a look on request interceptors but it will run on all my graphql endpoints. This checking will be only added in 2 or 3 end points that's why I want to make it as an attribute.

**Comment by tobias-tengler** [comment]
I think what you are referring to as endpoint is a field of your graph / a resolver.

In this case I would create a field middleware and make it available through an attribute.

```csharp
public class ExampleAttribute : ObjectFieldDescriptorAttribute
{
    public override void OnConfigure(IDescriptorContext context,
        IObjectFieldDescriptor descriptor, MemberInfo member)
    {
        descriptor.Use(next => async context =>
        {
            var accessor = context.Service<IHttpContextAccessor>();

            if (checkFailed)
            {
                throw new GraphQLException("Check failed");
            }

            await next.Invoke(context);
        });
    }
}

// ,,,

[Example]
public Entity MyResolver() => ...
```

**DISCLAIMER** This is not tested and might require some tweaking!

**Comment by tobias-tengler** [comment]
I'm closing this since your use case can be done using middleware. I don't see a need for the proposed ActionFilterAttribute. 
Feel free to reopen if you still have issues / questions :)
