### ISSUE TITLE
Can't use schema with Any scalar type

### ISSUE THREAD

**Issue by jorrit** [ChilliCream/hotchocolate#4405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using StrawberryShake to access a HotChocolate GraphQL server that uses the Any scalar type. I have followed the guide on https://chillicream.com/docs/strawberryshake/scalars/#any-or-json to make this work.

When running `dotnet build` I get:

```
CSC : error SS0006: Unable to resolve type reference `None: Any`. [.....csproj]
```

When I replace Any with JSONObject in my schema file, the error goes away. It seems to be related to the name Any.

### Steps to reproduce

1. Set up a StrawberryShake client as described on https://chillicream.com/docs/strawberryshake/get-started/console, using a GraphQL endpoint that exposes the `Any` type.
2. Build the project using `dotnet build`

### Relevant log output

```shell
CSC : error SS0006: Unable to resolve type reference `None: Any`. [.....csproj]
```

### Product

Strawberry Shake

### Version

12.1.0

**Comment by michaelstaib** [comment]
Have you looked at the following test class `AnyScalarDefaultSerializationTest`?

**Comment by jorrit** [comment]
After a lot of tinkering I have found a failure case. I've made a PR with just a changed test at #4418. I hope you can find time to take a look!
