### ISSUE TITLE
StrawberryShake Visual Studio extension - support for Visual Studio 2022

### ISSUE THREAD

**Issue by guillaumeserale** [ChilliCream/hotchocolate#4409]
### Is your feature request related to a problem?

Currently, there's an existing [StrawberryShake Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=ChilliCream.strawberryshake-visualstudio) that is only supported by Visual Studio 2019.

Unfortunately, this extension is not available for the recently released Visual Studio 2022.

### The solution you'd like

Could you make this StrawberryShake Visual Studio extension available for Visual Studio 2022 please ?

### Product

Strawberry Shake

**Comment by guillaumeserale** [comment]
@michaelstaib I see that you have released the [VS 2022 extension](https://marketplace.visualstudio.com/items?itemName=ChilliCream.strawberryshake-visualstudio&ssr=false#overview).
Somehow, the VS 2019 extension is not available anymore. Can you make it available again ?

**Comment by michaelstaib** [comment]
@guillaumeserale not really... I just pushed the new version and they dropped the old one.
