### ISSUE TITLE
Custom attribute for UseDatabase broken

### ISSUE THREAD

**Issue by Jonatthu** [ChilliCream/hotchocolate#4416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a bug where the short hand of
[UseDbContext(typeof(TradingDbContext))]
won't work as
[UseAppDbContext]
This is using 12.2

1. The middleware pipeline order for the field `Query.stopOrders` is invalid. Middleware order is important especially with data pipelines. The correct order of a data pipeline is as follows: UseDbContext -> UsePaging -> UseProjection -> UseFiltering -> UseSorting. You may omit any of these middleware or have other middleware in between but you need to abide by the overall order. Your order is: UsePaging -> UseProjection -> UseFiltering -> UseSorting -> UseDbContext.... (HotChocolate.Types.ObjectType)

### Steps to reproduce

1. https://hotchocolategraphql.slack.com/files/U027FD05RHS/F02M3GKRRM1/image.png
https://hotchocolategraphql.slack.com/files/U027FD05RHS/F02M0H0TLQ5/image.png
https://hotchocolategraphql.slack.com/files/U027FD05RHS/F02MT75CK24/image.png

### Relevant log output

```shell
1. The middleware pipeline order for the field `Query.stopOrders` is invalid. Middleware order is important especially with data pipelines. The correct order of a data pipeline is as follows: UseDbContext -> UsePaging -> UseProjection -> UseFiltering -> UseSorting. You may omit any of these middleware or have other middleware in between but you need to abide by the overall order. Your order is: UsePaging -> UseProjection -> UseFiltering -> UseSorting -> UseDbContext.... (HotChocolate.Types.ObjectType)
```

### Additional Context?

Hotchocolate latest version 12.2.0

### Product

Hot Chocolate

### Version

12.2.0

**Comment by michaelstaib** [comment]
This is not a bug. The order of attributes in C# is not guaranteed, that is why we reworked the attributes to infer the order from the code line number.

Add the following constructor to your attribute:

```csharp
public UseAppDbContext([CallerLineNumber] int order = 0)
{
    Order = order;
}
```

**Comment by zaneclaes** [comment]
This works spuriously for me on v`12.12.1`. It solved my error in one case, but does not work in others. 

Attribute:
```public class UseFurDataContext : ObjectFieldDescriptorAttribute {
  public UseFurDataContext([CallerLineNumber] int order = 0) {
    Order = order;
  }
  
  public override void OnConfigure(
    IDescriptorContext context,
    IObjectFieldDescriptor descriptor,
    MemberInfo member) {
    descriptor.UseDbContext<FurDataContext>();
  }
}
```

Implementation:
```
[ExtendObjectType(typeof(BossBattlePlayer))]
public class GameBattleExtensions {
  [GraphQLDescription("Paginate through the moves in the game")]
  [Serial] 
  [UseFurDataContext] 
  [UsePaging]
  public IQueryable<BattleMove> GetMoves([Service] FurContext context, [Parent] BossBattlePlayer battle) => context.Data.BattleMoves
    .IncludeDefaultBattleMove() 
    .Where(m => m.BattleId.Equals(battle.Id))
    .OrderByDescending(s => s.CreatedAt);
}
```

Error:
```
{
  "errors": [
    {
      "message": "For more details look at the `Errors` property.\n\n1. The middleware pipeline order for the field `BossBattlePlayer.moves` is invalid. Middleware order is important especially with data pipelines. The correct order of a data pipeline is as follows: UseDbContext -> UsePaging -> UseProjection -> UseFiltering -> UseSorting. You may omit any of these middleware or have other middleware in between but you need to abide by the overall order. Your order is: UsePaging -> UseSorting -> UseDbContext... -> UsePaging. (Furballs.Api.Bosses.BossBattlePlayerType)\n",
      "type": "Exception",
      "code": "SchemaException",
      "data": {},
      "stack": [ ...
      ]
    }
  ],
  "meta": {
    "traceId": "0HMK6R5OEHV8H:00000002"
  }
}
```

**Comment by larsandreasvestbo** [comment]
For future Google travelers... If all your decorators are applied twice in order, it probably means you have a method with the same name elsewhere in your codebase.
```[10:32:42 ERR] An unhandled exception has occurred while executing the request.
HotChocolate.SchemaException: For more details look at the Errors property.

1. The middleware pipeline order for the field `Query.items` is invalid. Middleware order is important especially with data pipelines. The correct order of a data pipeline is as follows: UseDbContext -> UsePaging -> UseProjection -> UseFiltering -> UseSorting. You may omit any of these middleware or have other middleware in between but you need to abide by the overall order. Your order is: UsePaging -> UseProjection -> UseFiltering -> UseSorting -> UsePaging -> UseProjection -> UseFiltering -> UseSorting. (HotChocolate.Types.ObjectType<DataAccess.Query>)```

**Comment by clequang** [comment]
> For future Google travelers... If all your decorators are applied twice in order, it probably means you have a method with the same name elsewhere in your codebase. Example: `TestA.Items()` and `TestB.Items()`

👍 You save my day ! 
Many thanks.

**Comment by NickStrupat** [comment]
What about modifying the `DefaultTypeInspector.ApplyAttributes` method to sort the attributes into the correct middleware order for the user?

We just ran into an issue where our attributes were on the same line. The [CallerLineNumber] didn't help.
