### ISSUE TITLE
Validation Error: Add more extensions to the variable value type error

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#444]
When firing the following query:

```graphql
query AbitraryQuery($name: [String!]!) {
  # Omitted for brevity
}
```

I get the following validation error:

```graphql
{
  message: "The variable value is not of the correct type.",
  extensions: {
    variableName: "name"
  }
}
```

But it would be nice to have a more concise error description here. For example what is the type I passed through and what type was expected actually. See the following desirable error:

```graphql
{
  message: "The variable value is not of the correct type.",
  extensions: {
    variableName: "name",
	expectedType: "[String!]!",
	providedType: "String!"
  }
}
```

**Comment by michaelstaib** [comment]
Is this still open or is it solved with the new validation?

**Comment by michaelstaib** [comment]
This one is implemented on 11.
