### ISSUE TITLE
Graphql Errors should Return 200

### ISSUE THREAD

**Issue by cliedeman** [ChilliCream/hotchocolate#4447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to the [graphql over http specification](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes) any non 200 status code is not garunteed to have the graphql shape and should be ignored.

Currently hotchocolate returns a 500 status code when returning errors. This should be 200

### Steps to reproduce

1. Generate a server side exception
2. Inspect response - status code will be 500

### Additional Context?

Found an previou ticket that says this is the correct behaviour but could not find it in the specifiaction

- https://github.com/ChilliCream/hotchocolate/issues/2569#issuecomment-830921186
- https://github.com/ChilliCream/hotchocolate/issues/2779

### Product

Hot Chocolate

### Version

12.0.0

**Comment by tobias-tengler** [comment]
You are likely throwing the exception from within a non-null field, therefore no data can be produced and you get 500. If your field is nullable you should get 200.
If you get a 500 for throwing an exception within a nullable field, please open the issue again and share a minimal reproducible example :)
