### ISSUE TITLE
Strawberry Shake error about already registered type

### ISSUE THREAD

**Issue by jorrit** [ChilliCream/hotchocolate#4448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When building any project with Strawberry Shake 12.2.2, the following error is displayed:

```
CSC : error SS0006: The name `Query` was already registered by another type.
```

### Steps to reproduce

1. Clone https://github.com/jorrit/strawberryshakebug2
2. Run `dotnet build`

### Relevant log output

```shell
PS C:\Projects\strawberryshakebug2> dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error SS0006: The name `Query` was already registered by another type. [C:\Projects\strawberryshakebug2\strawberryshakebug2.csproj]

Build FAILED.

CSC : error SS0006: The name `Query` was already registered by another type. [C:\Projects\strawberryshakebug2\strawberryshakebug2.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.27
```

### Product

Strawberry Shake

### Version

12.2.2

**Comment by jorrit** [comment]
After submitting the issue I tried so change `"documents": "**/*.graphql",`  to `"documents": "Queries.graphql",` and this worked. Apparently the following config:

`
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
`

causes `schema.graphql` to be loaded twice.

This seems weird to me, as the manual recommends this configuration.

**Comment by jorrit** [comment]
No, it still didn't work for me either. The code generator could really benefit from some additional diagnostic output, as I have no idea how to debug it when nothing happens and no errors are generated.

**Comment by idasilva1** [comment]
Actually, I was taking a look at my scenario and it is a bit different from yours (but probably the same issue?)
I'm getting the error when trying to compile with `"documents": "**/*.graphql"`:
`error SS0006: An item with the same key has already been added. Key: Name [/../../../BlazorGraphql/BlazorGraphql.csproj]` did I understand this right? Is it trying to recreate my `.csproj` again?
And I'm using `.NET 6` with Blazor WebAssembly project.

**Comment by AmbroiseCouissin** [comment]
I have the same issue.
After updating the "documents" path, the error disappeared, but still nothing was generated.

**Comment by jorrit** [comment]
I have updated https://github.com/jorrit/strawberryshakebug2 to the latest preview: 12.7.0-preview.24. I've also added the StrawberryShake_LogFile setting. Opening this log file gives the following error in its output:

```
C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.24\build\..\analyzers\dotnet\cs
C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.24\build\..\analyzers\dotnet\cs
C:\Projects\GitHub\strawberryshakebug2\Queries.graphql
C:\Projects\GitHub\strawberryshakebug2\schema.graphql
C:\Projects\GitHub\strawberryshakebug2\schema.extensions.graphql
Begin SomeClient.
{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "location": "C:\\Projects\\GitHub\\strawberryshakebug2\\.graphqlrc.json",
  "extensions": {
    "strawberryShake": {
      "name": "SomeClient",
      "namespace": "strawberryshakebug2.Generated",
      "url": "https://workshop.chillicream.com/graphql/",
      "dependencyInjection": true,
      "strictSchemaValidation": true,
      "hashAlgorithm": "md5",
      "useSingleFile": true,
      "requestStrategy": "Default",
      "outputDirectoryName": "Generated",
      "noStore": false,
      "emitGeneratedCode": true,
      "razorComponents": false,
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}
Begin generate code.
{
  "ClientName": "SomeClient",
  "Namespace": "strawberryshakebug2.Generated",
  "StrictSchemaValidation": true,
  "NoStore": false,
  "InputRecords": false,
  "EntityRecords": false,
  "RazorComponents": false,
  "SingleCodeFile": true,
  "RequestStrategy": 0,
  "HashProvider": {
    "Name": "md5Hash",
    "Format": 1
  },
  "TransportProfiles": [
    {
      "Name": "Default",
      "Query": 0,
      "Mutation": 0,
      "Subscription": 1
    }
  ]
}
PersistedQueryLocation: 
Error: System.IO.FileNotFoundException
Kan bestand of assembly StrawberryShake.Resources, Version=12.6.0.0, Culture=neutral, PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
   bij StrawberryShake.CodeGeneration.CSharp.CSharpGenerator.Generate(IEnumerable`1 fileNames, CSharpGeneratorSettings settings)
   bij StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator.TryGenerateClient(ClientGeneratorContext context, CSharpGeneratorResult& result)
End generate code 00:00:00.0049990.
End 00:00:00.0049990.
```

```Kan bestand of assembly StrawberryShake.Resources, Version=12.6.0.0, Culture=neutral, PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.``` is Dutch for `can't find assembly .... or one of its dependencies`.

**Comment by michaelstaib** [comment]
This looks like there is an issue with different assembly versions. Ensure that everything is 12.7 and then restart your IDE.

**Comment by michaelstaib** [comment]
I checked it out and it works. I however had to clean up the project file.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <!-- https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/ -->
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.7.0-preview.24" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="12.7.0-preview.24" />
  </ItemGroup>

</Project>
```

**Comment by michaelstaib** [comment]
I will do another preview that will simplify the msbuild integration so that we no longer get these issues where visual studio puts in all those pesky item groups.

**Comment by jorrit** [comment]
The error is gone, but no files are generated. I now get this error when running `dotnet build -v:d` (after cleaning):

> CompilerServer: server failed - server rejected the request due to analyzer / generator issues 'analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.dll' has MVID 'e62a406f-2b13-4ebe-82fb-2df707f51d6b' but loaded assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' has MVID 'd5a3397a-e193-47f2-b8ba-724f38402fd3', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\Microsoft.CodeAnalysis.dll' has MVID '28bec010-898a-4306-a0a4-72af4672744e' but loaded assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' has MVID '89116d1f-6a31-47fe-8047-3b0212fff17d', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Collections.Immutable.dll' has MVID 'c3e60bed-3948-4527-bd6e-f698eb0b5b51' but loaded assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '5bf6037e-9c40-431d-a324-6ca50762eb0a', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Linq.Expressions.dll' has MVID '656221f2-24e3-46f8-8645-75303b78815b' but loaded assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '27b150c9-460a-4e3b-aab3-f2c2d3244701', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Linq.dll' has MVID 'ae6c9255-11ec-4c7f-a3cc-179890e4f18f' but loaded assembly 'System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '0076e8e6-ba77-4395-8bf8-05e51262bee6', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Memory.dll' has MVID '364de6aa-3638-4f0c-b478-eff7d6f86309' but loaded assembly 'System.Memory, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' has MVID '7b541888-8d0e-4eb3-abd6-cf10f1c18f1e', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Reflection.Metadata.dll' has MVID 'a28bbd25-b0f4-46c8-b5c4-929cc69d84ff' but loaded assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '0387e722-a0de-4915-aa46-3799f94de585', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Runtime.CompilerServices.Unsafe.dll' has MVID '523cab1e-d805-4300-a323-36a452cadd6c' but loaded assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID 'd3fc62e5-d006-4c73-841f-f5f279007e6d', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Runtime.Serialization.Primitives.dll' has MVID 'a47a8faf-c2a5-495a-8d2d-0dd301dab9c6' but loaded assembly 'System.Runtime.Serialization.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '00139e39-51ef-42cc-89db-6edea87bcbe0', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Text.Encoding.CodePages.dll' has MVID 'eabae3ba-ed10-4a96-85f6-bbc2d07c3649' but loaded assembly 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '5d9d7889-aa47-4331-a6ed-aac1afcfd0f3', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Text.RegularExpressions.dll' has MVID '0898b3c2-333d-4ffe-8c1e-681466a23ec8' but loaded assembly 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '8a7615fa-329e-4841-92d1-4cc08c2dc011', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Threading.dll' has MVID 'b0fc7487-a999-4b67-be0c-84a2b63adc68' but loaded assembly 'System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '4d67fa59-5f9f-4ae1-96bc-113ec321ef7f', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Xml.ReaderWriter.dll' has MVID '9079e164-7865-4d57-bab7-c2b90fa42e9d' but loaded assembly 'System.Xml.ReaderWriter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '95abd5b4-6f57-4a94-bfa8-02d2b1f49b3b', analyzer assembly 'C:\Users\Jorrit\.nuget\packages\strawberryshake.codegeneration.csharp.analyzers\12.7.0-preview.27\analyzers\dotnet\cs\System.Xml.XDocument.dll' has MVID '55a51808-c112-4eca-b0de-f23f2e9f10ea' but loaded assembly 'System.Xml.XDocument, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID 'b626731e-86f3-44ad-95c4-34502af33dc3'' - af415bda-db18-4b0f-98a5-279d358a8cff
```

Similar to #4430.

Also, at some point my .graphqlrc.json file is changed to just:

```json
{
  "projects": []
}
```

**Comment by michaelstaib** [comment]
I cannot the repro you posted works fine on Windows Visual Studio 2022, VScode macOS, and Rider macOS. Tested it in all environments.

**Comment by jorrit** [comment]
Thanks for taking a look. I also see that the dll contains the generated files. I used to check the `Generated` folder to see if files were generated. This was not the case, so I assumed the analyzer/generator did not work. Do you also see that the `Generated` folder remains empty?

**Comment by burhanriaz** [comment]
so where is final solution I didn't find ? 
Severity Code Description Project File Line Suppression State Error CS0102 The type 'CakeGqlClientServiceCollectionExtensions' already contains a definition for 'ClientServiceProvider' WpfBlazorGraphQl C:\Users\Burhan\Desktop\WpfBlazorGraphQl\WpfBlazorGraphQl\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\CakeGqlClient.StrawberryShake.cs 64 Active

**Comment by Kalyani1714** [comment]
I am getting the same issue. After changing the document path as suggested in this. I did not get any error but it is not created generated folder after building the project. I am using 12.15.0 version and vs2022

**Comment by michaelstaib** [comment]
Upgrade to the latest preview ... the package structure has changed so have a look at the following youtube video:
https://www.youtube.com/watch?v=-oq7YEciouM

**Comment by jfavrod** [comment]
I used to upgrade to the version 13 preview to work without the ambiguity errors, but I don't seem to be able to do that anymore. StrawberryShake.CodeGeneration.CSharp.Analyzers doesn't have a version 13 in NuGet. Did something change, or am I missing something?

**Comment by jfavrod** [comment]
> I used to upgrade to the version 13 preview to work without the ambiguity errors, but I don't seem to be able to do that anymore. StrawberryShake.CodeGeneration.CSharp.Analyzers doesn't have a version 13 in NuGet. Did something change, or am I missing something?

Okay, although it's not published on nuget.org, the version I can use is `13-preview.24`

**Comment by michaelstaib** [comment]
@jfavrod have you watched the video? `StrawberryShake.CodeGeneration.CSharp.Analyzers` is gone in 13. The setup is now different.

**Comment by jfavrod** [comment]
@michaelstaib , the project I'm working in was setup using v12.x.x. I just want to be able to make changes to the project, but that effort is confounded by the ambiguity errors. If version 13 is ready, we can look at making changes to deploy the app with 13, but seeing that 13 is still in preview we've been holding on that and still releasing version 12. I don't like the situation, and not sure what the best resolution is.

**Comment by RamziHamouda** [comment]
> @jfavrod have you watched the video? `StrawberryShake.CodeGeneration.CSharp.Analyzers` is gone in 13. The setup is now different.

@michaelstaib thanks for the clarification, the documentation at the moment states that a generated folder is still expected, that's why I got the confusion.
https://chillicream.com/docs/strawberryshake/v13/get-started/console

**Comment by raysuelzer** [comment]
What about those of us not using Blazor? I'm not understanding exactly where the typings end up.
