### ISSUE TITLE
Evaluate if hotchocolate can be used in a federated solution of Apollo Gateway

### ISSUE THREAD

**Issue by timonmasberg** [ChilliCream/hotchocolate#4449]
### Is your feature request related to a problem?

Currently, hotchocolate is not listed in the list of supported libraries for Apollo federation. It can be evaluated here: https://github.com/apollographql/apollo-federation-subgraph-compatibility

### The solution you'd like

Clarify how hotchocolate can be used with Apollo Federation as a subgraph and also show how hotchocolate can act as a replacement for Apollo Gateway with Apollo Servers with subgraph schemas.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We do have our own solution for schema federation and schema stitching and do not intend to support Apollo Federation as a subgraph. 

We however are exploring for the next Hot Chocolate Gateway version to support graphql servers that support Apollo federation.

In general, our approach works out of the box with any GraphQL server and gives more flexibility with hot reload capabilities, subscription stitching support for defer and stream while stitching and more complex query plans.
