### ISSUE TITLE
Option to only execute the selected text in the Banana Cake Pop query window

### ISSUE THREAD

**Issue by Kricke242** [ChilliCream/hotchocolate#4455]
### Is your feature request related to a problem?

Sometimes I just want to execute a part of the text in the editor. Now, I have to comment # away the lines I don't want to execute (alternatively cut them out), then execute the query and finally uncomment the lines back again (or paste them back) so they are saved when I close the editor.

### The solution you'd like

It would be cool if we could just select the text we want to execute, press the run button, and it only executes that selected text.  An example would be the SSMS query editor, where it only executes the selected SQL.
Perhaps also a keyboard shortcut to comment or uncomment all selected lines. :-)

In this example it would only execute the selected query in the middle.
![bild](https://user-images.githubusercontent.com/15107600/142624652-bbb6ce38-9028-474e-ae86-c93bdd9b1f59.png)

### Product

Banana Cake Pop

**Comment by tobias-tengler** [comment]
If you name your different queries, i.e.

```graphql
query MyQuery1 {
    ...
}
```

You can click on the Execute text above the query to execute only this query. :)

**Comment by Kricke242** [comment]
Thanks @tobias-tengler, that works. I missed that button, sorry. I will close this.
