### ISSUE TITLE
Simple example has no Operations showing

### ISSUE THREAD

**Issue by jkears** [ChilliCream/hotchocolate#4459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a default Web API in .Net 6 and installed verson 12.3.0 and created a simple book type with simple query to add book but when I run and look at Banana  Cake Pop I see the schema definition but no Operations.  I also tried this in a EF Core application with similar results.

### Steps to reproduce

Here is the Program startup 

```
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddGraphQLServer().AddQueryType<Query>();

var app = builder.Build();


app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL("/");
});

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

Here is the book class...

```
 public class Book
    {
        public string Title { get; set; }
        public string Author { get; set; }
    }
```

Here is the Query class ...

```
 public class Query
    {

        public Book GetBook() => new Book { Title = "tt", Author = "aaa" };

    }
```

Here is the Operations view...
![image](https://user-images.githubusercontent.com/1290937/142674340-4e77775a-d325-4e77-960f-69b19bec88bf.png)

Here is the  Schema reference view ...
![image](https://user-images.githubusercontent.com/1290937/142674391-76746ebb-06fb-4a8f-ae22-118316d21569.png)

and here is the Schema definition view ...

![image](https://user-images.githubusercontent.com/1290937/142674424-8b78eef7-bcbf-4409-9942-4eb70b5df3e1.png)

I was expecting to see the GetBook operation in the Operations view.  

What am I missing?

### Product

Hot Chocolate

### Version

12.3.0

**Comment by tobias-tengler** [comment]
You need to write the query yourself, for example

```graphql
{
  book {
    title
  }
}
```

If you are looking for a query builder feature, it is already on our list of things for a future release of BCP. :)

**Comment by jkears** [comment]
Ha, I was just discovering that. Thank you so much.
