### ISSUE TITLE
Banana Cake Pop unresponsive

### ISSUE THREAD

**Issue by shoooe** [ChilliCream/hotchocolate#4464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Quite reliably Banana Cake Pop stops working. After a couple of queries it becomes unresponsive. No console errors are shown, no network calls are performed when clicking "Run". Hard refreshing doesn't solve the issue. 

### Steps to reproduce

1. Run Banana Cake Pop on a .NET 6.0 project. 
2. Run a couple of queries / mutations
3. Notice the unresponsiveness after a while

### Product

Banana Cake Pop

### Version

12.0.1

**Comment by tobias-tengler** [comment]
From the version 12.0.1 I'm assuming you are using the Hot Chocolate middleware. Could you try updating to the latest version  or using the [standalone app](bananacakepop.com) and verifying whether the described issue still exists there?

**Comment by michaelstaib** [comment]
Or, use the cloud .... https://eat.bananacakepop.com
