### ISSUE TITLE
Change to default authorization behaviour

### ISSUE THREAD

**Issue by kolpav** [ChilliCream/hotchocolate#4465]
### Is your feature request related to a problem?

HC makes it really easy for people used working with asp .net identity to implement auth as it doesn't introduce almost no new concepts maybe just accessing `IResolverContext` within an `AuthorizationHandler` and thats it.

But it changes one of the fundamental concepts of .net authorization **requiring authenticated user for all policies**.

This is not how asp .net authorization works based on my testing and existence of [this test](https://github.com/dotnet/aspnetcore/blob/64c37113aafcbad73113b7cb86f86129e8839963/src/Security/Authorization/test/PolicyEvaluatorTests.cs#L76-L90)

```cs
    [Fact]
    public async Task AuthorizeSucceedsEvenIfAuthenticationFails()
    {
        // Arrange
        var evaluator = BuildEvaluator();
        var context = new DefaultHttpContext();
        var policy = new AuthorizationPolicyBuilder().RequireAssertion(_ => true).Build();

        // Act
        var result = await evaluator.AuthorizeAsync(policy, AuthenticateResult.Fail("Nooo"), context, resource: null);

        // Assert
        Assert.True(result.Succeeded);
        Assert.False(result.Challenged);
        Assert.False(result.Forbidden);
    }
```

I think checking policies even for unauthenticated user is less surprising behavior because that is how authors of asp authorization decided to implement policies and HC should just provide thin layer on top of their code.

**Where I might be wrong**

I am no expert in this area I am just making my best guess I might be completely wrong.

[In docs](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-6.0) it says

> Authorization is orthogonal and independent from authentication. However, **authorization requires an authentication mechanism**. Authentication is the process of ascertaining who a user is. Authentication may create one or more identities for the current user.

It might be interpreted that authorization requires authenticated user but they chose word mechanism. I think reason for that is you wouldn't be able to write authorization for specific user but nothing forbids you from creating policy for no user in particular.

### The solution you'd like

I am not sure how many ways are to achieve this but maybe removing `AuthorizeResult.NotAuthenticated` and have just `Allowed` and `NotAllowed` and leave it up to policies to decide if user allowed or not something like [DenyAnonymousAuthorizationRequirement](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Security/Authorization/Core/src/DenyAnonymousAuthorizationRequirement.cs)

_I know you are free to swap default handler with your own btw._

### Product

Hot Chocolate

**Comment by kolpav** [comment]
I wanted to create PR for my proposal but I think I will be unable to. I am still very new to how all of asp and hc auth works in depth. I might keep trying if this is accepted and nobody wants to work on it but I will need help when I am stuck.

Here are questions I have after digging through code:

- Why `IsInAnyRole` returns true if roles are empty or null?
https://github.com/ChilliCream/hotchocolate/blob/6077e82a97780a3fa232dcb6f23900f43eaa9578/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/DefaultAuthorizationHandler.cs#L75-L82
- Shouldn't the `roles == null || roles.Count == 0` check be either in `IsInAnyRole` or `NeedsPolicyValidation` but not both?
- Why are policies checked only if principal is in any role?
https://github.com/ChilliCream/hotchocolate/blob/6077e82a97780a3fa232dcb6f23900f43eaa9578/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/DefaultAuthorizationHandler.cs#L37-L47
- What is the significance of whitespace policy? 
https://github.com/ChilliCream/hotchocolate/blob/6077e82a97780a3fa232dcb6f23900f43eaa9578/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/DefaultAuthorizationHandler.cs#L124-L125

**Comment by michaelstaib** [comment]
> Why IsInAnyRole returns true if roles are empty or null?

roles are kind of how you did auth before.... if roles is not sed we do not require roles auth.

**Comment by kolpav** [comment]
Closing as I am not sure if what I am proposing is good idea anymore.
