### ISSUE TITLE
HotChocolate GraphQl UnitTest "IBatchDispatcher" error...

### ISSUE THREAD

**Issue by MuctebaTayfur** [ChilliCream/hotchocolate#4466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 class AggregatorUnitTests
    {
             [Test]
        [UseReporter(typeof(DiffReporter))]

        public async Task setup()
        {        
            IServiceProvider serviceProvider = new ServiceCollection()     
            .BuildServiceProvider();

            HotChocolate.ISchema schema = SchemaBuilder.New()
            .AddQueryType<QueryType>()
            .Create();

            IReadOnlyQueryRequest request =
            QueryRequestBuilder.New()          
            .SetQuery("query querytype{hello}")
            .SetServices(serviceProvider)                         
            .Create();

            IExecutionResult result = await schema.MakeExecutable().ExecuteAsync(request);
            var resultJson = result.ToJson();
            resultJson.MatchSnapshot();
        }
    }
 
    public class QueryType : ObjectType
    {
        [Obsolete]
        
        protected override void Configure(IObjectTypeDescriptor descriptor)
        {           
       
            descriptor
                .Field("hello").Resolve("world");
        }
 
 }
// I take an error from snapshot:
{
  "errors": [
    {
      "message": "Make sure that you have registered an IBatchDispatcher with your scoped request services."
    }
  ]
}
//What should ı do?

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12

**Comment by PascalSenn** [comment]
Can you use the new API?
```

var response = 
    await new ServiceCollection()
        .AddGraphQL()
        ....
        .ExecuteRequestAsync();

response.ToJson().MatchSnapshot()
```

**Comment by michaelstaib** [comment]
Closing this since its  answered.
