### ISSUE TITLE
Stitching The current user is not authorized to access this resource. in Gateway Fail, run direct microservice works

### ISSUE THREAD

**Issue by ZephiroRB** [ChilliCream/hotchocolate#4469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a gateway with a microservice auth.graphql 

When I run a query that requires Authorize from the Gateway return "code": "AUTH_NOT_AUTHENTICATED"
When I run it directly in the microservice if it works

Gateway Config
`
var builder = WebApplication.CreateBuilder(args);

var Auth = "auth";

builder.Services.Configure<TokenSettings>(builder.Configuration.GetSection("TokenSettings"));

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidIssuer = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Issuer"),
        ValidateIssuer = true,
        ValidAudience = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Audience"),
        ValidateAudience = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration.GetSection("TokenSettings").GetValue<string>("Key"))),
        ValidateIssuerSigningKey = true
    };
});

builder.Services.AddHttpClient(Auth, c => c.BaseAddress = new Uri("https://localhost:7132/graphql"));

builder.Services.AddAuthorization();
builder.Services.AddGraphQLServer()
    .AddRemoteSchema(Auth);

var app = builder.Build();

app.UseAuthentication();
app.UseAuthorization();

app.MapGraphQL();

app.Run();
`

Auth.Graphql

`
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AuthContext>();
builder.Services.Configure<TokenSettings>(builder.Configuration.GetSection("TokenSettings"));

//builder.Services.AddSingleton<ICountryService, CountryService>();
builder.Services.AddTransient<IMemberService, MemberService>();
builder.Services.AddTransient<ICountryService, CountryService>();
builder.Services.AddScoped(typeof(IRepository<>), typeof(BaseRepository<>));
builder.Services.AddTransient<IUnitOfWork, UnitOfWork>();

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidIssuer = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Issuer"),
        ValidateIssuer = true,
        ValidAudience = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Audience"),
        ValidateAudience = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration.GetSection("TokenSettings").GetValue<string>("Key"))),
        ValidateIssuerSigningKey = true
    };
});

builder.Services.AddAuthorization();
builder.Services
    .AddGraphQLServer()
    .AddConvention<IFilterConvention>(new FilterConvention(x =>
        x.AddDefaults()))
    .AddConvention<IFilterConvention>(new FilterConventionExtension(descriptor =>
    {
        descriptor.ArgumentName("filter");
    }))
    .AddQueryType<Global>()
    .AddMutationType()
        .AddTypeExtension<CreateMemberMutation>()
        .AddTypeExtension<LoginMemberMutation>()
        .AddTypeExtension<CreateCompanyMutation>()
        .AddTypeExtension<CreateProjectMutation>()
        .AddTypeExtension<CreateUserMutation>()
        .AddTypeExtension<UpdateProfileMutation>()
        .AddTypeExtension<UpdatePasswordMutation>()
        .AddTypeExtension<ActiveMemberMutation>()
    .ConfigureResolverCompiler(c => c.AddService<AuthContext>())
    .AddFiltering()
    .AddSorting()
    .AddProjections()
    .AddAuthorization();

builder.Services.AddCors(option => {
    option.AddPolicy("allowedOrigin",
        builder => builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()
        );
});

var app = builder.Build();

app.UseCors("allowedOrigin");
app.UseAuthentication();
app.UseAuthentication();

app.Use(async (context, next) =>
{
    var user = context.User;
    Console.WriteLine("--------------------------------------");
    Console.WriteLine(user);
    Console.WriteLine("--------------------------------------");
    // Call the next delegate/middleware in the pipeline
    await next();
});

app.MapGraphQL();

await app.RunAsync();

`

### Steps to reproduce

1. I use .NET6
2. Create Project Gateway with JWT and authorization and add microservice Auth.GraphQL
3. Create Project Auth.GraphQL  with JWT and authorization and create Query with Autorize
4. Directly from auth.graphql if you recognize the authorization headers 
5. Directamente desde Gateway no reconoce los headers de Authorization same Query auth.graphql with Autorize

### Relevant log output

```shell
"errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED",
        "remote": {
          "message": "The current user is not authorized to access this resource.",
          "locations": [
            {
              "line": 1,
              "column": 15
            }
          ],
          "path": [
            "me"
          ],
          "extensions": {
            "code": "AUTH_NOT_AUTHENTICATED"
          }
        },
        "schemaName": "auth"
      }
    }
  ]
}
```

### Product

Hot Chocolate

### Version

12.3.0

**Comment by michaelstaib** [comment]
Please put questions to slack.chillicream.com. In order to have authentication between the gateway and the downstream services you need to configure this through the HttpClientFactory. This is standard ASP.NET core stuff.

**Comment by hnazari13701371** [comment]
Hi can u describe how to configure this using HttpClientFactory?
