### ISSUE TITLE
Strawberry Shake - empty result with error, results in error with "Value cannot be null"

### ISSUE THREAD

**Issue by MarcelMalik** [ChilliCream/hotchocolate#4477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Banana Cake Pop I get the following response:
![Screenshot01](https://user-images.githubusercontent.com/2485844/143294545-0e9b96ef-378f-411c-9673-5c492a261184.png)
And this looks fine to me.

But in Strawberry Shake I get a client error with “Value cannot be null” and in the Extensions is the GraphQL error:
![Screenshot02](https://user-images.githubusercontent.com/2485844/143294646-604e6d32-025a-49fd-9eab-04682b1bd81a.png)

### Steps to reproduce

1. Consume a empty GraphQL response with raised GraphQLException.

### Product

Strawberry Shake

### Version

12.3.2

**Comment by PascalSenn** [comment]
This is resolved in 12.5
