### ISSUE TITLE
strawberry shake failes to generate code for lower case type names..

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#4478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

strawberry shake failes to generate code for lower case type names..

at least for input type variables..

the first example works, the 2nd one does not

```
query MyTestInv($where: MyTestInvFilterInput){
  MyTestInv (where: $where){
    nodes{
      TestProp
    }
  }
}
```

```
query myTestInv2($where: myTestInv2FilterInput){
  myTestInv2 (where: $where){
    nodes{
      TestProp
    }
  }
}
```

the error in visual studio says

Error	SS0006	Sequence contains no matching element	

### Steps to reproduce

the schema looks something like this

```
type Query {
  myTestInv2(
    lastId: String
    pageSize: Int
    listPagination: [PaginationInput]
    validityDate: DateTime
    allValidityPeriods: Boolean
    first: Int
    after: String
    last: Int
    before: String
    where: myTestInv2FilterInput
    order: [myTestInv2SortInput!]
  ): myTestInv2Connection
}

type myTestInv2Connection {
  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!

  """
  A list of edges.
  """
  edges: [myTestInv2Edge!]

  """
  A flattened list of the nodes.
  """
  nodes: [myTestInv2]
}


type myTestInv2 implements Node {
  id: ID!
  _revision: Int!
  _inventoryItemId: String
  _displayValue: String
  _propertyPermissions: [FilteredPermission]
  TestProp: String
}
```

### Product

Strawberry Shake

### Version

12.3.2

**Comment by PascalSenn** [comment]
@MariaCobretti  i tried to reproduce this error but i cannot.
can you share the whole schema and query?

**Comment by MariaCobretti** [comment]
sorry for the late response.. here is my complete schema
[schema.txt](https://github.com/ChilliCream/hotchocolate/files/7703519/schema.txt)
 
and here is the query
[query.txt](https://github.com/ChilliCream/hotchocolate/files/7703524/query.txt)

the issue is with the type "bwr_TimeSeriesFilterInput"

**Comment by PascalSenn** [comment]
I added a test based on you schema and fixed the bug:
https://github.com/ChilliCream/hotchocolate/blob/bf55513146df5b4feaf1db5d118815df3f230be6/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/__resources__/UnderlinedFieldsInSchema.graphql
