### ISSUE TITLE
Banana Cake Pop virus warning

### ISSUE THREAD

**Issue by czmirek** [ChilliCream/hotchocolate#4479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Downloaded the Banana Cake Pop for Windows 10, executed it and the following error box appeared. I've never seen this before in my life.

![image](https://user-images.githubusercontent.com/18615545/143552652-1a45dd2f-9e9b-4400-82e8-ab63e5210f91.png)

### Steps to reproduce

1. Download latest Banana Cake Pop installer
2. Run it

### Additional Context?

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

### Product

Banana Cake Pop

### Version

latest on the website

**Comment by czmirek** [comment]
Wrong project

**Comment by czmirek** [comment]
I did not find a Banana Cake Pop project so I assume it belongs here.

**Comment by tburi** [comment]
For me defender removed it after dowload, the log says `Detected: Trojan:Win32/Bulta!rfn` downloaded file was BananaCakePop-1.0.0-preview.18-win-x64.exe
