### ISSUE TITLE
fields that start with an underscore are always returned null in strawberry shake despite an alias

### ISSUE THREAD

**Issue by MariaCobretti** [ChilliCream/hotchocolate#4480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when the server schema has fields that start with an underscore.. those are always returned null
even if you use an alias -> the fields get generated correctly without the underscore but the value is still null

### Steps to reproduce

1. have a simple schema where a property starts with an underscore
2. use an alias in strawberry

query MyItems {
  itemId: _itemId
}

### Product

Strawberry Shake

### Version

12.3.2

**Comment by PascalSenn** [comment]
@MariaCobretti  i could not reproduce this issue:
https://github.com/ChilliCream/hotchocolate/pull/4492

**Comment by MariaCobretti** [comment]
this is fine.. my gateway was acting up
