### ISSUE TITLE
Offer to use FIPS compliant hashing algorithms

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4488]
### Is your feature request related to a problem?

Hot Chocolate uses MD5 hashing to for example determine the document hash. The problem is that MD5 is not FIPS compliant.  So if Hot Chocolate is being run on a device that is in [FIPS](https://www.nist.gov/standardsgov/compliance-faqs-federal-information-processing-standards-fips) compliance mode, every time a hash for a document needs to be computed an error will be thrown. This is caused by [.NET Core passing cryptographic primitives calls through to the standard modules of the OS](https://docs.microsoft.com/en-us/dotnet/standard/security/fips-compliance).

In the current state (US) government agencies as well as probably others are unable to use Hot Chocolate.

A user just reported this in the Slack channel [here](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1638029622128400).

### The solution you'd like

First we should evaluate where cryptographic calls are being used and whether it is feasible to swap them out for FIPS compliant alternatives. Maybe we could offer a setting to use FIPS compliant algorithms, if it isn't feasible to swap out MD5 for performance reasons for example.

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
If I remember correctly a user should be able to take out the document hashing library. If this is the only case where MD5 is being used in the hot request path, we could maybe also just document how to do so in a first step.

**Comment by PascalSenn** [comment]
@tobias-tengler  is Sha256 FIPS compliant? 
Because then you can just do `AddSha256DocumentHashProvider` on the service collection :)

**Comment by PascalSenn** [comment]
And if you want to do a completely custom implementation: IDocumentHashProvider :)

**Comment by tobias-tengler** [comment]
Perfect, thank you @PascalSenn :)
I've replied to the user with this issue on Slack, so hopefully this resolves his issues :) I also will add a note about this to the documentation.
Closing this for now.

**Comment by tobias-tengler** [comment]
This is now documented [here](https://chillicream.com/docs/hotchocolate/security/#fips-compliance).
