### ISSUE TITLE
Align state attributes and context methods

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4494]
### Is your feature request related to a problem?

If you want to access local state in your resolver you have two options:

1
```csharp
public string Resolver1([LocalState] string key) => ...
```

2
```csharp
public string Resolver1(IResolverContext context)
{
    var value = context.GetLocalValue<string>("key");
}
```

The first thing that bothers me is the different terminology. LocalState vs LocalValue - we should only use one.
The second thing is that they behave differently. The attribute throws an exception if it can't find the key and the context method returns the default value.

This is not cohesive and affects all of the state related APIs.

### The solution you'd like

I propose marking the `GetXValue` methods as obselete and introducing two new methods per state variant, i.e.:

```csharp
var value = context.GetLocalState<string>("key"); // throws if key does not exist
var value = context.GetLocalStateOrDefault<string>("key"); // returns the default if key does not exist
```

The main benefits are:
1. The `OrDefault` makes the intent clear and should feel familiar to C# developers (LINQ).
2. `[LocalState]` and `GetLocalState` behave exactly the same.
3. There's probably a lot of code just checking if what `GetLocalValue` returns is default and then throwing. This would take this responsibility from the user.

To be consistent `SetXValue` should probably also be deprecated in favor of `SetXState`.

There's probably not too much code in user land using these context APIs and even if it's a simple rename from `GetXValue` to `GetXStateOrDefault`. Same goes for the Hot Chocolate code base - a simple global rename should probably suffice.

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
It should probably also be called `SetGlobalState` on the `IQueryRequestBuilder` instead of `SetProperty`.

**Comment by tobias-tengler** [comment]
Also is there a use case for `SetGlobalState` on the IResolverContext? To me it seems like it's never a good idea to set global state from a field / middleware.

**Comment by PascalSenn** [comment]
to add to the mix:
```csharp
public string Resolver1([SetScopedState("key")] SetState setKey) => ...
```

**Comment by tobias-tengler** [comment]
@PascalSenn when would this be useful? If you want to add a resolver argument to the state? I think this is a relatively uncommon case, so sticking with injecting `IResolverContext` and calling `context.SetScopedState` should suffice IMO.

**Comment by PascalSenn** [comment]
```csharp
public async Task<Customer> GetCustomerByIdAsync(
     [Service] CustomerService serivce,
     IResolverContext context,
     Guid customerId, 
     CancellationToken ct)
{
     var customer = await serivce.GetByIdAsync(customerId, ct);    
     context.ScopedContextData = context.ScopedContextData.Set("customer", cutomer);
     return customer;
}
```
vs
```csharp
public async Task<Customer> GetCustomerByIdAsync(
     [Service] CustomerService serivce,
     [SetScopedState("customer")] SetState setCustomer, 
     Guid customerId, 
     CancellationToken ct)
{
     var customer = await serivce.GetByIdAsync(customerId, ct);    
     setCustomer(cutomer);
     return customer;
}
```

The second one has a few benefits:
    - The user cannot make the mistake to call the scoped context data without reassigning the value (tbh. same thing with SetScopeState) 
     - The intend is a lot clearer. You do not have to have access to the whole resolver context just to set the scoped context. Firing with a tank on a bird
     - The second one would maybe allow for a few execution engine optimizations, as the engine knows that this resolver "just" uses the Scoped state (it also uses a service, which make optimization a lot harder

**Comment by tobias-tengler** [comment]
Ah I misunderstood the intent. I'm not against it now that you've laid out the benefits. It's definitely something that wouldn't come naturally to me as a user, but I think it could also have a real benefit.

**Comment by tobias-tengler** [comment]
I'm not that happy with the name yet. `SetScopedState` sounds like it's setting something immediately, but in reality we are retrieving a setter (if I understand you correctly). I also don't like that it is not typed.

For me it would be more like:

```csharp
[ScopedStateSetter("customer")] StateSetter<Customer> setCustomer
```

Not yet sure how that would translate to an implementation though 😅

**Comment by michaelstaib** [comment]
Just looked at this.

I agree with changing the name to GetXState and so on ... being consistent here will help with new users. We should mark the old ones obsolete. But we should keep the old ones around for at least another 3 major versions. It does not cost anything to have them but will upset a lot of users if we remove them.

Further, we have `GetOrAddXValue` which is also quite useful.

Looking through the sources I also found `RemoveGlobalValue` which we can mark obsolete without replacement.

In general we will keep the name ContextData = GlobalState, ScopedContextData = ScopedState, LocalContextData = LocalState for the dictionaries. In my opinion the cost of also renaming the dictionaries is to high.

I can do a PR tomorrow on this if we all agree.

**Comment by tobias-tengler** [comment]
I agree with not renaming the dictionaries and also keeping the old methods around for a while. :)
If @PascalSenn also agrees I think we can get started on this 🚀

**Comment by tobias-tengler** [comment]
I might be wrong in this assumption, but isn't the ContextData on IRequestContext just the GlobalState of the request? Same for the properties on the IQueryRequestBuilder.

I think there are also too many terms here.
I think we should add Get/SetGlobalState extension methods to the IRequestContext to interact with the ContextData.
I would also like to make AddProperty on the IQueryRequestBuilder obsolete and replace it with SetGlobalState.

I think this will make the whole API more cohesive for users, given my assumption of all of this just being global state is correct of course...
