### ISSUE TITLE
AddedOperationToCache method is not getting called in DiagnosticEventListener

### ISSUE THREAD

**Issue by Gaurav-Puri101187** [ChilliCream/hotchocolate#4500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a DiagnosticEventListener
```
[ExcludeFromCodeCoverage]
    public class GraphQLAPMLogger : DiagnosticEventListener
    {
        [DiagnosticName("HotChocolate.Execution.Query.Start")]
        public override void AddedOperationToCache(IRequestContext context)
        {
            LogOperationName(context);

            base.AddedOperationToCache(context);
        }

        [DiagnosticName("HotChocolate.Execution.Query.Start")]
        public override void RetrievedOperationFromCache(IRequestContext context)
        {
            LogOperationName(context);

            base.AddedOperationToCache(context);
        }
```
It was working before with HC upgrade to 11.2.2 it Above methods suddenly stop getting called.

### Steps to reproduce

1. Create a DiagnosticEventListener with AddedOperationToCache overriden
2. Make a call to GQL server above method won't be called.

### Product

Hot Chocolate

### Version

11.2.2

**Comment by tobias-tengler** [comment]
This should be working in v12. Please try the latest version and re-open the issue, if the problem persists.
