### ISSUE TITLE
Type of property ignored by ExtendObjectType.IgnoreProperties is still tried to be inferred

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think the cause of the issue is the same as #1447, but it also points to an issue with the ExtendObjectType as well.
It seems like Hot Chocolate tries to infer the type of a property, even if it was ignored by a Type Extension and you can end up with an error if the type of this property can't be inferred.

So this issue is less about the `Unable to create instance of type ``.` I get that is talked about in the other issue and more about how the property seems to not really be ignored.

### Steps to reproduce

1. Have a model with an interface property

```csharp
public class Test
{
    public string Prop1{ get; set; }

    public ITest Prop2{ get; set; }
}
```

2. The interface has a generic method that returns the same type (I could not get it to reproduce otherwise)

```csharp
public interface ITest
{
    ITest SomethingGeneric<TValue>(TValue value);

    public string Prop3{ get; set; }
}
```

3. Have a type extension that ignores the property with the interface return type (and yes I've made sure it's registered)

```csharp
[ExtendObjectType(typeof(Test), IgnoreProperties = new[] { nameof(Test.Prop2) })]
public class TestExtensions
{
}
```

### Product

Hot Chocolate

### Version

12.4.0-preview.12

**Comment by michaelstaib** [comment]
The issue here is the initialization process... the ignore in this case is more of a remove :)
