### ISSUE TITLE
Cannot Query nested relations

### ISSUE THREAD

**Issue by HurricanKai** [ChilliCream/hotchocolate#4514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the Neo4J integration I cannot query nested relations (like `(:A)->(:B)->(:C)`) instead, an InvalidOperationException is thrown in HotChocolate.Data.Neo4J.Projections.Neo4JProjectionVisitorContextExtensions.TryCreateRelationshipProjection due to the stack being empty.

### Steps to reproduce

1. Create 3 Neo4J object types in a structure like `(:A)->(:B)->(:C)`
2. Try to run a graphql query like `query { a { b { c { someprop } } } }`
3. View the exception

### Relevant log output

```shell
Unexpected Execution Error System.InvalidOperationException: Stack empty.    at Sy
stem.Collections.Generic.Stack`1.ThrowForEmptyStack()    at System.Collections.Generic.Stack`1.Peek()    at HotChocolate.Data.Neo4J.Projections.Neo4JProjectionVisitorContextExtensions.TryCreateRelationshipProjection(Neo4JProjectionVisitor
Context context, PatternComprehension& patternComprehension)    at HotChocolate.Data.Neo4J.Projections.Neo4JProjectionFieldHandler.TryHandleLeave(Neo4JProjectionVisitorContext context, ISelection selection, ISelectionVisitorAction& action
)    at HotChocolate.Data.Projections.ProjectionVisitor`1.Leave(ISelection selection, TContext context)    at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(ISelection selection, TContext context)    at HotChocolate.Data.Projectio
ns.ProjectionVisitor`1.Visit(ISelection selection, TContext context)    at HotChocolate.Data.Projections.SelectionVisitor`1.VisitObjectType(IOutputField field, ObjectType objectType, SelectionSetNode selectionSet, TContext context)    at
HotChocolate.Data.Projections.SelectionVisitor`1.VisitChildren(IOutputField field, TContext context)    at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(IOutputField field, TContext context)    at HotChocolate.Data.Projections.Pr
ojectionVisitor`1.Visit(IOutputField field, TContext context)    at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(TContext context)    at HotChocolate.Data.Neo4J.Projections.Neo4JProjectionProvider.<CreateExecutor>g__ExecuteAsyn
c|2_1[TEntityType](FieldDelegate next, IMiddlewareContext context)    at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext() --- End of stack trace from previous loca
tion ---    at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext() --- End of stack trace from previous location ---    at HotChocolate.Execution.Processing.Tasks.Res
olverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)    at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Product

Hot Chocolate

### Version

12.3.2
12.4.0-preview14

**Comment by HurricanKai** [comment]
I'd look whether I can fix this, if that is something doable for someone that has never touched the codebase before?

**Comment by michaelstaib** [comment]
Are you on slack.chillicream.com? we will do meeting on Neo4J next week.

**Comment by michaelstaib** [comment]
There is a channel #neo4j.

**Comment by HurricanKai** [comment]
Thank you, I'm on there, will join the meeting :smile:

**Comment by HurricanKai** [comment]
I think this is also related to Paging + Projections not working together. Seems like in the case of paging `nodes` is also `ConnectionType` which isn't handled properly (?) and then ends up terminating the ProjectionVisitor because no `CombinedEdgeField` selection has been made. Not 100% sure but that's what I've gathered from stabbing around the codebase.
Not really understanding what `CombinedEdgeField` is and why it's ever expected to occur in a Neo4J environment, seems like on IQueryable ever actually generates it right now.
I'm guessing Neo4J should somewhere create `CombinedEdgeField` selections from cases like
```
outer
{
    field
}
```
instead of keeping them as just `outer`
