### ISSUE TITLE
Input Object Type argument created by Input helper is nullable

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would've assumed that the input argument created by the [Input] helper would be non-null, but it is nullable.

### Steps to reproduce

```csharp
[Input]
public string MyResolver(string arg1, object? arg2) ...
```

I also know that the [Input] is soon to be replaced, but I think it will affect the new MutationConvention attribute as well at the moment.

### Product

Hot Chocolate

### Version

12.4.0-preview.12

**Comment by michaelstaib** [comment]
This one is fixed now.
