### ISSUE TITLE
Generate Field Names

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#452]
So right now if you have a method that starts with Get it removes the word get for the generated field name

is there some rule in graphql spec that says methods may not start with the word get? 

Can we have an option to turn that off?

Also since we are making changes to the names

I would like if I have a method like

GetUsersAsync

can it remove the word async in the generated type?

**Comment by michaelstaib** [comment]
> can it remove the word async in the generated type?
preview.25 does remove Async.

**Comment by drowhunter** [comment]
cool when will that be released?

and what of the opting out of the Get prefix removal?

**Comment by michaelstaib** [comment]
In GraphQL we are talking about fields and mostly do not have verbs like in .net methods. This is not enforced by the spec and you could basically name it like you want. You can overwrite the naming rules with `Name`. 

But at the moment there is no option to customize this rule. We will introduce something like that with the new schema builder in Version 0.8.0. The idea is that you could replace the default rules or extend them.

**Comment by michaelstaib** [comment]
> cool when will that be released?

With the DataLoaders ... probably on the 10.01. 

At least we are aiming for that.
