### ISSUE TITLE
IdField property not working in Node data-annotation

### ISSUE THREAD

**Issue by jllano10** [ChilliCream/hotchocolate#4521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A specific property is not recognized as the ID while trying to implement the Node interface using the IdField in the data-annotation.
Background: I'm trying to use the query: node(id: "HashedSerial")  in a model that doesn't have a property call `Id` nor `ExampleModelId`
```
    [ExtendObjectType(typeof(ExampleModel))]
    [Node(IdField = nameof(ExampleModel.Serial))]
    public class ExampleModelNode
    {
        [NodeResolver]
        [BindMember(nameof(ExampleModel.Serial))]
        public async Task<ExampleModel?> GetExampleModelBySerialAsync(
            long serial,
            ExampleModelBySerialDataLoader exampleModelBySerial,
            CancellationToken cancellationToken)
            => await exampleModelBySerial.LoadAsync(serial, cancellationToken);
```
The application compiles but in execution time it throws the following error in the output console:
```
The specified id field Serial does not exist on ...ExampleModelNode.
```
It seems that is trying to find the Serial property in the `ExampleModelNode` class and not in the `ExampleModel` class.
I tried to add this property and bind it to the model but it doesn't work too:
```
    [ExtendObjectType(typeof(ExampleModel))]
    [Node(IdField = nameof(ExampleModel.Serial))]
    public class ExampleModelNode
    {
        //[BindMember(nameof(ExampleModel.Serial))] with this it doesn't work too
        public string? Serial { get; set; }
        
        [NodeResolver]
        [BindMember(nameof(ExampleModel.Serial))]
        public async Task<ExampleModel?> GetExampleModelBySerialAsync(
            long serial,
            ExampleModelBySerialDataLoader exampleModelBySerial,
            CancellationToken cancellationToken)
            => await exampleModelBySerial.LoadAsync(serial, cancellationToken);
```
The error is not appearing anymore in the console but the query result always have the Serial with value zero.

After one [comment](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1638531636333400?thread_ts=1638531493.333100&cid=CD9TNKT8T) in the slack channel, I also tried to create a property call `Id` inside the `ExampleModelNode` class:
```
    [ExtendObjectType(typeof(ExampleModel))]
    [Node(IdField = nameof(ExampleModelNode.Id))] 
    public class ExampleModelNode
    {
        [BindMember(nameof(ExampleModel.Serial))] 
        public string? Id { get; set; } // Also tried:  public long Id { get; set; }
        
        [NodeResolver]
        [BindMember(nameof(ExampleModel.Serial))] // Also tried with/without this data annotation
        public async Task<ExampleModel?> GetExampleModelBySerialAsync(
            long serial,
            ExampleModelBySerialDataLoader exampleModelBySerial,
            CancellationToken cancellationToken)
            => await exampleModelBySerial.LoadAsync(serial, cancellationToken);
```
I'm getting the same result as before.

It is possible that the `IdField` or `BindMember` annotation are not working as expected?

### Steps to reproduce

1. Create a model with a property called Serial.
2. Create the Node for this model in any of the ways I described before. 
3. Create the Resolver in any of the ways I described before.   
4. Verify that you get the explained behavior for each scenario.

**Query to run**
```
query  {
  exampleModelBySerial(serial: 1) {
    serial
    id
 }
}
```
**Expected Result**
```
{
  "data": {
    "exampleModelBySerial": {
      "serial": 1,
      "id": "<hashedSerial>",
 }
}
```

### Product

Hot Chocolate

### Version

12.0.1

**Comment by tobias-tengler** [comment]
Just to get this right, your model contains a string property called `Serial`, which should be rewritten as the `ID` field, but it should still be called `serial` in the schema, right?

Also I'm not sure what you are attempting with the `BindMember` on the `NodeResovler`, what is your goal here?

I would expect it to work like the following:

```csharp
[ExtendObjectType(typeof(ExampleModel))]
[Node(IdField = nameof(ExampleModel.Serial))]
public class ExampleModelNode
{
    [NodeResolver]
    public async Task<ExampleModel?> GetExampleModelBySerialAsync(
        long serial,
        ExampleModelBySerialDataLoader exampleModelBySerial,
        CancellationToken cancellationToken)
        => await exampleModelBySerial.LoadAsync(serial, cancellationToken);
}
```

**Comment by jllano10** [comment]
Hello Tobias, thanks you for replying also in the slack channel too.

`Just to get this right, your model contains a string property called Serial, which should be rewritten as the ID field, but it should still be called serial in the schema, right?`
Yes, this is what I'm trying to do.

`Also I'm not sure what you are attempting with the BindMember on the NodeResovler, what is your goal here?`
I was thinking that this could bind my property with the specific field that I need. Also, it was a suggestion that someone tries here: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1637272494256700

`I would expect it to work like the following:`
I tested it as the way you are saying and I'm getting this error in the console (the same I reported before):
```
The specified id field Serial does not exist on ...ExampleModelNode.
```

**Comment by tobias-tengler** [comment]
I've updated my post from above. I was able to confirm the issue. Could you please confirm that it still represents what you are trying to do?

**Comment by jllano10** [comment]
```
The user should be able to query this like the following:
{
  id # ID!
  serial #Long!
}
```
Yes, this is exactly what I need.

**Comment by tobias-tengler** [comment]
I think we should definitely make this work using the `IdField`, but if you require an immediate solution, you can use the following workaround:

```csharp
[Node]
[ExtendObjectType(typeof(Model))]
public class ModelNode
{
    [ID]
    public long Id([Parent] Model model) => model.Serial;

    [NodeResolver]
    public Model GetModelAsync(long id)
    {
        // ...
    }
}
```

**Comment by jllano10** [comment]
Thanks for this information, it is working if I run the query requesting the Id and Serial with this fix.
It is possible that with this workaround the node() query doesn't work?
```
query nodeExampleModel{
  node(id: "<hashedId>"){
    id    
    ... on ExampleModel {
      id   
    }
  }
}
```
I get the following error:
```
{
  "errors": [
    {
      "message": "There was no argument with the name `serial` found on the field `node`.",
    }
}
```

**Comment by tobias-tengler** [comment]
It should be working, I tested the workaround before. Could you post your Node definition again?

**Comment by jllano10** [comment]
**Model Class:**
```
public class ExampleModel
{
    public long Serial { get; set; }
}
```
**Node Class with fix:**
```
   [Node]
   [ExtendObjectType(typeof(ExampleModel))] ​
   ​public class ExampleModelNode
   ​{
       [ID]
       public long Id([Parent] ExampleModel model) => model.Serial;
       ​
       ​[NodeResolver]
       ​public async Task<ExampleModel?> GetExampleModelBySerialAsync(
           ​long serial,
           ​ExampleModelBySerialDataLoader exampleModelBySerial,
           ​CancellationToken cancellationToken)
           ​=> await exampleModelBySerial.LoadAsync(serial, cancellationToken);
```

**Comment by tobias-tengler** [comment]
The issue appears to be that the parameter to the `GetExampleModelBySerialAsync` method is called `serial` and not `id`. It works with `id`, but not with something else like `serial`. I'm raising a different issue for this.

**Comment by ignj** [comment]
I stumbled into this issue and it seems to be scoped to the Data-annotation approach, which forces you to update your model to use `Id` as the property name.
Code-first approach works fine and lets you use the name you want for the property within the model
