### ISSUE TITLE
Different scoped service instance between Azure Function Call and resolver

### ISSUE THREAD

**Issue by lchmielewski** [ChilliCream/hotchocolate#4524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys,

I'm building an azure function that uses CosmosDB with graphQL API. I use input binding to get cosmosDB client and then I want to use the client in my resolver. The problem is that currently Azure Function support doesn't allow that out of the box.

Specifically IGraphQLRequestExecutor doesn't allow to pass anything except for request.
My solution was to build CosmosDBProvider that I would pass the client to and inject the provider into resolver.

The problem is that 

```
    public class Query
    {
        [GraphQLDescription("Get all properties")]
        public async Task<IEnumerable<Property>> GetProperties(IResolverContext context, [Service] ICosmosClientProvider clientProvider)
        {
            var client = clientProvider.Get();
      ...
```

The provider here is not the same as the one at the beginning. Is that by design? From documentation it seems that it should be the same instance, not the new one made for graphql pipeline specifically?

### Steps to reproduce

1. Create azure function
2. Configure service in the startup as Scoped.
3. First inject it inside Run method of the function.
4. Then inject it with [Service] attribute, it's not the same instance.

### Product

Hot Chocolate

### Version

12.3.2

**Comment by tobias-tengler** [comment]
You have registered your service as scoped, so you'll be getting a new instance per request. From your explanation you likely want to have a singleton instancee.

[Learn more about service lifetimes](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-lifetimes)

**Comment by lchmielewski** [comment]
@tobias-tengler But both injections were in the same azure function call. Shouldn't it be the same? Isn't that the difference between scoped and transient?

And I don't think passing cosmosdb client through singleton in the world of serverless make much sense...

**Comment by tobias-tengler** [comment]
Ah sorry I misunderstood your issue. Your issue is that you get a different scoped instance depending on whether you are in the GraphQL portion of the program or in the function portion, i.e. the `Run` method. 
Could you share how you access the service in the `Run` method as well?

If I remember correctly, Hot Chocolate (Server) uses the `RequestServices` ServiceProvider on the `HttpContext`. I just quickly skimmed the Azure Functions code and I don't see it behaving differently. I just don't know how the `Run` method fits in there.

I guess @michaelstaib knows more about this.

**Comment by lchmielewski** [comment]
Yeah, sure, maybe I wasnt clear enough.

This is my Run method
`        [FunctionName("GraphQLHttpFunction")]
        public async Task<IActionResult> Run(

            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql/{**slug}")]
            HttpRequest request,
            [CosmosDB(
                databaseName: "properties",
                collectionName: "property",
                ConnectionStringSetting = "CosmosDBConnection")]
            DocumentClient client,
            [GraphQL]
        IGraphQLRequestExecutor executor, 
        CancellationToken cancellationToken)
            {
                _clientProvider.Set(client);
                return await executor.ExecuteAsync(request);
            }
`
And yeah, it's a different instance here and in graphql code.

Of course it would be nice to be able to pass a dictonary of paramers to the execute method as now the graphql code simply cannot make any use of any input bindings in the azure function, but still, properly working DI allows me to do it this way, so good enough.

**Comment by michaelstaib** [comment]
Scoped as far as I know is per request. 
Singleton per service instance and transient is essentially a new instance every time you ask for. It would be very strange of the scoping in AzF is different than with ASP.NET Core.

**Comment by lukasz-blazity** [comment]
@michaelstaib I've digged a bit deeper and it seems that the issue is more with Azure Function than hotchocolate. When I fetched the service from RequestServices, then I got the same instance. Seems that ATM function constructor has a different scope than function's Run method... Which is weird, as constructor is mentioned as a recommended way to do DI.

Anyways, when I do service locator inside Run method everything works:
```
        [FunctionName("GraphQLHttpFunction")]
        public async Task<IActionResult> Run(

            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql/{**slug}")]
            HttpRequest request,
            [CosmosDB(
                databaseName: "properties",
                collectionName: "property",
                ConnectionStringSetting = "CosmosDBConnection")]
            DocumentClient client,
            [GraphQL]
        IGraphQLRequestExecutor executor, 
        CancellationToken cancellationToken)
            {
                var clientProvider = request.HttpContext.RequestServices.GetRequiredService<ICosmosClientProvider>();
                clientProvider.Set(client);

                return await executor.ExecuteAsync(request);
            }
```

so I think we're good here, thanks :)

**Comment by lchmielewski** [comment]
@michaelstaib I've digged a bit deeper and it seems that the issue is more with Azure Function than hotchocolate. When I fetched the service from RequestServices, then I got the same instance. Seems that ATM function constructor has a different scope than function's Run method... Which is weird, as constructor is mentioned as a recommended way to do DI.

Anyways, when I do service locator inside Run method everything works:

        [FunctionName("GraphQLHttpFunction")]
        public async Task<IActionResult> Run(

            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql/{**slug}")]
            HttpRequest request,
            [CosmosDB(
                databaseName: "properties",
                collectionName: "property",
                ConnectionStringSetting = "CosmosDBConnection")]
            DocumentClient client,
            [GraphQL]
        IGraphQLRequestExecutor executor, 
        CancellationToken cancellationToken)
            {
                var clientProvider = request.HttpContext.RequestServices.GetRequiredService<ICosmosClientProvider>();
                clientProvider.Set(client);

                return await executor.ExecuteAsync(request);
            }
so I think we're good here, thanks :)
