### ISSUE TITLE
Neo4J Mutations

### ISSUE THREAD

**Issue by HurricanKai** [ChilliCream/hotchocolate#4526]
### Is your feature request related to a problem?

Using HotChocolate as my central place of maintaining the database types and relations seems very appealing. Ignoring some bugs this works perfectly for read access, for write access using the same existing types with attributes marking relations seems possible.

### The solution you'd like

Defining Neo4J backed Mutations similar to Neo4J backed Queries would be possible. I haven't fully understood how Mutations work internally, and whether there is a mechanism like Data Loaders for them. Queries of course use Neo4JExecutable but I'm not sure whether this can somehow be extended to queries.

This complicates even more considering that if an existing object is to be mutated `MATCH` (similar to the existing Queries) is used, with the changing properties set using `SET`. For actual creations `CREATE` should be used instead, or maybe also `MERGE` when it's unclear whether an object already exists, with `ON CREATE` and `ON MATCH`.

### Product

Hot Chocolate

**Comment by HurricanKai** [comment]
Note on ITransactionScopeHandler: This can't really be used with Neo4J, because the Neo4J driver expects you to use the returned IAsyncTransaction to run all associated queries, but ITransactionScopeHandler doesn't have the capabilities to somehow resolve a service used by the query.

Just injecting the scoped IAsyncSession and using the Read/WriteTransactionAsync methods seems reasonable enough.

**Comment by michaelstaib** [comment]
That is not true, ITransactionScopeHandler can resolve anything from any resolver.

**Comment by michaelstaib** [comment]
The way you can graph things from the request is trhough the request context which can be reached through the request context accessor. If this is the right tool it remains to be seen. Mutations is not yet solved.... @arif-hanif wants to organize a meeting on this to discuss further things.

**Comment by HurricanKai** [comment]
Interesting, I guess injecting an IAsyncTransaction is possible then. Regardless of Mutations support I think it'd be useful to provide this as a TransactionScopeHandler, it'd both help with writing custom mutations backed by Neo4J as well as making it possible to use transactions in queries.

**Comment by michaelstaib** [comment]
Would be great to get you on board then :)
