### ISSUE TITLE
FileUpload / UploadType error -> Invalid number, expected digit but got: `-` (45).

### ISSUE THREAD

**Issue by AmbroiseCouissin** [ChilliCream/hotchocolate#4530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When uploading a file, I get the following error:

`Invalid number, expected digit but got: `-` (45).`

![image](https://user-images.githubusercontent.com/9957278/145327065-e2df3741-2335-499a-a99c-82efe300d7be.png)

### Steps to reproduce

1.  Here is a minimal sample repository: https://github.com/AmbroiseCouissin/HotChocolate-FileUpload-Sample

2. Run the program and go to /ui/altair

3. Input the following mutation:

``` graphql
mutation($someFile: Upload!) {
  uploadFile(input: {
    bucketName: ""
    key: "someKey"
    content: $someFile
  })
}
```

4. Input the file variable of Altair
![image](https://user-images.githubusercontent.com/9957278/145327274-3799bc36-4c5a-460a-9eaf-83db02f85314.png)

### Relevant log output

```shell
https://github.com/AmbroiseCouissin/HotChocolate-FileUpload-Sample
```

### Product

Hot Chocolate

### Version

1.2.4.0-rc1

**Comment by tobias-tengler** [comment]
I can't access the linked repository - it needs to be public.

**Comment by michaelstaib** [comment]
Me to ... get a 404 :)

**Comment by AmbroiseCouissin** [comment]
@tobias-tengler @michaelstaib Terribly sorry... It was private.

It is now public.

**Comment by AmbroiseCouissin** [comment]
@michaelstaib I see you added this to the Backlog :)

Any idea what was the issue?

**Comment by michaelstaib** [comment]
Not yet ... I would guess some error in Altair but have not verified it. Underneath we use the Microsoft implementation for the mime stream. Backlog just means that someone can pull this item to analyze it.  The flow is backlog -> 12.x.x -> specific version.

**Comment by KNobelsPortima** [comment]
I have this problem also ... don't get it why.
`locations: [{line: 1, column: 1}]
0: {line: 1, column: 1}
message: "Invalid number, expected digit but got: `-` (45)."`

![image](https://user-images.githubusercontent.com/126657419/234416142-1c1b69ed-53d8-4b7c-bb7e-7fbe75800fa1.png)
