### ISSUE TITLE
Add support for DateOnly and TimeOnly to Data

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#4531]
### Is your feature request related to a problem?

Add support for DateOnly and TimeOnly to Data

### The solution you'd like

-

### Product

Hot Chocolate

**Comment by moander** [comment]
`TimeOnly` is serialized the same way as `TimeSpan` (as a iso duration). It also shows up in the schema as TimeSpan. 

I was expecting a iso time like `T00:00:00` instead of `PT0S`.

Is this the expected behavior or am I doing something wrong?
