### ISSUE TITLE
Investigate Nested Dataloader in Exectuion Engine

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#4532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@sep2 from slack: 
>I have made a repo here https://github.com/sep2/dataloader-being-stuck , sorry it's in F# as I am not familiar in C#. Tell me if you need any assistance @Pascal

### Steps to reproduce

1. Check Readme

### Product

Hot Chocolate

### Version

12.4.0-rc.1

**Comment by sep2** [comment]
I have simplify the code a bit, now it's only [one file](https://github.com/sep2/dataloader-being-stuck/blob/main/DataLoaderBeingStuck/Program.fs).

please see the readme for sample query.

**Comment by michaelstaib** [comment]
Awesome ... thanks guys for putting it together :D also, F# looks so pretty :D

**Comment by sep2** [comment]
I think the issue probably comes from `CacheDataLoader`. After replacing all `CacheDataLoader` by `BatchDataLoader` it's now okay.

**Comment by michaelstaib** [comment]
I am investigating this ...

**Comment by michaelstaib** [comment]
This issue is fixed with 12.4.0-rc.2
