### ISSUE TITLE
Banana Cake Pop: Folder renames do not sync

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/hotchocolate#4542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I rename a folder in BCP, the change doesn't get synchronised. When I sync the workspace at another URL, the folder still has its old name. The only way to effectively change the name is to recreate all the documents in a new folder and delete the old folder.

### Steps to reproduce

1. Create a folder and a document in a workspace at URL 1
2. Sync
3. Open the workspace at URL 2 and sync; check that the folder and doc are there
4. Go back to URL 1; rename the folder you created. Notice that the sync button stays green.
5. Sync
6. Go back to URL 2 and sync. The folder still has its old name.

### Product

Banana Cake Pop

### Version

12.3.2

**Comment by tobias-tengler** [comment]
I can not reproduce this issue on https://eat.bananacakepop.com, for me it syncs as expected.
The BCP middleware for Hot Chocolate has been updated since 12.3.2 and is included in the preview version `12.4.0-rc.2`. Could you try this version and confirm if the issue persists or not?

**Comment by AlexKubiesa** [comment]
We have just updated to HC 12.6 and I still see the same problem.
