### ISSUE TITLE
Support sorting by a child object's property value

### ISSUE THREAD

**Issue by h5aaimtron** [ChilliCream/hotchocolate#4553]
### Is your feature request related to a problem?

Let's say I have a Team Object that has a List of Member objects, each member containing FirstName, LastName, and a bool IsCaptain. If I return a list of Teams, I can generally display all data without issue. I may be displaying this data in a table and want to be able to sort by the Team captains name, however; Members would not be part of the TeamSortInput object as its an array. I'm not sure it being the array is the exact cause for it not showing in the schema definitions, but its been my experience so far.

### The solution you'd like

I would like to be able to sort a List (usually IQueryable) items by any property including children's properties.

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
@h5aaimtron  sorting on nested object values is supported
Sorting by a member of a nested list is not because there is no order
