### ISSUE TITLE
Migration from HC11 to HC12 throw "Could not resolve the actual object type from "

### ISSUE THREAD

**Issue by kYann** [ChilliCream/hotchocolate#4555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using entity framework with proxy support, new dynamic types (castle proxies) get created.
When describing those types using code-first I get a "Could not resolve the actual object type from " exception.

This was working in HC11.

### Steps to reproduce

1. Create an interface type

```csharp
public class MatchCriteriaType : InterfaceType<MatchCriteria>
	{
		protected override void Configure(IInterfaceTypeDescriptor<MatchCriteria> descriptor)
		{
			descriptor.BindFieldsImplicitly();
			base.Configure(descriptor);
		}
	}
```

2. Define type
```csharp
public class OccupationMatchCriteriaType : ObjectType<OccupationMatchCriteria>
	{
        protected override void Configure(IObjectTypeDescriptor<OccupationMatchCriteria> descriptor)
		{
			descriptor.Implements<MatchCriteriaType>();
			base.Configure(descriptor);
		}
	}
```
	
3. Activate [EF Core Change tracking proxies](https://docs.microsoft.com/en-us/ef/core/change-tracking/change-detection#change-tracking-proxies) but this is an inheritance issue and not really related to efcore.

### Additional Context?

The workaround is to override the IsInstanceOfType method in the object definition 

```csharp
public override bool IsInstanceOfType(IResolverContext context, object resolverResult)
		{
			var isInstanceOfType = this.RuntimeType.IsInstanceOfType(resolverResult);
			return isInstanceOfType;
		}
```

### Product

Hot Chocolate

### Version

12.3.2

**Comment by michaelstaib** [comment]
We changed the instance check from IsInstanceOfType to `result is null || RuntimeType == result.GetType();` which is a more explicit binding. In most cases this is the expected behaviour. We can add an option with 12.5 to allow for the 11 style check.

**Comment by michaelstaib** [comment]
Hot Chocolate 12.5.0-preview.3 now allows you to configure a global type check default on the options:

```csharp
services
    .AddGraphQLServer()
        .ModifyOptions(o => o.DefaultIsOfTypeCheck = (objectType, context, value) =>
        {
            return objectType.RuntimeType.IsInstanceOfType(value);
        })
   .....
```

This now makes it easier to override the default. 

This already is possible with your current version but the IsOfTypeFallback is more difficult to set, if you want to do it with your stable version:


```csharp
services.AddGraphQLServer().ConfigureSchema(sb => sb.SetTypeResolver("your delegate goes here!")))
```

With `ConfigureSchema` you can access the underlying ISchemaBuilder. However, we want to refactor the `ISchemaBuilder` and it is better to use the higher-level config API. That is why I have pulled up the setting to our new config API with 12.5
