### ISSUE TITLE
InputObject GeometryOverlaySortInput has no fields declared

### ISSUE THREAD

**Issue by edihasaj** [ChilliCream/hotchocolate#4579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Graphql with Hotchocolate does not start because GeometryOverlaySortInput of NetTopologySuite package has no fields declared.

I upgraded the Hotchocolate Graphql packages and EntityFramework Core packages, and now the application starts but graphql is not working. I tried downgrading the versions one by one, but it seems that reversing to ef core packages version 5.0.13 and lower this error doesn't happen. Maybe you can show me how can I contribute to fix this issue and I will do a PR.

Thanks a lot

### Steps to reproduce

1. Upgrade EntityFrameworkCore dependencies to 6.0.0 or 6.0.1
2. Include EntityFrameworkCore  NetTopologySuite library
3. Start GraphQL host instance

### Relevant log output

```shell
1. InputObject `GeometryOverlaySortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.GeometryOverlay>)
2. InputObject `CoordinateEqualityComparerSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.CoordinateEqualityComparer>)

   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
```


### Additional Context?

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows
IDE: JetBrains Rider

### Product

Hot Chocolate

### Version

12.4.1

**Comment by VovaSanduliak** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Graphql with Hotchocolate does not start because GeometryOverlaySortInput of NetTopologySuite package has no fields declared.
> 
> I upgraded the Hotchocolate Graphql packages and EntityFramework Core packages, and now the application starts but graphql is not working. I tried downgrading the versions one by one, but it seems that reversing to ef core packages version 5.0.13 and lower this error doesn't happen. Maybe you can show me how can I contribute to fix this issue and I will do a PR.
> 
> Thanks a lot
> 
> ### Steps to reproduce
> 1. Upgrade EntityFrameworkCore dependencies to 6.0.0 or 6.0.1
> 2. Include EntityFrameworkCore  NetTopologySuite library
> 3. Start GraphQL host instance
> 
> ### Relevant log output
> ```shell
> 1. InputObject `GeometryOverlaySortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.GeometryOverlay>)
> 2. InputObject `CoordinateEqualityComparerSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.CoordinateEqualityComparer>)
> 
>    at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
>    at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
>    at HotChocolate.Configuration.TypeInitializer.Initialize()
>    at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
>    at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
>    at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
>    at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
>    at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
>    at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
>    at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
>    at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
>    at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
>    at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
>    at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
>    at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> ```
> 
> ```
> 
> 
> ### Additional Context?
> 
> EF Core version: 6.0.1
> Database provider: Microsoft.EntityFrameworkCore.SqlServer
> Target framework: .NET 6.0
> Operating system: Windows
> IDE: JetBrains Rider
> 
> ### Product
> 
> Hot Chocolate
> 
> ### Version
> 
> 12.4.1
> ```

Have you resolved this problem?

**Comment by edihasaj** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Describe the bug
> > Graphql with Hotchocolate does not start because GeometryOverlaySortInput of NetTopologySuite package has no fields declared.
> > I upgraded the Hotchocolate Graphql packages and EntityFramework Core packages, and now the application starts but graphql is not working. I tried downgrading the versions one by one, but it seems that reversing to ef core packages version 5.0.13 and lower this error doesn't happen. Maybe you can show me how can I contribute to fix this issue and I will do a PR.
> > Thanks a lot
> > ### Steps to reproduce
> > 
> > 1. Upgrade EntityFrameworkCore dependencies to 6.0.0 or 6.0.1
> > 2. Include EntityFrameworkCore  NetTopologySuite library
> > 3. Start GraphQL host instance
> > 
> > ### Relevant log output
> > ```shell
> > 1. InputObject `GeometryOverlaySortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.GeometryOverlay>)
> > 2. InputObject `CoordinateEqualityComparerSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.CoordinateEqualityComparer>)
> > 
> >    at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
> >    at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
> >    at HotChocolate.Configuration.TypeInitializer.Initialize()
> >    at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
> >    at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
> >    at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
> >    at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
> >    at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
> >    at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
> >    at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
> >    at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
> >    at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
> >    at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
> >    at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
> >    at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
> >    at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> >    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> >    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> >    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > 
> > ### Additional Context?
> > 
> > EF Core version: 6.0.1
> > Database provider: Microsoft.EntityFrameworkCore.SqlServer
> > Target framework: .NET 6.0
> > Operating system: Windows
> > IDE: JetBrains Rider
> > 
> > ### Product
> > 
> > Hot Chocolate
> > 
> > ### Version
> > 
> > 12.4.1
> > ```
> 
> Have you resolved this problem?

No, not yet.. This is happening because these two objects now have no properties declared in netopologysuite, but the new verzion of hotchocolate is throwing this error.

**Comment by VovaSanduliak** [comment]
@edihasaj, I have the same proplem with spatial data, HotChocolate 12.4.1. Is there a version which is not throwing this error?

**Comment by edihasaj** [comment]
@VovaSanduliak the only solution for now is to reverse back the entity framework core to 5.0.13 or lower, but then you cannot create migrations and some other functionality added in 6.0

**Comment by VovaSanduliak** [comment]
@edihasaj, I created custom **PointSortType** which extends **SortInputType<Point>** and ignored all fields except for fields I need. It have met my need.

```
public class PointSortType : SortInputType<Point>
    {
        protected override void Configure(ISortInputTypeDescriptor<Point> descriptor)
        {
            descriptor.Ignore(f => f.Area);
            descriptor.Ignore(f => f.Boundary);
            descriptor.Ignore(f => f.BoundaryDimension);
            descriptor.Ignore(f => f.Centroid);
            descriptor.Ignore(f => f.Coordinate);
            descriptor.Ignore(f => f.Coordinates);
            descriptor.Ignore(f => f.CoordinateSequence);
            descriptor.Ignore(f => f.Dimension);
            descriptor.Ignore(f => f.Envelope);
            descriptor.Ignore(f => f.EnvelopeInternal);
            descriptor.Ignore(f => f.Factory);
            descriptor.Ignore(f => f.GeometryType);
            descriptor.Ignore(f => f.InteriorPoint);
            descriptor.Ignore(f => f.IsEmpty);
            descriptor.Ignore(f => f.IsRectangle);
            descriptor.Ignore(f => f.IsSimple);
            descriptor.Ignore(f => f.IsValid);
            descriptor.Ignore(f => f.Length);
            descriptor.Ignore(f => f.M);
            descriptor.Ignore(f => f.NumGeometries);
            descriptor.Ignore(f => f.NumPoints);
            descriptor.Ignore(f => f.OgcGeometryType);
            descriptor.Ignore(f => f.PointOnSurface);
            descriptor.Ignore(f => f.PrecisionModel);
            descriptor.Ignore(f => f.SRID);
            descriptor.Ignore(f => f.UserData);
            descriptor.Field(f => f.X);
            descriptor.Field(f => f.Y);
            descriptor.Field(f => f.Z);
        }
    }
```

Startup.cs
`.AddType<PointSortType>()`

`.AddSorting()`

**Comment by edihasaj** [comment]
@VovaSanduliak thank you for trying to help me out. I tried this, but it doesn't seem to work for me.

**Comment by edihasaj** [comment]
@michaelstaib At hotchocolate.data => hotchocolate.types => internal => FieldInitHelper.cs at code line '186' there is a function that makes the validation, I'll put it here in order to describe it better:

```
private static FieldCollection<TField> CompleteFieldsInternal<TField>(
        ITypeCompletionContext context,
        ITypeSystemMember declaringMember,
        TField[] fields)
        where TField : class, IField
    {
        if (declaringMember is IType type && fields.Length == 0)
        {
            context.ReportError(SchemaErrorBuilder.New()
                .SetMessage(string.Format(
                    CultureInfo.InvariantCulture,
                    TypeResources.FieldInitHelper_NoFields,
                    type.Kind.ToString(),
                    context.Type.Name))
                .SetCode(ErrorCodes.Schema.MissingType)
                .SetTypeSystemObject(context.Type)
                .AddSyntaxNode((type as IHasSyntaxNode)?.SyntaxNode)
                .Build());
            return FieldCollection<TField>.Empty;
        }

        foreach (TField field in fields)
        {
            ((IFieldCompletion)field).CompleteField(context, declaringMember);
        }

        return new FieldCollection<TField>(fields);
    }
```

this is returning the error because the updated version of efcore library, specifically, in the nettopologysuite lib there are two classes with no properties. But logically this should not be happening shouldn't it? Is there any way I can fix this I tried bypassing the check but still didn't get something promissing...

Any help would be much appreciated.

**Comment by edihasaj** [comment]
@VovaSanduliak any idea how to ignore the type (object) not the properties completely?

**Comment by michaelstaib** [comment]
Are you using our spatial package?

**Comment by edihasaj** [comment]
Yes

**Comment by edihasaj** [comment]
Using types like this one example from your demo package of spatial project:

```
 
  
 ​namespace​ ​Spatial​.​Demo​ { 
 ​    ​public​ ​class​ ​LiquorStore​ { 
 ​        ​public​ ​int​ ​Xid​ { ​get​; ​set​; } 
 ​        ​public​ ​int​ ​StoreNumber​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​Type​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​Name​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​Address​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​City​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​County​ { ​get​; ​set​; } 
 ​        ​public​ ​string​ ​Phone​ { ​get​; ​set​; } 
 ​        ​public​ ​int​ ​Zip​ { ​get​; ​set​; } 
 ​        ​public​ ​Point​ ​Shape​ { ​get​; ​set​; } 
 ​    } 
 ​}

```

**Comment by PascalSenn** [comment]
>  At hotchocolate.data => hotchocolate.types => internal => FieldInitHelper.cs
That is too deep in the type system. 
The approach @VovaSanduliak  posted with the custom filter types should technically work for you too
what was the issue you see?

**Comment by edihasaj** [comment]
@PascalSenn indeed is deep, I tried to ignore classes with no properties for days but that didn't work... Well, yes, the solution from @VovaSanduliak worked when do you for every geometry inherited type you use (which in my case was), I just wanted to fix the issue because technically this can happen for other types and libraries in the future.

Anyways should I close the issue or let it open for potential fixing?

**Comment by edihasaj** [comment]
Thanks for the support guys 👊

**Comment by michaelstaib** [comment]
But what would you do with types without methods or properties... The GraphQL spec forbids types that do not have any fields.

**Comment by edihasaj** [comment]
I read the specification and I know that it forbids, that's why I opened an issue in nettopologysuite lib maybe to add some types to those two classes that have only methods and no properties, their response is fair, I can extend the type and mark it as the default in that case (but extra work for someone who uses them). I didn't know that the spec forbids that when I got into debugging and trying to pass the error 🙄. Anyways if you guys suggest something that I can contribute here I will gladly do it 😁, you did a great job here 👍

**Comment by vishnu4** [comment]
Honestly I'm not entirely sure why this issue is closed, since it still occurs.  @VovaSanduliak 's solution didn't work for me, but it did give me a starting point for what i needed.  I had to add the following in my case:

```
public class GeometrySortType : SortInputType<NetTopologySuite.Geometries.Geometry>
    {
        protected override void Configure(ISortInputTypeDescriptor<NetTopologySuite.Geometries.Geometry> descriptor)
        {
            descriptor.Ignore(f => f.Area);
            descriptor.Ignore(f => f.Boundary);
            descriptor.Ignore(f => f.BoundaryDimension);
            descriptor.Ignore(f => f.Centroid);
            descriptor.Ignore(f => f.Dimension);
            descriptor.Ignore(f => f.Envelope);
            descriptor.Ignore(f => f.EnvelopeInternal);
            descriptor.Ignore(f => f.Factory);
            descriptor.Ignore(f => f.GeometryType);
            descriptor.Ignore(f => f.InteriorPoint);
            descriptor.Ignore(f => f.IsEmpty);
            descriptor.Ignore(f => f.IsRectangle);
            descriptor.Ignore(f => f.IsSimple);
            descriptor.Ignore(f => f.IsValid);
            descriptor.Ignore(f => f.Length);
            descriptor.Ignore(f => f.NumGeometries);
            descriptor.Ignore(f => f.NumPoints);
            descriptor.Ignore(f => f.OgcGeometryType);
            descriptor.Ignore(f => f.PointOnSurface);
            descriptor.Ignore(f => f.PrecisionModel);
            descriptor.Ignore(f => f.SRID);
            descriptor.Ignore(f => f.UserData);
            descriptor.Field(f => f.Coordinate);
            descriptor.Ignore(f => f.Coordinates);
        }
    }

    public class CoordinateSortType : SortInputType<NetTopologySuite.Geometries.Coordinate>
    {
        protected override void Configure(ISortInputTypeDescriptor<NetTopologySuite.Geometries.Coordinate> descriptor)
        {
            descriptor.Ignore(f => f.IsValid);
            descriptor.Ignore(f => f.M);
            descriptor.Field(f => f.X);
            descriptor.Field(f => f.Y);
            descriptor.Field(f => f.Z);
        }
    }
```

But honestly i would think that this should just be autoincluded from the 'AddSpatialTypes' in HotChocolate.Types.Spatial, not sure why something like this isn't?

**Comment by willwolfram18** [comment]
Hey folks! I'm wondering if there are other ideas or suggestions on how this issue can be addressed? My team is currently working with a data model and structure that uses some nested classes/documents (MongoDB as our database) and we're seeing this exception because the nested document type doesn't have anything other than the some enumerables.

Are there any attributes or methods we can use to tell the `UseSorting` middleware to ignore a particular property from introspection and reflection **but** still keep it for the other `UseFiltering` and selection set capabilities.

Below is some example code to help demonstrate the situation

```csharp
public class RootDocument
{
    [GraphQLType(typeof(NonNullType<IdType>))]
    public Guid Id { get; set; }

    public string Name { get; set; }

    public NestedDocument MyNestedField { get; set; }
}

// We use the nested document type to enable future type evolution to include additional properties at a later time, if needed
public class NestedDocument
{
    public IEnumerable<NestedDocElement> Items { get; set; }
}

public class NestedDocElement { public string Name { get; set; } }

public class Query
{
    // I want to keep all of these middlewares, but skip the NestDocument for the sort input types
    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public IExecutable<RootDocument> GetItems() { /* implementation */ }
}
```

So that I can do queries like, but don't need to worry about sorting on the `MyNestedField` field
```graphql
query {
  items(where: {
    myNestedField: { items: { any: true } } # or filtering for other specific values
  }) {
    nodes {
      id name # etc.
    }
  }
}
```

**Comment by willwolfram18** [comment]
> Hey folks! I'm wondering if there are other ideas or suggestions on how this issue can be addressed? My team is currently working with a data model and structure that uses some nested classes/documents (MongoDB as our database) and we're seeing this exception because the nested document type doesn't have anything other than the some enumerables.
> 
> Are there any attributes or methods we can use to tell the `UseSorting` middleware to ignore a particular property from introspection and reflection **but** still keep it for the other `UseFiltering` and selection set capabilities.
> 
> Below is some example code to help demonstrate the situation
> 
> ```cs
> public class RootDocument
> {
>     [GraphQLType(typeof(NonNullType<IdType>))]
>     public Guid Id { get; set; }
> 
>     public string Name { get; set; }
> 
>     public NestedDocument MyNestedField { get; set; }
> }
> 
> // We use the nested document type to enable future type evolution to include additional properties at a later time, if needed
> public class NestedDocument
> {
>     public IEnumerable<NestedDocElement> Items { get; set; }
> }
> 
> public class NestedDocElement { public string Name { get; set; } }
> 
> public class Query
> {
>     // I want to keep all of these middlewares, but skip the NestDocument for the sort input types
>     [UsePaging]
>     [UseFiltering]
>     [UseSorting]
>     public IExecutable<RootDocument> GetItems() { /* implementation */ }
> }
> ```
> 
> So that I can do queries like, but don't need to worry about sorting on the `MyNestedField` field
> 
> ```graphql
> query {
>   items(where: {
>     myNestedField: { items: { any: true } } # or filtering for other specific values
>   }) {
>     nodes {
>       id name # etc.
>     }
>   }
> }
> ```

I fill silly for not seeing this earlier. When creating a custom `SortInputType<T>`, the object passed to the  `Configure(ISortInputTypeDescriptor<T> descriptor)` method has an `Ignore()` method that can be used to explicitly remove a property from the object. So that override enabled me to fix my issue and keep all of the other sort and filtering capabilities I wanted with an overload like this.

```csharp
public class RootDocumentSortInputType : SortInputType<RootDocument>
{
    protected override void Configure(ISortInputTypeDescriptor<RootDocument> descriptor)
    {
        descriptor.Ignore(doc => doc.MyNestedField);
    }
}

// Then, in my program/startup class:
services.AddGraphQLServer()
    .AddQueryType<Query>()
    .AddType<RootDocument>()
    .AddType<RootDocumentSortInputType>();
```

I feel crazy because I read through the docs several times and looked at the configure overload multiple times and somehow missed the `Ignore()` method in both places 🤦 But glad to see that it's there and fairly easy to include, even if it does require a little extra code and type definitions.

**Comment by rsousacode** [comment]
> Is this fixed in any version lately? I got the same issue at 13.6.1, configuration just like tutorial https://chillicream.com/docs/hotchocolate/v13/integrations/spatial-data

Same here. I really don't understand why this is closed.

I tried @VovaSanduliak solution also without any success.
I saw that @edihasaj opened this issue https://github.com/NetTopologySuite/NetTopologySuite/issues/584. But I was unable to derive any solution from the answer. Im here in a quite rabbit hole here. 

The code I tried to use 

```cs
NetTopologySuite.NtsGeometryServices.Instance = new NetTopologySuite.NtsGeometryServices(
    NetTopologySuite.Geometries.Implementation.CoordinateArraySequenceFactory.Instance,
    new NetTopologySuite.Geometries.PrecisionModel(1000d),
    4326, 
    NetTopologySuite.Geometries.GeometryOverlay.NG,
    new HotCoordinateEqualityComparer());


services
    .AddGraphQLServer()
    .AddSpatialTypes()
    .AddFiltering()
    .AddProjections()
    .AddSpatialFiltering()
    .AddSpatialProjections()
    .AddSorting()
    .BindRuntimeType<Geometry, GeoJsonInterfaceType>()
    .AddType<GeometrySortType>()
    .AddType<CoordinateSortType>()
    .AddQueryType<Query>()
    .RegisterDbContext<ApplicationDbContext>(DbContextKind.Pooled);
```

Error:

```
      1. InputObject `GeometryOverlaySortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.GeometryOverlay>)
      2. InputObject `CoordinateEqualityComparerSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.CoordinateEqualityComparer>)
```

**Comment by amzhang** [comment]
Our Hot Chocolate 13 migration is stuck here as well.

**Comment by amzhang** [comment]
This is our solution:

```
using HotChocolate.Data.Sorting;
using NetTopologySuite.Geometries;

public class PointSortInputType : SortInputType<Point>
{
    protected override void Configure(ISortInputTypeDescriptor<Point> descriptor)
    {
        descriptor.BindFieldsExplicitly();
        descriptor.Field(f => f.X);
        descriptor.Field(f => f.Y);
        descriptor.Field(f => f.Z);
    }
}

public class PolygonSortInputType : SortInputType<Polygon>
{
    protected override void Configure(ISortInputTypeDescriptor<Polygon> descriptor)
    {
        descriptor.BindFieldsExplicitly();
        // Have to include at least one field.
        descriptor.Field(f => f.Centroid);
    }
}
```

In Program.cs:
```
graphqlServer
        .AddType<PointSortInputType>()
        .AddType<PolygonSortInputType>();
```

**Comment by wietlol** [comment]
This issue happens for all types that are subject to the automatic sorrting type generator, while not having properties that it supports.
For example, any class that only has properties of type List<*> will get this error.
I think the default automatic sorting type generator could check for those cases and simply ignore that type then completely.
This would mean that we are no longer required to specify for each usage that the property should be ignored for sorting purposes manually.
