### ISSUE TITLE
Bind UnsingedShort implicit

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#4583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.Scalars/UnsignedShortType.cs#L24

### Steps to reproduce

I think the type should be bound implicit

### Product

Hot Chocolate

### Version

12.4.0

**Comment by nelsonprsousa** [comment]
All the scalars but `UtcOffsetType` are bounded explicitly. 

Examples:,
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.Scalars/UnsignedIntType.cs#L24
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types.Scalars/UnsignedLongType.cs#L27
