### ISSUE TITLE
Strawberry Shake says Value cannot be Null if field starts with Underscore and is marked as not Null

### ISSUE THREAD

**Issue by meierhoeferjannis** [ChilliCream/hotchocolate#4593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

StrawberryShake throws an System.ArgumentNullException when a field starts with an underscore like _id and is marked as not nullable. I already saw the issue  #4480 which describes the same behaviour but was solved due to weird gateway behaviour. 
In the screenshot i attached, you can see that _id has a value so im wondering why i get this exception. Am i missing something ?

### Steps to reproduce
I created a short sample project, that reproduces the bug. https://github.com/meierhoeferjannis/SampleProject
Just start the SampleProject and set a breakpoint in the Index.razor OnInitializedAsync Method. You will see that result.Errors will contain a StrawberryShake.ClientError with the value cannot be null exception. Then check result.Errors.Extensions.Items[0].value.
You will see that the _id field has a value, which is simply getting ignored. (Just like in the screenshot i attached on this issue.

### Additional Context?

![grafik](https://user-images.githubusercontent.com/28475037/147251633-0ea9d3e4-7a3c-4285-b2f1-98c736bca867.png)

### Product

Strawberry Shake

### Version

12.4.1

**Comment by PascalSenn** [comment]
This is fixed in the latest 12.5 previews
