### ISSUE TITLE
Support default query arguments in Strawberry Shake

### ISSUE THREAD

**Issue by brian-tygotech** [ChilliCream/hotchocolate#4594]
### Is your feature request related to a problem?

Sort and Filter inputs generated by Hot Chocolate are nullable by default, so for example the following C# code

```[C#]
[UseSorting(typeof(AmenitySortInputType))]
[UseFiltering(typeof(AmenityFilterInputType))]
public IQueryable<AmenityEntity> GetAmenities( ...
```

Will generate the following graphql schema

```[graphql]
type Query {
  amenities(order: [AmenitySortInput!] where: AmenityFilterInput): [Amenity!]!
}
```

I can then define the following query in Strawberry Shake

```[graphql]
query GetAmenities(
    $order: [AmenitySortInput!] = null
    $where: AmenityFilterInput = null) {
  amenities(
    order: $order
    where: $where) {
    id
    name
  }
}
```

Currently it ignores the argument defaults in the generated code and generates

```[C#]
Task<IOperationResult<IGetAmenityCategoriesResult>> IGetAmenityCategoriesQuery.ExecuteAsync(
   IReadOnlyList<AmenityCategorySortInput>? order,
   AmenityCategoryFilterInput? where,
   CancellationToken cancellationToken = default)
```

### The solution you'd like

I would like Strawberry Shake to generate the following code

```[C#]
Task<IOperationResult<IGetAmenityCategoriesResult>> IGetAmenityCategoriesQuery.ExecuteAsync(
   IReadOnlyList<AmenityCategorySortInput>? order = default,
   AmenityCategoryFilterInput? where = default,
   CancellationToken cancellationToken = default)
```

In the slack discussion it was noted by Pascal that 

```[graphq]
query GetAmenities(
    $order: [AmenitySortInput!] = null
    $where: AmenityFilterInput! ) {
```

Is also valid graphql, but verbatim transpiling to C# would generate 

```[C#]
Task<IOperationResult<IGetAmenityCategoriesResult>> IGetAmenityCategoriesQuery.ExecuteAsync(
   IReadOnlyList<AmenityCategorySortInput>? order = default,
   AmenityCategoryFilterInput? where,
   CancellationToken cancellationToken = default)
```

Which is not valid C#. Reordering the parameters would be a breaking change.

I think the problem described above is the primary use case for this particular feature, however scalar defaults are also possible.

My preference for a first cut of this feature would be to:

- Only support default arguments for reference types.
- Only support default arguments when verbatim transpilation generates valid C#, i.e. not ($x = null, $y).

When default arguments are detected that do not meet the above criteria a warning should be emitted. There should be a setting in `.graphqlrc.json` to disable these warnings, by default these warnings should be emitted.

### Product

Strawberry Shake

**Comment by kyurkchyan** [comment]
I wonder if there is a plan to support default arguments?
