### ISSUE TITLE
Usage array of global identifiers in arguments. Code-first

### ISSUE THREAD

**Issue by lazybnz** [ChilliCream/hotchocolate#4599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Always get exception `HotChocolate.GraphQLException: 'The IDs 'Q2hlY2tMaXN0Cmkx' have an invalid format.'`
when accessing array of IDs by `ctx.ArgumentValue<List<int>>("ids")` and also `ctx.ArgumentValue<int[]>("ids")`

Tried:
```
.Argument("ids", a => a.Type<NonNullType<ListType<NonNullType<IdType>>>>().ID())	
.Argument("ids", a => a.Type<ListType<IdType>>().ID())
```

When map single parameter, works without problem:
```
descriptor
	.Field($"checkListById")
	.Argument("id", a => a.Type<NonNullType<IdType>>().ID())            
	.Resolve(ctx =>
	{
		var id = ctx.ArgumentValue<int>("id");		
	});
```

And "Annotation-based" approach worked no problem, like:
```
public IQueryable<CheckList> GetCheckListsById(
        [ID(nameof(CheckList))] int[] ids,
        ...
```
graphQL query:
```
query checkLists2 {
  checkListsById(ids: ["Q2hlY2tMaXN0Cmkx"]) {
    name
  }
}
```

### Steps to reproduce

1. `descriptor
	.Field($"checkListsById")
	.Argument("ids", a => a.Type<NonNullType<ListType<NonNullType<IdType>>>>().ID())	
	.Resolve(ctx =>
	{
		var ids = ctx.ArgumentValue<List<int>>("ids");
		
	});`

### Product

Hot Chocolate

### Version

12.4

**Comment by PascalSenn** [comment]
Try
```
```

**Comment by PascalSenn** [comment]
Try
```
descriptor
.Field($"checkListsById")
.Argument("ids", a => a.Type<NonNullType<ListType<NonNullType<IdType>>>>().ID())
.Resolve(ctx =>
{
var ids = ctx.ArgumentValue<List>("ids");

});
```

**Comment by lazybnz** [comment]
> var ids = ctx.ArgumentValue<List>("ids");
you mean `var ids = ctx.ArgumentValue<List<int>>("ids");` ?
tried, didn't work

**Comment by lazybnz** [comment]
@PascalSenn yes i get it but it doesn't work
