### ISSUE TITLE
Banana Cake Pop does not carry over previous settings when creating new tab

### ISSUE THREAD

**Issue by ashwinGokhale** [ChilliCream/hotchocolate#4600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every time I create a new tab, I have to enter the settings over and over again. This is pretty annoying if you have a lot of settings (OAuth 2.0 settings for example) and/or a lot of tabs. I feel like the settings can be stored in localstorage or something so I don't have to type everything again.

### Steps to reproduce

1. Setup OAuth 2.0 settings for tab 1
2. Create a new tab
3. Click settings button and click Authorization tab
4. Type is "No Auth" instead of "OAuth 2.0"

### Product

Banana Cake Pop

### Version

12.4

**Comment by michaelstaib** [comment]
That is correct ... each tab is independent.  We are working on a new node for the tree call API which will allow to specify a GraphQL API under this node you can create folders and documents that will inherit the settings.

**Comment by michaelstaib** [comment]
cc @rstaib

**Comment by PascalSenn** [comment]
@ashwinGokhale  this is actually a feature at the moment, the reasoning is that you have multiple documents pointing to different apis. but we work on a better way for you to specify it once per document group

**Comment by rstaib** [comment]
This has been solved with APIs. Documents stored beneath an API will use the APIs Connection Settings. To use this feature one have to be signed-in.

1. Sign in
2. Create an API not Folder in the Document Explorer
3. Create documents beneath an API

https://github.com/ChilliCream/graphql-platform/assets/4325318/e866b2fd-bc3e-458b-a338-82b8d42e4174
