### ISSUE TITLE
Support customizing Guid + IdType serialization format

### ISSUE THREAD

**Issue by ryepup** [ChilliCream/hotchocolate#4607]
### Is your feature request related to a problem?

I'm integrating graphql with an existing RESTful backend, and having some trouble with serialization formats.

* REST endpoint serializes `Guid`s using the default `ToString`, which included dashes. This gets loaded into javascript memory
* HotChocolodate serializes `IdType` `Guid`s using format `N`, which does not have dashes. This gets loaded elsewhere into javascript memory
* javascript breaks when trying to compare/match up these ids that are rendered as different strings, one with and one without dashes.

### The solution you'd like

Something similar to #1234 / #1301; some way to configured the format specifier that's currently hard-coded to `N`:

https://github.com/ChilliCream/hotchocolate/blob/c162ca29c23acc69cf81a33155d7384ad4dc9d0f/src/HotChocolate/Core/src/Types/Types/Relay/IdSerializer.cs#L105

https://github.com/ChilliCream/hotchocolate/blob/c162ca29c23acc69cf81a33155d7384ad4dc9d0f/src/HotChocolate/Core/src/Types/Types/Relay/IdSerializer.cs#L233

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
Is switching to the Uuid scalar an option for you? With this you could control the serialization format: https://chillicream.com/docs/hotchocolate/defining-a-schema/scalars/#uuid-type

If you need to keep the Id scalar you could also do the ToString in your resolver. I'm not sure why the Id Type would serialize a return type of Guid differently than .ToString() in your REST API...

**Comment by ryepup** [comment]
> Is switching to the Uuid scalar an option for you? 

I think I could do that if stopped using any `ID` types in my graphql schema, and lose the semantics that go along with `ID`. It'd be nice if I could retain the meaning of `ID`.

> I'm not sure why the Id Type would serialize a return type of Guid differently than .ToString() in your REST API...

the web framework called [`Guid.ToString()`](https://docs.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=net-6.0), which internally defaults to the `D` format. HotChocolate's `IdSerializer` uses the `N` format, so they come out different.

My workaround for now is adding more JS.

**Comment by ryepup** [comment]
`IdSerializer` might be the wrong spot; I tried to implement my own `IIdSerializer` and register is via `AddIdSerializer`, but it my breakpoints don't get hit when I make requests.

**Comment by tobias-tengler** [comment]
The `IIdSerializer` is for Relay Ids (`[ID]`), if you are just using the `IdType` it does not apply (to my knowledge).

I was able to confirm that the serialization differs between the following resolvers:

```csharp
public class Query
{
    private static readonly Guid _guid = Guid.NewGuid();

    public Guid ReturnGuid => _guid;

    [GraphQLType(typeof(IdType))]
    public Guid ReturnIdGuid => _guid;

    public string ReturnStringGuid => _guid.ToString();

    [GraphQLType(typeof(IdType))]
    public string ReturnStringIdGuid => _guid.ToString();
}
```

```graphql
{
  returnGuid
  returnIdGuid
  returnStringGuid
  returnStringIdGuid
}
```
yields

```csharp
{
  "data": {
    "returnGuid": "21ded8a7-8010-4cb2-8f55-c72008f6d590",
    "returnIdGuid": "21ded8a780104cb28f55c72008f6d590",
    "returnStringGuid": "21ded8a7-8010-4cb2-8f55-c72008f6d590",
    "returnStringIdGuid": "21ded8a7-8010-4cb2-8f55-c72008f6d590"
  }
}
```

which doesn't look correct to me.

Generally your frontend shouldn't have to rely on the serialization format of a field marked as `ID`, but I agree that the current behavior is weird.

**Comment by ryepup** [comment]
Ok, I think this is where the `N` is coming from in my case: https://github.com/ChilliCream/hotchocolate/blob/ab9724b2c8d4cf7d4bd9109f57f9e2cebded7b90/src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.Setup.cs#L92

I was able to make a workaround using `IChangeTypeProvider`s, based on the code for `HotChocolate.Utilities.DefaultTypeConverter`:

```csharp
class GuidFormatter : IChangeTypeProvider
{
    bool IChangeTypeProvider.TryCreateConverter(Type source, Type target, ChangeTypeProvider root, [NotNullWhen(true)] out ChangeType converter)
    {
        if (source == typeof(Guid) && target == typeof(string))
        {
            converter = Format;
            return true;
        }
        converter = null;
        return false;
    }

    private static object Format(object input)
        => input is Guid g
            ? g.ToString()
            : default(string);
}
```
Then I register that during statup:
```csharp
services.AddSingleton<IChangeTypeProvider, GuidFormatter>();
```

**Comment by michaelstaib** [comment]
Yes ... and you can override this.... 

```
services.AddGraphQLServer()
   .AddTypeConverter.....
```

**Comment by ryepup** [comment]
Thanks @michaelstaib, that's exactly what I was missing.
