### ISSUE TITLE
Apollo Federation SubGraph Support

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#4622]
- [ ] Integrate into deployment
- [ ] Fix Test Issues
- [ ] Test Suite

**Comment by W3Max** [comment]
Hi @michaelstaib !

Sorry if the question is dumb, I am new to the ChilliCream GraphQL Platform, but will it be possible (or is it already) to federate a SubGraph (HotChocolate) from Apollo gateway federation server or vice versa?

Is this what this issue is about? And if yes, do you have any timeframe (rough estimate) for this feature (I guess HC-12.6.0)?

Thank you!

**Comment by michaelstaib** [comment]
It will be possible vice versa... 12.6 you can make Hot Chocolate a SubGraph and with Hot Chocolate Stitching update you can also use the HotChocolate Gateway to integrate Apollo Federation Compatible Subgraphs.

We will start with previews next week. Final release is expected in February.

**Comment by michaelstaib** [comment]
Here is an example how this will work:
https://github.com/ChilliCream/hotchocolate/tree/main/src/HotChocolate/ApolloFederation/examples/ApolloFederation.OfficialDemo

**Comment by W3Max** [comment]
Thank you, that is fantastic!

Being able to easily mix technologies like that is really great.

I don't want to overstay my welcome, but would you accept to state the differences between Apollo Federation and Hot Chocolate Stitching? I'm also new to the whole federation/stitching thing. We are currently using one huge graph, but I would like to change that in a near future and I am wondering which solution we should use.

I also stumbled upon this talk [Reintroducing Schema Stitching in 2021](https://www.youtube.com/watch?v=hOdGL3DepDM) and I like the idea of combining unannotated graphs.

Anyway, thank you for this project. I am looking forward to try it!

**Comment by GoAnyway** [comment]
Hello @michaelstaib !

Can you please tell me why "FederationSchemaPrinter" removes all scalars from the schema?

Because of this, the ApolloFederation Gateway does not accept a schema that defines a type that has a field with a type, such as DateTime (which is also a scalar), because "FederationSchemaPrinter" removes the DateTime scalar definition from the schema.

**Comment by michaelstaib** [comment]
Could be a bug will have a look.

**Comment by GoAnyway** [comment]
Thanks!

**Comment by michaelstaib** [comment]
We are done with most of the work and have submitted the current version to testing with apollo:
https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/56

We reached the following result locally:
| Framework | _service | @key (single) | @key (multi) | @key (composite) | @requires | @provides | @ftv1 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| hotchocolate | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ❌ |

We will implement @ftv1 (federation tracing support) with the next iteration.

In the next previews, we will refine a couple of things like the reference resolver more, but as of preview 5, we are supporting all federation features.

I am closing this issue since we are done. Have fun everyone!

**Comment by michaelstaib** [comment]
@W3Max  join us on slack.chillicream.com we will soon start with previewing the Hot Chocolate Gateway.

**Comment by killjoy2013** [comment]
> Here is an example how this will work: https://github.com/ChilliCream/hotchocolate/tree/main/src/HotChocolate/ApolloFederation/examples/ApolloFederation.OfficialDemo

@michaelstaib  URL must have been changed,  page not found.  Where to find it?

**Comment by killjoy2013** [comment]
Hi,



> I think it is now [here](https://github.com/ChilliCream/hotchocolate/tree/main/src/HotChocolate/ApolloFederation/examples)

Thank you @tobias-tengler 

I'm trying to add a hotchocolate 12 subgraph to my existing Apollo federation using .net 5.0. Unfortunately receiving

```ts
(node:27900) UnhandledPromiseRejectionWarning: Error: Couldn't load service definitions for "supplier" at http://localhost:3003/graphql: 400: Bad Request
    at C:\dev\git\dev.to\graphql.net-in-apollo-federation\federation-gateway\node_modules\@apollo\gateway\src\supergraphManagers\IntrospectAndCompose\loadSer    at C:\dev\git\dev.to\graphql.net-in-apollo-federation\federation-gateway\node_modules\@apollo\gateway\src\supergraphManagers\Introsp
vicesFromRemoteEndpoint.ts:77:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at loadServicesFromRemoteEndpoint (C:\dev\git\dev.to\graphql.net-in-apollo-federation\federation-gateway\node_modules\@apollo\gateway\src\supergraphManagy\src\supergraphManagers\IntrospectAndCompose\loadServicesFromRemoteEndpoint.ts:81:30)

```

csproj

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	  <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="graphiql" Version="2.0.0" />
    <PackageReference Include="HotChocolate.Abstractions" Version="12.6.2" />
	  <PackageReference Include="HotChocolate.AspNetCore" Version="12.6.2" />	 
    <PackageReference Include="HotChocolate.ApolloFederation" Version="12.6.2" /> 	 
  </ItemGroup>
</Project>
```

startup.cs;

```c#
 public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {   
            services
                .AddGraphQLServer()
                .AddApolloFederation()
                .AddQueryType<Query>();                 

            services.AddGraphiQl(x =>
            {
                x.GraphiQlPath = "/graphiql-ui";
                x.GraphQlApiPath = "/graphql";
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseGraphiQl();
                   
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGraphQL();
            });

        }
```

Sample project [https://github.com/killjoy2013/hotchocolate-apollo-federation](https://github.com/killjoy2013/hotchocolate-apollo-federation)

What am I missing? 

Thanks

**Comment by michaelstaib** [comment]
Not an answer to your problem :) but you do to need:

```
            services.AddGraphiQl(x =>
            {
                x.GraphiQlPath = "/graphiql-ui";
                x.GraphQlApiPath = "/graphql";
            });
```

since we will automatically provide an IDE on the '/graphql' route.

**Comment by michaelstaib** [comment]
Join us on slack: 

https://slack.chillicream.com

on slack we have a ApolloFederation group where you can find help.
