### ISSUE TITLE
The name .. was already registered by another type. ...

### ISSUE THREAD

**Issue by jkears** [ChilliCream/hotchocolate#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Mongo Data Provider and am getting an exception when Query type includes two top-level object types (different types), when each has an object type **by the same name** but but of different type. 

### Steps to reproduce

Create two similar types as follows;  note that they **both contain a property named BCs** but of different types...

```
namespace Service1Test1SM
{
    [DataContract]
    [ProtoContract]
    [Serializable]
    [BsonIgnoreExtraElements]
    [Node(
    IdField = nameof(Id),
    NodeResolverType = typeof(Test1NodeResolver),
    NodeResolver = nameof(Test1NodeResolver.ResolveAsync))]
    public class Test1  
    {
      
        [ProtoMember(1)]
        [Field(Settable = false)]
        [DataMember]
        public string Comments { get; set; }

        [ProtoMember(2)]
        [Field(Settable = false)]
        [DataMember]
        public string SomeProp { get; set; }

        [ProtoMember(3)]
        [Field(Settable = false)]
        [DataMember]
        public ObservableCollection<Service1Test1SM.BC> BCs { get; set; }

        [ProtoMember(4)]
        [Field(Settable = false)]
        [DataMember]
        public Service1Test1SM.NumberTypes NumberTypes { get; set; }

        [ProtoMember(5)]
        [Field(Settable = false)]
        [DataMember]
        [BsonId(IdGenerator = typeof(GuidGenerator)), BsonRepresentation(BsonType.String)]
        public System.Guid Id { get; set; }
    }
}
```
```
namespace Service1Test2SM
{
    [DataContract]
    [ProtoContract]
    [Serializable]
    [BsonIgnoreExtraElements]
    [Node(
    IdField = nameof(Id),
    NodeResolverType = typeof(Test2NodeResolver),
    NodeResolver = nameof(Test2NodeResolver.ResolveAsync))]
    public class Test2 
    { 
 
        [ProtoMember(1)]
        [Field(Settable = false)]
        [DataMember]
        public string Property1 { get; set; }

        [ProtoMember(2)]
        [Field(Settable = false)]
        [DataMember]
        public ObservableCollection<Service1Test2SM.BC> BCs { get; set; }

        [ProtoMember(3)]
        [Field(Settable = false)]
        [DataMember]
        [BsonId(IdGenerator = typeof(GuidGenerator)), BsonRepresentation(BsonType.String)]
        public System.Guid Id { get; set; }
    }
}
```

Create Query Type as follows;

```
namespace GarthWare.TestModel1.Service1.API.AggregateRoots.Test1Aggregate.GraphQL
{


    public class Query
    {

        private readonly IService1CommandDispatcher _commandDispatcher;
        private readonly IMapper _mapper;
        private readonly IExecutionContextAccessor _executionContextAccessor;
        private readonly ILogger _logger;

        public Query(IService1CommandDispatcher commandDispatcher, IMapper mapper, IExecutionContextAccessor executionContextAccessor, ILogger logger)
        {
            _commandDispatcher = commandDispatcher;
            _mapper = mapper;
            _executionContextAccessor = executionContextAccessor;
            _logger = logger;
        }


        //[UsePaging]
        [UseProjection]
        [UseSorting(typeof(Service1Test1SM.Test1))]
        [UseFiltering(typeof(Service1Test1SM.Test1))]
        public IExecutable<Service1Test1SM.Test1> GetTest1s([Service] IMongoCollection<Service1Test1SM.Test1> collection)
        {
            return collection.AsExecutable();
        }

        [UseFirstOrDefault]
        public IExecutable<Service1Test1SM.Test1> GetTest1ById(
            [Service] IMongoCollection<Service1Test1SM.Test1> collection,
            Guid id)
        {
            return collection.Find(x => x.Id == id).AsExecutable();
        }

        //[UsePaging]
        [UseProjection]
        [UseSorting(typeof(Service1Test2SM.Test2))]
        [UseFiltering(typeof(Service1Test2SM.Test2))]
        public IExecutable<Service1Test2SM.Test2> GetTest2s([Service] IMongoCollection<Service1Test2SM.Test2> collection)
        {
            return collection.AsExecutable();
        }

        [UseFirstOrDefault]
        public IExecutable<Service1Test2SM.Test2> GetTest2ById(
            [Service] IMongoCollection<Service1Test2SM.Test2> collection,
            Guid id)
        {
            return collection.Find(x => x.Id == id).AsExecutable();
        }
  
    }
}

```

### Relevant log output

```shell
[garthware-testmodel1-service1-api_d8f6316c-1]: Unhandled exception. HotChocolate.SchemaException: For more details look at the `Errors` property.
[garthware-testmodel1-service1-api_d8f6316c-1]:
[garthware-testmodel1-service1-api_d8f6316c-1]: 1. The name `ListFilterInputTypeOfBCFilterInput` was already registered by another type. (HotChocolate.Data.Filters.ListFilterInputType<HotChocolate.Data.Filters.FilterInputType<Service1Test2SM.BC>>)
```

### Additional Context?

This is the domain model schema, I've highlighted the offending types, however they are not of the same type.

![image](https://user-images.githubusercontent.com/1290937/148633164-339d2bdc-1318-4ce6-87d3-9671077ab5f2.png)

It would be quite common to have top level aggregates that have properties of the same name with different types. 

### Product

Hot Chocolate

### Version

12.3.0

**Comment by PascalSenn** [comment]
This is the intended behaviour. 

*To solve your problem:*
The object type gets the name from the runtime type and there the type names must be unique. Thats why you run into a collision.
I guess as you intend to generate most of you code, you can either `[GraphQLTypeName("TheTypeName")]` onto your class or you can just override the `INamingConvention`. In the INamingConvention you can controll how you classes are named. You could for example include parts of the namepspace. 

Though,

**Comment by PascalSenn** [comment]
This is the intended behaviour. 

**To solve your problem:**
The object type gets the name from the runtime type and there the type names must be unique. Thats why you run into a collision.
I guess as you intend to generate most of you code, you can either `[GraphQLTypeName("TheTypeName")]` onto your class or you can just override the `INamingConvention`. In the INamingConvention you can controll how you classes are named. You could for example include parts of the namepspace. 

**Regarding duplicated type name**
You should also investigate why you have duplicated type names. A clean graphql schema should have good names for types and fields. If you have an issue with collidning type names and intend to use the same type name, then you probably have a flaw in the schema design. i can recommend the book of Marc andre www.productionreadygraphql.com as a reference for good schema design :)

**Comment by jkears** [comment]
@PascalSenn, thank you for your prompt reply.  I suppose I need to start testing with real domain models and not at 2am in the morning having worked 18 hours prior.   I am cool with everything that you said.  We would likely never have two different types with the same name in the same domain service and in a good way, it was good that HC bailed on this scenario.  

So far the code changes we will be required to make to our Roslyn code generator are quite minimal.  We currently code-generate to REST and gRPC integrations and the Query and Mutation type requirements are nearly identical, except we call an mutation input a request, and we will need to generate the exception attributes to on our mutations, but beyond all of that this will plug in nicely. 

We are also able to fully automate the creation of the stitching files on relating types as we capture all of that detail within the domain model.  

We are currently working on a UI Designer for Blazor which will code generate the Blazor apps, and we will use GraphQL to support that tool.   One of the things that really pleased me was the Reactive type support you have on the client side, as we code generate Reactive.UI ViewModels which those reactive types will integrate well with.   We will likely include Subscriptions as an option to include within our generated ViewModels as a first-class integration.  

As for your recommendation of  book of Marc Andre's book, it seems like it won't be published until March sometime, but I am enjoying his blog postings and I thank you for that valuable reference.  

We will soon be creating many core and sub domains through our tooling and I look forward to seeing how this all bolts together with HC and Strawberry Shake on Blazor.  I will reach out to you once we have real models to show you what we have created.  

Once again thank-you so much for your timely support!

**Comment by jkears** [comment]
@PascalSenn rightly pointed out that the issue was on my test model.
