### ISSUE TITLE
Filtering is not working for nested object

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/hotchocolate#4634]
Hi,

Using Annotation Based - Filtering, we are generating GQL Schema. 

My Schema is loading fine and I can execute queries and get response. Problem is while applying filter condition,it returns entire data as response,data is not filtered properly. Let say,this is my GQL Query with filter condition:

```
{
  getEquipmentLocationDetails(actionflag:"Tree"
  eqporLoc:"L",where:{
    data:{
      some:{
        EqpLocCode:{eq:"00001"}
      }
    }
    
  }){
    data{
      Childflag
      EqpLocCode
    }
  }
}
```
What I am expecting is,it should return data which matches the filter condition but it returns entire data.

Also getting the same behaviour while applying AND filter also:

```
{
  getEquipmentLocationDetails(actionflag:"Tree"
  eqporLoc:"L",where:{
    and:[
        { data:{some:{EqpLocCode:{eq:"as"}}}}
        { data:{some:{Childflag:{eq:"0"}}}}
      ]
    
  }){
    data{
      Childflag
      EqpLocCode
    }
  }
}
```

My schema registry in startup.cs  be like :
        
```
  servicecollection.AddGraphQLServer("test")
            .AddQueryType<EqpMetaData>()
            .AddFiltering()
```
Resolver and Type Definition class is implemented similar to the attached file :

EqpMetaData.cs : [EqpMetaData.cs.txt](https://github.com/ChilliCream/hotchocolate/files/7846958/EqpMetaData.cs.txt)

sample Response with and without filtering :
 
[Response.txt](https://github.com/ChilliCream/hotchocolate/files/7847042/Response.txt)

Is any other way to apply filter? How to add filtering for nested object in annotation-based approach and what does "some","any" and "all" mean in filters? 

### Product

Hot Chocolate

### Version

12.4.1

Thanks !

**Comment by PascalSenn** [comment]
you apply filtering on a field that returns `Response` and not on the list itself.

Inject `IResolverContext` into you resolver and apply filtering on `response.Data.Filter(context)`

**Comment by Sangeetha-Murugesan** [comment]
Hi @PascalSenn , any sample for applying filter on nested object. It may help!

**Comment by PascalSenn** [comment]
This is because you try to filter on a single item instead of a list 
```
[HotChocolate.Data.UseFiltering(typeof(FilterInputType<TheTypeOfDataProperty>)]
        public async System.Threading.Tasks.Task<Response> getEquipmentLocationDetailsAsync(IResolverContext res, string eqporLoc, string actionflag, string eqpLocCode, string eqpLocDesc, System.Threading.CancellationToken cancellationToken)
        {

                string response = ""; //some serialised response;
                var data = (JsonConvert.DeserializeObject<Response>(response));
                data.Data.Filter(res);
                return data;
        }
  ```

**Comment by Sangeetha-Murugesan** [comment]
Using [HotChocolate.Data.UseFiltering(typeof(FilterInputType<EqpMetaDataInfo>)] also not filtering data properly. So what I tried was,just added the [UseFiltering] attribute in the data field like below:

 ```
public class Response
    {
        [HotChocolate.Data.UseFiltering]
        [GraphQLName("data")]
        public EqpLocDetInfo[] Data { get; set; }

        [GraphQLName("message")]
        public string Message { get; set; }

    }
```
It resolved my issue and now filtering is working properly.

Thanks for your response!!
