### ISSUE TITLE
Xml documentation for Record properties is not published in schema

### ISSUE THREAD

**Issue by Euphoric** [ChilliCream/hotchocolate#4636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Records use different way to add xml documentation to their properties than classes. This is supported in IDE.
Right now, xml documentation for properties is not published in schema, while the summary for the type is.

### Steps to reproduce

1. Create record with XML documentation for it's properties. (see https://stackoverflow.com/a/64955905/463623)
2. Expose that record as part of GraphQL schema
3. Schema documentation is not generated from XML documenation for properties.

Example record:
```
/// <summary>
/// Represents a car.
/// </summary>
/// <param name="CarId">The id of the car.</param>
/// <param name="Cylinders">The number of cylinders.</param>
/// <param name="Make">The make of the car.</param>
/// <param name="Model">The model of the car.</param>
public record Car(int CarId, int Cylinders, string Make, string Model);
```

Expected:
```
"Represents a car."
type Car{
  "The id of the car."
  carId:Int!
  "The number of cylinders."
  cylinders:Int!
  "The make of the car."
  make:String!
  "The model of the car."
  model:String!
}
```

Got:
```
"Represents a car."
type Car{
  carId:Int!
  cylinders:Int!
  make:String!
  model:String!
}
```

### Product

Hot Chocolate

### Version

12.4.1

**Comment by PascalSenn** [comment]
I think this is a roslyn issue https://github.com/dotnet/roslyn/issues/52663

**Comment by PascalSenn** [comment]
Workaround:
```csparp
/// <summary>
/// Represents a car.
/// </summary>
/// <param name="CarId">The id of the car.</param>
/// <param name="Cylinders">The number of cylinders.</param>
/// <param name="Make">The make of the car.</param>
/// <param name="Model">The model of the car.</param>
public record Car(
 [property: GraphQLDescription("The id of the car.")]int CarId,
 ....);
```

**Comment by Euphoric** [comment]
@PascalSenn Thanks for clarifying and providing a workaround. I wasn't aware they are planning expanding the xml doc implementation in compiler. I guess it is sensible for HotChoco team to wait for that to be implemented instead of creating custom logic for current implementation.

**Comment by michaelstaib** [comment]
Closing this issue since we will just wait for the Roslyn team to implement the new XML syntax.
