### ISSUE TITLE
Update Hot Chocolate Get Started with new BCP screenshots

### ISSUE THREAD

**Issue by qazaljalilian** [ChilliCream/hotchocolate#4637]
### Is your feature request related to a problem?

I am following this : https://chillicream.com/docs/hotchocolate/get-started but it's not up to date!
the IDE doesn't even look like that anymore and I don't seem to see the files that I expect to see

### The solution you'd like

please update the documentations!

### Product

Banana Cake Pop

**Comment by tobias-tengler** [comment]
I have already started to update the guide in #4451, but I'm waiting on another UI Refresh planned for 12.5.0, before finalizing the screenshots. :)

**Comment by qazaljalilian** [comment]
okay great! I also found out your template demo code has different classes than the one in the explanation, just wanted to let you know :)
