### ISSUE TITLE
Order By Child-Parent-Child Yields "There can be only one input field named Child"

### ISSUE THREAD

**Issue by bbingCGI** [ChilliCream/hotchocolate#4657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ordering requires a sequential narrative presently, such as "order by Last Name, then by First Name, then by Age".  Because of this, if a query needs to order by parent and child properties where the child's properties are not back-to-back, the dreaded "There can only be one input field named Child" will appear.

### Steps to reproduce

I've [created a repository](https://github.com/bbingCGI/HotChocolate.Issues.OrderBy) to pull down and demonstrate the following example.

1. Ensure the root entity represented in the query has at least one child.
2. Order by a child property, then parent property, then child.
3. Attempt to execute the query

Sample query
```
query {
  people (order: {
    demographic: { gender: ASC }
    address: { state: ASC }
    demographic: { age: ASC }
  }) {
    lastName
    demographic {
      gender
      age
    }
    address {
      city
      state
    }
  }
}
```

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "There can be only one input field named `demographic`.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "people"
      ],
      "extensions": {
        "field": "demographic",
        "specifiedBy": "http://spec.graphql.org/October2021/#sec-Input-Object-Field-Uniqueness"
      }
    }
  ]
}
```

### Additional Context?

Note that this only applies to order.  Filters don't care about what order they are entered and can be grouped by child objects.

A possible workaround would be to use the array option like the where's `and` and `or` can use:
```
query {
  people (order: [
    { demographic: { gender: ASC } }
    { address: { state: ASC } }
    { demographic: { age: ASC } }
  ]) {
    lastName
    demographic {
      gender
      age
    }
    address {
      city
      state
    }
  }
}
```

### Product

Hot Chocolate

### Version

12.5.0

**Comment by bbingCGI** [comment]
Being as changing order from an object descriptor to an array, that would be a breaking change.  Perhaps adding a operation like the `and` operation in the filter convention would keep it from breaking existing functionality.  Something like `all`?

```
query {
  people (order: { all: [
    { demographic: { gender: ASC } }
    { address: { state: ASC } }
    { demographic: { age: ASC } }
  ]}) {
    lastName
    demographic {
      gender
      age
    }
    address {
      city
      state
    }
  }
}
```

**Comment by PascalSenn** [comment]
order is already an array, so you can do
```graphql
query {
  people(
    order: [
      { demographic: { gender: ASC } }
      { address: { state: ASC } }
      { demographic: { age: ASC } }
    ]
  ) {
    lastName
    demographic {
      gender
      age
    }
    address {
      city
      state
    }
  }
}

```
