### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'Void HotChocolate.Execution.Serialization.JsonQueryResultSerializer..ctor(Boolean)'.'

### ISSUE THREAD

**Issue by MeaningOfLights** [ChilliCream/hotchocolate#4664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upgrading https://github.com/binarythistle/S04E01---.NET-5-GraphQL-API to work on .Net 6. I set the Framework to 6, updated the DLL's to stable v12.5 and running the project I get the error:

System.MissingMethodException: 'Method not found: 'Void HotChocolate.Execution.Serialization.JsonQueryResultSerializer..ctor(Boolean)'.'

The source code has the method (https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/Serialization/JsonQueryResultSerializer.cs) and the Constructors bool is an optional parameter. Even the latest change with the 2nd Encoder argument couldn't cause the problem.

I reverted the HotChocolate.AspNetCore back to v11 and issued a dotnet build which failed with same error. 

Then I upgraded the to 12.5 and the error went away. 

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12.5.0

**Comment by tobias-tengler** [comment]
Errors like this usually happen if you have two HotChocolate.* packages with different version numbers in the same project. I see that your csproj also contains HotChocolate.Data. Is it possible that you only updated one of the packages when you received the error?

**Comment by MeaningOfLights** [comment]
I'm sure its either of those solutions &/or a close project (delete obj, bin folders and .suo file) and reopen.

I raised this issue because the error message didn't exist on the internet until now.
