### ISSUE TITLE
Method not foun 'void HotChocolate.language.FieldNode..ctor

### ISSUE THREAD

**Issue by ptufail** [ChilliCream/hotchocolate#4665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to create new GraphQl Client on VisualStudio 2022 with WASM .Net 6, and when i press Ok to create i received this error 

(HotChocolate.Language.Location,HotChocolate.Language.NameNode,Hotchocolate.Language.NameNode,System.Collections.Generic.IreadOnlyList'1<Hotchocolate.Language.DirectiveNode>,System.Collections.GEneric.IReadOnlyList'1<Hotchocolate.Language.ArgumentNode>,HotChocolate.Language.SelectionSetNode)'.

### Steps to reproduce

1. Right Click on Project
2. Add GraphQL Client
3. Fill the form
4. Press Ok

### Product

Strawberry Shake

### Version

12.5.0

**Comment by michaelstaib** [comment]
This seems like a dirty state in Visual Studio. We were unable to reproduce this.
