### ISSUE TITLE
Support S.T.Json source generation in .AspNetCore pkg

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#4673]
### Is your feature request related to a problem?

Benefits detailed in the announcement post [here](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#how-source-generation-provides-benefits).

### The solution you'd like

Similar setup to how they detail it [here](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#mvc-webapis-signalr-houdini) for ASP.NET MVC (although their code sample is wrong, it should be as below, with AddContext<T> coming off the `JsonSerializerOptions`).

Since we probably want to still restrict the json serialization heavily to be gql spec compliant, maybe we don't expose the full `System.Text.jJson.JsonSerializerOptions` that is used, but just have an explicit ext method to add the context.

```c#
[JsonSerializable(typeof(WeatherForecast[]))]
internal partial class MyJsonContext : JsonSerializerContext { }

// ASP.NET MVC
services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.AddContext<MyJsonContext>());

// Hot Chocolate
IRequestExecutorBuilder
    .AddJsonSerializerContext<MyJsonContext>() // where TContext : JsonSerializerContext, new()
```

I imagine it'd then be a matter of folks annotating the context with the attribute for all the types they expose out of their schema (if we could do that for them via, bonus). But I'm honestly not too familiar with how serialization works in HC. Maybe this is all custom process and this won't work?

Also consider if deserialization could be improved, but I think that's an entirely custom deserialization process, right? So this wouldn't help there.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We use the JsonWriter so a low level api to serialise results. Further we user optimised result objects that cannot just be serialized. So from a performance perspective I cannot see where this should gain something for us? What is the use-case you want to solve?
