### ISSUE TITLE
Is Hybrid model supported ?

### ISSUE THREAD

**Issue by muralidd** [ChilliCream/hotchocolate#4675]
### Is your feature request related to a problem?

We are trying to use a Schema first approach i.e loading the the SDL schema and then loading the equivalent C# type class. This works fine . With this approach , during start up time
1 . Can we leverage the built-in sorting, filtering , and paging capability of the HC middleware using object field descriptor?

2 . Can we add dynamic fields using object type extension ?

Please guide . Thanks

### The solution you'd like

Hybrid approach should work = LoadDocfromfile + C#Types + Object type extension

### Product

Hot Chocolate

**Comment by muralidd** [comment]
@PascalSenn - Thanks for your reply . We forked your sample repo and tried the schema way along with types. It is giving a problem. Appreciate your help and pointers for resolving the same.

Fork url - https://github.com/muralidd/DoMoreWithLessCodeInHotChocolate

![image](https://user-images.githubusercontent.com/27189210/150838262-e2e1b570-5310-42d0-b4a8-faaf786f41ba.png)

**Comment by michaelstaib** [comment]
I am closing this issue since this is neither bug nor an enhancement. For questions either use slack.chillicream.com or the Github discussions. I can recommend the slack channel.
