### ISSUE TITLE
Authorization fails on multiple authentication schemes (JWT Bearer)

### ISSUE THREAD

**Issue by davidjohanssonbf** [ChilliCream/hotchocolate#4680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Im unable to get multiple authentication schemes to work with HotChocolate.

We have some users in local db and some in Azure AD. So this is a must for us.

I have followed Microsoft's documentation as per below on how to implement this:
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-6.0#use-multiple-authentication-schemes

Quote from the documentation:
_The controller then accepts requests with JWT issued by the first or second issuer._

This is the feature we're after. I can get authentication to work with either one, but not with both.

Am I missing something in terms of how things have to be setup in HotChocolate or is this not supported yet?

### Steps to reproduce

````
.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidAudience = TokenSettings.Audience,
        ValidateAudience = true,
        ValidIssuer = TokenSettings.Issuer,
        ValidateIssuer = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration["JwtPassword"])),
        ValidateIssuerSigningKey = true,
    };
})
.AddJwtBearer("Auth0", options =>
{
    options.Audience = TokenSettings.Audience;
    options.Authority = TokenSettings.Authority;
});
````

````
.AddAuthorization(options =>
{
    var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme, "Auth0");

    defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();

    options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
});
````

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "private"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    }
  ]
}
```

### Product

Hot Chocolate

### Version

12.5.0

**Comment by tobias-tengler** [comment]
Closing, since this is a duplicate of #4333

**Comment by davidjohanssonbf** [comment]
I just wanted to let everyone who stumbles upon this issue to know that the workaround provided in #4333 is indeed working.
