### ISSUE TITLE
Application Stops Responding

### ISSUE THREAD

**Issue by pedro-coelho-ff** [ChilliCream/hotchocolate#4688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I have an issue where my application just stops or takes a long time to respond to the requests.

The application is working fine and all of a sudden we can see and downfall on the rps, the CPU also drops.

Response time:
![image](https://user-images.githubusercontent.com/81172893/151066330-d0107a4f-6a4c-4efa-a81a-d70ab538deab.png)

Throughput:
![image](https://user-images.githubusercontent.com/81172893/151066416-c3cae9b2-e73e-4111-bb08-6156952c1067.png)

CPU:
![image](https://user-images.githubusercontent.com/81172893/151066523-f8faa2f7-23a6-4238-ab04-a2cd9ad26732.png)

Memory:
![image](https://user-images.githubusercontent.com/81172893/151066620-5d042dd6-3a71-4c82-aea4-349b4cbae8f0.png)

This started happening when we migrated from version 11 to 12, also this is happening from time to time and we have yet to identify the root problem.

On version 12.3.2 we had the same behavior but we also had this error

```
at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
```

On version 12.5.0 we don't see any error but like I said before have the same behavior as on the previous version.

We were able to perform a thread profiler but it doesn't give much info.
![image](https://user-images.githubusercontent.com/81172893/151067231-07e3a88e-c10f-4a48-83e6-eafb8fa43a67.png)

Performing some search for something similar we stumbled upon this on Github https://github.com/mgravell/Pipelines.Sockets.Unofficial/issues/28 that references this post https://blog.marcgravell.com/2019/02/fun-with-spiral-of-death.html

The application is a gateway with a local schema and with federated schema with polling on with only one domain service.

Can someone help?

.Net Version - 3.1
HotChocolateVersion - 12.5.0

**Comment by michaelstaib** [comment]
It seems this is related to a bug in .NET Core 3.1. Have you tried to update to .NET 6?

**Comment by pedro-coelho-ff** [comment]
We are in the process of migrating to .Net 6 and that can take some time.

Still, I find it hard to believe that it's an issue with .Net Core 3.1 like I said before when with were using version 11 of HotChocolate this didn't happen, maybe we were just lucky don't know.

I think that the problem is somewhere with the use of the SemaphoreSlim that we use on our application and also if I'm not mistaken the HotChocolate engine also uses.

**Comment by michaelstaib** [comment]
Just read the blog you posted and there he stated that the issue was a bug in the SemaphoreSlim. I have not looked into this specific issue yet since I thought that kind was your conclusion :)

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/RequestExecutorProxy.cs
