### ISSUE TITLE
Enum does not place underscore before digit

### ISSUE THREAD

**Issue by tauchmi** [ChilliCream/hotchocolate#4690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

we are using multiple GraphQL implementations on our services and experienced an issue when switching to HotChocolate with Enum values.

`public enum Strategy
    {
        Active1,
        Active2,
        Active3,
    }`

We do get this values now as "ACTIVE1"... from HotChocolate, while other implementations do give "ACTIVE_1"... So placing an underscore before the digit.

As per spec https://spec.graphql.org/October2021/#sec-Names I would read it as the underscore is to be used.

### Steps to reproduce

`[InlineData("Active3", "ACTIVE_3")]`
`        public void GetEnumName(string runtimeName, string expectedSchemaName)`

Reproducable via the 

HotChocolate.Types.Descriptors DefaultNamingConventionsTests

Added the above InlineData for testing

### Product

Hot Chocolate

### Version

11.2.2

**Comment by PascalSenn** [comment]
Spec wise this is not an issue 

>A Name must not be followed by a NameContinue. In other words, a Name token is always the longest possible valid sequence. The source characters a1 cannot be interpreted as two tokens since a is followed by the NameContinue 1.

Where NameContinue can be Letter Digit or _. So it is a valid GraphQL Name.
It's more a matter of how you want to split it :) 

You can override the naming convetions 
```csharp
    public class CustomNamingConventions : DefaultNamingConventions {
        public override NameString GetEnumValueName(object value)
        {
            return base.GetEnumValueName(value);
        }
    }
```
```
services.AddGraphQLServer.AddConvention<INamingConventions, CustomNamingConventions>();
```

**Comment by michaelstaib** [comment]
@PascalSenn exactly. Also, you are referring to the wrong spec section if you are referring to enum names.

https://spec.graphql.org/October2021/#sec-Enum-Value

> Enum values are represented as unquoted names (ex. MOBILE_WEB). It is **recommended** that Enum values be “all caps”. Enum values are only used in contexts where the precise enumeration type is known. Therefore it’s not necessary to supply an enumeration type name in the literal.

**Comment by tauchmi** [comment]
Apologies for referencing the wrong spec section. Will go with the custom naming convention then.
