### ISSUE TITLE
Add bulk Apollo Federation entity resolver method

### ISSUE THREAD

**Issue by GoAnyway** [ChilliCream/hotchocolate#4698]
### Is your feature request related to a problem?

At the moment, when Apollo Gateway sends a request to get N entities of the same type, you have to make N calls to the repository, which greatly reduces the performance of the request.

### The solution you'd like

The ability to create a bulk method for each entity type, which would receive not one argument, but a collection as input.

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
@GoAnyway 
Isn't this what DataLoaders are for? https://chillicream.com/docs/hotchocolate/fetching-data/dataloader

**Comment by GoAnyway** [comment]
@PascalSenn Yes, that's what I needed. Thanks!
