### ISSUE TITLE
Add backwards compatibilty for PaginationAmount when upgrading from HC10.4 to HC12

### ISSUE THREAD

**Issue by sgabler-solytic** [ChilliCream/hotchocolate#4706]
### Is your feature request related to a problem?

We are currently in the process of migrating from HC 10.4 to HC 12. Yes, we are late with that :sweat_smile: We now hit a small issue.

A mobile app uses the following query:

```graphql
query FETCH_SITES($first: PaginationAmount) {
  sites(first: $first) {
  nodes {
    eid
    name
  }
  totalCount
  __typename
  }
}
```

Variables:
```json
{
  "first": 10
}

```

But `PaginationAmount` was removed in HC11, so those queries will throw errors after upgrading. The error message tells me that we should use `Int` instead of `PaginationAmount`.

I found [instructions regarding backwards compatibility for PaginationAmount in the Stitching section](https://chillicream.com/docs/hotchocolate/api-reference/migrate-from-10-to-11/#paginationamount), but those don't apply for what I'm trying to do according to @michaelstaib (clarified via slack).

### The solution you'd like

It would be nice if we can migrate from HC10.4 to HC12 without breaking backwards compatibility. I assume that's only possible by keeping PaginationAmount somehow.

### Product

Hot Chocolate

**Comment by sgabler** [comment]
Thank you @michaelstaib 

For future reference, this can be enabled like this:

```csharp
services
    .AddGraphQLServer()
    .AddQueryType<QueryType>()
    .SetPagingOptions(new PagingOptions { LegacySupport = true })
```

**Comment by sgabler-solytic** [comment]
@michaelstaib I upgraded now from 12.7.0-preview.41 to v12.7.0 and the `LegacySupport` field is no longer there. Was it removed by accident?

![image](https://user-images.githubusercontent.com/55686147/163404622-a34a41a8-2283-474f-9982-f2354b324a36.png)

Or is there now a different way of doing this?
