### ISSUE TITLE
Allow to map MapGraphQLHttp and MapGraphQLWebSocket to same endpoint

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4707]
### Is your feature request related to a problem?

_Taken from #4287 for better trackability_

Trying to have `MapGraphQLHttp` and `MapGraphQLWebSocket` co-exist at `/graphql` yields the following exception:

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

Hot Chocolate GraphQL HTTP Pipeline
Hot Chocolate GraphQL WebSocket Pipeline
```

In theory mapping them both to the same URL should be no problem, because they use different schemes.

- `https://localhost/graphql`
- `ws://localhost/graphql`

### The solution you'd like

Allow to map the individual middleware to the same endpoint.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Not planned since you have `MapGraphQL` for it. We created `MapGraphQLHttp` and `MapGraphQLWebSocket` to explicitly not have them on the same route.

If you want to have them on the same route use `MapGraphQL` and pass in options for things you want to exclude.
