### ISSUE TITLE
[ID] attribute does not deserialize base64 encoded string to an int in a Query

### ISSUE THREAD

**Issue by Kricke242** [ChilliCream/hotchocolate#4713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [ID] attribute on an id parameter in a Query stopped working in version 12.6, i.e converting a base64 encoded relay type id string to int. 
It works in 12.5 and earlier. 
Note: We dont use Relay i.e. AddGlobalObjectIdentification since we have stiched services, but intend to in the future, so we still used these IDs. This may have been an intended change in HotChocolate? However, it is breaking if only some stitched services are updated to 12.6.

C# query endpoint:
` public IQueryable<Person> GetPersonsByOrg([ID("Organization")] int orgId, string q, [ScopedService] PersonDbContext context)`

GraphQL query example:
```
query 
{
    personsByOrg (orgId: "T3JnYW5pemF0aW9uCmkx" q: "steve") {
        nodes {
          displayName
        }
    }
}
```

### Steps to reproduce

1. Create a Query that takes an int as parameter, decorated with an [ID] attribute
2. Send query encoded as a string, for example "T3JnYW5pemF0aW9uCmkx"
3. The ID should be dezerialized to an int before hitting the endpoint, but instead crashes.

### Relevant log output

```shell
Unable to convert the value of the argument `orgId` to `System.Int32`. Check if the requested type is correct or register a custom type converter.
```

### Additional Context?

In addition, the `descriptor.Field(x => x.Id).ID(nameof(Organization));`  does not seem to encode the ID to a base64 relay type id string any more. Just the plain integer number. 

### Product

Hot Chocolate

### Version

12.6

**Comment by tobias-tengler** [comment]
@michaelstaib was #4667 a breaking change in this regard?

**Comment by Kricke242** [comment]
@tobias-tengler Yes, that works! 👍 Thank you for the ultra fast response! That solves it for me.
 I actually tried AddGlobalObjectIdentification but missed the `registerNodeInterface `parameter.

**Comment by tobias-tengler** [comment]
I'm keeping this open, since I'm curious why the breaking change was introduced. Just from looking at the PR that introduced it, I don't see the point. From my understanding the ID attribute was already working without the `AddGlobalObjectIdentification`.

**Comment by Kricke242** [comment]
Yes, the ID attribute in itself has been working without AddGlobalObjectIdentification up to (including) 12.5.

**Comment by michaelstaib** [comment]
In essence, it now is more in line with other things. I am most of the time looking at the expectation for new users and making it easier for new users to come into the fold.

Having the ID attribute without the global ID semantics is more in line with the expectation that you have towards a GraphQL server. The GraphQL spec itself does not specify anything regarding the encoding of ID fields. The recommendation about how an ID shall look is done in the Relay for server specifications. So, it's fitting to have it bound to the `AddGlobalObjectIdentification` convention.
