### ISSUE TITLE
XML Documentation is not working

### ISSUE THREAD

**Issue by benzmarkus** [ChilliCream/hotchocolate#4736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

XML Description is not working

/// <summary>
/// Filter for specific machine and keyfigures.
/// </summary>
/// <returns>List of KeyFigures for a specific machine.</returns>
[UseFiltering]
public async Task<List<GetLatestKeyFiguresForMachineResult>> GetLatestKeyFiguresForMachine() {....}

This is my query and there is no description in Banana Cake.

### Steps to reproduce

1. Simple query
2. Adding XML Documentation
3. Using current version 12.6.0
4.

### Product

Banana Cake Pop

### Version

12.6.0

**Comment by PascalSenn** [comment]
you have to add 
```
<PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>

```` 
to you csproj and use the correct format of XML documentation e.g. <summary>You doc</summary>

**Comment by benzmarkus** [comment]
Thx is working
