### ISSUE TITLE
Add support for relative paths and filters in .graphqlrc.json

### ISSUE THREAD

**Issue by byme8** [ChilliCream/hotchocolate#4740]
### Is your feature request related to a problem?

Let's imagine that you have two websites and a mobile app. All of them use the same graphql server, but have different requirements for data and queries. 

At the moment you need to create three different folders that will contain three identical schema.graphql and schema.extensions.graphql files. In this case, the structure looks like that:
src/
-> website1
--> queries/*.graphql
--> .graphqlrc.json
--> schema.graphql
--> schema.extensions.graphql
-> website2
--> queries/*.graphql
--> .graphqlrc.json
--> schema.graphql
--> schema.extensions.graphql
-> mobileapp
--> queries/*.graphql
--> .graphqlrc.json
--> schema.graphql
--> schema.extensions.graphql

I would say it is too much boilerplate and can be tricky to manage.

### The solution you'd like

I see two possible ways to improve the situation.
1. Move schema*.graphql files to parent folder like that:
src/
-> schema.graphql
-> schema.extensions.graphql
-> website1
--> queries/*.graphql
--> .graphqlrc.json
-> website2
--> queries/*.graphql
--> .graphqlrc.json
-> mobileapp
--> queries/*.graphql
--> .graphqlrc.json

In this case, you will need to specify path like { "schema": "../schema.graphql" } in the .graphqlrc.json. I have tried this variant and it doesn't work. There are no errors or warnings, at the same time, the source generation doesn't happen.

2. Move schema*.graphql files to parent folder and define multiple .graphqlrc.json
src/
-> schema.graphql
-> schema.extensions.graphql
-> website1.graphqlrc.json
-> website2.graphqlrc.json
-> mobileapp.graphqlrc.json
-> website1
--> queries/*.graphql
-> website2
--> queries/*.graphql
-> mobileapp
--> queries/*.graphql

In this case, you will need to specify path for documents like { "documents": "mobileapp/**/*.graphql" } in the *.graphqlrc.json. It doesn't work either. The symptoms are identical to the first case.

### Product

Strawberry Shake

**Comment by byme8** [comment]
I am already investigating how it can be done with the intention to create a pull request. I have managed to build the solution, but at the moment I don't get how to write/execute tests for the strawberry shake.

P.S. I am familiar with the concept of "source generators" and how to write them.

**Comment by michaelstaib** [comment]
We have just pushed a bigger update to the code generator ... if you want to help we can do a quick zoom call. I can walk you through.

**Comment by byme8** [comment]
With the latest update, I have managed to find everything that I needed. I will dig around and write my finds here before the full PR.

**Comment by byme8** [comment]
@michaelstaib I played with different GraphQL source generators(for non-C# languages) and IDE integrations. It looks like both my solutions are not good enough. Both of them are just not supported by any IDE plugin, and without IDE support, there is just no point in implementing them. 

In theory, we can add special support for them in the VS Studio StrawberryShake plugging, but I don't think that it is a nice way to handle it.

Meanwhile, I found out that the GraphQL Config has support for "project" concept. If we utilize it then the solution for issue that I stated in the first message with look like that:
Folder structure:
src/
-> schema.graphql
-> schema.extensions.graphql
-> .graphqlrc.json
-> website1
--> queries/.graphql
-> website2
--> queries/.graphql
-> mobileapp
--> queries/*.graphql

the .graphqlrc.json
``` json
{
    "projects": {
      "mobile" : {
        "schema": "schema.graphql",
        "documents": "mobile/**/*.graphql"
      },
      "website1" : {
        "schema": "schema.graphql",
        "documents": "website1/**/*.graphql"
      },
      "website2" : {
        "schema": "schema.graphql",
        "documents": "website2/**/*.graphql"
      }
    }
  }
```
It works as expected in VS Code. It "works" in the Rider IDE. With the last one, it is a bit tricky. It is possible to break the Rider plugging if multiple schema files are used simultaneously, but it works fine if there is only one(my case).

So, my new idea to add support for projects. This ticket can be closed, because there is just not point to implement this functionality. New ticket should be created(maybe it is already exist?). 
What do you think about that?
