### ISSUE TITLE
Reduce boilerplate for errors

### ISSUE THREAD

**Issue by atrauzzi** [ChilliCream/hotchocolate#4741]
### Is your feature request related to a problem?

When I'm authoring my mutations and [defining their errors](https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations#errors), I find the amount of boilerplate annotations and code necessary to be a bit verbose.

I understand _why_ things are the way they are currently, but I feel like there needs to be a cleaner way?

### The solution you'd like

It would be nice if I could define one or several _generic_ types for GraphQL to use as as a special error type.

Then, instead of having several `ErrorAttribute` annotations, I could have just one, and allow the error type to be expressed by the code within my mutation:

```c#
[Error(typeof(ResultException))]
public async Task<MyType> MyMutation()
{
    // ...
```

For example, I have a domain layer which has its own success/failure result system.  It would map very cleanly to GraphQL errors with something like the following:

```c#
public class ResultException : Exception
{
    public ResultException(string message)
    : base(message)
    {
    }

    public static ResultException<NewResultType> Create<NewResultType>(NewResultType result)
    where NewResultType : Result
    {
        return new(result);
    }
}

public class ResultException<DomainResultType> : ResultException
where DomainResultType : Result
{
    public DomainResultType Result { get; init; }

    public ResultException(DomainResultType result)
    : base(result.GetType().ToString())
    {
        Result = result;
    }
}
```

...Unfortunately, the way things currently are, I have to write a shadow GraphQL error type for each type of domain error I can potentially encounter.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Is this because you actually have a domain error object?

**Comment by atrauzzi** [comment]
Yes! I actually started working on something like that, but HC didn't like the generic base error type.

**Comment by michaelstaib** [comment]
We will at some point allow error object mapping. At the moment we are experimenting. Once we have something we think is good we will do a proposal. Closing this issue for now.
