### ISSUE TITLE
HotChocolate 12 HotChocolate.Execution package doesn't match the Instrumentation documentation (classes don't exist)

### ISSUE THREAD

**Issue by AlilNinja** [ChilliCream/hotchocolate#4745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're trying to move from HotChocolate 10 to HotChocolate 12 and are converting the instrumentation. The official documentation on this page ([https://chillicream.com/docs/hotchocolate/server/instrumentation](url)) shows that there's now multiple types of `DiagnosticEventListeners` instead of a single one. The two we're interested in are the `ServerDiagnosticEventListener` and `ExecutionDiagnosticEventListener`. It seems pretty straightforward: make a class that implements those and override the methods you want. But none of the examples show what package contains the event listeners. The closest package I found based in the examples was `HotChocolate.Execution.Instrumentation`. However, in that package the `ServerDiagnosticEventListener` and `ExecutionDiagnosticEventListener` don't exist. The only thing that's there is an interface for the Execution EventListener (`IExecutionEventListener`), and because that's an interface and not a class, we'd have to implement every single method on it rather than just overriding the couple of methods we want. 

Why is there this discrepancy between the documentation and the packages available? Is it an error with the documentation? Are we using the wrong package and the correct classes are defined somewhere else?

What's the proper way to set this up?

### Steps to reproduce

1. Set up any basic query
2. Install the HotChocolate.Execution package
3. Try to add instrumentation by following the HotChocolate 12 Instrumentation documentation
4. The classes it says to use do not exist

### Product

Hot Chocolate

### Version

12.4.1 (though I checked 12.6.0 as well)

**Comment by tobias-tengler** [comment]
The `ServerDiagnosticEventListener` is part of the `HotChocolate.AspNetCore` package. The `ExecutionDiagnosticEventListener` should be available through the `HotChocolate.Execution` package (namespace `HotChocolate.Execution.Instrumentation`), which is also referenced by `HotChocolate.AspNetCore`. 

If you have added the `HotChocolate.AspNetCore` package and you are on 12.6 you should be able to have access to both these classes...

**Comment by AlilNinja** [comment]
Thanks for clarifying where both of the event listeners come from! I think my issue was some sort of weird internal crash in Visual Studio itself and that's why it wasn't recognizing or suggesting the correct packages for the event listeners. After a few restarts of VS and my computer, I verified that I did indeed have the `HotChocolate.AspNetCore` package installed with 12.6 and tried to create the event listener classes again and this time it worked with no issues
