### ISSUE TITLE
Cannot use any 12.7 release after preview 7.

### ISSUE THREAD

**Issue by atrauzzi** [ChilliCream/hotchocolate#4746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't seem to use any release after 12.7.0-preview.7.  I end up getting the error `Could not load file or assembly 'HotChocolate.Types, Version=12.7.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

### Steps to reproduce

Install any release of 12.7 after preview 7 via nuget.

### Product

Hot Chocolate

### Version

12.7.0-preview.15

**Comment by michaelstaib** [comment]
We are doing at the moment fundamental work on StrawberryShake. Closing this issue for now.
