### ISSUE TITLE
Cannot return computed properties when projecting

### ISSUE THREAD

**Issue by atrauzzi** [ChilliCream/hotchocolate#4747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to project a domain model to a DTO via Hot Chocolates `IQueryable` support.

One of the properties on my domain model is `get`-only. This means that it doesn't correspond to any field in the schema and cannot be used in a LINQ expression tree.

I have tried marking the DTO property with `IsProjected(false)`, but this simply results in the property being serialized with its default value.

### Steps to reproduce

1.  Create a domain model with a get-only property
2. Create a DTO with a property to receive that get-only property during projection
3. Attempt to project the DTO from a `Select()` on the `IQueryable` of the domain model that then gets returned to Hot Chocolate

### Product

Hot Chocolate

### Version

12.7-7

**Comment by atrauzzi** [comment]
```c#
public class MyGraphQlType 
{
    public Guid Id { get; init; }
    public string SomeNonProjectableValue { get; init; }
}

public class MyEntityFrameworkType
{
    public Guid Id { get; set;}
    public string SomeValue {
        get {
            return "Assume that getting this value was really complicated.";
        }
    }
}

public class MyQueryType
{
    public async Task<IQueryable<MyGraphQlType>> MyData([Service] MyQueryableService qService)
    {
        var myQueryable = qService.MyEfTypes.Select((myEfType) => new MyGraphQlType
        {
            Id = myEfType.Id,
            SomeNonProjectableValue = myEfType.SomeValue,
        };

        return myQueryable;
    }
}
```

The problem is that Hot Chocolate won't let me include the _calculated_ value of `myEfType.SomeValue` becaue it's not (and cannot be) an expression tree.

So when I'm projecting a value, how do I add extra values that may not necessarily be participating in the projection, but still need to be returned?

**Comment by CoreDX9** [comment]
You can use ExtendObjectType :
``` csharp
[ExtendObjectType(typeof(MyEntityFrameworkType))]
public class MyGraphQlType
{
    [BindMember(nameof(MyEntityFrameworkType.SomeValue), Replace = true)]
    public string GetSomeNonProjectableValue([Parent] MyEntityFrameworkType entity) => entity.SomeValue;
}
```
Then register to services :
``` csharp
builder.Services.AddGraphQLServer()
    .AddQueryType(d => d.Name(OperationTypeNames.Query))
    .AddTypeExtension<MyGraphQlType>()
    // ...
```
Last return original query :
``` csharp
public class MyQueryType
{
    public async Task<IQueryable<MyEntityFrameworkType>> MyData([Service] MyQueryableService qService)
    {
        return qService.MyEfTypes;
    }
}
```

**Comment by atrauzzi** [comment]
Doesn't that erase all context though?  How do I know which `MyEntityFrameworkType` to query for?
