### ISSUE TITLE
Playground as a separate app 

### ISSUE THREAD

**Issue by queil** [ChilliCream/hotchocolate#476]
Hotchocolate assumes Playground runs in the same aspnetcore app as the GraphQL server itself. PlaygroundOptions won't let an absolute QueryPath.

It would be great to provide ability to pass an absolute URL.

**Comment by michaelstaib** [comment]
This is a good point. We will add that.

**Comment by akaSybe** [comment]
Why would you like to have Playground middleware hosted separately from GraphQL-endpoint? You could download standalone app to test third-party GraphQL APIs

**Comment by queil** [comment]
@akaSybe: I am playing with an OpenIdConnect authentication where GraphQL is a resource server (requiring a JWT Bearer token) and Playground is a client (acquiring one via authorization code grant flow). So I need that kind of separation. That way I do not need to populate my bearer tokens manually. I could roll out my own solution but it sounds like re-inventing the wheel.
