### ISSUE TITLE
Banana Cake Pop don't send access token when open subscription

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#4761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Banana Cake Pop don't send access token to server when open subscription. Access token has sent using authorization header when run query or mutation. I use OpenIddict for Oauth2.

### Steps to reproduce

1. Fetch and apply token in web page.
2. Open subscription.
3. HttpContext.User is empty. If view request details in Chrome's DevTools, cann't find token header or query parameter.

### Product

Banana Cake Pop

### Version

12.6.0.0

**Comment by PascalSenn** [comment]
The Upgrade request of the WebSocket connection cannot contain headers. This is a restriction of the browsers. Do you intend to use your graph in a web app?

**Comment by CoreDX9** [comment]
I use web to debug server, if possible, can send token with query parameter? It's useful. And Authorize attribute doesn't work with subscription.

**Comment by CoreDX9** [comment]
I use web to debug server, if possible, can send token with query parameter? It's useful. And Authorize attribute doesn't work with subscription.

**Comment by obiwan007** [comment]
Is it supposed to add the token to the authorization key inside the connection_init packet send when connecting? This is not happening.
	39	
09:24:11.761
{"id":"1","type":"start","payload":{"query":"subscription {\n subscribeDisplayManagerItemAddedEvent {\n syslogMessage {\n milliSeconds\n dateTimeStamp\n }\n }\n}\n"}}	184	
09:24:11.761
{"type":"connection_ack"}	25	
09:24:11.767
{"type":"ka"}	13	
09:24:11.767
{"type":"ka"}	13	
09:24:16.775
{"type":"ka"}	13	
09:24:21.783
{"type":"ka"}	13	
09:24:26.800
{"payload":{"errors":[{"message":"The current user is not authorized to access this resource.","locations":[{"line":2,"column":3}],"path":["subscribeDisplayManagerItemAddedEvent"],"extensions":{"code":"AUTH_NOT_AUTHENTICATED"}}],"data":{"subscribeDisplayManagerItemAddedEvent":null}},"id":"1","type":"data"}	307	
09:24:29.346
{"payload":{"errors":[{"message":"The current user is not authorized to access this resource.","locations":[{"line":2,"column":3}],"path":["subscribeDisplayManagerItemAddedEvent"],"extensions":{"code":"AUTH_NOT_AUTHENTICATED"}}],"data":{"subscribeDisplayManagerItemAddedEvent":null}},"id":"1","type":"data"}	307	
09:24:29.346
{"payload":{"errors":[{"message":"The current user is not authorized to access this resource.","locations":[{"line":2,"column":3}],"path":["subscribeDisplayManagerItemAddedEvent"],"extensions":{"code":"AUTH_NOT_AUTHENTICATED"}}],"data":{"subscribeDisplayManagerItemAddedEvent":null}},"id":"1","type":"data"}	307	
09:24:29.348
{"type":"ka"}	13	
09:24:31.818
{"type":"ka"}	13	
09:24:36.836
{"type":"ka"}	13	
09:24:41.848
{"type":"ka"}	13	
09:24:46.858
{"type":"ka"}	13	
{type: "connection_init", payload: {}}
payload: {}
type: "connection_init"}

It should be more like:
{"type":"connection_init","payload":{"authorization":"Bearer eyJh.....

This is like apollo-client is doing it.

**Comment by CoreDX9** [comment]
> Is it supposed to add the token to the authorization key inside the connection_init packet send when connecting? This is not happening: {type: "connection_init", payload: {}} payload: {} type: "connection_init"}
> 
> It should be more like: {"type":"connection_init","payload":{"authorization":"Bearer eyJh.....
> 
> This is like apollo-client is doing it.

This is a better way to apply authorization!

**Comment by rstaib** [comment]
This issue has been solved by including the authorization token in the web socket connection parameters.
