### ISSUE TITLE
The `Field()` method should work with `x => x.SomeMethod` without specifying arguments

### ISSUE THREAD

**Issue by AradAral** [ChilliCream/hotchocolate#4764]
### Is your feature request related to a problem?

Currently, when you want to do `descriptor.Field(x => ...)` on a method, it requires a `MethodCallExpression`, which means you're going to have to call the method, and by extension, pass arguments, usually `default` is used:
```csharp
descriptor.Field(q => q.GetProductById(default, default, default, default))
    .BlahBlah(...);
```
In addition to being ugly and awkward, this also means that you'd need to come back here and change the number of `default`s every time the number of your method's parameters changes.

### The solution you'd like

Why not simply have an overload for the `Field()` method that would accept something like:
```csharp
descriptor.Field(q => q.GetProductById)
    .BlahBlah(...);
```
Clearly much prettier and more convenient, and it would also require no change whenever the number of the method's parameters changes.

I may be missing something, of course, so let me know.

Thank you.

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
This does not compile
