### ISSUE TITLE
Ambiguity error in Strawberry Shake client in Rider

### ISSUE THREAD

**Issue by osmnorhn** [ChilliCream/hotchocolate#4766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we are using [Strawberry Shake](https://chillicream.com/docs/strawberryshake), Rider is marking auto-generated types with red lines because it finds them in 2 locations.

I followed the documentation for generating Strawberry Shake client and Generated folder as "included" to the project. The project builds and runs fine both from the command line (with `dotnet build`) and in Rider, but Rider seems to detect the autogenerated code twice as the image below;
![image](https://user-images.githubusercontent.com/5622147/154265237-ad5a1758-be16-4e6c-af9c-b5694c5616ef.png)

In visual Studio works fine, and doesn't show any errors like this, but Rider and VS Code does. So it is not just a rider issue, it seems like the issue is on code generation in Strawberry Shake.
Jetbrains already looked into it, and came to the conclusion that it is not a rider issue.

The relevant issue in Rider is: 
https://youtrack.jetbrains.com/issue/RIDER-66262

If you need a sample project I can create a sample project and share the link. 

Product
Strawberry Shake

Version
12.6.0.0

### Steps to reproduce

1. Create a graphql endpoint with hotchocolate in Rider
2. Generate strawberry shake client
3. Include Generated folder to the project
4. Add some tests which are using the strawberry shake generated client classes
5. Rebuild the solution
6. See the error

### Product

Strawberry Shake

### Version

12.6.0

**Comment by michaelstaib** [comment]
Please try the new version of strawberry shake... most generator issues are fixed.
https://www.nuget.org/packages/StrawberryShake.CodeGeneration.CSharp.Analyzers/12.7.0-preview.27

**Comment by lou8566** [comment]
I have been getting an Ambiguous Reference using Strawberry Shake 12.7.0 however the error points to the same line of code in the generated client.

![Snag_1b495a](https://user-images.githubusercontent.com/3045049/161798627-5760d99a-c395-4193-be75-8df3696325ad.png)
.

I deleted the files and started over, and still I am getting this error.

**Comment by nesherhh** [comment]
I have this issue with VS 2022 17.4.3 + ReSharper 2022.3. StrawberryShake.CodeGeneration.CSharp.Analyzers 12.15.2

**Comment by lou8566** [comment]
This error has not been resolved on 12.7.0 as I have the same error

**Comment by michaelstaib** [comment]
No ... its resolved in 13

**Comment by michaelstaib** [comment]
The branch 12.7.0 preview 27 became the 13 branch.
