### ISSUE TITLE
"ProjectTo<TSource, TResult>(context)" from package HotChocolate.Data.AutoMapper does not work with EF when applying filters

### ISSUE THREAD

**Issue by RafaelMalgor** [ChilliCream/hotchocolate#4772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem
The `where` filter is not working properly when using projections. It only allows for filtering on fields that are being requested on the Query. 
This works:
`query {
  persons(where: {lastNameDto:{contains:"M"}}) {
    lastNameDto
  }
}`

This does not work:
`query {
  persons(where: {lastNameDto:{contains:"M"}}) {
    nameDto
  }
}`

### Context
We are returning a DTO from a Query using Filters and Projections. 
To project the object from the Entity to the DTO we are using the suggested `ProjectTo` method from HotChocolate.Data.AutoMapper and we are also configuring the Explicit Expansion on AutoMapper.

### Simple App to Repro

1. Download or clone [this](https://github.com/RafaelMalgor/hotchocolate-projection-issue-demo)
2. Edit connection string accordingly.
3. Run the project
4. Run the following Query on BCP:
`query {
  persons(where: {lastNameDto:{contains:"M"}}) {
    nameDto
  }
}`

### ### prerequisites

1. Setup the basic bootstrapping of HC with Entity Framework and AutoMapper.
2. Enable Filtering and Projection.
2. Make sure to use Explicit Expansion when mapping the DTO.
3. 
### ### Repro
1. Create a Query with a method that returns an `IQueriable<DTOType>`.
2. Add the `UseProjection` and `UseFiltering` attributes to the method. 
2. On the Query fetch the entities using EF.
3. Project the of IQueriable<EntityType> into an IQueriable<DTOType> using the `ProjectTo` method from  `HotChocolate.Data.AutoMapper`

For more details please check the [project](https://github.com/RafaelMalgor/hotchocolate-projection-issue-demo).

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "persons"
      ],
      "extensions": {
        "message": "The LINQ expression 'DbSet<Person>()\r\n    .Where(p => new PersonDto{ NameDto = p.Name }\r\n    .LastNameDto != null && new PersonDto{ NameDto = p.Name }\r\n    .LastNameDto.Contains(__p_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.",
        "stackTrace": "   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.IEnumerable.GetEnumerator()\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.<>c__DisplayClass58_0.<ExecuteResolverPipelineAsync>b__0()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ]
}
```

### Additional Context?

Interestingly enough, if the call to `.ForAllMembers(x => x.ExplicitExpansion());` is removed from the AutoMapper mapping, the filter starts to work fine, no matter what field is asked for, but projections are not enforced on the database, that is, the SQL SELECT projects all the fields, even when you are only asking for one.  

### Product

Hot Chocolate

### Version

12.6

**Comment by PascalSenn** [comment]
There is not much we can do here. The expression seems to be too complex for EF to translate.

**Comment by RafaelMalgor** [comment]
Thank you for looking into it. I understand it can be too complex. 
I would like to ask you, related to this limitation, what approach would you take? or what is the "HotChocolate" way for exposing information in a public API? What I mean is that we are using DTOs so we can encapsulate the underlaying models and have fine control on what we expose to the outside world. Should we just expose the full DB Entity? Is that "normal" or expected in GraphQL? I come from a more traditional RESTapi background so exposing the whole Entity "as is" feels a bit off to me, but I am open to suggestions.

**Comment by PascalSenn** [comment]
In most cases your GraphQL Types are your DTO:

You can extend them with resolver, remove fields on them (black or whitelist, depends on you prefrence) etc. 
You can also change the structure of types and everything.

```csharp
// annotation based [ExtendObjectType(typeof(User), IgnoreProperties = {nameofUser.SomeHiddenField} ]
public class UserExtensions
 {
        public string DisplayName([Parent] User user) => $”{user.FirstName} {user.LastName}” 
}  
        
      //or code first 
public class UserType : ObjectType<User> 
 {
    protected override void Configure(IObjectTypeDescriptor<User> descriptor)     
    {            
           descriptor.Ignore(x => x.SomeHiddenField); 
           descriptor.Field(“displayName”).ResolveWith<Resolvers>(x => x.DisplayName(default));    
     }
    
    public class Resolvers     
    {           
          public string DisplayName([Parent] User user) => $”{user.FirstName} {user.LastName}”  ;   
    }
 }
```

A custom resolver cannot be sorted or filtered by. But this limitation is with a clean schema design normally no problem. As when you desgin you graphql schema, you should prefere

```graphql
query GetUsers($search: String!) {    
    searchUsers(search: $search) {
        name
        lastName
   }
}
```

over 

```graphql
query GetUsers($search: String!) {    
   users(where: { OR [{ name: {contains: $search}}, {lastName: {contains:$search}}]}) {
        name
        lastName
   }
}
```
