### ISSUE TITLE
Invalid SQL when using  EntityFrameworkCore.Projectable (Package) for Computed Properties

### ISSUE THREAD

**Issue by 3ilal** [ChilliCream/hotchocolate#4778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hope everyone is doing well
I had an Aggregate model with bunch of Properties as well as some "**Computed Properties**", so I decided to use this open source  package [https://github.com/koenbeuk/EntityFrameworkCore.Projectables](url) to optimized my SQL. However, when using with HotChocolate Version 12.6.0  the Computed Properties values are Default Values and the the required SQL is not being generated. 
**//Query
query {
  purchaseInvoices {
    id,
    total,
    grossTotal
    
  }
}**

### Steps to reproduce

1. Add EntityFrameworkCore.Projectable Package
2. Mark Computed Properties with [Projectable] Attribute
2.Register Projectable in DbContext OnConfiguring
3.Query for Computed Properties

### Relevant log output

```shell
**//With HotChocolate**
//Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<PurchaseInvoice>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  Id -> 0
              SELECT p.Id
              FROM PurchaseInvoices AS p),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, PurchaseInvoice>,
          Infrastructure.Persistence.EntityFrameworkCore.DatabaseContext,
          False,
          False,
          True
      )'
**SELECT p."Id"
      FROM "PurchaseInvoices" AS p**

**//Without HotChocolate**
//Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<PurchaseInvoice>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  Id -> 0
              SELECT p.Id
              FROM PurchaseInvoices AS p),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, PurchaseInvoice>,
          Infrastructure.Persistence.EntityFrameworkCore.DatabaseContext,
          False,
          False,
          True
      **SELECT ((
          SELECT COALESCE(SUM(p0."CostPrice" * p0."Quantity"), 0.0)
          FROM "PurchaseInvoiceItem" AS p0
          WHERE p."Id" = p0."InvoiceId") - ((
          SELECT COALESCE(SUM(p1."CostPrice" * p1."Quantity"), 0.0)
          FROM "PurchaseInvoiceItem" AS p1
          WHERE p."Id" = p1."InvoiceId") * (p."DiscountPercentage" / 100.0))) + (
          SELECT COALESCE(SUM((p2."CostPrice" * p2."Quantity") * (p2."VATPercentage" / 100.0)), 0.0)
          FROM "PurchaseInvoiceItem" AS p2
          WHERE p."Id" = p2."InvoiceId")
      FROM "PurchaseInvoices" AS p**
```

### Product

Hot Chocolate

### Version

12.6.0

**Comment by PascalSenn** [comment]
Can you call `ExpandProjectables` in the resolver on the queryable?

**Comment by 3ilal** [comment]
> Can you call `ExpandProjectables` in the resolver on the queryable?

Yes i have tried that but having the same issue. However, it is being working with AutoMapper Projecto

**Comment by PascalSenn** [comment]
can you provide a repro?

**Comment by 3ilal** [comment]
> can you provide a repro?

https://github.com/3ilal/Contribution/tree/main/HotChocolate

**Comment by omelhus** [comment]
Any way we can help on this issue? Are you planning an equivalent for hot chocolate?
