### ISSUE TITLE
Nested exceptions aren't reported out fully by default

### ISSUE THREAD

**Issue by atrauzzi** [ChilliCream/hotchocolate#4781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When Hot Chocolate reports an exception that happens to nest another one, it only ever ends up returning the outermost one in the error response it generates by default.

### Steps to reproduce

1. Throw an exception that has another one nested within it.

### Product

Hot Chocolate

### Version

*

**Comment by PascalSenn** [comment]
Hm.. 
in what context?
- Error Filter
- Diagnostic Listener
- Mutation Convention
- GraphQL Errors for uncaught exceptions

**Comment by atrauzzi** [comment]
GraphQL Errors for uncaught exceptions in this case.

**Comment by atrauzzi** [comment]
@michaelstaib - I was thinking specifically for debugging purposes, if an exception has a nested error, if the default HotChocolate exception renderer could just also include the nested exception(s)...
