### ISSUE TITLE
Hot Chocolate's `DefaultAuthorizationHandler` does not allow anonymous authorization

### ISSUE THREAD

**Issue by loic-sharma** [ChilliCream/hotchocolate#4784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.NET Core's authorization handlers can authorize anonymous users. For example, here's an example that "disables" authentication in the development environment: https://stackoverflow.com/a/59558348

However, this trick does not work on Hot Chocolate as Hot Chocolate does not attempt to authorize a claims principal if it is not authenticated:

https://github.com/ChilliCream/hotchocolate/blob/9cfa1d11c01ac19d0c09513e3f3d82dcde9965dd/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/DefaultAuthorizationHandler.cs#L28-L50

Notice how Hot Chocolate returns `AuthorizeResult.NotAuthenticated` if the claims principal isn't authenticated. As a result, Hot Chocolate will always send a 401 response:

https://github.com/ChilliCream/hotchocolate/blob/9cfa1d11c01ac19d0c09513e3f3d82dcde9965dd/src/HotChocolate/AspNetCore/src/AspNetCore.Authorization/AuthorizeMiddleware.cs#L42-L53

### Steps to reproduce

Below is a web app that shows the differences between GraphQL and ASP.NET Core:

* The minimal API route requires authorization, but this gets bypassed by the `AllowAnonymous` authorization handler
* The GraphQL query requires authorization. The `AllowAnonymous` handler is never called and a 401 response is returned

```cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Identity.Web;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddGraphQLServer()
    .AddAuthorization()
    .AddQueryType<Query>();

builder
    .Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration);

builder.Services.AddSingleton<IAuthorizationHandler, AllowAnonymous>();

var app = builder.Build();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

// This minimal API route requires authorization, however,
// this gets bypassed by the `AllowAnonymous` authorization handler
// An anonymous user can call this as expected!
app.MapGet("/", [Authorize] () => "Hello world");

app.MapGraphQL();

app.Run();

// This GraphQL API requires authorization. Ideally this should behave
// just like the minimal API route. However, Hot Chocolate does not call the
// `AllowAnonymous` authorization handler if the claims principal is not authenticated.
// In other words, this returns a 401 error for anonymous users :(
[HotChocolate.AspNetCore.Authorization.Authorize]
public class Query
{
    public Book GetBook() => new Book(Title: "Foo Bar");
}

public class AllowAnonymous : IAuthorizationHandler
{
    public Task HandleAsync(AuthorizationHandlerContext context)
    {
        // Pass all pending requirements even for anonymous users.
        foreach (var requirement in context.PendingRequirements.ToList())
            context.Succeed(requirement); 

        return Task.CompletedTask;
    }
}

public record Book(string Title);
```

### Product

Hot Chocolate

### Version

12.6.0

**Comment by tobias-tengler** [comment]
Thanks for reporting, but I think this is a duplicate of #2884, so I'm closing it.

**Comment by loic-sharma** [comment]
Ah yup mine is a duplicate. I apologize for the noise, I had searched the issues but somehow missed that one!
