### ISSUE TITLE
IObjectFieldDescriptor should log warning or throw exception in case of rename fields for multiple times.

### ISSUE THREAD

**Issue by snys98** [ChilliCream/hotchocolate#4788]
### Is your feature request related to a problem?

I happened to have a problem of naming field in base classes and subclasses, they both called `IObjectFieldDescriptor.Field(x=>x.Foo)`. The subclass first name it with `descriptor.Name("foo1")`, and then, a multi-level nested base class named it with `descriptor.Name("foo2")`(which I didn't noticed), so the final name is `"foo2"`(which behaves correctly), but the name what I really want is `"foo1"`. And I just had a hard time to get noticed that there are renaming problems.

### The solution you'd like

Maybe we should have a warning (or a exception that can be manually supressed?) when renaming a field for multi times? 
And not just for naming, but also for other idempotent field operations(like `Authorize("policy")`?). I think it can make the schema building flow much more debug-friendly.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
That is by design. Some middleware like the Paging middleware is able to rewrite the type system. Taking this ability away would reduce the functionality of Hot Chocolate greatly.
