### ISSUE TITLE
Apollo federation - stream/defer directive issue

### ISSUE THREAD

**Issue by Joelgullander** [ChilliCream/hotchocolate#4795]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Apollo federation has not yet added support for the defer/stream directive, and we are now trying to deploy our first hotchocolate service to our cluster and got the schemavalidation below: 

```
@defer
EXECUTABLE_DIRECTIVES_IN_ALL_SERVICES

-> Custom directives must be implemented in every service. The following services do not implement the @defer directive: subscriptions, shoppinglists, shoppinglist-product, postalcodes, orderhistory, favorites, external, customers, carts.

@stream
EXECUTABLE_DIRECTIVES_IN_ALL_SERVICES

-> Custom directives must be implemented in every service. The following services do not implement the @stream directive: subscriptions, shoppinglists, shoppinglist-product, postalcodes, orderhistory, favorites, external, customers, carts.
```

Is there anyway to disable those directive until apollo-federation has introduced it?

### Steps to reproduce

Try to deploy an example schema to existing cluster of different graphql libraries. We are using hotchocolate for 1, and graphql-dotnet and nodejs for the other. 

### Product

Hot Chocolate

### Version

12.6.0

**Comment by michaelstaib** [comment]
Yeah ... will add a disable feature.

**Comment by Joelgullander** [comment]
Any workaround for now? Add the directive to the other schemas?

**Comment by da1rren** [comment]
Please assign this to me :)

**Comment by michaelstaib** [comment]
This feature is already implemented... let me find the PR

**Comment by michaelstaib** [comment]
This takes care of it:
https://github.com/ChilliCream/hotchocolate/blob/76da4a11b3fd4bb45c3a7347ec984473a727f36a/src/HotChocolate/ApolloFederation/src/ApolloFederation/FederationSchemaPrinter.cs#L72

**Comment by rohkhann** [comment]
@michaelstaib  any workaround for this?
