### ISSUE TITLE
API for subscription clean up (unsubscribe)

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4799]
### Is your feature request related to a problem?

At the moment there is no clean API to run some cleanup logic, after a subscription is canceled or terminated (I do not mean the subscription connection, for this we could use the `ISocketSessionInterceptor`, but an individual subscription within a connection).

Lets imagine the following scenario where I might need to do some setup, so my system actually starts to emit events. In this case its just a `Console.WriteLine`, but it might be something async:

```csharp
public class Subscription
{
    public ValueTask<ISourceStream<Book>> SubscribeToBook(
        string bookId, [Service] ITopicEventReceiver receiver)
    {
        Console.WriteLine("Subscribe to book: " + bookId);

        return receiver.SubscribeAsync<string, Book>($"BookUpdated_{bookId}", token);
    }

    [Subscribe(With = nameof(SubscribeToBook))]
    public Book OnBookUpdated(string bookId, [EventMessage] Book book)
        => book;
}
```

Of course I also want to clean up this setup, once the subscription ends - but how would I do that at the moment?
We could register on the `CancellationToken`:

```csharp
public ValueTask<ISourceStream<Book>> SubscribeToBook(
      string bookId, [Service] ITopicEventReceiver receiver,
      CancellationToken token)
  {
      Console.WriteLine("Subscribe to book: " + bookId);

      token.Register(() =>
      {
          Console.WriteLine("Unsubscribe from book: " + bookId);
      });

      return receiver.SubscribeAsync<string, Book>($"BookUpdated_{bookId}", token);
  }
```

But now we have a closure and no convenient way to in turn cleanup the `CancellationTokenRegistration`.

The best way, and what Michael suggested to me in the past, would be to implement an `IAsyncEnumerable` and `IAsyncEnumerator` and do the cleanup in the `DisposeAsync` of the enumerator. 
This might be the way to go if you are already building your own enumerator for subscriptions, but for people wanting to use the Hot Chocolate Pub-Sub system it's not really an option. It's a lot of boilerplate and passing things around, all while basically wrapping the existing Pub-Sub system in an enumerator.

### The solution you'd like

I would like a simple API that designates a method that should be run, if an individual subscription ends:

```csharp
public class Subscription
{
    public ValueTask<ISourceStream<Book>> SubscribeToBook(
        string bookId, [Service] ITopicEventReceiver receiver)
    {
        Console.WriteLine("Subscribe to book: " + bookId);

        return receiver.SubscribeAsync<string, Book>($"BookUpdated_{bookId}", token);
    }

    [Subscribe(With = nameof(SubscribeToBook))]
    // Of course we would also mirror this with Code-first 
    [Unsubscribe(With = nameof(CleanupBookSubscription))]
    public Book OnBookUpdated(string bookId, [EventMessage] Book book)
        => book;

    public ValueTask CleanupBookSubscription(string bookId, [Service] ISomeService service)
    {
        Console.WriteLine("Unsubscribe from book: " + bookId);
        return ValueTask.CompletedTask;
    }
}
```

In this cleanup method you should have access the the subscription arguments and dependency injection services.

I'm not sure how feasible it is to keep the subscription arguments around in memory to invoke the cleanup later, but I'm open for suggestions on this - this is just a proposal.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
You actually have this functionality already since you can use the `IAsyncEnumerator` dispose or more simply add some code after your for each async ...

```csharp
await foreach(var foo in bar) 
{
   yield return foo;
}

// cleanup
```

**Comment by tobias-tengler** [comment]
Ah nice, totally forgot about that. Will play around with it a bit and update the documentation afterwards.

**Comment by Jonatthu** [comment]
@michaelstaib  

This exception get's thrown before reach the // cleanup, and the code on // cleanup does not get executed.
```
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
```
```
await foreach(var foo in bar) 
{
   yield return foo;
}

// cleanup
```

**Comment by Jonatthu** [comment]
```
		symbols ??= Array.Empty<Guid>();
		var symbolSet = new HashSet<Guid>(symbols);
		ISourceStream stream = await receiver.SubscribeAsync<string, Guid>(nameof(SentChatMessageSubscription.OnSendChatMessageAsync), cancellationToken);

		cancellationToken.Register(async () =>
		{
			await queueStorage.SendMessageAsync(new NotificationMessage(
				Description: "Jonathan has sent you a message."
			), default);
		});

		await foreach (Guid symbol in stream.ReadEventsAsync().WithCancellation(cancellationToken))
		{
			if (symbols.Length == 0 || symbolSet.Contains(symbol))
			{
				yield return symbol;
			}
		}
```

So far this is the only thing that works, but the error keeps being thrown
```
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
```

**Comment by michaelstaib** [comment]
@Jonatthu  this is a cancellation exception. you can catch it or introduce a finally block.

**Comment by michaelstaib** [comment]
Apart from that V13 has a ton more hooks.

**Comment by Jonatthu** [comment]
@michaelstaib When I do try catch the compiler is not happy:
```
Cannot yield a value in the body of a try block with a catch clause [Account.EntryPoint]csharp(CS1626)
```
