### ISSUE TITLE
Some Enum value characters are changed to lowercase 

### ISSUE THREAD

**Issue by ChristoBoshoff** [ChilliCream/hotchocolate#4806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some enum values are generated with lower case characters in C#, i.e. 
In the graphql schema the enum will look like this:
enum PorMaa {
    VA003
    VA009
}
But in C# the second character is in lower case, a instead of A
public enum PorMaa
{
        Va003,
        Va009
}

Bug: The case should be the same.

### Steps to reproduce

1. 

### Product

Strawberry Shake

### Version

12.6.1

**Comment by michaelstaib** [comment]
It’s not a bug. We essentially apply naming conventions on top of the types. You override these with directives in the schema.extensions.graphql file.
