### ISSUE TITLE
Subscription throw exception on console app when dispose it.

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#4808]
### Is your feature request related to a problem?

![屏幕截图 2022-03-03 072306](https://user-images.githubusercontent.com/26616055/156475505-30da84bf-b93b-4f17-b318-454fd75fef80.jpg)

How can I get IAsyncDisposable? Or can you implement IDispose?

### The solution you'd like

I don't know if there is a solution.

### Product

Strawberry Shake

**Comment by tobias-tengler** [comment]
I think your subscription variable should just be of type `IAsyncDisposable` and then you can call

```csharp
await subscription.DisposeAsync();
```

**Comment by michaelstaib** [comment]
nope ... its the service provider. you need to do an async using on it.

**Comment by CoreDX9** [comment]
But I don't know how to get `IAsyncDisposable` . `Watch()` return to me a `IDisposable`.

**Comment by CoreDX9** [comment]
Sorry, I see it. `await using rootProvider` is right.
