### ISSUE TITLE
How can I get notice when server was called `eventSender.CompleteAsync("some_topic")`?

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#4810]
I'm sure to correctly handled cancellation tokens in the backend. I mean, when I call `eventSender.CompleteAsync("some_topic");` on server, how can I know subscription stream was completed and websocket connection was closed on client. I saw complete message and connection closed on DevTools. But client never notify me stream has terminated.

code like
``` csharp
var watcher = MyClient.OnNewMessage.Watch();

var subscription = watcher
    .Subscribe(res =>
    {
        Logger.LogInformation("New message: {0}", res);
    },
    ex => Logger.LogError(ex, "Exception happened."),
    () => Logger.LogInformation("Stream completed."));
```

`ex => Logger.LogError(ex, "Exception happened.")` only will be called when I call `subscription.Dispose()` with stream was not completed. It will not be called 
when I call `eventSender.CompleteAsync("some_topic");`. `() => Logger.LogInformation("Stream completed.")` is similar to previous one.

![屏幕截图 2022-03-03 072306](https://user-images.githubusercontent.com/26616055/156467134-158dc71a-6c87-46be-9cfe-73abcfc2d2c4.jpg)

_Originally posted by @CoreDX9 in https://github.com/ChilliCream/hotchocolate/issues/4804#issuecomment-1057495616_

**Comment by CoreDX9** [comment]
SignalR client has `Closed` event to notify me the connection has been closed by server or network error. Then I can reconnect to server or dispose the connection. Then I can update UI to tell user the connection was closed.
But I don't know how to know the subscription has been closed by server or network error. So I can't update UI to notify user this event.

**Comment by michaelstaib** [comment]
ISocketSessionInterceptor.OnCloseAsync you can inherit from the DefaultSocketSessionInterceptor.
