### ISSUE TITLE
Could not create instance of DataLoader

### ISSUE THREAD

**Issue by marshalluous** [ChilliCream/hotchocolate#4814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When making a query to "UserById" query for multiple users by id everything works fine. But when querying UserByEmail or multiple user by email, the following error occours: 
```Could not create instance of UserByEmailDataLoader```

Below the data loaders:
```
public class UserByIdDataLoader : BatchDataLoader<string, AspNetUser>
{
    private IDbContextFactory<ApplicationDbContext> _dbContextFactory;

    public UserByIdDataLoader(IBatchScheduler batchScheduler, IDbContextFactory<ApplicationDbContext> dbContextFactory) 
        : base(batchScheduler)
    {
        _dbContextFactory = dbContextFactory;
    }

    protected override async Task<IReadOnlyDictionary<string, AspNetUser>> LoadBatchAsync(
        IReadOnlyList<string> keys,
        CancellationToken cancellationToken)
    {
        await using var dbContext = await _dbContextFactory.CreateDbContextAsync(cancellationToken);

        return await dbContext.AspNetUsers.Where(s => keys.Contains(s.Id))
            .ToDictionaryAsync(t => t.Id, cancellationToken);
    }
}

public class UserByEmailDataLoader : BatchDataLoader<string, AspNetUser>
{
    private IDbContextFactory<ApplicationDbContext> _dbContextFactory;

    protected UserByEmailDataLoader(IBatchScheduler batchScheduler, IDbContextFactory<ApplicationDbContext> dbContextFactory)
        : base(batchScheduler)
    {
        _dbContextFactory = dbContextFactory;
    }

    protected override async Task<IReadOnlyDictionary<string, AspNetUser>> LoadBatchAsync(IReadOnlyList<string> emails, CancellationToken cancellationToken)
    {
        await using var dbContext = await _dbContextFactory.CreateDbContextAsync(cancellationToken);

        return await dbContext.AspNetUsers.Where(s => emails.Contains(s.Email))
            .ToDictionaryAsync(t => t.Id, cancellationToken);
    }
}

public class UsersByEmailsDataLoader : GroupedDataLoader<string, AspNetUser>
{
    private IDbContextFactory<ApplicationDbContext> _dbContextFactory;

    protected UsersByEmailsDataLoader(IBatchScheduler batchScheduler, IDbContextFactory<ApplicationDbContext> dbContextFactory)
        : base(batchScheduler)
    {
        _dbContextFactory = dbContextFactory;
    }

    protected override async Task<ILookup<string, AspNetUser>> LoadGroupedBatchAsync(IReadOnlyList<string> emails, CancellationToken cancellationToken)
    {
        await using var dbContext = await _dbContextFactory.CreateDbContextAsync(cancellationToken);

        return dbContext.AspNetUsers.Where(s => emails.Contains(s.Email))
            .ToLookup(t => t.Id);
    }
}
```

The query class:
```
[ExtendObjectType("Query")]
public class AccountQueries
{
    [UseApplicationDbContext]
    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public IQueryable<AspNetUser> GetUsers([ScopedService] ApplicationDbContext context) 
        => context.AspNetUsers;

    public async Task<AspNetUser> GetUserByIdAsync(
        string id,
        UserByIdDataLoader dataLoader,
        CancellationToken cancellationToken)
        => await dataLoader.LoadAsync(id, cancellationToken);

    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public async Task<IEnumerable<AspNetUser>> GetUsersByIdsAsync(
        string[] ids,
        UserByIdDataLoader dataLoader,
        CancellationToken cancellationToken)
        => await dataLoader.LoadAsync(ids, cancellationToken);

    public async Task<AspNetUser> GetUserByEmailAsync(
        string email,
        UserByEmailDataLoader dataLoader,
        CancellationToken cancellationToken)
        => await dataLoader.LoadAsync(email, cancellationToken);

    [UsePaging]
    [UseFiltering]
    [UseSorting]
    public async Task<IReadOnlyList<AspNetUser[]>> GetUsersByEmailsAsync(
        string[] emails,
        UsersByEmailsDataLoader dataLoader,
        CancellationToken cancellationToken)
        => await dataLoader.LoadAsync(emails, cancellationToken);
}
```

Query: e.g.
```{
    userByEmail(email: "me@world.com") {
            id
            email
    }
}
```

### Steps to reproduce

1. take code from above
2. make query 

### Relevant log output

```shell
{
    "errors": [
        {
            "message": "Unexpected Execution Error",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "userByEmail"
            ],
            "extensions": {
                "message": "Could not create an instance of `Bista.IdM.API.GraphQL.DataLoader.UserByEmailDataLoader`",
                "stackTrace": "   at HotChocolate.Utilities.ServiceFactory.CreateInstance(Type type)\r\n   at HotChocolate.Types.DataLoaderResolverContextExtensions.CreateDataLoader[T](IServiceProvider services)\r\n   at HotChocolate.Types.DataLoaderResolverContextExtensions.<>c__DisplayClass9_0`1.<DataLoader>b__0()\r\n   at HotChocolate.Fetching.DefaultDataLoaderRegistry.<>c__DisplayClass2_0`1.<GetOrRegister>b__0(String s)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at HotChocolate.Fetching.DefaultDataLoaderRegistry.GetOrRegister[T](String key, Func`1 createDataLoader)\r\n   at HotChocolate.Fetching.DefaultDataLoaderRegistry.GetOrRegister[T](Func`1 createDataLoader)\r\n   at HotChocolate.Types.DataLoaderResolverContextExtensions.DataLoader[T](IResolverContext context)\r\n   at lambda_method219(Closure , IResolverContext )\r\n   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
            }
        }
    ]
}
```

### Product

Green Donut

### Version

12.6.1

**Comment by the-dag** [comment]
HotChocolate is a heap of crap and should be avoided if at all possible. The "documentation" consists of a few examples, and the only people who can possibly use it are those who like to spend lots of time studying the open-sourced code of the stuff they are using, and, at the other end of the spectrum, those content to rely on StackOverflow to overcome all challenges.

I had the same behaviour as the OP. Two very similar data loaders, but one working and the other giving the not very helpful error message "Could not create an instance of Foo.Bar.ExampleLoader". I bet internally in HC, some call was made to some .net method - say, Activator.CreateInstance - and they caught that exception and threw another they felt was much clearer. The only little problem being that all hint of WHY it fails to create the loader is now gone. (In general, the most valuable diagnostics often result when using the exception chain as it was designed, i.e. catch, and throw another adding information, but keeping the inner exception...)

There is no mention of needing anything in StartUp in the provided examples: https://chillicream.com/docs/hotchocolate/fetching-data/dataloader

Nor had I done anything to configure these dependencies, yet one worked and the other did not. 

After wasting a lot of time scratching my head I eventually noticed that I had published the constructor (i.e. declared a public constructor, still invoking the protected base constructor of course) in the loader that worked, but not in the other. How much more useful it would have been if there had been an inner exception a la "There is no publicly available constructor on type Foo.Bar.ExampleLoader" - like you'd get from Activator.CreateInstance for example. That would have immediately pinpointed what was wrong and made it very quick to fix.

But even worse than this is how it behaves server-side. No errors or warnings get logged, there's nothing in the console, and even when I tried to turn on "break on exception" for all Common Language Runtime exceptions, everything looked as if it worked perfectly on the server-side. Combined with the brilliant idea that all responses including all errors should have HTTP status 200 OK (admittedly this is Facebook's lunacy, not ChilliCream's) it seems only the client would have the slightest idea anything went wrong.

Last but not least: even though data loaders are kind of cool, it's not cool that ChilliCream couldn't just get by with one type. The general case of one key with zero or more values covers the case of one key, one value rather well. The point of the dataloader is just to batch the keys so we don't have to make many trips to a database or make many calls to our REST service or whatever data source we are using - it is NOT a good idea to "optimize" for the case where each key corresponds to zero or one values. But GreenDonut.DataLoaderBase single model, which isn't especially user friendly, is hidden from view and replaced by two, the BatchDataLoader and the GroupedDataLoader, even though the latter would do perfectly well for the first case. One wants an IReadOnlyDictionary<TKey, TValue>, but the other wants an ILookUp<TKey, TValue> which is pretty close to an IDictionary<TKey, TValue[]> only much less easy to understand. This mess is partly Microsoft's fault, but there is no reason to opt in to it.
