### ISSUE TITLE
Likely copy/paste error found in HotChocolate.Types.UsePagingAttribute

### ISSUE THREAD

**Issue by treymack** [ChilliCream/hotchocolate#4815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just familiarizing myself with the codebase and ran across what's likely a copy / paste error, given there are default values for the mis-mapped fields in HotChocolate.Types.Pagination.PagingDefaults.

``` csharp
    /// <summary>
    /// Allow backward paging using <c>last</c> and <c>before</c>
    /// </summary>
    public bool AllowBackwardPagination
    {
        get => _allowBackwardPagination ?? PagingDefaults.AllowBackwardPagination;
        set => _allowBackwardPagination = value;
    }

    /// <summary>
    /// Defines if the paging middleware shall require the
    /// API consumer to specify paging boundaries.
    /// </summary>
    public bool RequirePagingBoundaries
    {
        get => _requirePagingBoundaries ?? PagingDefaults.AllowBackwardPagination;
        set => _requirePagingBoundaries = value;
    }

    /// <summary>
    /// Connection names are by default inferred from the field name to
    /// which they are bound to as opposed to the node type name.
    /// </summary>
    public bool InferConnectionNameFromField
    {
        get => _inferConnectionNameFromField ?? PagingDefaults.AllowBackwardPagination;
        set => _inferConnectionNameFromField = value;
    }
```
The 2nd and 3rd properties listed above are all mapped to the default for `AllowBackwardPagination` if no override is supplied.

### Steps to reproduce

1. Visit https://github.com/ChilliCream/hotchocolate/blob/c479c10343f22328f708dc4d8e80f98a76bbf518/src/HotChocolate/Core/src/Types.CursorPagination/Extensions/UsePagingAttribute.cs

### Product

Hot Chocolate

### Version

12 (HEAD of repo)

**Comment by tobias-tengler** [comment]
Thanks @treymack for reporting! Would you mind submitting a PR to address the issue?
