### ISSUE TITLE
Schema first: binding of input fails if has no enum value.

### ISSUE THREAD

**Issue by mcuzmenco** [ChilliCream/hotchocolate#4818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is for Schema First approach.

### Steps to reproduce

For example, input type `BookInput` has a enum field, which is not required. 
```
 input BookInput {
  title: String!
  author: String!
  genre: Genre
}

 enum Genre {
  UNKNOWN
  NON_FICTION
  FICTION
}
```

I have the following C# classes:
```csharp
       public class Book
	{
		public int Id { get; set; }
		public string Title { get; set; }
		public string Author { get; set; }
		public Genre Genre { get; set; }
	}

	public enum Genre
	{
		Unknown = 0,
		NonFiction = 1,
		Fiction = 2
	}
````
Also, type input is explicitly bound as runtime type during schema configuration:
```csharp
 ...
.BindRuntimeType<BookInput>()
````

The request will fail if enum value is not provided.
```
{
    "errors": [
        {
            "message": "Variable `input` got an invalid value.",
            "locations": [
                {
                    "line": 1,
                    "column": 59
                }
            ],
            "extensions": {
                "code": "HC0016",
                "variable": "input"
            }
        }
    ]
}
```

Bug reproduction repository:
https://github.com/mcuzmenco/HotChocolateOptionalEnumBug

### Additional Context?

It was working in HC v11, now it seems to be a breaking change when moving to HC v12.

### Product

Hot Chocolate

### Version

12.6.1

**Comment by mcuzmenco** [comment]
Looks like the same problem affects all `Boolean` fields too. Throws the same exception.

**Comment by erwan-joly** [comment]
Note their seems to be discrepencies between c# and gql

```
public Genre Genre { get; set; }
```
should be
```
public Genre? Genre { get; set; }
```

as both enum and boolean are value type.
