### ISSUE TITLE
Report problem in vscode with not exists in visual studio 2022 (Ambiguity between...)

### ISSUE THREAD

**Issue by liphvf** [ChilliCream/hotchocolate#4823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Visual Studi Code has a bunch of erros with Ambiguity after generated class to use.

I describe all problem in issue report for omnisharp https://github.com/OmniSharp/omnisharp-vscode/issues/5098

That erro no occur in Visual Studio 2022.

Sometimes, after build another obj folder outside of project folder has created with 2 files **GraphQlClient.code** and **GraphQlClient.GraphQlClient.CSharp.md5** . Exemplo:

├── anisync
│   ├── anisync.csproj
│   ├── bin
│   │   └── Debug
│   │       └── net6.0
│   │           ├── anisync.deps.json
│   │           ├── anisync.dll
│   │           ├── anisync.exe
│   │           ├── anisync.pdb
│   │           ├── anisync.runtimeconfig.json
│   │           ├── Microsoft.Extensions.Configuration.Abstractions.dll
│   │           ├── Microsoft.Extensions.Configuration.Binder.dll
│   │           ├── Microsoft.Extensions.Configuration.dll
│   │           ├── Microsoft.Extensions.DependencyInjection.Abstractions.dll
│   │           ├── Microsoft.Extensions.DependencyInjection.dll
│   │           ├── Microsoft.Extensions.Http.dll
│   │           ├── Microsoft.Extensions.Logging.Abstractions.dll
│   │           ├── Microsoft.Extensions.Logging.dll
│   │           ├── Microsoft.Extensions.Options.dll
│   │           ├── Microsoft.Extensions.Primitives.dll
│   │           ├── Newtonsoft.Json.dll
│   │           ├── StrawberryShake.Core.dll
│   │           ├── StrawberryShake.Resources.dll
│   │           ├── StrawberryShake.Tools.Configuration.dll
│   │           └── StrawberryShake.Transport.Http.dll
│   ├── GraphQlClients
│   │   ├── Generated
│   │   │   └── GraphQlClient.StrawberryShake.cs
│   │   ├── Queries
│   │   │   └── GetUserId.graphql
│   │   ├── schema.extensions.graphql
│   │   └── schema.graphql
│   ├── LICENSE
│   ├── obj
│   │   ├── anisync.csproj.nuget.dgspec.json
│   │   ├── anisync.csproj.nuget.g.props
│   │   ├── anisync.csproj.nuget.g.targets
│   │   ├── berry
│   │   │   ├── GraphQlClient.code
│   │   │   └── GraphQlClient.GraphQlClient.CSharp.md5
│   │   ├── Debug
│   │   │   └── net6.0
│   │   │       ├── anisync.AssemblyInfo.cs
│   │   │       ├── anisync.AssemblyInfoInputs.cache
│   │   │       ├── anisync.assets.cache
│   │   │       ├── anisync.csproj.AssemblyReference.cache
│   │   │       ├── anisync.csproj.BuildWithSkipAnalyzers
│   │   │       ├── anisync.csproj.CopyComplete
│   │   │       ├── anisync.csproj.CoreCompileInputs.cache
│   │   │       ├── anisync.csproj.FileListAbsolute.txt
│   │   │       ├── anisync.dll
│   │   │       ├── anisync.GeneratedMSBuildEditorConfig.editorconfig
│   │   │       ├── anisync.genruntimeconfig.cache
│   │   │       ├── anisync.GlobalUsings.g.cs
│   │   │       ├── anisync.pdb
│   │   │       ├── apphost.exe
│   │   │       ├── ref
│   │   │       │   └── anisync.dll
│   │   │       └── refint
│   │   │           └── anisync.dll
│   │   ├── project.assets.json
│   │   └── project.nuget.cache
│   ├── omnisharpLogAfterReinstall.txt
│   ├── omnisharpLog.txt
│   ├── Program.cs
│   └── README.md
└── **obj** <-- HERE!
    └── berry
        ├── GraphQlClient.code
        └── GraphQlClient.GraphQlClient.CSharp.md5

### Steps to reproduce

1. Build application in Visual Studio code
2. If that problem not appear, edit GetUserId.graphql with this:

```
query GetUserId ($name: String){
  User(name: $name) {
    id
  }
}
```

Sometimes only occur when run.

### Relevant log output

```shell
[{
	"resource": "/e:/Github/anisync/GraphQlClients/Generated/GraphQlClient.StrawberryShake.cs",
	"owner": "csharp",
	"code": "CS0229",
	"severity": 8,
	"message": "Ambiguity between 'GetUserIdResult.User' and 'GetUserIdResult.User' [anisync]",
	"source": "csharp",
	"startLineNumber": 11,
	"startColumn": 13,
	"endLineNumber": 11,
	"endColumn": 17
}]
```

### Product

Strawberry Shake

### Version

12.6.2

**Comment by michaelstaib** [comment]
This is fixed with the V13 previews. Upgrade to the lates 13 preview and after the upgrade restart your IDE and it will work.

**Comment by liphvf** [comment]
@michaelstaib after update new erros appers. Please check this branch: https://github.com/liphvf/anisync/tree/isolete-omnisharp-problem

New steps in that branch:
1- Update dotnet tools
2- Update package
3- Re-gerated

Other attempts:
- Update only package
- Update only dotnet tools and regerated.

# Log Erros on build:
In that file: https://github.com/liphvf/anisync/blob/isolete-omnisharp-problem/AfterUpdateToVersion13log.txt

**Comment by michaelstaib** [comment]
Delete the generated directory. There are no more generated files.

**Comment by michaelstaib** [comment]
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/9714350/157542060-82e0675b-1580-4a89-b06b-d364525fced1.png">

**Comment by michaelstaib** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="13.0.0-preview.11" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="13.0.0-preview.11" />
  </ItemGroup>

</Project>
```

**Comment by michaelstaib** [comment]
1. delete the generated folder
2. update the packages to 13
3. dotnet restore
4. reload vscode so that it correctly reloads the source genertors 

After this it will work just fine in any IDE

**Comment by chneau** [comment]
Just found a workaround.

For your client project where you have done the dotnet graphql init command, it will generate a .graphqlrc.json file.

Just set the emitGeneratedCode to false, then remove all the generated files, clean the repo with dotnet clean and restart your IDE. Works perfectly fine on VSCode with <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.12.1" />. Building the solution does not throw any error.

**Comment by Xuhv** [comment]
> Just found a workaround.
> 
> For your client project where you have done the dotnet graphql init command, it will generate a .graphqlrc.json file.
> 
> Just set the emitGeneratedCode to false, then remove all the generated files, clean the repo with dotnet clean and restart your IDE. Works perfectly fine on VSCode with . Building the solution does not throw any error.
> 
> Working perfectly fine with `<PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.12.1" />`, no more ambiguous errors.

In this way, vscode works fine, but vs2022 gives some red lines.
![7](https://user-images.githubusercontent.com/58001829/203701063-2575e2d8-0358-4d2c-b79f-21cdb6e7b0d2.png)

**Comment by michaelstaib** [comment]
There are a couple of reasons we dropped source generators for version 13... 
- IDEs support different versions of Source Generators. This is difficult to explain and also not very clear.
- Source Generators cannot be pipelined leading to issues with Blazor

**Comment by MelGrubb** [comment]
I am also seeing these red squigglies all over the place. Are you saying that you are no longer using Source Generators in v13? The really odd thing about this is that not everyone on my team is seeing these, only me. I've been going crazy deleting bin and obj folders, cleaning the solution, disabling ReSharper, etc. trying to figure out the difference.

Does this mean it's back to generated source files again? In that case we _shouldn't_ try to suppress the file generation anymore, right?

**Comment by xaimaran** [comment]
You can do one of these two things:

1- Create a new project inside your solution, put your graphql stuffs in it and generate your codes. Add a project reference in your other projects and unload the Graphql project from your solution.

2- Leave it where ever it is and just set <emitGeneratedCode> inside your rc file to <false> and build your project.

The first solution is better because it can find the exact codes inside your dll. No red line under anything.

**Comment by judebowman** [comment]
> I am also seeing these red squigglies all over the place. Are you saying that you are no longer using Source Generators in v13? The really odd thing about this is that not everyone on my team is seeing these, only me. I've been going crazy deleting bin and obj folders, cleaning the solution, disabling ReSharper, etc. trying to figure out the difference.
> 
> Does this mean it's back to generated source files again? In that case we _shouldn't_ try to suppress the file generation anymore, right?

@MelGrubb  - do you use ReSharper or Rider and your co-workers do not?  That is the experience I have seen with my co-workers.  When I set `emitGeneratedCode` to false when using ReSharper, I do not get the red squigglies but they do.  When we set `emitGeneratedCode` to true, I get red squigglies and they do not...

It has been said that version 13, due sometime in the next month according to @michaelstaib, should fix this issue.

By the way - small world.  I believe we both worked at Dynamit many years ago in Columbus.  I saw you on the Slack channel for HC/SS and recognized your name.

**Comment by MelGrubb** [comment]
We're all using ReSharper, except for the front-end guys with their Macs... poor guys. And yes, V13 should theoretically fix it, but I can use 13 at all because it chokes on our schema file even though v12 likes it just fine. I'd mentioned that problem separately multiple times, and it always gets lightly acknowledged and then never responded to. I check every now and then to see if maybe a new release has addressed the issue. So far, nothing.
