### ISSUE TITLE
dynamic DataLoader name not respected

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#4856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a dynamic name for a dataloader, the execution doesn't respect the different names and executes the dataloader only once.

Slack discussion here: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1640938992150400
Repro: https://github.com/OneCyrus/hcresolver_repro

three dataloaders are registered in the repro but only one is executed.
![image](https://user-images.githubusercontent.com/7747800/158205723-9984c9d2-fc2b-4ee2-b0e7-08ce9e188f36.png)

### Steps to reproduce

a repo is here: https://github.com/OneCyrus/hcresolver_repro

the repro query is in the readme.md

### Product

Hot Chocolate

### Version

12.x

**Comment by michaelstaib** [comment]
Found the issue. With the reworked DataLoader, we use a single cache. The cache key is composed of the type name and the key provided for an item. This means the DataLoader exists correctly in the DataLoaderRegistry but they are using all the same cache partition.

I will fix it later today.

**Comment by michaelstaib** [comment]
This shows again ... having a repro helps us find and fix things quickly :D

**Comment by michaelstaib** [comment]
Related to #4744

**Comment by michaelstaib** [comment]
This one is now fixed and will be integrated into:
13.0.0-preview.17
12.8.0-preview.1
