### ISSUE TITLE
Configure is never called for ObjectTypeExtension instances provided in ITypeModule.CreateTypesAsync

### ISSUE THREAD

**Issue by DaveRMaltby** [ChilliCream/hotchocolate#4867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If `ObjectTypeExtension.Configure()` is overridden or if an `Action<IObjectTypeDescriptor>` is provided to the ObjectTypeExtension ctor, neither is ever called.  For example, in my dynamic schema, I am adding an `ObjectFieldDefinition` to my query.  But in order to provide this to the `ITypeModule.CreateTypesAsync`, it must be added to the `ObjectTypeDefinition.Fields` query extension and converted into a `ObjectTypeExtension` like so:
```
ObjectTypeExtension.CreateUnsafe(typeDefinition)
```
This was all working fine until I wanted to add paging, sorting and filtering to my dynamically added schema field queries.  After much pouring through the Hot Chocolate code, I have ultimately determined that I should be able to inject these facilities, by deriving a class off of `ObjectTypeExtension` like so:  (The important call below is the `fieldDescriptor.UseSorting()`):

```
private class ObjectTypeExtensionEx : ObjectTypeExtension
    {
        public ObjectTypeExtensionEx()
            : base()
        {
        }

        protected override void Configure(IObjectTypeDescriptor descriptor)
        {
            var fieldDescriptor = descriptor as ObjectFieldDescriptor;
            fieldDescriptor.UseSorting(null);
            base.Configure(descriptor);
        }

        public static ObjectTypeExtensionEx CreateUnsafe(ObjectTypeDefinition definition)
            => new() { Definition = definition };
    }

```
and then call the `CreateUnsafe` static method on this derived class as the type extension to return for `ITypeModule.CreateTypesAsync()`.  
Unfortunately, in my testing the overridden `ObjectTypeExtensionEx.Configure()` never gets called.  
Maybe this approach wasn't intended to be supported though.  If not, is there another way that dynamic schemas can utilize Hot Chocolate's built in facilities for paging, sorting and filtering?
Thanks!
Note:  I'm happy to contribute a PR, but would need some guidance as this is a complicated area of the Hot Chocolate code base.

### Steps to reproduce

1. Clone the repo - https://github.com/DaveRMaltby/HotChocolateNotCallingConfigure
2. Set break points at https://github.com/DaveRMaltby/HotChocolateNotCallingConfigure/blob/master/ObjectTypeExtensionEx.cs#L12 and https://github.com/DaveRMaltby/HotChocolateNotCallingConfigure/blob/master/ObjectTypeExtensionEx.cs#L17
3. Build and run application.
4. Browse to http://localhost:5000/graphql
5. Notice how the schema only at the one query called 'tables'
6. Run the following operation:
```
mutation
{
   extendSchema(schemaDescription: { queryName: "Joe"}) {
     success
   }
}
```
7. Reload the schema in Banana Cakepop and notice that it breakpoints in the ctor of ObjectTypeExtensionEx, but not in the overridden Configure() method.  Also, you can see that the UseSorting() wasn't called and therefore the new query called 'Joe' doesn't have a UserInfoSortInput parameter like it would have had if the UseSorting() call in the Configure() method was executed.

### Product

Hot Chocolate

### Version

12.5.0

**Comment by michaelstaib** [comment]
This is because you are initializing the type with a definition. If you set the definition it's telling the type that there is no need to initialize and configure a definition. Remove the create factory and the constructor and it will be called.

**Comment by DaveRMaltby** [comment]
> This is because you are initializing the type with a definition. If you set the definition it's telling the type that there is no need to initialize and configure a definition. Remove the create factory and the constructor and it will be called.

Bravo, @michaelstaib!  I misunderstood the example for Type Modules and assumed that all the types returned by a Type Module had to provide a definition using the CreateUnsafe() method.  I have provided a [commit](https://github.com/DaveRMaltby/HotChocolateNotCallingConfigure/commit/6770b629740fb7ce085b3f8909f92d9e28f78c0f) to my repo mentioned in the "Steps to Reproduce" above, in case someone else is looking for the solution in the future.  

Thank you for the quick reply!  I love what you guys have done here!
