### ISSUE TITLE
Exceptions logged in DiagnosticListeners are swallowed

### ISSUE THREAD

**Issue by cliedeman** [ChilliCream/hotchocolate#4873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a DiagnosticListener for Logging and another for Telemetry.
An exception was thrown in the telemetry listener which I dont have access (Neither ServerEventListener, ExecutionListner or event ErrorFilter has access to the error

### Steps to reproduce

1. Register the following listener

```
public class MyExecutionDiagnosticEventListener : ExecutionDiagnosticEventListener
{
    
    public override IDisposable ExecuteRequest(IRequestContext context)
    {
        throw new Exception("Event Listener Error");
    }
}
```

This was the only way to managed to get output
```
services.AddGraphQLServer()
    .ModifyRequestOptions(opt => opt.IncludeExceptionDetails = true)
```

### Product

Hot Chocolate

### Version

12.5.0

**Comment by michaelstaib** [comment]
It is not allowed to throw any errors in the diagnostic listeners. Make sure that your code is never throwing exceptions here. Logging, tracing, and instrumentation components should not cause the execution error.

**Comment by cliedeman** [comment]
Thanks for the response.

This is not mentioned anywhere in the docs though. Can I add it?
https://chillicream.com/docs/hotchocolate/server/instrumentation

**Comment by tobias-tengler** [comment]
Yeah sure. I think it would belong as an appendix to this warning message:
![Screenshot_20220318_195601](https://user-images.githubusercontent.com/45513122/159067054-f2223fe3-0677-4aa4-a00e-f815c4895a11.png)
You can make the change [here](https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/server/instrumentation.md) and submit a pull request. If you find anything else missing or wrong, feel free to also add / correct it!
