### ISSUE TITLE
Cannot override field's type in ObjectType.Configure if used with BindFiledImplicitly

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#4875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is abbreviated version from our solution that we are migratin from v10 to v12:
```
class Instrument {
    public int id {get;set;}
    public decimal? Nominal { get; set; }
}
class InstrumentType: ObjectType<Instrument> {
    protected override void Configure(IObjectTypeDescriptor<Instrument> descriptor) { 
         descriptor.BindFieldsImplicitly(); 
          // We were reaplacing type of the field from DecimalType (which would be assigned automatically based on CLR type) to PriceType with custom resolver that transforms decimal to instance of Price class 
         descriptor.Field<InstrumentResolver>(_ => _.GetNominal(default)).Type<PriceType>();
    }
}
```
In v10 the type of the field nominal was Price.
In v12 the type of the field nominal is Decimal. 

If we use [ExtendObjectType]
```
[ExtendObjectType(Name = "Instrument")]
public class InstrumentResolver { 
     public Price GetNominal([Parent] Instrument parent) => /*omitted*/;
}
```
The type gets replaced and now it's correcly PriceType.

I suspect that order of object type's lifecycle changed and field set manually on descriptor object are applied before implicit binding. I suppose this is a bug (or is there another way how to override implicitly bound fields?).

This does not work even if we specify the type without specifying resolver method (re-typing the field nominal using descriptor object).

### Steps to reproduce

1. Have a DTO that has property in decimal
2. Have an object type that binds DTO's fields implicitly
3. Override field's type using descriptor obejct in Configure method
4. Observer that type still corresponds to the DTO's property type and not configured type

### Additional Context?

Migrating from v10 to v12.

### Product

Hot Chocolate

### Version

12.7.0

**Comment by cts-tradeit** [comment]
Additional info: Method GetNominal on resolver does not get called (so whole configuration gets ingored, not just the type)

**Comment by PascalSenn** [comment]
did you register the type on startup?

**Comment by michaelstaib** [comment]
Can you provide a repro? I mean proper code.
