### ISSUE TITLE
Wrong code documentation on HotChocolateDataRequestBuilderExtensions.AddSorting() and HotChocolateDataRequestBuilderExtensions.AddProjections()

### ISSUE THREAD

**Issue by kondelik** [ChilliCream/hotchocolate#4879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is only single doc comment inside [HotChocolateDataRequestBuilderExtensions](https://github.com/ChilliCream/hotchocolate/blob/8f0d403b1807b56215e188f2c90aec2bd5511bf2/src/HotChocolate/Data/src/Data/Extensions/HotChocolateDataRequestBuilderExtensions.cs) copy pasted to all methods.

```c#
/// <summary>
/// Adds filtering support.
/// </summary>
/// <param name="builder">
/// The <see cref="IRequestExecutorBuilder"/>.
/// </param>
/// <param name="name">
/// The filter convention name.
/// </param>
/// <returns>
/// Returns the <see cref="IRequestExecutorBuilder"/>.
/// </returns>
```

`AddSorting()` and `AddProjections()` should not have IntelliSense about filtering.

[Copy - paste](https://github.com/ChilliCream/hotchocolate/pull/2310/commits/8065afc32fa34416337d1b06e28066ae0433d7c4) and [no reviewer](https://github.com/ChilliCream/hotchocolate/pull/2310) 😄 What could go wrong... 🤣 

### Steps to reproduce

In Visual Studio (IntelliSense)
1. hover mouse over services.AddGraphQLServer().(...).**AddProjections**()
2. hover mouse over services.AddGraphQLServer().(...).**AddSorting**()

### Product

Hot Chocolate

### Version

12.6.0

**Comment by tobias-tengler** [comment]
If you want to, you can create a PR and fix the descriptions.
We'd love your contribution! :)
