### ISSUE TITLE
"Name ... was already registered by another type" when mixing schema-first and annotation-based approach

### ISSUE THREAD

**Issue by aloker** [ChilliCream/hotchocolate#4888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a type has been added through a schema-first approach (such as AddDocumentFromString or AddRemoteSchema), HC throws a SchemaException "The name ... was already registered by another type" when the bound runtime type is used as an output type.

I'm not sure whether this is a bug, a misunderstanding or incorrect configuration.

### Context: 
ASP.NET Core service, .NET 6
HC version 12.7

### Setup:
Define type `User` as schema-first, bind it to type `User`
```c#
services.AddGraphQLServer()
    .InitializeOnStartup()
    .AddQueryType(descriptor => descriptor.Name(OperationTypeNames.Query))
    .AddDocumentFromString(@"
type User {
	id: ID!
	name: String!
}
")
    .BindRuntimeType<User>()
    .AddTypeExtension<Query>();
```

### Types

```c#
public record User(Guid Id, string Name);

[ExtendObjectType(OperationTypeNames.Query)]
public class Query
{
    public User GetUser()
    {
        return new User(new Guid("8A0E7B54-9A1F-4D7A-9B25-4A98B953B4B4"), "John Doe");
    }
}
```

I'd expect HC not to try to register User again as it was already defined with AddDocumentFromString/BindRuntimeType.

### Workaround
If the GraphQL type is specified explicitly with a GraphQLType- attribute, no errors thrown
```c#
[ExtendObjectType(OperationTypeNames.Query)]
public class Query
{
    [GraphQLType("User!")]
    public User GetUser()
    {
        return new User(new Guid("8A0E7B54-9A1F-4D7A-9B25-4A98B953B4B4"), "John Doe");
    }
}
```

### Relevant log output

```shell
Unhandled exception. HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The name `User` was already registered by another type. (HotChocolate.Types.ObjectType<Proxy.User>)
```

### Additional Context?

Originally, we found this issue in the context of schema stitching. The downstream service defines a type User. In the stitching service, we'd like to add another Query field that uses that type. 

However, as shown above, the issue can be reproduced without stitching at all.

### Product

Hot Chocolate

### Version

12.7.0

**Comment by michaelstaib** [comment]
You are mixing approaches here that is why the annotation based discovery already dound the user type and inferred it ... you can stop inference by annotation.

```csharp
[GraphQLType("User!")]
    public User GetUser()
``` 

Hot Chocolate explicitly allows to mix schema building approaches for flexibility. But in this case you infact created two types. So the error is correct.

Why do you in this case use SDL-First in combination with the annotation-based schema bulding approach?

**Comment by aloker** [comment]
The actual use case involves schema stitching, not a locally defined schema. We have a gateway server that uses stitching to include the GraphQL api of a backend server (for example: `users: [User!]!`). However, the gateway server adds another query by itself that uses a type (`User`) coming from the backend server as its output type (let's say `me: User!`) So basically it's AddRemoteSchema instead of AddDocumentFromString, but the problem is exactly the same.

**Comment by OrionFOTL** [comment]
@aloker, did you ever figure this out by any chance?
