### ISSUE TITLE
BCP Authorization Code flow not working with Azure AD

### ISSUE THREAD

**Issue by dulfe** [ChilliCream/hotchocolate#4889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NOTE: This was initially reported thru [Slack](https://hotchocolategraphql.slack.com/archives/C02A2NX3WAH/p1647034759724299).

BCP fails to get a token when using `Authorization Code` flow against `Azure Active Directory`. 

### Steps to reproduce

Setting Credentials to `As Basic Auth Header` does not send `client_id` to the token endpoint:

![image](https://user-images.githubusercontent.com/12144048/159712209-ebdedd6c-9233-46ca-86ed-a1d06b3454b2.png)

Error:

![image](https://user-images.githubusercontent.com/12144048/159712433-072e9d67-7574-4474-997f-c77d205f9e02.png)

Setting Credentials to `In Request Body` does send `client_id` as well as an empty `client_secret` but it also returns an error:

![image](https://user-images.githubusercontent.com/12144048/159712897-e5028140-6ff4-43c3-9b10-c7a5c0d6dceb.png)

According to an issue raised in the MSAL repo (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2482) it means the HTTP Header `ORIGIN `is not been sent.

After setting that value in the BCP Auth page, I can see that value is not been used.

![image](https://user-images.githubusercontent.com/12144048/159713386-a888038c-0ebe-4f73-a49c-a1baf970c697.png)

![image](https://user-images.githubusercontent.com/12144048/159712812-6dd3c14c-9149-4a81-8dd3-401adca8a435.png)

### Relevant log output

```shell
Error messages are included in the screenshots.
```

### Additional Context?

AAD Application has been setup as SPA like this:

![image](https://user-images.githubusercontent.com/12144048/159713956-02836a68-1c8b-4df2-b4ea-bb7f66bd68ee.png)

### Product

Banana Cake Pop

### Version

Desktop / Preview 31

**Comment by michaelstaib** [comment]
Thanks for reporting!

**Comment by michaelstaib** [comment]
If you are on slack give me a ping and I point you to a discussion that shows the solution to this.

https://slack.chillicream.com

**Comment by benv-nti** [comment]
I'm having the same issue.  Is it possible to re-open this issue, or should I open a new one?

**Comment by srollinet** [comment]
Juste had the same issue with the web version

Response from the token endpoint
```json
{
    "error": "invalid_request",
    "error_description": "AADSTS900144: The request body must contain the following parameter: 'client_id'. Trace ID: dab07fc1-b75f-45ce-94da-6a8b3ddd0800 Correlation ID: de19ce7e-6e34-4d95-b901-28a5c2866e0e Timestamp: 2024-09-19 09:06:32Z",
    "error_codes": [
        900144
    ],
    "timestamp": "2024-09-19 09:06:32Z",
    "trace_id": "dab07fc1-b75f-45ce-94da-6a8b3ddd0800",
    "correlation_id": "de19ce7e-6e34-4d95-b901-28a5c2866e0e",
    "error_uri": "https://login.microsoftonline.com/error?code=900144"
}
```
