### ISSUE TITLE
Cannot use an IEnumerable<T> as the source of a CustomScalar

### ISSUE THREAD

**Issue by MattA48** [ChilliCream/hotchocolate#4893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You can define a custom scalar as a derivative of `ScalarType<T, TNodeType>` where T is the object that you want to convert into a leaf node of type TNodeType (i.e. StringValueNode)

It is not, however, possible to have T as an `IEnumerable<T1>`

What happens is that the code to convert T to TNodeType (TrySerialise) gets fed an individual T1, not the `IEnumerable<T1>`.

### Steps to reproduce

Our base registered ScalarType is the following:

    public class InternationalTextType : ScalarType<List<InternationalString>, StringValueNode>
    {
        public InternationalTextType()
            : base("InternationalText")
        {
        }

        public override IValueNode ParseResult(object? resultValue) => ParseValue(resultValue);

        public override bool TrySerialize(object? runtimeValue, out object? resultValue)
        {
            resultValue = null;
            if (runtimeValue is List<InternationalString> internationalStringText)
            {
                resultValue = internationalStringText.GetStringForLocale();
                return true;
            }

            return false;
        }

        protected override List<InternationalString> ParseLiteral(StringValueNode valueSyntax)
        {
            throw new System.NotImplementedException();
        }

        protected override StringValueNode ParseValue(List<InternationalString> runtimeValue) =>
            new StringValueNode(runtimeValue.GetStringForLocale());
    }

where InternationalString is an object of {lang: string, value: string}

With a GQL query that returns a List<InternationalString> I would expect TrySerialize runtimeValue to be a List<InternationalString>, however, runtimeValue is an InternationalString and so it returns false.

### Additional Context?

The use case that we're trying to solve this for is our source data contains an array of key-value pairs (string, string in our case). We want to return the value that relates to a key passed in via a header. We've not been able to do this and have had to resort to making resolvers for each field matching this pattern.

internationalStringText.GetStringForLocale(); for this case is a simple function to get a the value from the List which matches the header so the logic/code isn't that important for this issue.

We're running 11.2.2, but I don't think this is addressed in 12

### Product

Hot Chocolate

### Version

11.2.2

**Comment by michaelstaib** [comment]
This is a limitation at the moment. It still works but not implicitly. You need to annotate the property with the GraphQL type in this case. For the next release (V13), we have no plans to fix this. We will improve this at some point but it is not a pressing issue at the moment.

as a workaround you can do the following and then it will work

```
public class Foo 
{
    [GraphQLType(typeof(InternationalTextType)]
    public List<InternationalString> Bar() => ...
}
```

or if you use the fluent API use the type descriptor.
