### ISSUE TITLE
incorrect results when using 'or' filter as its translated to and in entity framework

### ISSUE THREAD

**Issue by mo-ah-dawood** [ChilliCream/hotchocolate#4894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when filter by multiple fields using 'or'
the generated command is and and the result is incorrect

lets take about the data

{ "id":1, "foodstuffs":false}
{ "id":2, "foodstuffs":false}
{ "id":3, "foodstuffs":false}
{ "id"4, "foodstuffs":false}

my query is 

```graphql
query {
  categories(where: { foodstuffs: { eq: false }, or: { id: { gt: 2 } } }) {
    nodes {
      id
      foodstuffs 
    }
  }
}

```

the result is
{ "id":3, "foodstuffs":false}
{ "id"4, "foodstuffs":false}

but it should be all the list

### Steps to reproduce

1.  run the query

### Relevant log output

```shell
the generated ef query is 

      SELECT TOP(@__p_2) [c].[Id], [c].[Foodstuffs]
      FROM [Categories] AS [c]
      WHERE ([c].[Deleted] IS NULL) AND (([c].[Foodstuffs] = @__p_0) AND ([c].[Id] > @__p_1))
```

### Product

Hot Chocolate

### Version

12.7.0

**Comment by PascalSenn** [comment]
This is by design, you can see it here in the docs: https://chillicream.com/docs/hotchocolate/fetching-data/filtering/#and--or-filter
