### ISSUE TITLE
Allow introspection queries to bypass authorization requirements

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/hotchocolate#4896]
### Is your feature request related to a problem?

I am building a public-facing API which external developers will code against. The API requires an access token to run normal queries and mutations, but there is no need to restrict introspection queries. IDEs and developer tools make introspection queries and blocking these would lead to a poor developer experience with no schema reference and no code completion.

I would like to apply the `Authorize` attribute to the query, mutation and subscription types, but unfortunately this blocks introspection queries.

### The solution you'd like

There should be an option which makes the `Authorize` attribute only apply to types in the context of a "normal" GraphQL operation, so that introspection queries are always allowed.

Ideally this would be in the startup code e.g. `IRequestExecutorBuilder.AddAuthorization`, so that it can be set in one place and apply globally to the schema.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
At the moment you need to annotate each field of the query type separate. We will improve the authorization component with version 13.

**Comment by AlexKubiesa** [comment]
@michaelstaib thank you, I'll try this. One more question - I have the same requirement in a gateway component that uses schema stitching. Is there a way to make the gateway component enforce that the user is authenticated when making a query, before sending the query to the remote API (and still not block introspection queries)? (I understand that ideally I would implement the authorization in the remote API instead, but currently this is not possible for other reasons).

**Comment by AlexKubiesa** [comment]
I managed to get authorization in the gateway by using type rewriting to add the authorize directive. However, I now get a duplicate type error from the error registry because the authorize directive is defined twice (once in one of the remote schemas, once in the gateway).

**Comment by AlexKubiesa** [comment]
Ok, I managed to overcome the duplicate type error. All sorted now I think.

**Comment by pratapkumarch** [comment]
> Ok, I managed to overcome the duplicate type error. All sorted now I think.

@AlexKubiesa,Could you please let me know how you overcame this duplicate-type error. I have two authorized directives in the gateway and the remote server.

**Comment by AlexKubiesa** [comment]
I had to tell the gateway to ignore the authorize directive from the remote server during stitching. While HC comes with an `IgnoreType` method to use in Startup, this doesn't work for directive types, so I adapted the source code of that to write my own `IgnoreDirectiveType`.

You use it like this in your startup code:
```csharp
builder
    .AddRemoteSchemaFromFile(RemoteSchemaName, RemoteSchemaPath, ignoreRootTypes)
    .IgnoreDirectiveType("authorize", RemoteSchemaName)
    ...
```

Below is the source code (insert namespace as appropriate).

HotChocolateStitchingRequestExecutorExtensions.cs:
```csharp
using HotChocolate;
using HotChocolate.Execution.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;

namespace YourNamespace
{
    public static class HotChocolateStitchingRequestExecutorExtensions
    {
        public static IRequestExecutorBuilder IgnoreDirectiveType(
            this IRequestExecutorBuilder builder,
            NameString typeName,
            NameString? schemaName = null)
        {
            if (builder is null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            typeName.EnsureNotEmpty(nameof(typeName));
            schemaName?.EnsureNotEmpty(nameof(schemaName));

            return builder.AddDocumentRewriter(
                new RemoveDirectiveTypeRewriter(typeName, schemaName));
        }
    }
}
```

RemoveDirectiveTypeRewriter.cs:
```csharp
using HotChocolate;
using HotChocolate.Language;
using HotChocolate.Stitching.Merge;
using HotChocolate.Stitching.Merge.Rewriters;
using System.Collections.Generic;
using System.Linq;

namespace YourNamespace
{
    public class RemoveDirectiveTypeRewriter : IDocumentRewriter
    {
        public RemoveDirectiveTypeRewriter(NameString typeName, NameString? schemaName = null)
        {
            TypeName = typeName.EnsureNotEmpty(nameof(typeName));
            SchemaName = schemaName?.EnsureNotEmpty(nameof(schemaName));
        }

        public NameString TypeName { get; }

        public NameString? SchemaName { get; }

        public DocumentNode Rewrite(ISchemaInfo schema, DocumentNode document)
        {
            if (SchemaName.HasValue && !SchemaName.Value.Equals(schema.Name))
                return document;

            DirectiveDefinitionNode? directiveDefinition = document.Definitions
                .OfType<DirectiveDefinitionNode>()
                .FirstOrDefault(t => TypeName.Equals(t.Name.Value));

            if (directiveDefinition is null)
                return document;

            var definitions = new List<IDefinitionNode>(document.Definitions);
            definitions.Remove(directiveDefinition);
            return document.WithDefinitions(definitions);
        }
    }
}
```

**Comment by pratapkumarch** [comment]
> I had to tell the gateway to ignore the authorize directive from the remote server during stitching. While HC comes with an `IgnoreType` method to use in Startup, this doesn't work for directive types, so I adapted the source code of that to write my own `IgnoreDirectiveType`.
> 
> You use it like this in your startup code:
> 
> ```cs
> builder
>     .AddRemoteSchemaFromFile(RemoteSchemaName, RemoteSchemaPath, ignoreRootTypes)
>     .IgnoreDirectiveType("authorize", RemoteSchemaName)
>     ...
> ```
> 
> Below is the source code (insert namespace as appropriate).
> 
> HotChocolateStitchingRequestExecutorExtensions.cs:
> 
> ```cs
> using HotChocolate;
> using HotChocolate.Execution.Configuration;
> using Microsoft.Extensions.DependencyInjection;
> using System;
> 
> namespace YourNamespace
> {
>     public static class HotChocolateStitchingRequestExecutorExtensions
>     {
>         public static IRequestExecutorBuilder IgnoreDirectiveType(
>             this IRequestExecutorBuilder builder,
>             NameString typeName,
>             NameString? schemaName = null)
>         {
>             if (builder is null)
>             {
>                 throw new ArgumentNullException(nameof(builder));
>             }
> 
>             typeName.EnsureNotEmpty(nameof(typeName));
>             schemaName?.EnsureNotEmpty(nameof(schemaName));
> 
>             return builder.AddDocumentRewriter(
>                 new RemoveDirectiveTypeRewriter(typeName, schemaName));
>         }
>     }
> }
> ```
> 
> RemoveDirectiveTypeRewriter.cs:
> 
> ```cs
> using HotChocolate;
> using HotChocolate.Language;
> using HotChocolate.Stitching.Merge;
> using HotChocolate.Stitching.Merge.Rewriters;
> using System.Collections.Generic;
> using System.Linq;
> 
> namespace YourNamespace
> {
>     public class RemoveDirectiveTypeRewriter : IDocumentRewriter
>     {
>         public RemoveDirectiveTypeRewriter(NameString typeName, NameString? schemaName = null)
>         {
>             TypeName = typeName.EnsureNotEmpty(nameof(typeName));
>             SchemaName = schemaName?.EnsureNotEmpty(nameof(schemaName));
>         }
> 
>         public NameString TypeName { get; }
> 
>         public NameString? SchemaName { get; }
> 
>         public DocumentNode Rewrite(ISchemaInfo schema, DocumentNode document)
>         {
>             if (SchemaName.HasValue && !SchemaName.Value.Equals(schema.Name))
>                 return document;
> 
>             DirectiveDefinitionNode? directiveDefinition = document.Definitions
>                 .OfType<DirectiveDefinitionNode>()
>                 .FirstOrDefault(t => TypeName.Equals(t.Name.Value));
> 
>             if (directiveDefinition is null)
>                 return document;
> 
>             var definitions = new List<IDefinitionNode>(document.Definitions);
>             definitions.Remove(directiveDefinition);
>             return document.WithDefinitions(definitions);
>         }
>     }
> }
> ```

Thank you!!
