### ISSUE TITLE
BCP: authorize with x-api-key header

### ISSUE THREAD

**Issue by spiesserheim** [ChilliCream/hotchocolate#4909]
### Is your feature request related to a problem?

I would like to set a custom header in particular the "x-api-key" to authorize the reuqest.
The server side already works fine but i could not run my request with the banana cake pop ui

### The solution you'd like

Add another Authoization Type ApiKey which fills the x-api-key header with the provided value or add a custom header Type with a key value pair wich will be added to the request headers

### Product

Banana Cake Pop

**Comment by PascalSenn** [comment]
@spiesserheim  you can add the header in the HTTP Headers section at the bottom:
![image](https://user-images.githubusercontent.com/14233220/161219637-dc345ad6-98e6-4e6f-a065-309f893ec729.png)
