### ISSUE TITLE
ConnectionPageInfo.TotalCount not being used at all for Connection's count calculation?

### ISSUE THREAD

**Issue by SpiritBob** [ChilliCream/hotchocolate#4955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can see why there's an option of passing a `Func<CancellationToken, ValueTask>` to get the count, but I don't see why it should be mandatory, especially when the page info object offers a field for count?

Furthermore, I feel like the delegate for counting can be improved. Right now, you can't do anything with it, unless you introduce a closure, which is unnecessary memory overhead. At minimum, I feel like consumers should have access to the list of nodes. Then they can simply do `.Count()` on them to get the count, if that would serve their purpose.

### Steps to reproduce

1. Return a Connection<> object whose `ConnectionPageInfo` object passed has defined `TotalCount` property.
2. The total count used by `Connection<>` does not make use of the one defined in `ConnecetionPageInfo`.

### Product

Hot Chocolate

### Version

12.0.0

**Comment by PascalSenn** [comment]
@SpiritBob  TotalCount is not the count of the returned items in the connection, it is the count of the total items in the db. It is a delegate that returns a valuetask so you can execute a query asynchronously. The delegate, and therefor the expensive fetch for total count, is only executed when you select `totalCount` in your query.

**Comment by SpiritBob** [comment]
> @SpiritBob TotalCount is not the count of the returned items in the connection, it is the count of the total items in the db. It is a delegate that returns a valuetask so you can execute a query asynchronously. The delegate, and therefor the expensive fetch for total count, is only executed when you select `totalCount` in your query.

If you're not using ORM, all of the calculations are already done as part of the returned response, i.e TotalCount will be calculated, granted you follow proper conventions and use Stored Procedures for paging + filtering (which if filtering is used, the total count reflects the filtered db entities rather than all db entities).  Perhaps offering an alternative to the usage of a delegate would be nice? 

And for what is `ConnectionPageInfo.TotalCount` property used for? In the source code, I see no references to it whatsoever. If it was meant for the count of the current items in the page - I think that can be dynamically calculated by counting the elements in the collection, so I assumed it's rather actually the property holding the count of all the db entities we query against, but that doesn't seem to be the case either?

Building a connection should be a straight-forward procedure!

**Comment by SpiritBob** [comment]
@michaelstaib Any estimates when a release with this change will be introduced?

**Comment by PascalSenn** [comment]
@SpiritBob  This was merged into main version 13 
This is the PR that backports it to v12.10 https://github.com/ChilliCream/hotchocolate/pull/5087
@michaelstaib  i think there are no breaking changes, it also adds a bunch of XML documentation to the codebase

**Comment by SpiritBob** [comment]
Weird. I'm using latest preview version (13) of `HotChocolate.AspNetCore`. Is that the issue?

**Comment by michaelstaib** [comment]
That is correct, we did not do a new 13 build for over 22 days. I have a couple of things to fix before there is a new one.

@PascalSenn did we already cherry-pick the change to 12.10?

**Comment by PascalSenn** [comment]
The PR for the backport is this one:
https://github.com/ChilliCream/hotchocolate/pull/5087
