### ISSUE TITLE
Field named the same as an operation type is treated like an operation

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/hotchocolate#4967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My GraphQL schema has a field called `subscription`, but BCP displays it as though it were an operation. It gets coloured blue instead of pink and incorrectly has an "Execute" link above it which throws an error when clicked. (Executing the full query works fine though). See screenshot:

![image](https://user-images.githubusercontent.com/35232497/163389646-fbe8158c-2589-48a4-8fcb-0cfb9a53963b.png)

### Steps to reproduce

1. Define a GraphQL schema where one of the fields of a type is called "subscription". (Presumably "query" and "mutation" would work too).
2. Create a document in BCP and write a query including the field.

### Product

Banana Cake Pop

### Version

12.6.0

**Comment by michaelstaib** [comment]
@rstaib can you have a look at this in bcp?

**Comment by rstaib** [comment]
I will have a look at it

**Comment by rstaib** [comment]
Hey @artola, maybe this one is something for you :-)

**Comment by artola** [comment]
This issue has been solved. Please upgrade to take advantage of the changes.

- **Desktop App**: check for updates, and load `Version 1.0.0-preview.41 (1.0.0-preview.41.20220628.3)` or greater.
- **Web App**: refresh or revisit the page [eat.bananacakepop.com](http://eat.bananacakepop.com/).

@AlexKubiesa Thanks for supporting our project.
