### ISSUE TITLE
No code is generated

### ISSUE THREAD

**Issue by dotnetsqlcoder** [ChilliCream/hotchocolate#4978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I followed the getting started using console application with Strawberry Shake
After the build i do not get any generated files . 
I m using the latest , and visual studio  2022 with .NET  6.0  
There is definitely a bug in there . 
The schema is generated just fine  , but there is no code generated .  

![image](https://user-images.githubusercontent.com/13077156/164011028-4c4d2ced-d4d1-4169-a4d6-a0907bf7446f.png)

### Steps to reproduce

1. follow here 
2. https://chillicream.com/docs/strawberryshake/get-started/console/#step-1-add-the-strawberry-shake-cli-tools

### Product

Strawberry Shake

### Version

12.7

**Comment by PascalSenn** [comment]
How does you .graphqlrc.json look like? we are using source generators, so the code is not emited by default, but generated on build / development time

**Comment by dotnetsqlcoder** [comment]
.graphqlrc.json

{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "extensions": {
    "strawberryShake": {
      "name": "CitroneerGraphQlClient",
      "namespace": "Demo.GraphQL",
      "url": "https://citroneertest.fasolutions.com/graphql",
      "dependencyInjection": true,
 
      "emitGeneratedCode": true,
      "razorComponents": false,
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}
schema.graphql  also looks really good .   

yes i tried  to build from Visual studio and from the command line  .  None of them generated any folder called generated .  Looked in all subfolders too .  

dotnet graphql init https://citroneertest.fasolutions.com/graphql  --clientName CitroneerGraphQlClient     --clientId xxxxxx  --clientSecret xxxxxxxxxxx   --tokenEndpoint https://xxxxxxl/openid-connect/token --Path C:\Code\Graph\Demo\Demo

I thought i check the analyzers node 
![image](https://user-images.githubusercontent.com/13077156/164106509-457f0b49-6d69-4326-a07f-a25bf068b831.png)

The generator does not generate any files caught my attention . Not sure if that matters ?

**Comment by PascalSenn** [comment]
@dotnetsqlcoder  Did you define a query file? 
![image](https://user-images.githubusercontent.com/14233220/164106845-99dc2ae0-4b5d-4ea5-a2e6-530bec4c409b.png)

It doesnt look like there is any

**Comment by dotnetsqlcoder** [comment]
i tried with and without  
![image](https://user-images.githubusercontent.com/13077156/164107192-86f1fd45-d626-4e8b-874c-618a4cd8e240.png)


query contact_information($id:String){
  contacts(contactId:$id){
    contactId
    name
    taxCountry {
      name
    }
    juridical {
      name
    }
    classification {
      name
    }
    identity {
      name
    }
    type
    profile {
      attributes {
        attributeKey
        id
        stringValue
      }
    }
   	portfolios {
      id
      name
      shortName
      accounts{
        name
        currency {
          name
        }
        bic
      }
      portfolioReport{
        accountBalance
        portfolioReportItems {
          securityName
          exposure
          marketValue
          amount
          valueChangeRelative
        }
      }
    }
  }
}

**Comment by PascalSenn** [comment]
Can you push this project on github? Then we can have a look.

**Comment by dotnetsqlcoder** [comment]
https://github.com/dotnetsqlcoder/mygraphql

**Comment by dotnetsqlcoder** [comment]
Is there some setting in visual studio that needs to change in order for code generation to work  ? 
I am using Visual Studio  2022 , updated today .

**Comment by PascalSenn** [comment]
Made a PR to you repository.

**Comment by PascalSenn** [comment]
Regarding https://github.com/dotnetsqlcoder/mygraphql/pull/1#commitcomment-71660207

Hmm it's weird that this even happend in the first place. 
Does this awlays happen when you add a graphql file?

**Comment by mmccupp** [comment]
Just wanted to chime in that I am seeing this as well. Followed every step and tried with and without a query and I cannot get any code to generate.

**Comment by PascalSenn** [comment]
did you check the PR? @mmccupp

**Comment by mmccupp** [comment]
My mistake, this is my first time using git issues and wasn't aware of the PR. My issue was the same, in that I created my graphql query inside my Visual Studio project and the .csproj automatically added an ItemGroup to remove the query file. Once I removed that from the .csproj, the rebuild successfully generated the code.

Thank you @PascalSenn for you help with this issue!
