### ISSUE TITLE
QUESTION: What might cause The argument `where` does not exist. (unit testing)

### ISSUE THREAD

**Issue by ronnyek** [ChilliCream/hotchocolate#4980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Firstly I'd like to say I searched, searched the code for this error message, and asked in slack chat first and got nowhere with that. This may not be a bug but a configuration issue.

I've got graphql integration that works, and altair / banana cake pop both can query with filtering criteria provided by a `where` keyword in the query parameters. While unit testing I get an error `The argument `where` does not exist`

### Steps to reproduce

1. Setup request executor like so
``` cs
var executor = await services
                .AddGraphQL()
                .AddQueryType<RootQuery>()
                .AddMutationType<RootMutation>()
                .AddSorting()
                .AddFiltering()
                .AddProjections()
                .BuildRequestExecutorAsync()
```
2. Execute query like so:
``` cs
var variables = new Dictionary<string, object>()
            {
                {
                    "id", new IntValueNode(34l)
                }
            };

            var query = QueryRequestBuilder.New()
                .SetQuery(@"query get($id: Long)
                {
                    getQuotes(where: {id: $id})
                    {
                        id
                    }
                }")
                .SetVariableValues(variables)
                .Create();

            var result = await _executor.ExecuteAsync(query);
```

3. Observe results of the query resulting in two errors and no data.
```
Message: The argument `where` does not exist.
SyntaxNode: {where: { id: $id }}
```
and
```
Message: "The following variables were not used: id."
SyntaxNode: {query get($id: Long) {
  getQuotes(where: { id: $id }) {
    id
  }
}}
```

### Additional Context?

I'm upgrading hotchocolate 10.2.0 to 12.7.0, and these tests worked prior to my changes / library upgrade.

It feels like this is PROBABLY something where the necessary stuff for filtering isn't being generated for the purposes of unit testing, but the configuration of the irequestbuilder is the same as I configure GraphQL in the actual server, and the Query is identical.

Again, I don't think this is ACTUALLY a bug, and probably something I'm just running into because of configuration, but as I said, even with the source of hotchocolate, I haven't been able to see what code even generates that error message.

### Product

Hot Chocolate

### Version

12.7.0

**Comment by PascalSenn** [comment]
@ronnyek  can you share the resolver of `getQuotes`?

**Comment by ronnyek** [comment]
I didnt have a lot of involvement in the initial implementation of these graphql stuff initially, but it looks like getQuotes just calls directly to a service. There is a QuoteResolver that appears to look up linked types. 

The query definition of this method looks liek
```cs
[GraphQLName("getQuotes")]
[GraphQLDescription("Retrieves quotes.")]
public async Task<List<Quote>> GetQuotes(IResolverContext resolverContext)
{
     return await _quoteService.GetQuotesAsync(resolverContext.GetQueryFields());
}
```

and the querytype
```cs
protected override void Configure(IObjectTypeDescriptor<EstimatingQuery> descriptor)
        {
            // Quote
            descriptor.Field(i => i.GetQuotes(default))
                .Type<ListType<QuoteType>>()
                .UseFiltering()
                .UseSorting();
}

```

As a side mention, Ideally this stuff will migrated to efcore integration in which a lot of this stuff wouldn't be one off... I'm just trying to get the library upgraded and functioning as it was before... then I can work with the team to migrate things to use the efcore integration (which in my experience has been much simpler and complete)

**Comment by PascalSenn** [comment]
It's hard to tell, can you provide a repro?

**Comment by ronnyek** [comment]
Oh boy.... not easily..

But I did make some realizations, I actually was setting up executor with sub query / sub mutations (that end up being members of the RootQuery/RootMutation. If I change the executor over to use the rootquery/rootmutation, and update the queries in the test to include the the query, the query executes. 

I feel like even though this isn't working for me, the way it used to, I think this is a reasonable concession. (and maybe its because rootquery/rootmutation are setting something up required for this estimating query class to behave correctly.)

**Comment by ronnyek** [comment]
You know I think this could be the problem. I've got `RootQuery->Estimating->GetQuotes`
`[GraphQLType(typeof(EstimatingMutationType))] ` exits in the root query when describing the estimating sub query, so if I was using `EstimatingQuery / EstimatingMutation` in the query executor, I could see how it may not have context to things setup in the ObjectType classes
