### ISSUE TITLE
Middleware Order breaks when adding Custom Middleware and UseFiltering at the same time

### ISSUE THREAD

**Issue by FanneYang** [ChilliCream/hotchocolate#4983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we upgrade our service from v11.3.1 to v12.7.0, the service has issue in middleware ordering. 
Previously we have one custom middleware which needs to execute after filter but before pagination. This middleware basically makes a few changes to the filtered result. 
However, after we upgrade to v12.7.0, when our custom middleware is executed (it needs to check on the value of the data so has to execute the IQueryable), the filter expression from the UseFiltering middleware is not applied when calling database to query the data, which cause a significant performance issue. 

The order of the middleware is as below.
```
[Authorize]
[UsePaging]
[CustomMiddleware]
[UseFiltering]
[UseSorting]
```

The implementation of the middleware is something like below:
```
await _next(context).ConfigureAwait(false);

if (context.Result is IQueryable<TEntity> q && context.Result != null)
{
        var data = q.ToList(); // when it execute the IQueryable here, the call to database doesn't include the filter expression in UseFiltering
        ......
}
```

One interesting thing - we found v12.0.0 worked correctly.

### Steps to reproduce

1. Create a custom middleware which needs to execute after filter but before pagination. 
2. Inside the middleware, execute the IQueryable.
3. The sql query made to Database doesn't include the filter expression in UseFiltering.

### Product

Hot Chocolate

### Version

12.7.0

**Comment by PascalSenn** [comment]
can you share a reproduction of the issue? It's hard to tell.

**Comment by michaelstaib** [comment]
Probably you did not pass the order in the constructor.

**Comment by michaelstaib** [comment]
Can we close this issue?

**Comment by FanneYang** [comment]
Thanks team for the quick update - I did a check on the middleware order vs constructor. This incorrect order only happens when you have multiple middleware for the query and yes, passing order in constructor solves that. For people like me: 


```
public class UseMyMiddlewareAttribute : ObjectFieldDescriptorAttribute
{
    public UseMyMiddlewareAttribute([CallerLineNumber] int order = 0)
    {
        Order = order;
    }

    public override void OnConfigure(IDescriptorContext context,
        IObjectFieldDescriptor descriptor, MemberInfo member)
    {
        descriptor.UseMyMiddleware();
    }
}
```


https://chillicream.com/docs/hotchocolate/execution-engine/field-middleware/#usage-as-an-attribute
