### ISSUE TITLE
MongoDb connection reset/wait queue full

### ISSUE THREAD

**Issue by MartinKuhne** [ChilliCream/hotchocolate#4994]
### Is your feature request related to a problem?

Note this is really not a direct feature request or bug report. We ran into some issues running and tuning MongoDb. I wanted to share and ask for advice.

Scenario

We are running a graphql service on Hot Chololate 12 with the MongoDb store. The environment is a linux container on k8s and the storage is mongo atlas.
We have run into two operational issues with mongo

1. Unable to read data from the transport connection: Connection reset by peer.

The underlying issue here is that when the remote closes the connection, the driver doesn't know until it wants to use the connection. The mongo driver does not retry this (even when the retry reads setting is set to true)

We set max connection idle time to 3 minutes to pre-empt the remote closing the connection. This seems to be an OK workaround. We have a ticket open with mongo support for a better solution (which may involve tuning TCP keepalives on the host or container)

Because our implementation goes directly to the IExecutable, we can not retry this with the driver ourselves.

2. The wait queue for acquiring a connection to server (server) is full.

The mongo client starts with 0 connections, opens up to 100 connections of which it opens two at a time, and maxes out at 500 connections. This likes to happen with queries like "query { customers { id companyId company { id } } } where the runtime goes and reads documents from another table one by one with high concurrency. [I am aware there is an option to write a batch fetcher]

We increased MinConnectionPoolSize and MaxConnecting which made this better but did not make it go away entirely. I remains a concern one query can consume such an excess of resources (600 connections). This is not an everyday use case for us but we likely need to implement batch data loaders rather soon because of the DoS risk.

I would find it beneficial to have a concurrency limit per query. I understand the implementation doesn't favor this (the resolvers all act independently).

Anyone else have experience with the mongo cloud?

Thanks!

### The solution you'd like

I would find it beneficial to have a concurrency limit per query. I understand the implementation doesn't favor this (the resolvers all act independently).

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
@MartinKuhne  How do you initialize the mongo client? is is registers as singleton? Do you store the `IMongoCollection<T>` also as singletons in the Database? 

There are ways to execute serially, but i work a lot with mongodb and never run into this issue. I think this is a configuration problem.

**Comment by MartinKuhne** [comment]
> @MartinKuhne How do you initialize the mongo client? is is registers as singleton? Do you store the `IMongoCollection<T>` also as singletons in the Database?
> 
> There are ways to execute serially, but i have worked with mongodb a fair amount but never ran into this issue. I think this is a configuration problem.

We have the collections as singletons and they are injected using [Service] on the individual functions. 

The failing stack is as follows (I omitted the Mongo driver stack)

```
   at HotChocolate.Data.MongoDb.MongoDbFindFluentExecutable`1.FirstOrDefaultAsync(CancellationToken cancellationToken)
   at HotChocolate.Data.Projections.FirstOrDefaultMiddleware`1.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Data.MongoDb.MongoDbProjectionProvider.<CreateExecutor>g__ExecuteAsync|2_1[TEntityType](FieldDelegate next, IMiddlewareContext context)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```
We can see the concurrency in the tracing. There are many calls into the related collection going on at the same time. This level of concurrency isn't entirely unexpected with async code.
