### ISSUE TITLE
Make StrawberryShake's subscription can finish automatically.

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#5006]
I think OnCompleted callback of console client will be triggered if add `observer.OnCompleted();` before `session.RequestSession.Dispose();`. https://github.com/ChilliCream/hotchocolate/blob/b56f0e96487fa7b2d4423d1cf1310b33aea73250/src/StrawberryShake/Client/src/Core/OperationExecutor.Observable.cs#L132-L134

In Microsoft Docs: [IObservable{T} Interface](https://docs.microsoft.com/en-us/dotnet/api/system.iobservable-1?view=net-6.0#examples)

``` csharp
   public void EndTransmission()
   {
      foreach (var observer in observers.ToArray())
         if (observers.Contains(observer))
            observer.OnCompleted();

      observers.Clear();
   }
```
IObservable should call observer's OnCompleted method to notify observer there is no further data is available.

_Originally posted by @CoreDX9 in https://github.com/ChilliCream/hotchocolate/issues/4813#issuecomment-1106632461_

**Comment by CoreDX9** [comment]
If convert `IObservable{T}` to AsyncEnumerable and use `await foreach` to enumerate stream, but observers never call `OnCompleted`, the thread will be permanently blocked.

**Comment by CoreDX9** [comment]
If web socket client closed because of network error, session don't notify subscription. `GraphQLWebSocketProtocol` need operation id to trigger `Notify` method.
So I use reflection to access nonpublic fields to complete subscription stream.

There is my solution. Can you add to StrawberryShake? This may require modifying the interface definition.

https://github.com/CoreDX9/GraphqlSubscriptionTest/blob/0ae3c6a651bf80b43d05b97a16cead6bce3f5f44/Libs/Core/OperationExecutor.Observable.cs#L133

https://github.com/CoreDX9/GraphqlSubscriptionTest/blob/0ae3c6a651bf80b43d05b97a16cead6bce3f5f44/TestClient/Program.cs#L89-L173

**Comment by kolpav** [comment]
@CoreDX9 You seem to know your way around web sockets do you think https://github.com/ChilliCream/hotchocolate/issues/4824 could be caused by what you are describing here? No need to for definite yes or no just best guess is enough. My subscriptions tests are flaky when running in CI and I can imagine not releasing threads on resource limited machine could be the reason why. Its hard to test because its like one in 20 whole test suite runs either way I guess I will find out when your PR gets released:)

**Comment by CoreDX9** [comment]
@kolpav I don't think so. Subscriptions use `Task` to process network stream, The `Watch` method will return when the task is created successfully. But the network connection may not be ready. Therefore, you can only try to check whether the subscription is working. If you want the test to be more reliable, you can only increase the number of retries and delay time.

**Comment by CoreDX9** [comment]
@kolpav If the network connection fails，`OnError` callback will be triggered. If the server actively ends the subscription, `OnComplete` callback will be triggered when the pull request #5008 merged into main branch. If the network connection is successful, then the connection is accidentally disconnected. See also [my interim solution](https://github.com/CoreDX9/GraphqlSubscriptionTest/blob/0ae3c6a651bf80b43d05b97a16cead6bce3f5f44/TestClient/Program.cs#L89-L173).

**Comment by kolpav** [comment]
@CoreDX9 I am now thinking about creating repro repo with CI, thank you for explanation 👍
