### ISSUE TITLE
Iso8601Duration produces incorrect results for negative values

### ISSUE THREAD

**Issue by celerum-deryck** [ChilliCream/hotchocolate#5075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Passing a negative duration `TimeSpan` from a StrawberryShake client to HotChocolate results in an incorrect deserialized value.

For example, passing the ISO8601 string "-P1D" results in a deserialized value of -1.00:00:02.1474836 and not -1:00:00:00.

Both StrawberryShake and HotChocolate share the almost identical `Iso8601Duration` code for serialization:

- src/StrawberryShake/Client/src/Core/Serialization/Iso8601Duration.cs
- src/HotChocolate/Core/src/Types/Types/Scalars/Iso8601Duration.cs

Unconfirmed fix is to add the following line:

``` 
nanoseconds &= ~NegativeBit;
```

after the line:

```
var isNegative = (nanoseconds & NegativeBit) != 0;
```
in the `TryToTimeSpan` method in both classes.

### Steps to reproduce

1. Simply call `Iso8601Duration.TryParse("-P1D", out var ts)` and compare `ts` with `TimeSpan.FromDays(-1)`.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
@celerum-deryck  thanks for reporting :) 
Do you want to make a pull request?
