### ISSUE TITLE
Array property on InterfaceType/abstract class not Filterable

### ISSUE THREAD

**Issue by zyofeng** [ChilliCream/hotchocolate#5081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following data structure using EF Core:

[InterfaceType]
public abstract class Animal
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public ICollection<Food> Food { get; internal set; } = new HashSet<Food>();
}

public class Cat : Animal
{
}

And Im trying to filter what Food based on animals
{
  animals {
      nodes {
        name,
        food(where: { name: { eq: "Carrot" } }) {
          name
        }
      }
  }
}

but got the following error:

      "message": "The argument `where` does not exist.",

### Steps to reproduce

I have created a repo replicating the issue
https://github.com/zyofeng/InheritanceFiltering

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
This is currently not supported. But there is a feature request here: #4849

**Comment by zyofeng** [comment]
Not sure if this is the same thing, I am not trying to filter on the typename field (aka Discriminator)
But "Food" is a common property (an object array) for all the animal types and I am trying to filter out or sort the food when querying "Animals"

**Comment by zyofeng** [comment]
`{
  animals {
      nodes {
        name,
        ...on Cat {
          food (where: { food: { name: { eq: "Chicken" } } }) {
            food {
              name
            }
          }
        }
        ...on Dog {
          food (where: { food: { name: { eq: "Chicken" } } }) {
            food {
              name
            }
          }
        }
      }
  }
}`

The only workaround I can see, is to specify filtering on each and every derived types as above, rather than on the abstract class itself
