### ISSUE TITLE
Enum as number (int)

### ISSUE THREAD

**Issue by M2xAy** [ChilliCream/hotchocolate#5085]
### Is your feature request related to a problem?

Hi Community

Its possible implement enum serilization in int? 

I want that Hotchoclate return the int and not string
Example: "adresstyp": "PROBENHERKUNFT_BETRIEBSADRESSE" ->> "adresstyp": 5

Best regards from Zürich
Murat

### The solution you'd like

"adresstyp": "PROBENHERKUNFT_BETRIEBSADRESSE" ->> "adresstyp": 5

### Product

Hot Chocolate

**Comment by Nivisan-Jeyananthan** [comment]
http://spec.graphql.org/draft/#sel-FAHfLABAB6EqpU

"Enums are not references for a numeric value, but are unique values in their own right. They may serialize as a string: the name of the represented value."

**Comment by PascalSenn** [comment]
@M2xAy  Can you give it a go with this: https://chillicream.com/docs/hotchocolate/defining-a-schema/scalars/#custom-converters

**Comment by tobias-tengler** [comment]
I laid out some options for the same problem here: https://stackoverflow.com/questions/73648349/how-to-display-enum-number-instead-of-enum-name-in-response/73650378#73650378

Don't think there's anything else we could do that would also be spec-compliant.
