### ISSUE TITLE
Filtering does not work at all when used in combination with UsePaging for a field resolver that returns a Connection<T>?

### ISSUE THREAD

**Issue by SpiritBob** [ChilliCream/hotchocolate#5091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using code-first approach, if we have the following example classes:

```
public class QueryType : ObjectType<ExampleQuery>
{
    protected override void Configure(IObjectTypeDescriptor<ExampleQuery> descriptor)
    {
        descriptor.BindFields(BindingBehavior.Implicit);

        descriptor.Field(static f => f.GetExamplesAsync(default, default))
            .UsePaging<ExampleType>(options: new PagingOptions { IncludeTotalCount = true, MaxPageSize = 50 })
            .UseFiltering<ExampleFilterInput>();
    }
}

public class ExampleQuery
{
	
	public async Task<Connection<ExampleViewModel>> GetExamplesAsync(string? after = null, int? first = 20)
	{
		// Code omitted for brevitiy.
	}

}

public class ExampleType : ObjectType<ExampleViewModel>
{
	protected override void Configure(IObjectTypeDescriptor<ExampleViewModel> descriptor)
	{
		descriptor.BindFields(BindingBehavior.Implicit);
	}
}

public class ExampleFilterInput : FilterInputType<ExampleViewModel>
{
	protected override void Configure(IFilterInputTypeDescriptor<ExampleViewModel> descriptor)
	{
		descriptor.BindFields(BindingBehavior.Implicit);
	}
}

public class ExampleViewModel
{
	public int Id { get; init ;}
	
	public string Name { get; init; }
}
```

And having the following configuration in `Startup.cs`:

```
services.AddGraphQLServer()
		.AddQueryType<QueryType>()
		.AddType<ExampleFilterInput>()
		.AddFiltering();
```

Filtering ends up not working at all.

### Steps to reproduce

1. Create above classes.
2. Try to use filtering.
3. It won't work.

### Additional Context?

It makes sense in a way that it won't work as `Connection<T>` is the final result I believe that you return to the clients, i.e if it's already paged, it's already filtered.

If so, how exactly can one combine the two when working with stored procedures? I'm guessing we first need to pass the "where" argument manually (how?) and then use that to pass it to our stored procedure filtering logic? Does the framework support any possibility for transforming the "where" type into another runtime type, or is that left for us to do?

### Product

Hot Chocolate

### Version

12.0.0

**Comment by PascalSenn** [comment]
```csharp
public class ExampleQuery
{
	public async Task<Connection<ExampleViewModel>> GetExamplesAsync(
              [Service] ISomeService service,
	      string? after = null,
	      int? first = 20, 
	      IResolverContext context)
	{
		var filteredResults = service.GetFoos().Filter(context);
		 // create conntection and retrun
	}
}
```

**Comment by SpiritBob** [comment]
> ```cs
> public class ExampleQuery
> {
> 	public async Task<Connection<ExampleViewModel>> GetExamplesAsync(
>               [Service] ISomeService service,
> 	      string? after = null,
> 	      int? first = 20, 
> 	      IResolverContext context)
> 	{
> 		var filteredResults = service.GetFoos().Filter(context);
> 		 // create conntection and retrun
> 	}
> }
> ```

Is there an alternative way to do the filtering? Dapper returns the data buffered by default, meaning if I'm to separate the filtering logic from the stored procedure, things will get much slower as C# is not ideal for these kind of operations.

Is it possible to traverse the input the user has passed for the filters in `where`  and start transforming them into an object that my stored procedure knows how to work with to achieve the filtering in question?

**Comment by PascalSenn** [comment]
@SpiritBob  we introduced the IFilterContext in v13 for this usecase: 
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Data/src/Data/Filters/Context/IFilterContext.cs

it's not avaialbe in 12 though.
