### ISSUE TITLE
Automatic ID serialization/deserialization does not work after v11?

### ISSUE THREAD

**Issue by SpiritBob** [ChilliCream/hotchocolate#5093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i've defined my field to be a unique ID the following way `descriptor.Field(f => f.SomeField).ID()` but for some reason the result is a string of my actual data type, instead of a base64 opaque unique id?

I'm using the same code and just confirmed that when I downgraded from 13 to 12, and from 12 to 11, only in version 11 my code successfully works and I can see that the field is finally serialized.

What's going on? 

In my startup.cs, my GraphQL configuration consists of just my query type, as I'm using code-first approach. The same code was tested between verisons to make sure that it works in 11 but doesn't in higher versions.

### Steps to reproduce

Declare a field as being ID and when the object type is fetched, the field won't be a base64 string, but just an ordinary string of your underlying field value.

### Product

Hot Chocolate

### Version

13.0.0

**Comment by SpiritBob** [comment]
> Do you do `.AddGlobalObjectIdentifier()` on the schema builder?

Thank you! I didn't know I was required to call that API along with configuring my types to implement Node + a method that resolves the node, as previous versions did not require that and worked outside of the box with just a simple `AddQueryType` in the schema builder.

If I may ask something off-topic - when you use the code-first approach, would you recommend as a best practice to never inject field arguments into in their own object type's (Resolver class) methods as parameters, but rather inject `IResolverContext` and use that to fetch the field arguments? Or both styles offer the same performance? The only case I found so far where this is a very bad idea is for Node resolver methods - the `id` argument you can only fetch if it's injected as a method parameter, not via `IResolverContext`.

**Comment by PascalSenn** [comment]
I generally think the contract of a method parameter is a lot stronger than the IResolverContext. Even when doing code first it's most of the time not required to specify the arguments. It leaves a lot of room for errors if you overspecify the types.
Best example is nullability. if you specify all the arguments, you will eventually change the nullability of a parameter but you will forget to change the nullability of the argument on the type. 

My personal preference is to just use the annotation based approach. Even when you have a clean data layer and no graphql dependency, you can everything just with `[ExtendObjectType]` in the GraphQL layer. (expect changing the type of a field i think). But this really is up to preference.
