### ISSUE TITLE
Error with automatic type registration and generics

### ISSUE THREAD

**Issue by ti-wr** [ChilliCream/hotchocolate#5111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The automatic type registration will copy the type parameters verbatim and create an error.

For example, using the response type in the docs produces this line in the generated automatic type registration file: `builder.AddType<GenericAutoRegistration.ResponseType<T>>();`

Which results in the error `CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?)`

### Steps to reproduce

1. Create new project with packages necessary for Hot Chocolate with auto registration.
2. Add necessary initialization.
3. Try to add the generic response type from the documentation.

[Example Repository](https://github.com/ti-wr/generic-auto-registration)

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
this is now fixed and integrated into 12.11.0-preview.2

https://github.com/ChilliCream/hotchocolate/releases/tag/12.11.0-preview.2
