### ISSUE TITLE
Exceeding complexity returns 500 http status code

### ISSUE THREAD

**Issue by KristianJakubik** [ChilliCream/hotchocolate#5116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Actual behavior**
When the request exceeds the complexity quota it returns 500 status code, which symbolized it is BE issue. However, the issue on the client-side is sending a too complex query. 

Example of the response:
![image](https://user-images.githubusercontent.com/28342527/171728888-5188bedb-16ff-452e-bd37-738a4ddeb130.png)

**Actual behavior**
I would be expecting that the returned response code is 400, basically the same behavior in case of an invalid query.

This particular example is mentioned in [gql over http spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#document-validation), and even there it says that BE **should** return Bad Request.

![image](https://user-images.githubusercontent.com/28342527/171729715-4d1be6cd-6817-406d-83b1-0a28cf83d575.png)

### Steps to reproduce

1. Enable the Complexity option
2. Create a request that exceeds the complexity
3. The response contains the correct error, but HTTP status code is 500

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
You are expecting correctly ... we will put this in 12.11

**Comment by michaelstaib** [comment]
This is fixed and included in 12.11.0-preview.1

**Comment by oravecjakub** [comment]
Hi @michaelstaib, thanx for fixing this. However, I've just noticed that too complex queries still return a status of 500 when [Apollo tracing](https://chillicream.com/docs/hotchocolate/v10/execution-engine/apollo-tracing) feature (in on demand mode) is activated using X-Apollo-Tracing=1 request header. The same query without the header ends with 400 Bad Request. I feel that this shouldn't make a difference.
version [12.11.0-preview.1](https://github.com/ChilliCream/hotchocolate/releases/tag/12.11.0-preview.1) used

**Comment by michaelstaib** [comment]
It should not make a difference
