### ISSUE TITLE
Is there a callback for when a subscription has been cancelled?

### ISSUE THREAD

**Issue by wolfman42** [ChilliCream/hotchocolate#5128]
### Is your feature request related to a problem?

My implementation needs to know when a subscription is no longer needed so resources that are associated with it can be cleaned up. Couldn't find anything relevant in the examples.

I implemented this style of subscription
```csharp
public class Subscription
{
    public ValueTask<ISourceStream<Book>> SubscribeToBooks(
        [Service] ITopicEventReceiver receiver)
        => receiver.SubscribeAsync<string, Book>("ExampleTopic");

    [Subscribe(With = nameof(SubscribeToBooks))]
    public Book BookAdded([EventMessage] Book book)
        => book;
}
```
I have a publisher continuously sending updates. When the subscription is cancelled on the client the calls to `BookAdded` simply stop.

Similarly, I'd also need to know if the subscription was terminated due to any error with the websocket, not just when explicitly cancelled.

### The solution you'd like

An additional callback method on the Subscription class that I implemented would be great.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Add a cancellation token to your `SubscribeToBooks` method. When cancellation is called its time to clean your resources.


Hot Chocolate 13 also introduces a new interceptor that lets you do this in a centralised place:
https://github.com/ChilliCream/hotchocolate/blob/76da4a11b3fd4bb45c3a7347ec984473a727f36a/src/HotChocolate/AspNetCore/src/AspNetCore/ISocketSessionInterceptor.cs#L9

Although, while 13 can do more :) 12 also allows for a centralised close.
https://github.com/ChilliCream/hotchocolate/blob/main-version-12/src/HotChocolate/AspNetCore/src/AspNetCore/ISocketSessionInterceptor.cs

If you want to use the interceptor you can override the base class `DefaultSocketSessionInterceptor`.

If you want to handle it in your subscribe method use the cancellation token.

**Comment by michaelstaib** [comment]
The cancellation token provides a callback mechanism ... `cancellationToken.Register...`
