### ISSUE TITLE
Schema Discovery Issue with null / non-nullable types

### ISSUE THREAD

**Issue by ThatDeveloper** [ChilliCream/hotchocolate#5130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Somehow only nullable entities are included when querying for all the fields. This is also the case for lists / arrays. When working with Entity Framework or in general with non-nullable types, this will get very problematic.

Also, I would expect that the schema discovery would show me everything, maybe with a "nullable" or a "?" in the type.
Instead, for a `long?` it responds with `"Long"`.

### Steps to reproduce

**GraphQL Query to reproduce:**
```
__type(name:"Customer") {
    fields {
       name
         
       type {
         name
         fields {
           name
         }
       }
    }  
}
```

**Entity "Customer" (NON NULLABLE ENTITIES - NOT WORKING):**
```
public class Customer {
   public long CustomerTypeId { get; set; }
   public virtual CustomerType CustomerType { get; set; } = null!; //does not work with or without the '= null!;'
}
```

**Entity "Customer" (NULLABLE ENTITIES - WORKING):**
```
public class Customer {
   public long? CustomerTypeId { get; set; }
   public virtual CustomerType? CustomerType { get; set; }
}
```

-------------------------------------------------------------------------------------------------------

1. [NOT WORKING] If you execute the GraphQL query with the non-nullable entities you receive the following response:
```
{
  "name": "customerTypeId",
  "type": {
	"name": null,
	"fields": null
  }
},
{
  "name": "customerType",
  "type": {
	"name": null,
	"fields": null
  }
} 
```

2. [WORKING] If you execute the GraphQL query with the nullable entities you receive the following response:
```
{
  "name": "customerTypeId",
  "type": {
	"name": "Long",
	"fields": null
  }
},
{
  "name": "customerType",
  "type": {
	"name": "CustomerType",
	"fields": [
	  {
		"name": "description"
	  },
	  {
		"name": "id"
	  },
	  {
		"name": "createTime"
	  },
	  {
		"name": "rowVersion"
	  }
	]
  }
}
```

### Additional Context?

Opening this issue as discussed on Slack

### Product

Hot Chocolate

### Version

I tested it with latest stable and latest preview (13.0.0-preview.24)

**Comment by PascalSenn** [comment]
@ThatDeveloper 

The problem is that if you query non nullable fields there is a Type construct between the type. 'NonNull'. 
It equal to how you define a NonNullable type in HC. You take the type and wrap it with NonNullableType<T>

Try this query:
```graphql
query introspection_phase_2 {
  __type(name: "Customer") {
    fields {
      name
      type {
        ...TypeRef
      }
    }
  }
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
          }
        }
      }
    }
  }
}

```

**Comment by PascalSenn** [comment]
Did you try the query ?
i get this result from it:
```json
{
  "data": {
    "__type": {
      "fields": [
        {
          "name": "customerTypeId",
          "type": {
            "kind": "NON_NULL",
            "name": null,
            "ofType": {
              "kind": "SCALAR",
              "name": "Long",
              "ofType": null
            }
          }
        },
        {
          "name": "customerType",
          "type": {
            "kind": "NON_NULL",
            "name": null,
            "ofType": {
              "kind": "OBJECT",
              "name": "CustomerType",
              "ofType": null
            }
          }
        }
      ]
    }
  }
}
```

from your query i get:
```json
{
  "data": {
    "__type": {
      "fields": [
        {
          "name": "customerTypeId",
          "type": {
            "name": null,
            "fields": null
          }
        },
        {
          "name": "customerType",
          "type": {
            "name": null,
            "fields": null
          }
        }
      ]
    }
  }
}
```
which is also correct

**Comment by ThatDeveloper** [comment]
@PascalSenn Yes, I did try it. But it is still wrong. 

The result expected is:
```
{
  "name": "customerTypeId",
  "type": {
	"name": "Long",
	"fields": null
  }
},
{
  "name": "customerType",
  "type": {
	"name": "CustomerType",
	"fields": [
	  {
		"name": "description"
	  },
	  {
		"name": "id"
	  },
	  {
		"name": "createTime"
	  },
	  {
		"name": "rowVersion"
	  }
	]
  }
}
```

**Comment by PascalSenn** [comment]
but this is not the correct introspection result. 
The introspection follows the specification and NON-NULL is defined as a part of the type structure. 

You see the only difference between your result and mine is that there is a structure element more:
```json
"type": {
            "kind": "NON_NULL",
            "name": null,
```

**Comment by ThatDeveloper** [comment]
@PascalSenn The underlying issue is different. In my result of the NULLABLE attempt you see that the "customerType" has a "fields" array, showing me the fields of that enttiy. ["description", "id", "createTime", "rowVersion"]
With the NON-NULLABLE I do not get any fields back.
