### ISSUE TITLE
Graphql Localization Type Name Error

### ISSUE THREAD

**Issue by Domdu** [ChilliCream/hotchocolate#5134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

Im building an app that uses multiple language support. One of our language is Turkish and after application deployment if first request Accepted-Language header include tr-TR value i get below error: 

1. `İnvitations` is not a valid GraphQL type name. (Parameter 'value') (HotChocolate.Types.ObjectTypeExtension<EGraphQL.GraphQL.UserInvitor.UserInvitorQuery>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   ...

When hot chocolate try to discover types, my Invitations type represent as İnvitations. I can fix this issue with using GraphQLName data annotation but I have too many types and I dont want do it for all.

What is your suggestions?

### Steps to reproduce

1. Use request localization in application and add one of your supported CultureInfo with tr-TR
2. Write a query which includes 'I' character. Ex: Invitations
3. Use Accepted-Language header and give tr-TR value
4. Call this query 

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
You can write a custom naming convention for this:
https://chillicream.com/docs/hotchocolate/api-reference/migrate-from-11-to-12#custom-naming-conventions

**Comment by Domdu** [comment]
Thanks for your response.

I tried to return NameString struct with passing en-US culture info. But nothings changed. Im still facing with same issue.

**Comment by PascalSenn** [comment]
Do you actually replace these characters? as by spec only the following are allowed 
https://spec.graphql.org/June2018/#sec-Names

**Comment by Domdu** [comment]
Hi Michael,

I recognized I did not explained well this case before. I debug my scenario, and I found the issue. Sorry for wrong information. This case occured when use Cursor Pagination. So i fix this issue and create pull request.

Thanks.
