### ISSUE TITLE
Filtering does not respect local time zone

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#5137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Our timezone offset is +2.

We have this filter input (occured is DateTime in .NET dto), which contains +0 value:
```
{
  "and": [
    {
      "occurred": {
        "neq": "2022-06-08T18:05:00.000Z"
      }
    }
  ]
}
```
When this gets translated to the IQueryable, the resulting DateTime is not DateTime.Kind == Local (as woult be created by for example doing DateTime.Prase) but it's DateTime.Kind == Utc.

Quick watch of the executing DbCommand:
![image](https://user-images.githubusercontent.com/71645109/172689707-3296a642-03a8-4420-9f63-b88985982bd9.png)

This is somewhat of an issue as data in database are stored relative to the local timezone and not in UTC.

I was trying to figure out which part of HC consturcts the DateTime from string, I was not able to find it (I figured out it does not use DateTimeType's method deserialize as I was unable to break there). One solution that comes to mind is intercepting EFC's DbCommand and replacing all UTC DateTimes with local DateTimes, however this will work only if the parsed value is utilized immediately by EFC and not by something else.

### Steps to reproduce

DTO:
```
public class UserActivity
{
    public int Id { get; set; }
    public int HttpActivityId { get; set; }
    public int UserId { get; set; }
    public UserActivityType Type { get; set; }
    public DateTime Occurred { get; set; }
    public UserActivityStatus Status { get; set; }
    public string? Error { get; set; }

    public User? User { get; set; }
    public HttpActivity? HttpActivity { get; set; }
}
```

Resolver:
```
[UseFiltering]
public IQueryable<UserActivity> GetUserActivities(DbContext dbContext)
{
    return dbContext.Set<UserActivity>()
}
```

### Relevant log output

```shell
Produced SQL query:

[Parameters=[@__p_2='6', @__login_0='cts-group\lprochazka3' (Size = 64) (DbType = AnsiString), @__p_1='2022-06-08T18:05:00.0000000Z'], CommandType='Text', CommandTimeout='30']
SELECT TOP(@__p_2) [u].[Id], [u].[Occurred], [u].[Type], [u].[Status], [u].[Error]
FROM [cus].[UserActivities] AS [u]
INNER JOIN [cus].[Users] AS [u0] ON [u].[UserId] = [u0].[Id]
WHERE ([u0].[Login] = @__login_0) AND ([u].[Occurred] = @__p_1)
ORDER BY [u].[Occurred] DESC
```
```


### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

12.9.0

**Comment by cts-tradeit** [comment]
To clarify, the question is how to alter deserialization when using filtering (as deserialization for scalar can be altered using it's ScalarType class).

**Comment by michaelstaib** [comment]
"2022-06-08T18:05:00.000Z" is kind of correct as a UTC since Z represents UTC. Have you tried to specify an actual offset?

**Comment by cts-tradeit** [comment]
Yes but outside useFiltering, we are able to alter how the datetime is deserialized so we can deserialize the valu as local timezone no matter whether utc/zulu or offset that does not match our zone.

**Comment by cts-tradeit** [comment]
One solution would be to port all DateTimes to DateeTimeOffsets (including col typ in sql server) as comparison done by sql server always compares values in UTC. However this is an existing database/applicatio which makes this rather difficult.

**Comment by michaelstaib** [comment]
Internally we use `DateTimeOffset` and you can override how we convert these to `DateTime`. For this, you need to specify a type converter.

I wanted to link to the docs, but somehow they are not documented :( 

So here is some code:

```csharp
builder.Services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddTypeConverter<DateTimeOffset, DateTime>(static t => t.UtcDateTime);
```

**Comment by michaelstaib** [comment]
Please provide feedback if this solved your issue so I can close the issue.

**Comment by michaelstaib** [comment]
If you are not using dotnet 6 do:

```csharp
.AddTypeConverter<DateTimeOffset, DateTime>(t => t.UtcDateTime);
```

**Comment by cts-tradeit** [comment]
Works like a charm.
