### ISSUE TITLE
Action separation (Muatation,Query), all in one typeextension registration

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [ChilliCream/hotchocolate#5150]
### Is your feature request related to a problem?

Hi, first of all thanks for the best GQL framework out in the wild. 

Recently I started using Fast endpoints, and I really like the code separation per endpoint. In Hot Chocolate I can achieve similar separation by action using the ExtendObjectType attribute, extending the main query/mutation.

What I am currently doing is that I create an empty Query,Mutation class which I register as my roots then I am using 
reflection to find all the type extensions. I create a new extension type per query/mutation

```
var gql = builder.Services.AddGraphQLServer();
gql.AddQueryType<Query>(); // here query is just an empty class

var typeExtensions = typeof(Program).Assembly.GetTypes()
    .Where(x => !x.IsAbstract && x.IsClass && x.GetCustomAttribute<ExtendObjectTypeAttribute>() is not null);
    
foreach (Type e in typeExtensions)
{
    if (e is not null)
    {
        gql.AddTypeExtension(e);
    }
}
```

It would be good to not have to create empty Query/Mutation objects in every new project.

Thanks

### The solution you'd like

Could Hot Chocolate register a default query if we don't specify one? Maybe extension Methods would be good 

- .AddDefaultQueryType()
- .AddDefaultMutationType()

The default Query/Mutation class then could be used with the ExtendObjectType attribute, so an empty Query/Mutation class would not be needed.

If we can get all the types using ExtendObjectType attribute, would it be possible to create an extension method for just registering all the types at once.

- .AddTypeExtensions(); // maybe the assembly could be an argument? 

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
@TheOnlyBeardedBeast 
I think this is already possible with
```
.AddQueryType()
.AddMutationType()
```

Also to avoid assembly scanning, you can use the source generator that will register all the extension type for you. 
@michaelstaib  do we have documentation for this anywhere?

**Comment by michaelstaib** [comment]
If you have questions join us on slack.chillicream.com

**Comment by TheOnlyBeardedBeast** [comment]
@michaelstaib thank you
