### ISSUE TITLE
Enabling Directive introspection breaks GraphQL Voyager

### ISSUE THREAD

**Issue by SpiritBob** [ChilliCream/hotchocolate#5154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you enable the directive introspection, GraphQL Voyager will break with the following exception:

```
voyager.min.js:82 Uncaught (in promise) Error: Name "__AppliedDirective" must not begin with "__", which is reserved by GraphQL introspection.

Name "__DirectiveArgument" must not begin with "__", which is reserved by GraphQL introspection.
    at voyager.min.js:82:186809
    at voyager.min.js:82:186870
    at Vn (voyager.min.js:82:187038)
    at n.schema (voyager.min.js:82:194555)
    at sr (voyager.min.js:82:194678)
    at gr (voyager.min.js:82:196715)
    at t.updateIntrospection (voyager.min.js:82:248696)
    at voyager.min.js:82:248557
```

### Steps to reproduce

1. Enable directive introspection in your schema builder:

```
services.AddGraphQLServer()
                    .ModifyOptions(o =>
                    {
                        o.EnableDirectiveIntrospection = true;
                    })
```
2. Open up your graphql voyager and see your JS console for the reported error.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
@SpiritBob  this is a issue of GraphQL Voyager as they do apparently do not support these types. The __DirectiveArgument is a offical introspection type, but it's a DRAFT feature on the spec.

I woudl suggest to raise this issue on the graphql voyager repository, as HC is spec compliant in this case

**Comment by SpiritBob** [comment]
@PascalSenn thanks!

**Comment by SpiritBob** [comment]
> @SpiritBob this is a issue of GraphQL Voyager as they do apparently not support these types. The __DirectiveArgument is a offical introspection type, but it's a DRAFT feature on the spec.
> 
> I woudl suggest to raise this issue on the graphql voyager repository, as HC is spec compliant in this case

Could you please toss a link to where they specify that it's an official introspection type? Latest working draft doesn't specify it, unless my CTR +F is playing tricks on me. https://spec.graphql.org/draft/
