### ISSUE TITLE
UseSingleOrDefault ignores GraphQLNonNullType, what about UseSingle?

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#5161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
[Authorize]
[UseSingleOrDefault]
[UseProjection]
[GraphQLNonNullType]
public IQueryable<User> CurrentUser([Service] IOperationContext context, JointDbContext dbContext)
    => dbContext.Set<User>().Where(u => u.Id == context.CurrentUser!.Id);
```

Will produce field currentUser with type User instead of User!, which is contextual nonsense as user can't be null due to authorize attribute.

### Steps to reproduce

1. Have resolver with attributes above.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by cts-tradeit** [comment]
Thank you, this works well.

I have extra question about this, how does HC load content of navigational properties? I suppose you are not using EFCore's Include() for IQueryable (as it is in EFCore's nuget which HC.Data does not reference).

**Comment by PascalSenn** [comment]
@cts-tradeit  We project into the selection sets `.Select(x => new Foo { Id = x.Id, Nested = new Nested { First = x.Nested.First}})`
