### ISSUE TITLE
RemoveUnreachableTypes option broke schema validation on BCP side..

### ISSUE THREAD

**Issue by damikun** [ChilliCream/hotchocolate#5163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Schema issue in case the server option `options.RemoveUnreachableTypes = true;` is enabled. 

- BCP is unable to fetch schema without showing error only logs exception to console.

```json
Uncaught (in promise) Error: Invalid or incomplete schema, unknown type: Int. Ensure that a full introspection query is used in order to build a client schema.
    at f (document-scheduler.0f28a64b.worker.js:2:730451)
    at p (document-scheduler.0f28a64b.worker.js:2:730322)
    at p (document-scheduler.0f28a64b.worker.js:2:730177)
    at D (document-scheduler.0f28a64b.worker.js:2:731698)
    at Mn (document-scheduler.0f28a64b.worker.js:2:687946)
    at g (document-scheduler.0f28a64b.worker.js:2:731641)
    at document-scheduler.0f28a64b.worker.js:2:729730
    at Array.map (<anonymous>)
    at ci (document-scheduler.0f28a64b.worker.js:2:729369)
    at document-scheduler.0f28a64b.worker.js:2:732465
```

![B](https://user-images.githubusercontent.com/54806834/174115917-f150f9fc-2849-4a0e-a4ea-fac197bc017e.png)

### Steps to reproduce

1) Preparation
   
 Make sure:
- you alwais clear website data in dev tool between changes BCP presist some state..
- make sure you disable caching in network view of dev tools
- do not use hot-reload restart server between changes it is chane in startup config.
  
By repo `setup` the error shoud appear since `options.RemoveUnreachableTypes = true;` 

1) disable option to `false`
2) restart server (do not use just hot reload)
3) clear bcp website data
4) Navigate to bcp default url
5) Schema will be loaded

### Additional Context?

The reproduction repo. : https://github.com/damikun/UnreachableTypes_Issue

### Product

Banana Cake Pop

### Version

12.11.1

### Connected issue

There is equal issue that was reported while ago but the fix was merged.. Im not sure what changes that there is again this problem..

https://github.com/ChilliCream/hotchocolate/issues/4712

**Comment by rstaib** [comment]
Thank you for reporting. We will take a look into that.

**Comment by michaelstaib** [comment]
This seems fixed in the latest 13 previews.
