### ISSUE TITLE
QueryDelegate missing 

### ISSUE THREAD

**Issue by romarro** [ChilliCream/hotchocolate#5183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the 2019-04-11-integration-tests.md at lines 277-293 there is an example of how to create a middleware that is using the QueryDelegate. Unfortunately, I could not find its definition anywhere in the source

### Steps to reproduce

1. Open VS code
2. Search for QueryDelegate
3. The only place where I can find it is in the 2019-04-11-integration-tests.md file

### Additional Context?

Maybe it is best to write also the packages that must be used for each example.

### Product

Hot Chocolate

### Version

latest master

**Comment by PascalSenn** [comment]
I think this is more  or less equivalent to use `SetProperty` on the request builder

**Comment by michaelstaib** [comment]
Thats is a good idea. With the new YouTube videos we are doing this. Closing this issue.
