### ISSUE TITLE
Experimental Feature: Flat chain syntax

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#519]
https://github.com/facebook/graphql/issues/174

We will implement this one with an experimental flag in order to check the limits and if such a feature is feasible.

**Comment by Relaxe111** [comment]
Some updates on this issue?

**Comment by michaelstaib** [comment]
Not yet ...

**Comment by cezarypiatekGC** [comment]
Hi @michaelstaib 
What's the current status of this feature?  This issue is marked as completed but I'm unable to use that new syntax. Do I need to enable it explicitly somehow?
