### ISSUE TITLE
Question: How to mass-bind field middleware?

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#5190]
### Is your feature request related to a problem?

Let's say we have a mutation resolvers:
```
class Mutations {
   public Task<Car> CreateCarAsync(CarInput input) {...} 
    
   public Task DestroyCarAsync(CarDestructionInput input) {...}
}
```
If I want to create a field middleware that will inspect an input and for example invoke IValidatableObject validation I can do make Attribute which will I can place on each method.
````
class Mutations {
   [InvokeValidation]
   public Task<Car> CreateCarAsync(CarInput input) {...} 
   [InvokeValidation]
   public Task DestroyCarAsync(CarDestructionInput input) {...}
}
````
However, this requires me to explicitly specify attribute anytime I add new method.

### The solution you'd like

One solution could be being able to place the attribute on the class:
```
[InvokeValidation]
class Mutations {

   public Task<Car> CreateCarAsync(CarInput input) {...} 

   public Task DestroyCarAsync(CarDestructionInput input) {...}
}
```

This is somewhat similar to Authrorization when dealing with ObjectType classes where we can do this:
```
class Foo: ObjectType {
    public override OnConfigure(Descriptor d) { 
          d.Authorize();  // apply to all fields
          d.Field("foo").Authorize(); // aply to this field
    }
}
```
However even with using explicit ObjectType class there is no simple way how to hook middelware on all fields at once (as I understand Authorize does not use field middlewares). One solution that comes in mind is itarate through each field and place the middleware there manually (I think there is another overridable method that exposes all registered fields and allows me to manipulate the registrations), but this cannot be used with annotation based approach.

I think that ever better solution could be ability to "define" global field middleware (not request interceptor).
```
services.AddGraphQLServer().AddGlobalFieldMiddleware(next => ctx => {...});
```
Thus anytime there is a parameter implementing IValidatableObject I can automatically discover it and invoke validation.

### Product

Hot Chocolate

**Comment by PascalSenn** [comment]
Probably the easiest way is to do it this way:

```csharp

public sealed class InvokeMiddlewareOnAllFieldsAttribute : ObjectTypeDescriptorAttribute
{
    public override void OnConfigure(
        IDescriptorContext context,
        IObjectTypeDescriptor descriptor,
        Type type)
    {
        descriptor.Extend()
            .OnBeforeCreate(d =>
            {
                foreach (var field in d.Fields)
                {
                    field.MiddlewareDefinitions.Add(new FieldMiddlewareDefinition(x =>
                    {
                        /*yourmiddlware*/
                    }));
                }
            });
    }
}

[InvokeMiddlewareOnAllFields]
public class Mutation {...}

```

There is a way to register "global middlewares" but do not do this. This will add the middleware on all fields, meaning we cannot inline them and your execution performance will drop significantly.
