### ISSUE TITLE
Ignored field is not projected

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#5197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This situation:
```
class Foo {
   public int ContractId { get; set; }
   public Something Else { get; set; }
}
class FooObjectType: ObjectType<Foo> {
  protected override void Configure(IObjectTypeDescriptor<Holding> descriptor)
    {
        descriptor.Authorize(ReadFooPolicy.Name);
        ReadFooPolicy.SetProjection(descriptor); // policy sets what field should get IsProjected as it will decide based on them
        descriptor.Field(_ => _.ContractId).Ignore(); // but we do not want to have this accesible in the schema
    }
}
class ReadFooPolicy: AuthorizationHandler<ReadFooRequirement, IResolverContext> {
        protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, Requirement requirement, IResolverContext resource)
        { 
             Foo foo = resource.Parent<Foo>();   
             Console.Write(foo.ContractId); // => 0 
             if (await resource.Service<Service>().CheckIfCurrentUserCanAccessContractAsync(foo.ContractId))
                 context.Succeed(requirement); 
             else 
                 context.Fail();
        } 
         
       public static void SetProjection(IObjectTypeDescriptor<Holding> descriptor)
       {
           descriptor.Field(_ => _.ContractId).IsProjected();
       }
}
```
As soon as I remove ignoring of ContractId projection starts working and ContractId is filled.

### Steps to reproduce

1. Have an object type
2. Set IsProjected and Ignored on one field.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
The porblem with this is that when you ignore the field it is also no longer on the object type itself. This could become possible when we introduce 'internal' fields. But at the moment this is not at the top of the priority list.

**Comment by kawazoe** [comment]
Just wanted to show some interest for this feature. I like to keep my schema clean and I'm disappointed I have to expose `fooId` and `foo` together all of the time, specially since I already have `foo { id }` as well. I think this gets particularly jarring when combined with Global Object Identification, where `fooId` and `foo { id }` will actually have different values that are not interchangeable in queries.
