### ISSUE TITLE
HotChocolate sorting on nested collection property

### ISSUE THREAD

**Issue by NikitaSTets** [ChilliCream/hotchocolate#5210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello everyone 
I have the same issue. 

Do we have any ideas on how to[ enable sorting on nested collection properties](https://stackoverflow.com/questions/71801912/hotchocolate-sorting-on-nested-collection-property)?

Used solutions [ from here](https://github.com/ChilliCream/hotchocolate/issues/1527), but without any success.

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment]
Not sure if i understand. Can you provide an example query?

**Comment by michaelstaib** [comment]
Closing this issue since no example was provided.
