### ISSUE TITLE
The ability to intercept and REPLACE input values

### ISSUE THREAD

**Issue by stand-sure** [ChilliCream/hotchocolate#5226]
### Is your feature request related to a problem?

It is often desirable to sanitize input values centrally.

For example, in a RESTful app, one might add a binder to trim leading/trailing whitespace (code sample: https://gist.github.com/stand-sure/d49fa33ea92e4be5937a388121485011).

There appears to be no way to do this uniformly in HC.

### The solution you'd like

Either a way to apply a "type system" to all (or most) fields with a certain runtime type, or a way to apply middleware or a directive to change the value of the input type or one of its properties.

The following approach works, but requires manual config

Type sample:

```c#
using HotChocolate.Language;

using JetBrains.Annotations;

[PublicAPI]
public class TrimmedStringType : ScalarType<string, StringValueNode>
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="TrimmedStringType" /> class.
    /// </summary>
    public TrimmedStringType() : base(new NameString("TrimmedString"))
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TrimmedStringType" /> class.
    /// </summary>
    public TrimmedStringType(
        NameString name,
        string? description = null,
        BindingBehavior bind = BindingBehavior.Explicit)
        : base(name, bind)
    {
        this.Description = description;
    }

    public override IValueNode ParseResult(object? resultValue) => this.ParseValue(resultValue);

    protected override string ParseLiteral(StringValueNode valueSyntax) => valueSyntax.Value.Trim();

    protected override StringValueNode ParseValue(string runtimeValue) => new(runtimeValue.Trim());
}
````

Usage sample:
```c#
public record TSDemoInput(string Name);

public class TSDemoInputType : InputObjectType<TSDemoInput>
{
    protected override void Configure(IInputObjectTypeDescriptor<TSDemoInput> descriptor)
    {
        descriptor.Field(input => input.Name)
            .Type<TrimmedStringType>();
    }
}
```

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
`IInputValueFormatter` is what you are looking for.

**Comment by glen-84** [comment]
There's [no documentation](https://github.com/ChilliCream/hotchocolate/discussions/5073) for value formatters or type interceptors.

I assume that you need to create a type interceptor like [this](https://github.com/ChilliCream/hotchocolate/blob/9a369c15a6bf218000322a4b049c02bde68c04ea/src/HotChocolate/Spatial/src/Types/Transformation/GeometryTransformerInterceptor.cs), that adds the formatter to all arguments/fields.

**Comment by stand-sure** [comment]
potentially reopening this

we have since discovered that Schema Stitching doesn't play well with custom scalars

**Comment by stand-sure** [comment]
Thanks

**Comment by glen-84** [comment]
@michaelstaib

I mentioned TypeInterceptors because we'd probably want to apply this to all (or many) arguments/fields, as opposed to just one at a time (which could be tedious).

(I don't really follow the `Trim` example. Is that method supposed to be implemented by the developer? It doesn't exist on `IInputFieldDescriptor`.)

**Comment by sgabler-solytic** [comment]
Google led me here. Has anyone figured out a solution for this that they could share? Our DB is full of extra white space, e.g. " My cool project" or "Foo Bar\n"

I could potentially solve it on the DB layer, but I was wondering if there is a generic way to do this in HotChocolate. Thanks for any ideas.

**Comment by Sbethm** [comment]
Came here looking for the same thing. Our database has who knows how many leading-white-space values. It would be a pain to trim every field, and many developers would forget to do so. It'd be great if a custom formatter could be implemented in hot chocolate to process user inputs that need to be trimmed

**Comment by glen-84** [comment]
Just a thought, but implementing the trimming at this layer may not be the best option, especially if you have a service layer or use MediatR commands, for example.

Imagine that you have 3 ways to execute business logic:

1. GraphQL -> Service -> Entity.
2. REST -> Service -> Entity.
3. CLI -> Service -> Entity.

If you implement this in the GraphQL layer, then untrimmed/invalid data could still be input via REST or a CLI.

It might be better to implement this at the Service/Command layer, or even in the entities themselves, perhaps using the [field keyword](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/field):

```cs
public string? Name { get; set => field = value?.Trim(); }
```

**Comment by hemed** [comment]
I have implemented a custom `TrimWhitespaceAttribute` that can be applied to both **GraphQL arguments** and **input fields**.  This ensures that leading and trailing whitespace is automatically trimmed before GraphQL field execution. Please see below for the details.


### `TrimInputFormatter`

```csharp
/// <summary>
///     A formatter that trims leading and trailing whitespace from string input values
///     before GraphQL field execution.
/// </summary>
public sealed class TrimInputFormatter : IInputValueFormatter
{
    public object? Format(object? runtimeValue)
    {
        if (runtimeValue is string s) return s.Trim();

        return runtimeValue;
    }
}
```

---

### `TrimWhitespaceAttribute`

```csharp
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Parameter)]
public sealed class TrimWhitespaceAttribute : DescriptorAttribute
{
    private static readonly TrimInputFormatter TrimFormatter = new();
    
    protected override void TryConfigure(
        IDescriptorContext context,
        IDescriptor descriptor,
        ICustomAttributeProvider element)
    {
        switch (descriptor)
        {
            case IArgumentDescriptor argumentDescriptor:
                argumentDescriptor.Extend().Definition.Formatters.Add(TrimFormatter);
                break;

            case IInputFieldDescriptor inputFieldDescriptor:
                inputFieldDescriptor.Extend().Definition.Formatters.Add(TrimFormatter);
                break;
        }
    }
}
```

---

## Usage

### On Arguments

```csharp
public async Task<SimpleProduct?> GetProductAsync(
    [Service] IProductRepository productRepo,
    [TrimWhitespace] string productCode,
    CancellationToken cancellationToken)
{
    // productCode is trimmed before reaching here
    return await productRepo.GetProductAsync(productCode, cancellationToken);
}
```

---

### On Input Fields

```csharp
public class AvailabilityRequest
{
    [TrimWhitespace]
    public required string DepartureCode { get; set; }

    [TrimWhitespace]
    public required string TicketCode { get; set; }
}
```

```csharp
public async Task<AvailabilityResponse> GetAvailabilityAsync(
    [Service] IAvailabilityRepository availabilityRepo,
    AvailabilityRequest availabilityRequest,
    CancellationToken cancellationToken)
{
    // DepartureCode and TicketCode are trimmed before reaching here
    return await availabilityRepo.CheckAvailability(availabilityRequest, cancellationToken);
}
```

---

## Example Query

### Before (extra spaces in input)
```graphql
query {
  getProduct(productCode: "   ABC123   ") {
    id
    name
  }
}
```

### After (value in resolver)
```csharp
// productCode == "ABC123"
```

---
