### ISSUE TITLE
Unability to define decimal between double quotes

### ISSUE THREAD

**Issue by pocky6** [ChilliCream/hotchocolate#5259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use Strawberry with a service which declares a field as a Decimal stored as a string. I have no control over their implementation. 
When importing the schema I see they declare Decimal this way:
```
"# Decimal\n\nDecimal value may be input as number or string and will be returned as string to get full precision"
scalar Decimal
```
The Decimal properties are mapped to decimal in C#. 
When getting items containing decimal properties, the json is valid but it fails to be parsed because of this line in the generated C#:
`return _decimalParser.Parse(obj.Value.GetDecimal()!);`
Before I found that I was trying to implement a custom parser, but an exception is raised even before I get the value, as GetDecimal fail when the inner value is a string.

I would like, either to be able to get decimal from string values, or to be able to implement a custom converter which would get the JsonElement to extract its value in another way.

### Steps to reproduce

1. - Have a service which declare a decimal scalar, but sent as a string
2. - Try to get an item containing this property

### Additional Context?

When getting __schema through GraphQL explorer, the Decimal part is as follows:
```
        {
          "name": "Decimal",
          "description": "# Decimal\n\nDecimal value may be input as number or string and will be returned as string to get full precision",
          "specifiedByURL": null,
          "kind": "SCALAR",
          "possibleTypes": null,
          "ofType": null,
          "interfaces": null,
          "fields": null
        },
```

### Product

Strawberry Shake

### Version

12.12.1

**Comment by PascalSenn** [comment]
You can override the serializers with `AddSerializer` on the dependency injection.

As an example, here is the DecimalSerializer that is used by StrawberryShake out of the box: https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/Client/src/Core/Serialization/DecimalSerializer.cs

**Comment by pocky6** [comment]
I can (and I tried), but as I said the following line will still raise an exception:return _decimalParser.Parse(obj.Value.GetDecimal()!);


    Le jeudi 28 juillet 2022 à 13:04:16 UTC+2, PascalSenn ***@***.***> a écrit :  
 
 


You can override the serializers with AddSerializer on the dependency injection.

As an example, here is the DecimalSerializer that is used by StrawberryShake out of the box: https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/Client/src/Core/Serialization/DecimalSerializer.cs

**Comment by PascalSenn** [comment]
@pocky6  that is because StrawberryShake expects the value to be a number. You can change the value in the `schema.extensions.graphql` file like this:

```graphql
extend scalar Decimal
  @serializationType(name: "global::System.Decimal")
  @runtimeType(name: "global::System.String")
```

**Comment by pocky6** [comment]
Thank you very much, it solves my problem (after swapping the types).

I wasn't expecting a non-c# solution :)
    Le jeudi 28 juillet 2022 à 13:28:50 UTC+2, PascalSenn ***@***.***> a écrit :  
 
 


@pocky6 that is because StrawberryShake expects the value to be a number. You can change the value in the schema.extensions.graphql file like this:
extend scalar Decimal
  @serializationType(name: "global::System.Decimal")
  @runtimeType(name: "global::System.String")
