### ISSUE TITLE
Cannot get dataloader to work

### ISSUE THREAD

**Issue by johntyrrell** [ChilliCream/hotchocolate#5263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an endpoint to request Club's. This endpoint uses EFCore + projections and paging to load the data. 
This works perfectly.

There is a subentity of club that I want load using a dataloader because the contents is stored elsewhere.
But whatever dataloader I use GroupDataLoader or BatchDataLoader, the request always "hangs" and no error and no data is returned. 

### Steps to reproduce

This is the code I am using at the moment for the Club setup and a simpe dataloader test to see how to get it to work.

```
[ExtendObjectType(OperationTypeNames.Query)]
public class ClubQueries
{
    [UseOffsetPaging(IncludeTotalCount = true, DefaultPageSize = PagingConstants.DefaultPageSize, MaxPageSize = PagingConstants.MaxPageSize)]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Club> GetClubs([Service] MyDbContext dbContext) => dbContext.Clubs;
}

public class ClubType : ObjectType<Club>
{
    protected override void Configure(IObjectTypeDescriptor<Club> descriptor)
    {
        descriptor.Field(c => c.Players).UseFiltering();
    }
}

[ExtendObjectType(typeof(Club))]
public class UserExtensions
{
    [BindMember("Test")]
    public Task<string[]> GetTestAsync(
        [Parent] Club club,
        IResolverContext context,
        CancellationToken cancellationToken
    )
    {
        return context.GroupDataLoader<Guid, string>(
                        async (keys, ct) =>
                        {
                            await Task.CompletedTask;
                            return keys.Select(x => new { Id = x, Value = x.ToString() }).ToLookup(x => x.Id, x => x.Value);
                        }).LoadAsync(club.Id, cancellationToken);
    }
}
```

### Relevant log output

```shell
Nothing is logged :(
```

### Additional Context?

I'm currently using:
- .NET 6
- EFCore 6.0.7
- HotChocolate.AspNetCore 12.12.1
- HotChocolate.Data.EntityFramework 12.12.1

### Product

Hot Chocolate

### Version

12.12.1

**Comment by michaelstaib** [comment]
Please post your question to https://slack.chillicream.com or to the GitHub Discussions as we track here enhancements or feature requests.
