### ISSUE TITLE
Append the word `Types` to the module name automatically

### ISSUE THREAD

**Issue by aradalvand** [ChilliCream/hotchocolate#5268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure if this should be considered a bug or a feature requested.
I'm using `HotChocolate.Types.Analyzers` version 12.12.1, and I have the following:
```c#
[assembly: Module("Foo")]
```
The generated extension method's name is `AddFoo` as opposed to `AddFooTypes`. Wouldn't it make more sense to append the word `Types` to the name of the module automatically? Does it really make sense to call the module "FooTypes" — like [Michael does here](https://youtu.be/QPelWd9L9ck?t=390)?! That seems a little awkward. 

This is at the very least inconsistent with how it works by default: If the name of the project is `Bar`, it generates an `AddBarTypes` extension method.

### Product

Hot Chocolate

### Version

12.12.1

**Comment by michaelstaib** [comment]
My thinking here is to give people full control over the name when you specify it on your own. You could for instance just have a module for data loader or other things. Or you might not want type as a postfix. By not interfering with your override we give you this possibility.
