### ISSUE TITLE
Support for imperative authorization

### ISSUE THREAD

**Issue by onionhammer** [ChilliCream/hotchocolate#5273]
### Is your feature request related to a problem?

The problem is resource-based authorization, where you need to download a resource (from, say, a database) based on the query and context and then check the authorization.

The guidance from Microsoft here is to use imperative auth rather than a declarative attribute ([Authorize]). This is supported in ASPNET Core with the `IAuthorizationService`, and you *can* call it from HotChocolate, but there's nothing to do with that information but throw some custom exception?

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-6.0

I am building a multi-tenant application with HotChocolate, and authorizing users for specific resources right now isn't straightforward to me. I have worked around it by basically using the 'Context' in an authorization handler and checking the type with '.Parent', but it feels hacky.. also there doesnt appear to be a good way to go up the chain of 'ancestors', for example a '.GetParentOfType<T>' where it keeps going up the tree of ancestors until it finds the parent of type T.

### The solution you'd like

It would be awesome if this scenario was better supported, or if it is well supported (showing my lack of knowledge here), better documented here ( https://chillicream.com/docs/hotchocolate/security/authorization ). 

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
There are now multiple issues open on authorization, all aiming at similar things. We will close this one. We have work later in the release cycle of 13 queued where we will discuss. things. 

you can add your thoughts to this item: https://github.com/ChilliCream/hotchocolate/issues/3456

Closing this one to keep the topic closer together.
