### ISSUE TITLE
SubscribeAndResolve: Projection was not found.

### ISSUE THREAD

**Issue by cts-tradeit** [ChilliCream/hotchocolate#5281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This:
```
[LogAccessViaMiddleware]
[UseProjection]
[SubscribeAndResolve]
public async IAsyncEnumerable<Instruction> OnInstruction(long id, 
   IResolverContext context, 
   CommonDbContext dbContext,
   // Thinks of this as ITopicEventReceiver
   [Service] IEventTarget eventTarget, 
   [EnumeratorCancellation] CancellationToken token)
{
   await foreach (AfterSaveEventArgs<Instruction> @event in eventTarget.PullEventsAsync<AfterSaveEventArgs<Instruction>>(token))
   {
      if (id is long idFilter && @event.Entity.Id != idFilter)
            continue;

      IQueryable<Instruction> instruction = MakeQueryableToLoadAdditionalData(@event.Entity);
      instruction = instruction.Project(context); // throws
      yield return instruction.SingleAsync(token);
   }
}
```

Produces:
```
HotChocolate.SchemaException
  HResult=0x80131500
  Message=For more details look at the `Errors` property.

1. Projection was not found. Register projection with [UseProjection] or descriptor.UseProjection().

  Source=HotChocolate.Data
  StackTrace:
   at HotChocolate.Data.Projections.Expressions.QueryableProjectExtensions.ExecuteProject[T](T input, IResolverContext context, Type expectedType) in C:\Users\lprochazka3\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\10b52e3e50ba4ea59d4f6936e9d21ce23e000\d5\b4eea0dc\QueryableProjectExtensions.cs:line 73
```

### Steps to reproduce

1. Have a subscription object type
2. Add one method that hooks using IAsyncEnumerable to a source (signature above)
3. In each iteration of IAsyncEnumerable apply projection on IQueryable made from recieved data

### Product

Hot Chocolate

### Version

12.9.0

**Comment by cts-tradeit** [comment]
I expect that the answer would be "not supported", so my additional question is: Is there a way how to create "projection" manually (ie. access query, fill context with projection and apply it)?

**Comment by tobias-tengler** [comment]
I think you just need to seperate the "subscriber" from the "resolver" and just apply the projection on the resolver. The last code example in [the subscription docs](https://chillicream.com/docs/hotchocolate/defining-a-schema/subscriptions/#itopiceventreceiver) shows an example.

**Comment by michaelstaib** [comment]
That is not supported ... also SubscribeAndResolve is not meant for data transactions ... when you use a DBContext you need to split them into separate subscriber and resolver since the subscribe part will have a single DI scope.

**Comment by cts-tradeit** [comment]
@michaelstaib Ok, but then it bring back this issue #5277 as without ability to project query, we are unable to resolve values that are not directly on the payload of message.

What do you mean by "subscribe part will have a single DI scope"? I thought that dependencies are resolved from request's scope (unless additional scopes are created from this very scope). This DbContext is pooled. 

Lastly how do I pass additional parameters to the "subscriber" part (I suppose that in the example "subscriber" is `SubscribeToBooks` and "resolver" is the one wisth `SubscribeAttribute` so `SubscribeToBooks`)? I need to filter out some events based on id.

**Comment by michaelstaib** [comment]
@tobias-tengler I think I will remove SubcribeAndResolve for V13 it is to confusing to people :)

**Comment by michaelstaib** [comment]
@cts-tradeit the following is how you should do it:

```csharp
public class Subscription
{
    // this represents the subscription factory
    public ValueTask<ISourceStream<Book>> SubscribeToBooks(
        [Service] ITopicEventReceiver receiver)
        => receiver.SubscribeAsync<string, Book>("ExampleTopic");

    [UseProjection] // <--- projection will work here
    [Subscribe(With = nameof(SubscribeToBooks))]
    public Book BookAdded([EventMessage] Book book)
        => book;
}

```

**Comment by cts-tradeit** [comment]
This works but I came across this issue #5288

**Comment by michaelstaib** [comment]
The arguments must always be declared on the resolver even if they are only used on subscribe ... this is something we will change in 13 but in 12 we have no plans to change this.

**Comment by cts-tradeit** [comment]
I think this should be mentioned in docs. It can save a lot of time debugging.

**Comment by michaelstaib** [comment]
Do you want to do a PR?
