### ISSUE TITLE
Cannot resolve output-type `System.DateTime`

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#530]
**Describe the bug**
there looks to be a regression with 0.7.0 (alpha.34) after upgrading from 0.6.11. 

**To Reproduce**
we get the following error
```
HotChocolate.SchemaException: 'testGraphQuery.date: Cannot resolve output-type `System.DateTime` - Type: TestGraphQuery'
```

with registering this simple type (```c.RegisterQueryType<TestGraphQuery>()```)

```
public class TestGraphQuery
    {
        public string Version { get; set; } = "0.0.1-alpha.1";
        public DateTime Date { get; set; } = DateTime.Now;
    }
```

**Expected behavior**
with 0.6.11 we get a Date GraphType

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.7.0 (alpha 34)

**Comment by scottrabara** [comment]
Hi Daniel,

There were some changes done for [#433](https://github.com/ChilliCream/hotchocolate/issues/433) made to address custom extended scalars. Since then, the stock built-in extended scalars must now be explicitly registered during schema configuration if you do not intend to override them:

```csharp
var schema = Schema.Create(c =>
{
    // Register all 6 pre-built extended scalar types
    c.RegisterExtendedScalarTypes();
});
```

or 

var schema = Schema.Create(c =>
{
    // Register only pre-built date time type
    c.RegisterType<DateTimeType>();
});

**Comment by scottrabara** [comment]
Perhaps we should include a migration section in Scalar Type Support to make light of this situation @michaelstaib

**Comment by OneCyrus** [comment]
oh good to know. thanks!

**Comment by michaelstaib** [comment]
Hey @scottrabara, that is a good point ...

but let's create a separate section and put all migration steps there since we have another breaking change with the DataLoader.

**Comment by michaelstaib** [comment]
This one is now done .... https://hotchocolate.io/docs/next/migration
