### ISSUE TITLE
Shortcut for executing query from Banana Cake Pop Web version

### ISSUE THREAD

**Issue by Sa1Gur** [ChilliCream/hotchocolate#5305]
### Is your feature request related to a problem?

I'm sorry if this feature already presented, but I couldn't find it in the docs or by randomly run commands in UI
It is more productive to run command straight from the editor. 

### The solution you'd like

Ctrl+Enter

### Product

Banana Cake Pop

**Comment by tobias-tengler** [comment]
When you hover the controls, they should generally display the shortcut to you: 
![image](https://user-images.githubusercontent.com/45513122/184910842-21c996b1-75c7-461c-b5a2-976b230b5704.png)
(Just noticed that the keys are not properly separated with a +)
