### ISSUE TITLE
Allow fallback from redis to a file for stitching

### ISSUE THREAD

**Issue by stand-sure** [ChilliCream/hotchocolate#5312]
### Is your feature request related to a problem?

- For local development, needing to build/run an upstream project to populate a local redis cache is unreasonable
- Hosting redis in k8s with no external ingress is a common pattern (i.e. namespace isolated).
  - This makes it impossible for a local project to grab the schema at startup from an environment
- Remote schemas from redis behave differently than ones from files
- Code running in CI often does not have access to a redis instance
  - Adding redis to a pipeline, while feasible, increases the needs (and runtime time) of the CI pipeline

This leads to code like this
```c#
internal static IRequestExecutorBuilder AddRemoteSchemas(this IRequestExecutorBuilder builder, IServiceCollection services)
    {
        if (IsNotRunningInCI() && SchemaKeyExists(services))
        {
            static IConnectionMultiplexer ConnectionFactory(IServiceProvider provider)
            {
                return provider.GetRequiredService<ConnectionMultiplexer>();
            }

            builder.AddRemoteSchemasFromRedis(myName, ConnectionFactory)
                .AddDirectiveMergeRule(MergeDirectiveRules)
                .AddTypeMergeRule(MergeTypeRules);
        }
        else
        {
            builder.AddRemoteSchema(myName, true);
        }

        return builder.AddTypeExtensionsFromFile("./Stitching.graphql")
            .ModifyOptions(options => options.RemoveUnreachableTypes = true);
    }
```

### The solution you'd like

Update the signature to add a fallback file
```c#
public static IRequestExecutorBuilder AddRemoteSchemasFromRedis(
            this IRequestExecutorBuilder builder,
            NameString configurationName,
            Func<IServiceProvider, IConnectionMultiplexer> connectionFactory,
            string? fallbackFileName = null)
```

Update the process to use the fallback file (initially) if the schema is not in redis, and devise a retry mechanism so that the schema is eventually picked up if it is published (create the key and subscribe to it)

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
The new gateway works already with file configurations. I am closing this since with 13 something similar will be available.
