### ISSUE TITLE
Subscriptions: RabbitMQ provider

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/hotchocolate#5315]
### Is your feature request related to a problem?

In our project (I've already reported some issue regarding subscriptions under @cts-tradeit) we are using RabbitMQ to sync multiple instances in a swarm (which inspired me to write docu in #5295 which is still waiting for second approval). As of now there is not out of the box provider for RabbitMQ's PubSub.

### The solution you'd like

Creation of ITopicEventReceiver  and ITopicEventSender for RabbitMQ using RabbitMQ.Client.

If you are not currently planning this feature I can submit our solution in PR (reworked as it does not use those standard interfaces of HC but relies on IAsyncEnumerables directly).

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Can you get it to work with the standard interfaces?

**Comment by Deathrage** [comment]
Yes I can. The only issue is non string topics but as I can see you are serializing them for redis imple to string. This approach can be used for RabbitMQ exchanges aswell. 

So, to main (13) or main-12? If interfaces did not change I can do it to main-12 and u can cherry-pick it.

**Comment by michaelstaib** [comment]
main please ... we can cherry pick it to 12 later.

**Comment by Deathrage** [comment]
#5321

**Comment by PascalSenn** [comment]
close with https://github.com/ChilliCream/hotchocolate/pull/5599
