### ISSUE TITLE
Path.ToCollection() is not outputting indexer 

### ISSUE THREAD

**Issue by scottrabara** [ChilliCream/hotchocolate#534]
**Describe the bug**

The path should be able to accurately represent an object index if the error occurs in a list.

```js
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ]
    }
  ],
  "data": {
    "hero": {
      "name": "R2-D2",
      "heroFriends": [
        {
          "id": "1000",
          "name": "Luke Skywalker"
        },
        {
          "id": "1002",
          "name": null
        },
        {
          "id": "1003",
          "name": "Leia Organa"
        }
      ]
    }
  }
}
```
Path signifies the issue is occurring in list heroFriends on element index of 1. Currently, the QueryError can be constructed with a Path object that can validly represent this

```cs
\\ Path.ToString() returns {hero\heroFriends[1]\name}
Path.New("hero").Append("heroFriends").Append(1).Append("name")
```

The issue is seen during serialization, when we are accessing the IError.Path property. This is populated by writing the Path into a `Stack<string>` via the `ToCollection()' method

```cs
public IReadOnlyCollection<string> ToCollection()
{
    var stack = new Stack<string>();
    Path current = this;

    while (current != null)
    {
        stack.Push(current.Name);
        current = current.Parent;
    }

    return stack;
}
```

When we push, could we add the index as well if it exists? We can then break down the index during serialization to produce the path including the index of an element.

**Comment by michaelstaib** [comment]
This one is fixed with #555
