### ISSUE TITLE
In UsePaging generated node types are needlessly nullable 

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/hotchocolate#5358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Nullables in csproj are enabled. Resolver
```csharp
[UsePaging]
public IQueryable<Car> GetCars(...) {...}
```
Produces schema
```
type Queries {
   cars(...): CarsConnection
}
type CarsConnection {
   edges: [CarsEdge!]
   nodes: [Car!]
   ...
}
```

As I have never came across connection nor edges nor nodes being null, it should be:
```
type Queries {
   cars(...): CarsConnection!
}
type CarsConnection {
   edges: [CarsEdge!]!
   nodes: [Car!]!
   ...
}
```

This is especially noticable when using TypeScript generators with TypeScript's strict null checks enabled.

### Steps to reproduce

1. Above

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
This is deliberate and not a bug. In GraphQL you should be sparse with non-nullability on objects. Especially when dealing with connections. The GitHub API is a good reference here. 

However, we will introduce a some more control over this with version 13.

**Comment by cts-tradeit** [comment]
Can u elaborate on why? If object cannot be null why is it nullable? If I am to be sparse why mark anything as non nullable in the first place.

**Comment by Deathrage** [comment]
Can u elaborate on why? If object cannot be null why is it nullable? If I am to be sparse why mark anything as non nullable in the first place.

**Comment by DerZade** [comment]
Just stumbled upon this. I would also love to know some details about the reasons why this is intended.

I kinda get why the Connection itself is nullable, but I never got why list should be nullable, instead of just empty.

Thanks a lot in advance! 🙃

**Comment by bmwebster** [comment]
@michaelstaib Just ran into this, and I agree it would be really helpful to get non-nullable edges, did the option to control this make it into version 13?
