### ISSUE TITLE
.Net framework example

### ISSUE THREAD

**Issue by brohit** [ChilliCream/hotchocolate#5359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team,
i am not getting any of graphql project which is not implemented in .net framework . Will you please share the example repository if you have it.

### Steps to reproduce

1. .net framework example repo
2. it should just contain any example

### Relevant log output

```shell
No log file
```

### Additional Context?

Example

### Product

Hot Chocolate

### Version

12.0.0

**Comment by michaelstaib** [comment]
Hot Chocolate from version 11 on dropped support for .NET Framework Classic...

The new version will only support:
- .NET Core 3.1
- .NET 5
- .NET 6
- .NET 7

However, the Hot Chocolate Core does support .NET Standard, but you will need to implement the transport on your own.

Alternatively you could use Hot Chocolate 10 which still has support.
https://github.com/ChilliCream/hotchocolate/tree/main-version-10/examples/AspNetClassic.StarWars

However, we do no longer provide bug fixes for version 10.
