### ISSUE TITLE
Name of LocalCurrency scalar is incorrect

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#5369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is `LocalCurency` and should be `LocalCurrency`. Docs refers to it correctly.

Current workaround:
```
.AddType(x => new LocalCurrencyType("LocalCurrency"))`
```

### Steps to reproduce

1. Use `.AddType<LocalCurrencyType>()`, see it in schema output as wrong.

### Product

Hot Chocolate

### Version

12.13.0

**Comment by benmccallum** [comment]
Would it be considered a bug @michaelstaib that the workaround to add it with a better name ends up dropping off the type's description? e.g.

```c#
"The LocalCurrency scalar type is a currency string."
scalar LocalCurency

scalar LocalCurrency # missing desc
```

**Comment by michaelstaib** [comment]
That is deliberate ... since when creating a new name you also specify kind of change sematics ... so keeping the description seems wrong.
