### ISSUE TITLE
[Collection] New HTTP transport isues

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#5384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I discovered some bugs when trying out the new HTTP transport. I'll list each problem I find as a separate comment.

- [x] Validation errors produce wrong status code with Accept multipart/mixed
- [x] Full deferred query result is returned for other request
- [x] Deferred responses might not be correctly processed by the browser
- [x] Full deferred query result is returned for other request
- [x] Unsupported Accept header starting with application or multipart = 500

### Steps to reproduce

Below.

### Product

Hot Chocolate

### Version

13.0.0-preview.48

**Comment by tobias-tengler** [comment]
## No Accept Header + `@defer` leads to exception

Not specifying an `Accept` header when sending a request containing `@defer` in Chrome leads to HTTP 500 and the following exception:

```
System.InvalidOperationException: Invalid accept media types specified.
   at HotChocolate.AspNetCore.Serialization.DefaultHttpResponseFormatter.FormatAsync(HttpResponse response, IExecutionResult result, AcceptMediaType[] acceptMediaTypes, Nullable`1 proposedStatusCode, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Content-Type: application/json
Origin: http://127.0.0.1:5173
Referer: http://127.0.0.1:5173/
Content-Length: 125
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```

The request is sent like this:
```typescript
const body = JSON.stringify({
  query: `{
      field1
      ... @defer {
        field2
      }
    }
  `,
});

const response = await fetch("http://localhost:5000/graphql", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body,
});
```

**Comment by tobias-tengler** [comment]
## Validation errors produce wrong status code with Accept `multipart/mixed`

Sending an invalid GraphQL query in combination with the `multipart/mixed` Accept header yields a status code of 200, which should be 400 instead. For `application/graphql-response+json` 400 is correctly returned. For `application/json` 200 is also correctly returned.

### Reproduction

```typescript
// The closing } is deliberatly missing to cause validation error
const body = JSON.stringify({
  query: `{
      field1
    
  `,
});

const response = await fetch("http://localhost:5000/graphql", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Accept: "multipart/mixed",
  },
  body,
});
```

**Comment by tobias-tengler** [comment]
## 400 status code for validation error when Accept header is omitted

In [this section](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#legacy-watershed-1) the spec states:
> Before 1st January 2025 (2025-01-01T00:00:00Z), if the client does not supply an Accept header, the server SHOULD treat the request as if it had Accept: application/json. 

In [this section](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationjson) the spec states that for `Accept: application/json`:
> The server SHOULD use the 200 status code, independent of any GraphQL request error or GraphQL field error raised.

My understanding is that if no Accept header is specified the sever should respond with 200 for any GraphQL errors, including a validation error.

### Reproduction

```typescript
// The closing } is deliberatly missing to cause validation error
const body = JSON.stringify({
  query: `{
      field1
    
  `,
});

const response = await fetch("http://localhost:5000/graphql", {
  method: "POST",
  headers: {
    "Content-Type": "application/json"
    // The Accept header is omitted deliberately
  },
  body,
});
```

**Comment by tobias-tengler** [comment]
## Deferred fields leak between requests if previous request throws exception

The following query

```graphql
{
  field1
  ... @defer {
   field2
  }
}
```

can produce the following result

![image](https://user-images.githubusercontent.com/45513122/189433826-3451f926-af53-41a4-8b30-1136d48211dc.png)

if a request before errored out with an exception.

### Reproduction

First produce an exception as described [here](https://github.com/ChilliCream/hotchocolate/issues/5384#issuecomment-1242384633), by omitting the Accept header:

```
const body = JSON.stringify({
  query: `{
      field1
      ... @defer {
        field2
      }
    }
  `,
});

const response = await fetch("http://localhost:5000/graphql", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    // Accept: "multipart/mixed",
  },
  body,
});
```

Now just comment the Accept header back in and execute the request and you will see the duplicate defer messages.

**Comment by tobias-tengler** [comment]
## Deferred responses might not be correctly processed by the browser

**This could be an issue with the browser, meros or Hot Chocolate: I can't say with certainty yet.**

Follow [this GIST](https://gist.github.com/tobias-tengler/0dc2ff9c30a43108c75ebeefcfc3c566) to setup a reproduction and observe how the GraphQL response sent by the server is handled as a single response.

**Comment by tobias-tengler** [comment]
## Full deferred query result is returned for other request

**Can't reproduce this reliably yet, but it happened twice already**

I used the same server setup as I had in the GIST above and sent the same query with the deferred field

```graphql
{
  field1
  ... @defer {
    field2
  }
}
```

I was playing around with different headers while sending the request. If you look at the server code you should see that field2 should take 5 seconds to compute, but I randomly had the case that the query succeeded immediately **and** it had the full response.
This makes me think that the response was incorrectly returned from some sort of "response cache" (which I don't think exists) or the response was "stuck" from a previously failed request. It could also be that the deferred tasks were still lingering and resolved immediately.

I sadly just returned constants from the fields, otherwise I might've been able to tell more clearly what has happened...

**Comment by tobias-tengler** [comment]
## Unsupported Accept header starting with `application` or `multipart` = 500

No Accept header value or a value of `this is not an accept header value` is correctly treated as `application/json`.
A header like `application/unsupported` or `multipart/unsupported` will however yield a HTTP 500 with an exception (shown below).

The [spec states](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#body):
 >In alignment with the [HTTP 1.1 Accept](https://tools.ietf.org/html/rfc7231#section-5.3.2) specification, when a client does not include at least one supported media type in the Accept HTTP header, the server MUST either:
>
> Disregard the Accept header and respond with the default media type of application/json, specifying this in the Content-Type header; OR
> Respond with a 406 Not Acceptable status code and stop processing the request.

```
System.InvalidOperationException: Invalid accept media types specified.
   at HotChocolate.AspNetCore.Serialization.DefaultHttpResponseFormatter.FormatAsync(HttpResponse response, IExecutionResult result, AcceptMediaType[] acceptMediaTypes, Nullable`1 proposedStatusCode, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/unsupported
Connection: keep-alive
Host: localhost:5000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Content-Type: application/json
Origin: http://127.0.0.1:5173
Referer: http://127.0.0.1:5173/
Content-Length: 38
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```

### Reproduction

```typescript
const body = JSON.stringify({
  query: `{
      field1
    }
  `,
});

const response = await fetch("http://localhost:5000/graphql", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Accept: "unsupported", // --> HTTP 200 with no exception
    // Accept: "application/unsupported", // --> HTTP 500 with exception
  },
  body,
});
```

**Comment by michaelstaib** [comment]
We are opting for `Respond with a 406 Not Acceptable status code and stop processing the request.` 

I will check what the issue is.

**Comment by michaelstaib** [comment]
Thank you @tobias-tengler! We did not correctly fail on invalid headers ... I have implemented that now ... both cases work now.

**Comment by tobias-tengler** [comment]
I have just created https://github.com/graphql/graphql-over-http/issues/228 because I think it would make sense to have a shared collection of test cases that server maintainers can reference.

**Comment by michaelstaib** [comment]
I am getting very skeptical on this. The spec allows a lot of variance. We for instance go for the 206 if we do not find any applicable accept header. Others could just return any response... they could choose the new one, multipart whatever :) 

There are other issues I think that are really not good with the spec at the moment. Like, when handling BadRequests, I can do bad requests but I should not if legacy behavior is selected. The spec language is not precise enough on this at the moment.

Also, in our case above, where we send an invalid accept header in ... what is the expectation? is it legacy case or not since the request could really have occurred like this forever and worked. We handle it as 400 and switch to the GraphQL response type. But you could also deny that request much earlier.

I am at the moment collecting my issues with the spec text to have a more precise feedback.

In general I think it should be much stricter and predictable. And yes in essence we would need to have a small client or script that tests for compliance.

I have put our spec tests here:
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/AspNetCore/test/AspNetCore.Tests/GraphQLOverHttpSpecTests.cs

Another issue that we in particular have is that we have already a lot more transport features than what the spec covers and fitting that in is not so easy.

**Comment by michaelstaib** [comment]
@tobias-tengler that does not mean its fruitless to attempt a common set of script. Its actually what everyone in the workgroup would like to have :)

**Comment by michaelstaib** [comment]
@tobias-tengler apart from that ... I found the issue that we have at the moment with the multipart response.

The issue seems to be that with multipart we need to write the (CRLF, ---, CRLF) delimiter for the multipart reader to start reading the next section.

This is a bit problematic since we await on an async iterator which might not have another result. It gets even a bit more complex with the latest changes I need to incorporate in which case the response stream will change to a `IAsyncEnumerable<IQueryResult|IQueryResult[]>`.

Not sure how to model this in .NET yet.

**Comment by michaelstaib** [comment]
OK, defer is now much better with the streams again ... we are still using the old payload ... thats the next thing I will start on tomorrow.

BTW ... this are the new responses:

```json
{
  "incremental": [
    {
      "label": "homeWorldDefer",
      "path": ["person"],
      "data": { "homeWorld": { "name": "Tatooine" } }
    },
    {
      "label": "filmsStream",
      "path": ["person", "films", 1],
      "items": [{ "title": "The Empire Strikes Back" }]
    }
  ],
  "hasNext": true
}
```

**Comment by tobias-tengler** [comment]
@michaelstaib is it supposed to HTTP 400, if I send two supported Accept header values?

```
Accept: "application/graphql-response+json, mulitpart/mixed"
```

I want to signal to the server that I support both multipart and "regular" responses. If possible it should use "application/graphql-response+json" for regular queries and "multipart/mixed" only for deferred queries. Am I assuming something wrong?

**Comment by michaelstaib** [comment]
Thats a bug that is fixed with preview 59

**Comment by tobias-tengler** [comment]
I think these have all been addressed, so I'm closing this.
