### ISSUE TITLE
Automatic type registration via source generator does not work

### ISSUE THREAD

**Issue by bohdan-kolomiiets** [ChilliCream/hotchocolate#5388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I simply cannot make it to generate source files for types registration.
I intentionally used `13.0.0-preview.19` version of library `HotChocolate.Types.Analyzers` for this demo as this version was used in this video by author.
https://www.youtube.com/watch?v=QPelWd9L9ck

![hotchocolate1](https://user-images.githubusercontent.com/23737741/189503222-3aed1f3c-4724-438d-af06-697efe4dcd7a.png)
![hotchocolate2](https://user-images.githubusercontent.com/23737741/189503224-7be9e8d6-55c1-4147-b31f-be19965a30fa.png)
![hotchocolate3](https://user-images.githubusercontent.com/23737741/189503225-11cdb2d2-1340-4852-8d67-64ee7454c1c9.png)

### Steps to reproduce

<b>Api.csproj</b>
```
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Api</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="13.0.0-preview.19" />
        <PackageReference Include="HotChocolate.Types.Analyzers" Version="13.0.0-preview.19" />
    </ItemGroup>
</Project>
```

<b>Program.cs</b>
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer().AddQueryType<Query>();

var app = builder.Build();
app.MapGraphQL();
app.Run();

public class Query
{
    public SomeEntity GetEntity() => new SomeEntity(Id: "1", Name: "name");
}
public record SomeEntity([GraphQLType(typeof(IdType))]string Id, string Name);
```

### Product

Hot Chocolate

### Version

13.0.0

**Comment by tobias-tengler** [comment]
No type is obviously a GraphQL type. You have a record, but you don't say that it should be a GraphQL type. It will be inferred as a type at schema build time, but at compile time the analyzer does not consider it a type.
Only types that are annotated as GraphQL types ([ObjectType], [InterfaceType], etc),  extend a type ([ExtendObjectType]) or are inheriting from one of the type classes (ObjectType<T>, etc.) are considered GraphQL.

Putting the [ObjectType] attribute on the record should make it show up.

**Comment by bohdan-kolomiiets** [comment]
Thanks for the advice. 
It turned out I had to add `[ObjectType]` attribute to `Query` type. It was no need to add attribute on `SomeEntity` record because it used by query, so inferred by reflection further as I understand.

So, an updated app code looks like this.
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer().AddApiTypes();

var app = builder.Build();
app.MapGraphQL();
app.Run();

[ObjectType]
public class Query
{
    public SomeEntity GetEntity() => new SomeEntity(Id: "1", Name: "name");
}

public record SomeEntity([GraphQLType(typeof(IdType))]string Id, string Name);
```

And the next code was auto-generated.

```
    public static class ApiTypesRequestExecutorBuilderExtensions
    {
        public static IRequestExecutorBuilder AddApiTypes(this IRequestExecutorBuilder builder)
        {
            builder.AddType<Query>();
            return builder;
        }
    }
```

**Comment by tobias-tengler** [comment]
I would always register the root operation types eyplicitly. I'm not sure if the query type will be treated as a Query type based solely on its name, when using `AddType`, but I doubt it.

**Comment by michaelstaib** [comment]
@tobias-tengler actually yes ... The spec says:

> Default Root Operation Type Names
> 
> While any type can be the root operation type for a GraphQL operation, the type system definition language can omit the schema definition when the query, mutation, and subscription root types are named Query, Mutation, and Subscription respectively.
> 
> Likewise, when representing a GraphQL schema using the type system definition language, a schema definition should be omitted if it only uses the default root operation type names.
> 
> This example describes a valid complete GraphQL schema, despite not explicitly including a schema definition. The Query type is presumed to be the query root operation type of the schema.

This spec text is for the SDL but we do it the same for code-first and annotation-based. 

So,

if you do not specify anything we will expect the `Query` type to be named query, which also means if you do `AddType<Query>` we will register it as query type.

But explicit is better so ... `AddQueryType<T>` is to be preferred....

Also as a side note... if you have a random type `Subscription` that actually is not meant to be the subscription type you need to rename the subscription type in the schema options so that we do not infer it as subscription type.
