### ISSUE TITLE
define enumType instead of intType from int property

### ISSUE THREAD

**Issue by hnazari13701371** [ChilliCream/hotchocolate#5395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

consider my model like below 
`public class user{
public int status{get;set;}
}`

i want to generate enumType base on status field that is a int type
and also using filtering feature that work on IQueryable using efcore

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
This is not a bug but more a question .... for questions join us on slack.chillicream.com
