### ISSUE TITLE
Fields with attached non-pure resolvers or middleware are not returned via @stream

### ISSUE THREAD

**Issue by atykhyy** [ChilliCream/hotchocolate#5403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I have a field in my code-first schema that has field middleware attached to it, or if its `ObjectFieldDefinition.Resolver` is set, the field is returned as expected from normal queries, but not if it is requested via `@stream` (the backing .NET object containing the field is structurally identical). However, if the field has a `ObjectFieldDefinition.PureResolver` set rather than a `Resolver`, or is just bound to a member of the object, then it is returned both with and without `@stream`.

### Steps to reproduce

Code reproducing the problem is given below. [Complete minimal repro project is attached](https://github.com/ChilliCream/hotchocolate/files/9586448/ConsoleApp1.zip). Tested with HC 12.11.1-12.13.2.
```csharp
public class Query
{
    public Container Container => new () ;
}

public class Container
{
    public Model? Model => new () { Value = "bar" } ;
    public async IAsyncEnumerable<Model?>? GetModels ()
    {
        yield return new () { Value = "foo" } ;
    }
}

public class Model
{
    public string? Value { get ; set ; }
}

internal class TypeInitializationInterceptor : TypeInterceptor
{
    public override void OnBeforeCompleteType (
        ITypeCompletionContext completionContext, DefinitionBase? definition, IDictionary<string, object?> contextData)
    {
        if (definition is ObjectTypeDefinition otd)
            foreach (var field in otd.Fields)
                if (field.Name == "value")
                    #if false
                    field.Resolver = context => new ValueTask<object?> ("baz") ; // field not present in response
                    #else
                    field.PureResolver = context => "baz" ; // field present in response with value 'baz'
                    #endif
    }
}

internal class Program
{
    static async Task Main ()
    {
        using var host = Microsoft.AspNetCore.WebHost
            .CreateDefaultBuilder ()
            .ConfigureServices (services => services
                .AddGraphQLServer ()
                .ConfigureSchema  (builder => builder
                    .AddQueryType<Query> ().AddObjectType<Container> ().AddObjectType<Model> ()
                    .TryAddTypeInterceptor (new TypeInitializationInterceptor ())))
            .Configure (app => app.UseRouting ().UseEndpoints (builder => builder.MapGraphQL ("/gql")))
            .UseKestrel (options => options.ListenLocalhost (11111)).Build () ;

        await host.StartAsync () ;
        using var client = new HttpClient () ;
        Console.WriteLine (await client.GetStringAsync (
            "http://localhost:11111/gql?query={container{models @stream{value}}}")) ;
    }
}
```

### Product

Hot Chocolate

### Version

12.13.2

**Comment by atykhyy** [comment]
Update: 13.0.0-preview.56 does not suffer from this issue.

**Comment by michaelstaib** [comment]
The implementation for 13 is completely reworked. Due to the spec proposal (which now entered draft stage) having changed from august to the september edits quite drastically we will not port them back to 12, as this would break to many people.

Version 13.0.0-preview.59 is now almost done for defer and stream ... so use this instead of 12 if you want to use stream.
