### ISSUE TITLE
No connection between Apollo Client and HC 13 using graphql-ws

### ISSUE THREAD

**Issue by maxnatamo** [ChilliCream/hotchocolate#5418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't seem to find a way to establish a connection between a NextJS app and Hot Chocolate 13. The NJS application uses Apollo Client with the `graphql-ws` transport.

I'm using the preview.59 version of HC for AspNetCore, Subscriptions and Subscriptions.InMemory.

Firefox reports that it can't establish a connection to the backend endpoint:
![image](https://user-images.githubusercontent.com/5898152/191278551-5e4520a1-d511-4276-897d-840be9b81ffb.png)

Banana Cake Pop also reports issues, but I'm unsure whether it has been updated to support the new `graphql-ws` transport:
```json
{
  "errors": [
    {
      "message": "Unknown subscription error"
    }
  ]
}
```

I've attached the relevant code snippets under 'Additional Context.'

### Steps to reproduce

1. Create .NET 6 application with a simple topic subscription in HC 13
2. Map HTTP to `/graphql` and WS to `/graphql/ws`
3. Try to connect via Apollo Client with `graphql-ws` and Banana Cake Pop

### Additional Context?

.NET 6 `Program.cs`:
```cs
public static void Main(string[] args)
{
    var builder = WebApplication.CreateBuilder(args);
    var graphQl = builder.Services.AddGraphQLServer();
    // [...]

    builder.Services.AddInMemorySubscriptions();
    builder.Services.AddCors();

    graphQl.AddSubscriptionType(v => v.Name("Subscription"))
           .AddTypeExtension<MessageSubscription>();

    // [...]
    var app = builder.Build();

    app.UseCors(builder =>
    {
        builder.AllowAnyOrigin()
               .AllowAnyHeader()
               .AllowAnyMethod();
    });

    app.MapGraphQLHttp("/graphql");
    app.MapGraphQLWebSocket("/graphql/ws");
    // [...]
}
```

NextJS Apollo Client snippet:
```js
const httpApiEndpoint = "http://localhost:5000";
const wsApiEndpoint = "ws://localhost:5000";

const createWsLink = () => {
    const httpLink = new HttpLink({
        uri: `${httpApiEndpoint}/graphql`
    });

    if(typeof window === 'undefined') {
        return httpLink;
    }

    const wsLink = new GraphQLWsLink(createClient({
        url: `${wsApiEndpoint}/graphql/ws`
    }));

    return split(
        ({query}) => {
            const def = getMainDefinition(query);
            return (
                def.kind === 'OperationDefinition' && def.operation === 'subscription'
            );
        },
        wsLink,
        httpLink
    );
};

const createApolloClient = (config) => {
    const defaultConfig = {
        link: createWsLink(),
        cache: new InMemoryCache(),
    };

    return new ApolloClient({
        ...defaultConfig,
        ...config
    });
};
```

### Product

Hot Chocolate

### Version

13.0.0-preview.59

**Comment by maxnatamo** [comment]
The issue still persists.

Also, [this](https://github.com/ChilliCream/hotchocolate/issues/3758#issuecomment-1203115517) seems to imply that the websocket middleware isn't necessary.

**Comment by tobias-tengler** [comment]
Mhmm apart from that everything looks fine. BCP supports graphql-ws and I'm also using graphql-ws in combination with Relay and Hot Chocolate 13.0.0-preview.58.
Since the issue is also happening in BCP I'm assuming that it's either a beowser issue or a Hot Chocolate issue. Can you maybe try a different browser besides Firefox and with no extensions, just to ensure it's not rhe browser's fault?
If the browser isn't at fault, can you craft a minimal reproduction of your Hot Chocolate server (example isn't runable).

**Comment by maxnatamo** [comment]
In creating the minimal setup, I realized the (my) error.

`MapGraphQL` obviously maps all of the services to a single endpoint. However, I was doing `MapGraphQLHttp` and `MapGraphQLWebSocket` individually, hereby excluding the schema-endpoint.

**Comment by tobias-tengler** [comment]
Okay, but the schema endpoint should have nothing to do with it. Both BCP and Apollo should work without it.
