### ISSUE TITLE
UseLazyLoadingProxies does not work properly together with pooled database contexts

### ISSUE THREAD

**Issue by OskarPersson** [ChilliCream/hotchocolate#5420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using UseLazyLoadingProxies on a pooled DbContext I can freely query related fields for a model and have EF create all the necessary joins without me having to add `.Include(...)` to my queries. This also seems to work when using GraphQL with the help of HotChocolate to query, but not when using a pooled context.

Instead I get the following error:
```
Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.\nObject name: 'LazyGraphQlDbContext'.
```

### Steps to reproduce

1. Clone my repo where I've tried to create a minimal example where this can be reproduced https://github.com/OskarPersson/LazyGraphQl
2. It includes a simple Sqlite database, `lazy.db`, which the app currently expects to be placed on the desktop of the host.
3. Start the app and visit `https://localhost:<port>/graphql/` and run:
```graphql
{
  books {
    title,
    author {
      name
    }
  }
}
```

This should result in the error described above.

4. When visiting `https://localhost:<port>/`, the same data is fetched without GraphQL and it works as expected.
5. Try changing to a non-pooled context OR updating BookQueries to the following and it should work:
```csharp
public class BookQueries
{
    public IQueryable<Book> GetBooks(LazyGraphQlDbContext context, IResolverContext resolverContext)
        => context.Books.Include(b => b.Author);
}
```

### Product

Hot Chocolate

### Version

12.13.2

**Comment by michaelstaib** [comment]
This is correct since the pooled DB context is already returned to the pool. This is expected behavior. A more predictable approach is to use projections instead of lazy loading. This will lead to the GraphQL engine rewriting the queryable to fetch all requested fields at once.
