### ISSUE TITLE
StrawberryShake - Cannot resolve scoped service 'ITokenService' from root provider.

### ISSUE THREAD

**Issue by telok-org** [ChilliCream/hotchocolate#5421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following [documentation](https://chilly-auth-docs.netlify.app/docs/strawberryshake/networking/authentication) I wrote this piece of code:

```
builder.Services.AddGraphQLService()
    .ConfigureHttpClient((serviceProvider, client) =>
    {
        var token = serviceProvider.GetRequiredService<ITokenService>().Value;

            client.BaseAddress =
                new Uri("https://localhost:7114/graphql/");
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", token);
    });
```

but I'm getting 

`Cannot resolve scoped service 'ITokenService' from root provider.`

I'm using .NET 6 with StrawberryShake v. 12.13.2

Any help will be strongly appreciated \m/

### Steps to reproduce

1. 

### Product

Strawberry Shake

### Version

12.13.2

**Comment by tobias-tengler** [comment]
Not a Strawberry Shake error and the error message is telling you exactly what's wrong: Your service is scoped and the `serviceProvider` is the root service provider, which can't resolve scoped services.

What you need to do is new up a scope yourself and resolve the service from there:

```csharp
using var scope = serviceProvider.CreateScope();
var tokenService = scope.ServiceProvider.GetRequiredService<ITokenService>();

// ...
```


If the using disposes resources your service depends on to early, just change to a using block or dispose it manually.

Hope this helps :)
