### ISSUE TITLE
Unit test coverage not detected, using coverlet in combination with report generator

### ISSUE THREAD

**Issue by philippfleischanderl** [ChilliCream/hotchocolate#5436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We measure our unit test coverage with following tools:

 - coverlet- coverage (https://github.com/coverlet-coverage/coverlet)
 - report generator (https://reportgenerator.io/)
 
All classes which use ExtendObjectType annotations like [ExtendObjectType("Query")], [ExtendObjectType("Mutation")], etc. have a coverage from 0% even when you write unit tests for these classes.

The expected behavior is that the coverage will be measured correctly.

### Steps to reproduce

1. use hotchocolate in a c# project
2. add queries, mutations and types
3. write unit tests for these classes
4. generate the coverage .xml file with coverlet-coverage tool, which is also part of .NET foundation (https://github.com/coverlet-coverage/coverlet, https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows)
5. pass the outcome of coverlet-coverage tool to the report generator (https://reportgenerator.io/usage)
6. you will face 0% coverage for all classes with ExtendObjectType (queries, mutation, types, etc.), therefore our internal quality gates cannot be fulfilled 

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
We use coverlet for all of our tests and have no issue with it so far. It might be the way you setup your projects, there are a couple of settings. But this is really not a Hot Chococlate issue. I am closing this issue since its out of scope for this project.
