### ISSUE TITLE
Way to create queries with custom errors [Error(typeof(...))]

### ISSUE THREAD

**Issue by vadymkutsenko** [ChilliCream/hotchocolate#5438]
### Is your feature request related to a problem?

Here is presented perfect way for creating custom errors at mutations:
https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations 
with `.AddMutationConventions()`

Do you plan introduce some similar feature for queries too?
In my case, i would to have shared custom errors for both (queries/mutations)

### The solution you'd like

```
[ExtendObjectType(typeof(Query))]
public class CurrentUserOperation
{
    [Error(typeof(CompanyHasNoAccessToError))]
    [Error(typeof(UserHasNoAccessToError))]
    public User GetCurrentUser()
    {
        return new User { Id = Guid.NewGuid().ToString() };
    }
}

public class UserHasNoAccessToError : Exception
{
    private string Resource { get; init; }
    public UserHasNoAccessToError(string resource) : base($"User has no access to this resource: {resource}")
    {
        Resource = resource;
    }
}

public class CompanyHasNoAccessToError : Exception
{
    private string Resource { get; init; }
    public CompanyHasNoAccessToError(string resource) : base($"Company has no access to this resource: {resource}")
    {
        Resource = resource;
    }
}
```

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
There are no plans to add this to query as this would lead to a bad schema design.  Input and Payload types ... and the errors in this case are implementing this on the payload type are a bad schema design in GraphQL. On queries the only thing that could go wrong is an actual error.

There is presedence for error unions on the query side ... But i would not really call them errors but results :) This is something we might look at.

I am closing this issue as we do not plan to pick it up.
