### ISSUE TITLE
Gateway enhancement

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#5443]
### Is your feature request related to a problem?

Hotchocolate is great, I am considering it for production,

But i thking the gateway lacks some important functions,  like heathcheck,  schema  register automatically  for new published service without restart gateway. etc.

For now , I had to register each service Manually (maybe can read from config file or anywhere else) , like this:
```c#
services.AddHttpClient(Accounts, c => c.BaseAddress = new Uri("http://localhost:5051/graphql"));
services.AddHttpClient(Inventory, c => c.BaseAddress = new Uri("http://localhost:5052/graphql"));
services.AddHttpClient(Products, c => c.BaseAddress = new Uri("http://localhost:5053/graphql"));
services.AddHttpClient(Reviews, c => c.BaseAddress = new Uri("http://localhost:5054/graphql"));
```

### The solution you'd like

![image](https://user-images.githubusercontent.com/49356505/192678663-0fd798bf-12f0-42b2-8d2b-8c6775918567.png)

I think the service downstream can generate this format when publish the schema to the redis.
```json
{
    "serviceName":"demo",
    "servicePort": 80,
    “scheme”:"xxx"   //base64 format string
}
```
so the full url is ```http://{serviceName}:{servicePort}/graphql```                (kindly for k8s)
ant the gateway can read config from redis and register/update schema of service downstream automatically,

And healthchek is clearly to implement.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
This is all coming with version 13. I am closing this issue since its to broad in focus and we already have implemented most of it.

**Comment by michaelstaib** [comment]
join us on slack.chillicream.com if you want to follow announcements on this.
