### ISSUE TITLE
Accept header with multiple media types is not accepted

### ISSUE THREAD

**Issue by aristotelos** [ChilliCream/hotchocolate#5444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sending a request with multiple `Accept` media types such as `application/json, text/plain, */*` (the Apollo Angular client default) results in an exception:

```
curl --location --request POST 'http://localhost:7001/api/worklistQuery' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Authorization: Bearer ***' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query {\r\n  posts {\r\n      id\r\n  }\r\n}","variables":{}}'
```

```
{
    "errors": [
        {
            "message": "Unable to parse the accept header value `application/json, text/plain, */*`.",
            "extensions": {
                "headerValue": "application/json, text/plain, */*",
                "code": "HC0064"
            }
        }
    ]
}
```

The same request with a simple `Accept` header such as `application/json` or `*/*` returns 200 OK, so it is about being able to parse multiple media types.

### Steps to reproduce

1. Send a GraphQL query with header `Accept: application/json, text/plain, */*`.
2. A 400 Bad Request is returned. Expected: 200 OK

### Product

Hot Chocolate

### Version

13.0.0-preview.56

**Comment by michaelstaib** [comment]
This is now fixed.
