### ISSUE TITLE
ChilliCream code generator on .NET 6 C# 10 (console) dont work

### ISSUE THREAD

**Issue by bnayae** [ChilliCream/hotchocolate#5457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following the Get Started [tutorial](https://chillicream.com/docs/strawberryshake/get-started/console) using .NET 6 & C# 10.
Don't generate code. 
`dotnet build` don't create the `Generated` folder.

### Steps to reproduce

1. Follow the [tutorial](https://chillicream.com/docs/strawberryshake/get-started/console) 

### Additional Context?

C# 10 .NET 6

### Product

Strawberry Shake

### Version

latest

**Comment by bieri** [comment]
Make sure the csproj file has no entries for the .graphql files like so

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.13.2" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="12.13.2" />
  </ItemGroup>
</Project>
```

**Comment by michaelstaib** [comment]
Check out our new generator in the preview... first watch the video as the package structure changed:
https://www.youtube.com/watch?v=utIbv15yn1Y
