### ISSUE TITLE
SS0006 error when using StrawberryShake 

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/hotchocolate#5462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting following error for each auto-generated client in VS2022:

```Error	SS0006	Method not found: 'Microsoft.Extensions.DependencyInjection.ServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.	Qualo.Applications.CasesManagement.Bll		1	Active
```

Application builds and runs just fine, but error is always there. It doesn't show in which file, removing `StrawberryShake.CodeGeneration.CSharp.Analyzers` from the dependencies fixes the issue.

### Steps to reproduce

Content of .graphqlrc.json:

```{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "extensions": {
    "strawberryShake": {
      "name": "TestClient",
      "url": "http://localhost:5010/graphql",
      "dependencyInjection": true,
      "strictSchemaValidation": true,
      "hashAlgorithm": "md5",
      "useSingleFile": true,
      "requestStrategy": "Default",
      "outputDirectoryName": "Generated",
      "noStore": false,
      "emitGeneratedCode": true,
      "razorComponents": false,
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}```

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Strawberry Shake

### Version

12.14.0

**Comment by michaelstaib** [comment]
We have fixed these issues already in the newer version of StrawberryShake ... 

Here is a video for getting started with Strawberry Shake in version 13 with Blazor:
https://www.youtube.com/watch?v=-oq7YEciouM

Or one to get started with Strawberry Shake in version 13 for server to server communication:
https://www.youtube.com/watch?v=I0ihOcBVu8c
