### ISSUE TITLE
New .graphql files added to the project are ignored

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/hotchocolate#5463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Each time I add file with `.graphql` extension to project that contains `StrawberryShake.CodeGeneration.CSharp.Analyzers` dependency, the following entry is added to the `.csproj` configuration file:

```  <ItemGroup>
    <GraphQL Remove="PATH_TO_GRAPHQL_FILE.graphql" />
  </ItemGroup>```

I need to manually remove this entry for code generation to kick-in.

### Steps to reproduce

1. Just add any `.graphql` file to project.

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Strawberry Shake

### Version

12.14.0

**Comment by michaelstaib** [comment]
This is already fixed for version 13
