### ISSUE TITLE
BananaCakePop not working when the app is behind a proxy

### ISSUE THREAD

**Issue by Rod-O** [ChilliCream/hotchocolate#5480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when the app is behind a proxy I receive:
You need to enable JavaScript to run this app.

### Steps to reproduce

1. Setup the app behind an nginx reverse proxy

### Product

Banana Cake Pop

### Version

12.15.0

**Comment by tobias-tengler** [comment]
Banana Cake Pop depends on additional files containing CSS and JavaScript, just as any other website.
You're proxy configuration is likely just forwarding requests for a single `/graphql` endpoint.
Banana Cake Pop's files are located at `/graphql/static/**/**` though. So you need to at least also forward anything that goes against the `/graphql/static`.
If your proxy is not setup correctly you should see failed requests to those content files in the browser dev tools.
Hope this helps.

If you come up with a working configuration, please share it and I'll add it as an example to the docs.
