### ISSUE TITLE
Preview package of StrawberryShake.CodeGeneration.CSharp.Analyzers

### ISSUE THREAD

**Issue by mrwellmann** [ChilliCream/hotchocolate#5487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm running a Strawberry Shake 13 in a Console application.

After updating `StrawberryShake.Transport.Http 13.0.0-preview.47` to .`70` I'm getting multiple `...namespace 'Helper' does not exist in the namespace 'StrawberryShake'...` after compiling it. The error comes from the auto generated file. The latest version it works without the error is `StrawberryShake.Transport.Http 13.0.0-preview.51`

My guess is this is because the package `StrawberryShake.CodeGeneration.CSharp.Analyzers` which is version `13.0.0-preview.24` is outdated. But I cant find a newer package. On [nuget](https://www.nuget.org/packages/StrawberryShake.CodeGeneration#versions-body-tab) there is even no more preview package of it.

What did I miss? Did the package changed?

### Steps to reproduce

1. Follow the guide Strawberry Shake in a Console application
2. Try to update it to 13.0.0-preview

### Product

Strawberry Shake

### Version

13.0.0-preview.70

**Comment by PascalSenn** [comment]
@mrwellmann  So we changed a bunch of stuff in version 13 and strawberry shake. One of the big changes is the compilation.
What do you use Strawberry Shake for? Server2Server, Blazor, MAUI? We now have helper packages which already configure everything you need for a specific environment

**Comment by mrwellmann** [comment]
I'm using it with in a Unity 3D application.

My current workflow is using a StrawberryShake Console project get the auto generated c# file `MyApp.g.cs`. Then I import that file into Unity.

The reason for this workflow is that Unity at its current state only suppots .NET Standart 2.1 and has a next to no support for nuget and It handle some packages. I was able to get strawberryshake.transport.http and some oder stuff like polly working. But I have to do the generation out side of Unity.

**Comment by michaelstaib** [comment]
In this case use the new StrawberryShake.Server package ... here is a youtube video explaining it:
https://www.youtube.com/watch?v=I0ihOcBVu8c

**Comment by michaelstaib** [comment]
If you need more help putting it together join us on slack.chillicream.com

**Comment by mrwellmann** [comment]
Works thanks for the help.
