### ISSUE TITLE
[HC 12.15.0] Schema federation with scoped field delegation throws an error

### ISSUE THREAD

**Issue by lynxz** [ChilliCream/hotchocolate#5490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Usage of Federated Graphs with `@delegate` directive that uses `$fields` references causes an error to be reported. This bug can be reproduced with the code in the following [GitHub repo](https://github.com/lynxz/FederationTest) . 

When testing the problem seems to originate in the _FieldScopedVariableResolver_ in _HotChocolate.Stitching_, the problem is that the item that is returned from `context.Parent<object>()`  is the original type and not the expected ´IReadOnlyDictionary<string, object>´, hence in the code the if statement is never executed and the `valueLiteral` is always null. 

```csharp
if (context.ObjectType.Fields.TryGetField(variable.Name.Value, out IObjectField? field))
            {
                object parent = context.Parent<object>();

                IValueNode? valueLiteral = null;

                if (parent is IReadOnlyDictionary<string, object> dict &&
                    dict.TryGetValue(field.Name, out var value))
                {
                    InputFormatter formatter = context.Service<InputFormatter>();

                    if (value is IValueNode v)
                    {
                        valueLiteral = v;
                    }
                    else if(field.Type.IsInputType() && field.Type is IInputType type)
                    {
                        valueLiteral = formatter.FormatValue(value, type, field.Name);
                    }
                }

                return new ScopedVariableValue
                (
                    variable.ToVariableName(),
                    targetType.ToTypeNode(),
                    valueLiteral ?? NullValueNode.Default,
                    null
                );
            }
```

Perhaps I'm missing some crucial part of the setup as I couldn't find any one else reporting this issue. 

### Steps to reproduce

1. Clone this repo [GitHub repo](https://github.com/lynxz/FederationTest) 
2.  Execute the following query against `Main` 
```graphql
{
  book {
     publisherId
     publisher {
      name
     }
  }
}
```

### Relevant log output

```shell
Response 

{
  "errors": [
    {
      "message": "Variable `__fields_publisherId` is required.",
      "extensions": {
        "code": "HC0018",
        "variable": "__fields_publisherId",
        "remote": {
          "message": "Variable `__fields_publisherId` is required.",
          "extensions": {
            "code": "HC0018",
            "variable": "__fields_publisherId"
          }
        },
        "schemaName": "publish"
      }
    }
  ]
}
```

### Product

Hot Chocolate

### Version

12.15.0

**Comment by lynxz** [comment]
I'm unsure what you mean by a gateway service. The example project is a simplified case of an example supplied by ChiliCream.

**Comment by vickytr44** [comment]
Please refer to the git repo for gateway implementation.
Link: https://github.com/vickytr44/FederationTest
You can think of a gateway as a separate service whose sole purpose is to stitch the schema of downstream service into one schema.

**Comment by lynxz** [comment]
I see now, I made the assumption that the Gateway could have models as well but the assumption is that all data is fetched from other instances. Thank you for explaining.
