### ISSUE TITLE
Serialization of multiple queries/mutations causes response timeout

### ISSUE THREAD

**Issue by ikirkpat** [ChilliCream/hotchocolate#5495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When multiple queries or mutations are being serialized, the response hangs up and a timeout occurs.

We override the IResponseStreamSerializer to get around the AllowSynchronousIO issue in https://github.com/ChilliCream/hotchocolate/issues/2273. We basically copied the source from HotChocolate 11 for the IResponseStreamSerializer. Here's a copy of the file for reference: [JsonQueryResultSerializer.cs](https://github.com/ChilliCream/hotchocolate/files/9831592/JsonQueryResultSerializer.cs.txt).

We've found that execution of the `SerializeAsync` methods seems to halt in the middle of execution. I put Console.WriteLines in and found that it halts while going to the next iteration in the for loop (line 35 in that file). It doesn't ever exit the for loop or go onto the next iteration. It gets one iteration in, finishes that iteration and then just dies.

```cs
35 await foreach (IReadOnlyQueryResult result in responseStream.WithCancellation(cancellationToken).ConfigureAwait(false))
36 {
37     await WriteNextResultAsync(result, outputStream, delimiter, cancellationToken).ConfigureAwait(false);
38     delimiter = true;
39 }
40 
41 await outputStream.WriteAsync(_rightBracket, 0, _rightBracket.Length).ConfigureAwait(false);
```

I saw that it was getting through line 38 above but that seemed to be the last line that was executed. I didn’t see it leave the for-loop and execute line 41… but it also never looped back and executed line 37 again.

### Steps to reproduce

It seems to be fairly inconsistent as to when this happens but it seems to happen mainly when the request contained multiple root level queries (the results are in the magnitude of Killobytes which makes it seem like size isn't really the issue... maybe I'm wrong though).

The result when it does happen is that the response just hangs up. Eventually, after a few minutes, the request/response times out.

### Additional Context?

We're using HotChocolate version 10.5.2. We have thought about upgrading but honestly, from looking into this issue, I'm not convinced that upgrading will fix the issue. Given the large amount of work that upgrading would require, I'd prefer to avoid that based on a hunch.

We could just remove the override but then we run into the issue in https://github.com/ChilliCream/hotchocolate/issues/2273. This could lead to other deadlocks due to Thread Starvation (see https://github.com/dotnet/aspnetcore/issues/7644).

I believe the underlying issue here may be found in https://github.com/dotnet/aspnetcore/pull/8303. It appears that System.Text.Json has always had issues with serializing large results because it's always been synchronous rather than asynchronous. Maybe the mixing of sync and async is causing a deadlock.

### Product

Hot Chocolate

### Version

10.5.2

**Comment by michaelstaib** [comment]
We no longer support version 10 or version 11. If you can reproduce the issue in version 12 latests or version 13 latests preview I can have a look.
