### ISSUE TITLE
Union schema type class does not generate a union type in the schema

### ISSUE THREAD

**Issue by dotarj** [ChilliCream/hotchocolate#5499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use a union schema type class for a query which can return two types of classes, a `File` and a `Folder`. These classes both inherit from `FileOrFolder`, which is required by Entity Framework Core to map a table to multiple types using discriminators. Before the union schema type class, I used the UnionTypeAttribute and marker a interface which worked good, but I'm trying to keep my models clean and thus try to move away from attributes. 

There is a lot of context to describe so I've created a GitHub repository in which this situation is mimicked: https://github.com/dotarj/UnionTypeTest. The main problem is that it seems that the schema is generated using the return type of the query method `public IQueryable<FileOrFolder> GetFilesAndFolders(...)` instead of the return type that has been defined using the query object type descriptor:

```
public class QueryObjectType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor
            .Field(query => query.GetFilesAndFolders(default!))
            .Type<ListType<FileOrFolderUnionType>>()
            .UseOffsetPaging(options: new PagingOptions() { IncludeTotalCount = true })
            .UseProjection()
            .UseFiltering()
            .UseSorting();
    }
}
```

This results in a schema which does not contain a union type (`union FileOrFolder = File | Folder`), but a type that is generated using the base type:

```
type FileOrFolder {
  id: Int!
  folderId: Int!
  name: String!
}
```

As I mentioned earlier, it seems that the object type is generated using the return type of the query method. If I change the return type of the query method to `IQueryable<object>` it does seem to work, but then projection, filtering and sorting must be disabled because related object types are also generated using query return type.

Is this a bug, or did I make a mistake in configuring the objects?

### Steps to reproduce

With the GitHub repository (https://github.com/dotarj/UnionTypeTest) it should be fairly easy to reproduce the problem.

### Product

Hot Chocolate

### Version

13.0.0-preview.69

**Comment by dotarj** [comment]
I've managed to get this working. I've updated the sample repository with a working version: https://github.com/dotarj/UnionTypeTest/tree/f87cd84a97aebbd4796a74dc7503ffb98b883e46.

The solution was indeed to return `IQueryable<object>`, and (of course) tell HotChocolate what type should be used using the Fluent configuration:

```
public class QueryObjectType : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor
            .Field(query => query.GetFilesAndFolders(default!))
            .Type<ListType<FileOrFolderUnionType>>()
            .UseOffsetPaging<FileOrFolderUnionType>(options: new PagingOptions() { IncludeTotalCount = true })
            .UseProjection()
            .UseFiltering<FileOrFolder>()
            .UseSorting<FileOrFolderSortInputType>();
    }
}
```

The use of `object` does result into an exception when using a union type list within an object type. I will create a new issue for that and close this one.

**Comment by michaelstaib** [comment]
Thanks for your feedback on this... it will help other users ... we can also create a small post on this.
