### ISSUE TITLE
Flags enum still doesn't work

### ISSUE THREAD

**Issue by spqr911** [ChilliCream/hotchocolate#5513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

#5186  merged, but enum flags still doesn't work. @PascalSenn 
![image](https://user-images.githubusercontent.com/2879386/198299602-3e2b9b53-7e1b-4f3e-bc50-3a294d2a3f68.png)
![image](https://user-images.githubusercontent.com/2879386/198299674-2ca9621b-d0d5-4fd5-b810-47f154883a9d.png)
this is but

### Steps to reproduce

1. Exec following query: 
    [Flags]
    public enum Example { First, Second, Third }
    public Example Loopback(Example input)
    {
        var val = Example.Second | Example.First | Example.Third;
        return val;
    }

### Product

Hot Chocolate

### Version

13.0.0-preview7.0

**Comment by PascalSenn** [comment]
you have to enable the flags enum on the request builder:
```cshap
server.AddGraphQLServer()
  ...
 .ModifyOptions(x => x.EnableFalgsEnum = true);
```

The input is no longer a enum though but is an input object
```graphql
input ExampleFlagsInput {
  isFirst: Boolean
  isSecond: Boolean
  isThird: Boolean
  }
```

**Comment by spqr911** [comment]
> .ModifyOptions(x => x.EnableFalgsEnum = true);

![photo_2022-10-28_12-49-31](https://user-images.githubusercontent.com/2879386/198522119-930ae6cb-b046-4ff2-972c-48c115f26cc8.jpg)

I don't see EnableFlagsEnum - property. Why input doesn't support enum flags?  Should I need write manualy transformation from bools to enum?

**Comment by PascalSenn** [comment]
@spqr911  what version are you on?

**Comment by zyofeng** [comment]
preview 13 version seems to have lost this setting. Is there another way of enabling enum flags?

**Comment by VictorSDK** [comment]
It works for me in 13.5.1 once you add the `EnableFalgsEnums` setting
```
server.AddGraphQLServer()
  ...
 .ModifyOptions(x => x.EnableFalgsEnums = true);
```
