### ISSUE TITLE
question:  Is there  a way to Classify Query/mutation types  in gateway?

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#5519]
### Is your feature request related to a problem?

As time goes on，   the types of query and mutaion  becomes more and more.   They are crowded together in gateway,  I can't tell which Service they belong to.     how can i fix this?

### The solution you'd like

swagger

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
head over to slack and post the question there:
https://slack.chillicream.com
