### ISSUE TITLE
HC sets all fields in InputObject even those not in request

### ISSUE THREAD

**Issue by stanislav-a-frolov** [ChilliCream/hotchocolate#5523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was trying to implement partial updates via saving properties that were set while deserializing and ran into fact that HC sets values to all properties even those that was not in mutation request (unlike System.Text.Json). 

### Steps to reproduce

1. Make an input object with a property like, place breakpoint
`public string Property { get; set {
   _property = value;
   _propertyWasSet = true;
}}`
2. Make a mutation request without mentioned property set
3. Breakpoint hits

### Product

Hot Chocolate

### Version

12.11.1

**Comment by michaelstaib** [comment]
Yes, this is by design. If you want to track user intent use `Optional<T>`.

**Comment by nesherhh** [comment]
I don't want to reference HotChocolate.Abstraction in Application layer. Only project that references HotChocolate is Infrastructure layer.
Would be great if we could use own implementation of Optional<T> without referencing HotChocolate.

**Comment by nesherhh** [comment]
There is a delegate to create instance of input type at InputObjectTypeDefinition.CreateInstance that gets array with values. At the calling site there also "processed" variable with the information which property was actually transferred. CreateInstance delegate can get second parameter "processed", so we can use the information to create the instance.

**Comment by michaelstaib** [comment]
Where do you see the processed information? While this factory can be used we are not passing on the processedBuffer to the factory. The processed buffer is a rented object so we will not expose it to the user.

**Comment by michaelstaib** [comment]
Can you open a feature request and write down your use-case?
