### ISSUE TITLE
BindOperationsExplicitly is in documentation but doesn't exist in latest versions

### ISSUE THREAD

**Issue by bamancio-futura** [ChilliCream/hotchocolate#5553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IFilterInputTypeDescriptor.BindOperationsExplicitly  is only available in the V10 documentation. The interface doesn't have that method in the latest versions, thought.

### Steps to reproduce

1. Check IFilterInputTypeDescriptor for BindOperationsExplicitly

### Product

Hot Chocolate

### Version

12.15.0

**Comment by michaelstaib** [comment]
It is available... but only in the generic variant.

**Comment by michaelstaib** [comment]
Closing this issue since it works as specified and is available. The reason that the non-generic version does not have the bindings is that nothing is inferred and everything has to be specified. This is consistent with other descriptors like the `IObjectTypeDescriptor`.
