### ISSUE TITLE
CursorPaginationAlgorithm

### ISSUE THREAD

**Issue by ygo74** [ChilliCream/hotchocolate#5563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I don't understand the difference between cursor pagination sql query sent to the database and the offset pagination sql query

I saw that Middleware is well applied as I don't have the same type for my queries, I also saw that projection, ordering are well sent to the database

But according the difference between the two kinds of pagination <https://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination> I expect to have an additional filter to retrieve elements after the value specify in the query

```
# Expected sql output
Query output from Cursor pagination :
SELECT p."Name", p."Code"
FROM "Plugin" AS p
Where p."Code" >= "last cursor value"
ORDER BY p."Code"
LIMIT @__p_1 OFFSET @__p_0
```

Thanks to inform if I don't understand your cursor pagination behavior or to help me to successfully use this cursor

Best regards,

Yannick

### Steps to reproduce

1. Cursor pagination
```chsarp
 [UsePaging]
        [UseProjection]
        [UseSorting]
        [UseFiltering]
        public IQueryable<Plugin> SearchPlugins(ConfigurationDbContext dbContext,
                                                      IResolverContext ctx)
        {
            return dbContext.Plugins;
        }

```
```graphql
# Graphql query
query search {
 searchPlugins(first: 1 after: "MA==" order: {code: ASC}) {
   pageInfo {
     hasNextPage
     hasPreviousPage
     startCursor
     endCursor
   }
   edges
   {
     cursor
     node {
       name
       code
     }
   }
 } 
}
```

2. Query pagination
```chsarp
        [UseOffsetPaging]
        [UseProjection]
        [UseSorting]
        [UseFiltering]
        public IQueryable<Plugin> SearchPlugins(ConfigurationDbContext dbContext,
                                                      IResolverContext ctx)
        {
            return dbContext.Plugins;
        }
```

```graphql
# Graphql query
query search {
 searchPlugins(skip: 1 take: 1 order: {code: ASC}) {
   pageInfo {
     hasNextPage
     hasPreviousPage     
   }
   items {
     name
     code
   }
 } 
}
```

### Relevant log output

```shell
Query output from Cursor pagination :
SELECT p."Name", p."Code"
FROM "Plugin" AS p
ORDER BY p."Code"
LIMIT @__p_1 OFFSET @__p_0

Query output from Offset pagination
SELECT p."Name", p."Code"
FROM "Plugin" AS p
ORDER BY p."Code"
LIMIT @__p_1 OFFSET @__p_0
```

### Additional Context?

I used these packages in my project

```xml
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="12.15.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="HotChocolate.AspNetCore" Version="12.15.2" />
    <PackageReference Include="HotChocolate.Data" Version="12.15.2" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="12.15.2" />
    <PackageReference Include="HotChocolate.Types.CursorPagination" Version="12.15.2" />
    <PackageReference Include="HotChocolate.Diagnostics" Version="12.15.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.1" />
```

### Product

Hot Chocolate

### Version

12.15.2

**Comment by tobias-tengler** [comment]
The UsePaging middleware does paging using LIMIT AND OFFSET per default, because it doesn't know what to use as the cursor instead. So per default your cursors are just indices. If you want to do "real" cursor based pagination, it's up to you to implement. The section on offset vs. cursor based pagination is just meant as a primer, since how you implement the pagination logic is up to you and your data source. Checkout [this](https://chillicream.com/docs/hotchocolate/v12/fetching-data/pagination/#custom-pagination-logic) on how to customize the pagination logic.

**Comment by ygo74** [comment]
thank you for your answer!
Does it mean that startcursor and endcursor values are the skip values ?

**Comment by tobias-tengler** [comment]
Not sure what you mean by "skip values", but out of the box the cursors are the index of the data slice returned. If you request the first ten items the startcursor will be 0 and the endcursor 9, if you then fetch the next page sending the endcursor as the after value, the 9 will be decoded from the cursor and used as the offset in the query to the datasource. Hope that makes sense :)

**Comment by ygo74** [comment]
Hello, wait and see....

As I try to have a clean architecture implementation, in fact I will not use directly this middleware, expect maybe to offer a full search capacity for my domain entities...

According Microsoft documentation, https://learn.microsoft.com/en-us/ef/core/querying/pagination, I'm trying to use [MR.EntityFrameworkCore.KeysetPagination](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination) and [MR.AspNetCore.Pagination](https://github.com/mrahhal/MR.AspNetCore.Pagination) which seems easy to implement.

My last concerns are about paging arguments :
1) Is it possible to remove the argument named "last" without create a new UsePaging ObjectFieldDescriptorAttribute/ IObjectFieldDescriptor
    I have no mechanism to use this arguments in MR.EntityFrameworkCore.KeysetPagination and I would like to remove it

2) How can I access to PagingOptions to check the "first" value against MaxPageSize or to retrieve the default value DefaultPageSize ?

Thank you for your support !

best regards

**Comment by tobias-tengler** [comment]
1. You can set `AllowBackwardPagination` to `false`. [Reference](https://chillicream.com/docs/hotchocolate/v12/fetching-data/pagination/#pagingoptions)

> Please note that the pagination is implementing a spec. Removing these parameters breaks the spec and in turn might break clients expecting the spec to be correctly implemented.

2. I don't know if this is currently possible. The PagingOptions seem to [exist on the DescriptorContext](https://github.com/ChilliCream/hotchocolate/blob/959657f276325c33b1eb994173d74752528b0b9b/src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs#L187), but I don't know whether these are the global PagingOptions or the local ones and whether you can access them in the resolver at runtime. Hopefully someone else on the team knows the answer :)
