### ISSUE TITLE
Visual Studio with elevated privileges cannot manage the `Generated` folder. 

### ISSUE THREAD

**Issue by mfigueiredo-repay** [ChilliCream/hotchocolate#5564]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you start Visual Studio 2022 as an Administrator, the Strawberry Shake `Generated` folder acts like it is being cached.

If you delete the folder, or any part of its contents, from your project or solution, it gets immediately recreated without building the project. New mutations won't generate new classes, and Intellisense eventually ceases to recognize some of the already generated classes, seemingly in an unpredictable way.

The only way to resolve this issue is to close Visual Studio, delete the `Generated` folder, and start Visual Studio with standard user privileges.

### Steps to reproduce

1. Start Visual Studio as an Administrator
2. Open any project with a dependency on `StrawberryShake.CodeGeneration.CSharp.Analyzers`
3. Delete the `Generated` folder

The folder should be immediately recreated, and building the project or solution does not recreate it.

4. Any new mutations you create won't be generated when you rebuild your project
5. You should also be able to soon start experiencing issues with Intellisense not recognizing some of the generated types.

### Product

Strawberry Shake

### Version

12.15.0

**Comment by michaelstaib** [comment]
This is already fixed with the version 13 previews.
