### ISSUE TITLE
Is it possible to retrieve totalCount asynchronously?

### ISSUE THREAD

**Issue by dmitrykarnitski** [ChilliCream/hotchocolate#5568]
### Is your feature request related to a problem?

During app debugging, I noticed that totalCount retrieval as part of offest paging is synchronous. 
https://github.com/ChilliCream/hotchocolate/blob/4f49949fcc4532c87c2a5603696f9d55f54aca21/src/HotChocolate/Core/src/Types.OffsetPagination/QueryableOffsetPagingHandler.cs#L62

```
        if (IncludeTotalCount &&
            context.Selection.Type is ObjectType objectType &&
            context.Selection.SyntaxNode.SelectionSet is not null)
        {
            var selections = context.GetSelections(objectType, null, true);

            for (var i = 0; i < selections.Count; i++)
            {
                if (selections[i].Field.Name is "totalCount")
                {
                    totalCount = source.Count(); // <----- here
                }
            }
        }
```

The same is applicable to cursor pagination handler.

### The solution you'd like

Could you please make totalCount retrieval async if possible?

Suggestion:
`totalCount = await Task.Run(query.Count, cancellationToken).ConfigureAwait(false);`

P.S. I think it is also possible to apply one small optimization here: if totalCount is retrieved, there is no need to iterate through all the remaining selections.

Suggestion:
```
                if (selections[i].Field.Name is "totalCount")
                {
                    totalCount = source.Count();
                    break;
                }
```

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Do you want to do a PR?
