### ISSUE TITLE
Error code HC0051 is present twice

### ISSUE THREAD

**Issue by kstastny** [ChilliCream/hotchocolate#5585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error Code HC0051 is present twice in error codes

https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Abstractions/ErrorCodes.cs

Under `Schema`

```
        /// <summary>
        /// Type system members are not supported as runtime types
        /// </summary>
        public const string NoSchemaTypesAllowedAsRuntimeType = "HC0051";
```

and under `Pagination

```
        /// <summary>
        /// The maximum allowed items per page were exceeded.
        /// </summary>
        public const string MaxPaginationItems = "HC0051";
```

I expect that the code uniquely identifies the error.

### Steps to reproduce

1. none - please see issue description

### Product

Hot Chocolate

### Version

12.15.2

**Comment by michaelstaib** [comment]
Yes, that actually is an issue ... at the moment we do a runtime validation but we should move that into the request validation phase. I am adding this to the V13 backlog.

**Comment by kstastny** [comment]
excellent, thank you very much!
