### ISSUE TITLE
DataLoader for entities count

### ISSUE THREAD

**Issue by corinaivanov** [ChilliCream/hotchocolate#5592]
### Is your feature request related to a problem?

Hi!

In some scenarios of GroupedDataLoader usage, we need only the count, not entire list of related entities loaded in memory.
Let's take the following example:
public class Post 
{
    public int Id { get; set; }
    public string Test { get; set; } = default!;
    public List<Comment> Comments { get; set; } = default!;
}

public class Comment
{
    public int Id { get; set; }
    public int PostId { get; set; }
    public string Text { get; set; } = default!;
    public Post Post { get; set; } = default!;
}

In some cases we need to query for multiple posts, in which case we would like to have a batched request for comments, grouped by PostId. But actually instead of loading all comments into memory to get the count I would suggest to have a data loader that returns the count only.
The query for comments should be paged but since data loaders don't support paging, I think this could be a nice workaround. We could have a separate query for comments that supports paging and filtering, but we will flood the server with requests for each post and that's exactly what data loaders try to fix.

I tried to look into IBatchDispatcher API to see if this could be achieved but couldn't find any documentation on it.

### The solution you'd like

CountDataLoader<TKey> - a new data loader implementation that returns the count of entities that correspond to the given keys.

protected abstract Task<IReadOnlyDictionary<TKey, int> LoadCountAsync(
            IReadOnlyList<TKey> keys,
            CancellationToken cancellationToken);

### Product

Green Donut

**Comment by michaelstaib** [comment]
That would be the standard `BatchDataLoader`.
