### ISSUE TITLE
GraphQLName not respected on subscription result

### ISSUE THREAD

**Issue by AlwaysHC** [ChilliCream/hotchocolate#5603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Referring to this issue: https://github.com/ChilliCream/hotchocolate/issues/5574
I updated the repo https://github.com/AlwaysHC/HotChocolateNamingConvention
to show the problem with GraphQLName and the subscription result casing:

Mutation result is ok:
![image](https://user-images.githubusercontent.com/2215615/207061900-9bcc6036-d181-4c0b-bac6-249aebe7aa61.png)

Subscription result no:
![image](https://user-images.githubusercontent.com/2215615/207061967-e6f012ff-fd63-4812-bafa-72a0656679f0.png)

### Steps to reproduce

GRAPHQLNAME_NOT_Respected_WITH_Subscriptions is transformed in graphqlnamE_NOT_Respected_WITH_Subscriptions.

### Relevant log output

```shell
Input:

subscription {
  bookAdded {
    title
    GRAPHQLNAME_NOT_Respected_WITH_Subscriptions {
      name
    }
  }
}

Output:
{
  "data": {
    "bookAdded": {
      "title": "T3",
      "graphqlnamE_NOT_Respected_WITH_Subscriptions": {
        "name": "N3"
      }
    }
  }
}
```

### Product

Hot Chocolate

### Version

12.*

**Comment by AlwaysHC** [comment]
SDL:
type Mutation {
  setBook(title: String!): Book!
  addBook(book: BookInput!): Book!
}

type Subscription {
  bookAdded: Book!
}

input BookInput {
  title: String!
  GRAPHQLNAME_NOT_Respected_WITH_Subscriptions: AuthorInput!
}

type Book {
  title: String!
  GRAPHQLNAME_NOT_Respected_WITH_Subscriptions: Author!
}

type Author {
  name: String!
}

input AuthorInput {
  name: String!
}

**Comment by PascalSenn** [comment]
Hi @AlwaysHC  

Thanks for reporting this issue and for the perfect reproduction of the bug!

This is fixed in version 13 and is already available as previews. As it has to do with the underlying serialisation which was reworked in v13, this cannot be fixed in v12.
