### ISSUE TITLE
Auto-Stitching

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#561]
With the current version of schema stitching we still have to do a lot of work regarding the schema SDL in order to stitch together two schemas.

In order to make this easier and less error prone we want to introduce some kind of auto-stitching.

## Auto-Fetch Schema

First part of this story is that I do not want to provide the remote schema with a schema. #543

So instead of:

```csharp
serviceCollection.AddRemoteQueryExecutor(b => b
    .SetSchemaName("contract")
    .SetSchema(FileResource.Open("Contract.graphql"))
    .AddScalarType<DateTimeType>());
```

I just want to say: 

```csharp
serviceCollection.AddRemoteQueryExecutor(b => b
    .SetSchemaName("contract")
    .AddScalarType<DateTimeType>());
```

The stitching layer shall the fetch the schema via introspection from the remote schema. I still will need to provide scalars that are not defined in the spec.

## Auto-Merge Schema

The next part of this story is auto-merging a schema. The auto merge shall provide a simple root field merging. So, root fields from both schemas will be merges. In order to solve collisions we want an `ISchemaMergeCollisionResolver` which can be passed in.

The default collision resolver will merge like the following when the name of a type is used in both schemas:

- Input types that are completely equal (including enums) will be merged so that a single type exists in the stitched schema. 

- Input types that are not 100% equal or that are output types will be prefixed with the schema name. So, the [typeName] becomes [schemaName_typeName].

## Extend Types

In order to make the types more useful and provide a deep level of stitching it shall be possible to extend the types via the sdl.

```GraphQL
extend type Foo {
  bar: Bar @schema(name: "schemaName") @delegate(path: bar.bars)
}
```
 
## Builder Support

For the stitched schema we should provide a builder class that makes it easy to create the stitched layer.

```csharp
StichingBuilder.New()
    .AddRemoteSchema(foo)
    .AddExtensionFromFile("Extensions.graphql")
    .AddMergeHandler(next => (context, types) => next.Invoke(types))
    .RemoveField(new FieldReference("Type", "field"))
    .RenameField("schemaName", new FieldReference("Type", "field"), "newFieldName")
    .RenameField(new FieldReference("Type", "field"), "newFieldName")
    .Merge();
```

**Comment by MakcStudio** [comment]
Was it implemented? I am now faced with this problem and decide whether to write in C# or nodeJS

**Comment by michaelstaib** [comment]
@MakcStudio schema stitching is implemented. 

But this issue is about making it easier.

have a look at out documentation:
https://hotchocolate.io/docs/next/stitching

**Comment by michaelstaib** [comment]
Also if you need help, join our slack channel:

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg

**Comment by michaelstaib** [comment]
also we have an example here:
https://github.com/ChilliCream/hotchocolate-examples/tree/master/Stitching

**Comment by MakcStudio** [comment]
I figured out an example, but I can not understand. How do I create a resolver for my remote schema ?
For example, I need to process an incoming value from a remote schema, how can I do this?

I found an example 
```
Schema.Create(
        c => c.Map ("Query", "field", next => asynccontext =>
    {
        await _next(context);

        if (context.Result is string s)
        {
            context.Result = s.ToUpper();
        }
    }));
```

but it doesn't. Apparently something was updated

**Comment by MakcStudio** [comment]
ok, one moment

**Comment by OneCyrus** [comment]
i really like your approach and it should enable all our use cases i'm aware at the moment.

### Auto-Fetch Schema
- at first it confused us that we have to add our own HttpClient for contract resolving. I guess it would help if setting the contract would auto add an HttpClient factory for this contract by default. But the factory should still be extensible as we need to pass OAuth acces tokens through our hierarchy.
- not directly related to stitching. but please make the introspection logic accessible for other devs so we could build on it and e.g. create a class generator for a typed graphql client (similiar use case as the REST clients which are generated from swagger definitions)

### Auto-Merge Schema
that sounds perfect. i really like the reusing of types with the same structure across multiple remote schemas. and a conflict resolver should enable us to solve all those special issues we don't know yet. one thing i'm just thinking about which might happen in the future is if there are multiple services which are using stitching.

e.g. we have multiple graphql services which are stitched together like this:
```
A -> B -> C
 \-> D -> C 
```

from point of A, service C is inexisting. May be we could help A with an override so it's aware of C and could delegate the requests directly to C (and use a dataloader which works across B and D). this is probably not a use case which is very common. but could be a problem once stitching gets really big.

### Extend Types
while this is perfectly fine, a code first approach for extending types would be welcome.


thanks for discussing this in the open!

**Comment by michaelstaib** [comment]
> not directly related to stitching. but please make the introspection logic accessible for other devs so we could build on it and e.g. create a class generator for a typed graphql client (similiar use case as the REST clients which are generated from swagger definitions)

What do you mean by that? The introspection queries can always be executed, this is defined by the spec. 

Or do you mean that we should make the introspection c# types public? The introspection types basically use `ISchema` to query for types and `ISchema` is public. 

Or do you mean that we should make the introspection logic of the auto-stitching public?

**Comment by michaelstaib** [comment]
@OneCyrus just as a side note, I have also started to outline how the batching will work since you mentioned _DataLoader_ logic etc.

https://github.com/ChilliCream/hotchocolate/issues/524

**Comment by michaelstaib** [comment]
> while this is perfectly fine, a code first approach for extending types would be welcome.

What do you think about adding a `ObjectTypeExtension` this would be basically the extension representation in csharp.

Or we could introduce a `ObjectTypeExtensionBuilder` this might actually be more useful. The builder lets you describe what you want to add to a schema.

**Comment by OneCyrus** [comment]
> > if setting the contract would auto add an HttpClient factory for this contract by default.
> 
> I think we could just use the default HttpClient if none is defined for the schema. Though the call for the schema **could** fail do to missing auth tokens etc..
> 
> We could handle this with a custom exception pointing to the documentation and explaining that one should add a custom http client.

that sounds good and will make the library more approachable.

**Comment by OneCyrus** [comment]
> > not directly related to stitching. but please make the introspection logic accessible for other devs so we could build on it and e.g. create a class generator for a typed graphql client (similiar use case as the REST clients which are generated from swagger definitions)
> 
> What do you mean by that? The introspection queries can always be executed, this is defined by the spec.
> 
> Or do you mean that we should make the introspection c# types public? The introspection types basically use `ISchema` to query for types and `ISchema` is public.
> 
> Or do you mean that we should make the introspection logic of the auto-stitching public?

yes, make/leave the remote ISchema public. what we try to accomplish is something like [NSwag](https://github.com/RSuter/NSwag) or the kind of thing that [ASP.Net Core is building for 3.0](https://github.com/aspnet/AspNetCore/issues/4896) with the OpenAPI. basically generate graphql client/proxy for easy consumption of graphql APIs from c#.

**Comment by OneCyrus** [comment]
> > while this is perfectly fine, a code first approach for extending types would be welcome.
> 
> What do you think about adding a `ObjectTypeExtension` this would be basically the extension representation in csharp.
> 
> Or we could introduce a `ObjectTypeExtensionBuilder` this might actually be more useful. The builder lets you describe what you want to add to a schema.

sounds good. currently I'm not sure what would be the most logical way of defining it. while a builder would give the most flexibility it's probably also very verbose and complex. i really like the otherwise simplicity of the hotchocolate API but with still very deep extension points when needed. I'm sure you'll figure the perfect balance for this.

**Comment by michaelstaib** [comment]
> > > not directly related to stitching. but please make the introspection logic accessible for other devs so we could build on it and e.g. create a class generator for a typed graphql client (similiar use case as the REST clients which are generated from swagger definitions)
> > 
> > 
> > What do you mean by that? The introspection queries can always be executed, this is defined by the spec.
> > Or do you mean that we should make the introspection c# types public? The introspection types basically use `ISchema` to query for types and `ISchema` is public.
> > Or do you mean that we should make the introspection logic of the auto-stitching public?
> 
> yes, make/leave the remote ISchema public. what we try to accomplish is something like [NSwag](https://github.com/RSuter/NSwag) or the kind of thing that [ASP.Net Core is building for 3.0](https://github.com/aspnet/AspNetCore/issues/4896) with the OpenAPI. basically generate graphql client/proxy for easy consumption of graphql APIs from c#.

OK, we will leave that open. The remote schema can basically also be used as an underlying client for any generated type. 

But that again is another topic. :) 

Anyway, we will provide access to the schema. You can then use `ISchema` to explore the GraphQL schema with a strong c# API. We should have this available at the end of this week.

**Comment by OneCyrus** [comment]
What just came to my mind. Would it be possible to defer the schema introspection until the first call to HotChocolate? As all our GraphQL microservices are protected by JWT we can't just fetch the schema without a valid token. If we could defer the introspection until the first user with a valid token makes a GQL request, we wouldn't need special authentication handling.

**Comment by michaelstaib** [comment]
That is possible. In the end it depends on how you will put everything together. But we will make it possible.

**Comment by michaelstaib** [comment]
The `AddConflictResolver` will now be called `AddMergeHandler`. Merge handlers are chained (Chain of responsibility) not handled parts can be passed down the chain. 

It basically works like a field middleware delegate.

Each type will be annotated with a source directive that contains the original name of the type and the schema name from which the type stems. 

Is a type merged than the new type carries two source directives:

```GraphQL
enum Schema_B_Foo @source(name: "Foo", schema: "Schema_B") @source(name: "Foo", schema: "Schema_C") {
  BAR
  BAZ
  QUX
}
```

This way the merge process can keep track of all the type references that have to be amended in case a type has to be renamed.

**Comment by michaelstaib** [comment]
We will remove the schema directive and merge it with the delegate directive. This way the annotations are less error prone.

```GraphQL
type Foo @source(name: "Foo", schema: "Schema_B") {
  bar @delegate(name: "baz" schema: "Schema_B")
}
```

Furthermore, we will allow the source directive on more elements like a field or an enum value. This is optional and can be used to rename the field.

```GraphQL
type Foo {
  bar @delegate(name: "baz" schema: "Schema_B")
}
```

A field or an enum value can have different names in different schemas In the case the enum was merged. This kind of merge can only be done by writing a custom merge handler or by providing the sdl for it.

```GraphQL
type Foo @source(name: "Foo", schema: "Schema_B") @source(name: "Bar", schema: "Schema_C") {
  bar @delegate(name: "baz" schema: "Schema_B") @delegate(name: "foo" schema: "Schema_C")
}
```

**Comment by michaelstaib** [comment]
@OneCyrus we have integrated the lazy stitching functionality with 0.8.0-preview.5. Should be available any minutes. I have an example read demonstrating this. I will push that to our example repo as soon as the package is online.

**Comment by michaelstaib** [comment]
TODOs:

- [ ] BUG: There seems to be a conversion issue when DateTime variables are provided as a variable
- [ ] honor rename on input fields
- [ ] honor rename on arguments
- [ ] BindResolver does not work
- [ ] when merging types copy directives
- [ ] Fix Null Value Issue
- [ ] Fix Code Coverage
- [ ] A field or an enum value can have different names in different schemas In the case the enum was merged. This kind of merge can only be done by writing a custom merge handler or by providing the sdl for it.
- [ ] Ensure that all types are always handled

**Comment by michaelstaib** [comment]
I am closing this one since we have finished the feature.
