### ISSUE TITLE
Add ability to redact operations and results

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/hotchocolate#5610]
### Is your feature request related to a problem?

I would like to log GraphQL operations sent to an API and responses from the API for operational purposes and data analytics. However, some arguments and fields are sensitive, so the values should be redacted prior to being logged. I would like a way to mark arguments and fields as "sensitive" on an individual basis and have a rewriter which redacts all the sensitive data in a query/mutation.

I have tried to do this with a custom directive but ran in to problems. When I extend `QuerySyntaxRewriter` and apply it to `IRequestContext.Operation.Definition`, the latter has no schema information, so when it encounters a syntax node, there is no way to check whether that syntax node corresponds to a field/argument with a "sensitive" directive. The only mildly useful information is argument/field name, but redacting on this basis is very coarse and would result in false positives. It would also mean the code deciding whether to redact a field/argument is very distant from the field/argument definition itself, reducing maintainability.

### The solution you'd like

The ideal solution would be either a "Sensitive" GraphQL directive or a CLR attribute which can be applied to, at the very least, fields and arguments of type `String` or `String!`. There would be a syntax rewriter which could rewrite queries/mutations to redact the sensitive data:
- Any sensitive field/argument whose value is a literal would be redacted to a fixed string, e.g. `***`.
- If a variable is passed to a sensitive field/argument, then that variable's value would be redacted.

There would also be (with lower priority) a rewriter for results. Sensitive fields would have their returned values redacted.

Any application of the Sensitive directive/attribute to a schema element where it has no effect would result in a warning/error, to guard against accidentally leaking sensitive data.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
I think this belongs into a community package or into userland not into the core library as I can think of a dozen variations on how people want to have that. There are also other areas this leads into like auditing of data that has be exposed to certain users and so on. 

I am closing this issue as we will not pick this up anytime soon.

**Comment by AlexKubiesa** [comment]
In that case, do you have any suggestions on how one would implement something like this? The logging is happening inside a custom `ExecutionDiagnosticEventListener` subclass, so we have access to `IRequestContext`. Here are the things I tried, all with variants of the Sensitive directive described above:
1. Traversing the structure of `IRequestContext.Operation.GetRootSelectionSet()`. Unfortunately there is no OOTB visitor/walker for this, and traversing the structure requires me to provide a lot of type information which is not easily accessible at this point. Continuing with this approach feels like it would be duplicating a lot of the core query processing logic. There is a method `Operation.Print` which might work if there was a way to inject custom rewriting/serialization into it, but currently there isn't.
2. Traversing `IRequestContext.Operation.Definition`. There are OOTB visitors/walkers for this, but using it is impossible because there is no schema information here, only syntax. This would be the best approach if it worked, because it does granular redaction (unlike (3)) and operates on the original operation, not a compiled form (unlike (2))
3. Field middleware which detects whether _some_ part of the operation has sensitive data so we can at least redact the whole operation in that case. This is impossible because I want to apply it to arguments and input fields, and field middleware doesn't work for those.

**Comment by michaelstaib** [comment]
Regarding arguments there are a couple of ways:
https://www.youtube.com/watch?v=yJ-2kxrs2TU
https://www.youtube.com/watch?v=4n0dYBJ4SDA

Each video shows a different approach.

To implement this are a couple of pieces. But all possible, you can extend each part of Hot Chocolate.
I think I would first identify in which area sensitive information can be, as I would not want to cause perf degradation for  things that cannot have such an issue.

Next you could use descriptor attributes or type interceptors to annotate to these things middleware or input formatter.

You could also traverse and rewrite the result structure ... not sure if I would do that actually... really depends on a lot of factors. If you want to access the request context in a mutable way use a request middleware.
https://www.youtube.com/watch?v=Ut33sSTYmgw

**Comment by michaelstaib** [comment]
Walking you through on how to implement such a thing is a lot of work.  You can join us on slack.chillicream.com and ask questions there. The links I posted are to our youtube channel where I show a lot of low level APIs of HC to change the behavior.

If all the free resources are not enough, we are also offering consulting:
https://chillicream.com/services/advisory

**Comment by michaelstaib** [comment]
BTW ... in Hot Chocolate 13 we have the new `ResultFormatterDefinition` which essentially is a sync middleware. Meaning you can use those on fields that are inlinable to add formatting logic like yours. This has a lot less impact on perf since these resolvers can be folded into their parent.
