### ISSUE TITLE
Access the list of subsccription's topics

### ISSUE THREAD

**Issue by AlwaysHC** [ChilliCream/hotchocolate#5614]
### Is your feature request related to a problem?

For a "spatial" application, I need to access the list of active topics that my users subscribed: as topic a use longitude and latitude.

### The solution you'd like

I'd like to filter for the topic list and send notifications only to some subscribers

### Product

Hot Chocolate

**Comment by AlwaysHC** [comment]
At the moment I'm storing the list of topics in a separate data structure, but it's like I'm duplicating data

**Comment by michaelstaib** [comment]
This is quite difficult with the GraphQL model as there is no client relationship in the GraphQL spec.

Technically you could achieve that with some context data on the request and the socket hooks that we have. But this is something that you have to do in your solution as it would add a lot of overhead to subscriptions that do not use this kind of addressing.

**Comment by AlwaysHC** [comment]
I found 
    private readonly ConcurrentDictionary<object, IEventTopic> _topics =
        new ConcurrentDictionary<object, IEventTopic>();
in "public class InMemoryPubSub"
There is a way to make it available?

**Comment by michaelstaib** [comment]
No, the pubsub implementations are only providers and have an immem representation of a single node. The best way to do it is as I stated and aggregate it on redis or somewhere else.
