### ISSUE TITLE
Filters do not work if "Scope" is not consistently specified.

### ISSUE THREAD

**Issue by strue36** [ChilliCream/hotchocolate#5622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried to follow the instructions in the documentation for using MongoDB filtering alongside IQueryable/IEnumerable.

>To use MongoDB filtering alongside with IQueryable/IEnumerable, you have to register the MongoDB convention under a different scope. You can specify the scope on the schema builder by executing AddMongoDbFiltering("yourScope"). You then have to specify this scope on each method you use MongoDb filtering: [UseFiltering(Scope = "yourScope")] or UseFiltering(scope = "yourScope")

I have used AddMongoDbFiltering("mongo") to selectively apply MongoDB filtering to specific queries, but if I have string fields in the Mongo and non-Mongo types that are being filtered I get an error.  Each filtering convention is generating a type named StringOperationFilterInput. When these are registered by the TypeRegistry the two filter types have different names mongo_StringOperationFilterInput and StringOperationFilterInput, but when Register(NameString typeName, RegisteredType registeredType) is called with the unscoped StringOperationFilterInput it throws a duplicate type name error. It looks like the mongo scoped StringOperationFilterInput has already been registered in the DiscoverTypes() step of TypeInitializer.Initialize() without the "mongo_" added to the name so when we attempt to do the same in CompleteName() we end up with a duplicate.

### Steps to reproduce

In HotChocolate.Data.Tests.IntegrationTests add the following.

```C#
public class MultipleScopes
{
    [UsePaging]
    [UseProjection(Scope = "Foo")]
    [UseFiltering(Scope = "Foo")]
    [UseSorting(Scope = "Foo")]
    public IQueryable<Book> GetBooks() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();

    [UsePaging]
    [UseProjection(Scope = "Bar")]
    [UseFiltering(Scope = "Bar")]
    [UseSorting(Scope = "Bar")]
    public IQueryable<Book> GetBooksWithDifferentScope() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();
}

public class DefaultAndNamedScope
{
    [UsePaging]
    [UseProjection(Scope = "Foo")]
    [UseFiltering(Scope = "Foo")]
    [UseSorting(Scope = "Foo")]
    public IQueryable<Book> GetBooks() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();

    [UsePaging]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Book> GetBooksWithNoScope() => new[]
    {
    d = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();
}
```

Alongside the following new tests.

```C#
[Fact]
public async Task CreateSchema_OnDefaultAndNamedScope()
{
    // arrange
    var executor = await new ServiceCollection()
                         .AddGraphQL()
                         .AddFiltering()
                         .AddSorting()
                         .AddProjections()
                         .AddFiltering("Foo")
                         .AddSorting("Foo")
                         .AddProjections("Foo")
                         .AddQueryType<DefaultAndNamedScope>()
                         .BuildRequestExecutorAsync();

    // act
    var result = await executor.ExecuteAsync(
        @"
            {
                booksWithNoScope(where: { title: {eq: ""BookTitle""}}) {
                    nodes { title }
                }
            }
            ");

    // assert
    await Snapshot
          .Create()
          .Add(result, "Result:")
          .Add(executor.Schema, "Schema:")
          .MatchAsync();
}

[Fact]
public async Task CreateSchema_OnMultipleNamedScopes()
{
    // arrange
    var executor = await new ServiceCollection()
                         .AddGraphQL()
                         .AddFiltering("Foo")
                         .AddSorting("Foo")
                         .AddProjections("Foo")
                         .AddFiltering("Bar")
                         .AddSorting("Bar")
                         .AddProjections("Bar")
                         .AddQueryType<MultipleScopes>()
                         .BuildRequestExecutorAsync();

    // act
    var result = await executor.ExecuteAsync(
        @"
            {
                booksWithDifferentScope(where: { title: {eq: ""BookTitle""}}) {
                    nodes { title }
                }
            }
            ");

    // assert
    await Snapshot
          .Create()
          .Add(result, "Result:")
          .Add(executor.Schema, "Schema:")
          .MatchAsync();
}
```

CreateSchema_OnMultipleNamedScopes passes but CreateSchema_OnDefaultAndNamedScope gives this error

>The name `BookFilterInput` was already registered by another type. (HotChocolate.Data.Filters.FilterInputType<HotChocolate.Data.Book>)

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

HotChocolate.SchemaException
For more details look at the `Errors` property.

1. The name `BookFilterInput` was already registered by another type. (HotChocolate.Data.Filters.FilterInputType<HotChocolate.Data.Book>)

   at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeRegistry.cs:line 218
   at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 235
   at HotChocolate.Configuration.TypeInitializer.<CompleteNames>b__22_0(RegisteredType type) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 194
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 427
   at HotChocolate.Configuration.TypeInitializer.CompleteNames() in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 194
   at HotChocolate.Configuration.TypeInitializer.Initialize() in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 88
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Setup.cs:line 192
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Setup.cs:line 57
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Create.cs:line 16
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Create.cs:line 32
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 352
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 282
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 86
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken) in D:\Repositories\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 62
   at HotChocolate.Data.IntegrationTests.CreateSchema_OnDefaultAndNamedScope() in D:\Repositories\hotchocolate\src\HotChocolate\Data\test\Data.Tests\IntegrationTests.cs:line 630
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

### Additional Context?

Initial issue found in 12.5.0 but reproduced on a77b7d613a9a82cea3520c7d3160e22c24cc0614

### Product

Hot Chocolate

### Version

a77b7d613a9a82cea3520c7d3160e22c24cc0614

**Comment by strue36** [comment]
This is a separate issue to #5228 but the same error is reported by @jkears in the discussion.

The workaround is to make sure that all filters have scopes if any filters have scopes.

**Comment by michaelstaib** [comment]
It's not actually a bug. What scope does is branching the typeset. The assumption that we made is that two database systems might have different operation capabilities. This would mean we need more than one type to represent the filter capabilities of such a datasource.

We will do a major overhaul of the data package towards the middle of next year. In general I think what users want is a stable set of operations instead of getting the most features out of any provider. Thus there should really only be one `StringOperationFilterInput`.

I am closing this issue as it works as designed. But we will have a look at these things when we head into next year.

CC @PascalSenn

**Comment by strue36** [comment]
@michaelstaib can this be marked as completed? The issue that I am treating as a bug is that if you add 2 types of filtering, one with a scope and the other without, you get a cryptic error that doesn't point you at the real issue, namely

>The name `BookFilterInput` was already registered by another type. (HotChocolate.Data.Filters.FilterInputType<HotChocolate.Data.Book>)

The docs currently say

>To use MongoDB filtering alongside with IQueryable/IEnumerable, you have to register the MongoDB convention under a different scope. You can specify the scope on the schema builder by executing AddMongoDbFiltering("yourScope"). You then have to specify this scope on each method you use MongoDb filtering: [UseFiltering(Scope = "yourScope")] or UseFiltering(scope = "yourScope")

I read this as

>If you are using `AddFiltering()` to use IQueryable filtering, and wish to also use MongoDB filtering, you need to specify a scope in `AddMongoDbFiltering("yourScope")` and any `UseFiltering` attributes.

If this is incorrect then the documentation should state that once a scope is specified in one location, it must be specified everywhere. Ideally there would be a check in the startup phase that throws an error telling you that you have not specified a scope and this is required.

Given that the exact same filter type can be registered under two different scopes and work fine (see `CreateSchema_OnMultipleNamedScopes`). It is not currently obvious that this should cause problems when the scope is `null`. I'm surprised if this is the intended behaviour.

I agree with you that there should only be one `StringOperationFilterInput`. This is the next thing I was going to raise as I feel that it leaks implementation details into the schema. I currently get some data from a Mongo database and some from a REST API, but don't want users to know that fact, or for the schema to change if I change this implementation. I think that currently the best approach leaves you with a `SourceA_BookFilterInput` and a `SourceB_BookFilterInput`. Is there an issue or discussion to comment on the plans for the overhaul of the data package?

**Comment by michaelstaib** [comment]
but this is what it states in the docs:
> You then have to specify this scope on each method you use MongoDb filtering: [UseFiltering(Scope = "yourScope")] or UseFiltering(scope = "yourScope")

You have to specify it on each method where you want to use it.

**Comment by michaelstaib** [comment]
Do you mean this one failes?

```csharp
public class DefaultAndNamedScope
{
    [UsePaging]
    [UseProjection(Scope = "Foo")]
    [UseFiltering(Scope = "Foo")]
    [UseSorting(Scope = "Foo")]
    public IQueryable<Book> GetBooks() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();

    [UsePaging]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Book> GetBooksWithNoScope() => new[]
    {
    d = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();
}
```

**Comment by strue36** [comment]
Yes, GetBooks and GetBooksWithNoScope would work independently but when added to the same schema they cause an error.

Doing this with 2 separate scopes (the other test) works fine.

**Comment by strue36** [comment]
The point here being that I'm not specifying the `"Mongo"` scope on methods that I don't want to use Mongo filtering on. Because there is no scope specified I get the duplicate type registration error. If I change my unscoped `AddFiltering()` in Startup.cs to `AddScope("NotMongo")` and add that scope to all the remaining filters it works, but

a) It isn't clear that this is required
b) Every FilterInput is then called Mongo_FilterInput or NotMongo_FilterInput which leaks the implementation detail (separate issue I think)

**Comment by Healios** [comment]
Something isn't working quite as expected here... I was encountering the same issue as @strue36, and I've narrowed down the issue to the order of the queries.

Let me explain using @strue36's example code.

**Example 1:**
The following example will cause an error (see "Relevant Log Output" in issue).
```
public class Query
{
    [UsePaging]
    [UseProjection(Scope = "Foo")]
    [UseFiltering(Scope = "Foo")]
    [UseSorting(Scope = "Foo")]
    public IQueryable<Book> GetBooks() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();

    [UsePaging]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Book> GetBooksWithNoScope() => new[]
    {
    d = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();
}
```

**Example 2:**
The following example will work as expected.
```
public class Query
{
    [UsePaging]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IQueryable<Book> GetBooksWithNoScope() => new[]
    {
    d = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();

    [UsePaging]
    [UseProjection(Scope = "Foo")]
    [UseFiltering(Scope = "Foo")]
    [UseSorting(Scope = "Foo")]
    public IQueryable<Book> GetBooks() => new[]
    {
        new Book { Id = 1, Title = "BookTitle", Author = new Author { Name = "Author" } }
    }.AsQueryable();
}
```

Surely this is not expected behaviour. I feel like there should be a way for the "engine" to handle this issue when building the schema.
