### ISSUE TITLE
Update GraphiQL Middleware

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#564]
Update the GraphiQL middleware with the new version of GraphiQL.

**Comment by mikelee516** [comment]
I'm assuming this issue should be closed as per the comments in #587 ?  I ask because I'm looking to contribute and this was tagged as "good first issue" - thanks!

**Comment by michaelstaib** [comment]
Hi @mikelee516,

yeah, this one should be closed :)

But there is still lots to contribute. Are you on your slack channel? If you like we can discuss things there.
