### ISSUE TITLE
MapGraphQLHttp options missing Tool property

### ISSUE THREAD

**Issue by wondering639** [ChilliCream/hotchocolate#5656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `MapGraphQL()` I can set an option to disable Hot Chocolate:

    app.MapGraphQL().WithOptions(new HotChocolate.AspNetCore.GraphQLServerOptions
    {
        Tool = {
            Enable = app.Environment.IsDevelopment()
        }
    });

When using directly `MapGraphQLHttp` then there is no `Tool` option/property.

    app.MapGraphQLHttp("/graphql").WithOptions(new HotChocolate.AspNetCore.GraphQLHttpOptions
    {
        // missing Tool property here - note that MapGraphQLHttp() includes Banana Cake Pop!
    }); 

### Steps to reproduce

see bug description

### Product

Hot Chocolate

### Version

12.16.0

**Comment by tobias-tengler** [comment]
That's not a bug, it's intentional. MapGraphQL includes our GraphQL IDE Banana Cake Pop, which can be configured through the Tool option. MapGraphQLHttp doesn't include the IDE, that's why you don't have the option to configure it.
