### ISSUE TITLE
Parent ID is not provided in type extension when it is not part of the query

### ISSUE THREAD

**Issue by apazureck** [ChilliCream/hotchocolate#5660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am not sure, if it is a bug per se, but when using `[Parent]` in a type extension, then the ID is default, if it is not part of the query. Maybe it is also to be expected behavior, at least for me it was not expected and about an hour of google searches did not bring up the problem (also I did not find anything in the slack channel).

For example:

```graphql
query myQuery {
  user(id: 2) {
    id # remove this and the type extension will not receive the id.
    firstName
    lastName
    userTransactionCounts(itemIds: [1, 2, 3]) {
      item {
        name
      }
      count
    }
  }
}
```

The resolver on the type extension of user:

```csharp
public async Task<TransactionCountResult[]> GetUserTransactionCounts(
        [Parent] User user,
        [Service] ITransactionService transactionService,
        int[] itemIds,
        DateTime? until)
    {
        if (user.Id == 0)
            throw new ArgumentException("ID is not set. Put the ID in the query, so it can be resolved");
            // This will throw, if the id is left out on the parent
```

Maybe I misunderstood something here and it is possible. At least I cannot find anything in the documentation.

### Steps to reproduce

1. Create a query which does not contain the ID of the type
2. Use the ID in a type extension using the parent
3. Check the id for default and throw

**Expected result**

1. The query gets resolved
2. The resolver on the extension method gets called
3. No exception is thrown

**Actual result**

1. The query gets resolved
2. The resolver on the extension method gets called
3. The exception is thrown

### Product

Hot Chocolate

### Version

12.16.0

**Comment by tobias-tengler** [comment]
I'm assuming you are projecting in your `user` field resolver, so the Id will not be retrieved from the database, if not queried. If it's essential information you should mark it to always be retrieved: https://chillicream.com/docs/hotchocolate/v12/fetching-data/projections/#always-project-fields

**Comment by apazureck** [comment]
Yes, you are right. I know about that (now) :) - after being confused at first. I did not find anything, so I thought I'll ask. So thanks for the quick answer and I hope it will help someone else stumbling over that problem.

Is it somehow possible to tell HC that it should always project the ID (or any specific property) when the resolver of an extended type is called?

Because now I just can opt-in to always resolve the specific property and causing overfetching on my DB, or the user of the API has to have the knowledge about what to specify to be resolved in order to get the correct response from the server. Thus, the API user needs to have internal knowledge about the API.

Or maybe it is not the right approach and I should use stitching or something in this case?

So maybe it would be a viable solution to tell what to autoproject on the parent:

```csharp
public async Task<TransactionCountResult[]> GetUserTransactionCounts(
       [Parent(nameof(User.Id), nameof(User.UserGroupId))] User user,
// ...
```
