### ISSUE TITLE
Add @defer support to the execution engine.

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#59]
https://www.apollographql.com/docs/react/features/defer-support.html

https://blog.apollographql.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07

https://www.reddit.com/r/graphql/comments/8wv1da/status_on_graphql_batch_stream_defer_live_etc/

https://github.com/facebook/relay/issues/288

https://github.com/facebook/relay/issues/2554

https://github.com/facebook/relay/issues/2194

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream

System.Net.Http.MultipartContent

**Comment by cgatian** [comment]
This would seriously blow people's minds.

**Comment by michaelstaib** [comment]
This is coming in April

**Comment by cgatian** [comment]
Dont tease me! April 1st?

**Comment by michaelstaib** [comment]
We are aiming at April 14 or the week after that.

**Comment by michaelstaib** [comment]
So, after talking to people on the relay channel I have changed my perspective on this one.... the Apollo way for @defer seemed so messy. But talking to guys on the relay channel it seems that relay will go a different way and instead will provide @defer on fragments rather than fields.

This makes much more sense and allows for much more powerful ways to delay fields. Moreover, with this we would not be forced to make a field nullable in order to be able to defer it.

**Comment by michaelstaib** [comment]
en_js  [1 day ago]
Thanks for the extra context. We're currently experimenting with "native" support for @defer and @stream in our internal GraphQL server and our GraphQL clients (Relay and our native client). As we did with GraphQL itself and our subscriptions RFC/spec we plan to get experience using the approach and validating it at scale before proceeding with any RFC.

Our current approach is that @defer can be used with inline fragments or fragment spreads while @stream can be used on plural fields. We don't have a publicly available version of a spec because, as noted, we aren't ready to proceed with an RFC yet. If you're curious you can look at the defer/stream-related tests and transforms, but again, just beware that they're subject to change.

**Comment by michaelstaib** [comment]
https://github.com/lilianammmatos/graphql-js/pull/1

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-js/pull/2318

https://github.com/graphql/graphql-js/pull/2319

**Comment by michaelstaib** [comment]
Facebook will start moving this into the spec.

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-spec/pull/679

**Comment by Jan080906** [comment]
hello any update on @defer? is it going to be in version 11.0.0?

**Comment by PascalSenn** [comment]
Still not spec'ed
https://github.com/graphql/graphql-spec/issues/704

**Comment by michaelstaib** [comment]
This one is now merged and released
