### ISSUE TITLE
Client Code Generator

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#590]
We are more thinking about a tool where you can really select and design what kind of client you want. You basically should be able to pick parts of the schema and than even extend the schema with parts that are not there. For example you could map the local file system into the schema etc… basically schema stitching on the client. The file system is a bad example really :slightly_smiling_face: But think a about a local storage like a database. This way you can access both local storage and services through one strongly typed interface.

We would than generate a client on that schema and you would have a client API that looks and functions like you want it to… This idea came to me while exploring what relay can do with the client schema.

**Comment by DonaldWebb** [comment]
Apollo does similar with the idea of LocalState. 
It does end up as you said just schema stitching.
Apollo adds an @client directive and client resolvers that can return data before/after hitting server. 
Effectively it adds a cut down gql server on the client.

From there its easy to use the schema transform tools apollo-tools, graphql-code-generator to create client libraries, interfaces etc.

**Comment by michaelstaib** [comment]
@DonaldWebb yeah, relayjs does something similar.... we will start on this after the summer. At the moment we are still focused on the backend and on the new tooling that is coming with version 9.

**Comment by michaelstaib** [comment]
This is basically implemented and will be related with version 11.
