### ISSUE TITLE
Tutorial Authentication

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#595]
https://www.howtographql.com/graphql-js/6-authentication/

**Comment by dominik4545** [comment]
It would be great to have this tutorial in place 👍

**Comment by tobias-tengler** [comment]
Closing this since Authentication and Authorization have now been documented.

https://chillicream.com/docs/hotchocolate/security/authentication
https://chillicream.com/docs/hotchocolate/security/authorization

Feel free to re-open if I missed the point of the issue. :)
