### ISSUE TITLE
Authorization using Annotation-based approach not working as expected

### ISSUE THREAD

**Issue by Tomasz-Cypser** [ChilliCream/hotchocolate#5990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Following the discussion on slack channel with Pascal Senn, per his suggestion I have created this issue.

Setting up authorization using the Annotation-based approach in HotChocolate does not work as I would expect it to work. The @authorize directive is not visible in the schema definition,

The schema output that does not mention @authorize directive:
```
directive @export(as: String) on FIELD

type Query {
  objects(pageSize: Int, paginationToken: String): ObjectsPagedResult!
}

enum ApplyPolicy {
  BEFORE_RESOLVER
  AFTER_RESOLVER
  VALIDATION
}

interface IPagedResult {
  pageSize: Int!
  paginationToken: String
}

type ObjectsPagedResult implements IPagedResult {
  pageSize: Int!
  paginationToken: String
  items: [Object!]!
}

type Object {
  id: ID!
  created: DateTime!
}

"""
The `DateTime` scalar represents an ISO-8601 compliant date time type.
"""
scalar DateTime

```

Additionally, when authorization fails, I get a '401' status code response, while the documentation here: https://chillicream.com/docs/hotchocolate/v13/security/authorization specifies that it should be '200'.

Environment:

HotChocolate version: 13.0.5
Operating system: Windows 11
.NET version: .net 6.0

### Steps to reproduce

I have isolated the code from my project with only the relevant configuration, using version 13.0.5 of HotChocolate, it can be reproduced in the following repo https://github.com/Tomasz-Cypser/GraphQLAuthorizationTest/.

### Additional Context?

The project is set to run in AWS Lambda, the issue is reproducible on both the local run and in AWS.

### Version

13.0.5

**Comment by michaelstaib** [comment]
Where did you get the first schema from? BCP? If so than its correct that it does not have any authorize directive as BCP generates an SDL based on the introspection. The introspection has no capabilities to expose type system directives,

**Comment by twirlse** [comment]
@michaelstaib Could you please ellaborate a bit more?
Just following the tutorial on the site I'm having similar problems as @Tomasz-Cypser  (authorize directive not present in schema, 401 response code instead of 200). Is there a sample project that one can you where everything is working as described in here (https://chillicream.com/docs/hotchocolate/v13/security/authorization)?
