### ISSUE TITLE
Pagination issue in local schema when using stitching

### ISSUE THREAD

**Issue by DmitriySav** [ChilliCream/hotchocolate#5997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When I use pagination on a local schema connected to the gateway, I get edges and nodes equal to null. However, when using only one graph without the gateway, everything is fine. I receive results with the gateway only if the requested number of items is divisible by 4.

It seems that the problem might be in ValueCompletion.List when you rent 4 items for an enumerable result.

Query example:

```
[ExtendObjectType(OperationType.Query)]
public class Query
{
    [UsePaging(ProviderName = ServiceConstants.SchemaPagingProviderName)]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public IExecutable<Category> GetCategories([Service] IMongoCollection<Category> collection)
        => collection.AsExecutable();
}
```

Local schema registration example:

 ```
collection.AddGraphQLServer(ServiceConstants.SchemaName)
            .ConfigureSchemaServices(sc =>
            {
                sc.AddSingleton<INamingConventions, NameConvention>();
            })
            .AddQueryType()
                .AddTypeExtension<Activities.GetCategories.Query>()
                .AddTypeExtension<Activities.GetCategory.Query>()
            .AddMutationType()
                .AddTypeExtension<Activities.CreateCategory.Mutation>()
            .AddInstrumentation()
            .AddMongoDbPagingProviders(ServiceConstants.SchemaPagingProviderName)
            .AddMongoDbProjections()
            .AddMongoDbFiltering()
            .AddMongoDbSorting()
            .SetPagingOptions(new PagingOptions()
            {
                IncludeTotalCount = true
            });
```
            
Gateway registration example:

```
builder.Services.AddGraphQLServer()
    .AddLocalSchema(schemaName: Categories.ServiceConstants.SchemaName)
    .AddLocalSchema(schemaName: Vendors.ServiceConstants.SchemaName)
    .AddDiagnosticEventListener<ErrorLoggingDiagnosticsEventListener>()
    .ModifyRequestOptions(modify: o => o.IncludeExceptionDetails = true)
    .AddTypeExtensionsFromResource(
        assembly: typeof(Vendors.ServiceConstants).Assembly,  
        key: Vendors.ServiceConstants.StitchingFilePath)
    .AddTypeExtensionsFromResource(
        assembly: typeof(Categories.ServiceConstants).Assembly,
        key: Categories.ServiceConstants.StitchingFilePath);   
```         
        
 Query:
 
 ```
query{
  categories(first: 5) {
    nodes {
      id
      vendorId
    }
    edges{
      node {
        id
        name
        vendorId
      }
    }
    totalCount
    pageInfo {
      startCursor
    }
  }
}
```

Result:

```
{
  "data": {
    "categories": {
      "nodes": null,
      "edges": null,
      "totalCount": 5,
      "pageInfo": {
        "startCursor": "MA=="
      }
    }
  }
}
```
        

### Steps to reproduce

1. Create a local schema with pagination, filtering, sorting, and projections
2. Register the local schema with the provided example in description
3. Register the gateway with the provided example in description
4. Execute a query with pagination on the local schema connected to the gateway
5. Observe that the edges and nodes in the response are null
6. Test with the number of items requested being divisible by 4 (e.g., 4, 8, 12), and observe that the gateway returns results in such cases (db should contains this amount of items)

### Additional Context?

Result before CompleteValue invocation in ResolverTask

![image](https://user-images.githubusercontent.com/42099709/228286331-68a81280-fff7-4869-8e7e-c61134e91621.png)

CompletedValue with empty nodes and edges

![image](https://user-images.githubusercontent.com/42099709/228286807-d50c3075-340a-4f44-b2a6-f0502cb5778c.png)

### Version

13.0.5

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.
