### ISSUE TITLE
`Method not found` after update to `MongoDB.Driver 2.19+` where Skip, Limit become Int64

### ISSUE THREAD

**Issue by reeloadead** [ChilliCream/hotchocolate#6042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

There is an runtime error after update from [MongoDB.Driver 2.18](https://github.com/mongodb/mongo-csharp-driver/blob/v2.18.x/src/MongoDB.Driver/IAggregateFluent.cs) to [MongoDB.Driver 2.19](https://github.com/mongodb/mongo-csharp-driver/blob/v2.19.x/src/MongoDB.Driver/IAggregateFluent.cs) due to a signature of the methods `Skip()`, `Limit()` was changed:
```
Skip(int skip) => Skip(long skip)
Limit(int limit) => Limit(long limit)
```

see [jira.mongodb CSHARP-4445: Support 64-bit values for Skip and Limit/Take](https://jira.mongodb.org/browse/CSHARP-4445):

### Steps to reproduce

1. Query with pagination
```
    [UsePaging]
    public IExecutable<DataModel> GetData()
```
2. Update to `MongoDB.Driver 2.19`
3. Runtime error when calling `GetData()` query

### Relevant log output

```shell
"message": "Method not found: 'MongoDB.Driver.IAggregateFluent`1<System.__Canon> MongoDB.Driver.IAggregateFluent`1.Limit(Int32)'.",
```

### Version

12.18.0

**Comment by michaelstaib** [comment]
That is a breaking change in the contract ... not really a bug on our side... We will create a new package version for 13.1

**Comment by vhatsura** [comment]
@michaelstaib, is there any chance to backport the Mongo Driver version bump to 12.x?

**Comment by michaelstaib** [comment]
This is now fixed
