### ISSUE TITLE
DateTime over variables issue

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#607]
There seems to be a conversion issue when DateTime values are provided as a variable

**Comment by GraemeF** [comment]
Can confirm this - the value gets converted from a `DateTime` (or `DateTimeOffset`?) to a string with the default format which then makes it ambiguous when parsed back to a `DateTime`/`DateTimeOffset` again later.

**Comment by michaelstaib** [comment]
@GraemeF thanks for the feedback...

I have pined down the issue and will issue a fix soon.

**Comment by michaelstaib** [comment]
@GraemeF we are moving this to out patch release that is coming on the 31st of March.

**Comment by michaelstaib** [comment]
This one is now fixed with #664
