### ISSUE TITLE
Non‐null type field with a default value is required although it should not be

### ISSUE THREAD

**Issue by etaletovic** [ChilliCream/hotchocolate#610]
**Describe the bug**
According to: https://facebook.github.io/graphql/June2018/#sec-Input-Object-Required-Fields
"An input field is required if it has a non‐null type and does not have a default value. Otherwise, the input object field is **optional**.". I am seeing different behavior. I defined ArticleInputType and configured it with default value using IntValueNode and I still get 'id' is required message. 

**To Reproduce**
``` 
class ArticleInputType : InputObjectType<Article>
    {
        protected override void Configure(IInputObjectTypeDescriptor<Article> descriptor)
        {
            //base.Configure(descriptor);

            descriptor.Name("Article");

            descriptor.Field(f => f.Id)
                .Type<IntType>()
                .DefaultValue(new IntValueNode(0));
        }
    }
```
```
public abstract class MediaItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public IEnumerable<Image> Images { get; set; }
    }
    public class Article : MediaItem
    {

    }
```
```
class MutationType : ObjectType<Mutation>
    {
        protected override void Configure(IObjectTypeDescriptor<Mutation> descriptor)
        {
            descriptor.Field(f => f.CreateArticle(default(Article)))
                .Type<NonNullType<ArticleType>>()
                .Argument("article", a => a.Type<NonNullType<ArticleInputType>>());
        }
    }
```
**Expected behavior**
When i execute:
```
mutation createArticle{
  createArticle(article: {}){
    
  }
}
```
I shouldn't get this:
```
{
  "errors": [
    {
      "message": "`id` is a required field and cannot be null.",
      "locations": [
        {
          "line": 29,
          "column": 27
        }
      ]
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by michaelstaib** [comment]
Hi,

I will write a little test and check this one out. Give me a view minutes.

**Comment by etaletovic** [comment]
No problem. This is my first time using this library and I spend some time on this and I still cannot figure it out.

**Comment by etaletovic** [comment]
I'd like to not have property Id: int be required when I create my Articles.

**Comment by etaletovic** [comment]
I updated my report with MutationType.cs

**Comment by michaelstaib** [comment]
Btw.... you can just provide an int here `DefaultValue(0);` The input value node is more for the schema first world. But that has nothing to do with the error :)

**Comment by etaletovic** [comment]
Yeah, that was the first thing I did but after I got the error above I tried multiple things including
DefaultValue(0) and DefaultValue(default(int))

**Comment by michaelstaib** [comment]
There must be something with your schema setup. Could you provide me with your full schema? I think that the type is somewhere not wrapped by a schema type and then the schema will infer the type. Since int is not nullable it would then become a nonnulltype.

**Comment by michaelstaib** [comment]
Are you by any chance registering your schema like the following?

```
Schema.Create(c => c.RegisterMutationType<Mutation>());
```

Since then. we would not use the schema types and their description. The following would be how to provide us with the schema types:

```
Schema.Create(c => c.RegisterMutationType<MutationType>());
```

**Comment by etaletovic** [comment]
That's probably it! Let me try.

**Comment by michaelstaib** [comment]
The first registration is if you want to work with poco types. We will then basically infer everything from your types. You can then annotate your types the attributes to give us more hints.

The second variant is code-first with schema types, which keeps your .net types clean from any attributes.

**Comment by michaelstaib** [comment]
We also have a slack group. Feel free to join us there for any help:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg

**Comment by michaelstaib** [comment]
Does it work?

**Comment by etaletovic** [comment]
I am getting an exception when I try to run the application after
registering MutationType cs Mutation. Once I figure that out I'll let you
know. Thank you for helping out!

**Comment by michaelstaib** [comment]
OK, great! If you need any further help to get it running just let me know.

BTW, if it is a schema exception then you can look up the schema violations in the errors collection of the exception.

There is also a Star Wars example here:
https://hotchocolate.io/docs/example-star-wars-code-first

and some other examples for more advance concepts here:
https://hotchocolate.io/docs/example-other-code-first

**Comment by etaletovic** [comment]
After I resolved couple of Schema exceptions I have it working now! I'll
make sure to join Slack group you sent me. Thank you!

**Comment by etaletovic** [comment]
I am closing this issue as it's resolved.
