### ISSUE TITLE
Resolver method with a [Service] parameter is not called if the service is not found, and no error is thrown

### ISSUE THREAD

**Issue by eduleite** [ChilliCream/hotchocolate#626]
If a resolver method has a [Service] parameter, if the engine does not find the corresponding [Service], the resolver is not called and null is returned by the engine instead, without throwing any errors.

Tonight I will work on a sample test case and replicate this issue.

**Comment by eduleite** [comment]
Humn, I could not replicate the same error I have on the server I am working on.
I will do more investigations on this one.

**Comment by michaelstaib** [comment]
We have now an explicit unit test for this (9.0.0-preview.25)
