### ISSUE TITLE
IErrorFilter is not given the exception unless IncludeExceptionDetails is enabled

### ISSUE THREAD

**Issue by GraemeF** [ChilliCream/hotchocolate#637]
**Describe the bug**
Error filters can not make use of exception information when `IncludeExceptionDetails` is `false`.

**To Reproduce**
1. Register an `IErrorFilter` which uses `error.Exception` as in the second example in [the documentation](https://hotchocolate.io/docs/errors#exceptions)
2. Set `IncludeExceptionDetails` to `false`
3. Run a query which throws an exception

**Expected behavior**
The `IErrorFilter` implementation should be executed and able to use `error.Exception` to decide what to do.

**Additional context**
This was very confusing until I realised it was only working when the debugger was attached. The docs are misleading, at the very least...

**Comment by michaelstaib** [comment]
I can confirm this issue. I will fix it tonight and integrate it in the next preview build.

**Comment by michaelstaib** [comment]
This one is now fixed with 9.0.0-preview.4
