### ISSUE TITLE
Allow multiple schemas in one server

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#643]

**Comment by nkovacic** [comment]
This would be very useful for splitting schema to public and internal.

**Comment by michaelstaib** [comment]
This one is now implemented on the execution engine branch for version 11.

**Comment by nkovacic** [comment]
Any eta to whebh will this be merged to master?

**Comment by mario-santos-solytic** [comment]
@michaelstaib what is the issue number related to this change?
I did not find anything related at https://github.com/ChilliCream/hotchocolate/milestone/45
