### ISSUE TITLE
FieldScopedVariableResolver expect dictionary parent

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#654]
**Describe the bug**
When creating an extended stitched schema using the `$fields` option during delegation won't work if the type is from the extended schema and not a remote schema. This is because `FieldScopedVariableResolver` expects `context.Parent` to be ` IReadOnlyDictionary<string, object>` and not a regular C# object.

**To Reproduce**
In a stitched schema extensions have something that looks like
```
extend type Query {
  product(productKey: String!): Product!
}

type Product {
	productKey: String!

	orders(customerKey: String): [Order!]!
		@delegate(schema: "commerce", path: "orders(productKey: $fields:productKey, customerKey: $arguments:customerKey)")
}
```

When executing a query that uses the above we see the message
> Unable to cast object of type 'Experiments.GraphQL.Schemas.Extensions.Product' to type 'System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Object]'.

**Expected behavior**
Would expect the query to be able to use the Product field data in the delegated query.

Using Hot Chocolate `0.8.0`.

**Comment by michaelstaib** [comment]
I will fix that in 0.8.1 so that we call the field resolver instead.

**Comment by michaelstaib** [comment]
@nigel-sampson  I am moving this one to version 9 since it has to many implications for the patch release on Sunday.

**Comment by nigel-sampson** [comment]
No worries, I've worked around it by having the resolver add the field to `ScopedContextData` and using that instead of `$fields`.

**Comment by michaelstaib** [comment]
We will move this one, one more time since we will have a major shift in the stitching layer with the upcoming execution plans.

**Comment by michaelstaib** [comment]
This one is outdated.
