### ISSUE TITLE
Introduce error context to IError

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#662]
The error should have context data which represent non-serializable objects that can be used in the error filters. This is basically the same like the exception property.

**Comment by tsmojver** [comment]
Will this include properties on IResolverContext such as 'Path' and 'FieldSelection'?

Thanks for all the great work!

**Comment by michaelstaib** [comment]
The contextual data of the resolver context should already be added at this point. I will have to check the code again to answer the question correctly :) But the context data object will not have those properties. It is more meant for the dev to put in additional context data if needed... custom things that are unknown to us like a user id or so.

**Comment by michaelstaib** [comment]
We are abandoning this idea for now.
