### ISSUE TITLE
`IChangeTypeProvider` is not called for generic types

### ISSUE THREAD

**Issue by rick-micpoint** [ChilliCream/hotchocolate#6737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have a strongly typed `Id` struct that needs to be mapped to and from graphql. When I try to register a `IChangeTypeProvider` though, `TryCreateConverter` isn't even called, resulting in schema generation errors.

### Steps to reproduce

# Strongly typed Id
```csharp
public readonly record struct Id<TEntity>
{
    public Id(Guid value)
    {
        Value = value;
    }

    public readonly Guid Value { get; }
}
```

# ChangeTypeProvider
```csharp
public class IdChangeTypeProvider : IChangeTypeProvider
{
    public IdChangeTypeProvider()
    {
        bool boop = true;
    }

    public bool TryCreateConverter(Type source, Type target, ChangeTypeProvider root, [NotNullWhen(true)] out ChangeType? converter)
    {
        converter = null;
        return false;
    }

    private static bool IsId(Type type)
    {
        return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Id<>);
    }
}
```

# Query
```csharp
public sealed record Foo
{
    public Id<Foo> Id { get; init; }
}

public class Query
{
    public Foo GetFoo() => new Foo();
}
```
# Registration
```csharp
builder.Services
    .AddGraphQLServer()
    .AddTypeConverter<IdChangeTypeProvider>()
    .AddQueryType<Query>()
```

Put a breakpoint in the constructor and `TryCreateConverter` of `IdChangeTypeProvider`. The constructor of  is called, but `TryCreateConverter` is never entered.

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to infer or resolve a schema type from the type reference `Id<Foo!> (Output)`.
```

### Version

13.7.0

**Comment by michaelstaib** [comment]
You also need to bind the type.

**Comment by rick-micpoint** [comment]
> ```cs
> builder.Services
>     .AddGraphQLServer()
>     .AddTypeConverter<IdChangeTypeProvider>()
>     .BindRuntimeType<Id<int>, IdType>()
>     .AddQueryType<Query>()
> ```

And how do I do this for a generic type?

**Comment by rick-micpoint** [comment]
And what is the point of a converter when I need to create an `IdType` anyway? Now the `IdType` takes care of all the parsing instead.

**Comment by rick-micpoint** [comment]
Neither `ScalarType.ParseValue` nor the converter is called, despite registering them both, even with closed generic. Instead I now get `"id": "Id { Value = f12cd36b-72fc-597a-3795-7e48faf05a69 }"` as a result.
