### ISSUE TITLE
v12 to v13 migration guide doesn't contain information about IExecutionResult interface changes

### ISSUE THREAD

**Issue by gmanvel** [ChilliCream/hotchocolate#6740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In our project we make use of `ExecutionDiagnosticEventListener` and override `ExecuteRequest` method
```
public override IDisposable ExecuteRequest(IRequestContext context)
{
    var errors = context.Result.Errors;
    // implementation
}
```

in v12, `IExecutionResult` contained `Errors` property, after upgrading to v13, there is no such error anymore.
[v12 to v13 migration wiki](https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13) does not contain any information about this breaking change.

Was it moved or removed ?

### Steps to reproduce

Use HotChocolate v12
Use the IExecutionResult interface
Update to HotChocolate v13
Implementation is broken

### Version

13.7.0

**Comment by glen-84** [comment]
It looks like it was removed in #4874.

You could perhaps use the `RequestError` and/or `ResolverError` methods.

```cs
public override void RequestError(IRequestContext context, Exception exception)
{
    this.logger.LogError(exception, "A request error occurred.");
}

public override void ResolverError(IMiddlewareContext context, IError error)
{
    this.logger.LogError(error.Exception, "A resolver error occurred.");
}
```

**Comment by michaelstaib** [comment]
As pointed out you can use the error hooks ... but you could also look if this response contains errors ...

```csharp
if(context.Result is IQueryResult queryResult) 
{
     log.Errors(queryResult.Errors)
}
```

In case of a subscription or a deferred request the result will be an IResponseStream
