### ISSUE TITLE
Two things missing in the documentation

### ISSUE THREAD

**Issue by Kricke242** [ChilliCream/hotchocolate#688]
I think the following two points should be clarified in the documentation.

1) When stitching two schemas, each with pagination. In the stitching gatway, do one manually have to add PagingatingTypes? Like
```
.AddSchemaConfiguration(c =>
                      {
                          c.RegisterExtendedScalarTypes();
                          c.RegisterType<PaginationAmountType>(); //<--this
```
2) Dataloaders need to return the results in the same order as the keys (in the overriden `FetchAsync(IReadOnlyList<int> keys)`. Right? Is so, I think the documentation about dataloaders should mention that, or the returned objects could be mapped to the wrong key/id.
Do we know the order of the keys, because now, I have to kinda 
`OrderBy(p => keys.ToList().IndexOf(p.Id))`

**Comment by michaelstaib** [comment]
I will look into this tomorrow.

**Comment by michaelstaib** [comment]
2. is as specified in the data loader spec. But you are right we should make that clear in the documentation. 

Just as a side note if you are using the delegate data loader helper we will take care of this this for you.
