### ISSUE TITLE
Dynamic type modifiers not respected?

### ISSUE THREAD

**Issue by adamjones1** [ChilliCream/hotchocolate#689]
I'm trying to declare the types of my type fields using the constructors for `NonNullType`, `StringType`, etc and finding that the type modifiers (`NonNullType` and `ListType`) aren't being respected when declaring them this way.

eg. If I use the Star Wars template example, and in line 20 of QueryType.cs change the statement from:
```
descriptor.Field(t => t.GetCharacter(default, default))
          .Type<NonNullType<ListType<NonNullType<CharacterType>>>>()
          .Argument("characterIds",
              a => a.Type<NonNullType<ListType<NonNullType<IdType>>>>());
```
to:
```
descriptor.Field(t => t.GetCharacter(default, default))
          .Type<NonNullType<ListType<NonNullType<CharacterType>>>>()
          .Argument("characterIds",
              a => a.Type(new NonNullType(new ListType(new NonNullType(new IdType())))));
```
then I see that the field definition for `characterIds` in `Query` becomes just:
```
character(characterIds: ID): [Character!]!
```
ie. the input type is `ID` rather than `[ID!]!`. I'm not sure if this is supposed to work but I note that the style appears to work for normal types (and is extremely helpful for constructing the schema dynamically), just not the modifiers.

**Comment by michaelstaib** [comment]
Good catch, I will look into this tomorrow and write a test for this one.

**Comment by adamjones1** [comment]
Hi there, just want to ask, is this still on the radar? I notice it's in the 0.8.3 milestone but that's looking a bit lonely at the moment 😄 (it seems like's development's jumped ahead to 9.1.0?). Thanks!

**Comment by michaelstaib** [comment]
Oh sorry, indeed :)

**Comment by michaelstaib** [comment]
we skipped 0.8.3 and I overlooked this one... I moved it to the current stream.

**Comment by adamjones1** [comment]
Hi, is there any update on this one? This is actively preventing me from using HC in my app at the moment.

**Comment by michaelstaib** [comment]
This one is on the backlog for 11. We we put more effort in the pure code-first mode since that was in high demand. 

As a workaround you could use the typenode objects instead to achieve what you want to do.

**Comment by adamjones1** [comment]
Okay, thanks for the update!

**Comment by michaelstaib** [comment]
We will look at dynamic Schemas after 11. We will however look at better ways to enable this. I am closing this issue and we will create a new issue lining out our idea around this.
