### ISSUE TITLE
Support for circular references in dynamically produced schemas

### ISSUE THREAD

**Issue by adamjones1** [ChilliCream/hotchocolate#690]
Using the usual static `.Type<MyType>()` declaration on fields we can create types which refer to themselves in their fields, eg. `CharacterType` in the Star Wars example uses 
```
descriptor.Field("friends")
          .Type<ListType<CharacterType>>();
```
to add a list of its own type to itself as a field.

I'm not clear on how to do this when constructing types dynamically with the "types as instances" API since the referenced type won't exist yet:
```
descriptor.Field("friends")
          .Type(new ListType(new CharacterType()));
```
(if I'm not mistaken, it appears to not be supported currently.)

Not being able to do this is very limiting on the kinds of schemas that can be produced dynamically. In my case I'd like to be able to use Hot Chocolate for dynamic schema production (it's much closer to being able to achieve this than graphql-dotnet). Could there be an addition of a "reference type" so we can write something like:
```
descriptor.Field("friends")
          .Type(new ListType(new NamedTypeReference("Character")));
```
(or have a ctor overload on `ObjectType` whose `configure` delegate provides the end type as a parameter, or anything else that makes the end result possible?)

**Comment by michaelstaib** [comment]
This should work already I think.

Could you upload your sample to a GitHub repo so we can have a look at this together?

The way you could go about is to provide a AST reference with version 8 though I think it is kind of ugly :)

`.Type(new ListTypeNode(new NamedTypeNode("Character")))`

We could have a look that this becomes nicer with the next version.

**Comment by michaelstaib** [comment]
This is basically what we do with schema-first schemas... since you can mix and match ... this should actually work.

**Comment by adamjones1** [comment]
Hi, apologies for the late reply! I've realised I wasn't actually quite specific enough with what I'm trying to achieve, though I had a look at using the AST and it does provide a (sub-optimal) workaround for what I'm looking for.

Basically what I've got is something a bit like this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using HotChocolate;
using HotChocolate.Types;

namespace Api.GraphQL
{
    class GraphQLSchemaGenerator
    {
        public IOutputType PrimitiveSchema(Type type)
        {
            var schemas = new Dictionary<Type, IOutputType>
            {
                [typeof(int)] = new IntType(),
                [typeof(string)] = new StringType(),
                [typeof(DateTime)] = new DateTimeType()
            };
            return schemas[type];
        }

        public IOutputType ArraySchema(IOutputType itemType)
        {
            return new ListType(itemType);
        }

        public IOutputType RecordSchema(RecordInfo info, IReadOnlyList<IOutputType> propTypes)
        {
            return new ObjectType(config =>
            {
                config.Name(info.TypeName);

                foreach (var (property, type) in info.ChildProperties.Zip(propTypes, (x,y) => (x,y)))
                {
                    config.Field(new NameString(property.Name)) 
                          .Type(type)
                          .Resolver(...);
                }
            });
        }

        public IOutputType ForeignKeySchema(IOutputType idType, string foreignTypeName) =>
            null; // new NamedTypeReference(foreignTypeName);

    }
}
```

so as in, there's a "schema generator" class which traverses some POCO class and when it encounters an `int`, `string`, or `DateTime` returns an `IOutputType` produced by `PrimitiveSchema`, when it encounters an array type it returns an `IOutputType` formed from whatever it produced when it ran on the inner element type, when it encounters a record type it returns an `ObjectType` formed from whatever it produced when it ran on the record's public properties' types, etc. 

One of the 'types' in this hierarchy can be denoted as a 'foreign key', meaning it refers to another type. My issue here is that to return an `ObjectType` here would potentially result in infinite recursion, eg. if there was a class like

```
class MyType
{
    public ForeignKey<MyType> MyProperty { get; }
}
```

So some kind of a reference using the type name is needed. Using something like what the AST has, a `NamedTypeNode`, is ideal except that it can't be composed with other `IOutputTypes` so the entire schema generator would have to work with AST nodes, which I've found to be far too low-level for some types to be practical. Essentially the ideal solution would be an equivalent of `NamedTypeNode` for the `IOutputType` API (the commented out "`NamedTypeReference`").

The workaround using ASTs is to wrap the foreign key in an object type so `ForeignKeySchema` returns something like:

```
public IOutputType ForeignKeySchema(IOutputType idType, string foreignTypeName) =>
    new ObjectType(config =>
    {
        config.Name(new NameString($"ForeignKey_{foreignTypeName}"));
        config.Field(new NameString("value"))
            .Type(new NonNullTypeNode(new NamedTypeNode(new NameNode(foreignTypeName))))
            .Resolver(...);
    });;
```

But I'd rather not do this as it adds a fair bit of verbosity/cruft to the API especially when GraphQL doesn't have generic types.

**Comment by michaelstaib** [comment]
So,

the `NameTypeReference` would get as an input the full type spec ... so a non-null string would look like the following: `new NameTypeReference("String!")`?

We could add this to the next version.

**Comment by michaelstaib** [comment]
Sorry, I misread you again,

you just want a type name reference  with the standard types. I got now :)

OK, lets put this in the version backlog.

**Comment by michaelstaib** [comment]
Just as an info, you can also just add the poco type to the schema builder and we will actually infer the schema type from your poco. With version 9 you can even override the conventions for this. Our schema builder can handle recursive types.

```csharp
Schema schema = SchemaBuilder.New().AddType(typeof(MyFooType)).AddType<MyBarType>().Create();
```

**Comment by adamjones1** [comment]
Yep that's right just a type name reference. Thanks, that would great! The schema builder looks nice, I'll look more into it but I think for this particular use case it probably won't fit my needs because of...reasons. (The shape of the API I'm hooking HC into.)

**Comment by michaelstaib** [comment]
I will close this one since we have decided to move the subject of dynamic schemas to the next release. We will soon create a feature issue lining out how we will enable dynamic schemas.
