### ISSUE TITLE
Union Type Descriptor - Documentation

### ISSUE THREAD

**Issue by kyrim** [ChilliCream/hotchocolate#697]
Firstly, amazing work on this library, the way you guys have implemented this and the speed at which you guys improve the functionality consistently is great.

I'm having trouble figuring out how to implement union types in a code first fashion. I've had a look at the documentation here: https://hotchocolate.io/docs/code-first-introduction (at the bottom) but unfortunately the link for [Union Type Descriptor](https://hotchocolate.io/docs/code-first-union-type.md) gives a 404 page (Enum and Input object types also present 404 pages). 

#416 suggests you need to create a marker interface and register the types, but i'm unsure how exactly to do this.

Are there any examples I can follow to do this in a code first manner?

Please forgive me if this is the incorrect place to submit this question.

**Comment by michaelstaib** [comment]
Hi @kyrim,

we will improve the documentation for all schema types with the next release. I have that one one my todo list.

So, 

as for your question, we have some unit tests that might help you here:

```csharp
[Fact]
        public void GenericUnionType_DynamicName()
        {
            // act
            var schema = Schema.Create(c =>
            {
                c.RegisterType(new UnionType<IFooOrBar>(d => d
                    .Name(dep => dep.Name + "Foo")
                    .DependsOn<StringType>()));

                c.RegisterType(new FooType());
                c.RegisterType(new BarType());

                c.Options.StrictValidation = false;
            });

            // assert
            UnionType type = schema.GetType<UnionType>("StringFoo");
            Assert.NotNull(type);
        }
```

All the union type tests are here:
https://github.com/ChilliCream/hotchocolate/blob/master/src/Core/Types.Tests/Types/UnionTypeTests.cs

They might give you an idea how to use the union type.

We also have a slack channel if you like to join:
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg

My response time is higher on there :)

**Comment by michaelstaib** [comment]
If this answers your question please be so kind to close this issue.

**Comment by michaelstaib** [comment]
I have added #698 to track the documentation update.

**Comment by kyrim** [comment]
Thank you that answers my question :)
