### ISSUE TITLE
Allow `@authorize` directive on input fields

### ISSUE THREAD

**Issue by gregsdennis** [ChilliCream/hotchocolate#744]
The `@authorize` directive should be applicable to input fields as well as output fields.

Use case: 

I have a mutation that, among other actions, stores data.  One of the data fields is a date/time.  In production, I always want to use the current date/time, but when testing it's nice to be able to explicitly set the date/time to a specific value so that when the item is retrieved, I can validate the date/time that was used.

To achieve this, I want to expose a date/time field on the input type that is only accessible to callers with a specified policy (e.g. "TesterGroup").

If a caller does not have this policy and tries to set this value, an "unauthorized" error is returned, similarly to if a caller requests an output field they are not authorized to retrieve.

Our current alternative is to create a completely separate mutation that takes in another type that has the date/time field on it.  But this uses a different resolver, and thus different code, so I'm not testing the correct code path.

**Comment by michaelstaib** [comment]
I am closing this as a duplicate. The conversation is happening on #1879

**Comment by gregsdennis** [comment]
Odd that this one is marked as the duplicate of a later issue, but okay.

**Comment by michaelstaib** [comment]
Just because the discussion evolved on the newer issue.
