### ISSUE TITLE
Automatic OData stitching 

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#748]
We will add a description to this one soon. 

It will complement the http directives and allow auto-stitching of odata. So the ideas here is that you could just stitch in OData as if it were a GraphQL schema. At the moment you would have to do some manual stuff to achieve that. This will allow to integrate things like Microsoft Graph and SAP into your schemas. 

Resources:
http://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html

**Comment by sherland** [comment]
> At the moment you would have to do some manual stuff to achieve that.
Do you have pointers to documentation or examples of this?

**Comment by dtbenson43** [comment]
Is this actually complete? I've tried looking for examples and going through the source code, but I'm not seeing any other reference to OData, or how to use the CDSL for auto stitching with Hot Chocolate.

**Comment by michaelstaib** [comment]
We abandoned this task.
