### ISSUE TITLE
Support for Automatic Persisted Queries (APQ)

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#755]
https://medium.com/open-graphql/graphql-dynamic-persisted-queries-eb259700f1d3

**Comment by michaelstaib** [comment]
#834

**Comment by willwolfram18** [comment]
So if I understand correctly, #266  is just a high level story about building query persistance into HC. This issue is focused specifically on the ability for queries to be dynamically stored (to some storage medium) and then accessed again by some Id (hash, GUID, etc.), correct?

**Comment by michaelstaib** [comment]
@willwolfram18 exactly. With this we are basically add the ability to store queries dynamically. So, if someone queries something and gives us a name parameter we use that a key to store that query. Moreover, we have to add a standardized error that is thrown when a query is not found.

**Comment by michaelstaib** [comment]
This one is now implemented.
