### ISSUE TITLE
Non-blocking Schema Initialization for ASP.net core middleware

### ISSUE THREAD

**Issue by jemeric** [ChilliCream/hotchocolate#764]
**Is your feature request related to a problem? Please describe.**
I'm just started looking into this tool so perhaps I'm missing something, but it would be nice if there were the option to load the schema in a non-blocking when using the ASP.net core middleware.

Right now I'm having to do something like this to initialize the schema in Startup.cs:

`
public void ConfigureServices(IServiceCollection services)
{
  ISchema schema = Schema.Create(File.ReadAllText(($"{env.ContentRootPath}/GraphQL/schema.graphql")));
  services.AddGraphQL(schema);
}
`

**Describe the solution you'd like**
It would be nice if there were an alternative async lazy initialization. I imagine there could be performance downsides if requests come in before the application loads; however, this could be mitigated by using something like this (https://github.com/thomaslevesque/AspNetCore.AsyncInitialization) for those concerned about performance. 

**Describe alternatives you've considered**
- Not using the middleware and implementing async schema loading/the endpoint 
- Maybe this is possible and I've just overlooked something key

**Comment by michaelstaib** [comment]
Is your concern here for the `ReadAllText`?
What would be the gain here?

**Comment by jemeric** [comment]
Yep, my primary concern is needing to do blocking file IO associated with ReadAllText, although it could extend to the schema binding as well depending on performance. The primary benefit would be a faster startup time in applications that do a lot of work starting up.

On a side note, I really appreciated what you're doing with this tool, it reminds me a bit of graphql java tools. I was happy to find there seems to be support for async graphql resolvers, which is far more important when it comes to performance.

**Comment by michaelstaib** [comment]
The schema binding itself does no IO work. So, it basically is only the ReadAllText. I think it becomes problematic with dependency injection since everything there is sync. 

So, we could introduce some kind of Async alternative to create an assembly but if you let dependency injection take care of creating the schema instance than you are basically blocking again.

However, we will do a lot of work for startup performance in general with version 9.1. There will be options to lazy compile resolvers and other stuff.

**Comment by jemeric** [comment]
Thanks @michaelstaib , I'm looking forward to the changes in 9.1! I'm a big proponent of schema-first development and it sounds like the upgrade will involve some major improvements there. I've found this pattern to be a nice clean way to get started with schema-first development:

```
            var schema = Schema.Create(schema, c =>
            {
                c.BindResolver<MutationResolver>().To("Mutation");
                c.BindResolver<QueryResolver>().To("Query");
            });
```

```
    public class MutationResolver
    {
        ...
        [GraphQLName("updateVersion")]
        public Settings UpdateVersion(string version)
        {
            ...
            return settingsService.get();
        }
    }
```

**Comment by michaelstaib** [comment]
If you are on version 9 preview try the new schema builder:

```csharp
SchemaBuilder.New()
    .AddDocumentFromString("type Query { ....")
    .BindResolver<MutationResolver>().To("Mutation")
    .BindResolver<QueryResolver>().To("Query")
    .Create();  
```

**Comment by jemeric** [comment]
I haven't upgraded yet, but I'll be sure to use that when I do. Thanks for the tip!

**Comment by jemeric** [comment]
> If you are on version 9 preview try the new schema builder:
> 
> ```cs
> SchemaBuilder.New()
>     .AddDocumentFromString("type Query { ....")
>     .BindResolver<MutationResolver>().To("Mutation")
>     .BindResolver<QueryResolver>().To("Query")
>     .Create();  
> ```

@michaelstaib I've upgraded to version 9.0.1 but it doesn't look like it supports the "To("..")" in your schema builder example. Is it done another way now?

**Comment by michaelstaib** [comment]
This one is now implemented with the new configuration API on version 11.
