### ISSUE TITLE
Transforming array of object identifiers to array of objects during schema stitching

### ISSUE THREAD

**Issue by anadale** [ChilliCream/hotchocolate#768]
**Is your feature request related to a problem? Please describe.**
Schema stitching is a powerful tool when combining a set of APIs into one large API. However, it lacks the ability to transform arrays of object IDs into arrays of objects using delegation and Data Loaders. While it is easy to replace, for example, `author: ID!` with `author: User!`, using `@delegate(schema: "users", path: "user(id: $fields:authorId)")` it needs a separate helper method on `users` schema to transform `authors: [ID!]` into `authors: [User!]` since it is not clear how to point that call to `user` should take the value of each item in the array of identifiers.

**Describe the solution you'd like**
It would be great to describe the transformation like `authors: [User!] @delegate(schema: "users" path: "user(id: @item)")`, where `@item` will be replaced with array item values, resulting calls will be batch-sent to `users` API using Data Loader technique to avoid N+M problems.

**Comment by michaelstaib** [comment]
> It would be great to describe the transformation like authors: [User!] @delegate(schema: "users" path: "user(id: @item)"), where @item will be replaced with array item values, resulting calls will be batch-sent to users API using Data Loader technique to avoid N+M problems.

The stitching layer batches automatically today. So, we do not need anything to do here.

I think we also need no new syntax since the stitching layer should be able to figure out that the input is an array and that the target is a single value argument.

If we had something like this:

`user(id: $fields:authorIds)`

The stitching layer would create the following query:

```graphql
{
  a: user(id: 1) {
    ...
  }
  b: user(id: 2) {
    ...
  }
  c: user(id: 3) {
    ...
  }
}
```

What is more interestingly what should happen when we have two list arguments.

`user(id: $fields:authorIds somethingElse: $fields:somethingElseIds)`

There are also other cases that have to be looked at. What if the inputs are non-null but the arguments are nullable:

`[String]` => `String!`

The stitching layer could remove all invalid values and proceed, but do we want that.

**Comment by michaelstaib** [comment]
We might move this one to the next release (9.1).

**Comment by anadale** [comment]
> There are also other cases that have to be looked at. What if the inputs are non-null but the arguments are nullable:
> 
> [String] => String!
> 
> The stitching layer could remove all invalid values and proceed, but do we want that.

I think that, in most cases, there will be no such collisions, so stitching layer can fail fast when it cannot convert arguments. Also, an ability to specify converter (through directive or somehow) is a reasonable alternative/addition.

**Comment by apazureck** [comment]
Hi @anadale,

Would it be possible to show a small example for your "workaround" to this problem? That is exactly what I would like to do on our gateway, too. As I am new to that topic it would help a lot (I think others, too).

Thanks and cheers!

**Comment by anadale** [comment]
Hi @apazureck,

Please take a look at https://gist.github.com/anadale/39f366ad3edb9c99173ba6d08d69b2ef – although we did not use it for quite a while, we have maintained compatibility with the recent versions of HC.

The idea of the usage is simple (let's take a look at `ObjectOrIdOrNull` method): to get a `TResult` object for some identifier, that is retrievable from the current "parent" in context, you pass:
- a `dataLoader`, used to load an object by ID
- an `idGetter`, lambda that will return required identifier out of the parent object (for example: `p => p.AccountId`)
- `justId` lambda, that will return an instance of `TResult` with only `Id` field set

This method can return:

- `null`, if identifier, returned by `idGetter` is null
- An instance of `TResult` with only `Id` field populated by `justId` lambda (if `id` is the only field, requested by the client)
- Full object, loaded by `dataLoader`

Rest of the methods are variations to make life easier.

If you'll have any questions – please, don't hesitate to reach me.

**Comment by apazureck** [comment]
@anadale thank you for that fast reply! I will try that right now.
