### ISSUE TITLE
Enable programmatic identification of Authorize errors

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#770]
In our application front end we need to handle a number of differing uses cases when the stitched schema returns null for a field.

A field can be null for a number of reasons including:
1. There is no data for the field.
2. The remote schema responsible for the field is unavailable.
3. The calling user does not have authorization for the field.

How the UI reacts to 2 and 3 are usually very different which means the front end needs to be able to distinguish between the two different errors. 

We have a contract we'd like in our error extensions to enable to front end to do the disambiguation. We're trying to enable this using Error Filters.

We can identity remote errors using the presence of a `remote` extension.   However for errors returned by `AuthorizeDirectiveType` have no identifying characteristics beyond the message

> The current user is not authorized to access this resource.

Using that doesn't feel particularly nice.  It would be good to see some sort of way to programmatically identity those auth errors in an error filter.

**Comment by michaelstaib** [comment]
We are planing to introduce error codes for all errors that come form the HC. Would that be something that could help here?

**Comment by michaelstaib** [comment]
We have started this with V9 but have to cover more ground here.
https://github.com/ChilliCream/hotchocolate/blob/c6b8b006f7852f4313e574656d6960e1a5a8a65c/src/Stitching/Stitching/ErrorCodes.cs

**Comment by michaelstaib** [comment]
I think we could get the error codes for your cases into the V9 release.

**Comment by nigel-sampson** [comment]
Excellent. thanks.
