### ISSUE TITLE
Add support for .net core 3`s non-null ref types

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#780]
With .net core 3 we finally have support for non-null reference types. This really plays well with GraphQL and we can then infer the non-nullability from reference types like string.

**Comment by glucaci** [comment]
We should keep support at least for the last .NET Core LTS version, that means we have to support:
1. .NET Framework
2. .NET Core LTS (2.1)
3. .NET Core Current (2.2 => 3.0)

3.0 will not be for sure LTS
