### ISSUE TITLE
Automatic Database Mapping

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#793]
We want to introduce a database abstraction that can be used to generate a GraphQL schema from a database without a single line of code.

I think there should be two models of this, one where we describe a database via a GraphQL definition and one where the GraphQL definition is inferred from the database.

**Comment by ChristianWeyer** [comment]
Maybe even have an EF model as an abstraction? Generate GQL from EF.

**Comment by michaelstaib** [comment]
@ChristianWeyer that is one thing we want to support. But I think our internal abstraction should be more abstract in order to optimize databases more. EF is good for many things but it tends to be slow in some scenarios.

The ideas that we have is to have two implementations in the beginning, one for mongo and one for EF Core. Also we are at the moment exploring to write a connector to postgress since we see a lot of demand for that.

**Comment by michaelstaib** [comment]
One more aspect that we are looking into is in real-time communication with databases where we get trigger by the database. Mongo provides this kind of eventing for instance and this would allow us to build a GraphQL schema on top of a database that event support subscriptions without writing too much code.

**Comment by michaelstaib** [comment]
#412

**Comment by MaximS** [comment]
Just some considerations:

- Direct DB access, i.e. storage layer, is not that is really expected from the back-front glue component. In most cases, there is some logic layer in between. So autogeneration from EF or NHibernate models could be more adequate. Has anybody seen [EntityGraphQL](https://github.com/lukemurray/EntityGraphQL)?

**Comment by michaelstaib** [comment]
@MaximS I think to add a layer for ef is not that difficult with HC, if you want to contribute something in the area we are open to discuss that.

This issue is more geared to allow something like Hasura and Prisma allow. So, basically you can describe your database with the GraphQL-SDL syntax and then the server will handle the rest for you. This way you design the database through the SDL and abstract the models from the actual database engine. We will be able to use lower level database APIs to provide better performance than EF does. Moreover, we will be able to enable subscriptions on databases that support eventing features like mongo and postgress. 

This feature becomes very interesting when you think serverless and rapid development.

The cool thing here is that you can extend on those models sdl-first and code-first.

But as I said we are looking at different directions and if you are willing to contribute then open an issue that proposes your Idea to introduce schema builder extensions that allow simple integration of the entity framework. I would love to see things like that and would help you along.

**Comment by badre429** [comment]
@michaelstaib take a look at this library [Graphity](https://github.com/WiredUK/Graphity) it has great approach  it take me two line to add a graphql api to my project based on my NorthwindDbContext (efcore context)
```cs
            services.AddGraphity<NorthwindDbContext>();
            app.UseGraphity("/graphql");
```
***Graphity*** two line and ready to go

**Comment by michaelstaib** [comment]
We have something similar in mind although we do not want to bind solely to EF. 

I also want to just add an sql server with 1000 tables and do not worry about ef issues.

Moreover I want to support subscriptions with Mongo or Postgres.

**Comment by OneCyrus** [comment]
in addition to michael's reasons, the magic strings for filtered queries aren't that great for graphql too. this will limit the power of schema/query validation quite a bit.

**Comment by brent-williams** [comment]
> Moreover I want to support subscriptions with Mongo or Postgres.

Just a note, [Postgraphile](https://github.com/graphile/postgraphile) already does this for Postgres, including subscriptions and live queries.

**Comment by michaelstaib** [comment]
I know, hasura as well. But we want to do it on any db.

**Comment by shreyasraghunath** [comment]
Hi @michaelstaib, Any chance this will be picked up in HC-11.x.x?

**Comment by steveoh** [comment]
> I also want to just add an sql server with 1000 tables and do not worry about ef issues.

THIS!

**Comment by ManfredLange** [comment]
In terms of database support, allow me a comment: While I realize that a lot of people are using EF, it is not the only option. GraphQL as such has no relation with EF, so it would be sad to see if there is more and more things in Hot Chocolate that would keep people from using something other than EF, e.g. (Fluent) NHibernate, which others may prefer.

Just my two cents. :-)

**Comment by michaelstaib** [comment]
@ManfredLange Hot Chocolate works with anything that supports IQueryable out of the box. 

Moreover, we support the native mongo driver. Hot Chocolate supports more query constructs than through the .NET mongo API possible. Further, we are working on a Neo4J integration and a Dapper Integration and have the Microsoft Graph and Elastic planned.

The HotChocolate.Data layer has all the abstractions there if you think NHibernate is something worth, why not, help us and contribute :)

This issue will get more traction with the Neo4J story and once we have that working we will move the new Automatic Database Mapping integration into HotChocolate.Data so that it works with all the drivers we currently support.

**Comment by RomanVashchegin** [comment]
@michaelstaib could you please help with integration with NHibernate?

message=Session is closed! Object name: 'ISession'.
stackTrace=   at NHibernate.Impl.AbstractSessionImpl.ErrorIfClosed()
   at NHibernate.Impl.AbstractSessionImpl.CheckAndUpdateSessionStatus()
   at NHibernate.Impl.AbstractSessionImpl.ProcessHelper.BeginProcess(AbstractSessionImpl session)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at HotChocolate.Types.Pagination.QueryableCursorPagingHandler`1.ResolveAsync(IQueryable`1 source, CursorPagingArguments arguments, CancellationToken cancellationToken)
   at HotChocolate.Types.Pagination.CursorPagingHandler.HotChocolate.Types.Pagination.IPagingHandler.SliceAsync(IResolverContext context, Object source)
   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)

Session is created through Autofac per life time scope, but looks like should be session per request, or maybe there are any options inside HotChocolate?

**Comment by michaelstaib** [comment]
@RomanVashchegin can you get onto slack? https://bit.ly/joinchilli

**Comment by michaelstaib** [comment]
We have now implemented automatic database mapping and released as a preview for Neo4J.

**Comment by raghavareddykv** [comment]
@michaelstaib. Really loved HotChocolate. The Development on it was a breeze. I have an enhancement suggestion, can we look into integrating Hasura like feature for automatic database mapping to generate schemas with out writing much code like you mentioned in this thread. But with a small kicker, it would be even more useful if the build workflow can generate the classes for every entity in the datastore as .cs files so adding additional features like validation and any custom tasks can be added to the appropriate methods by the developers. This way it can handle both schema generation and the flexibility to add more logic in one go in a more predictable way.  Let me know your thoughts on this, i would love to contribute to the project if you like it.

**Comment by h5aaimtron** [comment]
@michaelstaib is there any documentation to the automatic database mapping? I didn't see anything specific in the v12 or v13 docs around automatic mapping. Perhaps I missed it?
