### ISSUE TITLE
Add support for Apollo Federation

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#827]
https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#federation-schema-specification

We want to be able to consume services that use Apollo Federation and also expose federation schema in-case a user is using Apollo Federation instead of our schema registry.

**Comment by OneCyrus** [comment]
it would be really nice if the schema stitching of hotchocolate could use the apollo federation directives for schema stitching as well. this would help to separate the concerns of the different schemas.

**Comment by michaelstaib** [comment]
@OneCyrus 

We will add support for it, but we think that what we have come up with for our own platform is more powerful and we will focus first on our solution.

But since we are open to what other GraphQL implementations do we will support consuming Apollo federation services with our stitching platform. Moreover, we will support HC to be stitched into apollos federation gateway. 

However, we will implement that issue in the later 10.x releases ... 10.1 or 10.2 since we will focus on the schema registry first.

**Comment by robotrick** [comment]
@michaelstaib: is there any news about the support of apollo federation?

**Comment by michaelstaib** [comment]
This is what we can do today:
https://hotchocolate.io/docs/stitching

This very issue is scheduled for version 12 or 13.

**Comment by robotrick** [comment]
are you planing to implement federation schema earlier than version 12 or 13?

**Comment by michaelstaib** [comment]
No since we have out own stitching solution which will get a big feature upgrade with version 12 that goes beyond what federations can do.

**Comment by michaelstaib** [comment]
But we will be able to consume federation micro services.

**Comment by robotrick** [comment]
bad news, then we have to switch to graphqlnet :-( 
thank you for pointing out and your work on hot chocolate.

**Comment by michaelstaib** [comment]
@robotrick you do realize that you can add support fo this yourself by adding the Apollo federation directives.

We will just not add these to the core library. 

From our perspective we have to focus our efforts onto our platform which brings with version 11 so many new components.

But as I stated earlier our stitching gateway will out-of the box be able to consume federation micro services.

If you want to contribute a package containing Apollo Federation support we will be happy to host it.

If you want to move to another GraphQL server we are sad to see you leave since we invest a lot into this community and love how people engage and help each other on our slack channel.

If you need help creating directives feel free to join us on slack:
 https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by dillanmann** [comment]
Hi Michael, it seems from the explanation above that your integration with Apollo Spec federation is more "we can consume it" rather than "we can be integrated with it". Is this the case?

E.g. would a solution written in Hot Chocolate be able to be integrated into an existing Apollo federated gateway? or do you have to use the Hot Chocolate gateway to host the federated API?

**Comment by michaelstaib** [comment]
@dillanmann you can integrate it. What we have not done so far is providing an explicit integration package. If someone wants to contribute that we are open to that. But you can technically integrate any GraphQL compliant server with Apollo Federation, you just have to provide certain directives in your schema.

From our perspective we are working on a new Gateway that will bring much more to the table than federation can do at the moment. So we are fully focussing our energy on Hot Chocolate 11 and the new Hot Chocolate Gateway.

**Comment by michaelstaib** [comment]
This it is quite trivial to implement Apollo Federation support we will do it. Would have hoped that someone else would pick this up.

**Comment by michaelstaib** [comment]
We are abandoning the implementation of Apollo Federation in favor of our own solution.

**Comment by lefoulkrod** [comment]
@michaelstaib just wanted to provide some feedback on your decision.  We are going to need to move away from HC due to its lack of support for federation.   We have mostly node and less .net so we simply can't give up on federation.

**Comment by michaelstaib** [comment]
For us its more important to charter our own way and invest into our own solution for distributed graphs which works with any solution also with node. With the upcoming tooling there is better manageability, insights and better graph composibility. For us it is better to invest our time, which by the way is our free time that I could also spend with my three children, into our own project.

While I am sad to see any of our users go, I think we as a project are providing so much to our users for free in our free time that I really think this comment is really disrespectful of our work we do for the .NET OSS community.

**Comment by michaelstaib** [comment]
Also just saw that you have not starred a single OSS project. This is the easiest thing that you can do to provide something to the software you use for free. And I do not mean our project also all the components that you use in node, maybe apollo server. Also you are talking about apollo federation, also no star.

**Comment by lefoulkrod** [comment]
> For us its more important to charter our own way and invest into our own solution for distributed graphs which works with any solution also with node. With the upcoming tooling there is better manageability, insights and better graph composibility. For us it is better to invest our time, which by the way is our free time that I could also spend with my three children, into our own project.
> 
> While I am sad to see any of our users go, I think we as a project are providing so much to our users for free in our free time that I really think this comment is really disrespectful of our work we do for the .NET OSS community.

Hey, sorry if I came off as disrespectful that was not my intention.  I was only trying to provide some feedback as consumer of your project that I thought you might like to consider as you prioritize future work.  

I do appreciate all the work you and other OSS contributors do.  The world is a better place because of y’all!   

If at some point we decide to add federation support to HC I’ll do my best to have it open sourced and give back.
