### ISSUE TITLE
Stitching type renames fail with non null types

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#829]
We've been doing directive based renames in our stitching layer using an `ITypeRewriter` that has the following implementation.

``` csharp
public class RenameTypeRewriter : ITypeRewriter
{
	public ITypeDefinitionNode Rewrite(ISchemaInfo schema, ITypeDefinitionNode typeDefinition)
	{
		var renameDirective = typeDefinition.Directives.SingleOrDefault(d => d.Name.Value == DirectiveNames.Rename);

		if (renameDirective != null) {
			var newNameArgumment = renameDirective.Arguments.Single(a => a.Name.Value == DirectiveArgumentNames.Rename_Name);

			if (newNameArgumment.Value is StringValueNode stringValue) {
				return typeDefinition
					.WithDirectives(typeDefinition.Directives.Except(new[] { renameDirective }).ToList())
					.WithName(stringValue.Value);
			}
		}

		return typeDefinition;
	}
}
```

We've found this is failing when the type being renamed is used in a non-null field. When the type being renamed is only used in null fields then the rename works correctly when we view the stitched schema via the `/graphql/schema` endpoint.

I've verified the behavior also exists with the `RenameType` method in `StitchingBuilderExtensions`. 

I've pushed an [example of this issue](https://github.com/nigel-sampson/hc-directive-bug), running it as it looks right now fails with exception
> Unable to resolve type reference `Output: [Person]!`. - Type: Query

Changing [this line](https://github.com/nigel-sampson/hc-directive-bug/blob/master/StichingTest.GraphQL/Schema.graphql#L6) to 
```
people: [Person]
```
works correctly.

**Comment by michaelstaib** [comment]
@nigel-sampson as soon as I have figured this one out I will first integrate it in version 9.1.0.
After that we will port it back on the 9.0.x branch.

**Comment by michaelstaib** [comment]
Thanks for the repro on this one. I have found the bug. I will write a couple more tests and integrate it in the next build.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/pull/988
