### ISSUE TITLE
Properties are sorted alphabetically

### ISSUE THREAD

**Issue by RohrerF** [ChilliCream/hotchocolate#830]
**Describe the bug**
If I have a class like 

```csharp
public class User {
	public string Id {get; set;}
	public string Firstname{get; set;}
	public string Lastname {get; set;}
}
```

before the update to version 9 my Snapshot of the Schema looked like 

```graphql
type User{
	id: ID
	firstname: string
	lastname: String
}
``` 

but after the update to v9 it looks like this:

```graphql
type User{
	firstname: string
	id: ID
	lastname: String
}
``` 

This new behavior is probably caused by [this line](https://github.com/ChilliCream/hotchocolate/blob/c953a1c376df27e982214799fa3e79bf4091ceb1/src/Core/Types/Types/FieldCollection.cs#L22)

**Expected behavior**
I would like the properties in the Schema to be sorted as they are in my class and not alphabetically as they are now. The alphabetical sorting makes a schema harder to read.

**Comment by PascalSenn** [comment]
Just because of interest.
Why do you want the fields not sorted alphabetically?

**Comment by RohrerF** [comment]
In my opinion it makes more sense to have the fields sorted the same as they are in the actual class. For example I always put the ID of an entity on the top because it's the place I would expect it.

**Comment by PascalSenn** [comment]
@RohrerF  I think this was resolved a long time ago, gonna close this issue :)
