### ISSUE TITLE
ShowExceptionDetails Predicate

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#831]
I would like to be able to hide exception details, except for when I put a use a special user agent string in my browser or custom header

so on the server side when HC is deciding whether to show exception details It would allow me to run my own logic which returns true or false

so in this instance I could do something like
```
var options = new QueryExecutionOptions()
            {
                IncludeExceptionDetails = true,
                IncludeExceptionDetailsPredicate = (context) => {
                    var httpContext = context.Service<IHttpContextAccessor>().HttpContext;
                
                    var ua = httpContext.Request.Headers?["User-Agent"].ToString();
    
                    return ua.Contains("secretDevKey");
              })               
            };
```

**Comment by michaelstaib** [comment]
This would introduce HttpContext to the core of the execution engine and I want the execution engine to be free of those dependencies.

But I get what you want, I just think that this approach will not work.

**Comment by michaelstaib** [comment]
I think rather than putting in another option we can actually solve this with an error filter. We just need to get rid of the second dependency injection container that we are using right now and you would be able to inject the IErrorHandler as a service. By this you could add anything you want to your errors.

**Comment by michaelstaib** [comment]
I put this issue on V10 since we have full backlogs for the next to versions.

**Comment by drowhunter** [comment]
cool, I look forward to it.  I like the idea of using the error filter.

**Comment by drowhunter** [comment]
Now that #760 is done.  this can be worked on yes?
