### ISSUE TITLE
Enum values are not validated to the schema in a schema-first approach.

### ISSUE THREAD

**Issue by gregsdennis** [ChilliCream/hotchocolate#833]
**Describe the bug**
It doesn't appear that enumeration values are validated against the schema in a schema-first approach.

**To Reproduce**
1. Create a schema that contains an enumeration (e.g. `ZERO`, `ONE`, `TWO`).
2. Create an associated enum in C# and bind it to the schema enum.
    - Add a `Three` value to the C# enum, but *not* the schema enum.
3. Create a mutation that accepts the enum as an input.
4. Call the mutation and pass `THREE` for the enum field.

**Actual behavior**
`THREE` is accepted and translated to `Three` in the C# enum.

**Expected behavior**
HotChocolate should reject `THREE` since it's not a valid value according to the schema.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
- .Net Core 2.1

**Comment by hrai** [comment]
@gregsdennis is there a code example of schema binding for the enum type where you do NOT map `Three` to the schema?

**Comment by gregsdennis** [comment]
Schema:

```graphql
enum MyValue {
  ZERO
  ONE
  TWO
}

mutation {
  setMyValue(myValue: MyValue): Boolean!
}
```

Code:

```c#
public enum MyValue {
    Zero,
    One,
    Two,
    Three
}

public class Mutation {
    public bool SetMyValue(MyValue myValue) => return true;
}
```

With this setup, I can pass in `THREE` and the validation logic will accept it because it maps to a value on the underlying C# enumeration type.  However, because it's not listed in the schema (and we're using a schema-first approach), this value should be rejected.

**Comment by michaelstaib** [comment]
I am pretty sure this is fixed on 11.
