### ISSUE TITLE
Float type not included in default types in 9.0

### ISSUE THREAD

**Issue by jkporter** [ChilliCream/hotchocolate#835]
**Describe the bug**
When using schema-first approach errors were throw for Float fields. Manually adding Float seemed to fix the issue. Since this is a standard scalar I would suspect this would be supported w/o having to manually add it.

**To Reproduce**
1. Create schema with fields that have a return type of Float!
2. User schemabuilder to create schema from document.

**Expected behavior**
```
var builder = SchemaBuilder.New()
                .AddServices(new Dependencies().BuildServiceProvider())
                .AddDocument(document)
                .AddType<DecimalType>()
                // .AddType<FloatType>() // Should not be required?
                .AddCustomTypes(typeNames)
                .BindModels(typeNames)
                .BindResolvers(typeNames);
```

**Comment by michaelstaib** [comment]
If that is so, than this is a bug and we might have introduced it with the new schema builder. I will look at this tomorrow.

**Comment by michaelstaib** [comment]
I just quickly checked the code and it does seem right. Can you send me you SDL so I can repro the issue?

**Comment by michaelstaib** [comment]
```
.AddType<DecimalType>()
                // .AddType<FloatType>() // Should not be required?
                .AddCustomTypes(typeNames)
```

Both should not be needed. Since. we should be able to figure both out with schema first.

**Comment by jkporter** [comment]
Not sure it's a SDL i'm ready to share publicly but I'll see if can isolate it to just the types that were failing and provide just that bit.

**Comment by michaelstaib** [comment]
@jkporter and news on a repro?

**Comment by michaelstaib** [comment]
we have the following unit test:

```csharp
        [Fact]
        public void BuiltInScalarsAreRecognized()
        {
            // arrange
            string sourceText = @"
                type Query {
                    string_field: String
                    string_non_null_field: String!
                    int_field: Int
                    int_non_null_field: Int!
                    float_field: Float
                    float_non_null_field: Float!
                    bool_field: Boolean
                    bool_non_null_field: Boolean!
                }
            ";

            // act
            ISchema schema = SchemaBuilder.New()
                .AddDocumentFromString(sourceText)
                .Use(next => context => Task.CompletedTask)
                .Create();

            // assert
            schema.ToString().MatchSnapshot();
        }
```

**Comment by jkporter** [comment]
Didn't have time to test my original setup but removed Add float from my production schema in 9.0.4 and it's no longer errorring.
