### ISSUE TITLE
Extended input validation like with GraphQL-java

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#841]
https://github.com/bbakerman/graphql-java-extended-validation

**Comment by Dblike** [comment]
I would really love to see this as I'm currently using ValidationAttributes in our business objects, but it'd be nice to be able to extend those attributes to the input validation. I think the GraphQL-Java project already covers the large majority of use cases, and would probably be a good place to start. We already make use of analogs for Size, PositiveOrZero, and Min/Max

**Comment by michaelstaib** [comment]
@Dblike sure. We cannot do it like the java guys did it I think. They are building a context for each argument which would be kind of slow and produces a lot of garbage for the GC.

**Comment by michaelstaib** [comment]
@Dblike can you start with the directives... When you have done that we can have a look at the actual validation rule.

**Comment by michaelstaib** [comment]
@Dblike I have talked to Nigel and we will wait for his implementation. I think from what I have seen so far it looks quite good and with some additions it might also work on sdl-first. So, I put this on hold for now.

**Comment by PascalSenn** [comment]
We have many great extension for hotchocolate for this use case
[See here for more info](https://github.com/ChilliCream/hotchocolate/blob/main/COMMUNITY.md#validation)
