### ISSUE TITLE
Overriding scalar types gives unhelpful error

### ISSUE THREAD

**Issue by KereyWatters** [ChilliCream/hotchocolate#847]
**Describe the bug**
When I create a new type with the same name as a scalar - e.g. Date, I get 
`HotChocolate.SchemaException: Unable to resolve type reference 'Output: String'. - Type: PhoneNumber` which doesn't match the reason it failed. PhoneNumber is another type in my schema, which has a String field in it.

**To Reproduce**
1. In an existing, working schema, add:
```
type Date {
	isValid: Boolean
}
```
2. Try to run application

**Expected behavior**
A message along the lines of: type Date is already defined as a scalar

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by michaelstaib** [comment]
Did you also declare the usage of the `Date` scalar?

**Comment by michaelstaib** [comment]
Could you provide more of your schema so that I can do a repro?

**Comment by KereyWatters** [comment]
This was schema first, though Date is also being auto-generated in the ISchema as a scalar alongside the type. I'll try to create a sample project today 👍

**Comment by michaelstaib** [comment]
@KereyWatters any update? Do you have a repro so that we can fix this? We are wrapping up version 9.1 and it would be great to fix this.
