### ISSUE TITLE
XML documentation generated in Schema differs between machines

### ISSUE THREAD

**Issue by elliot-whiley** [ChilliCream/hotchocolate#850]
**Describe the bug**
XML documentation generated in the Schema differs between local machine and on our build agent. Seems to be dependent on the file `C:\Users\{user}\.nuget\packages\hotchocolate.aspnetcore.authorization\9.0.1\lib\netstandard2.0\HotChocolate.AspNetCore.Authorization.xml` which is present locally, but not on the build agent. If we delete this file locally and generate the schema, it matches the build agent.

Local:
![image](https://user-images.githubusercontent.com/15881389/59717445-1cded680-926c-11e9-9200-41b5e4fec093.png)

Build agent:
![image](https://user-images.githubusercontent.com/15881389/59717463-236d4e00-926c-11e9-831e-4428d0a05e78.png)

**To Reproduce**
1. Generate Schema e.g. via unit test in a project referencing HotChocolate, something similar to:
```
[Fact]
public void VerifySchema()
{
	using (var lifetimeScope = Container.BeginLifetimeScope()) {
		var schema = lifetimeScope.Resolve<ISchema>();
		var serializedSchema = SchemaSerializer.Serialize(schema);
		ApprovalTests.Approvals.Verify(serializedSchema);
	}
}
```
2. Run unit test locally with local `C:\Users\{user}\.nuget\packages\hotchocolate.aspnetcore.authorization\9.0.1\lib\netstandard2.0\HotChocolate.AspNetCore.Authorization.xml`  file present (should be there by default if your project is referencing HotChocolate via nuget).
3. Delete `C:\Users\{user}\.nuget\packages\hotchocolate.aspnetcore.authorization\9.0.1\lib\netstandard2.0\HotChocolate.AspNetCore.Authorization.xml`  file and run test against.
4. Observe differences in XML documentation between the 2 test runs.

**Expected behavior**
XML documentation generated in Schema should be the same regardless of what machine the Schema is generated from and what other local nuget files are present.

**Desktop:**
 OS: Windows 10

**Additional context**
Referencing HotChocolate.AspNetCore v9.0.1.

**Comment by gregsdennis** [comment]
It should be noted that we use `dotnet publish` on our build server.  This has issues pulling non-DLL files from Nuget packages.

https://github.com/dotnet/sdk/issues/1458
https://github.com/dotnet/cli/issues/9478

**Comment by michaelstaib** [comment]
This one should now be fixed with preview.24. Can you two confirm this?

**Comment by elliot-whiley** [comment]
@michaelstaib on preview.24, my local machine produces: 
![image](https://user-images.githubusercontent.com/15881389/60849920-1a571780-a241-11e9-9a10-9bd298b44ae7.png) which is different to what it used to.  I can't tell what the build agent produces for this exact line until I can work out how to get the whole file off the build agent. Currently I can only see a snippet of what lines didn't match.

This also introduced a few other mis-matches for example on deprecated fields in the schema:
![image](https://user-images.githubusercontent.com/15881389/60850084-c4cf3a80-a241-11e9-9a42-0b9c5b821859.png)
Left is the result running locally, right is the result on the build agent.

**Comment by elliot-whiley** [comment]
I believe the original problem is solved, as our original workaround was to delete `C:\Users\{user}\.nuget\packages\hotchocolate.aspnetcore.authorization\9.0.1\lib\netstandard2.0\HotChocolate.AspNetCore.Authorization.xml` before generated the schema so it would match the build agent (which didn't have this file). Now when I delete this file, it seems the output is consistent. So I think the issue above is caused by something different

**Comment by elliot-whiley** [comment]
Looks like we have an outstanding issue to include the XML file in our build agent which should fix this. Will resolve for now, thanks for the help Michael
