### ISSUE TITLE
Field middleware not working for introspection fields

### ISSUE THREAD

**Issue by mIkhail-zaretsky** [ChilliCream/hotchocolate#853]
**Describe the bug**
Field middleware is not executing for introspection fields

**To Reproduce**
1. Please check https://github.com/ChilliCream/hotchocolate/pull/852
2. Data for introspection field is not touched

**Expected behavior**
Middleware should work for all fields. As an option, could you please suggest how I can distinguish introspection query and add additional logic for it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 9.0.4

**Comment by michaelstaib** [comment]
Sorry for the wait ... will tell you how this works tomorrow.

**Comment by mIkhail-zaretsky** [comment]
@michaelstaib , sorry for disturbing you, but could you please point me to the right place where I can add additional security check (special scope) for introspection query?
Thanks in advance

**Comment by michaelstaib** [comment]
Hi, sorry for letting that hang so long. When we designed hc we did on purpose exclude middlewares from introspection resolvers since by adding transformations you could make your server non-spec compliant. 

Reflecting on that we could opt to allow this with an additional schema option. I will move this to the next release.

**Comment by michaelstaib** [comment]
OK, this one is supported with 9.1 preview 44

```csharp
[Fact]
        public async Task FieldMiddlewareHasAnEffectOnIntrospectIfSwitchedOn()
        {
            // arrange
            string query = "{ __typename a }";

            ISchema schema = SchemaBuilder.New()
                .AddQueryType<Query>()
                .Use(next => async context =>
                {
                    await next.Invoke(context);

                    if (context.Result is string s)
                    {
                        context.Result = s.ToUpperInvariant();
                    }
                })
                .ModifyOptions(o =>
                    o.FieldMiddleware = FieldMiddlewareApplication.AllFields)
                .Create();

            IQueryExecutor executor = schema.MakeExecutable();

            // act
            IExecutionResult result = await executor.ExecuteAsync(query);

            // assert
            Assert.Empty(result.Errors);
            result.MatchSnapshot();
        }
```
