### ISSUE TITLE
Serialized directive definitions do not follow the GraphQL Specification

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#855]
As part of #716 directive definitions are not included in the serialized schema. It looks like the format does not follow the [specification](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives).

For example in a stitched schema the `@source` directive is used. It's current serialization looks like the following:
```
"Annotates the original name of a type."
directive @source("The original name of the annotated type." name: Name! "The name of the schema to which this type belongs to." schema: Name!) repeatable on Enum | Object | Interface | Union | InputObject | FieldDefinition | InputFieldDefinition | ArgumentDefinition | EnumValue
```

I would expect something like
```
"Annotates the original name of a type."
directive @source("The original name of the annotated type." name: Name! "The name of the schema to which this type belongs to." schema: Name!) on ENUM | OBJECT | INTERFACE | UNION | INPUT_OBJECT | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE
```
The important differences besides the casing on the locations are:
1. The `repeatable` concept for directives is not part of the specification.
2. `FieldDefinition` vs `FIELD_DEFINITION`.

**Comment by michaelstaib** [comment]
> The repeatable concept for directives is not part of the specification.

Repeatable is becoming part of the draft specification. We are implementing features once they become draft status.

https://github.com/graphql/graphql-spec/pull/472/files

**Comment by nigel-sampson** [comment]
Thought it may be something like that and checked the [draft specifications](https://graphql.github.io/graphql-spec/draft/). what's the official status if it hasn't actually been merged yet?

This leaves us in a bit of a tough place as a lot of other tools such as [GraphQL Code Generator](https://graphql-code-generator.com/) don't support that unpublished draft spec.

**Comment by michaelstaib** [comment]
But are you using isrepeatable?
