### ISSUE TITLE
Playground not working if GraphQL path is set

### ISSUE THREAD

**Issue by sgt** [ChilliCream/hotchocolate#877]
I don't really get the new `PlaygroundOptions` logic, but the `_pathIsSet` variable seems to be always false, and therefore the playground is broken when the path is set manually via options.

```csharp
            app.UseGraphQL("/g");
            app.UsePlayground(new PlaygroundOptions {QueryPath = "/g"});
```

When the `/playground` url is accessed in this setup, 404 is returned.

**Comment by michaelstaib** [comment]
Hi @sgt,

sorry for the wait. There seems to be a copy paste error here.

I will add some tests and fix the options class.

**Comment by michaelstaib** [comment]
You can follow this here  #984

**Comment by michaelstaib** [comment]
This one is now fixed and will be included into V10 preview 52.

**Comment by skmunichetty** [comment]
This worked for me 
app.UsePlayground(new PlaygroundOptions { QueryPath = "/graphql", Path = "/playground" });
