### ISSUE TITLE
Review coercion rules regarding default values

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#878]
> That means whenever the argument is null we take the default reason.

We have to change it to this: That means whenever the argument is not provided we take the default reason.

We did the above rule wrong regarding to directive arguments and should fix this. There is however some issue here. When something was provided as a .net object than we cannot really detect if something was provided or is null.

**Comment by tobias-tengler** [comment]
Closing in favor of #4179
