### ISSUE TITLE
AuthorizeMiddle does not honor updated User

### ISSUE THREAD

**Issue by willwolfram18** [ChilliCream/hotchocolate#880]
**Describe the bug**
When using `QueryMiddlewareOptions` to assign a new `HttpContext.User` value, the `AuthorizeMiddleware` does not honor the updated `ClaimsPrincipal` value. This creates a problem where developers may want to include authorization in their application, but not enforce it while doing local development to expedite the development process.

**To Reproduce**
1. Create a new ASP.NET Core project using Hot Chocolate and the HotChcolate.AspNetCore.Authorization package.
2. When creating the schema, register the authorization middleware using the [extension method outlined in the Hot Choclate docs](https://hotchocolate.io/docs/authorization#authorization).
3. In the `Configure(IApplicationBuilder)` method where the GraphQL middleware is added, use the `UseGraphQL()` overload that takes a `QueryMiddlewareOptions` object and configure the `OnCreateRequest` method to update the `httpContext.User` property.
```
app.UseGraphQL(new QueryMiddlewareOptions
{
    OnCreateRequest = (httpContext, requestBuilder, cancellationToken) =>
    {
        if (Environment.IsDevelopment() && !httpContext.User.Identity.IsAuthenticated)
        {
            // User.Identity.IsAuthenticated is only true when an authentication type is specified
           // in the claims identity. So we overwrite the User with an "IsAuthenticated" identity.
            var localIdentity = new ClaimsIdentity("LocalDevelopment");
            httpContext.User = new ClaimsPrincipal(localIdentity);
        }
        return Task.CompletedTask;
    }
});
```
4. Start application and execute a query on a field that requires authorization.

**Expected behavior**
The request should execute the query and return the appropriate result for the field(s) specified. 

**Desktop:**
 - OS: Windows 10 
 - Version 9.0.4

**Additional context**
The goal my tea is trying to accomplish is placing an `AuthorizeDirective` on the `Query` type itself to enforce authorization to even access the API. Then we will be more specific with fields on the root `Query` type.

Again, to make development faster and easier, we want to be able to allow local development to skip the authorization process but setting up a basic `ClaimsPrincipal` that is seen as authenticated.

It looks like the issue is that the `AuthorizeMiddleware` is using the `ClaimsPrincipal` key, which does not contain the updated `User`, however the `HttpContext` key *does* have the updated User. So this could likely be solved by using the `HttpContext` directly, or ensuring that the `ClaimsPrincipal` key in the context data is updated after the `OnCreateRequest` delegate is executed.

**Comment by willwolfram18** [comment]
* Example repo with 9.0.4: https://github.com/willwolfram18/hotchocolate/tree/bugreport/setting-user-in-middleware-is-ignore-9.0.4

* Example repo with latest in master: https://github.com/willwolfram18/hotchocolate/tree/bugreport/setting-user-in-middleware-is-missing
    * This appears to have a larger issue in that the `IHttpContext` abstraction is preventing the `HttpContext` from getting updated at all. Which means the `AuthorizeMiddleware` now has no way to access an updated identity.

**Comment by michaelstaib** [comment]
this is now implemented:
https://github.com/ChilliCream/hotchocolate/commit/538f3ca9b9909de8d591b9e21ffd0433b2fccac6

**Comment by michaelstaib** [comment]
we will ship it with preview-33
