### ISSUE TITLE
Authorization returns wrong http code

### ISSUE THREAD

**Issue by pustun** [ChilliCream/hotchocolate#900]
I've added your authorization directive to decorate some queries. And it works fine but it returns 200 code if user is not athenticated. Do I miss something or it's not how http based API suppose to work.
![2019-07-08_18-38-50](https://user-images.githubusercontent.com/5030240/60823566-76259000-a1b0-11e9-89e5-891088864980.png)

**Comment by michaelstaib** [comment]
It's common practice to use `200` for all GraphQL requests. 

When errors happen, they're put in the "errors" collection. 

Non-200 response codes indicate that some issue occurred at the HTTP transport layer, not the GraphQL layer.

**Comment by michaelstaib** [comment]
https://github.com/APIs-guru/graphql-over-http

**Comment by pustun** [comment]
Cool, thanks for your explanation.
