### ISSUE TITLE
Support `ITypeRewriter` and `IDocumentRewriter` on regular schemas

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#904]
The `IDocumentRewriter` and `ITypeRewriter` interfaces allow you to programmatically rewrite parts or all of your schema. Currently these are only supported in stitched schemas, but not regular ones.

These interfaces are useful for adding cross cutting concerns across an entire schema in a convention based approach.

One use case we have in mind is to apply a piece of validation middleware to all fields that take arguments. Doing it this way means it happens automatically and creates a "pit of success".

**Comment by michaelstaib** [comment]
With the introduction of the new type- and schema-interceptor adding cross-cutting functionality is now possible.
