### ISSUE TITLE
Null propagation/guard when stitching schemas

### ISSUE THREAD

**Issue by anadale** [ChilliCream/hotchocolate#909]
**Is your feature request related to a problem? Please describe.**
Sometimes we can predict that the value of the delegated field will be null if one of the arguments for that field is null, for example:

```graphql
# Schema: Users
type User {
 avatarImageId: ID
}

# Schema: Images
type Query {
  imageUrl(id: ID): String
}
``` 

Extending type `User` we add an `avatarImage` field delegated to the `Images` service:

```graphql
extend type User {
  avatarImage: String @delegate(schema: "Images", path: "imageUrl(id: $fields:avatarImageId)")
}
```

However, we know for sure, that the result of resolving an `imageUrl` field with `null` as an argument will be `null` as well. Moreover, the `imageUrl` can be defined with a non-nullable argument and calling field `imageUrl` with a `null` is prohibited.

**Describe the solution you'd like**
A `@nullGuard` directive that will tell stitching engine that execution can be shortcutted in case of `null` argument:

```graphql
extend type User {
  avatarImage: String @delegate(schema: "Images", path: "imageUrl(id: $fields:avatarImageId)") @nullGuard(check: "$fields:avatarImageId")
}
```

**Comment by PendingChanges** [comment]
Have you any workaround on that issue for now?
We are facing the same predictions about our fields being null before calling the delegated schema.
Thanks in advance.

**Comment by ylukomskyi** [comment]
I am facing the same issue, having `@nullGuard` would be really helpful. Are there any plans to add this feature to hotchocolate?

**Comment by jfheins** [comment]
This is still an area of interest for me... it it not coming then?
