### ISSUE TITLE
Make descriptor default binding behavior explicit

### ISSUE THREAD

**Issue by glucaci** [ChilliCream/hotchocolate#918]
Currently when a `InputObjectType` or `ObjectType` is described, must always set `BindingBehavior.Explicit`
```csharp
public class MyInputType : InputObjectType<MyInput>
{
    protected override void Configure(
        IInputObjectTypeDescriptor<MyInput> descriptor)
    {
        descriptor.BindFields(BindingBehavior.Explicit);
        
        // .. configure
    }
}
```

If this is not set, all the properties of the given type will be exposed.

It will be much "explicit" to have as default `BindingBehavior.Explicit` and possibility to switch on `BindingBehavior.Implicit` by registering the appropriate convention.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IBindingConventions, ImplicitBindingConvention>();
}
```
or more user friendly
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddImplicitBindingConvention();
}
```

**Comment by michaelstaib** [comment]
This one is not implemented.... the default binding can be specified as a schema option.
