### ISSUE TITLE
Filters: Implement Object Filters

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#921]
scroll down for the description :)

**Comment by PascalSenn** [comment]
# Object Filters 

## Introduction
Filters for scalars will be released in V10. In a upcomming release also nested object filters will be supported. This gives you the ability to filter deep inside a object tree. 

## Proposal
### Example Objects
All examples will take place in the following domain:
```csharp
public class Foo {
     public Bar bar {get;set;}
}

public class Bar {
     public string baz {get;set;}
     public int blub {get;set;}
}
```

### Proposal
Nested object filters in HotChocolate will look like the following example: 
```graphql
query {
  foos(where: {bar: {blub_gt: 18}}) {
    bar {
      baz
      blub
    }
  }
}
```



### How others did it
#### Prisma
```graphql
query {
  foos(where: {
    bar: {
      blub_gt: 18
    }
  }) {
    bar {
      baz
      blub
    }
  }
}
```

#### Horsura 
```graphql
 query {
   foos(where: {bar: {blub: {_gt: 18}}}) {
    bar {
      baz
      blub
    }
  }
}
```

#### Gatsby 
```graphql
query {
  foos(
    filter: {
      bar: { blub: {gt: 18} }
  	}
  ) {
   bar {
      baz
      blub
    }
  }
}
```

#### GraphCMS
```graphql
query {
  foos(where: {bar: {
               blub_gt: 18
             }
  }) {
   bar {
      baz
      blub
    }
  }
}
```

**Comment by PascalSenn** [comment]
Schema generation of nested types is done  in #929

**Comment by MaximS** [comment]
IMHO, combining field names and operators is a bad idea. One gets some artificial names that do not correspond to anything meaningful. Of course, Prisma is a big player, so probably supporting both styles worths the efforts.

**Comment by michaelstaib** [comment]
@MaximS with hot chocolate you can overwrite the inferred defaults here by providing your own filter type. You can define what operators you want to include and how those are named. If you want to drive that even further you can change the structure of those field types.

Personally, I quite like the way prisma solved the issue here, it reminds me a lot of how you write query objects with mongo. Hasura is even closer to how you would write a query in mongo.

Mongo Query Example

```
db.inventory.find( { status: { $in: [ "A", "D" ] } } )
``` 

So, in regards to the GraphQL limitations in input objects I think the prisma style is quite nice.

Also, such a query graph translates really well to native database queries. We have implemented this in a way that you can inherit from our filter visitor any by visiting the filter graph with a depth-first algorithm you can create your database query. We have ready-to-go implementations for mongo and queryable so if you use any database layer that provides its data through `IQueryable` the filters are plug-and-play.

**Comment by nkovacic** [comment]
@michaelstaib is there any ETA on release of object filters? Saw they are already merged to [master](https://github.com/ChilliCream/hotchocolate/pull/929)..
Can they be used in 11 preview versions?

**Comment by michaelstaib** [comment]
They are already available in the current preview builds, also array filters are already implented and available in the preview builds...

And yes they are in the master
https://github.com/ChilliCream/hotchocolate/blob/26f4d521867f5e7ba5cf7c60955701e491a3e8b0/src/Core/Types.Filters.Tests/QueryableFilterTests.cs#L139

**Comment by ShaikhShakeebAhmed** [comment]
Really need this any updates on release dates ? . is it included in 10.5 ?

**Comment by PascalSenn** [comment]
It has all been im place and was working but currently we are doing a rewrite more into the direction that hasura took.  Going the prisma way was not ideal. Turns out @MaximS  was right ;)

**Comment by ShaikhShakeebAhmed** [comment]
ahh means more wait for this to be released. is there any temporary workaround  to this currently ?

**Comment by moamen-naanou** [comment]
Any update on this please? or any workaround?

**Comment by jorgeolive** [comment]
So, what is the current status for this? Is there an open issue / feature request we can track?

**Comment by ShaikhShakeebAhmed** [comment]
Its added in 11.0.0 when ever that is going to be.
