### ISSUE TITLE
Filters: IEnumerable Filters

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#922]
Scroll down for the description :)

**Comment by PascalSenn** [comment]
# IEnumerable Filters 

## Introduction
Filters for scalars will be released in V10. In a upcomming release also nested object filters will be supported. To complete full support of filters we also need array filters. Array filters can either be used with object filters or with scalars. 

We do need some kind of abstraction for scalars filters. In case of a scalar collection we need to introduce some kind of object. 
```graphql
{
    foos(where: { roles_every: {el:"test"}) { ... }
}
```

## Proposal
### Example Objects
All examples will take place in the following domain:
```csharp
public class Foo {
     public IEnumerable<string> roles {get;set;}
     public Bar[] bars {get;set;}
}

public class Bar {
     public string baz {get;set;}
     public int blub {get;set;}
}
```
### Words
Suggested words in the following examples like `every`, `some`, `el` will be part of the `NamingConvention` and can be customized by the user. 

### Scalar Abstraction 
For scalars we need to introduce an abstraction. 
```graphql
{
    foos(where: { roles_every: {el:"test"}) { ... }
}
```
Suggested is one of the following: 
- [ ] `elm` (for element)
- [ ] `el` (for element but shorter
- [ ] `item`

### Proposal
To have complete support for all possible ways of filtering, we will need different types of filters. 

#### Every / All
This filters returns when all of the items in the array evaluate to true. 

##### Possible Words 
- [ ] `every`
- [ ] `all`

##### Example 
```graphql
query {
  foos(where: {
       roles_all: {
              el: "test"
           }
        }
        bars_all: { bar: "test"}) {
    bar {
      baz 
    }
  }
}
```

#### Some 
This filters returns when at least one of the items in the array evaluate to true. 

##### Possible Words 
- [ ] `some`

##### Example 
```graphql
query {
  foos(where: {
       roles_some: {
              el: "test"
           }
        }
        bars_some: { bar: "test"}) {
    bar {
      baz 
    }
  }
}
```


#### None
This filters returns when none of the items in the array evaluate to true. 

##### Possible Words 
- [ ] `none`

##### Example 
```graphql
query {
  foos(where: {
       roles_none: {
              el: "test"
           }
        }
        bars_none: { bar: "test"}) {
    bar {
      baz 
    }
  }
}
```



### How others did it
#### Prisma
```graphql
{
  foos(where: { bars_every: {bar: "test"}) {
    bar {
      baz
    }
  }
}

{
  foos(where: { bars_some: {bar: "test"}) {
    bar {
      baz
    }
  }
}

{
  foos(where: { bars_none: {bar: "test"}) {
    bar {
      baz
    }
  }
}
```

#### Horsura 
```graphql
{
  foos(where: {roles: {el: "test"}}, bars: {bar: "test"}) {
    bar {
      baz
    }
  }
}

# No Implemenation of some

{
  foos(where: {_not: {roles: {el: "test"}}, bars: {bar: "test"}}) {
    bar {
      baz
    }
  }
}
```

#### Gatsby 
```graphql
# No Example Found
```

#### GraphCMS
```graphql
{
  foos(where: { bars_every: {bar: "test"}) {
    bar {
      baz
    }
  }
}

{
  foos(where: {bars_some: {bar: "test"}) {
    bar {
      baz
    }
  }
}

{
  foos(where: { bars_none: {bar: "test"}) {
    bar {
      baz
    }
  }
}
```

**Comment by SlyNet** [comment]
Is there a way to implement it in 11.0.0-preview.117 version without this issue implemented?
