### ISSUE TITLE
Filters: Support for sorting

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#923]
Scroll down for the description:

**Comment by PascalSenn** [comment]
# Support for Sorting
## Introduction
The ability to sort data is necessary for paging. Furthermore is sorting in the backend with loads of data often way faster than sorting in the frontend. 

## Proposal
Scalars and nested objects can be sorted ascending (ASC) and descending (DESC). For all fields that support sorting a input object is generated. This input object has fields of a enum input type. The input type supports ASC and DESC. 

### Example Objects
All examples will take place in the following domain:
```csharp
public class Foo {
     public string role {get;set;}
     public Bar bars {get;set;}
}

public class Bar {
     public string baz {get;set;}
     public int blub {get;set;}
}
```
### Sorting Order / Prioritization 
The order of the different fields defines the order of the sortings. The order is preserved as specified in the graphql spec: https://graphql.github.io/graphql-spec/draft/#sec-Objects

>GraphQL Objects represent a list of named fields, each of which yield a value of a specific type. Object values should be serialized as ordered maps, where the queried field names (or aliases) are the keys and the result of evaluating the field is the value, ordered by the order in which they appear in the query.

### Example
```graphql
{
  foos(order_by: { role: ASC,  bar: {baz: DESC}}) {
    bar {
      baz
    }
  }
}
```


### How others did it
#### Prisma
```graphql
# Prisma does not support nested and multi field sorting
{
  foos(orderBy: role_ASC) {
    bar {
      baz
    }
  }
}
```

#### Horsura 
```graphql
{
  foos(order_by: { role: asc,  bar: {baz: desc}}) {
    bar {
      baz
    }
  }
}
```

#### Gatsby 
```graphql
 {
  foos(sort: {
      fields: [role, bar__baz]
      order: ASC
    })
  bar {
      baz
    }
  }
}
```

#### GraphCMS
```graphql
### no example found
```

**Comment by michaelstaib** [comment]
@PascalSenn do you know how others by default name the sort classes?

**Comment by michaelstaib** [comment]
@gmiserez @PascalSenn 

Open Issues:

- [ ] Add support for child property sorting
- [ ] Add support for directives on sort fields
- [ ] Default naming of the sort type is not clear yet

**Comment by michaelstaib** [comment]
I will merge #1022 and build preview 3 now ... then we can see how it feels and decide on how to implement the open issues with it.

**Comment by PascalSenn** [comment]
@michaelstaib  sorry totally lost track of this issue.  Was around the time I was in service. 

##Default naming
####Prisma
[image](https://user-images.githubusercontent.com/14233220/66699193-d31b6f80-ece4-11e9-8297-a3b93df2bf77.png)
#### Hasrua
![image](https://user-images.githubusercontent.com/14233220/66699285-c21f2e00-ece5-11e9-8a00-9de7157cfed6.png)


I personally think OrderBy makes sense too. This is what the type really does right?. 

I will start working on the nested sorting stuff any time soon. 

What do we need directives for? 

We should really also configure a way to handle the sort Enum. As those are input types we really need to have a configurable API so a migrations does not mean breaking changes in the frontend.

**Comment by michaelstaib** [comment]
@PascalSenn  this one is done or?

**Comment by PascalSenn** [comment]
This one is done
