### ISSUE TITLE
Unable to use @include or @skip when stitching

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#937]
**Describe the bug**
Stitched queries that use `@include` or `@skip` directives that refer to a variable return a message that the variable is not declared. This effectively means that @include and @skip don't work when stitching as the primary use-case would be having them handle a variable.

**To Reproduce**
1. Create a stitched schema
2. Attempt to use an `@include` directive with a boolean field in playground. For example:
```
query TEST($ok:Boolean!) {
  hey {
    hello @include(if:$ok)
  }
}
```
3. Note the error: `"The following variables were not declared: YOUR_VARIABLE."`

**Expected behavior**
Same behavior as if the literal `true` or `false` were passed to the `@include` directive.

**Additional context**
In some limited debugging, it looks like these variables are not in  the `_usedVariables` list in `AllVariablesUsedVisitor.cs`, I'm guessing they're not being sent to the client endpoint, but I haven't dug-in that deep.

**Comment by michaelstaib** [comment]
OK, this one is more complicated :) the query rewriter does not correctly visit the directive hence the variables are not touched. I will look at this tomorrow.

**Comment by michaelstaib** [comment]
This bug is now fixed.
