### ISSUE TITLE
Factory expression for custom dataloader compiles every request

### ISSUE THREAD

**Issue by DaniilSokolyuk** [ChilliCream/hotchocolate#938]
**Is your feature request related to a problem? Please describe.**
Factory expression for custom dataloader compiles every request because IDataLoaderRegistry is scoped

https://github.com/ChilliCream/hotchocolate/blob/a09c4a2884726b54bffc440338bb8d1a2421c704/src/Core/Types/DataLoader/DataLoaderResolverContextExtensions.cs#L319

**Describe the solution you'd like**
Ideally making _factories field in DataLoaderRegistry - static if possible, it will also reduce the number of allocations

**Comment by michaelstaib** [comment]
We have reworked this part.
