### ISSUE TITLE
Deadlock in BatchOperationHandler

### ISSUE THREAD

**Issue by DaniilSokolyuk** [ChilliCream/hotchocolate#941]
**Describe the bug**
I got deadlock in dataloader mechanism 

**To Reproduce**
When https://github.com/ChilliCream/hotchocolate/blob/090a84bc9271e2a1bee67f9f22755dd84e4c18c7/src/Core/Core/Execution/Utilities/BatchedOperationHandler.cs#L37
gets 2 tasks (from execution strategy) and if one Task is completed  then dataloader batch operation is not invoked

I think this was due to incorrect refactoring. https://github.com/ChilliCream/hotchocolate/commit/4c9cb95f0cde3ca2711bbaa66fb0dc7f8a6f6491#diff-749e6c72c58e4879fb9c5720ca8638c5R50

I think there should be "Any"

**Comment by michaelstaib** [comment]
We will merge this into preview 40 tomorrow.

**Comment by michaelstaib** [comment]
Just as a hint, we also have a slack channel ...
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q
