### ISSUE TITLE
Passing variable to single value in complex input type ends up sending null value

### ISSUE THREAD

**Issue by rolfwessels** [ChilliCream/hotchocolate#945]
**Describe the bug**
Passing variable to single value in complex input type ends up sending null value

**To Reproduce**
1. Setup a mutation with `String!` and second with complex input type.
2. Send the following variables 
```json
{
  "id":"123",
  "name":"does not populate"
}
```
2. The following query works as expected
```graphql
mutation updateProject($id: String!) {
  projects {
    update(id: $id, project: { name: "works"}) {
      id
    }
  }
}
```
3. The following example will populate the id as expected but populates a null name value
```graphql
mutation updateProject1($id: String!, $name: String!) {
  projects {
    update(id: $id, project: { name: $name }) {
      id
    }
  }
}
```

**Expected behavior**
```graphql
mutation updateProject1($id: String!, $name: String!) {
  projects {
    update(id: $id, project: { name: $name }) {
      id
    }
  }
}
```
Should populate the project.name with the $name variable (eg."does not populate")

**Desktop :**
 - OS: Windows10
 - Version 9.0.4

**Comment by michaelstaib** [comment]
This one is fixed in the preview builds.

**Comment by michaelstaib** [comment]
I am closing this since it is fixed.

**Comment by rolfwessels** [comment]
Thank you. Updated and it is resolved.

**Comment by michaelstaib** [comment]
@rolfwessels  we will release the next version end of next week ...

**Comment by rolfwessels** [comment]
@michaelstaib I've been using graphql-dotnet for about a year now (for work and personal projects). I started converting my personal projects over to hot-chocolate and I have to say I am loving it. The API is a lot cleaner and consistent. With graphql-dotnet I had to hack it a bit to enable proper error filters and with hot-chocolate it was just so easy. Thank you very much for your work.

**Comment by michaelstaib** [comment]
The error filters can now also be injected so with the upcoming version they become a lot easier.

If you like our API please give us a star so that we get more visible.

**Comment by michaelstaib** [comment]
also we have a slack channel for support .... 

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q
