### ISSUE TITLE
Subscriptions not working with custom input types

### ISSUE THREAD

**Issue by afillebrown** [ChilliCream/hotchocolate#949]
**Description**
Subscription notifications are not being received by the client when the subscription's argument is a custom input type.

**To Reproduce**
- Modify the AspNetCore.StarWars example server `onReview` subscription to take a custom input type.
- Start the AspNetCore.StarWars example server.
- Send an `onReview` subscription request using the new input type in GraphQL Playground.
- Send a `createReview` mutation as normal.

See commit afillebrown@76b4f45 in my HotChocolate fork for a modified version of the AspNetCore.StarWars example server demonstrating the issue.

**Expected behavior**
Subscription notifications should be received by the client when the subscription's input type is a custom input type.

**Comment by michaelstaib** [comment]
Hi @afillebrown,

with custom input type you mean like an input object?

**Comment by michaelstaib** [comment]
Sorry did not see your demo :)

**Comment by michaelstaib** [comment]
I will look tomorrow into this ...

**Comment by afillebrown** [comment]
Were you able to reproduce the issue using the demo at afillebrown/hotchocolate@76b4f45?

Are we doing something wrong in the event class that's causing the resolver to fail?

**Comment by michaelstaib** [comment]
Sorry.... not yet ... it is on my stack of issues we will work on this week but I have not had the time to look into it. We are releasing V10 RC1 this week and we will look at your issue before we release it ....

**Comment by michaelstaib** [comment]
OK, found the issue.... will be fixed with the next preview build.

**Comment by michaelstaib** [comment]
The fix is now included in:
https://github.com/ChilliCream/hotchocolate/releases/tag/10.0.0-preview.50

**Comment by afillebrown** [comment]
Thank you!
