### ISSUE TITLE
CollectFields doesn't seem to work

### ISSUE THREAD

**Issue by jkporter** [ChilliCream/hotchocolate#992]
**Describe the bug**
Perhaps more a question than a bug but in previous correspondence it was mentioned that CollectFields could be used to properly walk the query tree. While passing in the Field.Type & FieldSelection.SelectionSet from the context works fine. Using the same values from a child IFieldSelection (with the same IResolverContext.CollectFields) does not. Not sure if this is a bug but unsure how to proceed.

**To Reproduce**
1. Create middleware method and  capture IMiddlewareContext of top level ObjectType
2. User IMiddlewareContext.CollectFields and get selected fields of type
3. Recursively attempt to get children of previous children using same IMiddlewareContext.CollectFields

**Expected behavior**
Recursively be able to walk the tree w/o error

**Lib:**
 - Version 10.0.0-preview.51

**Comment by michaelstaib** [comment]
Can you post some code?  We are using it internally so it works but I think there is something wring with how you walk the tree.

**Comment by jkporter** [comment]
I tried looking through the source code for examples but couldn't find any references to CollectFields to use an example. Anyways I put together this sample of what operation I was trying to do.

[CollectFieldsSample.zip](https://github.com/ChilliCream/hotchocolate/files/3489101/CollectFieldsSample.zip)

Thanks

**Comment by michaelstaib** [comment]
OK, your code is the issue... I will write you a little example.

The issue is the following you have to always provider the object type that the selection set will have. 

This means also with interfaces and unions that you have to check what you got and collect for each individual case.

In my sample I will only do it for the object type case and not for interfaces and union ... but I have helper functions that can provide you with the possible types in those cases.

**Comment by michaelstaib** [comment]
Sorry I misread your code ... it should be ok ... I will look into it

**Comment by michaelstaib** [comment]
OK, it is a bug ... the underlying api is working correctly... but the we are not correctly passing the selection set:

```csharp
public IReadOnlyCollection<FieldSelection> CollectFields(
            ObjectType typeContext, SelectionSetNode selectionSet) =>
            _executionContext.CollectFields(
                typeContext, FieldSelection.SelectionSet, Path);
```

I will write a couple more tests and fix it with the next build.

**Comment by jkporter** [comment]
Thanks again for the quick feedback and time investment.

**Comment by michaelstaib** [comment]
RC1 is out now.
